<?php 

 return [
     "home" => "ขายหมดแล้ว",
     "blogs" => "บล็อก",
     "helps" => "ช่วย",
     "current_location" => "รายการนี้",
     "dashboard" => "dashboard",
     "my_shops" => "ร้านค้าของฉัน",
     "wallet" => "wallet",
     "about" => "เกี่ยวกับ Selldone",
     "contact" => "contact us",
     "comments" => "comments",
     "likes" => "ชอบ",
     "power" => "เชียร์",
     "build_free_shop" => "สร้างร้านค้าของคุณได้ฟรี",
     "shop_name" => "shop name",
     "categories" => "categories",
     "sub_articles" => "More",
     "terms" => "เงื่อนไข",
     "colour" => "สี",
     "style" => "style",
     "volume" => "volume",
     "weight" => "weight",
     "pack" => "หีบห่อ",
     "type" => "type",
     "add_to_card" => "ใส่ในรถเข็น",
     "overview" => "Overview",
     "reviews" => "ความคิดเห็น",
     "spec" => "สเปคเต็มๆ",
     "you_may_also_like" => "คุณอาจชอบ",
     "about_us" => "เกี่ยวกับเรา",
     "contact_us" => "contact us",
     "cookie_privacy" => "Cookie &amp; privacy policy",
     "follow_us" => "ตามเรามา",
     "category" => "หมวดหมู่",
     "author" => "Written by ",
     "published_at" => "เผยแพร่ที่",
     "modified_at" => "แก้ไขแล้วที่",
     "price" => "ราคา",
     "discount" => "การลดราคา",
     "price_after_discount" => "ราคาหลังหักส่วนลด",
     "available" => "มีอยู่",
     "sold_out" => "ขายหมดแล้ว",
     "buy" => "ซื้อเลย",
     "login_shop" => "เข้าสู่ระบบร้านค้า",
     "posted_on" => "โพสต์เมื่อ :วันที่",
];