export default {
  "currency_default": "USD",
  "language_default": "en",
  "selldone": "продадено",
  "store": "магазин",
  "not_exist": "не съществува",
  "error": "грешка",
  "active": "активен",
  "inactive": "неактивен",
  "required_value": "задължителни стойности",
  "original_warranty": "гаранция за оригинален продукт",
  "return_warranty_days": "{days} дни право за връщане",
  "no_return_warranty": "без връщане",
  "reed_agree_terms": "Прочетох условията за ползване и политиката за поверителност и съм съгласен с тях.",
  "commons": {
    "Currency": "Валута",
    "COD": "COD",
    "State": "Състояние",
    "Price": "Цена",
    "order_price": "Сума на поръчката",
    "VAT": "ДДС",
    "Discount": "Отстъпка",
    "In_Stock": "В наличност",
    "Variants": "Варианти",
    "No_variants": "Без вариант",
    "all": "ВСИЧКО",
    "today": "днес",
    "yesterday": "вчера",
    "license": "разрешително",
    "home": "начало",
    "support": "поддръжка",
    "messages": "съобщения",
    "no_message": "няма съобщение",
    "empty": "празен",
    "phone": "телефон",
    "address": "адрес",
    "name": "име",
    "password": "парола",
    "email": "електронна поща",
    "mobile": "мобилен телефон",
    "login": "влизане",
    "register": "регистриране",
    "select_account": "изберете профил",
    "online": "на линия",
    "offline": "извън линия",
    "finish": "завършване",
    "finished": "готово",
    "preview": "преглед",
    "free": "безплатно",
    "free_completely": "напълно безплатно",
    "fee": "такса",
    "month": "месец",
    "months": "месеци",
    "faq": "често задавани въпроси",
    "question": "въпрос",
    "answer": "отговор",
    "create_date": "дата на създаване",
    "update_date": "дата на обновяване",
    "start_date": "начална дата",
    "end_date": "крайна дата",
    "social": "социални",
    "total": "обща сума",
    "orders": "поръчки",
    "sessions": "сесии",
    "product_views": "преглеждане на продукти",
    "add_to_carts": "добавяне в количките",
    "checkouts": "преглед на количката",
    "payments": "плащане",
    "organic_search": "органично търсене",
    "other": "друго",
    "landing_page": "целева страница",
    "discount_code": "код за отстъпка",
    "total_sell": "общо продажби",
    "details": "подробности",
    "currency": "валута",
    "amount": "количество",
    "published": "публикувано",
    "draft": "чернова",
    "save_changes": "запазване на промените",
    "source": "източник",
    "medium": "среден",
    "url": "URL адрес",
    "revenue": "приходи",
    "performance": "производителност",
    "term": "срок",
    "content": "съдържание",
    "session": "сесия",
    "product": "продукт",
    "add": "добавяне",
    "checkout": "купи",
    "payment": "плащане",
    "more_options": "повече възможности",
    "full_name": "три имена",
    "tel": "телефон",
    "about_me": "за мен",
    "request_checking": "заявка за проверка",
    "passport": "паспорт",
    "birthday": "рожден ден",
    "country": "държава",
    "city": "град",
    "gender": "пол",
    "offer": "оферта",
    "website": "уебсайт",
    "apply_for_all_products": "кандидатствайте за всички продукти",
    "fix_commission": "фиксирана комисионна",
    "percent_commission": "процентна комисионна",
    "fixed_discount": "фиксирана отстъпка",
    "discount_percentage": "процентна отстъпка",
    "discount_limit": "предел за отстъпка",
    "no_code": "няма код",
    "max_count": "максимален брой",
    "count_unit": "бр.",
    "used": "използван",
    "daily": "ежедневно",
    "monthly": "месечно",
    "yearly": "годишно",
    "state": "състояние",
    "disable": "изключване",
    "enable": "включване",
    "activation_code": "код за активиране",
    "quantity": "количество",
    "no_club": "няма клуб",
    "per_order": "на поръчка",
    "count": "бр.",
    "seconds": "Секунди",
    "auto": "Автоматичен",
    "title": "Заглавие",
    "message": "Съобщение",
    "width": "широчина",
    "length": "Дължина",
    "height": "Височина",
    "label": "Етикет",
    "click": "Щракнете върху",
    "bank": "банка",
    "default": "По подразбиране",
    "role": "Роля",
    "user": "потребител",
    "users": "потребители",
    "code": "код",
    "total_payment": "Общо плащане",
    "balance": "Баланс",
    "chance": "Шанс",
    "free_for_new_users": "Безплатно за нови потребители",
    "prize_amount": "Размер на наградата",
    "win": "Печеля",
    "gift_card": "Карта за подарък",
    "discount": "Отстъпка",
    "config": "Конфиг",
    "prize": "награда",
    "Prizes": "награди",
    "result": "Резултат",
    "price": "цена",
    "lottery": "лотария",
    "coupon": "Купон",
    "customer_club": "Клуб на клиентите",
    "shipping": "Доставка",
    "sum": "Сума",
    "not_paid": "Неплатен",
    "category": "Категория",
    "done": "готово",
    "email_from": "От",
    "subject": "Предмет",
    "schedule": "График",
    "files_list": "Списък с файлове",
    "file_max_size": "Максимален размер на файла",
    "value": "Стойност",
    "help": "Помощ",
    "shipping_tax": "такса за превоз",
    "net_price": "нетна цена",
    "tax": "данък",
    "tax_included": "Включено в цената",
    "limit": "Лимит",
    "min_purchase": "Минимална покупка",
    "eligible_for": "Отговаря на условията за",
    "only_for_first_buy": "Само за първа покупка",
    "one_time_use": "Може да се използва еднократно",
    "period_of_qualify": "Периодично ограничение на употреба",
    "no_constraint": "Няма ограничение",
    "timespan": "Времеви период",
    "days": "ден(и)",
    "weight": "Тегло",
    "distance": "Разстояние",
    "last_status": "Последно състояние",
    "issued_at": "Издадено на",
    "order": "Поръчка",
    "order_detail": "Подробности за поръчката",
    "percent": "Процент",
    "applied_count": "Приложен брой",
    "campaign": "кампания",
    "os": "Операционна система",
    "browser": "Браузър",
    "device": "устройство",
    "device_ip": "IP адрес на устройството",
    "location": "Местоположение",
    "user_agent": "Потребителски агент",
    "affiliate": "Партньор",
    "timeline": "Времева линия",
    "add_note": "Добавяне на бележка",
    "record": "Запис",
    "unlimited": "Неограничен",
    "show_coupons": "Показване на купони",
    "hide_coupons": "Скриване на купони",
    "service_area": "Зона на обслужване",
    "apps": "Приложения",
    "plugins": "Разширения",
    "bots": "ботове",
    "categories": "Категории",
    "products": "продукти",
    "business": "Бизнес",
    "personal": "физическо лице",
    "size": "размер",
    "holiday": "Празник",
    "sod": "Плащане при доставка",
    "cod": "Наложен платеж",
    "free_shipping": "Безплатна доставка",
    "hours": "Часа",
    "send_date": "Дата на изпращане",
    "deliver_date": "Дата на доставка",
    "return_date": "Дата на връщане",
    "pending": "В очакване",
    "delivered": "Доставено",
    "returned": "Върнат",
    "canceled": "Отменен",
    "shipping_cost": "Цена за доставка",
    "action": "Действие",
    "cancel_date": "Дата на анулиране",
    "deliver_in_process": "Поръчката е изпратена",
    "kind": "Тип",
    "detail": "Подробности",
    "map": "Карта",
    "actions": "Действия",
    "navigation": "Навигация",
    "navigation_app": "Приложение",
    "payment_date": "Дата за плащане",
    "duration": "Продължителност",
    "bill": "Фактуриране",
    "delivery_persons": "Куриери",
    "delivery_services": "Услуги за доставка",
    "live_view": "На живо",
    "cart": "Количка",
    "priority": "Приоритет",
    "sufficient_credit": "Достатъчен кредит",
    "max_package_size": "Максимален размер на опаковката",
    "delay": "Закъснение",
    "credit": "Кредит",
    "livemode": "На живо",
    "paused": "На пауза",
    "debug": "Отстраняване на грешки",
    "token": "Токен",
    "status": "Състояние",
    "courier": "куриер",
    "track": "проследяване",
    "track_order": "Проследяване на поръчката",
    "cost": "Разходи",
    "receipt": "Разписка",
    "origin": "Произход",
    "destination": "Местоположение",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "няма достатъчно наличност",
    "sub_total": "Междинна сума",
    "customer": "Клиент",
    "delivery": "Доставка",
    "online_orders": "Онлайн поръчки",
    "pos_orders": "POS поръчки",
    "chips": "Чипс",
    "subscribed": "Абонирах се",
    "unsubscribed": "отписан",
    "last_login": "Последно влизане",
    "join_at": "Дата на присъединяване",
    "club": "Клуб",
    "buyer": "Купувач",
    "seller": "Продавач",
    "or": "Или",
    "type": "Тип",
    "condition": "състояние",
    "brand": "Бранд",
    "attempt": "Опит",
    "error": "Грешка",
    "success": "успех",
    "fail": "неуспех",
    "inventory": "Складова наличност",
    "link": "Връзка",
    "visits": "Посещения",
    "transactions": "Транзакции",
    "vat": "ддс",
    "pos_vat": "POS ДДС",
    "sort_by": "Подреждане по",
    "from": "От",
    "from_lead_time": "В рамките на следващите {hours} часа",
    "no_credit_card_info": "Няма информация за картата!",
    "active": "Активен",
    "not_active": "Неактивен",
    "referrals": "Реферали",
    "dashboard": "Табло",
    "more": "| Повече ▼",
    "inactive": "неактивен",
    "developer": "Разработчик",
    "setting": "Настройка",
    "membership_conditions": "Условия за членство",
    "customers": "Клиенти",
    "created_at": "Дата на създаване",
    "updated_at": "Дата на обновяване",
    "register_at": "Дата на регистрация",
    "old": "Стар",
    "new": "Нов",
    "start": "Начало",
    "end": "Край",
    "pos": "POS",
    "out_of_stock": "Няма наличност",
    "fake": "Фалшив",
    "low_inventory_warning": "Внимание, ниска наличност!",
    "webhook": "Webhook",
    "notification": "уведомление",
    "sms": "SMS",
    "online_payment_link": "Връзка за онлайн плащане",
    "waiting_load_data": "Изчаква се зареждане на данни",
    "views": "преглеждания",
    "sales": "продажби",
    "total_views": "Общо преглеждания",
    "total_sales": "Общо продажби",
    "from_previous_n_days": "От последните {days} дни",
    "drop_shipping": "Дропшипинг",
    "commission": "комисия",
    "shipping_area": "Зона за доставка",
    "main_seller": "Основен продавач",
    "domain": "домейн",
    "contact": "Информация за контакт",
    "wallet": "портфейл",
    "reseller": "Препродавач",
    "tracking_code": "Проследяващ код",
    "tracking_url": "URL за проследяване",
    "fulfillments": "Изпълнения",
    "reject": "Отхвърляне",
    "reserved": "Запазено",
    "score": "Резултат",
    "customer_price": "Клиентска цена",
    "options": "Настройки",
    "show_details": "Показване на подробности",
    "no_data": "Няма данни",
    "waiting": "Изчакване",
    "waiting_connecting_payment": "В очакване на услугата за плащане",
    "creating_secure_payment": "Създаване на сигурно плащане.",
    "officer": "офицер",
    "ticket": "Билет",
    "ticket_url": "URL адрес на билета",
    "closed_at": "Затворен в",
    "close_ticket": "Затваряне на билета",
    "reopen_ticket": "Повторно отваряне на билета",
    "require": "Изискване*",
    "search": "Търсене...",
    "language": "език",
    "tasks": "Задачи",
    "permissions": "Разрешения",
    "finish_date": "Крайна дата",
    "complete_date": "Дата на завършване",
    "settle_date": "Дата на уреждане",
    "cost_span": "Ценови диапазон",
    "industry": "индустрия",
    "rating": "Рейтинги",
    "rates": "оценки",
    "seen_at": "Видяно",
    "completed": "Завършено",
    "you": "Вие",
    "shop": "Пазарувайте",
    "store": "магазин",
    "granted": "Разрешено",
    "deny": "отказ",
    "request": "Заявка",
    "expert": "Експерт",
    "response": "Отговор",
    "requests": "Заявки",
    "experts": "Експерти",
    "responses": "Отговори",
    "negotiations": "Преговори",
    "all_chats": "Всички чатове",
    "chats": "чатове",
    "tags": "Етикети",
    "description": "Описание",
    "rates_count": "Брой оценки",
    "rate": "оценяване",
    "comment": "коментиране",
    "chat": "Чат",
    "install": "Инсталирай",
    "edited": "Редактирано",
    "undo": "Отмяна",
    "redo": "Повторете",
    "male": "Мъжки пол",
    "female": "Женски пол",
    "calculator": "Калкулатор",
    "catalog": "Каталог",
    "max_height": "Максимална височина",
    "images_compare": "Сравнение на изображения",
    "canvas": "Платно",
    "table_of_contents": "Съдържание",
    "comments": "Коментари",
    "badge_codes": "Код на значките",
    "need_more": "Имате нужда от повече?",
    "invite_glow_caption": "Вземете 14,9$ за всеки приятел!",
    "register_free": "100% безплатна регистрация",
    "gift": "Подарък",
    "google": "Google",
    "facebook": "Facebook",
    "instagram": "Instagram",
    "instashop": "Instashop",
    "show": "показване",
    "hide": "скриване",
    "waiting_review": "В очакване на преглед",
    "not_selected": "Не е избрано",
    "time": "Време",
    "final_price": "Крайна цена",
    "starting_price": "Начална цена",
    "day": "ден",
    "paid": "Платено",
    "service_bill": "Плащане на фактура",
    "avocado": "авокадо",
    "delivery_price": "Цена за доставка",
    "select_address": "Изберете адрес",
    "image": "Изображение",
    "view": "Преглед",
    "sell": "Разпродажба",
    "hyper": "Хипер",
    "cart_list": "Количка",
    "barcode_scanner": "Баркод скенер",
    "scan_qr_code": "Сканирайте QR код",
    "new_carts": "Нови колички",
    "pays": "плащания",
    "annually": "Годишно",
    "sells": "продажби",
    "articles": "статии",
    "jobs": "Работни места",
    "job": "работа",
    "blog": "Блог",
    "deleted_at": "Изтриване",
    "capacity": "Капацитет",
    "download_at": "Дата на последно изтегляне",
    "downloads": "Изтегляния",
    "usage": "Използване",
    "select_upload_file": "Изберете или пуснете файл",
    "download_link": "Връзка за изтегляне",
    "uploading": "Качване..",
    "files": "Файлове",
    "star": "звезда",
    "speed": "Скорост",
    "feedback": "Обратна връзка",
    "new_messages": "Нови съобщения",
    "file": "Файл",
    "attachment": "Прикачен файл",
    "gallery": "Галерия",
    "sync": "Синхронизиране",
    "diff_time": "Времева разлика",
    "network": "мрежа",
    "account": "Сметка",
    "configuration": "Конфигурация",
    "blockchain": "Блокчейн",
    "blog_link": "Връзка към блога",
    "community": "общност",
    "critical_zone": "Критична зона",
    "statistics": "Статистика",
    "access": "Достъп",
    "seo": "SEO",
    "followers": "последователи",
    "followings": "последвания",
    "private": "Визуализация",
    "soon": "Скоро",
    "features": "Характеристика",
    "bot": "бот",
    "sample": "Проба",
    "how_it_work": "Как работи?",
    "page": "Страница",
    "congratulations": "Честито",
    "recommend": "Препоръчвам",
    "recommended": "Препоръчва се",
    "recoms": "Препоръки",
    "likes": "Харесвания",
    "clicks": "Кликвания",
    "platform": "Платформа",
    "cms": "CMS",
    "cash": "Пари в брой",
    "dir_payment": "банков превод",
    "auto_complete": "Автоматично завършване",
    "compare": "Сравняване",
    "infinite": "Безкраен",
    "tips": "Съвети",
    "technical": "Технически",
    "finance": "Финанси",
    "your_phone_input": "Въведете телефонен номер",
    "income": "доходи",
    "change": "Промяна",
    "new_users": "Нови потребители",
    "success_orders": "Успешни поръчки",
    "direct": "Директен",
    "last_activity": "Последна активност",
    "landing": "Кацане",
    "now": "Сега",
    "accept_agreement": "Прочетох и приех условията.",
    "report": "доклад",
    "tablet": "таблет",
    "pc": "компютър",
    "acquisition_channel": "Канал за придобиване",
    "to": "До",
    "info": "Информация",
    "general": "Общ",
    "upload": "Качване",
    "general_config": "Обща конфигурация",
    "limits_config": "Ограничения",
    "design_config": "Дизайн и стил",
    "duration_config": "Ограничение на продължителността",
    "constraints_config": "Граници на допустимост",
    "clubs_config": "Предлага се в клубове",
    "additional_config": "Допълнителни конфигурации",
    "import": "Импортиране",
    "ribbon": "Лента",
    "countries": "Държави",
    "edit": "редактиране",
    "delete": "Изтрий",
    "analytics": "Анализ",
    "rules": "правила",
    "unset": "Не е зададено",
    "carts": "Колички",
    "optional": "По избор",
    "design": "Дизайн",
    "filter": "Филтър",
    "send": "Изпратете",
    "approved": "Одобрен",
    "unit": "Мерна единица",
    "profile": "профил",
    "shipping_rates": "Цени за доставка",
    "package": "Пакет",
    "overview": "Общ преглед",
    "live": "На живо",
    "never": "никога",
    "always": "винаги",
    "mandatory": "Задължителен",
    "expire_at": "Срок на годност",
    "position": "позиция",
    "channel": "канал",
    "age": "възраст",
    "charge": "Зареждане",
    "giftcard": "Карта за подарък",
    "acquisition": "Придобиване",
    "conversion": "Преобразуване",
    "total_payments": "Общо плащания",
    "community_ask": "Попитайте в общността",
    "children": "деца",
    "export": "Експортиране",
    "list": "Списък",
    "hierarchy": "Йерархия",
    "images": "Изображения",
    "demo": "Демонстрация",
    "author": "Автор",
    "designer": "Дизайнер",
    "max": "Максимум",
    "accepted": "Прието",
    "reply": "Отговор",
    "reviewed": "Прегледано",
    "restored": "Възстановено",
    "merchant": "търговец",
    "per_product": "на продукт",
    "journey": "Пътуване",
    "after": "След"
  },
  "dialogs": {
    "delete": {
      "title": "Изтриване",
      "message": "Сигурни ли сте, че ще изтриете този елемент?",
      "action": "Да, изтрийте сега"
    }
  },
  "actions": {
    "add_to_cart": "Добавяне в кошницата",
    "cancel": "отмяна",
    "update": "обновяване",
    "add": "добавяне",
    "delete": "изтриване",
    "new": "Нов",
    "save_continue": "Запазване и продължаване",
    "save": "Запазване",
    "save_changes": "Запазване на промените",
    "change": "Промяна",
    "continue": "продължаване",
    "close": "затваряне",
    "finish": "готово",
    "poll": "Анкета",
    "view": "Преглед",
    "edit": "редактиране",
    "next": "Следващ",
    "previous": "Предишен",
    "create": "Създаване",
    "set": "комплект",
    "find": "намиране",
    "accept": "Приемане",
    "reject": "Отхвърляне",
    "back": "обратно",
    "pay": "Плащане",
    "pay_now": "Плащане сега",
    "print": "Печат",
    "return": "Връщане",
    "publish": "Публикуване",
    "confirm": "Потвърдаване",
    "copy": "Копиране",
    "submit": "Изпращане",
    "send": "Изпращане",
    "yes": "да",
    "no": "не",
    "meh": "Хмм",
    "clear": "Ясно",
    "dismiss": "Отхвърляне",
    "search": "Търсене",
    "deselect_all": "премахване на избора",
    "select_all": "Избери всичко",
    "refresh": "обновяване",
    "verify": "потвърждаване",
    "play": "игра",
    "open": "отваряне",
    "calculate": "изчисляване",
    "quick_buy": "Бърза покупка",
    "click_here": "Натисни тук",
    "schedule": "График",
    "send_now": "изпращане сега",
    "download": "изтегляне",
    "reset_default": "връщане на първоначалните настройки",
    "reset": "нулиране",
    "check": "проверка",
    "cod_payment": "наложен платеж",
    "dir_payment": "паричен превод",
    "online_payment": "онлайн плащане",
    "checkout": "купи",
    "show_all": "покажи всички",
    "login": "влизане",
    "logout": "излизане от профила",
    "more": "повече ▼..",
    "collapse": "свиване",
    "apply_change": "прилагане на промените",
    "apply": "прилагане",
    "add_giftcard": "добавете карта за подарък",
    "charge": "зареждане",
    "send_invites": "изпращане на покани",
    "past": "предишен",
    "restore": "възстановявяне",
    "cut": "изрязване",
    "get_sms_code": "вземете код за удостоверяване",
    "register_no_mail": "продължете без електронна поща",
    "no_mail_register_message": "Нямате електронна поща или сте забравили паролата си?",
    "reset_by_mail": "възстановяване на парола по електронна поща",
    "reset_by_sms": "възстановяване на парола чрез sms",
    "cash_payment": "Плащане в брой",
    "show_chart": "показване на диаграма",
    "open_app": "Отворете приложението",
    "login_now": "влизане",
    "watch_video": "гледане на видео",
    "check_now": "преглед",
    "remove_image": "Премахване на изображението",
    "view_website": "Отваряне на връзка",
    "explore": "Разгледайте {name}",
    "go": "Отивам",
    "read_more": "Прочетете още",
    "start_now": "Започнете сега - безплатно е",
    "view_live": "Вижте на живо",
    "resend_code": "Код за препращане",
    "invite": "покана",
    "add_more": "Добавяне на още",
    "install_now": "Инсталиране сега",
    "uninstall": "Деинсталиране",
    "show_preview": "Показване на изглед",
    "hide_preview": "Скриване на изглед",
    "download_now": "Сваляне сега",
    "auto_fill": "Автоматично попълване",
    "track": "проследяване",
    "change_state": "Промяна на състоянието",
    "done": "готово",
    "reply": "Отговор"
  },
  "instance_message_title": "Изпратете незабавно съобщение",
  "instance_message": "Здравейте, {name}, казвам се {author} от {company}.",
  "errors": {
    "419": "Не сте били активни от дълго време, моля <b>⟳ ОСНОВАТЕ СТРАНИЦАТА</b> от съображения за сигурност.",
    "gateway_blockchain_sync_error": "Системата не се синхронизира с блокчейна. Няма да е възможно да се създаде нова транзакция, докато не бъдат завършени синхронизациите на нашите сървъри. Ние решаваме проблема.",
    "gateway_network_error": "Услугата за шлюз за плащане срещна проблем с комуникацията."
  },
  "receiver_info": {
    "map": {
      "title": "Адрес за доставка",
      "confirm": "Задайте местоположение",
      "address_type": "адрес",
      "receptor_type": "получател"
    },
    "receiver_address": "Изберете адрес за доставка",
    "address": "адрес",
    "postcode": "Пощенски код",
    "enter_value": "Попълнете тук",
    "address_note": "Забележка",
    "tel": "Номер за връзка"
  },
  "weight": {
    "g": "гр",
    "oz": "oz",
    "lb": "lb",
    "kg": "кг"
  },
  "mass_unit_name": {
    "g": "грам",
    "oz": "oz",
    "lb": "lb",
    "kg": "килограм"
  },
  "length": {
    "cm": "см",
    "in": "в",
    "ft": "фута",
    "mm": "мм",
    "m": "м",
    "yd": "ярд"
  },
   "size_unit_name": {
    "cm": "сантиметър",
    "in": "инч",
    "ft": "фута",
    "mm": "милиметър",
    "m": "метър",
    "yd": "ярд"
  },
  "distance": {
    "m": "м",
    "km": "км"
  },
  "time": {
    "days": "дни",
    "hours": "часа",
    "minutes": "минути",
    "seconds": "секунди"
  },
    "units": [
    "мерна единица",
    "вещ",
    "всеки",
    "комплект",
    "парче",
    "килограм",
    "грам",
    "милиграм",
    "метър",
    "милиметър",
    "квадратен метър",
    "квадратни фута",
    "кубичен метър",
    "литър",
    "милилитър",
    "крака",
    "галони",
    "инча",
    "унции",
    "паунда",
    "кварти",
    "ярда",
    "стая",
    "продукт(и)"
  ],
  "region_types": {
    "State": "област",
    "Territory": "територия",
    "Province": "провинция"
  },
  "transaction_status": {
    "RequireAction": "изисква се действие",
    "Processing": "обработка",
    "Canceled": "отменен",
    "Succeeded": "успешно"
  },
  "placeholders": {
    "name": "иван петров",
    "email": "your-mail@mail.com",
    "phone": "+1 000 0000",
    "language": "изберете език..",
    "friend_email": "електронна поща на Ваш приятел...",
    "friend_name": "името на Ваш приятел",
    "select_date": "изберете дата..."
  },

  "notification": {
    "confirm": "Потвърдете",
    "confirm_message": "Промените са запазени успешно.",
    "error": "Грешка",
    "message": "Съобщение",
    "caution": "Внимание",
    "warning": "Внимание",
    "award": "поздравления",
    "error_message": "За съжаление възникна грешка.",
    "congratulation": "поздравления",
    "coming_soon": "Скоро",
    "on_fetching_data": "Получаване на информация ..",
    "new_pwa_version": "Нова версия е налична сега. Искате ли да актуализирате приложението?",
    "over_license_limit": "Над ограничението на лиценза",
    "update_license": "Актуализирайте лиценза си",
    "required": "Задължително",
    "invalid_email": "Грешен имейл",
    "invalid_domain": "Невалиден домейн",
    "invalid_min_length": "Минималната дължина трябва да бъде {length}",
    "invalid_min_array_length": "Изберете поне {length} елементи",
    "invalid_max_chars": "Макс. {maxCount} знака",
    "invalid_url": "невалиден адрес"
  },
  "colors": {
    "#D32F2F": "червен",
    "#C2185B": "розово",
    "#7B1FA2": "лилаво",
    "#512DA8": "тъмно лилаво",
    "#303F9F": "индиго синьо",
    "#1976D2": "син",
    "#0288D1": "светло синьо",
    "#0097A7": "тюркоазено синьо",
    "#00796B": "гъши зелено",
    "#388E3C": "зелено",
    "#689F38": "светло зелено",
    "#AFB42B": "лимузина",
    "#FBC02D": "жълт",
    "#FFA000": "амбър",
    "#F57C00": "оранжево",
    "#E64A19": "блестящ портокал",
    "#5D4037": "кафяв",
    "#616161": "сив",
    "#455A64": "сиво синьо",
    "#FFD700": "златен",
    "#C0C0C0": "сребро",
    "#b76e79": "златна роза",
    "#383838": "матово черно",
    "#FFFFFF": "бяла",
    "#FFF": "бяла",
    "#000000": "черен",
    "#000": "черен"
  },
  "address_info": {
   "name": "име",
    "tel": "телефон",
    "email": "електронна поща",
    "country": "държава",
    "city": "град",
    "state": "област",
    "address": "адрес",
    "building_number": "номер на сградата",
    "building_unit": "етаж",
    "postcode": "пощенски код",
    "note": "забележка"
  },
  "product_types": {
    "physical": "физически",
    "physical_description": "Физически продукти като: мобилни телефони, книги, електронни компоненти.",
    "virtual": "Виртуален",
    "virtual_description": "Удобни за интернет продукти като: карта за презареждане, хотелска резервация, презареждане на игри.",
    "file": "Файл",
    "file_description": "Всички разрешени файлове като онлайн видео курсове, документи за изтегляне.",
    "service": "Обслужване",
    "service_description": "Услуги като: ремонт, транспорт, обучение."
  },
  "license": {
    "free": "Безплатно",
    "startup": "Започвам",
    "company": "Компания",
    "enterprise": "Предприятие"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "Томан",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW"
  },
  "variants": {
    "color": "цвят",
    "volume": "размер",
    "count_in_pack": "бройки в опаковка",
    "weight": "тегло",
    "type": "материал",
    "style": "стил"

  },
  "delivery_state": {
    "check_queue": "в очакване на преглед",
    "order_confirm": "потвърждение на поръчката",
    "preparing_order": "приготвяне",
    "sent_order": "изпращане",
    "to_customer": "доставянео"
  },
  "status": {
    "unpaid": "неплатено",
    "paid": "платено",
    "canceled": "отменено",
    "completed": "завършено",
    "reserved": "запазено",
    "COD": "cod",
    "sold": "продадено",
    "open": "отвори",
    "cancel": "отмяна",
    "active": "активен",
    "inactive": "неактивен",
    "debug": "отстраняване на грешки",
    "live": "на живо",
    "test": "тест",
    "connected": "свързан",
    "disconnected": "прекъснат",
    "accept": "приемане",
    "reject": "отхвърляне",
    "pending": "в очакване",
    "rejected": "отхвърлено",
    "accepted": "прието"
  },
  "dimensions": {
    "cm": "см",
    "km": "км",
    "kg": "кг"
  },
  "transportation_type": {
    "motorbike": "Мотор",
    "motorbike_description": "Средно тегло в рамките на няколко километра.",
    "cargo_small": "Малък товар",
    "cargo_small_description": "Многокилометров лек товар.",
    "cargo": "Товарни",
    "cargo_description": "Средно тегло в рамките на няколко километра.",
    "truck": "Камион",
    "truck_description": "Насипни или тежки товари в страната.",
    "fast_post": "Доствка до офис",
    "fast_post_description": "Изпращане до офис на Спиди.",
    "post": "Доставка до адрес",
    "post_description": "Изпращане до ваш адрес.",
    "airplane": "Въздушна поща",
    "airplane_description": "Вътрешни и чуждестранни леки и средни товари.",
    "bicycle": "Чисто изпращане",
    "bicycle_description": "Лек товар, в рамките на няколкостотин ярда от немоторни превозни средства.",
    "global": "Глобален транспорт",
    "global_description": "Доставка в чужбина по въздух, море или суша.",
    "pickup": "Вдигни",
    "pickup_description": "Клиентите вземат артикулите във вашия физически магазин или склад."
  },
  "article": {
    "login_to_see_error": "Влезте за достъп до статията",
    "create_new_action": "Създаване на ново съдържание",
    "menu_title": "Меню",
    "menu": {
      "edit": "Режим на редактиране",
      "view_mode": "Режим на преглед",
      "delete": "Изтриване на статия"
    },
    "schedule_action": "Искате ли да насрочите публикуване?",
    "schedule_title": "Насрочете автоматично публикуване",
    "edit_mode": "редактиране",
    "public_view_mode": "Обществен поглед",
    "publish_at": "Публикувайте в",
    "published": "Публикувано",
    "draft": "Чернова",
    "saving": "Запазване",
    "save_and_publish_action": "Запазване и публикуване",
    "save_draft_action": "Чернова",
    "private": "Частен",
    "public": "Обществени",
    "category_input": "Категория",
    "category_input_message": "Изберете категория статия",
    "parent_input": "Родителска категория",
    "parent_input_message": "Изберете съдържание на баща",
    "schedule_input": "График",
    "schedule_input_placeholder": "Ако искате историята да бъде публикувана в определено време.",
    "schedule_view_action": "Вижте графика за публикуване",
    "author_title": "Написано от",
    "read_time": "Време за учене",
    "read_time_unit": "Минути",
    "claps_action": "Пляскане",
    "claps": "Пляскане",
    "likes": "като",
    "about_author": "За автора",
    "updated_at": "Актуализиран",
    "wrote_at": "Написано на",
    "now": "Сега",
    "follow_action": "последвам",
    "followed": "Следва",
    "report_and_delete_action": "Докладвайте и изтрийте тази статия",
    "report_action": "Съобщете за злоупотреба",
    "you_reported_this_article": "Тази статия вече има сигнал за злоупотреба.",
    "add_to_publication_action": "Добавяне към публикацията",
    "author_socials": "Автор в социалните мрежи",
    "share": "Дял",
    "report_dialog": {
      "report_and_delete_title": "Подайте сигнал за злоупотреба и премахнете съдържание",
      "report_title": "Подайте сигнал за това съдържание като злоупотребяващо",
      "message": "Каква е причината за изпращане на това съдържание? Изберете една от следните опции.",
      "accept_and_delete_action": "Потвърдете и изтрийте съдържание"
    },
    "schedule_dialog": {
      "title": "График за пускане на съдържание",
      "publish_at": "Публикувайте в",
      "last_edit": "Последна редакция",
      "view_action": "Вижте статията"
    },
    "notifications": {
      "update_success_title": "Изпратете информация",
      "update_success": "Статията е актуализирана успешно.",
      "update_error": "Въведената информация не е валидна.",
      "delete_error": "Не можете да изтриете тази статия!",
      "report_and_delete_success_title": "Докладвай и изтрий",
      "report_and_delete_success_message": "Статията е изтрита успешно.",
      "report_success_title": "Докладвайте статия",
      "report_success_message": "Вашият доклад за тази статия е публикуван."
    },
    "alert": {
      "delete_article": {
        "title": "Изтриване на статия",
        "message": "Наистина ли искате да изтриете тази статия за постоянно?",
        "action": "Изтрий"
      }
    },
    "edit_window": {
      "title": "Изберете Текст на изображението и Резюме",
      "digest": "Резюме"
    },
    "editor": {
      "title_placeholder": "Заглавие..",
      "body_placeholder": "Пишете страхотно съдържание..",
      "accept_file_types_error": "Този файлов формат е неприемлив:",
      "max_file_size_error": "Този файл е твърде голям:",
      "notifications": {
        "image_uploaded_success": "Изображението е запазено успешно",
        "image_uploaded_failed": "Грешка при зареждане на изображението."
      },
      "embed_placeholder": "Въведете кода на iframe, Facebook, Youtube или друг URL и натиснете enter.",
      "embed_caption_placeholder": "Въведете заглавие (по избор)",
      "images_caption_placeholder": "Въведете заглавие за това изображение .."
    }
  },
  "article_report": {
    "inappropriate": "Съдържанието на тази статия е неподходящо.",
    "fake": "Това е фалшиво и измамно.",
    "spam": "Този елемент е изпратен със спам и копиран.",
    "scam": "Може да се очаква това да причини злонамерен софтуер, вируси или срив на системата.",
    "hacked": "Изглежда, че този сайт е бил хакнат.",
    "offensive": "Езиковото съдържание и речник са неетични и неуважителни.",
    "violent": "Мисля, че това съдържание съдържа порнография и е в нарушение на законите.",
    "harassment": "Мисля, че това е расистко.",
    "hate": "Мисля, че става дума за насърчаване на насилието.",
    "infringe": "Това нарушава правата ми."
  },
  "comments": {
    "new_action": "Кликнете, за да оставите коментар..",
    "title": "Коментари",
    "body_placeholder": "Вашият коментар или съобщение",
    "send_action": "Изпратете коментар",
    "body_is_empty_error": "Коментарът е празен!",
    "comments": "Коментари",
    "no_comments": "Напишете първия коментар...",
    "load_more_action": "Вземете още коментари..",
    "cant_send_comment": "Не можете да добавите нова публикация.",
    "cant_remove_this_comment": "Не можете да изтриете този коментар!",
    "product_buyer": "Купувач",
    "delete_alert": {
      "title": "Изтриване на коментар",
      "message": "Искате ли да изтриете този коментар?",
      "action": "Изтрий"
    },
    "notifications": {
      "delete_success": "Вашият коментар е изтрит успешно."
    },
    "first_send": "Първи пост",
    "comment_at": "На",
    "edit_comment": "Редактиране на коментар"
  },
  "customer_club": {
    "bronze": "бронз",
    "silver": "сребро",
    "gold": "злато",
    "platinum": "платина",
    "diamond": "диамант"
  },
  "application_categories": {
    "tracking": "Проверка на поведението на потребителя",
    "payment": "Плащане",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "Транспорт",
    "automation": "Автоматизация",
    "inventory": "Складиране",
    "accounting": "Счетоводство",
    "marketing": "Маркетинг",
    "advertising": "Реклама",
    "staff": "Персонал",
    "incentive": "Стимули",
    "shop": "Пазарувайте"
  },
  "social_network": {
    "instagram": "Instagram",
    "telegram": "Телеграма",
    "googleplay": "Google Play",
    "appstore": "AppStore",
    "twitter": "Twitter",
    "linkedin": "Linkedin",
    "medium": "Среден",
    "selldone": "Продадено",
    "facebook": "Facebook",
    "pinterest": "Pinterest",
    "whatsapp": "WhatsApp",
    "skype": "Skype",
    "facebook_messenger": "Facebook Messenger"
  },
  "form_builder": {
    "add_item_action": "Добавяне на нов елемент",
    "title_input": "Заглавие",
    "name_input": "Име на променлива",
    "value_input": "Стойности",
    "value_input_message": "Списък с потребителски опции",
    "default": "Стойност по подразбиране",
    "types": {
      "simple": "прост",
      "selective": "Селективни",
      "switch": "Превключете"
    }
  },
  "virtual_order_info_summery": {
    "title": "Име на продукта",
    "reserved_at": "Дата на Регистрация",
    "total_price": "Обща сума",
    "discount": "Отстъпка",
    "final_price": "Крайна сума",
    "payment_status": "Статус на плащането",
    "payment_status_waiting": "В очакване на плащане",
    "payment_status_paid": "Платено",
    "buyer": "Купувач"
  },
  "virtual_item_info": {
    "title": "Виртуален елемент",
    "outputs": {
      "title": "Изходна информация",
      "sub_title": "Поверителна информация за този артикул",
      "message": "Тази информация ще бъде показана на потребителя след закупуване на продукта."
    },
    "inputs": {
      "title": "Изисква се информация",
      "sub_title": "Изисква се информация за купувача",
      "message": "Купувачът трябва да въведе исканата информация във формуляра"
    },
    "notifications": {
      "inputs_set_success": "Формулярът за информация е регистриран успешно.",
      "confirm_by_admin_success": "Завършването на поръчката е потвърдено.",
      "confirm_by_buyer_success": "Завършването на поръчката е потвърдено."
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "Тази поръчка не може да бъде приета от плащането на COD.",
    "payment_returned": "Плащането от клиента се връща.",
    "payment_fraud": "Плащането е идентифицирано като измама.",
    "location_out_of_service": "Местоположението на клиента е извън обслужване.",
    "user_not_responding": "Клиентът не отговаряше на обажданията.",
    "shop_owner_fault": "Възникна грешка от служителите на магазина при попълването на информацията.",
    "lack_of_inventory": "Не е налично.",
    "legal_restriction": "Не може да се направи поръчка поради законови ограничения.",
    "pricing_fault": "Ценова грешка от продавача.",
    "system_fault": "Системна грешка."
  },
  "basket_order_info_summery": {
    "receiver": "получател",
    "phone": "телефон",
    "reserved_date": "дата на закупуване",
    "total_price": "обща сума",
    "discount": "отстъпка",
    "final_price": "крайна сума",
    "address": "адрес за доставка",
    "payment_status": "статус на плащането"
  },
  "basket_status": {
    "open": "отворяне",
    "reserved": "запазване",
    "paid": "платено",
    "canceled": "отменено",
    "cod": "плащане при доставка",
    "receipt_added": "разписката е добавена",
    "payment_processing": "обработка на плащане"
  },
  "basket_delivery_state": {
    "rejected": "отхвърлено",
    "reject_reason_not_found": "причината е неизвестна.",
    "step_1": "преглед",
    "step_2": "потвърждение",
    "step_3": "подготовка",
    "step_4": "изпращане",
    "step_5": "доставка"
  },
  "basket_return_request_view": {
        "title": "заявка за връщане",
    "delivery_date": "дата на доставка",
    "return_date": "дата на заявка",
    "items_count": "върнатите продукти",
    "items_count_unit": "продукт(и)",
    "reason": "причина",
    "description": "описание",
    "status": "състояние",
    "download_image": "изтеглете изображение",
    "download_film": "изтегляне на видео",
    "download_voice": "изтегляне на аудио",
    "accept_by_admin_action": "приемете заявката",
    "reject_by_admin_action": "отхвърляне на заявка",
    "message_for_admin": "Съгласно споразумението, което сте приели с помощта на Selldone, трябва да се свържете с купувача и да го/я информирате за процеса на връщане на неговата/нейната поръчка. Това трябва да стане, ако искането бъде прието или отхвърлено и е получено пълното съгласие на купувача.",
    "notifications": {
    "update_status_success": "Състоянието на заявката е обновено."
    }
  },
  "basket_list": {
    "return_count": "Връщане: {count} номер",
    "table": {
      "row": "Ред",
      "image": "Изображение",
      "product_name": "Продукт",
      "variant": "Вариант",
      "warranty": "Гаранции",
      "count": "бр.",
      "price": "цена"
    }
  },
  "return_request_list": {
    "count": "Номер за справка",
    "return_warranty": "Гарантирано връщане на парите",
    "return_warranty_unit": "ден(и)",
    "table": {
      "code": "Код за поръчка",
      "product": "Продукт",
      "delivery_at": "Дата на получаване",
      "state": "Състояние",
      "reason": "Причина",
      "return_warranty_period": "Гаранционен срок"
    }
  },
  "data_toolbar": {
    "search": "Търсене",
    "sort_by": "Подреждане по",
    "count_item": "Показване на {item} продукти"
  },
  "sort": {
    "created_at": "дата на създаване",
    "updated_at": "дата на обновяване",
    "title": "заглавие",
    "description": "описание",
    "like": "харесване",
    "power": "пляскане",
    "product_type": "вид продукт",
    "discount": "отстъпка",
    "rate": "рейтинг",
    "rate_count": "брой оценки",
    "category": "категория",
    "product": "продукт",
    "body": "съдържание",
    "card_type": "вид на карта",
    "card_number": "номер на карта",
    "balance": "баланс",
    "paid": "изхарчена сума",
    "currency": "валута",
    "expire_at": "срок на годност",
    "discount_code": "код за отстъпка",
    "discount_percent": "отстъпка",
    "discount_limit": "лимит за отстъпка",
    "max_count": "максимален брой",
    "used_count": "използван",
    "start_date": "начална дата",
    "end_date": "крайна дата",
    "total_discount_amount": "общо отстъпки",
    "initial_charge": "първоначално зареждане",
    "total_count": "общ брой",
    "amount_paid": "платено количество",
    "name": "име",
    "published": "публикувано",
    "visits": "посещения",
    "color": "цвят",
    "landing_page": "целева страница",
    "enable": "разрешаване",
    "fix_commission": "фиксирана комисионна",
    "percent_commission": "процентна комисионна",
    "payment_at": "дата за плащане",
    "issued_at": "дата на издаване",
    "payment": "плащане",
    "website": "уебсайт",
    "email": "електронна поща",
    "user": "потребител",
    "code": "код",
    "schedule_at": "дата на график",
    "sender": "подател",
    "in_que": "на опашка",
    "sent": "изпратено",
    "shop": "пазарувайте",
    "quantity": "количество",
    "amount": "количество",
    "jobs": "работните места",
    "success": "успешно",
    "fail": "брой неуспехи",
    "distance": "разстояние",
    "duration": "продължителност",
    "reset_at": "нулиране на датата",
    "delivery_person": "лице",
    "delivery_service": "обслужване",
    "date": "дата",
    "order": "поръчка",
    "order_id": "идент. № на поръчката",
    "status": "състояние",
    "price": "цена",
    "count": "бр.",
    "final_price": "крайна цена",
    "charge": "зареждане",
    "mention": "споменаване",
    "officer": "офицер",
    "registered": "регистриран",
    "purchased": "купен",
    "sex": "пол"
  },
  "search_box": {
    "result": "Резултати от търсенето",
    "tips": "Търсете продукти и категории",
    "label": "Търсене ...",
    "category": "Категория"
  },
  "lead_status": {
    "physical_fast_delivery": "Незабавна доставка",
    "physical_under_24h_delivery": "Доставете в рамките на следващите {lead} часа",
    "physical_over_24h_delivery": "Подготвя се и се изпраща от следващите {days} дни",
    "virtual_fast_prepare": "Незабавна доставка",
    "virtual_under_24h": "Ще бъде направено в рамките на следващите {lead} часа",
    "virtual_over_24h": "Ще бъде направено от следващите {days} дни"
  },
  "return_request_state": {
    "pending": "В очакване",
    "accepted": "Потвърдено",
    "rejected": "Отхвърлено"
  },
  "return_order_reason": {
    "physical": {
      "U1": "Несъответствие на продукта",
      "U2": "Няма продукт в транспортната опаковка",
      "U3": "Счупване на опаковка или продукт",
      "U4": "Подправяне на пакет или сериен номер",
      "U5": "Някои артикули от пратката липсват",
      "U6": "Продуктът не е оригинален",
      "U7": "Продуктът не отговаря на спецификациите"
    }
  },
  "image_uploader": {
    "label": "Плъзнете и пуснете или <u>Изберете файл</u>",
    "max_size": "Максимално позволен размер: {size}"
  },
  "timespan": {
    "Morning": "08:00ч -12:00ч",
    "Evening": "12:00ч -18:00ч",
    "Night": "18:00ч -00:00ч",
    "Instant": "незабавна"
  },
  "week_day": {
    "Saturday": "събота",
    "Sunday": "неделя",
    "Monday": "понеделник",
    "Tuesday": "вторник",
    "Wednesday": "сряда",
    "Thursday": "четвъртък",
    "Friday": "петък"
  },
  "payment_form": {
    "title": "изберете метод на плащане",
    "gift_cards_input": "подаръчни карти",
    "gift_cards_input_empty": "няма намерени карти за подарък",
    "more": "повече",
    "pay_amount_by_gift_cards": "плащане с карта за подарък",
    "select_payment_method": "Изберете своя начин на плащане от следните възможности",
    "payment_amount_remained": "оставаща сума за плащане",
    "payment_amount": "платено количество",
    "all_paid_by_gift_cards": "Поздравления, не е необходимо да плащате за тази поръчка. Натиснете бутона - плащане с карта за подарък.",
    "pay_by_gift_cards_action": "Платете поръчката с карта за подарък",
    "order_free_payment": "Поздравления, Вашата поръчка е безплатна!",
    "order_free_payment_action": "поръчайте безплатно сега",
    "qr": {
      "address": "адрес за плащане",
      "amount": "количество"
    }
  },
  "discount_input": {
    "limit": "{percent}% отстъпка до {limit} {currency}",
    "action": "Добавете код за отстъпка",
    "code_input": "Код за отстъпка",
    "notifications": {
      "add_success": "Поздравления, валиден код за отстъпка."
    }
  },
  "gift_card": {
    "inactive": "Картата е деактивирана",
    "expire": "Срок на годност",
    "transfer": "Трансфер",
    "send_to_friend": "Изпрати на приятел"
  },
  "count_down": {
    "days": "ден",
    "hours": "час",
    "minutes": "минути",
    "seconds": "секунди"
  },
  "gift_status": {
    "Unpaid": "Очаква плащане",
    "Paid": "Платено",
    "Rejected": "Отхвърлено",
    "Canceled": "Отменено"
  },
  "gift_program_status": {
    "Airdrop": "Платежна система",
    "Advertising": "Реклама",
    "PersonalGift": "Личен подарък",
    "ShopGift": "Магазин за подаръци"
  },
  "currency_selector": {
    "label": "Валута"
  },
  "need_login": {
    "title": "Влизане",
    "login_sms": "Вход чрез SMS",
    "login_google": "Вход чрез Google",
    "login_facebook": "Вход чрез Facebook",
    "login_account": "Вход чрез Selldone",
    "register": "Нов потребител? Регистрирайте се сега.",
    "mobile_input": "Въведете мобилния си телефон",
    "verification_code": "Код за потвърждение",
    "msg_title": "Здравейте,",
    "msg_body": "Може да влезете по следните начини:"
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "5-годишен златен магазин"
    },
    "GOLDEN_2YEAR": {
      "name": "4-годишен златен магазин"
    },
    "GOLDEN_3YEAR": {
      "name": "3-годишен златен магазин"
    },
    "GOLDEN_4YEAR": {
      "name": "2-годишен златен магазин"
    },
    "GOLDEN_5YEAR": {
      "name": "1 година златен магазин"
    },
    "TOKEN_OWNER_1M": {
      "name": "Златен инвеститор"
    },
    "TOKEN_OWNER_10M": {
      "name": "Диамантен инвеститор"
    },
    "TOKEN_OWNER_100M": {
      "name": "Рубин инвеститор"
    },
    "COMMUNITY_LOYAL": {
      "name": "Член на висшата общност на комуникационните мрежи"
    },
    "GOLD_SUPPLIER": {
      "name": "Доставчик на злато"
    },
    "GOLD_SELLER": {
      "name": "Търговец на злато"
    },
    "CONTENT_SUPERMAN": {
      "name": "Топ производител на съдържание"
    },
    "NINJA": {
      "name": "нинджа"
    },
    "STAR": {
      "name": "звезда"
    },
    "GUARDIAN": {
      "name": "Страхотно обслужване на клиенти"
    },
    "KING": {
      "name": "Кралят на пазара"
    }
  },
  "cookie": {
    "title": "Този уебсайт използва бисквитки",
    "message": "Този уебсайт използва бисквитки за подобряване на потребителското изживяване. Използвайки нашия уебсайт, вие се съгласявате с всички бисквитки в съответствие с нашата Политика за бисквитки.",
    "preferences_action": "Управление на предпочитанията",
    "agree_action": "Съгласен съм"
  },
  "basket_item_message": {
    "title": "Необходима информация за този артикул",
    "save_actions": "Запазване на съобщението",
    "notifications": {
      "success": "Вашите входни данни са запазени."
    }
  },
  "faq": {
    "faq": "често задавани въпроси",
    "title": "Въпроси и отговори",
    "sub_title": "Това, което ни помоли да направим.",
    "message": "Потърсете отговора на вашия въпрос сред отговорите по-долу. Попитайте ни, ако ако не откриете търсения отговор.",
    "add_question_action": "Задайте нов въпрос",
    "read_more": "Прочетете още ..",
    "load_more": "Още въпроси ..",
    "main_page": "Главна страница с често задавани въпроси",
    "add_new": "Изпратете нов въпрос",
    "login_alert": "Влезте, за да зададете въпрос.",
    "question_input": "Въпрос",
    "question_input_placeholder": "Задайте въпроса си.",
    "notifications": {
      "success_add": "Въпросът Ви е изпратен успешно."
    }
  },
  "rating_labels": [
    "много зле",
    "зле",
    "нормално",
    "добре",
    "отлично"
  ],
  "map_view": {
    "address_detail": "подробности за адреса",
    "change": "промяна",
    "select": "изберете",
    "not_found_address": "няма намерен адрес",
    "enter_address_hint": "въведете адрес на местоназначение",
    "enter_your_address": "въведете Вашия адрес.",
    "postal_code": "пощенски код",
    "phone_input": "телефон",
    "building_number": "номер на сградата",
    "building_unit": "етаж",
    "full_name_input": "три имена",
    "save_detail_action": "запазете подробности",
    "more_detail_input": "повече подробности",
    "add_address_to_list": "добавете адрес към списъка",
    "address_title_input": "адресен етикет (изисква се)",
    "notifications": {
      "save_in_list": "този адрес е запазен във Вашия списък с всички подробности.",
      "edit_success": "новите адреси са запазени"
    },
    "delete_address_dialog": {
      "title": "Изтриване на адрес",
      "message": "Наистина ли искате да изтриете този адрес?",
      "action": "Премахнете адреса"
    }
  },
  "comment_manager": {
    "can_not_edit": "Не мога да редактирам този коментар!",
    "comment_input_empty": "Текстът на съобщението е празен!",
    "article_not_saved": "Запазете статията!"
  },
  "wheel_fortune": {
    "title": "Играйте и печелете",
    "message": "Цената на всяка игра е 10 чипа. В момента имате {chips} чип. Вземете повече чип, като закупите от магазина.",
    "win_message": "Поздравления, Вие спечелихте!",
    "lost_message": "Съжалявам, загубихте играта.",
    "try_again": "Можете да опитате отново"
  },
  "json": {
    "add": "Добавете структурни данни",
    "add_message": "Създайте нови структурни данни",
    "structures": "Структури",
    "book": {
      "title": "Книга",
      "desc": "Действия с книга, които позволяват на потребителите да купуват книгата, която намират директно от резултатите от търсенето."
    },
    "occupation": {
      "title": "Прогнозна заплата",
      "desc": "Информация за оценката на заплатата, като диапазони на заплатите и средни възнаграждения на базата на региона за типове работни места, показвани в опита за търсене на работа в Google."
    },
    "course": {
      "title": "Разбира се",
      "desc": "Образователни курсове, които се появяват в списък за специфичен доставчик. Курсовете могат да включват заглавие на курса, доставчик и кратко описание."
    },
    "howto": {
      "title": "Как да",
      "desc": "Наръчник превежда потребителите през набор от стъпки за успешно изпълнение на задача, включващ видео, изображения и текст."
    },
    "recipe": {
      "title": "Рецепта",
      "desc": "Рецепти, които се показват като индивидуален богат резултат или част от хост въртележка."
    }
  },
  "support": {
    "Financial": "финансови",
    "Technical": "Технически",
    "Advisor": "съветник"
  },
  "condition": {
    "new": "Нов",
    "refurbished": "Ремонтиран",
    "used": "Използван",
    "used_fair": "Използвано справедливо",
    "used_good": "Използван добре",
    "used_like_new": "Използван - като нов"
  },
  "variant_filter": {
    "title": "Филтър за вариант на продукта",
    "only_available": "В наличност"
  },
  "service": {
    "task": {
      "title": "Задачи",
      "message": "Списък на задачите, изпълнявани в тази услуга."
    },
    "appointment": {
      "title": "Назначаване",
      "message": "Изберете часовете от седмицата от следните часове въз основа на деня и часа, които са подходящи за вас."
    },
    "booking": {
      "title": "Резервация",
      "message": "Посочете периода от време на дните, в които искате да направите резервация в календара по-долу."
    },
    "subscription": {
      "title": "Абонамент"
    },
    "charge": {
      "title": "Зареждане"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "Фиксирана цена",
      "message": "При този тип ценообразуване цената на продукта е фиксирана сума и няма нужда купувачът да иска калкулация на цената."
    },
    "ESTIMATION": {
      "title": "Прогнозна цена",
      "message": "Цената на продуктите и услугите ще се калкулира до известна степен от продавача при подаване на поръчка, фактурите за плащане могат да се променят или добавят по време на услугата."
    },
    "AGREEMENT": {
      "title": "Ценообразуване по споразумение",
      "message": "Крайната цена на продуктите или услугите няма да се променя от продавача след направена поръчка."
    },
    "BID": {
      "title": "Наддаване / търг",
      "message": "Продуктът ще бъде продаден на най-високата оферирана цена от потенциалните купувачи."
    }
  },
  "map": {
    "title": "Местоположение за получаване на продукти",
    "confirm": "Задайте местоположение",
    "address": "адрес",
    "receptor": "получател"
  },
  "ShopBots": {
    "telegram": "Телеграма"
  },
  "article_tags": {
    "title": "Етикети за съдържание",
    "tags_input": "Етикети",
    "tags_input_message": "Списък с етикети на тази статия",
    "notification": {
      "add_success": "Добавени са етикети"
    }
  }
};