export default {
  "currency_default": "USD",
  "language_default": "en",
  "selldone": "Prodáno",
  "store": "ukládat",
  "not_exist": "neexistuje",
  "error": "Chyba",
  "active": "Aktivní",
  "inactive": "neaktivní",
  "required_value": "Požadované hodnoty",
  "original_warranty": "Záruka originálního produktu",
  "return_warranty_days": "{days} dny záruky vrácení",
  "no_return_warranty": "Bez návratu",
  "reed_agree_terms": "Přečetl jsem si podmínky použití a zásady ochrany osobních údajů a souhlasím s nimi.",
  "commons": {
    "Currency": "Měna",
    "COD": "COD",
    "State": "Stát",
    "Price": "cena",
    "order_price": "Částka objednávky",
    "VAT": "VAT",
    "Discount": "Sleva",
    "In_Stock": "Na skladě",
    "Variants": "Varianty",
    "No_variants": "Žádná varianta",
    "all": "VŠECHNO",
    "today": "Dnes",
    "yesterday": "Včera",
    "license": "Licence",
    "home": "Domov",
    "support": "Podpěra, podpora",
    "messages": "Zprávy",
    "no_message": "Žádná zpráva",
    "empty": "Prázdný",
    "phone": "Telefon",
    "address": "adresa",
    "name": "název",
    "password": "Heslo",
    "email": "E-mailem",
    "mobile": "mobilní, pohybliví",
    "login": "přihlásit se",
    "register": "Registrovat",
    "select_account": "Vyberte účet",
    "online": "online",
    "offline": "Offline",
    "finish": "Dokončit",
    "finished": "Hotovo",
    "preview": "Náhled",
    "free": "Volný, uvolnit",
    "free_completely": "Zcela bezplatné předplatné",
    "fee": "Poplatek",
    "month": "Měsíc",
    "months": "měsíce",
    "faq": "Často kladené otázky",
    "question": "Otázka",
    "answer": "Odpovědět",
    "create_date": "Vytvořit datum",
    "update_date": "Datum aktualizace",
    "start_date": "Datum zahájení",
    "end_date": "Datum ukončení",
    "social": "Sociální",
    "total": "Celkový",
    "orders": "Objednávky",
    "sessions": "Relace",
    "product_views": "Zobrazení produktu",
    "add_to_carts": "Přidat do košíků",
    "checkouts": "Překontrolovat",
    "payments": "Způsob platby",
    "organic_search": "Organické vyhledávání",
    "other": "jiný",
    "landing_page": "Vstupní stránka",
    "discount_code": "Slevový kód",
    "total_sell": "Celkové tržby",
    "details": "Podrobnosti",
    "currency": "Měna",
    "amount": "Množství",
    "published": "Publikováno",
    "draft": "Návrh",
    "save_changes": "Uložit změny",
    "source": "Zdroj",
    "medium": "Střední",
    "url": "URL",
    "revenue": "Příjmy",
    "performance": "Výkon",
    "term": "Období",
    "content": "Obsah",
    "session": "Zasedání",
    "product": "Produkt",
    "add": "Přidat",
    "checkout": "Překontrolovat",
    "payment": "Způsob platby",
    "more_options": "Více možností",
    "full_name": "Celé jméno",
    "tel": "Tel",
    "about_me": "O mně",
    "request_checking": "Žádost o kontrolu",
    "passport": "Cestovní pas",
    "birthday": "Narozeniny",
    "country": "Země",
    "city": "Město",
    "gender": "Rod",
    "offer": "Nabídka",
    "website": "webová stránka",
    "apply_for_all_products": "∞ Platí pro všechny produkty",
    "fix_commission": "Pevná provize",
    "percent_commission": "Procentní provize",
    "fixed_discount": "Pevná sleva",
    "discount_percentage": "Procentní sleva",
    "discount_limit": "Slevový limit",
    "no_code": "Žádný kód",
    "max_count": "Maximální počet",
    "count_unit": "Položky",
    "used": "Použitý",
    "daily": "Denně",
    "monthly": "Měsíční",
    "yearly": "Roční",
    "state": "Postavení",
    "disable": "Zakázat",
    "enable": "Umožnit",
    "activation_code": "Aktivační kód",
    "quantity": "Množství",
    "no_club": "Žádný klub",
    "per_order": "Na objednávku",
    "count": "Počet",
    "seconds": "Sekundy",
    "auto": "Auto",
    "title": "Titul",
    "message": "Zpráva",
    "width": "Šířka",
    "length": "Délka",
    "height": "Výška",
    "label": "Označení",
    "click": "Klikněte",
    "bank": "banka",
    "default": "Výchozí",
    "role": "Role",
    "user": "Uživatel",
    "users": "Uživatelé",
    "code": "Kód",
    "total_payment": "Celková platba",
    "balance": "Zůstatek",
    "chance": "Šance",
    "free_for_new_users": "Zdarma pro nové uživatele",
    "prize_amount": "Výše ceny",
    "win": "Vyhrát",
    "gift_card": "Dárková poukázka",
    "discount": "Sleva",
    "config": "Konfigurace",
    "prize": "Cena",
    "Prizes": "Ceny",
    "result": "Výsledek",
    "price": "cena",
    "lottery": "Loterie",
    "coupon": "Kupón",
    "customer_club": "Zákaznický klub",
    "shipping": "Lodní doprava",
    "sum": "Součet",
    "not_paid": "Nezaplaceno",
    "category": "Kategorie",
    "done": "Hotovo",
    "email_from": "Z",
    "subject": "Předmět",
    "schedule": "Plán",
    "files_list": "Seznam souborů",
    "file_max_size": "Maximální velikost souboru",
    "value": "Hodnota",
    "help": "Pomoc",
    "shipping_tax": "Přepravní daň",
    "net_price": "Čistá cena",
    "tax": "Daň",
    "tax_included": "V ceně",
    "limit": "Omezit",
    "min_purchase": "Minimální nákup",
    "eligible_for": "Způsobilé pro",
    "only_for_first_buy": "Pouze při prvním nákupu",
    "one_time_use": "Lze použít jednou",
    "period_of_qualify": "Limit používání období",
    "no_constraint": "Bez omezení",
    "timespan": "Časový úsek",
    "days": "dny",
    "weight": "Hmotnost",
    "distance": "Vzdálenost",
    "last_status": "Poslední stav",
    "issued_at": "Vydáno v",
    "order": "Objednat",
    "order_detail": "Podrobnosti objednávky",
    "percent": "Procent",
    "applied_count": "Aplikovaný počet",
    "campaign": "Kampaň",
    "os": "Operační systém",
    "browser": "Prohlížeč",
    "device": "přístroj",
    "device_ip": "IP adresa zařízení",
    "location": "Umístění",
    "user_agent": "Uživatelský agent",
    "affiliate": "Přidružený",
    "timeline": "Časová osa",
    "add_note": "Přidat poznámku",
    "record": "Záznam",
    "unlimited": "Neomezený",
    "show_coupons": "Zobrazit kupóny",
    "hide_coupons": "Skrýt kupóny",
    "service_area": "Oblast služeb",
    "apps": "Aplikace",
    "plugins": "Pluginy",
    "bots": "roboti",
    "categories": "Kategorie",
    "products": "produkty",
    "business": "podnikání",
    "personal": "Osobní",
    "size": "Velikost",
    "holiday": "Dovolená",
    "sod": "Platba při doručení",
    "cod": "Dobírka",
    "free_shipping": "Doprava zdarma",
    "hours": "hodiny",
    "send_date": "Datum odeslání",
    "deliver_date": "Datum doručení",
    "return_date": "Datum návratu",
    "pending": "čekající",
    "delivered": "Doručeno",
    "returned": "Vrátil",
    "canceled": "Zrušeno",
    "shipping_cost": "Cena poštovného",
    "action": "Akce",
    "cancel_date": "Zrušit datum",
    "deliver_in_process": "Objednávka je odeslána..",
    "kind": "Typ",
    "detail": "Podrobnosti",
    "map": "Mapa",
    "actions": "Akce",
    "navigation": "Navigace",
    "navigation_app": "aplikace",
    "payment_date": "Datum splatnosti",
    "duration": "Doba trvání",
    "bill": "Účtovat",
    "delivery_persons": "Kurýři",
    "delivery_services": "Doručovací služby",
    "live_view": "Živý pohled",
    "cart": "Vozík",
    "priority": "Přednost",
    "sufficient_credit": "Dostatečný kredit",
    "max_package_size": "Maximální velikost balení",
    "delay": "Zpoždění",
    "credit": "Kredit",
    "livemode": "Žít",
    "paused": "Pozastaveno",
    "debug": "Ladit",
    "token": "Žeton",
    "status": "Postavení",
    "courier": "Kurýr",
    "track": "Dráha",
    "track_order": "Sledování objednávky",
    "cost": "Náklady",
    "receipt": "Účtenka",
    "origin": "Původ",
    "destination": "Destinace",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "Nedostatek zásob!",
    "sub_total": "Mezisoučet",
    "customer": "Zákazník",
    "delivery": "dodávka",
    "online_orders": "Online objednávky",
    "pos_orders": "POS objednávky",
    "chips": "Bramborové hranolky",
    "subscribed": "Odebíráno",
    "unsubscribed": "Neodebíraný",
    "last_login": "Poslední přihlášení",
    "join_at": "Datum vstupu",
    "club": "Klub",
    "buyer": "Kupující",
    "seller": "prodejce",
    "or": "Nebo",
    "type": "Typ",
    "condition": "Stav",
    "brand": "Značka",
    "attempt": "Pokus",
    "error": "Chyba",
    "success": "Úspěch",
    "fail": "Selhat",
    "inventory": "Inventář",
    "link": "Odkaz",
    "visits": "Návštěvy",
    "transactions": "Transakce",
    "vat": "VAT",
    "pos_vat": "POS DPH",
    "sort_by": "Seřazeno podle..",
    "from": "Z",
    "from_lead_time": "Během následujících {hours} hodin",
    "no_credit_card_info": "Žádné informace o kartě!",
    "active": "Aktivní",
    "not_active": "Neaktivováno!",
    "referrals": "doporučení",
    "dashboard": "Přístrojová deska",
    "more": "Více",
    "inactive": "neaktivní",
    "developer": "Vývojář",
    "setting": "Nastavení",
    "membership_conditions": "Podmínky členství",
    "customers": "Zákazníci",
    "created_at": "Datum vytvoření",
    "updated_at": "Poslední aktualizace",
    "register_at": "Datum registrace",
    "old": "Starý",
    "new": "Nový",
    "start": "Start",
    "end": "Konec",
    "pos": "POS",
    "out_of_stock": "Vyprodáno",
    "fake": "Falešný",
    "low_inventory_warning": "Pozor, nízké zásoby!",
    "webhook": "Webhook",
    "notification": "Oznámení",
    "sms": "SMS",
    "online_payment_link": "Odkaz na online platbu",
    "waiting_load_data": "Čekání na načtení dat..",
    "views": "Pohledy",
    "sales": "Odbyt",
    "total_views": "Celkový počet zobrazení",
    "total_sales": "Celkové tržby",
    "from_previous_n_days": "Z posledních {days} dnů",
    "drop_shipping": "Dropshipping",
    "commission": "Komise",
    "shipping_area": "Oblast expedice",
    "main_seller": "Hlavní prodejce",
    "domain": "Doména",
    "contact": "Kontaktní informace",
    "wallet": "Peněženka",
    "reseller": "Překupník",
    "tracking_code": "Sledovací kód",
    "tracking_url": "Sledovací URL",
    "fulfillments": "Splnění",
    "reject": "Odmítnout",
    "reserved": "Rezervováno",
    "score": "Skóre",
    "customer_price": "Zákaznická cena",
    "options": "Možnosti",
    "show_details": "Ukázat detaily",
    "no_data": "Žádná data..",
    "waiting": "Čekání...",
    "waiting_connecting_payment": "Čekání na platební službu...",
    "creating_secure_payment": "Vytvoření bezpečné platby.",
    "officer": "Důstojník",
    "ticket": "Lístek",
    "ticket_url": "Adresa URL lístku",
    "closed_at": "Zavřeno v",
    "close_ticket": "Zavřít lístek",
    "reopen_ticket": "Znovu otevřít lístek",
    "require": "Vyžadovat*",
    "search": "Vyhledávání...",
    "language": "Jazyk",
    "tasks": "Úkoly",
    "permissions": "Oprávnění",
    "finish_date": "Datum ukončení",
    "complete_date": "Datum dokončení",
    "settle_date": "Datum vypořádání",
    "cost_span": "Cenové rozpětí",
    "industry": "Průmysl",
    "rating": "Hodnocení",
    "rates": "Hodnocení",
    "seen_at": "Viděno na",
    "completed": "Dokončeno",
    "you": "Vy",
    "shop": "Prodejna",
    "store": "ukládat",
    "granted": "Přiznáno",
    "deny": "Odmítnout",
    "request": "Žádost",
    "expert": "Expert",
    "response": "Odezva",
    "requests": "Žádosti",
    "experts": "Odborníci",
    "responses": "Odezvy",
    "negotiations": "Vyjednávání",
    "all_chats": "Všechny chaty",
    "chats": "Chaty",
    "tags": "Tagy",
    "description": "Popis",
    "rates_count": "Počet hodnocení",
    "rate": "Hodnocení",
    "comment": "Komentář",
    "chat": "Povídat si",
    "install": "Nainstalujte",
    "edited": "Upraveno",
    "undo": "vrátit",
    "redo": "Předělat",
    "male": "mužský",
    "female": "ženský",
    "calculator": "Kalkulačka",
    "catalog": "Katalog",
    "max_height": "Maximální výška",
    "images_compare": "Porovnání obrázků",
    "canvas": "Plátno",
    "table_of_contents": "Obsah",
    "comments": "Komentáře",
    "badge_codes": "Kód odznaků",
    "need_more": "Potřebovat více?",
    "invite_glow_caption": "Získejte 14,9 $ za každého přítele!",
    "register_free": "100% bezplatná registrace",
    "gift": "Dar",
    "google": "Google",
    "facebook": "Facebook",
    "instagram": "Instagram",
    "instashop": "Instashop",
    "show": "Ukázat",
    "hide": "Skrýt",
    "waiting_review": "Čeká se na recenzi",
    "not_selected": "Nevybraný",
    "time": "Čas",
    "final_price": "Konečná cena",
    "starting_price": "Vyvolávací cena",
    "day": "Den",
    "paid": "Zaplaceno",
    "service_bill": "Platba faktury",
    "avocado": "Avokádo",
    "delivery_price": "Cena poštovného",
    "select_address": "Vyberte adresu",
    "image": "obraz",
    "view": "Pohled",
    "sell": "Prodej",
    "hyper": "Hyper",
    "cart_list": "Vozík",
    "barcode_scanner": "Čtečka kódů",
    "scan_qr_code": "Naskenujte QR kód",
    "new_carts": "Nové vozíky",
    "pays": "Platby",
    "annually": "Každoročně",
    "sells": "Odbyt",
    "articles": "články",
    "jobs": "Pracovní místa",
    "job": "Práce",
    "blog": "Blog",
    "deleted_at": "Smazáno v",
    "capacity": "Kapacita",
    "download_at": "Datum posledního stažení",
    "downloads": "Stahování",
    "usage": "Používání",
    "select_upload_file": "Vyberte nebo přetáhněte soubor",
    "download_link": "Odkaz ke stažení",
    "uploading": "Nahrávání...",
    "files": "Soubory",
    "star": "Hvězda",
    "speed": "Rychlost",
    "feedback": "Zpětná vazba",
    "new_messages": "Nové zprávy",
    "file": "Soubor",
    "attachment": "Příloha",
    "gallery": "Galerie",
    "sync": "Synchronizovat",
    "diff_time": "Časový rozdíl",
    "network": "Síť",
    "account": "Účet",
    "configuration": "Konfigurace",
    "blockchain": "Blockchain",
    "blog_link": "Odkaz na blog",
    "community": "Společenství",
    "critical_zone": "Kritická zóna",
    "statistics": "Statistika",
    "access": "Přístup",
    "seo": "SEO",
    "followers": "Následovníci",
    "followings": "Sledující",
    "private": "Náhled",
    "soon": "Již brzy",
    "features": "Funkce",
    "bot": "Bot",
    "sample": "Vzorek",
    "how_it_work": "Jak to funguje?",
    "page": "Strana",
    "congratulations": "Gratulujeme",
    "recommend": "Doporučit",
    "recommended": "Doporučeno",
    "recoms": "Doporučení",
    "likes": "Líbí se",
    "clicks": "kliknutí",
    "platform": "Plošina",
    "cms": "CMS",
    "cash": "Hotovost",
    "dir_payment": "bankovní převod",
    "auto_complete": "Automatické dokončení",
    "compare": "Porovnejte",
    "infinite": "Nekonečný",
    "tips": "Tipy",
    "technical": "Technický",
    "finance": "Finance",
    "your_phone_input": "vložte telefonní číslo",
    "income": "Příjem",
    "change": "Změna",
    "new_users": "Noví uživatelé",
    "success_orders": "Úspěšné objednávky",
    "direct": "Přímo",
    "last_activity": "Poslední aktivita",
    "landing": "Přistání",
    "now": "Nyní",
    "accept_agreement": "Přečetl jsem si podmínky a souhlasím s nimi.",
    "report": "Zpráva",
    "tablet": "Tableta",
    "pc": "PC",
    "acquisition_channel": "Akviziční kanál",
    "to": "Na",
    "info": "Info",
    "general": "Všeobecné",
    "upload": "nahrát",
    "general_config": "Obecná konfigurace",
    "limits_config": "Omezení",
    "design_config": "Design & Styl",
    "duration_config": "Limit trvání",
    "constraints_config": "Limity způsobilosti",
    "clubs_config": "K dispozici v klubech",
    "additional_config": "Další konfigurace",
    "import": "Import",
    "ribbon": "Stuha",
    "countries": "země",
    "edit": "Upravit",
    "delete": "Vymazat",
    "analytics": "Analytics",
    "rules": "Pravidla",
    "unset": "Nenastaveno",
    "carts": "Vozíky",
    "optional": "Volitelný",
    "design": "Design",
    "filter": "Filtr",
    "send": "Poslat",
    "approved": "Schválený",
    "unit": "Jednotka",
    "profile": "profil",
    "shipping_rates": "Poštovné",
    "package": "Balík",
    "overview": "Přehled",
    "live": "Žít",
    "never": "Nikdy",
    "always": "Vždy",
    "mandatory": "Povinné",
    "expire_at": "Datum vypršení platnosti",
    "position": "Pozice",
    "channel": "Kanál",
    "age": "Stáří",
    "charge": "Nabít",
    "giftcard": "Dárková poukázka",
    "acquisition": "Získávání",
    "conversion": "Konverze",
    "total_payments": "Celkové platby",
    "community_ask": "Zeptejte se v komunitě",
    "children": "Děti",
    "export": "Vývozní",
    "list": "Seznam",
    "hierarchy": "Hierarchie",
    "images": "snímky",
    "demo": "Demo",
    "author": "Autor",
    "designer": "Návrhář",
    "max": "Maximum",
    "accepted": "Přijato",
    "reply": "Odpověď",
    "reviewed": "Zkontrolováno",
    "restored": "Obnoveno",
    "merchant": "Obchodník",
    "per_product": "Na produkt",
    "journey": "Cesta",
    "after": "Po",
    "waiting_for_payment": "Prosím o dokončení platby...",
    "hour": "Hodina",
    "minute": "Minuta",
    "premium": "Pojistné",
    "light": "Světlo",
    "dark": "Temný",
    "guest": "Host",
    "shops": "Obchody",
    "vendor": "Prodejce",
    "vendors": "Prodejci",
    "marketplace": "Tržiště",
    "verify_date": "Ověřte datum",
    "note": "Poznámka",
    "panel": "Panel",
    "removed": "Odebráno",
    "segments": "Segmenty",
    "personal_info": "Osobní informace",
    "preferences": "Předvolby",
    "spec": "Spec",
    "reviews": "Recenze",
    "constraints": "Omezení",
    "flexible": "Flexibilní",
    "usage_limit": "Limit použití",
    "temporary": "Dočasný",
    "original": "Originál",
    "saved": "Uložené!",
    "sort": "Seřadit",
    "documents": "Dokumenty",
    "document": "Dokument",
    "please_wait": "Prosím, čekejte...",
    "pickup": "Vyzvednout",
    "customize": "přizpůsobit",
    "difficulty": "Obtížnost",
    "banned": "Zakázáno",
    "company": "Společnost",
    "tax_shipping": "Přepravní daň",
    "warranty": "Záruka",
    "return_policy": "Reklamační řád",
    "guide": "Průvodce",
    "translate": "přeložit",
    "public": "Veřejnost",
    "deleted": "Smazáno",
    "variant": "Varianta",
    "secure": "Zajistit",
    "admin": "Admin",
    "tax_included_abstract": "vč.",
    "payment_not_settled": "Platba neproběhla!",
    "orders_list": "Seznam objednávek",
    "subscription_plan": "Plán předplatného",
    "contents": "Obsah",
    "pricings": "Ceny",
    "static_page": "Statická stránka",
    "shop_button": "Tlačítko Obchod",
    "embed": "Vložit",
    "over": "Přes",
    "tax_vary_by_location": "lišit se. umístění",
    "product_type": "Typ produktu",
    "tax_id": "DIČ",
    "business_name": "Obchodní jméno",
    "invoice": "Faktura",
    "included_in_the_product": "Součástí produktu",
    "included_in_the_product_description": "Výrobek obsahuje následující komponenty",
    "cross_sell": "Křížový prodej",
    "discount_off": "OFF",
    "extra_discount": "Extra sleva",
    "template": "Šablona",
    "in_cart": "V košíku",
    "pros_and_cons": "Výhody a nevýhody",
    "related_products": "Související produkty",
    "related_categories": "Související kategorie",
    "badges": "Odznaky",
    "explore": "Prozkoumat"
  },
  "dialogs": {
    "delete": {
      "title": "Vymazat",
      "message": "Opravdu chcete tuto položku smazat?",
      "action": "Ano, smazat nyní"
    }
  },
  "actions": {
    "add_to_cart": "Přidat do košíku",
    "cancel": "zrušení",
    "update": "Aktualizace",
    "add": "Přidat",
    "delete": "Vymazat",
    "new": "Nový",
    "save_continue": "Uložit a pokračovat",
    "save": "Uložit",
    "save_changes": "Uložit změny",
    "change": "Změna",
    "continue": "Pokračovat",
    "close": "Zavřít",
    "finish": "Dokončit",
    "poll": "Hlasování",
    "view": "Pohled",
    "edit": "Upravit",
    "next": "další",
    "previous": "Předchozí",
    "create": "Vytvořit",
    "set": "soubor",
    "find": "Nalézt",
    "accept": "Přijmout",
    "reject": "Odmítnout",
    "back": "Zadní",
    "pay": "Platit",
    "pay_now": "Zaplať teď",
    "print": "Tisk",
    "return": "Vrátit se",
    "publish": "Publikovat",
    "confirm": "Potvrdit",
    "copy": "kopírovat",
    "submit": "Předložit",
    "send": "Poslat",
    "yes": "Ano",
    "no": "Ne",
    "meh": "Hmm",
    "clear": "Průhledná",
    "dismiss": "Zavrhnout",
    "search": "Vyhledávání",
    "deselect_all": "Odznačit vše",
    "select_all": "Vybrat vše",
    "refresh": "Obnovit",
    "verify": "Ověřte",
    "play": "Hrát si",
    "open": "OTEVŘENO",
    "calculate": "Vypočítat",
    "quick_buy": "Rychlý nákup",
    "click_here": "Klikněte zde",
    "schedule": "Plán",
    "send_now": "Odeslat nyní",
    "download": "Stažení",
    "reset_default": "Obnovit do základního nastavení",
    "reset": "Resetovat",
    "check": "Šek",
    "cod_payment": "Dobírka",
    "dir_payment": "Převod peněz",
    "online_payment": "Platba přes internet",
    "checkout": "Překontrolovat",
    "show_all": "Ukázat vše",
    "login": "přihlásit se",
    "logout": "Odhlásit se",
    "more": "Více..",
    "collapse": "Kolaps",
    "apply_change": "Aplikuj změny",
    "apply": "Aplikovat",
    "add_giftcard": "Přidat dárkovou kartu",
    "charge": "Nabít",
    "send_invites": "Poslat pozvánky",
    "past": "Minulost",
    "restore": "Obnovit",
    "cut": "Střih",
    "get_sms_code": "Získejte ověřovací kód",
    "register_no_mail": "Pokračujte bez e-mailu",
    "no_mail_register_message": "Nemáte e-mailovou adresu nebo jste zapomněli heslo?",
    "reset_by_mail": "Obnovení hesla e-mailem",
    "reset_by_sms": "Obnovení hesla pomocí SMS",
    "cash_payment": "Platba v hotovosti",
    "show_chart": "Zobrazit graf",
    "open_app": "Otevřete aplikaci",
    "login_now": "Přihlas se nyní",
    "watch_video": "Sledovat video",
    "check_now": "Zkontroluj to teď",
    "remove_image": "Odebrat obrázek",
    "view_website": "Otevřít odkaz",
    "explore": "Prozkoumat {name}",
    "go": "Jít",
    "read_more": "Přečtěte si více",
    "start_now": "Začněte hned – je to zdarma",
    "view_live": "Zobrazit živě",
    "resend_code": "Znovu odeslat kód",
    "invite": "Pozvat",
    "add_more": "Přidej víc",
    "install_now": "Nainstalovat nyní",
    "uninstall": "Odinstalovat",
    "show_preview": "Ukaž ukázku",
    "hide_preview": "Skrýt náhled",
    "download_now": "Stáhnout teď",
    "auto_fill": "Automatické vyplňování",
    "track": "Dráha",
    "change_state": "Změnit stav",
    "done": "Hotovo",
    "reply": "Odpověď",
    "watch_now": "Sledujte nyní",
    "unlock": "Odemknout",
    "lock": "Zámek",
    "create_clone": "Vytvořte klon",
    "regenerate": "Regenerovat",
    "add_message": "Přidat zprávu",
    "continue_chat": "Pokračovat v chatu",
    "add_new_message": "Přidat novou zprávu",
    "change_setting": "Změnit nastavení",
    "delete_all": "Smazat všechny",
    "transfer_fund": "Převodový fond",
    "reverse_fund": "Reverzní fond",
    "settlement": "Vyrovnání",
    "refund": "Vrácení peněz",
    "partial_refund": "Částečné vrácení peněz",
    "change_payment_method": "Změňte způsob platby",
    "buy": "Koupit",
    "view_all": "Zobrazit vše",
    "view_now": "Zobrazit nyní"
  },
  "instance_message_title": "Odeslat okamžitou zprávu",
  "instance_message": "Ahoj {name}, jmenuji se {author} ze společnosti {company}.",
  "errors": {
    "419": "Jste po dlouhou dobu neaktivní, z bezpečnostních důvodů prosím <b>⟳ OBNOVUTE STRÁNKU</b> .",
    "gateway_blockchain_sync_error": "Systém se nesynchronizuje s blockchainem. Dokud nebudou dokončeny synchronizace našich serverů, nebude možné vytvořit novou transakci. Problém řešíme.",
    "gateway_network_error": "Služba platební brány zaznamenala problém s komunikací."
  },
  "receiver_info": {
    "map": {
      "title": "Doručovací adresa",
      "confirm": "Nastavit umístění",
      "address_type": "Destinace",
      "receptor_type": "Přijímač"
    },
    "receiver_address": "Vyberte dodací adresu",
    "address": "adresa",
    "postcode": "PSČ",
    "enter_value": "Vyplňte zde",
    "address_note": "Poznámka",
    "tel": "Kontaktní číslo",
    "service_address": "Vyberte svou adresu"
  },
  "weight": {
    "g": "G",
    "oz": "oz",
    "lb": "lb",
    "kg": "kg"
  },
  "mass_unit_name": {
    "g": "gram",
    "oz": "Unce",
    "lb": "Libra",
    "kg": "kilogram"
  },
  "length": {
    "cm": "cm",
    "in": "v",
    "ft": "ft",
    "mm": "mm",
    "m": "m",
    "yd": "yd"
  },
  "size_unit_name": {
    "cm": "Centimetr",
    "in": "Palec",
    "ft": "Chodidlo",
    "mm": "milimetr",
    "m": "Metr",
    "yd": "Yard"
  },
  "distance": {
    "m": "Metr",
    "km": "km"
  },
  "time": {
    "days": "Dny",
    "hours": "hodiny",
    "minutes": "Minut",
    "seconds": "Sekundy"
  },
  "units": [
    "Jednotka",
    "položka",
    "každý",
    "soubor",
    "kus",
    "kilogram",
    "gram",
    "miligram",
    "Metr",
    "milimetr",
    "metr čtvereční",
    "čtvereční stopa",
    "metr krychlový",
    "litr",
    "mililitr",
    "chodidla",
    "galonů",
    "palce",
    "unce",
    "liber",
    "litry",
    "yardů",
    "pokoj, místnost",
    "sekundy",
    "minut",
    "hodin",
    "dní",
    "týdnů",
    "měsíce",
    "let"
  ],
  "region_types": {
    "State": "Stát",
    "Territory": "Území",
    "Province": "Provincie"
  },
  "transaction_status": {
    "RequireAction": "Je vyžadována akce",
    "Processing": "zpracovává se",
    "Canceled": "Zrušeno",
    "Succeeded": "Uspěl"
  },
  "placeholders": {
    "name": "Jone Cox",
    "email": "váš-mail@mail.com",
    "phone": "+1 000 0000",
    "language": "Zvolte jazyk..",
    "friend_email": "E-mail vašeho přítele...",
    "friend_name": "Opt. Jméno tvého přítele",
    "select_date": "Vyberte datum..."
  },
  "notification": {
    "confirm": "Potvrdit",
    "confirm_message": "Změny byly úspěšně uloženy.",
    "error": "Chyba",
    "message": "Zpráva",
    "caution": "Pozor",
    "warning": "Varování",
    "award": "gratuluji",
    "error_message": "Bohužel došlo k chybě.",
    "congratulation": "gratuluji",
    "coming_soon": "Již brzy",
    "on_fetching_data": "Příjem informací..",
    "new_pwa_version": "Nová verze je nyní k dispozici. Chcete aplikaci aktualizovat?",
    "over_license_limit": "Překročení licenčního limitu",
    "update_license": "Aktualizujte svou licenci",
    "required": "Požadované",
    "invalid_email": "Neplatný e-mail",
    "invalid_domain": "Neplatná doména",
    "invalid_min_length": "Minimální délka musí být {length}",
    "invalid_min_array_length": "Vyberte alespoň {length} položek",
    "invalid_max_chars": "Max {maxCount} znaků",
    "invalid_url": "neplatná URL",
    "country_invalid": "Vyberte cílovou zemi!",
    "postal_code_invalid": "Nastavte platné PSČ!"
  },
  "colors": {
    "#D32F2F": "Červené",
    "#C2185B": "Růžový",
    "#7B1FA2": "Nachový",
    "#512DA8": "Tmavě fialová",
    "#303F9F": "Tmavá modř",
    "#1976D2": "Modrý",
    "#0288D1": "Světle modrá",
    "#0097A7": "Tyrkysově modrá",
    "#00796B": "Husa zelená",
    "#388E3C": "Zelená",
    "#689F38": "Světle zelená",
    "#AFB42B": "Limonáda",
    "#FBC02D": "Žlutá",
    "#FFA000": "Jantar",
    "#F57C00": "oranžový",
    "#E64A19": "Lesklá oranžová",
    "#5D4037": "Hnědý",
    "#616161": "Šedá",
    "#455A64": "Šedá Modrá",
    "#FFD700": "Zlatý",
    "#C0C0C0": "stříbrný",
    "#b76e79": "Zlatá růže",
    "#383838": "Matná černá",
    "#FFFFFF": "Bílý",
    "#FFF": "Bílý",
    "#000000": "Černá",
    "#000": "Černá",
    "#7d263a": "Maroon",
    "#FD9F17": "Zlato",
    "#229DBF": "Aqua",
    "#6DC9E2": "Aqua Triblend",
    "#413B2D": "Armáda",
    "#474747": "Asfalt",
    "#E6195C": "Bobule",
    "#B2184C": "Berry Triblend",
    "#FC7F5F": "Spálený pomeranč",
    "#80011F": "Kardinál",
    "#382829": "Čokoláda",
    "#F06336": "Korál",
    "#FAE7C9": "Krém",
    "#6B2257": "Rybíz",
    "#222127": "Tmavošedý",
    "#0D5A74": "Deep Teal",
    "#00582F": "Evergreen",
    "#214C30": "Les",
    "#DC2867": "Fuchsie",
    "#38561F": "Kelly",
    "#5C884D": "List",
    "#558450": "Světlá Aqua",
    "#96B5C9": "Světle modrá",
    "#DCAFCE": "Šeřík",
    "#D3E1A4": "Limetka",
    "#9DE7C2": "Máta",
    "#F6EAD2": "Přírodní",
    "#1A1F35": "námořnictvo",
    "#404624": "Olivový",
    "#271020": "Švestka",
    "#A8355C": "Malina",
    "#D6BEA6": "Jemný krém",
    "#BEA994": "Opálení",
    "#0DB2AE": "Teal",
    "#A86EA9": "fialový",
    "#36454F": "Dřevěné uhlí",
    "#b3b0ab": "uhlíkově šedá",
    "#463e3d": "Uhlí vřes",
    "#282d3c": "Navy Blazer"
  },
  "address_info": {
    "name": "název",
    "tel": "Telefon",
    "email": "E-mailem",
    "country": "Země",
    "city": "Město",
    "state": "Stát",
    "address": "adresa",
    "building_number": "Číslo budovy",
    "building_unit": "Jednotka",
    "postcode": "PSČ",
    "note": "Poznámka",
    "county": "okres"
  },
  "product_types": {
    "physical": "Fyzický",
    "physical_description": "Fyzické produkty jako: mobilní telefony, knihy, elektronické součástky.",
    "virtual": "Virtuální",
    "virtual_description": "Internetové produkty jako: dobíjecí karta, rezervace hotelu, dobíjení her.",
    "file": "Soubor",
    "file_description": "Všechny povolené soubory, jako je video z online kurzu, dokumenty ke stažení.",
    "service": "Servis",
    "service_description": "Služby jako: opravy, doprava, výuka.",
    "subscription": "Předplatné",
    "subscription_description": "Předplatné a fakturace za produkty, služby nebo obsah."
  },
  "license": {
    "free": "Volný, uvolnit",
    "startup": "Spuštění",
    "company": "Společnost",
    "enterprise": "Podnik"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "Muži",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW",
    "GHS": "GHS",
    "ZWD": "ZWD",
    "IQD": "IQD",
    "SYP": "SYP"
  },
  "variants": {
    "color": "Barva",
    "volume": "Velikost",
    "count_in_pack": "Počítejte v balení",
    "weight": "Hmotnost",
    "type": "Materiál",
    "style": "Styl"
  },
  "delivery_state": {
    "check_queue": "Čeká se na recenzi",
    "order_confirm": "Potvrzení objednávky",
    "preparing_order": "Připravuje se",
    "sent_order": "Na dobírku",
    "to_customer": "Doručeno"
  },
  "status": {
    "unpaid": "Nezaplaceno",
    "paid": "Zaplaceno",
    "canceled": "Zrušeno",
    "completed": "Usazeno",
    "reserved": "Rezervováno",
    "COD": "COD",
    "sold": "Prodáno",
    "open": "OTEVŘENO",
    "cancel": "Zrušeno",
    "active": "Aktivní",
    "inactive": "neaktivní",
    "debug": "Ladit",
    "live": "Žít",
    "test": "Test",
    "connected": "Připojeno",
    "disconnected": "Odpojeno",
    "accept": "Přijmout",
    "reject": "Odmítnout",
    "pending": "čekající",
    "rejected": "Odmítnuto",
    "accepted": "Přijato"
  },
  "dimensions": {
    "cm": "cm",
    "km": "km",
    "kg": "kg"
  },
  "transportation_type": {
    "motorbike": "Motorka",
    "motorbike_description": "Střední hmotnost v okruhu několika kilometrů.",
    "cargo_small": "Malý náklad",
    "cargo_small_description": "Vícekilometrový lehký náklad.",
    "cargo": "Náklad",
    "cargo_description": "Střední hmotnost v okruhu několika kilometrů.",
    "truck": "Náklaďák",
    "truck_description": "Hromadný nebo těžký náklad v rámci země.",
    "fast_post": "Rychlý příspěvek",
    "fast_post_description": "Rychlé odeslání poštou.",
    "post": "Normální příspěvek",
    "post_description": "Běžná pošta přes poštu.",
    "airplane": "Letecká pošta",
    "airplane_description": "Tuzemský a zahraniční lehký a střední náklad.",
    "bicycle": "Čisté odeslání",
    "bicycle_description": "Lehký náklad do několika set yardů od nemotorových vozidel.",
    "global": "Globální doprava",
    "global_description": "Doprava do zámoří letecky, po moři nebo po zemi.",
    "pickup": "Vyzvednout",
    "pickup_description": "Zákazníci si zboží vyzvednou ve vaší kamenné prodejně nebo skladu."
  },
  "article": {
    "login_to_see_error": "Pro přístup k článku se přihlaste",
    "create_new_action": "Vytvořit nový obsah",
    "menu_title": "Jídelní lístek",
    "menu": {
      "edit": "Mód úprav",
      "view_mode": "Režim zobrazení",
      "delete": "Smazat článek"
    },
    "schedule_action": "Chcete naplánovat zveřejnění?",
    "schedule_title": "Naplánujte automatické publikování",
    "edit_mode": "Upravit",
    "public_view_mode": "Pohled veřejnosti",
    "publish_at": "Publikovat na",
    "published": "Publikováno",
    "draft": "Návrh",
    "saving": "Ukládání",
    "save_and_publish_action": "Uložit a publikovat",
    "save_draft_action": "Uložit koncept",
    "private": "soukromé",
    "public": "Veřejnost",
    "category_input": "Kategorie",
    "category_input_message": "Vyberte kategorii článku",
    "parent_input": "Rodičovská Kategorie",
    "parent_input_message": "Vyberte obsah otce",
    "schedule_input": "Plán",
    "schedule_input_placeholder": "Pokud chcete, aby byl příběh zveřejněn v konkrétním čase.",
    "schedule_view_action": "Zobrazit plán publikování",
    "author_title": "Napsáno",
    "read_time": "Studijní čas",
    "read_time_unit": "Minut",
    "claps_action": "tleská",
    "claps": "tleská",
    "likes": "Jako",
    "about_author": "O autorovi",
    "updated_at": "Aktualizováno",
    "wrote_at": "Napsáno v",
    "now": "Nyní",
    "follow_action": "Následovat",
    "followed": "Následoval",
    "report_and_delete_action": "Nahlásit a smazat tento článek",
    "report_action": "Nahlásit zneužití",
    "you_reported_this_article": "Tento článek již obsahuje zprávu o zneužití.",
    "add_to_publication_action": "Přidat do publikace",
    "author_socials": "Autor na sociálních sítích",
    "share": "Podíl",
    "report_dialog": {
      "report_and_delete_title": "Nahlaste zneužití a odstraňte obsah",
      "report_title": "Nahlásit tento obsah jako urážlivý",
      "message": "Jaký je důvod odeslání tohoto obsahu? Vyberte jednu z následujících možností.",
      "accept_and_delete_action": "Potvrdit a smazat obsah"
    },
    "schedule_dialog": {
      "title": "Plán vydání obsahu",
      "publish_at": "Publikovat na",
      "last_edit": "Poslední úprava",
      "view_action": "Zobrazit článek"
    },
    "notifications": {
      "update_success_title": "Odeslat informace",
      "update_success": "Článek byl úspěšně aktualizován.",
      "update_error": "Zadané informace nejsou platné.",
      "delete_error": "Tento článek nemůžete smazat!",
      "report_and_delete_success_title": "Nahlásit a smazat",
      "report_and_delete_success_message": "Článek byl úspěšně smazán.",
      "report_success_title": "Reportážní článek",
      "report_success_message": "Vaše zpráva o tomto článku byla zveřejněna."
    },
    "alert": {
      "delete_article": {
        "title": "Smazat článek",
        "message": "Opravdu chcete tento článek trvale smazat?",
        "action": "Vymazat"
      }
    },
    "edit_window": {
      "title": "Vyberte Text obrázku a Souhrn",
      "digest": "souhrn"
    },
    "editor": {
      "title_placeholder": "Titul..",
      "body_placeholder": "Pište skvělý obsah..",
      "accept_file_types_error": "Tento formát souboru je nepřijatelný:",
      "max_file_size_error": "Tento soubor je příliš velký:",
      "notifications": {
        "image_uploaded_success": "Obrázek byl úspěšně uložen",
        "image_uploaded_failed": "Chyba při načítání obrázku."
      },
      "embed_placeholder": "Zadejte kód iframe, Facebook, Youtube nebo jakoukoli jinou adresu URL a stiskněte enter.",
      "embed_caption_placeholder": "Zadejte název (volitelné)",
      "images_caption_placeholder": "Zadejte název tohoto obrázku.."
    }
  },
  "article_report": {
    "inappropriate": "Obsah tohoto článku je nevhodný.",
    "fake": "To je falešné a klamné.",
    "spam": "Tato položka byla spamována a zkopírována.",
    "scam": "Dá se očekávat, že to způsobí malware, viry nebo selhání systému.",
    "hacked": "Zdá se, že tento web byl napaden hackery.",
    "offensive": "Jazykový obsah a slovní zásoba jsou neetické a neuctivé.",
    "violent": "Myslím, že tento obsah obsahuje pornografii a je v rozporu se zákony.",
    "harassment": "Myslím, že je to rasistické.",
    "hate": "Myslím, že jde o propagaci násilí.",
    "infringe": "To porušuje moje práva."
  },
  "comments": {
    "new_action": "Kliknutím zanecháte komentář..",
    "title": "Komentáře",
    "body_placeholder": "Váš komentář nebo zpráva",
    "send_action": "Odeslat komentář",
    "body_is_empty_error": "Komentář je prázdný!",
    "comments": "Komentáře",
    "no_comments": "Napište první komentář...",
    "load_more_action": "Získejte další komentáře..",
    "cant_send_comment": "Nemůžete přidat nový příspěvek.",
    "cant_remove_this_comment": "Tento komentář nemůžete smazat!",
    "product_buyer": "Kupující",
    "delete_alert": {
      "title": "Smazat komentář",
      "message": "Chcete tento komentář smazat?",
      "action": "Vymazat"
    },
    "notifications": {
      "delete_success": "Váš komentář byl úspěšně smazán."
    },
    "first_send": "První příspěvek",
    "comment_at": "Na",
    "edit_comment": "Upravit komentář",
    "my_comments": "Moje komentáře"
  },
  "customer_club": {
    "bronze": "Bronz",
    "silver": "stříbrný",
    "gold": "Zlatý",
    "platinum": "Platina",
    "diamond": "diamant"
  },
  "application_categories": {
    "tracking": "Kontrola chování uživatelů",
    "payment": "Způsob platby",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "Přeprava",
    "automation": "Automatizace",
    "inventory": "Skladování",
    "accounting": "Účetnictví",
    "marketing": "Marketing",
    "advertising": "Reklamní",
    "staff": "Personál",
    "incentive": "Pobídky",
    "shop": "Prodejna"
  },
  "social_network": {
    "instagram": "Instagram",
    "telegram": "Telegram",
    "googleplay": "Google Play",
    "appstore": "Obchod s aplikacemi",
    "twitter": "Cvrlikání",
    "linkedin": "Linkedin",
    "medium": "Střední",
    "selldone": "Prodáno",
    "facebook": "Facebook",
    "pinterest": "Pinterest",
    "whatsapp": "WhatsApp",
    "skype": "Skype",
    "facebook_messenger": "Facebook Messenger"
  },
  "form_builder": {
    "add_item_action": "Přidat novou položku",
    "title_input": "Titul",
    "name_input": "Název proměnné",
    "value_input": "Hodnoty",
    "value_input_message": "Seznam uživatelských možností",
    "default": "Výchozí hodnota",
    "types": {
      "simple": "Jednoduchý",
      "selective": "Selektivní",
      "switch": "Přepínač",
      "file": "Soubor",
      "number": "Číslo"
    },
    "placeholder_input": "Zástupný symbol",
    "file_type_input": "Přijatelné typy souborů",
    "file_type_message": "jpeg, png, zip, ..."
  },
  "virtual_order_info_summery": {
    "title": "jméno výrobku",
    "reserved_at": "datum registrace",
    "total_price": "Celková částka",
    "discount": "Sleva",
    "final_price": "Konečná částka",
    "payment_status": "Status platby",
    "payment_status_waiting": "Čekání na platbu",
    "payment_status_paid": "Zaplaceno",
    "buyer": "Kupující"
  },
  "virtual_item_info": {
    "title": "Virtuální položka",
    "outputs": {
      "title": "Informace o výstupu",
      "sub_title": "Důvěrné informace o této Položce",
      "message": "Tyto informace se uživateli zobrazí po zakoupení produktu."
    },
    "inputs": {
      "title": "Požadované informace",
      "sub_title": "Informace o kupujícím jsou povinné",
      "message": "Kupující musí do formuláře zadat požadované údaje"
    },
    "notifications": {
      "inputs_set_success": "Informační formulář byl úspěšně zaregistrován.",
      "confirm_by_admin_success": "Dokončení objednávky potvrzeno.",
      "confirm_by_buyer_success": "Dokončení objednávky potvrzeno."
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "Tuto objednávku nelze přijmout platbou na dobírku.",
    "payment_returned": "Platba od zákazníka je vrácena.",
    "payment_fraud": "Platba byla identifikována jako podvod.",
    "location_out_of_service": "Adresa zákazníka je mimo provoz.",
    "user_not_responding": "Zákazník nereagoval na hovory.",
    "shop_owner_fault": "Došlo k chybě personálu obchodu při vyplňování informací.",
    "lack_of_inventory": "Vyprodáno.",
    "legal_restriction": "Nelze zadat objednávku z důvodu zákonných omezení.",
    "pricing_fault": "Chyba v ceně prodejce.",
    "system_fault": "Systémová chyba."
  },
  "basket_order_info_summery": {
    "receiver": "Přijímač",
    "phone": "Tel",
    "reserved_date": "Datum nákupu",
    "total_price": "Celková částka",
    "discount": "Sleva",
    "final_price": "Konečná částka",
    "address": "Doručovací adresa",
    "payment_status": "Status platby"
  },
  "basket_status": {
    "open": "OTEVŘENO",
    "reserved": "Rezervováno",
    "paid": "Zaplaceno",
    "canceled": "Zrušeno",
    "cod": "Platba při doručení",
    "receipt_added": "Potvrzení přidáno",
    "payment_processing": "Platba je v procesu zpracování"
  },
  "basket_delivery_state": {
    "rejected": "Odmítnuto",
    "reject_reason_not_found": "Důvod není znám.",
    "step_1": "Posouzení",
    "step_2": "potvrzení",
    "step_3": "Příprava",
    "step_4": "Na dobírku",
    "step_5": "Doručeno"
  },
  "basket_return_request_view": {
    "title": "Žádost o vrácení",
    "delivery_date": "Datum doručení",
    "return_date": "Datum požadavku",
    "items_count": "Počítají se vrácené položky",
    "items_count_unit": "položky",
    "reason": "Důvod",
    "description": "Popis",
    "status": "Postavení",
    "download_image": "Stáhnout obrázek",
    "download_film": "Stáhnout video",
    "download_voice": "Stáhnout hlas",
    "accept_by_admin_action": "Přijmout žádost",
    "reject_by_admin_action": "Odmítnout žádost",
    "message_for_admin": "Podle smlouvy, kterou jste přijali používáním Prodávaného, musíte kontaktovat kupujícího a informovat ho o procesu vrácení jeho objednávky. Toto musí být provedeno, pokud je žádost přijata nebo zamítnuta a je získán úplný souhlas kupujícího.",
    "notifications": {
      "update_status_success": "Stav požadavku aktualizován."
    }
  },
  "basket_list": {
    "return_count": "Návrat: {count} číslo",
    "table": {
      "row": "Řádek",
      "image": "obraz",
      "product_name": "Produkt",
      "variant": "Varianta",
      "warranty": "Záruky",
      "count": "Počet",
      "price": "cena"
    }
  },
  "return_request_list": {
    "count": "Referenční číslo",
    "return_warranty": "Záruka vrácení peněz",
    "return_warranty_unit": "dny",
    "table": {
      "code": "Objednací kód",
      "product": "Produkt",
      "delivery_at": "Obdržené datum",
      "state": "Postavení",
      "reason": "Důvod",
      "return_warranty_period": "Záruční doba"
    }
  },
  "data_toolbar": {
    "search": "Vyhledávání",
    "sort_by": "Seřazeno podle",
    "count_item": "Zobrazit položky ({item})."
  },
  "sort": {
    "created_at": "Vytvořit datum",
    "updated_at": "Upravit datum",
    "title": "Titul",
    "description": "Popis",
    "like": "Popularita",
    "power": "tleská",
    "product_type": "Typ produktu",
    "discount": "Sleva",
    "rate": "Hodnocení",
    "rate_count": "Počet hodnocení",
    "category": "Kategorie",
    "product": "Produkt",
    "body": "Obsah",
    "card_type": "Typ karty",
    "card_number": "Číslo karty",
    "balance": "Zůstatek",
    "paid": "Utracená částka",
    "currency": "Měna",
    "expire_at": "Datum vypršení platnosti",
    "discount_code": "Slevový kód",
    "discount_percent": "Sleva",
    "discount_limit": "Slevový limit",
    "max_count": "Maximální počet",
    "used_count": "Použitý",
    "start_date": "Datum zahájení",
    "end_date": "Datum ukončení",
    "total_discount_amount": "Celkové slevy",
    "initial_charge": "Počáteční poplatek",
    "total_count": "Celkový součet",
    "amount_paid": "Částka vyplacená",
    "name": "název",
    "published": "Publikováno",
    "visits": "Návštěvy",
    "color": "Barva",
    "landing_page": "Vstupní stránka",
    "enable": "Umožnit",
    "fix_commission": "Pevná provize",
    "percent_commission": "Procentní provize",
    "payment_at": "Datum splatnosti",
    "issued_at": "Datum vydání",
    "payment": "Způsob platby",
    "website": "webová stránka",
    "email": "E-mailem",
    "user": "Uživatel",
    "code": "Kód",
    "schedule_at": "Termín rozvrhu",
    "sender": "Odesílatel",
    "in_que": "V řadě",
    "sent": "Odesláno",
    "shop": "Prodejna",
    "quantity": "Množství",
    "amount": "Množství",
    "jobs": "Práce se počítají",
    "success": "Úspěch se počítá",
    "fail": "Počet selhání",
    "distance": "Vzdálenost",
    "duration": "Doba trvání",
    "reset_at": "Resetovat datum",
    "delivery_person": "Osoba",
    "delivery_service": "Servis",
    "date": "datum",
    "order": "Objednat",
    "order_id": "číslo objednávky",
    "status": "Postavení",
    "price": "cena",
    "count": "Počet",
    "final_price": "Konečná cena",
    "charge": "Nabít",
    "mention": "Zmínit se",
    "officer": "Důstojník",
    "registered": "Registrovaný",
    "purchased": "Zakoupeno",
    "sex": "Rod"
  },
  "search_box": {
    "result": "Výsledky vyhledávání",
    "tips": "Hledat produkty a kategorie",
    "label": "Vyhledávání ...",
    "category": "Kategorie"
  },
  "lead_status": {
    "physical_fast_delivery": "Okamžité dodání",
    "physical_under_24h_delivery": "Doručte během následujících {lead} hodin",
    "physical_over_24h_delivery": "Příprava a odesílání od příštích {days} dnů",
    "virtual_fast_prepare": "Okamžité dodání",
    "virtual_under_24h": "Bude hotovo během následujících {lead} hodin",
    "virtual_over_24h": "Bude provedeno od příštích {days} dnů"
  },
  "return_request_state": {
    "pending": "čekající",
    "accepted": "Potvrzeno",
    "rejected": "Odmítnuto"
  },
  "return_order_reason": {
    "physical": {
      "U1": "Nesoulad produktu",
      "U2": "Žádný produkt v přepravním balíčku",
      "U3": "Rozbití obalu nebo produktu",
      "U4": "Manipulace s balíkem nebo sériovým číslem",
      "U5": "Některé položky ze zásilky chybí",
      "U6": "Produkt není originální",
      "U7": "Produkt nesplňuje specifikace"
    }
  },
  "image_uploader": {
    "label": "Drag & Drop nebo <u>Vyberte soubor</u>",
    "max_size": "Maximální povolená velikost: {size}"
  },
  "timespan": {
    "Morning": "8:00–12:00",
    "Evening": "od 12 do 18 hodin",
    "Night": "18:00–12:00",
    "Instant": "Okamžitá pošta"
  },
  "week_day": {
    "Saturday": "sobota",
    "Sunday": "Neděle",
    "Monday": "pondělí",
    "Tuesday": "úterý",
    "Wednesday": "středa",
    "Thursday": "Čtvrtek",
    "Friday": "pátek"
  },
  "payment_form": {
    "title": "Vyberte způsob platby",
    "gift_cards_input": "Dárkové poukázky",
    "gift_cards_input_empty": "Nebyly nalezeny žádné dárkové karty..",
    "more": "jiný",
    "pay_amount_by_gift_cards": "Platba kartou Charge",
    "select_payment_method": "Vyberte si způsob platby z následujících možností.",
    "payment_amount_remained": "Zbývající částka platby",
    "payment_amount": "Částka vyplacená",
    "all_paid_by_gift_cards": "Gratulujeme, za tuto objednávku nemusíte platit. Stiskněte tlačítko Zaplatit dárkovou kartou.",
    "pay_by_gift_cards_action": "Zaplaťte objednávku platební kartou",
    "order_free_payment": "Gratulujeme, vaše objednávka je zdarma!",
    "order_free_payment_action": "Objednejte si zdarma hned teď",
    "qr": {
      "address": "Platební adresa",
      "amount": "Množství"
    }
  },
  "discount_input": {
    "limit": "{percent}% sleva až do {limit} {currency}",
    "action": "Přidejte slevový kód",
    "code_input": "Slevový kód",
    "notifications": {
      "add_success": "Gratulujeme, platný slevový kód."
    }
  },
  "gift_card": {
    "inactive": "Karta je deaktivována",
    "expire": "Uplynutí",
    "transfer": "Převod",
    "send_to_friend": "Poslat kamarádovi"
  },
  "count_down": {
    "days": "Den",
    "hours": "Hodina",
    "minutes": "Minut",
    "seconds": "Sekundy"
  },
  "gift_status": {
    "Unpaid": "Čekání na potvrzení",
    "Paid": "Zaplaceno",
    "Rejected": "Odmítnuto",
    "Canceled": "Zrušeno"
  },
  "gift_program_status": {
    "Airdrop": "Platební systém",
    "Advertising": "Reklamní",
    "PersonalGift": "Osobní dárek",
    "ShopGift": "Dárkový obchod"
  },
  "currency_selector": {
    "label": "Měna"
  },
  "need_login": {
    "title": "přihlásit se",
    "login_sms": "SMS přihlášení",
    "login_google": "Přihlaste se pomocí Google",
    "login_facebook": "Přihlásit se pomocí Facebooku",
    "login_account": "Přihlášení přes Selldone",
    "register": "Nový uživatel? Zaregistrujte se nyní.",
    "mobile_input": "Zadejte svůj mobil",
    "verification_code": "Ověřovací kód",
    "msg_title": "Ahoj,",
    "msg_body": "Prosím přihlašte se. Zabere to jen pár sekund.",
    "login_apple": "Přihlaste se pomocí Apple",
    "login_email": "Přihlaste se emailem",
    "email_login_step_1": "Zadejte prosím platnou e-mailovou adresu a my na ni zašleme přihlašovací kód. Není nutná žádná registrace.",
    "email_login_step_2": "Jste si jisti, že jste svou e-mailovou adresu zadali správně? Přihlašovací kód zašleme na uvedený e-mail, dbejte proto prosím na jeho správnost.",
    "email_login_step_3": "Na váš e-mail jsme zaslali kód. Upozorňujeme, že platnost kódu vyprší za 10 minut."
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "5letý obchod se zlatem"
    },
    "GOLDEN_2YEAR": {
      "name": "4letý zlatý obchod"
    },
    "GOLDEN_3YEAR": {
      "name": "3letý zlatý obchod"
    },
    "GOLDEN_4YEAR": {
      "name": "2letý zlatý obchod"
    },
    "GOLDEN_5YEAR": {
      "name": "1 Year Gold Store"
    },
    "TOKEN_OWNER_1M": {
      "name": "Zlatý investor"
    },
    "TOKEN_OWNER_10M": {
      "name": "Diamantový investor"
    },
    "TOKEN_OWNER_100M": {
      "name": "Ruby Investor"
    },
    "COMMUNITY_LOYAL": {
      "name": "Člen vyšší komunity komunikačních sítí"
    },
    "GOLD_SUPPLIER": {
      "name": "Dodavatel zlata"
    },
    "GOLD_SELLER": {
      "name": "Prodejce zlata"
    },
    "CONTENT_SUPERMAN": {
      "name": "Nejlepší producent obsahu"
    },
    "NINJA": {
      "name": "Ninja"
    },
    "STAR": {
      "name": "Hvězda"
    },
    "GUARDIAN": {
      "name": "Skvělý zákaznický servis"
    },
    "KING": {
      "name": "Král trhu"
    }
  },
  "cookie": {
    "title": "Tento web používá soubory cookie",
    "message": "Tento web používá soubory cookie ke zlepšení uživatelské zkušenosti. Používáním našich webových stránek souhlasíte se všemi soubory cookie v souladu s našimi Zásadami používání souborů cookie.",
    "preferences_action": "Spravovat předvolby",
    "agree_action": "Souhlasím"
  },
  "basket_item_message": {
    "title": "Požadované informace pro tuto položku",
    "save_actions": "Uložit zprávu",
    "notifications": {
      "success": "Vaše vstupní data byla uložena."
    },
    "product_inputs_preview_message": "Tyto možnosti přizpůsobení jsou k dispozici pro váš objednaný produkt. Po přidání položky do košíku zde budete moci provést úpravy."
  },
  "faq": {
    "faq": "Často kladené otázky",
    "title": "Otázky a odpovědi",
    "sub_title": "O co jste nás požádali.",
    "message": "V níže uvedených odpovědích hledejte odpověď na svou otázku. Zeptejte se nás, pokud otázky zůstanou nezodpovězené.",
    "add_question_action": "Položte novou otázku",
    "read_more": "Přečtěte si více ..",
    "load_more": "Více otázek ..",
    "main_page": "Hlavní stránka FAQ",
    "add_new": "Odeslat novou otázku",
    "login_alert": "Chcete-li položit otázku, přihlaste se.",
    "question_input": "Otázka",
    "question_input_placeholder": "Zeptej se.",
    "notifications": {
      "success_add": "Váš dotaz byl úspěšně odeslán."
    }
  },
  "rating_labels": [
    "Velmi špatný",
    "Špatný",
    "Normální",
    "Dobrý",
    "Vynikající"
  ],
  "map_view": {
    "address_detail": "Podrobnosti adresy",
    "change": "Změna",
    "select": "Vybrat",
    "not_found_address": "Nebyla nalezena žádná hodnota",
    "enter_address_hint": "Zadejte cílovou adresu",
    "enter_your_address": "Zadejte svou adresu.",
    "postal_code": "PSČ",
    "phone_input": "Telefon {type}",
    "building_number": "Číslo budovy",
    "building_unit": "Jednotka",
    "full_name_input": "Celé jméno {type}",
    "save_detail_action": "Uložte podrobnosti",
    "more_detail_input": "Další popis",
    "add_address_to_list": "Přidat adresu do seznamu",
    "address_title_input": "Štítek adresy (vyžadovat)",
    "notifications": {
      "save_in_list": "Tato adresa byla uložena do vašeho seznamu se všemi podrobnostmi.",
      "edit_success": "Nové hodnoty adresy uložené v {title}."
    },
    "delete_address_dialog": {
      "title": "Smazat adresu",
      "message": "Opravdu chcete smazat tuto adresu?",
      "action": "Odebrat adresu"
    }
  },
  "comment_manager": {
    "can_not_edit": "Tento komentář nelze upravit!",
    "comment_input_empty": "Text zprávy je prázdný!",
    "article_not_saved": "Uložte článek!"
  },
  "wheel_fortune": {
    "title": "Play & Win",
    "message": "Cena každé hry je 10 žetonů. Aktuálně máte čip {chips}. Získejte více čipů nákupem v obchodě.",
    "win_message": "Gratulujeme, vyhráli jste!",
    "lost_message": "Promiň, prohrál jsi hru.",
    "try_again": "Můžete to zkusit znovu"
  },
  "json": {
    "add": "Přidejte data struktury",
    "add_message": "Vytvořte data nové struktury",
    "structures": "Struktury",
    "book": {
      "title": "Rezervovat",
      "desc": "Akce s knihami, které uživatelům umožňují koupit knihu, kterou naleznou přímo z výsledků vyhledávání."
    },
    "occupation": {
      "title": "Odhadovaný plat",
      "desc": "Informace o odhadu platu, jako jsou rozsahy platů a průměrné platy podle regionů pro typy pracovních míst, zobrazené při hledání práce na Googlu."
    },
    "course": {
      "title": "Chod",
      "desc": "Vzdělávací kurzy, které se zobrazují v seznamu konkrétních poskytovatelů. Kurzy mohou obsahovat název kurzu, poskytovatele a krátký popis."
    },
    "howto": {
      "title": "Jak",
      "desc": "Návod provede uživatele souborem kroků k úspěšnému dokončení úkolu, včetně videa, obrázků a textu."
    },
    "recipe": {
      "title": "Recept",
      "desc": "Recepty, které se zobrazují jako samostatný rozšířený výsledek nebo součást hostitelského karuselu."
    }
  },
  "support": {
    "Financial": "Finanční",
    "Technical": "Technický",
    "Advisor": "poradce"
  },
  "condition": {
    "new": "Nový",
    "refurbished": "Zrekonstruovaný",
    "used": "Použitý",
    "used_fair": "Použitý veletrh",
    "used_good": "Použité dobře",
    "used_like_new": "Použitý - jako nový"
  },
  "variant_filter": {
    "title": "Filtr variant produktu",
    "only_available": "Na skladě"
  },
  "service": {
    "task": {
      "title": "Úkoly",
      "message": "Seznam úkolů prováděných v této službě."
    },
    "appointment": {
      "title": "Jmenování",
      "message": "Vyberte si časy v týdnu z následujících časů podle dne a hodiny, která vám vyhovuje."
    },
    "booking": {
      "title": "Rezervace",
      "message": "V kalendáři níže zadejte časové období dnů, kdy chcete provést rezervaci."
    },
    "subscription": {
      "title": "Předplatné"
    },
    "charge": {
      "title": "Nabít"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "Pevná cena",
      "message": "V tomto typu cenotvorby je cena produktu pevná a není potřeba, aby kupující požadoval cenovou kalkulaci."
    },
    "ESTIMATION": {
      "title": "Odhadní ceny",
      "message": "Cena produktů a služeb bude do určité míry vypočítána prodávajícím při zadávání objednávky, platební faktury lze v průběhu služby měnit či doplňovat."
    },
    "AGREEMENT": {
      "title": "Cena dohodou",
      "message": "Konečná cena produktů nebo služeb nebude prodávajícím po provedení objednávky změněna."
    },
    "BID": {
      "title": "Příhoz / Aukce",
      "message": "Produkt bude potenciálními kupci prodán za nejvyšší nabídkovou cenu."
    }
  },
  "map": {
    "title": "Cíl pro příjem produktů",
    "confirm": "Nastavit umístění",
    "address": "Destinace",
    "receptor": "Přijímač"
  },
  "ShopBots": {
    "telegram": "Telegram"
  },
  "article_tags": {
    "title": "Obsahové značky",
    "tags_input": "Tagy",
    "tags_input_message": "Tagy Seznam tohoto článku",
    "notification": {
      "add_success": "Štítky přidány"
    }
  },
  "difficulties": {
    "very_complicated": "Velmi komplikované",
    "hard": "Tvrdý",
    "intermediate": "středně pokročilí",
    "easy": "Snadný"
  },
  "billing_period": {
    "Daily": "Denně",
    "Weekly": "Týdně",
    "Monthly": "Měsíční",
    "Every3Months": "Každé 3 měsíce",
    "Every6Months": "Každých 6 měsíců",
    "Yearly": "Roční"
  },
  "buyer_rating_statement": {
    "between1_2": "Och to není dobré!",
    "between2_3": "To je v pořádku!",
    "between3_4": "Lidem se to líbí!",
    "between4_5": "Lidé to milují!"
  }
};