export default {
  "currency_default": "USD",
  "language_default": "en",
  "selldone": "Πωλείται",
  "store": "κατάστημα",
  "not_exist": "Δεν υπάρχει",
  "error": "Λάθος",
  "active": "Ενεργός",
  "inactive": "αδρανής",
  "required_value": "Απαιτούμενες τιμές",
  "original_warranty": "Αρχική εγγύηση προϊόντος",
  "return_warranty_days": "{days} ημέρες εγγύησης επιστροφής",
  "no_return_warranty": "Χωρίς επιστροφή",
  "reed_agree_terms": "Έχω διαβάσει τους όρους χρήσης και την πολιτική απορρήτου και συμφωνώ μαζί τους.",
  "commons": {
    "Currency": "Νόμισμα",
    "COD": "COD",
    "State": "κατάσταση",
    "Price": "τιμή",
    "order_price": "Ποσό παραγγελίας",
    "VAT": "VAT",
    "Discount": "Εκπτωση",
    "In_Stock": "Σε απόθεμα",
    "Variants": "Παραλλαγές",
    "No_variants": "Καμία παραλλαγή",
    "all": "ΟΛΑ",
    "today": "Σήμερα",
    "yesterday": "Εχθές",
    "license": "Αδεια",
    "home": "Σπίτι",
    "support": "Υποστήριξη",
    "messages": "Μηνύματα",
    "no_message": "Ούτε ένα μήνυμα",
    "empty": "Αδειάζω",
    "phone": "Τηλέφωνο",
    "address": "διεύθυνση",
    "name": "Ονομα",
    "password": "Κωδικός πρόσβασης",
    "email": "ΗΛΕΚΤΡΟΝΙΚΗ ΔΙΕΥΘΥΝΣΗ",
    "mobile": "Κινητό",
    "login": "Σύνδεση",
    "register": "Κανω ΕΓΓΡΑΦΗ",
    "select_account": "Επιλέξτε λογαριασμό",
    "online": "Σε σύνδεση",
    "offline": "Εκτός σύνδεσης",
    "finish": "Φινίρισμα",
    "finished": "Πεπερασμένος",
    "preview": "Προεπισκόπηση",
    "free": "Ελεύθερος",
    "free_completely": "Εντελώς δωρεάν συνδρομή",
    "fee": "Τέλη",
    "month": "Μήνας",
    "months": "Μήνες",
    "faq": "Συχνές Ερωτήσεις",
    "question": "Ερώτηση",
    "answer": "Απάντηση",
    "create_date": "Ημερομηνία δημιουργίας",
    "update_date": "Ημερομηνία ενημέρωσης",
    "start_date": "Ημερομηνία έναρξης",
    "end_date": "Ημερομηνία λήξης",
    "social": "Κοινωνικός",
    "total": "Σύνολο",
    "orders": "Παραγγελίες",
    "sessions": "Συνεδρίες",
    "product_views": "Προβολές προϊόντων",
    "add_to_carts": "Προσθήκη στα καλάθια",
    "checkouts": "ολοκλήρωση παραγγελίας",
    "payments": "Πληρωμή",
    "organic_search": "Οργανική αναζήτηση",
    "other": "Αλλα",
    "landing_page": "Σελίδα προορισμού",
    "discount_code": "Κωδικός έκπτωσης",
    "total_sell": "Συνολικές πωλήσεις",
    "details": "Λεπτομέριες",
    "currency": "Νόμισμα",
    "amount": "Ποσό",
    "published": "Δημοσίευσε",
    "draft": "Προσχέδιο",
    "save_changes": "Αποθήκευσε τις αλλαγές",
    "source": "Πηγή",
    "medium": "Μεσαίο",
    "url": "Url",
    "revenue": "Εσοδα",
    "performance": "Εκτέλεση",
    "term": "Ορος",
    "content": "Περιεχόμενο",
    "session": "Συνεδρίαση",
    "product": "Προϊόν",
    "add": "Προσθήκη",
    "checkout": "ολοκλήρωση παραγγελίας",
    "payment": "Πληρωμή",
    "more_options": "Περισσότερες επιλογές",
    "full_name": "Πλήρες όνομα",
    "tel": "Τηλ",
    "about_me": "Σχετικά με μένα",
    "request_checking": "Ζητήστε έλεγχο",
    "passport": "Διαβατήριο",
    "birthday": "Γενέθλια",
    "country": "Χώρα",
    "city": "Πόλη",
    "gender": "Γένος",
    "offer": "Προσφορά",
    "website": "Δικτυακός τόπος",
    "apply_for_all_products": "∞ Αίτηση για όλα τα προϊόντα",
    "fix_commission": "Σταθερή προμήθεια",
    "percent_commission": "Ποσοστό προμήθειας",
    "fixed_discount": "Σταθερή έκπτωση",
    "discount_percentage": "Ποσοστό έκπτωσης",
    "discount_limit": "Όριο έκπτωσης",
    "no_code": "Χωρίς κωδικό",
    "max_count": "Μέγιστο πλήθος",
    "count_unit": "Είδη",
    "used": "Μεταχειρισμένος",
    "daily": "Καθημερινά",
    "monthly": "Μηνιαίο",
    "yearly": "Ετήσια",
    "state": "Κατάσταση",
    "disable": "Καθιστώ ανίκανο",
    "enable": "επιτρέπω",
    "activation_code": "Κωδικός ενεργοποίησης",
    "quantity": "Ποσότητα",
    "no_club": "Κανένας σύλλογος",
    "per_order": "Ανά παραγγελία",
    "count": "μετρώ",
    "seconds": "Δευτερόλεπτα",
    "auto": "Αυτο",
    "title": "Τίτλος",
    "message": "Μήνυμα",
    "width": "Πλάτος",
    "length": "Μήκος",
    "height": "Υψος",
    "label": "Επιγραφή",
    "click": "Κάντε κλικ",
    "bank": "Τράπεζα",
    "default": "Προκαθορισμένο",
    "role": "Ρόλος",
    "user": "Χρήστης",
    "users": "Χρήστες",
    "code": "Κώδικας",
    "total_payment": "Συνολική πληρωμή",
    "balance": "Ισορροπία",
    "chance": "Ευκαιρία",
    "free_for_new_users": "Δωρεάν για νέους χρήστες",
    "prize_amount": "Ποσό βραβείου",
    "win": "Νίκη",
    "gift_card": "Δωροκάρτα",
    "discount": "Εκπτωση",
    "config": "Διαμόρφωση",
    "prize": "Βραβείο",
    "Prizes": "βραβεία",
    "result": "Αποτέλεσμα",
    "price": "τιμή",
    "lottery": "Λαχείο",
    "coupon": "Κουπόνι",
    "customer_club": "Λέσχη Πελατών",
    "shipping": "Αποστολή",
    "sum": "Αθροισμα",
    "not_paid": "Απληρωτος",
    "category": "Κατηγορία",
    "done": "Εγινε",
    "email_from": "Από",
    "subject": "Θέμα",
    "schedule": "Πρόγραμμα",
    "files_list": "Λίστα αρχείων",
    "file_max_size": "Μέγιστο μέγεθος αρχείου",
    "value": "αξία",
    "help": "Βοήθεια",
    "shipping_tax": "Φόρος αποστολής",
    "net_price": "Καθαρή τιμή",
    "tax": "Φόρος",
    "tax_included": "Περιλαμβάνεται στην τιμή",
    "limit": "Οριο",
    "min_purchase": "Ελάχιστη αγορά",
    "eligible_for": "Κατάλληλο για",
    "only_for_first_buy": "Μόνο για πρώτη αγορά",
    "one_time_use": "Μπορεί να χρησιμοποιηθεί μία φορά",
    "period_of_qualify": "Όριο χρήσης περιόδου",
    "no_constraint": "Κανένα όριο",
    "timespan": "Χρονικό διάστημα",
    "days": "Μέρες)",
    "weight": "Βάρος",
    "distance": "Απόσταση",
    "last_status": "Τελευταία κατάσταση",
    "issued_at": "Που εκδίδονται σε",
    "order": "Σειρά",
    "order_detail": "Λεπτομέρειες Παραγγελίας",
    "percent": "Τοις εκατό",
    "applied_count": "Εφαρμοσμένο πλήθος",
    "campaign": "καμπάνια",
    "os": "Λειτουργικό σύστημα",
    "browser": "Πρόγραμμα περιήγησης",
    "device": "Συσκευή",
    "device_ip": "Διεύθυνση IP συσκευής",
    "location": "Τοποθεσία",
    "user_agent": "Πράκτορας χρήστη",
    "affiliate": "Υιοθετώ",
    "timeline": "Χρονοδιάγραμμα",
    "add_note": "Προσθήκη σημείωσης",
    "record": "Ρεκόρ",
    "unlimited": "Απεριόριστος",
    "show_coupons": "Εμφάνιση κουπονιών",
    "hide_coupons": "Απόκρυψη κουπονιών",
    "service_area": "Χώρος εξυπηρέτησης",
    "apps": "Εφαρμογές",
    "plugins": "Πρόσθετα",
    "bots": "Bots",
    "categories": "Κατηγορίες",
    "products": "Προϊόντα",
    "business": "Επιχείρηση",
    "personal": "Προσωπικός",
    "size": "Μέγεθος",
    "holiday": "Αργία",
    "sod": "Πληρωμή κατά την παράδοση",
    "cod": "Με αντικαταβολή",
    "free_shipping": "Δωρεάν αποστολή",
    "hours": "Ωρες",
    "send_date": "Ημερομηνία αποστολής",
    "deliver_date": "Ημερομηνία παράδοσης",
    "return_date": "Ημερομηνία επιστροφής",
    "pending": "εκκρεμής",
    "delivered": "Παραδόθηκε",
    "returned": "Επέστρεψαν",
    "canceled": "Ακυρώθηκε",
    "shipping_cost": "Κόστος αποστολής",
    "action": "Δράση",
    "cancel_date": "Ημερομηνία ακύρωσης",
    "deliver_in_process": "Η παραγγελία αποστέλλεται..",
    "kind": "Τύπος",
    "detail": "Λεπτομέριες",
    "map": "Χάρτης",
    "actions": "Ενέργειες",
    "navigation": "Πλοήγηση",
    "navigation_app": "Εφαρμογή",
    "payment_date": "Ημερομηνία πληρωμής",
    "duration": "Διάρκεια",
    "bill": "Νομοσχέδιο",
    "delivery_persons": "Ταχυμεταφορείς",
    "delivery_services": "Υπηρεσίες παράδοσης",
    "live_view": "Ζωντανή μετάδοση",
    "cart": "Καροτσάκι",
    "priority": "Προτεραιότητα",
    "sufficient_credit": "Επαρκής πίστωση",
    "max_package_size": "Μέγιστο μέγεθος συσκευασίας",
    "delay": "Καθυστέρηση",
    "credit": "Πίστωση",
    "livemode": "Ζω",
    "paused": "Σε παύση",
    "debug": "Εντοπισμός σφαλμάτων",
    "token": "Ενδειξη",
    "status": "Κατάσταση",
    "courier": "Μεταφορέας",
    "track": "Πίστα",
    "track_order": "Εντοπισμός παραγγελίας",
    "cost": "Κόστος",
    "receipt": "Παραλαβή",
    "origin": "Προέλευση",
    "destination": "Προορισμός",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "Δεν υπάρχει αρκετό απόθεμα!",
    "sub_total": "ΜΕΡΙΚΟ ΣΥΝΟΛΟ",
    "customer": "Πελάτης",
    "delivery": "Διανομή",
    "online_orders": "Διαδικτυακές Παραγγελίες",
    "pos_orders": "Παραγγελίες POS",
    "chips": "Τσιπς",
    "subscribed": "Εγγεγραμμένος",
    "unsubscribed": "Καταργήθηκε η εγγραφή",
    "last_login": "Τελευταία είσοδος",
    "join_at": "Ημερομηνία προσχώρησης",
    "club": "Λέσχη",
    "buyer": "Αγοραστής",
    "seller": "Πωλητής",
    "or": "Ή",
    "type": "Τύπος",
    "condition": "Κατάσταση",
    "brand": "Μάρκα",
    "attempt": "Απόπειρα",
    "error": "Λάθος",
    "success": "Επιτυχία",
    "fail": "Αποτυγχάνω",
    "inventory": "Καταγραφή εμπορευμάτων",
    "link": "Σύνδεσμος",
    "visits": "Επισκέψεις",
    "transactions": "Συναλλαγές",
    "vat": "VAT",
    "pos_vat": "POS ΦΠΑ",
    "sort_by": "Ταξινόμηση κατά..",
    "from": "Από",
    "from_lead_time": "Μέσα στις επόμενες {hours} ώρες",
    "no_credit_card_info": "Δεν υπάρχουν πληροφορίες κάρτας!",
    "active": "Ενεργός",
    "not_active": "Μη ενεργοποιημένο!",
    "referrals": "Παραπομπές",
    "dashboard": "Ταμπλό",
    "more": "Περισσότερο",
    "inactive": "αδρανής",
    "developer": "Προγραμματιστής",
    "setting": "Σύνθεση",
    "membership_conditions": "Προϋποθέσεις μέλους",
    "customers": "Οι πελάτες",
    "created_at": "Ημερομηνία δημιουργίας",
    "updated_at": "Τελευταία ενημέρωση",
    "register_at": "Ημερομηνία εγγραφής",
    "old": "Παλαιός",
    "new": "Νέος",
    "start": "Αρχή",
    "end": "Τέλος",
    "pos": "POS",
    "out_of_stock": "Εκτός αποθέματος",
    "fake": "Απομίμηση",
    "low_inventory_warning": "Προσοχή, Χαμηλό απόθεμα!",
    "webhook": "Webhook",
    "notification": "Γνωστοποίηση",
    "sms": "SMS",
    "online_payment_link": "Σύνδεσμος ηλεκτρονικής πληρωμής",
    "waiting_load_data": "Αναμονή για φόρτωση δεδομένων..",
    "views": "Προβολές",
    "sales": "Εκπτώσεις",
    "total_views": "Συνολικές προβολές",
    "total_sales": "Συνολικές πωλήσεις",
    "from_previous_n_days": "Από τις τελευταίες {days} ημέρες",
    "drop_shipping": "Η ναυτιλία πτώσης",
    "commission": "Επιτροπή",
    "shipping_area": "Χώρος αποστολής",
    "main_seller": "Κύριος πωλητής",
    "domain": "Τομέα",
    "contact": "Πληροφορίες επαφής",
    "wallet": "Πορτοφόλι",
    "reseller": "Μεταπωλητής",
    "tracking_code": "Κώδικας παρακολούθησης",
    "tracking_url": "URL παρακολούθησης",
    "fulfillments": "Εκπληρώσεις",
    "reject": "Απορρίπτω",
    "reserved": "Κατοχυρωμένα",
    "score": "Σκορ",
    "customer_price": "Τιμή πελάτη",
    "options": "Επιλογές",
    "show_details": "Δείξε λεπτομέρειες",
    "no_data": "Χωρίς δεδομένα..",
    "waiting": "Αναμονή...",
    "waiting_connecting_payment": "Αναμονή για την υπηρεσία πληρωμών...",
    "creating_secure_payment": "Δημιουργία ασφαλούς πληρωμής.",
    "officer": "Αξιωματικός",
    "ticket": "Εισιτήριο",
    "ticket_url": "Διεύθυνση URL εισιτηρίου",
    "closed_at": "Κλειστό στις",
    "close_ticket": "Κλείσιμο εισιτηρίου",
    "reopen_ticket": "Ανοίξτε ξανά το εισιτήριο",
    "require": "Απαιτώ*",
    "search": "Αναζήτηση...",
    "language": "Γλώσσα",
    "tasks": "Καθήκοντα",
    "permissions": "Άδειες",
    "finish_date": "Ημερομηνία λήξης",
    "complete_date": "Ημερομηνία ολοκλήρωσης",
    "settle_date": "Ημερομηνία διακανονισμού",
    "cost_span": "Εύρος τιμών",
    "industry": "Βιομηχανία",
    "rating": "Ακροαματικότητα",
    "rates": "Εκτίμηση",
    "seen_at": "Βλέπεται στο",
    "completed": "Ολοκληρώθηκε το",
    "you": "Εσύ",
    "shop": "Κατάστημα",
    "store": "κατάστημα",
    "granted": "Χορηγείται",
    "deny": "Αρνούμαι",
    "request": "Αίτηση",
    "expert": "Ειδικός",
    "response": "Απάντηση",
    "requests": "Αιτήσεων",
    "experts": "Ειδικοί",
    "responses": "Απαντήσεις",
    "negotiations": "Διαπραγματεύσεις",
    "all_chats": "Όλες οι συνομιλίες",
    "chats": "Συνομιλίες",
    "tags": "Ετικέτες",
    "description": "Περιγραφή",
    "rates_count": "Αριθμός βαθμολογιών",
    "rate": "Εκτίμηση",
    "comment": "Σχόλιο",
    "chat": "Κουβέντα",
    "install": "Εγκαθιστώ",
    "edited": "Επεξεργάστηκε",
    "undo": "Ξεκάνω",
    "redo": "Ξανακάνω",
    "male": "Αρσενικός",
    "female": "Θηλυκός",
    "calculator": "Αριθμομηχανή",
    "catalog": "Κατάλογος",
    "max_height": "Μέγιστο ύψος",
    "images_compare": "Σύγκριση εικόνων",
    "canvas": "Καμβάς",
    "table_of_contents": "Πίνακας περιεχομένων",
    "comments": "Σχόλια",
    "badge_codes": "Κωδικός σημάτων",
    "need_more": "Χρειάζομαι περισσότερο?",
    "invite_glow_caption": "Πάρτε 14,9$ για κάθε φίλο!",
    "register_free": "100% Δωρεάν εγγραφή",
    "gift": "Δώρο",
    "google": "Google",
    "facebook": "Facebook",
    "instagram": "Ίνσταγκραμ",
    "instashop": "Instashop",
    "show": "προβολή",
    "hide": "Κρύβω",
    "waiting_review": "Αναμονή αναθεώρησης",
    "not_selected": "Μη επιλεγμένο",
    "time": "χρόνος",
    "final_price": "Τελική τιμή",
    "starting_price": "Αρχική τιμή",
    "day": "Ημέρα",
    "paid": "επί πληρωμή",
    "service_bill": "Πληρωμή τιμολογίου",
    "avocado": "Αβοκάντο",
    "delivery_price": "Κόστος αποστολής",
    "select_address": "Επιλέξτε διεύθυνση",
    "image": "Εικόνα",
    "view": "Θέα",
    "sell": "Πώληση",
    "hyper": "Υπερπληθωρισμός",
    "cart_list": "Καροτσάκι",
    "barcode_scanner": "Σάρωση γραμμοκώδικα",
    "scan_qr_code": "Σάρωση κωδικού QR",
    "new_carts": "Νέα καρότσια",
    "pays": "Πληρωμές",
    "annually": "Ετησίως",
    "sells": "Εκπτώσεις",
    "articles": "Άρθρα",
    "jobs": "Θέσεις εργασίας",
    "job": "Δουλειά",
    "blog": "Ιστολόγιο",
    "deleted_at": "Διαγράφηκε στις",
    "capacity": "Χωρητικότητα",
    "download_at": "Ημερομηνία τελευταίας λήψης",
    "downloads": "Λήψεις",
    "usage": "Χρήση",
    "select_upload_file": "Επιλέξτε ή αποθέστε αρχείο",
    "download_link": "Σύνδεσμος λήψης",
    "uploading": "Μεταφόρτωση..",
    "files": "Αρχεία",
    "star": "Αστέρι",
    "speed": "Ταχύτητα",
    "feedback": "Ανατροφοδότηση",
    "new_messages": "Νέα μηνύματα",
    "file": "Αρχείο",
    "attachment": "Συνημμένο",
    "gallery": "Εκθεσιακός χώρος",
    "sync": "Συγχρονισμός",
    "diff_time": "Διαφορά ώρας",
    "network": "Δίκτυο",
    "account": "λογαριασμός",
    "configuration": "Διαμόρφωση",
    "blockchain": "Blockchain",
    "blog_link": "Σύνδεσμος ιστολογίου",
    "community": "Κοινότητα",
    "critical_zone": "Κρίσιμη ζώνη",
    "statistics": "Στατιστική",
    "access": "Πρόσβαση",
    "seo": "SEO",
    "followers": "Οπαδοί",
    "followings": "Ακολουθούν",
    "private": "Προεπισκόπηση",
    "soon": "Σύντομα",
    "features": "Χαρακτηριστικά",
    "bot": "Bot",
    "sample": "Δείγμα",
    "how_it_work": "Πώς λειτουργεί;",
    "page": "Σελίδα",
    "congratulations": "Συγχαρητήρια",
    "recommend": "Συνιστώ",
    "recommended": "Συνιστάται",
    "recoms": "συστάσεις",
    "likes": "Μου αρέσει",
    "clicks": "Κλικ",
    "platform": "Πλατφόρμα",
    "cms": "CMS",
    "cash": "Μετρητά",
    "dir_payment": "τραπεζική μεταφορά",
    "auto_complete": "Αυτόματη ολοκλήρωση",
    "compare": "Συγκρίνω",
    "infinite": "Απειρος",
    "tips": "Συμβουλές",
    "technical": "Τεχνικός",
    "finance": "Χρηματοδότηση",
    "your_phone_input": "Εισάγετε αριθμό τηλεφώνου",
    "income": "Εισόδημα",
    "change": "Αλλαγή",
    "new_users": "Νέοι χρήστες",
    "success_orders": "Επιτυχείς παραγγελίες",
    "direct": "Απευθείας",
    "last_activity": "Τελευταία δραστηριότητα",
    "landing": "Προσγείωση",
    "now": "Τώρα",
    "accept_agreement": "Έχω διαβάσει και αποδέχομαι τους όρους.",
    "report": "Κανω ΑΝΑΦΟΡΑ",
    "tablet": "Δισκίο",
    "pc": "PC",
    "acquisition_channel": "Κανάλι απόκτησης",
    "to": "Προς την",
    "info": "Πληροφορίες",
    "general": "Γενικός",
    "upload": "Μεταφόρτωση",
    "general_config": "Γενική διαμόρφωση",
    "limits_config": "Περιορισμοί",
    "design_config": "Σχέδιο & Στυλ",
    "duration_config": "Όριο διάρκειας",
    "constraints_config": "Όρια επιλεξιμότητας",
    "clubs_config": "Διαθέσιμο σε Clubs",
    "additional_config": "Πρόσθετες ρυθμίσεις παραμέτρων",
    "import": "Εισαγωγή",
    "ribbon": "Ταινία",
    "countries": "Χώρες",
    "edit": "Επεξεργασία",
    "delete": "Διαγράφω",
    "analytics": "Analytics",
    "rules": "Κανόνες",
    "unset": "Δεν ρυθμίστηκε",
    "carts": "Καρότσια",
    "optional": "Προαιρετικός",
    "design": "Σχέδιο",
    "filter": "Φίλτρο",
    "send": "Στείλετε",
    "approved": "Εγκρίθηκε",
    "unit": "Μονάδα",
    "profile": "Προφίλ",
    "shipping_rates": "Τιμές αποστολής",
    "package": "Πακέτο",
    "overview": "ΣΦΑΙΡΙΚΗ ΕΙΚΟΝΑ",
    "live": "Ζω",
    "never": "Ποτέ",
    "always": "Πάντα",
    "mandatory": "Επιτακτικός",
    "expire_at": "Ημερομηνία λήξης",
    "position": "Θέση",
    "channel": "Κανάλι",
    "age": "Ηλικία",
    "charge": "Χρέωση",
    "giftcard": "Δωροκάρτα",
    "acquisition": "Απόκτηση",
    "conversion": "Μετατροπή",
    "total_payments": "Συνολικές πληρωμές",
    "community_ask": "Ρωτήστε στην κοινότητα",
    "children": "Παιδιά",
    "export": "Εξαγωγή",
    "list": "Λίστα",
    "hierarchy": "Ιεραρχία",
    "images": "εικόνες",
    "demo": "Διαδήλωση",
    "author": "Συγγραφέας",
    "designer": "Σχεδιαστής",
    "max": "Το μέγιστο",
    "accepted": "Δεκτός",
    "reply": "Απάντηση",
    "reviewed": "Αξιολογήθηκε",
    "restored": "Ανακαινισμένο",
    "merchant": "Εμπορος",
    "per_product": "Ανά προϊόν",
    "journey": "Ταξίδι",
    "after": "Μετά",
    "waiting_for_payment": "Παρακαλώ ολοκληρώστε την πληρωμή...",
    "hour": "Ωρα",
    "minute": "Λεπτό",
    "premium": "Ασφάλιστρο",
    "light": "Φως",
    "dark": "Σκοτάδι",
    "guest": "Επισκέπτης",
    "shops": "Προμήθεια",
    "vendor": "Προμηθευτή",
    "vendors": "Πωλητές",
    "marketplace": "Αγορά",
    "verify_date": "Επαλήθευση ημερομηνίας",
    "note": "Σημείωση",
    "panel": "Πίνακας",
    "removed": "Καταργήθηκε",
    "segments": "Τμήματα",
    "personal_info": "Προσωπικές πληροφορίες",
    "preferences": "Προτιμήσεις",
    "spec": "Spec",
    "reviews": "Κριτικές",
    "constraints": "Περιορισμοί",
    "flexible": "Εύκαμπτος",
    "usage_limit": "Όριο χρήσης",
    "temporary": "Προσωρινός",
    "original": "Πρωτότυπο",
    "saved": "Αποθηκεύτηκε!",
    "sort": "Είδος",
    "documents": "Εγγραφα",
    "document": "Εγγραφο",
    "please_wait": "Παρακαλώ περιμένετε...",
    "pickup": "Μαζεύω",
    "customize": "προσαρμόστε",
    "difficulty": "Δυσκολία",
    "banned": "Απαγορευμένος",
    "company": "Εταιρία",
    "tax_shipping": "Φόρος αποστολής",
    "warranty": "Εγγύηση",
    "return_policy": "ΠΟΛΙΤΙΚΗ ΕΠΙΣΤΡΟΦΗΣ ΠΡΟΪΟΝΤΩΝ",
    "guide": "Οδηγός",
    "translate": "Μεταφράζω",
    "public": "Δημόσιο",
    "deleted": "Διαγράφηκε",
    "variant": "Παραλαγή",
    "secure": "Ασφαλής",
    "admin": "διαχειριστής",
    "tax_included_abstract": "συμπεριλαμβανομένου",
    "payment_not_settled": "Η πληρωμή δεν διευθετήθηκε!",
    "orders_list": "Λίστα παραγγελιών",
    "subscription_plan": "Πρόγραμμα συνδρομής",
    "contents": "Περιεχόμενα",
    "pricings": "Τιμές",
    "static_page": "Στατική σελίδα",
    "shop_button": "Κουμπί καταστήματος",
    "embed": "Ενθέτω",
    "over": "Πάνω από",
    "tax_vary_by_location": "ποικίλλω. τοποθεσία",
    "product_type": "Τύπος Προϊόντος",
    "tax_id": "Τον αριθμό φορολογικού μητρώου",
    "business_name": "Επωνυμία Επιχείρησης",
    "invoice": "Τιμολόγιο",
    "included_in_the_product": "Περιλαμβάνεται στο προϊόν",
    "included_in_the_product_description": "Το προϊόν περιλαμβάνει τα ακόλουθα συστατικά",
    "cross_sell": "Cross Sell",
    "discount_off": "OFF",
    "extra_discount": "Επιπλέον Έκπτωση",
    "template": "Πρότυπο",
    "in_cart": "Στο καλάθι",
    "pros_and_cons": "Υπέρ και κατά",
    "related_products": "Σχετικά προϊόντα",
    "related_categories": "Σχετικές Κατηγορίες",
    "badges": "Σήματα",
    "explore": "Εξερευνώ"
  },
  "dialogs": {
    "delete": {
      "title": "Διαγράφω",
      "message": "Είστε βέβαιοι ότι θα διαγράψετε αυτό το στοιχείο;",
      "action": "Ναι, Διαγραφή τώρα"
    }
  },
  "actions": {
    "add_to_cart": "Προσθήκη στο καλάθι",
    "cancel": "Ματαίωση",
    "update": "Εκσυγχρονίζω",
    "add": "Προσθήκη",
    "delete": "Διαγράφω",
    "new": "Νέος",
    "save_continue": "Αποθήκευση & Συνέχεια",
    "save": "Σώσει",
    "save_changes": "Αποθήκευσε τις αλλαγές",
    "change": "Αλλαγή",
    "continue": "Να συνεχίσει",
    "close": "Κλείσε",
    "finish": "Φινίρισμα",
    "poll": "Ψηφοφορία",
    "view": "Θέα",
    "edit": "Επεξεργασία",
    "next": "Επόμενο",
    "previous": "Προηγούμενος",
    "create": "Δημιουργώ",
    "set": "σειρά",
    "find": "Εύρημα",
    "accept": "Αποδέχομαι",
    "reject": "Απορρίπτω",
    "back": "Πίσω",
    "pay": "Πληρωμή",
    "pay_now": "Πλήρωσε τώρα",
    "print": "Τυπώνω",
    "return": "ΕΠΙΣΤΡΟΦΗ",
    "publish": "Δημοσιεύω",
    "confirm": "Επιβεβαιώνω",
    "copy": "αντίγραφο",
    "submit": "υποβάλλουν",
    "send": "Στείλετε",
    "yes": "Ναί",
    "no": "όχι",
    "meh": "Χμμ",
    "clear": "Σαφή",
    "dismiss": "Απολύω",
    "search": "Αναζήτηση",
    "deselect_all": "Αποεπιλογή όλων",
    "select_all": "Επιλογή όλων",
    "refresh": "Φρεσκάρω",
    "verify": "Επαληθεύω",
    "play": "Παίζω",
    "open": "Ανοιξε",
    "calculate": "Υπολογίζω",
    "quick_buy": "Γρήγορη Αγορά",
    "click_here": "Κάντε κλικ ΕΔΩ",
    "schedule": "Πρόγραμμα",
    "send_now": "Στειλε τωρα",
    "download": "Κατεβάστε",
    "reset_default": "Επαναφορά στο προκαθορισμένο",
    "reset": "Επαναφορά",
    "check": "Ελεγχος",
    "cod_payment": "Με αντικαταβολή",
    "dir_payment": "Μεταφορά χρημάτων",
    "online_payment": "Διαδικτυακή πληρωμή",
    "checkout": "ολοκλήρωση παραγγελίας",
    "show_all": "Προβολή όλων",
    "login": "Σύνδεση",
    "logout": "Αποσύνδεση",
    "more": "Περισσότερο..",
    "collapse": "Κατάρρευση",
    "apply_change": "Εφαρμόστε αλλαγές",
    "apply": "Ισχύουν",
    "add_giftcard": "Προσθήκη δωροκάρτας",
    "charge": "Χρέωση",
    "send_invites": "Στείλε προσκλήσεις",
    "past": "Το παρελθόν",
    "restore": "Επαναφέρω",
    "cut": "Τομή",
    "get_sms_code": "Λάβετε κωδικό ελέγχου ταυτότητας",
    "register_no_mail": "Συνέχεια χωρίς email",
    "no_mail_register_message": "Δεν έχετε διεύθυνση email ή ξεχάσατε τον κωδικό πρόσβασής σας;",
    "reset_by_mail": "Ανάκτηση κωδικού πρόσβασης μέσω email",
    "reset_by_sms": "Ανάκτηση κωδικού πρόσβασης μέσω SMS",
    "cash_payment": "Πληρωμή με μετρητά",
    "show_chart": "Εμφάνιση γραφήματος",
    "open_app": "Ανοίξτε την εφαρμογή",
    "login_now": "Συνδεθείτε τώρα",
    "watch_video": "Δες το βίντεο",
    "check_now": "Ελέγξτε τώρα",
    "remove_image": "Αφαίρεση εικόνας",
    "view_website": "Ανοίξτε σύνδεσμο",
    "explore": "Εξερευνήστε το {name}",
    "go": "Πηγαίνω",
    "read_more": "Διαβάστε περισσότερα",
    "start_now": "Ξεκινήστε τώρα — Είναι δωρεάν",
    "view_live": "Δείτε ζωντανά",
    "resend_code": "Ξαναστείλε τον κωδικό",
    "invite": "Καλώ",
    "add_more": "Πρόσθεσε περισσότερα",
    "install_now": "Εγκατάσταση τώρα",
    "uninstall": "Απεγκατάσταση",
    "show_preview": "Εμφάνιση προεπισκόπησης",
    "hide_preview": "Απόκρυψη προεπισκόπησης",
    "download_now": "Κατεβάστε τώρα",
    "auto_fill": "Αυτόματη συμπλήρωση",
    "track": "Πίστα",
    "change_state": "Αλλαγή κατάστασης",
    "done": "Εγινε",
    "reply": "Απάντηση",
    "watch_now": "Παρακολουθήσετε τώρα",
    "unlock": "Ξεκλείδωμα",
    "lock": "Κλειδαριά",
    "create_clone": "Δημιουργία κλώνου",
    "regenerate": "Αναγεννηθείς",
    "add_message": "Πρόσθεσε μήνυμα",
    "continue_chat": "Συνεχίστε τη συνομιλία",
    "add_new_message": "Προσθήκη νέου μηνύματος",
    "change_setting": "Αλλαγή ρύθμισης",
    "delete_all": "Διαγραφή όλων",
    "transfer_fund": "Ταμείο μεταφοράς",
    "reverse_fund": "Αντίστροφο κεφάλαιο",
    "settlement": "Επίλυση",
    "refund": "Επιστροφή χρημάτων",
    "partial_refund": "Μερική αποζημίωση",
    "change_payment_method": "ΑΛΛΑΓΗ μεθόδου πληρωμής",
    "buy": "Αγορά",
    "view_all": "Προβολή όλων",
    "view_now": "Προβολή τώρα"
  },
  "instance_message_title": "Αποστολή άμεσου μηνύματος",
  "instance_message": "Γεια σας {name}, Το όνομά μου είναι {author} από την {company}.",
  "errors": {
    "419": "Είστε ανενεργοί για μεγάλο χρονικό διάστημα, <b>⟳ ΑΝΑΝΕΩΣΤΕ ΤΗ ΣΕΛΙΔΑ</b> για λόγους ασφαλείας.",
    "gateway_blockchain_sync_error": "Το σύστημα δεν συγχρονίζεται με το blockchain. Δεν θα είναι δυνατή η δημιουργία νέας συναλλαγής μέχρι να ολοκληρωθούν οι συγχρονισμοί των διακομιστών μας. Λύνουμε το πρόβλημα.",
    "gateway_network_error": "Η υπηρεσία πύλης πληρωμής αντιμετώπισε πρόβλημα επικοινωνίας."
  },
  "receiver_info": {
    "map": {
      "title": "Διεύθυνση αποστολής",
      "confirm": "Ορισμός τοποθεσίας",
      "address_type": "Προορισμός",
      "receptor_type": "Δέκτης"
    },
    "receiver_address": "Επιλέξτε διεύθυνση αποστολής",
    "address": "διεύθυνση",
    "postcode": "ΤΑΧΥΔΡΟΜΙΚΟΣ ΚΩΔΙΚΟΣ",
    "enter_value": "Συμπληρώστε εδώ",
    "address_note": "Σημείωση",
    "tel": "Αριθμός επαφής",
    "service_address": "Επιλέξτε τη διεύθυνσή σας"
  },
  "weight": {
    "g": "σολ",
    "oz": "ουγκιά",
    "lb": "λίβρα",
    "kg": "κιλό"
  },
  "mass_unit_name": {
    "g": "γραμμάριο",
    "oz": "Ουγκιά",
    "lb": "Λίβρα",
    "kg": "χιλιόγραμμο"
  },
  "length": {
    "cm": "εκ",
    "in": "σε",
    "ft": "πόδια",
    "mm": "mm",
    "m": "Μ",
    "yd": "yd"
  },
  "size_unit_name": {
    "cm": "Εκατοστόμετρο",
    "in": "Ιντσα",
    "ft": "Πόδι",
    "mm": "χιλιοστόμετρο",
    "m": "μετρητής",
    "yd": "Αυλή"
  },
  "distance": {
    "m": "μετρητής",
    "km": "χλμ"
  },
  "time": {
    "days": "Μέρες",
    "hours": "Ωρες",
    "minutes": "Λεπτά",
    "seconds": "Δευτερόλεπτα"
  },
  "units": [
    "Μονάδα",
    "είδος",
    "καθε",
    "σειρά",
    "κομμάτι",
    "χιλιόγραμμο",
    "γραμμάριο",
    "χιλιοστόγραμμο",
    "μετρητής",
    "χιλιοστόμετρο",
    "τετραγωνικό μέτρο",
    "τετραγωνικά πόδια",
    "κυβικό μέτρο",
    "λίτρο",
    "χιλιοστόλιτρο",
    "πόδια",
    "γαλόνια",
    "ίντσες",
    "ουγγιές",
    "λίρες",
    "τεταρτημόρια",
    "αυλές",
    "δωμάτιο",
    "δευτερόλεπτα",
    "λεπτά",
    "ώρες",
    "ημέρες",
    "εβδομάδες",
    "μήνες",
    "χρόνια"
  ],
  "region_types": {
    "State": "κατάσταση",
    "Territory": "Εδαφος",
    "Province": "Επαρχία"
  },
  "transaction_status": {
    "RequireAction": "Απαιτείται ενέργεια",
    "Processing": "Επεξεργασία",
    "Canceled": "Ακυρώθηκε",
    "Succeeded": "πέτυχε"
  },
  "placeholders": {
    "name": "Τζον Κοξ",
    "email": "your-mail@mail.com",
    "phone": "+1 000 0000",
    "language": "Επιλέξτε γλώσσα..",
    "friend_email": "Το email του φίλου σου...",
    "friend_name": "Επιλέγω. Το όνομα του φίλου σου",
    "select_date": "Επιλέξτε ημερομηνία..."
  },
  "notification": {
    "confirm": "Επιβεβαιώνω",
    "confirm_message": "Οι αλλαγές αποθηκεύτηκαν με επιτυχία.",
    "error": "Λάθος",
    "message": "Μήνυμα",
    "caution": "Προσοχή",
    "warning": "Προειδοποίηση",
    "award": "Συγχαρητήρια",
    "error_message": "Δυστυχώς, παρουσιάστηκε σφάλμα.",
    "congratulation": "Συγχαρητήρια",
    "coming_soon": "Σύντομα",
    "on_fetching_data": "Λήψη πληροφοριών..",
    "new_pwa_version": "Νέα έκδοση διαθέσιμη τώρα. Θέλετε να ενημερώσετε την εφαρμογή;",
    "over_license_limit": "Πάνω από το όριο άδειας χρήσης",
    "update_license": "Ενημερώστε την άδειά σας",
    "required": "Απαιτείται",
    "invalid_email": "Ακυρη διεύθυνση ηλεκτρονικού ταχυδρομείου",
    "invalid_domain": "Μη έγκυρος τομέας",
    "invalid_min_length": "Το ελάχιστο μήκος πρέπει να είναι {length}",
    "invalid_min_array_length": "Επιλέξτε τουλάχιστον {length} στοιχεία",
    "invalid_max_chars": "Μέγιστος {maxCount} χαρακτήρες",
    "invalid_url": "Μη έγκυρη διεύθυνση URL",
    "country_invalid": "Επιλέξτε χώρα προορισμού!",
    "postal_code_invalid": "Ορίστε έγκυρο ταχυδρομικό κώδικα!"
  },
  "colors": {
    "#D32F2F": "το κόκκινο",
    "#C2185B": "Ροζ",
    "#7B1FA2": "Μωβ",
    "#512DA8": "Σκούρο μοβ",
    "#303F9F": "Indigo Blue",
    "#1976D2": "Μπλε",
    "#0288D1": "Γαλάζιο",
    "#0097A7": "Μπλε τιρκουάζ",
    "#00796B": "Πράσινο χήνας",
    "#388E3C": "Πράσινος",
    "#689F38": "Ανοιχτό πράσινο",
    "#AFB42B": "Λιμουζίνα",
    "#FBC02D": "Κίτρινος",
    "#FFA000": "Κεχριμπάρι",
    "#F57C00": "Πορτοκάλι",
    "#E64A19": "Γυαλιστερό Πορτοκαλί",
    "#5D4037": "καφέ",
    "#616161": "Γκρί",
    "#455A64": "Γκρι Μπλε",
    "#FFD700": "Χρυσαφένιος",
    "#C0C0C0": "Ασήμι",
    "#b76e79": "χρυσό τριαντάφυλλο",
    "#383838": "Μαύρο ματ",
    "#FFFFFF": "λευκό",
    "#FFF": "λευκό",
    "#000000": "Μαύρος",
    "#000": "Μαύρος",
    "#7d263a": "Μαρόν",
    "#FD9F17": "Χρυσός",
    "#229DBF": "Aqua",
    "#6DC9E2": "Aqua Triblend",
    "#413B2D": "Στρατός",
    "#474747": "Ασφάλτος",
    "#E6195C": "Μούρο",
    "#B2184C": "Μπέρι Τρίμπλεντ",
    "#FC7F5F": "Καμένο Πορτοκάλι",
    "#80011F": "Καρδινάλιος",
    "#382829": "Σοκολάτα",
    "#F06336": "Κοράλλι",
    "#FAE7C9": "Κρέμα",
    "#6B2257": "Σταφίδα",
    "#222127": "Σκούρο γκρι",
    "#0D5A74": "Deep Teal",
    "#00582F": "Αειθαλής",
    "#214C30": "Δάσος",
    "#DC2867": "Φουξία",
    "#38561F": "Κέλλυ",
    "#5C884D": "Φύλλο",
    "#558450": "Light Aqua",
    "#96B5C9": "Γαλάζιο",
    "#DCAFCE": "Πασχαλιά",
    "#D3E1A4": "Ασβεστος",
    "#9DE7C2": "Μέντα",
    "#F6EAD2": "Φυσικός",
    "#1A1F35": "ΠΟΛΕΜΙΚΟ ΝΑΥΤΙΚΟ",
    "#404624": "Ελιά",
    "#271020": "Δαμάσκηνο",
    "#A8355C": "Βατόμουρο",
    "#D6BEA6": "Απαλή κρέμα",
    "#BEA994": "Ηλιοκαμένος",
    "#0DB2AE": "Βάσκας",
    "#A86EA9": "Βιολέτα",
    "#36454F": "Ξυλάνθρακας",
    "#b3b0ab": "Carbon Grey",
    "#463e3d": "Άνθρακα Heather",
    "#282d3c": "Navy Blazer"
  },
  "address_info": {
    "name": "Ονομα",
    "tel": "Τηλέφωνο",
    "email": "ΗΛΕΚΤΡΟΝΙΚΗ ΔΙΕΥΘΥΝΣΗ",
    "country": "Χώρα",
    "city": "Πόλη",
    "state": "κατάσταση",
    "address": "διεύθυνση",
    "building_number": "Αριθμός κτισίματος",
    "building_unit": "Μονάδα",
    "postcode": "ΤΑΧΥΔΡΟΜΙΚΟΣ ΚΩΔΙΚΟΣ",
    "note": "Σημείωση",
    "county": "Κομητεία"
  },
  "product_types": {
    "physical": "Φυσικός",
    "physical_description": "Φυσικά προϊόντα όπως: κινητά τηλέφωνα, βιβλία, ηλεκτρονικά εξαρτήματα.",
    "virtual": "Εικονικός",
    "virtual_description": "Προϊόντα φιλικά προς το Διαδίκτυο όπως: κάρτα επαναφόρτισης, κράτηση ξενοδοχείου, επαναφόρτιση παιχνιδιού.",
    "file": "Αρχείο",
    "file_description": "Όλα τα επιτρεπόμενα αρχεία, όπως βίντεο διαδικτυακού μαθήματος, έγγραφα με δυνατότητα λήψης.",
    "service": "Υπηρεσία",
    "service_description": "Υπηρεσίες όπως: επισκευή, μεταφορά, διδασκαλία.",
    "subscription": "Συνδρομή",
    "subscription_description": "Συνδρομές και τιμολόγηση προϊόντων, υπηρεσιών ή περιεχομένων."
  },
  "license": {
    "free": "Ελεύθερος",
    "startup": "Ξεκίνα",
    "company": "Εταιρία",
    "enterprise": "Επιχείρηση"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "Σε άντρα",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW",
    "GHS": "GHS",
    "ZWD": "ZWD",
    "IQD": "IQD",
    "SYP": "SYP"
  },
  "variants": {
    "color": "Χρώμα",
    "volume": "Μέγεθος",
    "count_in_pack": "Μετρήστε σε πακέτο",
    "weight": "Βάρος",
    "type": "Υλικό",
    "style": "Στυλ"
  },
  "delivery_state": {
    "check_queue": "Αναμονή αναθεώρησης",
    "order_confirm": "Επιβεβαίωση της παραγγελίας",
    "preparing_order": "Προετοιμασία",
    "sent_order": "κατά την παράδοση",
    "to_customer": "Παραδόθηκε"
  },
  "status": {
    "unpaid": "Απλήρωτος",
    "paid": "επί πληρωμή",
    "canceled": "Ακυρώθηκε",
    "completed": "Τακτοποιημένο",
    "reserved": "Κατοχυρωμένα",
    "COD": "COD",
    "sold": "Πωληθεί",
    "open": "Ανοιξε",
    "cancel": "Ακυρώθηκε",
    "active": "Ενεργός",
    "inactive": "αδρανής",
    "debug": "Εντοπισμός σφαλμάτων",
    "live": "Ζω",
    "test": "Δοκιμή",
    "connected": "Συνδεδεμένος",
    "disconnected": "Ασύνδετος",
    "accept": "Αποδέχομαι",
    "reject": "Απορρίπτω",
    "pending": "εκκρεμής",
    "rejected": "Απορρίφθηκε",
    "accepted": "Δεκτός"
  },
  "dimensions": {
    "cm": "εκ",
    "km": "χλμ",
    "kg": "κιλό"
  },
  "transportation_type": {
    "motorbike": "Μοτοσικλέτα",
    "motorbike_description": "Μέτριο βάρος σε λίγα χιλιόμετρα.",
    "cargo_small": "Μικρό φορτίο",
    "cargo_small_description": "Ελαφρύ φορτίο πολλών χιλιομέτρων.",
    "cargo": "Φορτίο",
    "cargo_description": "Μέτριο βάρος σε λίγα χιλιόμετρα.",
    "truck": "Φορτηγό",
    "truck_description": "Χύδην ή βαρύ φορτίο εντός της χώρας.",
    "fast_post": "Γρήγορη ανάρτηση",
    "fast_post_description": "Γρήγορη αποστολή μέσω ταχυδρομείου.",
    "post": "Κανονική ανάρτηση",
    "post_description": "Τακτική αποστολή μέσω του ταχυδρομείου.",
    "airplane": "Αεροπορικό ταχυδρομείο",
    "airplane_description": "Ελαφρύ και μεσαίο φορτίο εσωτερικού και εξωτερικού.",
    "bicycle": "Καθαρή αποστολή",
    "bicycle_description": "Ελαφρύ φορτίο, σε απόσταση λίγων εκατοντάδων μέτρων από μη μηχανοκίνητα οχήματα.",
    "global": "Παγκόσμια μεταφορά",
    "global_description": "Αποστολή στο εξωτερικό αεροπορικώς, θαλάσσης ή ξηράς.",
    "pickup": "Μαζεύω",
    "pickup_description": "Οι πελάτες παραλαμβάνουν τα είδη από το φυσικό κατάστημα ή την αποθήκη σας."
  },
  "article": {
    "login_to_see_error": "Συνδεθείτε για πρόσβαση στο άρθρο",
    "create_new_action": "Δημιουργία Νέου Περιεχομένου",
    "menu_title": "Μενού",
    "menu": {
      "edit": "Κατάσταση επεξεργασίας",
      "view_mode": "Λειτουργία προβολής",
      "delete": "Διαγραφή άρθρου"
    },
    "schedule_action": "Θέλετε να προγραμματίσετε τη δημοσίευση;",
    "schedule_title": "Προγραμματίστε την αυτόματη δημοσίευση",
    "edit_mode": "Επεξεργασία",
    "public_view_mode": "Δημόσια άποψη",
    "publish_at": "Δημοσίευση στο",
    "published": "Δημοσίευσε",
    "draft": "Προσχέδιο",
    "saving": "Οικονομία",
    "save_and_publish_action": "Αποθήκευση και Δημοσίευση",
    "save_draft_action": "Αποθηκεύσετε το σχέδιο",
    "private": "Ιδιωτικός",
    "public": "Δημόσιο",
    "category_input": "Κατηγορία",
    "category_input_message": "Επιλέξτε κατηγορία άρθρου",
    "parent_input": "Γονική κατηγορία",
    "parent_input_message": "Επιλέξτε πατρικό περιεχόμενο",
    "schedule_input": "Πρόγραμμα",
    "schedule_input_placeholder": "Εάν θέλετε η ιστορία να δημοσιευτεί σε μια συγκεκριμένη χρονική στιγμή.",
    "schedule_view_action": "Προβολή χρονοδιαγράμματος δημοσίευσης",
    "author_title": "Γραμμένο από",
    "read_time": "Ωρα διαβάσματος",
    "read_time_unit": "Λεπτά",
    "claps_action": "Παλαμάκια",
    "claps": "Παλαμάκια",
    "likes": "Αρέσει",
    "about_author": "Σχετικά με τον Συγγραφέα",
    "updated_at": "ΕΠΙΚΑΙΡΟΠΟΙΗΜΕΝΟ",
    "wrote_at": "Γράφτηκε στο",
    "now": "Τώρα",
    "follow_action": "Ακολουθηστε",
    "followed": "Ακολούθησε",
    "report_and_delete_action": "Αναφορά και διαγραφή αυτού του άρθρου",
    "report_action": "Αναφορά κατάχρησης",
    "you_reported_this_article": "Αυτό το άρθρο έχει ήδη μια αναφορά κατάχρησης.",
    "add_to_publication_action": "Προσθήκη στη Δημοσίευση",
    "author_socials": "Συγγραφέας στα social media",
    "share": "Μερίδιο",
    "report_dialog": {
      "report_and_delete_title": "Αναφορά κατάχρησης και κατάργηση περιεχομένου",
      "report_title": "Αναφέρετε αυτό το περιεχόμενο ως καταχρηστικό",
      "message": "Ποιος είναι ο λόγος για την υποβολή αυτού του περιεχομένου; Επιλέξτε μία από τις παρακάτω επιλογές.",
      "accept_and_delete_action": "Επιβεβαίωση και διαγραφή περιεχομένου"
    },
    "schedule_dialog": {
      "title": "Χρονοδιάγραμμα κυκλοφορίας περιεχομένου",
      "publish_at": "Δημοσίευση στο",
      "last_edit": "Τελευταία επεξεργασία",
      "view_action": "Δείτε το άρθρο"
    },
    "notifications": {
      "update_success_title": "Υποβολή πληροφοριών",
      "update_success": "Το άρθρο ενημερώθηκε με επιτυχία.",
      "update_error": "Οι πληροφορίες που εισάγονται δεν είναι έγκυρες.",
      "delete_error": "Δεν μπορείτε να διαγράψετε αυτό το άρθρο!",
      "report_and_delete_success_title": "Αναφορά και Διαγραφή",
      "report_and_delete_success_message": "Το άρθρο διαγράφηκε με επιτυχία.",
      "report_success_title": "Αναφορά άρθρου",
      "report_success_message": "Η αναφορά σας για αυτό το άρθρο έχει αναρτηθεί."
    },
    "alert": {
      "delete_article": {
        "title": "Διαγραφή άρθρου",
        "message": "Είστε βέβαιοι ότι θέλετε να διαγράψετε οριστικά αυτό το άρθρο;",
        "action": "Διαγράφω"
      }
    },
    "edit_window": {
      "title": "Επιλέξτε Κείμενο εικόνας και Σύνοψη",
      "digest": "Περίληψη"
    },
    "editor": {
      "title_placeholder": "Τίτλος..",
      "body_placeholder": "Γράψε υπέροχο περιεχόμενο..",
      "accept_file_types_error": "Αυτή η μορφή αρχείου δεν είναι αποδεκτή:",
      "max_file_size_error": "Αυτό το αρχείο είναι πολύ μεγάλο:",
      "notifications": {
        "image_uploaded_success": "Η εικόνα αποθηκεύτηκε με επιτυχία",
        "image_uploaded_failed": "Σφάλμα κατά τη φόρτωση της εικόνας."
      },
      "embed_placeholder": "Εισαγάγετε τον κωδικό iframe, το Facebook, το Youtube ή οποιαδήποτε άλλη διεύθυνση URL και πατήστε enter.",
      "embed_caption_placeholder": "Εισαγάγετε έναν τίτλο (προαιρετικό)",
      "images_caption_placeholder": "Εισαγάγετε έναν τίτλο για αυτήν την εικόνα .."
    }
  },
  "article_report": {
    "inappropriate": "Το περιεχόμενο αυτού του άρθρου είναι ακατάλληλο.",
    "fake": "Αυτό είναι ψεύτικο και παραπλανητικό.",
    "spam": "Αυτό το στοιχείο έχει γίνει ανεπιθύμητο και αντιγράφηκε.",
    "scam": "Αυτό μπορεί να αναμένεται να προκαλέσει κακόβουλο λογισμικό, ιούς ή κατάρρευση συστήματος.",
    "hacked": "Αυτός ο ιστότοπος φαίνεται να έχει παραβιαστεί.",
    "offensive": "Το γλωσσικό περιεχόμενο και το λεξιλόγιο είναι ανήθικο και ασεβές.",
    "violent": "Νομίζω ότι αυτό το περιεχόμενο περιέχει πορνογραφία και παραβιάζει τους νόμους.",
    "harassment": "Νομίζω ότι αυτό είναι ρατσιστικό.",
    "hate": "Νομίζω ότι πρόκειται για την προώθηση της βίας.",
    "infringe": "Αυτό παραβιάζει τα δικαιώματά μου."
  },
  "comments": {
    "new_action": "Κάντε κλικ για να αφήσετε ένα σχόλιο..",
    "title": "Σχόλια",
    "body_placeholder": "Το σχόλιο ή το μήνυμά σας",
    "send_action": "Αποστολή σχολίου",
    "body_is_empty_error": "Το σχόλιο είναι κενό!",
    "comments": "Σχόλια",
    "no_comments": "Γράψε το πρώτο σχόλιο...",
    "load_more_action": "Λάβετε περισσότερα σχόλια..",
    "cant_send_comment": "Δεν μπορείτε να προσθέσετε νέα ανάρτηση.",
    "cant_remove_this_comment": "Δεν μπορείτε να διαγράψετε αυτό το σχόλιο!",
    "product_buyer": "Αγοραστής",
    "delete_alert": {
      "title": "Διαγραφή σχολίου",
      "message": "Θέλετε να διαγράψετε αυτό το σχόλιο;",
      "action": "Διαγράφω"
    },
    "notifications": {
      "delete_success": "Το σχόλιό σας διαγράφηκε με επιτυχία."
    },
    "first_send": "Πρώτη ανάρτηση",
    "comment_at": "Επί",
    "edit_comment": "Επεξεργασία σχολίου",
    "my_comments": "Τα σχόλιά μου"
  },
  "customer_club": {
    "bronze": "Μπρούντζος",
    "silver": "Ασήμι",
    "gold": "Χρυσαφένιος",
    "platinum": "Πλατίνα",
    "diamond": "Διαμάντι"
  },
  "application_categories": {
    "tracking": "Έλεγχος συμπεριφοράς χρήστη",
    "payment": "Πληρωμή",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "Μεταφορά",
    "automation": "Αυτοματοποίηση",
    "inventory": "Αποθήκευση",
    "accounting": "Λογιστική",
    "marketing": "Εμπορία",
    "advertising": "Διαφήμιση",
    "staff": "Προσωπικό",
    "incentive": "Κίνητρα",
    "shop": "Κατάστημα"
  },
  "social_network": {
    "instagram": "Ίνσταγκραμ",
    "telegram": "Τηλεγράφημα",
    "googleplay": "Google Play",
    "appstore": "App Store",
    "twitter": "Κελάδημα",
    "linkedin": "Linkedin",
    "medium": "Μεσαίο",
    "selldone": "Πωλείται",
    "facebook": "Facebook",
    "pinterest": "Pinterest",
    "whatsapp": "WhatsApp",
    "skype": "Skype",
    "facebook_messenger": "Facebook Messenger"
  },
  "form_builder": {
    "add_item_action": "Προσθήκη νέου στοιχείου",
    "title_input": "Τίτλος",
    "name_input": "Όνομα μεταβλητής",
    "value_input": "Αξίες",
    "value_input_message": "Λίστα επιλογών χρήστη",
    "default": "Προεπιλεγμένη τιμή",
    "types": {
      "simple": "Απλός",
      "selective": "Εκλεκτικός",
      "switch": "Διακόπτης",
      "file": "Αρχείο",
      "number": "Αριθμός"
    },
    "placeholder_input": "Placeholder",
    "file_type_input": "Αποδεκτοί τύποι αρχείων",
    "file_type_message": "jpeg , png , zip , ..."
  },
  "virtual_order_info_summery": {
    "title": "Ονομασία προϊόντος",
    "reserved_at": "Ημερομηνία Εγγραφής",
    "total_price": "Συνολικό ποσό",
    "discount": "Εκπτωση",
    "final_price": "Τελικό ποσό",
    "payment_status": "Κατάσταση πληρωμής",
    "payment_status_waiting": "Αναμονή για πληρωμή",
    "payment_status_paid": "επί πληρωμή",
    "buyer": "Αγοραστής"
  },
  "virtual_item_info": {
    "title": "Εικονικό αντικείμενο",
    "outputs": {
      "title": "Πληροφορίες εξόδου",
      "sub_title": "Εμπιστευτικές Πληροφορίες αυτού του Στοιχείου",
      "message": "Αυτές οι πληροφορίες θα εμφανίζονται στον χρήστη μετά την αγορά του προϊόντος."
    },
    "inputs": {
      "title": "Απαιτούνται πληροφορίες",
      "sub_title": "Απαιτούνται πληροφορίες αγοραστή",
      "message": "Ο αγοραστής πρέπει να εισαγάγει τις πληροφορίες που ζητούνται στη φόρμα"
    },
    "notifications": {
      "inputs_set_success": "Η φόρμα πληροφοριών εγγράφηκε με επιτυχία.",
      "confirm_by_admin_success": "Η ολοκλήρωση της παραγγελίας επιβεβαιώθηκε.",
      "confirm_by_buyer_success": "Η ολοκλήρωση της παραγγελίας επιβεβαιώθηκε."
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "Αυτή η παραγγελία δεν μπορεί να γίνει αποδεκτή με την πληρωμή αντικαταβολής.",
    "payment_returned": "Η πληρωμή από τον πελάτη επιστρέφεται.",
    "payment_fraud": "Η πληρωμή έχει αναγνωριστεί ως απάτη.",
    "location_out_of_service": "Η τοποθεσία του πελάτη είναι εκτός υπηρεσίας.",
    "user_not_responding": "Ο πελάτης δεν απαντούσε στις κλήσεις.",
    "shop_owner_fault": "Παρουσιάστηκε σφάλμα από το προσωπικό του καταστήματος στη συμπλήρωση των πληροφοριών.",
    "lack_of_inventory": "Εκτός αποθέματος.",
    "legal_restriction": "Δεν είναι δυνατή η υποβολή παραγγελίας λόγω νομικών περιορισμών.",
    "pricing_fault": "Λάθος τιμολόγησης από τον πωλητή.",
    "system_fault": "Σφάλμα συστήματος."
  },
  "basket_order_info_summery": {
    "receiver": "Δέκτης",
    "phone": "Τηλ",
    "reserved_date": "Ημερομηνία αγοράς",
    "total_price": "Συνολικό ποσό",
    "discount": "Εκπτωση",
    "final_price": "Τελικό ποσό",
    "address": "Διεύθυνση παράδοσης",
    "payment_status": "Κατάσταση πληρωμής"
  },
  "basket_status": {
    "open": "Ανοιξε",
    "reserved": "Κατοχυρωμένα",
    "paid": "επί πληρωμή",
    "canceled": "Ακυρώθηκε",
    "cod": "Πληρωμή κατά την παράδοση",
    "receipt_added": "Προστέθηκε η απόδειξη",
    "payment_processing": "Επεξεργασία πληρωμής"
  },
  "basket_delivery_state": {
    "rejected": "Απορρίφθηκε",
    "reject_reason_not_found": "Ο λόγος είναι άγνωστος.",
    "step_1": "Ανασκόπηση",
    "step_2": "Επιβεβαίωση",
    "step_3": "Παρασκευή",
    "step_4": "κατά την παράδοση",
    "step_5": "Παραδόθηκε"
  },
  "basket_return_request_view": {
    "title": "Αίτημα επιστροφής",
    "delivery_date": "Ημερομηνία παράδοσης",
    "return_date": "Ημερομηνία Αίτησης",
    "items_count": "Τα επιστρεφόμενα στοιχεία μετράνε",
    "items_count_unit": "στοιχείο(α)",
    "reason": "Λόγος",
    "description": "Περιγραφή",
    "status": "Κατάσταση",
    "download_image": "Λήψη εικόνας",
    "download_film": "Λήψη βίντεο",
    "download_voice": "Λήψη φωνής",
    "accept_by_admin_action": "Αποδοχή αιτήματος",
    "reject_by_admin_action": "Απόρριψη αιτήματος",
    "message_for_admin": "Σύμφωνα με τη συμφωνία που έχετε αποδεχτεί χρησιμοποιώντας το Seldone, πρέπει να επικοινωνήσετε με τον αγοραστή και να τον ενημερώσετε για τη διαδικασία επιστροφής της παραγγελίας του. Αυτό πρέπει να γίνει εάν το αίτημα γίνει αποδεκτό ή απορριφθεί και ληφθεί η πλήρης συγκατάθεση του αγοραστή.",
    "notifications": {
      "update_status_success": "Η κατάσταση του αιτήματος ενημερώθηκε."
    }
  },
  "basket_list": {
    "return_count": "Επιστροφή: {count} αριθμός",
    "table": {
      "row": "Σειρά",
      "image": "Εικόνα",
      "product_name": "Προϊόν",
      "variant": "Παραλαγή",
      "warranty": "Εγγυήσεις",
      "count": "μετρώ",
      "price": "τιμή"
    }
  },
  "return_request_list": {
    "count": "Αριθμός αναφοράς",
    "return_warranty": "Εγγύηση επιστροφής χρημάτων",
    "return_warranty_unit": "Μέρες)",
    "table": {
      "code": "Κωδικός παραγγελίας",
      "product": "Προϊόν",
      "delivery_at": "Ημερομηνία παραλαβής",
      "state": "Κατάσταση",
      "reason": "Λόγος",
      "return_warranty_period": "Περίοδος εγγύησης"
    }
  },
  "data_toolbar": {
    "search": "Αναζήτηση",
    "sort_by": "Ταξινόμηση κατά",
    "count_item": "Εμφάνιση {item} στοιχείων"
  },
  "sort": {
    "created_at": "Ημερομηνία δημιουργίας",
    "updated_at": "Επεξεργασία ημερομηνίας",
    "title": "Τίτλος",
    "description": "Περιγραφή",
    "like": "Δημοτικότητα",
    "power": "Παλαμάκια",
    "product_type": "Τύπος Προϊόντος",
    "discount": "Εκπτωση",
    "rate": "Εκτίμηση",
    "rate_count": "Αριθμός βαθμολογιών",
    "category": "Κατηγορία",
    "product": "Προϊόν",
    "body": "Περιεχόμενο",
    "card_type": "Τύπος κάρτας",
    "card_number": "Αριθμός κάρτας",
    "balance": "Ισορροπία",
    "paid": "Ποσό που δαπανήθηκε",
    "currency": "Νόμισμα",
    "expire_at": "Ημερομηνία λήξης",
    "discount_code": "Κωδικός έκπτωσης",
    "discount_percent": "Εκπτωση",
    "discount_limit": "Όριο έκπτωσης",
    "max_count": "Μέγιστο πλήθος",
    "used_count": "Μεταχειρισμένος",
    "start_date": "Ημερομηνία έναρξης",
    "end_date": "Ημερομηνία λήξης",
    "total_discount_amount": "Συνολικές εκπτώσεις",
    "initial_charge": "Αρχική χρέωση",
    "total_count": "Συνολικός αριθμός",
    "amount_paid": "Ποσό που καταβάλλεται",
    "name": "Ονομα",
    "published": "Δημοσίευσε",
    "visits": "Επισκέψεις",
    "color": "Χρώμα",
    "landing_page": "Σελίδα προορισμού",
    "enable": "επιτρέπω",
    "fix_commission": "Σταθερή προμήθεια",
    "percent_commission": "Ποσοστό προμήθειας",
    "payment_at": "Ημερομηνία πληρωμής",
    "issued_at": "Ημερομηνία έκδοσης",
    "payment": "Πληρωμή",
    "website": "Δικτυακός τόπος",
    "email": "ΗΛΕΚΤΡΟΝΙΚΗ ΔΙΕΥΘΥΝΣΗ",
    "user": "Χρήστης",
    "code": "Κώδικας",
    "schedule_at": "Προγραμματίστε ημερομηνία",
    "sender": "Αποστολέας",
    "in_que": "Στην ουρά",
    "sent": "Απεσταλμένα",
    "shop": "Κατάστημα",
    "quantity": "Ποσότητα",
    "amount": "Ποσό",
    "jobs": "Οι δουλειές μετράνε",
    "success": "Μέτρηση επιτυχίας",
    "fail": "Καταμέτρηση αποτυχιών",
    "distance": "Απόσταση",
    "duration": "Διάρκεια",
    "reset_at": "Επαναφορά ημερομηνίας",
    "delivery_person": "Πρόσωπο",
    "delivery_service": "Υπηρεσία",
    "date": "Ημερομηνία",
    "order": "Σειρά",
    "order_id": "Αριθμός Παραγγελίας",
    "status": "Κατάσταση",
    "price": "τιμή",
    "count": "μετρώ",
    "final_price": "Τελική τιμή",
    "charge": "Χρέωση",
    "mention": "Αναφέρω",
    "officer": "Αξιωματικός",
    "registered": "Εγγεγραμμένος",
    "purchased": "Αγορασμένο",
    "sex": "Γένος"
  },
  "search_box": {
    "result": "Αποτελέσματα αναζήτησης",
    "tips": "Αναζήτηση προϊόντων και κατηγοριών",
    "label": "Αναζήτηση ...",
    "category": "Κατηγορία"
  },
  "lead_status": {
    "physical_fast_delivery": "Άμεση παράδοση",
    "physical_under_24h_delivery": "Παράδοση εντός των επόμενων {lead} ωρών",
    "physical_over_24h_delivery": "Προετοιμασία και υποβολή από τις επόμενες {days} ημέρες",
    "virtual_fast_prepare": "Άμεση παράδοση",
    "virtual_under_24h": "Θα γίνει εντός των επόμενων {lead} ωρών",
    "virtual_over_24h": "Θα γίνει από τις επόμενες {days} ημέρες"
  },
  "return_request_state": {
    "pending": "εκκρεμής",
    "accepted": "Επιβεβαιωμένος",
    "rejected": "Απορρίφθηκε"
  },
  "return_order_reason": {
    "physical": {
      "U1": "Αναντιστοιχία προϊόντος",
      "U2": "Δεν υπάρχει προϊόν στη συσκευασία αποστολής",
      "U3": "Σπάσιμο συσκευασίας ή προϊόντος",
      "U4": "Παραβίαση συσκευασίας ή σειριακού αριθμού",
      "U5": "Κάποια στοιχεία από το δέμα λείπουν",
      "U6": "Το προϊόν δεν είναι πρωτότυπο",
      "U7": "Το προϊόν δεν πληροί τις προδιαγραφές"
    }
  },
  "image_uploader": {
    "label": "Μεταφορά & απόθεση ή <u>Επιλογή αρχείου</u>",
    "max_size": "Μέγιστο επιτρεπόμενο μέγεθος: {size}"
  },
  "timespan": {
    "Morning": "8 π.μ. - 12 μ.μ",
    "Evening": "12 το μεσημέρι έως 6 μ.μ",
    "Night": "6 μ.μ.-12 μ.μ",
    "Instant": "Άμεση ανάρτηση"
  },
  "week_day": {
    "Saturday": "Σάββατο",
    "Sunday": "Κυριακή",
    "Monday": "Δευτέρα",
    "Tuesday": "Τρίτη",
    "Wednesday": "Τετάρτη",
    "Thursday": "Πέμπτη",
    "Friday": "Παρασκευή"
  },
  "payment_form": {
    "title": "Επιλέξτε Τρόπος πληρωμής",
    "gift_cards_input": "Δωροκάρτες",
    "gift_cards_input_empty": "Δεν βρέθηκαν δωροκάρτες..",
    "more": "Αλλα",
    "pay_amount_by_gift_cards": "Πληρωμή με κάρτα χρέωσης",
    "select_payment_method": "Επιλέξτε τον τρόπο πληρωμής σας από τις παρακάτω επιλογές.",
    "payment_amount_remained": "Υπόλοιπο ποσό πληρωμής",
    "payment_amount": "Ποσό που καταβάλλεται",
    "all_paid_by_gift_cards": "Συγχαρητήρια, δεν χρειάζεται να πληρώσετε για αυτήν την παραγγελία. Πατήστε το πλήκτρο Pay With Gift Card.",
    "pay_by_gift_cards_action": "Πληρώστε την παραγγελία με κάρτα χρέωσης",
    "order_free_payment": "Συγχαρητήρια, η παραγγελία σας είναι δωρεάν!",
    "order_free_payment_action": "Παραγγείλετε δωρεάν τώρα",
    "qr": {
      "address": "Διεύθυνση πληρωμής",
      "amount": "Ποσό"
    }
  },
  "discount_input": {
    "limit": "έκπτωση {percent}% έως {limit} {currency}",
    "action": "Προσθήκη κωδικού έκπτωσης",
    "code_input": "Κωδικός έκπτωσης",
    "notifications": {
      "add_success": "Συγχαρητήρια, έγκυρος εκπτωτικός κωδικός."
    }
  },
  "gift_card": {
    "inactive": "Η κάρτα είναι απενεργοποιημένη",
    "expire": "Λήξη",
    "transfer": "ΜΕΤΑΦΟΡΑ",
    "send_to_friend": "Αποστολή σε φίλο"
  },
  "count_down": {
    "days": "Ημέρα",
    "hours": "Ωρα",
    "minutes": "Λεπτά",
    "seconds": "Δευτερόλεπτα"
  },
  "gift_status": {
    "Unpaid": "Αναμονή παραλαβής",
    "Paid": "επί πληρωμή",
    "Rejected": "Απορρίφθηκε",
    "Canceled": "Ακυρώθηκε"
  },
  "gift_program_status": {
    "Airdrop": "Σύστημα πληρωμής",
    "Advertising": "Διαφήμιση",
    "PersonalGift": "Προσωπικό Δώρο",
    "ShopGift": "Κατάστημα δώρων"
  },
  "currency_selector": {
    "label": "Νόμισμα"
  },
  "need_login": {
    "title": "Σύνδεση",
    "login_sms": "Σύνδεση SMS",
    "login_google": "Συνδεθείτε με το Google",
    "login_facebook": "Σύνδεση με το Facebook",
    "login_account": "Είσοδος από τη Selldone",
    "register": "Νέος χρήστης? Κάνε εγγραφή τώρα.",
    "mobile_input": "Εισάγετε το κινητό σας",
    "verification_code": "Κωδικός επαλήθευσης",
    "msg_title": "Γεια,",
    "msg_body": "ΠΑΡΑΚΑΛΩ ΣΥΝΔΕΘΕΙΤΕ. Χρειάζονται μόνο λίγα δευτερόλεπτα.",
    "login_apple": "Συνδεθείτε με την Apple",
    "login_email": "Είσοδος μέσω email",
    "email_login_step_1": "Δώστε μια έγκυρη διεύθυνση email και θα στείλουμε τον κωδικό σύνδεσης σε αυτήν. Δεν απαιτείται εγγραφή.",
    "email_login_step_2": "Είστε σίγουροι ότι έχετε εισαγάγει σωστά τη διεύθυνση email σας; Θα στείλουμε τον κωδικό σύνδεσης στο παρεχόμενο email, επομένως βεβαιωθείτε για την ακρίβειά του.",
    "email_login_step_3": "Έχουμε στείλει έναν κωδικό στο email σας. Λάβετε υπόψη ότι ο κωδικός θα λήξει σε 10 λεπτά."
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "5ετές κατάστημα χρυσού"
    },
    "GOLDEN_2YEAR": {
      "name": "4ετές κατάστημα χρυσού"
    },
    "GOLDEN_3YEAR": {
      "name": "Κατάστημα χρυσού 3 ετών"
    },
    "GOLDEN_4YEAR": {
      "name": "Κατάστημα χρυσού 2 ετών"
    },
    "GOLDEN_5YEAR": {
      "name": "Κατάστημα χρυσού 1 έτους"
    },
    "TOKEN_OWNER_1M": {
      "name": "Χρυσός Επενδυτής"
    },
    "TOKEN_OWNER_10M": {
      "name": "Επενδυτής διαμαντιών"
    },
    "TOKEN_OWNER_100M": {
      "name": "Ruby Investor"
    },
    "COMMUNITY_LOYAL": {
      "name": "Μέλος της Ανώτερης Κοινότητας Δικτύων Επικοινωνίας"
    },
    "GOLD_SUPPLIER": {
      "name": "Προμηθευτής Χρυσού"
    },
    "GOLD_SELLER": {
      "name": "Έμπορος χρυσού"
    },
    "CONTENT_SUPERMAN": {
      "name": "Κορυφαίος Παραγωγός Περιεχομένου"
    },
    "NINJA": {
      "name": "Νίντζα"
    },
    "STAR": {
      "name": "Αστέρι"
    },
    "GUARDIAN": {
      "name": "Μεγάλη εξυπηρέτηση πελατών"
    },
    "KING": {
      "name": "Βασιλιάς της Αγοράς"
    }
  },
  "cookie": {
    "title": "Αυτός ο ιστότοπος χρησιμοποιεί cookies",
    "message": "Αυτός ο ιστότοπος χρησιμοποιεί cookies για τη βελτίωση της εμπειρίας χρήστη. Χρησιμοποιώντας τον ιστότοπό μας συναινείτε σε όλα τα cookies σύμφωνα με την Πολιτική μας για τα cookies.",
    "preferences_action": "Διαχείριση Προτιμήσεων",
    "agree_action": "Συμφωνώ"
  },
  "basket_item_message": {
    "title": "Απαιτούμενες πληροφορίες για αυτό το στοιχείο",
    "save_actions": "Αποθήκευση μηνύματος",
    "notifications": {
      "success": "Τα δεδομένα εισόδου σας έχουν αποθηκευτεί."
    },
    "product_inputs_preview_message": "Αυτές οι επιλογές προσαρμογής είναι διαθέσιμες για το προϊόν που έχετε παραγγείλει. Μόλις το προϊόν προστεθεί στο καλάθι σας, θα μπορείτε να κάνετε προσαρμογές εδώ."
  },
  "faq": {
    "faq": "Συχνές Ερωτήσεις",
    "title": "Ερωτήσεις και απαντήσεις",
    "sub_title": "Αυτό που μας ζητήσατε να κάνουμε.",
    "message": "Αναζητήστε την απάντηση στην ερώτησή σας ανάμεσα στις παρακάτω απαντήσεις. Ρωτήστε μας εάν οι ερωτήσεις παραμένουν αναπάντητα.",
    "add_question_action": "Κάντε νέα ερώτηση",
    "read_more": "Διαβάστε περισσότερα ..",
    "load_more": "Περισσότερες ερωτήσεις ..",
    "main_page": "Συχνές ερωτήσεις Κεντρική σελίδα",
    "add_new": "Υποβολή νέας ερώτησης",
    "login_alert": "Συνδεθείτε για να κάνετε μια ερώτηση.",
    "question_input": "Ερώτηση",
    "question_input_placeholder": "Ρώτα την ερώτησή σου.",
    "notifications": {
      "success_add": "Η ερώτησή σας υποβλήθηκε με επιτυχία."
    }
  },
  "rating_labels": [
    "Πολύ κακό",
    "Κακό",
    "Κανονικός",
    "Καλός",
    "Εξοχος"
  ],
  "map_view": {
    "address_detail": "Λεπτομέρειες διεύθυνσης",
    "change": "Αλλαγή",
    "select": "Επιλέγω",
    "not_found_address": "Δεν βρέθηκε τιμή",
    "enter_address_hint": "Εισαγάγετε τη διεύθυνση προορισμού",
    "enter_your_address": "Εισαγάγετε τη διεύθυνσή σας.",
    "postal_code": "ΤΑΧΥΔΡΟΜΙΚΟΣ ΚΩΔΙΚΟΣ",
    "phone_input": "Τηλέφωνο {type}",
    "building_number": "Αριθμός κτισίματος",
    "building_unit": "Μονάδα",
    "full_name_input": "Πλήρες όνομα {type}",
    "save_detail_action": "Αποθηκεύστε λεπτομέρειες",
    "more_detail_input": "Περισσότερη περιγραφή",
    "add_address_to_list": "Προσθήκη διεύθυνσης στη λίστα",
    "address_title_input": "Ετικέτα διεύθυνσης (Απαιτείται)",
    "notifications": {
      "save_in_list": "Αυτή η διεύθυνση έχει αποθηκευτεί στη λίστα σας με όλες τις λεπτομέρειες.",
      "edit_success": "Οι νέες τιμές διεύθυνσης αποθηκεύτηκαν στο {title}."
    },
    "delete_address_dialog": {
      "title": "Διαγραφή διεύθυνσης",
      "message": "Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτήν τη διεύθυνση;",
      "action": "Κατάργηση διεύθυνσης"
    }
  },
  "comment_manager": {
    "can_not_edit": "Δεν είναι δυνατή η επεξεργασία αυτού του σχολίου!",
    "comment_input_empty": "Το κείμενο του μηνύματος είναι κενό!",
    "article_not_saved": "Αποθηκεύστε το άρθρο!"
  },
  "wheel_fortune": {
    "title": "Παίξτε & Κερδίστε",
    "message": "Το κόστος κάθε παιχνιδιού είναι 10 μάρκες. Αυτήν τη στιγμή έχετε {chips} τσιπ. Αποκτήστε περισσότερα τσιπ αγοράζοντας από το κατάστημα.",
    "win_message": "Συγχαρητήρια, κερδίσατε!",
    "lost_message": "Συγγνώμη, έχασες το παιχνίδι.",
    "try_again": "Μπορείτε να προσπαθήσετε ξανά"
  },
  "json": {
    "add": "Προσθήκη δεδομένων δομής",
    "add_message": "Δημιουργήστε νέα δεδομένα δομής",
    "structures": "Δομές",
    "book": {
      "title": "Βιβλίο",
      "desc": "Ενέργειες βιβλίου που επιτρέπουν στους χρήστες να αγοράσουν το βιβλίο που βρίσκουν απευθείας από τα αποτελέσματα αναζήτησης."
    },
    "occupation": {
      "title": "Εκτιμώμενος μισθός",
      "desc": "Πληροφορίες σχετικά με την εκτίμηση μισθών, όπως το εύρος μισθών και οι μέσοι όροι μισθών βάσει της περιοχής για τύπους θέσεων εργασίας, εμφανίζονται στην εμπειρία αναζήτησης εργασίας στο Google."
    },
    "course": {
      "title": "Σειρά μαθημάτων",
      "desc": "Εκπαιδευτικά μαθήματα που εμφανίζονται σε μια λίστα για συγκεκριμένο πάροχο. Τα μαθήματα μπορούν να περιλαμβάνουν τον τίτλο του μαθήματος, τον πάροχο και μια σύντομη περιγραφή."
    },
    "howto": {
      "title": "Πως να",
      "desc": "Το How-to καθοδηγεί τους χρήστες σε ένα σύνολο βημάτων για την επιτυχή ολοκλήρωση μιας εργασίας, που περιλαμβάνει βίντεο, εικόνες και κείμενο."
    },
    "recipe": {
      "title": "Συνταγή",
      "desc": "Συνταγές που εμφανίζονται ως μεμονωμένο πλούσιο αποτέλεσμα ή μέρος ενός καρουζέλ υποδοχής."
    }
  },
  "support": {
    "Financial": "Χρηματοοικονομική",
    "Technical": "Τεχνικός",
    "Advisor": "Σύμβουλος"
  },
  "condition": {
    "new": "Νέος",
    "refurbished": "Ανακαινισμένο",
    "used": "Μεταχειρισμένος",
    "used_fair": "Μεταχειρισμένο δίκαια",
    "used_good": "Μεταχειρισμένο καλά",
    "used_like_new": "Μεταχειρισμένο - Σαν καινούργιο"
  },
  "variant_filter": {
    "title": "Φίλτρο παραλλαγής προϊόντος",
    "only_available": "Σε απόθεμα"
  },
  "service": {
    "task": {
      "title": "Καθήκοντα",
      "message": "Λίστα εργασιών που εκτελούνται σε αυτήν την υπηρεσία."
    },
    "appointment": {
      "title": "Ραντεβού",
      "message": "Επιλέξτε τις ώρες της εβδομάδας από τις παρακάτω ώρες με βάση την ημέρα και την ώρα που σας ταιριάζει."
    },
    "booking": {
      "title": "Κράτηση",
      "message": "Καθορίστε τη χρονική περίοδο των ημερών που θέλετε να κάνετε κράτηση στο παρακάτω ημερολόγιο."
    },
    "subscription": {
      "title": "Συνδρομή"
    },
    "charge": {
      "title": "Χρέωση"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "Σταθερή τιμολόγηση",
      "message": "Σε αυτό το είδος τιμολόγησης, η τιμή του προϊόντος είναι ένα σταθερό ποσό και δεν χρειάζεται να ζητήσει ο αγοραστής υπολογισμό τιμής."
    },
    "ESTIMATION": {
      "title": "Εκτίμηση Τιμολόγησης",
      "message": "Η τιμή των προϊόντων και των υπηρεσιών θα υπολογιστεί σε κάποιο βαθμό από τον πωλητή κατά την υποβολή μιας παραγγελίας, τα τιμολόγια πληρωμής μπορούν να αλλάξουν ή να προστεθούν κατά τη διάρκεια της υπηρεσίας."
    },
    "AGREEMENT": {
      "title": "Τιμολόγηση συμφωνίας",
      "message": "Η τελική τιμή των προϊόντων ή των υπηρεσιών δεν θα αλλάξει από τον πωλητή μετά την τοποθέτηση της παραγγελίας."
    },
    "BID": {
      "title": "Προσφορά / Δημοπρασία",
      "message": "Το προϊόν θα πωληθεί στην υψηλότερη τιμή προσφοράς από πιθανούς αγοραστές."
    }
  },
  "map": {
    "title": "Προορισμός παραλαβής προϊόντων",
    "confirm": "Ορισμός τοποθεσίας",
    "address": "Προορισμός",
    "receptor": "Δέκτης"
  },
  "ShopBots": {
    "telegram": "Τηλεγράφημα"
  },
  "article_tags": {
    "title": "Ετικέτες περιεχομένου",
    "tags_input": "Ετικέτες",
    "tags_input_message": "Ετικέτες Λίστα αυτού του άρθρου",
    "notification": {
      "add_success": "Προστέθηκαν ετικέτες"
    }
  },
  "difficulties": {
    "very_complicated": "Πολύ περίπλοκο",
    "hard": "Σκληρός",
    "intermediate": "Ενδιάμεσος",
    "easy": "Ανετα"
  },
  "billing_period": {
    "Daily": "Καθημερινά",
    "Weekly": "Εβδομαδιαίος",
    "Monthly": "Μηνιαίο",
    "Every3Months": "Κάθε 3 μήνες",
    "Every6Months": "Κάθε 6 μήνες",
    "Yearly": "Ετήσια"
  },
  "buyer_rating_statement": {
    "between1_2": "Ωχ δεν είναι καλό!",
    "between2_3": "Είναι εντάξει!",
    "between3_4": "Αρέσει στον κόσμο!",
    "between4_5": "Ο κόσμος το λατρεύει!"
  }
};