export default {
  "currency_default": "USD",
  "language_default": "fi",
  "selldone": "myyty valmis",
  "store": "tallentaa",
  "not_exist": "Ei ole olemassa",
  "error": "Virhe",
  "active": "Aktiivinen",
  "inactive": "epäaktiivinen",
  "required_value": "Vaaditut arvot",
  "original_warranty": "Alkuperäisen tuotteen takuu",
  "return_warranty_days": "{days} palautustakuupäivä(ä)",
  "no_return_warranty": "Ei paluuta",
  "reed_agree_terms": "Olen lukenut käyttöehdot ja tietosuojaselosteen ja hyväksyn ne.",
  "commons": {
    "Currency": "Valuutta",
    "COD": "COD",
    "State": "Osavaltio",
    "Price": "hinta",
    "order_price": "Tilausmäärä",
    "VAT": "VAT",
    "Discount": "Alennus",
    "In_Stock": "Varastossa",
    "Variants": "Vaihtoehdot",
    "No_variants": "Ei varianttia",
    "all": "KAIKKI",
    "today": "Tänään",
    "yesterday": "Eilen",
    "license": "Lisenssi",
    "home": "Koti",
    "support": "Tuki",
    "messages": "Viestit",
    "no_message": "Ei viestiä",
    "empty": "Tyhjä",
    "phone": "Puhelin",
    "address": "osoite",
    "name": "Nimi",
    "password": "Salasana",
    "email": "Sähköposti",
    "mobile": "mobiili",
    "login": "Kirjaudu sisään",
    "register": "Rekisteröidy",
    "select_account": "Valitse tili",
    "online": "verkossa",
    "offline": "Offline-tilassa",
    "finish": "Viedä loppuun",
    "finished": "Valmis",
    "preview": "Esikatselu",
    "free": "Vapaa",
    "free_completely": "Täysin ilmainen tilaus",
    "fee": "Maksu",
    "month": "Kuukausi",
    "months": "Kuukaudet",
    "faq": "Usein Kysytyt Kysymykset",
    "question": "Kysymys",
    "answer": "Vastaus",
    "create_date": "Luo päiväys",
    "update_date": "Päivitä päivämäärä",
    "start_date": "Aloituspäivämäärä",
    "end_date": "Päättymispäivä",
    "social": "Sosiaalinen",
    "total": "Kaikki yhteensä",
    "orders": "Tilaukset",
    "sessions": "Istunnot",
    "product_views": "Tuotenäkymät",
    "add_to_carts": "Lisää ostoskoriin",
    "checkouts": "Tarkista",
    "payments": "Maksu",
    "organic_search": "Orgaaninen haku",
    "other": "Muut",
    "landing_page": "Aloitussivu",
    "discount_code": "Alennuskoodi",
    "total_sell": "Kokonaismyynti",
    "details": "Yksityiskohdat",
    "currency": "Valuutta",
    "amount": "Määrä",
    "published": "Julkaistu",
    "draft": "Luonnos",
    "save_changes": "Tallenna muutokset",
    "source": "Lähde",
    "medium": "Keskikokoinen",
    "url": "URL-osoite",
    "revenue": "Tulot",
    "performance": "Esitys",
    "term": "Termi",
    "content": "Sisältö",
    "session": "istunto",
    "product": "Tuote",
    "add": "Lisätä",
    "checkout": "Tarkista",
    "payment": "Maksu",
    "more_options": "Lisää vaihtoehtoja",
    "full_name": "Koko nimi",
    "tel": "Puh",
    "about_me": "Minusta",
    "request_checking": "Pyydä tarkistusta",
    "passport": "Passi",
    "birthday": "Syntymäpäivä",
    "country": "Maa",
    "city": "Kaupunki",
    "gender": "Sukupuoli",
    "offer": "Tarjous",
    "website": "Verkkosivusto",
    "apply_for_all_products": "∞ Hae kaikkiin tuotteisiin",
    "fix_commission": "Kiinteä provisio",
    "percent_commission": "Prosenttipalkkio",
    "fixed_discount": "Kiinteä alennus",
    "discount_percentage": "Prosenttialennus",
    "discount_limit": "Alennusraja",
    "no_code": "Ei koodia",
    "max_count": "Enimmäismäärä",
    "count_unit": "Tuotteet",
    "used": "Käytetty",
    "daily": "Päivittäin",
    "monthly": "Kuukausittain",
    "yearly": "Vuosittain",
    "state": "Tila",
    "disable": "Poista käytöstä",
    "enable": "ota käyttöön",
    "activation_code": "Aktivointikoodi",
    "quantity": "Määrä",
    "no_club": "Ei klubi",
    "per_order": "Tilauksen mukaan",
    "count": "Kreivi",
    "seconds": "Sekuntia",
    "auto": "Auto",
    "title": "Otsikko",
    "message": "Viesti",
    "width": "Leveys",
    "length": "Pituus",
    "height": "Korkeus",
    "label": "Label",
    "click": "Klikkaus",
    "bank": "Pankki",
    "default": "Oletus",
    "role": "Rooli",
    "user": "Käyttäjä",
    "users": "Käyttäjät",
    "code": "Koodi",
    "total_payment": "Koko maksu",
    "balance": "Saldo",
    "chance": "Mahdollisuus",
    "free_for_new_users": "Uusille käyttäjille ilmainen",
    "prize_amount": "Palkinnon määrä",
    "win": "Voittaa",
    "gift_card": "Lahjakortti",
    "discount": "Alennus",
    "config": "Konfig",
    "prize": "Palkinto",
    "Prizes": "Palkinnot",
    "result": "Tulos",
    "price": "hinta",
    "lottery": "Arpajaiset",
    "coupon": "Kuponki",
    "customer_club": "Asiakasklubi",
    "shipping": "laivaus",
    "sum": "Summa",
    "not_paid": "Ei maksettu",
    "category": "Kategoria",
    "done": "Tehty",
    "email_from": "From",
    "subject": "Aihe",
    "schedule": "Ajoittaa",
    "files_list": "Tiedostojen luettelo",
    "file_max_size": "Tiedoston enimmäiskoko",
    "value": "Arvo",
    "help": "auta",
    "shipping_tax": "Toimitusvero",
    "net_price": "Nettohinta",
    "tax": "Verottaa",
    "tax_included": "Sisältyy hintaan",
    "limit": "Raja",
    "min_purchase": "Minimi osto",
    "eligible_for": "Oikeutettu",
    "only_for_first_buy": "Vain ensimmäiseen ostoon",
    "one_time_use": "Voidaan käyttää kerran",
    "period_of_qualify": "Jakson käyttöraja",
    "no_constraint": "Ei rajoitusta",
    "timespan": "Ajanjakso",
    "days": "päivä(t)",
    "weight": "Paino",
    "distance": "Etäisyys",
    "last_status": "Viimeinen tila",
    "issued_at": "Myönnetty klo",
    "order": "Tilaus",
    "order_detail": "Tilauksen tiedot",
    "percent": "prosenttia",
    "applied_count": "Sovellettu määrä",
    "campaign": "Kampanja",
    "os": "Käyttöjärjestelmä",
    "browser": "Selain",
    "device": "Laite",
    "device_ip": "Laitteen IP-osoite",
    "location": "Sijainti",
    "user_agent": "Käyttäjä agentti",
    "affiliate": "Yhteistyökumppani",
    "timeline": "Aikajana",
    "add_note": "Lisätä huomautus",
    "record": "Ennätys",
    "unlimited": "Rajoittamaton",
    "show_coupons": "Näytä kupongit",
    "hide_coupons": "Piilota kupongit",
    "service_area": "Palvelualue",
    "apps": "Sovellukset",
    "plugins": "Plugins",
    "bots": "Botit",
    "categories": "Luokat",
    "products": "Tuotteet",
    "business": "Liiketoimintaa",
    "personal": "Henkilökohtainen",
    "size": "Koko",
    "holiday": "Loma",
    "sod": "Maksa toimituksen yhteydessä",
    "cod": "Postiennakko",
    "free_shipping": "Ilmainen toimitus",
    "hours": "Tuntia",
    "send_date": "Lähetyspäivä",
    "deliver_date": "Toimituspäivä",
    "return_date": "Palautuspäivä",
    "pending": "Odottaa",
    "delivered": "Toimitettu",
    "returned": "Palannut",
    "canceled": "Peruutettu",
    "shipping_cost": "Toimituskulut",
    "action": "Toiminta",
    "cancel_date": "Peruuta päivämäärä",
    "deliver_in_process": "Tilaus toimitetaan..",
    "kind": "Tyyppi",
    "detail": "Yksityiskohdat",
    "map": "Kartta",
    "actions": "Toiminnot",
    "navigation": "Navigointi",
    "navigation_app": "Sovellus",
    "payment_date": "Maksupäivä",
    "duration": "Kesto",
    "bill": "Laskuttaa",
    "delivery_persons": "Kuriirit",
    "delivery_services": "Toimituspalvelut",
    "live_view": "Live-näkymä",
    "cart": "Kärry",
    "priority": "Prioriteetti",
    "sufficient_credit": "Riittävä luotto",
    "max_package_size": "Pakkauksen enimmäiskoko",
    "delay": "Viive",
    "credit": "Luotto",
    "livemode": "Elää",
    "paused": "Keskeytetty",
    "debug": "Debug",
    "token": "Token",
    "status": "Tila",
    "courier": "Kuriiri",
    "track": "Seurata",
    "track_order": "Tilauksen seuranta",
    "cost": "Kustannus",
    "receipt": "Kuitti",
    "origin": "Alkuperä",
    "destination": "Kohde",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "Varasto ei riitä!",
    "sub_total": "Välisumma",
    "customer": "Asiakas",
    "delivery": "Toimitus",
    "online_orders": "Online tilaukset",
    "pos_orders": "POS-tilaukset",
    "chips": "Chips",
    "subscribed": "Tilattu",
    "unsubscribed": "Tilaus peruutettu",
    "last_login": "Viimeinen kirjautuminen",
    "join_at": "Liittymispäivä",
    "club": "klubi",
    "buyer": "Ostaja",
    "seller": "Myyjä",
    "or": "Tai",
    "type": "Tyyppi",
    "condition": "Kunto",
    "brand": "Brändi",
    "attempt": "Yrittää",
    "error": "Virhe",
    "success": "Menestys",
    "fail": "Epäonnistua",
    "inventory": "Varasto",
    "link": "Linkki",
    "visits": "Vierailut",
    "transactions": "Tapahtumat",
    "vat": "VAT",
    "pos_vat": "POS ALV",
    "sort_by": "Järjestä..",
    "from": "From",
    "from_lead_time": "Seuraavien {hours} tunnin sisällä",
    "no_credit_card_info": "Ei korttitietoja!",
    "active": "Aktiivinen",
    "not_active": "Ei aktivoitu!",
    "referrals": "Viittaukset",
    "dashboard": "Kojelauta",
    "more": "Lisää",
    "inactive": "epäaktiivinen",
    "developer": "Kehittäjä",
    "setting": "Asetus",
    "membership_conditions": "Jäsenyyden ehdot",
    "customers": "Asiakkaat",
    "created_at": "Luontipäivämäärä",
    "updated_at": "Viimeisin päivitys",
    "register_at": "Ilmoittautumispäivä",
    "old": "Vanha",
    "new": "Uusi",
    "start": "alkaa",
    "end": "Loppu",
    "pos": "POS",
    "out_of_stock": "Loppu varastosta",
    "fake": "Fake",
    "low_inventory_warning": "Huomio, alhainen varasto!",
    "webhook": "Webhook",
    "notification": "Ilmoitus",
    "sms": "SMS",
    "online_payment_link": "Verkkomaksulinkki",
    "waiting_load_data": "Odotetaan tietojen lataamista..",
    "views": "Näkymät",
    "sales": "Myynti",
    "total_views": "Näyttökertoja yhteensä",
    "total_sales": "Kokonaismyynti",
    "from_previous_n_days": "Viimeisestä {days} päivästä",
    "drop_shipping": "Dropshipping",
    "commission": "komissio",
    "shipping_area": "Toimitusalue",
    "main_seller": "Päämyyjä",
    "domain": "Verkkotunnus",
    "contact": "Yhteystiedot",
    "wallet": "Lompakko",
    "reseller": "Jälleenmyyjä",
    "tracking_code": "Seurantakoodi",
    "tracking_url": "Seuranta-URL",
    "fulfillments": "Täyttymiset",
    "reject": "Hylätä",
    "reserved": "Varattu",
    "score": "Pisteet",
    "customer_price": "Asiakashinta",
    "options": "Vaihtoehdot",
    "show_details": "Näytä yksityiskohdat",
    "no_data": "Ei dataa..",
    "waiting": "Odotetaan...",
    "waiting_connecting_payment": "Maksupalvelua odotellessa...",
    "creating_secure_payment": "Turvallisen maksun luominen.",
    "officer": "upseeri",
    "ticket": "Lippu",
    "ticket_url": "Lipun URL-osoite",
    "closed_at": "Suljettu klo",
    "close_ticket": "Sulje lippu",
    "reopen_ticket": "Avaa lippu uudelleen",
    "require": "Vaatia*",
    "search": "Hae...",
    "language": "Kieli",
    "tasks": "Tehtävät",
    "permissions": "Käyttöoikeudet",
    "finish_date": "Päättymispäivä",
    "complete_date": "Valmistumispäivä",
    "settle_date": "Maksupäivä",
    "cost_span": "Hintaluokka",
    "industry": "Ala",
    "rating": "Arviot",
    "rates": "Luokitus",
    "seen_at": "Nähty klo",
    "completed": "Valmis",
    "you": "Sinä",
    "shop": "Myymälä",
    "store": "tallentaa",
    "granted": "Myönnetty",
    "deny": "Kiellä",
    "request": "Pyyntö",
    "expert": "Asiantuntija",
    "response": "Vastaus",
    "requests": "Pyynnöt",
    "experts": "Asiantuntijat",
    "responses": "Vastaukset",
    "negotiations": "Neuvottelut",
    "all_chats": "Kaikki chatit",
    "chats": "Chatit",
    "tags": "Tunnisteet",
    "description": "Kuvaus",
    "rates_count": "Arvioiden määrä",
    "rate": "Luokitus",
    "comment": "Kommentti",
    "chat": "Chat",
    "install": "Asentaa",
    "edited": "Muokattu",
    "undo": "Kumoa",
    "redo": "Toista",
    "male": "Uros",
    "female": "Nainen",
    "calculator": "Laskin",
    "catalog": "Luettelo",
    "max_height": "Suurin korkeus",
    "images_compare": "Kuvien vertailu",
    "canvas": "Kangas",
    "table_of_contents": "Sisällysluettelo",
    "comments": "Kommentit",
    "badge_codes": "Merkkien koodi",
    "need_more": "Tarvita lisää?",
    "invite_glow_caption": "Saat 14,9 dollaria jokaisesta ystävästä!",
    "register_free": "100% ilmainen rekisteröinti",
    "gift": "Lahja",
    "google": "Google",
    "facebook": "Facebook",
    "instagram": "Instagram",
    "instashop": "Instashop",
    "show": "Näytä",
    "hide": "Piilottaa",
    "waiting_review": "Odotetaan arvostelua",
    "not_selected": "Ei valittu",
    "time": "Aika",
    "final_price": "Lopullinen hinta",
    "starting_price": "Aloitushinta",
    "day": "Päivä",
    "paid": "Maksettu",
    "service_bill": "Laskun maksu",
    "avocado": "Avokado",
    "delivery_price": "Toimituskulut",
    "select_address": "Valitse osoite",
    "image": "Kuva",
    "view": "Näytä",
    "sell": "Myynti",
    "hyper": "Hyper",
    "cart_list": "Kärry",
    "barcode_scanner": "Viivakoodinlukija",
    "scan_qr_code": "Skannaa QR-koodi",
    "new_carts": "Uudet kärryt",
    "pays": "Maksut",
    "annually": "Vuosittain",
    "sells": "Myynti",
    "articles": "Artikkelit",
    "jobs": "Työpaikat",
    "job": "Job",
    "blog": "Blogi",
    "deleted_at": "Poistettu klo",
    "capacity": "Kapasiteetti",
    "download_at": "Viimeisin latauspäivä",
    "downloads": "Lataukset",
    "usage": "Käyttö",
    "select_upload_file": "Valitse tai pudota tiedosto",
    "download_link": "Lataa linkki",
    "uploading": "Ladataan...",
    "files": "Tiedostot",
    "star": "Tähti",
    "speed": "Nopeus",
    "feedback": "Palaute",
    "new_messages": "Uusia viestejä",
    "file": "Tiedosto",
    "attachment": "Liite",
    "gallery": "Galleria",
    "sync": "Synkronoi",
    "diff_time": "Aikaero",
    "network": "Verkko",
    "account": "Tili",
    "configuration": "Kokoonpano",
    "blockchain": "Blockchain",
    "blog_link": "Linkki blogiin",
    "community": "Yhteisö",
    "critical_zone": "Kriittinen vyöhyke",
    "statistics": "Tilastot",
    "access": "Pääsy",
    "seo": "SEO",
    "followers": "Seuraajia",
    "followings": "Seuraukset",
    "private": "Esikatselu",
    "soon": "Pian",
    "features": "ominaisuudet",
    "bot": "Bot",
    "sample": "Näyte",
    "how_it_work": "Kuinka se toimii?",
    "page": "Sivu",
    "congratulations": "Onnittelut",
    "recommend": "Suositella",
    "recommended": "Suositeltava",
    "recoms": "Suositukset",
    "likes": "Tykkää",
    "clicks": "Napsautukset",
    "platform": "Alusta",
    "cms": "CMS",
    "cash": "Käteinen raha",
    "dir_payment": "pankkisiirto",
    "auto_complete": "Automaattinen viimeistely",
    "compare": "Vertailla",
    "infinite": "Ääretön",
    "tips": "Vinkkejä",
    "technical": "Tekninen",
    "finance": "Rahoittaa",
    "your_phone_input": "Lisää puhelinnumero",
    "income": "Tulo",
    "change": "Muuttaa",
    "new_users": "Uudet käyttäjät",
    "success_orders": "Onnistuneet tilaukset",
    "direct": "Suoraan",
    "last_activity": "Viimeinen toiminta",
    "landing": "Lasku",
    "now": "Nyt",
    "accept_agreement": "Olen lukenut ja hyväksynyt ehdot.",
    "report": "Raportoi",
    "tablet": "Tabletti",
    "pc": "PC",
    "acquisition_channel": "Hankintakanava",
    "to": "Vastaanottaja",
    "info": "Tiedot",
    "general": "Kenraali",
    "upload": "Lataa",
    "general_config": "Yleinen konfigurointi",
    "limits_config": "Rajoitukset",
    "design_config": "Suunnittelu & Tyyli",
    "duration_config": "Kestorajoitus",
    "constraints_config": "Kelpoisuusrajat",
    "clubs_config": "Saatavilla Klubeissa",
    "additional_config": "Lisäasetukset",
    "import": "Tuonti",
    "ribbon": "Nauha",
    "countries": "Maat",
    "edit": "Muokata",
    "delete": "Poistaa",
    "analytics": "Analytics",
    "rules": "säännöt",
    "unset": "Ei valittu",
    "carts": "Kärryt",
    "optional": "Valinnainen",
    "design": "Design",
    "filter": "Suodattaa",
    "send": "Lähettää",
    "approved": "Hyväksytty",
    "unit": "Yksikkö",
    "profile": "profiili",
    "shipping_rates": "Toimitushinnat",
    "package": "Paketti",
    "overview": "Yleiskatsaus",
    "live": "Elää",
    "never": "Ei koskaan",
    "always": "Aina",
    "mandatory": "Pakollinen",
    "expire_at": "Päättymispäivä",
    "position": "asema",
    "channel": "kanava",
    "age": "Ikä",
    "charge": "Lataa",
    "giftcard": "Lahjakortti",
    "acquisition": "Hankinta",
    "conversion": "Muuntaminen",
    "total_payments": "Maksut yhteensä",
    "community_ask": "Kysy yhteisössä",
    "children": "Lapset",
    "export": "Viedä",
    "list": "Lista",
    "hierarchy": "Hierarkia",
    "images": "kuvat",
    "demo": "Demo",
    "author": "Tekijä",
    "designer": "Suunnittelija",
    "max": "Maksimi",
    "accepted": "Hyväksytty",
    "reply": "Vastaa",
    "reviewed": "Arvosteltu",
    "restored": "Palautettu",
    "merchant": "Kauppias",
    "per_product": "Tuotetta kohti",
    "journey": "Matka",
    "after": "Jälkeen",
    "waiting_for_payment": "Suorita maksu loppuun...",
    "hour": "Tunnin",
    "minute": "Minuutti",
    "premium": "Premium",
    "light": "Kevyt",
    "dark": "Tumma",
    "guest": "Vieras",
    "shops": "Kaupat",
    "vendor": "Myyjä",
    "vendors": "Myyjät",
    "marketplace": "Markkinapaikka",
    "verify_date": "Vahvista päivämäärä",
    "note": "Huomautus",
    "panel": "Paneeli",
    "removed": "Poistettu",
    "segments": "Segmentit",
    "personal_info": "Henkilökohtaiset tiedot",
    "preferences": "Asetukset",
    "spec": "Spec",
    "reviews": "Arvostelut",
    "constraints": "Rajoitukset",
    "flexible": "Joustava",
    "usage_limit": "Käyttörajoitus",
    "temporary": "Väliaikainen",
    "original": "Alkuperäinen",
    "saved": "Tallennettu!",
    "sort": "Järjestellä",
    "documents": "Asiakirjat",
    "document": "Asiakirja",
    "please_wait": "Odota...",
    "pickup": "Noukkia",
    "customize": "muokata",
    "difficulty": "Vaikeus",
    "banned": "Kielletty",
    "company": "Yhtiö",
    "tax_shipping": "Toimitusvero",
    "warranty": "Takuu",
    "return_policy": "PALAUTUSKÄYTÄNTÖ",
    "guide": "Opas",
    "translate": "Kääntää",
    "public": "Julkinen",
    "deleted": "Poistettu",
    "variant": "Variantti",
    "secure": "Turvallinen",
    "admin": "Admin",
    "tax_included_abstract": "sis.",
    "payment_not_settled": "Maksua ei suoritettu!",
    "orders_list": "Tilauslista",
    "subscription_plan": "Tilaussuunnitelma",
    "contents": "Sisällys",
    "pricings": "Hinnat",
    "static_page": "Staattinen sivu",
    "shop_button": "Kauppa-painike",
    "embed": "Upottaa",
    "over": "Yli",
    "tax_vary_by_location": "vaihdella. sijainti",
    "product_type": "Tuotetyyppi",
    "tax_id": "Verotunnus",
    "business_name": "Yrityksen nimi",
    "invoice": "Lasku",
    "included_in_the_product": "Sisältyy tuotteeseen",
    "included_in_the_product_description": "Tuote sisältää seuraavat komponentit",
    "cross_sell": "Ristimyynti",
    "discount_off": "OFF",
    "extra_discount": "Ylimääräinen alennus",
    "template": "Sapluuna",
    "in_cart": "Ostoskorissa",
    "pros_and_cons": "Hyvät ja huonot puolet",
    "related_products": "Liittyvät tuotteet",
    "related_categories": "Liittyvät kategoriat",
    "badges": "Tunnusmerkit",
    "explore": "Tutkia",
    "updated": "Päivitetty",
    "bank_name": "Pankin nimi",
    "bank_account_number": "Pankkitilin numero",
    "bank_routing_number": "Pankin reititysnumero",
    "bank_branch_address": "Pankin sivukonttorin osoite",
    "bank_account_name": "Tilin omistajan koko nimi",
    "valuation": "Arvostus",
    "cluster": "Klusteri",
    "clusters": "Klusterit",
    "subscriptions": "Tilaukset",
    "spam": "Roskaposti",
    "video": "Video"
  },
  "dialogs": {
    "delete": {
      "title": "Poistaa",
      "message": "Haluatko varmasti poistaa tämän kohteen?",
      "action": "Kyllä, poista nyt"
    }
  },
  "actions": {
    "add_to_cart": "Lisää ostoskoriin",
    "cancel": "Peruuttaa",
    "update": "Päivittää",
    "add": "Lisätä",
    "delete": "Poistaa",
    "new": "Uusi",
    "save_continue": "Tallenna ja jatka",
    "save": "Tallentaa",
    "save_changes": "Tallenna muutokset",
    "change": "Muuttaa",
    "continue": "Jatkaa",
    "close": "kiinni",
    "finish": "Viedä loppuun",
    "poll": "Poll",
    "view": "Näytä",
    "edit": "Muokata",
    "next": "Seuraava",
    "previous": "Edellinen",
    "create": "Luoda",
    "set": "aseta",
    "find": "löytö",
    "accept": "Hyväksyä",
    "reject": "Hylätä",
    "back": "Takaisin",
    "pay": "Maksaa",
    "pay_now": "Maksa nyt",
    "print": "Tulosta",
    "return": "Palata",
    "publish": "Julkaista",
    "confirm": "Vahvistaa",
    "copy": "Kopio",
    "submit": "Lähetä",
    "send": "Lähettää",
    "yes": "Joo",
    "no": "ei",
    "meh": "Hmm",
    "clear": "Asia selvä",
    "dismiss": "Hylkää",
    "search": "Hae",
    "deselect_all": "Poista kaikki valinnat",
    "select_all": "Valitse kaikki",
    "refresh": "virkistää",
    "verify": "Vahvista",
    "play": "pelata",
    "open": "Avata",
    "calculate": "Laskea",
    "quick_buy": "Pikaostos",
    "click_here": "Klikkaa tästä",
    "schedule": "Ajoittaa",
    "send_now": "Lähetä nyt",
    "download": "ladata",
    "reset_default": "Palauta oletusarvo",
    "reset": "Nollaa",
    "check": "Tarkistaa",
    "cod_payment": "Postiennakko",
    "dir_payment": "Rahansiirto",
    "online_payment": "Online Maksu",
    "checkout": "Tarkista",
    "show_all": "Näytä kaikki",
    "login": "Kirjaudu sisään",
    "logout": "Kirjautua ulos",
    "more": "Lisää..",
    "collapse": "Romahdus",
    "apply_change": "Ota muutokset käyttöön",
    "apply": "Käytä",
    "add_giftcard": "Lisää lahjakortti",
    "charge": "Lataa",
    "send_invites": "Lähettää kutsuja",
    "past": "Mennyt",
    "restore": "Palauttaa",
    "cut": "Leikata",
    "get_sms_code": "Hanki todennuskoodi",
    "register_no_mail": "Jatka ilman sähköpostia",
    "no_mail_register_message": "Eikö sinulla ole sähköpostiosoitetta tai unohditko salasanasi?",
    "reset_by_mail": "Salasanan palautus sähköpostitse",
    "reset_by_sms": "Salasanan palautus tekstiviestillä",
    "cash_payment": "Käteismaksu",
    "show_chart": "Näytä kaavio",
    "open_app": "Avaa sovellus",
    "login_now": "Kirjaudu sisään nyt",
    "watch_video": "Katso video",
    "check_now": "Tarkista nyt",
    "remove_image": "Poista kuva",
    "view_website": "Avaa linkki",
    "explore": "Tutustu {name}",
    "go": "Mennä",
    "read_more": "Lue lisää",
    "start_now": "Aloita nyt – se on ilmaista",
    "view_live": "Katso livenä",
    "resend_code": "Lähetä koodi uudelleen",
    "invite": "Kutsu",
    "add_more": "Lisää enemmän",
    "install_now": "Asenna nyt",
    "uninstall": "Poista asennus",
    "show_preview": "Näytä esikatselu",
    "hide_preview": "Piilota esikatselu",
    "download_now": "Lataa nyt",
    "auto_fill": "Automaattinen täyttö",
    "track": "Seurata",
    "change_state": "Vaihda tilaa",
    "done": "Tehty",
    "reply": "Vastaa",
    "watch_now": "Katso nyt",
    "unlock": "Avata",
    "lock": "Lukko",
    "create_clone": "Luo klooni",
    "regenerate": "Luo uudelleen",
    "add_message": "Lisää viesti",
    "continue_chat": "Jatka keskustelua",
    "add_new_message": "Lisää uusi viesti",
    "change_setting": "Muuta asetuksia",
    "delete_all": "Poista kaikki",
    "transfer_fund": "Siirtorahasto",
    "reverse_fund": "Käänteinen rahasto",
    "settlement": "Ratkaisu",
    "refund": "Maksun palautus",
    "partial_refund": "Osittainen hyvitys",
    "change_payment_method": "Vaihda maksutapaa",
    "buy": "Ostaa",
    "view_all": "Näytä kaikki",
    "view_now": "Näytä nyt",
    "paste": "Liitä"
  },
  "instance_message_title": "Lähetä pikaviesti",
  "instance_message": "Hei {name}, Nimeni on {author} yrityksestä {company}.",
  "errors": {
    "419": "Olet ollut epäaktiivinen pitkään aikaan, ole hyvä <b>⟳ PÄIVITTÄ SIVU</b> turvallisuussyistä.",
    "gateway_blockchain_sync_error": "Järjestelmä ei synkronoidu lohkoketjun kanssa. Uutta tapahtumaa ei voi luoda ennen kuin palvelintemme synkronoinnit on suoritettu. Ratkaisemme ongelman.",
    "gateway_network_error": "Maksuyhdyskäytäväpalvelu on havainnut viestintäongelman."
  },
  "receiver_info": {
    "map": {
      "title": "Toimitusosoite",
      "confirm": "Aseta sijainti",
      "address_type": "Kohde",
      "receptor_type": "Vastaanotin"
    },
    "receiver_address": "Valitse toimitusosoite",
    "address": "osoite",
    "postcode": "Postinumero",
    "enter_value": "Täytä tästä",
    "address_note": "Huomautus",
    "tel": "Yhteysnumero",
    "service_address": "Valitse osoitteesi"
  },
  "weight": {
    "g": "g",
    "oz": "oz",
    "lb": "paunaa",
    "kg": "kg"
  },
  "mass_unit_name": {
    "g": "gramma",
    "oz": "Unssi",
    "lb": "Punta",
    "kg": "kilogramma"
  },
  "length": {
    "cm": "cm",
    "in": "sisään",
    "ft": "ft",
    "mm": "mm",
    "m": "m",
    "yd": "yd"
  },
  "size_unit_name": {
    "cm": "Senttimetri",
    "in": "tuuma",
    "ft": "Jalka",
    "mm": "millimetri",
    "m": "mittari",
    "yd": "Piha"
  },
  "distance": {
    "m": "mittari",
    "km": "km"
  },
  "time": {
    "days": "päivää",
    "hours": "Tuntia",
    "minutes": "Pöytäkirja",
    "seconds": "Sekuntia"
  },
  "units": [
    "Yksikkö",
    "kohde",
    "jokainen",
    "aseta",
    "pala",
    "kilogramma",
    "gramma",
    "milligramma",
    "mittari",
    "millimetri",
    "neliömetri",
    "neliömetriä",
    "kuutiometri",
    "litraa",
    "millilitra",
    "jalat",
    "gallonaa",
    "tuumaa",
    "unssia",
    "puntaa",
    "quarts",
    "jaardia",
    "huone",
    "sekuntia",
    "pöytäkirja",
    "tuntia",
    "päivää",
    "viikkoa",
    "kuukaudet",
    "vuotta"
  ],
  "region_types": {
    "State": "Osavaltio",
    "Territory": "Alue",
    "Province": "maakunta"
  },
  "transaction_status": {
    "RequireAction": "Vaatii toimenpiteitä",
    "Processing": "Käsittely",
    "Canceled": "Peruutettu",
    "Succeeded": "Onnistui"
  },
  "placeholders": {
    "name": "Jone Cox",
    "email": "oma-mail@mail.com",
    "phone": "+1 000 0000",
    "language": "Valitse kieli..",
    "friend_email": "Ystäväsi sähköposti...",
    "friend_name": "Valita. Ystäväsi nimi",
    "select_date": "Valitse päivämäärä..."
  },
  "notification": {
    "confirm": "Vahvistaa",
    "confirm_message": "Muutokset tallennettu onnistuneesti.",
    "error": "Virhe",
    "message": "Viesti",
    "caution": "Varoitus",
    "warning": "Varoitus",
    "award": "Onnittelut",
    "error_message": "Valitettavasti tapahtui virhe.",
    "congratulation": "Onnittelut",
    "coming_soon": "Pian",
    "on_fetching_data": "Tietoa vastaanotetaan..",
    "new_pwa_version": "Uusi versio saatavilla nyt. Haluatko päivittää sovelluksen?",
    "over_license_limit": "Yli lisenssirajan",
    "update_license": "Päivitä lisenssisi",
    "required": "Edellytetään",
    "invalid_email": "Virheellinen sähköpostiosoite",
    "invalid_domain": "Virheellinen verkkotunnus",
    "invalid_min_length": "Vähimmäispituuden on oltava {length}",
    "invalid_min_array_length": "Valitse vähintään {length} kohdetta",
    "invalid_max_chars": "Enintään {maxCount} merkkiä",
    "invalid_url": "Virheellinen URL",
    "country_invalid": "Valitse kohdemaa!",
    "postal_code_invalid": "Aseta kelvollinen postinumero!"
  },
  "colors": {
    "#D32F2F": "Punainen",
    "#C2185B": "Vaaleanpunainen",
    "#7B1FA2": "Violetti",
    "#512DA8": "Tumma violetti",
    "#303F9F": "Indigonsininen",
    "#1976D2": "Sininen",
    "#0288D1": "Vaaleansininen",
    "#0097A7": "Turkoosin sininen",
    "#00796B": "Hanhenvihreä",
    "#388E3C": "Vihreä",
    "#689F38": "Vaaleanvihreä",
    "#AFB42B": "Limo",
    "#FBC02D": "Keltainen",
    "#FFA000": "Keltainen",
    "#F57C00": "Oranssi",
    "#E64A19": "Kiiltävä oranssi",
    "#5D4037": "Ruskea",
    "#616161": "harmaa",
    "#455A64": "Harmaa Sininen",
    "#FFD700": "Kultainen",
    "#C0C0C0": "Hopea",
    "#b76e79": "kultainen ruusu",
    "#383838": "Mattamusta",
    "#FFFFFF": "Valkoinen",
    "#FFF": "Valkoinen",
    "#000000": "Musta",
    "#000": "Musta",
    "#7d263a": "Kastanjanruskea",
    "#FD9F17": "Kulta",
    "#229DBF": "Aqua",
    "#6DC9E2": "Aqua Triblend",
    "#413B2D": "Armeija",
    "#474747": "Asfaltti",
    "#E6195C": "Marja",
    "#B2184C": "Berry Triblend",
    "#FC7F5F": "Poltettu appelsiini",
    "#80011F": "Kardinaali",
    "#382829": "Suklaa",
    "#F06336": "Koralli",
    "#FAE7C9": "Kerma",
    "#6B2257": "Herukka",
    "#222127": "Tummanharmaa",
    "#0D5A74": "Syvä sinivihreä",
    "#00582F": "Ikivihreä",
    "#214C30": "Metsä",
    "#DC2867": "fuksia",
    "#38561F": "Kelly",
    "#5C884D": "Puun lehti",
    "#558450": "Vaalea Aqua",
    "#96B5C9": "Vaaleansininen",
    "#DCAFCE": "Liila",
    "#D3E1A4": "Lime",
    "#9DE7C2": "Minttu",
    "#F6EAD2": "Luonnollinen",
    "#1A1F35": "Laivasto",
    "#404624": "Oliivi",
    "#271020": "Luumu",
    "#A8355C": "Vadelma",
    "#D6BEA6": "Pehmeä kerma",
    "#BEA994": "Tan",
    "#0DB2AE": "Sinivihreä",
    "#A86EA9": "Violetti",
    "#36454F": "Puuhiili",
    "#b3b0ab": "hiiliharmaa",
    "#463e3d": "Charcoal Heather",
    "#282d3c": "Navy Blazer"
  },
  "address_info": {
    "name": "Nimi",
    "tel": "Puhelin",
    "email": "Sähköposti",
    "country": "Maa",
    "city": "Kaupunki",
    "state": "Osavaltio",
    "address": "osoite",
    "building_number": "Rakennuksen numero",
    "building_unit": "Yksikkö",
    "postcode": "Postinumero",
    "note": "Huomautus",
    "county": "Lääni"
  },
  "product_types": {
    "physical": "Fyysinen",
    "physical_description": "Fyysiset tuotteet, kuten matkapuhelimet, kirjat, elektroniset komponentit.",
    "virtual": "Virtuaalinen",
    "virtual_description": "Internet-ystävälliset tuotteet, kuten: latauskortti, hotellivaraukset, pelien lataus.",
    "file": "Tiedosto",
    "file_description": "Kaikki sallitut tiedostot, kuten verkkokurssivideot, ladattavat asiakirjat.",
    "service": "Palvelu",
    "service_description": "Palvelut kuten: korjaus, kuljetus, opetus.",
    "subscription": "Tilaus",
    "subscription_description": "Tilaukset ja laskutus tuotteista, palveluista tai sisällöstä."
  },
  "license": {
    "free": "Vapaa",
    "startup": "Aloittaa",
    "company": "Yhtiö",
    "enterprise": "Yritys"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "Miehelle",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW",
    "GHS": "GHS",
    "ZWD": "ZWD",
    "IQD": "IQD",
    "SYP": "SYP"
  },
  "variants": {
    "color": "Väri",
    "volume": "Koko",
    "count_in_pack": "Laske pakkauksessa",
    "weight": "Paino",
    "type": "Materiaali",
    "style": "Tyyli"
  },
  "delivery_state": {
    "check_queue": "Odotetaan arvostelua",
    "order_confirm": "Tilausvahvistus",
    "preparing_order": "Valmistellaan",
    "sent_order": "Toimitettaessa",
    "to_customer": "Toimitettu"
  },
  "status": {
    "unpaid": "Palkaton",
    "paid": "Maksettu",
    "canceled": "Peruutettu",
    "completed": "Rajattu",
    "reserved": "Varattu",
    "COD": "COD",
    "sold": "myyty",
    "open": "Avata",
    "cancel": "Peruutettu",
    "active": "Aktiivinen",
    "inactive": "epäaktiivinen",
    "debug": "Debug",
    "live": "Elää",
    "test": "Testata",
    "connected": "Yhdistetty",
    "disconnected": "Yhteys katkaistu",
    "accept": "Hyväksyä",
    "reject": "Hylätä",
    "pending": "Odottaa",
    "rejected": "Hylätty",
    "accepted": "Hyväksytty"
  },
  "dimensions": {
    "cm": "cm",
    "km": "km",
    "kg": "kg"
  },
  "transportation_type": {
    "motorbike": "Moottoripyörä",
    "motorbike_description": "Keskipainoinen muutaman kilometrin säteellä.",
    "cargo_small": "Pieni rahti",
    "cargo_small_description": "Usean kilometrin kevyt rahti.",
    "cargo": "Rahti",
    "cargo_description": "Keskipainoinen muutaman kilometrin säteellä.",
    "truck": "Kuorma-auto",
    "truck_description": "Irtotavara tai raskas lasti maan sisällä.",
    "fast_post": "Nopea Postitus",
    "fast_post_description": "Nopea postitus postin kautta.",
    "post": "Normaali postaus",
    "post_description": "Tavallinen postitus postin kautta.",
    "airplane": "Lentoposti",
    "airplane_description": "Kotimaiset ja ulkomaiset kevyet ja keskisuuret lastit.",
    "bicycle": "Puhdista lähetys",
    "bicycle_description": "Kevyt rahti muutaman sadan jaardin säteellä ei-moottoriajoneuvoista.",
    "global": "Globaali liikenne",
    "global_description": "Toimitus ulkomaille lentäen, meritse tai maalla.",
    "pickup": "Noukkia",
    "pickup_description": "Asiakkaat noutavat tuotteet fyysisestä myymälästäsi tai varastostasi."
  },
  "article": {
    "login_to_see_error": "Kirjaudu sisään päästäksesi artikkeliin",
    "create_new_action": "Luo uutta sisältöä",
    "menu_title": "Valikko",
    "menu": {
      "edit": "Muokkausmoodi",
      "view_mode": "Katselutila",
      "delete": "Poista artikkeli"
    },
    "schedule_action": "Haluatko ajoittaa julkaisun?",
    "schedule_title": "Ajoita automaattinen julkaisu",
    "edit_mode": "Muokata",
    "public_view_mode": "Julkinen näkymä",
    "publish_at": "Julkaise osoitteessa",
    "published": "Julkaistu",
    "draft": "Luonnos",
    "saving": "Tallentaa",
    "save_and_publish_action": "Tallenna ja julkaise",
    "save_draft_action": "Tallenna luonnos",
    "private": "Yksityinen",
    "public": "Julkinen",
    "category_input": "Kategoria",
    "category_input_message": "Valitse artikkeliluokka",
    "parent_input": "Vanhempi luokka",
    "parent_input_message": "Valitse isän sisältö",
    "schedule_input": "Ajoittaa",
    "schedule_input_placeholder": "Jos haluat tarinan julkaistavan tiettyyn aikaan.",
    "schedule_view_action": "Näytä julkaisuaikataulu",
    "author_title": "Kirjoittanut",
    "read_time": "Opiskeluaika",
    "read_time_unit": "Pöytäkirja",
    "claps_action": "Taputuksia",
    "claps": "Taputuksia",
    "likes": "Kuten",
    "about_author": "Kirjailijasta",
    "updated_at": "Päivitetty",
    "wrote_at": "Kirjoitettu klo",
    "now": "Nyt",
    "follow_action": "Seuraa",
    "followed": "seurannut",
    "report_and_delete_action": "Ilmoita ja poista tämä artikkeli",
    "report_action": "Ilmoita väärinkäytöstä",
    "you_reported_this_article": "Tässä artikkelissa on jo väärinkäyttöraportti.",
    "add_to_publication_action": "Lisää julkaisuun",
    "author_socials": "Kirjoittaja sosiaalisessa mediassa",
    "share": "Jaa",
    "report_dialog": {
      "report_and_delete_title": "Ilmoita väärinkäytöstä ja poista sisältö",
      "report_title": "Ilmoita tästä sisällöstä loukkaavaksi",
      "message": "Mikä on syy tämän sisällön lähettämiseen? Valitse yksi seuraavista vaihtoehdoista.",
      "accept_and_delete_action": "Vahvista ja poista sisältö"
    },
    "schedule_dialog": {
      "title": "Sisällön julkaisuaikataulu",
      "publish_at": "Julkaise osoitteessa",
      "last_edit": "Viimeisin muokkaus",
      "view_action": "Katso artikkeli"
    },
    "notifications": {
      "update_success_title": "Lähetä tiedot",
      "update_success": "Artikkelin päivitys onnistui.",
      "update_error": "Annetut tiedot eivät kelpaa.",
      "delete_error": "Et voi poistaa tätä artikkelia!",
      "report_and_delete_success_title": "Ilmoita ja poista",
      "report_and_delete_success_message": "Artikkelin poistaminen onnistui.",
      "report_success_title": "Raportoi artikkeli",
      "report_success_message": "Raporttisi tästä artikkelista on julkaistu."
    },
    "alert": {
      "delete_article": {
        "title": "Poista artikkeli",
        "message": "Haluatko varmasti poistaa tämän artikkelin pysyvästi?",
        "action": "Poistaa"
      }
    },
    "edit_window": {
      "title": "Valitse Kuvateksti ja yhteenveto",
      "digest": "Yhteenveto"
    },
    "editor": {
      "title_placeholder": "Otsikko..",
      "body_placeholder": "Kirjoita mahtavaa sisältöä..",
      "accept_file_types_error": "Tätä tiedostomuotoa ei voida hyväksyä:",
      "max_file_size_error": "Tämä tiedosto on liian suuri:",
      "notifications": {
        "image_uploaded_success": "Kuvan tallennus onnistui",
        "image_uploaded_failed": "Virhe kuvan lataamisessa."
      },
      "embed_placeholder": "Syötä iframe-koodi, Facebook, Youtube tai mikä tahansa muu URL-osoite ja paina enter.",
      "embed_caption_placeholder": "Kirjoita otsikko (valinnainen)",
      "images_caption_placeholder": "Anna tälle kuvalle otsikko.."
    }
  },
  "article_report": {
    "inappropriate": "Tämän artikkelin sisältö on sopimatonta.",
    "fake": "Tämä on väärennös ja petollinen.",
    "spam": "Tämä kohde on lähetetty roskapostiksi ja kopioitu.",
    "scam": "Tämän voidaan odottaa aiheuttavan haittaohjelmia, viruksia tai järjestelmän kaatumisen.",
    "hacked": "Tämä sivusto näyttää olevan hakkeroitu.",
    "offensive": "Kielen sisältö ja sanasto on epäeettistä ja epäkunnioittavaa.",
    "violent": "Mielestäni tämä sisältö sisältää pornografiaa ja rikkoo lakeja.",
    "harassment": "Minusta tämä on rasistista.",
    "hate": "Mielestäni tässä on kyse väkivallan edistämisestä.",
    "infringe": "Tämä loukkaa oikeuksiani."
  },
  "comments": {
    "new_action": "Klikkaa jättääksesi kommentin..",
    "title": "Kommentit",
    "body_placeholder": "Kommenttisi tai viestisi",
    "send_action": "Lähetä kommentti",
    "body_is_empty_error": "Kommentti on tyhjä!",
    "comments": "Kommentit",
    "no_comments": "Kirjoita ensimmäinen kommentti...",
    "load_more_action": "Lisää kommentteja..",
    "cant_send_comment": "Et voi lisätä uutta viestiä.",
    "cant_remove_this_comment": "Et voi poistaa tätä kommenttia!",
    "product_buyer": "Ostaja",
    "delete_alert": {
      "title": "Poista kommentti",
      "message": "Haluatko poistaa tämän kommentin?",
      "action": "Poistaa"
    },
    "notifications": {
      "delete_success": "Kommenttisi poisto onnistui."
    },
    "first_send": "Ensimmäinen postaus",
    "comment_at": "Päällä",
    "edit_comment": "Muokkaa kommenttia",
    "my_comments": "Omat kommentit"
  },
  "customer_club": {
    "bronze": "Pronssi",
    "silver": "Hopea",
    "gold": "Kultainen",
    "platinum": "Platina",
    "diamond": "Timantti"
  },
  "application_categories": {
    "tracking": "Käyttäjän käyttäytymisen tarkistaminen",
    "payment": "Maksu",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "Kuljetus",
    "automation": "Automaatio",
    "inventory": "Varastointi",
    "accounting": "Kirjanpito",
    "marketing": "Markkinointi",
    "advertising": "Mainonta",
    "staff": "Henkilökunta",
    "incentive": "Kannustimet",
    "shop": "Myymälä"
  },
  "social_network": {
    "instagram": "Instagram",
    "telegram": "Telegram",
    "googleplay": "GooglePlay",
    "appstore": "Sovelluskauppa",
    "twitter": "Viserrys",
    "linkedin": "Linkedin",
    "medium": "Keskikokoinen",
    "selldone": "myyty valmis",
    "facebook": "Facebook",
    "pinterest": "Pinterest",
    "whatsapp": "WhatsApp",
    "skype": "Skype",
    "facebook_messenger": "Facebook Messenger"
  },
  "form_builder": {
    "add_item_action": "Lisää uusi kohde",
    "title_input": "Otsikko",
    "name_input": "Muuttujan nimi",
    "value_input": "Arvot",
    "value_input_message": "Käyttäjän asetusluettelo",
    "default": "Oletusarvo",
    "types": {
      "simple": "Yksinkertainen",
      "selective": "Valikoiva",
      "switch": "Vaihtaa",
      "file": "Tiedosto",
      "number": "Määrä"
    },
    "placeholder_input": "Paikanpitäjä",
    "file_type_input": "Hyväksytyt tiedostotyypit",
    "file_type_message": "jpeg, png, zip,..."
  },
  "virtual_order_info_summery": {
    "title": "tuotteen nimi",
    "reserved_at": "rekisteröinti päivämäärä",
    "total_price": "Kokonaismäärä",
    "discount": "Alennus",
    "final_price": "Lopullinen määrä",
    "payment_status": "Maksun tilanne",
    "payment_status_waiting": "odottaa maksua",
    "payment_status_paid": "Maksettu",
    "buyer": "Ostaja"
  },
  "virtual_item_info": {
    "title": "Virtuaalinen kohde",
    "outputs": {
      "title": "Tulostustiedot",
      "sub_title": "Tämän kohteen luottamukselliset tiedot",
      "message": "Nämä tiedot näytetään käyttäjälle tuotteen ostamisen jälkeen."
    },
    "inputs": {
      "title": "Tietoa tarvitaan",
      "sub_title": "Ostajan tiedot vaaditaan",
      "message": "Ostajan tulee syöttää pyydetyt tiedot lomakkeeseen"
    },
    "notifications": {
      "inputs_set_success": "Tietolomake rekisteröity onnistuneesti.",
      "confirm_by_admin_success": "Tilauksen valmistuminen vahvistettu.",
      "confirm_by_buyer_success": "Tilauksen valmistuminen vahvistettu."
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "Tätä tilausta ei voida hyväksyä COD-maksulla.",
    "payment_returned": "Asiakkaan maksama maksu palautetaan.",
    "payment_fraud": "Maksu on todettu petokseksi.",
    "location_out_of_service": "Asiakkaan sijainti ei ole käytössä.",
    "user_not_responding": "Asiakas ei vastannut puheluihin.",
    "shop_owner_fault": "Liikkeen henkilökunnalla tapahtui virhe tietojen täyttämisessä.",
    "lack_of_inventory": "Loppu varastosta.",
    "legal_restriction": "Tilausta ei voida tehdä lakisääteisten rajoitusten vuoksi.",
    "pricing_fault": "Myyjän hinnoitteluvirhe.",
    "system_fault": "Järjestelmävirhe."
  },
  "basket_order_info_summery": {
    "receiver": "Vastaanotin",
    "phone": "Puh",
    "reserved_date": "Ostopäivä",
    "total_price": "Kokonaismäärä",
    "discount": "Alennus",
    "final_price": "Lopullinen määrä",
    "address": "Toimitusosoite",
    "payment_status": "Maksun tilanne"
  },
  "basket_status": {
    "open": "Avata",
    "reserved": "Varattu",
    "paid": "Maksettu",
    "canceled": "Peruutettu",
    "cod": "Maksa toimituksen yhteydessä",
    "receipt_added": "Kuitti lisätty",
    "payment_processing": "Maksunkäsittely"
  },
  "basket_delivery_state": {
    "rejected": "Hylätty",
    "reject_reason_not_found": "Syy on tuntematon.",
    "step_1": "Arvostelu",
    "step_2": "Vahvistus",
    "step_3": "Valmistautuminen",
    "step_4": "Toimitettaessa",
    "step_5": "Toimitettu"
  },
  "basket_return_request_view": {
    "title": "Palautuspyyntö",
    "delivery_date": "Toimituspäivä",
    "return_date": "Pyydä päivämäärä",
    "items_count": "Palautetut tuotteet lasketaan",
    "items_count_unit": "tuote(t)",
    "reason": "Syy",
    "description": "Kuvaus",
    "status": "Tila",
    "download_image": "Lataa kuva",
    "download_film": "Lataa video",
    "download_voice": "Lataa ääni",
    "accept_by_admin_action": "Hyväksy pyyntö",
    "reject_by_admin_action": "Hylkää pyyntö",
    "message_for_admin": "Selldonea käyttämällä hyväksymäsi sopimuksen mukaan sinun tulee ottaa yhteyttä ostajaan ja pitää hänet ajan tasalla tilauksensa palautusprosessista. Tämä on tehtävä, jos pyyntö hyväksytään tai hylätään ja ostajan täydellinen suostumus on saatu.",
    "notifications": {
      "update_status_success": "Pyynnön tila päivitetty."
    }
  },
  "basket_list": {
    "return_count": "Palautus: {count} numero",
    "table": {
      "row": "Rivi",
      "image": "Kuva",
      "product_name": "Tuote",
      "variant": "Variantti",
      "warranty": "Takuut",
      "count": "Kreivi",
      "price": "hinta"
    }
  },
  "return_request_list": {
    "count": "Viitenumero",
    "return_warranty": "Rahat takaisin takuu",
    "return_warranty_unit": "päivä(t)",
    "table": {
      "code": "Tilauskoodi",
      "product": "Tuote",
      "delivery_at": "Vastaanottopäivämäärä",
      "state": "Tila",
      "reason": "Syy",
      "return_warranty_period": "Takuuaika"
    }
  },
  "data_toolbar": {
    "search": "Hae",
    "sort_by": "Järjestä",
    "count_item": "Näytä {item} kohdetta"
  },
  "sort": {
    "created_at": "Luo päiväys",
    "updated_at": "Muokkaa päivämäärää",
    "title": "Otsikko",
    "description": "Kuvaus",
    "like": "Suosio",
    "power": "Taputuksia",
    "product_type": "Tuotetyyppi",
    "discount": "Alennus",
    "rate": "Luokitus",
    "rate_count": "Arvioiden määrä",
    "category": "Kategoria",
    "product": "Tuote",
    "body": "Sisältö",
    "card_type": "Korttityyppi",
    "card_number": "Kortin numero",
    "balance": "Saldo",
    "paid": "Käytetty summa",
    "currency": "Valuutta",
    "expire_at": "Päättymispäivä",
    "discount_code": "Alennuskoodi",
    "discount_percent": "Alennus",
    "discount_limit": "Alennusraja",
    "max_count": "Enimmäismäärä",
    "used_count": "Käytetty",
    "start_date": "Aloituspäivämäärä",
    "end_date": "Päättymispäivä",
    "total_discount_amount": "Alennukset yhteensä",
    "initial_charge": "Alkuveloitus",
    "total_count": "Lopullinen määrä",
    "amount_paid": "Maksettu summa",
    "name": "Nimi",
    "published": "Julkaistu",
    "visits": "Vierailut",
    "color": "Väri",
    "landing_page": "Aloitussivu",
    "enable": "ota käyttöön",
    "fix_commission": "Kiinteä provisio",
    "percent_commission": "Prosenttipalkkio",
    "payment_at": "Maksupäivä",
    "issued_at": "Julkaisupäivämäärä",
    "payment": "Maksu",
    "website": "Verkkosivusto",
    "email": "Sähköposti",
    "user": "Käyttäjä",
    "code": "Koodi",
    "schedule_at": "Aikataulu päivämäärä",
    "sender": "Lähettäjä",
    "in_que": "Jonossa",
    "sent": "Lähetetty",
    "shop": "Myymälä",
    "quantity": "Määrä",
    "amount": "Määrä",
    "jobs": "Työt lasketaan",
    "success": "Onnistumisen määrä",
    "fail": "Epäonnistuneiden määrä",
    "distance": "Etäisyys",
    "duration": "Kesto",
    "reset_at": "Nollaa päivämäärä",
    "delivery_person": "Henkilö",
    "delivery_service": "Palvelu",
    "date": "Päivämäärä",
    "order": "Tilaus",
    "order_id": "tilausnumero",
    "status": "Tila",
    "price": "hinta",
    "count": "Kreivi",
    "final_price": "Lopullinen hinta",
    "charge": "Lataa",
    "mention": "Mainita",
    "officer": "upseeri",
    "registered": "Rekisteröity",
    "purchased": "Osti",
    "sex": "Sukupuoli"
  },
  "search_box": {
    "result": "Hakutulokset",
    "tips": "Hae tuotteita ja kategorioita",
    "label": "Hae ...",
    "category": "Kategoria"
  },
  "lead_status": {
    "physical_fast_delivery": "Välitön toimitus",
    "physical_under_24h_delivery": "Toimita seuraavan {lead} tunnin kuluessa",
    "physical_over_24h_delivery": "Valmistellaan ja lähetetään seuraavan {days} päivän kuluttua",
    "virtual_fast_prepare": "Välitön toimitus",
    "virtual_under_24h": "Valmistuu seuraavan {lead} tunnin kuluessa",
    "virtual_over_24h": "Tehdään seuraavan {days} päivän jälkeen"
  },
  "return_request_state": {
    "pending": "Odottaa",
    "accepted": "Vahvistettu",
    "rejected": "Hylätty"
  },
  "return_order_reason": {
    "physical": {
      "U1": "Tuote ei täsmää",
      "U2": "Ei tuotetta lähetyspakkauksessa",
      "U3": "Pakkauksen tai tuotteen rikkoutuminen",
      "U4": "Pakkauksen tai sarjanumeron peukalointi",
      "U5": "Osa paketista puuttuu",
      "U6": "Tuote ei ole alkuperäinen",
      "U7": "Tuote ei täytä spesifikaatioita"
    }
  },
  "image_uploader": {
    "label": "Vedä ja pudota tai <u>valitse tiedosto</u>",
    "max_size": "Suurin sallittu koko: {size}"
  },
  "timespan": {
    "Morning": "klo 8-12",
    "Evening": "klo 12-18",
    "Night": "klo 18-12",
    "Instant": "Pikapostitus"
  },
  "week_day": {
    "Saturday": "lauantaina",
    "Sunday": "sunnuntai",
    "Monday": "maanantai",
    "Tuesday": "tiistai",
    "Wednesday": "keskiviikko",
    "Thursday": "torstai",
    "Friday": "perjantai"
  },
  "payment_form": {
    "title": "Valitse Maksutapa",
    "gift_cards_input": "Lahjakortit",
    "gift_cards_input_empty": "Lahjakortteja ei löytynyt..",
    "more": "Muut",
    "pay_amount_by_gift_cards": "Veloita Korttimaksu",
    "select_payment_method": "Valitse maksutapasi seuraavista vaihtoehdoista.",
    "payment_amount_remained": "Jäljellä oleva maksusumma",
    "payment_amount": "Maksettu summa",
    "all_paid_by_gift_cards": "Onnittelut, sinun ei tarvitse maksaa tästä tilauksesta. Paina lahjakorttimaksunäppäintä.",
    "pay_by_gift_cards_action": "Maksa tilaus maksukortilla",
    "order_free_payment": "Onnittelut, tilauksesi on ilmainen!",
    "order_free_payment_action": "Tilaa nyt ilmaiseksi",
    "qr": {
      "address": "Maksuosoite",
      "amount": "Määrä"
    }
  },
  "discount_input": {
    "limit": "{percent}% alennus enintään {limit} {currency}",
    "action": "Lisää alennuskoodi",
    "code_input": "Alennuskoodi",
    "notifications": {
      "add_success": "Onnittelut, voimassa oleva alennuskoodi."
    }
  },
  "gift_card": {
    "inactive": "Kortti on poistettu käytöstä",
    "expire": "Vanheneminen",
    "transfer": "Siirtää",
    "send_to_friend": "Lähetä ystävälle"
  },
  "count_down": {
    "days": "Päivä",
    "hours": "Tunnin",
    "minutes": "Pöytäkirja",
    "seconds": "Sekuntia"
  },
  "gift_status": {
    "Unpaid": "odottaa kuittia",
    "Paid": "Maksettu",
    "Rejected": "Hylätty",
    "Canceled": "Peruutettu"
  },
  "gift_program_status": {
    "Airdrop": "Maksujärjestelmä",
    "Advertising": "Mainonta",
    "PersonalGift": "Henkilökohtainen lahja",
    "ShopGift": "Lahja kauppa"
  },
  "currency_selector": {
    "label": "Valuutta"
  },
  "need_login": {
    "title": "Kirjaudu sisään",
    "login_sms": "SMS-kirjautuminen",
    "login_google": "Kirjaudu sisään Googlella",
    "login_facebook": "Kirjaudu Facebookilla",
    "login_account": "Kirjautuminen Selldonen kautta",
    "register": "Uusi käyttäjä? Rekisteröidy nyt.",
    "mobile_input": "Anna matkapuhelimesi",
    "verification_code": "Vahvistuskoodi",
    "msg_title": "Moi,",
    "msg_body": "Kirjaudu sisään, ole hyvä. Se kestää vain muutaman sekunnin.",
    "login_apple": "Kirjaudu sisään Applella",
    "login_email": "Kirjaudu sisään sähköpostilla",
    "email_login_step_1": "Anna voimassa oleva sähköpostiosoite, niin lähetämme siihen kirjautumiskoodin. Rekisteröintiä ei tarvita.",
    "email_login_step_2": "Oletko varma, että olet kirjoittanut sähköpostiosoitteesi oikein? Lähetämme kirjautumiskoodin antamaasi sähköpostiosoitteeseen, joten varmistathan sen oikeellisuuden.",
    "email_login_step_3": "Olemme lähettäneet koodin sähköpostiisi. Huomaa, että koodi vanhenee 10 minuutin kuluttua."
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "5 vuoden kultakauppa"
    },
    "GOLDEN_2YEAR": {
      "name": "4 vuoden kultakauppa"
    },
    "GOLDEN_3YEAR": {
      "name": "3 vuoden kultakauppa"
    },
    "GOLDEN_4YEAR": {
      "name": "2 vuoden kultakauppa"
    },
    "GOLDEN_5YEAR": {
      "name": "1 vuoden kultakauppa"
    },
    "TOKEN_OWNER_1M": {
      "name": "Kultainen sijoittaja"
    },
    "TOKEN_OWNER_10M": {
      "name": "Timanttisijoittaja"
    },
    "TOKEN_OWNER_100M": {
      "name": "Ruby sijoittaja"
    },
    "COMMUNITY_LOYAL": {
      "name": "Viestintäverkkojen ylimmän yhteisön jäsen"
    },
    "GOLD_SUPPLIER": {
      "name": "Kullan toimittaja"
    },
    "GOLD_SELLER": {
      "name": "Kultakauppias"
    },
    "CONTENT_SUPERMAN": {
      "name": "Huippusisällöntuottaja"
    },
    "NINJA": {
      "name": "Ninja"
    },
    "STAR": {
      "name": "Tähti"
    },
    "GUARDIAN": {
      "name": "Loistava asiakaspalvelu"
    },
    "KING": {
      "name": "Markkinoiden kuningas"
    }
  },
  "cookie": {
    "title": "Tämä sivusto käyttää evästeitä",
    "message": "Tämä sivusto käyttää evästeitä parantaakseen käyttökokemusta. Käyttämällä verkkosivustoamme hyväksyt kaikki evästeet evästekäytäntömme mukaisesti.",
    "preferences_action": "Hallinnoi asetuksia",
    "agree_action": "Olen samaa mieltä"
  },
  "basket_item_message": {
    "title": "Vaaditut tiedot tälle kohteelle",
    "save_actions": "Tallenna viesti",
    "notifications": {
      "success": "Syöttötietosi on tallennettu."
    },
    "product_inputs_preview_message": "Nämä mukautusvaihtoehdot ovat käytettävissä tilaamallesi tuotteelle. Kun tuote on lisätty ostoskoriin, voit tehdä muutoksia täällä."
  },
  "faq": {
    "faq": "Usein Kysytyt Kysymykset",
    "title": "Kysymykset ja vastaukset",
    "sub_title": "Mitä pyysit meitä tekemään.",
    "message": "Etsi vastaus kysymykseesi alla olevista vastauksista. Kysy meiltä, jos kysymyksiä ei löydy.",
    "add_question_action": "Kysy Uusi Kysymys",
    "read_more": "Lue lisää ..",
    "load_more": "Lisää kysymyksiä ..",
    "main_page": "FAQ Pääsivu",
    "add_new": "Lähetä uusi kysymys",
    "login_alert": "Kirjaudu sisään kysyäksesi kysymyksen.",
    "question_input": "Kysymys",
    "question_input_placeholder": "Esitä kysymyksesi.",
    "notifications": {
      "success_add": "Kysymyksesi lähetys onnistui."
    }
  },
  "rating_labels": [
    "Todella paha",
    "Huono",
    "Normaali",
    "Hyvä",
    "Erinomainen"
  ],
  "map_view": {
    "address_detail": "Osoitetiedot",
    "change": "Muuttaa",
    "select": "Valitse",
    "not_found_address": "Arvoa ei löytynyt",
    "enter_address_hint": "Syötä kohdeosoite",
    "enter_your_address": "Kirjoita osoitteesi.",
    "postal_code": "Postinumero",
    "phone_input": "Puhelin {type}",
    "building_number": "Rakennuksen numero",
    "building_unit": "Yksikkö",
    "full_name_input": "Koko nimi {type}",
    "save_detail_action": "Tallenna tiedot",
    "more_detail_input": "Lisää kuvausta",
    "add_address_to_list": "Lisää osoite luetteloon",
    "address_title_input": "Osoitetarra (pakollinen)",
    "notifications": {
      "save_in_list": "Tämä osoite on tallennettu luetteloosi kaikkine tiedoineen.",
      "edit_success": "Uudet osoitearvot tallennettu kansioon {title}."
    },
    "delete_address_dialog": {
      "title": "Poista osoite",
      "message": "Haluatko varmasti poistaa tämän osoitteen?",
      "action": "Poista osoite"
    }
  },
  "comment_manager": {
    "can_not_edit": "Tätä kommenttia ei voi muokata!",
    "comment_input_empty": "Viestin teksti on tyhjä!",
    "article_not_saved": "Tallenna artikkeli!"
  },
  "wheel_fortune": {
    "title": "Pelaa & Voita",
    "message": "Jokaisen pelin hinta on 10 pelimerkkiä. Sinulla on tällä hetkellä {chips} pelimerkki. Hanki lisää sirua ostamalla kaupasta.",
    "win_message": "Onnittelut, sinä voitat!",
    "lost_message": "Anteeksi, hävisit pelin.",
    "try_again": "Voit yrittää uudelleen"
  },
  "json": {
    "add": "Lisää rakennetiedot",
    "add_message": "Luo uusia rakennetietoja",
    "structures": "Rakenteet",
    "book": {
      "title": "Kirja",
      "desc": "Kirjatoiminnot, joiden avulla käyttäjät voivat ostaa löytämänsä kirjan suoraan hakutuloksista."
    },
    "occupation": {
      "title": "Arvioitu palkka",
      "desc": "Googlen työnhakukokemuksessa näkyvät tiedot palkkaarvioista, kuten palkka-alueet ja aluekohtaiset palkkakeskiarvot työtyypeille."
    },
    "course": {
      "title": "Kurssi",
      "desc": "Koulutuskurssit, jotka näkyvät tarjoajakohtaisessa luettelossa. Kurssit voivat sisältää kurssin nimen, järjestäjän ja lyhyen kuvauksen."
    },
    "howto": {
      "title": "Miten",
      "desc": "Ohje opastaa käyttäjiä videon, kuvien ja tekstin avulla suoritettavien vaiheiden läpi."
    },
    "recipe": {
      "title": "Resepti",
      "desc": "Reseptit, jotka näkyvät yksittäisinä rich-tuloksena tai osana isäntäkarusellia."
    }
  },
  "support": {
    "Financial": "Taloudellinen",
    "Technical": "Tekninen",
    "Advisor": "Neuvonantaja"
  },
  "condition": {
    "new": "Uusi",
    "refurbished": "Kunnostettu",
    "used": "Käytetty",
    "used_fair": "Käytetty reilu",
    "used_good": "Käytetty hyvä",
    "used_like_new": "Käytetty - kuin uusi"
  },
  "variant_filter": {
    "title": "Tuoteversion suodatin",
    "only_available": "Varastossa"
  },
  "service": {
    "task": {
      "title": "Tehtävät",
      "message": "Luettelo tässä palvelussa suoritetuista tehtävistä."
    },
    "appointment": {
      "title": "Nimittäminen",
      "message": "Valitse seuraavista kellonajat sinulle sopivan päivän ja tunnin mukaan."
    },
    "booking": {
      "title": "Varaus",
      "message": "Määritä alla olevaan kalenteriin niiden päivien ajanjakso, joille haluat tehdä varauksen."
    },
    "subscription": {
      "title": "Tilaus"
    },
    "charge": {
      "title": "Lataa"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "Kiinteä hinnoittelu",
      "message": "Tällaisessa hinnoittelussa tuotteen hinta on kiinteä summa, eikä ostajan tarvitse pyytää hintalaskelmaa."
    },
    "ESTIMATION": {
      "title": "Arvioitu hinnoittelu",
      "message": "Tuotteiden ja palveluiden hinnan laskee jossain määrin myyjä tilauksen yhteydessä, maksulaskuja voidaan muuttaa tai lisätä palvelun aikana."
    },
    "AGREEMENT": {
      "title": "Sopimuksen hinnoittelu",
      "message": "Myyjä ei muuta tuotteiden tai palveluiden lopullista hintaa tilauksen tekemisen jälkeen."
    },
    "BID": {
      "title": "Tarjous/huutokauppa",
      "message": "Tuote myydään potentiaalisten ostajien korkeimmalla tarjotulla hinnalla."
    }
  },
  "map": {
    "title": "Tuotteiden vastaanottamisen kohde",
    "confirm": "Aseta sijainti",
    "address": "Kohde",
    "receptor": "Vastaanotin"
  },
  "ShopBots": {
    "telegram": "Telegram"
  },
  "article_tags": {
    "title": "Sisältötunnisteet",
    "tags_input": "Tunnisteet",
    "tags_input_message": "Tunnisteet Tämän artikkelin luettelo",
    "notification": {
      "add_success": "Tunnisteet lisätty"
    }
  },
  "difficulties": {
    "very_complicated": "Erittäin monimutkainen",
    "hard": "Kovaa",
    "intermediate": "Keskitason",
    "easy": "Helppo"
  },
  "billing_period": {
    "Daily": "Päivittäin",
    "Weekly": "Viikoittain",
    "Monthly": "Kuukausittain",
    "Every3Months": "3 kuukauden välein",
    "Every6Months": "6 kuukauden välein",
    "Yearly": "Vuosittain"
  },
  "buyer_rating_statement": {
    "between1_2": "Oi ei hyvä!",
    "between2_3": "Se on okei!",
    "between3_4": "Ihmiset pitävät siitä!",
    "between4_5": "Ihmiset rakastavat sitä!"
  },
  "seasons": {
    "spring": "kevät",
    "summer": "Kesä",
    "autumn": "Syksy",
    "winter": "Talvi"
  }
};