export default {
  "currency_default": "USD",
  "language_default": "en",
  "selldone": "સેલડન",
  "store": "દુકાન",
  "not_exist": "અસ્તિત્વમાં નથી",
  "error": "ભૂલ",
  "active": "સક્રિય",
  "inactive": "નિષ્ક્રિય",
  "required_value": "જરૂરી મૂલ્યો",
  "original_warranty": "મૂળ ઉત્પાદન ગેરંટી",
  "return_warranty_days": "{days} પરત કરવાની ગેરંટી દિવસ(ઓ)",
  "no_return_warranty": "વળતર નહીં",
  "reed_agree_terms": "મેં ઉપયોગની શરતો અને ગોપનીયતા નીતિ વાંચી છે અને તેમની સાથે સંમત છું.",
  "commons": {
    "Currency": "ચલણ",
    "COD": "COD",
    "State": "રાજ્ય",
    "Price": "કિંમત",
    "order_price": "ઓર્ડરની રકમ",
    "VAT": "VAT",
    "Discount": "ડિસ્કાઉન્ટ",
    "In_Stock": "ઉપલબ્ધ છે",
    "Variants": "ચલો",
    "No_variants": "કોઈ પ્રકાર નથી",
    "all": "બધા",
    "today": "આજે",
    "yesterday": "ગઇકાલે",
    "license": "લાઇસન્સ",
    "home": "ઘર",
    "support": "આધાર",
    "messages": "સંદેશાઓ",
    "no_message": "કોઈ સંદેશ નથી",
    "empty": "ખાલી",
    "phone": "ફોન",
    "address": "સરનામું",
    "name": "નામ",
    "password": "પાસવર્ડ",
    "email": "ઈમેલ",
    "mobile": "મોબાઈલ",
    "login": "પ્રવેશ કરો",
    "register": "નોંધણી કરો",
    "select_account": "એકાઉન્ટ પસંદ કરો",
    "online": "ઓનલાઈન",
    "offline": "ઑફલાઇન",
    "finish": "સમાપ્ત કરો",
    "finished": "સમાપ્ત",
    "preview": "પૂર્વાવલોકન",
    "free": "મફત",
    "free_completely": "સંપૂર્ણપણે મફત સબ્સ્ક્રિપ્શન",
    "fee": "ફી",
    "month": "માસ",
    "months": "મહિનાઓ",
    "faq": "વારંવાર પૂછાતા પ્રશ્નો",
    "question": "પ્રશ્ન",
    "answer": "જવાબ આપો",
    "create_date": "તારીખ બનાવો",
    "update_date": "અપડેટ તારીખ",
    "start_date": "પ્રારંભ તારીખ",
    "end_date": "અંતિમ તારીખ",
    "social": "સામાજિક",
    "total": "કુલ",
    "orders": "ઓર્ડર",
    "sessions": "સત્રો",
    "product_views": "ઉત્પાદન દૃશ્યો",
    "add_to_carts": "ગાડામાં ઉમેરો",
    "checkouts": "ચેકઆઉટ",
    "payments": "ચુકવણી",
    "organic_search": "ઓર્ગેનિક શોધ",
    "other": "અન્ય",
    "landing_page": "લેન્ડિંગ પેજ",
    "discount_code": "ડિસ્કાઉન્ટ કોડ",
    "total_sell": "કુલ વેચાણ",
    "details": "વિગતો",
    "currency": "ચલણ",
    "amount": "રકમ",
    "published": "પ્રકાશિત",
    "draft": "ડ્રાફ્ટ",
    "save_changes": "ફેરફારો સંગ્રહ",
    "source": "સ્ત્રોત",
    "medium": "મધ્યમ",
    "url": "યુઆરએલ",
    "revenue": "આવક",
    "performance": "પ્રદર્શન",
    "term": "મુદત",
    "content": "સામગ્રી",
    "session": "સત્ર",
    "product": "ઉત્પાદન",
    "add": "ઉમેરો",
    "checkout": "ચેકઆઉટ",
    "payment": "ચુકવણી",
    "more_options": "વધુ વિકલ્પ",
    "full_name": "પૂરું નામ",
    "tel": "ટેલ",
    "about_me": "મારા વિશે",
    "request_checking": "ચકાસણીની વિનંતી કરો",
    "passport": "પાસપોર્ટ",
    "birthday": "જન્મદિવસ",
    "country": "દેશ",
    "city": "શહેર",
    "gender": "જાતિ",
    "offer": "ઓફર",
    "website": "વેબસાઈટ",
    "apply_for_all_products": "∞ તમામ ઉત્પાદનો માટે અરજી કરો",
    "fix_commission": "નિશ્ચિત કમિશન",
    "percent_commission": "ટકાવારી કમિશન",
    "fixed_discount": "નિશ્ચિત ડિસ્કાઉન્ટ",
    "discount_percentage": "ટકાવારી ડિસ્કાઉન્ટ",
    "discount_limit": "ડિસ્કાઉન્ટ મર્યાદા",
    "no_code": "કોઈ કોડ નથી",
    "max_count": "મહત્તમ ગણતરી",
    "count_unit": "વસ્તુઓ",
    "used": "વપરાયેલ",
    "daily": "દૈનિક",
    "monthly": "માસિક",
    "yearly": "વાર્ષિક",
    "state": "સ્થિતિ",
    "disable": "અક્ષમ કરો",
    "enable": "સક્ષમ કરો",
    "activation_code": "સક્રિયકરણ કોડ",
    "quantity": "જથ્થો",
    "no_club": "કોઈ ક્લબ નથી",
    "per_order": "ઓર્ડર દીઠ",
    "count": "ગણતરી",
    "seconds": "સેકન્ડ",
    "auto": "ઓટો",
    "title": "શીર્ષક",
    "message": "સંદેશ",
    "width": "પહોળાઈ",
    "length": "લંબાઈ",
    "height": "ઊંચાઈ",
    "label": "લેબલ",
    "click": "ક્લિક કરો",
    "bank": "બેંક",
    "default": "ડિફૉલ્ટ",
    "role": "ભૂમિકા",
    "user": "વપરાશકર્તા",
    "users": "વપરાશકર્તાઓ",
    "code": "કોડ",
    "total_payment": "કુલ ચુકવણી",
    "balance": "સંતુલન",
    "chance": "તક",
    "free_for_new_users": "નવા વપરાશકર્તાઓ માટે મફત",
    "prize_amount": "ઈનામની રકમ",
    "win": "જીત",
    "gift_card": "ભેટ કાર્ડ",
    "discount": "ડિસ્કાઉન્ટ",
    "config": "રૂપરેખા",
    "prize": "ઇનામ",
    "Prizes": "ઈનામો",
    "result": "પરિણામ",
    "price": "કિંમત",
    "lottery": "લોટરી",
    "coupon": "કૂપન",
    "customer_club": "ગ્રાહક ક્લબ",
    "shipping": "વહાણ પરિવહન",
    "sum": "સરવાળો",
    "not_paid": "ચુકવેલ નહી",
    "category": "શ્રેણી",
    "done": "થઈ ગયું",
    "email_from": "થી",
    "subject": "વિષય",
    "schedule": "અનુસૂચિ",
    "files_list": "ફાઇલોની સૂચિ",
    "file_max_size": "મહત્તમ ફાઇલ કદ",
    "value": "મૂલ્ય",
    "help": "મદદ",
    "shipping_tax": "શિપિંગ કર",
    "net_price": "ચોખ્ખી કિંમત",
    "tax": "કર",
    "tax_included": "કિંમતમાં સમાવેશ થાય છે",
    "limit": "મર્યાદા",
    "min_purchase": "ન્યૂનતમ ખરીદી",
    "eligible_for": "માટે પાત્ર છે",
    "only_for_first_buy": "માત્ર પ્રથમ ખરીદી માટે",
    "one_time_use": "એક વખત ઉપયોગ કરી શકો છો",
    "period_of_qualify": "પીરિયડ વપરાશ મર્યાદા",
    "no_constraint": "કોઈ મર્યાદા નહી",
    "timespan": "સમયગાળો",
    "days": "દિવસ)",
    "weight": "વજન",
    "distance": "અંતર",
    "last_status": "છેલ્લી સ્થિતિ",
    "issued_at": "જારી",
    "order": "ઓર્ડર",
    "order_detail": "ઓર્ડર વિગતો",
    "percent": "ટકા",
    "applied_count": "લાગુ ગણતરી",
    "campaign": "ઝુંબેશ",
    "os": "ઓપરેટિંગ સિસ્ટમ",
    "browser": "બ્રાઉઝર",
    "device": "ઉપકરણ",
    "device_ip": "ઉપકરણ IP સરનામું",
    "location": "સ્થાન",
    "user_agent": "વપરાશકર્તા એજન્ટ",
    "affiliate": "સંલગ્ન",
    "timeline": "સમયરેખા",
    "add_note": "નોંધ ઉમેરો",
    "record": "રેકોર્ડ",
    "unlimited": "અમર્યાદિત",
    "show_coupons": "કૂપન્સ બતાવો",
    "hide_coupons": "કૂપન્સ છુપાવો",
    "service_area": "સેવા વિસ્તાર",
    "apps": "એપ્સ",
    "plugins": "પ્લગઇન્સ",
    "bots": "બૉટો",
    "categories": "શ્રેણીઓ",
    "products": "ઉત્પાદનો",
    "business": "બિઝનેસ",
    "personal": "અંગત",
    "size": "કદ",
    "holiday": "રજા",
    "sod": "ડિલિવરી પર ચૂકવણી કરો",
    "cod": "વસ્તુ મળે ત્યારે રોકડા રૂપિયા આપવા",
    "free_shipping": "મફત શિપિંગ",
    "hours": "કલાકો",
    "send_date": "માલ મોકલવા ની તારીખ",
    "deliver_date": "સોંપણી તારીખ",
    "return_date": "પરત તારીખ",
    "pending": "બાકી છે",
    "delivered": "વિતરિત",
    "returned": "પરત ફર્યા",
    "canceled": "રદ કરેલ",
    "shipping_cost": "માલવહન ખર્ચ",
    "action": "ક્રિયા",
    "cancel_date": "તારીખ રદ કરો",
    "deliver_in_process": "ઓર્ડર મોકલેલ છે..",
    "kind": "પ્રકાર",
    "detail": "વિગતો",
    "map": "નકશો",
    "actions": "ક્રિયાઓ",
    "navigation": "સંશોધક",
    "navigation_app": "અરજી",
    "payment_date": "ચુકવણીની તારીખ",
    "duration": "અવધિ",
    "bill": "બિલ",
    "delivery_persons": "કુરિયર્સ",
    "delivery_services": "ડિલિવરી સેવાઓ",
    "live_view": "જીવંત દૃશ્ય",
    "cart": "કાર્ટ",
    "priority": "પ્રાથમિકતા",
    "sufficient_credit": "પર્યાપ્ત ક્રેડિટ",
    "max_package_size": "મહત્તમ પેકેજ કદ",
    "delay": "વિલંબ",
    "credit": "જમા",
    "livemode": "જીવંત",
    "paused": "થોભાવ્યું",
    "debug": "ડીબગ",
    "token": "ટોકન",
    "status": "સ્થિતિ",
    "courier": "કુરિયર",
    "track": "ટ્રેક",
    "track_order": "ઓર્ડર ટ્રેકિંગ",
    "cost": "ખર્ચ",
    "receipt": "રસીદ",
    "origin": "મૂળ",
    "destination": "ગંતવ્ય",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "પૂરતો સ્ટોક નથી!",
    "sub_total": "પેટાટોટલ",
    "customer": "ગ્રાહક",
    "delivery": "ડિલિવરી",
    "online_orders": "ઓનલાઈન ઓર્ડર",
    "pos_orders": "POS ઓર્ડર્સ",
    "chips": "ચિપ્સ",
    "subscribed": "સબ્સ્ક્રાઇબ કર્યું",
    "unsubscribed": "અનસબ્સ્ક્રાઇબ કર્યું",
    "last_login": "છેલ્લું લૉગિન",
    "join_at": "જોડાવા તારીખ",
    "club": "ક્લબ",
    "buyer": "ખરીદનાર",
    "seller": "વિક્રેતા",
    "or": "અથવા",
    "type": "પ્રકાર",
    "condition": "શરત",
    "brand": "બ્રાન્ડ",
    "attempt": "પ્રયાસ",
    "error": "ભૂલ",
    "success": "સફળતા",
    "fail": "નિષ્ફળ",
    "inventory": "ઇન્વેન્ટરી",
    "link": "લિંક",
    "visits": "મુલાકાતો",
    "transactions": "વ્યવહારો",
    "vat": "VAT",
    "pos_vat": "POS VAT",
    "sort_by": "દ્વારા સૉર્ટ કરો..",
    "from": "થી",
    "from_lead_time": "આગામી {hours} કલાકમાં",
    "no_credit_card_info": "કોઈ કાર્ડ માહિતી નથી!",
    "active": "સક્રિય",
    "not_active": "સક્રિય નથી!",
    "referrals": "રેફરલ્સ",
    "dashboard": "ડેશબોર્ડ",
    "more": "વધુ",
    "inactive": "નિષ્ક્રિય",
    "developer": "વિકાસકર્તા",
    "setting": "સેટિંગ",
    "membership_conditions": "સભ્યપદ શરતો",
    "customers": "ગ્રાહકો",
    "created_at": "તારીખ બનાવી",
    "updated_at": "છેલ્લો સુધારો",
    "register_at": "નોંધણી તારીખ",
    "old": "જૂનું",
    "new": "નવી",
    "start": "શરૂઆત",
    "end": "અંત",
    "pos": "POS",
    "out_of_stock": "સ્ટોક નથી",
    "fake": "નકલી",
    "low_inventory_warning": "ધ્યાન, ઓછી ઇન્વેન્ટરી!",
    "webhook": "વેબહૂક",
    "notification": "સૂચના",
    "sms": "SMS",
    "online_payment_link": "ઓનલાઈન પેમેન્ટ લિંક",
    "waiting_load_data": "ડેટા લોડ થવાની રાહ જોઈ રહ્યાં છીએ..",
    "views": "દૃશ્યો",
    "sales": "વેચાણ",
    "total_views": "કુલ દૃશ્યો",
    "total_sales": "કુલ વેચાણ",
    "from_previous_n_days": "છેલ્લા {days} દિવસથી",
    "drop_shipping": "ડ્રોપશિપિંગ",
    "commission": "કમિશન",
    "shipping_area": "શિપિંગ વિસ્તાર",
    "main_seller": "મુખ્ય વિક્રેતા",
    "domain": "ડોમેન",
    "contact": "સંપર્ક માહિતી",
    "wallet": "વૉલેટ",
    "reseller": "પુનર્વિક્રેતા",
    "tracking_code": "ટ્રેકિંગ કોડ",
    "tracking_url": "ટ્રેકિંગ URL",
    "fulfillments": "પરિપૂર્ણતા",
    "reject": "અસ્વીકાર કરો",
    "reserved": "અનામત",
    "score": "સ્કોર",
    "customer_price": "ગ્રાહક ભાવ",
    "options": "વિકલ્પો",
    "show_details": "વિગતો બતાવો",
    "no_data": "કોઈ ડેટા નથી..",
    "waiting": "રાહ જોઈ રહ્યું છે...",
    "waiting_connecting_payment": "ચુકવણી સેવાની રાહ જોઈ રહ્યાં છીએ...",
    "creating_secure_payment": "સુરક્ષિત ચુકવણી બનાવવી.",
    "officer": "અધિકારી",
    "ticket": "ટિકિટ",
    "ticket_url": "ટિકિટ url",
    "closed_at": "ખાતે બંધ",
    "close_ticket": "ટિકિટ બંધ કરો",
    "reopen_ticket": "ટિકિટ ફરીથી ખોલો",
    "require": "જરૂરી*",
    "search": "શોધો...",
    "language": "ભાષા",
    "tasks": "કાર્યો",
    "permissions": "પરવાનગીઓ",
    "finish_date": "અંતિમ તારીખ",
    "complete_date": "પૂર્ણાહુતિ તારીખ્",
    "settle_date": "સમાધાન તારીખ",
    "cost_span": "કિંમત શ્રેણી",
    "industry": "ઉદ્યોગ",
    "rating": "રેટિંગ્સ",
    "rates": "રેટિંગ",
    "seen_at": "ખાતે જોવા મળે છે",
    "completed": "પૂર્ણ થયું",
    "you": "તમે",
    "shop": "દુકાન",
    "store": "દુકાન",
    "granted": "મંજૂર",
    "deny": "નામંજૂર કરો",
    "request": "વિનંતી",
    "expert": "નિષ્ણાત",
    "response": "પ્રતિભાવ",
    "requests": "વિનંતીઓ",
    "experts": "નિષ્ણાતો",
    "responses": "પ્રતિભાવો",
    "negotiations": "વાટાઘાટો",
    "all_chats": "બધી ચેટ્સ",
    "chats": "ચેટ્સ",
    "tags": "ટૅગ્સ",
    "description": "વર્ણન",
    "rates_count": "રેટિંગની સંખ્યા",
    "rate": "રેટિંગ",
    "comment": "ટિપ્પણી",
    "chat": "ચેટ",
    "install": "ઇન્સ્ટોલ કરો",
    "edited": "સંપાદિત",
    "undo": "પૂર્વવત્ કરો",
    "redo": "ફરી કરો",
    "male": "પુરુષ",
    "female": "સ્ત્રી",
    "calculator": "કેલ્ક્યુલેટર",
    "catalog": "કેટલોગ",
    "max_height": "મહત્તમ ઊંચાઈ",
    "images_compare": "છબીઓની સરખામણી",
    "canvas": "કેનવાસ",
    "table_of_contents": "સામગ્રીઓનું કોષ્ટક",
    "comments": "ટિપ્પણીઓ",
    "badge_codes": "બેજ કોડ",
    "need_more": "વધારે જોઈએ છે?",
    "invite_glow_caption": "દરેક મિત્ર માટે 14.9$ મેળવો!",
    "register_free": "100% મફત નોંધણી",
    "gift": "ભેટ",
    "google": "Google",
    "facebook": "ફેસબુક",
    "instagram": "ઇન્સ્ટાગ્રામ",
    "instashop": "ઇન્સ્ટાશોપ",
    "show": "બતાવો",
    "hide": "છુપાવો",
    "waiting_review": "સમીક્ષાની રાહ જોઈ રહ્યું છે",
    "not_selected": "પસંદ કરેલ નથી",
    "time": "સમય",
    "final_price": "અંતિમ કિંમત",
    "starting_price": "પ્રારંભિક કિંમત",
    "day": "દિવસ",
    "paid": "ચૂકવેલ",
    "service_bill": "ભરતિયું ચુકવણી",
    "avocado": "એવોકાડો",
    "delivery_price": "માલવહન ખર્ચ",
    "select_address": "સરનામું પસંદ કરો",
    "image": "છબી",
    "view": "જુઓ",
    "sell": "વેચાણ",
    "hyper": "હાયપર",
    "cart_list": "કાર્ટ",
    "barcode_scanner": "બારકોડ સ્કેનર",
    "scan_qr_code": "QR કોડ સ્કેન કરો",
    "new_carts": "નવી ગાડીઓ",
    "pays": "ચૂકવણી",
    "annually": "વાર્ષિક",
    "sells": "વેચાણ",
    "articles": "લેખો",
    "jobs": "નોકરીઓ",
    "job": "જોબ",
    "blog": "બ્લોગ",
    "deleted_at": "પર કાઢી નાખ્યું",
    "capacity": "ક્ષમતા",
    "download_at": "છેલ્લી ડાઉનલોડ તારીખ",
    "downloads": "ડાઉનલોડ્સ",
    "usage": "ઉપયોગ",
    "select_upload_file": "ફાઇલ પસંદ કરો અથવા છોડો",
    "download_link": "ડાઉનલોડ લિંક",
    "uploading": "અપલોડ કરી રહ્યું છે..",
    "files": "ફાઈલો",
    "star": "તારો",
    "speed": "ઝડપ",
    "feedback": "પ્રતિભાવ",
    "new_messages": "નવા સંદેશા",
    "file": "ફાઈલ",
    "attachment": "જોડાણ",
    "gallery": "ગેલેરી",
    "sync": "સમન્વય",
    "diff_time": "સમય તફાવત",
    "network": "નેટવર્ક",
    "account": "એકાઉન્ટ",
    "configuration": "રૂપરેખાંકન",
    "blockchain": "બ્લોકચેન",
    "blog_link": "બ્લોગ લિંક",
    "community": "સમુદાય",
    "critical_zone": "ક્રિટિકલ ઝોન",
    "statistics": "આંકડા",
    "access": "એક્સેસ",
    "seo": "SEO",
    "followers": "અનુયાયીઓ",
    "followings": "અનુસરણ",
    "private": "પૂર્વાવલોકન",
    "soon": "ટૂંક સમયમાં",
    "features": "વિશેષતા",
    "bot": "બોટ",
    "sample": "નમૂના",
    "how_it_work": "તે કેવી રીતે કામ કરે છે?",
    "page": "પૃષ્ઠ",
    "congratulations": "અભિનંદન",
    "recommend": "ભલામણ કરો",
    "recommended": "ભલામણ કરેલ",
    "recoms": "ભલામણો",
    "likes": "પસંદ",
    "clicks": "ક્લિક્સ",
    "platform": "પ્લેટફોર્મ",
    "cms": "CMS",
    "cash": "રોકડ",
    "dir_payment": "બેન્ક ટ્રાન્સફર",
    "auto_complete": "સ્વતઃ પૂર્ણ",
    "compare": "તુલના",
    "infinite": "અનંત",
    "tips": "ટિપ્સ",
    "technical": "ટેકનિકલ",
    "finance": "ફાઇનાન્સ",
    "your_phone_input": "ફોન નંબર દાખલ કરો",
    "income": "આવક",
    "change": "બદલો",
    "new_users": "નવા વપરાશકર્તાઓ",
    "success_orders": "સફળ ઓર્ડર",
    "direct": "પ્રત્યક્ષ",
    "last_activity": "છેલ્લી પ્રવૃત્તિ",
    "landing": "ઉતરાણ",
    "now": "હવે",
    "accept_agreement": "મેં શરતો વાંચી છે અને સ્વીકારી છે.",
    "report": "જાણ કરો",
    "tablet": "ટેબ્લેટ",
    "pc": "PC",
    "acquisition_channel": "એક્વિઝિશન ચેનલ",
    "to": "પ્રતિ",
    "info": "માહિતી",
    "general": "જનરલ",
    "upload": "અપલોડ કરો",
    "general_config": "સામાન્ય રૂપરેખા",
    "limits_config": "મર્યાદાઓ",
    "design_config": "ડિઝાઇન અને શૈલી",
    "duration_config": "અવધિ મર્યાદા",
    "constraints_config": "પાત્રતા મર્યાદા",
    "clubs_config": "ક્લબમાં ઉપલબ્ધ છે",
    "additional_config": "વધારાની રૂપરેખાઓ",
    "import": "આયાત કરો",
    "ribbon": "રિબન",
    "countries": "દેશો",
    "edit": "સંપાદિત કરો",
    "delete": "કાઢી નાખો",
    "analytics": "એનાલિટિક્સ",
    "rules": "નિયમો",
    "unset": "સેટ નથી",
    "carts": "ગાડું",
    "optional": "વૈકલ્પિક",
    "design": "ડિઝાઇન",
    "filter": "ફિલ્ટર કરો",
    "send": "મોકલો",
    "approved": "મંજૂર",
    "unit": "એકમ",
    "profile": "પ્રોફાઇલ",
    "shipping_rates": "શિપિંગ દરો",
    "package": "પેકેજ",
    "overview": "ઝાંખી",
    "live": "જીવંત",
    "never": "ક્યારેય",
    "always": "હંમેશા",
    "mandatory": "ફરજિયાત",
    "expire_at": "સમાપ્તિ તારીખ",
    "position": "પદ",
    "channel": "ચેનલ",
    "age": "ઉંમર",
    "charge": "ચાર્જ",
    "giftcard": "ભેટ કાર્ડ",
    "acquisition": "સંપાદન",
    "conversion": "રૂપાંતર",
    "total_payments": "કુલ ચૂકવણી",
    "community_ask": "સમુદાયમાં પૂછો",
    "children": "બાળકો",
    "export": "નિકાસ કરો",
    "list": "યાદી",
    "hierarchy": "વંશવેલો",
    "images": "છબીઓ",
    "demo": "ડેમો",
    "author": "લેખક",
    "designer": "ડિઝાઇનર",
    "max": "મહત્તમ",
    "accepted": "સ્વીકાર્યું",
    "reply": "જવાબ આપો",
    "reviewed": "સમીક્ષા કરી",
    "restored": "પુનઃસ્થાપિત",
    "merchant": "વેપારી",
    "per_product": "ઉત્પાદન દીઠ",
    "journey": "જર્ની",
    "after": "પછી",
    "waiting_for_payment": "કૃપા કરીને ચુકવણી પૂર્ણ કરો...",
    "hour": "કલાક",
    "minute": "મિનિટ",
    "premium": "પ્રીમિયમ",
    "light": "પ્રકાશ",
    "dark": "શ્યામ",
    "guest": "મહેમાન",
    "shops": "સ્ટોર્સ",
    "vendor": "વિક્રેતા",
    "vendors": "વિક્રેતાઓ",
    "marketplace": "બજાર",
    "verify_date": "તારીખ ચકાસો",
    "note": "નૉૅધ",
    "panel": "પેનલ",
    "removed": "દૂર",
    "segments": "સેગમેન્ટ્સ",
    "personal_info": "વ્યક્તિગત માહિતી",
    "preferences": "પસંદગીઓ",
    "spec": "સ્પેક",
    "reviews": "સમીક્ષાઓ",
    "constraints": "અવરોધો",
    "flexible": "લવચીક",
    "usage_limit": "વપરાશ મર્યાદા",
    "temporary": "કામચલાઉ",
    "original": "મૂળ",
    "saved": "સાચવ્યું!",
    "sort": "સૉર્ટ કરો",
    "documents": "દસ્તાવેજો",
    "document": "દસ્તાવેજ",
    "please_wait": "મહેરબાની કરી રાહ જુવો...",
    "pickup": "પિકઅપ",
    "customize": "કસ્ટમાઇઝ કરો",
    "difficulty": "મુશ્કેલી",
    "banned": "પ્રતિબંધિત",
    "company": "કંપની",
    "tax_shipping": "શિપિંગ ટેક્સ",
    "warranty": "વોરંટી",
    "return_policy": "રીટર્ન પોલિસી",
    "guide": "માર્ગદર્શન",
    "translate": "અનુવાદ કરો",
    "public": "જાહેર",
    "deleted": "કાઢી નાખ્યું",
    "variant": "વેરિઅન્ટ",
    "secure": "સુરક્ષિત",
    "admin": "એડમિન"
  },
  "dialogs": {
    "delete": {
      "title": "કાઢી નાખો",
      "message": "શું તમે આ આઇટમ કાઢી નાખવાની ખાતરી કરો છો?",
      "action": "હા, હવે કાઢી નાખો"
    }
  },
  "actions": {
    "add_to_cart": "સૂચી માં સામેલ કરો",
    "cancel": "રદ કરો",
    "update": "અપડેટ કરો",
    "add": "ઉમેરો",
    "delete": "કાઢી નાખો",
    "new": "નવી",
    "save_continue": "સાચવો અને ચાલુ રાખો",
    "save": "સાચવો",
    "save_changes": "ફેરફારો સંગ્રહ",
    "change": "બદલો",
    "continue": "ચાલુ રાખો",
    "close": "બંધ",
    "finish": "સમાપ્ત કરો",
    "poll": "મતદાન",
    "view": "જુઓ",
    "edit": "સંપાદિત કરો",
    "next": "આગળ",
    "previous": "અગાઉના",
    "create": "બનાવો",
    "set": "સેટ",
    "find": "શોધો",
    "accept": "સ્વીકારો",
    "reject": "અસ્વીકાર કરો",
    "back": "પાછળ",
    "pay": "પે",
    "pay_now": "હવે પૈસા આપો",
    "print": "છાપો",
    "return": "પરત",
    "publish": "પ્રકાશિત કરો",
    "confirm": "પુષ્ટિ કરો",
    "copy": "નકલ કરો",
    "submit": "સબમિટ કરો",
    "send": "મોકલો",
    "yes": "હા",
    "no": "ના",
    "meh": "હમ",
    "clear": "ચોખ્ખુ",
    "dismiss": "કાઢી નાખો",
    "search": "શોધો",
    "deselect_all": "બધાને નાપસંદ કરો",
    "select_all": "બધા પસંદ કરો",
    "refresh": "તાજું કરો",
    "verify": "ચકાસો",
    "play": "રમ",
    "open": "ખુલ્લા",
    "calculate": "ગણત્રી",
    "quick_buy": "ઝડપી ખરીદો",
    "click_here": "અહીં ક્લિક કરો",
    "schedule": "અનુસૂચિ",
    "send_now": "અત્યારે મોકલો",
    "download": "ડાઉનલોડ કરો",
    "reset_default": "ડિફૉલ્ટ પર રીસેટ કરો",
    "reset": "રીસેટ કરો",
    "check": "તપાસો",
    "cod_payment": "વસ્તુ મળે ત્યારે રોકડા રૂપિયા આપવા",
    "dir_payment": "મની ટ્રાન્સફર",
    "online_payment": "ઓનલાઈન પેમેન્ટ",
    "checkout": "ચેકઆઉટ",
    "show_all": "બધું બતાવો",
    "login": "પ્રવેશ કરો",
    "logout": "લૉગ આઉટ",
    "more": "વધુ..",
    "collapse": "સંકુચિત કરો",
    "apply_change": "ફેરફારો લાગુ કરો",
    "apply": "અરજી કરો",
    "add_giftcard": "ભેટ કાર્ડ ઉમેરો",
    "charge": "ચાર્જ",
    "send_invites": "આમંત્રણો મોકલો",
    "past": "ભૂતકાળ",
    "restore": "પુનઃસ્થાપિત",
    "cut": "કાપવું",
    "get_sms_code": "પ્રમાણીકરણ કોડ મેળવો",
    "register_no_mail": "ઇમેઇલ વિના ચાલુ રાખો",
    "no_mail_register_message": "તમારી પાસે ઈમેલ સરનામું નથી અથવા તમારો પાસવર્ડ ભૂલી ગયા છો?",
    "reset_by_mail": "ઇમેઇલ દ્વારા પાસવર્ડ પુનઃપ્રાપ્તિ",
    "reset_by_sms": "SMS દ્વારા પાસવર્ડ પુનઃપ્રાપ્તિ",
    "cash_payment": "રોકડ ચુકવણી",
    "show_chart": "ચાર્ટ બતાવો",
    "open_app": "એપ્લિકેશન ખોલો",
    "login_now": "હવે લોગીન કરો",
    "watch_video": "વિડીયો જુઓ",
    "check_now": "હવે તપાસો",
    "remove_image": "છબી દૂર કરો",
    "view_website": "લિંક ખોલો",
    "explore": "{name} નું અન્વેષણ કરો",
    "go": "જાઓ",
    "read_more": "વધુ વાંચો",
    "start_now": "હમણાં શરૂ કરો - તે મફત છે",
    "view_live": "લાઈવ જુઓ",
    "resend_code": "કોડ ફરીથી મોકલો",
    "invite": "આમંત્રિત",
    "add_more": "વધુ ઉમેરો",
    "install_now": "હવે ઇન્સ્ટોલ કરો",
    "uninstall": "અનઇન્સ્ટોલ કરો",
    "show_preview": "પૂર્વાવલોકન બતાવો",
    "hide_preview": "પૂર્વાવલોકન છુપાવો",
    "download_now": "ડાઉનલોડ કરો",
    "auto_fill": "ઑટોફિલ",
    "track": "ટ્રેક",
    "change_state": "સ્થિતિ બદલો",
    "done": "થઈ ગયું",
    "reply": "જવાબ આપો",
    "watch_now": "હવે જુઓ",
    "unlock": "અનલોક કરો",
    "lock": "તાળું",
    "create_clone": "ક્લોન બનાવો",
    "regenerate": "પુનર્જીવિત કરો",
    "add_message": "સંદેશ ઉમેરો",
    "continue_chat": "ચેટ ચાલુ રાખો",
    "add_new_message": "નવો સંદેશ ઉમેરો"
  },
  "instance_message_title": "ત્વરિત સંદેશ મોકલો",
  "instance_message": "હાય {name}, મારું નામ {company} તરફથી {author} છે.",
  "errors": {
    "419": "તમે લાંબા સમયથી નિષ્ક્રિય છો, કૃપા કરીને <b>⟳ સુરક્ષા કારણોસર પેજ રિફ્રેશ</b> કરો.",
    "gateway_blockchain_sync_error": "સિસ્ટમ બ્લોકચેન સાથે સિંક્રનાઇઝ થતી નથી. જ્યાં સુધી અમારા સર્વર્સનું સિંક્રનાઇઝેશન પૂર્ણ ન થાય ત્યાં સુધી નવો વ્યવહાર બનાવવો શક્ય બનશે નહીં. અમે સમસ્યા હલ કરી રહ્યા છીએ.",
    "gateway_network_error": "પેમેન્ટ ગેટવે સેવામાં સંચાર સમસ્યા આવી છે."
  },
  "receiver_info": {
    "map": {
      "title": "પહોંચાડવાનું સરનામું",
      "confirm": "સ્થાન સેટ કરો",
      "address_type": "ગંતવ્ય",
      "receptor_type": "રીસીવર"
    },
    "receiver_address": "શિપિંગ સરનામું પસંદ કરો",
    "address": "સરનામું",
    "postcode": "પોસ્ટકોડ",
    "enter_value": "અહીં ભરો",
    "address_note": "નૉૅધ",
    "tel": "સંપર્ક નંબર",
    "service_address": "તમારું સરનામું પસંદ કરો"
  },
  "weight": {
    "g": "g",
    "oz": "ઓઝ",
    "lb": "lb",
    "kg": "કિલો ગ્રામ"
  },
  "mass_unit_name": {
    "g": "ગ્રામ",
    "oz": "ઔંસ",
    "lb": "પાઉન્ડ",
    "kg": "કિલોગ્રામ"
  },
  "length": {
    "cm": "સેમી",
    "in": "માં",
    "ft": "ફૂટ",
    "mm": "મીમી",
    "m": "m",
    "yd": "yd"
  },
  "size_unit_name": {
    "cm": "સેન્ટીમીટર",
    "in": "ઇંચ",
    "ft": "પગ",
    "mm": "મિલિમીટર",
    "m": "મીટર",
    "yd": "યાર્ડ"
  },
  "distance": {
    "m": "મીટર",
    "km": "કિમી"
  },
  "time": {
    "days": "દિવસ",
    "hours": "કલાકો",
    "minutes": "મિનિટ",
    "seconds": "સેકન્ડ"
  },
  "units": [
    "એકમ",
    "વસ્તુ",
    "દરેક",
    "સેટ",
    "ટુકડો",
    "કિલોગ્રામ",
    "ગ્રામ",
    "મિલિગ્રામ",
    "મીટર",
    "મિલિમીટર",
    "ચોરસ મીટર",
    "ચોરસ ફૂટ",
    "ઘન મીટર",
    "લિટર",
    "મિલીલીટર",
    "પગ",
    "ગેલન",
    "ઇંચ",
    "ઔંસ",
    "પાઉન્ડ",
    "ક્વાર્ટ્સ",
    "યાર્ડ",
    "ઓરડો",
    "સેકન્ડ",
    "મિનિટ",
    "કલાક",
    "દિવસ",
    "અઠવાડિયા",
    "મહિનાઓ",
    "વર્ષ"
  ],
  "region_types": {
    "State": "રાજ્ય",
    "Territory": "પ્રદેશ",
    "Province": "પ્રાંત"
  },
  "transaction_status": {
    "RequireAction": "ક્રિયા જરૂરી",
    "Processing": "પ્રક્રિયા",
    "Canceled": "રદ કરેલ",
    "Succeeded": "સફળ"
  },
  "placeholders": {
    "name": "જોન કોક્સ",
    "email": "your-mail@mail.com",
    "phone": "+1 000 0000",
    "language": "ભાષા પસંદ કરો..",
    "friend_email": "તમારા મિત્રનો ઈમેલ...",
    "friend_name": "પસંદ કરો. તમારા મિત્રનું નામ",
    "select_date": "તારીખ પસંદ કરો..."
  },
  "notification": {
    "confirm": "પુષ્ટિ કરો",
    "confirm_message": "ફેરફારો સફળતાપૂર્વક સાચવવામાં આવ્યા.",
    "error": "ભૂલ",
    "message": "સંદેશ",
    "caution": "સાવધાન",
    "warning": "ચેતવણી",
    "award": "અભિનંદન",
    "error_message": "કમનસીબે, એક ભૂલ આવી છે.",
    "congratulation": "અભિનંદન",
    "coming_soon": "ટૂંક સમયમાં",
    "on_fetching_data": "માહિતી મેળવી રહી છે..",
    "new_pwa_version": "નવું સંસ્કરણ હવે ઉપલબ્ધ છે. શું તમે એપ્લિકેશન અપડેટ કરવા માંગો છો?",
    "over_license_limit": "લાયસન્સ મર્યાદાથી વધુ",
    "update_license": "તમારું લાઇસન્સ અપડેટ કરો",
    "required": "જરૂરી છે",
    "invalid_email": "અમાન્ય ઈ-મેલ",
    "invalid_domain": "અમાન્ય ડોમેન",
    "invalid_min_length": "ન્યૂનતમ લંબાઈ {length} હોવી જોઈએ",
    "invalid_min_array_length": "ઓછામાં ઓછી {length} આઇટમ પસંદ કરો",
    "invalid_max_chars": "મહત્તમ {maxCount} અક્ષરો",
    "invalid_url": "અમાન્ય URL",
    "country_invalid": "ગંતવ્ય દેશ પસંદ કરો!",
    "postal_code_invalid": "માન્ય પોસ્ટલ કોડ સેટ કરો!"
  },
  "colors": {
    "#D32F2F": "લાલ",
    "#C2185B": "ગુલાબી",
    "#7B1FA2": "જાંબલી",
    "#512DA8": "ઘેરો જાંબલી",
    "#303F9F": "ઈન્ડિગો બ્લુ",
    "#1976D2": "વાદળી",
    "#0288D1": "પ્રકાશ વાદળી",
    "#0097A7": "પીરોજ વાદળી",
    "#00796B": "હંસ ગ્રીન",
    "#388E3C": "લીલા",
    "#689F38": "આછો લીલો",
    "#AFB42B": "લિમો",
    "#FBC02D": "પીળો",
    "#FFA000": "અંબર",
    "#F57C00": "નારંગી",
    "#E64A19": "ચળકતી નારંગી",
    "#5D4037": "બ્રાઉન",
    "#616161": "ભૂખરા",
    "#455A64": "ગ્રે બ્લુ",
    "#FFD700": "સુવર્ણ",
    "#C0C0C0": "ચાંદીના",
    "#b76e79": "ગોલ્ડન રોઝ",
    "#383838": "મેટ બ્લેક",
    "#FFFFFF": "સફેદ",
    "#FFF": "સફેદ",
    "#000000": "કાળો",
    "#000": "કાળો",
    "#7d263a": "મરૂન",
    "#FD9F17": "સોનું",
    "#229DBF": "એક્વા",
    "#6DC9E2": "એક્વા Triblend",
    "#413B2D": "આર્મી",
    "#474747": "ડામર",
    "#E6195C": "બેરી",
    "#B2184C": "બેરી Triblend",
    "#FC7F5F": "બળી નારંગી",
    "#80011F": "કાર્ડિનલ",
    "#382829": "ચોકલેટ",
    "#F06336": "કોરલ",
    "#FAE7C9": "ક્રીમ",
    "#6B2257": "કિસમિસ",
    "#222127": "ડાર્ક ગ્રે",
    "#0D5A74": "ડીપ ટીલ",
    "#00582F": "સદાબહાર",
    "#214C30": "વન",
    "#DC2867": "ફુચિયા",
    "#38561": "કેલી",
    "#5C884D": "પર્ણ",
    "#558450": "લાઇટ એક્વા",
    "#96B5C9": "પ્રકાશ વાદળી",
    "#DCAFCE": "લીલાક",
    "#D3E1A4": "ચૂનો",
    "#9DE7C2": "ટંકશાળ",
    "#F6EAD2": "કુદરતી",
    "#1A1F35": "નૌસેના",
    "#404624": "ઓલિવ",
    "#271020": "આલુ",
    "#A8355C": "રાસ્પબેરી",
    "#D6BEA6": "સોફ્ટ ક્રીમ",
    "#BEA994": "ટેન",
    "#0DB2AE": "ટીલ",
    "#A86EA9": "વાયોલેટ",
    "#36454F": "ચારકોલ",
    "#b3b0ab": "કાર્બન ગ્રે",
    "#463e3d": "ચારકોલ હિથર",
    "#282d3c": "નેવી બ્લેઝર"
  },
  "address_info": {
    "name": "નામ",
    "tel": "ફોન",
    "email": "ઈમેલ",
    "country": "દેશ",
    "city": "શહેર",
    "state": "રાજ્ય",
    "address": "સરનામું",
    "building_number": "મકાન નંબર",
    "building_unit": "એકમ",
    "postcode": "પોસ્ટકોડ",
    "note": "નૉૅધ",
    "county": "કાઉન્ટી"
  },
  "product_types": {
    "physical": "ભૌતિક",
    "physical_description": "ભૌતિક ઉત્પાદનો જેમ કે: મોબાઈલ ફોન, પુસ્તકો, ઈલેક્ટ્રોનિક ઘટકો.",
    "virtual": "વર્ચ્યુઅલ",
    "virtual_description": "ઈન્ટરનેટ-ફ્રેંડલી પ્રોડક્ટ્સ જેમ કે: રિચાર્જ કાર્ડ, હોટેલ રિઝર્વેશન, ગેમ રિચાર્જ.",
    "file": "ફાઈલ",
    "file_description": "ઓનલાઈન કોર્સ વિડિયો, ડાઉનલોડ કરી શકાય તેવા દસ્તાવેજો જેવી તમામ પરવાનગીવાળી ફાઈલો.",
    "service": "સેવા",
    "service_description": "સેવાઓ જેવી કે: સમારકામ, પરિવહન, શિક્ષણ."
  },
  "license": {
    "free": "મફત",
    "startup": "શરુઆત",
    "company": "કંપની",
    "enterprise": "એન્ટરપ્રાઇઝ"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "ટોમન",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW",
    "GHS": "GHS",
    "ZWD": "ZWD",
    "IQD": "IQD",
    "SYP": "SYP"
  },
  "variants": {
    "color": "રંગ",
    "volume": "કદ",
    "count_in_pack": "પેકમાં ગણો",
    "weight": "વજન",
    "type": "સામગ્રી",
    "style": "શૈલી"
  },
  "delivery_state": {
    "check_queue": "સમીક્ષાની રાહ જોઈ રહ્યું છે",
    "order_confirm": "ઓડર પાક્કો",
    "preparing_order": "તૈયારી",
    "sent_order": "ડિલિવરી પર",
    "to_customer": "વિતરિત"
  },
  "status": {
    "unpaid": "અવેતન",
    "paid": "ચૂકવેલ",
    "canceled": "રદ કરેલ",
    "completed": "સ્થાયી થયા",
    "reserved": "અનામત",
    "COD": "COD",
    "sold": "વેચાય છે",
    "open": "ખુલ્લા",
    "cancel": "રદ કરેલ",
    "active": "સક્રિય",
    "inactive": "નિષ્ક્રિય",
    "debug": "ડીબગ",
    "live": "જીવંત",
    "test": "ટેસ્ટ",
    "connected": "કનેક્ટેડ",
    "disconnected": "ડિસ્કનેક્ટ",
    "accept": "સ્વીકારો",
    "reject": "અસ્વીકાર કરો",
    "pending": "બાકી છે",
    "rejected": "નામંજૂર",
    "accepted": "સ્વીકાર્યું"
  },
  "dimensions": {
    "cm": "સેમી",
    "km": "કિમી",
    "kg": "કિલો ગ્રામ"
  },
  "transportation_type": {
    "motorbike": "મોટરબાઈક",
    "motorbike_description": "થોડા કિલોમીટરની અંદર મધ્યમ વજન.",
    "cargo_small": "નાનો કાર્ગો",
    "cargo_small_description": "મલ્ટી-કિલોમીટર લાઇટ કાર્ગો.",
    "cargo": "કાર્ગો",
    "cargo_description": "થોડા કિલોમીટરની અંદર મધ્યમ વજન.",
    "truck": "ટ્રક",
    "truck_description": "દેશની અંદર જથ્થાબંધ અથવા ભારે કાર્ગો.",
    "fast_post": "ઝડપી પોસ્ટ",
    "fast_post_description": "પોસ્ટ ઓફિસ દ્વારા ઝડપી પોસ્ટિંગ.",
    "post": "સામાન્ય પોસ્ટ",
    "post_description": "પોસ્ટ ઓફિસ દ્વારા નિયમિત પોસ્ટ.",
    "airplane": "એરમેલ",
    "airplane_description": "સ્થાનિક અને વિદેશી પ્રકાશ અને મધ્યમ કાર્ગો.",
    "bicycle": "સ્વચ્છ મોકલો",
    "bicycle_description": "હલકો કાર્ગો, નોન-મોટર વાહનોના થોડાક સો યાર્ડની અંદર.",
    "global": "વૈશ્વિક પરિવહન",
    "global_description": "હવા, સમુદ્ર અથવા જમીન દ્વારા વિદેશમાં શિપિંગ.",
    "pickup": "પિકઅપ",
    "pickup_description": "ગ્રાહકો તમારા ભૌતિક સ્ટોર અથવા વેરહાઉસમાંથી વસ્તુઓ પસંદ કરે છે."
  },
  "article": {
    "login_to_see_error": "લેખ ઍક્સેસ કરવા માટે લૉગિન કરો",
    "create_new_action": "નવી સામગ્રી બનાવો",
    "menu_title": "મેનુ",
    "menu": {
      "edit": "સંપાદિત કરો મોડ",
      "view_mode": "જુઓ મોડ",
      "delete": "લેખ કાઢી નાખો"
    },
    "schedule_action": "શું તમે પ્રકાશન શેડ્યૂલ કરવા માંગો છો?",
    "schedule_title": "સ્વતઃ-પ્રકાશિત શેડ્યૂલ કરો",
    "edit_mode": "સંપાદિત કરો",
    "public_view_mode": "જાહેર દૃશ્ય",
    "publish_at": "પર પ્રકાશિત કરો",
    "published": "પ્રકાશિત",
    "draft": "ડ્રાફ્ટ",
    "saving": "બચત",
    "save_and_publish_action": "સાચવો અને પ્રકાશિત કરો",
    "save_draft_action": "રૂપરેખા સાચવો",
    "private": "ખાનગી",
    "public": "જાહેર",
    "category_input": "શ્રેણી",
    "category_input_message": "લેખ શ્રેણી પસંદ કરો",
    "parent_input": "પિતૃ શ્રેણી",
    "parent_input_message": "પિતા સામગ્રી પસંદ કરો",
    "schedule_input": "અનુસૂચિ",
    "schedule_input_placeholder": "જો તમે ઇચ્છો છો કે વાર્તા ચોક્કસ સમયે પ્રકાશિત થાય.",
    "schedule_view_action": "પ્રકાશિત શેડ્યૂલ જુઓ",
    "author_title": "દ્વારા લખાયેલ",
    "read_time": "ભણવાનાે સમય",
    "read_time_unit": "મિનિટ",
    "claps_action": "તાળી પાડે છે",
    "claps": "તાળી પાડે છે",
    "likes": "ગમે છે",
    "about_author": "લેખક વિશે",
    "updated_at": "અપડેટ કરેલ",
    "wrote_at": "ખાતે લખાયેલ",
    "now": "હવે",
    "follow_action": "અનુસરો",
    "followed": "અનુસર્યું",
    "report_and_delete_action": "આ લેખની જાણ કરો અને કાઢી નાખો",
    "report_action": "દુરુપયોગની જાણ કરો",
    "you_reported_this_article": "આ લેખમાં પહેલેથી જ દુરુપયોગની જાણ છે.",
    "add_to_publication_action": "પ્રકાશનમાં ઉમેરો",
    "author_socials": "સોશિયલ મીડિયા પર લેખક",
    "share": "શેર કરો",
    "report_dialog": {
      "report_and_delete_title": "દુરુપયોગની જાણ કરો અને સામગ્રી દૂર કરો",
      "report_title": "આ સામગ્રીની અપમાનજનક તરીકે જાણ કરો",
      "message": "આ સામગ્રી સબમિટ કરવાનું કારણ શું છે? નીચેના વિકલ્પોમાંથી એક પસંદ કરો.",
      "accept_and_delete_action": "પુષ્ટિ કરો અને સામગ્રી કાઢી નાખો"
    },
    "schedule_dialog": {
      "title": "સામગ્રી પ્રકાશન શેડ્યૂલ",
      "publish_at": "પર પ્રકાશિત કરો",
      "last_edit": "છેલ્લું સંપાદન",
      "view_action": "લેખ જુઓ"
    },
    "notifications": {
      "update_success_title": "માહિતી સબમિટ કરો",
      "update_success": "લેખ સફળતાપૂર્વક અપડેટ થયો.",
      "update_error": "દાખલ કરેલી માહિતી માન્ય નથી.",
      "delete_error": "તમે આ લેખ કાઢી શકતા નથી!",
      "report_and_delete_success_title": "જાણ કરો અને કાઢી નાખો",
      "report_and_delete_success_message": "લેખ સફળતાપૂર્વક કાઢી નાખવામાં આવ્યો છે.",
      "report_success_title": "અહેવાલ લેખ",
      "report_success_message": "આ લેખ પર તમારો અહેવાલ પોસ્ટ કરવામાં આવ્યો છે."
    },
    "alert": {
      "delete_article": {
        "title": "લેખ કાઢી નાખો",
        "message": "શું તમે ખરેખર આ લેખ કાયમ માટે કાઢી નાખવા માંગો છો?",
        "action": "કાઢી નાખો"
      }
    },
    "edit_window": {
      "title": "છબી ટેક્સ્ટ અને સારાંશ પસંદ કરો",
      "digest": "સારાંશ"
    },
    "editor": {
      "title_placeholder": "શીર્ષક..",
      "body_placeholder": "સરસ સામગ્રી લખો..",
      "accept_file_types_error": "આ ફાઇલ ફોર્મેટ અસ્વીકાર્ય છે:",
      "max_file_size_error": "આ ફાઇલ ખૂબ મોટી છે:",
      "notifications": {
        "image_uploaded_success": "છબી સફળતાપૂર્વક સાચવી",
        "image_uploaded_failed": "છબી લોડ કરવામાં ભૂલ."
      },
      "embed_placeholder": "iframe કોડ, Facebook, Youtube અથવા અન્ય કોઈપણ URL દાખલ કરો અને enter દબાવો.",
      "embed_caption_placeholder": "શીર્ષક દાખલ કરો (વૈકલ્પિક)",
      "images_caption_placeholder": "આ છબી માટે શીર્ષક દાખલ કરો.."
    }
  },
  "article_report": {
    "inappropriate": "આ લેખની સામગ્રી અયોગ્ય છે.",
    "fake": "આ બનાવટી અને ભ્રામક છે.",
    "spam": "આ આઇટમ સ્પામ અને કૉપિ કરવામાં આવી છે.",
    "scam": "આનાથી માલવેર, વાયરસ અથવા સિસ્ટમ ક્રેશ થવાની અપેક્ષા રાખી શકાય છે.",
    "hacked": "આ સાઈટ હેક થઈ હોવાનું જણાય છે.",
    "offensive": "ભાષાની સામગ્રી અને શબ્દભંડોળ અનૈતિક અને અપમાનજનક છે.",
    "violent": "મને લાગે છે કે આ સામગ્રીમાં પોર્નોગ્રાફી છે અને તે કાયદાનું ઉલ્લંઘન કરે છે.",
    "harassment": "મને લાગે છે કે આ જાતિવાદી છે.",
    "hate": "મને લાગે છે કે આ હિંસાને પ્રોત્સાહન આપવા વિશે છે.",
    "infringe": "આ મારા અધિકારોનું ઉલ્લંઘન કરે છે."
  },
  "comments": {
    "new_action": "ટિપ્પણી કરવા માટે ક્લિક કરો..",
    "title": "ટિપ્પણીઓ",
    "body_placeholder": "તમારી ટિપ્પણી અથવા સંદેશ",
    "send_action": "ટિપ્પણી મોકલો",
    "body_is_empty_error": "ટિપ્પણી ખાલી છે!",
    "comments": "ટિપ્પણીઓ",
    "no_comments": "પ્રથમ કોમેન્ટ લખો...",
    "load_more_action": "વધુ ટિપ્પણીઓ મેળવો ..",
    "cant_send_comment": "તમે નવી પોસ્ટ ઉમેરી શકતા નથી.",
    "cant_remove_this_comment": "તમે આ ટિપ્પણી કાઢી શકતા નથી!",
    "product_buyer": "ખરીદનાર",
    "delete_alert": {
      "title": "ટિપ્પણી કાઢી નાખો",
      "message": "શું તમે આ ટિપ્પણી કાઢી નાખવા માંગો છો?",
      "action": "કાઢી નાખો"
    },
    "notifications": {
      "delete_success": "તમારી ટિપ્પણી સફળતાપૂર્વક કાઢી નાખવામાં આવી."
    },
    "first_send": "પ્રથમ પોસ્ટ",
    "comment_at": "ચાલુ",
    "edit_comment": "ટિપ્પણી સંપાદિત કરો"
  },
  "customer_club": {
    "bronze": "કાંસ્ય",
    "silver": "ચાંદીના",
    "gold": "સુવર્ણ",
    "platinum": "પ્લેટિનમ",
    "diamond": "હીરા"
  },
  "application_categories": {
    "tracking": "વપરાશકર્તા વર્તન તપાસી રહ્યું છે",
    "payment": "ચુકવણી",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "પરિવહન",
    "automation": "ઓટોમેશન",
    "inventory": "વેરહાઉસિંગ",
    "accounting": "નામું",
    "marketing": "માર્કેટિંગ",
    "advertising": "જાહેરાત",
    "staff": "સ્ટાફ",
    "incentive": "પ્રોત્સાહનો",
    "shop": "દુકાન"
  },
  "social_network": {
    "instagram": "ઇન્સ્ટાગ્રામ",
    "telegram": "ટેલિગ્રામ",
    "googleplay": "GooglePlay",
    "appstore": "એપ્લિકેશન ની દુકાન",
    "twitter": "Twitter",
    "linkedin": "લિંક્ડિન",
    "medium": "મધ્યમ",
    "selldone": "સેલડન",
    "facebook": "ફેસબુક",
    "pinterest": "Pinterest",
    "whatsapp": "વોટ્સેપ",
    "skype": "સ્કાયપે",
    "facebook_messenger": "ફેસબુક મેસેન્જર"
  },
  "form_builder": {
    "add_item_action": "નવી આઇટમ ઉમેરો",
    "title_input": "શીર્ષક",
    "name_input": "ચલ નામ",
    "value_input": "મૂલ્યો",
    "value_input_message": "વપરાશકર્તા વિકલ્પોની સૂચિ",
    "default": "ડિફૉલ્ટ મૂલ્ય",
    "types": {
      "simple": "સરળ",
      "selective": "પસંદગીયુક્ત",
      "switch": "સ્વિચ કરો",
      "file": "ફાઈલ",
      "number": "નંબર"
    },
    "placeholder_input": "પ્લેસહોલ્ડર",
    "file_type_input": "સ્વીકાર્ય ફાઇલ પ્રકારો",
    "file_type_message": "jpeg , png , zip , ..."
  },
  "virtual_order_info_summery": {
    "title": "ઉત્પાદન નામ",
    "reserved_at": "નોંધણી તારીખ",
    "total_price": "કુલ રકમ",
    "discount": "ડિસ્કાઉન્ટ",
    "final_price": "અંતિમ રકમ",
    "payment_status": "ચુકવણી સ્થિતિ",
    "payment_status_waiting": "ચુકવણી માટે રાહ જોઈ રહ્યું છે",
    "payment_status_paid": "ચૂકવેલ",
    "buyer": "ખરીદનાર"
  },
  "virtual_item_info": {
    "title": "વર્ચ્યુઅલ આઇટમ",
    "outputs": {
      "title": "આઉટપુટ માહિતી",
      "sub_title": "આ આઇટમની ગોપનીય માહિતી",
      "message": "આ માહિતી ઉત્પાદન ખરીદ્યા પછી વપરાશકર્તાને બતાવવામાં આવશે."
    },
    "inputs": {
      "title": "જરૂરી માહિતી",
      "sub_title": "ખરીદનાર માહિતી જરૂરી",
      "message": "ખરીદનારએ ફોર્મમાં વિનંતી કરેલ માહિતી દાખલ કરવી આવશ્યક છે"
    },
    "notifications": {
      "inputs_set_success": "માહિતી ફોર્મ સફળતાપૂર્વક નોંધાયેલ.",
      "confirm_by_admin_success": "ઓર્ડર પૂર્ણ થવાની પુષ્ટિ થઈ.",
      "confirm_by_buyer_success": "ઓર્ડર પૂર્ણ થવાની પુષ્ટિ થઈ."
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "આ ઓર્ડર COD ચુકવણી દ્વારા સ્વીકારી શકાતો નથી.",
    "payment_returned": "ગ્રાહક દ્વારા ચૂકવણી પરત કરવામાં આવે છે.",
    "payment_fraud": "ચુકવણીને છેતરપિંડી તરીકે ઓળખવામાં આવી છે.",
    "location_out_of_service": "ગ્રાહક સ્થાન સેવાની બહાર છે.",
    "user_not_responding": "ગ્રાહકે કોલ્સનો જવાબ આપ્યો ન હતો.",
    "shop_owner_fault": "માહિતી ભરવામાં સ્ટોર સ્ટાફ દ્વારા ભૂલ આવી.",
    "lack_of_inventory": "સ્ટોક નથી.",
    "legal_restriction": "કાનૂની પ્રતિબંધોને કારણે ઓર્ડર આપવામાં અસમર્થ.",
    "pricing_fault": "વિક્રેતા દ્વારા કિંમત નિર્ધારણની ભૂલ.",
    "system_fault": "સિસ્ટમ બગ."
  },
  "basket_order_info_summery": {
    "receiver": "રીસીવર",
    "phone": "ટેલ",
    "reserved_date": "ખરીદ તારીખ",
    "total_price": "કુલ રકમ",
    "discount": "ડિસ્કાઉન્ટ",
    "final_price": "અંતિમ રકમ",
    "address": "વિતરણ સરનામું",
    "payment_status": "ચુકવણી સ્થિતિ"
  },
  "basket_status": {
    "open": "ખુલ્લા",
    "reserved": "અનામત",
    "paid": "ચૂકવેલ",
    "canceled": "રદ કરેલ",
    "cod": "ડિલિવરી પર ચૂકવણી કરો",
    "receipt_added": "રસીદ ઉમેરી",
    "payment_processing": "ચુકવણી પ્રક્રિયા"
  },
  "basket_delivery_state": {
    "rejected": "નામંજૂર",
    "reject_reason_not_found": "કારણ અજ્ઞાત છે.",
    "step_1": "સમીક્ષા",
    "step_2": "પુષ્ટિકરણ",
    "step_3": "તૈયારી",
    "step_4": "ડિલિવરી પર",
    "step_5": "વિતરિત"
  },
  "basket_return_request_view": {
    "title": "પરત વિનંતી",
    "delivery_date": "સોંપણી તારીખ",
    "return_date": "વિનંતી તારીખ",
    "items_count": "પરત કરેલ વસ્તુઓની ગણતરી",
    "items_count_unit": "વસ્તુ(ઓ)",
    "reason": "કારણ",
    "description": "વર્ણન",
    "status": "સ્થિતિ",
    "download_image": "છબી ડાઉનલોડ કરો",
    "download_film": "વિડિઓ ડાઉનલોડ કરો",
    "download_voice": "અવાજ ડાઉનલોડ કરો",
    "accept_by_admin_action": "વિનંતી સ્વીકારો",
    "reject_by_admin_action": "વિનંતી નકારી કાઢો",
    "message_for_admin": "Selldone નો ઉપયોગ કરીને તમે જે કરાર સ્વીકાર્યો છે તે મુજબ, તમારે ખરીદનારનો સંપર્ક કરવો જોઈએ અને તેને/તેણીને તેનો/તેણીનો ઓર્ડર પરત કરવાની પ્રક્રિયા વિશે જાણ કરવી જોઈએ. જો વિનંતી સ્વીકારવામાં આવે અથવા નકારવામાં આવે અને ખરીદનારની સંપૂર્ણ સંમતિ પ્રાપ્ત થાય તો આ કરવું આવશ્યક છે.",
    "notifications": {
      "update_status_success": "વિનંતી સ્થિતિ અપડેટ કરી."
    }
  },
  "basket_list": {
    "return_count": "પરત કરો: {count} નંબર",
    "table": {
      "row": "પંક્તિ",
      "image": "છબી",
      "product_name": "ઉત્પાદન",
      "variant": "વેરિઅન્ટ",
      "warranty": "વોરંટી",
      "count": "ગણતરી",
      "price": "કિંમત"
    }
  },
  "return_request_list": {
    "count": "સંદર્ભ નંબર",
    "return_warranty": "મની બેક ગેરંટી",
    "return_warranty_unit": "દિવસ)",
    "table": {
      "code": "ઓર્ડર કોડ",
      "product": "ઉત્પાદન",
      "delivery_at": "પ્રાપ્ત તારીખ",
      "state": "સ્થિતિ",
      "reason": "કારણ",
      "return_warranty_period": "ખાતરી નો સમય ગાળો"
    }
  },
  "data_toolbar": {
    "search": "શોધો",
    "sort_by": "દ્વારા સૉર્ટ કરો",
    "count_item": "{item} આઇટમ બતાવો"
  },
  "sort": {
    "created_at": "તારીખ બનાવો",
    "updated_at": "તારીખ સંપાદિત કરો",
    "title": "શીર્ષક",
    "description": "વર્ણન",
    "like": "લોકપ્રિયતા",
    "power": "તાળી પાડે છે",
    "product_type": "ઉત્પાદનો પ્રકાર",
    "discount": "ડિસ્કાઉન્ટ",
    "rate": "રેટિંગ",
    "rate_count": "રેટિંગની સંખ્યા",
    "category": "શ્રેણી",
    "product": "ઉત્પાદન",
    "body": "સામગ્રી",
    "card_type": "કાર્ડ પ્રકાર",
    "card_number": "કાર્ડ ક્રમાંક",
    "balance": "સંતુલન",
    "paid": "ખર્ચ કરેલ રકમ",
    "currency": "ચલણ",
    "expire_at": "સમાપ્તિ તારીખ",
    "discount_code": "ડિસ્કાઉન્ટ કોડ",
    "discount_percent": "ડિસ્કાઉન્ટ",
    "discount_limit": "ડિસ્કાઉન્ટ મર્યાદા",
    "max_count": "મહત્તમ ગણતરી",
    "used_count": "વપરાયેલ",
    "start_date": "પ્રારંભ તારીખ",
    "end_date": "અંતિમ તારીખ",
    "total_discount_amount": "કુલ ડિસ્કાઉન્ટ",
    "initial_charge": "પ્રારંભિક ચાર્જ",
    "total_count": "કુલ ગણતરી",
    "amount_paid": "ચૂકવેલ રકમ",
    "name": "નામ",
    "published": "પ્રકાશિત",
    "visits": "મુલાકાતો",
    "color": "રંગ",
    "landing_page": "લેન્ડિંગ પેજ",
    "enable": "સક્ષમ કરો",
    "fix_commission": "નિશ્ચિત કમિશન",
    "percent_commission": "ટકાવારી કમિશન",
    "payment_at": "ચુકવણીની તારીખ",
    "issued_at": "ઇશ્યૂ તારીખ",
    "payment": "ચુકવણી",
    "website": "વેબસાઈટ",
    "email": "ઈમેલ",
    "user": "વપરાશકર્તા",
    "code": "કોડ",
    "schedule_at": "શેડ્યૂલ તારીખ",
    "sender": "મોકલનાર",
    "in_que": "કતાર માં",
    "sent": "મોકલેલ",
    "shop": "દુકાન",
    "quantity": "જથ્થો",
    "amount": "રકમ",
    "jobs": "નોકરીઓની ગણતરી",
    "success": "સફળતાની ગણતરી",
    "fail": "નિષ્ફળ ગણતરી",
    "distance": "અંતર",
    "duration": "અવધિ",
    "reset_at": "તારીખ રીસેટ કરો",
    "delivery_person": "વ્યક્તિ",
    "delivery_service": "સેવા",
    "date": "તારીખ",
    "order": "ઓર્ડર",
    "order_id": "ઓર્ડર આઈડી",
    "status": "સ્થિતિ",
    "price": "કિંમત",
    "count": "ગણતરી",
    "final_price": "અંતિમ કિંમત",
    "charge": "ચાર્જ",
    "mention": "ઉલ્લેખ",
    "officer": "અધિકારી",
    "registered": "રજીસ્ટર",
    "purchased": "ખરીદી",
    "sex": "જાતિ"
  },
  "search_box": {
    "result": "શોધ પરિણામો",
    "tips": "ઉત્પાદનો અને શ્રેણીઓ શોધો",
    "label": "શોધો...",
    "category": "શ્રેણી"
  },
  "lead_status": {
    "physical_fast_delivery": "ઇન્સ્ટન્ટ ડિલિવરી",
    "physical_under_24h_delivery": "આગલા {lead} કલાકમાં ડિલિવરી કરો",
    "physical_over_24h_delivery": "આગામી {days} દિવસથી તૈયારી અને સબમિટ કરી રહ્યાં છીએ",
    "virtual_fast_prepare": "ઇન્સ્ટન્ટ ડિલિવરી",
    "virtual_under_24h": "આગામી {lead} કલાકમાં કરવામાં આવશે",
    "virtual_over_24h": "આગામી {days} દિવસથી કરવામાં આવશે"
  },
  "return_request_state": {
    "pending": "બાકી છે",
    "accepted": "પુષ્ટિ",
    "rejected": "નામંજૂર"
  },
  "return_order_reason": {
    "physical": {
      "U1": "ઉત્પાદન મેળ ખાતું નથી",
      "U2": "શિપિંગ પેકેજમાં કોઈ ઉત્પાદન નથી",
      "U3": "પેકેજ અથવા ઉત્પાદન ભંગાણ",
      "U4": "પેકેજ અથવા સીરીયલ નંબર સાથે ચેડાં",
      "U5": "પાર્સલમાંથી કેટલીક વસ્તુઓ ગુમ છે",
      "U6": "ઉત્પાદન મૂળ નથી",
      "U7": "ઉત્પાદન સ્પષ્ટીકરણોને સંતોષતું નથી"
    }
  },
  "image_uploader": {
    "label": "ખેંચો અને છોડો અથવા <u>ફાઇલ પસંદ કરો</u>",
    "max_size": "મહત્તમ મંજૂર કદ: {size}"
  },
  "timespan": {
    "Morning": "8am - 12pm",
    "Evening": "બપોરે 12 થી 6 વાગ્યા સુધી",
    "Night": "સાંજે 6 થી 12 વાગ્યા સુધી",
    "Instant": "ઇન્સ્ટન્ટ પોસ્ટ"
  },
  "week_day": {
    "Saturday": "શનિવાર",
    "Sunday": "રવિવાર",
    "Monday": "સોમવાર",
    "Tuesday": "મંગળવારે",
    "Wednesday": "બુધવાર",
    "Thursday": "ગુરુવાર",
    "Friday": "શુક્રવાર"
  },
  "payment_form": {
    "title": "ચુકવણી પદ્ધતિ પસંદ કરો",
    "gift_cards_input": "ભેટ માં આપવાના કાર્ડ્સ",
    "gift_cards_input_empty": "કોઈ ભેટ કાર્ડ મળ્યાં નથી..",
    "more": "અન્ય",
    "pay_amount_by_gift_cards": "ચાર્જ કાર્ડ ચુકવણી",
    "select_payment_method": "નીચેના વિકલ્પોમાંથી તમારી ચુકવણી પદ્ધતિ પસંદ કરો.",
    "payment_amount_remained": "બાકી ચુકવણીની રકમ",
    "payment_amount": "ચૂકવેલ રકમ",
    "all_paid_by_gift_cards": "અભિનંદન, તમારે આ ઓર્ડર માટે ચૂકવણી કરવાની જરૂર નથી. ગિફ્ટ કાર્ડ કી સાથે પે દબાવો.",
    "pay_by_gift_cards_action": "ચાર્જ કાર્ડ વડે ઓર્ડર ચૂકવો",
    "order_free_payment": "અભિનંદન, તમારો ઓર્ડર મફત છે!",
    "order_free_payment_action": "હવે ફ્રી ઓર્ડર કરો",
    "qr": {
      "address": "ચુકવણી સરનામું",
      "amount": "રકમ"
    }
  },
  "discount_input": {
    "limit": "{limit} {currency} સુધી {percent}% ડિસ્કાઉન્ટ",
    "action": "ડિસ્કાઉન્ટ કોડ ઉમેરો",
    "code_input": "ડિસ્કાઉન્ટ કોડ",
    "notifications": {
      "add_success": "અભિનંદન, માન્ય ડિસ્કાઉન્ટ કોડ."
    }
  },
  "gift_card": {
    "inactive": "કાર્ડ અક્ષમ છે",
    "expire": "સમાપ્તિ",
    "transfer": "ટ્રાન્સફર",
    "send_to_friend": "મિત્રને મોકલો"
  },
  "count_down": {
    "days": "દિવસ",
    "hours": "કલાક",
    "minutes": "મિનિટ",
    "seconds": "સેકન્ડ"
  },
  "gift_status": {
    "Unpaid": "રાહ રસીદ",
    "Paid": "ચૂકવેલ",
    "Rejected": "નામંજૂર",
    "Canceled": "રદ કરેલ"
  },
  "gift_program_status": {
    "Airdrop": "ચુકવણી સિસ્ટમ",
    "Advertising": "જાહેરાત",
    "PersonalGift": "વ્યક્તિગત ભેટ",
    "ShopGift": "ભેટ ખરીદવા માટેની ની દુકાન"
  },
  "currency_selector": {
    "label": "ચલણ"
  },
  "need_login": {
    "title": "પ્રવેશ કરો",
    "login_sms": "SMS લૉગિન",
    "login_google": "Google સાથે લૉગિન કરો",
    "login_facebook": "ફેસબુક સાથે લોગિન કરો",
    "login_account": "Selldone દ્વારા લૉગિન કરો",
    "register": "નવા વપરાશકર્તા? અત્યારે નોંધાવો.",
    "mobile_input": "તમારો મોબાઈલ દાખલ કરો",
    "verification_code": "ચકાસણી કોડ",
    "msg_title": "હાય,",
    "msg_body": "કૃપા કરીને લૉગિન કરો. તે માત્ર થોડી સેકન્ડ લે છે.",
    "login_apple": "Apple સાથે લૉગિન કરો"
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "5 વર્ષ સોનાની દુકાન"
    },
    "GOLDEN_2YEAR": {
      "name": "4 વર્ષ સોનાની દુકાન"
    },
    "GOLDEN_3YEAR": {
      "name": "3 વર્ષ સોનાની દુકાન"
    },
    "GOLDEN_4YEAR": {
      "name": "2 વર્ષ સોનાની દુકાન"
    },
    "GOLDEN_5YEAR": {
      "name": "1 વર્ષ સોનાની દુકાન"
    },
    "TOKEN_OWNER_1M": {
      "name": "ગોલ્ડન ઇન્વેસ્ટર"
    },
    "TOKEN_OWNER_10M": {
      "name": "ડાયમંડ ઇન્વેસ્ટર"
    },
    "TOKEN_OWNER_100M": {
      "name": "રૂબી રોકાણકાર"
    },
    "COMMUNITY_LOYAL": {
      "name": "કોમ્યુનિકેશન નેટવર્ક્સના સુપિરિયર કમ્યુનિટીના સભ્ય"
    },
    "GOLD_SUPPLIER": {
      "name": "ગોલ્ડ સપ્લાયર"
    },
    "GOLD_SELLER": {
      "name": "સોનાનો વેપારી"
    },
    "CONTENT_SUPERMAN": {
      "name": "ટોચના સામગ્રી નિર્માતા"
    },
    "NINJA": {
      "name": "નીન્જા"
    },
    "STAR": {
      "name": "તારો"
    },
    "GUARDIAN": {
      "name": "ગ્રેટ ગ્રાહક સેવા"
    },
    "KING": {
      "name": "બજારનો રાજા"
    }
  },
  "cookie": {
    "title": "આ વેબસાઇટ કૂકીઝનો ઉપયોગ કરે છે",
    "message": "આ વેબસાઇટ વપરાશકર્તા અનુભવને સુધારવા માટે કૂકીઝનો ઉપયોગ કરે છે. અમારી વેબસાઇટનો ઉપયોગ કરીને તમે અમારી કૂકી નીતિ અનુસાર તમામ કૂકીઝ માટે સંમતિ આપો છો.",
    "preferences_action": "પસંદગીઓ મેનેજ કરો",
    "agree_action": "હું સહમત છુ"
  },
  "basket_item_message": {
    "title": "આ આઇટમ માટે જરૂરી માહિતી",
    "save_actions": "સંદેશ સાચવો",
    "notifications": {
      "success": "તમારો ઇનપુટ ડેટા સાચવવામાં આવ્યો છે."
    }
  },
  "faq": {
    "faq": "વારંવાર પૂછાતા પ્રશ્નો",
    "title": "પ્રશ્ન અને જવાબ",
    "sub_title": "તમે અમને શું કરવાનું કહ્યું.",
    "message": "નીચેના જવાબો વચ્ચે તમારા પ્રશ્નનો જવાબ શોધો. પ્રશ્નો અનુત્તરિત રહે તો અમને પૂછો.",
    "add_question_action": "નવો પ્રશ્ન પૂછો",
    "read_more": "વધુ વાંચો ..",
    "load_more": "વધુ પ્રશ્નો..",
    "main_page": "FAQ મુખ્ય પૃષ્ઠ",
    "add_new": "નવો પ્રશ્ન સબમિટ કરો",
    "login_alert": "પ્રશ્ન પૂછવા માટે લોગ ઇન કરો.",
    "question_input": "પ્રશ્ન",
    "question_input_placeholder": "તમારો પ્રશ્ન પૂછો.",
    "notifications": {
      "success_add": "તમારો પ્રશ્ન સફળતાપૂર્વક સબમિટ થયો."
    }
  },
  "rating_labels": [
    "ખૂબ જ ખરાબ",
    "ખરાબ",
    "સામાન્ય",
    "સારું",
    "ઉત્તમ"
  ],
  "map_view": {
    "address_detail": "સરનામાની વિગતો",
    "change": "બદલો",
    "select": "પસંદ કરો",
    "not_found_address": "કોઈ મૂલ્ય મળ્યું નથી",
    "enter_address_hint": "ગંતવ્ય સરનામું દાખલ કરો",
    "enter_your_address": "તમારું સરનામું દાખલ કરો.",
    "postal_code": "પોસ્ટકોડ",
    "phone_input": "ફોન {type}",
    "building_number": "મકાન નંબર",
    "building_unit": "એકમ",
    "full_name_input": "પૂરું નામ {type}",
    "save_detail_action": "વિગતો સાચવો",
    "more_detail_input": "વધુ વર્ણન",
    "add_address_to_list": "યાદીમાં સરનામું ઉમેરો",
    "address_title_input": "સરનામું લેબલ (જરૂરી)",
    "notifications": {
      "save_in_list": "આ સરનામું તેની તમામ વિગતો સાથે તમારી યાદીમાં સાચવવામાં આવ્યું છે.",
      "edit_success": "નવા સરનામાં મૂલ્યો {title} માં સાચવવામાં આવ્યા છે."
    },
    "delete_address_dialog": {
      "title": "સરનામું કાઢી નાખો",
      "message": "શું તમે ખરેખર આ સરનામું કાઢી નાખવા માંગો છો?",
      "action": "સરનામું દૂર કરો"
    }
  },
  "comment_manager": {
    "can_not_edit": "આ ટિપ્પણી સંપાદિત કરી શકાતી નથી!",
    "comment_input_empty": "સંદેશ ટેક્સ્ટ ખાલી છે!",
    "article_not_saved": "લેખ સાચવો!"
  },
  "wheel_fortune": {
    "title": "રમો અને જીતો",
    "message": "દરેક રમતની કિંમત 10 ચિપ્સ છે. તમારી પાસે હાલમાં {chips} ચિપ છે. સ્ટોરમાંથી ખરીદી કરીને વધુ ચિપ મેળવો.",
    "win_message": "અભિનંદન, તમે જીત્યા!",
    "lost_message": "માફ કરશો, તમે રમત હારી ગયા છો.",
    "try_again": "તમે ફરી પ્રયાસ કરી શકો છો"
  },
  "json": {
    "add": "સ્ટ્રક્ચર ડેટા ઉમેરો",
    "add_message": "નવો સ્ટ્રક્ચર ડેટા બનાવો",
    "structures": "સ્ટ્રક્ચર્સ",
    "book": {
      "title": "પુસ્તક",
      "desc": "પુસ્તક ક્રિયાઓ જે વપરાશકર્તાઓને પુસ્તક ખરીદવા માટે સક્ષમ કરે છે જે તેઓ સીધા શોધ પરિણામોમાંથી મેળવે છે."
    },
    "occupation": {
      "title": "અંદાજિત પગાર",
      "desc": "પગારના અંદાજ વિશેની માહિતી, જેમ કે પગારની શ્રેણી અને નોકરીના પ્રકારો માટે પ્રદેશ-આધારિત પગાર સરેરાશ, Google પર નોકરી શોધ અનુભવમાં પ્રદર્શિત થાય છે."
    },
    "course": {
      "title": "અભ્યાસક્રમ",
      "desc": "શૈક્ષણિક અભ્યાસક્રમો કે જે પ્રદાતા-વિશિષ્ટ સૂચિમાં દેખાય છે. અભ્યાસક્રમોમાં અભ્યાસક્રમનું શીર્ષક, પ્રદાતા અને ટૂંકું વર્ણન શામેલ હોઈ શકે છે."
    },
    "howto": {
      "title": "કઈ રીતે",
      "desc": "કેવી રીતે કરવું એ વપરાશકર્તાઓને વિડિયો, છબીઓ અને ટેક્સ્ટ દર્શાવતા, કાર્યને સફળતાપૂર્વક પૂર્ણ કરવા માટે પગલાંઓના સમૂહ દ્વારા લઈ જાય છે."
    },
    "recipe": {
      "title": "રેસીપી",
      "desc": "રેસિપિ કે જે વ્યક્તિગત રિચ રિઝલ્ટ અથવા હોસ્ટ કેરોયુઝલના ભાગ તરીકે પ્રદર્શિત થાય છે."
    }
  },
  "support": {
    "Financial": "નાણાકીય",
    "Technical": "ટેકનિકલ",
    "Advisor": "સલાહકાર"
  },
  "condition": {
    "new": "નવી",
    "refurbished": "નવીનીકૃત",
    "used": "વપરાયેલ",
    "used_fair": "વાજબી ઉપયોગ",
    "used_good": "સારો ઉપયોગ કર્યો",
    "used_like_new": "નવાની જેમ વપરાય છે"
  },
  "variant_filter": {
    "title": "ઉત્પાદન વેરિઅન્ટ ફિલ્ટર",
    "only_available": "ઉપલબ્ધ છે"
  },
  "service": {
    "task": {
      "title": "કાર્યો",
      "message": "આ સેવામાં કરેલા કાર્યોની યાદી."
    },
    "appointment": {
      "title": "નિમણૂક",
      "message": "તમારા માટે યોગ્ય હોય તે દિવસ અને કલાકના આધારે નીચેના સમયમાંથી અઠવાડિયાનો સમય પસંદ કરો."
    },
    "booking": {
      "title": "બુકિંગ",
      "message": "નીચેના કેલેન્ડરમાં તમે જે દિવસો માટે આરક્ષણ કરવા માંગો છો તેનો સમયગાળો સ્પષ્ટ કરો."
    },
    "subscription": {
      "title": "સબ્સ્ક્રિપ્શન"
    },
    "charge": {
      "title": "ચાર્જ"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "નિશ્ચિત ભાવ",
      "message": "આ પ્રકારની કિંમતોમાં, ઉત્પાદનની કિંમત એક નિશ્ચિત રકમ હોય છે અને ખરીદનારને કિંમતની ગણતરીની વિનંતી કરવાની કોઈ જરૂર નથી."
    },
    "ESTIMATION": {
      "title": "અંદાજ કિંમત",
      "message": "ઑર્ડર આપતી વખતે વિક્રેતા દ્વારા ઉત્પાદનો અને સેવાઓની કિંમત અમુક અંશે ગણવામાં આવશે, સેવા દરમિયાન ચુકવણી ઇન્વૉઇસ બદલી અથવા ઉમેરી શકાય છે."
    },
    "AGREEMENT": {
      "title": "કરાર ભાવ",
      "message": "ઓર્ડર આપ્યા પછી વિક્રેતા દ્વારા ઉત્પાદનો અથવા સેવાઓની અંતિમ કિંમત બદલાશે નહીં."
    },
    "BID": {
      "title": "બિડ/ઓક્શન",
      "message": "ઉત્પાદન સંભવિત ખરીદદારો દ્વારા ઉચ્ચતમ બિડ કિંમતે વેચવામાં આવશે."
    }
  },
  "map": {
    "title": "ઉત્પાદનો પ્રાપ્ત કરવા માટેનું ગંતવ્ય",
    "confirm": "સ્થાન સેટ કરો",
    "address": "ગંતવ્ય",
    "receptor": "રીસીવર"
  },
  "ShopBots": {
    "telegram": "ટેલિગ્રામ"
  },
  "article_tags": {
    "title": "સામગ્રી ટૅગ્સ",
    "tags_input": "ટૅગ્સ",
    "tags_input_message": "આ લેખની ટૅગ્સની સૂચિ",
    "notification": {
      "add_success": "ટૅગ્સ ઉમેર્યા"
    }
  },
  "difficulties": {
    "very_complicated": "ખૂબ જટિલ",
    "hard": "કઠણ",
    "intermediate": "મધ્યમ",
    "easy": "સરળ"
  }
};