export default {
  "currency_default": "USD",
  "language_default": "he",
  "selldone": "סלדון",
  "store": "חנות",
  "not_exist": "לא קיים",
  "error": "שְׁגִיאָה",
  "active": "פָּעִיל",
  "inactive": "לֹא פָּעִיל",
  "required_value": "ערכים נדרשים",
  "original_warranty": "אחריות למוצר מקורי",
  "return_warranty_days": "{days} ימי אחריות להחזרה",
  "no_return_warranty": "אין דרך חזרה",
  "reed_agree_terms": "קראתי את תנאי השימוש ומדיניות הפרטיות ואני מסכים איתם.",
  "commons": {
    "Currency": "מַטְבֵּעַ",
    "COD": "COD",
    "State": "מדינה",
    "Price": "מחיר",
    "order_price": "כמות הזמנה",
    "VAT": "VAT",
    "Discount": "הנחה",
    "In_Stock": "במלאי",
    "Variants": "גרסאות",
    "No_variants": "אין וריאציה",
    "all": "את כל",
    "today": "היום",
    "yesterday": "אתמול",
    "license": "רישיון",
    "home": "בית",
    "support": "תמיכה",
    "messages": "הודעות",
    "no_message": "אין הודעה",
    "empty": "ריק",
    "phone": "טלפון",
    "address": "כתובת",
    "name": "שֵׁם",
    "password": "סיסמה",
    "email": "אימייל",
    "mobile": "נייד",
    "login": "התחברות",
    "register": "להירשם",
    "select_account": "בחר חשבון",
    "online": "באינטרנט",
    "offline": "לא מקוון",
    "finish": "סיים",
    "finished": "גָמוּר",
    "preview": "תצוגה מקדימה",
    "free": "חינם",
    "free_completely": "מנוי חינם לחלוטין",
    "fee": "תַשְׁלוּם",
    "month": "חוֹדֶשׁ",
    "months": "חודשים",
    "faq": "שאלות נפוצות",
    "question": "שְׁאֵלָה",
    "answer": "תשובה",
    "create_date": "צור תאריך",
    "update_date": "תאריך עדכון",
    "start_date": "תאריך התחלה",
    "end_date": "תאריך סיום",
    "social": "חֶברָתִי",
    "total": "סך הכל",
    "orders": "הזמנות",
    "sessions": "הפעלות",
    "product_views": "תצוגות מוצר",
    "add_to_carts": "הוסף לעגלות",
    "checkouts": "לבדוק",
    "payments": "תַשְׁלוּם",
    "organic_search": "חיפוש אורגני",
    "other": "אַחֵר",
    "landing_page": "דף נחיתה",
    "discount_code": "קוד הנחה",
    "total_sell": "סך המכירות",
    "details": "פרטים",
    "currency": "מַטְבֵּעַ",
    "amount": "כמות",
    "published": "יצא לאור",
    "draft": "טְיוּטָה",
    "save_changes": "שמור שינויים",
    "source": "מָקוֹר",
    "medium": "בינוני",
    "url": "כתובת אתר",
    "revenue": "הַכנָסָה",
    "performance": "ביצועים",
    "term": "טווח",
    "content": "תוֹכֶן",
    "session": "מוֹשָׁב",
    "product": "מוצר",
    "add": "לְהוֹסִיף",
    "checkout": "לבדוק",
    "payment": "תַשְׁלוּם",
    "more_options": "אפשרויות נוספות",
    "full_name": "שם מלא",
    "tel": "טל",
    "about_me": "עליי",
    "request_checking": "בקש בדיקה",
    "passport": "דַרכּוֹן",
    "birthday": "יום הולדת",
    "country": "מדינה",
    "city": "עִיר",
    "gender": "מִין",
    "offer": "הַצָעָה",
    "website": "אתר אינטרנט",
    "apply_for_all_products": "∞ הגש בקשה לכל המוצרים",
    "fix_commission": "עמלה קבועה",
    "percent_commission": "אחוז עמלה",
    "fixed_discount": "הנחה קבועה",
    "discount_percentage": "אחוז הנחה",
    "discount_limit": "מגבלת הנחה",
    "no_code": "אין קוד",
    "max_count": "ספירה מקסימלית",
    "count_unit": "פריטים",
    "used": "בשימוש",
    "daily": "יומי",
    "monthly": "יַרחוֹן",
    "yearly": "שְׁנָתִי",
    "state": "סטָטוּס",
    "disable": "השבת",
    "enable": "לְאַפשֵׁר",
    "activation_code": "קוד הפעלה",
    "quantity": "כַּמוּת",
    "no_club": "אין מועדון",
    "per_order": "לפי הזמנה",
    "count": "לספור",
    "seconds": "שניות",
    "auto": "אוטומטי",
    "title": "כותרת",
    "message": "הוֹדָעָה",
    "width": "רוֹחַב",
    "length": "אורך",
    "height": "גוֹבַה",
    "label": "תווית",
    "click": "נְקִישָׁה",
    "bank": "בַּנק",
    "default": "בְּרִירַת מֶחדָל",
    "role": "תַפְקִיד",
    "user": "מִשׁתַמֵשׁ",
    "users": "משתמשים",
    "code": "קוד",
    "total_payment": "סך התשלום",
    "balance": "איזון",
    "chance": "הִזדַמְנוּת",
    "free_for_new_users": "חינם למשתמשים חדשים",
    "prize_amount": "סכום הפרס",
    "win": "לנצח",
    "gift_card": "כרטיס מתנה",
    "discount": "הנחה",
    "config": "Config",
    "prize": "פרס",
    "Prizes": "פרסים",
    "result": "תוֹצָאָה",
    "price": "מחיר",
    "lottery": "הגרלה",
    "coupon": "קוּפּוֹן",
    "customer_club": "מועדון לקוחות",
    "shipping": "משלוח",
    "sum": "סְכוּם",
    "not_paid": "לא שולם",
    "category": "קטגוריה",
    "done": "בוצע",
    "email_from": "מ",
    "subject": "נושא",
    "schedule": "לוח זמנים",
    "files_list": "רשימת קבצים",
    "file_max_size": "גודל קובץ מקסימלי",
    "value": "ערך",
    "help": "עֶזרָה",
    "shipping_tax": "מס משלוח",
    "net_price": "מחיר נטו",
    "tax": "מַס",
    "tax_included": "כלול במחיר",
    "limit": "לְהַגבִּיל",
    "min_purchase": "מינימום רכישה",
    "eligible_for": "זכאי ל",
    "only_for_first_buy": "רק לרכישה ראשונה",
    "one_time_use": "יכול להשתמש פעם אחת",
    "period_of_qualify": "מגבלת שימוש לתקופה",
    "no_constraint": "אין גבול",
    "timespan": "תקופת זמן",
    "days": "ימים",
    "weight": "מִשׁקָל",
    "distance": "מֶרְחָק",
    "last_status": "סטטוס אחרון",
    "issued_at": "הונפק ב",
    "order": "להזמין",
    "order_detail": "פרטי הזמנה",
    "percent": "אָחוּז",
    "applied_count": "ספירה יישומית",
    "campaign": "קמפיין",
    "os": "מערכת הפעלה",
    "browser": "דפדפן",
    "device": "התקן",
    "device_ip": "כתובת IP של המכשיר",
    "location": "מקום",
    "user_agent": "סוכן משתמש",
    "affiliate": "שותף",
    "timeline": "ציר זמן",
    "add_note": "להוסיף הערה",
    "record": "תקליט",
    "unlimited": "ללא הגבלה",
    "show_coupons": "הצג קופונים",
    "hide_coupons": "הסתר קופונים",
    "service_area": "אזור שירות",
    "apps": "אפליקציות",
    "plugins": "תוספים",
    "bots": "בוטים",
    "categories": "קטגוריות",
    "products": "מוצרים",
    "business": "עֵסֶק",
    "personal": "אישי",
    "size": "גודל",
    "holiday": "חַג",
    "sod": "תשלום במשלוח",
    "cod": "מזומן במשלוח",
    "free_shipping": "משלוח חינם",
    "hours": "שעה (ות",
    "send_date": "תאריך משלוח",
    "deliver_date": "תאריך משלוח",
    "return_date": "תאריך חזרה",
    "pending": "ממתין ל",
    "delivered": "נמסר",
    "returned": "חזר",
    "canceled": "מבוטל",
    "shipping_cost": "מחיר משלוח",
    "action": "פעולה",
    "cancel_date": "בטל תאריך",
    "deliver_in_process": "ההזמנה נשלחת..",
    "kind": "סוּג",
    "detail": "פרטים",
    "map": "מַפָּה",
    "actions": "פעולות",
    "navigation": "ניווט",
    "navigation_app": "יישום",
    "payment_date": "תאריך תשלום",
    "duration": "מֶשֶׁך",
    "bill": "שטר כסף",
    "delivery_persons": "שליחים",
    "delivery_services": "שירותי משלוחים",
    "live_view": "שידור חי",
    "cart": "עֲגָלָה",
    "priority": "עדיפות",
    "sufficient_credit": "אשראי מספיק",
    "max_package_size": "גודל אריזה מקסימלי",
    "delay": "לְעַכֵּב",
    "credit": "אַשׁרַאי",
    "livemode": "לחיות",
    "paused": "מושהה",
    "debug": "לנפות",
    "token": "אֲסִימוֹן",
    "status": "סטָטוּס",
    "courier": "שָׁלִיחַ",
    "track": "מַסלוּל",
    "track_order": "מעקב אחר הזמנה",
    "cost": "עֲלוּת",
    "receipt": "קַבָּלָה",
    "origin": "מָקוֹר",
    "destination": "יַעַד",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "אין מספיק מלאי!",
    "sub_total": "סכום משנה",
    "customer": "צרכן",
    "delivery": "מְסִירָה",
    "online_orders": "הזמנות מקוונות",
    "pos_orders": "הזמנות קופה",
    "chips": "צ'יפס",
    "subscribed": "נרשם",
    "unsubscribed": "בוטל מנוי",
    "last_login": "כניסה אחרונה",
    "join_at": "תאריך הצטרפות",
    "club": "מוֹעֲדוֹן",
    "buyer": "קוֹנֶה",
    "seller": "מוֹכֵר",
    "or": "אוֹ",
    "type": "סוּג",
    "condition": "מַצָב",
    "brand": "מותג",
    "attempt": "לְנַסוֹת",
    "error": "שְׁגִיאָה",
    "success": "הַצלָחָה",
    "fail": "לְהִכָּשֵׁל",
    "inventory": "מְלַאי",
    "link": "קישור",
    "visits": "ביקורים",
    "transactions": "עסקאות",
    "vat": "VAT",
    "pos_vat": "מע\"מ קופה",
    "sort_by": "מיין לפי..",
    "from": "מ",
    "from_lead_time": "בתוך {hours} השעות הבאות",
    "no_credit_card_info": "אין מידע על כרטיס!",
    "active": "פָּעִיל",
    "not_active": "לא הופעל!",
    "referrals": "הפניות",
    "dashboard": "לוּחַ מַחווָנִים",
    "more": "יותר",
    "inactive": "לֹא פָּעִיל",
    "developer": "מפתח",
    "setting": "הגדרה",
    "membership_conditions": "תנאי חברות",
    "customers": "לקוחות",
    "created_at": "תאריך יצירה",
    "updated_at": "העדכון אחרון",
    "register_at": "תאריך הרשמה",
    "old": "ישן",
    "new": "חָדָשׁ",
    "start": "הַתחָלָה",
    "end": "סוֹף",
    "pos": "POS",
    "out_of_stock": "אזל במלאי",
    "fake": "מְזוּיָף",
    "low_inventory_warning": "שימו לב, מלאי נמוך!",
    "webhook": "Webhook",
    "notification": "הוֹדָעָה",
    "sms": "SMS",
    "online_payment_link": "קישור לתשלום מקוון",
    "waiting_load_data": "ממתין לטעינת נתונים..",
    "views": "צפיות",
    "sales": "מכירות",
    "total_views": "סך כל הצפיות",
    "total_sales": "סך המכירות",
    "from_previous_n_days": "מ-{days} ימים אחרונים",
    "drop_shipping": "דרופשיפינג",
    "commission": "עמלה",
    "shipping_area": "איזור משלוחים",
    "main_seller": "מוכר ראשי",
    "domain": "תְחוּם",
    "contact": "פרטים ליצירת קשר",
    "wallet": "ארנק",
    "reseller": "משווק",
    "tracking_code": "קוד מעקב",
    "tracking_url": "כתובת אתר למעקב",
    "fulfillments": "הגשמות",
    "reject": "לִדחוֹת",
    "reserved": "שמורות",
    "score": "ציון",
    "customer_price": "מחיר ללקוח",
    "options": "אפשרויות",
    "show_details": "הראה פרטים",
    "no_data": "אין מידע..",
    "waiting": "הַמתָנָה...",
    "waiting_connecting_payment": "מחכה לשירות התשלומים...",
    "creating_secure_payment": "יצירת תשלום מאובטח.",
    "officer": "קָצִין",
    "ticket": "כַּרְטִיס",
    "ticket_url": "כתובת אתר של כרטיס",
    "closed_at": "סגור בשעה",
    "close_ticket": "סגור כרטיס",
    "reopen_ticket": "פתח מחדש את הכרטיס",
    "require": "לִדרוֹשׁ*",
    "search": "לחפש...",
    "language": "שפה",
    "tasks": "משימות",
    "permissions": "הרשאות",
    "finish_date": "תאריך סיום",
    "complete_date": "תאריך השלמה",
    "settle_date": "מועד ההסדר",
    "cost_span": "טווח מחירים",
    "industry": "תַעֲשִׂיָה",
    "rating": "דירוגים",
    "rates": "דֵרוּג",
    "seen_at": "נראה ב",
    "completed": "הושלם",
    "you": "אתה",
    "shop": "לִקְנוֹת",
    "store": "חנות",
    "granted": "נכון",
    "deny": "לְהַכּחִישׁ",
    "request": "בַּקָשָׁה",
    "expert": "מוּמחֶה",
    "response": "תְגוּבָה",
    "requests": "בקשות",
    "experts": "מומחים",
    "responses": "תגובות",
    "negotiations": "משא ומתן",
    "all_chats": "כל הצ'אטים",
    "chats": "צ'אטים",
    "tags": "תגים",
    "description": "תיאור",
    "rates_count": "מספר דירוגים",
    "rate": "דֵרוּג",
    "comment": "תגובה",
    "chat": "לְשׂוֹחֵחַ",
    "install": "להתקין",
    "edited": "עָרוּך",
    "undo": "לבטל",
    "redo": "לַעֲשׂוֹת שׁוּב",
    "male": "זָכָר",
    "female": "נְקֵבָה",
    "calculator": "מַחשְׁבוֹן",
    "catalog": "קָטָלוֹג",
    "max_height": "גובה מקסימלי",
    "images_compare": "השוואת תמונות",
    "canvas": "בַּד",
    "table_of_contents": "תוכן עניינים",
    "comments": "הערות",
    "badge_codes": "קוד תגים",
    "need_more": "צריך עוד?",
    "invite_glow_caption": "קבלו 14.9$ לכל חבר!",
    "register_free": "100% הרשמה חינם",
    "gift": "מתנה",
    "google": "גוגל",
    "facebook": "פייסבוק",
    "instagram": "אינסטגרם",
    "instashop": "אינסטשופ",
    "show": "הופעה",
    "hide": "להתחבא",
    "waiting_review": "ממתין לסקירה",
    "not_selected": "לא נבחר",
    "time": "זְמַן",
    "final_price": "מחיר אחרון",
    "starting_price": "מחיר התחלתי",
    "day": "יְוֹם",
    "paid": "שולם",
    "service_bill": "תשלום חשבונית",
    "avocado": "אבוקדו",
    "delivery_price": "מחיר משלוח",
    "select_address": "בחר כתובת",
    "image": "תמונה",
    "view": "נוף",
    "sell": "מְכִירָה",
    "hyper": "יֶתֶר",
    "cart_list": "עֲגָלָה",
    "barcode_scanner": "סורק ברקוד",
    "scan_qr_code": "סרוק קוד QR",
    "new_carts": "עגלות חדשות",
    "pays": "תשלומים",
    "annually": "מדי שנה",
    "sells": "מכירות",
    "articles": "מאמרים",
    "jobs": "מקומות תעסוקה",
    "job": "עבודה",
    "blog": "בלוג",
    "deleted_at": "נמחק ב",
    "capacity": "קיבולת",
    "download_at": "תאריך הורדה אחרון",
    "downloads": "הורדות",
    "usage": "נוֹהָג",
    "select_upload_file": "בחר או שחרר קובץ",
    "download_link": "קישור להורדה",
    "uploading": "מעלה..",
    "files": "קבצים",
    "star": "כוכב",
    "speed": "מְהִירוּת",
    "feedback": "מָשׁוֹב",
    "new_messages": "הודעות חדשות",
    "file": "קוֹבֶץ",
    "attachment": "הִתקַשְׁרוּת",
    "gallery": "גלריה",
    "sync": "סינכרון",
    "diff_time": "הפרשי זמן",
    "network": "רֶשֶׁת",
    "account": "חֶשְׁבּוֹן",
    "configuration": "תְצוּרָה",
    "blockchain": "בלוקצ'יין",
    "blog_link": "קישור לבלוג",
    "community": "קהילה",
    "critical_zone": "אזור קריטי",
    "statistics": "סטָטִיסטִיקָה",
    "access": "גִישָׁה",
    "seo": "SEO",
    "followers": "עוקבים",
    "followings": "עוקבים",
    "private": "תצוגה מקדימה",
    "soon": "בקרוב",
    "features": "מאפיינים",
    "bot": "בוט",
    "sample": "לִטעוֹם",
    "how_it_work": "איך זה עובד?",
    "page": "עמוד",
    "congratulations": "מזל טוב",
    "recommend": "לְהַמלִיץ",
    "recommended": "מוּמלָץ",
    "recoms": "המלצות",
    "likes": "אוהב",
    "clicks": "קליקים",
    "platform": "פּלַטפוֹרמָה",
    "cms": "CMS",
    "cash": "כסף מזומן",
    "dir_payment": "העברה בנקאית",
    "auto_complete": "הושלם אוטומטי",
    "compare": "לְהַשְׁווֹת",
    "infinite": "אֵינְסוֹף",
    "tips": "טיפים",
    "technical": "טֶכנִי",
    "finance": "לְמַמֵן",
    "your_phone_input": "הזן מספר טלפון",
    "income": "הַכנָסָה",
    "change": "שינוי",
    "new_users": "משתמשים חדשים",
    "success_orders": "הזמנות מוצלחות",
    "direct": "ישיר",
    "last_activity": "פעילות אחרונה",
    "landing": "נְחִיתָה",
    "now": "עַכשָׁיו",
    "accept_agreement": "קראתי וקיבלתי את התנאים.",
    "report": "להגיש תלונה",
    "tablet": "לוּחַ",
    "pc": "PC",
    "acquisition_channel": "ערוץ רכישה",
    "to": "ל",
    "info": "מידע",
    "general": "כללי",
    "upload": "העלה",
    "general_config": "תצורה כללית",
    "limits_config": "מגבלות",
    "design_config": "עיצוב וסגנון",
    "duration_config": "מגבלת משך",
    "constraints_config": "מגבלות זכאות",
    "clubs_config": "זמין במועדונים",
    "additional_config": "הגדרות נוספות",
    "import": "יְבוּא",
    "ribbon": "סֶרֶט",
    "countries": "מדינות",
    "edit": "לַעֲרוֹך",
    "delete": "לִמְחוֹק",
    "analytics": "ניתוח",
    "rules": "כללים",
    "unset": "לא מוכן",
    "carts": "עגלות",
    "optional": "אופציונאלי",
    "design": "לְעַצֵב",
    "filter": "לְסַנֵן",
    "send": "לִשְׁלוֹחַ",
    "approved": "אושר",
    "unit": "יחידה",
    "profile": "פּרוֹפִיל",
    "shipping_rates": "תעריפי משלוח",
    "package": "חֲבִילָה",
    "overview": "סקירה כללית",
    "live": "לחיות",
    "never": "לעולם לא",
    "always": "תמיד",
    "mandatory": "חובה",
    "expire_at": "תאריך תפוגה",
    "position": "עמדה",
    "channel": "עָרוּץ",
    "age": "גיל",
    "charge": "לחייב",
    "giftcard": "כרטיס מתנה",
    "acquisition": "רְכִישָׁה",
    "conversion": "הֲמָרָה",
    "total_payments": "סה\"כ תשלומים",
    "community_ask": "שאל בקהילה",
    "children": "יְלָדִים",
    "export": "יְצוּא",
    "list": "רשימה",
    "hierarchy": "הִיֵרַרכִיָה",
    "images": "תמונות",
    "demo": "הַדגָמָה",
    "author": "מְחַבֵּר",
    "designer": "מְעַצֵב",
    "max": "מַקסִימוּם",
    "accepted": "מְקוּבָּל",
    "reply": "תשובה",
    "reviewed": "נבדק",
    "restored": "מְשׁוּחזָר",
    "merchant": "סוֹחֵר",
    "per_product": "לכל מוצר",
    "journey": "מסע",
    "after": "לאחר",
    "waiting_for_payment": "נא להשלים את התשלום...",
    "hour": "שָׁעָה",
    "minute": "דַקָה",
    "premium": "פּרֶמיָה",
    "light": "אוֹר",
    "dark": "אפל",
    "guest": "אוֹרֵחַ",
    "shops": "חנויות",
    "vendor": "מוֹכֵר",
    "vendors": "ספקים",
    "marketplace": "זירת מסחר",
    "verify_date": "אמת את התאריך",
    "note": "פתק",
    "panel": "לוּחַ",
    "removed": "הוסר",
    "segments": "פלחים",
    "personal_info": "מידע אישי",
    "preferences": "העדפות",
    "spec": "מפרט",
    "reviews": "ביקורות",
    "constraints": "אילוצים",
    "flexible": "גָמִישׁ",
    "usage_limit": "מגבלת שימוש",
    "temporary": "זמני",
    "original": "מְקוֹרִי",
    "saved": "שמור!",
    "sort": "סוג",
    "documents": "מסמכים",
    "document": "מסמך",
    "please_wait": "המתן בבקשה...",
    "pickup": "לאסוף",
    "customize": "להתאים אישית",
    "difficulty": "קושי",
    "banned": "אָסוּר",
    "company": "חֶברָה",
    "tax_shipping": "מס משלוח",
    "warranty": "אַחֲרָיוּת",
    "return_policy": "מדיניות החזרה",
    "guide": "להנחות",
    "translate": "תרגם",
    "public": "פּוּמְבֵּי",
    "deleted": "נמחק",
    "variant": "גִרְסָה אַחֶרֶת",
    "secure": "לבטח",
    "admin": "מנהל מערכת"
  },
  "dialogs": {
    "delete": {
      "title": "לִמְחוֹק",
      "message": "האם אתה בטוח שתמחק את הפריט הזה?",
      "action": "כן, מחק עכשיו"
    }
  },
  "actions": {
    "add_to_cart": "הוסף לעגלה",
    "cancel": "לְבַטֵל",
    "update": "עדכון",
    "add": "לְהוֹסִיף",
    "delete": "לִמְחוֹק",
    "new": "חָדָשׁ",
    "save_continue": "שמור המשך",
    "save": "להציל",
    "save_changes": "שמור שינויים",
    "change": "שינוי",
    "continue": "לְהַמשִׁיך",
    "close": "סגור",
    "finish": "סיים",
    "poll": "מִשׁאָל",
    "view": "נוף",
    "edit": "לַעֲרוֹך",
    "next": "הַבָּא",
    "previous": "קודם",
    "create": "לִיצוֹר",
    "set": "מַעֲרֶכֶת",
    "find": "למצוא",
    "accept": "לְקַבֵּל",
    "reject": "לִדחוֹת",
    "back": "חזור",
    "pay": "לְשַׁלֵם",
    "pay_now": "שלם עכשיו",
    "print": "הדפס",
    "return": "לַחֲזוֹר",
    "publish": "לְפַרְסֵם",
    "confirm": "לְאַשֵׁר",
    "copy": "עותק",
    "submit": "שלח",
    "send": "לִשְׁלוֹחַ",
    "yes": "כן",
    "no": "לא",
    "meh": "הממ",
    "clear": "ברור",
    "dismiss": "לשחרר",
    "search": "לחפש",
    "deselect_all": "הסר סימון מהכל",
    "select_all": "בחר הכל",
    "refresh": "לְרַעֲנֵן",
    "verify": "תאשר",
    "play": "לְשַׂחֵק",
    "open": "לִפְתוֹחַ",
    "calculate": "לחשב",
    "quick_buy": "קנייה מהירה",
    "click_here": "לחץ כאן",
    "schedule": "לוח זמנים",
    "send_now": "שלח עכשיו",
    "download": "הורד",
    "reset_default": "אפס לברירת המחדל",
    "reset": "אִתחוּל",
    "check": "חשבון",
    "cod_payment": "מזומן במשלוח",
    "dir_payment": "העברת כספים",
    "online_payment": "תשלום אונליין",
    "checkout": "לבדוק",
    "show_all": "תראה הכול",
    "login": "התחברות",
    "logout": "להתנתק",
    "more": "יותר..",
    "collapse": "הִתמוֹטְטוּת",
    "apply_change": "החל שינויים",
    "apply": "להגיש מועמדות",
    "add_giftcard": "הוסף כרטיס מתנה",
    "charge": "לחייב",
    "send_invites": "לשלוח הזמנות",
    "past": "עבר",
    "restore": "לשחזר",
    "cut": "גזירה",
    "get_sms_code": "קבל קוד אימות",
    "register_no_mail": "המשך ללא דוא\"ל",
    "no_mail_register_message": "אין לך כתובת אימייל או שכחת את הסיסמה שלך?",
    "reset_by_mail": "שחזור סיסמא בדוא\"ל",
    "reset_by_sms": "שחזור סיסמא באמצעות SMS",
    "cash_payment": "תשלום במזומן",
    "show_chart": "הצג תרשים",
    "open_app": "אפליקציה פתוחה",
    "login_now": "התחבר עכשיו",
    "watch_video": "צפה בוידאו",
    "check_now": "בדוק עכשיו",
    "remove_image": "הסר תמונה",
    "view_website": "פתח קישור",
    "explore": "גלה את {name}",
    "go": "ללכת",
    "read_more": "קרא עוד",
    "start_now": "התחל עכשיו - זה בחינם",
    "view_live": "צפה בשידור חי",
    "resend_code": "שלח קוד שוב",
    "invite": "להזמין",
    "add_more": "הוסף עוד",
    "install_now": "להתקין עכשיו",
    "uninstall": "הסר את ההתקנה",
    "show_preview": "הצג תצוגה מקדימה",
    "hide_preview": "הסתר תצוגה מקדימה",
    "download_now": "הורד עכשיו",
    "auto_fill": "מילוי אוטומטי",
    "track": "מַסלוּל",
    "change_state": "לשנות סטטוס",
    "done": "בוצע",
    "reply": "תשובה",
    "watch_now": "צפה עכשיו",
    "unlock": "לבטל נעילה",
    "lock": "לנעול",
    "create_clone": "צור שיבוט",
    "regenerate": "לְהִתְחַדֵשׁ",
    "add_message": "הוסף הודעה",
    "continue_chat": "המשך בצ'אט",
    "add_new_message": "הוסף הודעה חדשה"
  },
  "instance_message_title": "שלח הודעה מיידית",
  "instance_message": "היי {name}, שמי {author} מ-{company}.",
  "errors": {
    "419": "לא היית פעיל במשך זמן רב, אנא <b>⟳ רענן את העמוד</b> מסיבות אבטחה.",
    "gateway_blockchain_sync_error": "המערכת לא מסתנכרנת עם הבלוקצ'יין. לא ניתן יהיה ליצור עסקה חדשה עד להשלמת הסנכרון של השרתים שלנו. אנחנו פותרים את הבעיה.",
    "gateway_network_error": "שירות שער תשלום נתקל בבעיית תקשורת."
  },
  "receiver_info": {
    "map": {
      "title": "כתובת למשלוח",
      "confirm": "הזן מיקום",
      "address_type": "יַעַד",
      "receptor_type": "מַקְלֵט"
    },
    "receiver_address": "בחר כתובת למשלוח",
    "address": "כתובת",
    "postcode": "מיקוד",
    "enter_value": "מלא כאן",
    "address_note": "פתק",
    "tel": "מספר איש קשר",
    "service_address": "בחר את הכתובת שלך"
  },
  "weight": {
    "g": "ז",
    "oz": "עוז",
    "lb": "lb",
    "kg": "ק\"ג"
  },
  "mass_unit_name": {
    "g": "גְרַם",
    "oz": "אוּנְקִיָה",
    "lb": "לִירָה",
    "kg": "קִילוֹגרָם"
  },
  "length": {
    "cm": "ס\"מ",
    "in": "ב",
    "ft": "ft",
    "mm": "מ\"מ",
    "m": "M",
    "yd": "yd"
  },
  "size_unit_name": {
    "cm": "סַנטִימֶטֶר",
    "in": "אִינְטשׁ",
    "ft": "כף רגל",
    "mm": "מִילִימֶטֶר",
    "m": "מטר",
    "yd": "חָצֵר"
  },
  "distance": {
    "m": "מטר",
    "km": "ק\"מ"
  },
  "time": {
    "days": "ימים",
    "hours": "שעה (ות",
    "minutes": "דקות",
    "seconds": "שניות"
  },
  "units": [
    "יחידה",
    "פריט",
    "כל אחד",
    "מַעֲרֶכֶת",
    "לְחַבֵּר",
    "קִילוֹגרָם",
    "גְרַם",
    "מִילִיגרָם",
    "מטר",
    "מִילִימֶטֶר",
    "מטר מרובע",
    "מטר - רבוע",
    "מטר מרובע",
    "לִיטר",
    "מיליליטר",
    "רגליים",
    "גלונים",
    "אינץ",
    "אונקיות",
    "פאונד",
    "ליטר",
    "מטרים",
    "חֶדֶר",
    "שניות",
    "דקות",
    "שעה (ות",
    "ימים",
    "שבועות",
    "חודשים",
    "שנים"
  ],
  "region_types": {
    "State": "מדינה",
    "Territory": "שֶׁטַח",
    "Province": "מָחוֹז"
  },
  "transaction_status": {
    "RequireAction": "פעולה נדרשת",
    "Processing": "מעבד",
    "Canceled": "מבוטל",
    "Succeeded": "הצליח"
  },
  "placeholders": {
    "name": "ג'ון קוקס",
    "email": "your-mail@mail.com",
    "phone": "+1,000,0000",
    "language": "בחר שפה..",
    "friend_email": "האימייל של חבריך...",
    "friend_name": "העדיף. שם חברך",
    "select_date": "בחר תאריך..."
  },
  "notification": {
    "confirm": "לְאַשֵׁר",
    "confirm_message": "השינויים נשמרו בהצלחה.",
    "error": "שְׁגִיאָה",
    "message": "הוֹדָעָה",
    "caution": "זְהִירוּת",
    "warning": "אַזהָרָה",
    "award": "מזל טוב",
    "error_message": "למרבה הצער, אירעה שגיאה.",
    "congratulation": "מזל טוב",
    "coming_soon": "בקרוב",
    "on_fetching_data": "מקבל מידע..",
    "new_pwa_version": "גרסה חדשה זמינה כעת. האם ברצונך לעדכן את האפליקציה?",
    "over_license_limit": "מעל מגבלת הרישיון",
    "update_license": "עדכן את הרישיון שלך",
    "required": "נדרש",
    "invalid_email": "אימייל שגוי",
    "invalid_domain": "דומיין לא חוקי",
    "invalid_min_length": "האורך המינימלי חייב להיות {length}",
    "invalid_min_array_length": "בחר לפחות {length} פריטים",
    "invalid_max_chars": "מקסימום {maxCount} תווים",
    "invalid_url": "כתובת אתר לא חוקית",
    "country_invalid": "בחר מדינת יעד!",
    "postal_code_invalid": "הגדר מיקוד חוקי!"
  },
  "colors": {
    "#D32F2F": "אָדוֹם",
    "#C2185B": "וָרוֹד",
    "#7B1FA2": "סָגוֹל",
    "#512DA8": "סגול כהה",
    "#303F9F": "כחול אינדיגו",
    "#1976D2": "כָּחוֹל",
    "#0288D1": "כחול בהיר",
    "#0097A7": "כחול טורקיז",
    "#00796B": "ירוק אווז",
    "#388E3C": "ירוק",
    "#689F38": "ירוק בהיר",
    "#AFB42B": "לימוזינה",
    "#FBC02D": "צהוב",
    "#FFA000": "עַנבָּר",
    "#F57C00": "תפוז",
    "#E64A19": "כתום מבריק",
    "#5D4037": "חום",
    "#616161": "אפור",
    "#455A64": "כחול אפור",
    "#FFD700": "זָהוּב",
    "#C0C0C0": "כסף",
    "#b76e79": "ורד מוזהב",
    "#383838": "שחור מט",
    "#FFFFFF": "לבן",
    "#FFF": "לבן",
    "#000000": "שָׁחוֹר",
    "#000": "שָׁחוֹר",
    "#7d263a": "חוּם עֲרמוֹנִי",
    "#FD9F17": "זהב",
    "#229DBF": "אקווה",
    "#6DC9E2": "אקווה טריבלנד",
    "#413B2D": "צָבָא",
    "#474747": "אַספַלט",
    "#E6195C": "ברי",
    "#B2184C": "ברי טריבלנד",
    "#FC7F5F": "תפוז שרוף",
    "#80011F": "קַרדִינָל",
    "#382829": "שוקולד",
    "#F06336": "אלמוג",
    "#FAE7C9": "קרם",
    "#6B2257": "דומדמניות",
    "#222127": "אפור כהה",
    "#0D5A74": "דיפ טיל",
    "#00582F": "יָרוֹק עַד",
    "#214C30": "יַעַר",
    "#DC2867": "ורוד פוקסיה",
    "#38561F" :"קלי",
    "#5C884D": "עלה",
    "#558450": "אקווה קלה",
    "#96B5C9": "כחול בהיר",
    "#DCAFCE": "לִילָך",
    "#D3E1A4": "ליים",
    "#9DE7C2": "מנטה",
    "#F6EAD2": "טִבעִי",
    "#1A1F35": "חיל הים",
    "#404624": "זית",
    "#271020": "שזיף",
    "#A8355C": "פֶּטֶל",
    "#D6BEA6": "קרם רך",
    "#BEA994": "לְהִשְׁתַזֵף",
    "#0DB2AE": "ירוק כחלחל",
    "#A86EA9": "סָגוֹל",
    "#36454F": "פֶּחָם",
    "#b3b0ab": "פחמן אפור",
    "#463e3d": "פחם הת'ר",
    "#282d3c": "בלייזר חיל הים"
  },
  "address_info": {
    "name": "שֵׁם",
    "tel": "טלפון",
    "email": "אימייל",
    "country": "מדינה",
    "city": "עִיר",
    "state": "מדינה",
    "address": "כתובת",
    "building_number": "מספר בניין",
    "building_unit": "יחידה",
    "postcode": "מיקוד",
    "note": "פתק",
    "county": "מָחוֹז"
  },
  "product_types": {
    "physical": "גוּפָנִי",
    "physical_description": "מוצרים פיזיים כגון: טלפונים ניידים, ספרים, רכיבים אלקטרוניים.",
    "virtual": "וירטואלי",
    "virtual_description": "מוצרים ידידותיים לאינטרנט כגון: כרטיס טעינה, הזמנת מלון, טעינת משחקים.",
    "file": "קוֹבֶץ",
    "file_description": "כל הקבצים המותרים כמו וידאו קורס מקוון, מסמכים להורדה.",
    "service": "שֵׁרוּת",
    "service_description": "שירותים כמו: תיקון, הובלה, הוראה."
  },
  "license": {
    "free": "חינם",
    "startup": "סטארט - אפ",
    "company": "חֶברָה",
    "enterprise": "מִפְעָל"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "לאיש",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW",
    "GHS": "GHS",
    "ZWD": "ZWD",
    "IQD": "IQD",
    "SYP": "SYP"
  },
  "variants": {
    "color": "צֶבַע",
    "volume": "גודל",
    "count_in_pack": "לספור בחבילה",
    "weight": "מִשׁקָל",
    "type": "חוֹמֶר",
    "style": "סִגְנוֹן"
  },
  "delivery_state": {
    "check_queue": "ממתין לסקירה",
    "order_confirm": "אישור הזמנה",
    "preparing_order": "מכין",
    "sent_order": "במשלוח",
    "to_customer": "נמסר"
  },
  "status": {
    "unpaid": "ללא תשלום",
    "paid": "שולם",
    "canceled": "מבוטל",
    "completed": "מְיוּשָׁב",
    "reserved": "שמורות",
    "COD": "COD",
    "sold": "נמכר",
    "open": "לִפְתוֹחַ",
    "cancel": "מבוטל",
    "active": "פָּעִיל",
    "inactive": "לֹא פָּעִיל",
    "debug": "לנפות",
    "live": "לחיות",
    "test": "מִבְחָן",
    "connected": "מְחוּבָּר",
    "disconnected": "מְנוּתָק",
    "accept": "לְקַבֵּל",
    "reject": "לִדחוֹת",
    "pending": "ממתין ל",
    "rejected": "נִדחֶה",
    "accepted": "מְקוּבָּל"
  },
  "dimensions": {
    "cm": "ס\"מ",
    "km": "ק\"מ",
    "kg": "ק\"ג"
  },
  "transportation_type": {
    "motorbike": "אוֹפנוֹעַ",
    "motorbike_description": "משקל בינוני תוך כמה קילומטרים.",
    "cargo_small": "מטען קטן",
    "cargo_small_description": "מטען קל רב קילומטרים.",
    "cargo": "מטען",
    "cargo_description": "משקל בינוני תוך כמה קילומטרים.",
    "truck": "מַשָׂאִית",
    "truck_description": "מטען בתפזורת או כבד בתוך הארץ.",
    "fast_post": "פוסט מהיר",
    "fast_post_description": "פרסום מהיר באמצעות הדואר.",
    "post": "פוסט רגיל",
    "post_description": "דואר רגיל דרך סניף הדואר.",
    "airplane": "דואר אויר",
    "airplane_description": "מטען קל ובינוני מקומי וזר.",
    "bicycle": "שלח נקי",
    "bicycle_description": "מטען קל, בטווח של כמה מאות מטרים מכלי רכב לא מנועי.",
    "global": "תחבורה גלובלית",
    "global_description": "משלוח לחו\"ל באוויר, בים או יבשתי.",
    "pickup": "לאסוף",
    "pickup_description": "לקוחות אוספים את הפריטים בחנות או במחסן הפיזי שלך."
  },
  "article": {
    "login_to_see_error": "התחבר כדי לגשת למאמר",
    "create_new_action": "צור תוכן חדש",
    "menu_title": "תַפרִיט",
    "menu": {
      "edit": "מצב עריכה",
      "view_mode": "מצב צפייה",
      "delete": "מחק מאמר"
    },
    "schedule_action": "האם אתה רוצה לתזמן פרסום?",
    "schedule_title": "תזמן פרסום אוטומטי",
    "edit_mode": "לַעֲרוֹך",
    "public_view_mode": "ראייה ציבורית",
    "publish_at": "פרסם ב",
    "published": "יצא לאור",
    "draft": "טְיוּטָה",
    "saving": "חִסָכוֹן",
    "save_and_publish_action": "שמור ופרסם",
    "save_draft_action": "שמור טיוטה",
    "private": "פְּרָטִי",
    "public": "פּוּמְבֵּי",
    "category_input": "קטגוריה",
    "category_input_message": "בחר קטגוריית מאמרים",
    "parent_input": "קטגורית הורים",
    "parent_input_message": "בחר תוכן אב",
    "schedule_input": "לוח זמנים",
    "schedule_input_placeholder": "אם אתה רוצה שהסיפור יתפרסם בזמן מסוים.",
    "schedule_view_action": "הצג את לוח הזמנים לפרסום",
    "author_title": "נכתב על ידי",
    "read_time": "זמן לימודים",
    "read_time_unit": "דקות",
    "claps_action": "מחיאות כפיים",
    "claps": "מחיאות כפיים",
    "likes": "כמו",
    "about_author": "על הסופר",
    "updated_at": "מְעוּדכָּן",
    "wrote_at": "נכתב ב",
    "now": "עַכשָׁיו",
    "follow_action": "לעקוב אחר",
    "followed": "בעקבות",
    "report_and_delete_action": "דווח ומחק מאמר זה",
    "report_action": "דווח על שימוש לרעה",
    "you_reported_this_article": "למאמר זה כבר יש דיווח על שימוש לרעה.",
    "add_to_publication_action": "הוסף לפרסום",
    "author_socials": "מחבר ברשתות חברתיות",
    "share": "לַחֲלוֹק",
    "report_dialog": {
      "report_and_delete_title": "דווח על שימוש לרעה והסר תוכן",
      "report_title": "דווח על תוכן זה כפוגעני",
      "message": "מהי הסיבה להגשת תוכן זה? בחר אחת מהאפשרויות הבאות.",
      "accept_and_delete_action": "אשר ומחק תוכן"
    },
    "schedule_dialog": {
      "title": "לוח זמנים לפרסום תוכן",
      "publish_at": "פרסם ב",
      "last_edit": "עריכה אחרונה",
      "view_action": "צפו במאמר"
    },
    "notifications": {
      "update_success_title": "שלח מידע",
      "update_success": "המאמר עודכן בהצלחה.",
      "update_error": "המידע שהוזן אינו חוקי.",
      "delete_error": "אתה לא יכול למחוק את המאמר הזה!",
      "report_and_delete_success_title": "דווח ומחק",
      "report_and_delete_success_message": "המאמר נמחק בהצלחה.",
      "report_success_title": "מאמר דיווח",
      "report_success_message": "הדיווח שלך על מאמר זה פורסם."
    },
    "alert": {
      "delete_article": {
        "title": "מחק מאמר",
        "message": "האם אתה בטוח שברצונך למחוק מאמר זה לצמיתות?",
        "action": "לִמְחוֹק"
      }
    },
    "edit_window": {
      "title": "בחר טקסט תמונה וסיכום",
      "digest": "סיכום"
    },
    "editor": {
      "title_placeholder": "כותרת..",
      "body_placeholder": "כתוב תוכן מעולה..",
      "accept_file_types_error": "פורמט קובץ זה אינו מקובל:",
      "max_file_size_error": "הקובץ הזה גדול מדי:",
      "notifications": {
        "image_uploaded_success": "התמונה נשמרה בהצלחה",
        "image_uploaded_failed": "שגיאה בטעינת התמונה."
      },
      "embed_placeholder": "הזן את קוד ה-iframe, Facebook, Youtube או כל כתובת אתר אחרת והקש אנטר.",
      "embed_caption_placeholder": "הזן כותרת (אופציונלי)",
      "images_caption_placeholder": "הזן כותרת לתמונה זו .."
    }
  },
  "article_report": {
    "inappropriate": "התוכן של מאמר זה אינו הולם.",
    "fake": "זה מזויף ומטעה.",
    "spam": "פריט זה זכה לספאם והועתק.",
    "scam": "צפוי שזה יגרום לתוכנות זדוניות, וירוסים או קריסת מערכת.",
    "hacked": "נראה שהאתר הזה נפרץ.",
    "offensive": "תוכן השפה ואוצר המילים אינם אתיים ולא מכבדים.",
    "violent": "אני חושב שהתוכן הזה מכיל פורנוגרפיה והוא מפר את החוקים.",
    "harassment": "אני חושב שזה גזעני.",
    "hate": "אני חושב שזה קשור לקידום אלימות.",
    "infringe": "זה פוגע בזכויות שלי."
  },
  "comments": {
    "new_action": "לחץ כדי להשאיר תגובה..",
    "title": "הערות",
    "body_placeholder": "התגובה או ההודעה שלך",
    "send_action": "שלח תגובה",
    "body_is_empty_error": "התגובה ריקה!",
    "comments": "הערות",
    "no_comments": "כתוב תגובה ראשונה...",
    "load_more_action": "קבלו עוד תגובות..",
    "cant_send_comment": "אתה לא יכול להוסיף פוסט חדש.",
    "cant_remove_this_comment": "אתה לא יכול למחוק את התגובה הזו!",
    "product_buyer": "קוֹנֶה",
    "delete_alert": {
      "title": "מחק תגובה",
      "message": "האם אתה רוצה למחוק את התגובה הזו?",
      "action": "לִמְחוֹק"
    },
    "notifications": {
      "delete_success": "התגובה שלך נמחקה בהצלחה."
    },
    "first_send": "פוסט ראשון",
    "comment_at": "עַל",
    "edit_comment": "ערוך תגובה"
  },
  "customer_club": {
    "bronze": "בְּרוֹנזָה",
    "silver": "כסף",
    "gold": "זָהוּב",
    "platinum": "פְּלָטִינָה",
    "diamond": "יהלום"
  },
  "application_categories": {
    "tracking": "בדיקת התנהגות משתמש",
    "payment": "תַשְׁלוּם",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "הוֹבָלָה",
    "automation": "אוטומציה",
    "inventory": "אחסנה",
    "accounting": "חשבונאות",
    "marketing": "שיווק",
    "advertising": "פִּרסוּם",
    "staff": "צוות",
    "incentive": "תמריצים",
    "shop": "לִקְנוֹת"
  },
  "social_network": {
    "instagram": "אינסטגרם",
    "telegram": "מִברָק",
    "googleplay": "גוגל פליי",
    "appstore": "חנות אפליקציות",
    "twitter": "טוויטר",
    "linkedin": "לינקדאין",
    "medium": "בינוני",
    "selldone": "סלדון",
    "facebook": "פייסבוק",
    "pinterest": "פינטרסט",
    "whatsapp": "וואטסאפ",
    "skype": "סקייפ",
    "facebook_messenger": "מסנג'ר של פייסבוק"
  },
  "form_builder": {
    "add_item_action": "הוסף פריט חדש",
    "title_input": "כותרת",
    "name_input": "שם משתנה",
    "value_input": "ערכים",
    "value_input_message": "רשימת אפשרויות משתמש",
    "default": "ערך ברירת מחדל",
    "types": {
      "simple": "פָּשׁוּט",
      "selective": "סֶלֶקטִיבִי",
      "switch": "החלף",
      "file": "קוֹבֶץ",
      "number": "מספר"
    },
    "placeholder_input": "מציין מקום",
    "file_type_input": "סוגי קבצים מקובלים",
    "file_type_message": "jpeg, png, zip,..."
  },
  "virtual_order_info_summery": {
    "title": "שם מוצר",
    "reserved_at": "תאריך רישום",
    "total_price": "הכמות הכוללת",
    "discount": "הנחה",
    "final_price": "סכום סופי",
    "payment_status": "מצב תשלום",
    "payment_status_waiting": "מחכה לתשלום",
    "payment_status_paid": "שולם",
    "buyer": "קוֹנֶה"
  },
  "virtual_item_info": {
    "title": "פריט וירטואלי",
    "outputs": {
      "title": "מידע פלט",
      "sub_title": "מידע סודי של פריט זה",
      "message": "מידע זה יוצג למשתמש לאחר רכישת המוצר."
    },
    "inputs": {
      "title": "מידע נדרש",
      "sub_title": "נדרש מידע לקונה",
      "message": "על הקונה להזין את המידע המבוקש בטופס"
    },
    "notifications": {
      "inputs_set_success": "טופס מידע נרשם בהצלחה.",
      "confirm_by_admin_success": "השלמת ההזמנה אושרה.",
      "confirm_by_buyer_success": "השלמת ההזמנה אושרה."
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "לא ניתן לקבל הזמנה זו על ידי תשלום COD.",
    "payment_returned": "התשלום על ידי הלקוח מוחזר.",
    "payment_fraud": "התשלום זוהה כהונאה.",
    "location_out_of_service": "מיקום הלקוח אינו בשירות.",
    "user_not_responding": "הלקוח לא ענה לשיחות.",
    "shop_owner_fault": "אירעה שגיאה של צוות החנות במילוי המידע.",
    "lack_of_inventory": "אזל במלאי.",
    "legal_restriction": "לא ניתן לבצע הזמנה עקב מגבלות חוקיות.",
    "pricing_fault": "טעות בתמחור של המוכר.",
    "system_fault": "באג מערכת."
  },
  "basket_order_info_summery": {
    "receiver": "מַקְלֵט",
    "phone": "טל",
    "reserved_date": "תאריך רכישה",
    "total_price": "הכמות הכוללת",
    "discount": "הנחה",
    "final_price": "סכום סופי",
    "address": "כתובת למשלוח",
    "payment_status": "מצב תשלום"
  },
  "basket_status": {
    "open": "לִפְתוֹחַ",
    "reserved": "שמורות",
    "paid": "שולם",
    "canceled": "מבוטל",
    "cod": "תשלום במשלוח",
    "receipt_added": "נוספה קבלה",
    "payment_processing": "עיבוד תשלומים"
  },
  "basket_delivery_state": {
    "rejected": "נִדחֶה",
    "reject_reason_not_found": "הסיבה לא ידועה.",
    "step_1": "סקירה",
    "step_2": "אִשׁוּר",
    "step_3": "הכנה",
    "step_4": "במשלוח",
    "step_5": "נמסר"
  },
  "basket_return_request_view": {
    "title": "בקשת החזרה",
    "delivery_date": "תאריך משלוח",
    "return_date": "תאריך מבוקש",
    "items_count": "פריטים שהוחזרו סופרים",
    "items_count_unit": "פריט(ים)",
    "reason": "סיבה",
    "description": "תיאור",
    "status": "סטָטוּס",
    "download_image": "הורד תמונה",
    "download_film": "הורד סרטון",
    "download_voice": "הורד קול",
    "accept_by_admin_action": "קבל בקשה",
    "reject_by_admin_action": "דחה בקשה",
    "message_for_admin": "על פי ההסכם שקיבלת על ידי שימוש ב-Seldone, עליך ליצור קשר עם הקונה ולעדכן אותו בתהליך החזרת ההזמנה שלו. יש לעשות זאת במידה והבקשה מתקבלת או נדחית ומתקבלת הסכמתו המלאה של הקונה.",
    "notifications": {
      "update_status_success": "סטטוס הבקשה עודכן."
    }
  },
  "basket_list": {
    "return_count": "החזרה: מספר {count}",
    "table": {
      "row": "שׁוּרָה",
      "image": "תמונה",
      "product_name": "מוצר",
      "variant": "גִרְסָה אַחֶרֶת",
      "warranty": "אחריות",
      "count": "לספור",
      "price": "מחיר"
    }
  },
  "return_request_list": {
    "count": "מספר אסמכתא",
    "return_warranty": "אחריות להחזר כספי",
    "return_warranty_unit": "ימים",
    "table": {
      "code": "קוד הזמנה",
      "product": "מוצר",
      "delivery_at": "תאריך קבלה",
      "state": "סטָטוּס",
      "reason": "סיבה",
      "return_warranty_period": "תקופת אחריות"
    }
  },
  "data_toolbar": {
    "search": "לחפש",
    "sort_by": "מיין לפי",
    "count_item": "הצג {item} פריטים"
  },
  "sort": {
    "created_at": "צור תאריך",
    "updated_at": "ערוך תאריך",
    "title": "כותרת",
    "description": "תיאור",
    "like": "פּוֹפּוּלָרִיוּת",
    "power": "מחיאות כפיים",
    "product_type": "סוג המוצר",
    "discount": "הנחה",
    "rate": "דֵרוּג",
    "rate_count": "מספר דירוגים",
    "category": "קטגוריה",
    "product": "מוצר",
    "body": "תוֹכֶן",
    "card_type": "סוג כרטיס",
    "card_number": "מספר כרטיס",
    "balance": "איזון",
    "paid": "סכום שהוצא",
    "currency": "מַטְבֵּעַ",
    "expire_at": "תאריך תפוגה",
    "discount_code": "קוד הנחה",
    "discount_percent": "הנחה",
    "discount_limit": "מגבלת הנחה",
    "max_count": "ספירה מקסימלית",
    "used_count": "בשימוש",
    "start_date": "תאריך התחלה",
    "end_date": "תאריך סיום",
    "total_discount_amount": "סך הנחות",
    "initial_charge": "טעינה ראשונית",
    "total_count": "ספירה כוללת",
    "amount_paid": "סכום ששולם",
    "name": "שֵׁם",
    "published": "יצא לאור",
    "visits": "ביקורים",
    "color": "צֶבַע",
    "landing_page": "דף נחיתה",
    "enable": "לְאַפשֵׁר",
    "fix_commission": "עמלה קבועה",
    "percent_commission": "אחוז עמלה",
    "payment_at": "תאריך תשלום",
    "issued_at": "תאריך הוצאה",
    "payment": "תַשְׁלוּם",
    "website": "אתר אינטרנט",
    "email": "אימייל",
    "user": "מִשׁתַמֵשׁ",
    "code": "קוד",
    "schedule_at": "תאריך לוח זמנים",
    "sender": "שׁוֹלֵחַ",
    "in_que": "בתור",
    "sent": "נשלח",
    "shop": "לִקְנוֹת",
    "quantity": "כַּמוּת",
    "amount": "כמות",
    "jobs": "משרות נחשבות",
    "success": "ספירת הצלחה",
    "fail": "ספירת נכשלים",
    "distance": "מֶרְחָק",
    "duration": "מֶשֶׁך",
    "reset_at": "אפס את התאריך",
    "delivery_person": "אדם",
    "delivery_service": "שֵׁרוּת",
    "date": "תַאֲרִיך",
    "order": "להזמין",
    "order_id": "מספר הזמנה",
    "status": "סטָטוּס",
    "price": "מחיר",
    "count": "לספור",
    "final_price": "מחיר אחרון",
    "charge": "לחייב",
    "mention": "אִזְכּוּר",
    "officer": "קָצִין",
    "registered": "רשום",
    "purchased": "נרכש",
    "sex": "מִין"
  },
  "search_box": {
    "result": "תוצאות חיפוש",
    "tips": "חפש מוצרים וקטגוריות",
    "label": "לחפש ...",
    "category": "קטגוריה"
  },
  "lead_status": {
    "physical_fast_delivery": "משלוח מיידי",
    "physical_under_24h_delivery": "אספקה בתוך {lead} השעות הבאות",
    "physical_over_24h_delivery": "הכנה ושליחה מ-{days} הימים הבאים",
    "virtual_fast_prepare": "משלוח מיידי",
    "virtual_under_24h": "יתבצע במהלך {lead} השעות הבאות",
    "virtual_over_24h": "יתבצע החל מ-{days} הימים הבאים"
  },
  "return_request_state": {
    "pending": "ממתין ל",
    "accepted": "מְאוּשָׁר",
    "rejected": "נִדחֶה"
  },
  "return_order_reason": {
    "physical": {
      "U1": "אי התאמה של המוצר",
      "U2": "אין מוצר בחבילת המשלוח",
      "U3": "שבירה של חבילה או מוצר",
      "U4": "שיבוש חבילה או מספר סידורי",
      "U5": "חלק מהפריטים מהחבילה חסרים",
      "U6": "המוצר אינו מקורי",
      "U7": "המוצר אינו עומד במפרט"
    }
  },
  "image_uploader": {
    "label": "גרור ושחרר או <u>בחר קובץ</u>",
    "max_size": "גודל מקסימלי מותר: {size}"
  },
  "timespan": {
    "Morning": "8:00 - 12:00",
    "Evening": "12 בצהריים עד 6 בערב",
    "Night": "18:00-12:00",
    "Instant": "פוסט מיידי"
  },
  "week_day": {
    "Saturday": "יום שבת",
    "Sunday": "יוֹם רִאשׁוֹן",
    "Monday": "יוֹם שֵׁנִי",
    "Tuesday": "יוֹם שְׁלִישִׁי",
    "Wednesday": "יום רביעי",
    "Thursday": "יוֹם חֲמִישִׁי",
    "Friday": "יוֹם שִׁישִׁי"
  },
  "payment_form": {
    "title": "בחר שיטת תשלום",
    "gift_cards_input": "כרטיסי ברכה",
    "gift_cards_input_empty": "לא נמצאו כרטיסי מתנה..",
    "more": "אַחֵר",
    "pay_amount_by_gift_cards": "תשלום בכרטיס חיוב",
    "select_payment_method": "בחר את שיטת התשלום שלך מהאפשרויות הבאות.",
    "payment_amount_remained": "סכום התשלום שנותר",
    "payment_amount": "סכום ששולם",
    "all_paid_by_gift_cards": "מזל טוב, אינך צריך לשלם עבור הזמנה זו. לחץ על מקש שלם עם כרטיס מתנה.",
    "pay_by_gift_cards_action": "שלם את ההזמנה באמצעות כרטיס חיוב",
    "order_free_payment": "מזל טוב, ההזמנה שלך בחינם!",
    "order_free_payment_action": "הזמינו בחינם עכשיו",
    "qr": {
      "address": "כתובת לתשלום",
      "amount": "כמות"
    }
  },
  "discount_input": {
    "limit": "{percent}% הנחה עד {limit} {currency}",
    "action": "הוסף קוד הנחה",
    "code_input": "קוד הנחה",
    "notifications": {
      "add_success": "מזל טוב, קוד הנחה תקף."
    }
  },
  "gift_card": {
    "inactive": "הכרטיס מושבת",
    "expire": "תְפוּגָה",
    "transfer": "לְהַעֲבִיר",
    "send_to_friend": "לשלוח לחבר"
  },
  "count_down": {
    "days": "יְוֹם",
    "hours": "שָׁעָה",
    "minutes": "דקות",
    "seconds": "שניות"
  },
  "gift_status": {
    "Unpaid": "ממתין לקבלה",
    "Paid": "שולם",
    "Rejected": "נִדחֶה",
    "Canceled": "מבוטל"
  },
  "gift_program_status": {
    "Airdrop": "מערכת תשלום",
    "Advertising": "פִּרסוּם",
    "PersonalGift": "מתנה אישית",
    "ShopGift": "חנות מתנות"
  },
  "currency_selector": {
    "label": "מַטְבֵּעַ"
  },
  "need_login": {
    "title": "התחברות",
    "login_sms": "כניסה ל-SMS",
    "login_google": "התחבר עם גוגל",
    "login_facebook": "התחבר עם פייסבוק",
    "login_account": "התחברות על ידי Seldone",
    "register": "משתמש חדש? הירשם עכשיו.",
    "mobile_input": "הכנס לנייד שלך",
    "verification_code": "קוד אימות",
    "msg_title": "היי,",
    "msg_body": "אנא התחבר. זה לוקח רק כמה שניות.",
    "login_apple": "התחבר עם אפל"
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "חנות זהב 5 שנים"
    },
    "GOLDEN_2YEAR": {
      "name": "חנות זהב 4 שנים"
    },
    "GOLDEN_3YEAR": {
      "name": "חנות זהב לשלוש שנים"
    },
    "GOLDEN_4YEAR": {
      "name": "חנות זהב לשנתיים"
    },
    "GOLDEN_5YEAR": {
      "name": "חנות זהב לשנה"
    },
    "TOKEN_OWNER_1M": {
      "name": "משקיע זהב"
    },
    "TOKEN_OWNER_10M": {
      "name": "משקיע יהלומים"
    },
    "TOKEN_OWNER_100M": {
      "name": "רובי משקיע"
    },
    "COMMUNITY_LOYAL": {
      "name": "חבר בקהילה המעולה של רשתות תקשורת"
    },
    "GOLD_SUPPLIER": {
      "name": "מספק זהב"
    },
    "GOLD_SELLER": {
      "name": "סוחר זהב"
    },
    "CONTENT_SUPERMAN": {
      "name": "מפיק תוכן מוביל"
    },
    "NINJA": {
      "name": "נינג'ה"
    },
    "STAR": {
      "name": "כוכב"
    },
    "GUARDIAN": {
      "name": "שירות לקוחות מעולה"
    },
    "KING": {
      "name": "מלך השוק"
    }
  },
  "cookie": {
    "title": "אתר זה משתמש בעוגיות",
    "message": "אתר זה משתמש בקובצי Cookie כדי לשפר את חווית המשתמש. על ידי שימוש באתר האינטרנט שלנו אתה מסכים לכל קובצי ה-Cookie בהתאם למדיניות העוגיות שלנו.",
    "preferences_action": "נהל העדפות",
    "agree_action": "אני מסכים"
  },
  "basket_item_message": {
    "title": "מידע נדרש עבור פריט זה",
    "save_actions": "שמור הודעה",
    "notifications": {
      "success": "נתוני הקלט שלך נשמרו."
    }
  },
  "faq": {
    "faq": "שאלות נפוצות",
    "title": "שאלות ותשובות",
    "sub_title": "מה שביקשת מאיתנו לעשות.",
    "message": "חפש את התשובה לשאלתך בין התשובות למטה. שאל אותנו אם שאלות נותרו ללא מענה.",
    "add_question_action": "שאל שאלה חדשה",
    "read_more": "קרא עוד ..",
    "load_more": "שאלות נוספות ..",
    "main_page": "שאלות נפוצות עמוד ראשי",
    "add_new": "שלח שאלה חדשה",
    "login_alert": "היכנס כדי לשאול שאלה.",
    "question_input": "שְׁאֵלָה",
    "question_input_placeholder": "תשאל את השאלה שלך.",
    "notifications": {
      "success_add": "שאלתך נשלחה בהצלחה."
    }
  },
  "rating_labels": [
    "רע מאוד",
    "רַע",
    "נוֹרמָלִי",
    "טוֹב",
    "מְעוּלֶה"
  ],
  "map_view": {
    "address_detail": "פרטי כתובת",
    "change": "שינוי",
    "select": "בחר",
    "not_found_address": "לא נמצא ערך",
    "enter_address_hint": "הזן כתובת יעד",
    "enter_your_address": "הזן את כתובתך.",
    "postal_code": "מיקוד",
    "phone_input": "טלפון {type}",
    "building_number": "מספר בניין",
    "building_unit": "יחידה",
    "full_name_input": "שם מלא {type}",
    "save_detail_action": "שמור פרטים",
    "more_detail_input": "תיאור נוסף",
    "add_address_to_list": "הוסף כתובת לרשימה",
    "address_title_input": "תווית כתובת (דרוש)",
    "notifications": {
      "save_in_list": "כתובת זו נשמרה ברשימה שלך עם כל הפרטים שלה.",
      "edit_success": "ערכי כתובת חדשים שנשמרו ב-{title}."
    },
    "delete_address_dialog": {
      "title": "מחק כתובת",
      "message": "האם אתה בטוח שברצונך למחוק כתובת זו?",
      "action": "הסר כתובת"
    }
  },
  "comment_manager": {
    "can_not_edit": "לא ניתן לערוך את התגובה הזו!",
    "comment_input_empty": "טקסט ההודעה ריק!",
    "article_not_saved": "שמור את המאמר!"
  },
  "wheel_fortune": {
    "title": "שחק ונצח",
    "message": "עלות כל משחק היא 10 צ'יפים. יש לך כרגע שבב {chips}. קבל יותר שבב על ידי רכישה מהחנות.",
    "win_message": "מזל טוב, זכית!",
    "lost_message": "סליחה, הפסדתם את המשחק.",
    "try_again": "אתה יכול לנסות שוב"
  },
  "json": {
    "add": "הוסף נתוני מבנה",
    "add_message": "צור נתוני מבנה חדשים",
    "structures": "מבנים",
    "book": {
      "title": "סֵפֶר",
      "desc": "פעולות ספר המאפשרות למשתמשים לקנות את הספר שהם מוצאים ישירות מתוצאות החיפוש."
    },
    "occupation": {
      "title": "שכר משוער",
      "desc": "מידע על הערכת שכר, כגון טווחי שכר וממוצעי שכר מבוססי אזור עבור סוגי משרות, המוצג בחוויית חיפוש העבודה בגוגל."
    },
    "course": {
      "title": "קוּרס",
      "desc": "קורסים חינוכיים המופיעים ברשימה ספציפית לספק. הקורסים יכולים לכלול את כותרת הקורס, ספק ותיאור קצר."
    },
    "howto": {
      "title": "איך ל",
      "desc": "A How-to מנחה את המשתמשים בקבוצה של שלבים להשלמת משימה בהצלחה, הכוללת וידאו, תמונות וטקסט."
    },
    "recipe": {
      "title": "מתכון",
      "desc": "מתכונים המוצגים כתוצאה עשירה אינדיבידואלית או כחלק מקרוסלת מארח."
    }
  },
  "support": {
    "Financial": "כַּספִּי",
    "Technical": "טֶכנִי",
    "Advisor": "יועץ"
  },
  "condition": {
    "new": "חָדָשׁ",
    "refurbished": "משופץ",
    "used": "בשימוש",
    "used_fair": "משומש הוגן",
    "used_good": "משומש טוב",
    "used_like_new": "משומש - כמו חדש"
  },
  "variant_filter": {
    "title": "מסנן וריאציות מוצר",
    "only_available": "במלאי"
  },
  "service": {
    "task": {
      "title": "משימות",
      "message": "רשימת המשימות שבוצעו בשירות זה."
    },
    "appointment": {
      "title": "קביעת פגישה",
      "message": "בחר את שעות השבוע מהזמנים הבאים על סמך היום והשעה המתאימים לך."
    },
    "booking": {
      "title": "הזמנה",
      "message": "ציין את פרק הזמן של הימים שבהם ברצונך לבצע הזמנה בלוח השנה למטה."
    },
    "subscription": {
      "title": "מִנוּי"
    },
    "charge": {
      "title": "לחייב"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "תמחור קבוע",
      "message": "בתמחור מסוג זה, מחיר המוצר הינו סכום קבוע ואין צורך של הקונה לבקש חישוב מחיר."
    },
    "ESTIMATION": {
      "title": "אומדן תמחור",
      "message": "מחיר המוצרים והשירותים יחושב במידה מסוימת על ידי המוכר בעת ביצוע ההזמנה, ניתן לשנות או להוסיף חשבוניות תשלום במהלך השירות."
    },
    "AGREEMENT": {
      "title": "תמחור הסכם",
      "message": "המחיר הסופי של המוצרים או השירותים לא ישונה על ידי המוכר לאחר ביצוע ההזמנה."
    },
    "BID": {
      "title": "הצעה / מכירה פומבית",
      "message": "המוצר יימכר במחיר ההצעה הגבוה ביותר על ידי קונים פוטנציאליים."
    }
  },
  "map": {
    "title": "יעד לקבלת מוצרים",
    "confirm": "הזן מיקום",
    "address": "יַעַד",
    "receptor": "מַקְלֵט"
  },
  "ShopBots": {
    "telegram": "מִברָק"
  },
  "article_tags": {
    "title": "תגיות תוכן",
    "tags_input": "תגים",
    "tags_input_message": "רשימת תגים של מאמר זה",
    "notification": {
      "add_success": "נוספו תגים"
    }
  },
  "difficulties": {
    "very_complicated": "מאוד מסובך",
    "hard": "קָשֶׁה",
    "intermediate": "ביניים",
    "easy": "קַל"
  }
};