export default {
  "currency_default": "USD",
  "language_default": "lt",
  "selldone": "Parduota",
  "store": "parduotuvė",
  "not_exist": "Neegzistuoja",
  "error": "Klaida",
  "active": "Aktyvus",
  "inactive": "neaktyvus",
  "required_value": "Reikalingos reikšmės",
  "original_warranty": "Originalios prekės garantija",
  "return_warranty_days": "{days} grąžinimo garantijos diena (-os)",
  "no_return_warranty": "Grąžinimo nėra",
  "reed_agree_terms": "Perskaičiau naudojimo sąlygas bei privatumo politiką ir su jomis sutinku.",
  "commons": {
    "Currency": "Valiuta",
    "COD": "COD",
    "State": "valstybė",
    "Price": "kaina",
    "order_price": "Užsakymo suma",
    "VAT": "VAT",
    "Discount": "Nuolaida",
    "In_Stock": "Sandelyje",
    "Variants": "Variantai",
    "No_variants": "Jokio varianto",
    "all": "VISI",
    "today": "Šiandien",
    "yesterday": "vakar",
    "license": "Licencija",
    "home": "Namai",
    "support": "Palaikymas",
    "messages": "Žinutės",
    "no_message": "Nėra žinutės",
    "empty": "Tuščia",
    "phone": "Telefonas",
    "address": "adresu",
    "name": "vardas",
    "password": "Slaptažodis",
    "email": "El. paštas",
    "mobile": "Mobilusis",
    "login": "Prisijungti",
    "register": "Registruotis",
    "select_account": "Pasirinkite paskyrą",
    "online": "Prisijungęs",
    "offline": "Neprisijungus",
    "finish": "Baigti",
    "finished": "Baigta",
    "preview": "Peržiūra",
    "free": "Laisvas",
    "free_completely": "Visiškai nemokama prenumerata",
    "fee": "Rinkliava",
    "month": "Mėnuo",
    "months": "Mėnesių",
    "faq": "Dažnai užduodami klausimai",
    "question": "Klausimas",
    "answer": "Atsakymas",
    "create_date": "Sukurti datą",
    "update_date": "Atnaujinti datą",
    "start_date": "Pradžios data",
    "end_date": "Pabaigos data",
    "social": "Socialinis",
    "total": "Iš viso",
    "orders": "Užsakymai",
    "sessions": "Seansai",
    "product_views": "Produktų peržiūros",
    "add_to_carts": "Pridėti į krepšelius",
    "checkouts": "Patikra",
    "payments": "Mokėjimas",
    "organic_search": "Organinė paieška",
    "other": "Kita",
    "landing_page": "Nukreipimo puslapis",
    "discount_code": "Nuolaidos kodas",
    "total_sell": "Bendras pardavimas",
    "details": "Detalės",
    "currency": "Valiuta",
    "amount": "Suma",
    "published": "Paskelbta",
    "draft": "Juodraštis",
    "save_changes": "Išsaugoti pakeitimus",
    "source": "Šaltinis",
    "medium": "Vidutinis",
    "url": "URL",
    "revenue": "Pajamos",
    "performance": "Spektaklis",
    "term": "Terminas",
    "content": "Turinys",
    "session": "Sesija",
    "product": "Produktas",
    "add": "Papildyti",
    "checkout": "Patikra",
    "payment": "Mokėjimas",
    "more_options": "Daugiau pasirinkimų",
    "full_name": "Pilnas vardas",
    "tel": "Tel",
    "about_me": "Apie mane",
    "request_checking": "Prašyti patikrinti",
    "passport": "Pasas",
    "birthday": "Gimtadienis",
    "country": "Šalis",
    "city": "Miestas",
    "gender": "Lytis",
    "offer": "Pasiūlyti",
    "website": "Interneto svetainė",
    "apply_for_all_products": "∞ Taikyti visiems produktams",
    "fix_commission": "Fiksuotas komisinis",
    "percent_commission": "Procentiniai komisiniai",
    "fixed_discount": "Fiksuota nuolaida",
    "discount_percentage": "Procentinė nuolaida",
    "discount_limit": "Nuolaidų limitas",
    "no_code": "Nėra kodo",
    "max_count": "Maksimalus skaičius",
    "count_unit": "Daiktai",
    "used": "Naudota",
    "daily": "Kasdien",
    "monthly": "Kas mėnesį",
    "yearly": "Kasmet",
    "state": "Būsena",
    "disable": "Išjungti",
    "enable": "Įgalinti",
    "activation_code": "Aktyvavimo kodas",
    "quantity": "Kiekis",
    "no_club": "Nėra klubo",
    "per_order": "Pagal užsakymą",
    "count": "Suskaičiuoti",
    "seconds": "sekundės",
    "auto": "Automatinis",
    "title": "Pavadinimas",
    "message": "Pranešimas",
    "width": "Plotis",
    "length": "Ilgis",
    "height": "Aukštis",
    "label": "Etiketė",
    "click": "Spustelėkite",
    "bank": "bankas",
    "default": "Numatytas",
    "role": "Vaidmuo",
    "user": "Vartotojas",
    "users": "Vartotojai",
    "code": "Kodas",
    "total_payment": "Visas mokėjimas",
    "balance": "Balansas",
    "chance": "Tikimybė",
    "free_for_new_users": "Nemokama naujiems vartotojams",
    "prize_amount": "Prizo suma",
    "win": "Laimėk",
    "gift_card": "Dovanų kortelė",
    "discount": "Nuolaida",
    "config": "konfig",
    "prize": "Prizas",
    "Prizes": "Prizai",
    "result": "Rezultatas",
    "price": "kaina",
    "lottery": "Loterija",
    "coupon": "Kuponas",
    "customer_club": "Klientų klubas",
    "shipping": "Siuntimas",
    "sum": "Suma",
    "not_paid": "Nesumoketas",
    "category": "Kategorija",
    "done": "padaryta",
    "email_from": "Iš",
    "subject": "Tema",
    "schedule": "Tvarkaraštis",
    "files_list": "Failų sąrašas",
    "file_max_size": "Maksimalus failo dydis",
    "value": "Vertė",
    "help": "Pagalba",
    "shipping_tax": "Siuntimo mokestis",
    "net_price": "Grynoji kaina",
    "tax": "Mokesčiai",
    "tax_included": "Į kainą įskaičiuota",
    "limit": "Riba",
    "min_purchase": "Minimalus pirkimas",
    "eligible_for": "Tinkamas",
    "only_for_first_buy": "Tik pirmam pirkimui",
    "one_time_use": "Galima naudoti vieną kartą",
    "period_of_qualify": "Laikotarpio naudojimo limitas",
    "no_constraint": "Nėra limito",
    "timespan": "Laiko tarpas",
    "days": "Diena (-os)",
    "weight": "Svoris",
    "distance": "Atstumas",
    "last_status": "Paskutinė būsena",
    "issued_at": "Išleistas",
    "order": "Įsakymas",
    "order_detail": "Užsakymo detalės",
    "percent": "proc",
    "applied_count": "Taikomas skaičius",
    "campaign": "Kampanija",
    "os": "Operacinė sistema",
    "browser": "Naršyklė",
    "device": "Įrenginys",
    "device_ip": "Įrenginio IP adresas",
    "location": "Vieta",
    "user_agent": "Vartotojo atstovas",
    "affiliate": "Filialas",
    "timeline": "Laiko juosta",
    "add_note": "Pridėti pastabą",
    "record": "Įrašas",
    "unlimited": "Neribota",
    "show_coupons": "Rodyti kuponus",
    "hide_coupons": "Slėpti kuponus",
    "service_area": "Aptarnavimo sritis",
    "apps": "Programėlės",
    "plugins": "Papildiniai",
    "bots": "Botai",
    "categories": "Kategorijos",
    "products": "Produktai",
    "business": "Verslas",
    "personal": "Asmeninis",
    "size": "Dydis",
    "holiday": "Šventė",
    "sod": "Mokėti pristatymo metu",
    "cod": "Mokėti pristatymo metu",
    "free_shipping": "Nemokamas pristatymas",
    "hours": "Valandos",
    "send_date": "Išsiuntimo data",
    "deliver_date": "Pristatymo data",
    "return_date": "Grįžimo data",
    "pending": "Kol",
    "delivered": "Pristatyta",
    "returned": "Sugrįžo",
    "canceled": "Atšauktas",
    "shipping_cost": "Siuntimo kaina",
    "action": "Veiksmas",
    "cancel_date": "Atšaukti datą",
    "deliver_in_process": "Užsakymas išsiųstas..",
    "kind": "Tipas",
    "detail": "Detalės",
    "map": "Žemėlapis",
    "actions": "Veiksmai",
    "navigation": "Navigacija",
    "navigation_app": "Taikymas",
    "payment_date": "Mokėjimo diena",
    "duration": "Trukmė",
    "bill": "Bill",
    "delivery_persons": "Kurjeriai",
    "delivery_services": "Pristatymo paslaugos",
    "live_view": "Tiesioginis vaizdas",
    "cart": "Krepšelis",
    "priority": "Pirmenybė",
    "sufficient_credit": "Pakankamas kreditas",
    "max_package_size": "Maksimalus pakuotės dydis",
    "delay": "Delsimas",
    "credit": "Kreditas",
    "livemode": "Tiesiogiai",
    "paused": "Pristabdyta",
    "debug": "Derinimas",
    "token": "Žetonas",
    "status": "Būsena",
    "courier": "Kurjeris",
    "track": "Trasa",
    "track_order": "Užsakymo sekimas",
    "cost": "Kaina",
    "receipt": "Kvitas",
    "origin": "Kilmė",
    "destination": "Kelionės tikslas",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "Nepakanka atsargų!",
    "sub_total": "Tarpinė suma",
    "customer": "Klientas",
    "delivery": "Pristatymas",
    "online_orders": "Užsakymai internetu",
    "pos_orders": "POS užsakymai",
    "chips": "Traškučiai",
    "subscribed": "Prenumeruoti",
    "unsubscribed": "Atsisakė prenumeratos",
    "last_login": "Paskutinis prisijungimas",
    "join_at": "Įstojimo data",
    "club": "Klubas",
    "buyer": "Pirkėjas",
    "seller": "Pardavėjas",
    "or": "Arba",
    "type": "Tipas",
    "condition": "Būklė",
    "brand": "Prekės ženklas",
    "attempt": "Bandymas",
    "error": "Klaida",
    "success": "Sėkmė",
    "fail": "Nepavyko",
    "inventory": "Inventorius",
    "link": "Nuoroda",
    "visits": "Apsilankymai",
    "transactions": "Sandoriai",
    "vat": "VAT",
    "pos_vat": "POS PVM",
    "sort_by": "Rūšiuoti pagal..",
    "from": "Iš",
    "from_lead_time": "Per kitas {hours} valandas",
    "no_credit_card_info": "Nėra kortelės informacijos!",
    "active": "Aktyvus",
    "not_active": "Neaktyvuota!",
    "referrals": "Rekomendacijos",
    "dashboard": "Prietaisų skydelis",
    "more": "Daugiau",
    "inactive": "neaktyvus",
    "developer": "Programuotojas",
    "setting": "Nustatymas",
    "membership_conditions": "Narystės sąlygos",
    "customers": "Klientai",
    "created_at": "Sukūrimo data",
    "updated_at": "Paskutiniai pakeitimai",
    "register_at": "Registracijos data",
    "old": "Senas",
    "new": "Nauja",
    "start": "Pradėti",
    "end": "Pabaiga",
    "pos": "POS",
    "out_of_stock": "Išparduota",
    "fake": "Netikras",
    "low_inventory_warning": "Dėmesio, mažai atsargų!",
    "webhook": "Webhook",
    "notification": "Pranešimas",
    "sms": "SMS",
    "online_payment_link": "Mokėjimo internetu nuoroda",
    "waiting_load_data": "Laukiama duomenų įkėlimo..",
    "views": "Peržiūrėjo",
    "sales": "Pardavimai",
    "total_views": "Bendras peržiūrų skaičius",
    "total_sales": "Bendras pardavimas",
    "from_previous_n_days": "Nuo pastarųjų {days} dienų",
    "drop_shipping": "Dropshippingas",
    "commission": "Komisija",
    "shipping_area": "Laivybos sritis",
    "main_seller": "Pagrindinis pardavėjas",
    "domain": "Domenas",
    "contact": "Kontaktinė informacija",
    "wallet": "Piniginė",
    "reseller": "Perpardavėjas",
    "tracking_code": "Sekimo kodas",
    "tracking_url": "Stebėjimo URL",
    "fulfillments": "Išsipildymai",
    "reject": "Atmesti",
    "reserved": "Rezervuota",
    "score": "Rezultatas",
    "customer_price": "Kliento kaina",
    "options": "Galimybės",
    "show_details": "Parodyk detales",
    "no_data": "Nėra duomenų..",
    "waiting": "Laukiama...",
    "waiting_connecting_payment": "Laukiama mokėjimo paslaugos...",
    "creating_secure_payment": "Sukurti saugų mokėjimą.",
    "officer": "Pareigūnas",
    "ticket": "Bilietas",
    "ticket_url": "Bilieto url",
    "closed_at": "Uždaryta val",
    "close_ticket": "Uždaryti bilietą",
    "reopen_ticket": "Iš naujo atidarykite bilietą",
    "require": "Reikalauti*",
    "search": "Paieška...",
    "language": "Kalba",
    "tasks": "Užduotys",
    "permissions": "Leidimai",
    "finish_date": "Pabaigos data",
    "complete_date": "Baigimo data",
    "settle_date": "Atsiskaitymo data",
    "cost_span": "Kainų diapazonas",
    "industry": "Industrija",
    "rating": "Įvertinimai",
    "rates": "Įvertinimas",
    "seen_at": "Pamatyta",
    "completed": "Užbaigta",
    "you": "Tu",
    "shop": "Parduotuvė",
    "store": "parduotuvė",
    "granted": "Suteikta",
    "deny": "Neigti",
    "request": "Prašymas",
    "expert": "Ekspertas",
    "response": "Atsakymas",
    "requests": "Prašymai",
    "experts": "Ekspertai",
    "responses": "Atsakymai",
    "negotiations": "Derybos",
    "all_chats": "Visi pokalbiai",
    "chats": "Pokalbiai",
    "tags": "Žymos",
    "description": "apibūdinimas",
    "rates_count": "Įvertinimų skaičius",
    "rate": "Įvertinimas",
    "comment": "komentuoti",
    "chat": "Pokalbis",
    "install": "Diegti",
    "edited": "Redaguota",
    "undo": "Anuliuoti",
    "redo": "Perdaryti",
    "male": "Patinas",
    "female": "Moteris",
    "calculator": "Skaičiuoklė",
    "catalog": "Katalogas",
    "max_height": "Maksimalus aukštis",
    "images_compare": "Vaizdų palyginimas",
    "canvas": "Drobė",
    "table_of_contents": "Turinys",
    "comments": "komentarai",
    "badge_codes": "Ženklelių kodas",
    "need_more": "Reikia daugiau?",
    "invite_glow_caption": "Gaukite 14,9 USD už kiekvieną draugą!",
    "register_free": "100% nemokama registracija",
    "gift": "Dovana",
    "google": "Google",
    "facebook": "Facebook",
    "instagram": "Instagramas",
    "instashop": "Instashop",
    "show": "Rodyti",
    "hide": "Slėpti",
    "waiting_review": "Laukiama peržiūros",
    "not_selected": "Nepasirinkta",
    "time": "Laikas",
    "final_price": "Galutinė kaina",
    "starting_price": "Pradinė kaina",
    "day": "Diena",
    "paid": "Mokama",
    "service_bill": "Sąskaitos faktūros apmokėjimas",
    "avocado": "Avokadas",
    "delivery_price": "Siuntimo kaina",
    "select_address": "Pasirinkite adresą",
    "image": "Vaizdas",
    "view": "Žiūrėti",
    "sell": "Išpardavimas",
    "hyper": "Hiper",
    "cart_list": "Krepšelis",
    "barcode_scanner": "Brūkšninių kodų skaitytuvas",
    "scan_qr_code": "Nuskaitykite QR kodą",
    "new_carts": "Nauji vežimėliai",
    "pays": "Mokėjimai",
    "annually": "Kasmet",
    "sells": "Pardavimai",
    "articles": "Straipsniai",
    "jobs": "Darbai",
    "job": "Darbas",
    "blog": "Dienoraštis",
    "deleted_at": "Ištrinta adresu",
    "capacity": "Talpa",
    "download_at": "Paskutinio atsisiuntimo data",
    "downloads": "Atsisiuntimai",
    "usage": "Naudojimas",
    "select_upload_file": "Pasirinkite arba numeskite failą",
    "download_link": "Parsisiuntimo nuoroda",
    "uploading": "Įkeliama...",
    "files": "Failai",
    "star": "Žvaigždė",
    "speed": "Greitis",
    "feedback": "Atsiliepimas",
    "new_messages": "Nauji pranešimai",
    "file": "Failas",
    "attachment": "Priedas",
    "gallery": "Galerija",
    "sync": "Sinchronizuoti",
    "diff_time": "Laiko skirtumas",
    "network": "Tinklas",
    "account": "sąskaita",
    "configuration": "Konfigūracija",
    "blockchain": "Blockchain",
    "blog_link": "Tinklaraščio nuoroda",
    "community": "bendruomenė",
    "critical_zone": "Kritinė zona",
    "statistics": "Statistika",
    "access": "Prieiga",
    "seo": "SEO",
    "followers": "Sekėjai",
    "followings": "Stebėjimai",
    "private": "Peržiūra",
    "soon": "Greitai",
    "features": "funkcijos",
    "bot": "Botas",
    "sample": "Pavyzdys",
    "how_it_work": "Kaip tai veikia?",
    "page": "Puslapis",
    "congratulations": "Sveikinu",
    "recommend": "Rekomenduoti",
    "recommended": "Rekomenduojamas",
    "recoms": "Rekomendacijos",
    "likes": "Patinka",
    "clicks": "Paspaudimai",
    "platform": "Platforma",
    "cms": "CMS",
    "cash": "Grynieji pinigai",
    "dir_payment": "banko pervedimas",
    "auto_complete": "Automatinis užbaigimas",
    "compare": "Palyginti",
    "infinite": "Begalinis",
    "tips": "Patarimai",
    "technical": "Techninė",
    "finance": "Finansai",
    "your_phone_input": "Įveskite telefono numerį",
    "income": "Pajamos",
    "change": "Keisti",
    "new_users": "Nauji vartotojai",
    "success_orders": "Sėkmingi užsakymai",
    "direct": "Tiesioginis",
    "last_activity": "Paskutinė veikla",
    "landing": "Nusileidimas",
    "now": "Dabar",
    "accept_agreement": "Aš perskaičiau ir sutinku su sąlygomis.",
    "report": "Pranešimas",
    "tablet": "Tablėtė",
    "pc": "PC",
    "acquisition_channel": "Įsigijimo kanalas",
    "to": "Į",
    "info": "Informacija",
    "general": "Generolas",
    "upload": "Įkelti",
    "general_config": "Bendroji konfigūracija",
    "limits_config": "Apribojimai",
    "design_config": "Dizainas ir stilius",
    "duration_config": "Trukmės riba",
    "constraints_config": "Tinkamumo ribos",
    "clubs_config": "Galima įsigyti klubuose",
    "additional_config": "Papildomos konfigūracijos",
    "import": "Importuoti",
    "ribbon": "Juostelė",
    "countries": "Šalys",
    "edit": "Redaguoti",
    "delete": "Ištrinti",
    "analytics": "Analizė",
    "rules": "Taisyklės",
    "unset": "Nenustatyta",
    "carts": "Vežimėliai",
    "optional": "Neprivaloma",
    "design": "Dizainas",
    "filter": "Filtras",
    "send": "Siųsti",
    "approved": "Patvirtinta",
    "unit": "Vienetas",
    "profile": "profilis",
    "shipping_rates": "Siuntimo įkainiai",
    "package": "Paketas",
    "overview": "Apžvalga",
    "live": "Tiesiogiai",
    "never": "Niekada",
    "always": "Visada",
    "mandatory": "Privaloma",
    "expire_at": "Galiojimo pabaigos data",
    "position": "Padėtis",
    "channel": "Kanalas",
    "age": "Amžius",
    "charge": "Apmokestinti",
    "giftcard": "Dovanų kortelė",
    "acquisition": "Įsigijimas",
    "conversion": "Konversija",
    "total_payments": "Iš viso mokėjimų",
    "community_ask": "Klauskite bendruomenėje",
    "children": "Vaikai",
    "export": "Eksportuoti",
    "list": "Sąrašas",
    "hierarchy": "Hierarchija",
    "images": "Vaizdai",
    "demo": "Demo",
    "author": "Autorius",
    "designer": "Dizaineris",
    "max": "Maksimalus",
    "accepted": "Priimta",
    "reply": "Atsakyti",
    "reviewed": "Apžvelgta",
    "restored": "Atkurta",
    "merchant": "Prekybininkas",
    "per_product": "Pagal gaminį",
    "journey": "Kelionė",
    "after": "Po to",
    "waiting_for_payment": "Užbaikite mokėjimą...",
    "hour": "Valanda",
    "minute": "Minutė",
    "premium": "Premija",
    "light": "Šviesa",
    "dark": "Tamsus",
    "guest": "Svečias",
    "shops": "Parduotuvės",
    "vendor": "Pardavėjas",
    "vendors": "Pardavėjai",
    "marketplace": "Turgavietė",
    "verify_date": "Patvirtinkite datą",
    "note": "Pastaba",
    "panel": "Skydas",
    "removed": "Pašalinta",
    "segments": "Segmentai",
    "personal_info": "Asmeninė informacija",
    "preferences": "Parinktys",
    "spec": "Spec",
    "reviews": "Atsiliepimai",
    "constraints": "Apribojimai",
    "flexible": "Lankstus",
    "usage_limit": "Naudojimo limitas",
    "temporary": "Laikinas",
    "original": "Originalus",
    "saved": "Išsaugota!",
    "sort": "Rūšiuoti",
    "documents": "Dokumentai",
    "document": "dokumentas",
    "please_wait": "Prašau palauk...",
    "pickup": "Paimti",
    "customize": "pritaikyti",
    "difficulty": "Sunkumas",
    "banned": "Uždrausta",
    "company": "Įmonė",
    "tax_shipping": "Siuntimo mokestis",
    "warranty": "Garantija",
    "return_policy": "Gražinimo politika",
    "guide": "Vadovas",
    "translate": "Išversti",
    "public": "Viešas",
    "deleted": "Ištrinta",
    "variant": "Variantas",
    "secure": "Saugus",
    "admin": "Admin",
    "tax_included_abstract": "įskaitant",
    "payment_not_settled": "Mokėjimas neapmokėtas!",
    "orders_list": "Užsakymų sąrašas",
    "subscription_plan": "Prenumeratos planas",
    "contents": "Turinys",
    "pricings": "Kainos",
    "static_page": "Statinis puslapis",
    "shop_button": "Parduotuvės mygtukas",
    "embed": "Įterpti",
    "over": "Baigėsi",
    "tax_vary_by_location": "skirtis. vieta",
    "product_type": "Produkto tipas",
    "tax_id": "Mokesčių ID",
    "business_name": "Verslo pavadinimas",
    "invoice": "Sąskaita faktūra",
    "included_in_the_product": "Įeina į gaminį",
    "included_in_the_product_description": "Produktą sudaro šie komponentai",
    "cross_sell": "Kryžminis pardavimas",
    "discount_off": "OFF",
    "extra_discount": "Papildoma nuolaida",
    "template": "Šablonas",
    "in_cart": "Krepšelyje",
    "pros_and_cons": "Už ir prieš",
    "related_products": "Susiję produktai",
    "related_categories": "Susijusios kategorijos",
    "badges": "Ženkliukai",
    "explore": "Naršyti",
    "updated": "Atnaujinta",
    "bank_name": "Banko pavadinimas",
    "bank_account_number": "Banko sąskaitos numeris",
    "bank_routing_number": "Banko maršruto numeris",
    "bank_branch_address": "Banko filialo adresas",
    "bank_account_name": "Visas paskyros savininko vardas ir pavardė",
    "valuation": "Vertinimas",
    "cluster": "Klasteris",
    "clusters": "Klasteriai",
    "subscriptions": "Prenumeratos",
    "spam": "Šlamštas",
    "video": "Vaizdo įrašas"
  },
  "dialogs": {
    "delete": {
      "title": "Ištrinti",
      "message": "Ar tikrai ištrinsite šį elementą?",
      "action": "Taip, Ištrinti dabar"
    }
  },
  "actions": {
    "add_to_cart": "Į krepšelį",
    "cancel": "Atšaukti",
    "update": "Atnaujinti",
    "add": "Papildyti",
    "delete": "Ištrinti",
    "new": "Nauja",
    "save_continue": "Išsaugoti ir tęsti",
    "save": "Sutaupyti",
    "save_changes": "Išsaugoti pakeitimus",
    "change": "Keisti",
    "continue": "Tęsti",
    "close": "Uždaryti",
    "finish": "Baigti",
    "poll": "Apklausa",
    "view": "Žiūrėti",
    "edit": "Redaguoti",
    "next": "Kitas",
    "previous": "Ankstesnis",
    "create": "Sukurti",
    "set": "rinkinys",
    "find": "Rasti",
    "accept": "Priimti",
    "reject": "Atmesti",
    "back": "Atgal",
    "pay": "Mokėti",
    "pay_now": "Sumokėk dabar",
    "print": "Spausdinti",
    "return": "Grįžti",
    "publish": "Paskelbti",
    "confirm": "Patvirtinti",
    "copy": "Kopijuoti",
    "submit": "Pateikti",
    "send": "Siųsti",
    "yes": "Taip",
    "no": "ne",
    "meh": "Hmm",
    "clear": "Aišku",
    "dismiss": "Atsisakyti",
    "search": "Paieška",
    "deselect_all": "Atzymeti visus pasirinkimus",
    "select_all": "Pasirinkti viską",
    "refresh": "Atnaujinti",
    "verify": "Patvirtinti",
    "play": "žaisti",
    "open": "Atviras",
    "calculate": "Apskaičiuoti",
    "quick_buy": "Greitas pirkimas",
    "click_here": "Paspauskite čia",
    "schedule": "Tvarkaraštis",
    "send_now": "Išsiusti dabar",
    "download": "parsisiųsti",
    "reset_default": "Iš naujo nustatyti numatytuosius",
    "reset": "Nustatyti iš naujo",
    "check": "Patikrinti",
    "cod_payment": "Mokėti pristatymo metu",
    "dir_payment": "Pinigų pervedimas",
    "online_payment": "Mokėjimas internetu",
    "checkout": "Patikra",
    "show_all": "Rodyti viską",
    "login": "Prisijungti",
    "logout": "Atsijungti",
    "more": "Daugiau...",
    "collapse": "Sutraukti",
    "apply_change": "Taikyti pakeitimus",
    "apply": "Taikyti",
    "add_giftcard": "Pridėti dovanų kortelę",
    "charge": "Apmokestinti",
    "send_invites": "Siųsti kvietimus",
    "past": "Praeitis",
    "restore": "Atkurti",
    "cut": "Iškirpti",
    "get_sms_code": "Gaukite autentifikavimo kodą",
    "register_no_mail": "Tęskite be el",
    "no_mail_register_message": "Neturite el. pašto adreso arba pamiršote slaptažodį?",
    "reset_by_mail": "Slaptažodžio atkūrimas el",
    "reset_by_sms": "Slaptažodžio atkūrimas SMS žinute",
    "cash_payment": "Apmokėjimas grynaisiais",
    "show_chart": "Rodyti diagramą",
    "open_app": "Atidarykite programą",
    "login_now": "Prisijunk dabar",
    "watch_video": "Žiūrėti video",
    "check_now": "Patikrink Dabar",
    "remove_image": "Pašalinti vaizdą",
    "view_website": "Atidaryti nuorodą",
    "explore": "Naršyti {name}",
    "go": "Eik",
    "read_more": "Skaityti daugiau",
    "start_now": "Pradėkite dabar – tai nemokama",
    "view_live": "Žiūrėti gyvai",
    "resend_code": "Atsiųskite kodą dar kartą",
    "invite": "Pakviesti",
    "add_more": "Pridėti daugiau",
    "install_now": "Įdiegti dabar",
    "uninstall": "Pašalinkite",
    "show_preview": "Rodyti peržiūrą",
    "hide_preview": "Slėpti peržiūrą",
    "download_now": "Parsisiųsti dabar",
    "auto_fill": "Automatinis pildymas",
    "track": "Trasa",
    "change_state": "Pakeisti būseną",
    "done": "padaryta",
    "reply": "Atsakyti",
    "watch_now": "Žiūrėk dabar",
    "unlock": "Atrakinti",
    "lock": "Užraktas",
    "create_clone": "Sukurti kloną",
    "regenerate": "Regeneruoti",
    "add_message": "Pridėti pranešimą",
    "continue_chat": "Tęsti pokalbį",
    "add_new_message": "Pridėti naują pranešimą",
    "change_setting": "Pakeiskite nustatymą",
    "delete_all": "Ištrinti viską",
    "transfer_fund": "Pervedimo fondas",
    "reverse_fund": "Atvirkštinis fondas",
    "settlement": "Atsiskaitymas",
    "refund": "Grąžinti pinigus",
    "partial_refund": "Dalinis grąžinimas",
    "change_payment_method": "Keisti mokėjimo būdą",
    "buy": "Pirkti",
    "view_all": "Peržiūrėti visus",
    "view_now": "Žiūrėti dabar",
    "paste": "Įklijuoti"
  },
  "instance_message_title": "Siųsti momentinę žinutę",
  "instance_message": "Sveiki, {name}, mano vardas yra {author} iš {company}.",
  "errors": {
    "419": "Ilgą laiką buvote neaktyvus, prašome <b>⟳ Saugumo sumetimais ATNAUJINTI PUSLAPĮ</b> .",
    "gateway_blockchain_sync_error": "Sistema nesinchronizuojama su blokų grandine. Nebus įmanoma sukurti naujos operacijos, kol nebus baigtas mūsų serverių sinchronizavimas. Mes sprendžiame problemą.",
    "gateway_network_error": "Mokėjimo šliuzo paslauga susidūrė su ryšio problema."
  },
  "receiver_info": {
    "map": {
      "title": "Pristatymo adresas",
      "confirm": "Nustatyti vietą",
      "address_type": "Kelionės tikslas",
      "receptor_type": "Imtuvas"
    },
    "receiver_address": "Pasirinkite pristatymo adresą",
    "address": "adresu",
    "postcode": "Pašto indeksas",
    "enter_value": "Užpildykite čia",
    "address_note": "Pastaba",
    "tel": "Kontaktinis numeris",
    "service_address": "Pasirinkite savo adresą"
  },
  "weight": {
    "g": "g",
    "oz": "oz",
    "lb": "lb",
    "kg": "kilogramas"
  },
  "mass_unit_name": {
    "g": "gramas",
    "oz": "Uncija",
    "lb": "Svaras",
    "kg": "kilogramas"
  },
  "length": {
    "cm": "cm",
    "in": "in",
    "ft": "ft",
    "mm": "mm",
    "m": "m",
    "yd": "yd"
  },
  "size_unit_name": {
    "cm": "centimetras",
    "in": "Col",
    "ft": "Pėda",
    "mm": "milimetras",
    "m": "metras",
    "yd": "Kiemas"
  },
  "distance": {
    "m": "metras",
    "km": "km"
  },
  "time": {
    "days": "Dienos",
    "hours": "Valandos",
    "minutes": "Minutės",
    "seconds": "sekundės"
  },
  "units": [
    "Vienetas",
    "daiktas",
    "kiekviena",
    "rinkinys",
    "gabalas",
    "kilogramas",
    "gramas",
    "miligramas",
    "metras",
    "milimetras",
    "kvadratinis metras",
    "kvadratinė pėda",
    "kubinis metras",
    "litras",
    "mililitro",
    "pėdos",
    "galonų",
    "colių",
    "uncijų",
    "svarų",
    "kvortų",
    "kiemai",
    "kambarys",
    "sekundžių",
    "minučių",
    "valandų",
    "dienų",
    "savaites",
    "mėnesių",
    "metų"
  ],
  "region_types": {
    "State": "valstybė",
    "Territory": "Teritorija",
    "Province": "Provincija"
  },
  "transaction_status": {
    "RequireAction": "Reikalingas veiksmas",
    "Processing": "Apdorojimas",
    "Canceled": "Atšauktas",
    "Succeeded": "Pavyko"
  },
  "placeholders": {
    "name": "Jone'as Coxas",
    "email": "jūsų-paštas{'@'}mail.com",
    "phone": "+1 000 0000",
    "language": "Pasirinkite kalbą..",
    "friend_email": "Jūsų draugo el. paštas...",
    "friend_name": "Pasirinkti Tavo draugo vardas",
    "select_date": "Pasirinkite datą..."
  },
  "notification": {
    "confirm": "Patvirtinti",
    "confirm_message": "Pakeitimai sėkmingai išsaugoti.",
    "error": "Klaida",
    "message": "Pranešimas",
    "caution": "Atsargiai",
    "warning": "Įspėjimas",
    "award": "Sveikinu",
    "error_message": "Deja, įvyko klaida.",
    "congratulation": "Sveikinu",
    "coming_soon": "Greitai",
    "on_fetching_data": "Informacijos gavimas..",
    "new_pwa_version": "Dabar prieinama nauja versija. Ar norite atnaujinti programą?",
    "over_license_limit": "Virš licencijos limito",
    "update_license": "Atnaujinkite savo licenciją",
    "required": "Reikalingas",
    "invalid_email": "Neteisingas el. pašto adresas",
    "invalid_domain": "Neteisingas domenas",
    "invalid_min_length": "Minimalus ilgis turi būti {length}",
    "invalid_min_array_length": "Pasirinkite bent {length} elementus",
    "invalid_max_chars": "Daugiausia simbolių: {maxCount}",
    "invalid_url": "neteisingas URL",
    "country_invalid": "Pasirinkite paskirties šalį!",
    "postal_code_invalid": "Nustatykite galiojantį pašto kodą!"
  },
  "colors": {
    "#D32F2F": "Raudona",
    "#C2185B": "Rožinis",
    "#7B1FA2": "Violetinė",
    "#512DA8": "Tamsiai violetinė",
    "#303F9F": "Indigo mėlyna",
    "#1976D2": "Mėlyna",
    "#0288D1": "Šviesiai mėlynas",
    "#0097A7": "Turkio mėlyna",
    "#00796B": "Žąsų žalia",
    "#388E3C": "Žalias",
    "#689F38": "Šviesiai žalia",
    "#AFB42B": "Limuzinas",
    "#FBC02D": "Geltona",
    "#FFA000": "Gintaras",
    "#F57C00": "Oranžinė",
    "#E64A19": "Blizganti oranžinė",
    "#5D4037": "Ruda",
    "#616161": "Pilka",
    "#455A64": "Pilka Mėlyna",
    "#FFD700": "Auksinis",
    "#C0C0C0": "sidabras",
    "#b76e79": "Auksinė rožė",
    "#383838": "Matinė juoda",
    "#FFFFFF": "Baltas",
    "#FFF": "Baltas",
    "#000000": "Juoda",
    "#000": "Juoda",
    "#7d263a": "Maroon",
    "#FD9F17": "Auksas",
    "#229DBF": "Aqua",
    "#6DC9E2": "Aqua Triblend",
    "#413B2D": "Armija",
    "#474747": "Asfaltas",
    "#E6195C": "Uoga",
    "#B2184C": "Berry Triblend",
    "#FC7F5F": "Degintas apelsinas",
    "#80011F": "kardinolas",
    "#382829": "Šokoladas",
    "#F06336": "Koralas",
    "#FAE7C9": "Kremas",
    "#6B2257": "Serbentas",
    "#222127": "Tamsiai pilka",
    "#0D5A74": "Giliai žalsvai mėlyna",
    "#00582F": "Evergreen",
    "#214C30": "Miškas",
    "#DC2867": "Fuksija",
    "#38561F": "Kelly",
    "#5C884D": "Lapas",
    "#558450": "Šviesus Aqua",
    "#96B5C9": "Šviesiai mėlynas",
    "#DCAFCE": "Alyva",
    "#D3E1A4": "Kalkės",
    "#9DE7C2": "Mėtų",
    "#F6EAD2": "Natūralus",
    "#1A1F35": "karinis jūrų laivynas",
    "#404624": "Alyvuogių",
    "#271020": "Slyva",
    "#A8355C": "Avietinė",
    "#D6BEA6": "Minkštas kremas",
    "#BEA994": "Tan",
    "#0DB2AE": "žalsvai mėlyna",
    "#A86EA9": "Violetinė",
    "#36454F": "Anglis",
    "#b3b0ab": "anglies pilka",
    "#463e3d": "Anglies viržiai",
    "#282d3c": "Navy Blazer"
  },
  "address_info": {
    "name": "vardas",
    "tel": "Telefonas",
    "email": "El. paštas",
    "country": "Šalis",
    "city": "Miestas",
    "state": "valstybė",
    "address": "adresu",
    "building_number": "Pastato numeris",
    "building_unit": "Vienetas",
    "postcode": "Pašto indeksas",
    "note": "Pastaba",
    "county": "Apygarda"
  },
  "product_types": {
    "physical": "Fizinis",
    "physical_description": "Fiziniai produktai, tokie kaip: mobilieji telefonai, knygos, elektroniniai komponentai.",
    "virtual": "Virtualus",
    "virtual_description": "Internetui patogūs produktai, tokie kaip: papildymo kortelė, viešbučio rezervavimas, žaidimų papildymas.",
    "file": "Failas",
    "file_description": "Visi leidžiami failai, pvz., internetinio kurso vaizdo įrašas, atsisiunčiami dokumentai.",
    "service": "Aptarnavimas",
    "service_description": "Tokios paslaugos kaip: remontas, transportavimas, mokymas.",
    "subscription": "Prenumerata",
    "subscription_description": "Prenumeratos ir sąskaitų faktūrų išrašymas už produktus, paslaugas ar turinį."
  },
  "license": {
    "free": "Laisvas",
    "startup": "Pradėti",
    "company": "Įmonė",
    "enterprise": "Įmonė"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "Vyrui",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW",
    "GHS": "GHS",
    "ZWD": "ZWD",
    "IQD": "IQD",
    "SYP": "SYP"
  },
  "variants": {
    "color": "Spalva",
    "volume": "Dydis",
    "count_in_pack": "Suskaičiuoti pakuotėje",
    "weight": "Svoris",
    "type": "Medžiaga",
    "style": "Stilius"
  },
  "delivery_state": {
    "check_queue": "Laukiama peržiūros",
    "order_confirm": "Užsakymo patvirtinimas",
    "preparing_order": "Rengia",
    "sent_order": "Pristačius",
    "to_customer": "Pristatyta"
  },
  "status": {
    "unpaid": "Neapmokėta",
    "paid": "Mokama",
    "canceled": "Atšauktas",
    "completed": "Įsikūrė",
    "reserved": "Rezervuota",
    "COD": "COD",
    "sold": "Parduota",
    "open": "Atviras",
    "cancel": "Atšauktas",
    "active": "Aktyvus",
    "inactive": "neaktyvus",
    "debug": "Derinimas",
    "live": "Tiesiogiai",
    "test": "Testas",
    "connected": "Prisijungta",
    "disconnected": "Atsijungta",
    "accept": "Priimti",
    "reject": "Atmesti",
    "pending": "Kol",
    "rejected": "Atstumtas",
    "accepted": "Priimta"
  },
  "dimensions": {
    "cm": "cm",
    "km": "km",
    "kg": "kilogramas"
  },
  "transportation_type": {
    "motorbike": "Motociklas",
    "motorbike_description": "Vidutinis svoris kelių kilometrų atstumu.",
    "cargo_small": "Smulkus krovinys",
    "cargo_small_description": "Kelių kilometrų lengvasis krovinys.",
    "cargo": "Krovinys",
    "cargo_description": "Vidutinis svoris kelių kilometrų atstumu.",
    "truck": "Sunkvežimis",
    "truck_description": "Birūs arba sunkūs kroviniai šalies viduje.",
    "fast_post": "Greitas paštas",
    "fast_post_description": "Greitas siuntimas per paštą.",
    "post": "Normalus postas",
    "post_description": "Įprastas paštas per paštą.",
    "airplane": "Oro paštas",
    "airplane_description": "Vidaus ir užsienio lengvi ir vidutiniai kroviniai.",
    "bicycle": "Išvalyti siuntimą",
    "bicycle_description": "Lengvieji kroviniai, keli šimtai jardų nuo nemotorinių transporto priemonių.",
    "global": "Pasaulinis transportas",
    "global_description": "Siuntimas į užsienį oru, jūra arba sausuma.",
    "pickup": "Paimti",
    "pickup_description": "Klientai prekes atsiima jūsų fizinėje parduotuvėje ar sandėlyje."
  },
  "article": {
    "login_to_see_error": "Prisijunkite norėdami pasiekti straipsnį",
    "create_new_action": "Sukurkite naują turinį",
    "menu_title": "Meniu",
    "menu": {
      "edit": "Redagavimo režimas",
      "view_mode": "Žiūrėjimo režimas",
      "delete": "Ištrinti straipsnį"
    },
    "schedule_action": "Ar norite suplanuoti paskelbimą?",
    "schedule_title": "Suplanuokite automatinį paskelbimą",
    "edit_mode": "Redaguoti",
    "public_view_mode": "Viešas vaizdas",
    "publish_at": "Paskelbti adresu",
    "published": "Paskelbta",
    "draft": "Juodraštis",
    "saving": "Išsaugomas",
    "save_and_publish_action": "Išsaugoti ir paskelbti",
    "save_draft_action": "Išsaugoti juodraštį",
    "private": "Privatus",
    "public": "Viešas",
    "category_input": "Kategorija",
    "category_input_message": "Pasirinkite straipsnio kategoriją",
    "parent_input": "Tėvų kategorija",
    "parent_input_message": "Pasirinkite tėvo turinį",
    "schedule_input": "Tvarkaraštis",
    "schedule_input_placeholder": "Jei norite, kad istorija būtų paskelbta konkrečiu laiku.",
    "schedule_view_action": "Žiūrėti paskelbimo tvarkaraštį",
    "author_title": "Parašyta",
    "read_time": "Mokslo laikas",
    "read_time_unit": "Minutės",
    "claps_action": "Plojimai",
    "claps": "Plojimai",
    "likes": "Kaip",
    "about_author": "Apie autorių",
    "updated_at": "Atnaujinta",
    "wrote_at": "Parašyta adresu",
    "now": "Dabar",
    "follow_action": "Sekite",
    "followed": "Sekė",
    "report_and_delete_action": "Praneškite ir ištrinkite šį straipsnį",
    "report_action": "Pranešti apie smurtą",
    "you_reported_this_article": "Šiame straipsnyje jau yra pranešimas apie piktnaudžiavimą.",
    "add_to_publication_action": "Pridėti prie leidinio",
    "author_socials": "Autorius socialiniuose tinkluose",
    "share": "Dalintis",
    "report_dialog": {
      "report_and_delete_title": "Praneškite apie piktnaudžiavimą ir pašalinkite turinį",
      "report_title": "Pranešti apie šį turinį kaip įžeidžiantį",
      "message": "Kokia šio turinio pateikimo priežastis? Pasirinkite vieną iš toliau pateiktų parinkčių.",
      "accept_and_delete_action": "Patvirtinkite ir ištrinkite turinį"
    },
    "schedule_dialog": {
      "title": "Turinio išleidimo tvarkaraštis",
      "publish_at": "Paskelbti adresu",
      "last_edit": "Paskutinis redagavimas",
      "view_action": "Žiūrėti straipsnį"
    },
    "notifications": {
      "update_success_title": "Pateikti informaciją",
      "update_success": "Straipsnis sėkmingai atnaujintas.",
      "update_error": "Įvesta informacija neteisinga.",
      "delete_error": "Negalite ištrinti šio straipsnio!",
      "report_and_delete_success_title": "Pranešti ir ištrinti",
      "report_and_delete_success_message": "Straipsnis sėkmingai ištrintas.",
      "report_success_title": "Pranešimo straipsnis",
      "report_success_message": "Jūsų pranešimas apie šį straipsnį paskelbtas."
    },
    "alert": {
      "delete_article": {
        "title": "Ištrinti straipsnį",
        "message": "Ar tikrai norite visam laikui ištrinti šį straipsnį?",
        "action": "Ištrinti"
      }
    },
    "edit_window": {
      "title": "Pasirinkite Vaizdo tekstas ir santrauka",
      "digest": "Santrauka"
    },
    "editor": {
      "title_placeholder": "Pavadinimas..",
      "body_placeholder": "Rašyk puikų turinį..",
      "accept_file_types_error": "Šis failo formatas yra nepriimtinas:",
      "max_file_size_error": "Šis failas per didelis:",
      "notifications": {
        "image_uploaded_success": "Vaizdas sėkmingai išsaugotas",
        "image_uploaded_failed": "Įkeliant vaizdą įvyko klaida."
      },
      "embed_placeholder": "Įveskite iframe kodą, Facebook, Youtube ar bet kurį kitą URL ir paspauskite enter.",
      "embed_caption_placeholder": "Įveskite pavadinimą (nebūtina)",
      "images_caption_placeholder": "Įveskite šio vaizdo pavadinimą.."
    }
  },
  "article_report": {
    "inappropriate": "Šio straipsnio turinys netinkamas.",
    "fake": "Tai netikra ir apgaulinga.",
    "spam": "Šis elementas buvo išsiųstas el. pašto šiukšlėmis ir nukopijuotas.",
    "scam": "Tai gali sukelti kenkėjiškų programų, virusų arba sistemos gedimą.",
    "hacked": "Atrodo, kad į šią svetainę buvo įsilaužta.",
    "offensive": "Kalbos turinys ir žodynas yra neetiški ir nepagarbūs.",
    "violent": "Manau, kad šiame turinyje yra pornografijos ir jis pažeidžia įstatymus.",
    "harassment": "Manau, kad tai yra rasizmas.",
    "hate": "Manau, kad tai yra smurto skatinimas.",
    "infringe": "Tai pažeidžia mano teises."
  },
  "comments": {
    "new_action": "Spustelėkite norėdami palikti komentarą..",
    "title": "komentarai",
    "body_placeholder": "Jūsų komentaras ar žinutė",
    "send_action": "Siųsti komentarą",
    "body_is_empty_error": "Komentaras tuščias!",
    "comments": "komentarai",
    "no_comments": "Rašyk pirmą komentarą...",
    "load_more_action": "Gaukite daugiau komentarų..",
    "cant_send_comment": "Negalite pridėti naujo įrašo.",
    "cant_remove_this_comment": "Negalite ištrinti šio komentaro!",
    "product_buyer": "Pirkėjas",
    "delete_alert": {
      "title": "Ištrinti komentarą",
      "message": "Ar norite ištrinti šį komentarą?",
      "action": "Ištrinti"
    },
    "notifications": {
      "delete_success": "Jūsų komentaras sėkmingai ištrintas."
    },
    "first_send": "Pirmas postas",
    "comment_at": "Įjungta",
    "edit_comment": "Redaguoti komentarą",
    "my_comments": "Mano komentarai"
  },
  "customer_club": {
    "bronze": "Bronza",
    "silver": "sidabras",
    "gold": "Auksinis",
    "platinum": "Platina",
    "diamond": "Deimantas"
  },
  "application_categories": {
    "tracking": "Vartotojo elgesio tikrinimas",
    "payment": "Mokėjimas",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "Transportas",
    "automation": "Automatika",
    "inventory": "Sandėliavimas",
    "accounting": "Apskaita",
    "marketing": "Rinkodara",
    "advertising": "Reklama",
    "staff": "Personalas",
    "incentive": "Paskatos",
    "shop": "Parduotuvė"
  },
  "social_network": {
    "instagram": "Instagramas",
    "telegram": "Telegrama",
    "googleplay": "Google Play",
    "appstore": "Programėlių parduotuvė",
    "twitter": "Twitter",
    "linkedin": "Linkedin",
    "medium": "Vidutinis",
    "selldone": "Parduota",
    "facebook": "Facebook",
    "pinterest": "Pinterest",
    "whatsapp": "WhatsApp",
    "skype": "Skype",
    "facebook_messenger": "Facebook Messenger"
  },
  "form_builder": {
    "add_item_action": "Pridėti naują elementą",
    "title_input": "Pavadinimas",
    "name_input": "Kintamojo pavadinimas",
    "value_input": "Vertybės",
    "value_input_message": "Vartotojo parinkčių sąrašas",
    "default": "Numatytoji reikšmė",
    "types": {
      "simple": "Paprasta",
      "selective": "Atrankinis",
      "switch": "Jungiklis",
      "file": "Failas",
      "number": "Skaičius"
    },
    "placeholder_input": "Vietos rezervuaras",
    "file_type_input": "Priimtini failų tipai",
    "file_type_message": "jpeg, png, zip,..."
  },
  "virtual_order_info_summery": {
    "title": "produkto pavadinimas",
    "reserved_at": "Registracijos data",
    "total_price": "Visas kiekis",
    "discount": "Nuolaida",
    "final_price": "Galutinė suma",
    "payment_status": "Mokėjimo būsena",
    "payment_status_waiting": "Laukiama apmokėjimo",
    "payment_status_paid": "Mokama",
    "buyer": "Pirkėjas"
  },
  "virtual_item_info": {
    "title": "Virtualus daiktas",
    "outputs": {
      "title": "Išvesties informacija",
      "sub_title": "Konfidenciali šio elemento informacija",
      "message": "Ši informacija bus parodyta vartotojui įsigijus prekę."
    },
    "inputs": {
      "title": "Reikalinga informacija",
      "sub_title": "Reikalinga pirkėjo informacija",
      "message": "Pirkėjas formoje turi įvesti prašomą informaciją"
    },
    "notifications": {
      "inputs_set_success": "Informacijos forma sėkmingai užregistruota.",
      "confirm_by_admin_success": "Užsakymo įvykdymas patvirtintas.",
      "confirm_by_buyer_success": "Užsakymo įvykdymas patvirtintas."
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "Šis užsakymas negali būti priimtas mokant COD.",
    "payment_returned": "Kliento sumokėtas mokėjimas grąžinamas.",
    "payment_fraud": "Mokėjimas buvo pripažintas sukčiavimu.",
    "location_out_of_service": "Kliento vieta neveikia.",
    "user_not_responding": "Klientas į skambučius neatsiliepė.",
    "shop_owner_fault": "Parduotuvės darbuotojai pildydami informaciją įvyko klaida.",
    "lack_of_inventory": "Išparduota.",
    "legal_restriction": "Neįmanoma pateikti užsakymo dėl teisinių apribojimų.",
    "pricing_fault": "Pardavėjo kainos klaida.",
    "system_fault": "Sistemos klaida."
  },
  "basket_order_info_summery": {
    "receiver": "Imtuvas",
    "phone": "Tel",
    "reserved_date": "Pirkimo data",
    "total_price": "Visas kiekis",
    "discount": "Nuolaida",
    "final_price": "Galutinė suma",
    "address": "Pristatymo adresas",
    "payment_status": "Mokėjimo būsena"
  },
  "basket_status": {
    "open": "Atviras",
    "reserved": "Rezervuota",
    "paid": "Mokama",
    "canceled": "Atšauktas",
    "cod": "Mokėti pristatymo metu",
    "receipt_added": "Pridėtas kvitas",
    "payment_processing": "Mokėjimo apdorojimas"
  },
  "basket_delivery_state": {
    "rejected": "Atstumtas",
    "reject_reason_not_found": "Priežastis nežinoma.",
    "step_1": "Apžvalga",
    "step_2": "Patvirtinimas",
    "step_3": "Paruošimas",
    "step_4": "Pristačius",
    "step_5": "Pristatyta"
  },
  "basket_return_request_view": {
    "title": "Prašymas grąžinti",
    "delivery_date": "Pristatymo data",
    "return_date": "Užklausos data",
    "items_count": "Skaičiuojasi grąžintos prekės",
    "items_count_unit": "prekė (-ės)",
    "reason": "Priežastis",
    "description": "apibūdinimas",
    "status": "Būsena",
    "download_image": "Parsisiųsti paveikslėlį",
    "download_film": "Atsisiųsti vaizdo įrašą",
    "download_voice": "Atsisiųsti balsą",
    "accept_by_admin_action": "Priimti prašymą",
    "reject_by_admin_action": "Atmesti prašymą",
    "message_for_admin": "Pagal sutartį, su kuria sutikote naudodamiesi „Selldone“, turite susisiekti su pirkėju ir informuoti jį apie jo užsakymo grąžinimo procesą. Tai turi būti padaryta, jei prašymas yra priimtas arba atmetamas ir gautas visiškas pirkėjo sutikimas.",
    "notifications": {
      "update_status_success": "Užklausos būsena atnaujinta."
    }
  },
  "basket_list": {
    "return_count": "Grąžinti: {count} numeris",
    "table": {
      "row": "Eilė",
      "image": "Vaizdas",
      "product_name": "Produktas",
      "variant": "Variantas",
      "warranty": "Garantijos",
      "count": "Suskaičiuoti",
      "price": "kaina"
    }
  },
  "return_request_list": {
    "count": "Šaltinio numeris",
    "return_warranty": "Pinigų gražinimo garantija",
    "return_warranty_unit": "Diena (-os)",
    "table": {
      "code": "Užsakymo kodas",
      "product": "Produktas",
      "delivery_at": "Gavimo data",
      "state": "Būsena",
      "reason": "Priežastis",
      "return_warranty_period": "Garantinis laikotarpis"
    }
  },
  "data_toolbar": {
    "search": "Paieška",
    "sort_by": "Rūšiuoti pagal",
    "count_item": "Rodyti {item} elementus"
  },
  "sort": {
    "created_at": "Sukurti datą",
    "updated_at": "Redaguoti datą",
    "title": "Pavadinimas",
    "description": "apibūdinimas",
    "like": "Populiarumas",
    "power": "Plojimai",
    "product_type": "Produkto tipas",
    "discount": "Nuolaida",
    "rate": "Įvertinimas",
    "rate_count": "Įvertinimų skaičius",
    "category": "Kategorija",
    "product": "Produktas",
    "body": "Turinys",
    "card_type": "Kortelės tipas",
    "card_number": "Kortelės numeris",
    "balance": "Balansas",
    "paid": "Išleista suma",
    "currency": "Valiuta",
    "expire_at": "Galiojimo pabaigos data",
    "discount_code": "Nuolaidos kodas",
    "discount_percent": "Nuolaida",
    "discount_limit": "Nuolaidų limitas",
    "max_count": "Maksimalus skaičius",
    "used_count": "Naudota",
    "start_date": "Pradžios data",
    "end_date": "Pabaigos data",
    "total_discount_amount": "Visos nuolaidos",
    "initial_charge": "Pradinis mokestis",
    "total_count": "Bendras skaičius",
    "amount_paid": "Sumokėta suma",
    "name": "vardas",
    "published": "Paskelbta",
    "visits": "Apsilankymai",
    "color": "Spalva",
    "landing_page": "Nukreipimo puslapis",
    "enable": "Įgalinti",
    "fix_commission": "Fiksuotas komisinis",
    "percent_commission": "Procentiniai komisiniai",
    "payment_at": "Mokėjimo diena",
    "issued_at": "Išdavimo data",
    "payment": "Mokėjimas",
    "website": "Interneto svetainė",
    "email": "El. paštas",
    "user": "Vartotojas",
    "code": "Kodas",
    "schedule_at": "Suplanuokite datą",
    "sender": "Siuntėjas",
    "in_que": "Eilėje",
    "sent": "Išsiųsta",
    "shop": "Parduotuvė",
    "quantity": "Kiekis",
    "amount": "Suma",
    "jobs": "Darbai skaičiuojami",
    "success": "Sėkmės skaičiavimas",
    "fail": "Nesėkmių skaičiavimas",
    "distance": "Atstumas",
    "duration": "Trukmė",
    "reset_at": "Iš naujo nustatyti datą",
    "delivery_person": "Asmuo",
    "delivery_service": "Aptarnavimas",
    "date": "Data",
    "order": "Įsakymas",
    "order_id": "Užsakymo ID",
    "status": "Būsena",
    "price": "kaina",
    "count": "Suskaičiuoti",
    "final_price": "Galutinė kaina",
    "charge": "Apmokestinti",
    "mention": "Paminėti",
    "officer": "Pareigūnas",
    "registered": "Registruotas",
    "purchased": "Nupirkta",
    "sex": "Lytis"
  },
  "search_box": {
    "result": "Paieškos rezultatai",
    "tips": "Ieškoti produktų ir kategorijų",
    "label": "Paieška ...",
    "category": "Kategorija"
  },
  "lead_status": {
    "physical_fast_delivery": "Momentinis pristatymas",
    "physical_under_24h_delivery": "Pristatykite per kitas {lead} valandas",
    "physical_over_24h_delivery": "Ruošiamas ir pateikiamas nuo kitų {days} dienų",
    "virtual_fast_prepare": "Momentinis pristatymas",
    "virtual_under_24h": "Bus atlikta per kitas {lead} valandas",
    "virtual_over_24h": "Bus atlikta per kitas {days} dienas"
  },
  "return_request_state": {
    "pending": "Kol",
    "accepted": "Patvirtinta",
    "rejected": "Atstumtas"
  },
  "return_order_reason": {
    "physical": {
      "U1": "Produkto neatitikimas",
      "U2": "Siuntimo pakuotėje nėra prekės",
      "U3": "Paketo ar gaminio sulaužymas",
      "U4": "Pakuotės arba serijos numerio klastojimas",
      "U5": "Trūksta kai kurių prekių iš siuntinio",
      "U6": "Prekė neoriginali",
      "U7": "Prekė neatitinka specifikacijų"
    }
  },
  "image_uploader": {
    "label": "Drag & Drop arba <u>Pasirinkite failą</u>",
    "max_size": "Didžiausias leistinas dydis: {size}"
  },
  "timespan": {
    "Morning": "8-12 val",
    "Evening": "nuo 12 iki 18 val",
    "Night": "18-12 val",
    "Instant": "Momentinis paštas"
  },
  "week_day": {
    "Saturday": "šeštadienis",
    "Sunday": "sekmadienis",
    "Monday": "pirmadienis",
    "Tuesday": "antradienis",
    "Wednesday": "trečiadienį",
    "Thursday": "ketvirtadienis",
    "Friday": "penktadienis"
  },
  "payment_form": {
    "title": "Pasirinkite Mokėjimo būdas",
    "gift_cards_input": "Dovanų kuponai",
    "gift_cards_input_empty": "Dovanų kortelių nerasta..",
    "more": "Kita",
    "pay_amount_by_gift_cards": "Apmokėjimas kortele",
    "select_payment_method": "Pasirinkite mokėjimo būdą iš toliau pateiktų parinkčių.",
    "payment_amount_remained": "Likusi mokėjimo suma",
    "payment_amount": "Sumokėta suma",
    "all_paid_by_gift_cards": "Sveikiname, jums nereikia mokėti už šį užsakymą. Paspauskite mygtuką Mokėti dovanų kortele.",
    "pay_by_gift_cards_action": "Apmokėkite užsakymą mokėjimo kortele",
    "order_free_payment": "Sveikiname, jūsų užsakymas nemokamas!",
    "order_free_payment_action": "Užsisakykite nemokamai dabar",
    "qr": {
      "address": "Mokėjimo adresas",
      "amount": "Suma"
    }
  },
  "discount_input": {
    "limit": "{percent} % nuolaida iki {limit} {currency}",
    "action": "Pridėti nuolaidos kodą",
    "code_input": "Nuolaidos kodas",
    "notifications": {
      "add_success": "Sveikiname, galiojantis nuolaidos kodas."
    }
  },
  "gift_card": {
    "inactive": "Kortelė išjungta",
    "expire": "Galiojimo laikas",
    "transfer": "Perkėlimas",
    "send_to_friend": "Siųsti draugui"
  },
  "count_down": {
    "days": "Diena",
    "hours": "Valanda",
    "minutes": "Minutės",
    "seconds": "sekundės"
  },
  "gift_status": {
    "Unpaid": "Laukiama kvito",
    "Paid": "Mokama",
    "Rejected": "Atstumtas",
    "Canceled": "Atšauktas"
  },
  "gift_program_status": {
    "Airdrop": "Mokėjimo sistema",
    "Advertising": "Reklama",
    "PersonalGift": "Asmeninė dovana",
    "ShopGift": "Dovanų parduotuvė"
  },
  "currency_selector": {
    "label": "Valiuta"
  },
  "need_login": {
    "title": "Prisijungti",
    "login_sms": "SMS prisijungimas",
    "login_google": "Prisijunkite naudodami Google",
    "login_facebook": "Prisijunkite su Facebook",
    "login_account": "Prisijungimas per Selldone",
    "register": "Naujas vartotojas? Registruokis dabar.",
    "mobile_input": "Įveskite savo mobilųjį telefoną",
    "verification_code": "Patvirtinimo kodas",
    "msg_title": "Sveiki,",
    "msg_body": "Prašome prisijungti. Tai užtrunka vos kelias sekundes.",
    "login_apple": "Prisijunkite naudodami „Apple“.",
    "login_email": "Prisijunkite el. paštu",
    "email_login_step_1": "Nurodykite galiojantį el. pašto adresą ir mes atsiųsime prisijungimo kodą. Registracija nereikalinga.",
    "email_login_step_2": "Ar esate tikri, kad teisingai įvedėte savo el. pašto adresą? Prisijungimo kodą atsiųsime nurodytu el. pašto adresu, todėl įsitikinkite, kad jis yra tikslus.",
    "email_login_step_3": "Išsiuntėme kodą į jūsų el. Atminkite, kad kodas baigs galioti po 10 minučių."
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "5 metų aukso parduotuvė"
    },
    "GOLDEN_2YEAR": {
      "name": "4 metų aukso parduotuvė"
    },
    "GOLDEN_3YEAR": {
      "name": "3 metų aukso parduotuvė"
    },
    "GOLDEN_4YEAR": {
      "name": "2 metų aukso parduotuvė"
    },
    "GOLDEN_5YEAR": {
      "name": "1 metų aukso parduotuvė"
    },
    "TOKEN_OWNER_1M": {
      "name": "Auksinis investuotojas"
    },
    "TOKEN_OWNER_10M": {
      "name": "Deimantinis investuotojas"
    },
    "TOKEN_OWNER_100M": {
      "name": "Rubino investuotojas"
    },
    "COMMUNITY_LOYAL": {
      "name": "Aukščiausios ryšių tinklų bendruomenės narys"
    },
    "GOLD_SUPPLIER": {
      "name": "Aukso tiekėjas"
    },
    "GOLD_SELLER": {
      "name": "Aukso prekiautojas"
    },
    "CONTENT_SUPERMAN": {
      "name": "Geriausias turinio gamintojas"
    },
    "NINJA": {
      "name": "Nindzė"
    },
    "STAR": {
      "name": "Žvaigždė"
    },
    "GUARDIAN": {
      "name": "Puikus klientų aptarnavimas"
    },
    "KING": {
      "name": "Turgaus karalius"
    }
  },
  "cookie": {
    "title": "Ši svetainė naudoja slapukus",
    "message": "Ši svetainė naudoja slapukus, kad pagerintų vartotojo patirtį. Naudodamiesi mūsų svetaine sutinkate su visais slapukais pagal mūsų slapukų politiką.",
    "preferences_action": "Tvarkyti nuostatas",
    "agree_action": "Aš sutinku"
  },
  "basket_item_message": {
    "title": "Būtina informacija apie šią prekę",
    "save_actions": "Išsaugoti pranešimą",
    "notifications": {
      "success": "Jūsų įvesties duomenys buvo išsaugoti."
    },
    "product_inputs_preview_message": "Šios tinkinimo parinktys galimos jūsų užsakytam produktui. Kai prekė bus įtraukta į krepšelį, čia galėsite atlikti pakeitimus."
  },
  "faq": {
    "faq": "Dažnai užduodami klausimai",
    "title": "Klausimai ir atsakymai",
    "sub_title": "Ko tu paprašei mūsų padaryti.",
    "message": "Ieškokite atsakymo į savo klausimą tarp toliau pateiktų atsakymų. Klauskite mūsų, jei liko neatsakytų klausimų.",
    "add_question_action": "Užduokite naują klausimą",
    "read_more": "Skaityti daugiau ..",
    "load_more": "Daugiau klausimų..",
    "main_page": "DUK Pagrindinis puslapis",
    "add_new": "Pateikti naują klausimą",
    "login_alert": "Prisijunkite norėdami užduoti klausimą.",
    "question_input": "Klausimas",
    "question_input_placeholder": "Užduokite savo klausimą.",
    "notifications": {
      "success_add": "Jūsų klausimas sėkmingai pateiktas."
    }
  },
  "rating_labels": [
    "Labai blogai",
    "Blogai",
    "Normalus",
    "Gerai",
    "Puikiai"
  ],
  "map_view": {
    "address_detail": "Adreso informacija",
    "change": "Keisti",
    "select": "Pasirinkite",
    "not_found_address": "Vertės nerasta",
    "enter_address_hint": "Įveskite paskirties adresą",
    "enter_your_address": "Įveskite savo adresą.",
    "postal_code": "Pašto indeksas",
    "phone_input": "Telefonas {type}",
    "building_number": "Pastato numeris",
    "building_unit": "Vienetas",
    "full_name_input": "Visas vardas {type}",
    "save_detail_action": "Išsaugokite informaciją",
    "more_detail_input": "Daugiau aprašymo",
    "add_address_to_list": "Pridėti adresą į sąrašą",
    "address_title_input": "Adreso etiketė (būtina)",
    "notifications": {
      "save_in_list": "Šis adresas buvo išsaugotas jūsų sąraše su visa jo informacija.",
      "edit_success": "Naujos adreso reikšmės išsaugotos {title}."
    },
    "delete_address_dialog": {
      "title": "Ištrinti adresą",
      "message": "Ar tikrai norite ištrinti šį adresą?",
      "action": "Pašalinti adresą"
    }
  },
  "comment_manager": {
    "can_not_edit": "Negalima redaguoti šio komentaro!",
    "comment_input_empty": "Pranešimo tekstas tuščias!",
    "article_not_saved": "Išsaugokite straipsnį!"
  },
  "wheel_fortune": {
    "title": "Žaisk ir laimėk",
    "message": "Kiekvieno žaidimo kaina yra 10 žetonų. Šiuo metu turite {chips} lustą. Gaukite daugiau lustų pirkdami parduotuvėje.",
    "win_message": "Sveikiname, Jūs laimėjote!",
    "lost_message": "Atsiprašome, jūs pralaimėjote žaidimą.",
    "try_again": "Galite bandyti dar kartą"
  },
  "json": {
    "add": "Pridėkite struktūros duomenis",
    "add_message": "Sukurkite naujus struktūros duomenis",
    "structures": "Struktūros",
    "book": {
      "title": "Knyga",
      "desc": "Knygos veiksmai, leidžiantys naudotojams nusipirkti knygą, kurią jie randa tiesiai iš Paieškos rezultatų."
    },
    "occupation": {
      "title": "Numatomas atlyginimas",
      "desc": "Informacija apie darbo užmokesčio įvertinimą, pvz., atlyginimų diapazonas ir regiono atlyginimų vidurkis pagal darbo tipus, rodomas darbo paieškos sistemoje „Google“."
    },
    "course": {
      "title": "Kursas",
      "desc": "Mokomieji kursai, rodomi konkretaus teikėjo sąraše. Kursai gali apimti kurso pavadinimą, teikėją ir trumpą aprašymą."
    },
    "howto": {
      "title": "Kaip",
      "desc": "Vadovėlis supažindins vartotojus su vaizdo įrašu, vaizdais ir tekstu, kaip sėkmingai atlikti užduotį."
    },
    "recipe": {
      "title": "Receptas",
      "desc": "Receptai, kurie rodomi kaip individualus turtingas rezultatas arba pagrindinės karuselės dalis."
    }
  },
  "support": {
    "Financial": "Finansinis",
    "Technical": "Techninė",
    "Advisor": "Patarėjas"
  },
  "condition": {
    "new": "Nauja",
    "refurbished": "Renovuotas",
    "used": "Naudota",
    "used_fair": "Naudotas sąžiningas",
    "used_good": "Naudotas geras",
    "used_like_new": "Naudotas kaip naujas"
  },
  "variant_filter": {
    "title": "Produkto variantų filtras",
    "only_available": "Sandelyje"
  },
  "service": {
    "task": {
      "title": "Užduotys",
      "message": "Šioje tarnyboje atliekamų užduočių sąrašas."
    },
    "appointment": {
      "title": "Paskyrimas",
      "message": "Pasirinkite savaitės laiką iš toliau pateiktų laikų, atsižvelgdami į jums tinkamiausią dieną ir valandą."
    },
    "booking": {
      "title": "Rezervavimas",
      "message": "Žemiau esančiame kalendoriuje nurodykite dienų, kurias norite rezervuoti, laikotarpį."
    },
    "subscription": {
      "title": "Prenumerata"
    },
    "charge": {
      "title": "Apmokestinti"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "Fiksuota kainodara",
      "message": "Tokio tipo kainodaroje prekės kaina yra fiksuota suma ir pirkėjui nereikia prašyti kainos apskaičiavimo."
    },
    "ESTIMATION": {
      "title": "Numatoma kaina",
      "message": "Prekių ir paslaugų kainą tam tikru mastu apskaičiuos pardavėjas pateikdamas užsakymą, mokėjimo sąskaitos faktūros gali būti keičiamos ar pridedamos paslaugos metu."
    },
    "AGREEMENT": {
      "title": "Sutarties kainodara",
      "message": "Galutinės prekių ar paslaugų kainos pardavėjas po užsakymo pateikimo nekeis."
    },
    "BID": {
      "title": "Pasiūlymas / aukcionas",
      "message": "Prekė bus parduota už didžiausią siūlomą kainą potencialių pirkėjų."
    }
  },
  "map": {
    "title": "Produktų gavimo paskirties vieta",
    "confirm": "Nustatyti vietą",
    "address": "Kelionės tikslas",
    "receptor": "Imtuvas"
  },
  "ShopBots": {
    "telegram": "Telegrama"
  },
  "article_tags": {
    "title": "Turinio žymos",
    "tags_input": "Žymos",
    "tags_input_message": "Žymos Šio straipsnio sąrašas",
    "notification": {
      "add_success": "Pridėtos žymos"
    }
  },
  "difficulties": {
    "very_complicated": "Labai sudėtinga",
    "hard": "Sunku",
    "intermediate": "Tarpinis",
    "easy": "Lengva"
  },
  "billing_period": {
    "Daily": "Kasdien",
    "Weekly": "Kas savaitę",
    "Monthly": "Kas mėnesį",
    "Every3Months": "Kas 3 mėnesius",
    "Every6Months": "Kas 6 mėnesius",
    "Yearly": "Kasmet"
  },
  "buyer_rating_statement": {
    "between1_2": "Oi neblogai!",
    "between2_3": "Viskas gerai!",
    "between3_4": "Žmonėms tai patinka!",
    "between4_5": "Žmonėms tai patinka!"
  },
  "seasons": {
    "spring": "Pavasaris",
    "summer": "Vasara",
    "autumn": "Ruduo",
    "winter": "Žiema"
  }
};