export default {
  "currency_default": "USD",
  "language_default": "en",
  "selldone": "Seldone",
  "store": "toa",
  "not_exist": "Karekau",
  "error": "Hapa",
  "active": "Hohe",
  "inactive": "hohekore",
  "required_value": "Nga uara e hiahiatia ana",
  "original_warranty": "Taurangi Hua Taketake",
  "return_warranty_days": "{ngā) rā taurangi whakahoki",
  "no_return_warranty": "Karekau he hokinga mai",
  "reed_agree_terms": "Kua panuihia e au nga tikanga mo te whakamahi me te kaupapa here tūmataiti me te whakaae ki a raatau.",
  "commons": {
    "Currency": "Moni",
    "COD": "COD",
    "State": "State",
    "Price": "utu",
    "order_price": "Te nui ota",
    "VAT": "VAT",
    "Discount": "Te utu",
    "In_Stock": "Kei roto i nga taonga",
    "Variants": "Nga momo rereke",
    "No_variants": "Kaore he rereke",
    "all": "KATOA",
    "today": "I tenei ra",
    "yesterday": "Inanahi",
    "license": "Raihana",
    "home": "Kainga",
    "support": "Tautoko",
    "messages": "Nga Karere",
    "no_message": "Karekau he karere",
    "empty": "Putua",
    "phone": "Waea",
    "address": "wāhi noho",
    "name": "Ingoa",
    "password": "Kupuhipa",
    "email": "Īmēra",
    "mobile": "Pukoro",
    "login": "takiuru",
    "register": "Rehita",
    "select_account": "Tīpako pūkete",
    "online": "ipurangi",
    "offline": "Tuimotu",
    "finish": "Whakaoti",
    "finished": "Kua oti",
    "preview": "Arokite",
    "free": "Kore utu",
    "free_completely": "Ohaurunga tino kore utu",
    "fee": "Utu",
    "month": "Marama",
    "months": "Marama",
    "faq": "Pātai Auau",
    "question": "Pātai",
    "answer": "Whakautu",
    "create_date": "Waihangahia te ra",
    "update_date": "Whakahou ra",
    "start_date": "Te ra timata",
    "end_date": "Te ra mutunga",
    "social": "Hapori",
    "total": "Tapeke",
    "orders": "Nga ota",
    "sessions": "Wātū",
    "product_views": "Nga tirohanga hua",
    "add_to_carts": "Tāpirihia ki nga kaata",
    "checkouts": "Takitaki",
    "payments": "Utu",
    "organic_search": "Rapu pararopi",
    "other": "Ētahi atu",
    "landing_page": "Whārangi Taunga",
    "discount_code": "Waehere hekenga",
    "total_sell": "Tapeke hoko",
    "details": "Nga korero",
    "currency": "Moni",
    "amount": "Te nui",
    "published": "Whakaputaina",
    "draft": "Hukarere",
    "save_changes": "Tiakina nga huringa",
    "source": "Puna",
    "medium": "Waenga",
    "url": "Url",
    "revenue": "Te moni whiwhi",
    "performance": "Mahi",
    "term": "Wāhanga",
    "content": "Ihirangi",
    "session": "Wātū",
    "product": "Hua",
    "add": "Tāpiri",
    "checkout": "Takitaki",
    "payment": "Utu",
    "more_options": "Ētahi atu kōwhiringa",
    "full_name": "Ingoa katoa",
    "tel": "Waea",
    "about_me": "Mo au",
    "request_checking": "Tono arowhai",
    "passport": "Uruwhenua",
    "birthday": "Ra whanau",
    "country": "Whenua",
    "city": "Taone",
    "gender": "Ira tangata",
    "offer": "tuku",
    "website": "paetukutuku",
    "apply_for_all_products": "∞ Tono mo nga hua katoa",
    "fix_commission": "Komihana pumau",
    "percent_commission": "Komihana ōrau",
    "fixed_discount": "hekenga tuturu",
    "discount_percentage": "Te hekenga ōrau",
    "discount_limit": "Tepe utu",
    "no_code": "Karekau he waehere",
    "max_count": "Tatau mōrahi",
    "count_unit": "Nga taonga",
    "used": "Kua whakamahia",
    "daily": "Ia rā",
    "monthly": "Ia marama",
    "yearly": "Ia tau",
    "state": "Tūnga",
    "disable": "Monokia",
    "enable": "Whakahohe",
    "activation_code": "Waehere whakahohe",
    "quantity": "Te nui",
    "no_club": "Karekau he karapu",
    "per_order": "Ia ota",
    "count": "Tatau",
    "seconds": "Hekona",
    "auto": "Aunoa",
    "title": "Taitara",
    "message": "Karere",
    "width": "Whānui",
    "length": "Te roa",
    "height": "Teitei",
    "label": "Tapanga",
    "click": "Pāwhiri",
    "bank": "Peeke",
    "default": "Taunoa",
    "role": "Tūnga",
    "user": "kaiwhakamahi",
    "users": "Kaiwhakamahi",
    "code": "Waehere",
    "total_payment": "Utu katoa",
    "balance": "Taurite",
    "chance": "Faingamālie",
    "free_for_new_users": "Kore utu mo nga kaiwhakamahi hou",
    "prize_amount": "Te moni utu",
    "win": "Win",
    "gift_card": "Kaari koha",
    "discount": "Te utu",
    "config": "Whirihora",
    "prize": "taonga",
    "Prizes": "Nga taonga",
    "result": "Hua",
    "price": "utu",
    "lottery": "Rota",
    "coupon": "tīkitipati",
    "customer_club": "Karapu Kiritaki",
    "shipping": "Te tuku",
    "sum": "Huihuinga",
    "not_paid": "Kaore i utua",
    "category": "Kāwai",
    "done": "Kua oti",
    "email_from": "Mai",
    "subject": "Kaupapa",
    "schedule": "Hōtaka",
    "files_list": "Rarangi kōnae",
    "file_max_size": "Te rahi o te konae",
    "value": "Uara",
    "help": "Awhina",
    "shipping_tax": "Taake tuku",
    "net_price": "Utu kupenga",
    "tax": "Taake",
    "tax_included": "Kei roto i te utu",
    "limit": "Tepe",
    "min_purchase": "Te hokonga iti",
    "eligible_for": "E tika ana mo",
    "only_for_first_buy": "Mo te hoko tuatahi anake",
    "one_time_use": "Ka taea te whakamahi i te wa kotahi",
    "period_of_qualify": "Te rohe whakamahi wa",
    "no_constraint": "Kaore he rohe",
    "timespan": "Wā wā",
    "days": "Ra(ng)",
    "weight": "Taumaha",
    "distance": "Tawhiti",
    "last_status": "Te mana whakamutunga",
    "issued_at": "I tukuna i",
    "order": "Ota",
    "order_detail": "Nga korero ota",
    "percent": "ōrau",
    "applied_count": "Tatau whakamahia",
    "campaign": "Whakatairanga",
    "os": "Pūnaha whakahaere",
    "browser": "Pūtirotiro",
    "device": "Pūrere",
    "device_ip": "Wāhitau IP Pūrere",
    "location": "Tauwāhi",
    "user_agent": "Kaiwhakamahi Kaiwhakamahi",
    "affiliate": "Hononga",
    "timeline": "Rarangi Wā",
    "add_note": "Tāpiri tuhipoka",
    "record": "Tuhia",
    "unlimited": "He mutunga kore",
    "show_coupons": "Whakaatuhia nga tīkitipati",
    "hide_coupons": "Huna tīkitipati",
    "service_area": "Te waahi ratonga",
    "apps": "Taupānga",
    "plugins": "monomai",
    "bots": "Bots",
    "categories": "Ngā Kāwai",
    "products": "Hua",
    "business": "Pakihi",
    "personal": "Whaiaro",
    "size": "Rahi",
    "holiday": "Hararei",
    "sod": "Utu I te Tukunga",
    "cod": "Moni i runga i te tuku",
    "free_shipping": "He utu kore utu",
    "hours": "Nga haora",
    "send_date": "Te ra tuku",
    "deliver_date": "Te ra tuku",
    "return_date": "Te rā hokinga mai",
    "pending": "Tarewa ana",
    "delivered": "Kua tukuna",
    "returned": "Kua hoki mai",
    "canceled": "Kua whakakorehia",
    "shipping_cost": "Utu kaipuke",
    "action": "Mahi",
    "cancel_date": "Whakakore rā",
    "deliver_in_process": "Ka tukuna te ota..",
    "kind": "Momo",
    "detail": "Nga korero",
    "map": "Mapi",
    "actions": "Nga Mahi",
    "navigation": "Whakaterenga",
    "navigation_app": "Taupānga",
    "payment_date": "Te ra utu",
    "duration": "Roanga",
    "bill": "Pire",
    "delivery_persons": "Karere",
    "delivery_services": "Nga ratonga tuku",
    "live_view": "Tiro ora",
    "cart": "Kaata",
    "priority": "Ko te kaupapa matua",
    "sufficient_credit": "He nama rawaka",
    "max_package_size": "Rahi mōrahi mōkihi",
    "delay": "Whakaroa",
    "credit": "Te nama",
    "livemode": "Ora",
    "paused": "Kua whakataa",
    "debug": "Patuiro",
    "token": "Tohu",
    "status": "Tūnga",
    "courier": "Karere",
    "track": "Aroturuki",
    "track_order": "Aroturuki Tono",
    "cost": "Utu",
    "receipt": "Rihiti",
    "origin": "Taketake",
    "destination": "tauranga",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "He iti rawa nga taonga!",
    "sub_total": "Tapekeroto",
    "customer": "Kiritaki",
    "delivery": "Tukunga",
    "online_orders": "Nga Ota Ipurangi",
    "pos_orders": "Nga Ota POS",
    "chips": "Nga maramara",
    "subscribed": "Kua ohauru",
    "unsubscribed": "Kore ohaurunga",
    "last_login": "Takiuru whakamutunga",
    "join_at": "Te ra hono",
    "club": "Karapu",
    "buyer": "Kaihoko",
    "seller": "Kaihoko",
    "or": "Ranei",
    "type": "Momo",
    "condition": "Tikanga",
    "brand": "Waitohu",
    "attempt": "Nganatanga",
    "error": "Hapa",
    "success": "Angitu",
    "fail": "Rahua",
    "inventory": "Inventory",
    "link": "Hononga",
    "visits": "Nga toronga",
    "transactions": "Nga tauwhitinga",
    "vat": "VAT",
    "pos_vat": "POS VAT",
    "sort_by": "Kōmaka mā..",
    "from": "Mai",
    "from_lead_time": "I roto i nga {hours} e whai ake nei",
    "no_credit_card_info": "Kaore he korero kaari!",
    "active": "Hohe",
    "not_active": "Kaore i whakahohehia!",
    "referrals": "Tohutoro",
    "dashboard": "Papatohu",
    "more": "Ētahi atu",
    "inactive": "hohekore",
    "developer": "Kaihanga",
    "setting": "Tautuhinga",
    "membership_conditions": "Nga tikanga mema",
    "customers": "Kaihoko",
    "created_at": "Te ra i hanga",
    "updated_at": "Whakahoutanga whakamutunga",
    "register_at": "Te ra rehita",
    "old": "Tawhito",
    "new": "Hou",
    "start": "Tīmata",
    "end": "Whakamutunga",
    "pos": "POS",
    "out_of_stock": "Kua pau nga taonga",
    "fake": "rūpahu",
    "low_inventory_warning": "Kia tupato, He iti rawa nga taonga!",
    "webhook": "Tukutuku",
    "notification": "Panuitanga",
    "sms": "SMS",
    "online_payment_link": "Hononga utu ipurangi",
    "waiting_load_data": "E tatari ana ki te uta raraunga..",
    "views": "Tirohanga",
    "sales": "Hokonga",
    "total_views": "Katoa nga tirohanga",
    "total_sales": "Tapeke hoko",
    "from_previous_n_days": "No nga ra whakamutunga",
    "drop_shipping": "Te tuku tuku",
    "commission": "Komihana",
    "shipping_area": "Te waahi tuku",
    "main_seller": "Kaihoko matua",
    "domain": "Rohe",
    "contact": "Nga korero whakapā",
    "wallet": "Pukoro",
    "reseller": "Kaihoko",
    "tracking_code": "Waehere aroturuki",
    "tracking_url": "URL Aroturuki",
    "fulfillments": "Nga tutukitanga",
    "reject": "Whakakahore",
    "reserved": "Kua rahuitia",
    "score": "Tohu",
    "customer_price": "Utu kaihoko",
    "options": "Kōwhiringa",
    "show_details": "Whakaatuhia nga taipitopito",
    "no_data": "Karekau he raraunga..",
    "waiting": "E tatari ana...",
    "waiting_connecting_payment": "E tatari ana mo te ratonga utu...",
    "creating_secure_payment": "Te hanga utu haumaru.",
    "officer": "Apiha",
    "ticket": "Tikiti",
    "ticket_url": "url tikiti",
    "closed_at": "Katia i",
    "close_ticket": "Katia te tikiti",
    "reopen_ticket": "Whakatuwheratia ano te tikiti",
    "require": "Hiahia*",
    "search": "Rapu...",
    "language": "Reo",
    "tasks": "Nga Mahi",
    "permissions": "Whakaaetanga",
    "finish_date": "Te ra mutunga",
    "complete_date": "Te ra otinga",
    "settle_date": "Te ra whakataunga",
    "cost_span": "Awhe utu",
    "industry": "Ahumahi",
    "rating": "Whakatauranga",
    "rates": "Whakatauranga",
    "seen_at": "Ka kitea i",
    "completed": "Kua oti",
    "you": "Ko koe",
    "shop": "Toa",
    "store": "toa",
    "granted": "Whakaaetia",
    "deny": "Whakakahore",
    "request": "Tono",
    "expert": "Tohunga",
    "response": "Whakautu",
    "requests": "Nga tono",
    "experts": "Nga tohunga",
    "responses": "Nga whakautu",
    "negotiations": "Nga whiriwhiringa",
    "all_chats": "Nga korerorero katoa",
    "chats": "Kōrerorero",
    "tags": "Tohutohu",
    "description": "Whakaahuatanga",
    "rates_count": "Te maha o nga whakatauranga",
    "rate": "Whakatauranga",
    "comment": "Kōrero",
    "chat": "Kōrerorero",
    "install": "Tāuta",
    "edited": "Whakatikatika",
    "undo": "Wetekina",
    "redo": "Mahi ano",
    "male": "Tane",
    "female": "Wahine",
    "calculator": "Te tātaitai",
    "catalog": "Putumōhio",
    "max_height": "teitei teitei",
    "images_compare": "Whakatauritenga whakaahua",
    "canvas": "Kanawehi",
    "table_of_contents": "Ripanga ihirangi",
    "comments": "Nga korero",
    "badge_codes": "Waehere tohu",
    "need_more": "Me nui ake?",
    "invite_glow_caption": "Tikina 14.9$ mo ia hoa!",
    "register_free": "100% rehita kore utu",
    "gift": "Koha",
    "google": "Google",
    "facebook": "Pukamata",
    "instagram": "Instagram",
    "instashop": "Instashop",
    "show": "Whakaatu",
    "hide": "Huna",
    "waiting_review": "E tatari ana ki te arotake",
    "not_selected": "Kaore i tohua",
    "time": "Te wa",
    "final_price": "Utu whakamutunga",
    "starting_price": "Utu timata",
    "day": "Ra",
    "paid": "Ka utua",
    "service_bill": "Utu nama",
    "avocado": "Awhekātō",
    "delivery_price": "Utu kaipuke",
    "select_address": "Tīpako wāhitau",
    "image": "Whakaahua",
    "view": "Tirohanga",
    "sell": "Hokonga",
    "hyper": "Hiper",
    "cart_list": "Kaata",
    "barcode_scanner": "Matawai paewaehere",
    "scan_qr_code": "Matawai waehere QR",
    "new_carts": "Kaata hou",
    "pays": "Nga utu",
    "annually": "Ia tau",
    "sells": "Hokonga",
    "articles": "Tuhinga",
    "jobs": "Nga mahi",
    "job": "Hopa",
    "blog": "Blog",
    "deleted_at": "I mukua i",
    "capacity": "Te kaha",
    "download_at": "Te ra tango whakamutunga",
    "downloads": "Tikiake",
    "usage": "Whakamahinga",
    "select_upload_file": "Tīpakohia, maturuturu ranei te konae",
    "download_link": "Tikiake hono",
    "uploading": "Tukuake ana..",
    "files": "Kōnae",
    "star": "Whetu",
    "speed": "Te tere",
    "feedback": "Urupare",
    "new_messages": "Nga karere hou",
    "file": "Kōnae",
    "attachment": "Āpitihanga",
    "gallery": "Taiwhanga",
    "sync": "Tukutahi",
    "diff_time": "Te rereketanga o te wa",
    "network": "Whatunga",
    "account": "Pūkete",
    "configuration": "Whirihoranga",
    "blockchain": "Poraka",
    "blog_link": "Hononga rangitaki",
    "community": "Hapori",
    "critical_zone": "Rohe tino nui",
    "statistics": "Tauanga",
    "access": "Urunga",
    "seo": "SEO",
    "followers": "Kaiwhaiwhai",
    "followings": "Whai muri",
    "private": "Arokite",
    "soon": "Aita i maoro roa",
    "features": "Ngā āhuatanga",
    "bot": "Bot",
    "sample": "Tauira",
    "how_it_work": "Me pehea te mahi?",
    "page": "Whārangi",
    "congratulations": "Tena koe",
    "recommend": "Tohutohu",
    "recommended": "E taunaki ana",
    "recoms": "Nga Tohutohu",
    "likes": "Ka pai",
    "clicks": "Pāwhiri",
    "platform": "Paerewa",
    "cms": "CMS",
    "cash": "Moni moni",
    "dir_payment": "Te whakawhiti putea",
    "auto_complete": "Kua oti aunoa",
    "compare": "Whakataurite",
    "infinite": "He mutunga kore",
    "tips": "Tohutohu",
    "technical": "Hangarau",
    "finance": "Pūtea",
    "your_phone_input": "Whakauruhia he nama waea",
    "income": "Te moni whiwhi",
    "change": "Hurihia",
    "new_users": "Kaiwhakamahi hou",
    "success_orders": "Nga ota angitu",
    "direct": "Tika",
    "last_activity": "Mahi whakamutunga",
    "landing": "Taunga",
    "now": "Inaianei",
    "accept_agreement": "Kua panuitia e au, kua whakaae ahau ki nga tikanga.",
    "report": "Ripoata",
    "tablet": "Papa",
    "pc": "PC",
    "acquisition_channel": "Hongere hoko",
    "to": "Ki",
    "info": "Nga korero",
    "general": "Whānui",
    "upload": "Tukuake",
    "general_config": "whirihora whānui",
    "limits_config": "Nga herenga",
    "design_config": "Hoahoa me te ahua",
    "duration_config": "Tepe roa",
    "constraints_config": "Nga rohe whakauru",
    "clubs_config": "Kei roto i nga Karapu",
    "additional_config": "whirihora taapiri",
    "import": "Kawemai",
    "ribbon": "Ripene",
    "countries": "Nga whenua",
    "edit": "Whakatikatika",
    "delete": "Mukua",
    "analytics": "Nga tātaritanga",
    "rules": "Ture",
    "unset": "Kaore i whakaritea",
    "carts": "Kaata",
    "optional": "Kōwhiringa",
    "design": "Hoahoa",
    "filter": "Tātari",
    "send": "Tukua",
    "approved": "Whakaaetia",
    "unit": "Waeine",
    "profile": "kōtaha",
    "shipping_rates": "Reiti kaipuke",
    "package": "Mōkī",
    "overview": "Tirohanga",
    "live": "Ora",
    "never": "Kaua rawa",
    "always": "I nga wa katoa",
    "mandatory": "Whakahau",
    "expire_at": "Te Ra Whakamutunga",
    "position": "Turanga",
    "channel": "Hongere",
    "age": "Te tau",
    "charge": "Te utu",
    "giftcard": "Kaari koha",
    "acquisition": "Te hokonga",
    "conversion": "Te hurihanga",
    "total_payments": "Nga utu katoa",
    "community_ask": "Uia ki te hapori",
    "children": "Tamariki",
    "export": "Kaweake",
    "list": "Rarangi",
    "hierarchy": "Hierarchy",
    "images": "Whakaahua",
    "demo": "Whakaaturanga",
    "author": "Kaituhi",
    "designer": "Kaihoahoa",
    "max": "Mōrahi",
    "accepted": "Whakaaetia",
    "reply": "Whakautu",
    "reviewed": "Kua arotakehia",
    "restored": "Kua whakahokia",
    "merchant": "Kaihokohoko",
    "per_product": "Ia hua",
    "journey": "Haerenga",
    "after": "I muri",
    "waiting_for_payment": "Tena koa whakaoti utu...",
    "hour": "Haora",
    "minute": "Te meneti",
    "premium": "Moni",
    "light": "Maama",
    "dark": "pouri",
    "guest": "Manuhiri",
    "shops": "Toa",
    "vendor": "Kaihoko",
    "vendors": "Kaihoko",
    "marketplace": "Te kainga hokohoko",
    "verify_date": "Manatokohia te ra",
    "note": "Tuhipoka",
    "panel": "Paewhiri",
    "removed": "Kua tangohia",
    "segments": "Nga waahanga",
    "personal_info": "Nga korero whaiaro",
    "preferences": "Manakohanga",
    "spec": "Spec",
    "reviews": "Nga arotake",
    "constraints": "Nga herenga",
    "flexible": "He ngawari",
    "usage_limit": "Tepe whakamahi",
    "temporary": "Rangitahi",
    "original": "Taketake",
    "saved": "Kua tiakina!",
    "sort": "Kōmaka",
    "documents": "Tuhinga",
    "document": "Tuhinga",
    "please_wait": "Tatari koa...",
    "pickup": "Te tiki",
    "customize": "whakarite",
    "difficulty": "Te uaua",
    "banned": "Kua rāhuitia",
    "company": "Kamupene",
    "tax_shipping": "Taake Tukunga",
    "warranty": "Pūtāhui",
    "return_policy": "Kaupapa Whakahoki",
    "guide": "Arataki",
    "translate": "Whakamaori",
    "public": "Tūmatanui",
    "deleted": "Kua mukua",
    "variant": "He rereke",
    "secure": "Haumaru",
    "admin": "Kaiwhakahaere"
  },
  "dialogs": {
    "delete": {
      "title": "Mukua",
      "message": "Me muku tonu tenei mea?",
      "action": "Ae, Mukua inaianei"
    }
  },
  "actions": {
    "add_to_cart": "Tāpiri ki te Kete",
    "cancel": "Whakakore",
    "update": "Whakahou",
    "add": "Tāpiri",
    "delete": "Mukua",
    "new": "Hou",
    "save_continue": "Tiakina & Haere tonu",
    "save": "Tiaki",
    "save_changes": "Tiakina nga huringa",
    "change": "Hurihia",
    "continue": "Haere tonu",
    "close": "Katia",
    "finish": "Whakaoti",
    "poll": "Pooti",
    "view": "Tirohanga",
    "edit": "Whakatikatika",
    "next": "Whai muri",
    "previous": "Tuhinga o mua",
    "create": "Waihanga",
    "set": "whakatakotoria",
    "find": "Kimihia",
    "accept": "Whakaae",
    "reject": "Whakakahore",
    "back": "Whakamuri",
    "pay": "Utu",
    "pay_now": "Utu inaianei",
    "print": "Taa",
    "return": "Hoki mai",
    "publish": "Whakaputa",
    "confirm": "Whakaū",
    "copy": "Tārua",
    "submit": "Tukuna",
    "send": "Tukua",
    "yes": "Ae",
    "no": "kahore",
    "meh": "Hmm",
    "clear": "Maamaa",
    "dismiss": "Whakakore",
    "search": "Rapu",
    "deselect_all": "Whakakorehia te katoa",
    "select_all": "Tīpakohia te katoa",
    "refresh": "Tāmata",
    "verify": "Manatoko",
    "play": "Te purei",
    "open": "Tuwhera",
    "calculate": "Tatauhia",
    "quick_buy": "Hoko Tere",
    "click_here": "Pāwhiri ki konei",
    "schedule": "Hōtaka",
    "send_now": "Tukuna inaianei",
    "download": "Tikiake",
    "reset_default": "Tautuhi ki te taunoa",
    "reset": "Tautuhi Anō",
    "check": "Takina",
    "cod_payment": "Moni i runga i te tuku",
    "dir_payment": "Te whakawhiti moni",
    "online_payment": "Utu Online",
    "checkout": "Takitaki",
    "show_all": "Whakaatu katoa",
    "login": "takiuru",
    "logout": "Takiputa",
    "more": "Ētahi atu..",
    "collapse": "Tiango",
    "apply_change": "Hoatu nga huringa",
    "apply": "Tonoa",
    "add_giftcard": "Tāpiri kāri koha",
    "charge": "Te utu",
    "send_invites": "Tuku pōwhiri",
    "past": "o mua",
    "restore": "Whakaora",
    "cut": "Tapahia",
    "get_sms_code": "Tikina te waehere motuhēhēnga",
    "register_no_mail": "Haere tonu me te kore imeera",
    "no_mail_register_message": "Karekau he wahitau imeera kua wareware ranei i to kupuhipa?",
    "reset_by_mail": "Whakaora kupuhipa ma te imeera",
    "reset_by_sms": "Kupuhipa whakaora ma te SMS",
    "cash_payment": "Utu moni",
    "show_chart": "Whakaatu tūtohi",
    "open_app": "Tuwhera te taupānga",
    "login_now": "Takiuru inaianei",
    "watch_video": "Tirohia te ataata",
    "check_now": "Tirohia inaianei",
    "remove_image": "Tango atahanga",
    "view_website": "Tuwhera hono",
    "explore": "Tūhura {name}",
    "go": "Haere",
    "read_more": "Pānuitia atu",
    "start_now": "Tīmata ināianei — He kore utu",
    "view_live": "Tirohia ora",
    "resend_code": "Tukua ano te waehere",
    "invite": "Powhiri",
    "add_more": "Tāpiri atu",
    "install_now": "Tāuta ināianei",
    "uninstall": "Wetetāuta",
    "show_preview": "Whakaatu arokite",
    "hide_preview": "Huna arokite",
    "download_now": "Tikiake Na",
    "auto_fill": "WhakakīAunoa",
    "track": "Aroturuki",
    "change_state": "Huri Tūnga",
    "done": "Kua oti",
    "reply": "Whakautu",
    "watch_now": "Matakitaki Inaianei",
    "unlock": "Wewete",
    "lock": "Maukati",
    "create_clone": "Waihangahia te clone",
    "regenerate": "Whakahou",
    "add_message": "Tāpiri karere",
    "continue_chat": "Kōrerorero tonu",
    "add_new_message": "Tāpiri karere hōu"
  },
  "instance_message_title": "Tukuna he karere inamata",
  "instance_message": "Kia ora {name}, Ko {author} toku ingoa no {company}.",
  "errors": {
    "419": "Kua roa koe e kore e mahi, tena koa <b>⟳ WHAKATAUIA TE wharangi</b> mo nga take haumaru.",
    "gateway_blockchain_sync_error": "Kaore te punaha e tukutahi me te poraka. E kore e taea te hanga i tetahi tauwhitinga hou kia oti ra ano nga tukutahitanga a o tatou kaimau. Kei te whakaoti rapanga.",
    "gateway_network_error": "Kua raru te ratonga kuaha utu utu."
  },
  "receiver_info": {
    "map": {
      "title": "Wāhitau tuku",
      "confirm": "Tautuhia te waahi",
      "address_type": "tauranga",
      "receptor_type": "Kaiwhiwhi"
    },
    "receiver_address": "Tīpakohia te wāhitau kaipuke",
    "address": "wāhi noho",
    "postcode": "Waehere poutāpeta",
    "enter_value": "Whakakiia ki konei",
    "address_note": "Tuhipoka",
    "tel": "Tau whakapā",
    "service_address": "Tīpakohia tō wāhitau"
  },
  "weight": {
    "g": "g",
    "oz": "oz",
    "lb": "lb",
    "kg": "kg"
  },
  "mass_unit_name": {
    "g": "karamu",
    "oz": "hekere",
    "lb": "Pauna",
    "kg": "kirokaramu"
  },
  "length": {
    "cm": "cm",
    "in": "i roto",
    "ft": "ft",
    "mm": "mm",
    "m": "m",
    "yd": "yd"
  },
  "size_unit_name": {
    "cm": "Henemita",
    "in": "Inihi",
    "ft": "Waewae",
    "mm": "mirimita",
    "m": "mita",
    "yd": "Iari"
  },
  "distance": {
    "m": "mita",
    "km": "km"
  },
  "time": {
    "days": "Nga ra",
    "hours": "Nga haora",
    "minutes": "Nga meneti",
    "seconds": "Hekona"
  },
  "units": [
    "Waeine",
    "tūemi",
    "ia",
    "whakatakotoria",
    "wahi",
    "kirokaramu",
    "karamu",
    "mirakarama",
    "mita",
    "mirimita",
    "mita tapawha",
    "waewae tapawha",
    "mita pūtoru",
    "rita",
    "miramira",
    "waewae",
    "kārani",
    "inihi",
    "hekere",
    "pauna",
    "hauwhā",
    "iari",
    "ruma",
    "hēkona",
    "meneti",
    "haora",
    "nga ra",
    "wiki",
    "marama",
    "tau"
  ],
  "region_types": {
    "State": "State",
    "Territory": "Te rohe",
    "Province": "Porowini"
  },
  "transaction_status": {
    "RequireAction": "Me Mahi",
    "Processing": "Tukatuka",
    "Canceled": "Kua whakakorehia",
    "Succeeded": "I angitu"
  },
  "placeholders": {
    "name": "Jone Cox",
    "email": "your-mail@mail.com",
    "phone": "+1 000 0000",
    "language": "Tīpakohia te reo..",
    "friend_email": "Te imeera a to hoa...",
    "friend_name": "Kōwhiringa. Te ingoa o to hoa",
    "select_date": "Tīpakohia he rā..."
  },
  "notification": {
    "confirm": "Whakaū",
    "confirm_message": "Kua tiakina pai nga huringa.",
    "error": "Hapa",
    "message": "Karere",
    "caution": "Tupato",
    "warning": "Whakatupato",
    "award": "Mihi",
    "error_message": "Heoi, kua puta he hapa.",
    "congratulation": "Mihi",
    "coming_soon": "Aita i maoro roa",
    "on_fetching_data": "Kei te whiwhi korero ..",
    "new_pwa_version": "Putanga hou kei te waatea inaianei. Kei te pirangi koe ki te whakahou i te tono?",
    "over_license_limit": "Neke atu i te Tepe Raihana",
    "update_license": "Whakahoutia to raihana",
    "required": "E hiahiatia ana",
    "invalid_email": "ī-mēra muhu",
    "invalid_domain": "rohe muhu",
    "invalid_min_length": "Ko te roanga iti me {length}",
    "invalid_min_array_length": "Tīpakohia te {length} tūemi",
    "invalid_max_chars": "Max {maxCount} pūāhua",
    "invalid_url": "URL muhu",
    "country_invalid": "Tīpakohia te whenua ūnga!",
    "postal_code_invalid": "Tautuhi waehere poutāpeta whaimana!"
  },
  "colors": {
    "#D32F2F": "Whero",
    "#C2185B": "Mawhero",
    "#7B1FA2": "Waiporoporo",
    "#512DA8": "Papura pouri",
    "#303F9F": "Indigo Blue",
    "#1976D2": "Kahurangi",
    "#0288D1": "Kahurangi Maama",
    "#0097A7": "Turquoise Blue",
    "#00796B": "Kuihi Kākāriki",
    "#388E3C": "Kakariki",
    "#689F38": "Kakariki marama",
    "#AFB42B": "Limo",
    "#FBC02D": "Kōwhai",
    "#FFA000": "Amipere",
    "#F57C00": "Karaka",
    "#E64A19": "Karaka kanapa",
    "#5D4037": "Paraone",
    "#616161": "Kerei",
    "#455A64": "Kerei Kahurangi",
    "#FFD700": "koura",
    "#C0C0C0": "Hiriwa",
    "#b76e79": "Roohi koura",
    "#383838": "Maama pango",
    "#FFFFFF": "Mā",
    "#FFF": "Mā",
    "#000000": "Pango",
    "#000": "Pango",
    "#7d263a": "Maroon",
    "#FD9F17": "Koura",
    "#229DBF": "Aqua",
    "#6DC9E2": "Aqua Triblend",
    "#413B2D": "Ope Taua",
    "#474747": "Uku",
    "#E6195C": "Beri",
    "#B2184C": "Berry Triblend",
    "#FC7F5F": "Karaka Tahu",
    "#80011F": "Katinara",
    "#382829": "tiakarete",
    "#F06336": "Kao",
    "#FAE7C9": "Kirīmi",
    "#6B2257": "Currant",
    "#222127": "Kerei pouri",
    "#0D5A74": "Tii Hohonu",
    "#00582F": "Evergreen",
    "#214C30": "Ngahere",
    "#DC2867": "Puhihia",
    "#38561": "Kelly",
    "#5C884D": "Rau",
    "#558450": "Aqua Maama",
    "#96B5C9": "Kahurangi Maama",
    "#DCAFCE": "Raina",
    "#D3E1A4": "kotakota",
    "#9DE7C2": "Mint",
    "#F6EAD2": "Taiao",
    "#1A1F35": "Navy",
    "#404624": "Oriwa",
    "#271020": "Paramu",
    "#A8355C": "Rahipere",
    "#D6BEA6": "Kirīmi ngohengohe",
    "#BEA994": "Tan",
    "#0DB2AE": "Tii",
    "#A86EA9": "Waiora",
    "#36454F": "Te waro",
    "#b3b0ab": "waro Kerei",
    "#463e3d": "Heatere waro",
    "#282d3c": "Blazer Navy"
  },
  "address_info": {
    "name": "Ingoa",
    "tel": "Waea",
    "email": "Īmēra",
    "country": "Whenua",
    "city": "Taone",
    "state": "State",
    "address": "wāhi noho",
    "building_number": "Te nama whare",
    "building_unit": "Waeine",
    "postcode": "Waehere poutāpeta",
    "note": "Tuhipoka",
    "county": "Kaute"
  },
  "product_types": {
    "physical": "Tinana",
    "physical_description": "Ko nga hua tinana penei i: waea pukoro, pukapuka, waahanga hiko.",
    "virtual": "Mariko",
    "virtual_description": "Nga hua pai-ipurangi penei: te kaari utu, te rahui hotera, te utu keemu.",
    "file": "Kōnae",
    "file_description": "Ko nga konae katoa e whakaaetia ana penei i te ataata akoranga ipurangi, nga tuhinga ka taea te tango.",
    "service": "Ratonga",
    "service_description": "Nga ratonga penei: whakatika, kawe waka, whakaako."
  },
  "license": {
    "free": "Kore utu",
    "startup": "Whakaoho",
    "company": "Kamupene",
    "enterprise": "hinonga"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "Tomana",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW",
    "GHS": "GHS",
    "ZWD": "ZWD",
    "IQD": "IQD",
    "SYP": "SYP"
  },
  "variants": {
    "color": "Tae",
    "volume": "Rahi",
    "count_in_pack": "Tatauhia i roto i te kete",
    "weight": "Taumaha",
    "type": "Rauemi",
    "style": "Kāhua"
  },
  "delivery_state": {
    "check_queue": "E tatari ana ki te arotake",
    "order_confirm": "Whakaaetanga Whakatau",
    "preparing_order": "Te whakarite",
    "sent_order": "I runga i te tuku",
    "to_customer": "Kua tukuna"
  },
  "status": {
    "unpaid": "Kare i utua",
    "paid": "Ka utua",
    "canceled": "Kua whakakorehia",
    "completed": "Kua tau",
    "reserved": "Kua rahuitia",
    "COD": "COD",
    "sold": "Kua hokona",
    "open": "Tuwhera",
    "cancel": "Kua whakakorehia",
    "active": "Hohe",
    "inactive": "hohekore",
    "debug": "Patuiro",
    "live": "Ora",
    "test": "Whakamatau",
    "connected": "Kua hono",
    "disconnected": "Momotuhia",
    "accept": "Whakaae",
    "reject": "Whakakahore",
    "pending": "Tarewa ana",
    "rejected": "Kua whakakorehia",
    "accepted": "Whakaaetia"
  },
  "dimensions": {
    "cm": "cm",
    "km": "km",
    "kg": "kg"
  },
  "transportation_type": {
    "motorbike": "Motopaika",
    "motorbike_description": "Taumaha i roto i etahi kiromita.",
    "cargo_small": "Uta iti",
    "cargo_small_description": "Uta mama maha kiromita.",
    "cargo": "utanga",
    "cargo_description": "Taumaha i roto i etahi kiromita.",
    "truck": "Taraka",
    "truck_description": "Uta nui, taumaha ranei i roto i te motu.",
    "fast_post": "Panui Tere",
    "fast_post_description": "Te tuku tere ma te tari poutapeta.",
    "post": "Pounga noa",
    "post_description": "Ka tuku i nga wa katoa ma te tari poutapeta.",
    "airplane": "Rererangi",
    "airplane_description": "Nga waka o roto, o tawahi, o te marama me te uta waenga.",
    "bicycle": "Ma te Tukua",
    "bicycle_description": "Nga uta mama, i roto i nga rau iari o nga waka kore-motor.",
    "global": "Te kawe waka o te ao",
    "global_description": "Te tuku ki tawahi ma te rangi, moana, whenua ranei.",
    "pickup": "Te tiki",
    "pickup_description": "Ka kohia e nga kaihoko nga taonga i to toa tinana, whare putunga ranei."
  },
  "article": {
    "login_to_see_error": "Takiuru ki te uru atu ki te tuhinga",
    "create_new_action": "Waihanga Ihirangi Hou",
    "menu_title": "Tahua",
    "menu": {
      "edit": "Whakatika aratau",
      "view_mode": "Tirohia te aratau",
      "delete": "Mukua Tuhinga"
    },
    "schedule_action": "Kei te pirangi koe ki te whakarite i te whakaputanga?",
    "schedule_title": "Whakaritea te whakaputa-aunoa",
    "edit_mode": "Whakatikatika",
    "public_view_mode": "Tirohanga a te iwi",
    "publish_at": "Whakaputa i",
    "published": "Whakaputaina",
    "draft": "Hukarere",
    "saving": "Tiaki",
    "save_and_publish_action": "Tiaki me te Whakaputa",
    "save_draft_action": "Tiaki tauira",
    "private": "Tūmataiti",
    "public": "Tūmatanui",
    "category_input": "Kāwai",
    "category_input_message": "Tīpakohia te kāwai tuhinga",
    "parent_input": "Te waahanga matua",
    "parent_input_message": "Tīpakohia te ihirangi papa",
    "schedule_input": "Hōtaka",
    "schedule_input_placeholder": "Mena kei te pirangi koe kia whakaputahia te korero i tetahi wa motuhake.",
    "schedule_view_action": "Tirohia te Apiti Whakaputa",
    "author_title": "I tuhia e",
    "read_time": "Te wa ako",
    "read_time_unit": "Nga meneti",
    "claps_action": "Pakipaki",
    "claps": "Pakipaki",
    "likes": "Pērā",
    "about_author": "Mo te kaituhi",
    "updated_at": "Kua whakahoutia",
    "wrote_at": "I tuhia ki",
    "now": "Inaianei",
    "follow_action": "Whaia",
    "followed": "Whaia",
    "report_and_delete_action": "Ripoata ka mukua tenei tuhinga",
    "report_action": "Pūrongo Tukino",
    "you_reported_this_article": "He rīpoata tūkino kē tā tēnei tuhinga.",
    "add_to_publication_action": "Tāpirihia ki te Whakaputa",
    "author_socials": "Kaituhi i runga i nga paapori pāpori",
    "share": "Tiria",
    "report_dialog": {
      "report_and_delete_title": "Pūrongo tūkino me te tango ihirangi",
      "report_title": "Ripoatatia tenei ihirangi he mahi kino",
      "message": "He aha te take mo te tuku i enei korero? Kōwhiria tētahi o ngā kōwhiringa e whai ake nei.",
      "accept_and_delete_action": "Whakaū me te Mukua Ihirangi"
    },
    "schedule_dialog": {
      "title": "Apiti Tuku Ihirangi",
      "publish_at": "Whakaputa i",
      "last_edit": "Whakatikanga whakamutunga",
      "view_action": "Tirohia Tuhinga"
    },
    "notifications": {
      "update_success_title": "Tukua nga korero",
      "update_success": "I momoho te whakahou tuhinga.",
      "update_error": "Ko nga korero kua whakauruhia kaore i te tika.",
      "delete_error": "Kaore e taea e koe te muku i tenei tuhinga!",
      "report_and_delete_success_title": "Pūrongo me te Mukua",
      "report_and_delete_success_message": "Kua pai te whakakore i te tuhinga.",
      "report_success_title": "Purongo tuhinga",
      "report_success_message": "Kua whakairihia to ripoata mo tenei tuhinga."
    },
    "alert": {
      "delete_article": {
        "title": "Mukua Tuhinga",
        "message": "Me muku tonu tenei tuhinga?",
        "action": "Mukua"
      }
    },
    "edit_window": {
      "title": "Tīpakohia te Kuputuhi Atahanga me te Whakarāpopototanga",
      "digest": "Whakarāpopototanga"
    },
    "editor": {
      "title_placeholder": "Taitara..",
      "body_placeholder": "Tuhia he ihirangi pai..",
      "accept_file_types_error": "Ko tenei whakatakotoranga konae kaore e whakaaetia:",
      "max_file_size_error": "He nui rawa tenei kōnae:",
      "notifications": {
        "image_uploaded_success": "I ora pai te atahanga",
        "image_uploaded_failed": "Hapa te uta atahanga."
      },
      "embed_placeholder": "Whakauruhia te waehere iframe, Facebook, Youtube, tetahi atu URL ranei ka peehia te tomo.",
      "embed_caption_placeholder": "Whakauruhia he taitara (he kōwhiringa)",
      "images_caption_placeholder": "Whakauruhia he taitara mo tenei ahua .."
    }
  },
  "article_report": {
    "inappropriate": "Ko nga korero o tenei tuhinga kaore i te tika.",
    "fake": "He rūpahu, he tinihanga hoki tenei.",
    "spam": "Ko tenei mea kua tukuna, kua kapea.",
    "scam": "Ka taea e tenei ka puta he malware, he huaketo, he tukinga punaha ranei.",
    "hacked": "Te ahua nei kua taumanutia tenei pae.",
    "offensive": "Ko te kiko o te reo me nga kupu kupu he kore tikanga me te whakaute.",
    "violent": "Ki taku whakaaro kei roto i tenei ihirangi nga whakaahua karekau, kei te takahi i nga ture.",
    "harassment": "Ki taku whakaaro he kaikiri tenei.",
    "hate": "Ki taku whakaaro he whakatairanga tenei i te tutu.",
    "infringe": "Ka takahi tenei i aku mana."
  },
  "comments": {
    "new_action": "Paatohia ki te waiho he korero ..",
    "title": "Nga korero",
    "body_placeholder": "To korero, korero ranei",
    "send_action": "Tuku korero",
    "body_is_empty_error": "Kei te waatea te korero!",
    "comments": "Nga korero",
    "no_comments": "Tuhia te korero tuatahi...",
    "load_more_action": "Tikina atu nga korero..",
    "cant_send_comment": "Kaore e taea e koe te taapiri i te panui hou.",
    "cant_remove_this_comment": "Kaore e taea e koe te muku i tenei korero!",
    "product_buyer": "Kaihoko",
    "delete_alert": {
      "title": "Mukua te korero",
      "message": "Me muku tenei korero?",
      "action": "Mukua"
    },
    "notifications": {
      "delete_success": "I tutuki pai to korero."
    },
    "first_send": "Panui tuatahi",
    "comment_at": "Kei runga",
    "edit_comment": "Whakatika Kōrero"
  },
  "customer_club": {
    "bronze": "Parahi",
    "silver": "Hiriwa",
    "gold": "koura",
    "platinum": "Platinum",
    "diamond": "Taimana"
  },
  "application_categories": {
    "tracking": "Takina Whanonga Kaiwhakamahi",
    "payment": "Utu",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "Te kawe waka",
    "automation": "Aunoatanga",
    "inventory": "Whare putunga",
    "accounting": "Kaute",
    "marketing": "Te hokohoko",
    "advertising": "Panuitanga",
    "staff": "Kaimahi",
    "incentive": "Nga whakatenatena",
    "shop": "Toa"
  },
  "social_network": {
    "instagram": "Instagram",
    "telegram": "Waeaea",
    "googleplay": "GooglePlay",
    "appstore": "Taupānga",
    "twitter": "Twitter",
    "linkedin": "Linkin",
    "medium": "Waenga",
    "selldone": "Seldone",
    "facebook": "Pukamata",
    "pinterest": "Pinterest",
    "whatsapp": "WhatsApp",
    "skype": "Skype",
    "facebook_messenger": "Pukamata Karere"
  },
  "form_builder": {
    "add_item_action": "Tāpiri tūemi hōu",
    "title_input": "Taitara",
    "name_input": "Ingoa taurangi",
    "value_input": "Uara",
    "value_input_message": "Rarangi Kōwhiringa Kaiwhakamahi",
    "default": "Uara taunoa",
    "types": {
      "simple": "Maamaa",
      "selective": "Whiriwhiri",
      "switch": "Whakawhiti",
      "file": "Kōnae",
      "number": "Tau"
    },
    "placeholder_input": "Kaipupuri",
    "file_type_input": "Momo kōnae e whakaaetia ana",
    "file_type_message": "jpeg, png, zip, ..."
  },
  "virtual_order_info_summery": {
    "title": "Ingoa Hua",
    "reserved_at": "Te Ra Rehitatanga",
    "total_price": "Tapeke moni",
    "discount": "Te utu",
    "final_price": "Te moni whakamutunga",
    "payment_status": "Te mana utu",
    "payment_status_waiting": "E tatari ana mo te utu",
    "payment_status_paid": "Ka utua",
    "buyer": "Kaihoko"
  },
  "virtual_item_info": {
    "title": "Tūemi Mariko",
    "outputs": {
      "title": "Nga Korero Putanga",
      "sub_title": "Nga Korero Matatapu o tenei mea",
      "message": "Ka whakaatuhia enei korero ki te kaiwhakamahi i muri i te hokonga o te hua."
    },
    "inputs": {
      "title": "Ko nga korero e hiahiatia ana",
      "sub_title": "E hiahiatia ana nga korero mo te kaihoko",
      "message": "Me whakauru e te kaihoko nga korero i tonoa i roto i te puka"
    },
    "notifications": {
      "inputs_set_success": "Kua rehita angitu te puka korero.",
      "confirm_by_admin_success": "Kua whakamanahia te whakaotinga ota.",
      "confirm_by_buyer_success": "Kua whakamanahia te whakaotinga ota."
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "Ko tenei ota kaore e whakaaetia e te utu COD.",
    "payment_returned": "Ka whakahokia mai te utu a te kaihoko.",
    "payment_fraud": "Ko te utu kua tohua he tinihanga.",
    "location_out_of_service": "Karekau te waahi o nga kaihoko.",
    "user_not_responding": "Kaore nga kaihoko i whakautu waea.",
    "shop_owner_fault": "I hapa nga kaimahi toa i te whakakī korero.",
    "lack_of_inventory": "Kua pau nga taonga.",
    "legal_restriction": "Kaore e taea te ota na runga i nga here ture.",
    "pricing_fault": "He he te utu na te kaihoko.",
    "system_fault": "Pūnaha bug."
  },
  "basket_order_info_summery": {
    "receiver": "Kaiwhiwhi",
    "phone": "Waea",
    "reserved_date": "Te ra hoko",
    "total_price": "Tapeke moni",
    "discount": "Te utu",
    "final_price": "Te moni whakamutunga",
    "address": "Wāhitau Tukunga",
    "payment_status": "Te mana utu"
  },
  "basket_status": {
    "open": "Tuwhera",
    "reserved": "Kua rahuitia",
    "paid": "Ka utua",
    "canceled": "Kua whakakorehia",
    "cod": "Utu I te Tukunga",
    "receipt_added": "Kua tapirihia te rihīti",
    "payment_processing": "Te tukatuka utu"
  },
  "basket_delivery_state": {
    "rejected": "Kua whakakorehia",
    "reject_reason_not_found": "Kaore i te mohiotia te take.",
    "step_1": "Arotake",
    "step_2": "Whakapumautanga",
    "step_3": "Whakaritenga",
    "step_4": "I runga i te tuku",
    "step_5": "Kua tukuna"
  },
  "basket_return_request_view": {
    "title": "Tono Whakahoki",
    "delivery_date": "Te ra tuku",
    "return_date": "Te ra tono",
    "items_count": "Tatau nga taonga i whakahokia",
    "items_count_unit": "(ng) tūemi",
    "reason": "Te take",
    "description": "Whakaahuatanga",
    "status": "Tūnga",
    "download_image": "Tikiake pikitia",
    "download_film": "Tikiake ataata",
    "download_voice": "Tikiake reo",
    "accept_by_admin_action": "Whakaaetia te tono",
    "reject_by_admin_action": "Whakakahoretia te tono",
    "message_for_admin": "E ai ki te whakaaetanga i whakaaetia e koe ma te whakamahi i te Seldone, me whakapa atu koe ki te kaihoko me te whakamohio ki a ia mo te tikanga whakahoki i tana ota. Me mahi tenei mena ka whakaaehia, ka whakakorehia ranei te tono, ka riro te whakaaetanga katoa a te kaihoko.",
    "notifications": {
      "update_status_success": "Tono mana kia whakahoutia."
    }
  },
  "basket_list": {
    "return_count": "Whakahoki: {count} tau",
    "table": {
      "row": "Rarangi",
      "image": "Whakaahua",
      "product_name": "Hua",
      "variant": "He rereke",
      "warranty": "Pūtāhui",
      "count": "Tatau",
      "price": "utu"
    }
  },
  "return_request_list": {
    "count": "Tau tohutoro",
    "return_warranty": "Moni Whakahoki Moni",
    "return_warranty_unit": "Ra(ng)",
    "table": {
      "code": "Waehere ota",
      "product": "Hua",
      "delivery_at": "Te ra i riro mai",
      "state": "Tūnga",
      "reason": "Te take",
      "return_warranty_period": "wā pūtāhui"
    }
  },
  "data_toolbar": {
    "search": "Rapu",
    "sort_by": "Kōmaka mā",
    "count_item": "Whakaaturia {item} tūemi"
  },
  "sort": {
    "created_at": "Waihangahia te ra",
    "updated_at": "Whakatikahia te ra",
    "title": "Taitara",
    "description": "Whakaahuatanga",
    "like": "Te rongonui",
    "power": "Pakipaki",
    "product_type": "Momo hua",
    "discount": "Te utu",
    "rate": "Whakatauranga",
    "rate_count": "Te maha o nga whakatauranga",
    "category": "Kāwai",
    "product": "Hua",
    "body": "Ihirangi",
    "card_type": "Momo kaari",
    "card_number": "Tau Kaari",
    "balance": "Taurite",
    "paid": "Te moni i pau",
    "currency": "Moni",
    "expire_at": "Te Ra Whakamutunga",
    "discount_code": "Waehere hekenga",
    "discount_percent": "Te utu",
    "discount_limit": "Tepe utu",
    "max_count": "Tatau mōrahi",
    "used_count": "Kua whakamahia",
    "start_date": "Te ra timata",
    "end_date": "Te ra mutunga",
    "total_discount_amount": "Tapeke utu",
    "initial_charge": "Te utu tuatahi",
    "total_count": "Tatau katoa",
    "amount_paid": "Te moni i utua",
    "name": "Ingoa",
    "published": "Whakaputaina",
    "visits": "Nga toronga",
    "color": "Tae",
    "landing_page": "Whārangi Taunga",
    "enable": "Whakahohe",
    "fix_commission": "Komihana pumau",
    "percent_commission": "Komihana ōrau",
    "payment_at": "Te ra utu",
    "issued_at": "Te ra tuku",
    "payment": "Utu",
    "website": "paetukutuku",
    "email": "Īmēra",
    "user": "kaiwhakamahi",
    "code": "Waehere",
    "schedule_at": "Rā whakahōtaka",
    "sender": "Kaituku",
    "in_que": "Kei te rarangi",
    "sent": "Tukuna",
    "shop": "Toa",
    "quantity": "Te nui",
    "amount": "Te nui",
    "jobs": "Ka tatau nga mahi",
    "success": "Tatau angitu",
    "fail": "Tatau rahua",
    "distance": "Tawhiti",
    "duration": "Roanga",
    "reset_at": "Tautuhihia te ra",
    "delivery_person": "Tangata",
    "delivery_service": "Ratonga",
    "date": "Rā",
    "order": "Ota",
    "order_id": "ID ota",
    "status": "Tūnga",
    "price": "utu",
    "count": "Tatau",
    "final_price": "Utu whakamutunga",
    "charge": "Te utu",
    "mention": "Whakahua",
    "officer": "Apiha",
    "registered": "Kua rehitatia",
    "purchased": "Kua hokona",
    "sex": "Ira tangata"
  },
  "search_box": {
    "result": "Nga hua rapu",
    "tips": "Rapu Hua me nga waahanga",
    "label": "Rapu ...",
    "category": "Kāwai"
  },
  "lead_status": {
    "physical_fast_delivery": "Tukunga inamata",
    "physical_under_24h_delivery": "Tukuna i roto i nga haora {lead} e whai ake nei",
    "physical_over_24h_delivery": "Te whakarite me te tuku mai i nga ra e whai ake nei",
    "virtual_fast_prepare": "Tukunga inamata",
    "virtual_under_24h": "Ka mahia i roto i nga haora {lead} e whai ake nei",
    "virtual_over_24h": "Ka mahia mai i nga ra e whai ake nei"
  },
  "return_request_state": {
    "pending": "Tarewa ana",
    "accepted": "Kua whakapumautia",
    "rejected": "Kua whakakorehia"
  },
  "return_order_reason": {
    "physical": {
      "U1": "He tauritenga hua",
      "U2": "Kaore he hua kei roto i te kete tuku",
      "U3": "Ko te kete, te pakaru ranei o nga hua",
      "U4": "Whakararuraru i te mokete, tau rangatū ranei",
      "U5": "Kei te ngaro etahi taonga mai i te peera",
      "U6": "Ko te hua ehara i te mea taketake",
      "U7": "Kaore te hua e tutuki i nga whakaritenga"
    }
  },
  "image_uploader": {
    "label": "Tōia & Whakataka, <u>Tīpakohia rānei te konae</u>",
    "max_size": "Rahi mōrahi e whakaaetia ana: {size}"
  },
  "timespan": {
    "Morning": "8am - 12pm",
    "Evening": "12 i te ahiahi ki te 6 i te ahiahi",
    "Night": "6pm-12pm",
    "Instant": "Panui Inamata"
  },
  "week_day": {
    "Saturday": "Rāhoroi",
    "Sunday": "Rātapu",
    "Monday": "Mane",
    "Tuesday": "Turei",
    "Wednesday": "Wenerei",
    "Thursday": "Rāpare",
    "Friday": "Paraire"
  },
  "payment_form": {
    "title": "Tīpakohia te tikanga utu",
    "gift_cards_input": "Kaari Koha",
    "gift_cards_input_empty": "Karekau he kaari koha i kitea..",
    "more": "Ētahi atu",
    "pay_amount_by_gift_cards": "Utu Kaari Utu",
    "select_payment_method": "Kōwhirihia to tikanga utu mai i nga whiringa e whai ake nei.",
    "payment_amount_remained": "Te toenga utu",
    "payment_amount": "Te moni i utua",
    "all_paid_by_gift_cards": "Tena koe, kaore koe e utu mo tenei ota. Pēhia te kī Utu Ma te Kāri Koha.",
    "pay_by_gift_cards_action": "Utu te ota me te kaari nama",
    "order_free_payment": "Tena koe, he kore utu to ota!",
    "order_free_payment_action": "Ota Koreutu Inaianei",
    "qr": {
      "address": "Wāhitau utu",
      "amount": "Te nui"
    }
  },
  "discount_input": {
    "limit": "{percent}% hekenga ki te {limit} {currency}",
    "action": "Tāpiri Waehere hekenga",
    "code_input": "Waehere hekenga",
    "notifications": {
      "add_success": "Kia ora, waehere utu whaimana."
    }
  },
  "gift_card": {
    "inactive": "Kua monoa te kaari",
    "expire": "Whakamutunga",
    "transfer": "Whakawhiti",
    "send_to_friend": "Tukuna ki te hoa"
  },
  "count_down": {
    "days": "Ra",
    "hours": "Haora",
    "minutes": "Nga meneti",
    "seconds": "Hekona"
  },
  "gift_status": {
    "Unpaid": "Tatari Rihitiwhi",
    "Paid": "Ka utua",
    "Rejected": "Kua whakakorehia",
    "Canceled": "Kua whakakorehia"
  },
  "gift_program_status": {
    "Airdrop": "Pūnaha Utu",
    "Advertising": "Panuitanga",
    "PersonalGift": "Koha Whaiaro",
    "ShopGift": "Toa Taonga"
  },
  "currency_selector": {
    "label": "Moni"
  },
  "need_login": {
    "title": "takiuru",
    "login_sms": "Takiuru SMS",
    "login_google": "Takiuru me Google",
    "login_facebook": "Takiuru me Facebook",
    "login_account": "Takiuru na Seldone",
    "register": "Kaiwhakamahi hou? Rēhita ināianei.",
    "mobile_input": "Whakauruhia to waea pūkoro",
    "verification_code": "Waehere manatoko",
    "msg_title": "Kia ora,",
    "msg_body": "Takiuru koa. He hēkona noa iho.",
    "login_apple": "Takiuru me Apple"
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "5 Tau Toa Koura"
    },
    "GOLDEN_2YEAR": {
      "name": "4 Tau Toa Koura"
    },
    "GOLDEN_3YEAR": {
      "name": "3 Tau Toa Koura"
    },
    "GOLDEN_4YEAR": {
      "name": "2 Tau Toa Koura"
    },
    "GOLDEN_5YEAR": {
      "name": "1 Tau Toa Koura"
    },
    "TOKEN_OWNER_1M": {
      "name": "Kaipupuri koura"
    },
    "TOKEN_OWNER_10M": {
      "name": "Taimana Investor"
    },
    "TOKEN_OWNER_100M": {
      "name": "Ruby Investor"
    },
    "COMMUNITY_LOYAL": {
      "name": "He mema o te Hapori Nui o nga Whatunga Whakawhitiwhiti"
    },
    "GOLD_SUPPLIER": {
      "name": "Kaiwhakarato koura"
    },
    "GOLD_SELLER": {
      "name": "Kaihokohoko koura"
    },
    "CONTENT_SUPERMAN": {
      "name": "Kaihanga Ihirangi Runga Rawa"
    },
    "NINJA": {
      "name": "Ninja"
    },
    "STAR": {
      "name": "Whetu"
    },
    "GUARDIAN": {
      "name": "Ratonga Kiritaki Nui"
    },
    "KING": {
      "name": "Kingi o te Maakete"
    }
  },
  "cookie": {
    "title": "Ka whakamahia e tenei paetukutuku nga pihikete",
    "message": "Ka whakamahia e tenei paetukutuku nga pihikete hei whakapai ake i te wheako kaiwhakamahi. Ma te whakamahi i to maatau paetukutuku ka whakaae koe ki nga pihikete katoa i runga i ta maatau Kaupapahere Pihikete.",
    "preferences_action": "Whakahaere Manakohanga",
    "agree_action": "E whakaae ana ahau"
  },
  "basket_item_message": {
    "title": "Nga korero e hiahiatia ana mo tenei mea",
    "save_actions": "Tiaki Karere",
    "notifications": {
      "success": "Kua tiakina to raraunga whakauru."
    }
  },
  "faq": {
    "faq": "Pātai Auau",
    "title": "Nga Patapatai me nga Whakautu",
    "sub_title": "Ko ta koe i tono mai kia mahia e matou.",
    "message": "Rapua te whakautu ki to patai i waenga i nga whakautu kei raro nei. Patai mai mena kare tonu nga patai i whakautu.",
    "add_question_action": "Patai Hou",
    "read_more": "Pānuitia atu..",
    "load_more": "Ētahi atu pātai..",
    "main_page": "FAQ Whārangi Matua",
    "add_new": "Tukuna he patai hou",
    "login_alert": "Takiuru ki te patai i tetahi patai.",
    "question_input": "Pātai",
    "question_input_placeholder": "Uia to patai.",
    "notifications": {
      "success_add": "I tutuki pai to patai."
    }
  },
  "rating_labels": [
    "Tino kino",
    "kino",
    "Pūnoa",
    "Pai",
    "Tino pai"
  ],
  "map_view": {
    "address_detail": "Nga korero mo te wahitau",
    "change": "Hurihia",
    "select": "Tīpakohia",
    "not_found_address": "Karekau he uara i kitea",
    "enter_address_hint": "Tāuru wāhitau ūnga",
    "enter_your_address": "Whakauruhia to wahitau.",
    "postal_code": "Waehere poutāpeta",
    "phone_input": "Waea {type}",
    "building_number": "Te nama whare",
    "building_unit": "Waeine",
    "full_name_input": "Ingoa katoa {type}",
    "save_detail_action": "Tiakina nga korero",
    "more_detail_input": "Whakaahuatanga atu",
    "add_address_to_list": "Tāpiri wāhitau ki te rārangi",
    "address_title_input": "Tapanga Wāhitau (Hiahia)",
    "notifications": {
      "save_in_list": "Kua tiakina tenei wahitau ki to rarangi ingoa me ona korero katoa.",
      "edit_success": "Ko nga uara wahitau hou kua tiakina ki {title}."
    },
    "delete_address_dialog": {
      "title": "Muku Wāhitau",
      "message": "Kei te tino hiahia koe ki te muku i tenei wahitau?",
      "action": "Tango wāhitau"
    }
  },
  "comment_manager": {
    "can_not_edit": "Kaore e taea te whakatika i tenei korero!",
    "comment_input_empty": "Kei te waatea te kupu karere!",
    "article_not_saved": "Tiakina te tuhinga!"
  },
  "wheel_fortune": {
    "title": "Play & Win",
    "message": "Ko te utu mo ia keemu he 10 maramara. Kei a koe he maramara {chips} inaianei. Tikina atu maramara ma te hoko mai i te toa.",
    "win_message": "Kia ora, Ka toa koe!",
    "lost_message": "Aroha mai, kua ngaro koe i te keemu.",
    "try_again": "Ka taea e koe te ngana ano"
  },
  "json": {
    "add": "Tāpirihia nga raraunga hanganga",
    "add_message": "Waihangahia nga raraunga hanganga hou",
    "structures": "Hanganga",
    "book": {
      "title": "Pukapuka",
      "desc": "Nga mahi pukapuka ka taea e nga kaiwhakamahi te hoko pukapuka ka kitea tika mai i nga hua Rapu."
    },
    "occupation": {
      "title": "Te utu utu",
      "desc": "Ko nga korero mo te whakatau tata utu, penei i nga awhe utu me nga tauwaenga utu-a-rohe mo nga momo mahi, ka whakaatuhia i roto i te wheako rapu mahi i runga i a Google."
    },
    "course": {
      "title": "Akoranga",
      "desc": "Ko nga akoranga ako ka puta i roto i te rarangi kaiwhakarato-motuhake. Ka taea e nga akoranga te whakauru i te taitara akoranga, te kaiwhakarato, me te whakaahuatanga poto."
    },
    "howto": {
      "title": "Me pehea",
      "desc": "He Me pehea te hikoi i nga kaiwhakamahi i roto i te huinga o nga hikoinga ki te whakaoti angitu i tetahi mahi, e whakaatu ana i nga ataata, nga whakaahua, me nga tuhinga."
    },
    "recipe": {
      "title": "Recipe",
      "desc": "Ko nga tohutao e whakaatu ana he hua whai hua takitahi, he waahanga ranei o te carousel manaaki."
    }
  },
  "support": {
    "Financial": "Pūtea",
    "Technical": "Hangarau",
    "Advisor": "Kaitohutohu"
  },
  "condition": {
    "new": "Hou",
    "refurbished": "Kua whakahoutia",
    "used": "Kua whakamahia",
    "used_fair": "I whakamahia tika",
    "used_good": "I whakamahia pai",
    "used_like_new": "I whakamahia ano he hou"
  },
  "variant_filter": {
    "title": "Tātari Rerekē Hua",
    "only_available": "Kei roto i nga taonga"
  },
  "service": {
    "task": {
      "title": "Nga Mahi",
      "message": "Rarangi o nga mahi i mahia i tenei ratonga."
    },
    "appointment": {
      "title": "Whakaritenga",
      "message": "Whiriwhiria nga wa o te wiki mai i nga wa e whai ake nei i runga i te ra me te haora e tika ana mo koe."
    },
    "booking": {
      "title": "Rahui",
      "message": "Tauwhāitihia te wa o nga ra e hiahia ana koe ki te rahui ki te maramataka kei raro nei."
    },
    "subscription": {
      "title": "Ohaurunga"
    },
    "charge": {
      "title": "Te utu"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "Utu tuturu",
      "message": "I roto i tenei momo utu, ko te utu o te hua he moni tuturu, kaore he hiahia mo te kaihoko ki te tono i te tatauranga utu."
    },
    "ESTIMATION": {
      "title": "Utu Whakatau",
      "message": "Ko te utu o nga hua me nga ratonga ka tatauhia e te kaihoko i te wa e ota ana, ka taea te whakarereke, te taapiri ranei i nga nama utu i te wa o te ratonga."
    },
    "AGREEMENT": {
      "title": "Utu Whakaaetanga",
      "message": "Ko te utu whakamutunga o nga hua, ratonga ranei e kore e whakarereketia e te kaihoko i muri i te tukunga o te ota."
    },
    "BID": {
      "title": "Tono / Auction",
      "message": "Ka hokona te hua ki te utu utu nui rawa atu e nga kaihoko pea."
    }
  },
  "map": {
    "title": "Te tauranga ki te whiwhi hua",
    "confirm": "Tautuhia te waahi",
    "address": "tauranga",
    "receptor": "Kaiwhiwhi"
  },
  "ShopBots": {
    "telegram": "Waeaea"
  },
  "article_tags": {
    "title": "Tohu Ihirangi",
    "tags_input": "Tohutohu",
    "tags_input_message": "Nga Tohu Rarangi o tenei tuhinga",
    "notification": {
      "add_success": "Kua taapirihia nga tohu"
    }
  },
  "difficulties": {
    "very_complicated": "Tino uaua",
    "hard": "pakeke",
    "intermediate": "Takawaenga",
    "easy": "Māmā"
  }
};