export default {
  "currency_default": "USD",
  "language_default": "en",
  "selldone": "ସେଲଡୋନ୍ |",
  "store": "ଷ୍ଟୋର୍‌ କରନ୍ତୁ |",
  "not_exist": "ବିଦ୍ୟମାନ ନାହିଁ |",
  "error": "ତ୍ରୁଟି |",
  "active": "ସକ୍ରିୟ |",
  "inactive": "ନିଷ୍କ୍ରିୟ |",
  "required_value": "ଆବଶ୍ୟକ ମୂଲ୍ୟଗୁଡ଼ିକ |",
  "original_warranty": "ମୂଳ ଉତ୍ପାଦ ଗ୍ୟାରେଣ୍ଟି |",
  "return_warranty_days": "{days} ଫେରସ୍ତ ଗ୍ୟାରେଣ୍ଟି ଦିନ (ଗୁଡିକ)",
  "no_return_warranty": "କ return ଣସି ଫେରସ୍ତ ନାହିଁ |",
  "reed_agree_terms": "ମୁଁ ବ୍ୟବହାରର ସର୍ତ୍ତାବଳୀ ଏବଂ ଗୋପନୀୟତା ନୀତି ପ read ିଛି ଏବଂ ସେମାନଙ୍କ ସହ ସହମତ |",
  "commons": {
    "Currency": "ମୁଦ୍ରା",
    "COD": "COD",
    "State": "ରାଜ୍ୟ",
    "Price": "ମୂଲ୍ୟ",
    "order_price": "ଅର୍ଡର ପରିମାଣ",
    "VAT": "VAT",
    "Discount": "ରିହାତି",
    "In_Stock": "ମହଜୁଦ ଅଛି",
    "Variants": "ପ୍ରକାରଗୁଡିକ |",
    "No_variants": "କ varia ଣସି ପ୍ରକାର ନାହିଁ |",
    "all": "ସମସ୍ତ",
    "today": "ଆଜି |",
    "yesterday": "ଗତକାଲି",
    "license": "ଲାଇସେନ୍ସ |",
    "home": "ଘର",
    "support": "ସମର୍ଥନ",
    "messages": "ବାର୍ତ୍ତାଗୁଡିକ",
    "no_message": "କ No ଣସି ବାର୍ତ୍ତା ନାହିଁ |",
    "empty": "ଖାଲି",
    "phone": "ଫୋନ୍ |",
    "address": "ଠିକଣା",
    "name": "ନାମ",
    "password": "ପାସୱାର୍ଡ",
    "email": "ଇମେଲ୍ କରନ୍ତୁ |",
    "mobile": "ମୋବାଇଲ୍ |",
    "login": "ଭିତରକୁ ଯାଉ",
    "register": "ପଞ୍ଜିକରଣ କର |",
    "select_account": "ଖାତା ଚୟନ କରନ୍ତୁ |",
    "online": "ଅନଲାଇନ୍ |",
    "offline": "ଅଫଲାଇନ୍ |",
    "finish": "ସମାପ୍ତ",
    "finished": "ସମାପ୍ତ",
    "preview": "ପୂର୍ବାବଲୋକନ",
    "free": "ମାଗଣା |",
    "free_completely": "ସଂପୂର୍ଣ୍ଣ ମାଗଣା ସଦସ୍ୟତା |",
    "fee": "ଦେୟ",
    "month": "ମାସ",
    "months": "ମାସଗୁଡିକ",
    "faq": "ପ୍ରାୟତଃ ପଚରାଯାଇଥିବା ପ୍ରଶ୍ନ",
    "question": "ପ୍ରଶ୍ନ |",
    "answer": "ଉତ୍ତର",
    "create_date": "ତାରିଖ ସୃଷ୍ଟି କରନ୍ତୁ |",
    "update_date": "ତାରିଖ ଅଦ୍ୟତନ କରନ୍ତୁ |",
    "start_date": "ଆରମ୍ଭ ତାରିଖ",
    "end_date": "ଶେଷ ତାରିଖ",
    "social": "ସାମାଜିକ |",
    "total": "ସମୁଦାୟ",
    "orders": "ଆଦେଶ",
    "sessions": "ଅଧିବେଶନ",
    "product_views": "ଉତ୍ପାଦ ଦୃଶ୍ୟ |",
    "add_to_carts": "କାର୍ଟରେ ଯୋଡନ୍ତୁ |",
    "checkouts": "ଚେକଆଉଟ୍ |",
    "payments": "ଦେୟ",
    "organic_search": "ଜ Organ ବିକ ସନ୍ଧାନ |",
    "other": "ଅନ୍ୟମାନେ |",
    "landing_page": "ଅବତରଣ ପୃଷ୍ଠା |",
    "discount_code": "ରିହାତି କୋଡ୍ |",
    "total_sell": "ମୋଟ ବିକ୍ରୟ |",
    "details": "ବିବରଣୀଗୁଡିକ",
    "currency": "ମୁଦ୍ରା",
    "amount": "ପରିମାଣ",
    "published": "ପ୍ରକାଶିତ |",
    "draft": "ଡ୍ରାଫ୍ଟ",
    "save_changes": "ପରିବର୍ତ୍ତନଗୁଡିକ ସଞ୍ଚୟ କରନ୍ତୁ |",
    "source": "ଉତ୍ସ",
    "medium": "ମଧ୍ୟମ",
    "url": "Url",
    "revenue": "ରାଜସ୍ୱ",
    "performance": "ପ୍ରଦର୍ଶନ",
    "term": "ଅବଧି",
    "content": "ବିଷୟବସ୍ତୁ",
    "session": "ଅଧିବେଶନ",
    "product": "ଉତ୍ପାଦ",
    "add": "ଯୋଡନ୍ତୁ |",
    "checkout": "ଚେକଆଉଟ୍ |",
    "payment": "ଦେୟ",
    "more_options": "ଅଧିକ ବିକଳ୍ପ |",
    "full_name": "ପୁରା ନାମ",
    "tel": "ଟେଲ",
    "about_me": "ମୋ ବିସୟରେ",
    "request_checking": "ଯାଞ୍ଚ ପାଇଁ ଅନୁରୋଧ |",
    "passport": "ପାସପୋର୍ଟ",
    "birthday": "ଜନ୍ମଦିନ",
    "country": "ଦେଶ",
    "city": "ସହର",
    "gender": "ଲିଙ୍ଗ",
    "offer": "ଅଫର୍",
    "website": "ୱେବସାଇଟ୍",
    "apply_for_all_products": "All ସମସ୍ତ ଉତ୍ପାଦ ପାଇଁ ଆବେଦନ କରନ୍ତୁ |",
    "fix_commission": "ସ୍ଥିର ଆୟୋଗ |",
    "percent_commission": "ଶତ ପ୍ରତିଶତ କମିଶନ |",
    "fixed_discount": "ସ୍ଥିର ରିହାତି |",
    "discount_percentage": "ଶତକଡ଼ା ରିହାତି",
    "discount_limit": "ରିହାତି ସୀମା |",
    "no_code": "କ code ଣସି କୋଡ୍ ନାହିଁ |",
    "max_count": "ସର୍ବାଧିକ ଗଣନା",
    "count_unit": "ବସ୍ତୁଗୁଡ଼ିକ",
    "used": "ବ୍ୟବହୃତ |",
    "daily": "ଦ Daily ନିକ |",
    "monthly": "ମାସିକ",
    "yearly": "ବାର୍ଷିକ",
    "state": "ସ୍ଥିତି",
    "disable": "ଅକ୍ଷମ କରନ୍ତୁ |",
    "enable": "ସକ୍ଷମ କରନ୍ତୁ |",
    "activation_code": "ଆକ୍ଟିଭେସନ୍ କୋଡ୍ |",
    "quantity": "ପରିମାଣ",
    "no_club": "କ club ଣସି କ୍ଲବ୍ ନାହିଁ |",
    "per_order": "କ୍ରମାଙ୍କରେ |",
    "count": "ଗଣନା କର |",
    "seconds": "ସେକେଣ୍ଡ୍ |",
    "auto": "ଅଟୋ |",
    "title": "ଆଖ୍ୟା",
    "message": "ବାର୍ତ୍ତା",
    "width": "ମୋଟେଇ",
    "length": "ଦ Length ର୍ଘ୍ୟ",
    "height": "ଉଚ୍ଚତା",
    "label": "ଲେବଲ୍ |",
    "click": "କ୍ଲିକ୍ କରନ୍ତୁ |",
    "bank": "ବ୍ୟାଙ୍କ",
    "default": "ଡିଫଲ୍ଟ |",
    "role": "ଭୂମିକା",
    "user": "ଉପଯୋଗକର୍ତ୍ତା |",
    "users": "ଉପଯୋଗକର୍ତ୍ତାଗଣ |",
    "code": "କୋଡ୍",
    "total_payment": "ମୋଟ ଦେୟ",
    "balance": "ସନ୍ତୁଳନ",
    "chance": "ସମ୍ଭାବନା |",
    "free_for_new_users": "ନୂତନ ବ୍ୟବହାରକାରୀଙ୍କ ପାଇଁ ମାଗଣା |",
    "prize_amount": "ପୁରସ୍କାର ରାଶି",
    "win": "ଜିତନ୍ତୁ |",
    "gift_card": "ଉପହାର କାର୍ଡ |",
    "discount": "ରିହାତି",
    "config": "ବିନ୍ୟାସ କରନ୍ତୁ |",
    "prize": "ପୁରସ୍କାର",
    "Prizes": "ପୁରସ୍କାର",
    "result": "ଫଳାଫଳ",
    "price": "ମୂଲ୍ୟ",
    "lottery": "ଲଟେରୀ",
    "coupon": "କୁପନ୍ |",
    "customer_club": "ଗ୍ରାହକ କ୍ଲବ୍ |",
    "shipping": "ପରିବହନ",
    "sum": "ସମ",
    "not_paid": "ଦେୟ ଦିଆଯାଇନାହିଁ |",
    "category": "ବର୍ଗ",
    "done": "ସମାପ୍ତ ହେଲା |",
    "email_from": "ଠାରୁ",
    "subject": "ବିଷୟ",
    "schedule": "କାର୍ଯ୍ୟସୂଚୀ",
    "files_list": "ଫାଇଲ ତାଲିକା |",
    "file_max_size": "ସର୍ବାଧିକ ଫାଇଲ୍ ଆକାର |",
    "value": "ମୂଲ୍ୟ",
    "help": "ସାହାଯ୍ୟ",
    "shipping_tax": "ସିପିଂ ଟ୍ୟାକ୍ସ |",
    "net_price": "ନିଟ୍ ମୂଲ୍ୟ |",
    "tax": "କର",
    "tax_included": "ମୂଲ୍ୟରେ ଅନ୍ତର୍ଭୁକ୍ତ |",
    "limit": "ସୀମା",
    "min_purchase": "ସର୍ବନିମ୍ନ କ୍ରୟ |",
    "eligible_for": "ପାଇଁ ଯୋଗ୍ୟ",
    "only_for_first_buy": "କେବଳ ପ୍ରଥମ କ୍ରୟ ପାଇଁ |",
    "one_time_use": "ଗୋଟିଏ ଥର ବ୍ୟବହାର କରିପାରିବେ |",
    "period_of_qualify": "ଅବଧି ବ୍ୟବହାର ସୀମା |",
    "no_constraint": "କ limit ଣସି ସୀମା ନାହିଁ |",
    "timespan": "ସମୟ ଅବଧି",
    "days": "ଦିନ (ଗୁଡିକ)",
    "weight": "ଓଜନ",
    "distance": "ଦୂରତା |",
    "last_status": "ଶେଷ ସ୍ଥିତି |",
    "issued_at": "ରେ ପ୍ରଦାନ କରାଯାଇଛି",
    "order": "ଅର୍ଡର |",
    "order_detail": "ସବିଶେଷ ବିବରଣୀ ଅର୍ଡର କରନ୍ତୁ |",
    "percent": "ଶତକଡା",
    "applied_count": "ପ୍ରୟୋଗ ଗଣନା |",
    "campaign": "ଅଭିଯାନ |",
    "os": "ପରିଚାଳନା ପ୍ରଣାଳୀ",
    "browser": "ବ୍ରାଉଜର୍",
    "device": "ଉପକରଣ",
    "device_ip": "ଉପକରଣ IP ଠିକଣା",
    "location": "ଅବସ୍ଥାନ",
    "user_agent": "ବ୍ୟବହାରକାରୀ ଏଜେଣ୍ଟ |",
    "affiliate": "ଅନୁବନ୍ଧିତ",
    "timeline": "ସମୟସୀମା",
    "add_note": "ଟିପ୍ପଣୀ ଯୋଡନ୍ତୁ |",
    "record": "ରେକର୍ଡ କରନ୍ତୁ |",
    "unlimited": "ଅସୀମିତ |",
    "show_coupons": "କୁପନ୍ ଦେଖାନ୍ତୁ |",
    "hide_coupons": "କୁପନ୍ ଲୁଚାନ୍ତୁ |",
    "service_area": "ସେବା କ୍ଷେତ୍ର",
    "apps": "ଆପ୍ସ",
    "plugins": "ପ୍ଲଗଇନ୍ |",
    "bots": "ବୋଟ୍",
    "categories": "ବର୍ଗଗୁଡିକ",
    "products": "ଉତ୍ପାଦଗୁଡିକ",
    "business": "ବ୍ୟବସାୟ",
    "personal": "ବ୍ୟକ୍ତିଗତ",
    "size": "ଆକାର |",
    "holiday": "ଛୁଟିଦିନ",
    "sod": "ବିତରଣରେ ଦେୟ ଦିଅ |",
    "cod": "ବିତରଣରେ ନଗଦ",
    "free_shipping": "ମାଗଣା ପରିବହନ ଖର୍ଚ୍ଚ",
    "hours": "ଘଣ୍ଟା",
    "send_date": "ପଠାଇବା ତାରିଖ |",
    "deliver_date": "ପ୍ରସବ ତାରିଖ୍",
    "return_date": "ଫେରସ୍ତ ତାରିଖ",
    "pending": "ବିଚାରାଧୀନ ଅଛି |",
    "delivered": "ବିତରଣ କରାଯାଇଛି",
    "returned": "ପ୍ରତ୍ୟାବର୍ତ୍ତନ",
    "canceled": "ବାତିଲ",
    "shipping_cost": "ପଠାଇବା ଖର୍ଚ",
    "action": "କାର୍ଯ୍ୟ",
    "cancel_date": "ତାରିଖ ବାତିଲ୍ କରନ୍ତୁ |",
    "deliver_in_process": "ଅର୍ଡର ପଠାଯାଇଛି ..",
    "kind": "ଟାଇପ୍ କରନ୍ତୁ |",
    "detail": "ବିବରଣୀଗୁଡିକ",
    "map": "ମାନଚିତ୍ର",
    "actions": "କ୍ରିୟା",
    "navigation": "ନାଭିଗେସନ୍",
    "navigation_app": "ପ୍ରୟୋଗ",
    "payment_date": "ଦେୟ ତାରିଖ",
    "duration": "ଅବଧି",
    "bill": "ବିଲ୍ |",
    "delivery_persons": "କ୍ୟୁରିଅର୍ |",
    "delivery_services": "ବିତରଣ ସେବା",
    "live_view": "ଲାଇଭ୍ ଭ୍ୟୁ |",
    "cart": "କାର୍ଟ",
    "priority": "ପ୍ରାଥମିକତା",
    "sufficient_credit": "ପର୍ଯ୍ୟାପ୍ତ କ୍ରେଡିଟ୍ |",
    "max_package_size": "ସର୍ବାଧିକ ପ୍ୟାକେଜ୍ ଆକାର |",
    "delay": "ବିଳମ୍ବ",
    "credit": "କ୍ରେଡିଟ୍",
    "livemode": "ଲାଇଭ୍ |",
    "paused": "ବିରତ |",
    "debug": "ତ୍ରୁଟିନିବାରଣ",
    "token": "ଟୋକେନ୍ |",
    "status": "ସ୍ଥିତି",
    "courier": "କ୍ୟୁରିଅର୍ |",
    "track": "ଟ୍ରାକ୍ କରନ୍ତୁ |",
    "track_order": "ଟ୍ରାକିଂ ଅର୍ଡର |",
    "cost": "ମୂଲ୍ୟ",
    "receipt": "ରସିଦ",
    "origin": "ଉତ୍ପତ୍ତି",
    "destination": "ଗନ୍ତବ୍ୟସ୍ଥଳ",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "ପର୍ଯ୍ୟାପ୍ତ ଷ୍ଟକ୍ ନୁହେଁ!",
    "sub_total": "ସବଟୋଟାଲ୍ |",
    "customer": "ଗ୍ରାହକ",
    "delivery": "ବିତରଣ",
    "online_orders": "ଅନଲାଇନ୍ ଅର୍ଡର |",
    "pos_orders": "POS ଆଦେଶ |",
    "chips": "ଚିପ୍ସ |",
    "subscribed": "ସଦସ୍ୟତା",
    "unsubscribed": "ସଦସ୍ୟତା",
    "last_login": "ଶେଷ ଲଗଇନ୍ |",
    "join_at": "ତାରିଖରେ ଯୋଗ ଦିଅନ୍ତୁ |",
    "club": "କ୍ଲବ୍",
    "buyer": "କ୍ରେତା",
    "seller": "ବିକ୍ରେତା",
    "or": "କିମ୍ବା",
    "type": "ଟାଇପ୍ କରନ୍ତୁ |",
    "condition": "ଅବସ୍ଥା",
    "brand": "ବ୍ରାଣ୍ଡ",
    "attempt": "ଚେଷ୍ଟା",
    "error": "ତ୍ରୁଟି |",
    "success": "ସଫଳତା |",
    "fail": "ବିଫଳ",
    "inventory": "ଭଣ୍ଡାର",
    "link": "ଲିଙ୍କ୍ |",
    "visits": "ପରିଦର୍ଶନ |",
    "transactions": "କାରବାର",
    "vat": "VAT",
    "pos_vat": "POS ଭ୍ୟାଟ୍ |",
    "sort_by": "ଦ୍ୱାରା ସର୍ଟ କରନ୍ତୁ ..",
    "from": "ଠାରୁ",
    "from_lead_time": "ପରବର୍ତ୍ତୀ {hours} ଘଣ୍ଟା ମଧ୍ୟରେ |",
    "no_credit_card_info": "କ Card ଣସି କାର୍ଡ ସୂଚନା ନାହିଁ!",
    "active": "ସକ୍ରିୟ |",
    "not_active": "ସକ୍ରିୟ ନୁହେଁ!",
    "referrals": "ରେଫରାଲ୍ |",
    "dashboard": "ଡ୍ୟାସବୋର୍ଡ |",
    "more": "ଅଧିକ",
    "inactive": "ନିଷ୍କ୍ରିୟ |",
    "developer": "ବିକାଶକାରୀ",
    "setting": "ସେଟିଂ",
    "membership_conditions": "ସଦସ୍ୟତା ସର୍ତ୍ତ |",
    "customers": "ଗ୍ରାହକ",
    "created_at": "ସୃଷ୍ଟି ତାରିଖ |",
    "updated_at": "ଶେଷ ଅଦ୍ୟତନ |",
    "register_at": "ପଞ୍ଜିକରଣ ତାରିଖ |",
    "old": "ପୁରୁଣା",
    "new": "ନୂତନ",
    "start": "ଆରମ୍ଭ କରନ୍ତୁ |",
    "end": "ଶେଷ",
    "pos": "POS",
    "out_of_stock": "ଷ୍ଟକ୍ ସେଶ",
    "fake": "ନକଲି",
    "low_inventory_warning": "ଧ୍ୟାନ, ନିମ୍ନ ଭଣ୍ଡାର!",
    "webhook": "ୱେବ୍ ହକ୍ |",
    "notification": "ବିଜ୍ଞପ୍ତି",
    "sms": "SMS",
    "online_payment_link": "ଅନଲାଇନ୍ ପେମେଣ୍ଟ ଲିଙ୍କ୍ |",
    "waiting_load_data": "ଡାଟା ଲୋଡ୍ କରିବାକୁ ଅପେକ୍ଷା ..",
    "views": "ଦର୍ଶନ",
    "sales": "ବିକ୍ରୟ",
    "total_views": "ସମୁଦାୟ ଦୃଶ୍ୟ |",
    "total_sales": "ମୋଟ ବିକ୍ରୟ |",
    "from_previous_n_days": "ଶେଷ {days} ଦିନରୁ |",
    "drop_shipping": "ଡ୍ରପ୍ସିପିଙ୍ଗ୍ |",
    "commission": "ଆୟୋଗ",
    "shipping_area": "ପରିବହନ କ୍ଷେତ୍ର",
    "main_seller": "ମୁଖ୍ୟ ବିକ୍ରେତା |",
    "domain": "ଡୋମେନ୍",
    "contact": "ଯୋଗାଯୋଗ ସୂଚନା",
    "wallet": "ୱାଲେଟ୍ |",
    "reseller": "ପୁନ eller ବିକ୍ରେତା |",
    "tracking_code": "ଟ୍ରାକିଂ କୋଡ୍",
    "tracking_url": "ଟ୍ରାକିଂ URL",
    "fulfillments": "ପୂର୍ଣ୍ଣତା",
    "reject": "ପ୍ରତ୍ୟାଖ୍ୟାନ କରନ୍ତୁ |",
    "reserved": "ସଂରକ୍ଷିତ",
    "score": "ସ୍କୋର |",
    "customer_price": "ଗ୍ରାହକଙ୍କ ମୂଲ୍ୟ",
    "options": "ବିକଳ୍ପଗୁଡ଼ିକ",
    "show_details": "ବିବରଣୀ ଦେଖାନ୍ତୁ |",
    "no_data": "କ data ଣସି ତଥ୍ୟ ନାହିଁ ..",
    "waiting": "ଅପେକ୍ଷା ...",
    "waiting_connecting_payment": "ଦେୟ ସେବାକୁ ଅପେକ୍ଷା ...",
    "creating_secure_payment": "ସୁରକ୍ଷିତ ଦେୟ ସୃଷ୍ଟି କରିବା |",
    "officer": "ଅଧିକାରୀ",
    "ticket": "ଟିକେଟ୍",
    "ticket_url": "ଟିକେଟ୍ url",
    "closed_at": "ବନ୍ଦ",
    "close_ticket": "ଟିକେଟ୍ ବନ୍ଦ କରନ୍ତୁ |",
    "reopen_ticket": "ଟିକେଟ୍ ଖୋଲନ୍ତୁ |",
    "require": "ଆବଶ୍ୟକ *",
    "search": "ସନ୍ଧାନ ...",
    "language": "ଭାଷା",
    "tasks": "କାର୍ଯ୍ୟଗୁଡ଼ିକ",
    "permissions": "ଅନୁମତିଗୁଡିକ",
    "finish_date": "ଶେଷ ତାରିଖ",
    "complete_date": "ସମାପ୍ତି ତାରିଖ",
    "settle_date": "ସମାଧାନ ତାରିଖ",
    "cost_span": "ମୂଲ୍ୟ ପରିସର",
    "industry": "ଶିଳ୍ପ",
    "rating": "ମୂଲ୍ୟାୟନ",
    "rates": "ମୂଲ୍ୟାୟନ",
    "seen_at": "ଦେଖାଗଲା |",
    "completed": "ସମାପ୍ତ",
    "you": "ତୁମେ",
    "shop": "ଦୋକାନ କରନ୍ତୁ |",
    "store": "ଷ୍ଟୋର୍‌ କରନ୍ତୁ |",
    "granted": "ମଞ୍ଜୁର",
    "deny": "ଅସ୍ୱୀକାର କର |",
    "request": "ଅନୁରୋଧ",
    "expert": "ବିଶେଷଜ୍ଞ |",
    "response": "ପ୍ରତିକ୍ରିୟା",
    "requests": "ଅନୁରୋଧ",
    "experts": "ବିଶେଷଜ୍ଞମାନେ |",
    "responses": "ପ୍ରତିକ୍ରିୟା",
    "negotiations": "ଆଲୋଚନା",
    "all_chats": "ସମସ୍ତ ଚାଟ୍ |",
    "chats": "ଚାଟ୍",
    "tags": "ଟ୍ୟାଗ୍ସ |",
    "description": "ବର୍ଣ୍ଣନା",
    "rates_count": "ମୂଲ୍ୟାୟନ ସଂଖ୍ୟା",
    "rate": "ମୂଲ୍ୟାୟନ",
    "comment": "ମନ୍ତବ୍ୟ ଦିଅନ୍ତୁ |",
    "chat": "ଚାଟ୍ କରନ୍ତୁ |",
    "install": "ସଂସ୍ଥାପନ କରନ୍ତୁ |",
    "edited": "ସମ୍ପାଦିତ |",
    "undo": "ପୂର୍ବବତ୍ କରନ୍ତୁ |",
    "redo": "ରେଡୋ |",
    "male": "ପୁରୁଷ",
    "female": "ମହିଳା",
    "calculator": "କାଲକୁଲେଟର",
    "catalog": "କାଟାଲଗ୍",
    "max_height": "ସର୍ବାଧିକ ଉଚ୍ଚତା |",
    "images_compare": "ପ୍ରତିଛବି ତୁଳନା",
    "canvas": "କାନଭାସ୍ |",
    "table_of_contents": "ସୁଚୀ ପତ୍ର",
    "comments": "ମନ୍ତବ୍ୟଗୁଡିକ",
    "badge_codes": "ବ୍ୟାଜ୍ କୋଡ୍ |",
    "need_more": "ଅଧିକ ଆବଶ୍ୟକ କରନ୍ତି କି?",
    "invite_glow_caption": "ପ୍ରତ୍ୟେକ ସାଙ୍ଗ ପାଇଁ 14.9 $ ପାଆନ୍ତୁ!",
    "register_free": "100% ମାଗଣା ରେଜିଷ୍ଟର |",
    "gift": "ଉପହାର",
    "google": "ଗୁଗୁଲ୍",
    "facebook": "ଫେସବୁକ୍ |",
    "instagram": "ଇନଷ୍ଟାଗ୍ରାମ |",
    "instashop": "ଇନଷ୍ଟାସପ୍ |",
    "show": "ଦେଖାନ୍ତୁ |",
    "hide": "ଲୁଚାନ୍ତୁ |",
    "waiting_review": "ସମୀକ୍ଷା ଅପେକ୍ଷାରେ |",
    "not_selected": "ମନୋନୀତ ହୋଇନାହିଁ |",
    "time": "ସମୟ",
    "final_price": "ଅନ୍ତିମ ମୂଲ୍ୟ |",
    "starting_price": "ଆରମ୍ଭ ମୂଲ୍ୟ",
    "day": "ଦିନ",
    "paid": "ଦେୟ",
    "service_bill": "ଇନଭାଇସ୍ ଦେୟ |",
    "avocado": "ଆଭୋକାଡୋ |",
    "delivery_price": "ପଠାଇବା ଖର୍ଚ",
    "select_address": "ଠିକଣା ଚୟନ କରନ୍ତୁ |",
    "image": "ପ୍ରତିଛବି |",
    "view": "ଦର୍ଶନ କରନ୍ତୁ |",
    "sell": "ବିକ୍ରୟ |",
    "hyper": "ହାଇପର",
    "cart_list": "କାର୍ଟ",
    "barcode_scanner": "ବାରକୋଡ୍ ସ୍କାନର୍ |",
    "scan_qr_code": "QR କୋଡ୍ ସ୍କାନ୍ କରନ୍ତୁ |",
    "new_carts": "ନୂତନ କାର୍ଗୁଡ଼ିକ |",
    "pays": "ଦେୟ",
    "annually": "ବାର୍ଷିକ |",
    "sells": "ବିକ୍ରୟ",
    "articles": "ପ୍ରବନ୍ଧଗୁଡିକ",
    "jobs": "ଚାକିରି",
    "job": "ଚାକିରି",
    "blog": "ବ୍ଲଗ୍",
    "deleted_at": "ଡିଲିଟ୍ ହୋଇଛି",
    "capacity": "ସାମର୍ଥ୍ୟ |",
    "download_at": "ଶେଷ ଡାଉନଲୋଡ୍ ତାରିଖ |",
    "downloads": "ଡାଉନଲୋଡ୍ |",
    "usage": "ବ୍ୟବହାର",
    "select_upload_file": "ଫାଇଲ୍ ଚୟନ କରନ୍ତୁ କିମ୍ବା ଡ୍ରପ୍ କରନ୍ତୁ |",
    "download_link": "ଲିଙ୍କ୍ ଡାଉନଲୋଡ୍ କରନ୍ତୁ |",
    "uploading": "ଅପଲୋଡ୍ କରୁଛି ..",
    "files": "ଫାଇଲଗୁଡିକ",
    "star": "ତାରା |",
    "speed": "ଗତି",
    "feedback": "ମତାମତ",
    "new_messages": "ନୂତନ ବାର୍ତ୍ତା |",
    "file": "ଫାଇଲ୍ |",
    "attachment": "ସଂଲଗ୍ନ",
    "gallery": "ଗ୍ୟାଲେରୀ",
    "sync": "ସିଙ୍କ୍ କରନ୍ତୁ |",
    "diff_time": "ସମୟ ପାର୍ଥକ୍ୟ |",
    "network": "ନେଟୱାର୍କ |",
    "account": "ଖାତା",
    "configuration": "ବିନ୍ୟାସ",
    "blockchain": "ବ୍ଲକ୍ ଚେନ୍ |",
    "blog_link": "ବ୍ଲଗ୍ ଲିଙ୍କ୍ |",
    "community": "ସମ୍ପ୍ରଦାୟ |",
    "critical_zone": "ଜଟିଳ ଜୋନ୍ |",
    "statistics": "ପରିସଂଖ୍ୟାନ",
    "access": "ପ୍ରବେଶ",
    "seo": "SEO",
    "followers": "ଅନୁସରଣକାରୀ",
    "followings": "ଅନୁସରଣ",
    "private": "ପୂର୍ବାବଲୋକନ",
    "soon": "ଶୀଘ୍ର",
    "features": "ବ Features ଶିଷ୍ଟ୍ୟଗୁଡିକ",
    "bot": "ବଟ୍",
    "sample": "ନମୁନା |",
    "how_it_work": "ଏହା କିପରି କାମ କରେ?",
    "page": "ପୃଷ୍ଠା |",
    "congratulations": "ଅଭିନନ୍ଦନ",
    "recommend": "ସୁପାରିଶ କରନ୍ତୁ |",
    "recommended": "ପରାମର୍ଶିତ",
    "recoms": "ସୁପାରିଶଗୁଡିକ",
    "likes": "ପସନ୍ଦ",
    "clicks": "କ୍ଲିକ୍ କରନ୍ତୁ |",
    "platform": "ପ୍ଲାଟଫର୍ମ |",
    "cms": "CMS",
    "cash": "ନଗଦ",
    "dir_payment": "ବ୍ୟାଙ୍କ ସ୍ଥାନାନ୍ତର |",
    "auto_complete": "ଅଟୋ ସଂପୂର୍ଣ୍ଣ |",
    "compare": "ତୁଳନା କରନ୍ତୁ",
    "infinite": "ଅସୀମ |",
    "tips": "ଟିପ୍ସ",
    "technical": "ଯାନ୍ତ୍ରିକ |",
    "finance": "ଅର୍ଥ",
    "your_phone_input": "ଏକ ଫୋନ୍ ନମ୍ବର ପ୍ରବେଶ କରନ୍ତୁ |",
    "income": "ଆୟ",
    "change": "ପରିବର୍ତ୍ତନ କରନ୍ତୁ |",
    "new_users": "ନୂତନ ବ୍ୟବହାରକାରୀ |",
    "success_orders": "ସଫଳ ଆଦେଶ |",
    "direct": "ସିଧାସଳଖ |",
    "last_activity": "ଶେଷ କାର୍ଯ୍ୟକଳାପ |",
    "landing": "ଅବତରଣ",
    "now": "ବର୍ତ୍ତମାନ",
    "accept_agreement": "ମୁଁ ସର୍ତ୍ତଗୁଡିକ ପ read ିଛି ଏବଂ ଗ୍ରହଣ କରିଛି |",
    "report": "ରିପୋର୍ଟ କରନ୍ତୁ |",
    "tablet": "ଟାବଲେଟ୍ |",
    "pc": "PC",
    "acquisition_channel": "ଅଧିଗ୍ରହଣ ଚ୍ୟାନେଲ |",
    "to": "କୁ",
    "info": "ସୂଚନା",
    "general": "ଜେନେରାଲ୍ |",
    "upload": "ଅପଲୋଡ୍ କରନ୍ତୁ |",
    "general_config": "ସାଧାରଣ ବିନ୍ୟାସ",
    "limits_config": "ସୀମା",
    "design_config": "ଡିଜାଇନ୍ ଏବଂ ଷ୍ଟାଇଲ୍ |",
    "duration_config": "ଅବଧି ସୀମା",
    "constraints_config": "ଯୋଗ୍ୟତା ସୀମା |",
    "clubs_config": "କ୍ଲବରେ ଉପଲବ୍ଧ |",
    "additional_config": "ଅତିରିକ୍ତ ବିନ୍ୟାସ",
    "import": "ଆମଦାନୀ କରନ୍ତୁ |",
    "ribbon": "ରିବନ୍",
    "countries": "ଦେଶଗୁଡିକ |",
    "edit": "ସଂପାଦନ କରନ୍ତୁ |",
    "delete": "ଡିଲିଟ୍ କରନ୍ତୁ |",
    "analytics": "ଆନାଲିଟିକ୍ସ |",
    "rules": "ନିୟମ",
    "unset": "ସେଟ୍ ହୋଇନାହିଁ |",
    "carts": "କାର୍ଟଗୁଡିକ",
    "optional": "ବ tion କଳ୍ପିକ",
    "design": "ଡିଜାଇନ୍ |",
    "filter": "ଫିଲ୍ଟର୍ |",
    "send": "ପଠାନ୍ତୁ |",
    "approved": "ଅନୁମୋଦିତ |",
    "unit": "ୟୁନିଟ୍",
    "profile": "ପ୍ରୋଫାଇଲ୍",
    "shipping_rates": "ପରିବହନ ହାର",
    "package": "ପ୍ୟାକେଜ୍",
    "overview": "ସମୀକ୍ଷା",
    "live": "ଲାଇଭ୍ |",
    "never": "କଦାପି ନୁହେଁ |",
    "always": "ସର୍ବଦା |",
    "mandatory": "ବାଧ୍ୟତାମୂଳକ",
    "expire_at": "ସମାପ୍ତି ତାରିଖ",
    "position": "ଅବସ୍ଥାନ",
    "channel": "ଚ୍ୟାନେଲ୍ |",
    "age": "ବୟସ",
    "charge": "ଚାର୍ଜ",
    "giftcard": "ଉପହାର କାର୍ଡ |",
    "acquisition": "ଅଧିଗ୍ରହଣ",
    "conversion": "ରୂପାନ୍ତର",
    "total_payments": "ମୋଟ ଦେୟ",
    "community_ask": "ସମ୍ପ୍ରଦାୟରେ ପଚାର |",
    "children": "ପିଲାମାନେ |",
    "export": "ରପ୍ତାନି କରନ୍ତୁ |",
    "list": "ତାଲିକା |",
    "hierarchy": "ହାଇରାର୍କି",
    "images": "ପ୍ରତିଛବିଗୁଡିକ",
    "demo": "ଡେମୋ |",
    "author": "ଲେଖକ",
    "designer": "ଡିଜାଇନର୍",
    "max": "ସର୍ବାଧିକ",
    "accepted": "ଗ୍ରହଣ କରାଯାଇଛି",
    "reply": "ଉତ୍ତର ଦିଅ",
    "reviewed": "ସମୀକ୍ଷା କରାଯାଇଛି",
    "restored": "ପୁନ ored ସ୍ଥାପିତ |",
    "merchant": "ବ୍ୟବସାୟୀ",
    "per_product": "ପ୍ରତି ଉତ୍ପାଦ ପ୍ରତି |",
    "journey": "ଯାତ୍ରା",
    "after": "ପରେ",
    "waiting_for_payment": "ଦୟାକରି ଦେୟ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ ...",
    "hour": "ଘଣ୍ଟା |",
    "minute": "ମିନିଟ୍ |",
    "premium": "ପ୍ରିମିୟମ୍",
    "light": "ଆଲୋକ",
    "dark": "ଅନ୍ଧାର",
    "guest": "ଅତିଥି",
    "shops": "ଷ୍ଟୋରସମୂହ",
    "vendor": "ବିକ୍ରେତା",
    "vendors": "ବିକ୍ରେତାମାନେ |",
    "marketplace": "ମାର୍କେଟପ୍ଲେସ୍ |",
    "verify_date": "ତାରିଖ ଯାଞ୍ଚ କରନ୍ତୁ |",
    "note": "ଧ୍ୟାନ ଦିଅନ୍ତୁ",
    "panel": "ପ୍ୟାନେଲ୍ |",
    "removed": "ଅପସାରିତ ହୋଇଛି |",
    "segments": "ବିଭାଗଗୁଡିକ",
    "personal_info": "ବ୍ୟକ୍ତିଗତ ସୂଚନା",
    "preferences": "ପସନ୍ଦ",
    "spec": "ନିର୍ଦ୍ଦିଷ୍ଟ |",
    "reviews": "ସମୀକ୍ଷା",
    "constraints": "ପ୍ରତିବନ୍ଧକ |",
    "flexible": "ନମନୀୟ |",
    "usage_limit": "ବ୍ୟବହାର ସୀମା |",
    "temporary": "ଅସ୍ଥାୟୀ",
    "original": "ମୂଳ",
    "saved": "ସଞ୍ଚୟ!",
    "sort": "ସର୍ଟ କରନ୍ତୁ |",
    "documents": "ଡକ୍ୟୁମେଣ୍ଟ୍ |",
    "document": "ଡକ୍ୟୁମେଣ୍ଟ୍",
    "please_wait": "ଦୟାକରି ଅପେକ୍ଷା କର...",
    "pickup": "ପିକଅପ୍",
    "customize": "କଷ୍ଟମାଇଜ୍ କରନ୍ତୁ |",
    "difficulty": "ଅସୁବିଧା",
    "banned": "ନିଷେଧ |",
    "company": "କମ୍ପାନୀ",
    "tax_shipping": "ସିପିଂ ଟ୍ୟାକ୍ସ |",
    "warranty": "ୱାରେଣ୍ଟି",
    "return_policy": "ଫେରସ୍ତ ନୀତି",
    "guide": "ଗାଇଡ୍",
    "translate": "ଅନୁବାଦ କର |",
    "public": "ଜନସାଧାରଣ |",
    "deleted": "ବିଲୋପ",
    "variant": "ବିଭିନ୍ନ ପ୍ରକାର |",
    "secure": "ସୁରକ୍ଷିତ",
    "admin": "ଆଡମିନି",
    "tax_included_abstract": "ଅନ୍ତର୍ଭୂକ୍ତ",
    "payment_not_settled": "ଦେୟ ସମାଧାନ ହୋଇନାହିଁ!",
    "orders_list": "ଅର୍ଡର ତାଲିକା |",
    "subscription_plan": "ସଦସ୍ୟତା ଯୋଜନା",
    "contents": "ବିଷୟବସ୍ତୁ",
    "pricings": "ମୂଲ୍ୟ",
    "static_page": "ଷ୍ଟାଟିକ୍ ପୃଷ୍ଠା |",
    "shop_button": "ଦୋକାନ ବଟନ୍ |",
    "embed": "ଏମ୍ବେଡ୍ କରନ୍ତୁ |",
    "over": "ସମାପ୍ତ",
    "tax_vary_by_location": "ଭିନ୍ନ ଅଟେ ╏ ଅବସ୍ଥାନ",
    "product_type": "ଉତ୍ପାଦ ପ୍ରକାର |",
    "tax_id": "ଟ୍ୟାକ୍ସ ID",
    "business_name": "ବ୍ୟବସାୟ ନାମ",
    "invoice": "ଇନଭଏସ୍ |",
    "included_in_the_product": "ଉତ୍ପାଦରେ ଅନ୍ତର୍ଭୁକ୍ତ |",
    "included_in_the_product_description": "ଉତ୍ପାଦଟି ନିମ୍ନଲିଖିତ ଉପାଦାନଗୁଡ଼ିକୁ ଅନ୍ତର୍ଭୁକ୍ତ କରେ |",
    "cross_sell": "କ୍ରସ୍ ବିକ୍ରୟ |",
    "discount_off": "OFF",
    "extra_discount": "ଅତିରିକ୍ତ ରିହାତି",
    "template": "ଟେମ୍ପଲେଟ୍ |",
    "in_cart": "କାର୍ଟରେ |",
    "pros_and_cons": "ଭଲ ଏବଂ ମନ୍ଦ",
    "related_products": "ସମ୍ବନ୍ଧୀୟ ଉତ୍ପାଦଗୁଡିକ |",
    "related_categories": "ସମ୍ବନ୍ଧିତ ବର୍ଗଗୁଡିକ |",
    "badges": "ବ୍ୟାଜ୍",
    "explore": "ଏକ୍ସପ୍ଲୋର୍ କରନ୍ତୁ |",
    "updated": "ଅଦ୍ୟତନ କରାଯାଇଛି",
    "bank_name": "ବ୍ୟାଙ୍କ ନାମ",
    "bank_account_number": "ବ୍ୟାଙ୍କ ଆକାଉଣ୍ଟ ନମ୍ବର |",
    "bank_routing_number": "ବ୍ୟାଙ୍କ ରାଉଟିଙ୍ଗ୍ ନମ୍ବେ |",
    "bank_branch_address": "ବ୍ୟାଙ୍କ ଶାଖା ଠିକଣା |",
    "bank_account_name": "ଖାତା ମାଲିକର ସମ୍ପୂର୍ଣ୍ଣ ନାମ |",
    "valuation": "ମୂଲ୍ୟ",
    "cluster": "କ୍ଲଷ୍ଟର",
    "clusters": "କ୍ଲଷ୍ଟରଗୁଡିକ",
    "subscriptions": "ସଦସ୍ୟତା",
    "spam": "ସ୍ପାମ୍",
    "video": "ଭିଡିଓ"
  },
  "dialogs": {
    "delete": {
      "title": "ଡିଲିଟ୍ କରନ୍ତୁ |",
      "message": "ଆପଣ ଏହି ଆଇଟମ୍ ବିଲୋପ କରିବାକୁ ନିଶ୍ଚିତ କି?",
      "action": "ହଁ, ବର୍ତ୍ତମାନ ଡିଲିଟ୍ କରନ୍ତୁ |"
    }
  },
  "actions": {
    "add_to_cart": "କାର୍ଟରେ ଯୋଗ କର",
    "cancel": "ବାତିଲ୍ କରନ୍ତୁ |",
    "update": "ଅଦ୍ୟତନ କରନ୍ତୁ |",
    "add": "ଯୋଡନ୍ତୁ |",
    "delete": "ଡିଲିଟ୍ କରନ୍ତୁ |",
    "new": "ନୂତନ",
    "save_continue": "ସଞ୍ଚୟ ଏବଂ ଜାରି ରଖ |",
    "save": "ସଞ୍ଚୟ କରନ୍ତୁ |",
    "save_changes": "ପରିବର୍ତ୍ତନଗୁଡିକ ସଞ୍ଚୟ କରନ୍ତୁ |",
    "change": "ପରିବର୍ତ୍ତନ କରନ୍ତୁ |",
    "continue": "ଜାରି ରଖ |",
    "close": "ବନ୍ଦ",
    "finish": "ସମାପ୍ତ",
    "poll": "ମତଦାନ",
    "view": "ଦର୍ଶନ କରନ୍ତୁ |",
    "edit": "ସଂପାଦନ କରନ୍ତୁ |",
    "next": "ପରବର୍ତ୍ତୀ",
    "previous": "ପୂର୍ବ",
    "create": "ସୃଷ୍ଟି କରନ୍ତୁ |",
    "set": "ସେଟ୍ କରନ୍ତୁ |",
    "find": "ଖୋଜ |",
    "accept": "ଗ୍ରହଣ କରନ୍ତୁ",
    "reject": "ପ୍ରତ୍ୟାଖ୍ୟାନ କରନ୍ତୁ |",
    "back": "ପଛକୁ",
    "pay": "ଦେୟ ଦିଅ |",
    "pay_now": "ବର୍ତ୍ତମାନ ଦେୟ ଦିଅ |",
    "print": "ମୁଦ୍ରଣ",
    "return": "ଫେରନ୍ତୁ",
    "publish": "ପ୍ରକାଶନ କର |",
    "confirm": "ନିଶ୍ଚିତ କରନ୍ତୁ |",
    "copy": "କପି କରନ୍ତୁ |",
    "submit": "ଦାଖଲ କରନ୍ତୁ |",
    "send": "ପଠାନ୍ତୁ |",
    "yes": "ହଁ",
    "no": "ନା",
    "meh": "ହମ୍",
    "clear": "ସଫା କରନ୍ତୁ |",
    "dismiss": "ବରଖାସ୍ତ",
    "search": "ସନ୍ଧାନ |",
    "deselect_all": "ସମସ୍ତଙ୍କୁ ବାଛନ୍ତୁ |",
    "select_all": "ସବୁ ବାଛ",
    "refresh": "ସତେଜ",
    "verify": "ଯାଞ୍ଚ କରନ୍ତୁ |",
    "play": "ଖେଳନ୍ତୁ |",
    "open": "ଖୋଲନ୍ତୁ |",
    "calculate": "ଗଣନା କର |",
    "quick_buy": "ଶୀଘ୍ର କିଣ |",
    "click_here": "ଏଠି କ୍ଲିକ କରନ୍ତୁ",
    "schedule": "କାର୍ଯ୍ୟସୂଚୀ",
    "send_now": "ବର୍ତ୍ତମାନ ପଠାନ୍ତୁ |",
    "download": "ଡାଉନଲୋଡ୍ କରନ୍ତୁ |",
    "reset_default": "ଡିଫଲ୍ଟକୁ ପୁନ et ସେଟ୍ କରନ୍ତୁ |",
    "reset": "ପୁନ et ସେଟ୍ କରନ୍ତୁ |",
    "check": "ଯାଞ୍ଚ କରନ୍ତୁ |",
    "cod_payment": "ବିତରଣରେ ନଗଦ",
    "dir_payment": "ଟଙ୍କା ପଠେଇବା",
    "online_payment": "ଅନଲାଇନ୍ ଦେୟ |",
    "checkout": "ଚେକଆଉଟ୍ |",
    "show_all": "ସମସ୍ତ ଦେଖାନ୍ତୁ |",
    "login": "ଭିତରକୁ ଯାଉ",
    "logout": "ପ୍ରସ୍ଥାନ କର",
    "more": "ଅଧିକ ..",
    "collapse": "ପତନ",
    "apply_change": "ପରିବର୍ତ୍ତନଗୁଡିକ ପ୍ରୟୋଗ କରନ୍ତୁ |",
    "apply": "ପ୍ରୟୋଗ କରନ୍ତୁ |",
    "add_giftcard": "ଉପହାର କାର୍ଡ ଯୋଡନ୍ତୁ |",
    "charge": "ଚାର୍ଜ",
    "send_invites": "ନିମନ୍ତ୍ରଣ ପଠାନ୍ତୁ |",
    "past": "ଅତୀତ",
    "restore": "ପୁନରୁଦ୍ଧାର କରନ୍ତୁ |",
    "cut": "କାଟନ୍ତୁ |",
    "get_sms_code": "ପ୍ରାମାଣିକିକରଣ କୋଡ୍ ପାଆନ୍ତୁ |",
    "register_no_mail": "ଇମେଲ ବିନା ଜାରି ରଖନ୍ତୁ |",
    "no_mail_register_message": "ଆପଣଙ୍କର ଏକ ଇମେଲ୍ ଠିକଣା ନାହିଁ କିମ୍ବା ଆପଣଙ୍କର ପାସୱାର୍ଡ ଭୁଲି ଯାଇଛନ୍ତି କି?",
    "reset_by_mail": "ଇମେଲ ଦ୍ୱାରା ପାସୱାର୍ଡ ପୁନରୁଦ୍ଧାର |",
    "reset_by_sms": "SMS ଦ୍ୱାରା ପାସୱାର୍ଡ ପୁନରୁଦ୍ଧାର |",
    "cash_payment": "ନଗଦ ଦେୟ",
    "show_chart": "ଚାର୍ଟ ଦେଖାନ୍ତୁ |",
    "open_app": "ଆପ୍ ଖୋଲନ୍ତୁ |",
    "login_now": "ବର୍ତ୍ତମାନ ଲଗ୍ଇନ୍ କରନ୍ତୁ |",
    "watch_video": "ଭିଡିଓ ଦେଖନ୍ତୁ |",
    "check_now": "ବର୍ତ୍ତମାନ ଯାଞ୍ଚ କରନ୍ତୁ |",
    "remove_image": "ପ୍ରତିଛବି ଅପସାରଣ କରନ୍ତୁ |",
    "view_website": "ଲିଙ୍କ୍ ଖୋଲନ୍ତୁ |",
    "explore": "{name} ଏକ୍ସପ୍ଲୋର୍ କରନ୍ତୁ |",
    "go": "ଯାଅ |",
    "read_more": "ଅଧିକ ପଢ",
    "start_now": "ବର୍ତ୍ତମାନ ଆରମ୍ଭ କରନ୍ତୁ - ଏହା ମାଗଣା |",
    "view_live": "ଲାଇଭ୍ ଦର୍ଶନ କରନ୍ତୁ |",
    "resend_code": "କୋଡ୍ ପଠାନ୍ତୁ |",
    "invite": "ନିମନ୍ତ୍ରଣ",
    "add_more": "ଅଧିକ ଯୋଡନ୍ତୁ |",
    "install_now": "ବର୍ତ୍ତମାନ ସଂସ୍ଥାପନ କରନ୍ତୁ |",
    "uninstall": "ଅଣସଂସ୍ଥାପନ କରନ୍ତୁ |",
    "show_preview": "ପୂର୍ବାବଲୋକନ ଦେଖାନ୍ତୁ |",
    "hide_preview": "ପୂର୍ବାବଲୋକନ ଲୁଚାନ୍ତୁ |",
    "download_now": "ବର୍ତ୍ତମାନ ଡାଉନଲୋଡ୍ କରନ୍ତୁ",
    "auto_fill": "ଅଟୋଫିଲ୍ |",
    "track": "ଟ୍ରାକ୍ କରନ୍ତୁ |",
    "change_state": "ସ୍ଥିତି ପରିବର୍ତ୍ତନ କରନ୍ତୁ |",
    "done": "ସମାପ୍ତ ହେଲା |",
    "reply": "ଉତ୍ତର ଦିଅ",
    "watch_now": "ବର୍ତ୍ତମାନ ଦେଖନ୍ତୁ |",
    "unlock": "ଅନଲକ୍ କରନ୍ତୁ |",
    "lock": "ଲକ୍ କରନ୍ତୁ |",
    "create_clone": "କ୍ଲୋନ୍ ସୃଷ୍ଟି କରନ୍ତୁ |",
    "regenerate": "ପୁନ ener ନିର୍ମାଣ କରନ୍ତୁ |",
    "add_message": "ବାର୍ତ୍ତା ଯୋଡନ୍ତୁ |",
    "continue_chat": "ଚାଟ୍ ଜାରି ରଖନ୍ତୁ |",
    "add_new_message": "ନୂତନ ବାର୍ତ୍ତା ଯୋଡନ୍ତୁ |",
    "change_setting": "ସେଟିଂ ପରିବର୍ତ୍ତନ କରନ୍ତୁ |",
    "delete_all": "ସମସ୍ତ ବିଲୋପ କରନ୍ତୁ |",
    "transfer_fund": "ସ୍ଥାନାନ୍ତର ପାଣ୍ଠି",
    "reverse_fund": "ଓଲଟା ପାଣ୍ଠି |",
    "settlement": "ସମାଧାନ",
    "refund": "ଫେରସ୍ତ",
    "partial_refund": "ଆଂଶିକ ଫେରସ୍ତ",
    "change_payment_method": "ଦେୟ ପଦ୍ଧତି ପରିବର୍ତ୍ତନ କରନ୍ତୁ |",
    "buy": "କିଣନ୍ତୁ |",
    "view_all": "ସମସ୍ତ ଦେଖନ୍ତୁ |",
    "view_now": "ବର୍ତ୍ତମାନ ଦେଖନ୍ତୁ |",
    "paste": "ଲେପନ କରନ୍ତୁ |"
  },
  "instance_message_title": "ତତକ୍ଷଣାତ୍ ବାର୍ତ୍ତା ପଠାନ୍ତୁ |",
  "instance_message": "ହାଏ {name}, ମୋ ନାମ {company} ରୁ {author} |",
  "errors": {
    "419": "ଆପଣ ଦୀର୍ଘ ସମୟ ଧରି ନିଷ୍କ୍ରିୟ ହୋଇ ରହିଛନ୍ତି, ଦୟାକରି <b>security</b> ସୁରକ୍ଷା ଦୃଷ୍ଟିରୁ ପୃଷ୍ଠାକୁ ପୁନର୍ବାର କରନ୍ତୁ |",
    "gateway_blockchain_sync_error": "ସିଷ୍ଟମ୍ ବ୍ଲକ୍ ଚେନ୍ ସହିତ ସିଙ୍କ୍ରୋନାଇଜ୍ ହୁଏ ନାହିଁ ╏ ଆମର ସର୍ଭରଗୁଡ଼ିକର ସିଙ୍କ୍ରୋନାଇଜେସନ୍ ସମାପ୍ତ ନହେବା ପର୍ଯ୍ୟନ୍ତ ଏକ ନୂତନ କାରବାର ସୃଷ୍ଟି କରିବା ସମ୍ଭବ ନୁହେଁ ╏ ଆମେ ସମସ୍ୟାର ସମାଧାନ କରୁଛୁ |",
    "gateway_network_error": "ପେମେଣ୍ଟ ଗେଟୱେ ସେବା ଏକ ଯୋଗାଯୋଗ ସମସ୍ୟାର ସମ୍ମୁଖୀନ ହୋଇଛି |"
  },
  "receiver_info": {
    "map": {
      "title": "ପହଞ୍ଚାଇବା ସ୍ଥାନ",
      "confirm": "ଅବସ୍ଥାନ ସେଟ୍ କରନ୍ତୁ |",
      "address_type": "ଗନ୍ତବ୍ୟସ୍ଥଳ",
      "receptor_type": "ଗ୍ରହଣକାରୀ"
    },
    "receiver_address": "ସିପିଂ ଠିକଣା ଚୟନ କରନ୍ତୁ |",
    "address": "ଠିକଣା",
    "postcode": "ପୋଷ୍ଟକୋଡ୍",
    "enter_value": "ଏଠାରେ ପୁରଣ କରନ୍ତୁ |",
    "address_note": "ଧ୍ୟାନ ଦିଅନ୍ତୁ",
    "tel": "ଯୋଗାଯୋଗ ନମ୍ବର |",
    "service_address": "ଆପଣଙ୍କର ଠିକଣା ଚୟନ କରନ୍ତୁ |"
  },
  "weight": {
    "g": "g",
    "oz": "oz",
    "lb": "lb",
    "kg": "କିଲୋଗ୍ରାମ୍"
  },
  "mass_unit_name": {
    "g": "ଗ୍ରାମ",
    "oz": "Ounce",
    "lb": "ଛେଚିବା",
    "kg": "କିଲୋଗ୍ରାମ |"
  },
  "length": {
    "cm": "ସେ। ମି",
    "in": "ଭିତରେ",
    "ft": "ft",
    "mm": "mm",
    "m": "ମି",
    "yd": "yd"
  },
  "size_unit_name": {
    "cm": "ସେଣ୍ଟିମିଟର |",
    "in": "ଇଞ୍ଚ",
    "ft": "ପାଦ",
    "mm": "ମିଲିମିଟର |",
    "m": "ମିଟର",
    "yd": "ପ୍ରାଙ୍ଗଣ"
  },
  "distance": {
    "m": "ମିଟର",
    "km": "କି.ମି."
  },
  "time": {
    "days": "ଦିନଗୁଡିକ",
    "hours": "ଘଣ୍ଟା",
    "minutes": "ମିନିଟ୍",
    "seconds": "ସେକେଣ୍ଡ୍ |"
  },
  "units": [
    "ୟୁନିଟ୍",
    "ଆଇଟମ୍",
    "ପ୍ରତ୍ୟେକ",
    "ସେଟ୍ କରନ୍ତୁ |",
    "ଖଣ୍ଡ",
    "କିଲୋଗ୍ରାମ |",
    "ଗ୍ରାମ",
    "ମିଲିଗ୍ରାମ |",
    "ମିଟର",
    "ମିଲିମିଟର |",
    "ବର୍ଗ ମିଟର |",
    "ବର୍ଗ ଫୁଟ",
    "ଘନ ମିଟର |",
    "ଲିଟର",
    "ମିଲିଲିଟର",
    "ପାଦ",
    "ଗ୍ୟାଲନ୍ |",
    "ଇଞ୍ଚ",
    "ounces",
    "ପାଉଣ୍ଡ |",
    "କ୍ୱାର୍ଟସ୍",
    "ଅଗଣା",
    "କୋଠରୀ",
    "ସେକେଣ୍ଡ୍ |",
    "ମିନିଟ୍ |",
    "ଘଣ୍ଟା",
    "ଦିନ",
    "ସପ୍ତାହଗୁଡିକ |",
    "ମାସଗୁଡିକ",
    "ବର୍ଷ"
  ],
  "region_types": {
    "State": "ରାଜ୍ୟ",
    "Territory": "ଅଞ୍ଚଳ",
    "Province": "ପ୍ରଦେଶ"
  },
  "transaction_status": {
    "RequireAction": "କାର୍ଯ୍ୟ ଆବଶ୍ୟକ",
    "Processing": "ପ୍ରକ୍ରିୟାକରଣ",
    "Canceled": "ବାତିଲ",
    "Succeeded": "ସଫଳ ହେଲା |"
  },
  "placeholders": {
    "name": "ଜୋନ୍ କକ୍ସ |",
    "email": "your-mail{'@'}mail.com",
    "phone": "+1 000 0000",
    "language": "ଭାଷା ଚୟନ କରନ୍ତୁ ..",
    "friend_email": "ତୁମର ସାଙ୍ଗର ଇମେଲ୍ ...",
    "friend_name": "ଅପ୍ଟ ତୁମର ସାଙ୍ଗର ନାମ",
    "select_date": "ଏକ ତାରିଖ ଚୟନ କରନ୍ତୁ ..."
  },
  "notification": {
    "confirm": "ନିଶ୍ଚିତ କରନ୍ତୁ |",
    "confirm_message": "ପରିବର୍ତ୍ତନଗୁଡିକ ସଫଳତାର ସହିତ ସଞ୍ଚୟ ହେଲା |",
    "error": "ତ୍ରୁଟି |",
    "message": "ବାର୍ତ୍ତା",
    "caution": "ସାବଧାନ",
    "warning": "ଚେତାବନୀ",
    "award": "ଅଭିନନ୍ଦନ",
    "error_message": "ଦୁର୍ଭାଗ୍ୟବଶତ।, ଏକ ତ୍ରୁଟି ଘଟିଛି |",
    "congratulation": "ଅଭିନନ୍ଦନ",
    "coming_soon": "ଶୀଘ୍ର",
    "on_fetching_data": "ସୂଚନା ଗ୍ରହଣ କରିବା ..",
    "new_pwa_version": "ନୂତନ ସଂସ୍କରଣ ବର୍ତ୍ତମାନ ଉପଲବ୍ଧ ╏ ଆପଣ ଆପ୍ଲିକେସନ୍ ଅପଡେଟ୍ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?",
    "over_license_limit": "ଲାଇସେନ୍ସ ସୀମା ଉପରେ |",
    "update_license": "ଆପଣଙ୍କର ଲାଇସେନ୍ସ ଅଦ୍ୟତନ କରନ୍ତୁ |",
    "required": "ଆବଶ୍ୟକ",
    "invalid_email": "ଅବ val ଧ ଇ-ମେଲ୍ |",
    "invalid_domain": "ଅବ val ଧ ଡୋମେନ୍ |",
    "invalid_min_length": "ସର୍ବନିମ୍ନ ଲମ୍ବ {ଲମ୍ବ must ହେବା ଜରୁରୀ |",
    "invalid_min_array_length": "ଅତିକମରେ {length} ଆଇଟମ୍ ଚୟନ କରନ୍ତୁ |",
    "invalid_max_chars": "ସର୍ବାଧିକ {maxCount} ବର୍ଣ୍ଣଗୁଡିକ |",
    "invalid_url": "ଅବ val ଧ URL |",
    "country_invalid": "ଗନ୍ତବ୍ୟସ୍ଥଳ ଦେଶ ଚୟନ କରନ୍ତୁ!",
    "postal_code_invalid": "ବ valid ଧ ଡାକ କୋଡ୍ ସେଟ୍ କରନ୍ତୁ!"
  },
  "colors": {
    "#D32F2F": "ଲାଲ୍ |",
    "#C2185B": "ଗୋଲାପୀ |",
    "#7B1FA2": "ବାଇଗଣୀ",
    "#512DA8": "ଗା ark ବାଇଗଣୀ |",
    "#303F9F": "ଇଣ୍ଡିଗୋ ବ୍ଲୁ |",
    "#1976D2": "ନୀଳ",
    "#0288D1": "ହାଲୁକା ନୀଳ",
    "#0097A7": "କଇଁଚ ନୀଳ |",
    "#00796B": "ଗୋସ୍ ସବୁଜ |",
    "#388E3C": "ସବୁଜ",
    "#689F38": "ହାଲୁକା ସବୁଜ |",
    "#AFB42B": "ଲିମୋ |",
    "#FBC02D": "ହଳଦିଆ",
    "#FFA000": "ଅମ୍ବର |",
    "#F57C00": "କମଳା |",
    "#E64A19": "ତେଜସ୍ୱୀ କମଳା |",
    "#5D4037": "ବ୍ରାଉନ୍",
    "#616161": "ଧୂସର",
    "#455A64": "ଧୂସର ନୀଳ |",
    "#FFD700": "ସୁବର୍ଣ୍ଣ |",
    "#C0C0C0": "ରୂପା |",
    "#b76e79": "ସୁବର୍ଣ୍ଣ ଗୋଲାପ |",
    "#383838": "ମ୍ୟାଟ୍ କଳା |",
    "#FFFFFF": "ଧଳା |",
    "#FFF": "ଧଳା |",
    "#000000": "କଳା",
    "#000": "କଳା",
    "#7d263a": "ମାରୁନ୍ |",
    "#FD9F17": "ସୁନା |",
    "#229DBF": "କୁମ୍ଭ",
    "#6DC9E2": "Aqua Triblend",
    "#413B2D": "ସେନା",
    "#474747": "ଆସଫାଲ୍ଟ |",
    "#E6195C": "ବେରୀ |",
    "#B2184C": "ବେରୀ ଟ୍ରିବଲାଣ୍ଡ |",
    "#FC7F5F": "ଜଳୁଥିବା କମଳା |",
    "#80011F": "କାର୍ଡିନାଲ୍ |",
    "#382829": "ଚକୋଲେଟ୍ |",
    "#F06336": "ପ୍ରବାହ",
    "#FAE7C9": "କ୍ରିମ୍",
    "#6B2257": "କରେଣ୍ଟ୍ |",
    "#222127": "ଗା ark ଧୂସର",
    "#0D5A74": "ଗଭୀର ଟିଲ୍ |",
    "#00582F": "ଚିର ସବୁଜ |",
    "#214C30": "ଜଙ୍ଗଲ",
    "#DC2867": "ଫୁଚସିଆ |",
    "#38561F": "କେଲି |",
    "#5C884D": "ପତ୍ର |",
    "#558450": "ହାଲୁକା କୁମ୍ଭ",
    "#96B5C9": "ହାଲୁକା ନୀଳ",
    "#DCAFCE": "ଲିଲାକ୍ |",
    "#D3E1A4": "ଚୂନ |",
    "#9DE7C2": "ମେଣ୍ଟ",
    "#F6EAD2": "ପ୍ରାକୃତିକ |",
    "#1A1F35": "ନ y ସେନା |",
    "#404624": "ଅଲିଭ୍ |",
    "#271020": "ଘିଅ |",
    "#A8355C": "ରସଗୋଲା |",
    "#D6BEA6": "ସଫ୍ଟ କ୍ରିମ୍ |",
    "#BEA994": "ଟାନ୍ |",
    "#0DB2AE": "ଚା ’",
    "#A86EA9": "ଭିଏଲେଟ୍ |",
    "#36454F": "ଅଙ୍ଗାର",
    "#b3b0ab": "କାର୍ବନ ଗ୍ରେ",
    "#463e3d": "ଅଙ୍ଗାର ହେଥର |",
    "#282d3c": "ନ y ସେନା ବ୍ଲେଜର |"
  },
  "address_info": {
    "name": "ନାମ",
    "tel": "ଫୋନ୍ |",
    "email": "ଇମେଲ୍ କରନ୍ତୁ |",
    "country": "ଦେଶ",
    "city": "ସହର",
    "state": "ରାଜ୍ୟ",
    "address": "ଠିକଣା",
    "building_number": "ବିଲଡିଂ ନମ୍ବର |",
    "building_unit": "ୟୁନିଟ୍",
    "postcode": "ପୋଷ୍ଟକୋଡ୍",
    "note": "ଧ୍ୟାନ ଦିଅନ୍ତୁ",
    "county": "କାଉଣ୍ଟି |"
  },
  "product_types": {
    "physical": "ଶାରୀରିକ",
    "physical_description": "ଶାରୀରିକ ଉତ୍ପାଦ ଯେପରିକି: ମୋବାଇଲ୍ ଫୋନ୍, ବହି, ଇଲେକ୍ଟ୍ରୋନିକ୍ ଉପାଦାନ |",
    "virtual": "ଭର୍ଚୁଆଲ୍",
    "virtual_description": "ଇଣ୍ଟରନେଟ୍ ଅନୁକୂଳ ଉତ୍ପାଦ ଯେପରିକି: ରିଚାର୍ଜ କାର୍ଡ, ହୋଟେଲ ସଂରକ୍ଷଣ, ଖେଳ ରିଚାର୍ଜ |",
    "file": "ଫାଇଲ୍ |",
    "file_description": "ଅନଲାଇନ୍ କୋର୍ସ ଭିଡିଓ, ଡାଉନଲୋଡ୍ ଯୋଗ୍ୟ ଡକ୍ୟୁମେଣ୍ଟ୍ ପରି ସମସ୍ତ ଅନୁମତିପ୍ରାପ୍ତ ଫାଇଲଗୁଡିକ |",
    "service": "ସେବା",
    "service_description": "ସେବାଗୁଡିକ: ମରାମତି, ପରିବହନ, ଶିକ୍ଷାଦାନ |",
    "subscription": "ସଦସ୍ୟତା",
    "subscription_description": "ଉତ୍ପାଦ, ସେବା, କିମ୍ବା ବିଷୟବସ୍ତୁ ପାଇଁ ସଦସ୍ୟତା ଏବଂ ଇନଭଏସ୍ |"
  },
  "license": {
    "free": "ମାଗଣା |",
    "startup": "ଆରମ୍ଭ କର",
    "company": "କମ୍ପାନୀ",
    "enterprise": "ଏଣ୍ଟରପ୍ରାଇଜ୍"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "ଟୋମନ୍ |",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW",
    "GHS": "GHS",
    "ZWD": "ZWD",
    "IQD": "IQD",
    "SYP": "SYP"
  },
  "variants": {
    "color": "ରଙ୍ଗ",
    "volume": "ଆକାର |",
    "count_in_pack": "ପ୍ୟାକ୍ ରେ ଗଣନା କର |",
    "weight": "ଓଜନ",
    "type": "ସାମଗ୍ରୀ",
    "style": "ଶ Style ଳୀ"
  },
  "delivery_state": {
    "check_queue": "ସମୀକ୍ଷା ଅପେକ୍ଷାରେ |",
    "order_confirm": "ନିଶ୍ଚିତକରଣ ଅର୍ଡର |",
    "preparing_order": "ପ୍ରସ୍ତୁତି",
    "sent_order": "ବିତରଣରେ",
    "to_customer": "ବିତରଣ କରାଯାଇଛି"
  },
  "status": {
    "unpaid": "ଦେୟମୁକ୍ତ |",
    "paid": "ଦେୟ",
    "canceled": "ବାତିଲ",
    "completed": "ସ୍ଥିର ହୋଇଛି |",
    "reserved": "ସଂରକ୍ଷିତ",
    "COD": "COD",
    "sold": "ବିକ୍ରି ହୋଇଛି |",
    "open": "ଖୋଲନ୍ତୁ |",
    "cancel": "ବାତିଲ",
    "active": "ସକ୍ରିୟ |",
    "inactive": "ନିଷ୍କ୍ରିୟ |",
    "debug": "ତ୍ରୁଟିନିବାରଣ",
    "live": "ଲାଇଭ୍ |",
    "test": "ପରୀକ୍ଷା",
    "connected": "ସଂଯୋଗ ହୋଇଛି |",
    "disconnected": "ବିଚ୍ଛିନ୍ନ ହୋଇଛି |",
    "accept": "ଗ୍ରହଣ କରନ୍ତୁ",
    "reject": "ପ୍ରତ୍ୟାଖ୍ୟାନ କରନ୍ତୁ |",
    "pending": "ବିଚାରାଧୀନ ଅଛି |",
    "rejected": "ପ୍ରତ୍ୟାଖ୍ୟାନ",
    "accepted": "ଗ୍ରହଣ କରାଯାଇଛି"
  },
  "dimensions": {
    "cm": "ସେ। ମି",
    "km": "କି.ମି.",
    "kg": "କିଲୋଗ୍ରାମ୍"
  },
  "transportation_type": {
    "motorbike": "ମୋଟରସାଇକେଲ୍ |",
    "motorbike_description": "କିଛି କିଲୋମିଟର ମଧ୍ୟରେ ମଧ୍ୟମ ଓଜନ |",
    "cargo_small": "ଛୋଟ କାର୍ଗୋ |",
    "cargo_small_description": "ମଲ୍ଟି କିଲୋମିଟର ହାଲୁକା କାର୍ଗୋ |",
    "cargo": "କାର୍ଗୋ |",
    "cargo_description": "କିଛି କିଲୋମିଟର ମଧ୍ୟରେ ମଧ୍ୟମ ଓଜନ |",
    "truck": "ଟ୍ରକ",
    "truck_description": "ଦେଶ ମଧ୍ୟରେ ବଲ୍କ କିମ୍ବା ଭାରୀ ମାଲ ପରିବହନ |",
    "fast_post": "ଫାଷ୍ଟ ପୋଷ୍ଟ |",
    "fast_post_description": "ଡାକଘର ମାଧ୍ୟମରେ ଶୀଘ୍ର ପୋଷ୍ଟିଂ |",
    "post": "ସାଧାରଣ ପୋଷ୍ଟ |",
    "post_description": "ଡାକଘର ମାଧ୍ୟମରେ ନିୟମିତ ପୋଷ୍ଟ |",
    "airplane": "ଏୟାରମେଲ୍ |",
    "airplane_description": "ଘରୋଇ ଏବଂ ବିଦେଶୀ ଆଲୋକ ଏବଂ ମଧ୍ୟମ କାର୍ଗୋ |",
    "bicycle": "ସଫା ପଠାନ୍ତୁ |",
    "bicycle_description": "ଅଣ-ମୋଟର ଯାନଗୁଡିକର ଅଳ୍ପ ଶହେ ମିଟର ମଧ୍ୟରେ ହାଲୁକା କାର୍ଗୋ |",
    "global": "ବିଶ୍ୱ ପରିବହନ",
    "global_description": "ବାୟୁ, ସମୁଦ୍ର କିମ୍ବା ସ୍ଥଳଭାଗରେ ବିଦେଶ ପଠାଇବା |",
    "pickup": "ପିକଅପ୍",
    "pickup_description": "ଗ୍ରାହକମାନେ ତୁମର ଭ physical ତିକ ଷ୍ଟୋର୍ କିମ୍ବା ଗୋଦାମରେ ଆଇଟମ୍ ଉଠାନ୍ତି |"
  },
  "article": {
    "login_to_see_error": "ପ୍ରବନ୍ଧକୁ ପ୍ରବେଶ କରିବାକୁ ଲଗଇନ୍ କରନ୍ତୁ |",
    "create_new_action": "ନୂତନ ବିଷୟବସ୍ତୁ ସୃଷ୍ଟି କରନ୍ତୁ |",
    "menu_title": "ମେନୁ",
    "menu": {
      "edit": "ମୋଡ୍ ସଂପାଦନ କରନ୍ତୁ |",
      "view_mode": "ମୋଡ୍ ଦର୍ଶନ କରନ୍ତୁ |",
      "delete": "ପ୍ରବନ୍ଧ ବିଲୋପ କରନ୍ତୁ |"
    },
    "schedule_action": "ଆପଣ ପ୍ରକାଶନ ନିର୍ଦ୍ଧାରଣ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?",
    "schedule_title": "ସ୍ auto ତ - ପ୍ରକାଶନ କାର୍ଯ୍ୟସୂଚୀ |",
    "edit_mode": "ସଂପାଦନ କରନ୍ତୁ |",
    "public_view_mode": "ଜନସାଧାରଣ ଦୃଶ୍ୟ |",
    "publish_at": "ରେ ପ୍ରକାଶନ କରନ୍ତୁ |",
    "published": "ପ୍ରକାଶିତ |",
    "draft": "ଡ୍ରାଫ୍ଟ",
    "saving": "ସଞ୍ଚୟ",
    "save_and_publish_action": "ସଞ୍ଚୟ ଏବଂ ପ୍ରକାଶନ କର |",
    "save_draft_action": "ଡ୍ରାଫ୍ଟ ସଞ୍ଚୟ କରନ୍ତୁ |",
    "private": "ବ୍ୟକ୍ତିଗତ",
    "public": "ଜନସାଧାରଣ |",
    "category_input": "ବର୍ଗ",
    "category_input_message": "ପ୍ରବନ୍ଧ ବର୍ଗ ଚୟନ କରନ୍ତୁ |",
    "parent_input": "ପିତାମାତା ବର୍ଗ |",
    "parent_input_message": "ପିତା ବିଷୟବସ୍ତୁ ଚୟନ କରନ୍ତୁ |",
    "schedule_input": "କାର୍ଯ୍ୟସୂଚୀ",
    "schedule_input_placeholder": "ଯଦି ଆପଣ ଚାହୁଁଛନ୍ତି ଯେ କାହାଣୀ ଏକ ନିର୍ଦ୍ଦିଷ୍ଟ ସମୟରେ ପ୍ରକାଶିତ ହେଉ |",
    "schedule_view_action": "ପ୍ରକାଶନ ସୂଚୀ ଦେଖନ୍ତୁ |",
    "author_title": "ଲେଖକ",
    "read_time": "ଅଧ୍ୟୟନ ସମୟ |",
    "read_time_unit": "ମିନିଟ୍",
    "claps_action": "କରତାଳି",
    "claps": "କରତାଳି",
    "likes": "ଲାଇକ୍ କରନ୍ତୁ |",
    "about_author": "ଲେଖକଙ୍କ ବିଷୟରେ",
    "updated_at": "ଅଦ୍ୟତନ କରାଯାଇଛି",
    "wrote_at": "ରେ ଲେଖାଯାଇଛି",
    "now": "ବର୍ତ୍ତମାନ",
    "follow_action": "ଅନୁସରଣ କରନ୍ତୁ |",
    "followed": "ଅନୁସରଣ କରାଯାଇଛି",
    "report_and_delete_action": "ଏହି ଆର୍ଟିକିଲକୁ ରିପୋର୍ଟ ଏବଂ ବିଲୋପ କରନ୍ତୁ |",
    "report_action": "ଅପବ୍ୟବହାର ରିପୋର୍ଟ କରନ୍ତୁ |",
    "you_reported_this_article": "ଏହି ଆର୍ଟିକିଲରେ ଏକ ଅପବ୍ୟବହାର ରିପୋର୍ଟ ଅଛି |",
    "add_to_publication_action": "ପ୍ରକାଶନରେ ଯୋଡନ୍ତୁ |",
    "author_socials": "ସୋସିଆଲ ମିଡିଆରେ ଲେଖକ |",
    "share": "ଅଂଶୀଦାର କରନ୍ତୁ |",
    "report_dialog": {
      "report_and_delete_title": "ଅପବ୍ୟବହାର ରିପୋର୍ଟ କରନ୍ତୁ ଏବଂ ବିଷୟବସ୍ତୁ ଅପସାରଣ କରନ୍ତୁ |",
      "report_title": "ଏହି ବିଷୟବସ୍ତୁକୁ ଅପମାନଜନକ ଭାବରେ ରିପୋର୍ଟ କରନ୍ତୁ |",
      "message": "ଏହି ବିଷୟବସ୍ତୁ ଦାଖଲ କରିବାର କାରଣ କ’ଣ? ନିମ୍ନଲିଖିତ ବିକଳ୍ପଗୁଡ଼ିକ ମଧ୍ୟରୁ ଗୋଟିଏ ବାଛନ୍ତୁ |",
      "accept_and_delete_action": "ବିଷୟବସ୍ତୁ ନିଶ୍ଚିତ କରନ୍ତୁ ଏବଂ ବିଲୋପ କରନ୍ତୁ |"
    },
    "schedule_dialog": {
      "title": "ବିଷୟବସ୍ତୁ ପ୍ରକାଶନ ସୂଚୀ",
      "publish_at": "ରେ ପ୍ରକାଶନ କରନ୍ତୁ |",
      "last_edit": "ଶେଷ ସମ୍ପାଦନା |",
      "view_action": "ପ୍ରବନ୍ଧ ଦେଖନ୍ତୁ |"
    },
    "notifications": {
      "update_success_title": "ସୂଚନା ଦାଖଲ କରନ୍ତୁ |",
      "update_success": "ପ୍ରବନ୍ଧ ସଫଳତାର ସହିତ ଅଦ୍ୟତନ ହୋଇଛି |",
      "update_error": "ପ୍ରବିଷ୍ଟ ହୋଇଥିବା ସୂଚନା ବ valid ଧ ନୁହେଁ |",
      "delete_error": "ଆପଣ ଏହି ଆର୍ଟିକିଲ୍ ବିଲୋପ କରିପାରିବେ ନାହିଁ!",
      "report_and_delete_success_title": "ରିପୋର୍ଟ ଏବଂ ଡିଲିଟ୍ କରନ୍ତୁ |",
      "report_and_delete_success_message": "ଆର୍ଟିକିଲ୍ ସଫଳତାର ସହିତ ଡିଲିଟ୍ ହୋଇଛି |",
      "report_success_title": "ଆର୍ଟିକିଲ୍ ରିପୋର୍ଟ କରନ୍ତୁ |",
      "report_success_message": "ଏହି ଆର୍ଟିକିଲରେ ଆପଣଙ୍କର ରିପୋର୍ଟ ପୋଷ୍ଟ କରାଯାଇଛି |"
    },
    "alert": {
      "delete_article": {
        "title": "ପ୍ରବନ୍ଧ ବିଲୋପ କରନ୍ତୁ |",
        "message": "ଆପଣ ନିଶ୍ଚିତ କି ଆପଣ ଏହି ଆର୍ଟିକିଲକୁ ସ୍ଥାୟୀଭାବେ ବିଲୋପ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?",
        "action": "ଡିଲିଟ୍ କରନ୍ତୁ |"
      }
    },
    "edit_window": {
      "title": "ପ୍ରତିଛବି ପାଠ୍ୟ ଏବଂ ସାରାଂଶ ଚୟନ କରନ୍ତୁ |",
      "digest": "ସାରାଂଶ"
    },
    "editor": {
      "title_placeholder": "ଆଖ୍ୟା ..",
      "body_placeholder": "ଉତ୍ତମ ବିଷୟବସ୍ତୁ ଲେଖନ୍ତୁ ..",
      "accept_file_types_error": "ଏହି ଫାଇଲ୍ ଫର୍ମାଟ୍ ଗ୍ରହଣୀୟ ନୁହେଁ:",
      "max_file_size_error": "ଏହି ଫାଇଲ୍ ବହୁତ ବଡ:",
      "notifications": {
        "image_uploaded_success": "ପ୍ରତିଛବି ସଫଳତାର ସହିତ ସଞ୍ଚୟ ହୋଇଛି |",
        "image_uploaded_failed": "ପ୍ରତିଛବି ଧାରଣ କରିବାରେ ତ୍ରୁଟି |"
      },
      "embed_placeholder": "ଇଫ୍ରେମ୍ କୋଡ୍, ଫେସବୁକ୍, ୟୁଟ୍ୟୁବ୍ କିମ୍ବା ଅନ୍ୟ କ URL ଣସି URL ପ୍ରବେଶ କରନ୍ତୁ ଏବଂ ଏଣ୍ଟର୍ ଦାବନ୍ତୁ |",
      "embed_caption_placeholder": "ଏକ ଆଖ୍ୟା ପ୍ରବେଶ କରନ୍ତୁ (ବ al କଳ୍ପିକ)",
      "images_caption_placeholder": "ଏହି ପ୍ରତିଛବି ପାଇଁ ଏକ ଆଖ୍ୟା ପ୍ରବେଶ କରନ୍ତୁ .."
    }
  },
  "article_report": {
    "inappropriate": "ଏହି ପ୍ରବନ୍ଧର ବିଷୟବସ୍ତୁ ଅନୁପଯୁକ୍ତ |",
    "fake": "ଏହା ନକଲି ଏବଂ ପ୍ରତାରଣାକାରୀ |",
    "spam": "ଏହି ଆଇଟମ୍ ସ୍ପାମ୍ ହୋଇ କପି କରାଯାଇଛି |",
    "scam": "ଏହା ମାଲୱେର୍, ଭାଇରସ୍ କିମ୍ବା ସିଷ୍ଟମ୍ କ୍ରାସ୍ ହେବାର ଆଶଙ୍କା କରାଯାଇପାରେ |",
    "hacked": "ଏହି ସାଇଟ୍ ହ୍ୟାକ୍ ହୋଇଥିବା ଜଣାପଡିଛି |",
    "offensive": "ଭାଷା ବିଷୟବସ୍ତୁ ଏବଂ ଶବ୍ଦକୋଷ ଅନ eth ତିକ ଏବଂ ଅସମ୍ମାନ ଅଟେ |",
    "violent": "ମୁଁ ଭାବୁଛି ଏହି ବିଷୟବସ୍ତୁରେ ଅଶ୍ଳୀଳତା ଅଛି ଏବଂ ଏହା ନିୟମ ଉଲ୍ଲଂଘନ କରୁଛି |",
    "harassment": "ମୁଁ ଭାବୁଛି ଏହା ଜାତିପ୍ରଥା ଅଟେ |",
    "hate": "ମୁଁ ଭାବୁଛି ଏହା ହିଂସାକୁ ପ୍ରୋତ୍ସାହିତ କରିବା ବିଷୟରେ |",
    "infringe": "ଏହା ମୋର ଅଧିକାରର ଉଲ୍ଲଂଘନ କରେ |"
  },
  "comments": {
    "new_action": "ଏକ ମନ୍ତବ୍ୟ ଛାଡିବାକୁ କ୍ଲିକ୍ କରନ୍ତୁ ..",
    "title": "ମନ୍ତବ୍ୟଗୁଡିକ",
    "body_placeholder": "ତୁମର ମନ୍ତବ୍ୟ କିମ୍ବା ବାର୍ତ୍ତା |",
    "send_action": "ମନ୍ତବ୍ୟ ପଠାନ୍ତୁ |",
    "body_is_empty_error": "ମନ୍ତବ୍ୟ ଖାଲି!",
    "comments": "ମନ୍ତବ୍ୟଗୁଡିକ",
    "no_comments": "ପ୍ରଥମ ମନ୍ତବ୍ୟ ଲେଖ ...",
    "load_more_action": "ଅଧିକ ମନ୍ତବ୍ୟ ପ୍ରାପ୍ତ କରନ୍ତୁ ..",
    "cant_send_comment": "ଆପଣ ନୂତନ ପୋଷ୍ଟ ଯୋଡି ପାରିବେ ନାହିଁ |",
    "cant_remove_this_comment": "ଆପଣ ଏହି ମନ୍ତବ୍ୟ ବିଲୋପ କରିପାରିବେ ନାହିଁ!",
    "product_buyer": "କ୍ରେତା",
    "delete_alert": {
      "title": "ମନ୍ତବ୍ୟ ବିଲୋପ କରନ୍ତୁ |",
      "message": "ଆପଣ ଏହି ମନ୍ତବ୍ୟ ବିଲୋପ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?",
      "action": "ଡିଲିଟ୍ କରନ୍ତୁ |"
    },
    "notifications": {
      "delete_success": "ଆପଣଙ୍କର ମନ୍ତବ୍ୟ ସଫଳତାର ସହିତ ବିଲୋପ ହେଲା |"
    },
    "first_send": "ପ୍ରଥମ ପୋଷ୍ଟ |",
    "comment_at": "ଅନ୍",
    "edit_comment": "ମନ୍ତବ୍ୟ ସଂପାଦନ କରନ୍ତୁ |",
    "my_comments": "ମୋର ମନ୍ତବ୍ୟ"
  },
  "customer_club": {
    "bronze": "ପିତ୍ତଳ |",
    "silver": "ରୂପା |",
    "gold": "ସୁବର୍ଣ୍ଣ |",
    "platinum": "ପ୍ଲାଟିନମ୍ |",
    "diamond": "ହୀରା |"
  },
  "application_categories": {
    "tracking": "ଉପଯୋଗକର୍ତ୍ତା ଆଚରଣ ଯାଞ୍ଚ କରୁଛି |",
    "payment": "ଦେୟ",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "ପରିବହନ",
    "automation": "ସ୍ୱୟଂଚାଳିତ",
    "inventory": "ଗୋଦାମ ଘର",
    "accounting": "ହିସାବ",
    "marketing": "ମାର୍କେଟିଂ |",
    "advertising": "ବିଜ୍ଞାପନ",
    "staff": "କର୍ମଚାରୀ",
    "incentive": "ପ୍ରୋତ୍ସାହନ",
    "shop": "ଦୋକାନ କରନ୍ତୁ |"
  },
  "social_network": {
    "instagram": "ଇନଷ୍ଟାଗ୍ରାମ |",
    "telegram": "ଟେଲିଗ୍ରାମ |",
    "googleplay": "ଗୁଗୁଲ୍ ପ୍ଲେ |",
    "appstore": "ଆପ୍ ଷ୍ଟୋର |",
    "twitter": "ଟ୍ୱିଟର |",
    "linkedin": "ଲିଙ୍କ୍ଡେନ୍ |",
    "medium": "ମଧ୍ୟମ",
    "selldone": "ସେଲଡୋନ୍ |",
    "facebook": "ଫେସବୁକ୍ |",
    "pinterest": "Pinterest",
    "whatsapp": "ହ୍ ats ାଟସ୍ ଆପ୍",
    "skype": "ସ୍କାଇପ୍",
    "facebook_messenger": "ଫେସବୁକ୍ ମେସେଞ୍ଜର |"
  },
  "form_builder": {
    "add_item_action": "ନୂତନ ଆଇଟମ୍ ଯୋଡନ୍ତୁ |",
    "title_input": "ଆଖ୍ୟା",
    "name_input": "ଭେରିଏବଲ୍ ନାମ",
    "value_input": "ମୂଲ୍ୟଗୁଡ଼ିକ",
    "value_input_message": "ଉପଯୋଗକର୍ତ୍ତା ବିକଳ୍ପ ତାଲିକା |",
    "default": "ଡିଫଲ୍ଟ ମୂଲ୍ୟ",
    "types": {
      "simple": "ସରଳ",
      "selective": "ଚୟନକର୍ତ୍ତା |",
      "switch": "ସୁଇଚ୍",
      "file": "ଫାଇଲ୍ |",
      "number": "ସଂଖ୍ୟା"
    },
    "placeholder_input": "ସ୍ଥାନଧାରୀ",
    "file_type_input": "ଗ୍ରହଣୀୟ ଫାଇଲ୍ ପ୍ରକାରଗୁଡିକ |",
    "file_type_message": "jpeg, png, zip, ..."
  },
  "virtual_order_info_summery": {
    "title": "ଉତ୍ପାଦର ନାମ",
    "reserved_at": "ପଞ୍ଜୀକରଣ ତାରିଖ |",
    "total_price": "ମୋଟ ରାଶି",
    "discount": "ରିହାତି",
    "final_price": "ଅନ୍ତିମ ପରିମାଣ",
    "payment_status": "ଦେୟ ସ୍ଥିତି",
    "payment_status_waiting": "ଦେୟକୁ ଅପେକ୍ଷା",
    "payment_status_paid": "ଦେୟ",
    "buyer": "କ୍ରେତା"
  },
  "virtual_item_info": {
    "title": "ଭର୍ଚୁଆଲ୍ ଆଇଟମ୍ |",
    "outputs": {
      "title": "ଆଉଟପୁଟ୍ ସୂଚନା",
      "sub_title": "ଏହି ଆଇଟମ୍ ର ଗୋପନୀୟ ସୂଚନା |",
      "message": "ଉତ୍ପାଦ କିଣିବା ପରେ ଏହି ସୂଚନା ଉପଭୋକ୍ତାଙ୍କୁ ଦେଖାଯିବ |"
    },
    "inputs": {
      "title": "ସୂଚନା ଆବଶ୍ୟକ",
      "sub_title": "କ୍ରେତା ସୂଚନା ଆବଶ୍ୟକ |",
      "message": "କ୍ରେତା ନିଶ୍ଚିତ ଭାବରେ ଫର୍ମରେ ଅନୁରୋଧ କରାଯାଇଥିବା ସୂଚନା ପ୍ରବେଶ କରିବେ |"
    },
    "notifications": {
      "inputs_set_success": "ସୂଚନା ଫର୍ମ ସଫଳତାର ସହିତ ପଞ୍ଜିକୃତ |",
      "confirm_by_admin_success": "ଅର୍ଡର ସମାପ୍ତି ନିଶ୍ଚିତ ହୋଇଛି |",
      "confirm_by_buyer_success": "ଅର୍ଡର ସମାପ୍ତି ନିଶ୍ଚିତ ହୋଇଛି |"
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "ଏହି ଆଦେଶକୁ COD ଦେୟ ଦ୍ୱାରା ଗ୍ରହଣ କରାଯାଇପାରିବ ନାହିଁ |",
    "payment_returned": "ଗ୍ରାହକଙ୍କ ଦ୍ୱାରା ଦେୟ ଫେରସ୍ତ କରାଯାଇଥାଏ |",
    "payment_fraud": "ଦେୟ ଠକେଇ ବୋଲି ଚିହ୍ନଟ କରାଯାଇଛି |",
    "location_out_of_service": "ଗ୍ରାହକଙ୍କ ଅବସ୍ଥାନ ସେବା ବାହାରେ |",
    "user_not_responding": "ଗ୍ରାହକ କଲ୍ ର ଉତ୍ତର ଦେଇନଥିଲେ |",
    "shop_owner_fault": "ସୂଚନା ଭରିବାରେ ଷ୍ଟୋର କର୍ମଚାରୀଙ୍କ ଦ୍ୱାରା ଏକ ତ୍ରୁଟି ଘଟିଲା |",
    "lack_of_inventory": "ଷ୍ଟକ୍ ସେଶ।",
    "legal_restriction": "ଆଇନଗତ ପ୍ରତିବନ୍ଧକ ହେତୁ ଏକ ଅର୍ଡର ଦେବାକୁ ଅସମର୍ଥ |",
    "pricing_fault": "ବିକ୍ରେତାଙ୍କ ଦ୍ୱାରା ମୂଲ୍ୟ ନିର୍ଦ୍ଧାରଣ |",
    "system_fault": "ସିଷ୍ଟମ୍ ବଗ୍ |"
  },
  "basket_order_info_summery": {
    "receiver": "ଗ୍ରହଣକାରୀ",
    "phone": "ଟେଲ",
    "reserved_date": "କ୍ରୟ ତାରିଖ |",
    "total_price": "ମୋଟ ରାଶି",
    "discount": "ରିହାତି",
    "final_price": "ଅନ୍ତିମ ପରିମାଣ",
    "address": "ବିତରଣ ଠିକଣା",
    "payment_status": "ଦେୟ ସ୍ଥିତି"
  },
  "basket_status": {
    "open": "ଖୋଲନ୍ତୁ |",
    "reserved": "ସଂରକ୍ଷିତ",
    "paid": "ଦେୟ",
    "canceled": "ବାତିଲ",
    "cod": "ବିତରଣରେ ଦେୟ ଦିଅ |",
    "receipt_added": "ରସିଦ ଯୋଗ କରାଯାଇଛି |",
    "payment_processing": "ଦେୟ ପ୍ରକ୍ରିୟାକରଣ |"
  },
  "basket_delivery_state": {
    "rejected": "ପ୍ରତ୍ୟାଖ୍ୟାନ",
    "reject_reason_not_found": "ଏହାର କାରଣ ଜଣା ପଡିନାହିଁ।",
    "step_1": "ସମୀକ୍ଷା କରନ୍ତୁ |",
    "step_2": "ନିଶ୍ଚିତକରଣ",
    "step_3": "ପ୍ରସ୍ତୁତି",
    "step_4": "ବିତରଣରେ",
    "step_5": "ବିତରଣ କରାଯାଇଛି"
  },
  "basket_return_request_view": {
    "title": "ଫେରସ୍ତ ଅନୁରୋଧ",
    "delivery_date": "ପ୍ରସବ ତାରିଖ୍",
    "return_date": "ଅନୁରୋଧ ତାରିଖ |",
    "items_count": "ଫେରସ୍ତ ଆଇଟମ୍ ଗଣନା |",
    "items_count_unit": "ଆଇଟମ୍ (ଗୁଡିକ)",
    "reason": "କାରଣ",
    "description": "ବର୍ଣ୍ଣନା",
    "status": "ସ୍ଥିତି",
    "download_image": "ପ୍ରତିଛବି ଡାଉନଲୋଡ୍ କରନ୍ତୁ |",
    "download_film": "ଭିଡିଓ ଡାଉନଲୋଡ୍ କରନ୍ତୁ |",
    "download_voice": "ଭଏସ୍ ଡାଉନଲୋଡ୍ କରନ୍ତୁ |",
    "accept_by_admin_action": "ଅନୁରୋଧ ଗ୍ରହଣ କରନ୍ତୁ |",
    "reject_by_admin_action": "ଅନୁରୋଧ ପ୍ରତ୍ୟାଖ୍ୟାନ କରନ୍ତୁ |",
    "message_for_admin": "ସେଲଡୋନ୍ ବ୍ୟବହାର କରି ଆପଣ ଗ୍ରହଣ କରିଥିବା ଚୁକ୍ତିନାମା ଅନୁଯାୟୀ, ଆପଣ ନିଶ୍ଚିତ ଭାବରେ କ୍ରେତାଙ୍କୁ ଯୋଗାଯୋଗ କରିବେ ଏବଂ ତାଙ୍କୁ ତାଙ୍କ ଆଦେଶ ଫେରସ୍ତ ପ୍ରକ୍ରିୟା ବିଷୟରେ ଅବଗତ କରାଇବେ ╏ ଯଦି ଅନୁରୋଧ ଗ୍ରହଣ କିମ୍ବା ପ୍ରତ୍ୟାଖ୍ୟାନ କରାଯାଏ ଏବଂ କ୍ରେତାଙ୍କର ସମ୍ପୂର୍ଣ୍ଣ ସମ୍ମତି ପ୍ରାପ୍ତ ହୁଏ ତେବେ ଏହା କରିବା ଆବଶ୍ୟକ |",
    "notifications": {
      "update_status_success": "ଅନୁରୋଧ ସ୍ଥିତି ଅଦ୍ୟତନ ହୋଇଛି |"
    }
  },
  "basket_list": {
    "return_count": "ଫେରସ୍ତ: {count} ସଂଖ୍ୟା |",
    "table": {
      "row": "ଧାଡି",
      "image": "ପ୍ରତିଛବି |",
      "product_name": "ଉତ୍ପାଦ",
      "variant": "ବିଭିନ୍ନ ପ୍ରକାର |",
      "warranty": "ୱାରେଣ୍ଟି",
      "count": "ଗଣନା କର |",
      "price": "ମୂଲ୍ୟ"
    }
  },
  "return_request_list": {
    "count": "ଚିହ୍ନଟ ସଂଖ୍ୟା",
    "return_warranty": "ଟଙ୍କା ଫେରସ୍ତ ଗ୍ୟାରେଣ୍ଟି |",
    "return_warranty_unit": "ଦିନ (ଗୁଡିକ)",
    "table": {
      "code": "ଅର୍ଡର କୋଡ୍ |",
      "product": "ଉତ୍ପାଦ",
      "delivery_at": "ପ୍ରାପ୍ତ ତାରିଖ",
      "state": "ସ୍ଥିତି",
      "reason": "କାରଣ",
      "return_warranty_period": "ୱାରେଣ୍ଟି ଅବଧି"
    }
  },
  "data_toolbar": {
    "search": "ସନ୍ଧାନ |",
    "sort_by": "ଦ୍ୱାରା ସର୍ଟ କରନ୍ତୁ |",
    "count_item": "{item} ଆଇଟମ୍ ଦେଖାନ୍ତୁ |"
  },
  "sort": {
    "created_at": "ତାରିଖ ସୃଷ୍ଟି କରନ୍ତୁ |",
    "updated_at": "ତାରିଖ ସଂପାଦନ କରନ୍ତୁ |",
    "title": "ଆଖ୍ୟା",
    "description": "ବର୍ଣ୍ଣନା",
    "like": "ଲୋକପ୍ରିୟତା",
    "power": "କରତାଳି",
    "product_type": "ଉତ୍ପାଦ ପ୍ରକାର |",
    "discount": "ରିହାତି",
    "rate": "ମୂଲ୍ୟାୟନ",
    "rate_count": "ମୂଲ୍ୟାୟନ ସଂଖ୍ୟା",
    "category": "ବର୍ଗ",
    "product": "ଉତ୍ପାଦ",
    "body": "ବିଷୟବସ୍ତୁ",
    "card_type": "କାର୍ଡ ପ୍ରକାର |",
    "card_number": "କାର୍ଡ଼ ସଂଖ୍ୟା",
    "balance": "ସନ୍ତୁଳନ",
    "paid": "ଖର୍ଚ୍ଚ ହୋଇଥିବା ପରିମାଣ",
    "currency": "ମୁଦ୍ରା",
    "expire_at": "ସମାପ୍ତି ତାରିଖ",
    "discount_code": "ରିହାତି କୋଡ୍ |",
    "discount_percent": "ରିହାତି",
    "discount_limit": "ରିହାତି ସୀମା |",
    "max_count": "ସର୍ବାଧିକ ଗଣନା",
    "used_count": "ବ୍ୟବହୃତ |",
    "start_date": "ଆରମ୍ଭ ତାରିଖ",
    "end_date": "ଶେଷ ତାରିଖ",
    "total_discount_amount": "ମୋଟ ରିହାତି |",
    "initial_charge": "ପ୍ରାରମ୍ଭିକ ଚାର୍ଜ",
    "total_count": "ମୋଟ ଗଣନା",
    "amount_paid": "ଦେୟ ରାଶି",
    "name": "ନାମ",
    "published": "ପ୍ରକାଶିତ |",
    "visits": "ପରିଦର୍ଶନ |",
    "color": "ରଙ୍ଗ",
    "landing_page": "ଅବତରଣ ପୃଷ୍ଠା |",
    "enable": "ସକ୍ଷମ କରନ୍ତୁ |",
    "fix_commission": "ସ୍ଥିର ଆୟୋଗ |",
    "percent_commission": "ଶତ ପ୍ରତିଶତ କମିଶନ |",
    "payment_at": "ଦେୟ ତାରିଖ",
    "issued_at": "ପ୍ରକାଶ ତାରିଖ",
    "payment": "ଦେୟ",
    "website": "ୱେବସାଇଟ୍",
    "email": "ଇମେଲ୍ କରନ୍ତୁ |",
    "user": "ଉପଯୋଗକର୍ତ୍ତା |",
    "code": "କୋଡ୍",
    "schedule_at": "କାର୍ଯ୍ୟସୂଚୀ ତାରିଖ |",
    "sender": "ପ୍ରେରକ",
    "in_que": "ଧାଡିରେ |",
    "sent": "ପଠାଯାଇଛି",
    "shop": "ଦୋକାନ କରନ୍ତୁ |",
    "quantity": "ପରିମାଣ",
    "amount": "ପରିମାଣ",
    "jobs": "ଚାକିରି ଗଣନା |",
    "success": "ସଫଳତା ଗଣନା",
    "fail": "ବିଫଳ ଗଣନା",
    "distance": "ଦୂରତା |",
    "duration": "ଅବଧି",
    "reset_at": "ତାରିଖ ପୁନ Res ସେଟ୍ କରନ୍ତୁ |",
    "delivery_person": "ବ୍ୟକ୍ତି",
    "delivery_service": "ସେବା",
    "date": "ତାରିଖ",
    "order": "ଅର୍ଡର |",
    "order_id": "ଅର୍ଡର ID",
    "status": "ସ୍ଥିତି",
    "price": "ମୂଲ୍ୟ",
    "count": "ଗଣନା କର |",
    "final_price": "ଅନ୍ତିମ ମୂଲ୍ୟ |",
    "charge": "ଚାର୍ଜ",
    "mention": "ଉଲ୍ଲେଖ କରନ୍ତୁ |",
    "officer": "ଅଧିକାରୀ",
    "registered": "ପଞ୍ଜିକୃତ |",
    "purchased": "କିଣାଯାଇଛି",
    "sex": "ଲିଙ୍ଗ"
  },
  "search_box": {
    "result": "ସନ୍ଧାନ ଫଳାଫଳ |",
    "tips": "ଉତ୍ପାଦ ଏବଂ ବର୍ଗଗୁଡିକ ସନ୍ଧାନ କରନ୍ତୁ |",
    "label": "ସନ୍ଧାନ ...",
    "category": "ବର୍ଗ"
  },
  "lead_status": {
    "physical_fast_delivery": "ତତକ୍ଷଣାତ୍ ବିତରଣ |",
    "physical_under_24h_delivery": "ପରବର୍ତ୍ତୀ {lead} ଘଣ୍ଟା ମଧ୍ୟରେ ବିତରଣ କରନ୍ତୁ |",
    "physical_over_24h_delivery": "ପରବର୍ତ୍ତୀ {days} ଦିନରୁ ପ୍ରସ୍ତୁତି ଏବଂ ଦାଖଲ |",
    "virtual_fast_prepare": "ତତକ୍ଷଣାତ୍ ବିତରଣ |",
    "virtual_under_24h": "ପରବର୍ତ୍ତୀ {lead} ଘଣ୍ଟା ମଧ୍ୟରେ କରାଯିବ |",
    "virtual_over_24h": "ପରବର୍ତ୍ତୀ {days} ଦିନରୁ କରାଯିବ |"
  },
  "return_request_state": {
    "pending": "ବିଚାରାଧୀନ ଅଛି |",
    "accepted": "ନିଶ୍ଚିତ ହୋଇଛି",
    "rejected": "ପ୍ରତ୍ୟାଖ୍ୟାନ"
  },
  "return_order_reason": {
    "physical": {
      "U1": "ଉତ୍ପାଦର ମେଳ ଖାଉ ନାହିଁ |",
      "U2": "ସିପିଂ ପ୍ୟାକେଜରେ କ product ଣସି ଉତ୍ପାଦ ନାହିଁ |",
      "U3": "ପ୍ୟାକେଜ୍ କିମ୍ବା ଉତ୍ପାଦ ଭାଙ୍ଗିବା |",
      "U4": "ପ୍ୟାକେଜ୍ କିମ୍ବା କ୍ରମିକ ନମ୍ବର ଟ୍ୟାମ୍ପରିଂ |",
      "U5": "ପାର୍ସଲରୁ କିଛି ଆଇଟମ୍ ନିଖୋଜ |",
      "U6": "ଉତ୍ପାଦ ମୂଳ ନୁହେଁ |",
      "U7": "ଉତ୍ପାଦ ନିର୍ଦ୍ଦିଷ୍ଟତା ପୂରଣ କରେ ନାହିଁ |"
    }
  },
  "image_uploader": {
    "label": "<u>ଫାଇଲ୍ ଡ୍ରାଗ୍ ଏବଂ ଡ୍ରପ୍ କିମ୍ବା ସିଲେକ୍ଟ କରନ୍ତୁ |</u>",
    "max_size": "ସର୍ବାଧିକ ଅନୁମତି ପ୍ରାପ୍ତ ଆକାର: {size}"
  },
  "timespan": {
    "Morning": "8am - 12pm",
    "Evening": "ମଧ୍ୟାହ୍ନ 12 ରୁ 6 ଟା",
    "Night": "6pm-12pm",
    "Instant": "ତତକ୍ଷଣାତ୍ ପୋଷ୍ଟ |"
  },
  "week_day": {
    "Saturday": "ଶନିବାର",
    "Sunday": "ରବିବାର",
    "Monday": "ସୋମବାର",
    "Tuesday": "ମଙ୍ଗଳବାର |",
    "Wednesday": "ବୁଧବାର",
    "Thursday": "ଗୁରୁବାର",
    "Friday": "ଶୁକ୍ରବାର |"
  },
  "payment_form": {
    "title": "ଦେୟ ପଦ୍ଧତି ଚୟନ କରନ୍ତୁ |",
    "gift_cards_input": "ଉପହାର କାର୍ଡ |",
    "gift_cards_input_empty": "କ gift ଣସି ଉପହାର କାର୍ଡ ମିଳିଲା ନାହିଁ ..",
    "more": "ଅନ୍ୟମାନେ |",
    "pay_amount_by_gift_cards": "ଚାର୍ଜ କାର୍ଡ ଦେୟ |",
    "select_payment_method": "ନିମ୍ନଲିଖିତ ବିକଳ୍ପଗୁଡ଼ିକରୁ ଆପଣଙ୍କର ଦେୟ ପଦ୍ଧତି ବାଛନ୍ତୁ |",
    "payment_amount_remained": "ଅବଶିଷ୍ଟ ଦେୟ ରାଶି",
    "payment_amount": "ଦେୟ ରାଶି",
    "all_paid_by_gift_cards": "ଅଭିନନ୍ଦନ, ଆପଣଙ୍କୁ ଏହି ଅର୍ଡର ପାଇଁ ଦେୟ ଦେବାକୁ ପଡିବ ନାହିଁ ╏ ଗିଫ୍ଟ କାର୍ଡ କୀ ସହିତ ପେ ଦବାନ୍ତୁ |",
    "pay_by_gift_cards_action": "ଚାର୍ଜ କାର୍ଡ ସହିତ ଅର୍ଡର ଦିଅ |",
    "order_free_payment": "ଅଭିନନ୍ଦନ, ତୁମର ଅର୍ଡର ମାଗଣା!",
    "order_free_payment_action": "ବର୍ତ୍ତମାନ ମାଗଣା ଅର୍ଡର କରନ୍ତୁ |",
    "qr": {
      "address": "ଦେୟ ଠିକଣା",
      "amount": "ପରିମାଣ"
    }
  },
  "discount_input": {
    "limit": "{percent}% ରିହାତି {limit} {currency} ପର୍ଯ୍ୟନ୍ତ",
    "action": "ରିହାତି କୋଡ୍ ଯୋଡନ୍ତୁ |",
    "code_input": "ରିହାତି କୋଡ୍ |",
    "notifications": {
      "add_success": "ଅଭିନନ୍ଦନ, ବ valid ଧ ରିହାତି କୋଡ୍ |"
    }
  },
  "gift_card": {
    "inactive": "କାର୍ଡ ଅକ୍ଷମ ହୋଇଛି |",
    "expire": "ସମାପ୍ତି",
    "transfer": "ସ୍ଥାନାନ୍ତର |",
    "send_to_friend": "ସାଙ୍ଗକୁ ପଠାନ୍ତୁ |"
  },
  "count_down": {
    "days": "ଦିନ",
    "hours": "ଘଣ୍ଟା |",
    "minutes": "ମିନିଟ୍",
    "seconds": "ସେକେଣ୍ଡ୍ |"
  },
  "gift_status": {
    "Unpaid": "ରସିଦର ଅପେକ୍ଷାରେ",
    "Paid": "ଦେୟ",
    "Rejected": "ପ୍ରତ୍ୟାଖ୍ୟାନ",
    "Canceled": "ବାତିଲ"
  },
  "gift_program_status": {
    "Airdrop": "ଦେୟ ବ୍ୟବସ୍ଥା",
    "Advertising": "ବିଜ୍ଞାପନ",
    "PersonalGift": "ବ୍ୟକ୍ତିଗତ ଉପହାର |",
    "ShopGift": "ଉପହାର ଦୋକାନ"
  },
  "currency_selector": {
    "label": "ମୁଦ୍ରା"
  },
  "need_login": {
    "title": "ଭିତରକୁ ଯାଉ",
    "login_sms": "SMS ଲଗଇନ୍ |",
    "login_google": "ଗୁଗୁଲ୍ ସହିତ ଲଗ୍ଇନ୍ କରନ୍ତୁ |",
    "login_facebook": "ଫେସବୁକ୍ ସହିତ ଲଗ୍ଇନ୍ କରନ୍ତୁ |",
    "login_account": "ସେଲଡୋନ ଦ୍ୱାରା ଲଗଇନ୍ କରନ୍ତୁ |",
    "register": "ନୂତନ ବ୍ୟବହାରକାରୀ? ବର୍ତ୍ତମାନ ପଞ୍ଜିକରଣ କରନ୍ତୁ।",
    "mobile_input": "ଆପଣଙ୍କର ମୋବାଇଲ୍ ପ୍ରବେଶ କରନ୍ତୁ |",
    "verification_code": "ପ୍ରମାଣ ସଂକେତ",
    "msg_title": "ହାଏ,",
    "msg_body": "ଦୟାକରି ଲଗଇନ୍ କରନ୍ତୁ ╏ ଏହା ମାତ୍ର କିଛି ସେକେଣ୍ଡ ନେଇଥାଏ |",
    "login_apple": "ଆପଲ୍ ସହିତ ଲଗ୍ଇନ୍ କରନ୍ତୁ |",
    "login_email": "ଇମେଲ ଦ୍ୱାରା ଲଗଇନ୍ କରନ୍ତୁ |",
    "email_login_step_1": "ଦୟାକରି ଏକ ବ email ଧ ଇମେଲ୍ ଠିକଣା ପ୍ରଦାନ କରନ୍ତୁ, ଏବଂ ଆମେ ଏହାକୁ ଲଗ୍ଇନ୍ କୋଡ୍ ପଠାଇବୁ ╏ କ registration ଣସି ପଞ୍ଜୀକରଣ ଆବଶ୍ୟକ ନାହିଁ |",
    "email_login_step_2": "ଆପଣ ନିଶ୍ଚିତ କି ଆପଣ ଆପଣଙ୍କର ଇମେଲ୍ ଠିକଣା ସଠିକ୍ ଭାବରେ ପ୍ରବେଶ କରିଛନ୍ତି? ପ୍ରଦାନ କରାଯାଇଥିବା ଇମେଲକୁ ଆମେ ଲଗଇନ୍ କୋଡ୍ ପଠାଇବୁ, ତେଣୁ ଦୟାକରି ଏହାର ସଠିକତା ନିଶ୍ଚିତ କରନ୍ତୁ |",
    "email_login_step_3": "ଆମେ ଆପଣଙ୍କ ଇମେଲକୁ ଏକ କୋଡ୍ ପଠାଇଛୁ ╏ ଦୟାକରି ଧ୍ୟାନ ଦିଅନ୍ତୁ ଯେ କୋଡ୍ 10 ମିନିଟରେ ସମାପ୍ତ ହେବ |"
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "5 ବର୍ଷ ସୁନା ଷ୍ଟୋର୍ |"
    },
    "GOLDEN_2YEAR": {
      "name": "4 ବର୍ଷ ସୁନା ଷ୍ଟୋର୍ |"
    },
    "GOLDEN_3YEAR": {
      "name": "3 ବର୍ଷ ସୁନା ଷ୍ଟୋର୍ |"
    },
    "GOLDEN_4YEAR": {
      "name": "2 ବର୍ଷ ସୁନା ଷ୍ଟୋର୍ |"
    },
    "GOLDEN_5YEAR": {
      "name": "1 ବର୍ଷ ସୁନା ଷ୍ଟୋର୍ |"
    },
    "TOKEN_OWNER_1M": {
      "name": "ସୁବର୍ଣ୍ଣ ନିବେଶକ |"
    },
    "TOKEN_OWNER_10M": {
      "name": "ହୀରା ନିବେଶକ |"
    },
    "TOKEN_OWNER_100M": {
      "name": "ରୁବି ନିବେଶକ |"
    },
    "COMMUNITY_LOYAL": {
      "name": "ଯୋଗାଯୋଗ ନେଟୱାର୍କର ସୁପ୍ରିମୋ ସମ୍ପ୍ରଦାୟର ସଦସ୍ୟ |"
    },
    "GOLD_SUPPLIER": {
      "name": "ସୁନା ଯୋଗାଣକାରୀ |"
    },
    "GOLD_SELLER": {
      "name": "ସୁନା ଡିଲର |"
    },
    "CONTENT_SUPERMAN": {
      "name": "ଶୀର୍ଷ ବିଷୟବସ୍ତୁ ଉତ୍ପାଦକ |"
    },
    "NINJA": {
      "name": "ନିଞ୍ଜା |"
    },
    "STAR": {
      "name": "ତାରା |"
    },
    "GUARDIAN": {
      "name": "ଉତ୍ତମ ଗ୍ରାହକ ସେବା |"
    },
    "KING": {
      "name": "ବଜାରର ରାଜା |"
    }
  },
  "cookie": {
    "title": "ଏହି ୱେବସାଇଟ୍ କୁକିଜ୍ ବ୍ୟବହାର କରେ |",
    "message": "ଉପଭୋକ୍ତା ଅଭିଜ୍ଞତା ବୃଦ୍ଧି ପାଇଁ ଏହି ୱେବସାଇଟ୍ କୁକିଜ୍ ବ୍ୟବହାର କରେ ╏ ଆମର ୱେବସାଇଟ୍ ବ୍ୟବହାର କରି ଆପଣ ଆମର କୁକି ନୀତି ଅନୁଯାୟୀ ସମସ୍ତ କୁକିଜକୁ ରାଜି ହୁଅନ୍ତି |",
    "preferences_action": "ପସନ୍ଦଗୁଡିକ ପରିଚାଳନା କରନ୍ତୁ |",
    "agree_action": "ମୁଁ ସହମତ"
  },
  "basket_item_message": {
    "title": "ଏହି ଆଇଟମ୍ ପାଇଁ ଆବଶ୍ୟକ ସୂଚନା |",
    "save_actions": "ବାର୍ତ୍ତା ସଞ୍ଚୟ କରନ୍ତୁ |",
    "notifications": {
      "success": "ତୁମର ଇନପୁଟ୍ ଡାଟା ସେଭ୍ ହୋଇଛି |"
    },
    "product_inputs_preview_message": "ଏହି କଷ୍ଟୋମାଇଜେସନ୍ ବିକଳ୍ପଗୁଡ଼ିକ ତୁମର ଅର୍ଡର ହୋଇଥିବା ଉତ୍ପାଦ ପାଇଁ ଉପଲବ୍ଧ ╏ ଥରେ ଆଇଟମ୍ ଆପଣଙ୍କ କାର୍ଟରେ ଯୋଡି ହୋଇଗଲେ, ଆପଣ ଏଠାରେ ସଂଶୋଧନ କରିବାକୁ ସମର୍ଥ ହେବେ |"
  },
  "faq": {
    "faq": "ପ୍ରାୟତଃ ପଚରାଯାଇଥିବା ପ୍ରଶ୍ନ",
    "title": "ପ୍ରଶ୍ନ ଏବଂ ଉତ୍ତର",
    "sub_title": "ତୁମେ ଯାହା କରିବାକୁ ଆମକୁ କହିଲ |",
    "message": "ନିମ୍ନରେ ଥିବା ଉତ୍ତରଗୁଡ଼ିକ ମଧ୍ୟରେ ଆପଣଙ୍କ ପ୍ରଶ୍ନର ଉତ୍ତର ଖୋଜ ╏ ପ୍ରଶ୍ନଗୁଡିକ ଉତ୍ତରହୀନ ରହିଲେ ଆମକୁ ପଚାର |",
    "add_question_action": "ନୂତନ ପ୍ରଶ୍ନ ପଚାର |",
    "read_more": "ଅଧିକ ପଢ ..",
    "load_more": "ଅଧିକ ପ୍ରଶ୍ନ ..",
    "main_page": "FAQ ମୁଖ୍ୟ ପୃଷ୍ଠା |",
    "add_new": "ନୂତନ ପ୍ରଶ୍ନ ଉପସ୍ଥାପନ କରନ୍ତୁ |",
    "login_alert": "ଏକ ପ୍ରଶ୍ନ ପଚାରିବାକୁ ଲଗ୍ ଇନ୍ କରନ୍ତୁ |",
    "question_input": "ପ୍ରଶ୍ନ |",
    "question_input_placeholder": "ତୁମର ପ୍ରଶ୍ନ ପଚାର |",
    "notifications": {
      "success_add": "ତୁମର ପ୍ରଶ୍ନ ସଫଳତାର ସହିତ ଦାଖଲ ହେଲା |"
    }
  },
  "rating_labels": [
    "ବହୁତ ଖରାପ |",
    "ଖରାପ",
    "ସାଧାରଣ",
    "ଭଲ",
    "ଉତ୍କୃଷ୍ଟ |"
  ],
  "map_view": {
    "address_detail": "ଠିକଣା ବିବରଣୀ",
    "change": "ପରିବର୍ତ୍ତନ କରନ୍ତୁ |",
    "select": "ଚୟନ କରନ୍ତୁ |",
    "not_found_address": "କ value ଣସି ମୂଲ୍ୟ ମିଳିଲା ନାହିଁ |",
    "enter_address_hint": "ଗନ୍ତବ୍ୟସ୍ଥଳ ଠିକଣା ପ୍ରବେଶ କରନ୍ତୁ |",
    "enter_your_address": "ଆପଣଙ୍କର ଠିକଣା ପ୍ରବେଶ କରନ୍ତୁ |",
    "postal_code": "ପୋଷ୍ଟକୋଡ୍",
    "phone_input": "ଫୋନ୍ {type}",
    "building_number": "ବିଲଡିଂ ନମ୍ବର |",
    "building_unit": "ୟୁନିଟ୍",
    "full_name_input": "ପୂର୍ଣ୍ଣ ନାମ {type}",
    "save_detail_action": "ବିବରଣୀ ସଞ୍ଚୟ କରନ୍ତୁ |",
    "more_detail_input": "ଅଧିକ ବର୍ଣ୍ଣନା",
    "add_address_to_list": "ତାଲିକାରେ ଠିକଣା ଯୋଡନ୍ତୁ |",
    "address_title_input": "ଠିକଣା ଲେବଲ୍ (ଆବଶ୍ୟକ)",
    "notifications": {
      "save_in_list": "ଏହି ଠିକଣା ଏହାର ସମସ୍ତ ବିବରଣୀ ସହିତ ତୁମର ତାଲିକାରେ ସେଭ୍ ହୋଇଛି |",
      "edit_success": "{ଟାଇଟଲ୍ in ରେ ସେଭ୍ ହୋଇଥିବା ନୂତନ ଠିକଣା ମୂଲ୍ୟ |"
    },
    "delete_address_dialog": {
      "title": "ଠିକଣା ବିଲୋପ କରନ୍ତୁ |",
      "message": "ଆପଣ ନିଶ୍ଚିତ କି ଆପଣ ଏହି ଠିକଣା ବିଲୋପ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?",
      "action": "ଠିକଣା ହଟାନ୍ତୁ |"
    }
  },
  "comment_manager": {
    "can_not_edit": "ଏହି ମନ୍ତବ୍ୟକୁ ସଂପାଦନ କରିପାରିବେ ନାହିଁ!",
    "comment_input_empty": "ବାର୍ତ୍ତା ପାଠ ଖାଲି ଅଛି!",
    "article_not_saved": "ପ୍ରବନ୍ଧକୁ ସଂରକ୍ଷଣ କରନ୍ତୁ!"
  },
  "wheel_fortune": {
    "title": "ଖେଳ ଏବଂ ଜିତ |",
    "message": "ପ୍ରତ୍ୟେକ ଖେଳର ମୂଲ୍ୟ ହେଉଛି 10 ଟି ଚିପ୍ସ ╏ ଆପଣଙ୍କର ବର୍ତ୍ତମାନ {chips} ଚିପ୍ ଅଛି ╏ ଷ୍ଟୋରରୁ କ୍ରୟ କରି ଅଧିକ ଚିପ୍ ପ୍ରାପ୍ତ କରନ୍ତୁ |",
    "win_message": "ଅଭିନନ୍ଦନ, ତୁମେ ଜିତ!",
    "lost_message": "ଦୁ Sorry ଖିତ, ଆପଣ ଖେଳ ହରାଇଛନ୍ତି |",
    "try_again": "ଆପଣ ପୁନର୍ବାର ଚେଷ୍ଟା କରିପାରିବେ |"
  },
  "json": {
    "add": "ସଂରଚନା ତଥ୍ୟ ଯୋଡନ୍ତୁ |",
    "add_message": "ନୂତନ ସଂରଚନା ତଥ୍ୟ ସୃଷ୍ଟି କରନ୍ତୁ |",
    "structures": "ଗଠନ",
    "book": {
      "title": "ବୁକ୍ କରନ୍ତୁ |",
      "desc": "ବୁକ୍ କ୍ରିୟାଗୁଡ଼ିକ ଯାହା ଉପଭୋକ୍ତାମାନଙ୍କୁ ସନ୍ଧାନ ଫଳାଫଳରୁ ସିଧାସଳଖ ପାଇଥିବା ବହି କିଣିବାକୁ ସକ୍ଷମ କରେ |"
    },
    "occupation": {
      "title": "ଆନୁମାନିକ ଦରମା |",
      "desc": "ବେତନ ଆକଳନ ବିଷୟରେ ସୂଚନା, ଯେପରିକି ବେତନ ପରିସର ଏବଂ ଚାକିରି ପ୍ରକାର ପାଇଁ ଅଞ୍ଚଳ ଭିତ୍ତିକ ବେତନ ହାରାହାରି, ଗୁଗୁଲରେ ଚାକିରି ଖୋଜ ଅଭିଜ୍ଞତାରେ ପ୍ରଦର୍ଶିତ |"
    },
    "course": {
      "title": "ପାଠ୍ୟକ୍ରମ",
      "desc": "ଏକ ପ୍ରଦାନକାରୀ-ନିର୍ଦ୍ଦିଷ୍ଟ ତାଲିକାରେ ଦେଖାଯାଉଥିବା ଶିକ୍ଷାଗତ ପାଠ୍ୟକ୍ରମ ╏ ପାଠ୍ୟକ୍ରମଗୁଡ଼ିକ ପାଠ୍ୟକ୍ରମର ଆଖ୍ୟା, ପ୍ରଦାନକାରୀ ଏବଂ ଏକ ସଂକ୍ଷିପ୍ତ ବର୍ଣ୍ଣନା ଅନ୍ତର୍ଭୁକ୍ତ କରିପାରେ |"
    },
    "howto": {
      "title": "କେମିତି",
      "desc": "ଭିଡିଓ, ପ୍ରତିଛବି ଏବଂ ପାଠ୍ୟକୁ ଦର୍ଶାଇ ଏକ କାର୍ଯ୍ୟକୁ ସଫଳତାର ସହିତ ସମାପ୍ତ କରିବାକୁ ଷ୍ଟେପଗୁଡିକର ଏକ ସେଟ୍ ମାଧ୍ୟମରେ ଉପଭୋକ୍ତାମାନଙ୍କୁ କିପରି ଚାଲିବ |"
    },
    "recipe": {
      "title": "ରେସିପି |",
      "desc": "ରେସିପି ଯାହା ଏକ ବ୍ୟକ୍ତିଗତ ସମୃଦ୍ଧ ଫଳାଫଳ କିମ୍ବା ଏକ ହୋଷ୍ଟ କାରୁସେଲର ଅଂଶ ଭାବରେ ପ୍ରଦର୍ଶିତ ହୁଏ |"
    }
  },
  "support": {
    "Financial": "ଆର୍ଥିକ",
    "Technical": "ଯାନ୍ତ୍ରିକ |",
    "Advisor": "ପରାମର୍ଶଦାତା |"
  },
  "condition": {
    "new": "ନୂତନ",
    "refurbished": "ନବୀକରଣ",
    "used": "ବ୍ୟବହୃତ |",
    "used_fair": "ବ୍ୟବହୃତ ମେଳା |",
    "used_good": "ଭଲ ବ୍ୟବହୃତ |",
    "used_like_new": "ନୂଆ ପରି ବ୍ୟବହୃତ |"
  },
  "variant_filter": {
    "title": "ଉତ୍ପାଦ ଭାରିଆଣ୍ଟ ଫିଲ୍ଟର୍ |",
    "only_available": "ମହଜୁଦ ଅଛି"
  },
  "service": {
    "task": {
      "title": "କାର୍ଯ୍ୟଗୁଡ଼ିକ",
      "message": "ଏହି ସେବାରେ କରାଯାଇଥିବା କାର୍ଯ୍ୟଗୁଡ଼ିକର ତାଲିକା |"
    },
    "appointment": {
      "title": "ନିଯୁକ୍ତି",
      "message": "ଆପଣଙ୍କ ପାଇଁ ସଠିକ୍ ଦିନ ଏବଂ ଘଣ୍ଟା ଉପରେ ଆଧାର କରି ନିମ୍ନଲିଖିତ ସମୟରୁ ସପ୍ତାହର ସମୟ ବାଛନ୍ତୁ |"
    },
    "booking": {
      "title": "ବୁକିଂ",
      "message": "ନିମ୍ନରେ ଥିବା କ୍ୟାଲେଣ୍ଡରରେ ଆପଣ ସଂରକ୍ଷଣ କରିବାକୁ ଚାହୁଁଥିବା ଦିନର ସମୟ ଅବଧି ନିର୍ଦ୍ଦିଷ୍ଟ କରନ୍ତୁ |"
    },
    "subscription": {
      "title": "ସଦସ୍ୟତା"
    },
    "charge": {
      "title": "ଚାର୍ଜ"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "ସ୍ଥିର ମୂଲ୍ୟ",
      "message": "ଏହି ପ୍ରକାରର ମୂଲ୍ୟ ନିର୍ଧାରଣରେ, ଉତ୍ପାଦର ମୂଲ୍ୟ ଏକ ନିର୍ଦ୍ଦିଷ୍ଟ ପରିମାଣ ଅଟେ ଏବଂ କ୍ରେତା ମୂଲ୍ୟ ହିସାବ କରିବାକୁ ଅନୁରୋଧ କରିବାର କ is ଣସି ଆବଶ୍ୟକତା ନାହିଁ |"
    },
    "ESTIMATION": {
      "title": "ଆକଳନ ମୂଲ୍ୟ",
      "message": "ଏକ ଅର୍ଡର ଦେବାବେଳେ ବିକ୍ରେତାଙ୍କ ଦ୍ products ାରା ଉତ୍ପାଦ ଏବଂ ସେବାଗୁଡିକର ମୂଲ୍ୟ କିଛି ପରିମାଣରେ ହିସାବ କରାଯିବ, ସେବା ସମୟରେ ଦେୟ ଇନଭଏସ୍ ପରିବର୍ତ୍ତନ କିମ୍ବା ଯୋଗ କରାଯାଇପାରିବ |"
    },
    "AGREEMENT": {
      "title": "ଚୁକ୍ତିନାମା ମୂଲ୍ୟ",
      "message": "ଅର୍ଡର ଦିଆଯିବା ପରେ ବିକ୍ରେତାଙ୍କ ଦ୍ the ାରା ଉତ୍ପାଦ କିମ୍ବା ସେବାଗୁଡିକର ଅନ୍ତିମ ମୂଲ୍ୟ ପରିବର୍ତ୍ତନ ହେବ ନାହିଁ |"
    },
    "BID": {
      "title": "ବିଡ୍ / ନିଲାମ |",
      "message": "ସମ୍ଭାବ୍ୟ କ୍ରେତାମାନେ ଏହି ଉତ୍ପାଦକୁ ସର୍ବାଧିକ ବିଡ୍ ମୂଲ୍ୟରେ ବିକ୍ରି କରିବେ |"
    }
  },
  "map": {
    "title": "ଉତ୍ପାଦ ଗ୍ରହଣ କରିବାକୁ ଗନ୍ତବ୍ୟସ୍ଥଳ |",
    "confirm": "ଅବସ୍ଥାନ ସେଟ୍ କରନ୍ତୁ |",
    "address": "ଗନ୍ତବ୍ୟସ୍ଥଳ",
    "receptor": "ଗ୍ରହଣକାରୀ"
  },
  "ShopBots": {
    "telegram": "ଟେଲିଗ୍ରାମ |"
  },
  "article_tags": {
    "title": "ବିଷୟବସ୍ତୁ ଟ୍ୟାଗ୍ସ |",
    "tags_input": "ଟ୍ୟାଗ୍ସ |",
    "tags_input_message": "ଏହି ପ୍ରବନ୍ଧର ଟ୍ୟାଗ୍ ତାଲିକା |",
    "notification": {
      "add_success": "ଟ୍ୟାଗ୍ ଯୋଡା ଯାଇଛି |"
    }
  },
  "difficulties": {
    "very_complicated": "ବହୁତ ଜଟିଳ |",
    "hard": "କଠିନ |",
    "intermediate": "ମଧ୍ୟବର୍ତ୍ତୀ",
    "easy": "ସହଜ"
  },
  "billing_period": {
    "Daily": "ଦ Daily ନିକ |",
    "Weekly": "ସାପ୍ତାହିକ",
    "Monthly": "ମାସିକ",
    "Every3Months": "ପ୍ରତି 3 ମାସରେ |",
    "Every6Months": "ପ୍ରତି 6 ମାସରେ |",
    "Yearly": "ବାର୍ଷିକ"
  },
  "buyer_rating_statement": {
    "between1_2": "ଭଲ ନୁହେଁ!",
    "between2_3": "ଠିକ୍ ଅଛି!",
    "between3_4": "ଲୋକମାନେ ଏହାକୁ ପସନ୍ଦ କରନ୍ତି!",
    "between4_5": "ଲୋକମାନେ ଏହାକୁ ଭଲ ପାଆନ୍ତି!"
  },
  "seasons": {
    "spring": "ବସନ୍ତ |",
    "summer": "ଗ୍ରୀଷ୍ମ",
    "autumn": "ଶରତ",
    "winter": "ଶୀତ |"
  }
};