export default {
  "currency_default": "USD",
  "language_default": "en",
  "selldone": "ਵੇਚਿਆ",
  "store": "ਸਟੋਰ",
  "not_exist": "ਮੌਜੂਦ ਨਹੀਂ ਹੈ",
  "error": "ਗਲਤੀ",
  "active": "ਕਿਰਿਆਸ਼ੀਲ",
  "inactive": "ਅਕਿਰਿਆਸ਼ੀਲ",
  "required_value": "ਲੋੜੀਂਦੇ ਮੁੱਲ",
  "original_warranty": "ਮੂਲ ਉਤਪਾਦ ਦੀ ਗਾਰੰਟੀ",
  "return_warranty_days": "{days} ਵਾਪਸੀ ਦੀ ਗਰੰਟੀ ਦੇ ਦਿਨ",
  "no_return_warranty": "ਕੋਈ ਵਾਪਸੀ ਨਹੀਂ",
  "reed_agree_terms": "ਮੈਂ ਵਰਤੋਂ ਦੀਆਂ ਸ਼ਰਤਾਂ ਅਤੇ ਗੋਪਨੀਯਤਾ ਨੀਤੀ ਨੂੰ ਪੜ੍ਹ ਲਿਆ ਹੈ ਅਤੇ ਉਹਨਾਂ ਨਾਲ ਸਹਿਮਤ ਹਾਂ।",
  "commons": {
    "Currency": "ਮੁਦਰਾ",
    "COD": "COD",
    "State": "ਰਾਜ",
    "Price": "ਕੀਮਤ",
    "order_price": "ਆਰਡਰ ਦੀ ਮਾਤਰਾ",
    "VAT": "VAT",
    "Discount": "ਛੂਟ",
    "In_Stock": "ਭੰਡਾਰ ਵਿੱਚ",
    "Variants": "ਰੂਪ",
    "No_variants": "ਕੋਈ ਰੂਪ ਨਹੀਂ",
    "all": "ਸਾਰੇ",
    "today": "ਅੱਜ",
    "yesterday": "ਕੱਲ੍ਹ",
    "license": "ਲਾਇਸੰਸ",
    "home": "ਘਰ",
    "support": "ਸਪੋਰਟ",
    "messages": "ਸੁਨੇਹੇ",
    "no_message": "ਕੋਈ ਸੁਨੇਹਾ ਨਹੀਂ",
    "empty": "ਖਾਲੀ",
    "phone": "ਫ਼ੋਨ",
    "address": "ਪਤਾ",
    "name": "ਨਾਮ",
    "password": "ਪਾਸਵਰਡ",
    "email": "ਈ - ਮੇਲ",
    "mobile": "ਮੋਬਾਈਲ",
    "login": "ਲਾਗਿਨ",
    "register": "ਰਜਿਸਟਰ",
    "select_account": "ਖਾਤਾ ਚੁਣੋ",
    "online": "ਔਨਲਾਈਨ",
    "offline": "ਔਫਲਾਈਨ",
    "finish": "ਸਮਾਪਤ",
    "finished": "ਸਮਾਪਤ",
    "preview": "ਝਲਕ",
    "free": "ਮੁਫ਼ਤ",
    "free_completely": "ਪੂਰੀ ਤਰ੍ਹਾਂ ਮੁਫਤ ਗਾਹਕੀ",
    "fee": "ਫੀਸ",
    "month": "ਮਹੀਨਾ",
    "months": "ਮਹੀਨੇ",
    "faq": "ਅਕਸਰ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ",
    "question": "ਸਵਾਲ",
    "answer": "ਜਵਾਬ",
    "create_date": "ਤਾਰੀਖ ਬਣਾਓ",
    "update_date": "ਅੱਪਡੇਟ ਮਿਤੀ",
    "start_date": "ਤਾਰੀਖ ਸ਼ੁਰੂ",
    "end_date": "ਸਮਾਪਤੀ ਮਿਤੀ",
    "social": "ਸਮਾਜਿਕ",
    "total": "ਕੁੱਲ",
    "orders": "ਆਰਡਰ",
    "sessions": "ਸੈਸ਼ਨ",
    "product_views": "ਉਤਪਾਦ ਦ੍ਰਿਸ਼",
    "add_to_carts": "ਗੱਡੀਆਂ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ",
    "checkouts": "ਕਮਰਾ ਛੱਡ ਦਿਓ",
    "payments": "ਭੁਗਤਾਨ",
    "organic_search": "ਜੈਵਿਕ ਖੋਜ",
    "other": "ਹੋਰ",
    "landing_page": "ਲੈਂਡਿੰਗ ਪੰਨਾ",
    "discount_code": "ਛੋਟ ਕੋਡ",
    "total_sell": "ਕੁੱਲ ਵਿਕਰੀ",
    "details": "ਵੇਰਵੇ",
    "currency": "ਮੁਦਰਾ",
    "amount": "ਦੀ ਰਕਮ",
    "published": "ਪ੍ਰਕਾਸ਼ਿਤ",
    "draft": "ਡਰਾਫਟ",
    "save_changes": "ਕੀਤੇ ਗਏ ਬਦਲਾਅ ਸੁਰੱਖਿਅਤ ਕਰੋ",
    "source": "ਸਰੋਤ",
    "medium": "ਦਰਮਿਆਨਾ",
    "url": "ਯੂਆਰਐਲ",
    "revenue": "ਮਾਲੀਆ",
    "performance": "ਪ੍ਰਦਰਸ਼ਨ",
    "term": "ਮਿਆਦ",
    "content": "ਸਮੱਗਰੀ",
    "session": "ਸੈਸ਼ਨ",
    "product": "ਉਤਪਾਦ",
    "add": "ਸ਼ਾਮਲ ਕਰੋ",
    "checkout": "ਕਮਰਾ ਛੱਡ ਦਿਓ",
    "payment": "ਭੁਗਤਾਨ",
    "more_options": "ਹੋਰ ਵਿਕਲਪ",
    "full_name": "ਪੂਰਾ ਨਾਂਮ",
    "tel": "ਟੈਲੀ",
    "about_me": "ਮੇਰੇ ਬਾਰੇ ਵਿੱਚ",
    "request_checking": "ਜਾਂਚ ਲਈ ਬੇਨਤੀ ਕਰੋ",
    "passport": "ਪਾਸਪੋਰਟ",
    "birthday": "ਜਨਮਦਿਨ",
    "country": "ਦੇਸ਼",
    "city": "ਸ਼ਹਿਰ",
    "gender": "ਲਿੰਗ",
    "offer": "ਪੇਸ਼ਕਸ਼",
    "website": "ਵੈੱਬਸਾਈਟ",
    "apply_for_all_products": "∞ ਸਾਰੇ ਉਤਪਾਦਾਂ ਲਈ ਅਰਜ਼ੀ ਦਿਓ",
    "fix_commission": "ਸਥਿਰ ਕਮਿਸ਼ਨ",
    "percent_commission": "ਪ੍ਰਤੀਸ਼ਤ ਕਮਿਸ਼ਨ",
    "fixed_discount": "ਸਥਿਰ ਛੋਟ",
    "discount_percentage": "ਪ੍ਰਤੀਸ਼ਤ ਛੋਟ",
    "discount_limit": "ਛੂਟ ਸੀਮਾ",
    "no_code": "ਕੋਈ ਕੋਡ ਨਹੀਂ",
    "max_count": "ਵੱਧ ਤੋਂ ਵੱਧ ਗਿਣਤੀ",
    "count_unit": "ਇਕਾਈ",
    "used": "ਵਰਤਿਆ",
    "daily": "ਰੋਜ਼ਾਨਾ",
    "monthly": "ਮਹੀਨਾਵਾਰ",
    "yearly": "ਸਾਲਾਨਾ",
    "state": "ਸਥਿਤੀ",
    "disable": "ਅਸਮਰੱਥ",
    "enable": "ਯੋਗ ਕਰੋ",
    "activation_code": "ਐਕਟੀਵੇਸ਼ਨ ਕੋਡ",
    "quantity": "ਮਾਤਰਾ",
    "no_club": "ਕੋਈ ਕਲੱਬ ਨਹੀਂ",
    "per_order": "ਆਰਡਰ ਪ੍ਰਤੀ",
    "count": "ਗਿਣਤੀ",
    "seconds": "ਸਕਿੰਟ",
    "auto": "ਆਟੋ",
    "title": "ਸਿਰਲੇਖ",
    "message": "ਸੁਨੇਹਾ",
    "width": "ਚੌੜਾਈ",
    "length": "ਲੰਬਾਈ",
    "height": "ਉਚਾਈ",
    "label": "ਲੇਬਲ",
    "click": "ਕਲਿੱਕ ਕਰੋ",
    "bank": "ਬੈਂਕ",
    "default": "ਡਿਫਾਲਟ",
    "role": "ਭੂਮਿਕਾ",
    "user": "ਉਪਭੋਗਤਾ",
    "users": "ਉਪਭੋਗਤਾ",
    "code": "ਕੋਡ",
    "total_payment": "ਕੁੱਲ ਭੁਗਤਾਨ",
    "balance": "ਸੰਤੁਲਨ",
    "chance": "ਮੌਕਾ",
    "free_for_new_users": "ਨਵੇਂ ਉਪਭੋਗਤਾਵਾਂ ਲਈ ਮੁਫਤ",
    "prize_amount": "ਇਨਾਮ ਦੀ ਰਕਮ",
    "win": "ਜਿੱਤ",
    "gift_card": "ਗਿਫ਼ਟ ਕਾਰਡ",
    "discount": "ਛੂਟ",
    "config": "ਸੰਰਚਨਾ",
    "prize": "ਇਨਾਮ",
    "Prizes": "ਇਨਾਮ",
    "result": "ਨਤੀਜਾ",
    "price": "ਕੀਮਤ",
    "lottery": "ਲਾਟਰੀ",
    "coupon": "ਕੂਪਨ",
    "customer_club": "ਗਾਹਕ ਕਲੱਬ",
    "shipping": "ਸ਼ਿਪਿੰਗ",
    "sum": "ਜੋੜ",
    "not_paid": "ਭੁਗਤਾਨ ਨਹੀਂ ਕੀਤਾ ਗਿਆ",
    "category": "ਸ਼੍ਰੇਣੀ",
    "done": "ਹੋ ਗਿਆ",
    "email_from": "ਤੋਂ",
    "subject": "ਵਿਸ਼ਾ",
    "schedule": "ਸਮਾਸੂਚੀ, ਕਾਰਜ - ਕ੍ਰਮ",
    "files_list": "ਫਾਈਲਾਂ ਦੀ ਸੂਚੀ",
    "file_max_size": "ਅਧਿਕਤਮ ਫ਼ਾਈਲ ਆਕਾਰ",
    "value": "ਮੁੱਲ",
    "help": "ਮਦਦ ਕਰੋ",
    "shipping_tax": "ਸ਼ਿਪਿੰਗ ਟੈਕਸ",
    "net_price": "ਸ਼ੁੱਧ ਕੀਮਤ",
    "tax": "ਟੈਕਸ",
    "tax_included": "ਕੀਮਤ ਵਿੱਚ ਸ਼ਾਮਲ",
    "limit": "ਸੀਮਾ",
    "min_purchase": "ਘੱਟੋ-ਘੱਟ ਖਰੀਦਦਾਰੀ",
    "eligible_for": "ਲਈ ਯੋਗ ਹੈ",
    "only_for_first_buy": "ਸਿਰਫ ਪਹਿਲੀ ਖਰੀਦ ਲਈ",
    "one_time_use": "ਇੱਕ ਵਾਰ ਵਰਤ ਸਕਦੇ ਹੋ",
    "period_of_qualify": "ਮਿਆਦ ਦੀ ਵਰਤੋਂ ਸੀਮਾ",
    "no_constraint": "ਕੋਈ ਸੀਮਾ ਨਹੀਂ",
    "timespan": "ਸਮਾਂ ਮਿਆਦ",
    "days": "ਦਿਨ(ਦਿਨ)",
    "weight": "ਭਾਰ",
    "distance": "ਦੂਰੀ",
    "last_status": "ਆਖਰੀ ਸਥਿਤੀ",
    "issued_at": "'ਤੇ ਜਾਰੀ ਕੀਤਾ ਗਿਆ",
    "order": "ਆਰਡਰ",
    "order_detail": "ਆਰਡਰ ਵੇਰਵੇ",
    "percent": "ਪ੍ਰਤੀਸ਼ਤ",
    "applied_count": "ਲਾਗੂ ਗਿਣਤੀ",
    "campaign": "ਮੁਹਿੰਮ",
    "os": "ਆਪਰੇਟਿੰਗ ਸਿਸਟਮ",
    "browser": "ਬਰਾਊਜ਼ਰ",
    "device": "ਡਿਵਾਈਸ",
    "device_ip": "ਡਿਵਾਈਸ ਦਾ IP ਪਤਾ",
    "location": "ਟਿਕਾਣਾ",
    "user_agent": "ਉਪਭੋਗਤਾ ਏਜੰਟ",
    "affiliate": "ਐਫੀਲੀਏਟ",
    "timeline": "ਸਮਾਂਰੇਖਾ",
    "add_note": "ਨੋਟ ਸ਼ਾਮਲ ਕਰੋ",
    "record": "ਰਿਕਾਰਡ",
    "unlimited": "ਅਸੀਮਤ",
    "show_coupons": "ਕੂਪਨ ਦਿਖਾਓ",
    "hide_coupons": "ਕੂਪਨ ਲੁਕਾਓ",
    "service_area": "ਸੇਵਾ ਖੇਤਰ",
    "apps": "ਐਪਸ",
    "plugins": "ਪਲੱਗਇਨ",
    "bots": "ਬੋਟਸ",
    "categories": "ਵਰਗ",
    "products": "ਉਤਪਾਦ",
    "business": "ਕਾਰੋਬਾਰ",
    "personal": "ਨਿੱਜੀ",
    "size": "ਆਕਾਰ",
    "holiday": "ਛੁੱਟੀ",
    "sod": "ਡਿਲਿਵਰੀ 'ਤੇ ਭੁਗਤਾਨ ਕਰੋ",
    "cod": "ਡਿਲੀਵਰੀ 'ਤੇ ਨਕਦ",
    "free_shipping": "ਮੁਫਤ ਸ਼ਿਪਿੰਗ",
    "hours": "ਘੰਟੇ",
    "send_date": "ਸ਼ਿਪਿੰਗ ਮਿਤੀ",
    "deliver_date": "ਪਹੁੰਚਾਉਣ ਦੀ ਮਿਤੀ",
    "return_date": "ਵਾਪਸੀ ਦੀ ਮਿਤੀ",
    "pending": "ਬਕਾਇਆ",
    "delivered": "ਡਿਲੀਵਰ ਕੀਤਾ",
    "returned": "ਵਾਪਸ ਆ",
    "canceled": "ਰੱਦ ਕਰ ਦਿੱਤਾ",
    "shipping_cost": "ਸ਼ਿਪਿੰਗ ਦੀ ਲਾਗਤ",
    "action": "ਕਾਰਵਾਈ",
    "cancel_date": "ਮਿਤੀ ਰੱਦ ਕਰੋ",
    "deliver_in_process": "ਆਰਡਰ ਭੇਜ ਦਿੱਤਾ ਗਿਆ ਹੈ ..",
    "kind": "ਟਾਈਪ ਕਰੋ",
    "detail": "ਵੇਰਵੇ",
    "map": "ਨਕਸ਼ਾ",
    "actions": "ਕਾਰਵਾਈਆਂ",
    "navigation": "ਨੇਵੀਗੇਸ਼ਨ",
    "navigation_app": "ਐਪਲੀਕੇਸ਼ਨ",
    "payment_date": "ਭੁਗਤਾਨ ਦੀ ਮਿਤੀ",
    "duration": "ਮਿਆਦ",
    "bill": "ਬਿੱਲ",
    "delivery_persons": "ਕੋਰੀਅਰਜ਼",
    "delivery_services": "ਡਿਲਿਵਰੀ ਸੇਵਾਵਾਂ",
    "live_view": "ਲਾਈਵ ਦ੍ਰਿਸ਼",
    "cart": "ਕਾਰਟ",
    "priority": "ਤਰਜੀਹ",
    "sufficient_credit": "ਕਾਫ਼ੀ ਕ੍ਰੈਡਿਟ",
    "max_package_size": "ਵੱਧ ਤੋਂ ਵੱਧ ਪੈਕੇਜ ਦਾ ਆਕਾਰ",
    "delay": "ਦੇਰੀ",
    "credit": "ਕ੍ਰੈਡਿਟ",
    "livemode": "ਲਾਈਵ",
    "paused": "ਰੋਕਿਆ ਗਿਆ",
    "debug": "ਡੀਬੱਗ ਕਰੋ",
    "token": "ਟੋਕਨ",
    "status": "ਸਥਿਤੀ",
    "courier": "ਕੋਰੀਅਰ",
    "track": "ਟਰੈਕ",
    "track_order": "ਆਰਡਰ ਟ੍ਰੈਕਿੰਗ",
    "cost": "ਲਾਗਤ",
    "receipt": "ਰਸੀਦ",
    "origin": "ਮੂਲ",
    "destination": "ਮੰਜ਼ਿਲ",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "ਕਾਫ਼ੀ ਸਟਾਕ ਨਹੀਂ ਹੈ!",
    "sub_total": "ਉਪ-ਜੋੜ",
    "customer": "ਗਾਹਕ",
    "delivery": "ਡਿਲਿਵਰੀ",
    "online_orders": "ਔਨਲਾਈਨ ਆਰਡਰ",
    "pos_orders": "POS ਆਰਡਰ",
    "chips": "ਚਿਪਸ",
    "subscribed": "ਸਬਸਕ੍ਰਾਈਬ ਕੀਤਾ",
    "unsubscribed": "ਗਾਹਕੀ ਰੱਦ ਕੀਤੀ",
    "last_login": "ਆਖਰੀ ਲਾਗਇਨ",
    "join_at": "ਸ਼ਾਮਲ ਹੋਣ ਦੀ ਮਿਤੀ",
    "club": "ਕਲੱਬ",
    "buyer": "ਖਰੀਦਦਾਰ",
    "seller": "ਵਿਕਰੇਤਾ",
    "or": "ਜਾਂ",
    "type": "ਟਾਈਪ ਕਰੋ",
    "condition": "ਹਾਲਤ",
    "brand": "ਬ੍ਰਾਂਡ",
    "attempt": "ਕੋਸ਼ਿਸ਼",
    "error": "ਗਲਤੀ",
    "success": "ਸਫਲਤਾ",
    "fail": "ਫੇਲ",
    "inventory": "ਵਸਤੂ ਸੂਚੀ",
    "link": "ਲਿੰਕ",
    "visits": "ਮੁਲਾਕਾਤਾਂ",
    "transactions": "ਲੈਣ-ਦੇਣ",
    "vat": "VAT",
    "pos_vat": "POS ਵੈਟ",
    "sort_by": "ਦੇ ਨਾਲ ਕ੍ਰਮਬੱਧ..",
    "from": "ਤੋਂ",
    "from_lead_time": "ਅਗਲੇ {hours} ਘੰਟਿਆਂ ਦੇ ਅੰਦਰ",
    "no_credit_card_info": "ਕੋਈ ਕਾਰਡ ਜਾਣਕਾਰੀ ਨਹੀਂ!",
    "active": "ਕਿਰਿਆਸ਼ੀਲ",
    "not_active": "ਕਿਰਿਆਸ਼ੀਲ ਨਹੀਂ!",
    "referrals": "ਰੈਫਰਲ",
    "dashboard": "ਡੈਸ਼ਬੋਰਡ",
    "more": "ਹੋਰ",
    "inactive": "ਅਕਿਰਿਆਸ਼ੀਲ",
    "developer": "ਵਿਕਾਸਕਾਰ",
    "setting": "ਸੈਟਿੰਗ",
    "membership_conditions": "ਮੈਂਬਰਸ਼ਿਪ ਦੀਆਂ ਸ਼ਰਤਾਂ",
    "customers": "ਗਾਹਕ",
    "created_at": "ਮਿਤੀ ਬਣਾਈ ਗਈ",
    "updated_at": "ਆਖਰੀ ਅੱਪਡੇਟ",
    "register_at": "ਰਜਿਸਟਰ ਕਰਨ ਦੀ ਮਿਤੀ",
    "old": "ਪੁਰਾਣਾ",
    "new": "ਨਵਾਂ",
    "start": "ਸ਼ੁਰੂ ਕਰੋ",
    "end": "ਅੰਤ",
    "pos": "POS",
    "out_of_stock": "ਖਤਮ ਹੈ",
    "fake": "ਫਰਜ਼ੀ",
    "low_inventory_warning": "ਧਿਆਨ, ਘੱਟ ਵਸਤੂ ਸੂਚੀ!",
    "webhook": "ਵੈਬਹੁੱਕ",
    "notification": "ਸੂਚਨਾ",
    "sms": "SMS",
    "online_payment_link": "ਔਨਲਾਈਨ ਭੁਗਤਾਨ ਲਿੰਕ",
    "waiting_load_data": "ਡਾਟਾ ਲੋਡ ਕਰਨ ਦੀ ਉਡੀਕ ਕਰ ਰਿਹਾ ਹੈ..",
    "views": "ਵਿਚਾਰ",
    "sales": "ਵਿਕਰੀ",
    "total_views": "ਕੁੱਲ ਦ੍ਰਿਸ਼",
    "total_sales": "ਕੁੱਲ ਵਿਕਰੀ",
    "from_previous_n_days": "ਪਿਛਲੇ {days} ਦਿਨਾਂ ਤੋਂ",
    "drop_shipping": "ਡ੍ਰੌਪਸ਼ਿਪਿੰਗ",
    "commission": "ਕਮਿਸ਼ਨ",
    "shipping_area": "ਸ਼ਿਪਿੰਗ ਖੇਤਰ",
    "main_seller": "ਮੁੱਖ ਵਿਕਰੇਤਾ",
    "domain": "ਡੋਮੇਨ",
    "contact": "ਸੰਪਰਕ ਜਾਣਕਾਰੀ",
    "wallet": "ਬਟੂਆ",
    "reseller": "ਵਿਕਰੇਤਾ",
    "tracking_code": "ਟਰੈਕਿੰਗ ਕੋਡ",
    "tracking_url": "ਟਰੈਕਿੰਗ URL",
    "fulfillments": "ਪੂਰਤੀ",
    "reject": "ਅਸਵੀਕਾਰ ਕਰੋ",
    "reserved": "ਰਾਖਵਾਂ",
    "score": "ਸਕੋਰ",
    "customer_price": "ਗਾਹਕ ਕੀਮਤ",
    "options": "ਵਿਕਲਪ",
    "show_details": "ਵੇਰਵਾ ਦਿਖਾਓ",
    "no_data": "ਕੋਈ ਡਾਟਾ ਨਹੀਂ..",
    "waiting": "ਉਡੀਕ ਕਰ ਰਿਹਾ ਹੈ...",
    "waiting_connecting_payment": "ਭੁਗਤਾਨ ਸੇਵਾ ਦੀ ਉਡੀਕ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...",
    "creating_secure_payment": "ਸੁਰੱਖਿਅਤ ਭੁਗਤਾਨ ਬਣਾਉਣਾ।",
    "officer": "ਅਧਿਕਾਰੀ",
    "ticket": "ਟਿਕਟ",
    "ticket_url": "ਟਿਕਟ url",
    "closed_at": "'ਤੇ ਬੰਦ ਹੋਇਆ",
    "close_ticket": "ਟਿਕਟ ਬੰਦ ਕਰੋ",
    "reopen_ticket": "ਟਿਕਟ ਦੁਬਾਰਾ ਖੋਲ੍ਹੋ",
    "require": "ਲੋੜ ਹੈ*",
    "search": "ਖੋਜ...",
    "language": "ਭਾਸ਼ਾ",
    "tasks": "ਕਾਰਜ",
    "permissions": "ਇਜਾਜ਼ਤਾਂ",
    "finish_date": "ਸਮਾਪਤੀ ਮਿਤੀ",
    "complete_date": "ਸਮਾਪਤੀ ਦੀ ਤਿਥਿ",
    "settle_date": "ਬੰਦੋਬਸਤ ਦੀ ਮਿਤੀ",
    "cost_span": "ਕੀਮਤ ਸੀਮਾ",
    "industry": "ਉਦਯੋਗ",
    "rating": "ਰੇਟਿੰਗ",
    "rates": "ਰੇਟਿੰਗ",
    "seen_at": "'ਤੇ ਦੇਖਿਆ ਗਿਆ",
    "completed": "ਪੂਰਾ ਹੋਇਆ",
    "you": "ਤੁਹਾਨੂੰ",
    "shop": "ਦੁਕਾਨ",
    "store": "ਸਟੋਰ",
    "granted": "ਦਿੱਤੀ ਗਈ",
    "deny": "ਇਨਕਾਰ",
    "request": "ਬੇਨਤੀ",
    "expert": "ਮਾਹਰ",
    "response": "ਜਵਾਬ",
    "requests": "ਬੇਨਤੀਆਂ",
    "experts": "ਮਾਹਿਰ",
    "responses": "ਜਵਾਬ",
    "negotiations": "ਗੱਲਬਾਤ",
    "all_chats": "ਸਾਰੀਆਂ ਚੈਟਾਂ",
    "chats": "ਗੱਲਬਾਤ",
    "tags": "ਟੈਗਸ",
    "description": "ਵਰਣਨ",
    "rates_count": "ਰੇਟਿੰਗਾਂ ਦੀ ਗਿਣਤੀ",
    "rate": "ਰੇਟਿੰਗ",
    "comment": "ਟਿੱਪਣੀ",
    "chat": "ਚੈਟ",
    "install": "ਇੰਸਟਾਲ ਕਰੋ",
    "edited": "ਸੰਪਾਦਿਤ ਕੀਤਾ",
    "undo": "ਵਾਪਿਸ",
    "redo": "ਦੁਬਾਰਾ ਕਰੋ",
    "male": "ਨਰ",
    "female": "ਔਰਤ",
    "calculator": "ਕੈਲਕੁਲੇਟਰ",
    "catalog": "ਕੈਟਾਲਾਗ",
    "max_height": "ਅਧਿਕਤਮ ਉਚਾਈ",
    "images_compare": "ਚਿੱਤਰਾਂ ਦੀ ਤੁਲਨਾ",
    "canvas": "ਕੈਨਵਸ",
    "table_of_contents": "ਵਿਸ਼ਾ - ਸੂਚੀ",
    "comments": "ਟਿੱਪਣੀਆਂ",
    "badge_codes": "ਬੈਜ ਕੋਡ",
    "need_more": "ਹੋਰ ਦੀ ਲੋੜ ਹੈ?",
    "invite_glow_caption": "ਹਰੇਕ ਦੋਸਤ ਲਈ 14.9$ ਪ੍ਰਾਪਤ ਕਰੋ!",
    "register_free": "100% ਮੁਫ਼ਤ ਰਜਿਸਟਰ",
    "gift": "ਤੋਹਫ਼ਾ",
    "google": "ਗੂਗਲ",
    "facebook": "ਫੇਸਬੁੱਕ",
    "instagram": "Instagram",
    "instashop": "Instashop",
    "show": "ਦਿਖਾਓ",
    "hide": "ਓਹਲੇ",
    "waiting_review": "ਸਮੀਖਿਆ ਦੀ ਉਡੀਕ ਕਰ ਰਿਹਾ ਹੈ",
    "not_selected": "ਚੁਣਿਆ ਨਹੀਂ ਗਿਆ",
    "time": "ਸਮਾਂ",
    "final_price": "ਅੰਤਿਮ ਕੀਮਤ",
    "starting_price": "ਸ਼ੁਰੂਆਤੀ ਕੀਮਤ",
    "day": "ਦਿਨ",
    "paid": "ਦਾ ਭੁਗਤਾਨ",
    "service_bill": "ਚਲਾਨ ਦਾ ਭੁਗਤਾਨ",
    "avocado": "ਆਵਾਕੈਡੋ",
    "delivery_price": "ਸ਼ਿਪਿੰਗ ਦੀ ਲਾਗਤ",
    "select_address": "ਪਤਾ ਚੁਣੋ",
    "image": "ਚਿੱਤਰ",
    "view": "ਦੇਖੋ",
    "sell": "ਵਿਕਰੀ",
    "hyper": "ਹਾਈਪਰ",
    "cart_list": "ਕਾਰਟ",
    "barcode_scanner": "ਬਾਰਕੋਡ ਸਕੈਨਰ",
    "scan_qr_code": "QR ਕੋਡ ਸਕੈਨ ਕਰੋ",
    "new_carts": "ਨਵੀਆਂ ਗੱਡੀਆਂ",
    "pays": "ਭੁਗਤਾਨ",
    "annually": "ਸਾਲਾਨਾ",
    "sells": "ਵਿਕਰੀ",
    "articles": "ਲੇਖ",
    "jobs": "ਨੌਕਰੀਆਂ",
    "job": "ਨੌਕਰੀ",
    "blog": "ਬਲੌਗ",
    "deleted_at": "'ਤੇ ਮਿਟਾਇਆ ਗਿਆ",
    "capacity": "ਸਮਰੱਥਾ",
    "download_at": "ਆਖਰੀ ਡਾਊਨਲੋਡ ਮਿਤੀ",
    "downloads": "ਡਾਊਨਲੋਡ",
    "usage": "ਵਰਤੋਂ",
    "select_upload_file": "ਫਾਈਲ ਚੁਣੋ ਜਾਂ ਛੱਡੋ",
    "download_link": "ਡਾਊਨਲੋਡ ਲਿੰਕ",
    "uploading": "ਅੱਪਲੋਡ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ..",
    "files": "ਫਾਈਲਾਂ",
    "star": "ਤਾਰਾ",
    "speed": "ਗਤੀ",
    "feedback": "ਸੁਝਾਅ",
    "new_messages": "ਨਵੇਂ ਸੁਨੇਹੇ",
    "file": "ਫਾਈਲ",
    "attachment": "ਅਟੈਚਮੈਂਟ",
    "gallery": "ਗੈਲਰੀ",
    "sync": "ਸਿੰਕ",
    "diff_time": "ਸਮੇਂ ਦਾ ਅੰਤਰ",
    "network": "ਨੈੱਟਵਰਕ",
    "account": "ਖਾਤਾ",
    "configuration": "ਸੰਰਚਨਾ",
    "blockchain": "ਬਲਾਕਚੈਨ",
    "blog_link": "ਬਲੌਗ ਲਿੰਕ",
    "community": "ਭਾਈਚਾਰਾ",
    "critical_zone": "ਨਾਜ਼ੁਕ ਜ਼ੋਨ",
    "statistics": "ਅੰਕੜੇ",
    "access": "ਪਹੁੰਚ",
    "seo": "SEO",
    "followers": "ਅਨੁਯਾਈ",
    "followings": "ਅਨੁਸਰਣ",
    "private": "ਝਲਕ",
    "soon": "ਜਲਦੀ ਹੀ",
    "features": "ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
    "bot": "ਬੋਟ",
    "sample": "ਨਮੂਨਾ",
    "how_it_work": "ਇਹ ਕਿਵੇਂ ਚਲਦਾ ਹੈ?",
    "page": "ਪੰਨਾ",
    "congratulations": "ਵਧਾਈਆਂ",
    "recommend": "ਦੀ ਸਿਫ਼ਾਰਸ਼ ਕਰੋ",
    "recommended": "ਸਿਫ਼ਾਰਿਸ਼ ਕੀਤੀ",
    "recoms": "ਸਿਫ਼ਾਰਿਸ਼ਾਂ",
    "likes": "ਪਸੰਦ ਹੈ",
    "clicks": "ਕਲਿਕਸ",
    "platform": "ਪਲੇਟਫਾਰਮ",
    "cms": "CMS",
    "cash": "ਨਕਦ",
    "dir_payment": "ਬਕ ਤਬਾਦਲਾ",
    "auto_complete": "ਆਟੋ ਪੂਰਾ",
    "compare": "ਤੁਲਨਾ ਕਰੋ",
    "infinite": "ਅਨੰਤ",
    "tips": "ਸੁਝਾਅ",
    "technical": "ਤਕਨੀਕੀ",
    "finance": "ਵਿੱਤ",
    "your_phone_input": "ਇੱਕ ਫ਼ੋਨ ਨੰਬਰ ਦਾਖਲ ਕਰੋ",
    "income": "ਆਮਦਨ",
    "change": "ਬਦਲੋ",
    "new_users": "ਨਵੇਂ ਉਪਭੋਗਤਾ",
    "success_orders": "ਸਫਲ ਆਦੇਸ਼",
    "direct": "ਸਿੱਧਾ",
    "last_activity": "ਆਖਰੀ ਗਤੀਵਿਧੀ",
    "landing": "ਲੈਂਡਿੰਗ",
    "now": "ਹੁਣ",
    "accept_agreement": "ਮੈਂ ਸ਼ਰਤਾਂ ਪੜ੍ਹੀਆਂ ਹਨ ਅਤੇ ਮੰਨ ਲਈਆਂ ਹਨ।",
    "report": "ਰਿਪੋਰਟ",
    "tablet": "ਟੈਬਲੇਟ",
    "pc": "PC",
    "acquisition_channel": "ਪ੍ਰਾਪਤੀ ਚੈਨਲ",
    "to": "ਨੂੰ",
    "info": "ਜਾਣਕਾਰੀ",
    "general": "ਜਨਰਲ",
    "upload": "ਅੱਪਲੋਡ ਕਰੋ",
    "general_config": "ਆਮ ਸੰਰਚਨਾ",
    "limits_config": "ਸੀਮਾਵਾਂ",
    "design_config": "ਡਿਜ਼ਾਈਨ ਅਤੇ ਸ਼ੈਲੀ",
    "duration_config": "ਮਿਆਦ ਸੀਮਾ",
    "constraints_config": "ਯੋਗਤਾ ਸੀਮਾਵਾਂ",
    "clubs_config": "ਕਲੱਬਾਂ ਵਿੱਚ ਉਪਲਬਧ ਹੈ",
    "additional_config": "ਵਧੀਕ ਸੰਰਚਨਾਵਾਂ",
    "import": "ਆਯਾਤ ਕਰੋ",
    "ribbon": "ਰਿਬਨ",
    "countries": "ਦੇਸ਼",
    "edit": "ਸੰਪਾਦਿਤ ਕਰੋ",
    "delete": "ਮਿਟਾਓ",
    "analytics": "ਵਿਸ਼ਲੇਸ਼ਣ",
    "rules": "ਨਿਯਮ",
    "unset": "ਸੈੱਟ ਨਹੀਂ ਹੈ",
    "carts": "ਗੱਡੀਆਂ",
    "optional": "ਵਿਕਲਪਿਕ",
    "design": "ਡਿਜ਼ਾਈਨ",
    "filter": "ਫਿਲਟਰ",
    "send": "ਭੇਜੋ",
    "approved": "ਨੂੰ ਮਨਜ਼ੂਰੀ ਦਿੱਤੀ",
    "unit": "ਯੂਨਿਟ",
    "profile": "ਪ੍ਰੋਫਾਈਲ",
    "shipping_rates": "ਸ਼ਿਪਿੰਗ ਦਰਾਂ",
    "package": "ਪੈਕੇਜ",
    "overview": "ਸੰਖੇਪ ਜਾਣਕਾਰੀ",
    "live": "ਲਾਈਵ",
    "never": "ਕਦੇ ਨਹੀਂ",
    "always": "ਹਮੇਸ਼ਾ",
    "mandatory": "ਲਾਜ਼ਮੀ",
    "expire_at": "ਅੰਤ ਦੀ ਤਾਰੀਖ",
    "position": "ਸਥਿਤੀ",
    "channel": "ਚੈਨਲ",
    "age": "ਉਮਰ",
    "charge": "ਚਾਰਜ",
    "giftcard": "ਗਿਫ਼ਟ ਕਾਰਡ",
    "acquisition": "ਪ੍ਰਾਪਤੀ",
    "conversion": "ਪਰਿਵਰਤਨ",
    "total_payments": "ਕੁੱਲ ਭੁਗਤਾਨ",
    "community_ask": "ਭਾਈਚਾਰੇ ਵਿੱਚ ਪੁੱਛੋ",
    "children": "ਬੱਚੇ",
    "export": "ਨਿਰਯਾਤ",
    "list": "ਸੂਚੀ",
    "hierarchy": "ਦਰਜਾਬੰਦੀ",
    "images": "ਚਿੱਤਰ",
    "demo": "ਡੈਮੋ",
    "author": "ਲੇਖਕ",
    "designer": "ਡਿਜ਼ਾਈਨਰ",
    "max": "ਅਧਿਕਤਮ",
    "accepted": "ਸਵੀਕਾਰ ਕੀਤਾ",
    "reply": "ਜਵਾਬ",
    "reviewed": "ਸਮੀਖਿਆ ਕੀਤੀ",
    "restored": "ਬਹਾਲ ਕੀਤਾ",
    "merchant": "ਵਪਾਰੀ",
    "per_product": "ਪ੍ਰਤੀ ਉਤਪਾਦ",
    "journey": "ਯਾਤਰਾ",
    "after": "ਤੋਂ ਬਾਅਦ"
  },
  "dialogs": {
    "delete": {
      "title": "ਮਿਟਾਓ",
      "message": "ਕੀ ਤੁਸੀਂ ਯਕੀਨੀ ਤੌਰ 'ਤੇ ਇਸ ਆਈਟਮ ਨੂੰ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
      "action": "ਹਾਂ, ਹੁਣੇ ਮਿਟਾਓ"
    }
  },
  "actions": {
    "add_to_cart": "ਠੇਲ੍ਹੇ ਵਿੱਚ ਪਾਓ",
    "cancel": "ਰੱਦ ਕਰੋ",
    "update": "ਅੱਪਡੇਟ ਕਰੋ",
    "add": "ਸ਼ਾਮਲ ਕਰੋ",
    "delete": "ਮਿਟਾਓ",
    "new": "ਨਵਾਂ",
    "save_continue": "ਸੁਰੱਖਿਅਤ ਕਰੋ ਅਤੇ ਜਾਰੀ ਰੱਖੋ",
    "save": "ਸੇਵ ਕਰੋ",
    "save_changes": "ਕੀਤੇ ਗਏ ਬਦਲਾਅ ਸੁਰੱਖਿਅਤ ਕਰੋ",
    "change": "ਬਦਲੋ",
    "continue": "ਜਾਰੀ ਰੱਖੋ",
    "close": "ਬੰਦ ਕਰੋ",
    "finish": "ਸਮਾਪਤ",
    "poll": "ਚੋਣ",
    "view": "ਦੇਖੋ",
    "edit": "ਸੰਪਾਦਿਤ ਕਰੋ",
    "next": "ਅਗਲਾ",
    "previous": "ਪਿਛਲਾ",
    "create": "ਬਣਾਓ",
    "set": "ਸੈੱਟ",
    "find": "ਲੱਭੋ",
    "accept": "ਸਵੀਕਾਰ ਕਰੋ",
    "reject": "ਅਸਵੀਕਾਰ ਕਰੋ",
    "back": "ਵਾਪਸ",
    "pay": "ਭੁਗਤਾਨ ਕਰੋ",
    "pay_now": "ਹੁਣੇ ਭੁਗਤਾਨ ਕਰੋ",
    "print": "ਛਾਪੋ",
    "return": "ਵਾਪਸੀ",
    "publish": "ਪ੍ਰਕਾਸ਼ਿਤ ਕਰੋ",
    "confirm": "ਪੁਸ਼ਟੀ ਕਰੋ",
    "copy": "ਕਾਪੀ ਕਰੋ",
    "submit": "ਜਮ੍ਹਾਂ ਕਰੋ",
    "send": "ਭੇਜੋ",
    "yes": "ਹਾਂ",
    "no": "ਨਹੀਂ",
    "meh": "ਹਮ",
    "clear": "ਸਾਫ਼",
    "dismiss": "ਖਾਰਜ ਕਰੋ",
    "search": "ਖੋਜ",
    "deselect_all": "ਸਭ ਨੂੰ ਅਣਚੁਣਿਆ ਕਰੋ",
    "select_all": "ਸਾਰਿਆ ਨੂੰ ਚੁਣੋ",
    "refresh": "ਤਾਜ਼ਾ ਕਰੋ",
    "verify": "ਪੁਸ਼ਟੀ ਕਰੋ",
    "play": "ਖੇਡੋ",
    "open": "ਖੋਲ੍ਹੋ",
    "calculate": "ਗਣਨਾ ਕਰੋ",
    "quick_buy": "ਤੁਰੰਤ ਖਰੀਦੋ",
    "click_here": "ਇੱਥੇ ਕਲਿੱਕ ਕਰੋ",
    "schedule": "ਸਮਾਸੂਚੀ, ਕਾਰਜ - ਕ੍ਰਮ",
    "send_now": "ਹੁਣੇ ਭੇਜੋ",
    "download": "ਡਾਊਨਲੋਡ ਕਰੋ",
    "reset_default": "ਪੂਰਵ-ਨਿਰਧਾਰਤ 'ਤੇ ਰੀਸੈਟ ਕਰੋ",
    "reset": "ਰੀਸੈਟ ਕਰੋ",
    "check": "ਚੈਕ",
    "cod_payment": "ਡਿਲੀਵਰੀ 'ਤੇ ਨਕਦ",
    "dir_payment": "ਪੈਸੇ ਦਾ ਤਬਾਦਲਾ",
    "online_payment": "ਆਨਲਾਈਨ ਭੁਗਤਾਨ",
    "checkout": "ਕਮਰਾ ਛੱਡ ਦਿਓ",
    "show_all": "ਸਾਰੇ ਦਿਖਾਓ",
    "login": "ਲਾਗਿਨ",
    "logout": "ਲਾੱਗ ਆਊਟ, ਬਾਹਰ ਆਉਣਾ",
    "more": "ਹੋਰ..",
    "collapse": "ਸਮੇਟਣਾ",
    "apply_change": "ਤਬਦੀਲੀਆਂ ਲਾਗੂ ਕਰੋ",
    "apply": "ਲਾਗੂ ਕਰੋ",
    "add_giftcard": "ਤੋਹਫ਼ਾ ਕਾਰਡ ਸ਼ਾਮਲ ਕਰੋ",
    "charge": "ਚਾਰਜ",
    "send_invites": "ਸੱਦੇ ਭੇਜੋ",
    "past": "ਅਤੀਤ",
    "restore": "ਰੀਸਟੋਰ ਕਰੋ",
    "cut": "ਕੱਟੋ",
    "get_sms_code": "ਪ੍ਰਮਾਣੀਕਰਨ ਕੋਡ ਪ੍ਰਾਪਤ ਕਰੋ",
    "register_no_mail": "ਈਮੇਲ ਤੋਂ ਬਿਨਾਂ ਜਾਰੀ ਰੱਖੋ",
    "no_mail_register_message": "ਕੋਈ ਈਮੇਲ ਪਤਾ ਨਹੀਂ ਹੈ ਜਾਂ ਆਪਣਾ ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ ਹੋ?",
    "reset_by_mail": "ਈਮੇਲ ਦੁਆਰਾ ਪਾਸਵਰਡ ਰਿਕਵਰੀ",
    "reset_by_sms": "SMS ਦੁਆਰਾ ਪਾਸਵਰਡ ਰਿਕਵਰੀ",
    "cash_payment": "ਨਕਦ ਭੁਗਤਾਨ",
    "show_chart": "ਚਾਰਟ ਦਿਖਾਓ",
    "open_app": "ਐਪ ਖੋਲ੍ਹੋ",
    "login_now": "ਹੁਣੇ ਲੌਗਇਨ ਕਰੋ",
    "watch_video": "ਵੀਡੀਓ ਦੇਖੋ",
    "check_now": "ਹੁਣੇ ਜਾਂਚ ਕਰੋ",
    "remove_image": "ਚਿੱਤਰ ਨੂੰ ਹਟਾਓ",
    "view_website": "ਲਿੰਕ ਖੋਲ੍ਹੋ",
    "explore": "{name} ਦੀ ਪੜਚੋਲ ਕਰੋ",
    "go": "ਜਾਣਾ",
    "read_more": "ਹੋਰ ਪੜ੍ਹੋ",
    "start_now": "ਹੁਣੇ ਸ਼ੁਰੂ ਕਰੋ - ਇਹ ਮੁਫ਼ਤ ਹੈ",
    "view_live": "ਲਾਈਵ ਦੇਖੋ",
    "resend_code": "ਕੋਡ ਦੁਬਾਰਾ ਭੇਜੋ",
    "invite": "ਸੱਦਾ",
    "add_more": "ਹੋਰ ਸ਼ਾਮਲ ਕਰੋ",
    "install_now": "ਹੁਣੇ ਸਥਾਪਿਤ ਕਰੋ",
    "uninstall": "ਅਣਇੰਸਟੌਲ ਕਰੋ",
    "show_preview": "ਝਲਕ ਦਿਖਾਓ",
    "hide_preview": "ਝਲਕ ਲੁਕਾਓ",
    "download_now": "ਹੁਣੇ ਡਾਊਨਲੋਡ ਕਰੋ",
    "auto_fill": "ਆਟੋਫਿਲ",
    "track": "ਟਰੈਕ",
    "change_state": "ਸਥਿਤੀ ਬਦਲੋ",
    "done": "ਹੋ ਗਿਆ",
    "reply": "ਜਵਾਬ"
  },
  "instance_message_title": "ਤੁਰੰਤ ਸੁਨੇਹਾ ਭੇਜੋ",
  "instance_message": "ਹੈਲੋ {name}, ਮੇਰਾ ਨਾਮ {company} ਤੋਂ {author} ਹੈ।",
  "errors": {
    "419": "ਤੁਸੀਂ ਲੰਬੇ ਸਮੇਂ ਤੋਂ ਅਕਿਰਿਆਸ਼ੀਲ ਹੋ, ਕਿਰਪਾ ਕਰਕੇ <b>⟳</b> ਸੁਰੱਖਿਆ ਕਾਰਨਾਂ ਕਰਕੇ ਪੰਨੇ ਨੂੰ ਤਾਜ਼ਾ ਕਰੋ।",
    "gateway_blockchain_sync_error": "ਸਿਸਟਮ ਬਲਾਕਚੈਨ ਨਾਲ ਸਮਕਾਲੀ ਨਹੀਂ ਹੁੰਦਾ ਹੈ। ਜਦੋਂ ਤੱਕ ਸਾਡੇ ਸਰਵਰਾਂ ਦਾ ਸਮਕਾਲੀਕਰਨ ਪੂਰਾ ਨਹੀਂ ਹੋ ਜਾਂਦਾ, ਉਦੋਂ ਤੱਕ ਨਵਾਂ ਲੈਣ-ਦੇਣ ਕਰਨਾ ਸੰਭਵ ਨਹੀਂ ਹੋਵੇਗਾ। ਅਸੀਂ ਸਮੱਸਿਆ ਦਾ ਹੱਲ ਕਰ ਰਹੇ ਹਾਂ।",
    "gateway_network_error": "ਭੁਗਤਾਨ ਗੇਟਵੇ ਸੇਵਾ ਵਿੱਚ ਇੱਕ ਸੰਚਾਰ ਸਮੱਸਿਆ ਆਈ ਹੈ।"
  },
  "receiver_info": {
    "map": {
      "title": "ਸ਼ਿਪਿੰਗ ਪਤਾ",
      "confirm": "ਟਿਕਾਣਾ ਸੈੱਟ ਕਰੋ",
      "address_type": "ਮੰਜ਼ਿਲ",
      "receptor_type": "ਪ੍ਰਾਪਤ ਕਰਨ ਵਾਲਾ"
    },
    "receiver_address": "ਸ਼ਿਪਿੰਗ ਪਤਾ ਚੁਣੋ",
    "address": "ਪਤਾ",
    "postcode": "ਪੋਸਟਕੋਡ",
    "enter_value": "ਇੱਥੇ ਭਰੋ",
    "address_note": "ਨੋਟ ਕਰੋ",
    "tel": "ਸੰਪਰਕ ਨੰਬਰ"
  },
  "weight": {
    "g": "g",
    "oz": "ਔਂਸ",
    "lb": "lb",
    "kg": "ਕਿਲੋ"
  },
  "mass_unit_name": {
    "g": "ਗ੍ਰਾਮ",
    "oz": "ਔਂਸ",
    "lb": "ਪੌਂਡ",
    "kg": "ਕਿਲੋਗ੍ਰਾਮ"
  },
  "length": {
    "cm": "cm",
    "in": "ਵਿੱਚ",
    "ft": "ਫੁੱਟ",
    "mm": "ਮਿਲੀਮੀਟਰ",
    "m": "m",
    "yd": "yd"
  },
  "size_unit_name": {
    "cm": "ਸੈਂਟੀਮੀਟਰ",
    "in": "ਇੰਚ",
    "ft": "ਪੈਰ",
    "mm": "ਮਿਲੀਮੀਟਰ",
    "m": "ਮੀਟਰ",
    "yd": "ਵਿਹੜਾ"
  },
  "distance": {
    "m": "ਮੀਟਰ",
    "km": "ਕਿਲੋਮੀਟਰ"
  },
  "time": {
    "days": "ਦਿਨ",
    "hours": "ਘੰਟੇ",
    "minutes": "ਮਿੰਟ",
    "seconds": "ਸਕਿੰਟ"
  },
  "units": [
    "ਯੂਨਿਟ",
    "ਆਈਟਮ",
    "ਹਰੇਕ",
    "ਸੈੱਟ",
    "ਟੁਕੜਾ",
    "ਕਿਲੋਗ੍ਰਾਮ",
    "ਗ੍ਰਾਮ",
    "ਮਿਲੀਗ੍ਰਾਮ",
    "ਮੀਟਰ",
    "ਮਿਲੀਮੀਟਰ",
    "ਵਰਗ ਮੀਟਰ",
    "ਵਰਗ ਫੁੱਟ",
    "ਘਣ ਮੀਟਰ",
    "ਲਿਟਰ",
    "ਮਿਲੀਲੀਟਰ",
    "ਪੈਰ",
    "ਗੈਲਨ",
    "ਇੰਚ",
    "ਔਂਸ",
    "ਪੌਂਡ",
    "ਕੁਆਰਟ",
    "ਗਜ਼",
    "ਕਮਰਾ"
  ],
  "region_types": {
    "State": "ਰਾਜ",
    "Territory": "ਖੇਤਰ",
    "Province": "ਸੂਬਾ"
  },
  "transaction_status": {
    "RequireAction": "ਕਾਰਵਾਈ ਦੀ ਲੋੜ ਹੈ",
    "Processing": "ਕਾਰਵਾਈ",
    "Canceled": "ਰੱਦ ਕਰ ਦਿੱਤਾ",
    "Succeeded": "ਸਫਲ ਹੋਇਆ"
  },
  "placeholders": {
    "name": "ਜੋਨ ਕੋਕਸ",
    "email": "your-mail@mail.com",
    "phone": "+1 000 0000",
    "language": "ਭਾਸ਼ਾ ਚੁਣੋ..",
    "friend_email": "ਤੁਹਾਡੇ ਦੋਸਤ ਦੀ ਈਮੇਲ...",
    "friend_name": "ਚੋਣ ਤੁਹਾਡੇ ਦੋਸਤ ਦਾ ਨਾਮ",
    "select_date": "ਇੱਕ ਮਿਤੀ ਚੁਣੋ..."
  },
  "notification": {
    "confirm": "ਪੁਸ਼ਟੀ ਕਰੋ",
    "confirm_message": "ਤਬਦੀਲੀਆਂ ਸਫਲਤਾਪੂਰਵਕ ਸੁਰੱਖਿਅਤ ਕੀਤੀਆਂ ਗਈਆਂ।",
    "error": "ਗਲਤੀ",
    "message": "ਸੁਨੇਹਾ",
    "caution": "ਸਾਵਧਾਨ",
    "warning": "ਚੇਤਾਵਨੀ",
    "award": "ਵਧਾਈ",
    "error_message": "ਬਦਕਿਸਮਤੀ ਨਾਲ, ਇੱਕ ਗੜਬੜ ਹੋ ਗਈ ਹੈ।",
    "congratulation": "ਵਧਾਈ",
    "coming_soon": "ਜਲਦੀ ਹੀ",
    "on_fetching_data": "ਜਾਣਕਾਰੀ ਪ੍ਰਾਪਤ ਕਰਦੇ ਹੋਏ ..",
    "new_pwa_version": "ਨਵਾਂ ਸੰਸਕਰਣ ਹੁਣ ਉਪਲਬਧ ਹੈ। ਕੀ ਤੁਸੀਂ ਐਪਲੀਕੇਸ਼ਨ ਨੂੰ ਅਪਡੇਟ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?",
    "over_license_limit": "ਲਾਇਸੈਂਸ ਸੀਮਾ ਤੋਂ ਵੱਧ",
    "update_license": "ਆਪਣਾ ਲਾਇਸੰਸ ਅੱਪਡੇਟ ਕਰੋ",
    "required": "ਲੋੜੀਂਦਾ ਹੈ",
    "invalid_email": "ਅਵੈਧ ਈ-ਮੇਲ",
    "invalid_domain": "ਅਵੈਧ ਡੋਮੇਨ",
    "invalid_min_length": "ਘੱਟੋ-ਘੱਟ ਲੰਬਾਈ {length} ਹੋਣੀ ਚਾਹੀਦੀ ਹੈ",
    "invalid_min_array_length": "ਘੱਟੋ-ਘੱਟ {length} ਆਈਟਮਾਂ ਦੀ ਚੋਣ ਕਰੋ",
    "invalid_max_chars": "ਅਧਿਕਤਮ {maxCount} ਅੱਖਰ",
    "invalid_url": "ਅਵੈਧ URL"
  },
  "colors": {
    "#D32F2F": "ਲਾਲ",
    "#C2185B": "ਗੁਲਾਬੀ",
    "#7B1FA2": "ਜਾਮਨੀ",
    "#512DA8": "ਗੂੜ੍ਹਾ ਜਾਮਨੀ",
    "#303F9F": "ਇੰਡੀਗੋ ਬਲੂ",
    "#1976D2": "ਨੀਲਾ",
    "#0288D1": "ਹਲਕਾ ਨੀਲਾ",
    "#0097A7": "ਫਿਰੋਜ਼ੀ ਨੀਲਾ",
    "#00796B": "ਹੰਸ ਗ੍ਰੀਨ",
    "#388E3C": "ਹਰਾ",
    "#689F38": "ਫਿੱਕਾ ਹਰਾ",
    "#AFB42B": "ਲਿਮੋ",
    "#FBC02D": "ਪੀਲਾ",
    "#FFA000": "ਅੰਬਰ",
    "#F57C00": "ਸੰਤਰਾ",
    "#E64A19": "ਚਮਕਦਾਰ ਸੰਤਰੀ",
    "#5D4037": "ਭੂਰਾ",
    "#616161": "ਸਲੇਟੀ",
    "#455A64": "ਸਲੇਟੀ ਨੀਲਾ",
    "#FFD700": "ਸੁਨਹਿਰੀ",
    "#C0C0C0": "ਚਾਂਦੀ",
    "#b76e79": "ਗੋਲਡਨ ਰੋਜ਼",
    "#383838": "ਮੈਟ ਕਾਲਾ",
    "#FFFFFF": "ਚਿੱਟਾ",
    "#FFF": "ਚਿੱਟਾ",
    "#000000": "ਕਾਲਾ",
    "#000": "ਕਾਲਾ"
  },
  "address_info": {
    "name": "ਨਾਮ",
    "tel": "ਫ਼ੋਨ",
    "email": "ਈ - ਮੇਲ",
    "country": "ਦੇਸ਼",
    "city": "ਸ਼ਹਿਰ",
    "state": "ਰਾਜ",
    "address": "ਪਤਾ",
    "building_number": "ਬਿਲਡਿੰਗ ਨੰਬਰ",
    "building_unit": "ਯੂਨਿਟ",
    "postcode": "ਪੋਸਟਕੋਡ",
    "note": "ਨੋਟ ਕਰੋ"
  },
  "product_types": {
    "physical": "ਸਰੀਰਕ",
    "physical_description": "ਭੌਤਿਕ ਉਤਪਾਦ ਜਿਵੇਂ ਕਿ: ਮੋਬਾਈਲ ਫ਼ੋਨ, ਕਿਤਾਬਾਂ, ਇਲੈਕਟ੍ਰਾਨਿਕ ਹਿੱਸੇ।",
    "virtual": "ਵਰਚੁਅਲ",
    "virtual_description": "ਇੰਟਰਨੈੱਟ-ਅਨੁਕੂਲ ਉਤਪਾਦ ਜਿਵੇਂ ਕਿ: ਰੀਚਾਰਜ ਕਾਰਡ, ਹੋਟਲ ਰਿਜ਼ਰਵੇਸ਼ਨ, ਗੇਮ ਰੀਚਾਰਜ।",
    "file": "ਫਾਈਲ",
    "file_description": "ਸਾਰੀਆਂ ਇਜਾਜ਼ਤ ਵਾਲੀਆਂ ਫਾਈਲਾਂ ਜਿਵੇਂ ਕਿ ਔਨਲਾਈਨ ਕੋਰਸ ਵੀਡੀਓ, ਡਾਊਨਲੋਡ ਕਰਨ ਯੋਗ ਦਸਤਾਵੇਜ਼।",
    "service": "ਸੇਵਾ",
    "service_description": "ਸੇਵਾਵਾਂ ਜਿਵੇਂ: ਮੁਰੰਮਤ, ਆਵਾਜਾਈ, ਅਧਿਆਪਨ।"
  },
  "license": {
    "free": "ਮੁਫ਼ਤ",
    "startup": "ਸ਼ੁਰੂ ਕਰਣਾ",
    "company": "ਕੰਪਨੀ",
    "enterprise": "ਐਂਟਰਪ੍ਰਾਈਜ਼"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "ਤੋਮਨ",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW"
  },
  "variants": {
    "color": "ਰੰਗ",
    "volume": "ਆਕਾਰ",
    "count_in_pack": "ਪੈਕ ਵਿੱਚ ਗਿਣੋ",
    "weight": "ਭਾਰ",
    "type": "ਸਮੱਗਰੀ",
    "style": "ਸ਼ੈਲੀ"
  },
  "delivery_state": {
    "check_queue": "ਸਮੀਖਿਆ ਦੀ ਉਡੀਕ ਕਰ ਰਿਹਾ ਹੈ",
    "order_confirm": "ਆਰਡਰ ਪੱਕਾ ਕਰਨਾ",
    "preparing_order": "ਤਿਆਰ ਕਰ ਰਿਹਾ ਹੈ",
    "sent_order": "ਡਿਲੀਵਰੀ 'ਤੇ",
    "to_customer": "ਡਿਲੀਵਰ ਕੀਤਾ"
  },
  "status": {
    "unpaid": "ਬਿਨਾਂ ਭੁਗਤਾਨ ਕੀਤੇ",
    "paid": "ਦਾ ਭੁਗਤਾਨ",
    "canceled": "ਰੱਦ ਕਰ ਦਿੱਤਾ",
    "completed": "ਵਸਾਇਆ",
    "reserved": "ਰਾਖਵਾਂ",
    "COD": "COD",
    "sold": "ਵਿਕਿਆ",
    "open": "ਖੋਲ੍ਹੋ",
    "cancel": "ਰੱਦ ਕਰ ਦਿੱਤਾ",
    "active": "ਕਿਰਿਆਸ਼ੀਲ",
    "inactive": "ਅਕਿਰਿਆਸ਼ੀਲ",
    "debug": "ਡੀਬੱਗ ਕਰੋ",
    "live": "ਲਾਈਵ",
    "test": "ਟੈਸਟ",
    "connected": "ਜੁੜਿਆ ਹੋਇਆ ਹੈ",
    "disconnected": "ਡਿਸਕਨੈਕਟ ਕੀਤਾ",
    "accept": "ਸਵੀਕਾਰ ਕਰੋ",
    "reject": "ਅਸਵੀਕਾਰ ਕਰੋ",
    "pending": "ਬਕਾਇਆ",
    "rejected": "ਰੱਦ ਕਰ ਦਿੱਤਾ",
    "accepted": "ਸਵੀਕਾਰ ਕੀਤਾ"
  },
  "dimensions": {
    "cm": "cm",
    "km": "ਕਿਲੋਮੀਟਰ",
    "kg": "ਕਿਲੋ"
  },
  "transportation_type": {
    "motorbike": "ਮੋਟਰਬਾਈਕ",
    "motorbike_description": "ਕੁਝ ਕਿਲੋਮੀਟਰ ਦੇ ਅੰਦਰ ਮੱਧਮ ਭਾਰ।",
    "cargo_small": "ਛੋਟਾ ਮਾਲ",
    "cargo_small_description": "ਮਲਟੀ-ਕਿਲੋਮੀਟਰ ਹਲਕਾ ਕਾਰਗੋ.",
    "cargo": "ਕਾਰਗੋ",
    "cargo_description": "ਕੁਝ ਕਿਲੋਮੀਟਰ ਦੇ ਅੰਦਰ ਮੱਧਮ ਭਾਰ।",
    "truck": "ਟਰੱਕ",
    "truck_description": "ਦੇਸ਼ ਦੇ ਅੰਦਰ ਬਲਕ ਜਾਂ ਭਾਰੀ ਮਾਲ।",
    "fast_post": "ਤੇਜ਼ ਪੋਸਟ",
    "fast_post_description": "ਡਾਕਘਰ ਦੁਆਰਾ ਤੇਜ਼ ਪੋਸਟਿੰਗ.",
    "post": "ਆਮ ਪੋਸਟ",
    "post_description": "ਡਾਕਘਰ ਦੁਆਰਾ ਨਿਯਮਤ ਡਾਕ.",
    "airplane": "ਏਅਰਮੇਲ",
    "airplane_description": "ਘਰੇਲੂ ਅਤੇ ਵਿਦੇਸ਼ੀ ਰੋਸ਼ਨੀ ਅਤੇ ਮੱਧਮ ਕਾਰਗੋ।",
    "bicycle": "ਸਾਫ਼ ਭੇਜੋ",
    "bicycle_description": "ਹਲਕਾ ਕਾਰਗੋ, ਗੈਰ-ਮੋਟਰ ਵਾਹਨਾਂ ਦੇ ਕੁਝ ਸੌ ਗਜ਼ ਦੇ ਅੰਦਰ।",
    "global": "ਗਲੋਬਲ ਆਵਾਜਾਈ",
    "global_description": "ਹਵਾ, ਸਮੁੰਦਰ ਜਾਂ ਜ਼ਮੀਨ ਦੁਆਰਾ ਵਿਦੇਸ਼ਾਂ ਵਿੱਚ ਸ਼ਿਪਿੰਗ.",
    "pickup": "ਚੁੱਕਣਾ",
    "pickup_description": "ਗਾਹਕ ਤੁਹਾਡੇ ਭੌਤਿਕ ਸਟੋਰ ਜਾਂ ਵੇਅਰਹਾਊਸ ਤੋਂ ਆਈਟਮਾਂ ਨੂੰ ਚੁੱਕਦੇ ਹਨ।"
  },
  "article": {
    "login_to_see_error": "ਲੇਖ ਨੂੰ ਐਕਸੈਸ ਕਰਨ ਲਈ ਲੌਗਇਨ ਕਰੋ",
    "create_new_action": "ਨਵੀਂ ਸਮੱਗਰੀ ਬਣਾਓ",
    "menu_title": "ਮੀਨੂ",
    "menu": {
      "edit": "ਸੰਪਾਦਨ ਮੋਡ",
      "view_mode": "ਵਿਊ ਮੋਡ",
      "delete": "ਲੇਖ ਮਿਟਾਓ"
    },
    "schedule_action": "ਕੀ ਤੁਸੀਂ ਪ੍ਰਕਾਸ਼ਨ ਨੂੰ ਨਿਯਤ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?",
    "schedule_title": "ਸਵੈ-ਪ੍ਰਕਾਸ਼ਿਤ ਕਰਨ ਦੀ ਸਮਾਂ-ਸੂਚੀ ਬਣਾਓ",
    "edit_mode": "ਸੰਪਾਦਿਤ ਕਰੋ",
    "public_view_mode": "ਜਨਤਕ ਦ੍ਰਿਸ਼",
    "publish_at": "'ਤੇ ਪ੍ਰਕਾਸ਼ਿਤ ਕਰੋ",
    "published": "ਪ੍ਰਕਾਸ਼ਿਤ",
    "draft": "ਡਰਾਫਟ",
    "saving": "ਸੰਭਾਲ ਰਿਹਾ ਹੈ",
    "save_and_publish_action": "ਸੁਰੱਖਿਅਤ ਕਰੋ ਅਤੇ ਪ੍ਰਕਾਸ਼ਿਤ ਕਰੋ",
    "save_draft_action": "ਡਰਾਫਟ ਸੁਰੱਖਿਅਤ ਕਰੋ",
    "private": "ਨਿਜੀ",
    "public": "ਜਨਤਕ",
    "category_input": "ਸ਼੍ਰੇਣੀ",
    "category_input_message": "ਲੇਖ ਸ਼੍ਰੇਣੀ ਚੁਣੋ",
    "parent_input": "ਮਾਪੇ ਸ਼੍ਰੇਣੀ",
    "parent_input_message": "ਪਿਤਾ ਸਮੱਗਰੀ ਦੀ ਚੋਣ ਕਰੋ",
    "schedule_input": "ਸਮਾਸੂਚੀ, ਕਾਰਜ - ਕ੍ਰਮ",
    "schedule_input_placeholder": "ਜੇਕਰ ਤੁਸੀਂ ਚਾਹੁੰਦੇ ਹੋ ਕਿ ਕਹਾਣੀ ਕਿਸੇ ਖਾਸ ਸਮੇਂ 'ਤੇ ਪ੍ਰਕਾਸ਼ਿਤ ਹੋਵੇ।",
    "schedule_view_action": "ਪ੍ਰਕਾਸ਼ਿਤ ਸਮਾਂ-ਸੂਚੀ ਦੇਖੋ",
    "author_title": "ਦੁਆਰਾ ਲਿਖਿਆ ਗਿਆ",
    "read_time": "ਅਧਿਐਨ ਕਰਨ ਦਾ ਸਮਾਂ",
    "read_time_unit": "ਮਿੰਟ",
    "claps_action": "ਤਾੜੀਆਂ",
    "claps": "ਤਾੜੀਆਂ",
    "likes": "ਪਸੰਦ ਹੈ",
    "about_author": "ਲੇਖਕ ਬਾਰੇ",
    "updated_at": "ਅੱਪਡੇਟ ਕੀਤਾ",
    "wrote_at": "'ਤੇ ਲਿਖਿਆ ਗਿਆ",
    "now": "ਹੁਣ",
    "follow_action": "ਦਾ ਪਾਲਣ ਕਰੋ",
    "followed": "ਦਾ ਅਨੁਸਰਣ ਕੀਤਾ",
    "report_and_delete_action": "ਇਸ ਲੇਖ ਦੀ ਰਿਪੋਰਟ ਕਰੋ ਅਤੇ ਮਿਟਾਓ",
    "report_action": "ਦੁਰੁਪਯੋਗ ਹੋਣ ਦੀ ਸੂਚਨਾ ਦੇਣੀ",
    "you_reported_this_article": "ਇਸ ਲੇਖ ਵਿੱਚ ਪਹਿਲਾਂ ਹੀ ਦੁਰਵਿਵਹਾਰ ਦੀ ਰਿਪੋਰਟ ਹੈ।",
    "add_to_publication_action": "ਪ੍ਰਕਾਸ਼ਨ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ",
    "author_socials": "ਸੋਸ਼ਲ ਮੀਡੀਆ 'ਤੇ ਲੇਖਕ",
    "share": "ਸ਼ੇਅਰ ਕਰੋ",
    "report_dialog": {
      "report_and_delete_title": "ਦੁਰਵਿਵਹਾਰ ਦੀ ਰਿਪੋਰਟ ਕਰੋ ਅਤੇ ਸਮੱਗਰੀ ਨੂੰ ਹਟਾਓ",
      "report_title": "ਇਸ ਸਮੱਗਰੀ ਦੀ ਦੁਰਵਿਵਹਾਰ ਵਜੋਂ ਰਿਪੋਰਟ ਕਰੋ",
      "message": "ਇਸ ਸਮੱਗਰੀ ਨੂੰ ਦਰਜ ਕਰਨ ਦਾ ਕਾਰਨ ਕੀ ਹੈ? ਹੇਠਾਂ ਦਿੱਤੇ ਵਿਕਲਪਾਂ ਵਿੱਚੋਂ ਇੱਕ ਚੁਣੋ।",
      "accept_and_delete_action": "ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਸਮੱਗਰੀ ਨੂੰ ਮਿਟਾਓ"
    },
    "schedule_dialog": {
      "title": "ਸਮੱਗਰੀ ਰੀਲੀਜ਼ ਅਨੁਸੂਚੀ",
      "publish_at": "'ਤੇ ਪ੍ਰਕਾਸ਼ਿਤ ਕਰੋ",
      "last_edit": "ਆਖਰੀ ਸੰਪਾਦਨ",
      "view_action": "ਲੇਖ ਦੇਖੋ"
    },
    "notifications": {
      "update_success_title": "ਜਾਣਕਾਰੀ ਦਰਜ ਕਰੋ",
      "update_success": "ਲੇਖ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਕੀਤਾ ਗਿਆ।",
      "update_error": "ਦਰਜ ਕੀਤੀ ਜਾਣਕਾਰੀ ਵੈਧ ਨਹੀਂ ਹੈ।",
      "delete_error": "ਤੁਸੀਂ ਇਸ ਲੇਖ ਨੂੰ ਮਿਟਾ ਨਹੀਂ ਸਕਦੇ!",
      "report_and_delete_success_title": "ਰਿਪੋਰਟ ਕਰੋ ਅਤੇ ਮਿਟਾਓ",
      "report_and_delete_success_message": "ਲੇਖ ਸਫਲਤਾਪੂਰਵਕ ਮਿਟਾ ਦਿੱਤਾ ਗਿਆ ਹੈ।",
      "report_success_title": "ਰਿਪੋਰਟ ਲੇਖ",
      "report_success_message": "ਇਸ ਲੇਖ 'ਤੇ ਤੁਹਾਡੀ ਰਿਪੋਰਟ ਪੋਸਟ ਕੀਤੀ ਗਈ ਹੈ।"
    },
    "alert": {
      "delete_article": {
        "title": "ਲੇਖ ਮਿਟਾਓ",
        "message": "ਕੀ ਤੁਸੀਂ ਪੱਕੇ ਤੌਰ 'ਤੇ ਇਸ ਲੇਖ ਨੂੰ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
        "action": "ਮਿਟਾਓ"
      }
    },
    "edit_window": {
      "title": "ਚਿੱਤਰ ਟੈਕਸਟ ਅਤੇ ਸੰਖੇਪ ਚੁਣੋ",
      "digest": "ਸੰਖੇਪ"
    },
    "editor": {
      "title_placeholder": "ਸਿਰਲੇਖ..",
      "body_placeholder": "ਵਧੀਆ ਸਮੱਗਰੀ ਲਿਖੋ ..",
      "accept_file_types_error": "ਇਹ ਫਾਈਲ ਫਾਰਮੈਟ ਅਸਵੀਕਾਰਨਯੋਗ ਹੈ:",
      "max_file_size_error": "ਇਹ ਫ਼ਾਈਲ ਬਹੁਤ ਵੱਡੀ ਹੈ:",
      "notifications": {
        "image_uploaded_success": "ਚਿੱਤਰ ਨੂੰ ਸਫਲਤਾਪੂਰਵਕ ਸੁਰੱਖਿਅਤ ਕੀਤਾ ਗਿਆ",
        "image_uploaded_failed": "ਚਿੱਤਰ ਲੋਡ ਕਰਨ ਵਿੱਚ ਤਰੁੱਟੀ।"
      },
      "embed_placeholder": "iframe ਕੋਡ, Facebook, Youtube ਜਾਂ ਕੋਈ ਹੋਰ URL ਦਰਜ ਕਰੋ ਅਤੇ enter ਦਬਾਓ।",
      "embed_caption_placeholder": "ਇੱਕ ਸਿਰਲੇਖ ਦਰਜ ਕਰੋ (ਵਿਕਲਪਿਕ)",
      "images_caption_placeholder": "ਇਸ ਚਿੱਤਰ ਲਈ ਇੱਕ ਸਿਰਲੇਖ ਦਰਜ ਕਰੋ .."
    }
  },
  "article_report": {
    "inappropriate": "ਇਸ ਲੇਖ ਦੀ ਸਮੱਗਰੀ ਅਣਉਚਿਤ ਹੈ।",
    "fake": "ਇਹ ਫਰਜ਼ੀ ਅਤੇ ਧੋਖੇਬਾਜ਼ ਹੈ।",
    "spam": "ਇਸ ਆਈਟਮ ਨੂੰ ਸਪੈਮ ਅਤੇ ਕਾਪੀ ਕੀਤਾ ਗਿਆ ਹੈ।",
    "scam": "ਇਸ ਨਾਲ ਮਾਲਵੇਅਰ, ਵਾਇਰਸ ਜਾਂ ਸਿਸਟਮ ਕਰੈਸ਼ ਹੋਣ ਦੀ ਉਮੀਦ ਕੀਤੀ ਜਾ ਸਕਦੀ ਹੈ।",
    "hacked": "ਇਹ ਸਾਈਟ ਹੈਕ ਕੀਤੀ ਜਾਪਦੀ ਹੈ।",
    "offensive": "ਭਾਸ਼ਾ ਦੀ ਸਮੱਗਰੀ ਅਤੇ ਸ਼ਬਦਾਵਲੀ ਅਨੈਤਿਕ ਅਤੇ ਨਿਰਾਦਰ ਹੈ।",
    "violent": "ਮੈਨੂੰ ਲੱਗਦਾ ਹੈ ਕਿ ਇਸ ਸਮੱਗਰੀ ਵਿੱਚ ਅਸ਼ਲੀਲਤਾ ਸ਼ਾਮਲ ਹੈ ਅਤੇ ਕਾਨੂੰਨਾਂ ਦੀ ਉਲੰਘਣਾ ਹੈ।",
    "harassment": "ਮੈਨੂੰ ਲੱਗਦਾ ਹੈ ਕਿ ਇਹ ਨਸਲਵਾਦੀ ਹੈ।",
    "hate": "ਮੈਨੂੰ ਲੱਗਦਾ ਹੈ ਕਿ ਇਹ ਹਿੰਸਾ ਨੂੰ ਉਤਸ਼ਾਹਿਤ ਕਰਨ ਬਾਰੇ ਹੈ।",
    "infringe": "ਇਹ ਮੇਰੇ ਅਧਿਕਾਰਾਂ ਦੀ ਉਲੰਘਣਾ ਕਰਦਾ ਹੈ।"
  },
  "comments": {
    "new_action": "ਇੱਕ ਟਿੱਪਣੀ ਛੱਡਣ ਲਈ ਕਲਿੱਕ ਕਰੋ ..",
    "title": "ਟਿੱਪਣੀਆਂ",
    "body_placeholder": "ਤੁਹਾਡੀ ਟਿੱਪਣੀ ਜਾਂ ਸੁਨੇਹਾ",
    "send_action": "ਟਿੱਪਣੀ ਭੇਜੋ",
    "body_is_empty_error": "ਟਿੱਪਣੀ ਖਾਲੀ ਹੈ!",
    "comments": "ਟਿੱਪਣੀਆਂ",
    "no_comments": "ਪਹਿਲੀ ਟਿੱਪਣੀ ਲਿਖੋ...",
    "load_more_action": "ਹੋਰ ਟਿੱਪਣੀਆਂ ਪ੍ਰਾਪਤ ਕਰੋ ..",
    "cant_send_comment": "ਤੁਸੀਂ ਨਵੀਂ ਪੋਸਟ ਸ਼ਾਮਲ ਨਹੀਂ ਕਰ ਸਕਦੇ।",
    "cant_remove_this_comment": "ਤੁਸੀਂ ਇਸ ਟਿੱਪਣੀ ਨੂੰ ਮਿਟਾ ਨਹੀਂ ਸਕਦੇ!",
    "product_buyer": "ਖਰੀਦਦਾਰ",
    "delete_alert": {
      "title": "ਟਿੱਪਣੀ ਮਿਟਾਓ",
      "message": "ਕੀ ਤੁਸੀਂ ਇਸ ਟਿੱਪਣੀ ਨੂੰ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
      "action": "ਮਿਟਾਓ"
    },
    "notifications": {
      "delete_success": "ਤੁਹਾਡੀ ਟਿੱਪਣੀ ਸਫਲਤਾਪੂਰਵਕ ਮਿਟਾਈ ਗਈ।"
    },
    "first_send": "ਪਹਿਲੀ ਪੋਸਟ",
    "comment_at": "'ਤੇ",
    "edit_comment": "ਟਿੱਪਣੀ ਦਾ ਸੰਪਾਦਨ ਕਰੋ"
  },
  "customer_club": {
    "bronze": "ਕਾਂਸੀ",
    "silver": "ਚਾਂਦੀ",
    "gold": "ਸੁਨਹਿਰੀ",
    "platinum": "ਪਲੈਟੀਨਮ",
    "diamond": "ਹੀਰਾ"
  },
  "application_categories": {
    "tracking": "ਉਪਭੋਗਤਾ ਵਿਵਹਾਰ ਦੀ ਜਾਂਚ ਕਰ ਰਿਹਾ ਹੈ",
    "payment": "ਭੁਗਤਾਨ",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "ਆਵਾਜਾਈ",
    "automation": "ਆਟੋਮੇਸ਼ਨ",
    "inventory": "ਵੇਅਰਹਾਊਸਿੰਗ",
    "accounting": "ਲੇਖਾ",
    "marketing": "ਮਾਰਕੀਟਿੰਗ",
    "advertising": "ਇਸ਼ਤਿਹਾਰਬਾਜ਼ੀ",
    "staff": "ਸਟਾਫ",
    "incentive": "ਪ੍ਰੋਤਸਾਹਨ",
    "shop": "ਦੁਕਾਨ"
  },
  "social_network": {
    "instagram": "Instagram",
    "telegram": "ਟੈਲੀਗ੍ਰਾਮ",
    "googleplay": "GooglePlay",
    "appstore": "ਐਪ ਸਟੋਰ",
    "twitter": "ਟਵਿੱਟਰ",
    "linkedin": "ਲਿੰਕਡਇਨ",
    "medium": "ਦਰਮਿਆਨਾ",
    "selldone": "ਵੇਚਿਆ",
    "facebook": "ਫੇਸਬੁੱਕ",
    "pinterest": "Pinterest",
    "whatsapp": "ਵਟਸਐਪ",
    "skype": "ਸਕਾਈਪ",
    "facebook_messenger": "ਫੇਸਬੁੱਕ ਮੈਸੇਂਜਰ"
  },
  "form_builder": {
    "add_item_action": "ਨਵੀਂ ਆਈਟਮ ਸ਼ਾਮਲ ਕਰੋ",
    "title_input": "ਸਿਰਲੇਖ",
    "name_input": "ਵੇਰੀਏਬਲ ਨਾਮ",
    "value_input": "ਮੁੱਲ",
    "value_input_message": "ਉਪਭੋਗਤਾ ਵਿਕਲਪਾਂ ਦੀ ਸੂਚੀ",
    "default": "ਪੂਰਵ-ਨਿਰਧਾਰਤ ਮੁੱਲ",
    "types": {
      "simple": "ਆਸਾਨ",
      "selective": "ਚੋਣਵੇਂ",
      "switch": "ਸਵਿੱਚ ਕਰੋ"
    }
  },
  "virtual_order_info_summery": {
    "title": "ਉਤਪਾਦ ਦਾ ਨਾਮ",
    "reserved_at": "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਮਿਤੀ",
    "total_price": "ਕੁੱਲ ਮਾਤਰਾ",
    "discount": "ਛੂਟ",
    "final_price": "ਅੰਤਮ ਰਕਮ",
    "payment_status": "ਭੁਗਤਾਨ ਸਥਿਤੀ",
    "payment_status_waiting": "ਭੁਗਤਾਨ ਦੀ ਉਡੀਕ ਕਰ ਰਿਹਾ ਹੈ",
    "payment_status_paid": "ਦਾ ਭੁਗਤਾਨ",
    "buyer": "ਖਰੀਦਦਾਰ"
  },
  "virtual_item_info": {
    "title": "ਵਰਚੁਅਲ ਆਈਟਮ",
    "outputs": {
      "title": "ਆਉਟਪੁੱਟ ਜਾਣਕਾਰੀ",
      "sub_title": "ਇਸ ਆਈਟਮ ਦੀ ਗੁਪਤ ਜਾਣਕਾਰੀ",
      "message": "ਇਹ ਜਾਣਕਾਰੀ ਉਤਪਾਦ ਖਰੀਦਣ ਤੋਂ ਬਾਅਦ ਉਪਭੋਗਤਾ ਨੂੰ ਦਿਖਾਈ ਜਾਵੇਗੀ।"
    },
    "inputs": {
      "title": "ਜਾਣਕਾਰੀ ਦੀ ਲੋੜ ਹੈ",
      "sub_title": "ਖਰੀਦਦਾਰ ਜਾਣਕਾਰੀ ਦੀ ਲੋੜ ਹੈ",
      "message": "ਖਰੀਦਦਾਰ ਨੂੰ ਫਾਰਮ ਵਿੱਚ ਬੇਨਤੀ ਕੀਤੀ ਜਾਣਕਾਰੀ ਦਰਜ ਕਰਨੀ ਚਾਹੀਦੀ ਹੈ"
    },
    "notifications": {
      "inputs_set_success": "ਜਾਣਕਾਰੀ ਫਾਰਮ ਸਫਲਤਾਪੂਰਵਕ ਰਜਿਸਟਰ ਕੀਤਾ ਗਿਆ।",
      "confirm_by_admin_success": "ਆਰਡਰ ਪੂਰਾ ਹੋਣ ਦੀ ਪੁਸ਼ਟੀ ਕੀਤੀ ਗਈ।",
      "confirm_by_buyer_success": "ਆਰਡਰ ਪੂਰਾ ਹੋਣ ਦੀ ਪੁਸ਼ਟੀ ਕੀਤੀ ਗਈ।"
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "ਇਹ ਆਰਡਰ COD ਭੁਗਤਾਨ ਦੁਆਰਾ ਸਵੀਕਾਰ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਦਾ ਹੈ।",
    "payment_returned": "ਗਾਹਕ ਦੁਆਰਾ ਭੁਗਤਾਨ ਵਾਪਸ ਕਰ ਦਿੱਤਾ ਗਿਆ ਹੈ.",
    "payment_fraud": "ਭੁਗਤਾਨ ਨੂੰ ਧੋਖਾਧੜੀ ਵਜੋਂ ਪਛਾਣਿਆ ਗਿਆ ਹੈ।",
    "location_out_of_service": "ਗਾਹਕ ਦੀ ਸਥਿਤੀ ਸੇਵਾ ਤੋਂ ਬਾਹਰ ਹੈ।",
    "user_not_responding": "ਗਾਹਕ ਨੇ ਕਾਲਾਂ ਦਾ ਜਵਾਬ ਨਹੀਂ ਦਿੱਤਾ।",
    "shop_owner_fault": "ਸਟੋਰ ਦੇ ਸਟਾਫ਼ ਦੁਆਰਾ ਜਾਣਕਾਰੀ ਭਰਨ ਵਿੱਚ ਇੱਕ ਤਰੁੱਟੀ ਆਈ ਹੈ।",
    "lack_of_inventory": "ਖਤਮ ਹੈ.",
    "legal_restriction": "ਕਨੂੰਨੀ ਪਾਬੰਦੀਆਂ ਕਾਰਨ ਆਰਡਰ ਦੇਣ ਵਿੱਚ ਅਸਮਰੱਥ।",
    "pricing_fault": "ਵਿਕਰੇਤਾ ਦੁਆਰਾ ਕੀਮਤ ਦੀ ਗਲਤੀ.",
    "system_fault": "ਸਿਸਟਮ ਬੱਗ।"
  },
  "basket_order_info_summery": {
    "receiver": "ਪ੍ਰਾਪਤ ਕਰਨ ਵਾਲਾ",
    "phone": "ਟੈਲੀ",
    "reserved_date": "ਖਰੀਦ ਦੀ ਮਿਤੀ",
    "total_price": "ਕੁੱਲ ਮਾਤਰਾ",
    "discount": "ਛੂਟ",
    "final_price": "ਅੰਤਮ ਰਕਮ",
    "address": "ਡਿਲੀਵਰੀ ਦਾ ਪਤਾ",
    "payment_status": "ਭੁਗਤਾਨ ਸਥਿਤੀ"
  },
  "basket_status": {
    "open": "ਖੋਲ੍ਹੋ",
    "reserved": "ਰਾਖਵਾਂ",
    "paid": "ਦਾ ਭੁਗਤਾਨ",
    "canceled": "ਰੱਦ ਕਰ ਦਿੱਤਾ",
    "cod": "ਡਿਲਿਵਰੀ 'ਤੇ ਭੁਗਤਾਨ ਕਰੋ",
    "receipt_added": "ਰਸੀਦ ਸ਼ਾਮਲ ਕੀਤੀ ਗਈ",
    "payment_processing": "ਭੁਗਤਾਨ ਪ੍ਰਕਿਰਿਆ"
  },
  "basket_delivery_state": {
    "rejected": "ਰੱਦ ਕਰ ਦਿੱਤਾ",
    "reject_reason_not_found": "ਕਾਰਨ ਅਣਜਾਣ ਹੈ.",
    "step_1": "ਸਮੀਖਿਆ",
    "step_2": "ਪੁਸ਼ਟੀ",
    "step_3": "ਤਿਆਰੀ",
    "step_4": "ਡਿਲੀਵਰੀ 'ਤੇ",
    "step_5": "ਡਿਲੀਵਰ ਕੀਤਾ"
  },
  "basket_return_request_view": {
    "title": "ਵਾਪਸੀ ਦੀ ਬੇਨਤੀ",
    "delivery_date": "ਪਹੁੰਚਾਉਣ ਦੀ ਮਿਤੀ",
    "return_date": "ਬੇਨਤੀ ਦੀ ਮਿਤੀ",
    "items_count": "ਵਾਪਸ ਆਈਟਮਾਂ ਦੀ ਗਿਣਤੀ",
    "items_count_unit": "ਇਕਾਈ)",
    "reason": "ਕਾਰਨ",
    "description": "ਵਰਣਨ",
    "status": "ਸਥਿਤੀ",
    "download_image": "ਚਿੱਤਰ ਡਾਊਨਲੋਡ ਕਰੋ",
    "download_film": "ਵੀਡੀਓ ਡਾਊਨਲੋਡ ਕਰੋ",
    "download_voice": "ਅਵਾਜ਼ ਡਾਊਨਲੋਡ ਕਰੋ",
    "accept_by_admin_action": "ਬੇਨਤੀ ਸਵੀਕਾਰ ਕਰੋ",
    "reject_by_admin_action": "ਬੇਨਤੀ ਨੂੰ ਅਸਵੀਕਾਰ ਕਰੋ",
    "message_for_admin": "ਸੇਲਡੋਨ ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਤੁਹਾਡੇ ਦੁਆਰਾ ਸਵੀਕਾਰ ਕੀਤੇ ਗਏ ਸਮਝੌਤੇ ਦੇ ਅਨੁਸਾਰ, ਤੁਹਾਨੂੰ ਖਰੀਦਦਾਰ ਨਾਲ ਸੰਪਰਕ ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ ਅਤੇ ਉਸਨੂੰ ਉਸਦੇ ਆਰਡਰ ਨੂੰ ਵਾਪਸ ਕਰਨ ਦੀ ਪ੍ਰਕਿਰਿਆ ਬਾਰੇ ਸੂਚਿਤ ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ। ਜੇਕਰ ਬੇਨਤੀ ਸਵੀਕਾਰ ਜਾਂ ਅਸਵੀਕਾਰ ਕੀਤੀ ਜਾਂਦੀ ਹੈ ਅਤੇ ਖਰੀਦਦਾਰ ਦੀ ਪੂਰੀ ਸਹਿਮਤੀ ਪ੍ਰਾਪਤ ਕੀਤੀ ਜਾਂਦੀ ਹੈ ਤਾਂ ਅਜਿਹਾ ਕਰਨਾ ਲਾਜ਼ਮੀ ਹੈ।",
    "notifications": {
      "update_status_success": "ਬੇਨਤੀ ਸਥਿਤੀ ਅੱਪਡੇਟ ਕੀਤੀ ਗਈ।"
    }
  },
  "basket_list": {
    "return_count": "ਵਾਪਸੀ: {count} ਨੰਬਰ",
    "table": {
      "row": "ਕਤਾਰ",
      "image": "ਚਿੱਤਰ",
      "product_name": "ਉਤਪਾਦ",
      "variant": "ਰੂਪ",
      "warranty": "ਵਾਰੰਟੀਆਂ",
      "count": "ਗਿਣਤੀ",
      "price": "ਕੀਮਤ"
    }
  },
  "return_request_list": {
    "count": "ਹਵਾਲਾ ਨੰਬਰ",
    "return_warranty": "ਪੈਸੇ ਵਾਪਸ ਕਰਨ ਦੀ ਗਾਰੰਟੀ",
    "return_warranty_unit": "ਦਿਨ(ਦਿਨ)",
    "table": {
      "code": "ਆਰਡਰ ਕੋਡ",
      "product": "ਉਤਪਾਦ",
      "delivery_at": "ਪ੍ਰਾਪਤੀ ਦੀ ਮਿਤੀ",
      "state": "ਸਥਿਤੀ",
      "reason": "ਕਾਰਨ",
      "return_warranty_period": "ਵਾਰੰਟੀ ਦੀ ਮਿਆਦ"
    }
  },
  "data_toolbar": {
    "search": "ਖੋਜ",
    "sort_by": "ਦੇ ਨਾਲ ਕ੍ਰਮਬੱਧ",
    "count_item": "{item} ਆਈਟਮਾਂ ਦਿਖਾਓ"
  },
  "sort": {
    "created_at": "ਤਾਰੀਖ ਬਣਾਓ",
    "updated_at": "ਤਾਰੀਖ ਦਾ ਸੰਪਾਦਨ ਕਰੋ",
    "title": "ਸਿਰਲੇਖ",
    "description": "ਵਰਣਨ",
    "like": "ਪ੍ਰਸਿੱਧੀ",
    "power": "ਤਾੜੀਆਂ",
    "product_type": "ਉਤਪਾਦ ਦੀ ਕਿਸਮ",
    "discount": "ਛੂਟ",
    "rate": "ਰੇਟਿੰਗ",
    "rate_count": "ਰੇਟਿੰਗਾਂ ਦੀ ਗਿਣਤੀ",
    "category": "ਸ਼੍ਰੇਣੀ",
    "product": "ਉਤਪਾਦ",
    "body": "ਸਮੱਗਰੀ",
    "card_type": "ਕਾਰਡ ਦੀ ਕਿਸਮ",
    "card_number": "ਕਾਰਡ ਨੰਬਰ",
    "balance": "ਸੰਤੁਲਨ",
    "paid": "ਖਰਚ ਕੀਤੀ ਰਕਮ",
    "currency": "ਮੁਦਰਾ",
    "expire_at": "ਅੰਤ ਦੀ ਤਾਰੀਖ",
    "discount_code": "ਛੋਟ ਕੋਡ",
    "discount_percent": "ਛੂਟ",
    "discount_limit": "ਛੂਟ ਸੀਮਾ",
    "max_count": "ਵੱਧ ਤੋਂ ਵੱਧ ਗਿਣਤੀ",
    "used_count": "ਵਰਤਿਆ",
    "start_date": "ਤਾਰੀਖ ਸ਼ੁਰੂ",
    "end_date": "ਸਮਾਪਤੀ ਮਿਤੀ",
    "total_discount_amount": "ਕੁੱਲ ਛੋਟਾਂ",
    "initial_charge": "ਸ਼ੁਰੂਆਤੀ ਚਾਰਜ",
    "total_count": "ਕੁੱਲ ਗਿਣਤੀ",
    "amount_paid": "ਭੁਗਤਾਨ ਕੀਤੀ ਰਕਮ",
    "name": "ਨਾਮ",
    "published": "ਪ੍ਰਕਾਸ਼ਿਤ",
    "visits": "ਮੁਲਾਕਾਤਾਂ",
    "color": "ਰੰਗ",
    "landing_page": "ਲੈਂਡਿੰਗ ਪੰਨਾ",
    "enable": "ਯੋਗ ਕਰੋ",
    "fix_commission": "ਸਥਿਰ ਕਮਿਸ਼ਨ",
    "percent_commission": "ਪ੍ਰਤੀਸ਼ਤ ਕਮਿਸ਼ਨ",
    "payment_at": "ਭੁਗਤਾਨ ਦੀ ਮਿਤੀ",
    "issued_at": "ਜਾਰੀ ਕਰਨ ਦੀ ਮਿਤੀ",
    "payment": "ਭੁਗਤਾਨ",
    "website": "ਵੈੱਬਸਾਈਟ",
    "email": "ਈ - ਮੇਲ",
    "user": "ਉਪਭੋਗਤਾ",
    "code": "ਕੋਡ",
    "schedule_at": "ਸਮਾਂ ਤਹਿ ਕਰੋ",
    "sender": "ਭੇਜਣ ਵਾਲਾ",
    "in_que": "ਕਤਾਰ ਵਿਚ",
    "sent": "ਭੇਜਿਆ",
    "shop": "ਦੁਕਾਨ",
    "quantity": "ਮਾਤਰਾ",
    "amount": "ਦੀ ਰਕਮ",
    "jobs": "ਨੌਕਰੀਆਂ ਦੀ ਗਿਣਤੀ",
    "success": "ਸਫਲਤਾ ਦੀ ਗਿਣਤੀ",
    "fail": "ਅਸਫਲ ਗਿਣਤੀ",
    "distance": "ਦੂਰੀ",
    "duration": "ਮਿਆਦ",
    "reset_at": "ਤਾਰੀਖ ਰੀਸੈਟ ਕਰੋ",
    "delivery_person": "ਵਿਅਕਤੀ",
    "delivery_service": "ਸੇਵਾ",
    "date": "ਤਾਰੀਖ਼",
    "order": "ਆਰਡਰ",
    "order_id": "ਆਰਡਰ ਆਈ.ਡੀ",
    "status": "ਸਥਿਤੀ",
    "price": "ਕੀਮਤ",
    "count": "ਗਿਣਤੀ",
    "final_price": "ਅੰਤਿਮ ਕੀਮਤ",
    "charge": "ਚਾਰਜ",
    "mention": "ਜ਼ਿਕਰ",
    "officer": "ਅਧਿਕਾਰੀ",
    "registered": "ਰਜਿਸਟਰਡ",
    "purchased": "ਖਰੀਦਿਆ",
    "sex": "ਲਿੰਗ"
  },
  "search_box": {
    "result": "ਖੋਜ ਨਤੀਜੇ",
    "tips": "ਉਤਪਾਦਾਂ ਅਤੇ ਸ਼੍ਰੇਣੀਆਂ ਦੀ ਖੋਜ ਕਰੋ",
    "label": "ਖੋਜ...",
    "category": "ਸ਼੍ਰੇਣੀ"
  },
  "lead_status": {
    "physical_fast_delivery": "ਤੁਰੰਤ ਡਿਲੀਵਰੀ",
    "physical_under_24h_delivery": "ਅਗਲੇ {lead} ਘੰਟਿਆਂ ਦੇ ਅੰਦਰ ਡਿਲੀਵਰ ਕਰੋ",
    "physical_over_24h_delivery": "ਅਗਲੇ {days} ਦਿਨਾਂ ਤੋਂ ਤਿਆਰੀ ਅਤੇ ਸਪੁਰਦ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ",
    "virtual_fast_prepare": "ਤੁਰੰਤ ਡਿਲੀਵਰੀ",
    "virtual_under_24h": "ਅਗਲੇ {lead} ਘੰਟਿਆਂ ਵਿੱਚ ਕੀਤਾ ਜਾਵੇਗਾ",
    "virtual_over_24h": "ਅਗਲੇ {days} ਦਿਨਾਂ ਤੋਂ ਕੀਤਾ ਜਾਵੇਗਾ"
  },
  "return_request_state": {
    "pending": "ਬਕਾਇਆ",
    "accepted": "ਪੱਕਾ",
    "rejected": "ਰੱਦ ਕਰ ਦਿੱਤਾ"
  },
  "return_order_reason": {
    "physical": {
      "U1": "ਉਤਪਾਦ ਬੇਮੇਲ",
      "U2": "ਸ਼ਿਪਿੰਗ ਪੈਕੇਜ ਵਿੱਚ ਕੋਈ ਉਤਪਾਦ ਨਹੀਂ",
      "U3": "ਪੈਕੇਜ ਜਾਂ ਉਤਪਾਦ ਟੁੱਟਣਾ",
      "U4": "ਪੈਕੇਜ ਜਾਂ ਸੀਰੀਅਲ ਨੰਬਰ ਨਾਲ ਛੇੜਛਾੜ",
      "U5": "ਪਾਰਸਲ ਵਿੱਚੋਂ ਕੁਝ ਆਈਟਮਾਂ ਗਾਇਬ ਹਨ",
      "U6": "ਉਤਪਾਦ ਅਸਲੀ ਨਹੀਂ ਹੈ",
      "U7": "ਉਤਪਾਦ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ ਨੂੰ ਪੂਰਾ ਨਹੀਂ ਕਰਦਾ"
    }
  },
  "image_uploader": {
    "label": "ਡਰੈਗ ਐਂਡ ਡ੍ਰੌਪ ਜਾਂ <u>ਫਾਈਲ ਚੁਣੋ</u>",
    "max_size": "ਅਧਿਕਤਮ ਮਨਜ਼ੂਰ ਆਕਾਰ: {size}"
  },
  "timespan": {
    "Morning": "8am - 12pm",
    "Evening": "ਦੁਪਹਿਰ 12 ਤੋਂ ਸ਼ਾਮ 6 ਵਜੇ ਤੱਕ",
    "Night": "ਸ਼ਾਮ 6-12 ਵਜੇ",
    "Instant": "ਤੁਰੰਤ ਪੋਸਟ"
  },
  "week_day": {
    "Saturday": "ਸ਼ਨੀਵਾਰ",
    "Sunday": "ਐਤਵਾਰ",
    "Monday": "ਸੋਮਵਾਰ",
    "Tuesday": "ਮੰਗਲਵਾਰ",
    "Wednesday": "ਬੁੱਧਵਾਰ",
    "Thursday": "ਵੀਰਵਾਰ",
    "Friday": "ਸ਼ੁੱਕਰਵਾਰ"
  },
  "payment_form": {
    "title": "ਭੁਗਤਾਨ ਵਿਧੀ ਚੁਣੋ",
    "gift_cards_input": "ਗਿਫਟ ਕਾਰਡ",
    "gift_cards_input_empty": "ਕੋਈ ਗਿਫਟ ਕਾਰਡ ਨਹੀਂ ਮਿਲੇ..",
    "more": "ਹੋਰ",
    "pay_amount_by_gift_cards": "ਚਾਰਜ ਕਾਰਡ ਭੁਗਤਾਨ",
    "select_payment_method": "ਹੇਠਾਂ ਦਿੱਤੇ ਵਿਕਲਪਾਂ ਵਿੱਚੋਂ ਆਪਣੀ ਭੁਗਤਾਨ ਵਿਧੀ ਚੁਣੋ।",
    "payment_amount_remained": "ਬਾਕੀ ਭੁਗਤਾਨ ਦੀ ਰਕਮ",
    "payment_amount": "ਭੁਗਤਾਨ ਕੀਤੀ ਰਕਮ",
    "all_paid_by_gift_cards": "ਵਧਾਈਆਂ, ਤੁਹਾਨੂੰ ਇਸ ਆਰਡਰ ਲਈ ਭੁਗਤਾਨ ਕਰਨ ਦੀ ਲੋੜ ਨਹੀਂ ਹੈ। ਗਿਫਟ ਕਾਰਡ ਕੁੰਜੀ ਨਾਲ ਭੁਗਤਾਨ ਕਰੋ ਨੂੰ ਦਬਾਓ।",
    "pay_by_gift_cards_action": "ਚਾਰਜ ਕਾਰਡ ਨਾਲ ਆਰਡਰ ਦਾ ਭੁਗਤਾਨ ਕਰੋ",
    "order_free_payment": "ਵਧਾਈਆਂ, ਤੁਹਾਡਾ ਆਰਡਰ ਮੁਫਤ ਹੈ!",
    "order_free_payment_action": "ਹੁਣੇ ਮੁਫਤ ਆਰਡਰ ਕਰੋ",
    "qr": {
      "address": "ਭੁਗਤਾਨ ਪਤਾ",
      "amount": "ਦੀ ਰਕਮ"
    }
  },
  "discount_input": {
    "limit": "{limit} {currency} ਤੱਕ {percent}% ਛੋਟ",
    "action": "ਛੂਟ ਕੋਡ ਸ਼ਾਮਲ ਕਰੋ",
    "code_input": "ਛੋਟ ਕੋਡ",
    "notifications": {
      "add_success": "ਵਧਾਈਆਂ, ਵੈਧ ਛੂਟ ਕੋਡ।"
    }
  },
  "gift_card": {
    "inactive": "ਕਾਰਡ ਅਯੋਗ ਹੈ",
    "expire": "ਮਿਆਦ ਪੁੱਗਣ",
    "transfer": "ਟ੍ਰਾਂਸਫਰ ਕਰੋ",
    "send_to_friend": "ਦੋਸਤ ਨੂੰ ਭੇਜੋ"
  },
  "count_down": {
    "days": "ਦਿਨ",
    "hours": "ਘੰਟਾ",
    "minutes": "ਮਿੰਟ",
    "seconds": "ਸਕਿੰਟ"
  },
  "gift_status": {
    "Unpaid": "ਰਸੀਦ ਦਾ ਇੰਤਜ਼ਾਰ ਕਰ ਰਿਹਾ ਹਾਂ",
    "Paid": "ਦਾ ਭੁਗਤਾਨ",
    "Rejected": "ਰੱਦ ਕਰ ਦਿੱਤਾ",
    "Canceled": "ਰੱਦ ਕਰ ਦਿੱਤਾ"
  },
  "gift_program_status": {
    "Airdrop": "ਭੁਗਤਾਨ ਸਿਸਟਮ",
    "Advertising": "ਇਸ਼ਤਿਹਾਰਬਾਜ਼ੀ",
    "PersonalGift": "ਨਿੱਜੀ ਤੋਹਫ਼ਾ",
    "ShopGift": "ਤੋਹਫਿਆਂ ਦੀ ਦੁਕਾਨ"
  },
  "currency_selector": {
    "label": "ਮੁਦਰਾ"
  },
  "need_login": {
    "title": "ਲਾਗਿਨ",
    "login_sms": "SMS ਲਾਗਇਨ",
    "login_google": "ਗੂਗਲ ਨਾਲ ਲੌਗਇਨ ਕਰੋ",
    "login_facebook": "Facebook ਨਾਲ ਲੌਗਇਨ ਕਰੋ",
    "login_account": "Selldone ਦੁਆਰਾ ਲੌਗਇਨ ਕਰੋ",
    "register": "ਨਵਾਂ ਉਪਭੋਗਤਾ? ਹੁਣੇ ਦਰਜ ਕਰਵਾਓ.",
    "mobile_input": "ਆਪਣਾ ਮੋਬਾਈਲ ਦਾਖਲ ਕਰੋ",
    "verification_code": "ਪੜਤਾਲ ਕੋਡ",
    "msg_title": "ਹੈਲੋ,",
    "msg_body": "ਕਿਰਪਾ ਕਰਕੇ ਲਾਗਇਨ ਕਰੋ। ਇਸ ਵਿੱਚ ਸਿਰਫ਼ ਕੁਝ ਸਕਿੰਟ ਲੱਗਦੇ ਹਨ।"
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "5 ਸਾਲ ਦਾ ਗੋਲਡ ਸਟੋਰ"
    },
    "GOLDEN_2YEAR": {
      "name": "4 ਸਾਲ ਦਾ ਗੋਲਡ ਸਟੋਰ"
    },
    "GOLDEN_3YEAR": {
      "name": "3 ਸਾਲ ਦਾ ਗੋਲਡ ਸਟੋਰ"
    },
    "GOLDEN_4YEAR": {
      "name": "2 ਸਾਲ ਦਾ ਗੋਲਡ ਸਟੋਰ"
    },
    "GOLDEN_5YEAR": {
      "name": "1 ਸਾਲ ਦਾ ਗੋਲਡ ਸਟੋਰ"
    },
    "TOKEN_OWNER_1M": {
      "name": "ਗੋਲਡਨ ਨਿਵੇਸ਼ਕ"
    },
    "TOKEN_OWNER_10M": {
      "name": "ਹੀਰਾ ਨਿਵੇਸ਼ਕ"
    },
    "TOKEN_OWNER_100M": {
      "name": "ਰੂਬੀ ਨਿਵੇਸ਼ਕ"
    },
    "COMMUNITY_LOYAL": {
      "name": "ਸੁਪੀਰੀਅਰ ਕਮਿਊਨਿਟੀ ਆਫ ਕਮਿਊਨੀਕੇਸ਼ਨ ਨੈੱਟਵਰਕ ਦਾ ਮੈਂਬਰ"
    },
    "GOLD_SUPPLIER": {
      "name": "ਗੋਲਡ ਸਪਲਾਇਰ"
    },
    "GOLD_SELLER": {
      "name": "ਸੋਨੇ ਦਾ ਵਪਾਰੀ"
    },
    "CONTENT_SUPERMAN": {
      "name": "ਪ੍ਰਮੁੱਖ ਸਮਗਰੀ ਨਿਰਮਾਤਾ"
    },
    "NINJA": {
      "name": "ਨਿੰਜਾ"
    },
    "STAR": {
      "name": "ਤਾਰਾ"
    },
    "GUARDIAN": {
      "name": "ਮਹਾਨ ਗਾਹਕ ਸੇਵਾ"
    },
    "KING": {
      "name": "ਬਜ਼ਾਰ ਦਾ ਰਾਜਾ"
    }
  },
  "cookie": {
    "title": "ਇਹ ਵੈੱਬਸਾਈਟ ਕੂਕੀਜ਼ ਦੀ ਵਰਤੋਂ ਕਰਦੀ ਹੈ",
    "message": "ਇਹ ਵੈੱਬਸਾਈਟ ਉਪਭੋਗਤਾ ਅਨੁਭਵ ਨੂੰ ਬਿਹਤਰ ਬਣਾਉਣ ਲਈ ਕੂਕੀਜ਼ ਦੀ ਵਰਤੋਂ ਕਰਦੀ ਹੈ। ਸਾਡੀ ਵੈਬਸਾਈਟ ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਤੁਸੀਂ ਸਾਡੀ ਕੂਕੀ ਨੀਤੀ ਦੇ ਅਨੁਸਾਰ ਸਾਰੀਆਂ ਕੂਕੀਜ਼ ਲਈ ਸਹਿਮਤੀ ਦਿੰਦੇ ਹੋ।",
    "preferences_action": "ਤਰਜੀਹਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ",
    "agree_action": "ਮੈਂ ਸਹਿਮਤ ਹਾਂ l"
  },
  "basket_item_message": {
    "title": "ਇਸ ਆਈਟਮ ਲਈ ਲੋੜੀਂਦੀ ਜਾਣਕਾਰੀ",
    "save_actions": "ਸੁਨੇਹਾ ਸੁਰੱਖਿਅਤ ਕਰੋ",
    "notifications": {
      "success": "ਤੁਹਾਡਾ ਇਨਪੁਟ ਡੇਟਾ ਸੁਰੱਖਿਅਤ ਕੀਤਾ ਗਿਆ ਹੈ।"
    }
  },
  "faq": {
    "faq": "ਅਕਸਰ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ",
    "title": "ਸਵਾਲ ਅਤੇ ਜਵਾਬ",
    "sub_title": "ਜੋ ਤੁਸੀਂ ਸਾਨੂੰ ਕਰਨ ਲਈ ਕਿਹਾ ਹੈ।",
    "message": "ਹੇਠਾਂ ਦਿੱਤੇ ਜਵਾਬਾਂ ਵਿੱਚੋਂ ਆਪਣੇ ਸਵਾਲ ਦਾ ਜਵਾਬ ਲੱਭੋ। ਸਾਨੂੰ ਪੁੱਛੋ ਕਿ ਕੀ ਸਵਾਲ ਜਵਾਬ ਨਹੀਂ ਹਨ।",
    "add_question_action": "ਨਵਾਂ ਸਵਾਲ ਪੁੱਛੋ",
    "read_more": "ਹੋਰ ਪੜ੍ਹੋ ..",
    "load_more": "ਹੋਰ ਸਵਾਲ ..",
    "main_page": "FAQ ਮੁੱਖ ਪੰਨਾ",
    "add_new": "ਨਵਾਂ ਸਵਾਲ ਦਰਜ ਕਰੋ",
    "login_alert": "ਕੋਈ ਸਵਾਲ ਪੁੱਛਣ ਲਈ ਲੌਗ ਇਨ ਕਰੋ।",
    "question_input": "ਸਵਾਲ",
    "question_input_placeholder": "ਆਪਣਾ ਸਵਾਲ ਪੁੱਛੋ।",
    "notifications": {
      "success_add": "ਤੁਹਾਡਾ ਸਵਾਲ ਸਫਲਤਾਪੂਰਵਕ ਸਪੁਰਦ ਕੀਤਾ ਗਿਆ।"
    }
  },
  "rating_labels": [
    "ਬਹੁਤ ਬੁਰਾ",
    "ਬੁਰਾ",
    "ਸਧਾਰਣ",
    "ਚੰਗਾ",
    "ਸ਼ਾਨਦਾਰ"
  ],
  "map_view": {
    "address_detail": "ਪਤੇ ਦੇ ਵੇਰਵੇ",
    "change": "ਬਦਲੋ",
    "select": "ਚੁਣੋ",
    "not_found_address": "ਕੋਈ ਮੁੱਲ ਨਹੀਂ ਮਿਲਿਆ",
    "enter_address_hint": "ਮੰਜ਼ਿਲ ਦਾ ਪਤਾ ਦਾਖਲ ਕਰੋ",
    "enter_your_address": "ਆਪਣਾ ਪਤਾ ਦਰਜ ਕਰੋ।",
    "postal_code": "ਪੋਸਟਕੋਡ",
    "phone_input": "ਫ਼ੋਨ {type}",
    "building_number": "ਬਿਲਡਿੰਗ ਨੰਬਰ",
    "building_unit": "ਯੂਨਿਟ",
    "full_name_input": "ਪੂਰਾ ਨਾਮ {type}",
    "save_detail_action": "ਵੇਰਵੇ ਸੁਰੱਖਿਅਤ ਕਰੋ",
    "more_detail_input": "ਹੋਰ ਵੇਰਵਾ",
    "add_address_to_list": "ਸੂਚੀ ਵਿੱਚ ਪਤਾ ਸ਼ਾਮਲ ਕਰੋ",
    "address_title_input": "ਪਤਾ ਲੇਬਲ (ਲੋੜੀਂਦਾ ਹੈ)",
    "notifications": {
      "save_in_list": "ਇਹ ਪਤਾ ਇਸ ਦੇ ਸਾਰੇ ਵੇਰਵਿਆਂ ਦੇ ਨਾਲ ਤੁਹਾਡੀ ਸੂਚੀ ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਕੀਤਾ ਗਿਆ ਹੈ।",
      "edit_success": "ਨਵੇਂ ਪਤਾ ਮੁੱਲ {title} ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਕੀਤੇ ਗਏ ਹਨ।"
    },
    "delete_address_dialog": {
      "title": "ਪਤਾ ਮਿਟਾਓ",
      "message": "ਕੀ ਤੁਸੀਂ ਯਕੀਨਨ ਇਸ ਪਤੇ ਨੂੰ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
      "action": "ਪਤਾ ਹਟਾਓ"
    }
  },
  "comment_manager": {
    "can_not_edit": "ਇਸ ਟਿੱਪਣੀ ਦਾ ਸੰਪਾਦਨ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਦਾ!",
    "comment_input_empty": "ਸੁਨੇਹਾ ਟੈਕਸਟ ਖਾਲੀ ਹੈ!",
    "article_not_saved": "ਲੇਖ ਨੂੰ ਸੰਭਾਲੋ!"
  },
  "wheel_fortune": {
    "title": "ਖੇਡੋ ਅਤੇ ਜਿੱਤੋ",
    "message": "ਹਰੇਕ ਗੇਮ ਦੀ ਕੀਮਤ 10 ਚਿਪਸ ਹੈ। ਤੁਹਾਡੇ ਕੋਲ ਇਸ ਵੇਲੇ {chips} ਚਿੱਪ ਹੈ। ਸਟੋਰ ਤੋਂ ਖਰੀਦ ਕੇ ਹੋਰ ਚਿੱਪ ਪ੍ਰਾਪਤ ਕਰੋ।",
    "win_message": "ਵਧਾਈਆਂ, ਤੁਸੀਂ ਜਿੱਤ ਗਏ!",
    "lost_message": "ਮਾਫ਼ ਕਰਨਾ, ਤੁਸੀਂ ਗੇਮ ਹਾਰ ਗਏ।",
    "try_again": "ਤੁਸੀਂ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰ ਸਕਦੇ ਹੋ"
  },
  "json": {
    "add": "ਢਾਂਚਾ ਡਾਟਾ ਸ਼ਾਮਲ ਕਰੋ",
    "add_message": "ਨਵਾਂ ਢਾਂਚਾ ਡਾਟਾ ਬਣਾਓ",
    "structures": "ਬਣਤਰ",
    "book": {
      "title": "ਕਿਤਾਬ",
      "desc": "ਕਿਤਾਬ ਦੀਆਂ ਕਾਰਵਾਈਆਂ ਜੋ ਉਪਭੋਗਤਾਵਾਂ ਨੂੰ ਉਹ ਕਿਤਾਬ ਖਰੀਦਣ ਦੇ ਯੋਗ ਬਣਾਉਂਦੀਆਂ ਹਨ ਜੋ ਉਹਨਾਂ ਨੂੰ ਖੋਜ ਨਤੀਜਿਆਂ ਤੋਂ ਸਿੱਧੇ ਮਿਲਦੀਆਂ ਹਨ।"
    },
    "occupation": {
      "title": "ਅੰਦਾਜ਼ਨ ਤਨਖਾਹ",
      "desc": "ਤਨਖ਼ਾਹ ਦੇ ਅਨੁਮਾਨ ਬਾਰੇ ਜਾਣਕਾਰੀ, ਜਿਵੇਂ ਕਿ ਤਨਖ਼ਾਹ ਦੀਆਂ ਰੇਂਜਾਂ ਅਤੇ ਨੌਕਰੀ ਦੀਆਂ ਕਿਸਮਾਂ ਲਈ ਖੇਤਰ-ਅਧਾਰਿਤ ਤਨਖ਼ਾਹ ਔਸਤ, Google 'ਤੇ ਨੌਕਰੀ ਖੋਜ ਅਨੁਭਵ ਵਿੱਚ ਪ੍ਰਦਰਸ਼ਿਤ ਕੀਤੀ ਜਾਂਦੀ ਹੈ।"
    },
    "course": {
      "title": "ਕੋਰਸ",
      "desc": "ਵਿਦਿਅਕ ਕੋਰਸ ਜੋ ਪ੍ਰਦਾਤਾ-ਵਿਸ਼ੇਸ਼ ਸੂਚੀ ਵਿੱਚ ਦਿਖਾਈ ਦਿੰਦੇ ਹਨ। ਕੋਰਸਾਂ ਵਿੱਚ ਕੋਰਸ ਦਾ ਸਿਰਲੇਖ, ਪ੍ਰਦਾਤਾ, ਅਤੇ ਇੱਕ ਛੋਟਾ ਵੇਰਵਾ ਸ਼ਾਮਲ ਹੋ ਸਕਦਾ ਹੈ।"
    },
    "howto": {
      "title": "ਕਿਵੇਂ",
      "desc": "ਵੀਡੀਓ, ਚਿੱਤਰ ਅਤੇ ਟੈਕਸਟ ਦੀ ਵਿਸ਼ੇਸ਼ਤਾ ਵਾਲੇ ਇੱਕ ਕੰਮ ਨੂੰ ਸਫਲਤਾਪੂਰਵਕ ਪੂਰਾ ਕਰਨ ਲਈ ਇੱਕ ਕਿਵੇਂ-ਕਿਵੇਂ ਕਰਨਾ ਹੈ ਉਪਭੋਗਤਾਵਾਂ ਨੂੰ ਕਦਮਾਂ ਦੇ ਇੱਕ ਸਮੂਹ ਵਿੱਚ ਲੈ ਜਾਂਦਾ ਹੈ।"
    },
    "recipe": {
      "title": "ਵਿਅੰਜਨ",
      "desc": "ਪਕਵਾਨਾਂ ਜੋ ਵਿਅਕਤੀਗਤ ਅਮੀਰ ਨਤੀਜੇ ਜਾਂ ਹੋਸਟ ਕੈਰੋਸਲ ਦੇ ਹਿੱਸੇ ਵਜੋਂ ਪ੍ਰਦਰਸ਼ਿਤ ਹੁੰਦੀਆਂ ਹਨ।"
    }
  },
  "support": {
    "Financial": "ਵਿੱਤੀ",
    "Technical": "ਤਕਨੀਕੀ",
    "Advisor": "ਸਲਾਹਕਾਰ"
  },
  "condition": {
    "new": "ਨਵਾਂ",
    "refurbished": "ਮੁਰੰਮਤ ਕੀਤੀ ਗਈ",
    "used": "ਵਰਤਿਆ",
    "used_fair": "ਨਿਰਪੱਖ ਵਰਤਿਆ",
    "used_good": "ਚੰਗਾ ਵਰਤਿਆ",
    "used_like_new": "ਨਵੇਂ ਵਾਂਗ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ"
  },
  "variant_filter": {
    "title": "ਉਤਪਾਦ ਵੇਰੀਐਂਟ ਫਿਲਟਰ",
    "only_available": "ਭੰਡਾਰ ਵਿੱਚ"
  },
  "service": {
    "task": {
      "title": "ਕਾਰਜ",
      "message": "ਇਸ ਸੇਵਾ ਵਿੱਚ ਕੀਤੇ ਕੰਮਾਂ ਦੀ ਸੂਚੀ।"
    },
    "appointment": {
      "title": "ਮੁਲਾਕਾਤ",
      "message": "ਤੁਹਾਡੇ ਲਈ ਸਹੀ ਦਿਨ ਅਤੇ ਘੰਟੇ ਦੇ ਆਧਾਰ 'ਤੇ ਹੇਠਾਂ ਦਿੱਤੇ ਸਮੇਂ ਵਿੱਚੋਂ ਹਫ਼ਤੇ ਦੇ ਸਮੇਂ ਦੀ ਚੋਣ ਕਰੋ।"
    },
    "booking": {
      "title": "ਬੁਕਿੰਗ",
      "message": "ਹੇਠਾਂ ਦਿੱਤੇ ਕੈਲੰਡਰ ਵਿੱਚ ਉਹਨਾਂ ਦਿਨਾਂ ਦੀ ਸਮਾਂ ਮਿਆਦ ਨਿਰਧਾਰਤ ਕਰੋ ਜਿਨ੍ਹਾਂ ਲਈ ਤੁਸੀਂ ਇੱਕ ਰਿਜ਼ਰਵੇਸ਼ਨ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ।"
    },
    "subscription": {
      "title": "ਗਾਹਕੀ"
    },
    "charge": {
      "title": "ਚਾਰਜ"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "ਸਥਿਰ ਕੀਮਤ",
      "message": "ਇਸ ਕਿਸਮ ਦੀ ਕੀਮਤ ਵਿੱਚ, ਉਤਪਾਦ ਦੀ ਕੀਮਤ ਇੱਕ ਨਿਸ਼ਚਿਤ ਰਕਮ ਹੁੰਦੀ ਹੈ ਅਤੇ ਖਰੀਦਦਾਰ ਨੂੰ ਕੀਮਤ ਦੀ ਗਣਨਾ ਲਈ ਬੇਨਤੀ ਕਰਨ ਦੀ ਕੋਈ ਲੋੜ ਨਹੀਂ ਹੁੰਦੀ ਹੈ।"
    },
    "ESTIMATION": {
      "title": "ਅਨੁਮਾਨ ਕੀਮਤ",
      "message": "ਉਤਪਾਦਾਂ ਅਤੇ ਸੇਵਾਵਾਂ ਦੀ ਕੀਮਤ ਦੀ ਗਣਨਾ ਕੁਝ ਹੱਦ ਤੱਕ ਵਿਕਰੇਤਾ ਦੁਆਰਾ ਕੀਤੀ ਜਾਵੇਗੀ ਜਦੋਂ ਇੱਕ ਆਰਡਰ ਦਿੱਤਾ ਜਾਂਦਾ ਹੈ, ਸੇਵਾ ਦੇ ਦੌਰਾਨ ਭੁਗਤਾਨ ਇਨਵੌਇਸ ਨੂੰ ਬਦਲਿਆ ਜਾਂ ਜੋੜਿਆ ਜਾ ਸਕਦਾ ਹੈ।"
    },
    "AGREEMENT": {
      "title": "ਇਕਰਾਰਨਾਮੇ ਦੀ ਕੀਮਤ",
      "message": "ਆਰਡਰ ਦਿੱਤੇ ਜਾਣ ਤੋਂ ਬਾਅਦ ਉਤਪਾਦਾਂ ਜਾਂ ਸੇਵਾਵਾਂ ਦੀ ਅੰਤਿਮ ਕੀਮਤ ਵਿਕਰੇਤਾ ਦੁਆਰਾ ਨਹੀਂ ਬਦਲੀ ਜਾਵੇਗੀ।"
    },
    "BID": {
      "title": "ਬੋਲੀ/ਨਿਲਾਮੀ",
      "message": "ਉਤਪਾਦ ਨੂੰ ਸੰਭਾਵੀ ਖਰੀਦਦਾਰਾਂ ਦੁਆਰਾ ਉੱਚਤਮ ਬੋਲੀ ਦੀ ਕੀਮਤ 'ਤੇ ਵੇਚਿਆ ਜਾਵੇਗਾ।"
    }
  },
  "map": {
    "title": "ਉਤਪਾਦ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਮੰਜ਼ਿਲ",
    "confirm": "ਟਿਕਾਣਾ ਸੈੱਟ ਕਰੋ",
    "address": "ਮੰਜ਼ਿਲ",
    "receptor": "ਪ੍ਰਾਪਤ ਕਰਨ ਵਾਲਾ"
  },
  "ShopBots": {
    "telegram": "ਟੈਲੀਗ੍ਰਾਮ"
  },
  "article_tags": {
    "title": "ਸਮੱਗਰੀ ਟੈਗਸ",
    "tags_input": "ਟੈਗਸ",
    "tags_input_message": "ਇਸ ਲੇਖ ਦੀ ਟੈਗ ਸੂਚੀ",
    "notification": {
      "add_success": "ਟੈਗ ਸ਼ਾਮਲ ਕੀਤੇ ਗਏ"
    }
  }
};