export default {
  "currency_default": "USD",
  "language_default": "pt",
  "selldone": "Vendido",
  "store": "armazenar",
  "not_exist": "Não existe",
  "error": "Erro",
  "active": "Ativo",
  "inactive": "inativo",
  "required_value": "Valores obrigatórios",
  "original_warranty": "Garantia do produto original",
  "return_warranty_days": "{days} dia(s) de garantia de devolução",
  "no_return_warranty": "Sem retorno",
  "reed_agree_terms": "Li os termos de uso e política de privacidade e concordo com eles.",
  "commons": {
    "Currency": "Moeda",
    "COD": "COD",
    "State": "Estado",
    "Price": "preço",
    "order_price": "Valor do pedido",
    "VAT": "VAT",
    "Discount": "Desconto",
    "In_Stock": "Em estoque",
    "Variants": "Variantes",
    "No_variants": "Nenhuma variante",
    "all": "TUDO",
    "today": "Hoje",
    "yesterday": "Ontem",
    "license": "Licença",
    "home": "Casa",
    "support": "Apoio, suporte",
    "messages": "Mensagens",
    "no_message": "Nenhuma mensagem",
    "empty": "Vazio",
    "phone": "Telefone",
    "address": "Morada",
    "name": "Nome",
    "password": "Senha",
    "email": "E-mail",
    "mobile": "Móvel",
    "login": "Conecte-se",
    "register": "Registro",
    "select_account": "Selecionar conta",
    "online": "Conectados",
    "offline": "desligada",
    "finish": "Terminar",
    "finished": "Finalizado",
    "preview": "Visualizar",
    "free": "Livre",
    "free_completely": "Assinatura totalmente gratuita",
    "fee": "Taxa",
    "month": "Mês",
    "months": "Meses",
    "faq": "perguntas frequentes",
    "question": "Pergunta",
    "answer": "Responda",
    "create_date": "Criar Data",
    "update_date": "Data de atualização",
    "start_date": "Data de início",
    "end_date": "Data final",
    "social": "Social",
    "total": "Total",
    "orders": "Pedidos",
    "sessions": "Sessões",
    "product_views": "Visualizações do produto",
    "add_to_carts": "Adicionar aos carrinhos",
    "checkouts": "Confira",
    "payments": "Pagamento",
    "organic_search": "Pesquisa orgânica",
    "other": "Outro",
    "landing_page": "Página de destino",
    "discount_code": "Código de desconto",
    "total_sell": "Vendas totais",
    "details": "Detalhes",
    "currency": "Moeda",
    "amount": "Resultar",
    "published": "Publicados",
    "draft": "Esboço, projeto",
    "save_changes": "Salvar alterações",
    "source": "Fonte",
    "medium": "Médio",
    "url": "URL",
    "revenue": "receita",
    "performance": "atuação",
    "term": "Prazo",
    "content": "Contente",
    "session": "Sessão",
    "product": "produtos",
    "add": "Adicionar",
    "checkout": "Confira",
    "payment": "Pagamento",
    "more_options": "Mais opções",
    "full_name": "Nome completo",
    "tel": "Telefone",
    "about_me": "Sobre mim",
    "request_checking": "Solicitar verificação",
    "passport": "Passaporte",
    "birthday": "Aniversário",
    "country": "País",
    "city": "Cidade",
    "gender": "Gênero",
    "offer": "Oferecer",
    "website": "Local na rede Internet",
    "apply_for_all_products": "∞ Aplicar para todos os produtos",
    "fix_commission": "Comissão fixa",
    "percent_commission": "Comissão percentual",
    "fixed_discount": "Desconto fixo",
    "discount_percentage": "Porcentagem de desconto",
    "discount_limit": "Limite de desconto",
    "no_code": "Nenhum código",
    "max_count": "Contagem máxima",
    "count_unit": "Itens",
    "used": "Usado",
    "daily": "Diário",
    "monthly": "Por mês",
    "yearly": "Anual",
    "state": "Status",
    "disable": "Desativar",
    "enable": "Habilitar",
    "activation_code": "Código de ativação",
    "quantity": "Quantidade",
    "no_club": "Nenhum clube",
    "per_order": "Por pedido",
    "count": "Contar",
    "seconds": "Segundos",
    "auto": "Auto",
    "title": "Título",
    "message": "Mensagem",
    "width": "Largura",
    "length": "Comprimento",
    "height": "Altura",
    "label": "Rótulo",
    "click": "Clique",
    "bank": "Banco",
    "default": "Predefinição",
    "role": "Função",
    "user": "Do utilizador",
    "users": "Comercial",
    "code": "Código",
    "total_payment": "Pagamento total",
    "balance": "Equilíbrio",
    "chance": "Chance",
    "free_for_new_users": "Gratuito para novos usuários",
    "prize_amount": "Valor do prêmio",
    "win": "Vencer",
    "gift_card": "Cartão Presente",
    "discount": "Desconto",
    "config": "Configuração",
    "prize": "Prêmio",
    "Prizes": "Prêmios",
    "result": "Resultado",
    "price": "preço",
    "lottery": "Loteria",
    "coupon": "Cupom",
    "customer_club": "Clube do Cliente",
    "shipping": "Envio",
    "sum": "Soma",
    "not_paid": "Não pago",
    "category": "Categoria",
    "done": "Feito",
    "email_from": "A partir de",
    "subject": "Sujeito",
    "schedule": "Cronograma",
    "files_list": "Lista de arquivos",
    "file_max_size": "Tamanho máximo do arquivo",
    "value": "Valor",
    "help": "Ajuda",
    "shipping_tax": "Taxa de envio",
    "net_price": "Preço líquido",
    "tax": "Imposto",
    "tax_included": "Incluído no preço",
    "limit": "Limite",
    "min_purchase": "Compra mínima",
    "eligible_for": "Elegíveis para",
    "only_for_first_buy": "Somente para primeira compra",
    "one_time_use": "Pode usar uma vez",
    "period_of_qualify": "Limite de uso do período",
    "no_constraint": "Sem limite",
    "timespan": "Período de tempo",
    "days": "Dias)",
    "weight": "Peso",
    "distance": "Distância",
    "last_status": "Último status",
    "issued_at": "Emitido em",
    "order": "Pedido",
    "order_detail": "Detalhes do pedido",
    "percent": "Por cento",
    "applied_count": "Contagem aplicada",
    "campaign": "Campanha",
    "os": "Sistema operacional",
    "browser": "Navegador",
    "device": "Dispositivo",
    "device_ip": "Endereço IP do dispositivo",
    "location": "Localização",
    "user_agent": "Agente de usuário",
    "affiliate": "Afiliado",
    "timeline": "Linha do tempo",
    "add_note": "Adicionar nota",
    "record": "Registro",
    "unlimited": "Ilimitado",
    "show_coupons": "Mostrar cupons",
    "hide_coupons": "Ocultar cupons",
    "service_area": "Área de serviço",
    "apps": "Aplicativos",
    "plugins": "Plug-ins",
    "bots": "Bots",
    "categories": "Categorias",
    "products": "Produtos",
    "business": "O negócio",
    "personal": "Pessoal",
    "size": "Tamanho",
    "holiday": "Feriado",
    "sod": "Pagamento na entrega",
    "cod": "Dinheiro na entrega",
    "free_shipping": "Envio Grátis",
    "hours": "Horas",
    "send_date": "Data de envio",
    "deliver_date": "Data de entrega",
    "return_date": "Data de retorno",
    "pending": "Pendente",
    "delivered": "Entregue",
    "returned": "Devolvida",
    "canceled": "Cancelado",
    "shipping_cost": "Frete",
    "action": "Açao",
    "cancel_date": "Cancelar data",
    "deliver_in_process": "O pedido é enviado..",
    "kind": "Tipo",
    "detail": "Detalhes",
    "map": "Mapa",
    "actions": "Ações",
    "navigation": "Navegação",
    "navigation_app": "Inscrição",
    "payment_date": "Data de pagamento",
    "duration": "Duração",
    "bill": "Projeto de lei",
    "delivery_persons": "Correios",
    "delivery_services": "Serviço de entrega",
    "live_view": "Visualização ao vivo",
    "cart": "Carrinho",
    "priority": "Prioridade",
    "sufficient_credit": "Crédito suficiente",
    "max_package_size": "Tamanho máximo do pacote",
    "delay": "Atraso",
    "credit": "Crédito",
    "livemode": "Ao vivo",
    "paused": "Pausado",
    "debug": "Depurar",
    "token": "Símbolo",
    "status": "Status",
    "courier": "Correio",
    "track": "Acompanhar",
    "track_order": "Acompanhamento de pedidos",
    "cost": "Custo",
    "receipt": "Recibo",
    "origin": "Origem",
    "destination": "Destino",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "Estoque insuficiente!",
    "sub_total": "Subtotal",
    "customer": "Cliente",
    "delivery": "Entrega",
    "online_orders": "Pedidos on-line",
    "pos_orders": "Pedidos de PDV",
    "chips": "Salgadinhos",
    "subscribed": "Subscrito",
    "unsubscribed": "Cancelado",
    "last_login": "Último Login",
    "join_at": "Data de inscrição",
    "club": "Clube",
    "buyer": "Comprador",
    "seller": "Vendedor",
    "or": "Ou",
    "type": "Tipo",
    "condition": "Doença",
    "brand": "Marca",
    "attempt": "Tentar",
    "error": "Erro",
    "success": "Sucesso",
    "fail": "Falhou",
    "inventory": "Inventário",
    "link": "Link",
    "visits": "Visitas",
    "transactions": "Transações",
    "vat": "VAT",
    "pos_vat": "IVA POS",
    "sort_by": "Ordenar por..",
    "from": "A partir de",
    "from_lead_time": "Nas próximas {hours} horas",
    "no_credit_card_info": "Sem informações do cartão!",
    "active": "Ativo",
    "not_active": "Não ativado!",
    "referrals": "Referências",
    "dashboard": "Painel",
    "more": "Mais",
    "inactive": "inativo",
    "developer": "Desenvolvedor",
    "setting": "Contexto",
    "membership_conditions": "Condições de associação",
    "customers": "Clientes",
    "created_at": "Data de criação",
    "updated_at": "Última atualização",
    "register_at": "Data de registo",
    "old": "Velho",
    "new": "Novo",
    "start": "Começar",
    "end": "Fim",
    "pos": "POS",
    "out_of_stock": "Fora de estoque",
    "fake": "Falso",
    "low_inventory_warning": "Atenção, Estoque baixo!",
    "webhook": "Webhook",
    "notification": "Notificação",
    "sms": "SMS",
    "online_payment_link": "Link de pagamento on-line",
    "waiting_load_data": "Aguardando para carregar os dados..",
    "views": "Visualizações",
    "sales": "Vendas",
    "total_views": "Total de visualizações",
    "total_sales": "Vendas totais",
    "from_previous_n_days": "Dos últimos {days} dias",
    "drop_shipping": "Dropshipping",
    "commission": "Comissão",
    "shipping_area": "Área de despacho",
    "main_seller": "Vendedor principal",
    "domain": "Domínio",
    "contact": "Informações de contato",
    "wallet": "Carteira",
    "reseller": "Revendedor",
    "tracking_code": "Código de acompanhamento",
    "tracking_url": "URL de rastreamento",
    "fulfillments": "Cumprimentos",
    "reject": "Rejeitar",
    "reserved": "Reservado",
    "score": "Pontuação",
    "customer_price": "Preço do cliente",
    "options": "Opções",
    "show_details": "Mostrar detalhes",
    "no_data": "Sem dados..",
    "waiting": "Esperando...",
    "waiting_connecting_payment": "Aguardando o serviço de pagamento...",
    "creating_secure_payment": "Criando pagamento seguro.",
    "officer": "Policial",
    "ticket": "Bilhete",
    "ticket_url": "URL do bilhete",
    "closed_at": "Fechado em",
    "close_ticket": "Fechar ticket",
    "reopen_ticket": "Reabrir ticket",
    "require": "Exigir*",
    "search": "Procurar...",
    "language": "Linguagem",
    "tasks": "Tarefas",
    "permissions": "Permissões",
    "finish_date": "Data final",
    "complete_date": "Data de conclusão",
    "settle_date": "Data de liquidação",
    "cost_span": "Faixa de preço",
    "industry": "Indústria",
    "rating": "Classificações",
    "rates": "Avaliação",
    "seen_at": "Visto em",
    "completed": "Concluído",
    "you": "Vocês",
    "shop": "Comprar",
    "store": "armazenar",
    "granted": "Garantido",
    "deny": "Negar",
    "request": "Solicitação",
    "expert": "Especialista",
    "response": "Resposta",
    "requests": "solicitações de",
    "experts": "Especialistas",
    "responses": "Respostas",
    "negotiations": "Negociações",
    "all_chats": "Todos os bate-papos",
    "chats": "Bate-papo",
    "tags": "Tag",
    "description": "Descrição",
    "rates_count": "Número de avaliações",
    "rate": "Avaliação",
    "comment": "Comente",
    "chat": "Bate-papo",
    "install": "Instalar",
    "edited": "Editado",
    "undo": "Desfazer",
    "redo": "Refazer",
    "male": "Macho",
    "female": "Fêmea",
    "calculator": "Calculadora",
    "catalog": "Catálogo",
    "max_height": "Altura máxima",
    "images_compare": "Comparação de imagens",
    "canvas": "Tela",
    "table_of_contents": "Índice",
    "comments": "Comentários",
    "badge_codes": "Código dos emblemas",
    "need_more": "Preciso de mais?",
    "invite_glow_caption": "Receba 14,9 $ por cada amigo!",
    "register_free": "Registo 100% Gratuito",
    "gift": "Presente",
    "google": "Google",
    "facebook": "Facebook",
    "instagram": "Instagram",
    "instashop": "Instashop",
    "show": "exposição",
    "hide": "Esconder",
    "waiting_review": "Aguardando revisão",
    "not_selected": "Não selecionado",
    "time": "Tempo",
    "final_price": "Preço final",
    "starting_price": "Preço inicial",
    "day": "Dia",
    "paid": "Pago",
    "service_bill": "Pagamento da fatura",
    "avocado": "Abacate",
    "delivery_price": "Frete",
    "select_address": "Selecionar endereço",
    "image": "Imagem",
    "view": "Visualizar",
    "sell": "Oferta",
    "hyper": "Hiper",
    "cart_list": "Carrinho",
    "barcode_scanner": "Leitor de códigos de barra",
    "scan_qr_code": "Digitalize o código QR",
    "new_carts": "Novos carrinhos",
    "pays": "Pagamentos",
    "annually": "Anualmente",
    "sells": "Vendas",
    "articles": "Artigos",
    "jobs": "Empregos",
    "job": "Trabalho",
    "blog": "Blogue",
    "deleted_at": "Excluído em",
    "capacity": "Capacidade",
    "download_at": "Data do último download",
    "downloads": "Transferências",
    "usage": "Uso",
    "select_upload_file": "Selecione ou solte o arquivo",
    "download_link": "Link para Download",
    "uploading": "Enviando..",
    "files": "arquivos",
    "star": "Estrela",
    "speed": "Velocidade",
    "feedback": "Comentários",
    "new_messages": "Novas mensagens",
    "file": "Arquivo",
    "attachment": "Acessório",
    "gallery": "Galeria",
    "sync": "Sincronizar",
    "diff_time": "Diferença de tempo",
    "network": "Rede",
    "account": "Conta",
    "configuration": "Configuração",
    "blockchain": "Blockchain",
    "blog_link": "Link do blog",
    "community": "Comunidade",
    "critical_zone": "Zona crítica",
    "statistics": "Estatisticas",
    "access": "Acesso",
    "seo": "SEO",
    "followers": "Seguidores",
    "followings": "Seguidores",
    "private": "Visualizar",
    "soon": "Em breve",
    "features": "Recursos",
    "bot": "Robô",
    "sample": "Amostra",
    "how_it_work": "Como funciona?",
    "page": "Página",
    "congratulations": "Parabéns",
    "recommend": "Recomendar",
    "recommended": "Recomendado",
    "recoms": "Recomendações",
    "likes": "Gostos",
    "clicks": "Cliques",
    "platform": "Plataforma",
    "cms": "CMS",
    "cash": "Dinheiro",
    "dir_payment": "transferência bancária",
    "auto_complete": "Autocompletar",
    "compare": "Comparar",
    "infinite": "Infinito",
    "tips": "Pontas",
    "technical": "Técnico",
    "finance": "Finança",
    "your_phone_input": "Insira um número de telefone",
    "income": "Renda",
    "change": "Mudar",
    "new_users": "Novos usuários",
    "success_orders": "Pedidos bem-sucedidos",
    "direct": "Direto",
    "last_activity": "Ultima atividade",
    "landing": "Pousar",
    "now": "Agora",
    "accept_agreement": "Li e aceito as condições.",
    "report": "Relatório",
    "tablet": "Tábua",
    "pc": "PC",
    "acquisition_channel": "Canal de aquisição",
    "to": "Para",
    "info": "Informações",
    "general": "Em geral",
    "upload": "Carregar",
    "general_config": "Configuração geral",
    "limits_config": "Limitações",
    "design_config": "Design e estilo",
    "duration_config": "Limite de duração",
    "constraints_config": "Limites de qualificação",
    "clubs_config": "Disponível em Clubes",
    "additional_config": "Configurações adicionais",
    "import": "Importar",
    "ribbon": "Fita",
    "countries": "Países",
    "edit": "Editar",
    "delete": "Excluir",
    "analytics": "Análise",
    "rules": "Regras",
    "unset": "Não configurado",
    "carts": "Carrinhos",
    "optional": "Opcional",
    "design": "Projeto",
    "filter": "Filtro",
    "send": "Mandar",
    "approved": "Aprovado",
    "unit": "Unidade",
    "profile": "Perfil",
    "shipping_rates": "Taxas de envio",
    "package": "Pacote",
    "overview": "Visão geral",
    "live": "Ao vivo",
    "never": "Nunca",
    "always": "Sempre",
    "mandatory": "Obrigatoriedade",
    "expire_at": "Data de validade",
    "position": "Posição",
    "channel": "Canal",
    "age": "Idade",
    "charge": "Carregar",
    "giftcard": "Cartão Presente",
    "acquisition": "Aquisição",
    "conversion": "Conversão",
    "total_payments": "Total de pagamentos",
    "community_ask": "Pergunte na comunidade",
    "children": "Crianças",
    "export": "Exportar",
    "list": "Lista",
    "hierarchy": "Hierarquia",
    "images": "Imagens",
    "demo": "Demonstração",
    "author": "Autor",
    "designer": "Projetista",
    "max": "Máximo",
    "accepted": "Aceitaram",
    "reply": "Responder",
    "reviewed": "Revisado",
    "restored": "Restaurado",
    "merchant": "Comerciante",
    "per_product": "Por produto",
    "journey": "Jornada",
    "after": "Depois",
    "waiting_for_payment": "Por favor, complete o pagamento...",
    "hour": "Hora",
    "minute": "Minuto",
    "premium": "Prêmio",
    "light": "Leve",
    "dark": "Escuro",
    "guest": "Convidado",
    "shops": "Lojas",
    "vendor": "Fornecedor",
    "vendors": "Fornecedores",
    "marketplace": "Mercado",
    "verify_date": "Verificar data",
    "note": "Observação",
    "panel": "Painel",
    "removed": "Removido",
    "segments": "Segmentos",
    "personal_info": "Informação pessoal",
    "preferences": "Preferências",
    "spec": "Especificação",
    "reviews": "Avaliações",
    "constraints": "Restrições",
    "flexible": "Flexível",
    "usage_limit": "Limite de uso",
    "temporary": "Temporário",
    "original": "Original",
    "saved": "Salvou!",
    "sort": "Ordenar",
    "documents": "Documentos",
    "document": "Documento",
    "please_wait": "Por favor, espere...",
    "pickup": "Escolher",
    "customize": "customizar",
    "difficulty": "Dificuldade",
    "banned": "Banido",
    "company": "Companhia",
    "tax_shipping": "Taxa de envio",
    "warranty": "garantia",
    "return_policy": "Política de devolução",
    "guide": "Guia",
    "translate": "Traduzir",
    "public": "Público",
    "deleted": "Excluído",
    "variant": "Variante",
    "secure": "Seguro",
    "admin": "Administrador",
    "tax_included_abstract": "incl.",
    "payment_not_settled": "Pagamento não quitado!",
    "orders_list": "lista de pedidos",
    "subscription_plan": "plano de assinatura",
    "contents": "Conteúdo",
    "pricings": "preços",
    "static_page": "página estática",
    "shop_button": "Botão Comprar",
    "embed": "Embutir",
    "over": "Sobre",
    "tax_vary_by_location": "variar. localização",
    "product_type": "Tipo de Produto",
    "tax_id": "CPF",
    "business_name": "Nome da empresa",
    "invoice": "Fatura",
    "included_in_the_product": "Incluído no produto",
    "included_in_the_product_description": "O produto inclui os seguintes componentes",
    "cross_sell": "Venda cruzada",
    "discount_off": "OFF",
    "extra_discount": "desconto extra",
    "template": "Modelo",
    "in_cart": "No carrinho",
    "pros_and_cons": "Prós e contras",
    "related_products": "produtos relacionados",
    "related_categories": "Categorias relacionadas",
    "badges": "Distintivos",
    "explore": "Explorar",
    "updated": "Atualizada",
    "bank_name": "Nome do banco",
    "bank_account_number": "Número da conta de banco",
    "bank_routing_number": "Número de roteamento bancário",
    "bank_branch_address": "Endereço da agência bancária",
    "bank_account_name": "Nome completo do proprietário da conta",
    "valuation": "Avaliação",
    "cluster": "Conjunto",
    "clusters": "Aglomerados",
    "subscriptions": "Assinaturas",
    "spam": "Spam",
    "video": "Vídeo"
  },
  "dialogs": {
    "delete": {
      "title": "Excluir",
      "message": "Tem certeza de que deseja excluir este item?",
      "action": "Sim, Excluir agora"
    }
  },
  "actions": {
    "add_to_cart": "Adicionar ao carrinho",
    "cancel": "Cancelar",
    "update": "Atualizar",
    "add": "Adicionar",
    "delete": "Excluir",
    "new": "Novo",
    "save_continue": "Salvar e continuar",
    "save": "Salve ",
    "save_changes": "Salvar alterações",
    "change": "Mudar",
    "continue": "Continuar",
    "close": "Perto",
    "finish": "Terminar",
    "poll": "Enquete",
    "view": "Visualizar",
    "edit": "Editar",
    "next": "Próximo",
    "previous": "Anterior",
    "create": "Criar",
    "set": "definir",
    "find": "Encontrar",
    "accept": "Aceitar",
    "reject": "Rejeitar",
    "back": "Costas",
    "pay": "Pagar",
    "pay_now": "Pague agora",
    "print": "Impressão",
    "return": "Retornar",
    "publish": "Publicar",
    "confirm": "confirme",
    "copy": "cópia de",
    "submit": "Enviar",
    "send": "Mandar",
    "yes": "Sim",
    "no": "não",
    "meh": "Hum",
    "clear": "Claro",
    "dismiss": "Dispensar",
    "search": "Procurar",
    "deselect_all": "Desmarcar todos",
    "select_all": "Selecionar tudo",
    "refresh": "Atualizar",
    "verify": "Verificar",
    "play": "Toque",
    "open": "Aberto",
    "calculate": "Calcular",
    "quick_buy": "Compra rápida",
    "click_here": "Clique aqui",
    "schedule": "Cronograma",
    "send_now": "Envie agora",
    "download": "Download",
    "reset_default": "Restaurar ao padrão",
    "reset": "Redefinir",
    "check": "Verificar",
    "cod_payment": "Dinheiro na entrega",
    "dir_payment": "Transferência de dinheiro",
    "online_payment": "Pagamento online",
    "checkout": "Confira",
    "show_all": "Mostre tudo",
    "login": "Conecte-se",
    "logout": "Sair",
    "more": "Mais..",
    "collapse": "Colapso",
    "apply_change": "Aplicar mudanças",
    "apply": "Aplicar",
    "add_giftcard": "Adicionar vale-presente",
    "charge": "Carregar",
    "send_invites": "Enviar convites",
    "past": "Passado",
    "restore": "Restaurar",
    "cut": "Cortar",
    "get_sms_code": "Obter código de autenticação",
    "register_no_mail": "Continuar sem e-mail",
    "no_mail_register_message": "Não possui um endereço de e-mail ou esqueceu sua senha?",
    "reset_by_mail": "Recuperação de senha por e-mail",
    "reset_by_sms": "Recuperação de senha por SMS",
    "cash_payment": "Pagamento em dinheiro",
    "show_chart": "Mostrar gráfico",
    "open_app": "Abrir aplicativo",
    "login_now": "Conecte-se agora",
    "watch_video": "Assistir vídeo",
    "check_now": "Verifique agora",
    "remove_image": "Remover imagem",
    "view_website": "Link aberto",
    "explore": "Explorar {name}",
    "go": "Vai",
    "read_more": "Consulte Mais informação",
    "start_now": "Comece agora — é grátis",
    "view_live": "Ver ao vivo",
    "resend_code": "Reenviar código",
    "invite": "Convidar",
    "add_more": "Adicione mais",
    "install_now": "Instale agora",
    "uninstall": "Desinstalar",
    "show_preview": "Mostrar visualização",
    "hide_preview": "Ocultar visualização",
    "download_now": "Baixe Agora",
    "auto_fill": "Preenchimento automático",
    "track": "Acompanhar",
    "change_state": "Alterar status",
    "done": "Feito",
    "reply": "Responder",
    "watch_now": "Assista agora",
    "unlock": "Desbloquear",
    "lock": "Trancar",
    "create_clone": "Criar clone",
    "regenerate": "Regenerado",
    "add_message": "Adicionar mensagem",
    "continue_chat": "Continuar bate-papo",
    "add_new_message": "Adicionar nova mensagem",
    "change_setting": "Alterar configuração",
    "delete_all": "Excluir tudo",
    "transfer_fund": "Transferir Fundo",
    "reverse_fund": "fundo reverso",
    "settlement": "Povoado",
    "refund": "Reembolso",
    "partial_refund": "Reembolso parcial",
    "change_payment_method": "Mudar o metodo de pagamento",
    "buy": "Comprar",
    "view_all": "Ver tudo",
    "view_now": "Veja Agora",
    "paste": "Colar"
  },
  "instance_message_title": "Enviar mensagem instantânea",
  "instance_message": "Olá {name}, meu nome é {author} de {company}.",
  "errors": {
    "419": "Você está inativo há muito tempo, por favor <b>⟳ ATUALIZE A PÁGINA</b> por motivos de segurança.",
    "gateway_blockchain_sync_error": "O sistema não sincroniza com o blockchain. Não será possível criar uma nova transação até que as sincronizações de nossos servidores sejam concluídas. Estamos resolvendo o problema.",
    "gateway_network_error": "O serviço de gateway de pagamento encontrou um problema de comunicação."
  },
  "receiver_info": {
    "map": {
      "title": "Endereço para envio",
      "confirm": "Defina localização",
      "address_type": "Destino",
      "receptor_type": "Receptor"
    },
    "receiver_address": "Selecione o endereço de entrega",
    "address": "Morada",
    "postcode": "Código postal",
    "enter_value": "Preencha aqui",
    "address_note": "Observação",
    "tel": "Número de contato",
    "service_address": "Selecione seu endereço"
  },
  "weight": {
    "g": "g",
    "oz": "oz",
    "lb": "Libra",
    "kg": "kg"
  },
  "mass_unit_name": {
    "g": "grama",
    "oz": "Onça",
    "lb": "Libra",
    "kg": "quilograma"
  },
  "length": {
    "cm": "cm",
    "in": "dentro",
    "ft": "pés",
    "mm": "milímetros",
    "m": "m",
    "yd": "jarda"
  },
  "size_unit_name": {
    "cm": "Centímetro",
    "in": "Polegada",
    "ft": "Pé",
    "mm": "milímetro",
    "m": "metro",
    "yd": "Quintal"
  },
  "distance": {
    "m": "metro",
    "km": "km"
  },
  "time": {
    "days": "Dias",
    "hours": "Horas",
    "minutes": "Minutos",
    "seconds": "Segundos"
  },
  "units": [
    "Unidade",
    "item",
    "cada",
    "definir",
    "pedaço",
    "quilograma",
    "grama",
    "miligrama",
    "metro",
    "milímetro",
    "metro quadrado",
    "pés quadrados",
    "metro cúbico",
    "litro",
    "mililitro",
    "pés",
    "galões",
    "polegadas",
    "onças",
    "libras",
    "quartos",
    "jardas",
    "sala",
    "segundos",
    "minutos",
    "horas",
    "dias",
    "semanas",
    "meses",
    "anos"
  ],
  "region_types": {
    "State": "Estado",
    "Territory": "Território",
    "Province": "Província"
  },
  "transaction_status": {
    "RequireAction": "Ação requerida",
    "Processing": "Em processamento",
    "Canceled": "Cancelado",
    "Succeeded": "Sucesso"
  },
  "placeholders": {
    "name": "Jon Cox",
    "email": "seu-mail@mail.com",
    "phone": "+1 000 0000",
    "language": "Selecione o idioma..",
    "friend_email": "E-mail do seu amigo...",
    "friend_name": "Optar. O nome do seu amigo",
    "select_date": "Selecione uma data..."
  },
  "notification": {
    "confirm": "confirme",
    "confirm_message": "Alterações salvas com sucesso.",
    "error": "Erro",
    "message": "Mensagem",
    "caution": "Cuidado",
    "warning": "Aviso",
    "award": "Parabéns",
    "error_message": "Infelizmente, ocorreu um erro.",
    "congratulation": "Parabéns",
    "coming_soon": "Em breve",
    "on_fetching_data": "Recebendo informações..",
    "new_pwa_version": "Nova versão já disponível. Deseja atualizar o aplicativo?",
    "over_license_limit": "Acima do limite de licença",
    "update_license": "Atualize sua licença",
    "required": "Requerido",
    "invalid_email": "E-mail inválido",
    "invalid_domain": "Domínio inválido",
    "invalid_min_length": "O comprimento mínimo deve ser {length}",
    "invalid_min_array_length": "Pelo menos selecione {length} itens",
    "invalid_max_chars": "Máximo de {maxCount} caracteres",
    "invalid_url": "URL inválida",
    "country_invalid": "Selecione o país de destino!",
    "postal_code_invalid": "Defina um código postal válido!"
  },
  "colors": {
    "#D32F2F": "Vermelho",
    "#C2185B": "Rosa",
    "#7B1FA2": "Roxa",
    "#512DA8": "Roxo escuro",
    "#303F9F": "Azul índigo",
    "#1976D2": "Azul",
    "#0288D1": "Azul claro",
    "#0097A7": "Azul turquesa",
    "#00796B": "Ganso Verde",
    "#388E3C": "Verde",
    "#689F38": "Luz verde",
    "#AFB42B": "Limusine",
    "#FBC02D": "Amarelo",
    "#FFA000": "Âmbar",
    "#F57C00": "Laranja",
    "#E64A19": "Laranja Brilhante",
    "#5D4037": "Marrom",
    "#616161": "Cinza",
    "#455A64": "Cinza azul",
    "#FFD700": "Dourado",
    "#C0C0C0": "Prata",
    "#b76e79": "Rosa Dourada",
    "#383838": "Preto fosco",
    "#FFFFFF": "Branco",
    "#FFF": "Branco",
    "#000000": "Preto",
    "#000": "Preto",
    "#7d263a": "marrom",
    "#FD9F17": "Ouro",
    "#229DBF": "Água",
    "#6DC9E2": "Aqua Triblend",
    "#413B2D": "Exército",
    "#474747": "Asfalto",
    "#E6195C": "baga",
    "#B2184C": "Berry Triblend",
    "#FC7F5F": "Laranja queimado",
    "#80011F": "Cardeal",
    "#382829": "Chocolate",
    "#F06336": "Coral",
    "#FAE7C9": "Creme",
    "#6B2257": "Groselha",
    "#222127": "Cinza escuro",
    "#0D5A74": "Cerceta Profunda",
    "#00582F": "Evergreen",
    "#214C30": "Floresta",
    "#DC2867": "Fúcsia",
    "#38561F": "Kelly",
    "#5C884D": "Folha",
    "#558450": "Água clara",
    "#96B5C9": "Azul claro",
    "#DCAFCE": "Lilás",
    "#D3E1A4": "Lima",
    "#9DE7C2": "hortelã",
    "#F6EAD2": "Natural",
    "#1A1F35": "Marinha",
    "#404624": "Oliva",
    "#271020": "Ameixa",
    "#A8355C": "Framboesa",
    "#D6BEA6": "Creme Suave",
    "#BEA994": "bronzeado",
    "#0DB2AE": "Cerceta",
    "#A86EA9": "Tolet",
    "#36454F": "Carvão",
    "#b3b0ab": "cinza carbono",
    "#463e3d": "Carvão Urze",
    "#282d3c": "Blazer da Marinha"
  },
  "address_info": {
    "name": "Nome",
    "tel": "Telefone",
    "email": "E-mail",
    "country": "País",
    "city": "Cidade",
    "state": "Estado",
    "address": "Morada",
    "building_number": "Número do prédio",
    "building_unit": "Unidade",
    "postcode": "Código postal",
    "note": "Observação",
    "county": "Condado"
  },
  "product_types": {
    "physical": "Físico",
    "physical_description": "Produtos físicos como: telefones celulares, livros, componentes eletrônicos.",
    "virtual": "Virtual",
    "virtual_description": "Produtos compatíveis com a Internet, como: cartão de recarga, reserva de hotel, recarga de jogos.",
    "file": "Arquivo",
    "file_description": "Todos os arquivos permitidos, como vídeo do curso online, documentos para download.",
    "service": "Serviço",
    "service_description": "Serviços como: reparação, transporte, ensino.",
    "subscription": "Inscrição",
    "subscription_description": "Assinaturas e faturação de produtos, serviços ou conteúdos."
  },
  "license": {
    "free": "Livre",
    "startup": "Comece",
    "company": "Companhia",
    "enterprise": "Empreendimento"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "Para homem",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW",
    "GHS": "GHS",
    "ZWD": "ZWD",
    "IQD": "IQD",
    "SYP": "SYP"
  },
  "variants": {
    "color": "Cor",
    "volume": "Tamanho",
    "count_in_pack": "Contar em pacote",
    "weight": "Peso",
    "type": "Material",
    "style": "Estilo"
  },
  "delivery_state": {
    "check_queue": "Aguardando revisão",
    "order_confirm": "Confirmação do pedido",
    "preparing_order": "Preparando",
    "sent_order": "Em entrega",
    "to_customer": "Entregue"
  },
  "status": {
    "unpaid": "Não pago",
    "paid": "Pago",
    "canceled": "Cancelado",
    "completed": "Assentou",
    "reserved": "Reservado",
    "COD": "COD",
    "sold": "Vendido",
    "open": "Aberto",
    "cancel": "Cancelado",
    "active": "Ativo",
    "inactive": "inativo",
    "debug": "Depurar",
    "live": "Ao vivo",
    "test": "Teste",
    "connected": "Conectado",
    "disconnected": "Desconectado",
    "accept": "Aceitar",
    "reject": "Rejeitar",
    "pending": "Pendente",
    "rejected": "Rejeitado",
    "accepted": "Aceitaram"
  },
  "dimensions": {
    "cm": "cm",
    "km": "km",
    "kg": "kg"
  },
  "transportation_type": {
    "motorbike": "Moto",
    "motorbike_description": "Peso médio dentro de alguns quilômetros.",
    "cargo_small": "Carga pequena",
    "cargo_small_description": "Carga leve de vários quilômetros.",
    "cargo": "Carga",
    "cargo_description": "Peso médio dentro de alguns quilômetros.",
    "truck": "Caminhão",
    "truck_description": "Carga a granel ou pesada dentro do país.",
    "fast_post": "Postagem rápida",
    "fast_post_description": "Postagem rápida via correios.",
    "post": "Postagem normal",
    "post_description": "Correio normal através dos correios.",
    "airplane": "Correio aéreo",
    "airplane_description": "Cargas leves e médias nacionais e estrangeiras.",
    "bicycle": "Limpar envio",
    "bicycle_description": "Carga leve, a algumas centenas de metros de veículos não motorizados.",
    "global": "Transporte global",
    "global_description": "Envio para o exterior por via aérea, marítima ou terrestre.",
    "pickup": "Escolher",
    "pickup_description": "Os clientes retiram os itens em sua loja física ou depósito."
  },
  "article": {
    "login_to_see_error": "Faça login para acessar o artigo",
    "create_new_action": "Criar novo conteúdo",
    "menu_title": "Cardápio",
    "menu": {
      "edit": "Modo de edição",
      "view_mode": "Modo de visualização",
      "delete": "Excluir artigo"
    },
    "schedule_action": "Deseja agendar a publicação?",
    "schedule_title": "Agendar publicação automática",
    "edit_mode": "Editar",
    "public_view_mode": "Visualização pública",
    "publish_at": "Publicar em",
    "published": "Publicados",
    "draft": "Esboço, projeto",
    "saving": "Salvando",
    "save_and_publish_action": "Salvar e publicar",
    "save_draft_action": "Salvar rascunho",
    "private": "Privado",
    "public": "Público",
    "category_input": "Categoria",
    "category_input_message": "Selecione a categoria do artigo",
    "parent_input": "Categoria Parental",
    "parent_input_message": "Selecione o conteúdo pai",
    "schedule_input": "Cronograma",
    "schedule_input_placeholder": "Se você quiser que a história seja publicada em um momento específico.",
    "schedule_view_action": "Ver programação de publicação",
    "author_title": "Escrito por",
    "read_time": "Tempo de estudo",
    "read_time_unit": "Minutos",
    "claps_action": "Palmas",
    "claps": "Palmas",
    "likes": "Como",
    "about_author": "Sobre o autor",
    "updated_at": "Atualizada",
    "wrote_at": "Escrito em",
    "now": "Agora",
    "follow_action": "Seguir",
    "followed": "Seguido",
    "report_and_delete_action": "Denunciar e excluir este artigo",
    "report_action": "Denunciar abuso",
    "you_reported_this_article": "Este artigo já tem uma denúncia de abuso.",
    "add_to_publication_action": "Adicionar à publicação",
    "author_socials": "Autor nas redes sociais",
    "share": "Compartilhar",
    "report_dialog": {
      "report_and_delete_title": "Denunciar abuso e remover conteúdo",
      "report_title": "Denunciar este conteúdo como abusivo",
      "message": "Qual é o motivo para enviar este conteúdo? Escolha uma das seguintes opções.",
      "accept_and_delete_action": "Confirmar e excluir conteúdo"
    },
    "schedule_dialog": {
      "title": "Cronograma de lançamento de conteúdo",
      "publish_at": "Publicar em",
      "last_edit": "Última edição",
      "view_action": "Ver artigo"
    },
    "notifications": {
      "update_success_title": "Enviar informações",
      "update_success": "Artigo atualizado com sucesso.",
      "update_error": "As informações inseridas não são válidas.",
      "delete_error": "Você não pode excluir este artigo!",
      "report_and_delete_success_title": "Denunciar e excluir",
      "report_and_delete_success_message": "O artigo foi excluído com sucesso.",
      "report_success_title": "Artigo de relatório",
      "report_success_message": "Seu relatório sobre este artigo foi publicado."
    },
    "alert": {
      "delete_article": {
        "title": "Excluir artigo",
        "message": "Tem certeza de que deseja excluir permanentemente este artigo?",
        "action": "Excluir"
      }
    },
    "edit_window": {
      "title": "Selecionar texto e resumo da imagem",
      "digest": "Resumo"
    },
    "editor": {
      "title_placeholder": "Título..",
      "body_placeholder": "Escreva um ótimo conteúdo..",
      "accept_file_types_error": "Este formato de arquivo é inaceitável:",
      "max_file_size_error": "Este arquivo é muito grande:",
      "notifications": {
        "image_uploaded_success": "Imagem salva com sucesso",
        "image_uploaded_failed": "Erro ao carregar a imagem."
      },
      "embed_placeholder": "Digite o código iframe, Facebook, Youtube ou qualquer outro URL e pressione enter.",
      "embed_caption_placeholder": "Insira um título (opcional)",
      "images_caption_placeholder": "Digite um título para esta imagem .."
    }
  },
  "article_report": {
    "inappropriate": "O conteúdo deste artigo é inadequado.",
    "fake": "Isso é falso e enganoso.",
    "spam": "Este item foi spam e copiado.",
    "scam": "Isso pode causar malware, vírus ou travamento do sistema.",
    "hacked": "Este site parece ter sido hackeado.",
    "offensive": "O conteúdo e o vocabulário da linguagem são antiéticos e desrespeitosos.",
    "violent": "Acho que este conteúdo contém pornografia e viola as leis.",
    "harassment": "Acho isso racista.",
    "hate": "Acho que se trata de promover a violência.",
    "infringe": "Isso viola meus direitos."
  },
  "comments": {
    "new_action": "Clique para deixar um comentário..",
    "title": "Comentários",
    "body_placeholder": "Seu comentário ou mensagem",
    "send_action": "Enviar comentário",
    "body_is_empty_error": "O comentário está em branco!",
    "comments": "Comentários",
    "no_comments": "Escreva o primeiro comentário...",
    "load_more_action": "Receba mais comentários..",
    "cant_send_comment": "Você não pode adicionar uma nova postagem.",
    "cant_remove_this_comment": "Você não pode excluir este comentário!",
    "product_buyer": "Comprador",
    "delete_alert": {
      "title": "Excluir comentário",
      "message": "Deseja excluir este comentário?",
      "action": "Excluir"
    },
    "notifications": {
      "delete_success": "Seu comentário foi excluído com sucesso."
    },
    "first_send": "Primeiro post",
    "comment_at": "Em",
    "edit_comment": "Editar comentário",
    "my_comments": "Meus comentários"
  },
  "customer_club": {
    "bronze": "Bronze",
    "silver": "Prata",
    "gold": "Dourado",
    "platinum": "Platina",
    "diamond": "Diamante"
  },
  "application_categories": {
    "tracking": "Verificando o comportamento do usuário",
    "payment": "Pagamento",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "Transporte",
    "automation": "Automação",
    "inventory": "Armazenagem",
    "accounting": "Contabilidade",
    "marketing": "Marketing",
    "advertising": "Anúncio",
    "staff": "Pessoal",
    "incentive": "Incentivos",
    "shop": "Comprar"
  },
  "social_network": {
    "instagram": "Instagram",
    "telegram": "Telegrama",
    "googleplay": "Google Play",
    "appstore": "Loja de aplicativos",
    "twitter": "Twitter",
    "linkedin": "Linkedin",
    "medium": "Médio",
    "selldone": "Vendido",
    "facebook": "Facebook",
    "pinterest": "Pinterest",
    "whatsapp": "Whatsapp",
    "skype": "Skype",
    "facebook_messenger": "Facebook Messenger"
  },
  "form_builder": {
    "add_item_action": "Adicionar novo item",
    "title_input": "Título",
    "name_input": "Nome variável",
    "value_input": "Valores",
    "value_input_message": "Lista de opções do usuário",
    "default": "Valor padrão",
    "types": {
      "simple": "Simples",
      "selective": "Seletivo",
      "switch": "Trocar",
      "file": "Arquivo",
      "number": "Número"
    },
    "placeholder_input": "Espaço reservado",
    "file_type_input": "Tipos de arquivo aceitáveis",
    "file_type_message": "jpeg, png, zip, ..."
  },
  "virtual_order_info_summery": {
    "title": "Nome do Produto",
    "reserved_at": "data de registro",
    "total_price": "Montante total",
    "discount": "Desconto",
    "final_price": "Quantidade final",
    "payment_status": "Status do pagamento",
    "payment_status_waiting": "À espera de pagamento",
    "payment_status_paid": "Pago",
    "buyer": "Comprador"
  },
  "virtual_item_info": {
    "title": "Item virtual",
    "outputs": {
      "title": "Informações de saída",
      "sub_title": "Informações Confidenciais deste Item",
      "message": "Essas informações serão mostradas ao usuário após a compra do produto."
    },
    "inputs": {
      "title": "Informação necessária",
      "sub_title": "Informações do comprador obrigatórias",
      "message": "O comprador deve inserir as informações solicitadas no formulário"
    },
    "notifications": {
      "inputs_set_success": "Formulário de informações cadastrado com sucesso.",
      "confirm_by_admin_success": "Conclusão do pedido confirmada.",
      "confirm_by_buyer_success": "Conclusão do pedido confirmada."
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "Este pedido não pode ser aceito pelo pagamento COD.",
    "payment_returned": "O pagamento pelo cliente é devolvido.",
    "payment_fraud": "O pagamento foi identificado como fraude.",
    "location_out_of_service": "A localização do cliente está fora de serviço.",
    "user_not_responding": "O cliente não atendeu as ligações.",
    "shop_owner_fault": "Ocorreu um erro da equipe da loja no preenchimento das informações.",
    "lack_of_inventory": "Fora de estoque.",
    "legal_restriction": "Não é possível fazer um pedido devido a restrições legais.",
    "pricing_fault": "Erro de preço do vendedor.",
    "system_fault": "Erro do sistema."
  },
  "basket_order_info_summery": {
    "receiver": "Receptor",
    "phone": "Telefone",
    "reserved_date": "Data de compra",
    "total_price": "Montante total",
    "discount": "Desconto",
    "final_price": "Quantidade final",
    "address": "Endereço de entrega",
    "payment_status": "Status do pagamento"
  },
  "basket_status": {
    "open": "Aberto",
    "reserved": "Reservado",
    "paid": "Pago",
    "canceled": "Cancelado",
    "cod": "Pagamento na entrega",
    "receipt_added": "Recibo adicionado",
    "payment_processing": "Processo de pagamento"
  },
  "basket_delivery_state": {
    "rejected": "Rejeitado",
    "reject_reason_not_found": "O motivo é desconhecido.",
    "step_1": "Análise",
    "step_2": "Confirmação",
    "step_3": "Preparação",
    "step_4": "Em entrega",
    "step_5": "Entregue"
  },
  "basket_return_request_view": {
    "title": "Solicitação de devolução",
    "delivery_date": "Data de entrega",
    "return_date": "Data do Pedido",
    "items_count": "Contagem de itens devolvidos",
    "items_count_unit": "Itens)",
    "reason": "Razão",
    "description": "Descrição",
    "status": "Status",
    "download_image": "Baixar imagem",
    "download_film": "Baixar video",
    "download_voice": "Baixar voz",
    "accept_by_admin_action": "Aceitar pedido",
    "reject_by_admin_action": "Rejeitar solicitação",
    "message_for_admin": "De acordo com o acordo que você aceitou usando o Selldone, você deve entrar em contato com o comprador e mantê-lo informado sobre o processo de devolução do seu pedido. Isso deve ser feito se a solicitação for aceita ou rejeitada e o consentimento total do comprador for obtido.",
    "notifications": {
      "update_status_success": "Status da solicitação atualizado."
    }
  },
  "basket_list": {
    "return_count": "Retorno: {count} número",
    "table": {
      "row": "Linha",
      "image": "Imagem",
      "product_name": "produtos",
      "variant": "Variante",
      "warranty": "Garantias",
      "count": "Contar",
      "price": "preço"
    }
  },
  "return_request_list": {
    "count": "Número de referência",
    "return_warranty": "Garantia de devolução de dinheiro",
    "return_warranty_unit": "Dias)",
    "table": {
      "code": "Código de encomenda",
      "product": "produtos",
      "delivery_at": "Data de recebimento",
      "state": "Status",
      "reason": "Razão",
      "return_warranty_period": "Período de garantia"
    }
  },
  "data_toolbar": {
    "search": "Procurar",
    "sort_by": "Ordenar por",
    "count_item": "Mostrar {item} itens"
  },
  "sort": {
    "created_at": "Criar Data",
    "updated_at": "Editar data",
    "title": "Título",
    "description": "Descrição",
    "like": "Popularidade",
    "power": "Palmas",
    "product_type": "Tipo de Produto",
    "discount": "Desconto",
    "rate": "Avaliação",
    "rate_count": "Número de avaliações",
    "category": "Categoria",
    "product": "produtos",
    "body": "Contente",
    "card_type": "Tipo de carta",
    "card_number": "Número do cartão",
    "balance": "Equilíbrio",
    "paid": "Valor gasto",
    "currency": "Moeda",
    "expire_at": "Data de validade",
    "discount_code": "Código de desconto",
    "discount_percent": "Desconto",
    "discount_limit": "Limite de desconto",
    "max_count": "Contagem máxima",
    "used_count": "Usado",
    "start_date": "Data de início",
    "end_date": "Data final",
    "total_discount_amount": "Descontos totais",
    "initial_charge": "Carga inicial",
    "total_count": "Contagem total",
    "amount_paid": "Quantia paga",
    "name": "Nome",
    "published": "Publicados",
    "visits": "Visitas",
    "color": "Cor",
    "landing_page": "Página de destino",
    "enable": "Habilitar",
    "fix_commission": "Comissão fixa",
    "percent_commission": "Comissão percentual",
    "payment_at": "Data de pagamento",
    "issued_at": "Data de emissão",
    "payment": "Pagamento",
    "website": "Local na rede Internet",
    "email": "E-mail",
    "user": "Do utilizador",
    "code": "Código",
    "schedule_at": "Agendar data",
    "sender": "Remetente",
    "in_que": "Na fila",
    "sent": "Enviei",
    "shop": "Comprar",
    "quantity": "Quantidade",
    "amount": "Resultar",
    "jobs": "Contagem de trabalhos",
    "success": "Contagem de sucesso",
    "fail": "Contagem de falhas",
    "distance": "Distância",
    "duration": "Duração",
    "reset_at": "Redefinir data",
    "delivery_person": "Pessoa",
    "delivery_service": "Serviço",
    "date": "Encontro",
    "order": "Pedido",
    "order_id": "Código do pedido",
    "status": "Status",
    "price": "preço",
    "count": "Contar",
    "final_price": "Preço final",
    "charge": "Carregar",
    "mention": "Menção",
    "officer": "Policial",
    "registered": "Registrado",
    "purchased": "Comprado",
    "sex": "Gênero"
  },
  "search_box": {
    "result": "Procurar Resultados",
    "tips": "Pesquisar produtos e categorias",
    "label": "Procurar ...",
    "category": "Categoria"
  },
  "lead_status": {
    "physical_fast_delivery": "Entrega instantânea",
    "physical_under_24h_delivery": "Entregue nas próximas {lead} horas",
    "physical_over_24h_delivery": "Preparando e enviando a partir dos próximos {days} dias",
    "virtual_fast_prepare": "Entrega instantânea",
    "virtual_under_24h": "Será feito nas próximas {lead} horas",
    "virtual_over_24h": "Será feito a partir dos próximos {days} dias"
  },
  "return_request_state": {
    "pending": "Pendente",
    "accepted": "Confirmado",
    "rejected": "Rejeitado"
  },
  "return_order_reason": {
    "physical": {
      "U1": "Produto incompatível",
      "U2": "Nenhum produto no pacote de envio",
      "U3": "Quebra de pacote ou produto",
      "U4": "Adulteração de pacote ou número de série",
      "U5": "Alguns itens do pacote estão faltando",
      "U6": "Produto não é original",
      "U7": "Produto não atende as especificações"
    }
  },
  "image_uploader": {
    "label": "Arraste e solte ou <u>selecione o arquivo</u>",
    "max_size": "Tamanho máximo permitido: {size}"
  },
  "timespan": {
    "Morning": "8h - 12h",
    "Evening": "12h às 18h",
    "Night": "18h-12h",
    "Instant": "Postagem instantânea"
  },
  "week_day": {
    "Saturday": "Sábado",
    "Sunday": "Domingo",
    "Monday": "Segunda-feira",
    "Tuesday": "Terça-feira",
    "Wednesday": "Quarta-feira",
    "Thursday": "Quinta-feira",
    "Friday": "Sexta-feira"
  },
  "payment_form": {
    "title": "Selecione o método de pagamento",
    "gift_cards_input": "Cartões de presente",
    "gift_cards_input_empty": "Nenhum vale-presente encontrado..",
    "more": "Outro",
    "pay_amount_by_gift_cards": "Pagamento com cartão de cobrança",
    "select_payment_method": "Escolha sua forma de pagamento entre as opções a seguir.",
    "payment_amount_remained": "Valor restante do pagamento",
    "payment_amount": "Quantia paga",
    "all_paid_by_gift_cards": "Parabéns, você não precisa pagar por este pedido. Pressione a tecla Pagar com cartão-presente.",
    "pay_by_gift_cards_action": "Pague o pedido com cartão de cobrança",
    "order_free_payment": "Parabéns, seu pedido é grátis!",
    "order_free_payment_action": "Peça grátis agora",
    "qr": {
      "address": "Endereço de pagamento",
      "amount": "Resultar"
    }
  },
  "discount_input": {
    "limit": "{percent}% de desconto até {limit} {currency}",
    "action": "Adicionar código de desconto",
    "code_input": "Código de desconto",
    "notifications": {
      "add_success": "Parabéns, código de desconto válido."
    }
  },
  "gift_card": {
    "inactive": "O cartão está desativado",
    "expire": "Termo",
    "transfer": "Transferir",
    "send_to_friend": "Envie a um amigo"
  },
  "count_down": {
    "days": "Dia",
    "hours": "Hora",
    "minutes": "Minutos",
    "seconds": "Segundos"
  },
  "gift_status": {
    "Unpaid": "Esperando recibo",
    "Paid": "Pago",
    "Rejected": "Rejeitado",
    "Canceled": "Cancelado"
  },
  "gift_program_status": {
    "Airdrop": "Sistema de pagamento",
    "Advertising": "Anúncio",
    "PersonalGift": "Presente Pessoal",
    "ShopGift": "Loja de presentes"
  },
  "currency_selector": {
    "label": "Moeda"
  },
  "need_login": {
    "title": "Conecte-se",
    "login_sms": "Login por SMS",
    "login_google": "Entrar com o Google",
    "login_facebook": "Entrar com o Facebook",
    "login_account": "Login por Selldone",
    "register": "Novo usuário? Registrar agora.",
    "mobile_input": "Digite seu celular",
    "verification_code": "Código de verificação",
    "msg_title": "Oi,",
    "msg_body": "Por favor entre. Leva apenas alguns segundos.",
    "login_apple": "Entrar com a Apple",
    "login_email": "Entrar por e-mail",
    "email_login_step_1": "Forneça um endereço de e-mail válido e enviaremos o código de login para ele. Nenhum registro é necessário.",
    "email_login_step_2": "Tem certeza de que digitou seu endereço de e-mail corretamente? Estaremos enviando o código de login para o e-mail fornecido, portanto, verifique sua precisão.",
    "email_login_step_3": "Enviamos um código para o seu e-mail. Por favor, note que o código irá expirar em 10 minutos."
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "Loja de ouro de 5 anos"
    },
    "GOLDEN_2YEAR": {
      "name": "Loja de ouro de 4 anos"
    },
    "GOLDEN_3YEAR": {
      "name": "Loja de ouro de 3 anos"
    },
    "GOLDEN_4YEAR": {
      "name": "Loja de ouro de 2 anos"
    },
    "GOLDEN_5YEAR": {
      "name": "Loja de ouro de 1 ano"
    },
    "TOKEN_OWNER_1M": {
      "name": "Investidor Dourado"
    },
    "TOKEN_OWNER_10M": {
      "name": "Investidor Diamante"
    },
    "TOKEN_OWNER_100M": {
      "name": "Investidor Rubi"
    },
    "COMMUNITY_LOYAL": {
      "name": "Membro da Comunidade Superior de Redes de Comunicação"
    },
    "GOLD_SUPPLIER": {
      "name": "fornecedor de ouro"
    },
    "GOLD_SELLER": {
      "name": "Negociante de ouro"
    },
    "CONTENT_SUPERMAN": {
      "name": "Melhor produtor de conteúdo"
    },
    "NINJA": {
      "name": "Ninja"
    },
    "STAR": {
      "name": "Estrela"
    },
    "GUARDIAN": {
      "name": "Ótimo atendimento ao cliente"
    },
    "KING": {
      "name": "rei do mercado"
    }
  },
  "cookie": {
    "title": "Este site usa cookies",
    "message": "Este site usa cookies para melhorar a experiência do usuário. Ao usar nosso site, você concorda com todos os cookies de acordo com nossa Política de Cookies.",
    "preferences_action": "Gerenciar preferências",
    "agree_action": "Eu concordo"
  },
  "basket_item_message": {
    "title": "Informações necessárias para este item",
    "save_actions": "Salvar mensagem",
    "notifications": {
      "success": "Seus dados de entrada foram salvos."
    },
    "product_inputs_preview_message": "Essas opções de personalização estão disponíveis para o produto solicitado. Depois que o item for adicionado ao seu carrinho, você poderá fazer ajustes aqui."
  },
  "faq": {
    "faq": "perguntas frequentes",
    "title": "Perguntas e respostas",
    "sub_title": "O que você nos pediu para fazer.",
    "message": "Procure a resposta para sua pergunta entre as respostas abaixo. Pergunte-nos se as perguntas permanecerem sem resposta.",
    "add_question_action": "Fazer nova pergunta",
    "read_more": "Consulte Mais informação ..",
    "load_more": "Mais perguntas ..",
    "main_page": "Página principal de perguntas frequentes",
    "add_new": "Enviar nova pergunta",
    "login_alert": "Faça login para fazer uma pergunta.",
    "question_input": "Pergunta",
    "question_input_placeholder": "Faça sua pergunta.",
    "notifications": {
      "success_add": "Sua pergunta foi enviada com sucesso."
    }
  },
  "rating_labels": [
    "Muito mal",
    "Ruim",
    "Normal",
    "Bom",
    "Excelente"
  ],
  "map_view": {
    "address_detail": "Detalhes do Endereço",
    "change": "Mudar",
    "select": "Selecionar",
    "not_found_address": "Nenhum valor encontrado",
    "enter_address_hint": "Digite o endereço de destino",
    "enter_your_address": "Digite seu endereço.",
    "postal_code": "Código postal",
    "phone_input": "Tipo de telefone}",
    "building_number": "Número do prédio",
    "building_unit": "Unidade",
    "full_name_input": "Nome completo {type}",
    "save_detail_action": "Salvar detalhes",
    "more_detail_input": "Mais descrição",
    "add_address_to_list": "Adicionar endereço à lista",
    "address_title_input": "Etiqueta de endereço (obrigatório)",
    "notifications": {
      "save_in_list": "Este endereço foi salvo em sua lista com todos os seus detalhes.",
      "edit_success": "Novos valores de endereço salvos em {title}."
    },
    "delete_address_dialog": {
      "title": "Excluir endereço",
      "message": "Tem certeza de que deseja excluir este endereço?",
      "action": "Remover endereço"
    }
  },
  "comment_manager": {
    "can_not_edit": "Não é possível editar este comentário!",
    "comment_input_empty": "O texto da mensagem está em branco!",
    "article_not_saved": "Salve o artigo!"
  },
  "wheel_fortune": {
    "title": "Jogue e Ganhe",
    "message": "O custo de cada jogo é de 10 fichas. Atualmente você tem {chips} chip. Obtenha mais chip comprando na loja.",
    "win_message": "Parabéns, você venceu!",
    "lost_message": "Desculpe, você perdeu o jogo.",
    "try_again": "Você pode tentar novamente"
  },
  "json": {
    "add": "Adicionar dados de estrutura",
    "add_message": "Criar novos dados de estrutura",
    "structures": "Estruturas",
    "book": {
      "title": "Livro",
      "desc": "Ações de livros que permitem aos usuários comprar o livro que encontram diretamente nos resultados da Pesquisa."
    },
    "occupation": {
      "title": "Salário estimado",
      "desc": "Informações sobre estimativa de salário, como faixas salariais e médias salariais com base na região para tipos de trabalho, exibidas na experiência de pesquisa de emprego no Google."
    },
    "course": {
      "title": "Curso",
      "desc": "Cursos educacionais que aparecem em uma lista específica do provedor. Os cursos podem incluir o título do curso, o provedor e uma breve descrição."
    },
    "howto": {
      "title": "Como",
      "desc": "Um How-to orienta os usuários por um conjunto de etapas para concluir uma tarefa com êxito, apresentando vídeo, imagens e texto."
    },
    "recipe": {
      "title": "Receita",
      "desc": "Receitas que são exibidas como uma pesquisa aprimorada individual ou parte de um carrossel de host."
    }
  },
  "support": {
    "Financial": "Financeiro",
    "Technical": "Técnico",
    "Advisor": "Orientador"
  },
  "condition": {
    "new": "Novo",
    "refurbished": "Remodelado",
    "used": "Usado",
    "used_fair": "Feira de usados",
    "used_good": "Usado bom",
    "used_like_new": "Usado - Como Novo"
  },
  "variant_filter": {
    "title": "Filtro de variante de produto",
    "only_available": "Em estoque"
  },
  "service": {
    "task": {
      "title": "Tarefas",
      "message": "Lista de tarefas executadas neste serviço."
    },
    "appointment": {
      "title": "Compromisso",
      "message": "Escolha os horários da semana a partir dos seguintes horários com base no dia e na hora certa para você."
    },
    "booking": {
      "title": "Reserva",
      "message": "Especifique o período de tempo dos dias em que deseja fazer uma reserva no calendário abaixo."
    },
    "subscription": {
      "title": "Inscrição"
    },
    "charge": {
      "title": "Carregar"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "Preço fixo",
      "message": "Nesse tipo de precificação, o preço do produto é um valor fixo e não há necessidade de o comprador solicitar cálculo de preço."
    },
    "ESTIMATION": {
      "title": "Preço estimado",
      "message": "O preço dos produtos e serviços será calculado em certa medida pelo vendedor ao fazer um pedido, as faturas de pagamento podem ser alteradas ou adicionadas durante o serviço."
    },
    "AGREEMENT": {
      "title": "Preço do Contrato",
      "message": "O preço final dos produtos ou serviços não será alterado pelo vendedor após a realização do pedido."
    },
    "BID": {
      "title": "Lance / Leilão",
      "message": "O produto será vendido ao preço de lance mais alto por potenciais compradores."
    }
  },
  "map": {
    "title": "Destino para receber produtos",
    "confirm": "Defina localização",
    "address": "Destino",
    "receptor": "Receptor"
  },
  "ShopBots": {
    "telegram": "Telegrama"
  },
  "article_tags": {
    "title": "Tags de conteúdo",
    "tags_input": "Tag",
    "tags_input_message": "Lista de tags deste artigo",
    "notification": {
      "add_success": "Tags adicionadas"
    }
  },
  "difficulties": {
    "very_complicated": "Muito complicado",
    "hard": "Duro",
    "intermediate": "Intermediário",
    "easy": "Fácil"
  },
  "billing_period": {
    "Daily": "Diário",
    "Weekly": "Semanalmente",
    "Monthly": "Por mês",
    "Every3Months": "A cada 3 meses",
    "Every6Months": "A cada 6 meses",
    "Yearly": "Anual"
  },
  "buyer_rating_statement": {
    "between1_2": "Não é bom!",
    "between2_3": "Tudo bem!",
    "between3_4": "As pessoas gostam!",
    "between4_5": "As pessoas adoram!"
  },
  "seasons": {
    "spring": "Primavera",
    "summer": "Verão",
    "autumn": "Outono",
    "winter": "Inverno"
  }
};