export default {
  "currency_default": "USD",
  "language_default": "en",
  "selldone": "продано",
  "store": "хранить",
  "not_exist": "Не существует",
  "error": "Ошибка",
  "active": "Активный",
  "inactive": "неактивный",
  "required_value": "Требуемые значения",
  "original_warranty": "Гарантия оригинального продукта",
  "return_warranty_days": "{days} дней гарантии возврата",
  "no_return_warranty": "Без возврата",
  "reed_agree_terms": "Я прочитал условия использования и политику конфиденциальности и согласен с ними.",
  "commons": {
    "Currency": "Валюта",
    "COD": "COD",
    "State": "Состояние",
    "Price": "цена",
    "order_price": "Сумма заказа",
    "VAT": "VAT",
    "Discount": "Скидка",
    "In_Stock": "В наличии",
    "Variants": "Варианты",
    "No_variants": "Нет варианта",
    "all": "ВСЕ",
    "today": "Сегодня",
    "yesterday": "Вчера",
    "license": "Лицензия",
    "home": "Дом",
    "support": "Поддерживать",
    "messages": "Сообщения",
    "no_message": "Нет сообщений",
    "empty": "Пустой",
    "phone": "Телефон",
    "address": "адрес",
    "name": "Имя",
    "password": "Пароль",
    "email": "Эл. адрес",
    "mobile": "Мобильный",
    "login": "Авторизоваться",
    "register": "регистр",
    "select_account": "Выберите аккаунт",
    "online": "В сети",
    "offline": "Не в сети",
    "finish": "Заканчивать",
    "finished": "Законченный",
    "preview": "Предварительный просмотр",
    "free": "Бесплатно",
    "free_completely": "Полностью бесплатная подписка",
    "fee": "Платеж",
    "month": "Месяц",
    "months": "Месяцы",
    "faq": "Часто задаваемые вопросы",
    "question": "Вопрос",
    "answer": "Отвечать",
    "create_date": "Дата создания",
    "update_date": "Дата обновления",
    "start_date": "Дата начала",
    "end_date": "Дата окончания",
    "social": "Социальное",
    "total": "Общее",
    "orders": "Заказы",
    "sessions": "Сессии",
    "product_views": "Просмотры продукта",
    "add_to_carts": "Добавить в корзину",
    "checkouts": "Проверить",
    "payments": "Оплата",
    "organic_search": "Органический поиск",
    "other": "Другой",
    "landing_page": "Целевая страница",
    "discount_code": "Код скидки",
    "total_sell": "Тотальная распродажа",
    "details": "Подробности",
    "currency": "Валюта",
    "amount": "Количество",
    "published": "Опубликовано",
    "draft": "Проект",
    "save_changes": "Сохранить изменения",
    "source": "Источник",
    "medium": "Середина",
    "url": "URL",
    "revenue": "Доход",
    "performance": "Спектакль",
    "term": "Срок",
    "content": "Содержание",
    "session": "Сессия",
    "product": "Продукт",
    "add": "Добавлять",
    "checkout": "Проверить",
    "payment": "Оплата",
    "more_options": "Больше опций",
    "full_name": "ФИО",
    "tel": "Тел.",
    "about_me": "Обо мне",
    "request_checking": "Запросить проверку",
    "passport": "Заграничный пасспорт",
    "birthday": "День рождения",
    "country": "Страна",
    "city": "Город",
    "gender": "Пол",
    "offer": "Предложение",
    "website": "Интернет сайт",
    "apply_for_all_products": "∞ Подать заявку на все продукты",
    "fix_commission": "Фиксированная комиссия",
    "percent_commission": "Процентная комиссия",
    "fixed_discount": "Фиксированная скидка",
    "discount_percentage": "Процентная скидка",
    "discount_limit": "Лимит скидки",
    "no_code": "Нет кода",
    "max_count": "Максимальное количество",
    "count_unit": "Предметы",
    "used": "Использовал",
    "daily": "Повседневная",
    "monthly": "Ежемесячно",
    "yearly": "Ежегодно",
    "state": "Статус",
    "disable": "Запрещать",
    "enable": "Давать возможность",
    "activation_code": "Код активации",
    "quantity": "Количество",
    "no_club": "Нет клуба",
    "per_order": "За заказ",
    "count": "Считать",
    "seconds": "Секунды",
    "auto": "Авто",
    "title": "Заголовок",
    "message": "Сообщение",
    "width": "Ширина",
    "length": "Длина",
    "height": "Высота",
    "label": "Этикетка",
    "click": "Нажмите",
    "bank": "Банк",
    "default": "По умолчанию",
    "role": "Роль",
    "user": "Пользователь",
    "users": "Пользователи",
    "code": "Код",
    "total_payment": "Всего к оплате",
    "balance": "Остаток средств",
    "chance": "Шанс",
    "free_for_new_users": "Бесплатно для новых пользователей",
    "prize_amount": "Сумма приза",
    "win": "Победить",
    "gift_card": "Подарочная карта",
    "discount": "Скидка",
    "config": "Конфигурация",
    "prize": "Приз",
    "Prizes": "Призы",
    "result": "Результат",
    "price": "цена",
    "lottery": "Лотерея",
    "coupon": "Купон",
    "customer_club": "Клуб клиентов",
    "shipping": "Перевозки",
    "sum": "Сумма",
    "not_paid": "Не выплачивается",
    "category": "Категория",
    "done": "Готово",
    "email_from": "От",
    "subject": "Тема",
    "schedule": "Расписание",
    "files_list": "Список файлов",
    "file_max_size": "Максимальный размер файла",
    "value": "Ценность",
    "help": "Помощь",
    "shipping_tax": "Налог на доставку",
    "net_price": "Цена нетто",
    "tax": "налог",
    "tax_included": "Включено в цену",
    "limit": "Ограничение",
    "min_purchase": "Минимальная покупка",
    "eligible_for": "Право на",
    "only_for_first_buy": "Только на первую покупку",
    "one_time_use": "Можно использовать один раз",
    "period_of_qualify": "Ограничение периода использования",
    "no_constraint": "Безлимитный",
    "timespan": "Временной период",
    "days": "День (дни)",
    "weight": "Масса",
    "distance": "Расстояние",
    "last_status": "Последний статус",
    "issued_at": "Выпущено в",
    "order": "порядок",
    "order_detail": "Информация для заказа",
    "percent": "Процентов",
    "applied_count": "Примененный счет",
    "campaign": "Кампания",
    "os": "Операционная система",
    "browser": "Браузер",
    "device": "Устройство",
    "device_ip": "IP-адрес устройства",
    "location": "Место нахождения",
    "user_agent": "Пользовательский агент",
    "affiliate": "Партнер",
    "timeline": "График",
    "add_note": "Добавить заметку",
    "record": "Записывать",
    "unlimited": "Неограниченный",
    "show_coupons": "Показать купоны",
    "hide_coupons": "Скрыть купоны",
    "service_area": "Зона обслуживания",
    "apps": "Программы",
    "plugins": "Плагины",
    "bots": "Боты",
    "categories": "Категории",
    "products": "Товары",
    "business": "Бизнес",
    "personal": "Личный",
    "size": "Размер",
    "holiday": "Праздничный день",
    "sod": "Оплата при доставке",
    "cod": "Оплата при доставке",
    "free_shipping": "Бесплатная доставка",
    "hours": "Часы",
    "send_date": "Дата отгрузки",
    "deliver_date": "Дата доставки",
    "return_date": "Дата возврата",
    "pending": "В ожидании",
    "delivered": "Доставленный",
    "returned": "Вернулся",
    "canceled": "Отменено",
    "shipping_cost": "Стоимость доставки",
    "action": "Действие",
    "cancel_date": "Дата отмены",
    "deliver_in_process": "Заказ отправлен..",
    "kind": "Тип",
    "detail": "Подробности",
    "map": "карта",
    "actions": "Действия",
    "navigation": "Навигация",
    "navigation_app": "Заявление",
    "payment_date": "Дата платежа",
    "duration": "Продолжительность",
    "bill": "Счет",
    "delivery_persons": "Курьеры",
    "delivery_services": "Службы доставки",
    "live_view": "Прямая трансляция",
    "cart": "Корзина",
    "priority": "приоритет",
    "sufficient_credit": "Достаточный кредит",
    "max_package_size": "Максимальный размер пакета",
    "delay": "Задерживать",
    "credit": "Кредит",
    "livemode": "Жить",
    "paused": "Приостановлено",
    "debug": "Отлаживать",
    "token": "Токен",
    "status": "Статус",
    "courier": "Курьер",
    "track": "Отслеживать",
    "track_order": "Отслеживание заказа",
    "cost": "Расходы",
    "receipt": "Чек",
    "origin": "Источник",
    "destination": "Пункт назначения",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "Не хватает запаса!",
    "sub_total": "Промежуточный итог",
    "customer": "Клиент",
    "delivery": "Доставка",
    "online_orders": "Онлайн-заказы",
    "pos_orders": "POS-заказы",
    "chips": "Чипсы",
    "subscribed": "Подписан",
    "unsubscribed": "Отписался",
    "last_login": "Последний Войти",
    "join_at": "Дате вступления",
    "club": "Клуб",
    "buyer": "Покупатель",
    "seller": "Продавец",
    "or": "Или",
    "type": "Тип",
    "condition": "Состояние",
    "brand": "Бренд",
    "attempt": "Пытаться",
    "error": "Ошибка",
    "success": "Успех",
    "fail": "Неудача",
    "inventory": "Инвентарь",
    "link": "Связь",
    "visits": "Посещения",
    "transactions": "Транзакции",
    "vat": "VAT",
    "pos_vat": "POS НДС",
    "sort_by": "Сортировать по..",
    "from": "От",
    "from_lead_time": "В течение следующих {hours} часов",
    "no_credit_card_info": "Нет информации о карте!",
    "active": "Активный",
    "not_active": "Не активирован!",
    "referrals": "Рефералы",
    "dashboard": "Панель приборов",
    "more": "Более",
    "inactive": "неактивный",
    "developer": "Разработчик",
    "setting": "Параметр",
    "membership_conditions": "Условия членства",
    "customers": "Клиенты",
    "created_at": "Дата создания",
    "updated_at": "Последнее обновление",
    "register_at": "Дата регистрации",
    "old": "Старый",
    "new": "Новый",
    "start": "Начинать",
    "end": "Конец",
    "pos": "POS",
    "out_of_stock": "Распродано",
    "fake": "Не настоящие",
    "low_inventory_warning": "Внимание, низкий инвентарь!",
    "webhook": "Вебхук",
    "notification": "Уведомление",
    "sms": "SMS",
    "online_payment_link": "Ссылка для оплаты онлайн",
    "waiting_load_data": "Ожидание загрузки данных..",
    "views": "Взгляды",
    "sales": "Продажи",
    "total_views": "Всего просмотров",
    "total_sales": "Тотальная распродажа",
    "from_previous_n_days": "За последние {days} дн.",
    "drop_shipping": "Дропшиппинг",
    "commission": "комиссия",
    "shipping_area": "Зона отгрузки",
    "main_seller": "Основной продавец",
    "domain": "Домен",
    "contact": "Контактная информация",
    "wallet": "Бумажник",
    "reseller": "Реселлер",
    "tracking_code": "Код отслеживания",
    "tracking_url": "URL отслеживания",
    "fulfillments": "Исполнения",
    "reject": "Отклонять",
    "reserved": "Зарезервированный",
    "score": "Счет",
    "customer_price": "Цена клиента",
    "options": "Опции",
    "show_details": "Показать детали",
    "no_data": "Нет данных..",
    "waiting": "Ожидающий...",
    "waiting_connecting_payment": "Ожидание платежного сервиса...",
    "creating_secure_payment": "Создание защищенного платежа.",
    "officer": "Офицер",
    "ticket": "Билет",
    "ticket_url": "URL билета",
    "closed_at": "Закрыто в",
    "close_ticket": "Закрыть тикет",
    "reopen_ticket": "Повторно открыть билет",
    "require": "Требовать*",
    "search": "Поиск...",
    "language": "Язык",
    "tasks": "Задачи",
    "permissions": "Разрешения",
    "finish_date": "Дата окончания",
    "complete_date": "Дата завершения",
    "settle_date": "Расчетная дата",
    "cost_span": "Ценовой диапазон",
    "industry": "Промышленность",
    "rating": "Рейтинги",
    "rates": "Рейтинг",
    "seen_at": "Видел в",
    "completed": "Завершенный",
    "you": "Ты",
    "shop": "Магазин",
    "store": "хранить",
    "granted": "Предоставляется",
    "deny": "Отрицать",
    "request": "Запрос",
    "expert": "Эксперт",
    "response": "Ответ",
    "requests": "Запросы",
    "experts": "Эксперты",
    "responses": "Ответы",
    "negotiations": "Переговоры",
    "all_chats": "Все чаты",
    "chats": "Чаты",
    "tags": "Теги",
    "description": "Описание",
    "rates_count": "Количество оценок",
    "rate": "Рейтинг",
    "comment": "Комментарий",
    "chat": "Чат",
    "install": "Установить",
    "edited": "Отредактировано",
    "undo": "Отменить",
    "redo": "Повторить",
    "male": "Мужской",
    "female": "женский",
    "calculator": "Калькулятор",
    "catalog": "Каталог",
    "max_height": "Максимальная высота",
    "images_compare": "Сравнение изображений",
    "canvas": "Холст",
    "table_of_contents": "Оглавление",
    "comments": "Комментарии",
    "badge_codes": "Код значка",
    "need_more": "Нужно больше?",
    "invite_glow_caption": "Получите 14,9$ за каждого друга!",
    "register_free": "100% бесплатная регистрация",
    "gift": "Подарок",
    "google": "Google",
    "facebook": "Фейсбук",
    "instagram": "Инстаграм",
    "instashop": "Инсташоп",
    "show": "Шоу",
    "hide": "Скрывать",
    "waiting_review": "Ожидает рассмотрения",
    "not_selected": "Не выбран",
    "time": "Время",
    "final_price": "Окончательная цена",
    "starting_price": "Стартовая цена",
    "day": "День",
    "paid": "Оплаченный",
    "service_bill": "Оплата счета",
    "avocado": "Авокадо",
    "delivery_price": "Стоимость доставки",
    "select_address": "Выберите адрес",
    "image": "Изображение",
    "view": "Вид",
    "sell": "Распродажа",
    "hyper": "Гипер",
    "cart_list": "Корзина",
    "barcode_scanner": "Сканер штрих-кода",
    "scan_qr_code": "Сканировать QR-код",
    "new_carts": "Новые тележки",
    "pays": "Платежи",
    "annually": "Ежегодно",
    "sells": "Продажи",
    "articles": "Статьи",
    "jobs": "Работа",
    "job": "Работа",
    "blog": "Блог",
    "deleted_at": "Удалено в",
    "capacity": "Вместимость",
    "download_at": "Дата последней загрузки",
    "downloads": "Загрузки",
    "usage": "использование",
    "select_upload_file": "Выберите или перетащите файл",
    "download_link": "Ссылка для скачивания",
    "uploading": "Загрузка..",
    "files": "Файлы",
    "star": "Звезда",
    "speed": "Скорость",
    "feedback": "Обратная связь",
    "new_messages": "Новые сообщения",
    "file": "Файл",
    "attachment": "Вложение",
    "gallery": "Галерея",
    "sync": "Синхронизировать",
    "diff_time": "Разница во времени",
    "network": "Сеть",
    "account": "Счет",
    "configuration": "Конфигурация",
    "blockchain": "Блокчейн",
    "blog_link": "Ссылка на блог",
    "community": "Сообщество",
    "critical_zone": "Критическая зона",
    "statistics": "Статистика",
    "access": "Доступ",
    "seo": "SEO",
    "followers": "Последователи",
    "followings": "Подписки",
    "private": "Предварительный просмотр",
    "soon": "Скоро",
    "features": "Функции",
    "bot": "Бот",
    "sample": "Образец",
    "how_it_work": "Как это работает?",
    "page": "Страница",
    "congratulations": "Поздравления",
    "recommend": "Рекомендовать",
    "recommended": "рекомендуемые",
    "recoms": "Рекомендации",
    "likes": "Нравится",
    "clicks": "Клики",
    "platform": "Платформа",
    "cms": "CMS",
    "cash": "Денежные средства",
    "dir_payment": "банковский перевод",
    "auto_complete": "Автозаполнение",
    "compare": "Сравнивать",
    "infinite": "Бесконечный",
    "tips": "Советы",
    "technical": "Технические",
    "finance": "Финансы",
    "your_phone_input": "Введите номер телефона",
    "income": "Доход",
    "change": "Сдача",
    "new_users": "Новые пользователи",
    "success_orders": "Успешные заказы",
    "direct": "Прямой",
    "last_activity": "Последняя активность",
    "landing": "Посадка",
    "now": "Теперь",
    "accept_agreement": "Я прочитал и принял условия.",
    "report": "Отчет",
    "tablet": "планшет",
    "pc": "PC",
    "acquisition_channel": "Канал приобретения",
    "to": "К",
    "info": "Информация",
    "general": "Общий",
    "upload": "Загрузить",
    "general_config": "Общая конфигурация",
    "limits_config": "Ограничения",
    "design_config": "Дизайн и стиль",
    "duration_config": "Ограничение продолжительности",
    "constraints_config": "Ограничения приемлемости",
    "clubs_config": "Доступно в клубах",
    "additional_config": "Дополнительные конфиги",
    "import": "импорт",
    "ribbon": "Лента",
    "countries": "Страны",
    "edit": "Редактировать",
    "delete": "Удалить",
    "analytics": "Аналитика",
    "rules": "Правила",
    "unset": "Не задано",
    "carts": "Тележки",
    "optional": "Необязательный",
    "design": "Дизайн",
    "filter": "Фильтр",
    "send": "Отправлять",
    "approved": "Одобренный",
    "unit": "Ед. изм",
    "profile": "Профиль",
    "shipping_rates": "Тарифы на доставку",
    "package": "Упаковка",
    "overview": "Обзор",
    "live": "Жить",
    "never": "Никогда",
    "always": "Всегда",
    "mandatory": "Обязательное",
    "expire_at": "Срок действия",
    "position": "Позиция",
    "channel": "Канал",
    "age": "Возраст",
    "charge": "Заряд",
    "giftcard": "Подарочная карта",
    "acquisition": "Получение",
    "conversion": "Преобразование",
    "total_payments": "Всего платежей",
    "community_ask": "Спросите в сообществе",
    "children": "Дети",
    "export": "Экспорт",
    "list": "Список",
    "hierarchy": "Иерархия",
    "images": "Картинки",
    "demo": "Демо",
    "author": "Автор",
    "designer": "Дизайнер",
    "max": "Максимум",
    "accepted": "Принятый",
    "reply": "Отвечать",
    "reviewed": "Рассмотрено",
    "restored": "Восстановлено",
    "merchant": "Торговец",
    "per_product": "За продукт",
    "journey": "Путешествие",
    "after": "После",
    "waiting_for_payment": "Пожалуйста, завершите оплату...",
    "hour": "Час",
    "minute": "Минута",
    "premium": "Премиум",
    "light": "Светлый",
    "dark": "Темный",
    "guest": "Гость",
    "shops": "магазины",
    "vendor": "Продавец",
    "vendors": "Продавцы",
    "marketplace": "Торговая площадка",
    "verify_date": "Подтвердить дату",
    "note": "Примечание",
    "panel": "Панель",
    "removed": "Удаленный",
    "segments": "Сегменты",
    "personal_info": "Личная информация",
    "preferences": "Настройки",
    "spec": "Спецификация",
    "reviews": "Отзывы",
    "constraints": "Ограничения",
    "flexible": "Гибкий",
    "usage_limit": "Лимит использования",
    "temporary": "Временный",
    "original": "Оригинал",
    "saved": "Сохранено!",
    "sort": "Сортировать",
    "documents": "Документы",
    "document": "Документ",
    "please_wait": "Пожалуйста подождите...",
    "pickup": "Подбирать",
    "customize": "настроить",
    "difficulty": "Сложность",
    "banned": "Запрещено",
    "company": "Компания",
    "tax_shipping": "Налог на доставку",
    "warranty": "Гарантия",
    "return_policy": "Политика возврата",
    "guide": "Руководство",
    "translate": "Перевести",
    "public": "Общественный",
    "deleted": "Удалено",
    "variant": "Вариант",
    "secure": "Безопасный",
    "admin": "Администратор"
  },
  "dialogs": {
    "delete": {
      "title": "Удалить",
      "message": "Вы уверены, что хотите удалить этот элемент?",
      "action": "Да, удалить сейчас"
    }
  },
  "actions": {
    "add_to_cart": "Добавить в корзину",
    "cancel": "Отмена",
    "update": "Обновлять",
    "add": "Добавлять",
    "delete": "Удалить",
    "new": "Новый",
    "save_continue": "Сохранить и продолжить",
    "save": "Сохранять",
    "save_changes": "Сохранить изменения",
    "change": "Сдача",
    "continue": "Продолжать",
    "close": "Закрывать",
    "finish": "Заканчивать",
    "poll": "Голосование",
    "view": "Вид",
    "edit": "Редактировать",
    "next": "Следующий",
    "previous": "Предыдущий",
    "create": "Создавать",
    "set": "набор",
    "find": "Находить",
    "accept": "Принимать",
    "reject": "Отклонять",
    "back": "Назад",
    "pay": "Платить",
    "pay_now": "Заплатить сейчас",
    "print": "Распечатать",
    "return": "Возврат",
    "publish": "Публиковать",
    "confirm": "Подтверждать",
    "copy": "Копировать",
    "submit": "Представлять на рассмотрение",
    "send": "Отправлять",
    "yes": "Да",
    "no": "нет",
    "meh": "Хм",
    "clear": "Прозрачный",
    "dismiss": "Увольнять",
    "search": "Поиск",
    "deselect_all": "Убрать выделение со всего",
    "select_all": "Выбрать все",
    "refresh": "Обновить",
    "verify": "Проверять",
    "play": "Играть",
    "open": "Открытым",
    "calculate": "Рассчитать",
    "quick_buy": "Быстрая покупка",
    "click_here": "кликните сюда",
    "schedule": "Расписание",
    "send_now": "Отправить сейчас",
    "download": "Скачать",
    "reset_default": "Восстановление значений по умолчанию",
    "reset": "Перезагрузить",
    "check": "Проверять",
    "cod_payment": "Оплата при доставке",
    "dir_payment": "Перевод денег",
    "online_payment": "Онлайн платеж",
    "checkout": "Проверить",
    "show_all": "Показать все",
    "login": "Авторизоваться",
    "logout": "Выйти",
    "more": "Более..",
    "collapse": "Крах",
    "apply_change": "Применить изменения",
    "apply": "Применять",
    "add_giftcard": "Добавить подарочную карту",
    "charge": "Заряд",
    "send_invites": "Отправить приглашения",
    "past": "прошлое",
    "restore": "Восстановить",
    "cut": "Резать",
    "get_sms_code": "Получить код аутентификации",
    "register_no_mail": "Продолжить без электронной почты",
    "no_mail_register_message": "У вас нет адреса электронной почты или вы забыли пароль?",
    "reset_by_mail": "Восстановление пароля по электронной почте",
    "reset_by_sms": "Восстановление пароля по смс",
    "cash_payment": "Наличный расчет",
    "show_chart": "Показать диаграмму",
    "open_app": "Открыть приложение",
    "login_now": "Войти сейчас",
    "watch_video": "Смотреть видео",
    "check_now": "Проверь сейчас",
    "remove_image": "Удалить изображение",
    "view_website": "Открыть ссылку",
    "explore": "Исследуйте {name}",
    "go": "Идти",
    "read_more": "Прочитайте больше",
    "start_now": "Начните сейчас — это бесплатно",
    "view_live": "Смотреть в прямом эфире",
    "resend_code": "Отправить код еще раз",
    "invite": "Приглашать",
    "add_more": "Добавить больше",
    "install_now": "Установить сейчас",
    "uninstall": "Удалить",
    "show_preview": "Показать предварительный просмотр",
    "hide_preview": "Скрыть предварительный просмотр",
    "download_now": "Скачать сейчас",
    "auto_fill": "Автозаполнение",
    "track": "Отслеживать",
    "change_state": "Изменить статус",
    "done": "Готово",
    "reply": "Отвечать",
    "watch_now": "Смотри",
    "unlock": "Разблокировать",
    "lock": "Замок",
    "create_clone": "Создать клон",
    "regenerate": "Регенерировать",
    "add_message": "Добавить сообщение",
    "continue_chat": "Продолжить чат",
    "add_new_message": "Добавить новое сообщение"
  },
  "instance_message_title": "Отправить мгновенное сообщение",
  "instance_message": "Привет, {name}, меня зовут {author} из {company}.",
  "errors": {
    "419": "Вы долгое время были неактивны, пожалуйста <b>⟳ ОБНОВИТЕ СТРАНИЦУ</b> в целях безопасности.",
    "gateway_blockchain_sync_error": "Система не синхронизируется с блокчейном. Невозможно будет создать новую транзакцию, пока синхронизация наших серверов не будет завершена. Мы решаем проблему.",
    "gateway_network_error": "Служба платежного шлюза столкнулась с проблемой связи."
  },
  "receiver_info": {
    "map": {
      "title": "Адреса доставки",
      "confirm": "Установить местоположение",
      "address_type": "Пункт назначения",
      "receptor_type": "Получатель"
    },
    "receiver_address": "Выберите адрес доставки",
    "address": "адрес",
    "postcode": "Почтовый индекс",
    "enter_value": "Заполните здесь",
    "address_note": "Примечание",
    "tel": "Контактный телефон",
    "service_address": "Выберите свой адрес"
  },
  "weight": {
    "g": "грамм",
    "oz": "унция",
    "lb": "фунт",
    "kg": "кг"
  },
  "mass_unit_name": {
    "g": "грамм",
    "oz": "Унция",
    "lb": "Фунт",
    "kg": "килограмм"
  },
  "length": {
    "cm": "см",
    "in": "в",
    "ft": "футов",
    "mm": "мм",
    "m": "м",
    "yd": "ярд"
  },
  "size_unit_name": {
    "cm": "сантиметр",
    "in": "Дюйм",
    "ft": "Стопа",
    "mm": "миллиметр",
    "m": "метр",
    "yd": "Площадка"
  },
  "distance": {
    "m": "метр",
    "km": "км"
  },
  "time": {
    "days": "Дней",
    "hours": "Часы",
    "minutes": "Минуты",
    "seconds": "Секунды"
  },
  "units": [
    "Ед. изм",
    "вещь",
    "каждый",
    "набор",
    "кусок",
    "килограмм",
    "грамм",
    "миллиграмм",
    "метр",
    "миллиметр",
    "квадратный метр",
    "квадратный фут",
    "кубический метр",
    "литр",
    "миллилитр",
    "ноги",
    "галлоны",
    "дюймы",
    "унции",
    "фунты",
    "кварт",
    "ярды",
    "номер",
    "секунды",
    "минуты",
    "часы",
    "дни",
    "недели",
    "месяцы",
    "годы"
  ],
  "region_types": {
    "State": "Состояние",
    "Territory": "Территория",
    "Province": "Провинция"
  },
  "transaction_status": {
    "RequireAction": "Требуются действия",
    "Processing": "Обработка",
    "Canceled": "Отменено",
    "Succeeded": "Успешно"
  },
  "placeholders": {
    "name": "Джон Кокс",
    "email": "ваш-mail@mail.com",
    "phone": "+1 000 0000",
    "language": "Выбрать язык..",
    "friend_email": "Электронная почта вашего друга...",
    "friend_name": "Опц. Имя твоего друга",
    "select_date": "Выберите дату..."
  },
  "notification": {
    "confirm": "Подтверждать",
    "confirm_message": "Изменения успешно сохранены.",
    "error": "Ошибка",
    "message": "Сообщение",
    "caution": "Осторожность",
    "warning": "Предупреждение",
    "award": "Поздравление",
    "error_message": "К сожалению, произошла ошибка.",
    "congratulation": "Поздравление",
    "coming_soon": "Скоро",
    "on_fetching_data": "Получение информации..",
    "new_pwa_version": "Доступна новая версия. Хотите обновить приложение?",
    "over_license_limit": "Превышение лимита лицензии",
    "update_license": "Обновите свою лицензию",
    "required": "Необходимый",
    "invalid_email": "Неверный адрес электронной почты",
    "invalid_domain": "Недействительный домен",
    "invalid_min_length": "Минимальная длина должна быть {length}",
    "invalid_min_array_length": "По крайней мере, выберите {length} элементов",
    "invalid_max_chars": "Макс. {maxCount} символов",
    "invalid_url": "Неверная ссылка",
    "country_invalid": "Выберите страну назначения!",
    "postal_code_invalid": "Укажите действительный почтовый индекс!"
  },
  "colors": {
    "#D32F2F": "Красный",
    "#C2185B": "Розовый",
    "#7B1FA2": "Пурпурный",
    "#512DA8": "Темно фиолетовый",
    "#303F9F": "Индиго синий",
    "#1976D2": "Синий",
    "#0288D1": "Светло-синий",
    "#0097A7": "Бирюзово-синий",
    "#00796B": "Гусь Грин",
    "#388E3C": "Зеленый",
    "#689F38": "Светло-зеленый",
    "#AFB42B": "лимузин",
    "#FBC02D": "Желтый",
    "#FFA000": "Янтарь",
    "#F57C00": "Апельсин",
    "#E64A19": "Блестящий апельсин",
    "#5D4037": "Коричневый",
    "#616161": "Серый",
    "#455A64": "Серый Синий",
    "#FFD700": "Золотой",
    "#C0C0C0": "Серебряный",
    "#b76e79": "Золотая роза",
    "#383838": "Матовый черный",
    "#FFFFFF": "Белый",
    "#FFF": "Белый",
    "#000000": "Чернить",
    "#000": "Чернить",
    "#7d263a": "темно-бордовый",
    "#FD9F17": "Золото",
    "#229DBF": "Аква",
    "#6DC9E2": "Аква Трибленд",
    "#413B2D": "Армия",
    "#474747": "Асфальт",
    "#E6195C": "Ягода",
    "#B2184C": "Берри Трибленд",
    "#FC7F5F": "Жженый апельсин",
    "#80011F": "Кардинал",
    "#382829": "Шоколад",
    "#F06336": "коралловый",
    "#FAE7C9": "Пломбир",
    "#6B2257": "Смородина",
    "#222127": "Темно-серый",
    "#0D5A74": "Глубокий бирюзовый",
    "#00582F": "Вечнозеленый",
    "#214C30": "Лес",
    "#DC2867": "фуксия",
    "#38561": "Келли",
    "#5C884D": "Лист",
    "#558450": "Светлая вода",
    "#96B5C9": "Светло-синий",
    "#DCAFCE": "Сирень",
    "#D3E1A4": "Лайм",
    "#9DE7C2": "Монетный двор",
    "#F6EAD2": "Естественный",
    "#1A1F35": "Военно-морской",
    "#404624": "Оливковое",
    "#271020": "слива",
    "#A8355C": "Малина",
    "#D6BEA6": "Мягкий крем",
    "#BEA994": "Тан",
    "#0DB2AE": "Бирюзовый",
    "#A86EA9": "Фиолетовый",
    "#36454F": "Древесный уголь",
    "#b3b0ab": "карбоновый серый",
    "#463e3d": "Древесный уголь вереск",
    "#282d3c": "Темно-синий блейзер"
  },
  "address_info": {
    "name": "Имя",
    "tel": "Телефон",
    "email": "Эл. адрес",
    "country": "Страна",
    "city": "Город",
    "state": "Состояние",
    "address": "адрес",
    "building_number": "Номер здания",
    "building_unit": "Ед. изм",
    "postcode": "Почтовый индекс",
    "note": "Примечание",
    "county": "округ"
  },
  "product_types": {
    "physical": "Физический",
    "physical_description": "Физические продукты, такие как: мобильные телефоны, книги, электронные компоненты.",
    "virtual": "Виртуальный",
    "virtual_description": "Удобные для Интернета продукты, такие как: карта пополнения, бронирование отеля, пополнение счета в игре.",
    "file": "Файл",
    "file_description": "Все разрешенные файлы, такие как видео онлайн-курса, загружаемые документы.",
    "service": "Услуга",
    "service_description": "Такие услуги, как: ремонт, транспорт, обучение."
  },
  "license": {
    "free": "Бесплатно",
    "startup": "Запускать",
    "company": "Компания",
    "enterprise": "Предприятие"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "Мужчине",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW",
    "GHS": "GHS",
    "ZWD": "ZWD",
    "IQD": "IQD",
    "SYP": "SYP"
  },
  "variants": {
    "color": "Цвет",
    "volume": "Размер",
    "count_in_pack": "Количество в упаковке",
    "weight": "Масса",
    "type": "Материал",
    "style": "Стиль"
  },
  "delivery_state": {
    "check_queue": "Ожидает рассмотрения",
    "order_confirm": "Подтверждение заказа",
    "preparing_order": "Подготовка",
    "sent_order": "В процессе доставки",
    "to_customer": "Доставленный"
  },
  "status": {
    "unpaid": "Неоплачиваемый",
    "paid": "Оплаченный",
    "canceled": "Отменено",
    "completed": "Урегулировано",
    "reserved": "Зарезервированный",
    "COD": "COD",
    "sold": "Продал",
    "open": "Открытым",
    "cancel": "Отменено",
    "active": "Активный",
    "inactive": "неактивный",
    "debug": "Отлаживать",
    "live": "Жить",
    "test": "Контрольная работа",
    "connected": "Связанный",
    "disconnected": "Отключено",
    "accept": "Принимать",
    "reject": "Отклонять",
    "pending": "В ожидании",
    "rejected": "Отклоненный",
    "accepted": "Принятый"
  },
  "dimensions": {
    "cm": "см",
    "km": "км",
    "kg": "кг"
  },
  "transportation_type": {
    "motorbike": "мотоцикл",
    "motorbike_description": "Средний вес в пределах нескольких километров.",
    "cargo_small": "Мелкий груз",
    "cargo_small_description": "Многокилометровый легкий груз.",
    "cargo": "Груз",
    "cargo_description": "Средний вес в пределах нескольких километров.",
    "truck": "Грузовая машина",
    "truck_description": "Сыпучие или тяжеловесные грузы внутри страны.",
    "fast_post": "Быстрая почта",
    "fast_post_description": "Быстрая отправка через почтовое отделение.",
    "post": "Обычный пост",
    "post_description": "Обычная почта через почтовое отделение.",
    "airplane": "Авиапочта",
    "airplane_description": "Внутренние и зарубежные легкие и средние грузы.",
    "bicycle": "Чистая отправка",
    "bicycle_description": "Легкий груз в пределах нескольких сотен ярдов от немоторизованных транспортных средств.",
    "global": "Глобальный транспорт",
    "global_description": "Доставка за границу воздушным, морским или наземным транспортом.",
    "pickup": "Подбирать",
    "pickup_description": "Клиенты забирают товары в вашем физическом магазине или на складе."
  },
  "article": {
    "login_to_see_error": "Войдите, чтобы получить доступ к статье",
    "create_new_action": "Создать новый контент",
    "menu_title": "Меню",
    "menu": {
      "edit": "Режим редактирования",
      "view_mode": "Режим просмотра",
      "delete": "Удалить статью"
    },
    "schedule_action": "Хотите запланировать публикацию?",
    "schedule_title": "Запланировать автоматическую публикацию",
    "edit_mode": "Редактировать",
    "public_view_mode": "Общий вид",
    "publish_at": "Опубликовать в",
    "published": "Опубликовано",
    "draft": "Проект",
    "saving": "Сохранение",
    "save_and_publish_action": "Сохранить и опубликовать",
    "save_draft_action": "Сохранить черновик",
    "private": "Частный",
    "public": "Общественный",
    "category_input": "Категория",
    "category_input_message": "Выберите категорию статьи",
    "parent_input": "Родительская категория",
    "parent_input_message": "Выберите отцовский контент",
    "schedule_input": "Расписание",
    "schedule_input_placeholder": "Если вы хотите, чтобы история была опубликована в определенное время.",
    "schedule_view_action": "Посмотреть расписание публикации",
    "author_title": "Написано",
    "read_time": "Учебное время",
    "read_time_unit": "Минуты",
    "claps_action": "Хлопки",
    "claps": "Хлопки",
    "likes": "Нравиться",
    "about_author": "Об авторе",
    "updated_at": "Обновлено",
    "wrote_at": "Написано в",
    "now": "Теперь",
    "follow_action": "Следовать",
    "followed": "Подписано",
    "report_and_delete_action": "Пожаловаться и удалить эту статью",
    "report_action": "Сообщить о нарушении",
    "you_reported_this_article": "В этой статье уже есть сообщение о нарушении.",
    "add_to_publication_action": "Добавить в публикацию",
    "author_socials": "Автор в социальных сетях",
    "share": "Делиться",
    "report_dialog": {
      "report_and_delete_title": "Сообщить о нарушении и удалить контент",
      "report_title": "Сообщить об этом контенте как оскорбительном",
      "message": "Какова причина отправки этого контента? Выберите один из следующих вариантов.",
      "accept_and_delete_action": "Подтвердить и удалить контент"
    },
    "schedule_dialog": {
      "title": "График выпуска контента",
      "publish_at": "Опубликовать в",
      "last_edit": "Последнее редактирование",
      "view_action": "Посмотреть статью"
    },
    "notifications": {
      "update_success_title": "Отправить информацию",
      "update_success": "Статья успешно обновлена.",
      "update_error": "Введенная информация недействительна.",
      "delete_error": "Вы не можете удалить эту статью!",
      "report_and_delete_success_title": "Сообщить и удалить",
      "report_and_delete_success_message": "Статья успешно удалена.",
      "report_success_title": "Сообщить о статье",
      "report_success_message": "Ваш отчет по этой статье опубликован."
    },
    "alert": {
      "delete_article": {
        "title": "Удалить статью",
        "message": "Вы уверены, что хотите навсегда удалить эту статью?",
        "action": "Удалить"
      }
    },
    "edit_window": {
      "title": "Выберите текст изображения и сводку",
      "digest": "Резюме"
    },
    "editor": {
      "title_placeholder": "Заголовок..",
      "body_placeholder": "Пишите отличный контент..",
      "accept_file_types_error": "Этот формат файла недопустим:",
      "max_file_size_error": "Этот файл слишком большой:",
      "notifications": {
        "image_uploaded_success": "Изображение успешно сохранено",
        "image_uploaded_failed": "Ошибка загрузки изображения."
      },
      "embed_placeholder": "Введите код iframe, Facebook, Youtube или любой другой URL-адрес и нажмите Enter.",
      "embed_caption_placeholder": "Введите название (необязательно)",
      "images_caption_placeholder": "Введите название для этого изображения.."
    }
  },
  "article_report": {
    "inappropriate": "Содержание этой статьи не соответствует действительности.",
    "fake": "Это фальшиво и обманчиво.",
    "spam": "Этот элемент был заспамлен и скопирован.",
    "scam": "Можно ожидать, что это вызовет вредоносное ПО, вирусы или системный сбой.",
    "hacked": "Похоже, что этот сайт был взломан.",
    "offensive": "Языковое содержание и словарный запас являются неэтичными и неуважительными.",
    "violent": "Я считаю, что этот контент содержит порнографию и нарушает законы.",
    "harassment": "Я думаю, что это расизм.",
    "hate": "Я думаю, что это пропаганда насилия.",
    "infringe": "Это нарушает мои права."
  },
  "comments": {
    "new_action": "Нажмите, чтобы оставить комментарий..",
    "title": "Комментарии",
    "body_placeholder": "Ваш комментарий или сообщение",
    "send_action": "Отправить комментарий",
    "body_is_empty_error": "Комментарий пуст!",
    "comments": "Комментарии",
    "no_comments": "Напишите первый комментарий...",
    "load_more_action": "Получить больше комментариев ..",
    "cant_send_comment": "Вы не можете добавить новый пост.",
    "cant_remove_this_comment": "Вы не можете удалить этот комментарий!",
    "product_buyer": "Покупатель",
    "delete_alert": {
      "title": "Удалить комментарий",
      "message": "Вы хотите удалить этот комментарий?",
      "action": "Удалить"
    },
    "notifications": {
      "delete_success": "Ваш комментарий успешно удален."
    },
    "first_send": "Первый пост",
    "comment_at": "На",
    "edit_comment": "Редактировать комментарий"
  },
  "customer_club": {
    "bronze": "Бронза",
    "silver": "Серебряный",
    "gold": "Золотой",
    "platinum": "Платина",
    "diamond": "Алмаз"
  },
  "application_categories": {
    "tracking": "Проверка поведения пользователя",
    "payment": "Оплата",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "Транспорт",
    "automation": "Автоматизация",
    "inventory": "Складирование",
    "accounting": "Бухгалтерский учет",
    "marketing": "Маркетинг",
    "advertising": "Реклама",
    "staff": "Персонал",
    "incentive": "Стимулы",
    "shop": "Магазин"
  },
  "social_network": {
    "instagram": "Инстаграм",
    "telegram": "Телеграмма",
    "googleplay": "Гугл игры",
    "appstore": "Магазин приложений",
    "twitter": "Твиттер",
    "linkedin": "Линкедин",
    "medium": "Середина",
    "selldone": "продано",
    "facebook": "Фейсбук",
    "pinterest": "Пинтерест",
    "whatsapp": "WhatsApp",
    "skype": "Скайп",
    "facebook_messenger": "Facebook-мессенджер"
  },
  "form_builder": {
    "add_item_action": "Добавить новый элемент",
    "title_input": "Заголовок",
    "name_input": "Имя переменной",
    "value_input": "Ценности",
    "value_input_message": "Список параметров пользователя",
    "default": "Значение по умолчанию",
    "types": {
      "simple": "Простой",
      "selective": "Селективный",
      "switch": "Выключатель",
      "file": "Файл",
      "number": "Число"
    },
    "placeholder_input": "Заполнитель",
    "file_type_input": "Допустимые типы файлов",
    "file_type_message": "jpeg, png, zip, ..."
  },
  "virtual_order_info_summery": {
    "title": "наименование товара",
    "reserved_at": "Дата регистрации",
    "total_price": "Общая сумма",
    "discount": "Скидка",
    "final_price": "Окончательная сумма",
    "payment_status": "Статус платежа",
    "payment_status_waiting": "ожидается платеж",
    "payment_status_paid": "Оплаченный",
    "buyer": "Покупатель"
  },
  "virtual_item_info": {
    "title": "Виртуальный предмет",
    "outputs": {
      "title": "Выходная информация",
      "sub_title": "Конфиденциальная информация об этом элементе",
      "message": "Эта информация будет показана пользователю после покупки продукта."
    },
    "inputs": {
      "title": "Требуется информация",
      "sub_title": "Требуется информация о покупателе",
      "message": "Покупатель должен ввести запрашиваемую информацию в форму"
    },
    "notifications": {
      "inputs_set_success": "Информационная форма успешно зарегистрирована.",
      "confirm_by_admin_success": "Подтверждено выполнение заказа.",
      "confirm_by_buyer_success": "Подтверждено выполнение заказа."
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "Этот заказ не может быть принят наложенным платежом.",
    "payment_returned": "Оплата заказчиком возвращается.",
    "payment_fraud": "Оплата признана мошенничеством.",
    "location_out_of_service": "Местоположение клиента недоступно.",
    "user_not_responding": "Клиент не отвечал на звонки.",
    "shop_owner_fault": "Произошла ошибка сотрудников магазина при заполнении информации.",
    "lack_of_inventory": "Распродано.",
    "legal_restriction": "Невозможно разместить заказ из-за юридических ограничений.",
    "pricing_fault": "Ошибка продавца в цене.",
    "system_fault": "Системная ошибка."
  },
  "basket_order_info_summery": {
    "receiver": "Получатель",
    "phone": "Тел.",
    "reserved_date": "Дата покупки",
    "total_price": "Общая сумма",
    "discount": "Скидка",
    "final_price": "Окончательная сумма",
    "address": "Адрес доставки",
    "payment_status": "Статус платежа"
  },
  "basket_status": {
    "open": "Открытым",
    "reserved": "Зарезервированный",
    "paid": "Оплаченный",
    "canceled": "Отменено",
    "cod": "Оплата при доставке",
    "receipt_added": "Квитанция добавлена",
    "payment_processing": "Процесс оплаты"
  },
  "basket_delivery_state": {
    "rejected": "Отклоненный",
    "reject_reason_not_found": "Причина неизвестна.",
    "step_1": "Рассмотрение",
    "step_2": "Подтверждение",
    "step_3": "Подготовка",
    "step_4": "В процессе доставки",
    "step_5": "Доставленный"
  },
  "basket_return_request_view": {
    "title": "Запрос на возврат",
    "delivery_date": "Дата доставки",
    "return_date": "Дата заказа",
    "items_count": "Количество возвращенных товаров",
    "items_count_unit": "Предметы)",
    "reason": "Причина",
    "description": "Описание",
    "status": "Статус",
    "download_image": "Скачать изображение",
    "download_film": "Скачать видео",
    "download_voice": "Скачать голос",
    "accept_by_admin_action": "Принять запрос",
    "reject_by_admin_action": "Отклонить запрос",
    "message_for_admin": "В соответствии с соглашением, которое вы приняли с помощью Selldone, вы должны связаться с покупателем и информировать его о процессе возврата его заказа. Это необходимо сделать, если запрос принят или отклонен и получено полное согласие покупателя.",
    "notifications": {
      "update_status_success": "Статус запроса обновлен."
    }
  },
  "basket_list": {
    "return_count": "Возврат: {count} число",
    "table": {
      "row": "Ряд",
      "image": "Изображение",
      "product_name": "Продукт",
      "variant": "Вариант",
      "warranty": "Гарантии",
      "count": "Считать",
      "price": "цена"
    }
  },
  "return_request_list": {
    "count": "Справочный номер",
    "return_warranty": "Гарантия возврата денег",
    "return_warranty_unit": "День (дни)",
    "table": {
      "code": "Код заказа",
      "product": "Продукт",
      "delivery_at": "Дата получения",
      "state": "Статус",
      "reason": "Причина",
      "return_warranty_period": "Гарантийный срок"
    }
  },
  "data_toolbar": {
    "search": "Поиск",
    "sort_by": "Сортировать по",
    "count_item": "Показать {item} элементов"
  },
  "sort": {
    "created_at": "Дата создания",
    "updated_at": "Изменить дату",
    "title": "Заголовок",
    "description": "Описание",
    "like": "Популярность",
    "power": "Хлопки",
    "product_type": "Тип продукта",
    "discount": "Скидка",
    "rate": "Рейтинг",
    "rate_count": "Количество оценок",
    "category": "Категория",
    "product": "Продукт",
    "body": "Содержание",
    "card_type": "Тип карты",
    "card_number": "Номер карты",
    "balance": "Остаток средств",
    "paid": "Сумма потрачена",
    "currency": "Валюта",
    "expire_at": "Срок действия",
    "discount_code": "Код скидки",
    "discount_percent": "Скидка",
    "discount_limit": "Лимит скидки",
    "max_count": "Максимальное количество",
    "used_count": "Использовал",
    "start_date": "Дата начала",
    "end_date": "Дата окончания",
    "total_discount_amount": "Всего скидок",
    "initial_charge": "Первоначальный заряд",
    "total_count": "Общее количество",
    "amount_paid": "Выплаченная сумма",
    "name": "Имя",
    "published": "Опубликовано",
    "visits": "Посещения",
    "color": "Цвет",
    "landing_page": "Целевая страница",
    "enable": "Давать возможность",
    "fix_commission": "Фиксированная комиссия",
    "percent_commission": "Процентная комиссия",
    "payment_at": "Дата платежа",
    "issued_at": "Дата выпуска",
    "payment": "Оплата",
    "website": "Интернет сайт",
    "email": "Эл. адрес",
    "user": "Пользователь",
    "code": "Код",
    "schedule_at": "Дата расписания",
    "sender": "Отправитель",
    "in_que": "В очереди",
    "sent": "Отправлено",
    "shop": "Магазин",
    "quantity": "Количество",
    "amount": "Количество",
    "jobs": "количество рабочих мест",
    "success": "Количество успехов",
    "fail": "Счетчик ошибок",
    "distance": "Расстояние",
    "duration": "Продолжительность",
    "reset_at": "Сбросить дату",
    "delivery_person": "Человек",
    "delivery_service": "Услуга",
    "date": "Дата",
    "order": "порядок",
    "order_id": "номер заказа",
    "status": "Статус",
    "price": "цена",
    "count": "Считать",
    "final_price": "Окончательная цена",
    "charge": "Заряд",
    "mention": "Упомянуть",
    "officer": "Офицер",
    "registered": "Зарегистрировано",
    "purchased": "Куплено",
    "sex": "Пол"
  },
  "search_box": {
    "result": "Результаты поиска",
    "tips": "Поиск продуктов и категорий",
    "label": "Поиск ...",
    "category": "Категория"
  },
  "lead_status": {
    "physical_fast_delivery": "Мгновенная доставка",
    "physical_under_24h_delivery": "Доставить в течение следующих {lead} часов",
    "physical_over_24h_delivery": "Подготовка и отправка со следующих {days} дн.",
    "virtual_fast_prepare": "Мгновенная доставка",
    "virtual_under_24h": "Будет сделано в течение следующих {lead} часов",
    "virtual_over_24h": "Будет сделано в ближайшие {days} дн."
  },
  "return_request_state": {
    "pending": "В ожидании",
    "accepted": "Подтвержденный",
    "rejected": "Отклоненный"
  },
  "return_order_reason": {
    "physical": {
      "U1": "Несоответствие продукта",
      "U2": "Нет товара в транспортировочной упаковке",
      "U3": "Повреждение упаковки или продукта",
      "U4": "Фальсификация упаковки или серийного номера",
      "U5": "Некоторые предметы из посылки отсутствуют",
      "U6": "Товар не оригинальный",
      "U7": "Товар не соответствует заявленным характеристикам"
    }
  },
  "image_uploader": {
    "label": "Перетащите или <u>выберите файл</u>",
    "max_size": "Максимально допустимый размер: {size}"
  },
  "timespan": {
    "Morning": "с 8:00 до 12:00",
    "Evening": "с 12:00 до 18:00",
    "Night": "18:00-12:00",
    "Instant": "Мгновенная публикация"
  },
  "week_day": {
    "Saturday": "Суббота",
    "Sunday": "Воскресенье",
    "Monday": "Понедельник",
    "Tuesday": "Вторник",
    "Wednesday": "Среда",
    "Thursday": "Четверг",
    "Friday": "Пятница"
  },
  "payment_form": {
    "title": "Выберите способ оплаты",
    "gift_cards_input": "Подарочные карты",
    "gift_cards_input_empty": "Подарочные карты не найдены..",
    "more": "Другой",
    "pay_amount_by_gift_cards": "Платежная карта",
    "select_payment_method": "Выберите способ оплаты из следующих вариантов.",
    "payment_amount_remained": "Оставшаяся сумма платежа",
    "payment_amount": "Выплаченная сумма",
    "all_paid_by_gift_cards": "Поздравляем, вам не нужно платить за этот заказ. Нажмите кнопку «Оплатить подарочной картой».",
    "pay_by_gift_cards_action": "Оплатите заказ банковской картой",
    "order_free_payment": "Поздравляем, ваш заказ бесплатный!",
    "order_free_payment_action": "Заказать бесплатно сейчас",
    "qr": {
      "address": "Платежный адрес",
      "amount": "Количество"
    }
  },
  "discount_input": {
    "limit": "Скидка {percent}% до {limit} {currency}",
    "action": "Добавить код скидки",
    "code_input": "Код скидки",
    "notifications": {
      "add_success": "Поздравляем, действующий код скидки."
    }
  },
  "gift_card": {
    "inactive": "Карта отключена",
    "expire": "Срок действия",
    "transfer": "Передача",
    "send_to_friend": "Отправить другу"
  },
  "count_down": {
    "days": "День",
    "hours": "Час",
    "minutes": "Минуты",
    "seconds": "Секунды"
  },
  "gift_status": {
    "Unpaid": "Ожидание получения",
    "Paid": "Оплаченный",
    "Rejected": "Отклоненный",
    "Canceled": "Отменено"
  },
  "gift_program_status": {
    "Airdrop": "Платежная система",
    "Advertising": "Реклама",
    "PersonalGift": "Личный подарок",
    "ShopGift": "Магазин подарков"
  },
  "currency_selector": {
    "label": "Валюта"
  },
  "need_login": {
    "title": "Авторизоваться",
    "login_sms": "СМС вход",
    "login_google": "Войти через Google",
    "login_facebook": "Войти с Facebook",
    "login_account": "Войти через Selldone",
    "register": "Новый пользователь? Зарегистрируйтесь сейчас.",
    "mobile_input": "Введите свой мобильный",
    "verification_code": "Проверочный код",
    "msg_title": "Привет,",
    "msg_body": "Пожалуйста, войдите. Это занимает всего несколько секунд.",
    "login_apple": "Войти через Apple"
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "5-летний золотой магазин"
    },
    "GOLDEN_2YEAR": {
      "name": "4-летний золотой магазин"
    },
    "GOLDEN_3YEAR": {
      "name": "3-летний золотой магазин"
    },
    "GOLDEN_4YEAR": {
      "name": "2-летний золотой магазин"
    },
    "GOLDEN_5YEAR": {
      "name": "Золотой магазин на 1 год"
    },
    "TOKEN_OWNER_1M": {
      "name": "Золотой инвестор"
    },
    "TOKEN_OWNER_10M": {
      "name": "Алмазный инвестор"
    },
    "TOKEN_OWNER_100M": {
      "name": "Рубиновый инвестор"
    },
    "COMMUNITY_LOYAL": {
      "name": "Член Высшего сообщества коммуникационных сетей"
    },
    "GOLD_SUPPLIER": {
      "name": "Поставщик золота"
    },
    "GOLD_SELLER": {
      "name": "Золотой дилер"
    },
    "CONTENT_SUPERMAN": {
      "name": "Лучший производитель контента"
    },
    "NINJA": {
      "name": "Ниндзя"
    },
    "STAR": {
      "name": "Звезда"
    },
    "GUARDIAN": {
      "name": "Отличное обслуживание клиентов"
    },
    "KING": {
      "name": "Король рынка"
    }
  },
  "cookie": {
    "title": "Этот веб-сайт использует файлы cookie",
    "message": "Этот веб-сайт использует файлы cookie для улучшения взаимодействия с пользователем. Используя наш веб-сайт, вы соглашаетесь на все файлы cookie в соответствии с нашей Политикой использования файлов cookie.",
    "preferences_action": "Управление настройками",
    "agree_action": "Я согласен"
  },
  "basket_item_message": {
    "title": "Необходимая информация для этого элемента",
    "save_actions": "Сохранить сообщение",
    "notifications": {
      "success": "Ваши входные данные сохранены."
    }
  },
  "faq": {
    "faq": "Часто задаваемые вопросы",
    "title": "Вопросы и ответы",
    "sub_title": "То, что вы просили нас сделать.",
    "message": "Найдите ответ на свой вопрос среди ответов ниже. Спросите нас, если вопросы остались без ответа.",
    "add_question_action": "Задать новый вопрос",
    "read_more": "Прочитайте больше ..",
    "load_more": "Больше вопросов ..",
    "main_page": "Часто задаваемые вопросы Главная страница",
    "add_new": "Отправить новый вопрос",
    "login_alert": "Войдите, чтобы задать вопрос.",
    "question_input": "Вопрос",
    "question_input_placeholder": "Задавай вопрос.",
    "notifications": {
      "success_add": "Ваш вопрос успешно отправлен."
    }
  },
  "rating_labels": [
    "Очень плохой",
    "Плохой",
    "Нормальный",
    "Хорошо",
    "Превосходно"
  ],
  "map_view": {
    "address_detail": "Подробности адреса",
    "change": "Сдача",
    "select": "Выбирать",
    "not_found_address": "Значение не найдено",
    "enter_address_hint": "Введите адрес назначения",
    "enter_your_address": "Введите свой адрес.",
    "postal_code": "Почтовый индекс",
    "phone_input": "Телефон {type}",
    "building_number": "Номер здания",
    "building_unit": "Ед. изм",
    "full_name_input": "Полное имя {type}",
    "save_detail_action": "Сохранить детали",
    "more_detail_input": "Подробнее описание",
    "add_address_to_list": "Добавить адрес в список",
    "address_title_input": "Адресная метка (требуется)",
    "notifications": {
      "save_in_list": "Этот адрес был сохранен в вашем списке со всеми его деталями.",
      "edit_success": "Новые значения адреса сохранены в {title}."
    },
    "delete_address_dialog": {
      "title": "Удалить адрес",
      "message": "Вы уверены, что хотите удалить этот адрес?",
      "action": "Удалить адрес"
    }
  },
  "comment_manager": {
    "can_not_edit": "Не могу редактировать этот комментарий!",
    "comment_input_empty": "Текст сообщения пуст!",
    "article_not_saved": "Сохраните статью!"
  },
  "wheel_fortune": {
    "title": "Играй и выигрывай",
    "message": "Стоимость каждой игры составляет 10 фишек. В настоящее время у вас есть чип {chips}. Получите больше фишек, купив в магазине.",
    "win_message": "Поздравляем, Вы выиграли!",
    "lost_message": "Извините, вы проиграли игру.",
    "try_again": "Вы можете попробовать еще раз"
  },
  "json": {
    "add": "Добавить данные структуры",
    "add_message": "Создать новые данные структуры",
    "structures": "Структуры",
    "book": {
      "title": "Книга",
      "desc": "Действия с книгами, которые позволяют пользователям покупать книги, которые они находят непосредственно в результатах поиска."
    },
    "occupation": {
      "title": "Расчетная зарплата",
      "desc": "Информация об оценке заработной платы, например диапазоны окладов и средние оклады по регионам для типов вакансий, отображаемая в процессе поиска вакансий в Google."
    },
    "course": {
      "title": "Курс",
      "desc": "Образовательные курсы, которые отображаются в списке конкретного поставщика. Курсы могут включать название курса, поставщика и краткое описание."
    },
    "howto": {
      "title": "Как",
      "desc": "С практическими рекомендациями пользователи проходят ряд шагов для успешного выполнения задачи, включая видео, изображения и текст."
    },
    "recipe": {
      "title": "Рецепт блюда",
      "desc": "Рецепты, которые отображаются как отдельный расширенный результат или часть основной карусели."
    }
  },
  "support": {
    "Financial": "финансовый",
    "Technical": "Технические",
    "Advisor": "Советник"
  },
  "condition": {
    "new": "Новый",
    "refurbished": "Отремонтированный",
    "used": "Использовал",
    "used_fair": "Подержанная ярмарка",
    "used_good": "Используется хорошо",
    "used_like_new": "Используется - Как новый"
  },
  "variant_filter": {
    "title": "Фильтр вариантов продукта",
    "only_available": "В наличии"
  },
  "service": {
    "task": {
      "title": "Задачи",
      "message": "Список задач, выполняемых в этом сервисе."
    },
    "appointment": {
      "title": "Встреча",
      "message": "Выберите время недели из следующих вариантов в зависимости от дня и часа, который подходит именно вам."
    },
    "booking": {
      "title": "Бронирование",
      "message": "Укажите период времени дней, которые вы хотите сделать бронирование в календаре ниже."
    },
    "subscription": {
      "title": "Подписка"
    },
    "charge": {
      "title": "Заряд"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "Фиксированные цены",
      "message": "В этом типе ценообразования цена продукта является фиксированной суммой, и покупателю не нужно запрашивать расчет цены."
    },
    "ESTIMATION": {
      "title": "Оценка",
      "message": "Цена товаров и услуг будет в некоторой степени рассчитываться продавцом при оформлении заказа, платежные счета могут быть изменены или добавлены в процессе обслуживания."
    },
    "AGREEMENT": {
      "title": "Соглашение",
      "message": "Окончательная цена товаров или услуг не будет изменена продавцом после размещения заказа."
    },
    "BID": {
      "title": "Ставка/аукцион",
      "message": "Товар будет продан по самой высокой цене, предложенной потенциальными покупателями."
    }
  },
  "map": {
    "title": "Место получения продукции",
    "confirm": "Установить местоположение",
    "address": "Пункт назначения",
    "receptor": "Получатель"
  },
  "ShopBots": {
    "telegram": "Телеграмма"
  },
  "article_tags": {
    "title": "Теги контента",
    "tags_input": "Теги",
    "tags_input_message": "Теги Список этой статьи",
    "notification": {
      "add_success": "Теги добавлены"
    }
  },
  "difficulties": {
    "very_complicated": "Очень сложный",
    "hard": "Жесткий",
    "intermediate": "Средний",
    "easy": "Легкий"
  }
};