export default {
  "currency_default": "USD",
  "language_default": "en",
  "selldone": "විකුණුවා",
  "store": "ගබඩා",
  "not_exist": "නොපවතියි",
  "error": "දෝෂයකි",
  "active": "ක්රියාකාරී",
  "inactive": "අක්රිය",
  "required_value": "අවශ්ය අගයන්",
  "original_warranty": "මුල් නිෂ්පාදන සහතිකය",
  "return_warranty_days": "{days} ආපසු පැමිණීමේ සහතික දින(ය)",
  "no_return_warranty": "ආපසු නැත",
  "reed_agree_terms": "මම භාවිත නියමයන් සහ පෞද්ගලිකත්ව ප්‍රතිපත්ති කියවා ඒවාට එකඟ වෙමි.",
  "commons": {
    "Currency": "මුදල්",
    "COD": "COD",
    "State": "රජයේ",
    "Price": "මිල",
    "order_price": "ඇණවුම් මුදල",
    "VAT": "VAT",
    "Discount": "වට්ටම්",
    "In_Stock": "ගබඩාවේ ඇත",
    "Variants": "ප්රභේද",
    "No_variants": "ප්‍රභේදයක් නැත",
    "all": "සෑම",
    "today": "අද",
    "yesterday": "ඊයේ",
    "license": "බලපත්රය",
    "home": "නිවස",
    "support": "සහාය",
    "messages": "පණිවිඩ",
    "no_message": "පණිවිඩයක් නැත",
    "empty": "හිස්",
    "phone": "දුරකථන",
    "address": "ලිපිනය",
    "name": "නම",
    "password": "මුරපදය",
    "email": "විද්යුත් තැපෑල",
    "mobile": "ජංගම",
    "login": "ඇතුල් වන්න",
    "register": "ලියාපදිංචි කරන්න",
    "select_account": "ගිණුම තෝරන්න",
    "online": "ඔන්ලයින්",
    "offline": "නොබැඳි",
    "finish": "අවසන් කරන්න",
    "finished": "අවසන්",
    "preview": "පෙරදසුන",
    "free": "නිදහස්",
    "free_completely": "සම්පුර්ණයෙන්ම නොමිලේ දායකත්වය",
    "fee": "ගාස්තු",
    "month": "මාසික",
    "months": "මාස",
    "faq": "නිතර අසන ප්රශ්න",
    "question": "ප්රශ්නය",
    "answer": "පිළිතුර",
    "create_date": "දිනය සාදන්න",
    "update_date": "යාවත්කාලීන දිනය",
    "start_date": "ආරම්භක දිනය",
    "end_date": "අවසාන දිනය",
    "social": "සමාජ",
    "total": "සමස්ත",
    "orders": "නියෝග",
    "sessions": "සැසිවාර",
    "product_views": "නිෂ්පාදන දර්ශන",
    "add_to_carts": "කරත්ත වලට එකතු කරන්න",
    "checkouts": "පරීක්ෂාකාරී වන්න",
    "payments": "ගෙවීම",
    "organic_search": "කාබනික සෙවීම",
    "other": "වෙනත්",
    "landing_page": "ගොඩබෑමේ පිටුව",
    "discount_code": "වට්ටම් කේතය",
    "total_sell": "මුළු විකුණුම්",
    "details": "විස්තර",
    "currency": "මුදල්",
    "amount": "ප්රමාණය",
    "published": "ප්‍රකාශිතයි",
    "draft": "කෙටුම්පත",
    "save_changes": "වෙනස්කම් සුරකින්න",
    "source": "මූලාශ්රය",
    "medium": "මධ්යම",
    "url": "Url",
    "revenue": "ආදායම",
    "performance": "කාර්ය සාධනය",
    "term": "වාරය",
    "content": "අන්තර්ගතය",
    "session": "වාරය",
    "product": "නිෂ්පාදන",
    "add": "එකතු කරන්න",
    "checkout": "පරීක්ෂාකාරී වන්න",
    "payment": "ගෙවීම",
    "more_options": "තවත් විකල්පයන්",
    "full_name": "සම්පූර්ණ නම",
    "tel": "දුරකථන",
    "about_me": "මා ගැන",
    "request_checking": "පරීක්ෂා කිරීම ඉල්ලන්න",
    "passport": "ගමන් බලපත්ර",
    "birthday": "උපන් දිනය",
    "country": "රට",
    "city": "නගරය",
    "gender": "ස්ත්රී පුරුෂ භාවය",
    "offer": "පිරිනැමීම",
    "website": "වෙබ් අඩවිය",
    "apply_for_all_products": "∞ සියලුම නිෂ්පාදන සඳහා අයදුම් කරන්න",
    "fix_commission": "ස්ථාවර කොමිස්",
    "percent_commission": "ප්‍රතිශත කොමිස්",
    "fixed_discount": "ස්ථාවර වට්ටමක්",
    "discount_percentage": "ප්‍රතිශත වට්ටමක්",
    "discount_limit": "වට්ටම් සීමාව",
    "no_code": "කේතයක් නැත",
    "max_count": "උපරිම ගණන",
    "count_unit": "අයිතම",
    "used": "පාවිච්චි කළා",
    "daily": "දිනපතා",
    "monthly": "මාසික",
    "yearly": "වාර්ෂිකව",
    "state": "තත්ත්වය",
    "disable": "අක්රිය කරන්න",
    "enable": "සබල කරන්න",
    "activation_code": "සක්රිය කිරීමේ කේතය",
    "quantity": "ප්රමාණය",
    "no_club": "සමාජයක් නැත",
    "per_order": "ඇණවුම අනුව",
    "count": "ගණන් කරන්න",
    "seconds": "තත්පර",
    "auto": "ඔටෝ",
    "title": "ශීර්ෂය",
    "message": "පණිවුඩය",
    "width": "පළල",
    "length": "දිග",
    "height": "උස",
    "label": "ලේබලය",
    "click": "ක්ලික් කරන්න",
    "bank": "බැංකුව",
    "default": "පෙරනිමිය",
    "role": "කාර්යභාරය",
    "user": "පරිශීලක",
    "users": "පරිශීලකයන්",
    "code": "කේතය",
    "total_payment": "සම්පූර්ණ ගෙවීම",
    "balance": "ශේෂය",
    "chance": "අවස්ථාවක්",
    "free_for_new_users": "නව පරිශීලකයින් සඳහා නොමිලේ",
    "prize_amount": "ත්‍යාග මුදල",
    "win": "දිනන්න",
    "gift_card": "තෑගි කාඩ්පත",
    "discount": "වට්ටම්",
    "config": "වින්යාසය",
    "prize": "ත්‍යාගය",
    "Prizes": "ත්‍යාග",
    "result": "ප්රතිඵලය",
    "price": "මිල",
    "lottery": "ලොතරැයිය",
    "coupon": "කූපනය",
    "customer_club": "පාරිභෝගික සමාජය",
    "shipping": "නාවික",
    "sum": "එකතුව",
    "not_paid": "නොගෙවූ",
    "category": "වර්ගය",
    "done": "කළා",
    "email_from": "සිට",
    "subject": "විෂය",
    "schedule": "කාලසටහන",
    "files_list": "ගොනු ලැයිස්තුව",
    "file_max_size": "උපරිම ගොනු විශාලත්වය",
    "value": "වටිනාකම",
    "help": "උදව්",
    "shipping_tax": "නැව් බදු",
    "net_price": "ශුද්ධ මිල",
    "tax": "බද්ද",
    "tax_included": "මිලෙහි ඇතුළත් වේ",
    "limit": "සීමාව",
    "min_purchase": "අවම මිලදී ගැනීම",
    "eligible_for": "සඳහා සුදුසුකම්",
    "only_for_first_buy": "පළමු මිලදී ගැනීම සඳහා පමණි",
    "one_time_use": "එක් වරක් භාවිතා කළ හැකිය",
    "period_of_qualify": "කාල පරිහරණ සීමාව",
    "no_constraint": "සීමාවක් නැත",
    "timespan": "කාල සීමාව",
    "days": "දින)",
    "weight": "බර",
    "distance": "දුර",
    "last_status": "අවසාන තත්ත්වය",
    "issued_at": "දී නිකුත් කර ඇත",
    "order": "නියෝග",
    "order_detail": "ඇණවුම් විස්තර",
    "percent": "සියයට",
    "applied_count": "යෙදූ ගණන",
    "campaign": "ව්‍යාපාරය",
    "os": "මෙහෙයුම් පද්ධතිය",
    "browser": "බ්රවුසරය",
    "device": "උපාංගය",
    "device_ip": "උපාංග IP ලිපිනය",
    "location": "ස්ථානය",
    "user_agent": "පරිශීලක නියෝජිතයා",
    "affiliate": "අනුබද්ධ",
    "timeline": "කාලරේඛාව",
    "add_note": "සටහනක් එක් කරන්න",
    "record": "වාර්තාව",
    "unlimited": "අසීමිතයි",
    "show_coupons": "කූපන් පත් පෙන්වන්න",
    "hide_coupons": "කූපන් පත් සඟවන්න",
    "service_area": "සේවා ප්රදේශය",
    "apps": "යෙදුම්",
    "plugins": "ප්ලගීන",
    "bots": "බොට්ස්",
    "categories": "වර්ග",
    "products": "නිෂ්පාදන",
    "business": "ව්යාපාරික",
    "personal": "පුද්ගලික",
    "size": "ප්රමාණය",
    "holiday": "නිවාඩු",
    "sod": "භාරදීමේදී ගෙවන්න",
    "cod": "බෙදාහැරීමේ මුදල්",
    "free_shipping": "ගාස්තු රහිත නැව්ගත කිරීම",
    "hours": "පැය",
    "send_date": "නැව්ගත කරන දිනය",
    "deliver_date": "බෙදාහැරීමේ දිනය",
    "return_date": "ආපසු පැමිණීමේ දිනය",
    "pending": "පොරොත්තුවෙන්",
    "delivered": "භාර දුන්නා",
    "returned": "ආපසු ආවා",
    "canceled": "අවලංගු කළා",
    "shipping_cost": "නැව්ගත කිරීමේ පිරිවැය",
    "action": "කටයුතු",
    "cancel_date": "දිනය අවලංගු කරන්න",
    "deliver_in_process": "ඇණවුම එවා ඇත..",
    "kind": "ටයිප් කරන්න",
    "detail": "විස්තර",
    "map": "සිතියම",
    "actions": "ක්රියාවන්",
    "navigation": "සංචලනය",
    "navigation_app": "අයදුම්පත",
    "payment_date": "ගෙවීම් දිනය",
    "duration": "කාල සීමාව",
    "bill": "බිල්පත්",
    "delivery_persons": "කූරියර්ස්",
    "delivery_services": "බෙදාහැරීමේ සේවා",
    "live_view": "සජීවී දසුන",
    "cart": "කරත්තය",
    "priority": "ප්රමුඛත්වය",
    "sufficient_credit": "ප්රමාණවත් ණය",
    "max_package_size": "උපරිම පැකේජ ප්රමාණය",
    "delay": "ප්රමාදය",
    "credit": "ණය",
    "livemode": "සජීවි",
    "paused": "විරාම කළා",
    "debug": "දෝෂහරණය කරන්න",
    "token": "ටෝකනය",
    "status": "තත්ත්වය",
    "courier": "කුරියර්",
    "track": "ලුහුබැඳීම",
    "track_order": "ඇණවුම් ලුහුබැඳීම",
    "cost": "පිරිවැය",
    "receipt": "රිසිට්පත",
    "origin": "සම්භවය",
    "destination": "ගමනාන්තය",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "ප්රමාණවත් තොගයක් නැත!",
    "sub_total": "උප එකතුව",
    "customer": "පාරිභෝගික",
    "delivery": "භාරදීම",
    "online_orders": "මාර්ගගත ඇණවුම්",
    "pos_orders": "POS ඇණවුම්",
    "chips": "චිප්ස්",
    "subscribed": "දායක විය",
    "unsubscribed": "දායක නොවීය",
    "last_login": "අවසන් පිවිසුම",
    "join_at": "එක්වන දිනය",
    "club": "සමාජය",
    "buyer": "ගැනුම්කරු",
    "seller": "විකුණුම්කරු",
    "or": "හෝ",
    "type": "ටයිප් කරන්න",
    "condition": "තත්ත්වය",
    "brand": "වෙළඳ නාමය",
    "attempt": "උත්සාහය",
    "error": "දෝෂයකි",
    "success": "සාර්ථකත්වය",
    "fail": "අසාර්ථකයි",
    "inventory": "ඉන්වෙන්ටරි",
    "link": "සබැඳිය",
    "visits": "සංචාරයන්",
    "transactions": "ගනුදෙනු",
    "vat": "VAT",
    "pos_vat": "POS වැට්",
    "sort_by": "අනුව තෝරන්න..",
    "from": "සිට",
    "from_lead_time": "ඉදිරි පැය {hours} ඇතුළත",
    "no_credit_card_info": "කාඩ්පත් තොරතුරු නැත!",
    "active": "ක්රියාකාරී",
    "not_active": "සක්රිය කර නැත!",
    "referrals": "යොමු කිරීම්",
    "dashboard": "උපකරණ පුවරුව",
    "more": "තව",
    "inactive": "අක්රිය",
    "developer": "සංවර්ධකයා",
    "setting": "සැකසීම",
    "membership_conditions": "සාමාජික කොන්දේසි",
    "customers": "පාරිභෝගිකයන්",
    "created_at": "සාදන ලද දිනය",
    "updated_at": "අවසාන යාවත්කාලීන කිරීම",
    "register_at": "ලියාපදිංචි දිනය",
    "old": "පැරණි",
    "new": "අලුත්",
    "start": "ආරම්භ කරන්න",
    "end": "අවසානය",
    "pos": "POS",
    "out_of_stock": "තොග නැති",
    "fake": "ව්යාජ",
    "low_inventory_warning": "අවධානය, අඩු ඉන්වෙන්ටරි!",
    "webhook": "වෙබ්හුක්",
    "notification": "දැනුම්දීම",
    "sms": "SMS",
    "online_payment_link": "මාර්ගගත ගෙවීම් සබැඳිය",
    "waiting_load_data": "දත්ත පූරණය කිරීමට රැඳී සිටිමින්..",
    "views": "දසුන්",
    "sales": "විකුණුම්",
    "total_views": "මුළු දසුන්",
    "total_sales": "මුළු විකුණුම්",
    "from_previous_n_days": "පසුගිය දින {days} සිට",
    "drop_shipping": "dropshipping",
    "commission": "කොමිසම",
    "shipping_area": "නැව්ගත කිරීමේ ප්රදේශය",
    "main_seller": "ප්රධාන විකුණුම්කරු",
    "domain": "වසම්",
    "contact": "සම්බන්ධතා තොරතුරු",
    "wallet": "පසුම්බිය",
    "reseller": "නැවත විකුණුම්කරු",
    "tracking_code": "ලුහුබැඳීමේ කේතය",
    "tracking_url": "ලුහුබැඳීමේ URL",
    "fulfillments": "ඉටුකිරීම්",
    "reject": "ප්රතික්ෂේප කරන්න",
    "reserved": "වෙන්කර ඇත",
    "score": "ලකුණු",
    "customer_price": "පාරිභෝගික මිල",
    "options": "විකල්ප",
    "show_details": "විස්තර පෙන්වන්න",
    "no_data": "දත්ත නැත..",
    "waiting": "බලාගෙන ඉන්නවා...",
    "waiting_connecting_payment": "ගෙවීම් සේවාව සඳහා රැඳී සිටිමින්...",
    "creating_secure_payment": "ආරක්ෂිත ගෙවීමක් නිර්මාණය කිරීම.",
    "officer": "නිලධාරී",
    "ticket": "ටිකට්",
    "ticket_url": "ටිකට් url",
    "closed_at": "දී වසා ඇත",
    "close_ticket": "ටිකට් වසන්න",
    "reopen_ticket": "ටිකට් නැවත විවෘත කරන්න",
    "require": "අවශ්ය*",
    "search": "සෙවීම...",
    "language": "භාෂාව",
    "tasks": "කාර්යයන්",
    "permissions": "අවසර",
    "finish_date": "අවසාන දිනය",
    "complete_date": "නිම කිරීමේ දිනය",
    "settle_date": "බේරුම්කරණ දිනය",
    "cost_span": "මිල පරාසය",
    "industry": "කර්මාන්ත",
    "rating": "ශ්රේණිගත කිරීම්",
    "rates": "ශ්රේණිගත කිරීම",
    "seen_at": "දී දැක ඇත",
    "completed": "සම්පූර්ණ කළා",
    "you": "ඔබට",
    "shop": "සාප්පු යන්න",
    "store": "ගබඩා",
    "granted": "ලබා දුන්නා",
    "deny": "ප්රතික්ෂේප කරන්න",
    "request": "ඉල්ලීම",
    "expert": "විශේෂඥ",
    "response": "ප්රතිචාරය",
    "requests": "ඉල්ලීම්",
    "experts": "විශේෂඥයන්",
    "responses": "ප්‍රතිචාර",
    "negotiations": "සාකච්ඡා",
    "all_chats": "සියලුම කතාබස්",
    "chats": "කතාබස්",
    "tags": "ටැග්",
    "description": "විස්තර",
    "rates_count": "ශ්රේණිගත කිරීම් සංඛ්යාව",
    "rate": "ශ්රේණිගත කිරීම",
    "comment": "අදහස් දක්වන්න",
    "chat": "කතාබස් කරන්න",
    "install": "ස්ථාපනය කරන්න",
    "edited": "සංස්කරණය කළා",
    "undo": "අහෝසි කරන්න",
    "redo": "නැවත කරන්න",
    "male": "පිරිමි",
    "female": "ගැහැණු",
    "calculator": "කැල්කියුලේටරය",
    "catalog": "නාමාවලිය",
    "max_height": "උපරිම උස",
    "images_compare": "රූප සංසන්දනය",
    "canvas": "කැන්වස්",
    "table_of_contents": "අන්තර්ගත වගුව",
    "comments": "අදහස්",
    "badge_codes": "ලාංඡන කේතය",
    "need_more": "තව ඕනේ?",
    "invite_glow_caption": "සෑම මිතුරෙකුටම ඩොලර් 14.9 ක් ලබා ගන්න!",
    "register_free": "100% නොමිලේ ලියාපදිංචිය",
    "gift": "තෑගි",
    "google": "ගූගල්",
    "facebook": "ෆේස්බුක්",
    "instagram": "Instagram",
    "instashop": "Instashop",
    "show": "පෙන්වන්න",
    "hide": "සඟවන්න",
    "waiting_review": "සමාලෝචනය බලාපොරොත්තුවෙන්",
    "not_selected": "තෝරාගෙන නැත",
    "time": "වේලාව",
    "final_price": "අවසාන මිල",
    "starting_price": "ආරම්භක මිල",
    "day": "දිනය",
    "paid": "ගෙවා ඇත",
    "service_bill": "ඉන්වොයිස් ගෙවීම",
    "avocado": "අලිගැටපේර",
    "delivery_price": "නැව්ගත කිරීමේ පිරිවැය",
    "select_address": "ලිපිනය තෝරන්න",
    "image": "රූප",
    "view": "දැක්ම",
    "sell": "විකිණීමට",
    "hyper": "අධි",
    "cart_list": "කරත්තය",
    "barcode_scanner": "තීරු කේත ස්කෑනරය",
    "scan_qr_code": "QR කේතය පරිලෝකනය කරන්න",
    "new_carts": "අලුත් කරත්ත",
    "pays": "ගෙවීම",
    "annually": "වාර්ෂිකව",
    "sells": "විකුණුම්",
    "articles": "ලිපි",
    "jobs": "රැකියා",
    "job": "රැකියා",
    "blog": "බ්ලොග්",
    "deleted_at": "දී මකා දමන ලදී",
    "capacity": "ධාරිතාව",
    "download_at": "අවසන් බාගත දිනය",
    "downloads": "බාගත කිරීම්",
    "usage": "භාවිතය",
    "select_upload_file": "ගොනුව තෝරන්න හෝ අතහැර දමන්න",
    "download_link": "බාගත කිරීමේ සබැඳිය",
    "uploading": "උඩුගත කරමින්..",
    "files": "ගොනු",
    "star": "තරුව",
    "speed": "වේගය",
    "feedback": "ප්රතිපෝෂණ",
    "new_messages": "නව පණිවිඩ",
    "file": "ගොනුව",
    "attachment": "ඇමුණුම",
    "gallery": "ගැලරිය",
    "sync": "සමමුහුර්ත කරන්න",
    "diff_time": "කාල වෙනස",
    "network": "ජාල",
    "account": "ගිණුම",
    "configuration": "මානකරනය",
    "blockchain": "බ්ලොක්චේන්",
    "blog_link": "බ්ලොග් සබැඳිය",
    "community": "ප්රජාව",
    "critical_zone": "විවේචනාත්මක කලාපය",
    "statistics": "සංඛ්යා ලේඛන",
    "access": "ප්රවේශ",
    "seo": "SEO",
    "followers": "අනුගාමිකයින්",
    "followings": "පහත සඳහන්",
    "private": "පෙරදසුන",
    "soon": "ඉක්මනින්",
    "features": "විශේෂාංග",
    "bot": "බොට්",
    "sample": "නියැදිය",
    "how_it_work": "එය ක්රියා කරන්නේ කෙසේද?",
    "page": "පිටුව",
    "congratulations": "සුභ පැතුම්",
    "recommend": "නිර්දේශ කරන්න",
    "recommended": "නිර්දේශ කර ඇත",
    "recoms": "නිර්දේශ",
    "likes": "කැමති",
    "clicks": "ක්ලික් කිරීම්",
    "platform": "වේදිකාව",
    "cms": "CMS",
    "cash": "මුදල්",
    "dir_payment": "බැංකු මාරු කිරීම",
    "auto_complete": "ස්වයංක්‍රීයව සම්පූර්ණයි",
    "compare": "සසඳන්න",
    "infinite": "අනන්තයි",
    "tips": "ඉඟි",
    "technical": "කාර්මික",
    "finance": "මූල්ය",
    "your_phone_input": "දුරකථන අංකයක් ඇතුළත් කරන්න",
    "income": "ආදායම්",
    "change": "වෙනස් කරන්න",
    "new_users": "නව පරිශීලකයන්",
    "success_orders": "සාර්ථක ඇණවුම්",
    "direct": "සෘජු",
    "last_activity": "අවසාන ක්‍රියාකාරකම",
    "landing": "ගොඩබෑම",
    "now": "දැන්",
    "accept_agreement": "මම කොන්දේසි කියවා පිළිගෙන ඇත.",
    "report": "වාර්තාව",
    "tablet": "ටැබ්ලට්",
    "pc": "PC",
    "acquisition_channel": "අත්පත් කර ගැනීමේ නාලිකාව",
    "to": "දක්වා",
    "info": "තොරතුරු",
    "general": "පොදු",
    "upload": "උඩුගත කරන්න",
    "general_config": "සාමාන්ය වින්යාසය",
    "limits_config": "සීමාවන්",
    "design_config": "නිර්මාණය සහ විලාසය",
    "duration_config": "කාල සීමාව",
    "constraints_config": "සුදුසුකම් සීමාවන්",
    "clubs_config": "සමාජශාලා වල ඇත",
    "additional_config": "අතිරේක සැකසුම්",
    "import": "ආනයන",
    "ribbon": "රිබන්",
    "countries": "රටවල්",
    "edit": "සංස්කරණය කරන්න",
    "delete": "මකන්න",
    "analytics": "විශ්ලේෂණ",
    "rules": "නීති",
    "unset": "සකසා නැත",
    "carts": "කරත්ත",
    "optional": "විකල්ප",
    "design": "නිර්මාණ",
    "filter": "පෙරහන",
    "send": "යවන්න",
    "approved": "අනුමත කළා",
    "unit": "ඒකකය",
    "profile": "පැතිකඩ",
    "shipping_rates": "නැව් ගාස්තු",
    "package": "පැකේජය",
    "overview": "දළ විශ්ලේෂණය",
    "live": "සජීවි",
    "never": "කවදාවත් නැහැ",
    "always": "සැමවිටම",
    "mandatory": "අනිවාර්යයි",
    "expire_at": "කල්පිරෙන දිනය",
    "position": "තනතුර",
    "channel": "නාලිකාව",
    "age": "වයස",
    "charge": "අයකිරීම",
    "giftcard": "තෑගි කාඩ්පත",
    "acquisition": "අත්පත් කර ගැනීම",
    "conversion": "පරිවර්තනය",
    "total_payments": "මුළු ගෙවීම්",
    "community_ask": "ප්රජාව තුළ අසන්න",
    "children": "ළමා",
    "export": "අපනයන",
    "list": "ලැයිස්තුව",
    "hierarchy": "ධුරාවලිය",
    "images": "රූප",
    "demo": "Demo",
    "author": "කර්තෘ",
    "designer": "නිර්මාණකරු",
    "max": "උපරිම",
    "accepted": "පිළිගත්තා",
    "reply": "පිලිතුරු",
    "reviewed": "සමාලෝචනය කරන ලදී",
    "restored": "ප්‍රතිෂ්ඨාපනය කළා",
    "merchant": "වෙළෙන්දා",
    "per_product": "නිෂ්පාදනයක් අනුව",
    "journey": "ගමන",
    "after": "පසු",
    "waiting_for_payment": "කරුණාකර ගෙවීම සම්පූර්ණ කරන්න...",
    "hour": "පැය",
    "minute": "මිනිත්තුව",
    "premium": "වාරික",
    "light": "ආලෝකය",
    "dark": "අඳුරු",
    "guest": "අමුත්තන්ගේ",
    "shops": "ගබඩා",
    "vendor": "වෙළෙන්දා",
    "vendors": "වෙළෙන්දෝ",
    "marketplace": "වෙළඳපොළ",
    "verify_date": "දිනය තහවුරු කරන්න",
    "note": "සටහන",
    "panel": "පැනලය",
    "removed": "ඉවත් කරන ලදී",
    "segments": "කොටස්",
    "personal_info": "පෞද්ගලික තොරතුරු",
    "preferences": "මනාප",
    "spec": "පිරිවිතර",
    "reviews": "සමාලෝචන",
    "constraints": "සීමා කිරීම්",
    "flexible": "නම්යශීලී",
    "usage_limit": "භාවිත සීමාව",
    "temporary": "තාවකාලික",
    "original": "මුල්",
    "saved": "සුරකින ලදී!",
    "sort": "වර්ග කරන්න",
    "documents": "ලේඛන",
    "document": "ලේඛනය",
    "please_wait": "කරුණාකර රැඳී සිටින්න...",
    "pickup": "අවුලා ගන්න",
    "customize": "අභිරුචිකරණය",
    "difficulty": "දුෂ්කරතාව",
    "banned": "තහනම් කළා",
    "company": "සමාගම",
    "tax_shipping": "නැව් බද්ද",
    "warranty": "වගකීම් සහතිකය",
    "return_policy": "ආපසු දෙන ප්රතිපත්තිය",
    "guide": "මගපෙන්වීම",
    "translate": "පරිවර්තනය කරන්න",
    "public": "මහජන",
    "deleted": "මකා දමන ලදී",
    "variant": "ප්රභේදය",
    "secure": "ආරක්ෂිතයි",
    "admin": "පරිපාලක"
  },
  "dialogs": {
    "delete": {
      "title": "මකන්න",
      "message": "ඔබට මෙම අයිතමය මැකීමට විශ්වාසද?",
      "action": "ඔව්, දැන් මකන්න"
    }
  },
  "actions": {
    "add_to_cart": "ගැලට එක් කරන්න",
    "cancel": "අවලංගු කරන්න",
    "update": "යාවත්කාලීන කරන්න",
    "add": "එකතු කරන්න",
    "delete": "මකන්න",
    "new": "අලුත්",
    "save_continue": "සුරකින්න සහ ඉදිරියට යන්න",
    "save": "සුරකින්න",
    "save_changes": "වෙනස්කම් සුරකින්න",
    "change": "වෙනස් කරන්න",
    "continue": "දිගටම කරගෙන යන්න",
    "close": "වසන්න",
    "finish": "අවසන් කරන්න",
    "poll": "මත විමසුම",
    "view": "දැක්ම",
    "edit": "සංස්කරණය කරන්න",
    "next": "ඊළඟ",
    "previous": "කලින්",
    "create": "නිර්මාණය කරන්න",
    "set": "කට්ටලය",
    "find": "සොයන්න",
    "accept": "පිළිගන්න",
    "reject": "ප්රතික්ෂේප කරන්න",
    "back": "ආපසු",
    "pay": "ගෙවන්න",
    "pay_now": "දැන් ගෙවන්න",
    "print": "මුද්‍රණය කරන්න",
    "return": "ආපසු",
    "publish": "ප්‍රකාශ කරන්න",
    "confirm": "තහවුරු කරන්න",
    "copy": "පිටපත් කරන්න",
    "submit": "ඉදිරිපත් කරන්න",
    "send": "යවන්න",
    "yes": "ඔව්",
    "no": "නැත",
    "meh": "හ්ම්",
    "clear": "පැහැදිලිව",
    "dismiss": "අස් කරන්න",
    "search": "සෙවීම",
    "deselect_all": "සියල්ල තේරීම ඉවත් කරන්න",
    "select_all": "සියල්ල තෝරන්න",
    "refresh": "නැවුම් කරන්න",
    "verify": "තහවුරු කරන්න",
    "play": "සෙල්ලම් කරන්න",
    "open": "විවෘත",
    "calculate": "ගණනය කරන්න",
    "quick_buy": "ඉක්මන් මිලදී ගැනීම",
    "click_here": "මෙහි ක්ලික් කරන්න",
    "schedule": "කාලසටහන",
    "send_now": "දැන්ම යවන්න",
    "download": "බාගත",
    "reset_default": "පෙරනිමියට යළි පිහිටුවන්න",
    "reset": "යළි පිහිටුවන්න",
    "check": "චෙක් පත",
    "cod_payment": "බෙදාහැරීමේ මුදල්",
    "dir_payment": "මුදල් මාරුව",
    "online_payment": "මාර්ගගත ගෙවීම්",
    "checkout": "පරීක්ෂාකාරී වන්න",
    "show_all": "සියල්ල පෙන්වන්න",
    "login": "ඇතුල් වන්න",
    "logout": "පිටවීම",
    "more": "තව..",
    "collapse": "හකුළන්න",
    "apply_change": "වෙනස්කම් යොදන්න",
    "apply": "අයදුම් කරන්න",
    "add_giftcard": "තෑගි කාඩ්පත එක් කරන්න",
    "charge": "අයකිරීම",
    "send_invites": "ආරාධනා යවන්න",
    "past": "පසුගිය",
    "restore": "ප්‍රතිෂ්ඨාපනය කරන්න",
    "cut": "කපනවා",
    "get_sms_code": "සත්‍යාපන කේතය ලබා ගන්න",
    "register_no_mail": "ඊමේල් නොමැතිව ඉදිරියට යන්න",
    "no_mail_register_message": "ඊමේල් ලිපිනයක් නොමැතිද නැතහොත් ඔබගේ මුරපදය අමතකද?",
    "reset_by_mail": "ඊමේල් මගින් මුරපද ප්‍රතිසාධනය",
    "reset_by_sms": "SMS මගින් මුරපද ප්‍රතිසාධනය",
    "cash_payment": "මුදල් ගෙවීම්",
    "show_chart": "ප්‍රස්ථාරය පෙන්වන්න",
    "open_app": "යෙදුම විවෘත කරන්න",
    "login_now": "දැන් ලොග් වෙන්න",
    "watch_video": "වීඩියෝව නරඹන්න",
    "check_now": "දැන් පරීක්ෂා කරන්න",
    "remove_image": "රූපය ඉවත් කරන්න",
    "view_website": "විවෘත ලින්ක්",
    "explore": "{name} ගවේෂණය කරන්න",
    "go": "යන්න",
    "read_more": "වැඩිදුර කියවන්න",
    "start_now": "දැන් ආරම්භ කරන්න - එය නොමිලේ",
    "view_live": "සජීවීව බලන්න",
    "resend_code": "කේතය නැවත යවන්න",
    "invite": "ආරාධනා කරන්න",
    "add_more": "තව එකතු කරන්න",
    "install_now": "දැන් ස්ථාපනය කරන්න",
    "uninstall": "අස්ථාපනය කරන්න",
    "show_preview": "පෙරදසුන පෙන්වන්න",
    "hide_preview": "පෙරදසුන සඟවන්න",
    "download_now": "දැන් බාගන්න",
    "auto_fill": "ස්වයං පිරවීම",
    "track": "ලුහුබැඳීම",
    "change_state": "තත්ත්වය වෙනස් කරන්න",
    "done": "කළා",
    "reply": "පිලිතුරු",
    "watch_now": "දැන් නරඹන්න",
    "unlock": "අගුළු හරින්න",
    "lock": "අගුළු දමන්න",
    "create_clone": "ක්ලෝනය සාදන්න",
    "regenerate": "නැවත උත්පාදනය කරන්න",
    "add_message": "පණිවිඩය එක් කරන්න",
    "continue_chat": "කතාබස් කරගෙන යන්න",
    "add_new_message": "නව පණිවිඩයක් එක් කරන්න"
  },
  "instance_message_title": "ක්ෂණික පණිවිඩයක් යවන්න",
  "instance_message": "ආයුබෝවන් {name}, මගේ නම {author} {company} වෙතින්.",
  "errors": {
    "419": "ඔබ දිගු කලක් අක්‍රියව සිට ඇත, ආරක්ෂක හේතූන් මත කරුණාකර <b>⟳ පිටුව නැවුම්</b> කරන්න.",
    "gateway_blockchain_sync_error": "පද්ධතිය blockchain සමඟ සමමුහුර්ත නොවේ. අපගේ සේවාදායකයන්ගේ සමමුහුර්ත කිරීම් අවසන් වන තුරු නව ගනුදෙනුවක් නිර්මාණය කිරීමට නොහැකි වනු ඇත. අපි ගැටලුව විසඳනවා.",
    "gateway_network_error": "ගෙවීම් ද්වාර සේවාව සන්නිවේදන ගැටලුවකට මුහුණ දී ඇත."
  },
  "receiver_info": {
    "map": {
      "title": "බෙදාහැරීමේ ලිපිනය",
      "confirm": "ස්ථානය සකසන්න",
      "address_type": "ගමනාන්තය",
      "receptor_type": "ග්රාහකයා"
    },
    "receiver_address": "නැව්ගත කිරීමේ ලිපිනය තෝරන්න",
    "address": "ලිපිනය",
    "postcode": "තැපැල් කේතය",
    "enter_value": "මෙතනින් පුරවන්න",
    "address_note": "සටහන",
    "tel": "ඇමතුම් අංකය",
    "service_address": "ඔබගේ ලිපිනය තෝරන්න"
  },
  "weight": {
    "g": "g",
    "oz": "oz",
    "lb": "රාත්තල්",
    "kg": "kg"
  },
  "mass_unit_name": {
    "g": "ග්රෑම්",
    "oz": "අවුන්ස",
    "lb": "පවුම්",
    "kg": "කිලෝ ග්රෑම්"
  },
  "length": {
    "cm": "සෙමී",
    "in": "තුල",
    "ft": "අඩි",
    "mm": "මි.මී",
    "m": "එම්",
    "yd": "yd"
  },
  "size_unit_name": {
    "cm": "සෙන්ටිමීටර",
    "in": "අඟල්",
    "ft": "පාදය",
    "mm": "මි.මී",
    "m": "මීටර්",
    "yd": "අංගනය"
  },
  "distance": {
    "m": "මීටර්",
    "km": "කි.මී"
  },
  "time": {
    "days": "දින",
    "hours": "පැය",
    "minutes": "මිනිත්තු",
    "seconds": "තත්පර"
  },
  "units": [
    "ඒකකය",
    "අයිතමය",
    "සෑම",
    "කට්ටලය",
    "කෑල්ලක්",
    "කිලෝ ග්රෑම්",
    "ග්රෑම්",
    "මිලිග්රෑම්",
    "මීටර්",
    "මි.මී",
    "වර්ග මීටරය",
    "වර්ග අඩි",
    "ඝන මීටර්",
    "ලීටර්",
    "මිලි ලීටර්",
    "අඩි",
    "ගැලුම්",
    "අඟල්",
    "අවුන්ස",
    "පවුම්",
    "ක්වාර්ට්ස්",
    "යාර",
    "කාමරය",
    "තත්පර",
    "මිනිත්තු",
    "පැය",
    "දින",
    "සති",
    "මාස",
    "වසර"
  ],
  "region_types": {
    "State": "රජයේ",
    "Territory": "භූමිය",
    "Province": "පළාත"
  },
  "transaction_status": {
    "RequireAction": "ක්‍රියාව අවශ්‍යයි",
    "Processing": "සැකසීම",
    "Canceled": "අවලංගු කළා",
    "Succeeded": "සාර්ථක විය"
  },
  "placeholders": {
    "name": "ජෝන් කොක්ස්",
    "email": "your-mail@mail.com",
    "phone": "+1 000 0000",
    "language": "භාෂාව තෝරන්න..",
    "friend_email": "ඔබේ මිතුරාගේ විද්‍යුත් තැපෑල...",
    "friend_name": "තෝරාගන්න. ඔබේ මිතුරාගේ නම",
    "select_date": "දිනයක් තෝරන්න..."
  },
  "notification": {
    "confirm": "තහවුරු කරන්න",
    "confirm_message": "වෙනස්කම් සාර්ථකව සුරකින ලදී.",
    "error": "දෝෂයකි",
    "message": "පණිවුඩය",
    "caution": "අවවාදයයි",
    "warning": "අවවාදයයි",
    "award": "සුභ පැතුම්",
    "error_message": "අවාසනාවකට, දෝෂයක් සිදුවී ඇත.",
    "congratulation": "සුභ පැතුම්",
    "coming_soon": "ඉක්මනින්",
    "on_fetching_data": "තොරතුරු ලැබීම..",
    "new_pwa_version": "නව අනුවාදය දැන් තිබේ. ඔබට යෙදුම යාවත්කාලීන කිරීමට අවශ්‍යද?",
    "over_license_limit": "බලපත්ර සීමාව ඉක්මවා",
    "update_license": "ඔබේ බලපත්‍රය යාවත්කාලීන කරන්න",
    "required": "අවශ්යයි",
    "invalid_email": "වලංගු නොවන විද්‍යුත් තැපෑලක්",
    "invalid_domain": "වලංගු නොවන වසම",
    "invalid_min_length": "අවම දිග {length} විය යුතුය",
    "invalid_min_array_length": "අවම වශයෙන් අයිතම {length} තෝරන්න",
    "invalid_max_chars": "උපරිම අක්ෂර {maxCount}",
    "invalid_url": "වලංගු නැති URL",
    "country_invalid": "ගමනාන්ත රට තෝරන්න!",
    "postal_code_invalid": "වලංගු තැපැල් කේතය සකසන්න!"
  },
  "colors": {
    "#D32F2F": "රතු",
    "#C2185B": "රෝස",
    "#7B1FA2": "දම් පාට",
    "#512DA8": "තද දම් පාට",
    "#303F9F": "ඉන්ඩිගෝ නිල්",
    "#1976D2": "නිල්",
    "#0288D1": "ලා නිල්",
    "#0097A7": "ටර්කියුයිස් නිල්",
    "#00796B": "පාත්ත කොළ",
    "#388E3C": "කොළ",
    "#689F38": "ලා කොළ",
    "#AFB42B": "ලිමෝ",
    "#FBC02D": "කහ",
    "#FFA000": "ඇම්බර්",
    "#F57C00": "දොඩම්",
    "#E64A19": "දිලිසෙන තැඹිලි",
    "#5D4037": "දුඹුරු",
    "#616161": "අළු",
    "#455A64": "අළු නිල්",
    "#FFD700": "රන්වන්",
    "#C0C0C0": "රිදී",
    "#b76e79": "රන් රෝස",
    "#383838": "මැට් කළු",
    "#FFFFFF": "සුදු",
    "#FFF": "සුදු",
    "#000000": "කලු",
    "#000": "කලු",
    "#7d263a": "මෙරූන්",
    "#FD9F17": "රන්",
    "#229DBF": "ඇක්වා",
    "#6DC9E2": "Aqua Triblend",
    "#413B2D": "හමුදා",
    "#474747": "ඇස්ෆල්ට්",
    "#E6195C": "බෙරී",
    "#B2184C": "බෙරී ට්‍රිබ්ලන්ඩ්",
    "#FC7F5F": "පිළිස්සුණු තැඹිලි",
    "#80011F": "කාදිනල්",
    "#382829": "චොකලට්",
    "#F06336": "කොරල්පර",
    "#FAE7C9": "ක්රීම්",
    "#6B2257": "කරන්ට් ඇතුළු",
    "#222127": "තද අළු",
    "#0D5A74": "ගැඹුරු තේ",
    "#00582F": "සදාහරිත",
    "#214C30": "වන",
    "#DC2867": "Fuchsia",
    "#38561": "කෙලී",
    "#5C884D": "කොළ",
    "#558450": "සැහැල්ලු ඇක්වා",
    "#96B5C9": "ලා නිල්",
    "#DCAFCE": "ලිලැක්",
    "#D3E1A4": "දෙහි",
    "#9DE7C2": "මින්ට්",
    "#F6EAD2": "ස්වාභාවික",
    "#1A1F35": "නාවික",
    "#404624": "ඔලිව්",
    "#271020": "වියලි මිදි",
    "#A8355C": "රාස්බෙරි",
    "#D6BEA6": "මෘදු ක්රීම්",
    "#BEA994": "ටැන්",
    "#0DB2AE": "ටීල්",
    "#A86EA9": "වයලට්",
    "#36454F": "අඟුරු",
    "#b3b0ab": "කාබන් අළු",
    "#463e3d": "අඟුරු හෙදර්",
    "#282d3c": "නාවික හමුදා බ්ලේසර්"
  },
  "address_info": {
    "name": "නම",
    "tel": "දුරකථන",
    "email": "විද්යුත් තැපෑල",
    "country": "රට",
    "city": "නගරය",
    "state": "රජයේ",
    "address": "ලිපිනය",
    "building_number": "ගොඩනැගිලි අංකය",
    "building_unit": "ඒකකය",
    "postcode": "තැපැල් කේතය",
    "note": "සටහන",
    "county": "ප්රාන්තය"
  },
  "product_types": {
    "physical": "ශාරීරික",
    "physical_description": "භෞතික නිෂ්පාදන වැනි: ජංගම දුරකථන, පොත්, ඉලෙක්ට්‍රොනික උපාංග.",
    "virtual": "අතථ්‍ය",
    "virtual_description": "අන්තර්ජාල හිතකාමී නිෂ්පාදන වැනි: රීචාජ් කාඩ්පත, හෝටල් වෙන්කරවා ගැනීම, ක්‍රීඩා නැවත ආරෝපණය කිරීම.",
    "file": "ගොනුව",
    "file_description": "සබැඳි පාඨමාලා වීඩියෝ, බාගත හැකි ලේඛන වැනි සියලුම අවසර ලත් ගොනු.",
    "service": "සේවය",
    "service_description": "වැනි සේවාවන්: අලුත්වැඩියාව, ප්‍රවාහනය, ඉගැන්වීම."
  },
  "license": {
    "free": "නිදහස්",
    "startup": "පණ ගන්වන්න",
    "company": "සමාගම",
    "enterprise": "ව්යවසාය"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "ටොමන්",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW",
    "GHS": "GHS",
    "ZWD": "ZWD",
    "IQD": "IQD",
    "SYP": "SYP"
  },
  "variants": {
    "color": "වර්ණ",
    "volume": "ප්රමාණය",
    "count_in_pack": "ඇසුරුමේ ගණන් කරන්න",
    "weight": "බර",
    "type": "ද්රව්ය",
    "style": "ශෛලිය"
  },
  "delivery_state": {
    "check_queue": "සමාලෝචනය බලාපොරොත්තුවෙන්",
    "order_confirm": "ඇණවුම තහවුරු කිරීම",
    "preparing_order": "සූදානම් කිරීම",
    "sent_order": "භාරදීමේදී",
    "to_customer": "භාර දුන්නා"
  },
  "status": {
    "unpaid": "නොගෙවූ",
    "paid": "ගෙවා ඇත",
    "canceled": "අවලංගු කළා",
    "completed": "පදිංචි වුණා",
    "reserved": "වෙන්කර ඇත",
    "COD": "COD",
    "sold": "විකුණුවා",
    "open": "විවෘත",
    "cancel": "අවලංගු කළා",
    "active": "ක්රියාකාරී",
    "inactive": "අක්රිය",
    "debug": "දෝෂහරණය කරන්න",
    "live": "සජීවි",
    "test": "පරීක්ෂණය",
    "connected": "සම්බන්ධයි",
    "disconnected": "විසන්ධි විය",
    "accept": "පිළිගන්න",
    "reject": "ප්රතික්ෂේප කරන්න",
    "pending": "පොරොත්තුවෙන්",
    "rejected": "ප්‍රතික්ෂේප කළා",
    "accepted": "පිළිගත්තා"
  },
  "dimensions": {
    "cm": "සෙමී",
    "km": "කි.මී",
    "kg": "kg"
  },
  "transportation_type": {
    "motorbike": "මෝටර් සයිකල්",
    "motorbike_description": "කිලෝමීටර කිහිපයක් ඇතුළත මධ්යම බර.",
    "cargo_small": "කුඩා භාණ්ඩ",
    "cargo_small_description": "බහු කිලෝමීටර් සැහැල්ලු භාණ්ඩ.",
    "cargo": "බඩු",
    "cargo_description": "කිලෝමීටර කිහිපයක් ඇතුළත මධ්යම බර.",
    "truck": "ට්රක් රථය",
    "truck_description": "රට තුළ තොග හෝ බර භාණ්ඩ.",
    "fast_post": "වේගවත් පෝස්ට්",
    "fast_post_description": "තැපැල් කාර්යාලය හරහා ඉක්මන් තැපැල් කිරීම.",
    "post": "සාමාන්‍ය තනතුර",
    "post_description": "තැපැල් කාර්යාලය හරහා නිතිපතා තැපැල් කිරීම.",
    "airplane": "ගුවන් තැපෑල",
    "airplane_description": "දේශීය හා විදේශීය සැහැල්ලු සහ මධ්යම භාණ්ඩ.",
    "bicycle": "පිරිසිදු යැවීම",
    "bicycle_description": "සැහැල්ලු භාණ්ඩ, මෝටර් නොවන වාහන යාර සිය ගණනක් ඇතුළත.",
    "global": "ගෝලීය ප්රවාහනය",
    "global_description": "ගුවනින්, මුහුදෙන් හෝ ගොඩබිමෙන් එතෙරට යැවීම.",
    "pickup": "අවුලා ගන්න",
    "pickup_description": "පාරිභෝගිකයින් ඔබේ භෞතික ගබඩාවේ හෝ ගබඩාවෙන් භාණ්ඩ ලබා ගනී."
  },
  "article": {
    "login_to_see_error": "ලිපියට ප්‍රවේශ වීමට පුරනය වන්න",
    "create_new_action": "නව අන්තර්ගතයක් සාදන්න",
    "menu_title": "මෙනු",
    "menu": {
      "edit": "සංස්කරණ මාදිලිය",
      "view_mode": "දර්ශන මාදිලිය",
      "delete": "ලිපිය මකන්න"
    },
    "schedule_action": "ඔබට ප්‍රකාශනය කාලසටහන් කිරීමට අවශ්‍යද?",
    "schedule_title": "කාලසටහන ස්වයංක්‍රීයව ප්‍රකාශනය කරන්න",
    "edit_mode": "සංස්කරණය කරන්න",
    "public_view_mode": "මහජන දර්ශනය",
    "publish_at": "ප්‍රකාශනය කරන්න",
    "published": "ප්‍රකාශිතයි",
    "draft": "කෙටුම්පත",
    "saving": "ඉතිරි කිරීම",
    "save_and_publish_action": "සුරකින්න සහ ප්‍රකාශ කරන්න",
    "save_draft_action": "කෙටුම්පත සුරකින්න",
    "private": "පුද්ගලික",
    "public": "මහජන",
    "category_input": "වර්ගය",
    "category_input_message": "ලිපි කාණ්ඩය තෝරන්න",
    "parent_input": "මාපිය කාණ්ඩය",
    "parent_input_message": "පියා අන්තර්ගතය තෝරන්න",
    "schedule_input": "කාලසටහන",
    "schedule_input_placeholder": "ඔබට කතාව නිශ්චිත වේලාවක පළ කිරීමට අවශ්‍ය නම්.",
    "schedule_view_action": "ප්‍රකාශන කාලසටහන බලන්න",
    "author_title": "ලියන ලද්දේ",
    "read_time": "පාඩම් කරන ෙව්ලාව",
    "read_time_unit": "මිනිත්තු",
    "claps_action": "ක්ලැප්ස්",
    "claps": "ක්ලැප්ස්",
    "likes": "මෙන්",
    "about_author": "කතුවරයා ගැන",
    "updated_at": "යාවත්කාලීන කරන ලදී",
    "wrote_at": "හිදී ලියා ඇත",
    "now": "දැන්",
    "follow_action": "අනුගමනය කරන්න",
    "followed": "අනුගමනය කළා",
    "report_and_delete_action": "මෙම ලිපිය වාර්තා කර මකන්න",
    "report_action": "අපයෝජනය වාර්තා කරන්න",
    "you_reported_this_article": "මෙම ලිපියේ දැනටමත් අපයෝජන වාර්තාවක් ඇත.",
    "add_to_publication_action": "ප්‍රකාශනයට එකතු කරන්න",
    "author_socials": "සමාජ මාධ්ය මත කර්තෘ",
    "share": "බෙදාගන්න",
    "report_dialog": {
      "report_and_delete_title": "අපයෝජනය වාර්තා කර අන්තර්ගතය ඉවත් කරන්න",
      "report_title": "මෙම අන්තර්ගතය අනිසි ලෙස වාර්තා කරන්න",
      "message": "මෙම අන්තර්ගතය ඉදිරිපත් කිරීමට හේතුව කුමක්ද? පහත විකල්ප වලින් එකක් තෝරන්න.",
      "accept_and_delete_action": "අන්තර්ගතය තහවුරු කර මකන්න"
    },
    "schedule_dialog": {
      "title": "අන්තර්ගත නිකුත් කිරීමේ කාලසටහන",
      "publish_at": "ප්‍රකාශනය කරන්න",
      "last_edit": "අවසන් සංස්කරණය",
      "view_action": "ලිපිය බලන්න"
    },
    "notifications": {
      "update_success_title": "තොරතුරු ඉදිරිපත් කරන්න",
      "update_success": "ලිපිය සාර්ථකව යාවත්කාලීන කරන ලදී.",
      "update_error": "ඇතුළත් කළ තොරතුරු වලංගු නොවේ.",
      "delete_error": "ඔබට මෙම ලිපිය මකා දැමිය නොහැක!",
      "report_and_delete_success_title": "වාර්තා කර මකන්න",
      "report_and_delete_success_message": "ලිපිය සාර්ථකව මකා ඇත.",
      "report_success_title": "වාර්තා ලිපිය",
      "report_success_message": "මෙම ලිපිය පිළිබඳ ඔබේ වාර්තාව පළ කර ඇත."
    },
    "alert": {
      "delete_article": {
        "title": "ලිපිය මකන්න",
        "message": "ඔබට මෙම ලිපිය ස්ථිරවම මැකීමට අවශ්‍ය බව විශ්වාසද?",
        "action": "මකන්න"
      }
    },
    "edit_window": {
      "title": "පින්තූර පෙළ සහ සාරාංශය තෝරන්න",
      "digest": "සාරාංශය"
    },
    "editor": {
      "title_placeholder": "ශීර්ෂය..",
      "body_placeholder": "නියම අන්තර්ගතය ලියන්න..",
      "accept_file_types_error": "මෙම ගොනු ආකෘතිය පිළිගත නොහැක:",
      "max_file_size_error": "මෙම ගොනුව ඉතා විශාලයි:",
      "notifications": {
        "image_uploaded_success": "රූපය සාර්ථකව සුරැකිණි",
        "image_uploaded_failed": "රූපය පූරණය කිරීමේ දෝෂයකි."
      },
      "embed_placeholder": "iframe කේතය, Facebook, Youtube හෝ වෙනත් ඕනෑම URL එකක් ඇතුළත් කර enter ඔබන්න.",
      "embed_caption_placeholder": "මාතෘකාවක් ඇතුළත් කරන්න (විකල්ප)",
      "images_caption_placeholder": "මෙම රූපය සඳහා මාතෘකාවක් ඇතුළත් කරන්න.."
    }
  },
  "article_report": {
    "inappropriate": "මෙම ලිපියේ අන්තර්ගතය නුසුදුසු ය.",
    "fake": "මෙය ව්යාජ හා රැවටිලිකාර ය.",
    "spam": "මෙම අයිතමය ස්පෑම් කර පිටපත් කර ඇත.",
    "scam": "මෙය අනිෂ්ට මෘදුකාංග, වෛරස් හෝ පද්ධති බිඳවැටීමක් ඇති කිරීමට අපේක්ෂා කළ හැක.",
    "hacked": "මෙම වෙබ් අඩවිය හැක් කර ඇති බව පෙනේ.",
    "offensive": "භාෂා අන්තර්ගතය සහ වචන මාලාව සදාචාර විරෝධී සහ අගෞරවනීය ය.",
    "violent": "මම හිතන්නේ මෙම අන්තර්ගතයේ අසභ්‍ය දර්ශන අඩංගු වන අතර එය නීති උල්ලංඝණය කරයි.",
    "harassment": "මම හිතන්නේ මේක ජාතිවාදීයි.",
    "hate": "මම හිතන්නේ මෙය ප්‍රචණ්ඩත්වය ප්‍රවර්ධනය කිරීමකි.",
    "infringe": "මෙය මගේ අයිතිවාසිකම් උල්ලංඝනය කරයි."
  },
  "comments": {
    "new_action": "අදහස් දැක්වීමට ක්ලික් කරන්න..",
    "title": "අදහස්",
    "body_placeholder": "ඔබේ අදහස හෝ පණිවිඩය",
    "send_action": "අදහස් එවන්න",
    "body_is_empty_error": "අදහස හිස්!",
    "comments": "අදහස්",
    "no_comments": "පළමු අදහස ලියන්න...",
    "load_more_action": "තවත් අදහස් ලබා ගන්න..",
    "cant_send_comment": "ඔබට නව තනතුරක් එක් කළ නොහැක.",
    "cant_remove_this_comment": "ඔබට මෙම අදහස මකා දැමිය නොහැක!",
    "product_buyer": "ගැනුම්කරු",
    "delete_alert": {
      "title": "අදහස මකන්න",
      "message": "ඔබට මෙම අදහස මැකීමට අවශ්‍යද?",
      "action": "මකන්න"
    },
    "notifications": {
      "delete_success": "ඔබේ අදහස සාර්ථකව මකා ඇත."
    },
    "first_send": "පළමු පෝස්ට් එක",
    "comment_at": "මත",
    "edit_comment": "අදහස සංස්කරණය කරන්න"
  },
  "customer_club": {
    "bronze": "ලෝකඩ",
    "silver": "රිදී",
    "gold": "රන්වන්",
    "platinum": "ප්ලැටිනම්",
    "diamond": "දියමන්ති"
  },
  "application_categories": {
    "tracking": "පරිශීලක හැසිරීම පරීක්ෂා කිරීම",
    "payment": "ගෙවීම",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "ප්රවාහන",
    "automation": "ස්වයංක්රීයකරණය",
    "inventory": "ගබඩා කිරීම",
    "accounting": "ගිණුම්කරණය",
    "marketing": "අලෙවි",
    "advertising": "ප්‍රචාරණය",
    "staff": "කාර්ය මණ්ඩලය",
    "incentive": "සහන",
    "shop": "සාප්පු යන්න"
  },
  "social_network": {
    "instagram": "Instagram",
    "telegram": "විදුලි පණිවුඩ",
    "googleplay": "GooglePlay",
    "appstore": "AppStore",
    "twitter": "ට්විටර්",
    "linkedin": "Linkedin",
    "medium": "මධ්යම",
    "selldone": "විකුණුවා",
    "facebook": "ෆේස්බුක්",
    "pinterest": "Pinterest",
    "whatsapp": "WhatsApp",
    "skype": "ස්කයිප්",
    "facebook_messenger": "ෆේස්බුක් මැසෙන්ජර්"
  },
  "form_builder": {
    "add_item_action": "නව අයිතමයක් එකතු කරන්න",
    "title_input": "ශීර්ෂය",
    "name_input": "විචල්ය නාමය",
    "value_input": "වටිනාකම්",
    "value_input_message": "පරිශීලක විකල්ප ලැයිස්තුව",
    "default": "පෙරනිමි අගය",
    "types": {
      "simple": "සරල",
      "selective": "වරණාත්මක",
      "switch": "මාරු කරන්න",
      "file": "ගොනුව",
      "number": "අංකය"
    },
    "placeholder_input": "ස්ථාන දරන්නා",
    "file_type_input": "පිළිගත හැකි ගොනු වර්ග",
    "file_type_message": "jpeg, png, zip, ..."
  },
  "virtual_order_info_summery": {
    "title": "නිෂ්පාදන නාමය",
    "reserved_at": "ලියාපදිංචි දිනය",
    "total_price": "මුලු වටිනාකම",
    "discount": "වට්ටම්",
    "final_price": "අවසාන මුදල",
    "payment_status": "ගෙවීම් තත්ත්වය",
    "payment_status_waiting": "ගෙවීම සඳහා රැඳී සිටීම",
    "payment_status_paid": "ගෙවා ඇත",
    "buyer": "ගැනුම්කරු"
  },
  "virtual_item_info": {
    "title": "අතථ්‍ය අයිතමය",
    "outputs": {
      "title": "ප්රතිදාන තොරතුරු",
      "sub_title": "මෙම අයිතමයේ රහස්‍ය තොරතුරු",
      "message": "භාණ්ඩය මිලදී ගැනීමෙන් පසු මෙම තොරතුරු පරිශීලකයාට පෙන්වනු ඇත."
    },
    "inputs": {
      "title": "අවශ්ය තොරතුරු",
      "sub_title": "ගැනුම්කරු තොරතුරු අවශ්‍යයි",
      "message": "ගැනුම්කරු විසින් ඉල්ලූ තොරතුරු පෝරමයේ ඇතුළත් කළ යුතුය"
    },
    "notifications": {
      "inputs_set_success": "තොරතුරු පෝරමය සාර්ථකව ලියාපදිංචි කර ඇත.",
      "confirm_by_admin_success": "ඇණවුම සම්පූර්ණ කිරීම තහවුරු කර ඇත.",
      "confirm_by_buyer_success": "ඇණවුම සම්පූර්ණ කිරීම තහවුරු කර ඇත."
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "COD ගෙවීමෙන් මෙම ඇණවුම පිළිගත නොහැක.",
    "payment_returned": "පාරිභෝගිකයා විසින් ගෙවීම ආපසු ලබා දෙනු ලැබේ.",
    "payment_fraud": "ගෙවීම වංචාවක් ලෙස හඳුනාගෙන ඇත.",
    "location_out_of_service": "පාරිභෝගික ස්ථානය සේවයෙන් බැහැරය.",
    "user_not_responding": "පාරිභෝගිකයා ඇමතුම්වලට පිළිතුරු දුන්නේ නැත.",
    "shop_owner_fault": "තොරතුරු පිරවීමේදී ගබඩා කාර්ය මණ්ඩලය විසින් දෝෂයක් සිදු විය.",
    "lack_of_inventory": "තොග නැති.",
    "legal_restriction": "නීතිමය සීමාවන් නිසා ඇණවුමක් කිරීමට නොහැකි විය.",
    "pricing_fault": "විකුණුම්කරුගේ මිල වැරැද්ද.",
    "system_fault": "පද්ධති දෝෂය."
  },
  "basket_order_info_summery": {
    "receiver": "ග්රාහකයා",
    "phone": "දුරකථන",
    "reserved_date": "මිලදීගත් දිනය",
    "total_price": "මුලු වටිනාකම",
    "discount": "වට්ටම්",
    "final_price": "අවසාන මුදල",
    "address": "භාරදීමේ ලිපිනය",
    "payment_status": "ගෙවීම් තත්ත්වය"
  },
  "basket_status": {
    "open": "විවෘත",
    "reserved": "වෙන්කර ඇත",
    "paid": "ගෙවා ඇත",
    "canceled": "අවලංගු කළා",
    "cod": "භාරදීමේදී ගෙවන්න",
    "receipt_added": "රිසිට්පත එකතු කරන ලදී",
    "payment_processing": "ගෙවීම් සැකසීම"
  },
  "basket_delivery_state": {
    "rejected": "ප්‍රතික්ෂේප කළා",
    "reject_reason_not_found": "හේතුව නොදනී.",
    "step_1": "සමාලෝචනය කරන්න",
    "step_2": "තහවුරු කිරීම",
    "step_3": "සකස් කිරීම",
    "step_4": "භාරදීමේදී",
    "step_5": "භාර දුන්නා"
  },
  "basket_return_request_view": {
    "title": "ආපසු ඉල්ලීම",
    "delivery_date": "බෙදාහැරීමේ දිනය",
    "return_date": "ඉල්ලුම් කරන දිනය",
    "items_count": "ආපසු ලබා දුන් අයිතම ගණන",
    "items_count_unit": "අයිතම)",
    "reason": "හේතුව",
    "description": "විස්තර",
    "status": "තත්ත්වය",
    "download_image": "රූපය බාගන්න",
    "download_film": "වීඩියෝ බාගන්න",
    "download_voice": "හඬ බාගන්න",
    "accept_by_admin_action": "ඉල්ලීම පිළිගන්න",
    "reject_by_admin_action": "ඉල්ලීම ප්‍රතික්ෂේප කරන්න",
    "message_for_admin": "Selldone භාවිතා කිරීමෙන් ඔබ පිළිගත් ගිවිසුමට අනුව, ඔබ ගැනුම්කරු සම්බන්ධ කර ඔහුගේ/ඇයගේ ඇණවුම ආපසු ලබා දීමේ ක්‍රියාවලිය පිළිබඳව ඔහු/ඇය දැනුවත් කළ යුතුය. ඉල්ලීම පිළිගෙන හෝ ප්‍රතික්ෂේප කළහොත් සහ ගැනුම්කරුගේ සම්පූර්ණ කැමැත්ත ලබා ගන්නේ නම් මෙය කළ යුතුය.",
    "notifications": {
      "update_status_success": "ඉල්ලීම් තත්ත්වය යාවත්කාලීන කරන ලදී."
    }
  },
  "basket_list": {
    "return_count": "ආපසු: {count} අංකය",
    "table": {
      "row": "පේළිය",
      "image": "රූප",
      "product_name": "නිෂ්පාදන",
      "variant": "ප්රභේදය",
      "warranty": "වගකීම්",
      "count": "ගණන් කරන්න",
      "price": "මිල"
    }
  },
  "return_request_list": {
    "count": "යොමු අංකය",
    "return_warranty": "මුදල් ආපසු ගෙවීමේ සහතිකය",
    "return_warranty_unit": "දින)",
    "table": {
      "code": "ඇණවුම් කේතය",
      "product": "නිෂ්පාදන",
      "delivery_at": "ලැබුණු දිනය",
      "state": "තත්ත්වය",
      "reason": "හේතුව",
      "return_warranty_period": "වගකීම් කාලය"
    }
  },
  "data_toolbar": {
    "search": "සෙවීම",
    "sort_by": "අනුව තෝරන්න",
    "count_item": "අයිතම {item} පෙන්වන්න"
  },
  "sort": {
    "created_at": "දිනය සාදන්න",
    "updated_at": "දිනය සංස්කරණය කරන්න",
    "title": "ශීර්ෂය",
    "description": "විස්තර",
    "like": "ජනප්රියත්වය",
    "power": "ක්ලැප්ස්",
    "product_type": "නිෂ්පාදන වර්ගය",
    "discount": "වට්ටම්",
    "rate": "ශ්රේණිගත කිරීම",
    "rate_count": "ශ්රේණිගත කිරීම් සංඛ්යාව",
    "category": "වර්ගය",
    "product": "නිෂ්පාදන",
    "body": "අන්තර්ගතය",
    "card_type": "කාඩ් වර්ගය",
    "card_number": "කාඩ්පත් අංකය",
    "balance": "ශේෂය",
    "paid": "වියදම් කළ මුදල",
    "currency": "මුදල්",
    "expire_at": "කල්පිරෙන දිනය",
    "discount_code": "වට්ටම් කේතය",
    "discount_percent": "වට්ටම්",
    "discount_limit": "වට්ටම් සීමාව",
    "max_count": "උපරිම ගණන",
    "used_count": "පාවිච්චි කළා",
    "start_date": "ආරම්භක දිනය",
    "end_date": "අවසාන දිනය",
    "total_discount_amount": "සම්පූර්ණ වට්ටම්",
    "initial_charge": "මූලික ගාස්තුව",
    "total_count": "මුළු ගණන",
    "amount_paid": "ගෙවූ මුදල",
    "name": "නම",
    "published": "ප්‍රකාශිතයි",
    "visits": "සංචාරයන්",
    "color": "වර්ණ",
    "landing_page": "ගොඩබෑමේ පිටුව",
    "enable": "සබල කරන්න",
    "fix_commission": "ස්ථාවර කොමිස්",
    "percent_commission": "ප්‍රතිශත කොමිස්",
    "payment_at": "ගෙවීම් දිනය",
    "issued_at": "නිකුත් කල දිනය",
    "payment": "ගෙවීම",
    "website": "වෙබ් අඩවිය",
    "email": "විද්යුත් තැපෑල",
    "user": "පරිශීලක",
    "code": "කේතය",
    "schedule_at": "කාලසටහන් දිනය",
    "sender": "යවන්නා",
    "in_que": "පෝලිමේ",
    "sent": "යවා ඇත",
    "shop": "සාප්පු යන්න",
    "quantity": "ප්රමාණය",
    "amount": "ප්රමාණය",
    "jobs": "රැකියා ගණන්",
    "success": "සාර්ථකත්වය ගණන්",
    "fail": "අසාර්ථක ගණනය",
    "distance": "දුර",
    "duration": "කාල සීමාව",
    "reset_at": "දිනය නැවත සකසන්න",
    "delivery_person": "පුද්ගලයා",
    "delivery_service": "සේවය",
    "date": "දිනය",
    "order": "නියෝග",
    "order_id": "ඕඩර අංකය",
    "status": "තත්ත්වය",
    "price": "මිල",
    "count": "ගණන් කරන්න",
    "final_price": "අවසාන මිල",
    "charge": "අයකිරීම",
    "mention": "සඳහන් කරන්න",
    "officer": "නිලධාරී",
    "registered": "ලියාපදිංචි",
    "purchased": "මිලදී ගත්තා",
    "sex": "ස්ත්රී පුරුෂ භාවය"
  },
  "search_box": {
    "result": "සෙවුම් ප්රතිඵල",
    "tips": "නිෂ්පාදන සහ කාණ්ඩ සොයන්න",
    "label": "සෙවීම ...",
    "category": "වර්ගය"
  },
  "lead_status": {
    "physical_fast_delivery": "ක්ෂණික භාරදීම",
    "physical_under_24h_delivery": "ඉදිරි {lead} ඇතුළත භාර දෙන්න",
    "physical_over_24h_delivery": "ඉදිරි දින {days} සිට සූදානම් කිරීම සහ ඉදිරිපත් කිරීම",
    "virtual_fast_prepare": "ක්ෂණික භාරදීම",
    "virtual_under_24h": "ඉදිරි {lead} ඇතුළත සිදු කෙරේ",
    "virtual_over_24h": "ඉදිරි දින {days} සිට සිදු කෙරේ"
  },
  "return_request_state": {
    "pending": "පොරොත්තුවෙන්",
    "accepted": "තහවුරු කර ඇත",
    "rejected": "ප්‍රතික්ෂේප කළා"
  },
  "return_order_reason": {
    "physical": {
      "U1": "නිෂ්පාදන නොගැලපීම",
      "U2": "නැව්ගත කිරීමේ පැකේජයේ නිෂ්පාදනයක් නොමැත",
      "U3": "පැකේජය හෝ නිෂ්පාදන කැඩීම",
      "U4": "පැකේජය හෝ අනුක්‍රමික අංකය විකෘති කිරීම",
      "U5": "පාර්සලයේ සමහර අයිතම අස්ථානගත වී ඇත",
      "U6": "නිෂ්පාදනය මුල් නොවේ",
      "U7": "නිෂ්පාදිතය පිරිවිතරයන් සපුරාලන්නේ නැත"
    }
  },
  "image_uploader": {
    "label": "<u>ගොනුව ඇද දමන්න හෝ තෝරන්න</u>",
    "max_size": "අවසර ලත් උපරිම ප්‍රමාණය: {size}"
  },
  "timespan": {
    "Morning": "පෙ.ව. 8 - ප.ව. 12",
    "Evening": "දහවල් 12 සිට සවස 6 දක්වා",
    "Night": "සවස 6 සිට 12 දක්වා",
    "Instant": "ක්ෂණික පෝස්ට්"
  },
  "week_day": {
    "Saturday": "සෙනසුරාදා",
    "Sunday": "ඉරිදා",
    "Monday": "සඳුදා",
    "Tuesday": "අඟහරුවාදා",
    "Wednesday": "බදාදා",
    "Thursday": "බ්රහස්පතින්දා",
    "Friday": "සිකුරාදා"
  },
  "payment_form": {
    "title": "ගෙවීම් ක්‍රමය තෝරන්න",
    "gift_cards_input": "තෑගි කාඩ්පත්",
    "gift_cards_input_empty": "තෑගි කාඩ්පත් හමු නොවීය..",
    "more": "වෙනත්",
    "pay_amount_by_gift_cards": "ගාස්තු කාඩ්පත් ගෙවීම",
    "select_payment_method": "පහත විකල්ප වලින් ඔබගේ ගෙවීම් ක්‍රමය තෝරන්න.",
    "payment_amount_remained": "ඉතිරි ගෙවීමේ මුදල",
    "payment_amount": "ගෙවූ මුදල",
    "all_paid_by_gift_cards": "සුභ පැතුම්, ඔබට මෙම ඇණවුම සඳහා ගෙවීමට අවශ්‍ය නැත. තෑගි කාඩ්පත සමඟ ගෙවන්න යතුර ඔබන්න.",
    "pay_by_gift_cards_action": "ගාස්තු කාඩ්පත සමඟ ඇණවුම ගෙවන්න",
    "order_free_payment": "සුභ පැතුම්, ඔබගේ ඇණවුම නොමිලේ!",
    "order_free_payment_action": "දැන් නොමිලේ ඇණවුම් කරන්න",
    "qr": {
      "address": "ගෙවීම් ලිපිනය",
      "amount": "ප්රමාණය"
    }
  },
  "discount_input": {
    "limit": "{percent}% {limit} {currency} දක්වා වට්ටමක්",
    "action": "වට්ටම් කේතය එකතු කරන්න",
    "code_input": "වට්ටම් කේතය",
    "notifications": {
      "add_success": "සුභ පැතුම්, වලංගු වට්ටම් කේතය."
    }
  },
  "gift_card": {
    "inactive": "කාඩ්පත අබල කර ඇත",
    "expire": "කල් ඉකුත්වීම",
    "transfer": "මාරු",
    "send_to_friend": "මිතුරෙකුට යවන්න"
  },
  "count_down": {
    "days": "දිනය",
    "hours": "පැය",
    "minutes": "මිනිත්තු",
    "seconds": "තත්පර"
  },
  "gift_status": {
    "Unpaid": "රිසිට්පතක් බලාපොරොත්තුවෙන්",
    "Paid": "ගෙවා ඇත",
    "Rejected": "ප්‍රතික්ෂේප කළා",
    "Canceled": "අවලංගු කළා"
  },
  "gift_program_status": {
    "Airdrop": "ගෙවීම් පද්ධතිය",
    "Advertising": "ප්‍රචාරණය",
    "PersonalGift": "පුද්ගලික තෑග්ග",
    "ShopGift": "තෑගි කඩය"
  },
  "currency_selector": {
    "label": "මුදල්"
  },
  "need_login": {
    "title": "ඇතුල් වන්න",
    "login_sms": "SMS පුරනය වීම",
    "login_google": "Google සමඟ ලොග් වන්න",
    "login_facebook": "ෆේස්බුක් සමග පිවිසුම්",
    "login_account": "Selldone මගින් ලොගින් වන්න",
    "register": "නව පරිශීලකයෙක්? දැන්ම ලියාපදිංචි වන්න.",
    "mobile_input": "ඔබගේ ජංගම දුරකථනය ඇතුලත් කරන්න",
    "verification_code": "සත්යාපන කේතය",
    "msg_title": "හායි,",
    "msg_body": "කරුණාකර පිවිසෙන්න. එය ගත වන්නේ තත්පර කිහිපයක් පමණි.",
    "login_apple": "Apple සමඟ ලොග් වන්න"
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "අවුරුදු 5 රන් ගබඩාව"
    },
    "GOLDEN_2YEAR": {
      "name": "අවුරුදු 4 රන් ගබඩාව"
    },
    "GOLDEN_3YEAR": {
      "name": "අවුරුදු 3 රන් ගබඩාව"
    },
    "GOLDEN_4YEAR": {
      "name": "අවුරුදු 2 රන් ගබඩාව"
    },
    "GOLDEN_5YEAR": {
      "name": "වසර 1ක රන් ගබඩාව"
    },
    "TOKEN_OWNER_1M": {
      "name": "රන් ආයෝජකයා"
    },
    "TOKEN_OWNER_10M": {
      "name": "දියමන්ති ආයෝජකයා"
    },
    "TOKEN_OWNER_100M": {
      "name": "රූබි ආයෝජකයා"
    },
    "COMMUNITY_LOYAL": {
      "name": "සන්නිවේදන ජාලවල උසස් ප්‍රජාවේ සාමාජික"
    },
    "GOLD_SUPPLIER": {
      "name": "රන් සැපයුම්කරු"
    },
    "GOLD_SELLER": {
      "name": "රන් වෙළෙන්දා"
    },
    "CONTENT_SUPERMAN": {
      "name": "ඉහළම අන්තර්ගත නිෂ්පාදකයා"
    },
    "NINJA": {
      "name": "නින්ජා"
    },
    "STAR": {
      "name": "තරුව"
    },
    "GUARDIAN": {
      "name": "විශිෂ්ට පාරිභෝගික සේවාවක්"
    },
    "KING": {
      "name": "වෙළඳපොලේ රජු"
    }
  },
  "cookie": {
    "title": "මෙම වෙබ් අඩවිය කුකීස් භාවිතා කරයි",
    "message": "මෙම වෙබ් අඩවිය පරිශීලක අත්දැකීම් වැඩිදියුණු කිරීමට කුකීස් භාවිතා කරයි. අපගේ වෙබ් අඩවිය භාවිතා කිරීමෙන් ඔබ අපගේ කුකී ප්‍රතිපත්තියට අනුකූලව සියලුම කුකීස් වලට එකඟ වේ.",
    "preferences_action": "මනාප කළමනාකරණය කරන්න",
    "agree_action": "මම එකඟයි"
  },
  "basket_item_message": {
    "title": "මෙම අයිතමය සඳහා අවශ්ය තොරතුරු",
    "save_actions": "පණිවිඩය සුරකින්න",
    "notifications": {
      "success": "ඔබගේ ආදාන දත්ත සුරැකී ඇත."
    }
  },
  "faq": {
    "faq": "නිතර අසන ප්රශ්න",
    "title": "ප්රශ්න සහ පිළිතුරු",
    "sub_title": "ඔබ අපෙන් ඉල්ලා සිටි දේ.",
    "message": "පහත පිළිතුරු අතර ඔබේ ප්‍රශ්නයට පිළිතුර සොයන්න. ප්‍රශ්නවලට පිළිතුරු නොමැති නම් අපෙන් අසන්න.",
    "add_question_action": "අලුත් ප්‍රශ්නයක් අහන්න",
    "read_more": "වැඩිදුර කියවන්න ..",
    "load_more": "තවත් ප්‍රශ්න..",
    "main_page": "නිතර අසන පැන ප්‍රධාන පිටුව",
    "add_new": "නව ප්‍රශ්නය ඉදිරිපත් කරන්න",
    "login_alert": "ප්‍රශ්නයක් ඇසීමට ලොග් වන්න.",
    "question_input": "ප්රශ්නය",
    "question_input_placeholder": "ඔබේ ප්‍රශ්නය අසන්න.",
    "notifications": {
      "success_add": "ඔබගේ ප්‍රශ්නය සාර්ථකව ඉදිරිපත් කරන ලදී."
    }
  },
  "rating_labels": [
    "හරිම නරකයි",
    "නරක",
    "සාමාන්ය",
    "හොඳ",
    "විශිෂ්ටයි"
  ],
  "map_view": {
    "address_detail": "ලිපිනය විස්තර",
    "change": "වෙනස් කරන්න",
    "select": "තෝරන්න",
    "not_found_address": "අගයක් හමු නොවීය",
    "enter_address_hint": "ගමනාන්ත ලිපිනය ඇතුලත් කරන්න",
    "enter_your_address": "ඔබගේ ලිපිනය ඇතුලත් කරන්න.",
    "postal_code": "තැපැල් කේතය",
    "phone_input": "දුරකථනය {type}",
    "building_number": "ගොඩනැගිලි අංකය",
    "building_unit": "ඒකකය",
    "full_name_input": "සම්පූර්ණ නම {type}",
    "save_detail_action": "විස්තර සුරකින්න",
    "more_detail_input": "වැඩි විස්තර",
    "add_address_to_list": "ලැයිස්තුවට ලිපිනය එක් කරන්න",
    "address_title_input": "ලිපින ලේබලය (අවශ්‍යයි)",
    "notifications": {
      "save_in_list": "මෙම ලිපිනය එහි සියලුම විස්තර සහිතව ඔබගේ ලැයිස්තුවට සුරැකී ඇත.",
      "edit_success": "නව ලිපින අගයන් {title} හි සුරකින ලදී."
    },
    "delete_address_dialog": {
      "title": "ලිපිනය මකන්න",
      "message": "ඔබට මෙම ලිපිනය මැකීමට අවශ්‍ය බව විශ්වාසද?",
      "action": "ලිපිනය ඉවත් කරන්න"
    }
  },
  "comment_manager": {
    "can_not_edit": "මෙම අදහස සංස්කරණය කළ නොහැක!",
    "comment_input_empty": "පණිවිඩ පෙළ හිස්ය!",
    "article_not_saved": "ලිපිය සුරකින්න!"
  },
  "wheel_fortune": {
    "title": "Play & Win",
    "message": "එක් ක්‍රීඩාවක මිල චිප්ස් 10 කි. ඔබට දැනට {chips} චිපය ඇත. ගබඩාවෙන් මිලදී ගැනීමෙන් වැඩි චිප් ලබා ගන්න.",
    "win_message": "සුභ පැතුම්, ඔබට ජය!",
    "lost_message": "සමාවන්න, ඔබට ක්‍රීඩාව අහිමි විය.",
    "try_again": "ඔබට නැවත උත්සාහ කළ හැක"
  },
  "json": {
    "add": "ව්යුහය දත්ත එකතු කරන්න",
    "add_message": "නව ව්‍යුහ දත්ත සාදන්න",
    "structures": "ව්යුහයන්",
    "book": {
      "title": "පොත",
      "desc": "සෙවුම් ප්‍රතිඵල වලින් සෘජුවම සොයා ගන්නා පොත මිලදී ගැනීමට පරිශීලකයින්ට හැකි පොත් ක්‍රියා."
    },
    "occupation": {
      "title": "ඇස්තමේන්තුගත වැටුප",
      "desc": "වැටුප් පරාසයන් සහ රැකියා වර්ග සඳහා කලාපීය පදනම් වැටුප් සාමාන්‍යයන් වැනි වැටුප් ඇස්තමේන්තු පිළිබඳ තොරතුරු, Google හි රැකියා සෙවීමේ අත්දැකීම තුළ ප්‍රදර්ශනය කෙරේ."
    },
    "course": {
      "title": "පාඨමාලාව",
      "desc": "සපයන්නා-විශේෂිත ලැයිස්තුවක දිස්වන අධ්‍යාපනික පාඨමාලා. පාඨමාලා මාතෘකාව, සපයන්නා සහ කෙටි විස්තරයක් ඇතුළත් විය හැක."
    },
    "howto": {
      "title": "කොහොමද",
      "desc": "වීඩියෝ, පින්තූර සහ පෙළ ඇතුළත් කාර්යයක් සාර්ථකව සම්පූර්ණ කිරීම සඳහා පියවර මාලාවක් හරහා පරිශීලකයින් ගමන් කරන්නේ කෙසේද?"
    },
    "recipe": {
      "title": "වට්ටෝරුව",
      "desc": "තනි පුද්ගල පොහොසත් ප්‍රතිඵලයක් හෝ සත්කාරක කැරොසල් කොටසක් ලෙස සංදර්ශන කරන වට්ටෝරු."
    }
  },
  "support": {
    "Financial": "මූල්යමය",
    "Technical": "කාර්මික",
    "Advisor": "උපදේශක"
  },
  "condition": {
    "new": "අලුත්",
    "refurbished": "නවීකරණය කරන ලදී",
    "used": "පාවිච්චි කළා",
    "used_fair": "සාධාරණ ලෙස භාවිතා කර ඇත",
    "used_good": "හොඳට පාවිච්චි කළා",
    "used_like_new": "අලුත් වගේ පාවිච්චි කරනවා"
  },
  "variant_filter": {
    "title": "නිෂ්පාදන ප්රභේද පෙරහන",
    "only_available": "ගබඩාවේ ඇත"
  },
  "service": {
    "task": {
      "title": "කාර්යයන්",
      "message": "මෙම සේවාව තුළ සිදු කරන ලද කාර්යයන් ලැයිස්තුව."
    },
    "appointment": {
      "title": "පත්වීම",
      "message": "ඔබට ගැලපෙන දිනය සහ පැය මත පදනම්ව පහත සඳහන් වේලාවන් වලින් සතියේ වේලාවන් තෝරන්න."
    },
    "booking": {
      "title": "වෙන්කරවා ගැනීම",
      "message": "පහත දින දර්ශනයේ ඔබට වෙන්කරවා ගැනීමට අවශ්‍ය දින වල කාල සීමාව සඳහන් කරන්න."
    },
    "subscription": {
      "title": "දායකත්වය"
    },
    "charge": {
      "title": "අයකිරීම"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "ස්ථාවර මිලකරණය",
      "message": "මෙම වර්ගයේ මිලකරණයේදී, භාණ්ඩයේ මිල ස්ථාවර මුදලක් වන අතර, ගැනුම්කරුට මිල ගණනය කිරීමක් ඉල්ලා සිටීමේ අවශ්‍යතාවයක් නොමැත."
    },
    "ESTIMATION": {
      "title": "ඇස්තමේන්තු මිලකරණය",
      "message": "ඇණවුමක් කිරීමේදී විකුණුම්කරු විසින් භාණ්ඩ හා සේවාවල මිල යම් ප්‍රමාණයකට ගණනය කරනු ලැබේ, සේවාව අතරතුර ගෙවීම් ඉන්වොයිසි වෙනස් කිරීමට හෝ එකතු කිරීමට හැකිය."
    },
    "AGREEMENT": {
      "title": "ගිවිසුම් මිලකරණය",
      "message": "ඇණවුම ලබා දීමෙන් පසු විකුණුම්කරු විසින් නිෂ්පාදන හෝ සේවාවන්හි අවසාන මිල වෙනස් නොවේ."
    },
    "BID": {
      "title": "ලංසු / වෙන්දේසිය",
      "message": "අනාගත ගැනුම්කරුවන් විසින් භාණ්ඩය ඉහළම ලංසුවකට විකුණනු ලැබේ."
    }
  },
  "map": {
    "title": "නිෂ්පාදන ලබා ගැනීමට ගමනාන්තය",
    "confirm": "ස්ථානය සකසන්න",
    "address": "ගමනාන්තය",
    "receptor": "ග්රාහකයා"
  },
  "ShopBots": {
    "telegram": "විදුලි පණිවුඩ"
  },
  "article_tags": {
    "title": "අන්තර්ගත ටැග්",
    "tags_input": "ටැග්",
    "tags_input_message": "මෙම ලිපියේ ටැග් ලැයිස්තුව",
    "notification": {
      "add_success": "ටැග් එකතු කරන ලදී"
    }
  },
  "difficulties": {
    "very_complicated": "ඉතා සංකීර්ණයි",
    "hard": "අමාරුයි",
    "intermediate": "අතරමැදි",
    "easy": "පහසු"
  }
};