export default {
  "currency_default": "USD",
  "language_default": "en",
  "selldone": "Predané",
  "store": "obchod",
  "not_exist": "neexistuje",
  "error": "Chyba",
  "active": "Aktívne",
  "inactive": "neaktívne",
  "required_value": "Požadované hodnoty",
  "original_warranty": "Záruka pôvodného produktu",
  "return_warranty_days": "{days} dni záruky vrátenia tovaru",
  "no_return_warranty": "Bez návratu",
  "reed_agree_terms": "Prečítal som si podmienky používania a zásady ochrany osobných údajov a súhlasím s nimi.",
  "commons": {
    "Currency": "mena",
    "COD": "COD",
    "State": "Štát",
    "Price": "cena",
    "order_price": "Suma objednávky",
    "VAT": "VAT",
    "Discount": "Zľava",
    "In_Stock": "Skladom",
    "Variants": "Varianty",
    "No_variants": "Žiadny variant",
    "all": "VŠETKY",
    "today": "dnes",
    "yesterday": "včera",
    "license": "Licencia",
    "home": "Domov",
    "support": "podpora",
    "messages": "Správy",
    "no_message": "Žiadna správa",
    "empty": "Prázdny",
    "phone": "Telefón",
    "address": "adresu",
    "name": "názov",
    "password": "heslo",
    "email": "Email",
    "mobile": "Mobilné",
    "login": "Prihlásiť sa",
    "register": "Registrovať",
    "select_account": "Vyberte účet",
    "online": "online",
    "offline": "Offline",
    "finish": "Skončiť",
    "finished": "Dokončené",
    "preview": "Náhľad",
    "free": "zadarmo",
    "free_completely": "Úplne bezplatné predplatné",
    "fee": "Poplatok",
    "month": "mesiac",
    "months": "mesiacov",
    "faq": "často kladené otázky",
    "question": "Otázka",
    "answer": "Odpoveď",
    "create_date": "Vytvorte dátum",
    "update_date": "Dátum aktualizácie",
    "start_date": "Dátum začiatku",
    "end_date": "Dátum ukončenia",
    "social": "Sociálne",
    "total": "Celkom",
    "orders": "objednávky",
    "sessions": "Relácie",
    "product_views": "Pohľady na produkt",
    "add_to_carts": "Pridať do košíkov",
    "checkouts": "Odhlásiť sa",
    "payments": "Platba",
    "organic_search": "Organické vyhľadávanie",
    "other": "Iné",
    "landing_page": "Vstupná stránka",
    "discount_code": "Zľavový kód",
    "total_sell": "Celkové predaje",
    "details": "Podrobnosti",
    "currency": "mena",
    "amount": "Suma",
    "published": "Publikovaný",
    "draft": "Návrh",
    "save_changes": "Uložiť zmeny",
    "source": "Zdroj",
    "medium": "Stredná",
    "url": "URL",
    "revenue": "Výnosy",
    "performance": "Výkon",
    "term": "Termín",
    "content": "Obsah",
    "session": "relácia",
    "product": "Produkt",
    "add": "Pridať",
    "checkout": "Odhlásiť sa",
    "payment": "Platba",
    "more_options": "Viac možností",
    "full_name": "Celé meno",
    "tel": "Tel",
    "about_me": "O mne",
    "request_checking": "Požiadať o kontrolu",
    "passport": "pas",
    "birthday": "narodeniny",
    "country": "Krajina",
    "city": "Mesto",
    "gender": "rod",
    "offer": "Ponuka",
    "website": "webové stránky",
    "apply_for_all_products": "∞ Použiť na všetky produkty",
    "fix_commission": "Pevná provízia",
    "percent_commission": "Percentuálna provízia",
    "fixed_discount": "Pevná zľava",
    "discount_percentage": "Percentuálna zľava",
    "discount_limit": "Zľavový limit",
    "no_code": "Žiadny kód",
    "max_count": "Maximálny počet",
    "count_unit": "Položky",
    "used": "Použité",
    "daily": "Denne",
    "monthly": "Mesačne",
    "yearly": "Ročne",
    "state": "Postavenie",
    "disable": "Zakázať",
    "enable": "Povoliť",
    "activation_code": "Aktivačný kód",
    "quantity": "množstvo",
    "no_club": "Žiadny klub",
    "per_order": "Na objednávku",
    "count": "počítať",
    "seconds": "sekúnd",
    "auto": "Automat",
    "title": "Názov",
    "message": "Správa",
    "width": "šírka",
    "length": "Dĺžka",
    "height": "Výška",
    "label": "Označenie",
    "click": "Kliknite",
    "bank": "breh",
    "default": "Predvolené",
    "role": "Role",
    "user": "Používateľ",
    "users": "Používatelia",
    "code": "kód",
    "total_payment": "Celková platba",
    "balance": "Zostatok",
    "chance": "Šanca",
    "free_for_new_users": "Zadarmo pre nových používateľov",
    "prize_amount": "Výška ceny",
    "win": "Vyhrať",
    "gift_card": "Darčeková karta",
    "discount": "Zľava",
    "config": "Konfig",
    "prize": "cena",
    "Prizes": "ceny",
    "result": "Výsledok",
    "price": "cena",
    "lottery": "Lotéria",
    "coupon": "kupón",
    "customer_club": "Zákaznícky klub",
    "shipping": "Doprava",
    "sum": "Sum",
    "not_paid": "Nezaplatené",
    "category": "Kategória",
    "done": "hotový",
    "email_from": "Od",
    "subject": "Predmet",
    "schedule": "Rozvrh",
    "files_list": "Zoznam súborov",
    "file_max_size": "Maximálna veľkosť súboru",
    "value": "Hodnota",
    "help": "Pomoc",
    "shipping_tax": "Prepravná daň",
    "net_price": "Internetová cena",
    "tax": "daň",
    "tax_included": "V cene",
    "limit": "Limit",
    "min_purchase": "Minimálny nákup",
    "eligible_for": "Vhodný na",
    "only_for_first_buy": "Len pri prvom nákupe",
    "one_time_use": "Možno použiť jednorazovo",
    "period_of_qualify": "Limit používania",
    "no_constraint": "Bez obmedzenia",
    "timespan": "Časový úsek",
    "days": "Dni)",
    "weight": "Hmotnosť",
    "distance": "Vzdialenosť",
    "last_status": "Posledný stav",
    "issued_at": "Vydané o",
    "order": "objednať",
    "order_detail": "Detaily objednávky",
    "percent": "percent",
    "applied_count": "Aplikovaný počet",
    "campaign": "kampaň",
    "os": "Operačný systém",
    "browser": "Prehliadač",
    "device": "Zariadenie",
    "device_ip": "IP adresa zariadenia",
    "location": "Miesto",
    "user_agent": "Používateľský agent",
    "affiliate": "Pridružený",
    "timeline": "Časová os",
    "add_note": "Pridať poznámku",
    "record": "Záznam",
    "unlimited": "Neobmedzene",
    "show_coupons": "Ukážte kupóny",
    "hide_coupons": "Skryť kupóny",
    "service_area": "Obsluhovaná oblasť",
    "apps": "aplikácie",
    "plugins": "Pluginy",
    "bots": "Roboty",
    "categories": "Kategórie",
    "products": "Produkty",
    "business": "Podnikanie",
    "personal": "Osobné",
    "size": "Veľkosť",
    "holiday": "Dovolenka",
    "sod": "Platba pri doručení",
    "cod": "Platba na dobierku",
    "free_shipping": "Doprava zdarma",
    "hours": "hodiny",
    "send_date": "Dátum prepravy",
    "deliver_date": "Dátum doručenia",
    "return_date": "Dátum návratu",
    "pending": "Čaká na spracovanie",
    "delivered": "Doručené",
    "returned": "Vrátený",
    "canceled": "Zrušené",
    "shipping_cost": "Náklady na dopravu",
    "action": "Akcia",
    "cancel_date": "Zrušiť dátum",
    "deliver_in_process": "Objednávka je odoslaná..",
    "kind": "Typ",
    "detail": "Podrobnosti",
    "map": "Mapa",
    "actions": "Akcie",
    "navigation": "Navigácia",
    "navigation_app": "Aplikácia",
    "payment_date": "Dátum platby",
    "duration": "Trvanie",
    "bill": "Bill",
    "delivery_persons": "Kuriéri",
    "delivery_services": "Doručovacie služby",
    "live_view": "Živý náhľad",
    "cart": "Košík",
    "priority": "Priorita",
    "sufficient_credit": "Dostatočný kredit",
    "max_package_size": "Maximálna veľkosť balenia",
    "delay": "Oneskorenie",
    "credit": "Kredit",
    "livemode": "naživo",
    "paused": "Pozastavené",
    "debug": "Debug",
    "token": "Token",
    "status": "Postavenie",
    "courier": "Kuriér",
    "track": "Sledovať",
    "track_order": "Sledovanie objednávky",
    "cost": "náklady",
    "receipt": "Potvrdenie",
    "origin": "Pôvod",
    "destination": "Destinácia",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "Nedostatok zásob!",
    "sub_total": "Medzisúčet",
    "customer": "Zákazník",
    "delivery": "Doručenie",
    "online_orders": "Online objednávky",
    "pos_orders": "POS objednávky",
    "chips": "Lupienky",
    "subscribed": "Predplatné",
    "unsubscribed": "Zrušený odber",
    "last_login": "Posledné prihlásenie",
    "join_at": "Pridať dátum",
    "club": "Klub",
    "buyer": "kupujúci",
    "seller": "Predávajúci",
    "or": "Alebo",
    "type": "Typ",
    "condition": "Podmienka",
    "brand": "Značka",
    "attempt": "Pokus",
    "error": "Chyba",
    "success": "Úspech",
    "fail": "Neúspech",
    "inventory": "Inventár",
    "link": "Odkaz",
    "visits": "Návštevy",
    "transactions": "Transakcie",
    "vat": "VAT",
    "pos_vat": "POS DPH",
    "sort_by": "Triediť podľa..",
    "from": "Od",
    "from_lead_time": "V priebehu nasledujúcich {hours} hodín",
    "no_credit_card_info": "Žiadne informácie o karte!",
    "active": "Aktívne",
    "not_active": "Nie je aktivované!",
    "referrals": "Odporúčania",
    "dashboard": "Dashboard",
    "more": "Viac",
    "inactive": "neaktívne",
    "developer": "Vývojár",
    "setting": "Nastavenie",
    "membership_conditions": "Podmienky členstva",
    "customers": "zákazníkov",
    "created_at": "Dátum vytvorenia",
    "updated_at": "Posledná aktualizácia",
    "register_at": "Dátum registrácie",
    "old": "Starý",
    "new": "Nový",
    "start": "Štart",
    "end": "Koniec",
    "pos": "POS",
    "out_of_stock": "Vypredané",
    "fake": "falošný",
    "low_inventory_warning": "Pozor, nízke zásoby!",
    "webhook": "Webhook",
    "notification": "Oznámenie",
    "sms": "SMS",
    "online_payment_link": "Odkaz na online platbu",
    "waiting_load_data": "Čaká sa na načítanie údajov..",
    "views": "Názory",
    "sales": "Predaj",
    "total_views": "Celkové pozretia",
    "total_sales": "Celkové predaje",
    "from_previous_n_days": "Z posledných {days} dní",
    "drop_shipping": "Dropshipping",
    "commission": "Komisia",
    "shipping_area": "Oblasť prepravy",
    "main_seller": "Hlavný predajca",
    "domain": "doména",
    "contact": "Kontaktné informácie",
    "wallet": "Peňaženka",
    "reseller": "Predajca",
    "tracking_code": "Sledovací kód",
    "tracking_url": "Sledovacia adresa URL",
    "fulfillments": "Splnenia",
    "reject": "Odmietnuť",
    "reserved": "Rezervované",
    "score": "skóre",
    "customer_price": "Zákaznícka cena",
    "options": "možnosti",
    "show_details": "Zobraziť podrobnosti",
    "no_data": "Žiadne dáta..",
    "waiting": "Čakanie...",
    "waiting_connecting_payment": "Čaká sa na platobnú službu...",
    "creating_secure_payment": "Vytvorenie bezpečnej platby.",
    "officer": "dôstojník",
    "ticket": "Lístok",
    "ticket_url": "Adresa URL lístka",
    "closed_at": "Zatvorené o",
    "close_ticket": "Zavrieť lístok",
    "reopen_ticket": "Znovu otvorte lístok",
    "require": "Vyžadovať*",
    "search": "Vyhľadávanie...",
    "language": "Jazyk",
    "tasks": "Úlohy",
    "permissions": "Povolenia",
    "finish_date": "Dátum ukončenia",
    "complete_date": "Dátum vyplnenia",
    "settle_date": "Dátum osídlenia",
    "cost_span": "Cenové rozpätie",
    "industry": "priemysel",
    "rating": "hodnotenia",
    "rates": "Hodnotenie",
    "seen_at": "Videné na",
    "completed": "Dokončené",
    "you": "vy",
    "shop": "Obchod",
    "store": "obchod",
    "granted": "Udelené",
    "deny": "Popierať",
    "request": "Žiadosť",
    "expert": "Expert",
    "response": "odpoveď",
    "requests": "Žiadosti",
    "experts": "Odborníci",
    "responses": "Odpovede",
    "negotiations": "Rokovania",
    "all_chats": "Všetky chaty",
    "chats": "Chaty",
    "tags": "Tagy",
    "description": "Popis",
    "rates_count": "Počet hodnotení",
    "rate": "Hodnotenie",
    "comment": "Komentujte",
    "chat": "Chat",
    "install": "Inštalácia",
    "edited": "Upravené",
    "undo": "Vrátenie späť",
    "redo": "Znovu",
    "male": "Muž",
    "female": "Žena",
    "calculator": "Kalkulačka",
    "catalog": "Katalóg",
    "max_height": "Maximálna výška",
    "images_compare": "Porovnanie obrázkov",
    "canvas": "Plátno",
    "table_of_contents": "Obsah",
    "comments": "Komentáre",
    "badge_codes": "Kód odznakov",
    "need_more": "Potrebovať viac?",
    "invite_glow_caption": "Získajte 14,9 $ za každého priateľa!",
    "register_free": "100% bezplatná registrácia",
    "gift": "Darček",
    "google": "Google",
    "facebook": "Facebook",
    "instagram": "Instagram",
    "instashop": "Instashop",
    "show": "Šou",
    "hide": "Skryť",
    "waiting_review": "Čaká sa na posúdenie",
    "not_selected": "Nevybraté",
    "time": "čas",
    "final_price": "Konečná cena",
    "starting_price": "Vyvolávacia cena",
    "day": "deň",
    "paid": "Zaplatené",
    "service_bill": "Platba faktúry",
    "avocado": "Avokádo",
    "delivery_price": "Náklady na dopravu",
    "select_address": "Vyberte adresu",
    "image": "Obrázok",
    "view": "vyhliadka",
    "sell": "zľava",
    "hyper": "Hyper",
    "cart_list": "Košík",
    "barcode_scanner": "Skener čiarového kódu",
    "scan_qr_code": "Naskenujte QR kód",
    "new_carts": "Nové vozíky",
    "pays": "Platby",
    "annually": "Ročne",
    "sells": "Predaj",
    "articles": "články",
    "jobs": "Práca",
    "job": "Job",
    "blog": "Blog",
    "deleted_at": "Vymazané o",
    "capacity": "Kapacita",
    "download_at": "Dátum posledného stiahnutia",
    "downloads": "K stiahnutiu",
    "usage": "Použitie",
    "select_upload_file": "Vyberte alebo pustite súbor",
    "download_link": "Odkaz na stiahnutie",
    "uploading": "Nahráva sa...",
    "files": "Súbory",
    "star": "Hviezda",
    "speed": "Rýchlosť",
    "feedback": "Spätná väzba",
    "new_messages": "Nové správy",
    "file": "Súbor",
    "attachment": "Príloha",
    "gallery": "Galéria",
    "sync": "Synchronizovať",
    "diff_time": "Časový posun",
    "network": "sieť",
    "account": "účtu",
    "configuration": "Konfigurácia",
    "blockchain": "Blockchain",
    "blog_link": "Odkaz na blog",
    "community": "Spoločenstva",
    "critical_zone": "Kritická zóna",
    "statistics": "Štatistiky",
    "access": "Prístup",
    "seo": "SEO",
    "followers": "Nasledovníci",
    "followings": "Sledovaní",
    "private": "Náhľad",
    "soon": "Čoskoro",
    "features": "Vlastnosti",
    "bot": "Bot",
    "sample": "Ukážka",
    "how_it_work": "Ako to funguje?",
    "page": "Stránka",
    "congratulations": "gratulujem",
    "recommend": "Odporučiť",
    "recommended": "Odporúčané",
    "recoms": "Odporúčania",
    "likes": "Páči sa mi",
    "clicks": "Kliknutia",
    "platform": "Plošina",
    "cms": "CMS",
    "cash": "Hotovosť",
    "dir_payment": "bankový prevod",
    "auto_complete": "Automaticky dokončené",
    "compare": "Porovnaj",
    "infinite": "Nekonečné",
    "tips": "Tipy",
    "technical": "Technická",
    "finance": "Financie",
    "your_phone_input": "Zadajte telefónne číslo",
    "income": "príjem",
    "change": "Zmeniť",
    "new_users": "Noví používatelia",
    "success_orders": "Úspešné objednávky",
    "direct": "Priamy",
    "last_activity": "Posledná aktivita",
    "landing": "Pristátie",
    "now": "Teraz",
    "accept_agreement": "Prečítal som si podmienky a súhlasím s nimi.",
    "report": "správa",
    "tablet": "Tablet",
    "pc": "PC",
    "acquisition_channel": "Akvizičný kanál",
    "to": "Komu",
    "info": "Info",
    "general": "generál",
    "upload": "Nahrať",
    "general_config": "Všeobecná konfigurácia",
    "limits_config": "Obmedzenia",
    "design_config": "Dizajn a štýl",
    "duration_config": "Obmedzenie trvania",
    "constraints_config": "Limity spôsobilosti",
    "clubs_config": "Dostupné v kluboch",
    "additional_config": "Ďalšie konfigurácie",
    "import": "Importovať",
    "ribbon": "Stuha",
    "countries": "krajiny",
    "edit": "Upraviť",
    "delete": "Odstrániť",
    "analytics": "Analytics",
    "rules": "pravidlá",
    "unset": "Nie je nastavené",
    "carts": "Vozíky",
    "optional": "Voliteľné",
    "design": "Dizajn",
    "filter": "Filter",
    "send": "Odoslať",
    "approved": "Schválené",
    "unit": "Jednotka",
    "profile": "profilu",
    "shipping_rates": "Sadzby za dopravu",
    "package": "Balíček",
    "overview": "Prehľad",
    "live": "naživo",
    "never": "Nikdy",
    "always": "Vždy",
    "mandatory": "Povinné",
    "expire_at": "Dátum spotreby",
    "position": "pozícia",
    "channel": "kanál",
    "age": "Vek",
    "charge": "Nabite",
    "giftcard": "Darčeková karta",
    "acquisition": "Akvizícia",
    "conversion": "Konverzia",
    "total_payments": "Celkové platby",
    "community_ask": "Pýtajte sa v komunite",
    "children": "deti",
    "export": "Export",
    "list": "Zoznam",
    "hierarchy": "Hierarchia",
    "images": "snímky",
    "demo": "Demo",
    "author": "Autor",
    "designer": "Dizajnér",
    "max": "Maximálne",
    "accepted": "Prijatý",
    "reply": "Odpovedzte",
    "reviewed": "Skontrolované",
    "restored": "Obnovené",
    "merchant": "Obchodník",
    "per_product": "Na produkt",
    "journey": "Cesta",
    "after": "Po",
    "waiting_for_payment": "Dokončite platbu...",
    "hour": "hodina",
    "minute": "Minúta",
    "premium": "Premium",
    "light": "Svetlo",
    "dark": "Tmavý",
    "guest": "Hosť",
    "shops": "Obchody",
    "vendor": "Predajca",
    "vendors": "Predajcovia",
    "marketplace": "Trhovisko",
    "verify_date": "Overte dátum",
    "note": "Poznámka",
    "panel": "Panel",
    "removed": "Odstránený",
    "segments": "Segmenty",
    "personal_info": "Osobné informácie",
    "preferences": "Predvoľby",
    "spec": "Špec",
    "reviews": "Recenzie",
    "constraints": "Obmedzenia",
    "flexible": "Flexibilné",
    "usage_limit": "Limit použitia",
    "temporary": "Dočasné",
    "original": "Originál",
    "saved": "Uložené!",
    "sort": "Triediť",
    "documents": "Dokumenty",
    "document": "Dokument",
    "please_wait": "Prosím čakajte...",
    "pickup": "Zdvihnúť",
    "customize": "prispôsobiť",
    "difficulty": "Obtiažnosť",
    "banned": "Zakázané",
    "company": "Spoločnosť",
    "tax_shipping": "Prepravná daň",
    "warranty": "Záruka",
    "return_policy": "Pravidlá vrátenia",
    "guide": "Sprievodca",
    "translate": "Preložiť",
    "public": "Verejné",
    "deleted": "Odstránené",
    "variant": "Varianta",
    "secure": "Zabezpečiť",
    "admin": "Admin",
    "tax_included_abstract": "vrátane",
    "payment_not_settled": "Platba neuhradená!",
    "orders_list": "Zoznam objednávok",
    "subscription_plan": "Plán predplatného",
    "contents": "Obsah",
    "pricings": "Ceny",
    "static_page": "Statická stránka",
    "shop_button": "Tlačidlo Shop",
    "embed": "Vložiť",
    "over": "Koniec",
    "tax_vary_by_location": "meniť. umiestnenie",
    "product_type": "Typ produktu",
    "tax_id": "DIČ",
    "business_name": "Obchodné meno",
    "invoice": "Faktúra",
    "included_in_the_product": "Zahrnuté v produkte",
    "included_in_the_product_description": "Produkt obsahuje nasledujúce komponenty",
    "cross_sell": "Krížový obchod",
    "discount_off": "OFF",
    "extra_discount": "Extra zľava",
    "template": "Šablóna",
    "in_cart": "V košíku",
    "pros_and_cons": "Klady a zápory",
    "related_products": "Súvisiace produkty",
    "related_categories": "Súvisiace kategórie",
    "badges": "Odznaky",
    "explore": "Preskúmať",
    "updated": "Aktualizované",
    "bank_name": "Meno banky",
    "bank_account_number": "Číslo bankového účtu",
    "bank_routing_number": "Bankové smerovacie číslo",
    "bank_branch_address": "Adresa pobočky banky",
    "bank_account_name": "Celé meno vlastníka účtu",
    "valuation": "Oceňovanie",
    "cluster": "Cluster",
    "clusters": "Zhluky",
    "subscriptions": "Predplatné",
    "spam": "Nevyžiadaná pošta",
    "video": "Video"
  },
  "dialogs": {
    "delete": {
      "title": "Odstrániť",
      "message": "Naozaj chcete odstrániť túto položku?",
      "action": "Áno, vymazať teraz"
    }
  },
  "actions": {
    "add_to_cart": "Pridať do košíka",
    "cancel": "Zrušiť",
    "update": "Aktualizovať",
    "add": "Pridať",
    "delete": "Odstrániť",
    "new": "Nový",
    "save_continue": "Uložiť a pokračovať",
    "save": "Uložiť",
    "save_changes": "Uložiť zmeny",
    "change": "Zmeniť",
    "continue": "ďalej",
    "close": "Zavrieť",
    "finish": "Skončiť",
    "poll": "Anketa",
    "view": "vyhliadka",
    "edit": "Upraviť",
    "next": "Ďalšie",
    "previous": "Predchádzajúce",
    "create": "Vytvorte",
    "set": "nastaviť",
    "find": "Nájsť",
    "accept": "súhlasiť",
    "reject": "Odmietnuť",
    "back": "späť",
    "pay": "zaplatiť",
    "pay_now": "Zaplatiť teraz",
    "print": "Tlačiť",
    "return": "Návrat",
    "publish": "Publikovať",
    "confirm": "Potvrďte",
    "copy": "Kopírovať",
    "submit": "Predložiť",
    "send": "Odoslať",
    "yes": "Áno",
    "no": "č",
    "meh": "Hmm",
    "clear": "jasný",
    "dismiss": "Odmietnuť",
    "search": "Vyhľadávanie",
    "deselect_all": "Odznačiť všetko",
    "select_all": "Vybrať všetko",
    "refresh": "Obnoviť",
    "verify": "Overiť",
    "play": "hrať",
    "open": "OTVORENÉ",
    "calculate": "Vypočítajte",
    "quick_buy": "Rýchly nákup",
    "click_here": "Kliknite tu",
    "schedule": "Rozvrh",
    "send_now": "Poslať teraz",
    "download": "Stiahnuť ▼",
    "reset_default": "Obnoviť pôvodné nastavenia",
    "reset": "Resetovať",
    "check": "Skontrolujte",
    "cod_payment": "Platba na dobierku",
    "dir_payment": "Prevod peňazí",
    "online_payment": "Online platba",
    "checkout": "Odhlásiť sa",
    "show_all": "Ukázať všetko",
    "login": "Prihlásiť sa",
    "logout": "Odhlásiť sa",
    "more": "Viac..",
    "collapse": "kolaps",
    "apply_change": "Aplikovať zmeny",
    "apply": "Použiť",
    "add_giftcard": "Pridať darčekovú kartu",
    "charge": "Nabite",
    "send_invites": "Posielajte pozvánky",
    "past": "Minulosť",
    "restore": "Obnoviť",
    "cut": "Vystrihnúť",
    "get_sms_code": "Získajte overovací kód",
    "register_no_mail": "Pokračujte bez e-mailu",
    "no_mail_register_message": "Nemáte e-mailovú adresu alebo ste zabudli heslo?",
    "reset_by_mail": "Obnovenie hesla e-mailom",
    "reset_by_sms": "Obnovenie hesla pomocou SMS",
    "cash_payment": "Platba v hotovosti",
    "show_chart": "Zobraziť graf",
    "open_app": "Otvorte aplikáciu",
    "login_now": "Prihlás sa teraz",
    "watch_video": "Pozeraj video",
    "check_now": "Skontroluj teraz",
    "remove_image": "Odstrániť obrázok",
    "view_website": "Otvoriť odkaz",
    "explore": "Preskúmať {name}",
    "go": "Choď",
    "read_more": "Čítaj viac",
    "start_now": "Začnite teraz – je to zadarmo",
    "view_live": "Zobraziť naživo",
    "resend_code": "Znova odoslať kód",
    "invite": "pozvať",
    "add_more": "Pridať VIAC",
    "install_now": "Nainštalovať teraz",
    "uninstall": "Odinštalovať",
    "show_preview": "Zobraziť náhľad",
    "hide_preview": "Skryť ukážku",
    "download_now": "Stiahni teraz",
    "auto_fill": "Automatické dopĺňanie",
    "track": "Sledovať",
    "change_state": "Zmeniť stav",
    "done": "hotový",
    "reply": "Odpovedzte",
    "watch_now": "Sledovať teraz",
    "unlock": "Odomknúť",
    "lock": "Zámok",
    "create_clone": "Vytvorte klon",
    "regenerate": "Regenerovať",
    "add_message": "Pridať správu",
    "continue_chat": "Pokračovať v chate",
    "add_new_message": "Pridať novú správu",
    "change_setting": "Zmeňte nastavenie",
    "delete_all": "Vymazať všetko",
    "transfer_fund": "Prevodový fond",
    "reverse_fund": "Reverzný fond",
    "settlement": "Osídlenie",
    "refund": "Vrátenie peňazí",
    "partial_refund": "Čiastočné vrátenie peňazí",
    "change_payment_method": "Zmeňte spôsob platby",
    "buy": "Kúpiť",
    "view_all": "Zobraziť všetko",
    "view_now": "Zobraziť teraz",
    "paste": "Prilepiť"
  },
  "instance_message_title": "Odoslať okamžitú správu",
  "instance_message": "Dobrý deň, {name}, volám sa {author} zo spoločnosti {company}.",
  "errors": {
    "419": "Boli ste dlho neaktívni, z bezpečnostných dôvodov <b>⟳ OBNOVTE STRÁNKU</b> .",
    "gateway_blockchain_sync_error": "Systém sa nesynchronizuje s blockchainom. Novú transakciu nebude možné vytvoriť, kým nebudú dokončené synchronizácie našich serverov. Problém riešime.",
    "gateway_network_error": "Služba platobnej brány zaznamenala problém s komunikáciou."
  },
  "receiver_info": {
    "map": {
      "title": "Dodacia adresa",
      "confirm": "Nastaviť polohu",
      "address_type": "Destinácia",
      "receptor_type": "Prijímač"
    },
    "receiver_address": "Vyberte dodaciu adresu",
    "address": "adresu",
    "postcode": "PSČ",
    "enter_value": "Vyplňte tu",
    "address_note": "Poznámka",
    "tel": "Kontaktné číslo",
    "service_address": "Vyberte svoju adresu"
  },
  "weight": {
    "g": "g",
    "oz": "oz",
    "lb": "lb",
    "kg": "kg"
  },
  "mass_unit_name": {
    "g": "gram",
    "oz": "unca",
    "lb": "Pound",
    "kg": "kilogram"
  },
  "length": {
    "cm": "cm",
    "in": "v",
    "ft": "ft",
    "mm": "mm",
    "m": "m",
    "yd": "yd"
  },
  "size_unit_name": {
    "cm": "Centimetre",
    "in": "palec",
    "ft": "Noha",
    "mm": "milimeter",
    "m": "meter",
    "yd": "Dvor"
  },
  "distance": {
    "m": "meter",
    "km": "km"
  },
  "time": {
    "days": "Dni",
    "hours": "hodiny",
    "minutes": "Minúty",
    "seconds": "sekúnd"
  },
  "units": [
    "Jednotka",
    "položka",
    "každý",
    "nastaviť",
    "kus",
    "kilogram",
    "gram",
    "miligram",
    "meter",
    "milimeter",
    "meter štvorcový",
    "štvorcových stôp",
    "meter kubický",
    "liter",
    "mililitra",
    "nohy",
    "galónov",
    "palce",
    "unca",
    "libier",
    "kvart",
    "yardov",
    "miestnosť",
    "sekúnd",
    "minút",
    "hodiny",
    "dni",
    "týždňov",
    "mesiacov",
    "rokov"
  ],
  "region_types": {
    "State": "Štát",
    "Territory": "Územie",
    "Province": "Provincie"
  },
  "transaction_status": {
    "RequireAction": "Vyžaduje sa akcia",
    "Processing": "Spracovanie",
    "Canceled": "Zrušené",
    "Succeeded": "Podarilo sa"
  },
  "placeholders": {
    "name": "Jone Cox",
    "email": "vasa-mail@mail.com",
    "phone": "+1 000 0000",
    "language": "Zvoľ jazyk..",
    "friend_email": "E-mail vášho priateľa...",
    "friend_name": "Opt. Meno tvojho priateľa",
    "select_date": "Vyberte dátum..."
  },
  "notification": {
    "confirm": "Potvrďte",
    "confirm_message": "Zmeny boli úspešne uložené.",
    "error": "Chyba",
    "message": "Správa",
    "caution": "Pozor",
    "warning": "POZOR",
    "award": "gratulujem",
    "error_message": "Žiaľ, vyskytla sa chyba.",
    "congratulation": "gratulujem",
    "coming_soon": "Čoskoro",
    "on_fetching_data": "Prijímanie informácií..",
    "new_pwa_version": "Teraz je k dispozícii nová verzia. Chcete aktualizovať aplikáciu?",
    "over_license_limit": "Prekročenie licenčného limitu",
    "update_license": "Aktualizujte svoju licenciu",
    "required": "Požadovaný",
    "invalid_email": "Neplatný email",
    "invalid_domain": "Neplatná doména",
    "invalid_min_length": "Minimálna dĺžka musí byť {length}",
    "invalid_min_array_length": "Vyberte aspoň {length} položiek",
    "invalid_max_chars": "Max. počet znakov: {maxCount}",
    "invalid_url": "neplatná URL adresa",
    "country_invalid": "Vyberte cieľovú krajinu!",
    "postal_code_invalid": "Nastavte platné poštové smerovacie číslo!"
  },
  "colors": {
    "#D32F2F": "Červená",
    "#C2185B": "Ružová",
    "#7B1FA2": "Fialová",
    "#512DA8": "Tmavofialová",
    "#303F9F": "Indigo modrá",
    "#1976D2": "Modrá",
    "#0288D1": "Svetlo modrá",
    "#0097A7": "Tyrkysovo modrá",
    "#00796B": "Husi zelená",
    "#388E3C": "zelená",
    "#689F38": "Svetlo zelená",
    "#AFB42B": "Limuzína",
    "#FBC02D": "žltá",
    "#FFA000": "Amber",
    "#F57C00": "Oranžová",
    "#E64A19": "Lesklá oranžová",
    "#5D4037": "Hnedá",
    "#616161": "Šedá",
    "#455A64": "Šedá modrá",
    "#FFD700": "Zlatý",
    "#C0C0C0": "Strieborná",
    "#b76e79": "Zlatá ruža",
    "#383838": "Matná čierna",
    "#FFFFFF": "biely",
    "#FFF": "biely",
    "#000000": "čierna",
    "#000": "čierna",
    "#7d263a": "Maroon",
    "#FD9F17": "Zlato",
    "#229DBF": "Aqua",
    "#6DC9E2": "Aqua Triblend",
    "#413B2D": "armády",
    "#474747": "Asfalt",
    "#E6195C": "Berry",
    "#B2184C": "Berry Triblend",
    "#FC7F5F": "Spálený pomaranč",
    "#80011F": "kardinál",
    "#382829": "Čokoláda",
    "#F06336": "Coral",
    "#FAE7C9": "Krém",
    "#6B2257": "Ríbezle",
    "#222127": "Tmavošedý",
    "#0D5A74": "Deep Teal",
    "#00582F": "Evergreen",
    "#214C30": "les",
    "#DC2867": "Fuchsiová",
    "#38561F": "Kelly",
    "#5C884D": "List",
    "#558450": "Svetlá Aqua",
    "#96B5C9": "Svetlo modrá",
    "#DCAFCE": "Lilac",
    "#D3E1A4": "Limetka",
    "#9DE7C2": "mäta",
    "#F6EAD2": "Prirodzené",
    "#1A1F35": "námorníctvo",
    "#404624": "Olivový",
    "#271020": "Slivka",
    "#A8355C": "Malina",
    "#D6BEA6": "Mäkký krém",
    "#BEA994": "Tan",
    "#0DB2AE": "Modrozelený",
    "#A86EA9": "fialový",
    "#36454F": "Drevené uhlie",
    "#b3b0ab": "uhlíková sivá",
    "#463e3d": "Charcoal Heather",
    "#282d3c": "Navy Blazer"
  },
  "address_info": {
    "name": "názov",
    "tel": "Telefón",
    "email": "Email",
    "country": "Krajina",
    "city": "Mesto",
    "state": "Štát",
    "address": "adresu",
    "building_number": "Číslo budovy",
    "building_unit": "Jednotka",
    "postcode": "PSČ",
    "note": "Poznámka",
    "county": "County"
  },
  "product_types": {
    "physical": "Fyzické",
    "physical_description": "Fyzické produkty ako: mobilné telefóny, knihy, elektronické súčiastky.",
    "virtual": "Virtuálne",
    "virtual_description": "Internetové produkty ako: dobíjacia karta, hotelová rezervácia, dobíjanie hry.",
    "file": "Súbor",
    "file_description": "Všetky povolené súbory, ako napríklad video z online kurzu, dokumenty na stiahnutie.",
    "service": "servis",
    "service_description": "Služby ako: oprava, doprava, výučba.",
    "subscription": "Predplatné",
    "subscription_description": "Predplatné a fakturácia za produkty, služby alebo obsah."
  },
  "license": {
    "free": "zadarmo",
    "startup": "Začiatok",
    "company": "Spoločnosť",
    "enterprise": "Enterprise"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "Mužovi",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW",
    "GHS": "GHS",
    "ZWD": "ZWD",
    "IQD": "IQD",
    "SYP": "SYP"
  },
  "variants": {
    "color": "Farba",
    "volume": "Veľkosť",
    "count_in_pack": "Počítajte v balení",
    "weight": "Hmotnosť",
    "type": "Materiál",
    "style": "Štýl"
  },
  "delivery_state": {
    "check_queue": "Čaká sa na posúdenie",
    "order_confirm": "Potvrdenie objednávky",
    "preparing_order": "Príprava",
    "sent_order": "Na doručenie",
    "to_customer": "Doručené"
  },
  "status": {
    "unpaid": "Nezaplatené",
    "paid": "Zaplatené",
    "canceled": "Zrušené",
    "completed": "Usadený",
    "reserved": "Rezervované",
    "COD": "COD",
    "sold": "Predané",
    "open": "OTVORENÉ",
    "cancel": "Zrušené",
    "active": "Aktívne",
    "inactive": "neaktívne",
    "debug": "Debug",
    "live": "naživo",
    "test": "Test",
    "connected": "Pripojené",
    "disconnected": "Odpojené",
    "accept": "súhlasiť",
    "reject": "Odmietnuť",
    "pending": "Čaká na spracovanie",
    "rejected": "Odmietnuté",
    "accepted": "Prijatý"
  },
  "dimensions": {
    "cm": "cm",
    "km": "km",
    "kg": "kg"
  },
  "transportation_type": {
    "motorbike": "Motorka",
    "motorbike_description": "Stredná hmotnosť do niekoľkých kilometrov.",
    "cargo_small": "Malý náklad",
    "cargo_small_description": "Viackilometrový ľahký náklad.",
    "cargo": "Náklad",
    "cargo_description": "Stredná hmotnosť do niekoľkých kilometrov.",
    "truck": "Nákladné auto",
    "truck_description": "Hromadný alebo ťažký náklad v rámci krajiny.",
    "fast_post": "Rýchla pošta",
    "fast_post_description": "Rýchle zaslanie poštou.",
    "post": "Normálny príspevok",
    "post_description": "Bežná pošta cez poštu.",
    "airplane": "Letecká pošta",
    "airplane_description": "Domáci a zahraničný ľahký a stredný náklad.",
    "bicycle": "Čisté odoslanie",
    "bicycle_description": "Ľahký náklad v okruhu niekoľkých stoviek yardov od nemotorových vozidiel.",
    "global": "Globálna doprava",
    "global_description": "Preprava do zahraničia letecky, po mori alebo po súši.",
    "pickup": "Zdvihnúť",
    "pickup_description": "Zákazníci si vyzdvihnú položky vo vašej kamennej predajni alebo sklade."
  },
  "article": {
    "login_to_see_error": "Pre prístup k článku sa prihláste",
    "create_new_action": "Vytvorte nový obsah",
    "menu_title": "Ponuka",
    "menu": {
      "edit": "Režim úprav",
      "view_mode": "Režim zobrazenia",
      "delete": "Odstrániť článok"
    },
    "schedule_action": "Chcete naplánovať zverejnenie?",
    "schedule_title": "Naplánujte automatické zverejnenie",
    "edit_mode": "Upraviť",
    "public_view_mode": "Verejný pohľad",
    "publish_at": "Zverejniť na",
    "published": "Publikovaný",
    "draft": "Návrh",
    "saving": "Ukladanie",
    "save_and_publish_action": "Uložiť a publikovať",
    "save_draft_action": "Uložiť koncept",
    "private": "Súkromné",
    "public": "Verejné",
    "category_input": "Kategória",
    "category_input_message": "Vyberte kategóriu článku",
    "parent_input": "Rodičovská kategória",
    "parent_input_message": "Vyberte obsah otca",
    "schedule_input": "Rozvrh",
    "schedule_input_placeholder": "Ak chcete, aby bol príbeh zverejnený v konkrétnom čase.",
    "schedule_view_action": "Zobraziť plán publikovania",
    "author_title": "Napísané",
    "read_time": "Čas na učenie",
    "read_time_unit": "Minúty",
    "claps_action": "Claps",
    "claps": "Claps",
    "likes": "Páči sa mi to",
    "about_author": "O autorovi",
    "updated_at": "Aktualizované",
    "wrote_at": "Napísané o",
    "now": "Teraz",
    "follow_action": "Nasledujte",
    "followed": "Sledované",
    "report_and_delete_action": "Nahláste a vymažte tento článok",
    "report_action": "Nahlásiť obťažovanie",
    "you_reported_this_article": "Tento článok už obsahuje hlásenie o zneužití.",
    "add_to_publication_action": "Pridať do publikácie",
    "author_socials": "Autor na sociálnych sieťach",
    "share": "zdieľam",
    "report_dialog": {
      "report_and_delete_title": "Nahláste zneužitie a odstráňte obsah",
      "report_title": "Nahláste tento obsah ako urážlivý",
      "message": "Aký je dôvod odoslania tohto obsahu? Vyberte jednu z nasledujúcich možností.",
      "accept_and_delete_action": "Potvrďte a odstráňte obsah"
    },
    "schedule_dialog": {
      "title": "Plán vydania obsahu",
      "publish_at": "Zverejniť na",
      "last_edit": "Posledná úprava",
      "view_action": "Zobraziť článok"
    },
    "notifications": {
      "update_success_title": "Odoslať informácie",
      "update_success": "Článok bol úspešne aktualizovaný.",
      "update_error": "Zadané informácie nie sú platné.",
      "delete_error": "Tento článok nemôžete vymazať!",
      "report_and_delete_success_title": "Nahlásiť a vymazať",
      "report_and_delete_success_message": "Článok bol úspešne odstránený.",
      "report_success_title": "Reportážny článok",
      "report_success_message": "Vaša správa k tomuto článku bola uverejnená."
    },
    "alert": {
      "delete_article": {
        "title": "Odstrániť článok",
        "message": "Naozaj chcete natrvalo odstrániť tento článok?",
        "action": "Odstrániť"
      }
    },
    "edit_window": {
      "title": "Vyberte Text obrázka a Súhrn",
      "digest": "Zhrnutie"
    },
    "editor": {
      "title_placeholder": "Názov..",
      "body_placeholder": "Napíšte skvelý obsah..",
      "accept_file_types_error": "Tento formát súboru je neprijateľný:",
      "max_file_size_error": "Tento súbor je príliš veľký:",
      "notifications": {
        "image_uploaded_success": "Obrázok bol úspešne uložený",
        "image_uploaded_failed": "Chyba pri načítavaní obrázka."
      },
      "embed_placeholder": "Zadajte kód iframe, Facebook, Youtube alebo akúkoľvek inú URL a stlačte enter.",
      "embed_caption_placeholder": "Zadajte názov (voliteľné)",
      "images_caption_placeholder": "Zadajte názov pre tento obrázok.."
    }
  },
  "article_report": {
    "inappropriate": "Obsah tohto článku je nevhodný.",
    "fake": "Toto je falošné a klamlivé.",
    "spam": "Táto položka bola spamovaná a skopírovaná.",
    "scam": "Dá sa očakávať, že to spôsobí malvér, vírusy alebo zlyhanie systému.",
    "hacked": "Zdá sa, že táto stránka bola napadnutá.",
    "offensive": "Jazykový obsah a slovná zásoba sú neetické a neúctivé.",
    "violent": "Myslím si, že tento obsah obsahuje pornografiu a je v rozpore so zákonmi.",
    "harassment": "Toto je podľa mňa rasistické.",
    "hate": "Myslím si, že ide o propagáciu násilia.",
    "infringe": "To porušuje moje práva."
  },
  "comments": {
    "new_action": "Kliknutím zanecháte komentár..",
    "title": "Komentáre",
    "body_placeholder": "Váš komentár alebo správa",
    "send_action": "Odoslať komentár",
    "body_is_empty_error": "Komentár je prázdny!",
    "comments": "Komentáre",
    "no_comments": "Napíšte prvý komentár...",
    "load_more_action": "Získajte viac komentárov..",
    "cant_send_comment": "Nemôžete pridať nový príspevok.",
    "cant_remove_this_comment": "Tento komentár nemôžete odstrániť!",
    "product_buyer": "kupujúci",
    "delete_alert": {
      "title": "Odstrániť komentár",
      "message": "Chcete odstrániť tento komentár?",
      "action": "Odstrániť"
    },
    "notifications": {
      "delete_success": "Váš komentár bol úspešne odstránený."
    },
    "first_send": "Prvý príspevok",
    "comment_at": "zapnuté",
    "edit_comment": "Upraviť komentár",
    "my_comments": "Moje komentáre"
  },
  "customer_club": {
    "bronze": "Bronzová",
    "silver": "Strieborná",
    "gold": "Zlatý",
    "platinum": "Platina",
    "diamond": "diamant"
  },
  "application_categories": {
    "tracking": "Kontrola správania používateľov",
    "payment": "Platba",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "Doprava",
    "automation": "automatizácia",
    "inventory": "Skladovanie",
    "accounting": "účtovníctvo",
    "marketing": "marketing",
    "advertising": "Reklama",
    "staff": "personál",
    "incentive": "Stimuly",
    "shop": "Obchod"
  },
  "social_network": {
    "instagram": "Instagram",
    "telegram": "telegram",
    "googleplay": "Google Play",
    "appstore": "Obchod s aplikaciami",
    "twitter": "Twitter",
    "linkedin": "Linkedin",
    "medium": "Stredná",
    "selldone": "Predané",
    "facebook": "Facebook",
    "pinterest": "Pinterest",
    "whatsapp": "WhatsApp",
    "skype": "Skype",
    "facebook_messenger": "Facebook Messenger"
  },
  "form_builder": {
    "add_item_action": "Pridať novú položku",
    "title_input": "Názov",
    "name_input": "Názov premennej",
    "value_input": "hodnoty",
    "value_input_message": "Zoznam možností používateľa",
    "default": "Predvolená hodnota",
    "types": {
      "simple": "Jednoduché",
      "selective": "Selektívne",
      "switch": "Prepínač",
      "file": "Súbor",
      "number": "číslo"
    },
    "placeholder_input": "Zástupný symbol",
    "file_type_input": "Prijateľné typy súborov",
    "file_type_message": "jpeg, png, zip, ..."
  },
  "virtual_order_info_summery": {
    "title": "Meno Produktu",
    "reserved_at": "dátum registrácie",
    "total_price": "Celková suma",
    "discount": "Zľava",
    "final_price": "Konečná suma",
    "payment_status": "Stav platby",
    "payment_status_waiting": "Čakanie na platbu",
    "payment_status_paid": "Zaplatené",
    "buyer": "kupujúci"
  },
  "virtual_item_info": {
    "title": "Virtuálna položka",
    "outputs": {
      "title": "Informácie o výstupe",
      "sub_title": "Dôverné informácie o tejto položke",
      "message": "Tieto informácie sa používateľovi zobrazia po zakúpení produktu."
    },
    "inputs": {
      "title": "Informácie sú povinné",
      "sub_title": "Informácie o kupujúcom sú povinné",
      "message": "Kupujúci musí do formulára zadať požadované údaje"
    },
    "notifications": {
      "inputs_set_success": "Informačný formulár bol úspešne zaregistrovaný.",
      "confirm_by_admin_success": "Dokončenie objednávky potvrdené.",
      "confirm_by_buyer_success": "Dokončenie objednávky potvrdené."
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "Túto objednávku nie je možné akceptovať platbou na dobierku.",
    "payment_returned": "Platba zo strany zákazníka je vrátená.",
    "payment_fraud": "Platba bola identifikovaná ako podvod.",
    "location_out_of_service": "Miesto zákazníka je mimo prevádzky.",
    "user_not_responding": "Zákazník neodpovedal na hovory.",
    "shop_owner_fault": "Pri vypĺňaní údajov sa vyskytla chyba personálu predajne.",
    "lack_of_inventory": "Vypredané.",
    "legal_restriction": "Nie je možné zadať objednávku z dôvodu zákonných obmedzení.",
    "pricing_fault": "Chyba v cene zo strany predajcu.",
    "system_fault": "Systémová chyba."
  },
  "basket_order_info_summery": {
    "receiver": "Prijímač",
    "phone": "Tel",
    "reserved_date": "Dátum nákupu",
    "total_price": "Celková suma",
    "discount": "Zľava",
    "final_price": "Konečná suma",
    "address": "Adresa dodania",
    "payment_status": "Stav platby"
  },
  "basket_status": {
    "open": "OTVORENÉ",
    "reserved": "Rezervované",
    "paid": "Zaplatené",
    "canceled": "Zrušené",
    "cod": "Platba pri doručení",
    "receipt_added": "Potvrdenie bolo pridané",
    "payment_processing": "Spracovanie platieb"
  },
  "basket_delivery_state": {
    "rejected": "Odmietnuté",
    "reject_reason_not_found": "Dôvod je neznámy.",
    "step_1": "Preskúmanie",
    "step_2": "Potvrdenie",
    "step_3": "Príprava",
    "step_4": "Na doručenie",
    "step_5": "Doručené"
  },
  "basket_return_request_view": {
    "title": "Žiadosť o vrátenie",
    "delivery_date": "Dátum doručenia",
    "return_date": "Dátum žiadosti",
    "items_count": "Počítajú sa vrátené položky",
    "items_count_unit": "položky",
    "reason": "Dôvod",
    "description": "Popis",
    "status": "Postavenie",
    "download_image": "Stiahnite si obrázok",
    "download_film": "Stiahnite si video",
    "download_voice": "Stiahnite si hlas",
    "accept_by_admin_action": "Prijmite požiadavku",
    "reject_by_admin_action": "Odmietnuť žiadosť",
    "message_for_admin": "Podľa zmluvy, ktorú ste prijali používaním Predaného, musíte kontaktovať kupujúceho a informovať ho o procese vrátenia jeho objednávky. Toto je potrebné urobiť, ak je žiadosť prijatá alebo zamietnutá a je získaný úplný súhlas kupujúceho.",
    "notifications": {
      "update_status_success": "Stav žiadosti bol aktualizovaný."
    }
  },
  "basket_list": {
    "return_count": "Návrat: {count} číslo",
    "table": {
      "row": "riadok",
      "image": "Obrázok",
      "product_name": "Produkt",
      "variant": "Varianta",
      "warranty": "Záruky",
      "count": "počítať",
      "price": "cena"
    }
  },
  "return_request_list": {
    "count": "Referenčné číslo",
    "return_warranty": "Garancia vrátenia peňazí",
    "return_warranty_unit": "Dni)",
    "table": {
      "code": "Objednávkový kód",
      "product": "Produkt",
      "delivery_at": "Dátum prijatia",
      "state": "Postavenie",
      "reason": "Dôvod",
      "return_warranty_period": "Záručná doba"
    }
  },
  "data_toolbar": {
    "search": "Vyhľadávanie",
    "sort_by": "Triediť podľa",
    "count_item": "Zobraziť položky ({item})."
  },
  "sort": {
    "created_at": "Vytvorte dátum",
    "updated_at": "Upraviť dátum",
    "title": "Názov",
    "description": "Popis",
    "like": "Popularita",
    "power": "Claps",
    "product_type": "Typ produktu",
    "discount": "Zľava",
    "rate": "Hodnotenie",
    "rate_count": "Počet hodnotení",
    "category": "Kategória",
    "product": "Produkt",
    "body": "Obsah",
    "card_type": "Typ karty",
    "card_number": "Číslo karty",
    "balance": "Zostatok",
    "paid": "Spotrebovaná suma",
    "currency": "mena",
    "expire_at": "Dátum spotreby",
    "discount_code": "Zľavový kód",
    "discount_percent": "Zľava",
    "discount_limit": "Zľavový limit",
    "max_count": "Maximálny počet",
    "used_count": "Použité",
    "start_date": "Dátum začiatku",
    "end_date": "Dátum ukončenia",
    "total_discount_amount": "Celkové zľavy",
    "initial_charge": "Počiatočný poplatok",
    "total_count": "Celkový počet",
    "amount_paid": "Čiastka vyplatená",
    "name": "názov",
    "published": "Publikovaný",
    "visits": "Návštevy",
    "color": "Farba",
    "landing_page": "Vstupná stránka",
    "enable": "Povoliť",
    "fix_commission": "Pevná provízia",
    "percent_commission": "Percentuálna provízia",
    "payment_at": "Dátum platby",
    "issued_at": "Dátum vydania",
    "payment": "Platba",
    "website": "webové stránky",
    "email": "Email",
    "user": "Používateľ",
    "code": "kód",
    "schedule_at": "Dátum plánu",
    "sender": "odosielateľ",
    "in_que": "V rade",
    "sent": "Odoslané",
    "shop": "Obchod",
    "quantity": "množstvo",
    "amount": "Suma",
    "jobs": "Úlohy sa počítajú",
    "success": "Počet úspechov",
    "fail": "Počet zlyhaní",
    "distance": "Vzdialenosť",
    "duration": "Trvanie",
    "reset_at": "Obnoviť dátum",
    "delivery_person": "Osoba",
    "delivery_service": "servis",
    "date": "Dátum",
    "order": "objednať",
    "order_id": "Číslo objednávky",
    "status": "Postavenie",
    "price": "cena",
    "count": "počítať",
    "final_price": "Konečná cena",
    "charge": "Nabite",
    "mention": "Spomenúť",
    "officer": "dôstojník",
    "registered": "Registrovaný",
    "purchased": "Kúpené",
    "sex": "rod"
  },
  "search_box": {
    "result": "Výsledky vyhľadávania",
    "tips": "Vyhľadajte produkty a kategórie",
    "label": "Vyhľadávanie ...",
    "category": "Kategória"
  },
  "lead_status": {
    "physical_fast_delivery": "Okamžité doručenie",
    "physical_under_24h_delivery": "Doručte do {lead} hodín",
    "physical_over_24h_delivery": "Pripravuje sa a odosiela sa od nasledujúcich {days} dní",
    "virtual_fast_prepare": "Okamžité doručenie",
    "virtual_under_24h": "Bude hotovo v priebehu nasledujúcich {lead} hodín",
    "virtual_over_24h": "Uskutoční sa od nasledujúcich {days} dní"
  },
  "return_request_state": {
    "pending": "Čaká na spracovanie",
    "accepted": "Potvrdené",
    "rejected": "Odmietnuté"
  },
  "return_order_reason": {
    "physical": {
      "U1": "Nesúlad produktu",
      "U2": "Žiadny produkt v prepravnom balení",
      "U3": "Rozbitie obalu alebo produktu",
      "U4": "Manipulácia s balíkom alebo sériovým číslom",
      "U5": "Niektoré položky z balíka chýbajú",
      "U6": "Produkt nie je originálny",
      "U7": "Produkt nespĺňa špecifikácie"
    }
  },
  "image_uploader": {
    "label": "Drag & Drop alebo <u>Select file</u>",
    "max_size": "Maximálna povolená veľkosť: {size}"
  },
  "timespan": {
    "Morning": "8:00 – 12:00",
    "Evening": "od 12:00 do 18:00",
    "Night": "18:00 – 12:00 hod",
    "Instant": "Okamžitý príspevok"
  },
  "week_day": {
    "Saturday": "sobota",
    "Sunday": "nedeľu",
    "Monday": "pondelok",
    "Tuesday": "utorok",
    "Wednesday": "streda",
    "Thursday": "štvrtok",
    "Friday": "piatok"
  },
  "payment_form": {
    "title": "Vyberte spôsob platby",
    "gift_cards_input": "Darčekové poukážky",
    "gift_cards_input_empty": "Nenašli sa žiadne darčekové poukážky..",
    "more": "Iné",
    "pay_amount_by_gift_cards": "Platba kartou Charge",
    "select_payment_method": "Vyberte si spôsob platby z nasledujúcich možností.",
    "payment_amount_remained": "Zostávajúca suma platby",
    "payment_amount": "Čiastka vyplatená",
    "all_paid_by_gift_cards": "Gratulujeme, za túto objednávku nemusíte platiť. Stlačte tlačidlo Zaplatiť darčekovou kartou.",
    "pay_by_gift_cards_action": "Zaplaťte objednávku platobnou kartou",
    "order_free_payment": "Gratulujeme, vaša objednávka je bezplatná!",
    "order_free_payment_action": "Objednajte si teraz zadarmo",
    "qr": {
      "address": "Platobná adresa",
      "amount": "Suma"
    }
  },
  "discount_input": {
    "limit": "Zľava {percent} % až do {limit} {currency}",
    "action": "Pridať zľavový kód",
    "code_input": "Zľavový kód",
    "notifications": {
      "add_success": "Gratulujeme, platný zľavový kód."
    }
  },
  "gift_card": {
    "inactive": "Karta je zakázaná",
    "expire": "Expirácia",
    "transfer": "Prestup",
    "send_to_friend": "Poslať priateľovi"
  },
  "count_down": {
    "days": "deň",
    "hours": "hodina",
    "minutes": "Minúty",
    "seconds": "sekúnd"
  },
  "gift_status": {
    "Unpaid": "Čaká sa na potvrdenie",
    "Paid": "Zaplatené",
    "Rejected": "Odmietnuté",
    "Canceled": "Zrušené"
  },
  "gift_program_status": {
    "Airdrop": "Platobný systém",
    "Advertising": "Reklama",
    "PersonalGift": "Osobný darček",
    "ShopGift": "Darčekový obchod"
  },
  "currency_selector": {
    "label": "mena"
  },
  "need_login": {
    "title": "Prihlásiť sa",
    "login_sms": "Prihlásenie cez SMS",
    "login_google": "Prihláste sa pomocou Google",
    "login_facebook": "Prihlásiť sa cez Facebook",
    "login_account": "Prihláste sa cez Soldone",
    "register": "Nový užívateľ? Zaregistrujte sa teraz.",
    "mobile_input": "Zadajte svoj mobil",
    "verification_code": "Overovací kód",
    "msg_title": "Ahoj,",
    "msg_body": "Prosím prihláste sa. Trvá to len pár sekúnd.",
    "login_apple": "Prihláste sa pomocou Apple",
    "login_email": "Prihláste sa emailom",
    "email_login_step_1": "Zadajte platnú e-mailovú adresu a my vám na ňu pošleme prihlasovací kód. Nie je potrebná žiadna registrácia.",
    "email_login_step_2": "Ste si istý, že ste svoju e-mailovú adresu zadali správne? Prihlasovací kód vám zašleme na uvedený e-mail, preto sa uistite, že je správnosť.",
    "email_login_step_3": "Na váš email sme poslali kód. Upozorňujeme, že platnosť kódu vyprší o 10 minút."
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "5-ročný obchod so zlatom"
    },
    "GOLDEN_2YEAR": {
      "name": "4-ročný obchod so zlatom"
    },
    "GOLDEN_3YEAR": {
      "name": "3-ročný obchod so zlatom"
    },
    "GOLDEN_4YEAR": {
      "name": "2-ročný obchod so zlatom"
    },
    "GOLDEN_5YEAR": {
      "name": "1 Year Gold Store"
    },
    "TOKEN_OWNER_1M": {
      "name": "Zlatý investor"
    },
    "TOKEN_OWNER_10M": {
      "name": "Diamantový investor"
    },
    "TOKEN_OWNER_100M": {
      "name": "Ruby Investor"
    },
    "COMMUNITY_LOYAL": {
      "name": "Člen Vyššej komunity komunikačných sietí"
    },
    "GOLD_SUPPLIER": {
      "name": "Dodávateľ zlata"
    },
    "GOLD_SELLER": {
      "name": "Predajca zlata"
    },
    "CONTENT_SUPERMAN": {
      "name": "Najlepší výrobca obsahu"
    },
    "NINJA": {
      "name": "Ninja"
    },
    "STAR": {
      "name": "Hviezda"
    },
    "GUARDIAN": {
      "name": "Skvelý zákaznícky servis"
    },
    "KING": {
      "name": "Kráľ trhu"
    }
  },
  "cookie": {
    "title": "Táto webová stránka používa cookies",
    "message": "Táto webová stránka používa súbory cookie na zlepšenie používateľského zážitku. Používaním našej webovej stránky súhlasíte so všetkými súbormi cookie v súlade s našimi Zásadami používania súborov cookie.",
    "preferences_action": "Spravovať predvoľby",
    "agree_action": "Súhlasím"
  },
  "basket_item_message": {
    "title": "Požadované informácie pre túto položku",
    "save_actions": "Uložiť správu",
    "notifications": {
      "success": "Vaše vstupné údaje boli uložené."
    },
    "product_inputs_preview_message": "Tieto možnosti prispôsobenia sú k dispozícii pre váš objednaný produkt. Po pridaní položky do košíka tu budete môcť vykonať úpravy."
  },
  "faq": {
    "faq": "často kladené otázky",
    "title": "Otázky a odpovede",
    "sub_title": "O čo ste nás požiadali.",
    "message": "V nižšie uvedených odpovediach hľadajte odpoveď na svoju otázku. Opýtajte sa nás, ak otázky zostanú nezodpovedané.",
    "add_question_action": "Položiť novú otázku",
    "read_more": "Čítaj viac ..",
    "load_more": "Ďalšie otázky..",
    "main_page": "Hlavná stránka FAQ",
    "add_new": "Odoslať novú otázku",
    "login_alert": "Ak chcete položiť otázku, prihláste sa.",
    "question_input": "Otázka",
    "question_input_placeholder": "Položte otázku.",
    "notifications": {
      "success_add": "Vaša otázka bola úspešne odoslaná."
    }
  },
  "rating_labels": [
    "Veľmi zle",
    "Zlé",
    "Normálne",
    "Dobre",
    "Výborne"
  ],
  "map_view": {
    "address_detail": "Podrobnosti adresy",
    "change": "Zmeniť",
    "select": "Vyberte",
    "not_found_address": "Nenašla sa žiadna hodnota",
    "enter_address_hint": "Zadajte cieľovú adresu",
    "enter_your_address": "Zadajte svoju adresu.",
    "postal_code": "PSČ",
    "phone_input": "Telefón {type}",
    "building_number": "Číslo budovy",
    "building_unit": "Jednotka",
    "full_name_input": "Celé meno {type}",
    "save_detail_action": "Uložiť podrobnosti",
    "more_detail_input": "Viac popisu",
    "add_address_to_list": "Pridať adresu do zoznamu",
    "address_title_input": "Štítok s adresou (vyžadovať)",
    "notifications": {
      "save_in_list": "Táto adresa bola uložená do vášho zoznamu so všetkými podrobnosťami.",
      "edit_success": "Nové hodnoty adresy uložené v {title}."
    },
    "delete_address_dialog": {
      "title": "Odstrániť adresu",
      "message": "Naozaj chcete odstrániť túto adresu?",
      "action": "Odstrániť adresu"
    }
  },
  "comment_manager": {
    "can_not_edit": "Tento komentár nie je možné upraviť!",
    "comment_input_empty": "Text správy je prázdny!",
    "article_not_saved": "Uložte článok!"
  },
  "wheel_fortune": {
    "title": "Hrajte a vyhrajte",
    "message": "Cena každej hry je 10 žetónov. Momentálne máte {chips} čip. Získajte viac žetónov nákupom v obchode.",
    "win_message": "Gratulujeme, vyhrali ste!",
    "lost_message": "Prepáčte, prehrali ste hru.",
    "try_again": "Môžete to skúsiť znova"
  },
  "json": {
    "add": "Pridajte štruktúrne údaje",
    "add_message": "Vytvorte nové údaje štruktúry",
    "structures": "Štruktúry",
    "book": {
      "title": "Kniha",
      "desc": "Akcie knihy, ktoré umožňujú používateľom kúpiť si knihu, ktorú nájdu priamo vo výsledkoch vyhľadávania."
    },
    "occupation": {
      "title": "Odhadovaný plat",
      "desc": "Informácie o odhade miezd, ako sú rozsahy miezd a priemerné platy podľa regiónu pre typy pracovných pozícií, zobrazené pri hľadaní zamestnania na Googli."
    },
    "course": {
      "title": "Kurz",
      "desc": "Vzdelávacie kurzy, ktoré sa zobrazujú v zozname špecifickom pre poskytovateľa. Kurzy môžu obsahovať názov kurzu, poskytovateľa a krátky popis."
    },
    "howto": {
      "title": "Ako",
      "desc": "Návod prevedie používateľov súborom krokov na úspešné dokončenie úlohy vrátane videa, obrázkov a textu."
    },
    "recipe": {
      "title": "Recept",
      "desc": "Recepty, ktoré sa zobrazujú ako samostatný bohatý výsledok alebo ako súčasť hostiteľského kolotoča."
    }
  },
  "support": {
    "Financial": "Finančné",
    "Technical": "Technická",
    "Advisor": "poradca"
  },
  "condition": {
    "new": "Nový",
    "refurbished": "Zrekonštruovaný",
    "used": "Použité",
    "used_fair": "Použité férovo",
    "used_good": "Použité dobre",
    "used_like_new": "Použité - Ako nové"
  },
  "variant_filter": {
    "title": "Filter variantov produktu",
    "only_available": "Skladom"
  },
  "service": {
    "task": {
      "title": "Úlohy",
      "message": "Zoznam úloh vykonaných v tejto službe."
    },
    "appointment": {
      "title": "Vymenovanie",
      "message": "Vyberte si časy v týždni z nasledujúcich časov podľa dňa a hodiny, ktorá vám vyhovuje."
    },
    "booking": {
      "title": "Rezervácia",
      "message": "V nižšie uvedenom kalendári zadajte časové obdobie dní, kedy chcete vykonať rezerváciu."
    },
    "subscription": {
      "title": "Predplatné"
    },
    "charge": {
      "title": "Nabite"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "Pevná cena",
      "message": "Pri tomto type cenotvorby je cena produktu pevná a nie je potrebné, aby kupujúci požadoval cenovú kalkuláciu."
    },
    "ESTIMATION": {
      "title": "Odhadovaná cena",
      "message": "Cena produktov a služieb bude do určitej miery vypočítaná predávajúcim pri zadávaní objednávky, platobné faktúry je možné v priebehu služby meniť alebo dopĺňať."
    },
    "AGREEMENT": {
      "title": "Cena dohodou",
      "message": "Konečná cena produktov alebo služieb nebude predávajúcim po odoslaní objednávky zmenená."
    },
    "BID": {
      "title": "Ponuka / Aukcia",
      "message": "Potenciálni kupci budú produkt predávať za najvyššiu ponukovú cenu."
    }
  },
  "map": {
    "title": "Cieľ na prijímanie produktov",
    "confirm": "Nastaviť polohu",
    "address": "Destinácia",
    "receptor": "Prijímač"
  },
  "ShopBots": {
    "telegram": "telegram"
  },
  "article_tags": {
    "title": "Značky obsahu",
    "tags_input": "Tagy",
    "tags_input_message": "Tagy Zoznam tohto článku",
    "notification": {
      "add_success": "Pridané značky"
    }
  },
  "difficulties": {
    "very_complicated": "Veľmi komplikované",
    "hard": "Ťažko",
    "intermediate": "Stredne pokročilý",
    "easy": "Jednoduché"
  },
  "billing_period": {
    "Daily": "Denne",
    "Weekly": "Týždenne",
    "Monthly": "Mesačne",
    "Every3Months": "Každé 3 mesiace",
    "Every6Months": "Každých 6 mesiacov",
    "Yearly": "Ročne"
  },
  "buyer_rating_statement": {
    "between1_2": "Och to nie je dobré!",
    "between2_3": "Je to v poriadku!",
    "between3_4": "Ľuďom sa to páči!",
    "between4_5": "Ľudia to milujú!"
  },
  "seasons": {
    "spring": "Jar",
    "summer": "Leto",
    "autumn": "jeseň",
    "winter": "Zima"
  }
};