export default {
  "currency_default": "USD",
  "language_default": "en",
  "selldone": "Prodano",
  "store": "trgovina",
  "not_exist": "Ne obstaja",
  "error": "Napaka",
  "active": "Aktiven",
  "inactive": "neaktiven",
  "required_value": "Zahtevane vrednosti",
  "original_warranty": "Garancija originalnega izdelka",
  "return_warranty_days": "{days} garancijski dan(-i) vračila",
  "no_return_warranty": "Brez vrnitve",
  "reed_agree_terms": "Prebral sem pogoje uporabe in politiko zasebnosti in se z njimi strinjam.",
  "commons": {
    "Currency": "valuta",
    "COD": "COD",
    "State": "Država",
    "Price": "cena",
    "order_price": "Znesek naročila",
    "VAT": "VAT",
    "Discount": "Popust",
    "In_Stock": "Na zalogi",
    "Variants": "Variante",
    "No_variants": "Brez variante",
    "all": "VSE",
    "today": "danes",
    "yesterday": "včeraj",
    "license": "Licenca",
    "home": "Domov",
    "support": "Podpora",
    "messages": "Sporočila",
    "no_message": "Brez sporočila",
    "empty": "Prazno",
    "phone": "Telefon",
    "address": "naslov",
    "name": "ime",
    "password": "Geslo",
    "email": "E-naslov",
    "mobile": "Mobilni",
    "login": "Vpiši se",
    "register": "Registriraj se",
    "select_account": "Izberite račun",
    "online": "Na spletu",
    "offline": "Brez povezave",
    "finish": "Končaj",
    "finished": "Dokončano",
    "preview": "Predogled",
    "free": "prost",
    "free_completely": "Popolnoma brezplačna naročnina",
    "fee": "Pristojbina",
    "month": "mesec",
    "months": "mesecev",
    "faq": "Pogosto zastavljena vprašanja",
    "question": "vprašanje",
    "answer": "Odgovori",
    "create_date": "Ustvari datum",
    "update_date": "Datum posodobitve",
    "start_date": "Začetni datum",
    "end_date": "Končni datum",
    "social": "Socialna",
    "total": "Skupaj",
    "orders": "Naročila",
    "sessions": "Seje",
    "product_views": "Ogledi izdelkov",
    "add_to_carts": "Dodaj v voziček",
    "checkouts": "Preveri",
    "payments": "Plačilo",
    "organic_search": "Organsko iskanje",
    "other": "Drugo",
    "landing_page": "Ciljna stran",
    "discount_code": "Koda za popust",
    "total_sell": "Skupna prodaja",
    "details": "Podrobnosti",
    "currency": "valuta",
    "amount": "Znesek",
    "published": "Objavljeno",
    "draft": "Osnutek",
    "save_changes": "Shrani spremembe",
    "source": "Vir",
    "medium": "srednje",
    "url": "URL",
    "revenue": "Prihodki",
    "performance": "Izvedba",
    "term": "Termin",
    "content": "Vsebina",
    "session": "Seja",
    "product": "Izdelek",
    "add": "Dodaj",
    "checkout": "Preveri",
    "payment": "Plačilo",
    "more_options": "Več možnosti",
    "full_name": "Polno ime",
    "tel": "tel",
    "about_me": "O meni",
    "request_checking": "Zahtevajte preverjanje",
    "passport": "potni list",
    "birthday": "rojstni dan",
    "country": "Država",
    "city": "mesto",
    "gender": "spol",
    "offer": "Ponudba",
    "website": "Spletna stran",
    "apply_for_all_products": "∞ Prijavite se za vse izdelke",
    "fix_commission": "Fiksna provizija",
    "percent_commission": "Odstotek provizije",
    "fixed_discount": "Fiksni popust",
    "discount_percentage": "Odstotek popusta",
    "discount_limit": "Omejitev popusta",
    "no_code": "Brez kode",
    "max_count": "Največje število",
    "count_unit": "Predmeti",
    "used": "Rabljen",
    "daily": "Dnevno",
    "monthly": "Mesečno",
    "yearly": "Letno",
    "state": "Stanje",
    "disable": "Onemogoči",
    "enable": "Omogoči",
    "activation_code": "Aktivacijska koda",
    "quantity": "Količina",
    "no_club": "Brez kluba",
    "per_order": "Po naročilu",
    "count": "štetje",
    "seconds": "Sekund",
    "auto": "Samodejno",
    "title": "Naslov",
    "message": "Sporočilo",
    "width": "Premer",
    "length": "Dolžina",
    "height": "Višina",
    "label": "Oznaka",
    "click": "Kliknite",
    "bank": "Banka",
    "default": "Privzeto",
    "role": "Vloga",
    "user": "Uporabnik",
    "users": "Uporabniki",
    "code": "Koda",
    "total_payment": "Celotno plačilo",
    "balance": "Ravnovesje",
    "chance": "Priložnost",
    "free_for_new_users": "Brezplačno za nove uporabnike",
    "prize_amount": "Znesek nagrade",
    "win": "Zmaga",
    "gift_card": "Darilne kartice",
    "discount": "Popust",
    "config": "Config",
    "prize": "nagrada",
    "Prizes": "Nagrade",
    "result": "Rezultat",
    "price": "cena",
    "lottery": "loterija",
    "coupon": "kupon",
    "customer_club": "Klub strank",
    "shipping": "Dostava",
    "sum": "vsota",
    "not_paid": "Ni plačano",
    "category": "Kategorija",
    "done": "Končano",
    "email_from": "Od",
    "subject": "Zadeva",
    "schedule": "Urnik",
    "files_list": "Seznam datotek",
    "file_max_size": "Največja velikost datoteke",
    "value": "vrednost",
    "help": "Pomagaj",
    "shipping_tax": "Davek na pošiljanje",
    "net_price": "Neto cena",
    "tax": "davek",
    "tax_included": "Vključeno v ceno",
    "limit": "Omejitev",
    "min_purchase": "Minimalni nakup",
    "eligible_for": "Primerno za",
    "only_for_first_buy": "Samo za prvi nakup",
    "one_time_use": "Lahko se uporabi enkrat",
    "period_of_qualify": "Omejitev obdobja uporabe",
    "no_constraint": "Ni omejitev",
    "timespan": "Časovno obdobje",
    "days": "Dnevi)",
    "weight": "Utež",
    "distance": "Razdalja",
    "last_status": "Zadnji status",
    "issued_at": "Izdano pri",
    "order": "Naročite",
    "order_detail": "Podrobnosti naročila",
    "percent": "Odstotek",
    "applied_count": "Uporabljeno štetje",
    "campaign": "Kampanja",
    "os": "operacijski sistem",
    "browser": "Brskalnik",
    "device": "Naprava",
    "device_ip": "IP naslov naprave",
    "location": "Lokacija",
    "user_agent": "Uporabniški agent",
    "affiliate": "Affiliate",
    "timeline": "Časovnica",
    "add_note": "Dodaj opombo",
    "record": "Zapis",
    "unlimited": "Neomejeno",
    "show_coupons": "Pokaži kupone",
    "hide_coupons": "Skrij kupone",
    "service_area": "Servisno območje",
    "apps": "aplikacije",
    "plugins": "Vtičniki",
    "bots": "Boti",
    "categories": "kategorije",
    "products": "Izdelki",
    "business": "Posel",
    "personal": "Osebno",
    "size": "Velikost",
    "holiday": "Počitnice",
    "sod": "Plačaj ob dostavi",
    "cod": "Gotovino po povzetju",
    "free_shipping": "Brezplačna dostava",
    "hours": "Ure",
    "send_date": "Datum pošiljanja",
    "deliver_date": "Datum dostave",
    "return_date": "Datum vrnitve",
    "pending": "V teku",
    "delivered": "Dostavljeno",
    "returned": "Vrnjeno",
    "canceled": "Prekinjeno",
    "shipping_cost": "Stroški pošiljanja",
    "action": "Ukrep",
    "cancel_date": "Datum preklica",
    "deliver_in_process": "Naročilo je odposlano..",
    "kind": "Vrsta",
    "detail": "Podrobnosti",
    "map": "Zemljevid",
    "actions": "Dejanja",
    "navigation": "Navigacija",
    "navigation_app": "Aplikacija",
    "payment_date": "Dan plačila",
    "duration": "Trajanje",
    "bill": "Bill",
    "delivery_persons": "Kurirji",
    "delivery_services": "Storitve dostave",
    "live_view": "Pogled v živo",
    "cart": "Voziček",
    "priority": "Prednost",
    "sufficient_credit": "Dovolj kredita",
    "max_package_size": "Največja velikost paketa",
    "delay": "Zamuda",
    "credit": "Kredit",
    "livemode": "V živo",
    "paused": "Zaustavljeno",
    "debug": "Odpravljanje napak",
    "token": "Žeton",
    "status": "Stanje",
    "courier": "Kurir",
    "track": "Sled",
    "track_order": "Sledenje naročilu",
    "cost": "Stroški",
    "receipt": "Potrdilo o prejemu",
    "origin": "Izvor",
    "destination": "Destinacija",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "Ni dovolj zalog!",
    "sub_total": "Vmesni seštevek",
    "customer": "Stranka",
    "delivery": "Dostava",
    "online_orders": "Spletna naročila",
    "pos_orders": "POS naročila",
    "chips": "čips",
    "subscribed": "Naročen",
    "unsubscribed": "Odjavljen",
    "last_login": "Zadnja prijava",
    "join_at": "Datum pridružitve",
    "club": "Klub",
    "buyer": "kupec",
    "seller": "Prodajalec",
    "or": "ali",
    "type": "Vrsta",
    "condition": "Stanje",
    "brand": "Blagovna znamka",
    "attempt": "Poskus",
    "error": "Napaka",
    "success": "uspeh",
    "fail": "Neuspešno",
    "inventory": "Inventar",
    "link": "Povezava",
    "visits": "Obiski",
    "transactions": "Transakcije",
    "vat": "VAT",
    "pos_vat": "POS DDV",
    "sort_by": "Razvrsti po..",
    "from": "Od",
    "from_lead_time": "V naslednjih {hours} urah",
    "no_credit_card_info": "Ni podatkov o kartici!",
    "active": "Aktiven",
    "not_active": "Ni aktivirano!",
    "referrals": "Napotitve",
    "dashboard": "Nadzorna plošča",
    "more": "Več",
    "inactive": "neaktiven",
    "developer": "Razvijalec",
    "setting": "Nastavitev",
    "membership_conditions": "Pogoji članstva",
    "customers": "Stranke",
    "created_at": "Datum ustvarjanja",
    "updated_at": "Zadnja posodobitev",
    "register_at": "Datum registracije",
    "old": "Star",
    "new": "Novo",
    "start": "Začni",
    "end": "Konec",
    "pos": "POS",
    "out_of_stock": "Ni na zalogi",
    "fake": "Lažne",
    "low_inventory_warning": "Pozor, malo zalog!",
    "webhook": "Webhook",
    "notification": "Obvestilo",
    "sms": "SMS",
    "online_payment_link": "Povezava za spletno plačilo",
    "waiting_load_data": "Čakanje na nalaganje podatkov..",
    "views": "Pogledi",
    "sales": "Prodaja",
    "total_views": "Skupno število ogledov",
    "total_sales": "Skupna prodaja",
    "from_previous_n_days": "Od zadnjih {days} dni",
    "drop_shipping": "Dropshipping",
    "commission": "provizija",
    "shipping_area": "Območje pošiljanja",
    "main_seller": "Glavni prodajalec",
    "domain": "domena",
    "contact": "Kontaktne informacije",
    "wallet": "denarnica",
    "reseller": "Preprodajalec",
    "tracking_code": "Koda za sledenje",
    "tracking_url": "URL za sledenje",
    "fulfillments": "Izpolnitve",
    "reject": "Zavrni",
    "reserved": "Rezervirano",
    "score": "Rezultat",
    "customer_price": "Cena za stranke",
    "options": "Opcije",
    "show_details": "Pokaži podrobnosti",
    "no_data": "Ni podatkov..",
    "waiting": "Čakanje ...",
    "waiting_connecting_payment": "Čakam na plačilno storitev ...",
    "creating_secure_payment": "Ustvarjanje varnega plačila.",
    "officer": "častnik",
    "ticket": "Vstopnica",
    "ticket_url": "URL vstopnice",
    "closed_at": "Zaprto ob",
    "close_ticket": "Zapri vstopnico",
    "reopen_ticket": "Ponovno odprite vstopnico",
    "require": "Zahtevaj*",
    "search": "Iskanje...",
    "language": "Jezik",
    "tasks": "Naloge",
    "permissions": "Dovoljenja",
    "finish_date": "Končni datum",
    "complete_date": "Datum dokončanja",
    "settle_date": "Datum poravnave",
    "cost_span": "Cenovni razpon",
    "industry": "Industrija",
    "rating": "Ocene",
    "rates": "Ocena",
    "seen_at": "Videno na",
    "completed": "Dokončano",
    "you": "ti",
    "shop": "Nakupujte",
    "store": "trgovina",
    "granted": "dovoljeno",
    "deny": "Zanikati",
    "request": "Prošnja",
    "expert": "Strokovnjak",
    "response": "Odziv",
    "requests": "Zahteve",
    "experts": "Strokovnjaki",
    "responses": "Odzivi",
    "negotiations": "pogajanja",
    "all_chats": "Vsi klepeti",
    "chats": "Klepeti",
    "tags": "Oznake",
    "description": "Opis",
    "rates_count": "Število ocen",
    "rate": "Ocena",
    "comment": "Komentar",
    "chat": "Klepetajte",
    "install": "Namestite",
    "edited": "Urejeno",
    "undo": "Razveljavi",
    "redo": "Ponovi",
    "male": "moški",
    "female": "Ženska",
    "calculator": "Kalkulator",
    "catalog": "Katalog",
    "max_height": "Največja višina",
    "images_compare": "Primerjava slik",
    "canvas": "Platno",
    "table_of_contents": "Kazalo",
    "comments": "Komentarji",
    "badge_codes": "Koda značke",
    "need_more": "Potrebujemo več?",
    "invite_glow_caption": "Prejmite 14,9 $ za vsakega prijatelja!",
    "register_free": "100% brezplačna registracija",
    "gift": "Darilo",
    "google": "Google",
    "facebook": "Facebook",
    "instagram": "Instagram",
    "instashop": "Instashop",
    "show": "Pokaži",
    "hide": "skrij",
    "waiting_review": "Čakanje na pregled",
    "not_selected": "Ni izbrano",
    "time": "Čas",
    "final_price": "Končna cena",
    "starting_price": "Začetna cena",
    "day": "dan",
    "paid": "Plačano",
    "service_bill": "Plačilo računa",
    "avocado": "Avokado",
    "delivery_price": "Stroški pošiljanja",
    "select_address": "Izberite naslov",
    "image": "Slika",
    "view": "Ogled",
    "sell": "Razprodaja",
    "hyper": "Hiper",
    "cart_list": "Voziček",
    "barcode_scanner": "Skener črtne kode",
    "scan_qr_code": "Skenirajte QR kodo",
    "new_carts": "Novi vozički",
    "pays": "plačila",
    "annually": "letno",
    "sells": "Prodaja",
    "articles": "Članki",
    "jobs": "Službe",
    "job": "Job",
    "blog": "Blog",
    "deleted_at": "Izbrisano ob",
    "capacity": "Zmogljivost",
    "download_at": "Datum zadnjega prenosa",
    "downloads": "Prenosi",
    "usage": "Uporaba",
    "select_upload_file": "Izberite ali spustite datoteko",
    "download_link": "Povezava za prenos",
    "uploading": "Nalaganje ...",
    "files": "Datoteke",
    "star": "zvezda",
    "speed": "Hitrost",
    "feedback": "Povratne informacije",
    "new_messages": "Nova sporočila",
    "file": "mapa",
    "attachment": "Priponka",
    "gallery": "Galerija",
    "sync": "Sinhronizacija",
    "diff_time": "Časovna razlika",
    "network": "omrežje",
    "account": "račun",
    "configuration": "Konfiguracija",
    "blockchain": "Blockchain",
    "blog_link": "Povezava do spletnega dnevnika",
    "community": "skupnost",
    "critical_zone": "Kritično območje",
    "statistics": "Statistika",
    "access": "Dostop",
    "seo": "SEO",
    "followers": "Spremljevalci",
    "followings": "Spremljanja",
    "private": "Predogled",
    "soon": "Kmalu",
    "features": "Lastnosti",
    "bot": "bot",
    "sample": "Vzorec",
    "how_it_work": "Kako deluje?",
    "page": "stran",
    "congratulations": "Čestitam",
    "recommend": "priporočam",
    "recommended": "Priporočeno",
    "recoms": "Priporočila",
    "likes": "Všeč mi je",
    "clicks": "Kliki",
    "platform": "Platforma",
    "cms": "CMS",
    "cash": "gotovina",
    "dir_payment": "bančno nakazilo",
    "auto_complete": "Samodejno dokončanje",
    "compare": "Primerjaj",
    "infinite": "neskončno",
    "tips": "Nasveti",
    "technical": "Tehnični",
    "finance": "finance",
    "your_phone_input": "Vnesite telefonsko številko",
    "income": "dohodek",
    "change": "Spremeni se",
    "new_users": "Novi uporabniki",
    "success_orders": "Uspešna naročila",
    "direct": "Neposredno",
    "last_activity": "Zadnja aktivnost",
    "landing": "Pristanek",
    "now": "zdaj",
    "accept_agreement": "Prebral sem in sprejemam pogoje.",
    "report": "Poročilo",
    "tablet": "tablica",
    "pc": "PC",
    "acquisition_channel": "Pridobitveni kanal",
    "to": "Za",
    "info": "Info",
    "general": "General",
    "upload": "Naloži",
    "general_config": "Splošna konfiguracija",
    "limits_config": "Omejitve",
    "design_config": "Oblikovanje in slog",
    "duration_config": "Omejitev trajanja",
    "constraints_config": "Meje upravičenosti",
    "clubs_config": "Na voljo v klubih",
    "additional_config": "Dodatne konfiguracije",
    "import": "Uvozi",
    "ribbon": "Trak",
    "countries": "države",
    "edit": "Uredi",
    "delete": "Izbriši",
    "analytics": "analitika",
    "rules": "Pravila",
    "unset": "Ni nastavljeno",
    "carts": "Vozički",
    "optional": "Neobvezno",
    "design": "Oblikovanje",
    "filter": "Filter",
    "send": "Pošlji",
    "approved": "Odobreno",
    "unit": "enota",
    "profile": "profil",
    "shipping_rates": "Cene pošiljanja",
    "package": "Paket",
    "overview": "Pregled",
    "live": "V živo",
    "never": "Nikoli",
    "always": "Nenehno",
    "mandatory": "Obvezno",
    "expire_at": "Rok uporabnosti",
    "position": "Položaj",
    "channel": "kanal",
    "age": "starost",
    "charge": "Napolniti",
    "giftcard": "Darilne kartice",
    "acquisition": "Pridobitev",
    "conversion": "Pretvorba",
    "total_payments": "Skupna plačila",
    "community_ask": "Vprašajte v skupnosti",
    "children": "Otroci",
    "export": "Izvozi",
    "list": "Seznam",
    "hierarchy": "Hierarhija",
    "images": "Slike",
    "demo": "Demo",
    "author": "Avtor",
    "designer": "Oblikovalec",
    "max": "največ",
    "accepted": "Sprejeto",
    "reply": "Odgovori",
    "reviewed": "Pregledano",
    "restored": "Obnovljeno",
    "merchant": "trgovec",
    "per_product": "Na izdelek",
    "journey": "Potovanje",
    "after": "Po",
    "waiting_for_payment": "Prosimo dokončajte plačilo ...",
    "hour": "ura",
    "minute": "minuta",
    "premium": "Premium",
    "light": "Svetloba",
    "dark": "Temno",
    "guest": "Gost",
    "shops": "Trgovine",
    "vendor": "Prodajalec",
    "vendors": "Prodajalci",
    "marketplace": "Tržnica",
    "verify_date": "Preverite datum",
    "note": "Opomba",
    "panel": "Panel",
    "removed": "Odstranjeno",
    "segments": "Segmenti",
    "personal_info": "Osebni podatki",
    "preferences": "Nastavitve",
    "spec": "Spec",
    "reviews": "Ocene",
    "constraints": "Omejitve",
    "flexible": "Prilagodljiv",
    "usage_limit": "Omejitev uporabe",
    "temporary": "Začasno",
    "original": "Original",
    "saved": "Shranjeno!",
    "sort": "Razvrsti",
    "documents": "Dokumenti",
    "document": "Dokument",
    "please_wait": "Prosim počakaj...",
    "pickup": "Prevzem",
    "customize": "prilagoditi",
    "difficulty": "Težavnost",
    "banned": "Prepovedano",
    "company": "Podjetje",
    "tax_shipping": "Davek na pošiljanje",
    "warranty": "Garancija",
    "return_policy": "Vračilo blaga",
    "guide": "Vodnik",
    "translate": "Prevesti",
    "public": "Javno",
    "deleted": "Izbrisano",
    "variant": "Varianta",
    "secure": "Varno",
    "admin": "skrbnik"
  },
  "dialogs": {
    "delete": {
      "title": "Izbriši",
      "message": "Ali ste prepričani, da želite izbrisati ta element?",
      "action": "Da, izbriši zdaj"
    }
  },
  "actions": {
    "add_to_cart": "Dodaj v voziček",
    "cancel": "Prekliči",
    "update": "Nadgradnja",
    "add": "Dodaj",
    "delete": "Izbriši",
    "new": "Novo",
    "save_continue": "Shrani & Nadaljuj",
    "save": "Shrani",
    "save_changes": "Shrani spremembe",
    "change": "Spremeni se",
    "continue": "Nadaljuj",
    "close": "Zapri",
    "finish": "Končaj",
    "poll": "Anketa",
    "view": "Ogled",
    "edit": "Uredi",
    "next": "Naslednji",
    "previous": "Prejšnji",
    "create": "Ustvari",
    "set": "set",
    "find": "Najti",
    "accept": "Sprejmi",
    "reject": "Zavrni",
    "back": "nazaj",
    "pay": "plačati",
    "pay_now": "Plačaj zdaj",
    "print": "Tiskanje",
    "return": "Vrnitev",
    "publish": "Objavi",
    "confirm": "Potrdi",
    "copy": "Kopirati",
    "submit": "Pošlji",
    "send": "Pošlji",
    "yes": "da",
    "no": "št",
    "meh": "Hmm",
    "clear": "Jasno",
    "dismiss": "Opusti",
    "search": "Iskanje",
    "deselect_all": "Počisti vse",
    "select_all": "Izberi vse",
    "refresh": "Osveži",
    "verify": "Preverite",
    "play": "Igraj",
    "open": "Odprto",
    "calculate": "Izračunaj",
    "quick_buy": "Hitri nakup",
    "click_here": "Klikni tukaj",
    "schedule": "Urnik",
    "send_now": "Pošlji zdaj",
    "download": "Prenesi",
    "reset_default": "Ponastavi na privzeto",
    "reset": "Ponastaviti",
    "check": "Preverite",
    "cod_payment": "Gotovino po povzetju",
    "dir_payment": "Denarna transakcija",
    "online_payment": "Spletno plačilo",
    "checkout": "Preveri",
    "show_all": "Pokaži vse",
    "login": "Vpiši se",
    "logout": "Odjava",
    "more": "Več..",
    "collapse": "Zrušiti",
    "apply_change": "Uporabi spremembe",
    "apply": "Prijavite se",
    "add_giftcard": "Dodajte darilno kartico",
    "charge": "Napolniti",
    "send_invites": "Pošlji vabila",
    "past": "preteklost",
    "restore": "Obnovi",
    "cut": "Izrežite",
    "get_sms_code": "Pridobite kodo za preverjanje pristnosti",
    "register_no_mail": "Nadaljujte brez e-pošte",
    "no_mail_register_message": "Nimate e-poštnega naslova ali ste pozabili geslo?",
    "reset_by_mail": "Obnovitev gesla po e-pošti",
    "reset_by_sms": "Obnovitev gesla s SMS-om",
    "cash_payment": "Gotovinsko plačilo",
    "show_chart": "Pokaži grafikon",
    "open_app": "Odprite aplikacijo",
    "login_now": "Prijavi se zdaj",
    "watch_video": "Oglejte si video",
    "check_now": "Preveri zdaj",
    "remove_image": "Odstrani sliko",
    "view_website": "Odpri povezavo",
    "explore": "Raziščite {name}",
    "go": "Pojdi",
    "read_more": "Preberi več",
    "start_now": "Začnite zdaj — brezplačno je",
    "view_live": "Ogled v živo",
    "resend_code": "Ponovno pošlji kodo",
    "invite": "Povabi",
    "add_more": "Dodaj Več",
    "install_now": "Namestiti zdaj",
    "uninstall": "Odstrani",
    "show_preview": "Pokaži predogled",
    "hide_preview": "Skrij predogled",
    "download_now": "Prenesi zdaj",
    "auto_fill": "Samodejno izpolnjevanje",
    "track": "Sled",
    "change_state": "Spremeni stanje",
    "done": "Končano",
    "reply": "Odgovori",
    "watch_now": "Pazi zdaj",
    "unlock": "Odkleni",
    "lock": "Zaklepanje",
    "create_clone": "Ustvari klon",
    "regenerate": "Regeneriraj",
    "add_message": "Dodaj sporočilo",
    "continue_chat": "Nadaljujte s klepetom",
    "add_new_message": "Dodaj novo sporočilo"
  },
  "instance_message_title": "Pošlji takojšnje sporočilo",
  "instance_message": "Pozdravljeni, {name}, moje ime je {author} iz podjetja {company}.",
  "errors": {
    "419": "Že dolgo niste bili aktivni, prosimo <b>⟳ OSVEŽITE STRAN</b> iz varnostnih razlogov.",
    "gateway_blockchain_sync_error": "Sistem se ne sinhronizira z blockchainom. Nove transakcije ne bo mogoče ustvariti, dokler sinhronizacije naših strežnikov niso dokončane. Problem rešujemo.",
    "gateway_network_error": "Storitev plačilnega prehoda je naletela na težavo s komunikacijo."
  },
  "receiver_info": {
    "map": {
      "title": "Naslov za pošiljanje",
      "confirm": "Nastavite lokacijo",
      "address_type": "Destinacija",
      "receptor_type": "Sprejemnik"
    },
    "receiver_address": "Izberite naslov za dostavo",
    "address": "naslov",
    "postcode": "poštna številka",
    "enter_value": "Izpolnite tukaj",
    "address_note": "Opomba",
    "tel": "Kontaktna številka",
    "service_address": "Izberite svoj naslov"
  },
  "weight": {
    "g": "g",
    "oz": "oz",
    "lb": "lb",
    "kg": "kg"
  },
  "mass_unit_name": {
    "g": "gram",
    "oz": "Unča",
    "lb": "funt",
    "kg": "kilogram"
  },
  "length": {
    "cm": "cm",
    "in": "v",
    "ft": "ft",
    "mm": "mm",
    "m": "m",
    "yd": "yd"
  },
  "size_unit_name": {
    "cm": "Centimeter",
    "in": "palec",
    "ft": "stopalo",
    "mm": "milimeter",
    "m": "meter",
    "yd": "dvorišče"
  },
  "distance": {
    "m": "meter",
    "km": "km"
  },
  "time": {
    "days": "Dnevi",
    "hours": "Ure",
    "minutes": "Minute",
    "seconds": "Sekund"
  },
  "units": [
    "enota",
    "predmet",
    "vsak",
    "set",
    "kos",
    "kilogram",
    "gram",
    "miligram",
    "meter",
    "milimeter",
    "kvadratni meter",
    "kvadratni čevelj",
    "kubični meter",
    "liter",
    "mililitra",
    "stopala",
    "galoni",
    "palcev",
    "unč",
    "funtov",
    "kvartov",
    "jardov",
    "soba",
    "sekund",
    "minut",
    "ure",
    "dnevi",
    "tedne",
    "mesecih",
    "leta"
  ],
  "region_types": {
    "State": "Država",
    "Territory": "ozemlje",
    "Province": "provinca"
  },
  "transaction_status": {
    "RequireAction": "Zahtevano dejanje",
    "Processing": "Obravnavati",
    "Canceled": "Prekinjeno",
    "Succeeded": "uspelo"
  },
  "placeholders": {
    "name": "Jone Cox",
    "email": "vaš-mail@mail.com",
    "phone": "+1 000 0000",
    "language": "Izberi jezik..",
    "friend_email": "e-pošta vašega prijatelja ...",
    "friend_name": "Opt. Ime vašega prijatelja",
    "select_date": "Izberite datum ..."
  },
  "notification": {
    "confirm": "Potrdi",
    "confirm_message": "Spremembe so uspešno shranjene.",
    "error": "Napaka",
    "message": "Sporočilo",
    "caution": "Pozor",
    "warning": "Opozorilo",
    "award": "Čestitam",
    "error_message": "Na žalost je prišlo do napake.",
    "congratulation": "Čestitam",
    "coming_soon": "Kmalu",
    "on_fetching_data": "Prejemanje informacij ..",
    "new_pwa_version": "Nova različica je na voljo zdaj. Ali želite posodobiti aplikacijo?",
    "over_license_limit": "Prekoračitev omejitve licence",
    "update_license": "Posodobite licenco",
    "required": "Obvezno",
    "invalid_email": "Neveljavna e-pošta",
    "invalid_domain": "Neveljavna domena",
    "invalid_min_length": "Najmanjša dolžina mora biti {length}",
    "invalid_min_array_length": "Izberite vsaj {length} elementov",
    "invalid_max_chars": "Največ {maxCount} znakov",
    "invalid_url": "Neveljaven URL",
    "country_invalid": "Izberite ciljno državo!",
    "postal_code_invalid": "Nastavite veljavno poštno številko!"
  },
  "colors": {
    "#D32F2F": "rdeča",
    "#C2185B": "Roza",
    "#7B1FA2": "vijolična",
    "#512DA8": "Temno vijolična",
    "#303F9F": "Indigo modra",
    "#1976D2": "modra",
    "#0288D1": "Svetlo modra",
    "#0097A7": "Turkizno modra",
    "#00796B": "Gos Green",
    "#388E3C": "Zelena",
    "#689F38": "Svetlo zelena",
    "#AFB42B": "Limuzina",
    "#FBC02D": "Rumena",
    "#FFA000": "Jantar",
    "#F57C00": "Oranžna",
    "#E64A19": "Svetleča oranžna",
    "#5D4037": "rjav",
    "#616161": "siva",
    "#455A64": "sivo modra",
    "#FFD700": "Zlati",
    "#C0C0C0": "Srebrna",
    "#b76e79": "Zlata vrtnica",
    "#383838": "Mat črna",
    "#FFFFFF": "Bela",
    "#FFF": "Bela",
    "#000000": "Črna",
    "#000": "Črna",
    "#7d263a": "Maroon",
    "#FD9F17": "zlato",
    "#229DBF": "Aqua",
    "#6DC9E2": "Aqua Triblend",
    "#413B2D": "vojska",
    "#474747": "Asfalt",
    "#E6195C": "Berry",
    "#B2184C": "Berry Triblend",
    "#FC7F5F": "Zažgana pomaranča",
    "#80011F": "Kardinal",
    "#382829": "Čokolada",
    "#F06336": "Korale",
    "#FAE7C9": "Krema",
    "#6B2257": "ribez",
    "#222127": "Temno siva",
    "#0D5A74": "Deep Teal",
    "#00582F": "Zimzelena",
    "#214C30": "Gozd",
    "#DC2867": "Fuksija",
    "#38561": "Kelly",
    "#5C884D": "List",
    "#558450": "Lahka Aqua",
    "#96B5C9": "Svetlo modra",
    "#DCAFCE": "Lila",
    "#D3E1A4": "Apno",
    "#9DE7C2": "Kovnica",
    "#F6EAD2": "Naravno",
    "#1A1F35": "Mornarica",
    "#404624": "olivno",
    "#271020": "Sliva",
    "#A8355C": "Malina",
    "#D6BEA6": "Mehka krema",
    "#BEA994": "Tan",
    "#0DB2AE": "Zelenomodra",
    "#A86EA9": "Vijolična",
    "#36454F": "Oglje",
    "#b3b0ab": "ogljikovo siva",
    "#463e3d": "Oglje Heather",
    "#282d3c": "Mornarsko modri jopič"
  },
  "address_info": {
    "name": "ime",
    "tel": "Telefon",
    "email": "E-naslov",
    "country": "Država",
    "city": "mesto",
    "state": "Država",
    "address": "naslov",
    "building_number": "Številka stavbe",
    "building_unit": "enota",
    "postcode": "poštna številka",
    "note": "Opomba",
    "county": "okrožje"
  },
  "product_types": {
    "physical": "fizično",
    "physical_description": "Fizični izdelki, kot so: mobilni telefoni, knjige, elektronske komponente.",
    "virtual": "Virtualna",
    "virtual_description": "Internetu prijazni izdelki, kot so: polnilna kartica, hotelska rezervacija, polnjenje iger.",
    "file": "mapa",
    "file_description": "Vse dovoljene datoteke, kot so videoposnetek spletnega tečaja, dokumenti, ki jih je mogoče prenesti.",
    "service": "Storitev",
    "service_description": "Storitve, kot so: popravilo, prevoz, poučevanje."
  },
  "license": {
    "free": "prost",
    "startup": "Začeti",
    "company": "Podjetje",
    "enterprise": "Enterprise"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "Toman",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW",
    "GHS": "GHS",
    "ZWD": "ZWD",
    "IQD": "IQD",
    "SYP": "SYP"
  },
  "variants": {
    "color": "Barva",
    "volume": "Velikost",
    "count_in_pack": "Štejte v paketu",
    "weight": "Utež",
    "type": "Material",
    "style": "Slog"
  },
  "delivery_state": {
    "check_queue": "Čakanje na pregled",
    "order_confirm": "Potrdilo naročila",
    "preparing_order": "Priprava",
    "sent_order": "Ob dostavi",
    "to_customer": "Dostavljeno"
  },
  "status": {
    "unpaid": "Neplačano",
    "paid": "Plačano",
    "canceled": "Prekinjeno",
    "completed": "Rešen",
    "reserved": "Rezervirano",
    "COD": "COD",
    "sold": "Prodano",
    "open": "Odprto",
    "cancel": "Prekinjeno",
    "active": "Aktiven",
    "inactive": "neaktiven",
    "debug": "Odpravljanje napak",
    "live": "V živo",
    "test": "Test",
    "connected": "Povezano",
    "disconnected": "Prekinjena povezava",
    "accept": "Sprejmi",
    "reject": "Zavrni",
    "pending": "V teku",
    "rejected": "Zavrnjeno",
    "accepted": "Sprejeto"
  },
  "dimensions": {
    "cm": "cm",
    "km": "km",
    "kg": "kg"
  },
  "transportation_type": {
    "motorbike": "motorno kolo",
    "motorbike_description": "Srednja teža v nekaj kilometrih.",
    "cargo_small": "Majhen tovor",
    "cargo_small_description": "Večkilometrski lahki tovor.",
    "cargo": "Tovor",
    "cargo_description": "Srednja teža v nekaj kilometrih.",
    "truck": "Tovornjak",
    "truck_description": "Razsuti ali težki tovor znotraj države.",
    "fast_post": "Hitra objava",
    "fast_post_description": "Hitra objava preko pošte.",
    "post": "Običajna objava",
    "post_description": "Redna pošta preko pošte.",
    "airplane": "Letalska pošta",
    "airplane_description": "Domači in tuji lahki in srednji tovor.",
    "bicycle": "Čisto pošiljanje",
    "bicycle_description": "Lahki tovor, znotraj nekaj sto metrov od nemotornih vozil.",
    "global": "Globalni promet",
    "global_description": "Pošiljanje v tujino po zraku, morju ali kopnem.",
    "pickup": "Prevzem",
    "pickup_description": "Stranke prevzamejo izdelke v vaši fizični trgovini ali skladišču."
  },
  "article": {
    "login_to_see_error": "Prijavite se za dostop do članka",
    "create_new_action": "Ustvari novo vsebino",
    "menu_title": "meni",
    "menu": {
      "edit": "Način urejanja",
      "view_mode": "Način pogleda",
      "delete": "Izbriši članek"
    },
    "schedule_action": "Ali želite načrtovati objavo?",
    "schedule_title": "Načrtujte samodejno objavo",
    "edit_mode": "Uredi",
    "public_view_mode": "Javni pogled",
    "publish_at": "Objavi na",
    "published": "Objavljeno",
    "draft": "Osnutek",
    "saving": "Shranjevanje",
    "save_and_publish_action": "Shrani in objavi",
    "save_draft_action": "Shrani osnutek",
    "private": "Zasebno",
    "public": "Javno",
    "category_input": "Kategorija",
    "category_input_message": "Izberite kategorijo artiklov",
    "parent_input": "Starševska kategorija",
    "parent_input_message": "Izberite vsebino očeta",
    "schedule_input": "Urnik",
    "schedule_input_placeholder": "Če želite, da bo zgodba objavljena ob določenem času.",
    "schedule_view_action": "Oglejte si razpored objave",
    "author_title": "Napisal",
    "read_time": "Čas za učenje",
    "read_time_unit": "Minute",
    "claps_action": "Claps",
    "claps": "Claps",
    "likes": "Všeč mi je",
    "about_author": "O avtorju",
    "updated_at": "Posodobljeno",
    "wrote_at": "Napisano na",
    "now": "zdaj",
    "follow_action": "Sledite",
    "followed": "Sledil",
    "report_and_delete_action": "Prijavite in izbrišite ta članek",
    "report_action": "Prijavi zlorabo",
    "you_reported_this_article": "Ta članek že vsebuje prijavo zlorabe.",
    "add_to_publication_action": "Dodaj v publikacijo",
    "author_socials": "Avtor na družbenih omrežjih",
    "share": "Deliti",
    "report_dialog": {
      "report_and_delete_title": "Prijavite zlorabo in odstranite vsebino",
      "report_title": "Prijavite to vsebino kot žaljivo",
      "message": "Kaj je razlog za oddajo te vsebine? Izberite eno od naslednjih možnosti.",
      "accept_and_delete_action": "Potrdite in izbrišite vsebino"
    },
    "schedule_dialog": {
      "title": "Urnik objave vsebine",
      "publish_at": "Objavi na",
      "last_edit": "Zadnja sprememba",
      "view_action": "Oglejte si članek"
    },
    "notifications": {
      "update_success_title": "Pošlji informacije",
      "update_success": "Članek je bil uspešno posodobljen.",
      "update_error": "Vneseni podatki niso veljavni.",
      "delete_error": "Tega članka ne morete izbrisati!",
      "report_and_delete_success_title": "Prijavi in izbriši",
      "report_and_delete_success_message": "Članek je bil uspešno izbrisan.",
      "report_success_title": "Prijavite članek",
      "report_success_message": "Vaše poročilo o tem članku je bilo objavljeno."
    },
    "alert": {
      "delete_article": {
        "title": "Izbriši članek",
        "message": "Ali ste prepričani, da želite trajno izbrisati ta članek?",
        "action": "Izbriši"
      }
    },
    "edit_window": {
      "title": "Izberite Slikovno besedilo in povzetek",
      "digest": "Povzetek"
    },
    "editor": {
      "title_placeholder": "Naslov..",
      "body_placeholder": "Napišite super vsebino..",
      "accept_file_types_error": "Ta oblika datoteke je nesprejemljiva:",
      "max_file_size_error": "Ta datoteka je prevelika:",
      "notifications": {
        "image_uploaded_success": "Slika je uspešno shranjena",
        "image_uploaded_failed": "Napaka pri nalaganju slike."
      },
      "embed_placeholder": "Vnesite kodo iframe, Facebook, Youtube ali kateri koli drug URL in pritisnite enter.",
      "embed_caption_placeholder": "Vnesite naslov (izbirno)",
      "images_caption_placeholder": "Vnesite naslov za to sliko .."
    }
  },
  "article_report": {
    "inappropriate": "Vsebina tega članka je neprimerna.",
    "fake": "To je lažno in zavajajoče.",
    "spam": "Ta element je bil neželeno poslan in kopiran.",
    "scam": "Pričakuje se, da bo to povzročilo zlonamerno programsko opremo, viruse ali zrušitev sistema.",
    "hacked": "Zdi se, da je bilo to spletno mesto vdrto.",
    "offensive": "Jezikovna vsebina in besedišče je neetično in nespoštljivo.",
    "violent": "Mislim, da ta vsebina vsebuje pornografijo in je v nasprotju z zakonodajo.",
    "harassment": "Mislim, da je to rasistično.",
    "hate": "Mislim, da gre za spodbujanje nasilja.",
    "infringe": "To krši moje pravice."
  },
  "comments": {
    "new_action": "Kliknite, če želite pustiti komentar..",
    "title": "Komentarji",
    "body_placeholder": "Vaš komentar ali sporočilo",
    "send_action": "Pošlji komentar",
    "body_is_empty_error": "Komentar je prazen!",
    "comments": "Komentarji",
    "no_comments": "Napiši prvi komentar...",
    "load_more_action": "Pridobite več komentarjev..",
    "cant_send_comment": "Ne morete dodati nove objave.",
    "cant_remove_this_comment": "Tega komentarja ne morete izbrisati!",
    "product_buyer": "kupec",
    "delete_alert": {
      "title": "Izbriši komentar",
      "message": "Ali želite izbrisati ta komentar?",
      "action": "Izbriši"
    },
    "notifications": {
      "delete_success": "Vaš komentar je bil uspešno izbrisan."
    },
    "first_send": "Prva objava",
    "comment_at": "Vklopljeno",
    "edit_comment": "Uredi komentar"
  },
  "customer_club": {
    "bronze": "bronasto",
    "silver": "Srebrna",
    "gold": "Zlati",
    "platinum": "Platina",
    "diamond": "Diamant"
  },
  "application_categories": {
    "tracking": "Preverjanje vedenja uporabnikov",
    "payment": "Plačilo",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "Prevoz",
    "automation": "Avtomatizacija",
    "inventory": "Skladiščenje",
    "accounting": "Računovodstvo",
    "marketing": "Trženje",
    "advertising": "Oglaševanje",
    "staff": "osebje",
    "incentive": "Spodbude",
    "shop": "Nakupujte"
  },
  "social_network": {
    "instagram": "Instagram",
    "telegram": "Telegram",
    "googleplay": "Google Play",
    "appstore": "Trgovina z aplikacijami",
    "twitter": "Twitter",
    "linkedin": "Linkedin",
    "medium": "srednje",
    "selldone": "Prodano",
    "facebook": "Facebook",
    "pinterest": "Pinterest",
    "whatsapp": "WhatsApp",
    "skype": "Skype",
    "facebook_messenger": "Facebook Messenger"
  },
  "form_builder": {
    "add_item_action": "Dodaj nov predmet",
    "title_input": "Naslov",
    "name_input": "Ime spremenljivke",
    "value_input": "Vrednote",
    "value_input_message": "Seznam uporabniških možnosti",
    "default": "Privzeta vrednost",
    "types": {
      "simple": "Preprosto",
      "selective": "Selektivno",
      "switch": "Preklopi",
      "file": "mapa",
      "number": "številka"
    },
    "placeholder_input": "Rezervirano mesto",
    "file_type_input": "Sprejemljive vrste datotek",
    "file_type_message": "jpeg, png, zip, ..."
  },
  "virtual_order_info_summery": {
    "title": "ime izdelka",
    "reserved_at": "datum registracije",
    "total_price": "Skupni znesek",
    "discount": "Popust",
    "final_price": "Končni znesek",
    "payment_status": "Stanje plačila",
    "payment_status_waiting": "Čakanje na plačilo",
    "payment_status_paid": "Plačano",
    "buyer": "kupec"
  },
  "virtual_item_info": {
    "title": "Virtualni predmet",
    "outputs": {
      "title": "Izhodne informacije",
      "sub_title": "Zaupne informacije o tem artiklu",
      "message": "Te informacije bodo uporabniku prikazane po nakupu izdelka."
    },
    "inputs": {
      "title": "Zahtevane informacije",
      "sub_title": "Zahtevani podatki o kupcu",
      "message": "Kupec mora v obrazec vnesti zahtevane podatke"
    },
    "notifications": {
      "inputs_set_success": "Informacijski obrazec je uspešno registriran.",
      "confirm_by_admin_success": "Dokončanje naročila potrjeno.",
      "confirm_by_buyer_success": "Dokončanje naročila potrjeno."
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "Tega naročila ni mogoče sprejeti s plačilom COD.",
    "payment_returned": "Plačilo s strani stranke se vrne.",
    "payment_fraud": "Plačilo je bilo ugotovljeno kot goljufija.",
    "location_out_of_service": "Lokacija stranke ni v uporabi.",
    "user_not_responding": "Stranka ni odgovorila na klice.",
    "shop_owner_fault": "Pri izpolnjevanju podatkov je prišlo do napake osebja trgovine.",
    "lack_of_inventory": "Ni na zalogi.",
    "legal_restriction": "Zaradi zakonskih omejitev ni mogoče oddati naročila.",
    "pricing_fault": "Napaka pri ceniku prodajalca.",
    "system_fault": "Sistemska napaka."
  },
  "basket_order_info_summery": {
    "receiver": "Sprejemnik",
    "phone": "tel",
    "reserved_date": "Datum nakupa",
    "total_price": "Skupni znesek",
    "discount": "Popust",
    "final_price": "Končni znesek",
    "address": "Dostavni naslov",
    "payment_status": "Stanje plačila"
  },
  "basket_status": {
    "open": "Odprto",
    "reserved": "Rezervirano",
    "paid": "Plačano",
    "canceled": "Prekinjeno",
    "cod": "Plačaj ob dostavi",
    "receipt_added": "Potrdilo je dodano",
    "payment_processing": "Obdelava plačil"
  },
  "basket_delivery_state": {
    "rejected": "Zavrnjeno",
    "reject_reason_not_found": "Razlog ni znan.",
    "step_1": "Pregled",
    "step_2": "Potrditev",
    "step_3": "Priprava",
    "step_4": "Ob dostavi",
    "step_5": "Dostavljeno"
  },
  "basket_return_request_view": {
    "title": "Zahteva za vračilo",
    "delivery_date": "Datum dostave",
    "return_date": "Datum zahteve",
    "items_count": "Štejejo se vrnjeni predmeti",
    "items_count_unit": "predmet(i)",
    "reason": "Razlog",
    "description": "Opis",
    "status": "Stanje",
    "download_image": "Prenesi sliko",
    "download_film": "Prenesi video",
    "download_voice": "Prenesite glas",
    "accept_by_admin_action": "Sprejmi zahtevo",
    "reject_by_admin_action": "Zavrni zahtevo",
    "message_for_admin": "V skladu s pogodbo, ki ste jo sprejeli z uporabo Selldone, morate kontaktirati kupca in ga obveščati o postopku vračila njegovega naročila. To je treba storiti, če je zahteva sprejeta ali zavrnjena in je pridobljeno kupčevo polno soglasje.",
    "notifications": {
      "update_status_success": "Stanje zahteve je posodobljeno."
    }
  },
  "basket_list": {
    "return_count": "Vrnitev: {count} številka",
    "table": {
      "row": "Vrstica",
      "image": "Slika",
      "product_name": "Izdelek",
      "variant": "Varianta",
      "warranty": "Garancije",
      "count": "štetje",
      "price": "cena"
    }
  },
  "return_request_list": {
    "count": "Referenčna številka",
    "return_warranty": "Garancija vračila denarja",
    "return_warranty_unit": "Dnevi)",
    "table": {
      "code": "Koda naročila",
      "product": "Izdelek",
      "delivery_at": "Datum prejema",
      "state": "Stanje",
      "reason": "Razlog",
      "return_warranty_period": "Garancijska doba"
    }
  },
  "data_toolbar": {
    "search": "Iskanje",
    "sort_by": "Razvrsti po",
    "count_item": "Pokaži {item} elementov"
  },
  "sort": {
    "created_at": "Ustvari datum",
    "updated_at": "Uredi datum",
    "title": "Naslov",
    "description": "Opis",
    "like": "Priljubljenost",
    "power": "Claps",
    "product_type": "Tip izdelka",
    "discount": "Popust",
    "rate": "Ocena",
    "rate_count": "Število ocen",
    "category": "Kategorija",
    "product": "Izdelek",
    "body": "Vsebina",
    "card_type": "Vrsta kartice",
    "card_number": "Številka kartice",
    "balance": "Ravnovesje",
    "paid": "Porabljeni znesek",
    "currency": "valuta",
    "expire_at": "Rok uporabnosti",
    "discount_code": "Koda za popust",
    "discount_percent": "Popust",
    "discount_limit": "Omejitev popusta",
    "max_count": "Največje število",
    "used_count": "Rabljen",
    "start_date": "Začetni datum",
    "end_date": "Končni datum",
    "total_discount_amount": "Skupni popusti",
    "initial_charge": "Začetno polnjenje",
    "total_count": "Skupno število",
    "amount_paid": "Plačani znesek",
    "name": "ime",
    "published": "Objavljeno",
    "visits": "Obiski",
    "color": "Barva",
    "landing_page": "Ciljna stran",
    "enable": "Omogoči",
    "fix_commission": "Fiksna provizija",
    "percent_commission": "Odstotek provizije",
    "payment_at": "Dan plačila",
    "issued_at": "Datum izdaje",
    "payment": "Plačilo",
    "website": "Spletna stran",
    "email": "E-naslov",
    "user": "Uporabnik",
    "code": "Koda",
    "schedule_at": "Datum urnika",
    "sender": "Pošiljatelj",
    "in_que": "V vrsti",
    "sent": "Poslano",
    "shop": "Nakupujte",
    "quantity": "Količina",
    "amount": "Znesek",
    "jobs": "Dela štejejo",
    "success": "Šteje se uspeh",
    "fail": "Število napak",
    "distance": "Razdalja",
    "duration": "Trajanje",
    "reset_at": "Ponastavi datum",
    "delivery_person": "Oseba",
    "delivery_service": "Storitev",
    "date": "Datum",
    "order": "Naročite",
    "order_id": "Številka naročila",
    "status": "Stanje",
    "price": "cena",
    "count": "štetje",
    "final_price": "Končna cena",
    "charge": "Napolniti",
    "mention": "Omeniti",
    "officer": "častnik",
    "registered": "Registriran",
    "purchased": "Kupljeno",
    "sex": "spol"
  },
  "search_box": {
    "result": "Rezultati iskanja",
    "tips": "Poiščite izdelke in kategorije",
    "label": "Iskanje ...",
    "category": "Kategorija"
  },
  "lead_status": {
    "physical_fast_delivery": "Takojšnja dostava",
    "physical_under_24h_delivery": "Dostavite v naslednjih {lead} urah",
    "physical_over_24h_delivery": "Priprava in oddaja od naslednjih {days} dni",
    "virtual_fast_prepare": "Takojšnja dostava",
    "virtual_under_24h": "Opravljeno v naslednjih {lead} urah",
    "virtual_over_24h": "Opravljeno od naslednjih {days} dni"
  },
  "return_request_state": {
    "pending": "V teku",
    "accepted": "Potrjeno",
    "rejected": "Zavrnjeno"
  },
  "return_order_reason": {
    "physical": {
      "U1": "Neusklajenost izdelkov",
      "U2": "V paketu za pošiljanje ni izdelka",
      "U3": "Zlom paketa ali izdelka",
      "U4": "Nedovoljeno poseganje v paket ali serijsko številko",
      "U5": "Nekateri predmeti iz paketa manjkajo",
      "U6": "Izdelek ni originalen",
      "U7": "Izdelek ne ustreza specifikacijam"
    }
  },
  "image_uploader": {
    "label": "Povlecite in spustite ali <u>izberite datoteko</u>",
    "max_size": "Največja dovoljena velikost: {size}"
  },
  "timespan": {
    "Morning": "8.00 - 12.00",
    "Evening": "od 12. do 18. ure",
    "Night": "18.00-12.00",
    "Instant": "Takojšnja objava"
  },
  "week_day": {
    "Saturday": "sobota",
    "Sunday": "nedelja",
    "Monday": "ponedeljek",
    "Tuesday": "torek",
    "Wednesday": "sreda",
    "Thursday": "četrtek",
    "Friday": "petek"
  },
  "payment_form": {
    "title": "Izberite način plačila",
    "gift_cards_input": "Darilne kartice",
    "gift_cards_input_empty": "Najdena ni bila nobena darilna kartica..",
    "more": "Drugo",
    "pay_amount_by_gift_cards": "Plačilo s kartico",
    "select_payment_method": "Izberite način plačila med naslednjimi možnostmi.",
    "payment_amount_remained": "Preostali znesek plačila",
    "payment_amount": "Plačani znesek",
    "all_paid_by_gift_cards": "Čestitamo, za to naročilo vam ni treba plačati. Pritisnite tipko Plačaj z darilno kartico.",
    "pay_by_gift_cards_action": "Plačajte naročilo s plačilno kartico",
    "order_free_payment": "Čestitamo, vaše naročilo je brezplačno!",
    "order_free_payment_action": "Naročite brezplačno zdaj",
    "qr": {
      "address": "Naslov za plačilo",
      "amount": "Znesek"
    }
  },
  "discount_input": {
    "limit": "{percent} % popusta do {limit} {currency}",
    "action": "Dodajte kodo za popust",
    "code_input": "Koda za popust",
    "notifications": {
      "add_success": "Čestitamo, veljavna koda za popust."
    }
  },
  "gift_card": {
    "inactive": "Kartica je onemogočena",
    "expire": "Potek veljavnosti",
    "transfer": "Prenos",
    "send_to_friend": "Pošlji prijatelju"
  },
  "count_down": {
    "days": "dan",
    "hours": "ura",
    "minutes": "Minute",
    "seconds": "Sekund"
  },
  "gift_status": {
    "Unpaid": "Čakanje na prejem",
    "Paid": "Plačano",
    "Rejected": "Zavrnjeno",
    "Canceled": "Prekinjeno"
  },
  "gift_program_status": {
    "Airdrop": "Plačilni sistem",
    "Advertising": "Oglaševanje",
    "PersonalGift": "Osebno darilo",
    "ShopGift": "Trgovina z darili"
  },
  "currency_selector": {
    "label": "valuta"
  },
  "need_login": {
    "title": "Vpiši se",
    "login_sms": "SMS prijava",
    "login_google": "Prijavite se z Googlom",
    "login_facebook": "Prijava s Facebookom",
    "login_account": "Prijava prek Selldone",
    "register": "Nov uporabnik? Registriraj se zdaj.",
    "mobile_input": "Vnesite svoj mobilni telefon",
    "verification_code": "Koda za preverjanje",
    "msg_title": "zdravo,",
    "msg_body": "Prosimo, prijavite se. Traja le nekaj sekund.",
    "login_apple": "Prijavite se z Appleom"
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "5 letna trgovina z zlatom"
    },
    "GOLDEN_2YEAR": {
      "name": "4-letna trgovina z zlatom"
    },
    "GOLDEN_3YEAR": {
      "name": "3 letna trgovina z zlatom"
    },
    "GOLDEN_4YEAR": {
      "name": "2-letna trgovina z zlatom"
    },
    "GOLDEN_5YEAR": {
      "name": "1 letna trgovina z zlatom"
    },
    "TOKEN_OWNER_1M": {
      "name": "Zlati investitor"
    },
    "TOKEN_OWNER_10M": {
      "name": "Diamantni investitor"
    },
    "TOKEN_OWNER_100M": {
      "name": "Ruby Investitor"
    },
    "COMMUNITY_LOYAL": {
      "name": "Član višje skupnosti komunikacijskih omrežij"
    },
    "GOLD_SUPPLIER": {
      "name": "Dobavitelj zlata"
    },
    "GOLD_SELLER": {
      "name": "Trgovec z zlatom"
    },
    "CONTENT_SUPERMAN": {
      "name": "Vrhunski proizvajalec vsebin"
    },
    "NINJA": {
      "name": "Ninja"
    },
    "STAR": {
      "name": "zvezda"
    },
    "GUARDIAN": {
      "name": "Odlična storitev za stranke"
    },
    "KING": {
      "name": "Kralj trga"
    }
  },
  "cookie": {
    "title": "To spletno mesto uporablja piškotke",
    "message": "To spletno mesto uporablja piškotke za izboljšanje uporabniške izkušnje. Z uporabo naše spletne strani se strinjate z vsemi piškotki v skladu z našo Politiko piškotkov.",
    "preferences_action": "Upravljanje nastavitev",
    "agree_action": "Strinjam se"
  },
  "basket_item_message": {
    "title": "Zahtevani podatki za ta artikel",
    "save_actions": "Shrani sporočilo",
    "notifications": {
      "success": "Vaši vhodni podatki so shranjeni."
    }
  },
  "faq": {
    "faq": "Pogosto zastavljena vprašanja",
    "title": "Vprašanja in odgovori",
    "sub_title": "Kaj ste zahtevali od nas.",
    "message": "Odgovor na svoje vprašanje poiščite med spodnjimi odgovori. Vprašajte nas, če vprašanja ostanejo neodgovorjena.",
    "add_question_action": "Postavite novo vprašanje",
    "read_more": "Preberi več ..",
    "load_more": "Več vprašanj ..",
    "main_page": "Glavna stran s pogostimi vprašanji",
    "add_new": "Pošlji novo vprašanje",
    "login_alert": "Prijavite se, če želite postaviti vprašanje.",
    "question_input": "vprašanje",
    "question_input_placeholder": "Zastavite svoje vprašanje.",
    "notifications": {
      "success_add": "Vaše vprašanje je uspešno poslano."
    }
  },
  "rating_labels": [
    "Zelo slabo",
    "Slab",
    "Normalno",
    "dobro",
    "Odlično"
  ],
  "map_view": {
    "address_detail": "Podrobnosti o naslovu",
    "change": "Spremeni se",
    "select": "Izberite",
    "not_found_address": "Najdena ni nobena vrednost",
    "enter_address_hint": "Vnesite ciljni naslov",
    "enter_your_address": "Vnesite svoj naslov.",
    "postal_code": "poštna številka",
    "phone_input": "Telefon {type}",
    "building_number": "Številka stavbe",
    "building_unit": "enota",
    "full_name_input": "Polno ime {type}",
    "save_detail_action": "Shranite podrobnosti",
    "more_detail_input": "Več opisa",
    "add_address_to_list": "Dodaj naslov na seznam",
    "address_title_input": "Oznaka naslova (zahteva)",
    "notifications": {
      "save_in_list": "Ta naslov je bil shranjen na vaš seznam z vsemi svojimi podrobnostmi.",
      "edit_success": "Nove vrednosti naslova so shranjene v {title}."
    },
    "delete_address_dialog": {
      "title": "Izbriši naslov",
      "message": "Ali ste prepričani, da želite izbrisati ta naslov?",
      "action": "Odstrani naslov"
    }
  },
  "comment_manager": {
    "can_not_edit": "Tega komentarja ni mogoče urediti!",
    "comment_input_empty": "Besedilo sporočila je prazno!",
    "article_not_saved": "Shranite članek!"
  },
  "wheel_fortune": {
    "title": "Igraj & Zmagaj",
    "message": "Cena posamezne igre je 10 žetonov. Trenutno imate {chips} čip. Pridobite več žetonov z nakupom v trgovini.",
    "win_message": "Čestitam, zmagal si!",
    "lost_message": "Oprosti, izgubil si igro.",
    "try_again": "Lahko poskusite znova"
  },
  "json": {
    "add": "Dodajte strukturne podatke",
    "add_message": "Ustvarite nove strukturne podatke",
    "structures": "Strukture",
    "book": {
      "title": "knjiga",
      "desc": "Dejanja knjige, ki uporabnikom omogočajo nakup knjige, ki jo najdejo neposredno iz rezultatov iskanja."
    },
    "occupation": {
      "title": "Ocenjena plača",
      "desc": "Informacije o oceni plače, kot so razponi plač in povprečne plače na podlagi regij za vrste delovnih mest, prikazane v izkušnji iskanja zaposlitve v Googlu."
    },
    "course": {
      "title": "seveda",
      "desc": "Izobraževalni tečaji, ki so prikazani na seznamu za posameznega ponudnika. Tečaji lahko vključujejo naslov tečaja, ponudnika in kratek opis."
    },
    "howto": {
      "title": "Kako",
      "desc": "Navodilo vodi uporabnike skozi niz korakov za uspešno dokončanje naloge, ki vključuje video, slike in besedilo."
    },
    "recipe": {
      "title": "Recept",
      "desc": "Recepti, ki so prikazani kot posamezen bogat rezultat ali del gostiteljskega vrtiljaka."
    }
  },
  "support": {
    "Financial": "Finančna",
    "Technical": "Tehnični",
    "Advisor": "svetovalec"
  },
  "condition": {
    "new": "Novo",
    "refurbished": "Prenovljen",
    "used": "Rabljen",
    "used_fair": "Rabljen pošteno",
    "used_good": "Dobro rabljeno",
    "used_like_new": "Rabljen kot nov"
  },
  "variant_filter": {
    "title": "Filter variante izdelka",
    "only_available": "Na zalogi"
  },
  "service": {
    "task": {
      "title": "Naloge",
      "message": "Seznam nalog, ki se izvajajo v tej storitvi."
    },
    "appointment": {
      "title": "Imenovanje",
      "message": "Izberite ure v tednu izmed naslednjih ur glede na dan in uro, ki vam ustrezata."
    },
    "booking": {
      "title": "Rezervacija",
      "message": "V spodnjem koledarju določite časovno obdobje dni, ko želite rezervirati."
    },
    "subscription": {
      "title": "Naročnina"
    },
    "charge": {
      "title": "Napolniti"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "Fiksne cene",
      "message": "Pri tovrstnem oblikovanju cen je cena izdelka fiksni znesek in kupcu ni treba zahtevati izračuna cene."
    },
    "ESTIMATION": {
      "title": "Ocene cen",
      "message": "Ceno izdelkov in storitev bo do neke mere izračunal prodajalec ob oddaji naročila, račune za plačila se lahko spreminjajo ali dodajajo med storitvijo."
    },
    "AGREEMENT": {
      "title": "Cene po dogovoru",
      "message": "Končne cene izdelkov ali storitev prodajalec po oddaji naročila ne bo spremenil."
    },
    "BID": {
      "title": "Ponudba / Dražba",
      "message": "Izdelek bodo potencialni kupci prodali po najvišji ponudbeni ceni."
    }
  },
  "map": {
    "title": "Destinacija za prejem izdelkov",
    "confirm": "Nastavite lokacijo",
    "address": "Destinacija",
    "receptor": "Sprejemnik"
  },
  "ShopBots": {
    "telegram": "Telegram"
  },
  "article_tags": {
    "title": "Oznake vsebine",
    "tags_input": "Oznake",
    "tags_input_message": "Seznam oznak tega članka",
    "notification": {
      "add_success": "Dodane oznake"
    }
  },
  "difficulties": {
    "very_complicated": "Zelo zapleteno",
    "hard": "težko",
    "intermediate": "Vmesno",
    "easy": "enostavno"
  }
};