export default {
  "currency_default": "USD",
  "language_default": "ен",
  "selldone": "Селлдоне",
  "store": "продавница",
  "not_exist": "Не постоји",
  "error": "Грешка",
  "active": "Ацтиве",
  "inactive": "неактиван",
  "required_value": "Обавезне вредности",
  "original_warranty": "Оригинална гаранција производа",
  "return_warranty_days": "{days} дан(а) гаранције поврата",
  "no_return_warranty": "Нема повратка",
  "reed_agree_terms": "Прочитао сам услове коришћења и политику приватности и слажем се са њима.",
  "commons": {
    "Currency": "Валута",
    "COD": "COD",
    "State": "Стање",
    "Price": "Цена",
    "order_price": "Износ поруџбине",
    "VAT": "VAT",
    "Discount": "Попуст",
    "In_Stock": "На лагеру",
    "Variants": "Варијанте",
    "No_variants": "Без варијанте",
    "all": "СВЕ",
    "today": "Данас",
    "yesterday": "Јучер",
    "license": "Лиценца",
    "home": "Кућа",
    "support": "Подршка",
    "messages": "Поруке",
    "no_message": "Нема поруке",
    "empty": "Празан",
    "phone": "Телефон",
    "address": "адреса",
    "name": "Име",
    "password": "Лозинка",
    "email": "Емаил",
    "mobile": "Мобилни",
    "login": "Пријавите се",
    "register": "Регистровати",
    "select_account": "Изаберите налог",
    "online": "Онлине",
    "offline": "Одсутан",
    "finish": "Заврши",
    "finished": "Готов",
    "preview": "Преглед",
    "free": "бесплатно",
    "free_completely": "Потпуно бесплатна претплата",
    "fee": "Надокнада",
    "month": "Месец дана",
    "months": "месеци",
    "faq": "Често постављана питања",
    "question": "Питање",
    "answer": "Одговор",
    "create_date": "Датум креирања",
    "update_date": "Ажурирати датум",
    "start_date": "Датум почетка",
    "end_date": "Крајњи датум",
    "social": "Социал",
    "total": "Укупно",
    "orders": "Наређења",
    "sessions": "Сесије",
    "product_views": "Прегледи производа",
    "add_to_carts": "Додај у колица",
    "checkouts": "Провери",
    "payments": "Плаћање",
    "organic_search": "Органска претрага",
    "other": "Остало",
    "landing_page": "Почетне странице",
    "discount_code": "Код за попуст",
    "total_sell": "Укупна продаја",
    "details": "Детаљи",
    "currency": "Валута",
    "amount": "Износ",
    "published": "Објављено",
    "draft": "Нацрт",
    "save_changes": "Сачувај промене",
    "source": "Извор",
    "medium": "Средње",
    "url": "Урл",
    "revenue": "Приход",
    "performance": "Перформансе",
    "term": "Термин",
    "content": "Садржај",
    "session": "Седница",
    "product": "Производ",
    "add": "Додати",
    "checkout": "Провери",
    "payment": "Плаћање",
    "more_options": "Више опција",
    "full_name": "Пуно име",
    "tel": "Тел",
    "about_me": "О мени",
    "request_checking": "Захтевај проверу",
    "passport": "Пасош",
    "birthday": "Рођендан",
    "country": "Држава",
    "city": "Град",
    "gender": "Пол",
    "offer": "Понуда",
    "website": "Веб сајт",
    "apply_for_all_products": "∞ Пријавите се за све производе",
    "fix_commission": "Фиксна провизија",
    "percent_commission": "Проценат провизије",
    "fixed_discount": "Фиксни попуст",
    "discount_percentage": "Проценат попуста",
    "discount_limit": "Ограничење попуста",
    "no_code": "Нема кода",
    "max_count": "Максимални број",
    "count_unit": "Предмети",
    "used": "Користи се",
    "daily": "Даили",
    "monthly": "Месечно",
    "yearly": "Годишње",
    "state": "Статус",
    "disable": "Онемогући",
    "enable": "Омогући",
    "activation_code": "Активациони код",
    "quantity": "Количина",
    "no_club": "Нема клуба",
    "per_order": "По наруџбини",
    "count": "Цоунт",
    "seconds": "Секунде",
    "auto": "Ауто",
    "title": "Наслов",
    "message": "Порука",
    "width": "Ширина",
    "length": "Дужина",
    "height": "Висина",
    "label": "Ознака",
    "click": "Кликните",
    "bank": "банка",
    "default": "Уобичајено",
    "role": "Улога",
    "user": "корисник",
    "users": "Корисници",
    "code": "Код",
    "total_payment": "Укупан износ",
    "balance": "Баланс",
    "chance": "Шанса",
    "free_for_new_users": "Бесплатно за нове кориснике",
    "prize_amount": "Износ награде",
    "win": "Победити",
    "gift_card": "Поклон картица",
    "discount": "Попуст",
    "config": "Цонфиг",
    "prize": "Награда",
    "Prizes": "Награде",
    "result": "Резултат",
    "price": "Цена",
    "lottery": "Лутрија",
    "coupon": "Цоупон",
    "customer_club": "Клуб купаца",
    "shipping": "поштарина",
    "sum": "Сум",
    "not_paid": "Неплаћен",
    "category": "Категорија",
    "done": "Готово",
    "email_from": "Од",
    "subject": "Предмет",
    "schedule": "Распоред",
    "files_list": "Листа датотека",
    "file_max_size": "Максимална величина датотеке",
    "value": "Валуе",
    "help": "Помоћ",
    "shipping_tax": "Порез на доставу",
    "net_price": "Нето цена",
    "tax": "Порез",
    "tax_included": "Укључено у цену",
    "limit": "Лимит",
    "min_purchase": "Минимална куповина",
    "eligible_for": "Право на",
    "only_for_first_buy": "Само за прву куповину",
    "one_time_use": "Може се користити једном",
    "period_of_qualify": "Ограничење употребе у периоду",
    "no_constraint": "Без лимита",
    "timespan": "Временски период",
    "days": "дан(и)",
    "weight": "Тежина",
    "distance": "Удаљеност",
    "last_status": "Последњи статус",
    "issued_at": "Издата у",
    "order": "Ред",
    "order_detail": "Детаљи поруџбине",
    "percent": "проценат",
    "applied_count": "Примењено бројање",
    "campaign": "Кампања",
    "os": "Оперативни систем",
    "browser": "Прегледач",
    "device": "Уређај",
    "device_ip": "ИП адреса уређаја",
    "location": "Локација",
    "user_agent": "Кориснички агент",
    "affiliate": "Аффилиате",
    "timeline": "Временска линија",
    "add_note": "Додај белешку",
    "record": "Запис",
    "unlimited": "Неограничено",
    "show_coupons": "Прикажи купоне",
    "hide_coupons": "Сакриј купоне",
    "service_area": "Сервис област",
    "apps": "апликације",
    "plugins": "Плугинс",
    "bots": "Ботс",
    "categories": "Категорије",
    "products": "Производи",
    "business": "Посао",
    "personal": "Лични",
    "size": "Величина",
    "holiday": "Празник",
    "sod": "Плаћање приликом испоруке",
    "cod": "Плаћање поузећем",
    "free_shipping": "Бесплатна достава",
    "hours": "Сати",
    "send_date": "Датум испоруке",
    "deliver_date": "Датум испоруке",
    "return_date": "Датум повратка",
    "pending": "нерешен",
    "delivered": "Испоручена",
    "returned": "Вратио се",
    "canceled": "Отказано",
    "shipping_cost": "Трошак отпремања",
    "action": "поступак",
    "cancel_date": "Датум отказивања",
    "deliver_in_process": "Наруџба је послата..",
    "kind": "Тип",
    "detail": "Детаљи",
    "map": "Мапа",
    "actions": "Акције",
    "navigation": "Навигација",
    "navigation_app": "Апликација",
    "payment_date": "Датум исплате",
    "duration": "Трајање",
    "bill": "Билл",
    "delivery_persons": "Курири",
    "delivery_services": "Услуге доставе",
    "live_view": "Поглед уживо",
    "cart": "Царт",
    "priority": "Приоритет",
    "sufficient_credit": "Довољан кредит",
    "max_package_size": "Максимална величина пакета",
    "delay": "Кашњење",
    "credit": "Кредит",
    "livemode": "Уживо",
    "paused": "Паузирано",
    "debug": "Отклањање грешака",
    "token": "Токен",
    "status": "Статус",
    "courier": "Курир",
    "track": "Трацк",
    "track_order": "Праћење наруџби",
    "cost": "Цост",
    "receipt": "Признаница",
    "origin": "Порекло",
    "destination": "Одредиште",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "Нема довољно залиха!",
    "sub_total": "Међузбир",
    "customer": "Купац",
    "delivery": "Испорука",
    "online_orders": "Онлине Ордерс",
    "pos_orders": "ПОС налоге",
    "chips": "Чипс",
    "subscribed": "Претплаћени",
    "unsubscribed": "Отказано је",
    "last_login": "Последње пријављивање",
    "join_at": "Датум придруживања",
    "club": "Цлуб",
    "buyer": "Купац",
    "seller": "продавац",
    "or": "Ор",
    "type": "Тип",
    "condition": "Стање",
    "brand": "Марка",
    "attempt": "Покушај",
    "error": "Грешка",
    "success": "успех",
    "fail": "Фаил",
    "inventory": "Инвентар",
    "link": "Линк",
    "visits": "Посете",
    "transactions": "Трансакције",
    "vat": "VAT",
    "pos_vat": "ПОС ПДВ",
    "sort_by": "Сортирај по..",
    "from": "Од",
    "from_lead_time": "У наредних {hours} сати",
    "no_credit_card_info": "Нема информација о картици!",
    "active": "Ацтиве",
    "not_active": "Није активиран!",
    "referrals": "Препоруке",
    "dashboard": "Командна табла",
    "more": "Више",
    "inactive": "неактиван",
    "developer": "Девелопер",
    "setting": "Подешавање",
    "membership_conditions": "Услови чланства",
    "customers": "Купци",
    "created_at": "Датум креирања",
    "updated_at": "Последње ажурирање",
    "register_at": "Датум регистрације",
    "old": "Стара",
    "new": "Нова",
    "start": "Почетак",
    "end": "Крај",
    "pos": "POS",
    "out_of_stock": "Нема на залихи",
    "fake": "Фалсификат",
    "low_inventory_warning": "Пажња, мали инвентар!",
    "webhook": "Вебхоок",
    "notification": "Обавештење",
    "sms": "SMS",
    "online_payment_link": "Линк за плаћање на мрежи",
    "waiting_load_data": "Чека се учитавање података..",
    "views": "Погледи",
    "sales": "Продаја",
    "total_views": "Укупно прегледа",
    "total_sales": "Укупна продаја",
    "from_previous_n_days": "Од последњих {days} дана",
    "drop_shipping": "Испустити поруџбеницу",
    "commission": "Комисија",
    "shipping_area": "Подручје испоруке",
    "main_seller": "Главни продавац",
    "domain": "Домаин",
    "contact": "Контакт информације",
    "wallet": "Новчаник",
    "reseller": "Реселлер",
    "tracking_code": "Код за праћење",
    "tracking_url": "УРЛ за праћење",
    "fulfillments": "Испуњења",
    "reject": "Одбити",
    "reserved": "Резервисано",
    "score": "Сцоре",
    "customer_price": "Цена купца",
    "options": "Опције",
    "show_details": "Прикажи детаље",
    "no_data": "Нема података..",
    "waiting": "чекам...",
    "waiting_connecting_payment": "Чека се услуга плаћања...",
    "creating_secure_payment": "Креирање безбедног плаћања.",
    "officer": "официр",
    "ticket": "Улазница",
    "ticket_url": "Тицкет урл",
    "closed_at": "Затворено у",
    "close_ticket": "Затвори карту",
    "reopen_ticket": "Поново отвори карту",
    "require": "Захтевај*",
    "search": "Претрага...",
    "language": "Језик",
    "tasks": "Задаци",
    "permissions": "Дозволе",
    "finish_date": "Крајњи датум",
    "complete_date": "Датум завршетка",
    "settle_date": "Датум поравнања",
    "cost_span": "Распон цена",
    "industry": "Индустрија",
    "rating": "Оцене",
    "rates": "Оцена",
    "seen_at": "Сеен ат",
    "completed": "Завршено",
    "you": "ти",
    "shop": "Схоп",
    "store": "продавница",
    "granted": "Одобрено",
    "deny": "негирати",
    "request": "Захтев",
    "expert": "Експерт",
    "response": "Одговор",
    "requests": "Захтеви",
    "experts": "Експерти",
    "responses": "Одговори",
    "negotiations": "Преговори",
    "all_chats": "Сва ћаскања",
    "chats": "Ћаскања",
    "tags": "Ознаке",
    "description": "Опис",
    "rates_count": "Број оцена",
    "rate": "Оцена",
    "comment": "Коментар",
    "chat": "Ћаскање",
    "install": "Инсталирај",
    "edited": "Едитед",
    "undo": "Поништи",
    "redo": "Понови",
    "male": "Мушки",
    "female": "Женско",
    "calculator": "Калкулатор",
    "catalog": "Каталог",
    "max_height": "Максимална висина",
    "images_compare": "Поређење слика",
    "canvas": "Цанвас",
    "table_of_contents": "Преглед садржаја",
    "comments": "Коментари",
    "badge_codes": "Код значке",
    "need_more": "Потребно више?",
    "invite_glow_caption": "Добијте 14,9$ за сваког пријатеља!",
    "register_free": "100% бесплатна регистрација",
    "gift": "Поклон",
    "google": "Гоогле",
    "facebook": "Фејсбук",
    "instagram": "инстаграм",
    "instashop": "Инстасхоп",
    "show": "Прикажи",
    "hide": "Сакрити",
    "waiting_review": "Чека се преглед",
    "not_selected": "Није изабран",
    "time": "време",
    "final_price": "Коначна цена",
    "starting_price": "Почетна цена",
    "day": "Дан",
    "paid": "Плаћено",
    "service_bill": "Фактура исплата",
    "avocado": "Авокадо",
    "delivery_price": "Трошак отпремања",
    "select_address": "Изаберите адресу",
    "image": "Слика",
    "view": "Поглед",
    "sell": "Распродаја",
    "hyper": "Хипер",
    "cart_list": "Царт",
    "barcode_scanner": "Бар код скенер",
    "scan_qr_code": "Скенирање КР код",
    "new_carts": "Нова колица",
    "pays": "Плаћања",
    "annually": "Сваке године",
    "sells": "Продаја",
    "articles": "Чланци",
    "jobs": "Послови",
    "job": "Јоб",
    "blog": "Блог",
    "deleted_at": "Избрисано у",
    "capacity": "Капацитет",
    "download_at": "Датум последњег преузимања",
    "downloads": "Преузимања",
    "usage": "Употреба",
    "select_upload_file": "Изаберите или испустите датотеку",
    "download_link": "Линк за скидање",
    "uploading": "Отпремање..",
    "files": "Фајлови",
    "star": "Звезда",
    "speed": "Брзина",
    "feedback": "Повратна информација",
    "new_messages": "Нове поруке",
    "file": "Филе",
    "attachment": "Прилог",
    "gallery": "Галерија",
    "sync": "Синхронизовати",
    "diff_time": "Временска разлика",
    "network": "Мрежа",
    "account": "Рачун",
    "configuration": "Конфигурација",
    "blockchain": "Блоцкцхаин",
    "blog_link": "Блог линк",
    "community": "Заједница",
    "critical_zone": "Критична зона",
    "statistics": "Статистика",
    "access": "Приступ",
    "seo": "SEO",
    "followers": "Фолловерс",
    "followings": "Фолловингс",
    "private": "Преглед",
    "soon": "Ускоро",
    "features": "Карактеристике",
    "bot": "Бот",
    "sample": "Узорак",
    "how_it_work": "Како то функционише?",
    "page": "Страна",
    "congratulations": "Честитам",
    "recommend": "Препоручити",
    "recommended": "Препоручено",
    "recoms": "Препоруке",
    "likes": "Свиђа",
    "clicks": "Кликови",
    "platform": "Платформа",
    "cms": "CMS",
    "cash": "Цасх",
    "dir_payment": "банкарски трансфер",
    "auto_complete": "Аутоматско довршавање",
    "compare": "Упоредити",
    "infinite": "Бесконачно",
    "tips": "Савети",
    "technical": "Технички",
    "finance": "финансије",
    "your_phone_input": "Унесите број телефона",
    "income": "Приходи",
    "change": "Промена",
    "new_users": "Нови Корисници",
    "success_orders": "Успешне поруџбине",
    "direct": "Директан",
    "last_activity": "Последња активност",
    "landing": "Слетање",
    "now": "Сада",
    "accept_agreement": "Прочитао сам и прихватио услове.",
    "report": "Извештај",
    "tablet": "Таблет",
    "pc": "PC",
    "acquisition_channel": "Канал аквизиције",
    "to": "До",
    "info": "Инфо",
    "general": "Генерал",
    "upload": "Отпремити",
    "general_config": "Општа конфигурација",
    "limits_config": "Ограничења",
    "design_config": "Дизајн и стил",
    "duration_config": "Ограничење трајања",
    "constraints_config": "Границе подобности",
    "clubs_config": "Доступно у клубовима",
    "additional_config": "Додатне конфигурације",
    "import": "Увоз",
    "ribbon": "Риббон",
    "countries": "Земље",
    "edit": "Уредити",
    "delete": "Избриши",
    "analytics": "Аналитика",
    "rules": "Правила",
    "unset": "Није подешено",
    "carts": "Цартс",
    "optional": "Опционо",
    "design": "Дизајн",
    "filter": "Филтер",
    "send": "Пошаљи",
    "approved": "Одобрено",
    "unit": "Јединица",
    "profile": "профил",
    "shipping_rates": "Схиппинг ратес",
    "package": "Пакет",
    "overview": "Преглед",
    "live": "Уживо",
    "never": "Никада",
    "always": "Увек",
    "mandatory": "Обавезно",
    "expire_at": "Датум истека",
    "position": "Положај",
    "channel": "Канал",
    "age": "Старост",
    "charge": "Напунити",
    "giftcard": "Поклон картица",
    "acquisition": "Аквизиција",
    "conversion": "Конверзија",
    "total_payments": "Укупна плаћања",
    "community_ask": "Питајте у заједници",
    "children": "Деца",
    "export": "Извоз",
    "list": "Листа",
    "hierarchy": "Хијерархија",
    "images": "Слике",
    "demo": "Демо",
    "author": "Аутор",
    "designer": "Дизајнер",
    "max": "Максимум",
    "accepted": "Прихваћено",
    "reply": "Одговорити",
    "reviewed": "Прегледано",
    "restored": "Обновљена",
    "merchant": "трговац",
    "per_product": "По производу",
    "journey": "Путовање",
    "after": "После"
  },
  "dialogs": {
    "delete": {
      "title": "Избриши",
      "message": "Да ли сте сигурни да избришете ову ставку?",
      "action": "Да, Избриши сада"
    }
  },
  "actions": {
    "add_to_cart": "Додај у колица",
    "cancel": "Поништити, отказати",
    "update": "ажурирање",
    "add": "Додати",
    "delete": "Избриши",
    "new": "Нова",
    "save_continue": "Сачувај и настави",
    "save": "сачувати",
    "save_changes": "Сачувај промене",
    "change": "Промена",
    "continue": "Настави",
    "close": "Близу",
    "finish": "Заврши",
    "poll": "Анкета",
    "view": "Поглед",
    "edit": "Уредити",
    "next": "Следећи",
    "previous": "Претходна",
    "create": "Креирај",
    "set": "комплет",
    "find": "Финд",
    "accept": "Прихвати",
    "reject": "Одбити",
    "back": "Назад",
    "pay": "Плати",
    "pay_now": "Платити сада",
    "print": "Принт",
    "return": "Повратак",
    "publish": "Објавите",
    "confirm": "Потврди",
    "copy": "Копирај",
    "submit": "прихвати",
    "send": "Пошаљи",
    "yes": "да",
    "no": "не",
    "meh": "Хмм",
    "clear": "Јасно",
    "dismiss": "Одбаци",
    "search": "Претрага",
    "deselect_all": "Поништите све",
    "select_all": "Изабери све",
    "refresh": "Освјежи",
    "verify": "Проверити",
    "play": "Игра",
    "open": "Отвори",
    "calculate": "Израчунај",
    "quick_buy": "Куицк Буи",
    "click_here": "Кликните овде",
    "schedule": "Распоред",
    "send_now": "Пошаљи одмах",
    "download": "Преузимање",
    "reset_default": "Ресетујте на подразумеване вредности",
    "reset": "Ресетовање",
    "check": "Проверавати",
    "cod_payment": "Плаћање поузећем",
    "dir_payment": "Трансфер новца",
    "online_payment": "Онлине Паимент",
    "checkout": "Провери",
    "show_all": "Покажи све",
    "login": "Пријавите се",
    "logout": "Одјавити се",
    "more": "Више..",
    "collapse": "Колапс",
    "apply_change": "Примените измене",
    "apply": "Применити",
    "add_giftcard": "Додајте поклон картицу",
    "charge": "Напунити",
    "send_invites": "Пошаљите позивнице",
    "past": "Прошлост",
    "restore": "Ресторе",
    "cut": "Цут",
    "get_sms_code": "Набавите код за аутентификацију",
    "register_no_mail": "Наставите без е-поште",
    "no_mail_register_message": "Немате адресу е-поште или сте заборавили лозинку?",
    "reset_by_mail": "Опоравак лозинке путем е-поште",
    "reset_by_sms": "Опоравак лозинке путем СМС-а",
    "cash_payment": "Готовинско плаћање",
    "show_chart": "Прикажи графикон",
    "open_app": "Отворите апликацију",
    "login_now": "Лог ин сада",
    "watch_video": "Погледајте видео",
    "check_now": "Проверите сада",
    "remove_image": "Уклони слику",
    "view_website": "Отвори линк",
    "explore": "Истражите {name}",
    "go": "Иди",
    "read_more": "Опширније",
    "start_now": "Почните сада — бесплатно је",
    "view_live": "Погледајте уживо",
    "resend_code": "Поново пошаљи шифру",
    "invite": "Позови",
    "add_more": "Додај још",
    "install_now": "Инсталирајте сада",
    "uninstall": "Деинсталирај",
    "show_preview": "Покажи преглед",
    "hide_preview": "Сакриј преглед",
    "download_now": "Преузми сада",
    "auto_fill": "Аутофилл",
    "track": "Трацк",
    "change_state": "Промени статус",
    "done": "Готово",
    "reply": "Одговорити"
  },
  "instance_message_title": "Пошаљите тренутну поруку",
  "instance_message": "Здраво {name}, ја сам {author} из {company}.",
  "errors": {
    "419": "Дуго сте били неактивни, молимо вас <b>⟳ ОСВЕЖИТЕ СТРАНИЦУ</b> из безбедносних разлога.",
    "gateway_blockchain_sync_error": "Систем се не синхронизује са блокчејном. Неће бити могуће креирати нову трансакцију док се синхронизације наших сервера не заврше. Ми решавамо проблем.",
    "gateway_network_error": "Услуга пролаза за плаћање је наишла на проблем у комуникацији."
  },
  "receiver_info": {
    "map": {
      "title": "Достава Адреса",
      "confirm": "Подесите локацију",
      "address_type": "Одредиште",
      "receptor_type": "Пријемник"
    },
    "receiver_address": "Изаберите адресу за испоруку",
    "address": "адреса",
    "postcode": "Поштански број",
    "enter_value": "Попуните овде",
    "address_note": "Белешка",
    "tel": "Контакт број"
  },
  "weight": {
    "g": "г",
    "oz": "оз",
    "lb": "фунта",
    "kg": "кг"
  },
  "mass_unit_name": {
    "g": "грам",
    "oz": "Унца",
    "lb": "фунта",
    "kg": "килограма"
  },
  "length": {
    "cm": "центиметар",
    "in": "ин",
    "ft": "фт",
    "mm": "мм",
    "m": "м",
    "yd": "ид"
  },
  "size_unit_name": {
    "cm": "Центиметар",
    "in": "Инч",
    "ft": "Нога",
    "mm": "милиметар",
    "m": "метар",
    "yd": "Двориште"
  },
  "distance": {
    "m": "метар",
    "km": "км"
  },
  "time": {
    "days": "Дани",
    "hours": "Сати",
    "minutes": "Минута",
    "seconds": "Секунде"
  },
  "units": [
    "Јединица",
    "предмет",
    "сваки",
    "комплет",
    "комад",
    "килограма",
    "грам",
    "милиграма",
    "метар",
    "милиметар",
    "квадратни метар",
    "квадратни Фит",
    "кубни метар",
    "литар",
    "милилитара",
    "стопала",
    "галона",
    "инча",
    "унце",
    "фунти",
    "кварти",
    "јарди",
    "соба"
  ],
  "region_types": {
    "State": "Стање",
    "Territory": "Територија",
    "Province": "Провинција"
  },
  "transaction_status": {
    "RequireAction": "Мере потребне",
    "Processing": "Обрада",
    "Canceled": "Отказано",
    "Succeeded": "Успео"
  },
  "placeholders": {
    "name": "Јоне Цок",
    "email": "ваш-маил@маил.цом",
    "phone": "+1 000 0000",
    "language": "Изаберите језик..",
    "friend_email": "Имејл вашег пријатеља...",
    "friend_name": "Опт. Име вашег пријатеља",
    "select_date": "Изаберите датум..."
  },
  "notification": {
    "confirm": "Потврди",
    "confirm_message": "Промене су успешно сачуване.",
    "error": "Грешка",
    "message": "Порука",
    "caution": "Опрез",
    "warning": "Упозорење",
    "award": "Честитам",
    "error_message": "Нажалост, дошло је до грешке.",
    "congratulation": "Честитам",
    "coming_soon": "Ускоро",
    "on_fetching_data": "Примање информација ..",
    "new_pwa_version": "Нова верзија доступна је сада. Да ли желите да ажурирате апликацију?",
    "over_license_limit": "Прекорачење ограничења лиценце",
    "update_license": "Ажурирајте своју лиценцу",
    "required": "Потребан",
    "invalid_email": "Неважећа е-маил",
    "invalid_domain": "Неважећи домен",
    "invalid_min_length": "Минимална дужина мора бити {length}",
    "invalid_min_array_length": "Барем изаберите {length} ставки",
    "invalid_max_chars": "Максимално {maxCount} знакова",
    "invalid_url": "Неважећи УРЛ"
  },
  "colors": {
    "#D32F2F": "Црвени",
    "#C2185B": "Пинк",
    "#7B1FA2": "Љубичаста",
    "#512DA8": "Тамно љубичаста",
    "#303F9F": "Индиго Блуе",
    "#1976D2": "Плави",
    "#0288D1": "Светло плава",
    "#0097A7": "Тиркизно плава",
    "#00796B": "Гоосе Греен",
    "#388E3C": "Зелена",
    "#689F38": "Светло зелена",
    "#AFB42B": "Лимузина",
    "#FBC02D": "Жута",
    "#FFA000": "Амбер",
    "#F57C00": "Оранге",
    "#E64A19": "Схини Оранге",
    "#5D4037": "Браон",
    "#616161": "Греи",
    "#455A64": "Греи Блуе",
    "#FFD700": "Златан",
    "#C0C0C0": "Сребро",
    "#b76e79": "Златна ружа",
    "#383838": "Мат црна",
    "#FFFFFF": "бео",
    "#FFF": "бео",
    "#000000": "Црн",
    "#000": "Црн"
  },
  "address_info": {
    "name": "Име",
    "tel": "Телефон",
    "email": "Емаил",
    "country": "Држава",
    "city": "Град",
    "state": "Стање",
    "address": "адреса",
    "building_number": "Број зграде",
    "building_unit": "Јединица",
    "postcode": "Поштански број",
    "note": "Белешка"
  },
  "product_types": {
    "physical": "Физички",
    "physical_description": "Физички производи као што су: мобилни телефони, књиге, електронске компоненте.",
    "virtual": "Виртуелно",
    "virtual_description": "Производи прилагођени Интернету као што су: картица за допуну, резервација хотела, допуна игара.",
    "file": "Филе",
    "file_description": "Све дозвољене датотеке попут видео записа о курсу на мрежи, докумената за преузимање.",
    "service": "Услуга",
    "service_description": "Услуге као што су: поправка, превоз, подучавање."
  },
  "license": {
    "free": "бесплатно",
    "startup": "Покренути",
    "company": "Компанија",
    "enterprise": "Ентерприсе"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "Човеку",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW"
  },
  "variants": {
    "color": "Боја",
    "volume": "Величина",
    "count_in_pack": "Броји у паковању",
    "weight": "Тежина",
    "type": "Материјал",
    "style": "Стил"
  },
  "delivery_state": {
    "check_queue": "Чека се преглед",
    "order_confirm": "Потврда поруџбине",
    "preparing_order": "Припрема",
    "sent_order": "При достави",
    "to_customer": "Испоручена"
  },
  "status": {
    "unpaid": "Неплаћено",
    "paid": "Плаћено",
    "canceled": "Отказано",
    "completed": "Решено",
    "reserved": "Резервисано",
    "COD": "COD",
    "sold": "Продато",
    "open": "Отвори",
    "cancel": "Отказано",
    "active": "Ацтиве",
    "inactive": "неактиван",
    "debug": "Отклањање грешака",
    "live": "Уживо",
    "test": "Тест",
    "connected": "Повезан",
    "disconnected": "Дисцоннецтед",
    "accept": "Прихвати",
    "reject": "Одбити",
    "pending": "нерешен",
    "rejected": "Одбијен",
    "accepted": "Прихваћено"
  },
  "dimensions": {
    "cm": "центиметар",
    "km": "км",
    "kg": "кг"
  },
  "transportation_type": {
    "motorbike": "Моторбике",
    "motorbike_description": "Средња тежина у року од неколико километара.",
    "cargo_small": "Мали терет",
    "cargo_small_description": "Вишекилометарски лаки терет.",
    "cargo": "терет",
    "cargo_description": "Средња тежина у року од неколико километара.",
    "truck": "Камион",
    "truck_description": "Расути или тешки терет унутар земље.",
    "fast_post": "Фаст Пост",
    "fast_post_description": "Брзо слање путем поште.",
    "post": "Нормалан пост",
    "post_description": "Редовна пошта преко поште.",
    "airplane": "Ваздушна пошта",
    "airplane_description": "Домаћи и страни лаки и средњи терети.",
    "bicycle": "Цлеан Сенд",
    "bicycle_description": "Лаки терет, у кругу од неколико стотина метара од немоторних возила.",
    "global": "Глобални транспорт",
    "global_description": "Достава у иностранство ваздухом, морем или копном.",
    "pickup": "Покупи",
    "pickup_description": "Купци преузимају артикле у вашој физичкој продавници или складишту."
  },
  "article": {
    "login_to_see_error": "Пријавите се да бисте приступили чланку",
    "create_new_action": "Креирајте нови садржај",
    "menu_title": "Мени",
    "menu": {
      "edit": "Мод едитовања",
      "view_mode": "Режим прегледа",
      "delete": "Избриши чланак"
    },
    "schedule_action": "Да ли желите да закажете објављивање?",
    "schedule_title": "Закажите аутоматско објављивање",
    "edit_mode": "Уредити",
    "public_view_mode": "Јавни поглед",
    "publish_at": "Објавите на",
    "published": "Објављено",
    "draft": "Нацрт",
    "saving": "Уштеда",
    "save_and_publish_action": "Сачувај и објави",
    "save_draft_action": "Сачувај нацрт",
    "private": "Приватни",
    "public": "Јавно",
    "category_input": "Категорија",
    "category_input_message": "Изаберите категорију чланка",
    "parent_input": "Родитељ Категорија",
    "parent_input_message": "Изаберите садржај оца",
    "schedule_input": "Распоред",
    "schedule_input_placeholder": "Ако желите да прича буде објављена у одређено време.",
    "schedule_view_action": "Погледајте распоред објављивања",
    "author_title": "Написао",
    "read_time": "Време за учење",
    "read_time_unit": "Минута",
    "claps_action": "Цлапс",
    "claps": "Цлапс",
    "likes": "Као",
    "about_author": "О аутору",
    "updated_at": "Ажуриран",
    "wrote_at": "Вриттен ат",
    "now": "Сада",
    "follow_action": "Пратити",
    "followed": "Затим",
    "report_and_delete_action": "Пријавите и избришите овај чланак",
    "report_action": "Пријави злоупотребу",
    "you_reported_this_article": "Овај чланак већ има пријаву злоупотребе.",
    "add_to_publication_action": "Додај у публикацију",
    "author_socials": "Аутор на друштвеним мрежама",
    "share": "Објави",
    "report_dialog": {
      "report_and_delete_title": "Пријавите злоупотребу и уклоните садржај",
      "report_title": "Пријавите овај садржај као увредљив",
      "message": "Који је разлог за подношење овог садржаја? Изаберите једну од следећих опција.",
      "accept_and_delete_action": "Потврдите и избришите садржај"
    },
    "schedule_dialog": {
      "title": "Распоред објављивања садржаја",
      "publish_at": "Објавите на",
      "last_edit": "Последња измена",
      "view_action": "Погледај чланак"
    },
    "notifications": {
      "update_success_title": "Пошаљите информације",
      "update_success": "Чланак је успешно ажуриран.",
      "update_error": "Унети подаци нису валидни.",
      "delete_error": "Не можете избрисати овај чланак!",
      "report_and_delete_success_title": "Пријави и избриши",
      "report_and_delete_success_message": "Чланак је успешно обрисан.",
      "report_success_title": "Пријавите чланак",
      "report_success_message": "Ваш извештај о овом чланку је објављен."
    },
    "alert": {
      "delete_article": {
        "title": "Избриши чланак",
        "message": "Да ли сте сигурни да желите да трајно избришете овај чланак?",
        "action": "Избриши"
      }
    },
    "edit_window": {
      "title": "Изаберите Текст слике и резиме",
      "digest": "Резиме"
    },
    "editor": {
      "title_placeholder": "Наслов..",
      "body_placeholder": "Пишите одличан садржај..",
      "accept_file_types_error": "Овај формат датотеке је неприхватљив:",
      "max_file_size_error": "Ова датотека је превелика:",
      "notifications": {
        "image_uploaded_success": "Слика је успешно сачувана",
        "image_uploaded_failed": "Грешка при учитавању слике."
      },
      "embed_placeholder": "Унесите ифраме код, Фацебоок, Иоутубе или било који други УРЛ и притисните ентер.",
      "embed_caption_placeholder": "Унесите наслов (опционо)",
      "images_caption_placeholder": "Унесите наслов за ову слику .."
    }
  },
  "article_report": {
    "inappropriate": "Садржај овог чланка је неприкладан.",
    "fake": "Ово је лажно и варљиво.",
    "spam": "Ова ставка је послата нежељеном поштом и копирана.",
    "scam": "Може се очекивати да ће ово изазвати малвер, вирусе или пад система.",
    "hacked": "Изгледа да је овај сајт хакован.",
    "offensive": "Језички садржај и речник су неетички и непоштовани.",
    "violent": "Мислим да овај садржај садржи порнографију и да је у супротности са законима.",
    "harassment": "Мислим да је ово расистички.",
    "hate": "Мислим да се овде ради о промовисању насиља.",
    "infringe": "Ово крши моја права."
  },
  "comments": {
    "new_action": "Кликните да оставите коментар..",
    "title": "Коментари",
    "body_placeholder": "Ваш коментар или порука",
    "send_action": "Пошаљите коментар",
    "body_is_empty_error": "Коментар је празан!",
    "comments": "Коментари",
    "no_comments": "Напишите први коментар...",
    "load_more_action": "Добијте више коментара..",
    "cant_send_comment": "Не можете додати нови пост.",
    "cant_remove_this_comment": "Не можете избрисати овај коментар!",
    "product_buyer": "Купац",
    "delete_alert": {
      "title": "Обриши коментар",
      "message": "Да ли желите да избришете овај коментар?",
      "action": "Избриши"
    },
    "notifications": {
      "delete_success": "Ваш коментар је успешно избрисан."
    },
    "first_send": "Први пост",
    "comment_at": "на",
    "edit_comment": "Уреди коментар"
  },
  "customer_club": {
    "bronze": "Бронза",
    "silver": "Сребро",
    "gold": "Златан",
    "platinum": "Платинум",
    "diamond": "Диамонд"
  },
  "application_categories": {
    "tracking": "Провера понашања корисника",
    "payment": "Плаћање",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "Транспорт",
    "automation": "Аутоматизација",
    "inventory": "Складиштење",
    "accounting": "Рачуноводство",
    "marketing": "Маркетинг",
    "advertising": "Оглашавање",
    "staff": "Особље",
    "incentive": "Подстицаји",
    "shop": "Схоп"
  },
  "social_network": {
    "instagram": "инстаграм",
    "telegram": "Телеграм",
    "googleplay": "ГооглеПлаи",
    "appstore": "Продавница апликација",
    "twitter": "Твиттер",
    "linkedin": "Линкедин",
    "medium": "Средње",
    "selldone": "Селлдоне",
    "facebook": "Фејсбук",
    "pinterest": "Пинтерест",
    "whatsapp": "ВхатсАпп",
    "skype": "Скипе",
    "facebook_messenger": "Фацебоок Мессенгер"
  },
  "form_builder": {
    "add_item_action": "Додај нову ставку",
    "title_input": "Наслов",
    "name_input": "Име променљиве",
    "value_input": "Вредности",
    "value_input_message": "Листа корисничких опција",
    "default": "Задана вриједност",
    "types": {
      "simple": "Симпле",
      "selective": "Селективно",
      "switch": "Свитцх"
    }
  },
  "virtual_order_info_summery": {
    "title": "Назив производа",
    "reserved_at": "Датум регистрације",
    "total_price": "Укупан износ",
    "discount": "Попуст",
    "final_price": "Коначан износ",
    "payment_status": "Статус плаћање",
    "payment_status_waiting": "чекање исплате новца",
    "payment_status_paid": "Плаћено",
    "buyer": "Купац"
  },
  "virtual_item_info": {
    "title": "Виртуелна ставка",
    "outputs": {
      "title": "Излазне информације",
      "sub_title": "Поверљиве информације ове ставке",
      "message": "Ове информације ће бити приказане кориснику након куповине производа."
    },
    "inputs": {
      "title": "Потребне информације",
      "sub_title": "Потребне су информације о купцу",
      "message": "Купац мора да унесе тражене податке у формулар"
    },
    "notifications": {
      "inputs_set_success": "Образац за информације је успешно регистрован.",
      "confirm_by_admin_success": "Потврђен завршетак поруџбине.",
      "confirm_by_buyer_success": "Потврђен завршетак поруџбине."
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "Ова поруџбина се не може прихватити плаћањем ЦОД-а.",
    "payment_returned": "Уплата од стране купца се враћа.",
    "payment_fraud": "Плаћање је идентификовано као превара.",
    "location_out_of_service": "Локација корисника није у функцији.",
    "user_not_responding": "Клијент није одговарао на позиве.",
    "shop_owner_fault": "Дошло је до грешке од стране особља продавнице приликом попуњавања информација.",
    "lack_of_inventory": "Нема на залихи.",
    "legal_restriction": "Није могуће наручити због законских ограничења.",
    "pricing_fault": "Грешка у цени од стране продавца.",
    "system_fault": "Системска грешка."
  },
  "basket_order_info_summery": {
    "receiver": "Пријемник",
    "phone": "Тел",
    "reserved_date": "Датум куповине",
    "total_price": "Укупан износ",
    "discount": "Попуст",
    "final_price": "Коначан износ",
    "address": "Адреса испоруке",
    "payment_status": "Статус плаћање"
  },
  "basket_status": {
    "open": "Отвори",
    "reserved": "Резервисано",
    "paid": "Плаћено",
    "canceled": "Отказано",
    "cod": "Плаћање приликом испоруке",
    "receipt_added": "Признаница је додата",
    "payment_processing": "Обрада плаћања"
  },
  "basket_delivery_state": {
    "rejected": "Одбијен",
    "reject_reason_not_found": "Разлог је непознат.",
    "step_1": "Преглед",
    "step_2": "Потврда",
    "step_3": "Припрема",
    "step_4": "При достави",
    "step_5": "Испоручена"
  },
  "basket_return_request_view": {
    "title": "Ретурн Рекуест",
    "delivery_date": "Датум испоруке",
    "return_date": "Упит Датум",
    "items_count": "Број враћених артикала",
    "items_count_unit": "ставка(е)",
    "reason": "Разлог",
    "description": "Опис",
    "status": "Статус",
    "download_image": "Преузмите слику",
    "download_film": "Преузмите видео",
    "download_voice": "Преузмите глас",
    "accept_by_admin_action": "Прихвати захтев",
    "reject_by_admin_action": "Одбијте захтев",
    "message_for_admin": "У складу са уговором који сте прихватили коришћењем Селлдоне-а, морате контактирати купца и обавестити га/ју о процесу враћања његове/њене наруџбине. Ово се мора урадити ако се захтев прихвати или одбије и добије потпуну сагласност купца.",
    "notifications": {
      "update_status_success": "Статус захтева је ажуриран."
    }
  },
  "basket_list": {
    "return_count": "Повратак: {count} број",
    "table": {
      "row": "Ред",
      "image": "Слика",
      "product_name": "Производ",
      "variant": "Варијанта",
      "warranty": "Гаранције",
      "count": "Цоунт",
      "price": "Цена"
    }
  },
  "return_request_list": {
    "count": "Референтни број",
    "return_warranty": "Гаранција поврата новца",
    "return_warranty_unit": "дан(и)",
    "table": {
      "code": "Шифра налога",
      "product": "Производ",
      "delivery_at": "Датум пријема",
      "state": "Статус",
      "reason": "Разлог",
      "return_warranty_period": "Гарантни рок"
    }
  },
  "data_toolbar": {
    "search": "Претрага",
    "sort_by": "Сортирај по",
    "count_item": "Прикажи {item} ставки"
  },
  "sort": {
    "created_at": "Датум креирања",
    "updated_at": "Уреди датум",
    "title": "Наслов",
    "description": "Опис",
    "like": "Популарност",
    "power": "Цлапс",
    "product_type": "Врста производа",
    "discount": "Попуст",
    "rate": "Оцена",
    "rate_count": "Број оцена",
    "category": "Категорија",
    "product": "Производ",
    "body": "Садржај",
    "card_type": "Тип картице",
    "card_number": "Број картице",
    "balance": "Баланс",
    "paid": "Потрошени износ",
    "currency": "Валута",
    "expire_at": "Датум истека",
    "discount_code": "Код за попуст",
    "discount_percent": "Попуст",
    "discount_limit": "Ограничење попуста",
    "max_count": "Максимални број",
    "used_count": "Користи се",
    "start_date": "Датум почетка",
    "end_date": "Крајњи датум",
    "total_discount_amount": "Тотални попусти",
    "initial_charge": "Почетно пуњење",
    "total_count": "Укупан број",
    "amount_paid": "Износ плаћен",
    "name": "Име",
    "published": "Објављено",
    "visits": "Посете",
    "color": "Боја",
    "landing_page": "Почетне странице",
    "enable": "Омогући",
    "fix_commission": "Фиксна провизија",
    "percent_commission": "Проценат провизије",
    "payment_at": "Датум исплате",
    "issued_at": "Датум издавања",
    "payment": "Плаћање",
    "website": "Веб сајт",
    "email": "Емаил",
    "user": "корисник",
    "code": "Код",
    "schedule_at": "Датум распореда",
    "sender": "Сендер",
    "in_que": "У реду",
    "sent": "Послано",
    "shop": "Схоп",
    "quantity": "Количина",
    "amount": "Износ",
    "jobs": "Послови се рачунају",
    "success": "Успех се рачуна",
    "fail": "Број неуспеха",
    "distance": "Удаљеност",
    "duration": "Трајање",
    "reset_at": "Ресетуј датум",
    "delivery_person": "Особа",
    "delivery_service": "Услуга",
    "date": "Датум",
    "order": "Ред",
    "order_id": "ИД поруџбине",
    "status": "Статус",
    "price": "Цена",
    "count": "Цоунт",
    "final_price": "Коначна цена",
    "charge": "Напунити",
    "mention": "Поменути",
    "officer": "официр",
    "registered": "Регистрован",
    "purchased": "Купио",
    "sex": "Пол"
  },
  "search_box": {
    "result": "Резултати претраге",
    "tips": "Претражите производе и категорије",
    "label": "Претрага ...",
    "category": "Категорија"
  },
  "lead_status": {
    "physical_fast_delivery": "Тренутна испорука",
    "physical_under_24h_delivery": "Испоручите у наредних {lead} сати",
    "physical_over_24h_delivery": "Припрема и слање од следећих {days} дана",
    "virtual_fast_prepare": "Тренутна испорука",
    "virtual_under_24h": "Биће обављено у наредних {lead} сати",
    "virtual_over_24h": "Биће урађено од наредних {days} дана"
  },
  "return_request_state": {
    "pending": "нерешен",
    "accepted": "Потврђено",
    "rejected": "Одбијен"
  },
  "return_order_reason": {
    "physical": {
      "U1": "Неусклађеност производа",
      "U2": "Нема производа у пакету за отпрему",
      "U3": "Ломљење пакета или производа",
      "U4": "Мењање пакета или серијског броја",
      "U5": "Неки предмети из пакета недостају",
      "U6": "Производ није оригиналан",
      "U7": "Производ не задовољава спецификације"
    }
  },
  "image_uploader": {
    "label": "Превуците и отпустите или <u>изаберите датотеку</u>",
    "max_size": "Максимална дозвољена величина: {size}"
  },
  "timespan": {
    "Morning": "8-12 часова",
    "Evening": "од 12 до 18 часова",
    "Night": "18:00-12:00",
    "Instant": "Инстант Пост"
  },
  "week_day": {
    "Saturday": "субота",
    "Sunday": "недеља",
    "Monday": "Понедељак",
    "Tuesday": "уторак",
    "Wednesday": "Среда",
    "Thursday": "четвртак",
    "Friday": "петак"
  },
  "payment_form": {
    "title": "Изаберите Начин плаћања",
    "gift_cards_input": "Поклон картице",
    "gift_cards_input_empty": "Нису пронађене поклон картице..",
    "more": "Остало",
    "pay_amount_by_gift_cards": "Плаћање картицом",
    "select_payment_method": "Изаберите начин плаћања из следећих опција.",
    "payment_amount_remained": "Преостали износ уплате",
    "payment_amount": "Износ плаћен",
    "all_paid_by_gift_cards": "Честитамо, не морате да плаћате за ову наруџбу. Притисните тастер Плати са поклон картицом.",
    "pay_by_gift_cards_action": "Платите поруџбину платном картицом",
    "order_free_payment": "Честитамо, ваша поруџбина је бесплатна!",
    "order_free_payment_action": "Наручите бесплатно одмах",
    "qr": {
      "address": "Плаћање Адреса",
      "amount": "Износ"
    }
  },
  "discount_input": {
    "limit": "{percent}% попуста до {limit} {currency}",
    "action": "Додајте код за попуст",
    "code_input": "Код за попуст",
    "notifications": {
      "add_success": "Честитамо, важећи код за попуст."
    }
  },
  "gift_card": {
    "inactive": "Картица је онемогућена",
    "expire": "Екпири",
    "transfer": "Трансфер",
    "send_to_friend": "Послати пријатељу"
  },
  "count_down": {
    "days": "Дан",
    "hours": "Сат",
    "minutes": "Минута",
    "seconds": "Секунде"
  },
  "gift_status": {
    "Unpaid": "Очекујем Пријем",
    "Paid": "Плаћено",
    "Rejected": "Одбијен",
    "Canceled": "Отказано"
  },
  "gift_program_status": {
    "Airdrop": "Систем плаћања",
    "Advertising": "Оглашавање",
    "PersonalGift": "Персонал Гифт",
    "ShopGift": "Продавница сувенира"
  },
  "currency_selector": {
    "label": "Валута"
  },
  "need_login": {
    "title": "Пријавите се",
    "login_sms": "СМС пријава",
    "login_google": "Пријавите се помоћу Гоогле-а",
    "login_facebook": "Пријавите се са Фејсбуком",
    "login_account": "Логин би Селлдоне",
    "register": "Нови корисник? Региструј се сада.",
    "mobile_input": "Унесите свој мобилни",
    "verification_code": "Верификациони код",
    "msg_title": "Здраво,",
    "msg_body": "Молим вас пријавите се. Потребно је само неколико секунди."
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "Продавница злата 5 година"
    },
    "GOLDEN_2YEAR": {
      "name": "Продавница злата 4 године"
    },
    "GOLDEN_3YEAR": {
      "name": "Продавница злата 3 године"
    },
    "GOLDEN_4YEAR": {
      "name": "2 Иеар Голд Сторе"
    },
    "GOLDEN_5YEAR": {
      "name": "Продавница злата за 1 годину"
    },
    "TOKEN_OWNER_1M": {
      "name": "Златни инвеститор"
    },
    "TOKEN_OWNER_10M": {
      "name": "Диамонд Инвестор"
    },
    "TOKEN_OWNER_100M": {
      "name": "Руби Инвестор"
    },
    "COMMUNITY_LOYAL": {
      "name": "Члан супериорне заједнице комуникационих мрежа"
    },
    "GOLD_SUPPLIER": {
      "name": "Голд Супплиер"
    },
    "GOLD_SELLER": {
      "name": "Голд Деалер"
    },
    "CONTENT_SUPERMAN": {
      "name": "Најбољи произвођач садржаја"
    },
    "NINJA": {
      "name": "Нинџа"
    },
    "STAR": {
      "name": "Звезда"
    },
    "GUARDIAN": {
      "name": "Одлична корисничка служба"
    },
    "KING": {
      "name": "Краљ тржишта"
    }
  },
  "cookie": {
    "title": "Ова веб локација користи колачиће",
    "message": "Ова веб локација користи колачиће за побољшање корисничког искуства. Коришћењем наше веб странице пристајете на све колачиће у складу са нашом Политиком о колачићима.",
    "preferences_action": "Манаге Преференцес",
    "agree_action": "Слажем се"
  },
  "basket_item_message": {
    "title": "Потребне информације за ову ставку",
    "save_actions": "Сачувај поруку",
    "notifications": {
      "success": "Ваши улазни подаци су сачувани."
    }
  },
  "faq": {
    "faq": "Често постављана питања",
    "title": "Питања и одговори",
    "sub_title": "Оно што сте тражили од нас.",
    "message": "Потражите одговор на своје питање међу одговорима у наставку. Питајте нас ако питања остају без одговора.",
    "add_question_action": "Поставите ново питање",
    "read_more": "Опширније ..",
    "load_more": "Више питања ..",
    "main_page": "ФАК Главна страница",
    "add_new": "Пошаљите ново питање",
    "login_alert": "Пријавите се да бисте поставили питање.",
    "question_input": "Питање",
    "question_input_placeholder": "Поставите своје питање.",
    "notifications": {
      "success_add": "Ваше питање је успешно послато."
    }
  },
  "rating_labels": [
    "Врло лоше",
    "Лоше",
    "Нормално",
    "Добро",
    "Одлично"
  ],
  "map_view": {
    "address_detail": "Детаљи о адреси",
    "change": "Промена",
    "select": "Изаберите",
    "not_found_address": "Није пронађена вредност",
    "enter_address_hint": "Унесите одредишну адресу",
    "enter_your_address": "Унесите своју адресу.",
    "postal_code": "Поштански број",
    "phone_input": "Телефон {type}",
    "building_number": "Број зграде",
    "building_unit": "Јединица",
    "full_name_input": "Пуно име {type}",
    "save_detail_action": "Сачувајте детаље",
    "more_detail_input": "Више описа",
    "add_address_to_list": "Додајте адресу на листу",
    "address_title_input": "Ознака адресе (захтева)",
    "notifications": {
      "save_in_list": "Ова адреса је сачувана на вашој листи са свим детаљима.",
      "edit_success": "Нове вредности адресе су сачуване у {title}."
    },
    "delete_address_dialog": {
      "title": "Избриши адресу",
      "message": "Да ли сте сигурни да желите да избришете ову адресу?",
      "action": "Уклони адресу"
    }
  },
  "comment_manager": {
    "can_not_edit": "Није могуће изменити овај коментар!",
    "comment_input_empty": "Текст поруке је празан!",
    "article_not_saved": "Сачувајте чланак!"
  },
  "wheel_fortune": {
    "title": "Играј и победи",
    "message": "Цена сваке игре је 10 жетона. Тренутно имате {chips} чип. Купите више чипова у продавници.",
    "win_message": "Честитамо, победили сте!",
    "lost_message": "Извините, изгубили сте игру.",
    "try_again": "Можете покушати поново"
  },
  "json": {
    "add": "Додајте податке о структури",
    "add_message": "Креирајте нове податке о структури",
    "structures": "Структуре",
    "book": {
      "title": "Боок",
      "desc": "Радње књига које омогућавају корисницима да купе књигу коју пронађу директно из резултата претраге."
    },
    "occupation": {
      "title": "Процењена плата",
      "desc": "Информације о процени плата, као што су распони плата и просеци плата на основу региона за типове послова, приказане у искуству претраживања посла на Гоогле-у."
    },
    "course": {
      "title": "Наравно",
      "desc": "Образовни курсеви који се појављују на листи специфичних за провајдера. Курсеви могу да садрже назив курса, провајдера и кратак опис."
    },
    "howto": {
      "title": "Како да",
      "desc": "Упутство води кориснике кроз низ корака да успешно заврше задатак, укључујући видео, слике и текст."
    },
    "recipe": {
      "title": "Рецепт",
      "desc": "Рецепти који се приказују као појединачни богати резултат или део вртешке домаћина."
    }
  },
  "support": {
    "Financial": "Финансијски",
    "Technical": "Технички",
    "Advisor": "саветник"
  },
  "condition": {
    "new": "Нова",
    "refurbished": "Реновиран",
    "used": "Користи се",
    "used_fair": "Коришћен сајам",
    "used_good": "Коришћено добро",
    "used_like_new": "Коришћено - као ново"
  },
  "variant_filter": {
    "title": "Филтер варијанте производа",
    "only_available": "На лагеру"
  },
  "service": {
    "task": {
      "title": "Задаци",
      "message": "Списак послова који се обављају у овој служби."
    },
    "appointment": {
      "title": "Именовање",
      "message": "Изаберите доба недеље од следећих на основу дана и сата који вам одговарају."
    },
    "booking": {
      "title": "Резервација",
      "message": "Наведите временски период у данима када желите да извршите резервацију у календару испод."
    },
    "subscription": {
      "title": "Претплата"
    },
    "charge": {
      "title": "Напунити"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "Фиксне цене",
      "message": "У овој врсти цене, цена производа је фиксни износ и нема потребе да купац захтева калкулацију цене."
    },
    "ESTIMATION": {
      "title": "Процена цена",
      "message": "Цену производа и услуга ће донекле обрачунати продавац приликом поруџбине, рачуни за плаћање се могу мењати или додавати током услуге."
    },
    "AGREEMENT": {
      "title": "Уговорене цене",
      "message": "Коначну цену производа или услуга продавац неће мењати након што је поруџбина послата."
    },
    "BID": {
      "title": "Понуда / аукција",
      "message": "Производ ће потенцијални купци продавати по највишој понуђеној цени."
    }
  },
  "map": {
    "title": "Одредиште за пријем производа",
    "confirm": "Подесите локацију",
    "address": "Одредиште",
    "receptor": "Пријемник"
  },
  "ShopBots": {
    "telegram": "Телеграм"
  },
  "article_tags": {
    "title": "Ознаке садржаја",
    "tags_input": "Ознаке",
    "tags_input_message": "Ознаке Листа овог чланка",
    "notification": {
      "add_success": "Ознаке су додате"
    }
  }
};