import colors from "./colors/en";

export default {
  //--------- Default Values ---------
  currency_default: "USD",
  language_default: "sv",
  //----------------------------------

  store: "Lagra",

  not_exist: "Finns inte",
  error: "fel",
  active: "Aktiva",
  inactive: "Inaktiv",
  required_value: "Obligatoriska värden",

  original_warranty: "Guarantee of originality of goods",
  return_warranty_days: "{days} dag för returgaranti",
  no_return_warranty: "Ingen returgaranti",

  reed_agree_terms:
    "Jag har läst användarvillkoren och integritetspolicyn och godkänner dem.",

  // Common:
  commons: {
    Currency: "Valuta",
    COD: "COD",
    State: "stat",
    Price: "Pris",
    order_price: "Beställningspris",
    VAT: "VAT",
    Discount: "Rabatt",
    In_Stock: "I lager",
    Variants: "Varianter",
    No_variants: "Inga varianter",
    all: "Allt",
    today: "I dag",
    yesterday: "I går",
    license: "Licens",
    home: "Hem",
    support: "Stöd",
    messages: "Meddelanden",
    no_message: "Inget meddelande",
    empty: "Tömma",
    phone: "Telefon",
    address: "Adress",
    name: "namn",
    password: "Lösenord",
    email: "E-post",
    mobile: "Mobil",
    login: "Logga in",
    register: "Registrera",
    select_account: "Välj konto",
    online: "Uppkopplad",
    offline: "Off-line",
    finish: "Avsluta",
    finished: "Färdiga",
    preview: "Förhandsvisning",
    free: "Fri",
    free_completely: "Helt gratis abonnemang",
    fee: "Avgift",
    month: "Månad",
    faq: "Vanliga frågor",
    question: "Fråga",
    answer: "Svar",

    create_date: "Skapa datum",
    update_date: "Uppdatera datum",
    start_date: "Start datum",
    end_date: "Slutdatum",
    social: "Social",
    total: "Total",
    orders: "Order",
    sessions: "Sessioner",
    product_views: "Produktvyer",
    add_to_carts: "Lägg till i kundvagnar",
    checkouts: "Kassor",
    payments: "Betalningar",
    organic_search: "Organisk sökning",
    other: "Övrig",

    landing_page: "Landningssida",
    discount_code: "Rabattkod",
    total_sell: "Total rea",
    details: "Detaljer",
    currency: "Valuta",
    amount: "Belopp",

    published: "Publicerad",
    draft: "Förslag",

    save_changes: "Spara ändringar",

    source: "Källa",
    medium: "Medium",
    url: "URL",
    revenue: "Inkomst",
    performance: "Prestanda",
    term: "Termin",
    content: "Innehåll",

    session: "Session",
    product: "Produkt",
    add: "Lägg till",
    checkout: "Kolla upp",
    payment: "Betalning",

    more_options: "Fler alternativ",

    full_name: "Fullständiga namn",
    tel: "Tel",
    about_me: "Om mig",
    request_checking: "Begär kontroll",
    passport: "Passera",
    birthday: "Födelsedag",
    country: "Landa",
    city: "Stad",

    gender: "Kön",

    offer: "Erbjudande",

    website: "Hemsida",

    apply_for_all_products: "Ansök om alla produkter",

    fix_commission: "Fixa provision",
    percent_commission: "Procent provision",

    fixed_discount: "Fast rabatt",
    discount_percentage: "Procent rabatt",
    discount_limit: "Rabattgräns",
    no_code: "Ingen kod",
    max_count: "Max antal",
    count_unit: "föremål",
    used: "Begagnade",
    daily: "Dagligen",
    monthly: "En gång i månaden",
    yearly: "Årlig",
    state: "stat",
    disable: "Inaktivera",
    enable: "Gör det möjligt",
    activation_code: "Aktiveringskod",
    quantity: "Kvantitet",
    no_club: "Ingen klubb",
    per_order: "Per beställning",
    count: "Räkna",

    seconds: "Sekunder",
    auto: "Bil",

    title: "Titel",
    message: "Meddelande",
    width: "Bredd",
    length: "Längd",
    height: "Höjd",

    label: "Märka",
    click: "Klick",
    bank: "Bank",

    default: "Standard",
    role: "Rulla",
    user: "Användare",
    users: "Användare",
    code: "Koda",
    total_payment: "Total betalning",
    balance: "Balans",

    chance: "Chans",
    free_for_new_users: "Gratis för nya användare",
    prize_amount: "Prissumma",
    win: "Vinna",
    gift_card: "Present kort",
    discount: "Rabatt",
    config: "Konfig",
    prize: "Pris",
    Prizes: "Priser",
    result: "Resultat",

    price: "Pris",
    lottery: "Lotteri",
    coupon: "Kupong",
    customer_club: "Kundklubb",
    shipping: "Frakt",
    sum: "Belopp",
    not_payed: "Inte betalad",
    category: "Kategori",
    done: "Gjort",
    email_from: "Från",
    subject: "Ämne",
    schedule: "Schema",

    files_list: "Fillista",
    file_max_size: "Max filstorlek",
    value: "Värde",
    help: "Hjälp",

    shipping_tax: "Fraktskatt",
    net_price: "Nettopris",
    tax: "Beskatta",
    tax_included: "Ingår i priset",

    limit: "Begränsa",
    min_purchase: "Minsta köp",
    eligible_for: "Kvalificerad för",
    only_for_first_buy: "Endast vid första köp",
    one_time_use: "Kan användas en gång",
    period_of_qualify: "Kvalificeringstid",
    no_constraint: "Ingen begränsning",

    timespan: "Tidsrymd",
    days: "dag(ar)",
    weight: "Vikt",
    distance: "Distans",

    last_status: "Senaste status",
    issued_at: "Utfärdas på",
    order: "Beställa",
    order_detail: "Orderdetaljer",

    percent: "Procent",
    applied_count: "Tillämpad räkning",
    campaign: "Kampanj",
    os: "Operativ system",
    browser: "Webbläsare",
    device: "Enhet",
    device_ip: "Enhetens IP-adress",
    location: "Plats",
    user_agent: "Användaragent",
    affiliate: "Dotterbolag",
    timeline: "Tidslinje",
    add_note: "Lägg till anteckning",
    record: "Spela in",
    unlimited: "Obegränsat",
    show_coupons: "Visa kuponger",
    hide_coupons: "Göm kuponger",
    service_area: "Serviceområde",
    apps: "Appar",
    plugins: "Plugins",
    bots: "Bots",
    categories: "Kategorier",
    products: "Produkter",
    business: "Företag",
    personal: "Personlig",
    size: "Storlek",
    holiday: "Semester",
    sod: "Frakt vid leverans",
    cod: "Postförskott",
    free_shipping: "Gratis frakt",
    hours: "Timmar",
    send_date: "Skicka datum",
    deliver_date: "Leveransdatum",
    return_date: "Återlämningsdatum",
    pending: "I väntan på",
    delivered: "Levereras",
    returned: "Returnerad",
    canceled: "Inställt",
    shipping_cost: "Fraktkostnad",
    action: "Handling",
    cancel_date: "Avbryt datum",
    deliver_in_process: "Beställningen skickas..",
    kind: "Snäll",
    detail: "Detalj",
    map: "Karta",
    actions: "Handlingar",
    navigation: "Navigering",
    navigation_app: "Ansökan",
    payment_date: "Betalningsdatum",
    duration: "Varaktighet",
    bill: "Räkningen",
    delivery_persons: "Leverans personer",
    delivery_services: "Leveranstjänster",
    live_view: "Realtidsbild",
    cart: "Vagn",
    priority: "Prioritet",
    sufficient_credit: "Tillräcklig kredit",
    max_package_size: "Max paketstorlek",
    delay: "Dröjsmål",
    credit: "Kreditera",
    livemode: "leva",
    debug: "Felsökning",
    token: "Tecken",
    status: "Status",
    courier: "Kurir",
    track: "Spår",
    track_order: "Spårningsorder",
    cost: "Kosta",
    receipt: "Mottagande",
    origin: "Ursprung",
    destination: "Destination",
    sku: "SKU",
    mpn: "MPN",
    not_in_stock: "Inte tillräckligt med lager!",
    sub_total: "Subsumma",
    customer: "Kund",
    delivery: "Leverans",
    online_orders: "Onlinebeställningar",
    pos_orders: "POS order",
    chips: "Pommes frites",
    subscribed: "Prenumererade",
    unsubscribed: "Avslutad prenumeration",
    last_login: "Senaste inloggning",
    join_at: "Gå med datum",
    club: "Klubb",
    buyer: "Köpare",
    seller: "Säljare",
    or: "Eller",
    type: "Typ",
    condition: "Skick",
    brand: "varumärke",
    attempt: "Försök",
    error: "Fel",
    success: "Framgång",
    fail: "Misslyckas",
    inventory: "Lager",
    link: "Länk",
    visits: "Besök",
    transactions: "Transaktioner",
    vat: "vat",
    pos_vat: "POS moms",
    sort_by: "Sortera efter..",
    from: "Från",
    from_lead_time: "inom de närmaste {hours} timmarna",
    no_credit_card_info: "Ingen kortinformation!",

    active: "Aktiva",
    not_active: "Inte aktiverad!",
    referrals: "Remisser",
    dashboard: "instrumentbräda",
    more: "Mer",
    inactive: "Inaktiv",
    developer: "Utvecklare",
    setting: "Miljö",
    membership_conditions: "Medlemsvillkor",
    customers: "Kunder",
    created_at: "Skapat Datum",
    updated_at: "Senaste uppdateringen",
    register_at: "Registreringsdatum",
    old: "Gammal",
    new: "Ny",
    start: "Start",
    end: "Slutet",
    pos: "POS",
    out_of_stock: "Slut i lager",
    fake: "Falsk",
    low_inventory_warning: "OBS, lågt lager!",
    webhook: "Webhook",
    notification: "Underrättelse",
    sms: "SMS",
    online_payment_link: "Online betalning länk",
    waiting_load_data: "Väntar på att ladda data..",

    views: "Visningar",
    sales: "Försäljning",
    total_views: "Totalt antal visningar",
    total_sales: "Total rea",
    from_previous_n_days: "från föregående {days} dagar",
    drop_shipping: "Släpp frakt",
    commission: "Tillhandahållande",
    shipping_area: "Fraktområde",
    main_seller: "Huvudsäljare",
    domain: "Domän",
    contact: "Kontaktinformation",
    wallet: "Plånbok",
    reseller: "Återförsäljare",

    tracking_code: "Spårningskod",
    tracking_url: "Spårningsadress",
    fulfillments: "Uppfyllelser",
    reject: "Avvisa",
    reserved: "Reserverad",
    score: "Göra",
    customer_price: "Kundpris",

    options: "alternativ",
    show_details: "Visa detaljer",
    no_data: "Inga data..",
    waiting: "Väntar...",
    waiting_connecting_payment: "Väntar på betaltjänsten...",
    creating_secure_payment:'Skapa säker betalning.',

    officer: "Officer",

    ticket: "Biljett",
    ticket_url: "Biljett-url",
    closed_at: "Stängt kl",
    close_ticket: "Stäng biljett",
    reopen_ticket: "Öppna biljett igen",
    require: "Behöva*",
    search: "Sök...",
    language: "Språk",
    tasks: "Uppgifter",
    permissions: "Behörigheter",
    finish_date: "Slutdatum",
    complete_date: "Komplett datum",
    settle_date: "Avgör datum",
    cost_span: "Prisklass",
    industry: "Industri",
    rating: "Betyg",
    rates: "Priser",
    seen_at: "Ses på",
    completed: "Avslutad",
    you: "Du",
    shop: "affär",
    store: "Lagra",
    granted: "Beviljas",
    deny: "Förneka",
    request: "Begäran",
    expert: "Expert",
    response: "Svar",
    requests: "Förfrågningar",
    experts: "Förfrågningar",
    responses: "Svar",
    negotiations: "Förhandlingar",
    all_chats: "Alla chattar",
    chats: "Chattar",
    tags: "Taggar",
    description: "Beskrivning",
    rates_count: "Priserna räknas",
    rate: "Betygsätta",
    comment: "Betygsätta",
    chat: "Chatt",
    install: "Installera",
    edited: "Redigerat",
    undo: "Ångra",
    redo: "Göra om",
    male: "Manlig",
    female: "Kvinna",
    calculator: "Kalkylator",
    catalog: "Katalog",
    max_height: "Maximal höjd",
    images_compare: "Jämför bilder",
    canvas: "Duk",
    table_of_contents: "Innehållsförteckning",
    comments: "Kommentarer",
    badge_codes: "Märkens kod",
    need_more: "Behöver mer?",
    invite_glow_caption: "Få 14,9 $ för varje vän!",
    register_free: "100 % gratis registrering",
    gift: "Gåva",

    google: "Google",
    facebook: "Facebook",
    instagram: "Instagram",
    instashop: "Instashop",

    show: "Show",
    hide: "Dölj",
    waiting_review: "Väntar på granskning",
    not_selected: "Ej valt",
    time: "Tid",

    final_price: "Slutgiltigt pris",
    starting_price: "Startpris",

    day: "dag",
    payed: "Betalt",
    service_bill: "Faktura betalning",
    avocado: "Avokado",

    delivery_price: "Fraktkostnad",
    select_address: "Välj adress",
    image: "Bild",
    view: "Se",
    sell: "Sälja",

    hyper: "Hyper",
    cart_list: "Vagn",
    barcode_scanner: "Streckkodsläsare",
    scan_qr_code: "Skanna QR kod",

    new_carts: "Nya vagnar",
    pays: "Betalningar",
    annually: "Årligen",
    sells: "Säljer",
    articles: "Artiklar",
    jobs: "Jobb",
    job: "Jobb",
    blog: "Blogg",
    deleted_at: "Raderade kl",
    capacity: "Kapacitet",
    download_at: "Senaste nedladdningsdatum",
    downloads: "Nedladdningar",
    usage: "Användande",
    select_upload_file: "Välj eller släpp fil",
    download_link: "Nedladdningslänk",
    uploading: "Laddar upp..",
    files: "Filer",
    star: "Stjärna",
    speed: "Fart",
    feedback: "Respons",
    new_messages: "Nya meddelanden",
    file: "Fil",
    attachment: "Anknytning",
    gallery: "Galleri",
    sync: "Synkronisera",
    diff_time: "Tidsskillnad",
    network: "Nätverk",
    account: "konto",
    configuration: "Konfiguration",
    blockchain: "Blockchain",
    blog_link: "Blogglänk",
    community: "gemenskap",
    critical_zone: "Kritisk zon",
    statistics: "Statistik",
    access: "Tillgång",
    seo: "SEO",
    followers: "Följare",
    followings: "Följande",
    private: "Förhandsvisning",
    soon: "Snart",
    features: "Funktioner",
    bot: "Bot",
    sample: "Prov",
    how_it_work: "Hur fungerar det?",
    page: "Sida",
    congratulations: "Grattis",
    recommend: "Rekommendera",
    recommended: "Rekommenderad",
    recoms: "Rekommenderar",
    likes: "Gillar",
    clicks: "Klick",
    platform: "Plattform",
    cms: "CMS",
    cash: "Kontanter",
    dir_payment: "banköverföring",
    auto_complete: "Komplett bil",
    compare: "Jämföra",
    infinite: "Oändlig",
    tips:'Tips',
    technical:'Teknisk',
    finance:'Finansiera',
    your_phone_input:'Fyll i ett telefonnummer',
    income:'Inkomst',
    change:'Förändra',
    new_users:'Nya användare',
    success_orders:'Framgångsorder',
    direct:'Direkt',
    last_activity:'Sista aktiviteten',
    landing:'Landning',

  },

  dialogs: {
    delete: {
      title: "Radera",
      message: "Är du säker på att ta bort det här objektet?",
      action: "Ja, radera nu",
    },
  },

  actions: {
    add_to_cart: "Lägg till i kundvagn",
    cancel: "Avbryt",
    update: "Uppdatering",
    add: "Lägg till",
    delete: "Radera",
    new: "Ny",
    save_continue: "Spara och fortsätt",
    save: "Spara",
    save_changes: "Spara ändringar",
    continue: "Fortsätta",
    close: "Stänga",
    finish: "Avsluta",
    poll: "Opinionsundersökning",
    view: "Se",
    edit: "Redigera",
    next: "Nästa",
    previous: "Tidigare",
    create: "Skapa",
    set: "Uppsättning",
    find: "Hitta",
    accept: "Acceptera",
    reject: "Avvisa",
    back: "Tillbaka",
    pay: "Betala",
    pay_now: "Betala nu",
    print: "Skriva ut",
    return: "Lämna tillbaka",
    publish: "Publicera",
    confirm: "Bekräfta",
    copy: "Kopiera",
    submit: "Skicka in",
    send: "Skicka",
    yes: "Ja",
    no: "Nej",
    meh: "Hmm",
    clear: "Klar",
    dismiss: "Avfärda",
    search: "Sök",
    deselect_all: "Avmarkera alla",
    select_all: "Välj alla",
    refresh: "Uppdatera",
    verify: "Kontrollera",
    play: "Spela",
    open: "Öppen",
    calculate: "Beräkna",
    quick_buy: "Snabbköp",
    click_here: "Klicka här",
    schedule: "Schema",
    send_now: "Skicka nu",
    download: "Ladda ner",
    reset_default: "Återställ till standard",
    reset: "Återställa",
    check: "Kontrollera",
    cod_payment: "Postförskott",
    dir_payment: "Pengaöverföring",
    online_payment: "Online betalning",
    checkout: "Kolla upp",
    show_all: "Visa allt",
    login: "Logga in",
    logout: "Logga ut",
    more: "Mer..",
    collapse: "Kollaps",
    apply_change: "Applicera förändringar",
    apply: "Tillämpa",
    add_giftcard: "Lägg till presentkort",
    charge: "Avgift",
    send_invites: "Skicka inbjudningar",
    past: "Över",
    restore: "Återställ",
    cut: "Skära",
    get_sms_code: "Få autentiseringskod",
    register_no_mail: "Fortsätt utan e-post",
    no_mail_register_message:
      "Har du ingen e-postadress eller glömt ditt lösenord?",
    reset_by_mail: "Lösenordsåterställning via e-post",
    reset_by_sms: "Lösenordsåterställning via SMS",
    cash_payment: "Kontant betalning",
    show_chart: "Visa diagram",
    open_app: "Öppna appen",
    login_now: "Logga in nu",
    watch_video: "Kolla på video",
    check_now: "Kolla nu",
    remove_image: "Ta bort bild",
    view_website: "Öppen länk",
    explore: "Utforska {name}",
    go: "Gå",
    read_more: "Läs mer",
    start_now: "Börja nu",
    view_live:'Visa live',
  },

  errors: {
    gateway_blockchain_sync_error:
      "Systemet synkroniserar inte med blockkedjan. Det kommer inte att vara möjligt att skapa en ny transaktion förrän synkroniseringen av våra servrar är klar. Vi löser problemet.",
    gateway_network_error:
      "Betalningsgatewaytjänsten har stött på ett kommunikationsproblem.",
  },

  /** @see BuyerReceiverInfoView **/
  receiver_info: {
    map: {
      title: "Leveransadress",
      confirm: "Ange plats",
      address_type: "Destination",
      receptor_type: "Mottagare",
    },
    receiver_address: "Välj leveransadress",
    address: "Adress",
    postcode: "Postnummer",
    enter_value: "Fyll här",
    address_note: "Notera",
    tel: "Kontaktnummer",
  },

  weight: {
    kg: "kg",
  },
  length: {
    cm: "centimeter",
  },

  distance: {
    m: "meter",
    km: "Km",
  },
  time: {
    days: "dagar",
    hours: "Timmar",
    minutes: "Minuter",
    seconds: "Sekunder",
  },

  units: [
    "enhet",
    "Artikel",
    "varje",
    "uppsättning",
    "bit",

    "kilogram",
    "gram",
    "milligram",

    "meter",
    "millimeter",

    "kvadratmeter",
    "kvadratfot",

    "kubikmeter",
    "liter",
    "milliliter",

    "fötter",
    "liter",
    "tum",
    "ounces",
    "pund",
    "kvarts",
    "yards",
    "rum",
  ],

  region_types: {
    State: "stat",
    Territory: "Territorium",
    Province: "Provins",
  },

  transaction_status: {
    RequireAction: "Kräv åtgärd",
    Processing: "Bearbetning",
    Canceled: "Inställt",
    Succeeded: "Lyckades",
  },

  placeholders: {
    name: "Okänd kvinna",
    email: "din-mail@mail.com",
    phone: "+1 000 0000",
    language: "Välj språk..",
    friend_email: "Din väns e-post...",
    friend_name: "Din väns namn",
  },

  notification: {
    confirm: "Bekräfta",
    confirm_message: "Ändringarna har sparats.",
    error: "Fel",
    message: "Meddelande",
    caution: "Varning",
    warning: "Varning",
    award: "Grattis",

    error_message: "Tyvärr har ett fel inträffat.",
    congratulation: "Grattis",
    coming_soon: "Snart",
    on_fetching_data: "Tar emot information..",
    new_pwa_version:
      "Ny version tillgänglig nu. Vill du uppdatera applikationen?",
    over_license_limit: "Över licensgräns",
    update_license: "Uppdatera din licens",

    required: "Nödvändig",
    invalid_email: "Ogiltig e-postadress",
    invalid_domain: "Ogiltig domän",
    invalid_min_length: "Minsta längd måste vara {length}",
    invalid_min_array_length: "Välj åtminstone {length} objekt",

    invalid_max_chars: "Max {maxCount} tecken",
    invalid_url: "Ogiltig URL",
  },

  colors: colors,

  address_info: {
    name: "namn",
    tel: "Telefon",
    email: "E-post",
    country: "Land",
    city: "Stad",
    state: "stat",
    address: "Adress",
    building_number: "Husnummer",
    building_unit: "Enhet",
    postcode: "Postnummer",
    note: "Notera",
  },

  /** {@see ProductType} **/
  product_types: {
    physical: "Fysisk",
    physical_description:
      "Fysiska varor såsom: mobiltelefoner, böcker, elektroniska komponenter.",

    virtual: "Virtuell",
    virtual_description:
      "Internetvänliga produkter såsom: laddningskort, hotellbokning, spelladdning.",

    file: "Fil",
    file_description: "Alla tillåtna filer faller inom denna kategori.",

    service: "Service",
    service_description: "Tjänster som: reparation, transport, undervisning.",
  },

  license: {
    free: "Fri",
    startup: "Börja",
    company: "Företag",
    enterprise: "Företag",
  },

  /** @see Currency */

  currency: {
    IRR: "IRR",
    IRR_alt: "Toman",
    USD: "USD",
    BTC: "BTC",
    ETH: "ETH",
    NIOC: "NIOC",
    SEL: "SEL",
    EUR: "EUR",
    ADA: "ADA",
    GBP: "GBP",
    AED: "AED",
    AFN: "AFN",
    CAD: "CAD",
    TRY: "TRY",
    CNY: "CNY",
    RUB: "RUB",
    SAR: "SAR",
    LBP: "LBP",
    QAR: "QAR",
    EGP: "EGP",
    INR: "INR",
    DKK: "DKK",
    PKR: "PKR",
    ALL: "ALL",
    AMD: "AMD",
    ANG: "ANG",
    AOA: "AOA",
    ARS: "ARS",
    AUD: "AUD",
    AWG: "AWG",
    AZN: "AZN",
    BAM: "BAM",
    BBD: "BBD",
    BDT: "BDT",
    BGN: "BGN",
    BIF: "BIF",
    BMD: "BMD",
    BND: "BND",
    BOB: "BOB",
    BRL: "BRL",
    BSD: "BSD",
    BWP: "BWP",
    BYN: "BYN",
    BZD: "BZD",
    CDF: "CDF",
    CHF: "CHF",
    CLP: "CLP",
    COP: "COP",
    CRC: "CRC",
    CVE: "CVE",
    CZK: "CZK",
    DJF: "DJF",
    DOP: "DOP",
    DZD: "DZD",
    ETB: "ETB",
    FJD:'FJD',
    FKP:'FKP',
    GEL:'GEL',
    GIP:'GIP',
    GMD:'GMD',
    GNF:'GNF',
    GTQ:'GTQ',
    GYD:'GYD',
    HKD:'HKD',
    HNL:'HNL',
    HRK:'HRK',
    HTG:'HTG',
    HUF:'HUF',
    IDR:'IDR',
    ILS:'ILS',
    ISK:'ISK',
    JMD:'JMD',
    JPY:'JPY',
    KES:'KES',
    KGS:'KGS',
    KHR:'KHR',
    KMF:'KMF',
    KRW:'KRW',
    KYD:'KYD',
    KZT:'KZT',
    LAK:'LAK',
    LKR:'LKR',
    LRD:'LRD',
    LSL:'LSL',
    MAD:'MAD',
    MDL:'MDL',
    MGA:'MGA',
    MKD:'MKD',
    MMK:'MMK',
    MNT:'MNT',
    MOP:'MOP',
    MRO:'MRO',
    MUR:'MUR',
    MVR:'MVR',
    MWK:'MWK',
    MXN:'MXN',
    MYR:'MYR',
    MZN:'MZN',
    NAD:'NAD',
    NGN:'NGN',
    NIO:'NIO',
    NOK:'NOK',
    NPR:'NPR',
    NZD:'NZD',
    PAB:'PAB',
    PLN:'PLN',
    SGD:'SGD',
    SEK:'SEK',



  },

  variants: {
    color: "Färg",
    volume: "Storlek",
    count_in_pack: "Räkna i förpackning",
    weight: "Vikt",
    type: "Material",
    style: "Stil",
  },

  /** {@see PhysicalOrderStates} **/
  delivery_state: {
    check_queue: "Väntar på granskning",
    order_confirm: "Orderbekräftelse",
    preparing_order: "Förbereder",
    sent_order: "På beställning",
    to_customer: "Levereras",
  },

  status: {
    unpaid: "Obetald",
    paid: "betalas",
    canceled: "Inställt",
    completed: "Fast",
    reserved: "Reserverad",
    COD: "COD",
    sold: "såld",
    open: "Öppen",
    cancel: "Inställt",
    active: "Aktiva",
    inactive: "Inaktiv",
    debug: "Felsökning",
    live: "leva",
    test: "Testa",
    connected: "Ansluten",
    disconnected: "Osammanhängande",
    accept: "Acceptera",
    reject: "Avvisa",
    pending: "I väntan på",
    rejected: "avvisade",
    accepted: "Accepterad",
  },
  dimensions: {
    cm: "centimeter",
    km: "km",
    kg: "kg",
  },

  /** {@see ShopTransportations} **/
  transportation_type: {
    motorbike: "Motorcykel",
    motorbike_description: "Medellång frakt inom några kilometer.",
    cargo_small: "Liten last",
    cargo_small_description: "Flerkilometer lätt last.",
    cargo: "Frakt",
    cargo_description: "Medellång frakt inom några kilometer.",
    truck: "Lastbil",
    truck_description: "Bulk eller tung last inom landet.",
    fast_post: "Snabbt inlägg",
    fast_post_description: "Snabb postning via posten.",
    post: "Vanligt inlägg",
    post_description: "Vanlig post via posten.",
    airplane: "Flygpost",
    airplane_description: "Inrikes och utrikes lätt och medelstor last.",
    bicycle: "Ren skicka",
    bicycle_description:
      "Lätt last, inom några hundra meter från icke-motorfordon.",
    global: "Globala transporter",
    global_description: "Frakt utomlands med flyg, sjö eller land.",
    pickup: "Plocka upp",
    pickup_description:
      "Beställningar kommer av kunden i din butik eller ditt lager.",
  },

  /** {@see ArticleView} **/
  article: {
    login_to_see_error: "Logga in för att komma åt artikeln",
    create_new_action: "Skapa nytt innehåll",
    menu_title: "Meny",
    menu: {
      edit: "Redigeringsläge",
      view_mode: "Visningsläge",
      delete: "Ta bort artikel",
    },
    schedule_action: "Vill du publicera schemat?",
    schedule_title: "Schemalägg automatisk publicering",
    edit_mode: "Redigera",
    public_view_mode: "Offentlig syn",
    publish_at: "Publicera till",
    published: "Publicerad",
    draft: "Förslag",
    saving: "I förvar",
    save_and_publish_action: "Spara och publicera",
    save_draft_action: "Spara utkast",
    private: "Privat",
    public: "offentlig",
    category_input: "Kategori",
    category_input_message: "Välj artikelkategori",
    parent_input: "Fars berättelse",
    parent_input_message: "Välj pappainnehåll",
    schedule_input: "Schema",
    schedule_input_placeholder:
      "Om du vill att berättelsen ska publiceras vid en viss tidpunkt.",
    schedule_view_action: "Se releaseschema",

    author_title: "Postat av",
    read_time: "Studietid",
    read_time_unit: "minuter",
    claps_action: "Klappar",
    claps: "heja på",
    likes: "Tycka om",
    about_author: "Om författaren",
    updated_at: "Uppdaterad",
    wrote_at: "Skrev kl",
    now: "Nu",
    follow_action: "Följ",
    followed: "Följt",
    report_and_delete_action: "Rapportera och ta bort denna post",
    report_action: "Rapportera missbruk",
    you_reported_this_article: "Du har redan en rapport för denna artikel.",
    add_to_publication_action: "Lägg till i publikation",
    author_socials: "Författare på sociala nätverk",
    share: "Dela med sig",
    report_dialog: {
      report_and_delete_title: "Rapportera missbruk och ta bort innehåll",
      report_title: "Rapportera missbruk för detta innehåll",
      message:
        "Vad är anledningen till att skicka in detta innehåll? Välj ett av följande alternativ.",
      accept_and_delete_action: "Bekräfta och ta bort innehåll",
    },
    schedule_dialog: {
      title: "Schema för innehållssläpp",
      publish_at: "Publicera till",
      last_edit: "Senaste redigering",
      view_action: "Se artikel",
    },
    notifications: {
      update_success_title: "Skicka information",
      update_success: "Artikel uppdaterad framgångsrikt.",
      update_error: "Den angivna informationen är inte giltig.",
      delete_error: "Du kan inte ta bort den här artikeln!",
      report_and_delete_success_title: "Rapportera och ta bort",
      report_and_delete_success_message:
        "Artikeln har raderats.",
      report_success_title: "Rapportera artikel",
      report_success_message: "Din rapport om den här artikeln har publicerats.",
    },
    alert: {
      delete_article: {
        title: "Ta bort artikel",
        message: "Är du säker på att du vill ta bort den här artikeln permanent?",
        action: "Radera",
      },
    },

    /** {@see ArticleEdit} **/
    edit_window: {
      title: "Välj Bildtext och Abstrakt",
      digest: "Sammanfattning",
    },
    /** {@see EditorContainer} **/
    editor: {
      title_placeholder: "titel..",
      body_placeholder: "Skriv bra innehåll..",
      accept_file_types_error: "Det här filformatet är oacceptabelt:",
      max_file_size_error: "Den här filen är för stor:",
      notifications: {
        image_uploaded_success: "Bilden har sparats",
        image_uploaded_failed: "Det gick inte att läsa in bilden.",
      },
      embed_placeholder:
        "Ange iframe-koden, facebook, youtube eller någon annan URL och tryck på enter.",
      embed_caption_placeholder: "Ange en titel (valfritt)",
      images_caption_placeholder: "Ange en titel för denna bild ..",
    },
  }, // article

  /** {@see ArticleReport} **/
  article_report: {
    inappropriate: "Innehållet i denna artikel är inte lämpligt.",
    fake: "Detta är falskt och vilseledande.",
    spam: "Den här artikeln har spammats och kopierats.",
    scam: "Detta kan förväntas orsaka skadlig programvara, virus eller systemanvändare att krascha.",
    hacked: "Den här sajten ser ut som att den håller på att huggas",
    offensive:
      "Språkinnehållet och vokabulären är oetiskt och respektlöst.",
    violent:
      "Jag tror att detta innehåll innehåller pornografi och strider mot lagarna.",
    harassment: "Jag tycker att detta är rasistiskt.",
    hate: "Jag tror att det här handlar om att främja våld.",
    infringe: "Detta kränker mina rättigheter.",
  },

  /** {@see CommentsManager} **/
  comments: {
    new_action: "Klicka för att lämna en kommentar..",
    title: "Kommentarer",
    body_placeholder: "Din kommentar eller meddelande",
    send_action: "Skicka kommentar",
    body_is_empty_error: "Kommentaren är tom!",
    comments: "Kommentarer",
    no_comments: "Skriv första kommentaren...",
    load_more_action: "Få fler kommentarer..",
    cant_send_comment: "Du kan inte lägga upp nya inlägg.",
    cant_remove_this_comment: "Du kan inte ta bort den här kommentaren!",
    product_buyer: "Köpare",

    delete_alert: {
      title: "Ta bort kommentar",
      message: "Vill du ta bort den här kommentaren?",
      action: "Radera",
    },
    notifications: {
      delete_success: "Din kommentar har raderats",
    },
    first_send: "Första inlägg",
    comment_at: "På",
    edit_comment: "Redigera kommentar",
  },

  /** {@see CustomerClubLevels} **/
  customer_club: {
    bronze: "Brons",
    silver: "Silver",
    gold: "gyllene",
    platinum: "Platina",
    diamond: "Diamant",
  },
  /** {@see ApplicationCategories} **/
  application_categories: {
    tracking: "Kontrollera användarens beteende",
    payment: "Betalning",
    seo: "SEO",
    crm: "CRM",
    transportation: "Transport",
    automation: "Automatisering",
    inventory: "magasinering",
    accounting: "Bokföring",
    marketing: "Marknadsföring",
    advertising: "Reklam",
    staff: "Personal",
    incentive: "Incitament",
    shop: "affär",
  },
  /** {@see SocialNetwork} **/
  social_network: {
    instagram: "Instagram",
    telegram: "Telegram",
    googleplay: "GooglePlay",
    appstore: "AppStore",
    twitter: "Twitter",
    linkedin: "Linkedin",
    medium: "Medium",
    selldone: "Selldone",
    facebook: "Facebook",
    pinterest: "Pinterest",
    whatsapp: "WhatsApp",
    skype: "Skype",
    facebook_messenger: "Facebook Messenger",
  },

  /** {@see FormBuilder} **/
  form_builder: {
    add_item_action: "Lägg till nytt föremål",
    title_input: "titel",
    name_input: "Variabelnamn",
    value_input: "värden",
    value_input_message: "Lista över användaralternativ",
    default: "Standardvärde",

    types: {
      simple: "enkel",
      selective: "selektiv",
      switch: "Växla",
    },
  },

  /** {@see VirtualItemOrderInfoSummery} **/
  virtual_order_info_summery: {
    title: "produktnamn",
    reserved_at: "Registrerings datum",
    total_price: "Totala summan",
    discount: "Rabatt",
    final_price: "Slutbelopp",
    payment_status: "Betalningsstatus",
    payment_status_waiting: "Väntar på betalning",
    payment_status_payed: "Betalt",
    buyer: "Köpare",
  },

  /** {@see VirtualItemInfo} **/
  virtual_item_info: {
    title: "Virtuella föremål",
    outputs: {
      title: "Utdatainformation",
      sub_title: "Konfidentiell information om detta föremål",
      message:
        "Denna information kommer att visas för användaren efter att ha köpt produkten.",
    },

    inputs: {
      title: "Information krävs",
      sub_title: "Köparinformation krävs",
      message:
        "Köparen ska ange den begärda informationen i det begärda informationsformuläret",
    },

    notifications: {
      inputs_set_success: "Informationsformuläret har registrerats framgångsrikt.",
      confirm_by_admin_success: "Beställning genomförd bekräftad.",
      confirm_by_buyer_success: "Beställning genomförd bekräftad.",
    },
  },

  /** {@see BasketRejectReasons} **/
  order_reject_reasons: {
    cant_accept_cod:
      "Denna beställning kan inte accepteras av kundens betalning på plats.",
    payment_returned: "Det belopp som kunden har satt in återbetalas.",
    payment_fraud: "Betalning har identifierats som bedrägeri.",
    location_out_of_service: "Kundens plats är ur funktion.",
    user_not_responding: "Kunden kan inte svara på samtal.",
    shop_owner_fault:
      "Ett fel inträffade av butikspersonal när informationen angavs.",
    lack_of_inventory: "Slut i lager.",
    legal_restriction: "Det går inte att göra en beställning på grund av juridiska begränsningar.",
    pricing_fault: "Prissättningsfel av säljaren.",
    system_fault: "Systembugg.",
  },

  /** {@see BasketOrderInfoSummery} **/
  basket_order_info_summery: {
    receiver: "Mottagarens leverans",
    phone: "Nummer id",
    reserved_date: "Registrerings datum",
    total_price: "Totalbelopp",
    discount: "Rabatt",
    final_price: "Slutgiltigt pris",
    address: "Mottagarens leveransadress",
    payment_status: "Betalningsstatus",
  },

  /** {@see BasketStatus} **/
  basket_status: {
    open: "Öppen",
    reserved: "Reserverad",
    payed: "Betalt",
    canceled: "Inställt",
    cod: "Postförskott",
    receipt_added: "Kvitto tillagt",
    payment_processing: "Betalningen behandlas",
  },

  /** {@see BasketDeliveryState} **/
  basket_delivery_state: {
    rejected: "avvisade",
    reject_reason_not_found: "Orsaken är okänd.",
    step_1: "Väntar på granskning",
    step_2: "Orderbekräftelse",
    step_3: "Förberedelse",
    step_4: "Till leveransombud",
    step_5: "Leverans till kund",
  },
  /** {@see BasketReturnItemsRequestView} **/
  basket_return_request_view: {
    title: "Returförfrågan",
    delivery_date: "Leveransdatum",
    return_date: "Datum för begäran",
    items_count: "Returräkning",
    items_count_unit: "föremål",
    reason: "Anledning",
    description: "Beskrivning",
    status: "Status",
    download_image: "Ladda ner bild",
    download_film: "Ladda ner video",
    download_voice: "Ladda ner röst",
    accept_by_admin_action: "Acceptera förfrågan",
    reject_by_admin_action: "Avvisa begäran",
    message_for_admin:
      "Enligt avtalet som du har accepterat genom att använda Selldonet måste du kontakta köparen och hålla honom/henne informerad om processen för att returnera hans/hennes beställning. Detta bör göras om begäran accepteras eller avslås och köparens fulla samtycke erhålls.",
    notifications: {
      update_status_success: "Begärans status uppdaterad.",
    },
  },

  /** {@see ShopProcessCenterBasketList} **/
  basket_list: {
    return_count: "Retur: {count} nummer",
    table: {
      row: "Rad",
      image: "Bild",
      product_name: "Produkt",
      variant: "Variant",
      warranty: "garantier",
      count: "Räkna",
      price: "Pris",
    },
  },

  /** {@see ReturnRequestsList} **/
  return_request_list: {
    count: "Referensnummer",
    return_warranty: "Returgaranti",
    return_warranty_unit: "dag(ar)",
    table: {
      code: "Beställningskod",
      product: "produkt",
      delivery_at: "Mottaget datum",
      state: "status",
      reason: "Anledning",
      return_warranty_period: "Garantiperiod",
    },
  },

  /** {@see DataIteratorToolbar} **/

  data_toolbar: {
    search: "Sök",
    sort_by: "Sortera efter",
    count_item: "Visa {item} objekt",
  },

  sort: {
    created_at: "Skapa datum",
    updated_at: "Ändra datum",
    title: "Titel",
    description: "Beskrivning",
    like: "Popularitet",
    power: "Klappar",
    product_type: "Produkttyp",
    discount: "Rabatt",
    rate: "Betyg",
    rate_count: "Antal kommentarer",
    category: "Kategori",
    product: "Produkt",
    body: "Innehåll",
    card_type: "Kort typ",
    card_number: "Kortnummer",
    balance: "Balans",
    payed: "Använt belopp",
    currency: "Valuta",
    expire_at: "Utgångsdatum",
    discount_code: "Rabattkod",
    discount_percent: "Rabatt i procent",
    discount_limit: "Rabattgräns",
    max_count: "Max antal",
    used_count: "Begagnat antal",
    start_date: "Start datum",
    end_date: "Slutdatum",
    total_discount_amount: "Totalt antal rabatter",
    initial_charge: "Initial laddning",
    total_count: "Totalt antal",
    amount_payed: "Betalt belopp",
    name: "namn",
    published: "Publicerad",
    visits: "Besök",
    color: "Färg",
    landing_page: "Landningssida",
    enable: "Gör det möjligt",
    fix_commission: "Fixa provision",
    percent_commission: "Procent provision",
    payment_at: "Betalningsdatum",
    payment: "Betalning",
    website: "Hemsida",
    email: "E-post",
    user: "Användare",
    code: "Koda",
    schedule_at: "Schemalägg datum",
    sender: "Avsändare",
    in_que: "I que",
    sent: "Skickat",

    shop: "affär",
    quantity: "Kvantitet",
    amount: "Belopp",
    jobs: "Jobb räknas",
    success: "Framgång räknas",
    fail: "Antal misslyckade",
    distance: "Distans",
    duration: "Varaktighet",
    reset_at: "Återställ datum",
    delivery_person: "Person",
    delivery_service: "Service",
    date: "Datum",
    order: "Beställa",
    order_id: "Beställnings-ID",
    status: "Status",
    price: "Pris",
    count: "Räkna",
    final_price: "Slutgiltigt pris",
    charge: "Avgift",
    mention: "Nämna",
    officer: "Officer",

    registered: "Registrerad",
    purchased: "Köpt",
    sex: "Sex",
  },

  /** {@see ShopSearchBox} **/

  search_box: {
    result: "sökresultat",
    tips: "Sök efter produkter och kategorier",
    label: "Sök ...",
    category: "Kategori",
  },

  /** {@see LeadStatus} **/
  lead_status: {
    physical_fast_delivery: "Omedelbar leverans",
    physical_under_24h_delivery: `Leverera inom {lead} nästa timme`,
    physical_over_24h_delivery: `Förbereder och skickar från {days} nästa dag`,
    virtual_fast_prepare: "Omedelbar leverans",
    virtual_under_24h: "Klar med {lead} nästa timme",
    virtual_over_24h: "Klart från {days} nästa dag",
  },

  /** {@see ReturnItemStates} **/
  return_request_state: {
    pending: "I väntan på",
    accepted: "Godkänd",
    rejected: "avvisade",
  },

  /** {@see ReturnOrderReason} **/
  return_order_reason: {
    physical: {
      U1: "produktfel",
      U2: "Ingen produkt i fraktpaketet",
      U3: "Paket- eller produktbrott",
      U4: "Paket eller serienummer manipulation",
      U5: "Brist i produkten",
      U6: "Icke-principen av varor",
      U7: "Överensstämmer med säljarens specifikationer",
    },
  },
  /** {@see ImageUploader} **/
  image_uploader: {
    label: "Dra och släpp eller <u>Välj fil</u>",
    max_size: "Högsta tillåtna storlek: {size}",
  },

  /** {@see TimeSpans} **/
  timespan: {
    Morning: "8-12",
    Evening: "12.00 till 18.00 ",
    Night: "18.00-12.00",
    Instant: "Instant Post",
  },
  /** {@see WeekDays} **/
  week_day: {
    Saturday: "lördag",
    Sunday: "söndag",
    Monday: "måndag",
    Tuesday: "tisdag",
    Wednesday: "onsdag",
    Thursday: "torsdag",
    Friday: "fredag",
  },
  /** {@see PaymentMethodsForm} **/
  payment_form: {
    title: "Välj betalningsmetod",
    gift_cards_input: "Presentkort",
    gift_cards_input_empty: "Inga presentkort hittades..",
    more: "Övrig",
    pay_amount_by_gift_cards: "Betalkortsbetalning",
    select_payment_method:
      "Välj din betalningsmetod från följande alternativ.",
    payment_amount_remained: "Återstående betalningssaldo",
    payment_amount: "betalt belopp",
    all_payed_by_gift_cards:
      "Grattis, du behöver inte betala mer för att köpa den här beställningen. Tryck på betalknappen med presentkortet. ",
    pay_by_gift_cards_action: "Full betalning med laddningskort",

    order_free_payment: "Grattis, din beställning är gratis! ",
    order_free_payment_action: "Beställ nu gratis",

    qr: {
      address: "betalningsadress",
      amount: "belopp",
    },
  },
  /** {@see DiscountField} **/
  discount_input: {
    limit: "{percent} % rabatt upp till {limit} {currency}",
    action: "Lägg till rabattkod",
    code_input: "Rabattkod",
    notifications: {
      add_success: "Grattis, giltig rabattkod.",
    },
  },
  /** {@see GiftCard} **/
  gift_card: {
    inactive: "Kortet är inaktiverat",
    expire: "Upphöra",
    transfer: "Överföra",
    send_to_friend: "Skicka till en vän",
  },
  /** {@see CountDown} **/
  count_down: {
    days: "dag",
    hours: "timme",
    minutes: "minuter",
    seconds: "sekunder",
  },
  /** {@see GiftStatus} **/
  gift_status: {
    Unpaid: "Väntar på kvitto",
    Paid: "Betalt",
    Rejected: "avvisade",
    Canceled: "Inställt",
  },

  /** {@see GiftStProgramTypes} **/
  gift_program_status: {
    Airdrop: "Betalningssystem",
    Advertising: "Reklam",
    PersonalGift: "Personlig gåva",
    ShopGift: "Presentaffär",
  },

  /** {@see CurrencySelector} **/
  currency_selector: {
    label: "Valuta",
  },

  /** {@see NeedLoginDialog} **/
  need_login: {
    title: "Logga in",
    login_sms: "SMS-inloggning",
    login_google: "Logga in med Google",
    login_facebook: "Logga in med Facebook",
    login_account: "Logga in av Selldone",
    register: "Ny användare? Registrera nu.",
    mobile_input: "Ange din mobil",
    verification_code: "Verifierings kod",
    msg_title: "Hej,",
    msg_body: "Vänligen logga in, det tar inte mer än några sekunder.",
  },

  /** {@see ShopBadges} **/
  shop_badges: {
    GOLDEN_1YEAR: {
      name: "5 års guldbutik",
    },
    GOLDEN_2YEAR: {
      name: "4 år gammal guldbutik",
    },
    GOLDEN_3YEAR: {
      name: "3 års guldbutik",
    },
    GOLDEN_4YEAR: {
      name: "2 år gammal guldbutik",
    },
    GOLDEN_5YEAR: {
      name: "1 års guldbutik",
    },
    TOKEN_OWNER_1M: {
      name: "Gyllene investerare",
    },
    TOKEN_OWNER_10M: {
      name: "Diamantinvesterare",
    },
    TOKEN_OWNER_100M: {
      name: "Ruby Investor",
    },
    COMMUNITY_LOYAL: {
      name: "Medlem av Superior Community of Communication Networks",
    },
    GOLD_SUPPLIER: {
      name: "Guldleverantör",
    },
    GOLD_SELLER: {
      name: "Guldhandlare",
    },
    CONTENT_SUPERMAN: {
      name: "Bästa innehållsproducent",
    },
    NINJA: {
      name: "Ninja",
    },
    STAR: {
      name: "Stjärna",
    },
    GUARDIAN: {
      name: "Bra kundservice",
    },
    KING: {
      name: "Kung av marknaden",
    },
  },

  /** {@see CookieDialog} **/

  cookie: {
    title: "Denna webbplats använder cookies",
    message:
      "Denna webbplats använder cookies för att förbättra användarupplevelsen. Genom att använda vår webbplats samtycker du till alla cookies i enlighet med vår Cookie Policy.",
    preferences_action: "Hantera inställningar",
    agree_action: "Jag håller med",
  },
  /** {@see BasketItemUserMessageForm} **/
  basket_item_message: {
    title: "Obligatorisk information för denna artikel",
    save_actions: "Spara meddelande",
    notifications: {
      success: "Dina indata har sparats.",
    },
  },
  /** {@see FAQ} **/
  faq: {
    faq: "Vanliga frågor",
    title: "Frågor och svar",
    sub_title: "Det du bad oss göra.",
    message:
      "Leta efter svaret på din fråga bland svaren nedan. Fråga oss om frågorna är obesvarade. ",
    add_question_action: "Ställ ny fråga",
    read_more: "Läs mer ..",
    load_more: "Fler frågor..",
    main_page: "FAQ Huvudsida",
    add_new: "Skicka in ny fråga",
    login_alert: "Logga in för att ställa en fråga.",
    question_input: "Fråga",
    question_input_placeholder: "Ställ din nya fråga.",
    notifications: {
      success_add: "Din fråga har skickats.",
    },
  },

  /** {@see RatingInput} **/
  rating_labels: ["Mycket dåligt", "Dåligt", "Normalt", "Bra", "Utmärkt"],

  /** {@see MapView} **/
  map_view: {
    address_detail: "Adressuppgifter",
    change: "Förändra",
    select: "Välj",
    not_found_address: "Inget värde hittades",
    enter_address_hint: "Ange destinationsadress",
    enter_your_address: "Ange din adress.",
    postal_code: "postnummer",
    phone_input: "Telefon {type}",
    building_number: "Husnummer",
    building_unit: "Enhet",
    full_name_input: "Fullständigt namn {type}",
    save_detail_action: "Spara detaljer",
    more_detail_input: "Mer beskrivning",
    add_address_to_list: "Lägg till adress i listan",
    address_title_input: "Adressetikett (Kräver)",
    notifications: {
      save_in_list:
        "Den här adressen har sparats i din lista med alla dess detaljer.",
      edit_success: "Nya adressvärden sparade i {title}.",
    },
    delete_address_dialog: {
      title: "Ta bort adress",
      message: "Är du säker på att du vill ta bort den här adressen?",
      action: "Ta bort adress",
    },
  },

  /** {@see CommentsManager} **/
  comment_manager: {
    can_not_edit: "Det går inte att redigera den här kommentaren!",
    comment_input_empty: "Meddelandetexten är tom!",
    article_not_saved: "Spara artikeln!",
  },

  /** {@see WheelOfFortune} **/
  wheel_fortune: {
    title: "Spela & vinn",
    message:
      "Kostnaden för varje spel är 10 marker. Du har för närvarande {chips} chip. Få mer chip genom att köpa från butiken.",
    win_message: "Grattis, du vinner!",
    lost_message: "Tyvärr, du förlorar spelet.",
    try_again: "Du kan försöka igen",
  },
  /** {@see Calculator} **/
 /* calculator: {
    title: "Miniräknarens titel",
    formula: "Formel",
    variable_name: "Variabelnamn",
    variable_name_message:
      "Ange variabelnamn och lägg till det att använda i din formel.",
    type: "Variabel typ",
    variable_title: "Variabel titel",
    duplicate_var_name_error: "Kan inte lägga till variabel med samma namn!",
  },*/

  /** {@see StructuredData} **/
  json: {
    add: "Lägg till strukturdata",
    add_message: "Skapa ny strukturdata",
    structures: "Strukturer",
    book: {
      title: "bok",
      desc: "Bokåtgärder som gör det möjligt för användare att köpa boken som de hittar direkt från sökresultat.",
    },
    occupation: {
      title: "Beräknad lön",
      desc: "Information om löneuppskattning, såsom löneintervall och regionbaserade lönemedelvärden för jobbtyper, visas i jobbsökningsupplevelsen på Google.",
    },
    course: {
      title: "Kurs",
      desc: "Utbildningskurser som visas i en leverantörsspecifik lista. Kurser kan innehålla kursens titel, leverantör och en kort beskrivning.",
    },
    howto: {
      title: "Hur",
      desc: "En How-to leder användarna genom en uppsättning steg för att framgångsrikt slutföra en uppgift, med video, bilder och text.",
    },
    recipe: {
      title: "Recept",
      desc: "Recept som visas som ett individuellt rikt resultat eller en del av en värdkarusell.",
    },
  },

  /** {@see SupportCategory} **/
  support: {
    Financial: "Finansiell",
    Technical: "Teknisk",
    Advisor: "Rådgivare",
  },

  /** {@see ProductCondition} **/
  condition: {
    new: "Ny",
    refurbished: "Renoverad",
    used: "Begagnade",
    used_fair: "Använd rättvist",
    used_good: "Använd bra",
    used_like_new: "Använd - Som ny",
  },

  /** @see VariantFilter **/
  variant_filter: {
    title: "Produktvariationsfilter",
    only_available: "I lager",
  },

  /** Service **/
  service: {
    task: {
      title: "Uppgifter",
      message: "Lista över uppgifter som utförs i denna tjänst.",
    },
    appointment: {
      title: "Utnämning",
      message:
        "Välj tider i veckan från följande tider baserat på den dag och timme som är rätt för dig.",
    },
    booking: {
      title: "Bokning",
      message:
        "Ange tidsperioden för de dagar du vill göra en bokning i kalendern nedan.",
    },
    subscription: {
      title: "Prenumeration",
    },
    charge: {
      title: "Avgift",
    },
  },
  /** PricingTypes **/
  PricingTypes: {
    FIX: {
      title: "Fast prissättning",
      message:
        "I denna typ av prissättning är priset på produkten ett fast belopp och det finns ingen anledning för köparen att begära en priskalkyl.",
    },
    ESTIMATION: {
      title: "Uppskattad prissättning",
      message:
        "Priset på varor och tjänster kommer till viss del att beräknas av säljaren vid beställning, betalningsfakturor kan ändras eller läggas till under tjänsten.",
    },
    AGREEMENT: {
      title: "Avtalsprissättning",
      message:
        "Det slutliga priset på varorna eller tjänsterna kommer inte att ändras av säljaren efter att beställningen har lagts.",
    },
    BID: {
      title: "Bud / Auktion",
      message:
        "Produkten kommer att säljas till det högsta budpriset av potentiella köpare.",
    },
  },

  /** {@see App} {@see Shop} **/
  map: {
    title: "Destination för att ta emot varor",
    confirm: "Ställ in plats",
    address: "Destination",
    receptor: "Receptor",
  },

  /** {@see ShopBots} **/
  ShopBots: {
    telegram: "Telegram",
  },

  /** {@see ArticleEditTags} **/
  article_tags: {
    title: "Innehållstaggar",
    tags_input: "Taggar",
    tags_input_message: "Taggar Lista över denna artikel",
    notification: {
      add_success: "Taggar har lagts till",
    },
  },
};
