import colors from "./colors/en";

export default {
  //--------- Default Values ---------
  currency_default: "USD",
  language_default: "en",
  //----------------------------------

  store: "Mağaza",

  not_exist: "mevcut değil",
  error: "hata",
  active: "Aktif",
  inactive: "etkin değil",
  required_value: "Gerekli değerler",

  original_warranty: "Malların orijinallik garantisi",
  return_warranty_days: "{days} iade garantisi günü",
  no_return_warranty: "İade garantisi yok",

  reed_agree_terms:
    "Kullanım şartlarını ve gizlilik politikasını okudum ve kabul ediyorum.",

  // Common:
  commons: {
    Currency: "Para birimi",
    COD: "COD",
    State: "Belirtmek, bildirmek",
    Price: "Fiyat",
    order_price: "Sipariş fiyatı",
    VAT: "VAT",
    Discount: "İndirim",
    In_Stock: "Stokta var",
    Variants: "varyantlar",
    No_variants: "Varyant yok",
    all: "Herşey",
    today: "Bugün",
    yesterday: "Dün",
    license: "Lisans",
    home: "Ev",
    support: "Destek",
    messages: "Mesajlar",
    no_message: "Mesaj yok",
    empty: "Boş",
    phone: "Telefon",
    address: "Adres",
    name: "İsim",
    password: "Parola",
    email: "E-posta",
    mobile: "mobil",
    login: "Giriş yapmak",
    register: "Kayıt olmak",
    select_account: "Hesap seçin",
    online: "İnternet üzerinden",
    offline: "Çevrimdışı",
    finish: "Sona ermek",
    finished: "bitmiş",
    preview: "Ön izleme",
    free: "Özgür",
    free_completely: "Tamamen ücretsiz abonelik",
    fee: "Ücret",
    month: "Ay",
    faq: "Sıkça Sorulan Sorular",
    question: "Soru",
    answer: "Yanıt vermek",

    create_date: "Oluşturma Tarihi",
    update_date: "Güncelleme Tarihi",
    start_date: "Başlangıç tarihi",
    end_date: "Bitiş tarihi",
    social: "Sosyal",
    total: "Toplam",
    orders: "Emirler",
    sessions: "Oturumlar",
    product_views: "Ürün görünümleri",
    add_to_carts: "sepetlere ekle",
    checkouts: "Ödemeler",
    payments: "ödemeler",
    organic_search: "Organik arama",
    other: "Diğer",

    landing_page: "Açılış sayfası",
    discount_code: "İndirim kodu",
    total_sell: "Toplam satış",
    details: "Detaylar",
    currency: "Para birimi",
    amount: "Miktar",

    published: "Yayınlanan",
    draft: "Taslak",

    save_changes: "Değişiklikleri Kaydet",

    source: "Kaynak",
    medium: "Orta",
    url: "URL'si",
    revenue: "Hasılat",
    performance: "Verim",
    term: "Terim",
    content: "İçerik",

    session: "Oturum",
    product: "Ürün",
    add: "Eklemek",
    checkout: "Ödeme",
    payment: "Ödeme",

    more_options: "Daha fazla seçenek",

    full_name: "Ad Soyad",
    tel: "telefon",
    about_me: "Benim hakkımda",
    request_checking: "Kontrol talebi",
    passport: "Pasaport",
    birthday: "Doğum günü",
    country: "Ülke",
    city: "Şehir",

    gender: "Cinsiyet",

    offer: "Teklif",

    website: "İnternet sitesi",

    apply_for_all_products: "Tüm ürünler için başvurun",

    fix_commission: "Komisyonu düzelt",
    percent_commission: "Yüzde komisyon",

    fixed_discount: "Sabit indirim",
    discount_percentage: "Yüzde indirim",
    discount_limit: "İndirim limiti",
    no_code: "Kod yok",
    max_count: "Maksimum sayı",
    count_unit: "öğeler",
    used: "Kullanılmış",
    daily: "Günlük",
    monthly: "Aylık",
    yearly: "Yıllık",
    state: "Belirtmek, bildirmek",
    disable: "Devre dışı bırakmak",
    enable: "Olanak vermek",
    activation_code: "Aktivasyon kodu",
    quantity: "Miktar",
    no_club: "kulüp yok",
    per_order: "Sipariş başına",
    count: "Saymak",

    seconds: "saniye",
    auto: "Oto",

    title: "Başlık",
    message: "İleti",
    width: "Genişlik",
    length: "Uzunluk",
    height: "Yükseklik",

    label: "Etiket",
    click: "Tıklamak",
    bank: "Banka",

    default: "Varsayılan",
    role: "rol",
    user: "kullanıcı",
    users: "Kullanıcılar",
    code: "kod",
    total_payment: "Toplam ödeme",
    balance: "Denge",

    chance: "Şans",
    free_for_new_users: "Yeni kullanıcılar için ücretsiz",
    prize_amount: "Ödül miktarı",
    win: "Kazanç",
    gift_card: "Hediye kartı",
    discount: "İndirim",
    config: "yapılandırma",
    prize: "Ödül",
    Prizes: "Ödüller",
    result: "Sonuç",

    price: "Fiyat",
    lottery: "Piyango",
    coupon: "Kupon",
    customer_club: "Müşteri kulübü",
    shipping: "Nakliye",
    sum: "Nakliye",
    not_payed: "Ödenmeyen",
    category: "Kategori",
    done: "Tamamlandı",
    email_from: "İtibaren",
    subject: "Ders",
    schedule: "Takvim",

    files_list: "Dosya listesi",
    file_max_size: "Maksimum Dosya Boyutu",
    value: "Değer",
    help: "Yardım",

    shipping_tax: "Nakliye vergisi",
    net_price: "Net fiyat",
    tax: "Vergi",
    tax_included: "Fiyata dahil",

    limit: "sınır",
    min_purchase: "Minimum satın alma",
    eligible_for: "Minimum satın alma",
    only_for_first_buy: "Sadece ilk satın alma için",
    one_time_use: "Bir kez kullanabilir",
    period_of_qualify: "Yeterlilik dönemi",
    no_constraint: "kısıtlama yok",

    timespan: "Zaman aralığı",
    days: "gün(ler)",
    weight: "Ağırlık",
    distance: "Mesafe",

    last_status: "Son durumu",
    issued_at: "Yayınlanan",
    order: "Emir",
    order_detail: "Sipariş detayı",

    percent: "Yüzde",
    applied_count: "Uygulanan sayım",
    campaign: "Kampanya",
    os: "İşletim sistemi",
    browser: "Tarayıcı",
    device: "Cihaz",
    device_ip: "Cihaz IP adresi",
    location: "Konum",
    user_agent: "Kullanıcı aracısı",
    affiliate: "bağlı kuruluş",
    timeline: "Zaman çizelgesi",
    add_note: "Not ekle",
    record: "Kayıt",
    unlimited: "Sınırsız",
    show_coupons: "Kuponları göster",
    hide_coupons: "Kuponları gizle",
    service_area: "Hizmet alanı",
    apps: "uygulamalar",
    plugins: "Eklentiler",
    bots: "Botlar",
    categories: "Kategoriler",
    products: "Ürün:% s",
    business: "İşletme",
    personal: "Kişiye özel",
    size: "Boyut",
    holiday: "Tatil",
    sod: "Teslimatta kargo",
    cod: "Kapıda ödeme",
    free_shipping: "Ücretsiz kargo",
    hours: "Saatler",
    send_date: "Gönderi tarihi",
    deliver_date: "Teslim tarihi",
    return_date: "Dönüş tarihi",
    pending: "Bekliyor",
    delivered: "Teslim edilmiş",
    returned: "İade",
    canceled: "İptal edildi",
    shipping_cost: "Nakliye maliyeti",
    action: "Eylem",
    cancel_date: "Tarihi iptal et",
    deliver_in_process: "Sipariş kargoya verildi..",
    kind: "Tür",
    detail: "detay",
    map: "Harita",
    actions: "Hareketler",
    navigation: "Navigasyon",
    navigation_app: "Uygulama",
    payment_date: "Ödeme tarihi",
    duration: "Süre",
    bill: "Fatura",
    delivery_persons: "Teslimat görevlileri",
    delivery_services: "Teslimat hizmetleri",
    live_view: "Canlı görüntü",
    cart: "Araba",
    priority: "Öncelik",
    sufficient_credit: "Yeterli kredi",
    max_package_size: "Maksimum paket boyutu",
    delay: "Gecikme",
    credit: "Kredi",
    livemode: "Canlı olarak",
    debug: "hata ayıklama",
    token: "Jeton",
    status: "Durum",
    courier: "Kurye",
    track: "İzlemek",
    track_order: "Takip sırası",
    cost: "Maliyet",
    receipt: "Fiş",
    origin: "Menşei",
    destination: "Hedef",
    sku: "SKU",
    mpn: "MPN",
    not_in_stock: "Yeterli stok yok!",
    sub_total: "Ara toplam",
    customer: "Müşteri",
    delivery: "Teslimat",
    online_orders: "Çevrimiçi Siparişler",
    pos_orders: "POS Siparişleri",
    chips: "cips",
    subscribed: "Abone olundu",
    unsubscribed: "abonelikten çıktı",
    last_login: "Son giriş",
    join_at: "Üyelik tarihi",
    club: "kulüp",
    buyer: "Alıcı",
    seller: "satıcı",
    or: "Veya",
    type: "Tip",
    condition: "Şart",
    brand: "Marka",
    attempt: "Girişim",
    error: "Hata",
    success: "Başarı",
    fail: "Başarısız",
    inventory: "Envanter",
    link: "Bağlantı",
    visits: "ziyaretler",
    transactions: "işlemler",
    vat: "vat",
    pos_vat: "POS KDV",
    sort_by: "Göre sırala..",
    from: "İtibaren",
    from_lead_time: "sonraki {hours} saat içinde",
    no_credit_card_info: "Kart Bilgisi Yok!",

    active: "Aktif",
    not_active: "Etkinleştirilmedi!",
    referrals: "tavsiyeler",
    dashboard: "Gösterge Paneli",
    more: "Daha",
    inactive: "etkin değil",
    developer: "geliştirici",
    setting: "Ayar",
    membership_conditions: "Üyelik koşulları",
    customers: "müşteriler",
    created_at: "Oluşturulma tarihi",
    updated_at: "Son Güncelleme",
    register_at: "Kayıt Tarihi",
    old: "Eskimiş",
    new: "Yeni",
    start: "Başlangıç",
    end: "Son",
    pos: "POS",
    out_of_stock: "Stoklar tükendi",
    fake: "Sahte",
    low_inventory_warning: "Dikkat, Düşük envanter!",
    webhook: "Web kancası",
    notification: "Bildirim",
    sms: "SMS",
    online_payment_link: "Çevrimiçi ödeme bağlantısı",
    waiting_load_data: "Veri yüklenmesi bekleniyor..",

    views: "Görüntüleme",
    sales: "Satış",
    total_views: "Toplam görüntülenme",
    total_sales: "Toplam satış",
    from_previous_n_days: "önceki {days} günden itibaren",
    drop_shipping: "Direk nakliye",
    commission: "komisyon",
    shipping_area: "Nakliye alanı",
    main_seller: "Ana satıcı",
    domain: "Alan adı",
    contact: "İletişim bilgileri",
    wallet: "Cüzdan",
    reseller: "bayi",

    tracking_code: "İzleme kodu",
    tracking_url: "İzleme URL'si",
    fulfillments: "yerine getirilmesi",
    reject: "Reddetmek",
    reserved: "Ayrılmış",
    score: "Puan",
    customer_price: "Müşteri fiyatı",

    options: "Seçenekler",
    show_details: "Detayları göster",
    no_data: "Veri yok..",
    waiting: "Beklemek...",
    waiting_connecting_payment: "Ödeme hizmetini bekliyorum...",
    creating_secure_payment:'Güvenli ödeme oluşturma.',

    officer: "Subay",

    ticket: "Bilet",
    ticket_url: "Bilet URL'si",
    closed_at: "Kapalı",
    close_ticket: "Bileti kapat",
    reopen_ticket: "Bileti yeniden aç",
    require: "Gerekmek*",
    search: "Aramak...",
    language: "Dilim",
    tasks: "Görevler",
    permissions: "izinler",
    finish_date: "Bitiş tarihi",
    complete_date: "Bitiş tarihi",
    settle_date: "Anlaşma tarihi",
    cost_span: "Fiyat aralığı",
    industry: "sanayi",
    rating: "Değerlendirme",
    rates: "oranlar",
    seen_at: "Görüldü",
    completed: "Tamamlanmış",
    you: "Sen",
    shop: "Mağaza",
    store: "Mağaza",
    granted: "İmtiyazlı",
    deny: "Reddetmek",
    request: "Rica etmek",
    expert: "Uzman",
    response: "Tepki",
    requests: "İstekler",
    experts: "uzmanlar",
    responses: "Tepkiler",
    negotiations: "müzakereler",
    all_chats: "Tüm sohbetler",
    chats: "sohbetler",
    tags: "Etiketler",
    description: "Açıklama",
    rates_count: "Oranlar sayılır",
    rate: "Oran",
    comment: "Yorum Yap",
    chat: "Sohbet etmek",
    install: "Düzenlemek",
    edited: "Düzenlendi",
    undo: "Geri alma",
    redo: "yinele",
    male: "Erkek",
    female: "Dişi",
    calculator: "Hesap makinesi",
    catalog: "Katalog",
    max_height: "maksimum yükseklik",
    images_compare: "Görüntüler karşılaştır",
    canvas: "Tuval",
    table_of_contents: "İçindekiler",
    comments: "Yorumlar",
    badge_codes: "Rozet kodu",
    need_more: "Daha fazlasına ihtiyaç var?",
    invite_glow_caption: "Her arkadaşınız için 14.9$ kazanın!",
    register_free: "%100 Ücretsiz kayıt",
    gift: "Hediye",

    google: "Google",
    facebook: "Facebook",
    instagram: "Instagram",
    instashop: "Instashop",

    show: "Göstermek",
    hide: "Saklamak",
    waiting_review: "İnceleme bekleniyor",
    not_selected: "Seçili değil",
    time: "Time",

    final_price: "Son fiyat",
    starting_price: "Başlangıç fiyatı",

    day: "gün",
    payed: "Paralı",
    service_bill: "Fatura ödeme",
    avocado: "Avokado",

    delivery_price: "Nakliye maliyeti",
    select_address: "Adres seçin",
    image: "resim",
    view: "görüş",
    sell: "Satmak",

    hyper: "Aşırı",
    cart_list: "Araba",
    barcode_scanner: "Barkod okuyucu",
    scan_qr_code: "QR kodunu tara",

    new_carts: "Yeni arabalar",
    pays: "ödemeler",
    annually: "yıllık",
    sells: "satıyor",
    articles: "Nesne",
    jobs: "Meslekler",
    job: "İş",
    blog: "Blog",
    deleted_at: "Silindi",
    capacity: "Kapasite",
    download_at: "Son indirme tarihi",
    downloads: "İndirilenler",
    usage: "kullanım",
    select_upload_file: "Dosya seç veya bırak",
    download_link: "İndirme: {link",
    uploading: "yükleniyor..",
    files: "Dosyalar",
    star: "Yıldız",
    speed: "Hız",
    feedback: "Geri bildirim",
    new_messages: "Yeni mesajlar",
    file: "Dosya",
    attachment: "Ek dosya",
    gallery: "Galeri",
    sync: "senkronizasyon",
    diff_time: "Zaman farkı",
    network: "Ağ",
    account: "Hesap",
    configuration: "Yapılandırma",
    blockchain: "blok zinciri",
    blog_link: "Blog bağlantısı",
    community: "Topluluk",
    critical_zone: "kritik bölge",
    statistics: "İstatistik",
    access: "Erişim",
    seo: "SEO",
    followers: "Takipçiler",
    followings: "Takip edilenler",
    private: "Ön izleme",
    soon: "Yakın zamanda",
    features: "Özellikleri",
    bot: "bot",
    sample: "Örnek",
    how_it_work: "O nasıl çalışır?",
    page: "Sayfa",
    congratulations: "Tebrikler",
    recommend: "Önermek",
    recommended: "Tavsiye edilen",
    recoms: "tavsiye eder",
    likes: "Seviyor",
    clicks: "tıklamalar",
    platform: "platformu",
    cms: "cms",
    cash: "Peşin",
    dir_payment: "Banka transferi",
    auto_complete: "Otomatik tamamlama",
    compare: "Karşılaştırmak",
    infinite: "Sonsuz",
    tips:'İpuçları',
    technical:'Teknik',
    finance:'finans',
    your_phone_input:'Telefon numarası girin',
    income:'Gelir',
    change:'Değişiklik',
    new_users:'Yeni kullanıcılar',
    success_orders:'Başarı siparişleri',
    direct:'doğrudan',
    last_activity:'Son Aktivite',
    landing:'İniş',

  },

  dialogs: {
    delete: {
      title: "Silmek",
      message: "Bu öğeyi silmek istediğinizden emin misiniz?",
      action: "Evet, Şimdi Sil",
    },
  },

  actions: {
    add_to_cart: "Sepete ekle",
    cancel: "İptal etmek",
    update: "Güncelleme",
    add: "Eklemek",
    delete: "Silmek",
    new: "Yeni",
    save_continue: "Kaydet ilerle",
    save: "Kayıt etmek",
    save_changes: "Değişiklikleri Kaydet",
    continue: "Devam et",
    close: "Kapat",
    finish: "Sona ermek",
    poll: "Anket",
    view: "görüş",
    edit: "Düzenlemek",
    next: "Sonraki",
    previous: "Öncesi",
    create: "Yaratmak",
    set: "Ayarlamak",
    find: "Bulmak",
    accept: "Kabul",
    reject: "Reddetmek",
    back: "Geri",
    pay: "Ödemek",
    pay_now: "Şimdi öde",
    print: "Yazdır",
    return: "Dönüş",
    publish: "Yayınla",
    confirm: "Teyit etmek",
    copy: "kopyala",
    submit: "Göndermek",
    send: "Göndermek",
    yes: "Evet",
    no: "Numara",
    meh: "Hmm",
    clear: "Temizlemek",
    dismiss: "Azletmek",
    search: "Aramak",
    deselect_all: "Tüm seçimleri kaldır",
    select_all: "Hepsini seç",
    refresh: "Yenile",
    verify: "Doğrulayın",
    play: "Oyna",
    open: "Açık",
    calculate: "Hesaplamak",
    quick_buy: "Hızlı satın al",
    click_here: "Buraya Tıkla",
    schedule: "Takvim",
    send_now: "Şimdi gönder",
    download: "İndirmek",
    reset_default: "Varsayılana sıfırla",
    reset: "Sıfırla",
    check: "Kontrol",
    cod_payment: "Kapıda ödeme",
    dir_payment: "Para transferi",
    online_payment: "Online ödeme",
    checkout: "Ödeme",
    show_all: "Hepsini Göster ↓",
    login: "Giriş yapmak",
    logout: "Çıkış Yap",
    more: "Daha..",
    collapse: "Yıkılmak",
    apply_change: "Değişiklikleri uygula",
    apply: "Uygulamak",
    add_giftcard: "Hediye kartı ekle",
    charge: "Şarj etmek",
    send_invites: "Davet gönder",
    past: "Geçmiş",
    restore: "Eski haline getirmek",
    cut: "Kesmek",
    get_sms_code: "Kimlik doğrulama kodunu al",
    register_no_mail: "E-posta olmadan devam et",
    no_mail_register_message:
      "Bir e-posta adresiniz yok mu veya şifrenizi mi unuttunuz?",
    reset_by_mail: "E-posta ile şifre kurtarma",
    reset_by_sms: "SMS ile şifre kurtarma",
    cash_payment: "Nakit ödeme",
    show_chart: "Grafiği göster",
    open_app: "Uygulamayı aç",
    login_now: "Şimdi giriş yap",
    watch_video: "Video izle",
    check_now: "Şimdi kontrol et",
    remove_image: "Resmi kaldır",
    view_website: "Linki aç",
    explore: "{name}'yi keşfedin",
    go: "Gitmek",
    read_more: "Daha fazla oku",
    start_now: "Şimdi başla",
    view_live:'Canlı izle',
  },

  errors: {
    gateway_blockchain_sync_error:
      "Sistem blok zinciri ile senkronize değil. Sunucularımızın senkronizasyonu tamamlanana kadar yeni bir işlem oluşturmak mümkün olmayacaktır. Sorunu çözüyoruz.",
    gateway_network_error:
      "Ödeme ağ geçidi hizmeti bir iletişim sorunuyla karşılaştı.",
  },

  /** @see BuyerReceiverInfoView **/
  receiver_info: {
    map: {
      title: "Teslimat Adresi",
      confirm: "Konumu ayarla",
      address_type: "Hedef",
      receptor_type: "Alıcı",
    },
    receiver_address: "Sevkiyat adresini seçin",
    address: "Adres",
    postcode: "Posta kodu",
    enter_value: "Burayı doldurun",
    address_note: "Not",
    tel: "İletişim numarası",
  },

  weight: {
    kg: "kilogram",
  },
  length: {
    cm: "santimetre",
  },

  distance: {
    m: "metre",
    km: "Km",
  },
  time: {
    days: "günler",
    hours: "Saatler",
    minutes: "dakika",
    seconds: "saniye",
  },

  units: [
    "birim",
    "kalem",
    "her biri",
    "ayarlamak",
    "adet",

    "kilogram",
    "gram",
    "miligram",

    "metre",
    "milimetre",

    "metrekare",
    "fit kare",

    "metreküp",
    "litre",
    "mililitre",

    "ayak",
    "galon",
    "inç",
    "ons",
    "pound",
    "çeyrek",
    "yarda",
    "oda",
  ],

  region_types: {
    State: "Belirtmek, bildirmek",
    Territory: "Bölge",
    Province: "Vilayet",
  },

  transaction_status: {
    RequireAction: "Eylem Gerektir",
    Processing: "İşleme",
    Canceled: "İptal edildi",
    Succeeded: "başarılı",
  },

  placeholders: {
    name: "jane dişi",
    email: "mailiniz@mail.com",
    phone: "+1 000 0000",
    language: "Dil Seçin..",
    friend_email: "Arkadaşlarınızın e-postası...",
    friend_name: "Arkadaşının adı",
  },

  notification: {
    confirm: "Teyit etmek",
    confirm_message: "Değişimler başarıyla kaydedildi.",
    error: "Hata",
    message: "İleti",
    caution: "Dikkat",
    warning: "Uyarı",
    award: "tebrikler",

    error_message: "Maalesef bir hata oluştu.",
    congratulation: "tebrikler",
    coming_soon: "Yakın zamanda",
    on_fetching_data: "Bilgi alınıyor..",
    new_pwa_version:
      "Yeni sürüm şu anda mevcut. Uygulamayı güncellemek istiyor musunuz?",
    over_license_limit: "Lisans Limitinin Üzerinde",
    update_license: "Lisansınızı güncelleyin",

    required: "Gerekli",
    invalid_email: "Geçersiz e-posta",
    invalid_domain: "geçersiz alan",
    invalid_min_length: "Minimum uzunluk {length} olmalıdır",
    invalid_min_array_length: "En azından {length} öğe seçin",

    invalid_max_chars: "Maks. {maxCount} karakter",
    invalid_url: "Geçersiz URL",
  },

  colors: colors,

  address_info: {
    name: "İsim",
    tel: "Telefon",
    email: "E-posta",
    country: "Ülke",
    city: "Şehir",
    state: "Belirtmek, bildirmek",
    address: "Adres",
    building_number: "Bina numarası",
    building_unit: "Birim",
    postcode: "Posta kodu",
    note: "Not",
  },

  /** {@see ProductType} **/
  product_types: {
    physical: "Fiziksel",
    physical_description:
      "Cep telefonları, kitaplar, elektronik bileşenler gibi fiziksel ürünler.",

    virtual: "Gerçek",
    virtual_description:
      "Şarj kartı, otel rezervasyonu, oyun şarjı gibi internet dostu ürünler.",
    file: "Dosya",
    file_description: "İzin verilen tüm dosyalar bu kategoriye girer.",

    service: "Hizmet",
    service_description: "Hizmetler: onarım, ulaşım, öğretim.",
  },

  license: {
    free: "Özgür",
    startup: "Başlatmak",
    company: "Şirket",
    enterprise: "Girişim",
  },

  /** @see Currency */

  currency: {
    IRR: "IRR",
    IRR_alt: "Toman",
    USD: "USD",
    BTC: "BTC",
    ETH: "ETH",
    NIOC: "NIOC",
    SEL: "SEL",
    EUR: "EUR",
    ADA: "ADA",
    GBP: "GBP",
    AED: "AED",
    AFN: "AFN",
    CAD: "CAD",
    TRY: "TRY",
    CNY: "CNY",
    RUB: "RUB",
    SAR: "SAR",
    LBP: "LBP",
    QAR: "QAR",
    EGP: "EGP",
    INR: "INR",
    DKK: "DKK",
    PKR: "PKR",
    ALL: "ALL",
    AMD: "AMD",
    ANG: "ANG",
    AOA: "AOA",
    ARS: "ARS",
    AUD: "AUD",
    AWG: "AWG",
    AZN: "AZN",
    BAM: "BAM",
    BBD: "BBD",
    BDT: "BDT",
    BGN: "BGN",
    BIF: "BIF",
    BMD: "BMD",
    BND: "BND",
    BOB: "BOB",
    BRL: "BRL",
    BSD: "BSD",
    BWP: "BWP",
    BYN: "BYN",
    BZD: "BZD",
    CDF: "CDF",
    CHF: "CHF",
    CLP: "CLP",
    COP: "COP",
    CRC: "CRC",
    CVE: "CVE",
    CZK: "CZK",
    DJF: "DJF",
    DOP: "DOP",
    DZD: "DZD",
    ETB: "ETB",
    FJD:'FJD',
    FKP:'FKP',
    GEL:'GEL',
    GIP:'GIP',
    GMD:'GMD',
    GNF:'GNF',
    GTQ:'GTQ',
    GYD:'GYD',
    HKD:'HKD',
    HNL:'HNL',
    HRK:'HRK',
    HTG:'HTG',
    HUF:'HUF',
    IDR:'IDR',
    ILS:'ILS',
    ISK:'ISK',
    JMD:'JMD',
    JPY:'JPY',
    KES:'KES',
    KGS:'KGS',
    KHR:'KHR',
    KMF:'KMF',
    KRW:'KRW',
    KYD:'KYD',
    KZT:'KZT',
    LAK:'LAK',
    LKR:'LKR',
    LRD:'LRD',
    LSL:'LSL',
    MAD:'MAD',
    MDL:'MDL',
    MGA:'MGA',
    MKD:'MKD',
    MMK:'MMK',
    MNT:'MNT',
    MOP:'MOP',
    MRO:'MRO',
    MUR:'MUR',
    MVR:'MVR',
    MWK:'MWK',
    MXN:'MXN',
    MYR:'MYR',
    MZN:'MZN',
    NAD:'NAD',
    NGN:'NGN',
    NIO:'NIO',
    NOK:'NOK',
    NPR:'NPR',
    NZD:'NZD',
    PAB:'PAB',
    PLN:'PLN',
    SGD:'SGD',
    SEK:'SEK',



  },

  variants: {
    color: "Renk",
    volume: "Boyut",
    count_in_pack: "Pakette say",
    weight: "Ağırlık",
    type: "Malzeme",
    style: "stil",
  },

  /** {@see PhysicalOrderStates} **/
  delivery_state: {
    check_queue: "İnceleme bekleniyor",
    order_confirm: "Sipariş onayı",
    preparing_order: "hazırlanıyor",
    sent_order: "Teslimatta",
    to_customer: "Teslim edilmiş",
  },
  
  
  status: {
    unpaid: "ödenmemiş",
    paid: "paralı",
    canceled: "İptal edildi",
    completed: "yerleşik",
    reserved: "Ayrılmış",
    COD: "COD",
    sold: "satıldı",
    open: "Açık",
    cancel: "İptal edildi",
    active: "Aktif",
    inactive: "etkin değil",
    debug: "hata ayıklama",
    live: "Canlı olarak",
    test: "Ölçek",
    connected: "bağlı",
    disconnected: "Bağlantı kesildi",
    accept: "Kabul",
    reject: "Reddetmek",
    pending: "Bekliyor",
    rejected: "Reddedildi",
    accepted: "Kabul edilmiş",
  },
  dimensions: {
    cm: "santimetre",
    km: "km",
    kg: "kilogram",
  },

  /** {@see ShopTransportations} **/
  transportation_type: {
    motorbike: "Motosiklet",
    motorbike_description: "Birkaç kilometre içinde orta navlun.",
    cargo_small: "Küçük kargo",
    cargo_small_description: "Çok kilometrelik hafif kargo.",
    cargo: "Kargo",
    cargo_description: "Birkaç kilometre içinde orta boy navlun.",
    truck: "kamyon",
    truck_description: "Ülke içinde dökme veya ağır kargo.",
    fast_post: "Hızlı Posta",
    fast_post_description: "Postane aracılığıyla hızlı gönderi.",
    post: "Normal posta",
    post_description: "Postane aracılığıyla normal posta.",
    airplane: "Uçak postası",
    airplane_description: "Yerli ve yabancı hafif ve orta kargo.",
    bicycle: "Temiz Gönder",
    bicycle_description:
      "Motorsuz araçların birkaç yüz metre yakınında hafif kargo.",
    global: "Küresel ulaşım",
    global_description: "Hava, deniz veya kara yoluyla deniz aşırı nakliye.",
    pickup: "Toplamak",
    pickup_description:
      "Siparişler müşteri tarafından mağazanızın veya deponuzun içinden alınır.",
  },

  /** {@see ArticleView} **/
  article: {
    login_to_see_error: "Makaleye erişmek için giriş yapın",
    create_new_action: "Yeni İçerik Oluştur",
    menu_title: "Menü",
    menu: {
      edit: "Düzenleme modu",
      view_mode: "Görüntüleme modu",
      delete: "Makaleyi Sil",
    },
    schedule_action: "Program yayınlamak istiyor musunuz?",
    schedule_title: "Otomatik yayınlamayı planla",
    edit_mode: "Düzenlemek",
    public_view_mode: "Halk görüşü",
    publish_at: "Yayınla",
    published: "Yayınlanan",
    draft: "Taslak",
    saving: "Depoda",
    save_and_publish_action: "Kaydet ve Yayınla",
    save_draft_action: "Taslağı kaydet",
    private: "Özel",
    public: "Halk",
    category_input: "Kategori",
    category_input_message: "Makale kategorisini seçin",
    parent_input: "babanın hikayesi",
    parent_input_message: "Baba içeriğini seç",
    schedule_input: "Takvim",
    schedule_input_placeholder:
      "Hikayenin belirli bir zamanda yayınlanmasını istiyorsanız.",
    schedule_view_action: "Yayın Planını Görüntüle",

    author_title: "Tarafından gönderildi",
    read_time: "Çalışma zamanı",
    read_time_unit: "dakika",
    claps_action: "Alkışlar",
    claps: "tezahürat",
    likes: "Beğenmek",
    about_author: "Yazar hakkında",
    updated_at: "Güncellenmiş",
    wrote_at: "Şu adrese yazdı:",
    now: "Şimdi",
    follow_action: "Takip et",
    followed: "Takip etti",
    report_and_delete_action: "Bu girişi bildirin ve silin",
    report_action: "Kötüye Kullanımı Bildir",
    you_reported_this_article: "Bu öğe için zaten bir raporunuz var.",
    add_to_publication_action: "Yayına Ekle",
    author_socials: "Sosyal ağlarda yazar",
    share: "Paylaş",
    report_dialog: {
      report_and_delete_title: "Kötüye kullanımı bildir ve içeriği kaldır",
      report_title: "Bu içerik için kötüye kullanımı bildir",
      message:
        "Bu içeriği gönderme sebebiniz nedir? Aşağıdaki seçeneklerden birini seçiniz.",
      accept_and_delete_action: "İçeriği Onayla ve Sil",
    },
    schedule_dialog: {
      title: "İçerik Yayın Takvimi",
      publish_at: "Yayınla",
      last_edit: "Son düzenleme",
      view_action: "Makaleyi Görüntüle",
    },
    notifications: {
      update_success_title: "Bilgi Gönder",
      update_success: "Makale başarıyla güncellendi.",
      update_error: "Girilen bilgiler geçerli değil.",
      delete_error: "Bu makaleyi silemezsiniz!",
      report_and_delete_success_title: "Rapor Etme ve Kaldırma",
      report_and_delete_success_message:
        "Makale başarıyla silindi.",
      report_success_title: "Makaleyi bildir",
      report_success_message: "Bu makaleyle ilgili raporunuz yayınlandı.",
    },
    alert: {
      delete_article: {
        title: "Makaleyi Sil",
        message: "Bu makaleyi kalıcı olarak silmek istediğinizden emin misiniz?",
        action: "Silmek",
      },
    },

    /** {@see ArticleEdit} **/
    edit_window: {
      title: "Resim Metni ve Özeti Seçin",
      digest: "Özet",
    },
    /** {@see EditorContainer} **/
    editor: {
      title_placeholder: "Başlık..",
      body_placeholder: "Harika içerikler yazın..",
      accept_file_types_error: "Bu dosya biçimi kabul edilemez:",
      max_file_size_error: "Bu dosya çok büyük:",
      notifications: {
        image_uploaded_success: "Görüntü başarıyla kaydedildi",
        image_uploaded_failed: "Resim yüklenirken hata oluştu.",
      },
      embed_placeholder:
        "iframe kodunu, facebook, youtube veya başka bir URL'yi girin ve enter tuşuna basın.",
      embed_caption_placeholder: "Bir başlık girin (isteğe bağlı)",
      images_caption_placeholder: "Bu resim için bir başlık girin ..",
    },
  }, // article

  /** {@see ArticleReport} **/
  article_report: {
    inappropriate: "Bu yazının içeriği uygun değildir.",
    fake: "Bu sahte ve aldatıcıdır.",
    spam: "Bu öğe spam olarak gönderildi ve kopyalandı.",
    scam: "Bunun kötü amaçlı yazılımlara, virüslere veya sistem kullanıcılarının çökmesine neden olması beklenebilir.",
    hacked: "Bu site oyulmuş gibi görünüyor",
    offensive:
      "Dil içeriği ve kelime dağarcığı etik dışı ve saygısız.",
    violent:
      "Bu içeriğin pornografi içerdiğini ve yasaları ihlal ettiğini düşünüyorum.",
    harassment: "Bence bu ırkçı.",
    hate: "Bence bu, şiddeti teşvik etmekle ilgili.",
    infringe: "Bu benim haklarımı ihlal ediyor.",
  },

  /** {@see CommentsManager} **/
  comments: {
    new_action: "Yorum bırakmak için tıklayın..",
    title: "Yorumlar",
    body_placeholder: "Yorumunuz veya mesajınız",
    send_action: "Yorum gönder",
    body_is_empty_error: "Yorum boş!",
    comments: "Yorumlar",
    no_comments: "İlk yorumu yaz...",
    load_more_action: "Daha fazla yorum alın..",
    cant_send_comment: "Youyeni gönderiler gönderemez.",
    cant_remove_this_comment: "Bu yorumu silemezsiniz!",
    product_buyer: "Alıcı",

    delete_alert: {
      title: "Yorumu Sil",
      message: "Bu yorumu silmek istiyor musunuz?",
      action: "Silmek",
    },
    notifications: {
      delete_success: "Yorumunuz başarıyla silindi",
    },
    first_send: "İlk gönderi",
    comment_at: "Açık",
    edit_comment: "Yorumu Düzenle",
  },

  /** {@see CustomerClubLevels} **/
  customer_club: {
    bronze: "Bronz",
    silver: "Gümüş rengi",
    gold: "Altın",
    platinum: "Platin",
    diamond: "Elmas",
  },
  /** {@see ApplicationCategories} **/
  application_categories: {
    tracking: "Kullanıcı Davranışını Kontrol Etme",
    payment: "Ödeme",
    seo: "SEO",
    crm: "CRM",
    transportation: "Toplu taşıma",
    automation: "Otomasyon",
    inventory: "depolama",
    accounting: "Muhasebe",
    marketing: "Pazarlama",
    advertising: "reklam",
    staff: "Personel",
    incentive: "Teşvikler",
    shop: "Mağaza",
  },
  /** {@see SocialNetwork} **/
  social_network: {
    instagram: "Instagram",
    telegram: "Telegram",
    googleplay: "GooglePlay",
    appstore: "AppStore",
    twitter: "Twitter",
    linkedin: "Linkedin",
    medium: "Medium",
    selldone: "Selldone",
    facebook: "Facebook",
    pinterest: "Pinterest",
    whatsapp: "WhatsApp",
    skype: "Skype",
    facebook_messenger: "Facebook Messenger",
  },

  /** {@see FormBuilder} **/
  form_builder: {
    add_item_action: "yeni öğe ekle",
    title_input: "Başlık",
    name_input: "Değişken ismi",
    value_input: "değerler",
    value_input_message: "Kullanıcı Seçenekleri Listesi",
    default: "Varsayılan değer",

    types: {
      simple: "basit",
      selective: "seçici",
      switch: "Değiştirmek",
    },
  },

  /** {@see VirtualItemOrderInfoSummery} **/
  virtual_order_info_summery: {
    title: "Ürün adı",
    reserved_at: "Kayıt Tarihi",
    total_price: "Toplam tutar",
    discount: "İndirim",
    final_price: "Son miktar",
    payment_status: "Ödeme Durumu",
    payment_status_waiting: "Ödeme için bekleniyor",
    payment_status_payed: "Paralı",
    buyer: "Alıcı",
  },

  /** {@see VirtualItemInfo} **/
  virtual_item_info: {
    title: "Sanal Öğe ",
    outputs: {
      title: "Çıktı Bilgileri",
      sub_title: "Bu Öğenin Gizli Bilgileri",
      message:
        "Bu bilgiler, ürünü satın aldıktan sonra kullanıcıya gösterilecektir.",
    },

    inputs: {
      title: "Bilgi gerekiyor",
      sub_title: "Alıcı Bilgileri Gerekli",
      message:
        "Alıcı, talep edilen bilgileri talep edilen bilgi formuna girmelidir",
    },

    notifications: {
      inputs_set_success: "Bilgi formu başarıyla kaydedildi.",
      confirm_by_admin_success: "Sipariş tamamlandı onaylandı.",
      confirm_by_buyer_success: "Sipariş tamamlandı onaylandı.",
    },
  },

  /** {@see BasketRejectReasons} **/
  order_reject_reasons: {
    cant_accept_cod:
      "Bu sipariş müşteri tarafından yerinde ödeme kabul edilemez.",
    payment_returned: "Müşteri tarafından yatırılan tutar iade edilir.",
    payment_fraud: "Ödemenin dolandırıcılık olduğu tespit edildi.",
    location_out_of_service: "Müşteri konumu hizmet dışı.",
    user_not_responding: "Müşteri aramalara cevap veremez.",
    shop_owner_fault:
      "Mağaza personeli tarafından bilgi girilirken bir hata oluştu.",
    lack_of_inventory: "Stoklar tükendi.",
    legal_restriction: "Yasal kısıtlamalar nedeniyle sipariş verilemiyor.",
    pricing_fault: "Satıcı tarafından fiyatlandırma hatası.",
    system_fault: "Sistem hatası.",
  },

  /** {@see BasketOrderInfoSummery} **/
  basket_order_info_summery: {
    receiver: "Alıcı teslimatı",
    phone: "Arayan kimliği",
    reserved_date: "Kayıt Tarihi",
    total_price: "Toplam fiyat",
    discount: "İndirim",
    final_price: "Son fiyat",
    address: "Alıcı Teslimat Adresi",
    payment_status: "Ödeme Durumu",
  },

  /** {@see BasketStatus} **/
  basket_status: {
    open: "Açık",
    reserved: "Ayrılmış",
    payed: "Paralı",
    canceled: "İptal edildi",
    cod: "Kapıda ödeme",
    receipt_added: "Fiş eklendi",
    payment_processing: "Odeme yapiliyor",
  },

  /** {@see BasketDeliveryState} **/
  basket_delivery_state: {
    rejected: "Reddedildi",
    reject_reason_not_found: "Nedeni bilinmiyor.",
    step_1: "İnceleme bekleniyor",
    step_2: "Sipariş onayı",
    step_3: "Hazırlık",
    step_4: "Teslimat acentesine",
    step_5: "Müşteriye teslim",
  },
  /** {@see BasketReturnItemsRequestView} **/
  basket_return_request_view: {
    title: "İade Talebi",
    delivery_date: "Teslim tarihi",
    return_date: "İstek Tarihi",
    items_count: "İade sayısı",
    items_count_unit: "öğeler)",
    reason: "Sebep",
    description: "Açıklama",
    status: "Durum",
    download_image: "Resmi indir",
    download_film: "Video indir",
    download_voice: "Sesi indir",
    accept_by_admin_action: "kabul et isteği",
    reject_by_admin_action: "isteği reddet",
    message_for_admin:
      "Selldone'u kullanarak kabul ettiğiniz sözleşmeye göre, alıcı ile iletişime geçmeli ve siparişinin iade süreci hakkında onu bilgilendirmelisiniz. Bu, talep kabul edilir veya reddedilirse ve alıcının tam onayı alınırsa yapılmalıdır.",
    notifications: {
      update_status_success: "İstek durumu güncellendi.",
    },
  },

  /** {@see ShopProcessCenterBasketList} **/
  basket_list: {
    return_count: "Dönüş: {count} sayı",
    table: {
      row: "Sıra",
      image: "resim",
      product_name: "Ürün",
      variant: "varyant",
      warranty: "garantiler",
      count: "Saymak",
      price: "Fiyat",
    },
  },

  /** {@see ReturnRequestsList} **/
  return_request_list: {
    count: "Referans numarası",
    return_warranty: "İade garantisi",
    return_warranty_unit: "gün(ler)",
    table: {
      code: "Sipariş Kodu",
      product: "ürün",
      delivery_at: "Ulaşma tarihi",
      state: "durum",
      reason: "Sebep",
      return_warranty_period: "Garanti süresi",
    },
  },

  /** {@see DataIteratorToolbar} **/

  data_toolbar: {
    search: "Ara",
    sort_by: "Göre sırala",
    count_item: "{item} öğelerini göster",
  },

  sort: {
    created_at: "Oluşturma Tarihi",
    updated_at: "Tarihi değiştir",
    title: "Başlık",
    description: "Açıklama",
    like: "Popülerlik",
    power: "Alkışlar",
    product_type: "Ürün tipi",
    discount: "İndirim",
    rate: "Değerlendirme",
    rate_count: "Yorum sayısı",
    category: "Kategori",
    product: "Ürün",
    body: "İçerik",
    card_type: "Kart tipi",
    card_number: "Kart numarası",
    balance: "Denge",
    payed: "Harcanan miktar",
    currency: "Para birimi",
    expire_at: "Son kullanma tarihi",
    discount_code: "İndirim kodu",
    discount_percent: "İndirim Yüzdesi",
    discount_limit: "İndirim limiti",
    max_count: "Maksimum sayı",
    used_count: "Kullanılan sayı",
    start_date: "Başlangıç tarihi",
    end_date: "Bitiş tarihi",
    total_discount_amount: "Toplam indirim tutarı",
    initial_charge: "Başlangıç ücreti",
    total_count: "Toplam sayım",
    amount_payed: "Ödenen miktar",
    name: "İsim",
    published: "Yayınlanan",
    visits: "ziyaretler",
    color: "Renk",
    landing_page: "Açılış sayfası",
    enable: "Olanak vermek",
    fix_commission: "Komisyonu düzelt",
    percent_commission: "Yüzde komisyon",
    payment_at: "Ödeme tarihi",
    payment: "Ödeme",
    website: "İnternet sitesi",
    email: "E-posta",
    user: "kullanıcı",
    code: "kod",
    schedule_at: "Takvim tarihi",
    sender: "Gönderen",
    in_que: "que",
    sent: "Gönderilmiş",

    shop: "Mağaza",
    quantity: "Miktar",
    amount: "Miktar",
    jobs: "İş sayısı",
    success: "Başarı sayısı",
    fail: "Başarısız sayısı",
    distance: "Mesafe",
    duration: "Süre",
    reset_at: "Tarihi sıfırla",
    delivery_person: "Kişi",
    delivery_service: "Hizmet",
    date: "Tarih",
    order: "Emir",
    order_id: "Sipariş Kimliği",
    status: "Durum",
    price: "Fiyat",
    count: "Saymak",
    final_price: "Son fiyat",
    charge: "Şarj etmek",
    mention: "Anma",
    officer: "Subay",

    registered: "Kayıtlı",
    purchased: "satın alındı",
    sex: "Seks",
  },

  /** {@see ShopSearchBox} **/

  search_box: {
    result: "Arama Sonuçları",
    tips: "Ürün ve Kategori Ara",
    label: "Aramak ...",
    category: "Kategori",
  },

  /** {@see LeadStatus} **/
  lead_status: {
    physical_fast_delivery: "Anında teslimat",
    physical_under_24h_delivery: `Önümüzdeki saat {lead} içinde teslim edin`,
    physical_over_24h_delivery: `Ertesi gün {days} tarihinden itibaren hazırlanıyor ve gönderiliyor`,
    virtual_fast_prepare: "Anında teslimat",
    virtual_under_24h: "Önümüzdeki saat {lead}'a kadar tamamlandı",
    virtual_over_24h: "{days} sonraki günden itibaren yapılır",
  },

  /** {@see ReturnItemStates} **/
  return_request_state: {
    pending: "Bekliyor",
    accepted: "Onaylandı",
    rejected: "Reddedildi",
  },

  /** {@see ReturnOrderReason} **/
  return_order_reason: {
    physical: {
      U1: "ürün uyuşmazlığı",
      U2: "Kargo paketinde ürün yok",
      U3: "Paket veya ürün kırılması",
      U4: "Paket veya seri numarası kurcalama",
      U5: "Ürün içi kıtlık",
      U6: "Mal ilkesi dışı",
      U7: "Satıcı Spesifikasyonlarına Uygun",
    },
  },
  /** {@see ImageUploader} **/
  image_uploader: {
    label: "Sürükle ve Bırak veya <u>Dosya seç</u>",
    max_size: "İzin verilen maksimum boyut: {size}",
  },

  /** {@see TimeSpans} **/
  timespan: {
    Morning: "8am - 12pm",
    Evening: "öğlen 12'den akşam 6'ya ",
    Night: "18:00-12:00",
    Instant: "Anında Gönderi",
  },
  /** {@see WeekDays} **/
  week_day: {
    Saturday: "Cumartesi",
    Sunday: "Pazar",
    Monday: "Pazartesi",
    Tuesday: "Salı",
    Wednesday: "Çarşamba",
    Thursday: "Perşembe",
    Friday: "Cuma",
  },
  /** {@see PaymentMethodsForm} **/
  payment_form: {
    title: "Ödeme türünü seçin",
    gift_cards_input: "Hediye Kartları",
    gift_cards_input_empty: "Hediye kartı bulunamadı..",
    more: "Diğer",
    pay_amount_by_gift_cards: "Ödeme Kartı Ödeme",
    select_payment_method:
      "Aşağıdaki seçeneklerden ödeme yönteminizi seçin.",
    payment_amount_remained: "Kalan ödeme bakiyesi",
    payment_amount: "ödenen miktar",
    all_payed_by_gift_cards:
      "Tebrikler, bu siparişi satın almak için daha fazla ödeme yapmanız gerekmeyecek. Hediye kartı ile ödeme tuşuna basın. ",
    pay_by_gift_cards_action: "Şarj kartı ile tam ödeme",

    order_free_payment: "Tebrikler, siparişiniz ücretsiz! ",
    order_free_payment_action: "Şimdi Ücretsiz Sipariş Edin",

    qr: {
      address: "fatura adresi",
      amount: "miktar",
    },
  },
  /** {@see DiscountField} **/
  discount_input: {
    limit: "{limit} {currency} değerine kadar {percent}% indirim",
    action: "İndirim Kodu Ekle",
    code_input: "İndirim kodu",
    notifications: {
      add_success: "Tebrikler, geçerli indirim kodu.",
    },
  },
  /** {@see GiftCard} **/
  gift_card: {
    inactive: "Kart devre dışı",
    expire: "sona erme",
    transfer: "Aktar",
    send_to_friend: "Arkadaşa gönder",
  },
  /** {@see CountDown} **/
  count_down: {
    days: "gün",
    hours: "saat",
    minutes: "dakika",
    seconds: "saniye",
  },
  /** {@see GiftStatus} **/
  gift_status: {
    Unpaid: "Makbuz Bekleniyor",
    Paid: "Paralı",
    Rejected: "Reddedildi",
    Canceled: "İptal edildi",
  },

  /** {@see GiftStProgramTypes} **/
  gift_program_status: {
    Airdrop: "Ödeme sistemi",
    Advertising: "reklam",
    PersonalGift: "Kişisel Hediye",
    ShopGift: "Hediye Dükkanı",
  },

  /** {@see CurrencySelector} **/
  currency_selector: {
    label: "Para birimi",
  },

  /** {@see NeedLoginDialog} **/
  need_login: {
    title: "Giriş yapmak",
    login_sms: "SMS Girişi",
    login_google: "Google ile giriş yap",
    login_facebook: "Facebook ile giriş",
    login_account: "Selldone ile giriş yapın",
    register: "Yeni kullanıcı mı? Şimdi kaydolun.",
    mobile_input: "Cep telefonunuzu girin",
    verification_code: "Doğrulama kodu",
    msg_title: "Merhaba,",
    msg_body: "Lütfen giriş yapın, birkaç saniyeden fazla sürmez.",
  },

  /** {@see ShopBadges} **/
  shop_badges: {
    GOLDEN_1YEAR: {
      name: "5 Yıl Altın Mağazası",
    },
    GOLDEN_2YEAR: {
      name: "4 Yıllık Altın Mağazası",
    },
    GOLDEN_3YEAR: {
      name: "3 Yıl Altın Mağazası",
    },
    GOLDEN_4YEAR: {
      name: "2 Yıllık Altın Mağazası",
    },
    GOLDEN_5YEAR: {
      name: "1 Yıl Altın Mağazası",
    },
    TOKEN_OWNER_1M: {
      name: "Altın Yatırımcı",
    },
    TOKEN_OWNER_10M: {
      name: "Elmas Yatırımcı",
    },
    TOKEN_OWNER_100M: {
      name: "Ruby Yatırımcı",
    },
    COMMUNITY_LOYAL: {
      name: "Üstün İletişim Ağları Topluluğu Üyesi",
    },
    GOLD_SUPPLIER: {
      name: "Altın Tedarikçisi",
    },
    GOLD_SELLER: {
      name: "Altın Satıcısı",
    },
    CONTENT_SUPERMAN: {
      name: "En İyi İçerik Üreticisi",
    },
    NINJA: {
      name: "ninja",
    },
    STAR: {
      name: "Yıldız",
    },
    GUARDIAN: {
      name: "Mükemmel Müşteri Hizmetleri",
    },
    KING: {
      name: "Pazarın Kralı",
    },
  },

  /** {@see CookieDialog} **/

  cookie: {
    title: "Bu web sitesi çerezleri kullanır",
    message:
      "Bu web sitesi, kullanıcı deneyimini geliştirmek için çerezleri kullanır. Web sitemizi kullanarak, Çerez Politikamız uyarınca tüm çerezlere izin vermiş olursunuz.",
    preferences_action: "Tercihleri Yönet",
    agree_action: "Kabul ediyorum",
  },
  /** {@see BasketItemUserMessageForm} **/
  basket_item_message: {
    title: "Bu öğe için gerekli bilgiler",
    save_actions: "Mesajı Kaydet",
    notifications: {
      success: "Giriş verileriniz kaydedildi.",
    },
  },
  /** {@see FAQ} **/
  faq: {
    faq: "Sıkça Sorulan Sorular",
    title: "Sorular ve cevaplar",
    sub_title: "Bizden ne yapmamızı istedin.",
    message:
      "Sorunuzun cevabını aşağıdaki cevaplar arasında arayınız. Soruların cevapsız kalıp kalmadığını bize sorun. ",
    add_question_action: "Yeni Soru Sor",
    read_more: "Daha fazla oku ..",
    load_more: "Daha çok soru ..",
    main_page: "SSS Ana Sayfası",
    add_new: "Yeni soru gönder",
    login_alert: "Soru sormak için giriş yapın.",
    question_input: "Soru",
    question_input_placeholder: "Yeni sorunuzu sorun.",
    notifications: {
      success_add: "Sorunuz başarıyla gönderildi.",
    },
  },

  /** {@see RatingInput} **/
  rating_labels: ["Çok kötü", "Kötü", "Normal", "İyi", "Mükemmel"],

  /** {@see MapView} **/
  map_view: {
    address_detail: "Adres detayları",
    change: "Değişiklik",
    select: "Seçme",
    not_found_address: "Değer bulunamadı",
    enter_address_hint: "Hedef adresi girin",
    enter_your_address: "Adresinizi girin.",
    postal_code: "Posta kodu",
    phone_input: "Telefon {type}",
    building_number: "Bina numarası",
    building_unit: "Birim",
    full_name_input: "Tam ad {type}",
    save_detail_action: "Ayrıntıları kaydet",
    more_detail_input: "Daha fazla açıklama",
    add_address_to_list: "Listeye adres ekleyin",
    address_title_input: "Adres etiketi (Gerekli)",
    notifications: {
      save_in_list:
        "Bu adres tüm detaylarıyla listenize kaydedildi.",
      edit_success: "{title} içine kaydedilen yeni adres değerleri.",
    },
    delete_address_dialog: {
      title: "Adresi Sil",
      message: "Bu adresi silmek istediğinizden emin misiniz?",
      action: "Adresi kaldır",
    },
  },

  /** {@see CommentsManager} **/
  comment_manager: {
    can_not_edit: "Bu yorum düzenlenemiyor!",
    comment_input_empty: "Mesaj metni boş!",
    article_not_saved: "Makaleyi kaydedin!",
  },

  /** {@see WheelOfFortune} **/
  wheel_fortune: {
    title: "Oyna ve kazan",
    message:
      "Her oyunun maliyeti 10 fiştir. Şu anda {chips} çipiniz var. Mağazadan satın alarak daha fazla chip kazanın.",
    win_message: "Tebrikler, kazandınız!",
    lost_message: "Üzgünüm, oyunu kaybettin.",
    try_again: "Tekrar deneyebilirsiniz",
  },
  /** {@see Calculator} **/
  calculator: {
    title: "Hesap makinesi başlığı",
    formula: "formül",
    variable_name: "Değişken ismi",
    variable_name_message:
      "Değişken adını girin ve formülünüzde kullanmak üzere ekleyin.",
    type: "Değişken tipi",
    variable_title: "Değişken başlığı",
    duplicate_var_name_error: "Aynı isimde değişken eklenemez!",
  },

  /** {@see StructuredData} **/
  json: {
    add: "Yapı verilerini ekle",
    add_message: "Yeni yapı verileri oluştur",
    structures: "Yapılar",
    book: {
      title: "Kitap",
      desc: "Kullanıcıların buldukları kitabı doğrudan Arama sonuçlarından satın almalarını sağlayan kitap işlemleri.",
    },
    occupation: {
      title: "Tahmini maaş",
      desc: "Google'da iş arama deneyiminde görüntülenen, iş türleri için maaş aralıkları ve bölge bazlı maaş ortalamaları gibi maaş tahminiyle ilgili bilgiler.",
    },
    course: {
      title: "Kurs",
      desc: "Sağlayıcıya özel bir listede görünen eğitim kursları. Kurslar, kurs başlığını, sağlayıcıyı ve kısa bir açıklamayı içerebilir.",
    },
    howto: {
      title: "Nasıl",
      desc: "Bir Nasıl Yapılır, bir görevi başarıyla tamamlamak için video, resim ve metin içeren bir dizi adım boyunca kullanıcılara yol gösterir.",
    },
    recipe: {
      title: "Yemek tarifi",
      desc: "Ayrı bir zengin sonuç veya ana makine karuselinin bir parçası olarak görüntülenen tarifler.",
    },
  },

  /** {@see SupportCategory} **/
  support: {
    Financial: "Parasal",
    Technical: "Teknik",
    Advisor: "danışman",
  },

  /** {@see ProductCondition} **/
  condition: {
    new: "Yeni",
    refurbished: "yenilenmiş",
    used: "Kullanılmış",
    used_fair: "İkinci el fuarı",
    used_good: "İyi kullanılmış",
    used_like_new: "Kullanılmış - Yeni Gibi",
  },

  /** @see VariantFilter **/
  variant_filter: {
    title: "Ürün Çeşit Filtresi",
    only_available: "Stokta var",
  },

  /** Service **/
  service: {
    task: {
      title: "Görevler",
      message: "Bu hizmette gerçekleştirilen görevlerin listesi.",
    },
    appointment: {
      title: "Randevu",
      message:
        "Haftanın saatlerini aşağıdaki saatlerden gün ve saate göre size uygun olanı seçin.",
    },
    booking: {
      title: "Rezervasyon",
      message:
        "Aşağıdaki takvimde rezervasyon yaptırmak istediğiniz günlerin zaman dilimini belirtin.",
    },
    subscription: {
      title: "abonelik",
    },
    charge: {
      title: "Şarj etmek",
    },
  },
  /** PricingTypes **/
  PricingTypes: {
    FIX: {
      title: "Sabit fiyatlandırma",
      message:
        "Bu fiyatlandırma türünde ürünün fiyatı sabit bir tutar olup alıcının fiyat hesaplama talebinde bulunmasına gerek yoktur.",
    },
    ESTIMATION: {
      title: "Tahmin Fiyatlandırma",
      message:
        "Mal ve hizmetlerin bedeli bir ölçüde satıcı tarafından sipariş verilirken hesaplanacak olup, ödeme faturaları hizmet sırasında değiştirilebilir veya eklenebilir.",
    },
    AGREEMENT: {
      title: "Anlaşma Fiyatlandırması",
      message:
        "Mal veya hizmetlerin nihai fiyatı, sipariş verildikten sonra satıcı tarafından değiştirilmeyecektir.",
    },
    BID: {
      title: "Teklif / Açık Artırma",
      message:
        "Ürün, potansiyel alıcılar tarafından en yüksek teklif fiyatına satılacaktır.",
    },
  },

  /** {@see App} {@see Shop} **/
  map: {
    title: "Malları almak için varış yeri",
    confirm: "Konumu ayarla",
    address: "Hedef",
    receptor: "alıcı",
  },

  /** {@see ShopBots} **/
  ShopBots: {
    telegram: "Telgraf",
  },

  /** {@see ArticleEditTags} **/
  article_tags: {
    title: "İçerik Etiketleri",
    tags_input: "Etiketler",
    tags_input_message: "Bu makalenin Etiketler Listesi",
    notification: {
      add_success: "Etiketler eklendi",
    },
  },
};
