export default {
  "currency_default": "USD",
  "language_default": "en",
  "selldone": "Селдон",
  "store": "кибет",
  "not_exist": "Notк",
  "error": "Хата",
  "active": "Актив",
  "inactive": "актив түгел",
  "required_value": "Кирәкле кыйммәтләр",
  "original_warranty": "Оригиналь продукт гарантиясе",
  "return_warranty_days": "{days} кире гарантия көне",
  "no_return_warranty": "Кайту юк",
  "reed_agree_terms": "Мин куллану шартларын һәм хосусыйлык политикасын укыдым һәм алар белән килешәм.",
  "commons": {
    "Currency": "Валюта",
    "COD": "COD",
    "State": "Дәүләт",
    "Price": "бәя",
    "order_price": "Заказ күләме",
    "VAT": "VAT",
    "Discount": "Ташлама",
    "In_Stock": "Барлыкта",
    "Variants": "Вариантлар",
    "No_variants": "Вариант юк",
    "all": "БАРЫ",
    "today": "Бүген",
    "yesterday": "Кичә",
    "license": "Лицензия",
    "home": "Өй",
    "support": "Ярдәм",
    "messages": "Хәбәрләр",
    "no_message": "Хәбәр юк",
    "empty": "Буш",
    "phone": "Телефон",
    "address": "адрес",
    "name": "Исем",
    "password": "Серсүз",
    "email": "Электрон почта",
    "mobile": "Мобиль",
    "login": "керергә",
    "register": "Теркәл",
    "select_account": "Хисапны сайлагыз",
    "online": "Онлайн",
    "offline": "Оффлайн",
    "finish": "Тәмам",
    "finished": "Тәмамланды",
    "preview": "Алдан карау",
    "free": "Түләүсез",
    "free_completely": "Бөтенләй бушлай язылу",
    "fee": "Түләү",
    "month": "Ай",
    "months": "Айлар",
    "faq": "Еш бирелә торган сораулар",
    "question": "Сорау",
    "answer": ".Авап",
    "create_date": "Дата яса",
    "update_date": "Яңарту датасы",
    "start_date": "Башлангыч көне",
    "end_date": "Ахыр датасы",
    "social": "Социаль",
    "total": "Барлыгы",
    "orders": "Заказлар",
    "sessions": "Сессияләр",
    "product_views": "Продукция күренеше",
    "add_to_carts": "Арбаларга өстәргә",
    "checkouts": "Тишерү",
    "payments": "Түләү",
    "organic_search": "Органик эзләү",
    "other": "Бүтәннәр",
    "landing_page": "Десант бите",
    "discount_code": "Ташлама коды",
    "total_sell": "Гомуми сатулар",
    "details": "Детальләр",
    "currency": "Валюта",
    "amount": "Күләм",
    "published": "Басылган",
    "draft": "Каралама",
    "save_changes": "Changesзгәрешләрне саклагыз",
    "source": "Чыганак",
    "medium": "Урта",
    "url": "Url",
    "revenue": "Керем",
    "performance": "Спектакль",
    "term": "Термин",
    "content": "Эчтәлек",
    "session": "Сессия",
    "product": "Продукция",
    "add": "Кушу",
    "checkout": "Тишерү",
    "payment": "Түләү",
    "more_options": "Күбрәк вариантлар",
    "full_name": "Тулы исем",
    "tel": "Тел",
    "about_me": "Минем турында",
    "request_checking": "Тикшерүне сорарга",
    "passport": "Паспорт",
    "birthday": "Туган көн",
    "country": "Ил",
    "city": "Шәһәр",
    "gender": "Гендер",
    "offer": "Тәкъдим итү",
    "website": "Вебсайт",
    "apply_for_all_products": "All Барлык продуктларга мөрәҗәгать итегез",
    "fix_commission": "Тикшерелгән комиссия",
    "percent_commission": "Процент комиссиясе",
    "fixed_discount": "Тикшерелгән ташлама",
    "discount_percentage": "Процент ташламасы",
    "discount_limit": "Ташлама чикләре",
    "no_code": "Код юк",
    "max_count": "Максималь санау",
    "count_unit": "Предметлар",
    "used": "Кулланыла",
    "daily": "Көн саен",
    "monthly": "Ай саен",
    "yearly": "Ел саен",
    "state": "Статус",
    "disable": "Сүндер",
    "enable": "Эшләтергә",
    "activation_code": "Активлаштыру коды",
    "quantity": "Сан",
    "no_club": "Клуб юк",
    "per_order": "Заказ буенча",
    "count": "Сана",
    "seconds": "Секундлар",
    "auto": "Авто",
    "title": "Титул",
    "message": "Хәбәр",
    "width": "Киңлек",
    "length": "Озынлык",
    "height": "Биеклек",
    "label": "Ярлык",
    "click": "Басыгыз",
    "bank": "Банк",
    "default": "Килешү",
    "role": "Роль",
    "user": "кулланучы",
    "users": "Кулланучылар",
    "code": "Код",
    "total_payment": "Гомуми түләү",
    "balance": "Баланс",
    "chance": "Шанс",
    "free_for_new_users": "Яңа кулланучылар өчен бушлай",
    "prize_amount": "Бүләк күләме",
    "win": ".Иңү",
    "gift_card": "Бүләк картасы",
    "discount": "Ташлама",
    "config": "Конфигурация",
    "prize": "Бүләк",
    "Prizes": "Бүләкләр",
    "result": "Нәтиҗә",
    "price": "бәя",
    "lottery": "Лотерея",
    "coupon": "Купон",
    "customer_club": "Клиентлар клубы",
    "shipping": "Юллау",
    "sum": "Сум",
    "not_paid": "Түләнми",
    "category": "Төркем",
    "done": "Булды",
    "email_from": "Кемнән",
    "subject": "Тема",
    "schedule": "Расписание",
    "files_list": "Файллар исемлеге",
    "file_max_size": "Максималь файл зурлыгы",
    "value": "Кыйммәт",
    "help": "Ярдәм итегез",
    "shipping_tax": "Сату салымы",
    "net_price": "Чиста бәя",
    "tax": "Салым",
    "tax_included": "Бәягә кертелгән",
    "limit": "Чик",
    "min_purchase": "Минималь сатып алу",
    "eligible_for": ".Әр сүзнең",
    "only_for_first_buy": "Беренче сатып алу өчен генә",
    "one_time_use": "Бер тапкыр куллана ала",
    "period_of_qualify": "Вакытлы куллану чикләре",
    "no_constraint": "Чик юк",
    "timespan": "Вакыт вакыты",
    "days": "Көн (көн)",
    "weight": "Авырлык",
    "distance": "Аралык",
    "last_status": "Соңгы статус",
    "issued_at": "Чыгарылган",
    "order": "Заказ",
    "order_detail": "Заказ детальләре",
    "percent": "процент",
    "applied_count": "Гамәли санау",
    "campaign": "Акция",
    "os": "Операцион система",
    "browser": "Браузер",
    "device": "Devайланма",
    "device_ip": "IPайланма IP адресы",
    "location": "Урын",
    "user_agent": "Кулланучы агент",
    "affiliate": "Килешү",
    "timeline": "Расписание",
    "add_note": "Искәрмә өстәгез",
    "record": "Язма",
    "unlimited": "Чикләнмәгән",
    "show_coupons": "Купоннарны күрсәт",
    "hide_coupons": "Купоннарны яшерегез",
    "service_area": "Хезмәт күрсәтү өлкәсе",
    "apps": "Кушымталар",
    "plugins": "Плагиннар",
    "bots": "Ботс",
    "categories": "Төркемнәр",
    "products": "Продукция",
    "business": "Бизнес",
    "personal": "Шәхси",
    "size": "Размер",
    "holiday": "Бәйрәм",
    "sod": "Тапшыруда түләгез",
    "cod": "Тапшыруда акча",
    "free_shipping": "Бушлай тапшыру",
    "hours": "Сәгать",
    "send_date": "Тапшыру датасы",
    "deliver_date": "Тапшыру вакыты",
    "return_date": "Кайту көне",
    "pending": "Көтелгән",
    "delivered": "Коткарылды",
    "returned": "Кайтты",
    "canceled": "Беркетелде",
    "shipping_cost": "Китерү бәясе",
    "action": "Эш",
    "cancel_date": "Датаны кире кагу",
    "deliver_in_process": "Заказ җибәрелә ..",
    "kind": "Тип",
    "detail": "Детальләр",
    "map": "Карта",
    "actions": "Эшләр",
    "navigation": "Навигация",
    "navigation_app": "Кушымта",
    "payment_date": "Түләү вакыты",
    "duration": "Озынлыгы",
    "bill": "Билл",
    "delivery_persons": "Курьерлар",
    "delivery_services": "Тапшыру хезмәтләре",
    "live_view": "Тере күренеш",
    "cart": "Арба",
    "priority": "Приоритет",
    "sufficient_credit": "Кредит җитәрлек",
    "max_package_size": "Пакетның максималь күләме",
    "delay": "Соңга калу",
    "credit": "Кредит",
    "livemode": "Тере",
    "paused": "Пауза",
    "debug": "Чишү",
    "token": "Токен",
    "status": "Статус",
    "courier": "Курьер",
    "track": "Трек",
    "track_order": "Заказны күзәтү",
    "cost": "Бәясе",
    "receipt": "Квитанция",
    "origin": "Чыгыш",
    "destination": "Максат",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "Акция җитми!",
    "sub_total": "Субтотал",
    "customer": "Клиент",
    "delivery": "Тапшыру",
    "online_orders": "Онлайн заказлар",
    "pos_orders": "POS заказлары",
    "chips": "Чипс",
    "subscribed": "Подписка",
    "unsubscribed": "Язылмаган",
    "last_login": "Соңгы логин",
    "join_at": "Датага кушылыгыз",
    "club": "Клуб",
    "buyer": "Сатып алучы",
    "seller": "Сатучы",
    "or": "Яисә",
    "type": "Тип",
    "condition": "Шарт",
    "brand": "Бренд",
    "attempt": "Омтылыш",
    "error": "Хата",
    "success": "Уңыш",
    "fail": "Уңышсызлык",
    "inventory": "Инвентаризация",
    "link": "Ссылка",
    "visits": "Визит",
    "transactions": "Транзакцияләр",
    "vat": "VAT",
    "pos_vat": "НДС",
    "sort_by": "Карата төрлә..",
    "from": "Кемнән",
    "from_lead_time": "Киләсе {hours} сәгать эчендә",
    "no_credit_card_info": "Карточка турында мәгълүмат юк!",
    "active": "Актив",
    "not_active": "Актив түгел!",
    "referrals": "Ferлламалар",
    "dashboard": "Такталар",
    "more": "Тулырак",
    "inactive": "актив түгел",
    "developer": "Төзүче",
    "setting": "Көйләү",
    "membership_conditions": "Әгъзалык шартлары",
    "customers": "Клиентлар",
    "created_at": "Ясалган дата",
    "updated_at": "Соңгы яңарту",
    "register_at": "Теркәлү датасы",
    "old": "Иске",
    "new": "Яңа",
    "start": "Башлау",
    "end": "Ахыр",
    "pos": "POS",
    "out_of_stock": "Складта юк",
    "fake": "Ялган",
    "low_inventory_warning": "Игътибар, түбән инвентаризация!",
    "webhook": "Вебхок",
    "notification": "Хәбәрләр",
    "sms": "SMS",
    "online_payment_link": "Онлайн түләү сылтамасы",
    "waiting_load_data": "Мәгълүматны йөкләүне көтү ..",
    "views": "Күрү",
    "sales": "Сату",
    "total_views": "Гомуми күренешләр",
    "total_sales": "Гомуми сатулар",
    "from_previous_n_days": "Соңгы {көннәрдән",
    "drop_shipping": "Тамчы",
    "commission": "Комиссия",
    "shipping_area": "Тапшыру өлкәсе",
    "main_seller": "Төп сатучы",
    "domain": "Домен",
    "contact": "Контакт өчен мәгълүмат",
    "wallet": "Капчык",
    "reseller": "Сатучы",
    "tracking_code": "Күзәтү коды",
    "tracking_url": "Күзәтү URL",
    "fulfillments": "Уңышлар",
    "reject": "Баш тарту",
    "reserved": "Сакланган",
    "score": "Хисап",
    "customer_price": "Клиент бәясе",
    "options": "Вариантлар",
    "show_details": "Детальләрне күрсәт",
    "no_data": "Мәгълүмат юк ..",
    "waiting": "Көтү ...",
    "waiting_connecting_payment": "Түләү хезмәтен көтү ...",
    "creating_secure_payment": "Куркынычсыз түләү булдыру.",
    "officer": "Офицер",
    "ticket": "Билет",
    "ticket_url": "Билет урл",
    "closed_at": "Ябык",
    "close_ticket": "Билетны ябу",
    "reopen_ticket": "Билетны ачу",
    "require": "Таләп *",
    "search": "Эзләү ...",
    "language": "Тел",
    "tasks": "Биремнәр",
    "permissions": "Рөхсәт",
    "finish_date": "Ахыр датасы",
    "complete_date": "Тәмамлау Датасы",
    "settle_date": "Урнаштыру датасы",
    "cost_span": "Бәяләр диапазоны",
    "industry": "Сәнәгать",
    "rating": "Рейтинглар",
    "rates": "Рейтинг",
    "seen_at": "Күрде",
    "completed": "Тәмамланды",
    "you": "Син",
    "shop": "Кибет",
    "store": "кибет",
    "granted": "Дөрес",
    "deny": "Инкарь",
    "request": "Сорау",
    "expert": "Эксперт",
    "response": "Onseавап",
    "requests": "Сораулар",
    "experts": "Белгечләр",
    "responses": ".Аваплар",
    "negotiations": "Сөйләшүләр",
    "all_chats": "Барлык чатлар",
    "chats": "Чатлар",
    "tags": "Теги",
    "description": "Тасвирлау",
    "rates_count": "Рейтинглар саны",
    "rate": "Рейтинг",
    "comment": "Аңлатма",
    "chat": "Чат",
    "install": "Урнаштыру",
    "edited": "Редакцияләнгән",
    "undo": "Кире кайтару",
    "redo": "Кабатлау",
    "male": "Ир-ат",
    "female": "Хатын-кыз",
    "calculator": "Калькулятор",
    "catalog": "Каталог",
    "max_height": "Максималь биеклек",
    "images_compare": "Рәсемнәрне чагыштыру",
    "canvas": "Кант",
    "table_of_contents": "Эчтәлек",
    "comments": "Аңлатмалар",
    "badge_codes": "Бейджлар коды",
    "need_more": "Күбрәк кирәкме?",
    "invite_glow_caption": "Friendәр дустыгыз өчен 14,9 $ алыгыз!",
    "register_free": "100% бушлай реестр",
    "gift": "Бүләк",
    "google": "Google",
    "facebook": "Facebook",
    "instagram": "Инстаграм",
    "instashop": "Инсташоп",
    "show": "Шоу",
    "hide": "Яшер",
    "waiting_review": "Кабатлау",
    "not_selected": "Сайланмаган",
    "time": "Вакыт",
    "final_price": "Соңгы бәя",
    "starting_price": "Башлангыч бәя",
    "day": "Көн",
    "paid": "Түләүле",
    "service_bill": "Фактура түләү",
    "avocado": "Авокадо",
    "delivery_price": "Китерү бәясе",
    "select_address": "Адресны сайлагыз",
    "image": "Рәсем",
    "view": "Күрү",
    "sell": "Сату",
    "hyper": "Гипер",
    "cart_list": "Арба",
    "barcode_scanner": "Штрих-код сканеры",
    "scan_qr_code": "QR кодны сканерлау",
    "new_carts": "Яңа арбалар",
    "pays": "Түләү",
    "annually": "Ел саен",
    "sells": "Сату",
    "articles": "Мәкаләләр",
    "jobs": "Эш урыннары",
    "job": "Эш",
    "blog": "Блог",
    "deleted_at": "Бетерелгән",
    "capacity": "Потенциал",
    "download_at": "Соңгы йөкләү датасы",
    "downloads": "Йөкләүләр",
    "usage": "Куллану",
    "select_upload_file": "Файлны сайлагыз яки ташлагыз",
    "download_link": "Ссылканы йөкләү",
    "uploading": "Йөкләү ..",
    "files": "Файллар",
    "star": "Йолдыз",
    "speed": "Тизлек",
    "feedback": "Фикер алышу",
    "new_messages": "Яңа хәбәрләр",
    "file": "Файл",
    "attachment": "Кушымта",
    "gallery": "Галерея",
    "sync": "Синхронизация",
    "diff_time": "Вакыт аермасы",
    "network": "Челтәр",
    "account": "Хисап",
    "configuration": "Конфигурация",
    "blockchain": "Блокчейн",
    "blog_link": "Блог сылтамасы",
    "community": "Communityәмгыять",
    "critical_zone": "Критик зона",
    "statistics": "Статистика",
    "access": "Рөхсәт",
    "seo": "SEO",
    "followers": "Ияртүчеләр",
    "followings": "Ияртүләр",
    "private": "Алдан карау",
    "soon": "Тиздән",
    "features": "Үзенчәлекләр",
    "bot": "Бот",
    "sample": "Ampleрнәк",
    "how_it_work": "Бу ничек эшли?",
    "page": "Бит",
    "congratulations": "Котлыйбыз",
    "recommend": "Тәкъдим итегез",
    "recommended": "Тәкъдим ителә",
    "recoms": "Тәкъдимнәр",
    "likes": "Яраталар",
    "clicks": "Басу",
    "platform": "Платформа",
    "cms": "CMS",
    "cash": "Акча",
    "dir_payment": "банк күчерүе",
    "auto_complete": "Авто тулы",
    "compare": "Чагыштырыгыз",
    "infinite": "Чиксез",
    "tips": "Киңәшләр",
    "technical": "Техник",
    "finance": "Финанс",
    "your_phone_input": "Телефон номерын кертегез",
    "income": "Керем",
    "change": "Changeзгәреш",
    "new_users": "Яңа кулланучылар",
    "success_orders": "Уңышлы заказлар",
    "direct": "Туры",
    "last_activity": "Соңгы эшчәнлек",
    "landing": "Десант",
    "now": "Хәзер",
    "accept_agreement": "Мин шартларны укыдым һәм кабул иттем.",
    "report": "Доклад",
    "tablet": "Планшет",
    "pc": "PC",
    "acquisition_channel": "Сатып алу каналы",
    "to": "Toәр сүзнең",
    "info": "Мәгълүмат",
    "general": "Генерал",
    "upload": "Йөкләү",
    "general_config": "Гомуми конфигурация",
    "limits_config": "Чикләүләр",
    "design_config": "Дизайн һәм стиль",
    "duration_config": "Озынлык чикләре",
    "constraints_config": "Хокук чикләре",
    "clubs_config": "Клубларда бар",
    "additional_config": "Өстәмә конфигурацияләр",
    "import": "Импорт",
    "ribbon": "Тасма",
    "countries": "Илләр",
    "edit": "Редакцияләү",
    "delete": "Бетерү",
    "analytics": "Аналитика",
    "rules": "Кагыйдәләр",
    "unset": "Көтелмәгән",
    "carts": "Арбалар",
    "optional": "Ихтыярсыз",
    "design": "Дизайн",
    "filter": "Фильтр",
    "send": "Ибәр",
    "approved": "Расланган",
    "unit": "Берәмлек",
    "profile": "профиль",
    "shipping_rates": "Тапшыру ставкалары",
    "package": "Пакет",
    "overview": "Гомуми күзәтү",
    "live": "Тере",
    "never": "Беркайчан да",
    "always": "Waysәрвакыт",
    "mandatory": "Мәҗбүри",
    "expire_at": "Гамәлдән чыгу көне",
    "position": "Позиция",
    "channel": "Канал",
    "age": "Яшь",
    "charge": "Түләү",
    "giftcard": "Бүләк картасы",
    "acquisition": "Сату",
    "conversion": "Конверсия",
    "total_payments": "Гомуми түләүләр",
    "community_ask": "Communityәмгыятьтә сора",
    "children": "Балалар",
    "export": "Экспорт",
    "list": "Исемлек",
    "hierarchy": "Иерархия",
    "images": "Рәсемнәр",
    "demo": "Демо",
    "author": "Автор",
    "designer": "Дизайнер",
    "max": "Максимум",
    "accepted": "Кабул ителде",
    "reply": "Lyавап бир",
    "reviewed": "Кабатланды",
    "restored": "Реставрация",
    "merchant": "Сәүдәгәр",
    "per_product": "Бер продукт өчен",
    "journey": "Сәяхәт",
    "after": "Соңыннан",
    "waiting_for_payment": "Зинһар, түләүне тәмамлагыз ...",
    "hour": "Сәгать",
    "minute": "Минут",
    "premium": "Премиум",
    "light": "Яктылык",
    "dark": "Караңгы",
    "guest": "Кунак",
    "shops": "Кибетләр",
    "vendor": "Сатучы",
    "vendors": "Сатучылар",
    "marketplace": "Базар",
    "verify_date": "Датаны раслагыз",
    "note": "Тамга",
    "panel": "Панель",
    "removed": "Чыгарылды",
    "segments": "Сегментлар",
    "personal_info": "Шәхси мәгълүмат",
    "preferences": "Сайлаулар",
    "spec": "Спек",
    "reviews": "Карап чыгу",
    "constraints": "Чикләүләр",
    "flexible": "Эчкерсез",
    "usage_limit": "Куллану чикләре",
    "temporary": "Вакытлыча",
    "original": "Оригиналь",
    "saved": "Коткарылды!",
    "sort": "Сортлау",
    "documents": "Документлар",
    "document": "Документ",
    "please_wait": "Зинһар, көтегез...",
    "pickup": "Сайлап алу",
    "customize": "көйләү",
    "difficulty": "Авырлык",
    "banned": "Тыйган",
    "company": "Компания",
    "tax_shipping": "Сату салымы",
    "warranty": "Гарантия",
    "return_policy": "Кайтару сәясәте",
    "guide": "Белешмәлек",
    "translate": "Тәрҗемә итү",
    "public": "Халык",
    "deleted": "Бетерелгән",
    "variant": "Вариант",
    "secure": "Куркынычсыз",
    "admin": "Админ"
  },
  "dialogs": {
    "delete": {
      "title": "Бетерү",
      "message": "Сез бу әйберне бетерергә ышанасызмы?",
      "action": "Әйе, хәзер бетерегез"
    }
  },
  "actions": {
    "add_to_cart": "Кәрзингә өстә",
    "cancel": "Баш тарту",
    "update": "Яңарту",
    "add": "Кушу",
    "delete": "Бетерү",
    "new": "Яңа",
    "save_continue": "Саклагыз һәм дәвам итегез",
    "save": "Саклагыз",
    "save_changes": "Changesзгәрешләрне саклагыз",
    "change": "Changeзгәреш",
    "continue": "Дәвам итегез",
    "close": "Ябу",
    "finish": "Тәмам",
    "poll": "Сораштыру",
    "view": "Күрү",
    "edit": "Редакцияләү",
    "next": "Чираттагы",
    "previous": "Алдагы",
    "create": "Ярат",
    "set": "көйләү",
    "find": "Табыгыз",
    "accept": "Кабул ит",
    "reject": "Баш тарту",
    "back": "Кире",
    "pay": "Түләү",
    "pay_now": "Хәзер түләгез",
    "print": "Басма",
    "return": "Кайту",
    "publish": "Бастыру",
    "confirm": "Ышандыр",
    "copy": "Күчереп алу",
    "submit": "Тапшыр",
    "send": "Ибәр",
    "yes": "Әйе",
    "no": "юк",
    "meh": "Хм",
    "clear": "Чиста",
    "dismiss": "Эштән чыгару",
    "search": "Эзләү",
    "deselect_all": "Барысын да сайлагыз",
    "select_all": "Барысын да сайлагыз",
    "refresh": "Яңарту",
    "verify": "Тикшерегез",
    "play": "Уйна",
    "open": "Ачык",
    "calculate": "Санагыз",
    "quick_buy": "Тиз сатып алу",
    "click_here": "Монда басыгыз",
    "schedule": "Расписание",
    "send_now": "Хәзер җибәр",
    "download": "Йөкләү",
    "reset_default": "Килешү буенча кире кайтару",
    "reset": "Бетерү",
    "check": "Тикшерегез",
    "cod_payment": "Тапшыруда акча",
    "dir_payment": "Акча күчерү",
    "online_payment": "Онлайн түләү",
    "checkout": "Тишерү",
    "show_all": "Барысын да күрсәт",
    "login": "керергә",
    "logout": "Чыгарга",
    "more": "Тулырак..",
    "collapse": "Apseимерелү",
    "apply_change": "Changesзгәрешләр кулланыгыз",
    "apply": "Кулланыгыз",
    "add_giftcard": "Бүләк картасын өстәгез",
    "charge": "Түләү",
    "send_invites": "Чакырулар җибәрегез",
    "past": "Pastткән",
    "restore": "Реставрация",
    "cut": "Кис",
    "get_sms_code": "Аутентификация кодын алыгыз",
    "register_no_mail": "Электрон почтасыз дәвам итегез",
    "no_mail_register_message": "Электрон почта адресыгыз юкмы яки серсүзегезне оныттыгызмы?",
    "reset_by_mail": "Электрон почта аша серсүзне торгызу",
    "reset_by_sms": "SMS аша серсүзне торгызу",
    "cash_payment": "Акча түләү",
    "show_chart": "Графикны күрсәт",
    "open_app": "Кушымта ачу",
    "login_now": "Хәзер керегез",
    "watch_video": "Видео карау",
    "check_now": "Хәзер тикшерегез",
    "remove_image": "Рәсемне бетерегез",
    "view_website": "Ачык сылтама",
    "explore": "{Исем белән танышу",
    "go": "Бар",
    "read_more": "Күбрәк укы",
    "start_now": "Хәзер башлау - бушлай",
    "view_live": "Тере карау",
    "resend_code": "Кодны җибәрү",
    "invite": "Чакырыгыз",
    "add_more": "Күбрәк өстәгез",
    "install_now": "Хәзер урнаштырыгыз",
    "uninstall": "Бетерү",
    "show_preview": "Алдан карау",
    "hide_preview": "Алдан карау",
    "download_now": "Хәзер йөкләү",
    "auto_fill": "Автофилл",
    "track": "Трек",
    "change_state": "Статусны үзгәртү",
    "done": "Булды",
    "reply": "Lyавап бир",
    "watch_now": "Хәзер карагыз",
    "unlock": "Блокны ачу",
    "lock": "Блок",
    "create_clone": "Клон ясагыз",
    "regenerate": "Яңарту",
    "add_message": "Хәбәр өстәгез",
    "continue_chat": "Чатны дәвам итегез",
    "add_new_message": "Яңа хәбәр өстәгез"
  },
  "instance_message_title": "Тиз хәбәр җибәр",
  "instance_message": "Сәлам {name}, Минем исемем {author} {company}.",
  "errors": {
    "419": "Сез озак вакыт актив булмагансыз, зинһар, куркынычсызлык сәбәпләреннән <b>БЕТНЕ ЯРАТЫГЫЗ</b> .",
    "gateway_blockchain_sync_error": "Система блокчейн белән синхронлашмый. Безнең серверларның синхронизациясе беткәнче яңа транзакция булдыру мөмкин булмаячак. Без проблеманы чишәбез.",
    "gateway_network_error": "Түләү шлюз хезмәте аралашу проблемасына юлыкты."
  },
  "receiver_info": {
    "map": {
      "title": "Тапшыру адресы",
      "confirm": "Урын куегыз",
      "address_type": "Максат",
      "receptor_type": "Алучы"
    },
    "receiver_address": "Тапшыру адресын сайлагыз",
    "address": "адрес",
    "postcode": "Почта индексы",
    "enter_value": "Монда тутырыгыз",
    "address_note": "Тамга",
    "tel": "Контакт номеры",
    "service_address": "Сезнең адресны сайлагыз"
  },
  "weight": {
    "g": "g",
    "oz": "oz",
    "lb": "lb",
    "kg": "кг"
  },
  "mass_unit_name": {
    "g": "грамм",
    "oz": "Ounce",
    "lb": "Фунт",
    "kg": "килограмм"
  },
  "length": {
    "cm": "см",
    "in": "эчендә",
    "ft": "ft",
    "mm": "мм",
    "m": "м",
    "yd": "yd"
  },
  "size_unit_name": {
    "cm": "Сантиметр",
    "in": "Инч",
    "ft": "Аяк",
    "mm": "миллиметр",
    "m": "метр",
    "yd": "Ишегалды"
  },
  "distance": {
    "m": "метр",
    "km": "км"
  },
  "time": {
    "days": "Көннәр",
    "hours": "Сәгать",
    "minutes": "Минутлар",
    "seconds": "Секундлар"
  },
  "units": [
    "Берәмлек",
    "пункт",
    "һәрберсе",
    "көйләү",
    "кисәк",
    "килограмм",
    "грамм",
    "миллилограм",
    "метр",
    "миллиметр",
    "квадрат метр",
    "квадрат метр",
    "куб метр",
    "литр",
    "миллилитр",
    "аяк",
    "галлон",
    "дюйм",
    "унция",
    "фунт",
    "кварталлар",
    "ишегалды",
    "бүлмә",
    "секунд",
    "минут",
    "сәгатьләр",
    "көннәр",
    "атналар",
    "айлар",
    "еллар"
  ],
  "region_types": {
    "State": "Дәүләт",
    "Territory": "Территория",
    "Province": "Өлкә"
  },
  "transaction_status": {
    "RequireAction": "Эш кирәк",
    "Processing": "Эшкәртү",
    "Canceled": "Беркетелде",
    "Succeeded": "Уңышка иреште"
  },
  "placeholders": {
    "name": "Джон Кокс",
    "email": "your-mail@mail.com",
    "phone": "+1 000 0000",
    "language": "Телне сайлагыз ..",
    "friend_email": "Дустыңның электрон почтасы ...",
    "friend_name": "Оп. Дустыңның исеме",
    "select_date": "Датаны сайлагыз ..."
  },
  "notification": {
    "confirm": "Ышандыр",
    "confirm_message": "Changesзгәрешләр уңышлы сакланды.",
    "error": "Хата",
    "message": "Хәбәр",
    "caution": "Сак булыгыз",
    "warning": "Кисәтү",
    "award": "Котлыйбыз",
    "error_message": "Кызганычка каршы, хата килеп чыкты.",
    "congratulation": "Котлыйбыз",
    "coming_soon": "Тиздән",
    "on_fetching_data": "Мәгълүмат алу ..",
    "new_pwa_version": "Яңа версия хәзер бар. Кушымтаны яңартырга телисезме?",
    "over_license_limit": "Лицензия чикләре өстендә",
    "update_license": "Лицензияне яңарту",
    "required": "Кирәк",
    "invalid_email": "Электрон почта дөрес түгел",
    "invalid_domain": "Домен дөрес түгел",
    "invalid_min_length": "Минималь озынлык {озынлык булырга тиеш",
    "invalid_min_array_length": "Ким дигәндә {length} әйберләрен сайлагыз",
    "invalid_max_chars": "Макс {maxCount} символлары",
    "invalid_url": "Яраксыз URL",
    "country_invalid": "Барган илне сайлагыз!",
    "postal_code_invalid": "Почта индексын куегыз!"
  },
  "colors": {
    "#D32F2F": "Кызыл",
    "#C2185B": "Алсу",
    "#7B1FA2": "Гурпа",
    "#512DA8": "Кара куе кызыл",
    "#303F9F": "Индиго Зәңгәр",
    "#1976D2": "Зәңгәр",
    "#0288D1": "Зәңгәрсу зәңгәр",
    "#0097A7": "Турция зәңгәр",
    "#00796B": "Каз яшел",
    "#388E3C": "Яшел",
    "#689F38": "Сыек яшел",
    "#AFB42B": "Лимо",
    "#FBC02D": "Сары",
    "#FFA000": "Эмбер",
    "#F57C00": "әфлисун",
    "#E64A19": "Ялтырап торган апельсин",
    "#5D4037": "Браун",
    "#616161": "Соры",
    "#455A64": "Соры зәңгәр",
    "#FFD700": "Алтын",
    "#C0C0C0": "Көмеш",
    "#b76e79": "Алтын Роза",
    "#383838": "Кара кара",
    "#FFFFFF": "Белый",
    "#FFF": "Белый",
    "#000000": "Кара",
    "#000": "Кара",
    "#7d263a": "Марон",
    "#FD9F17": "Алтын",
    "#229DBF": "Аква",
    "#6DC9E2": "Aqua Triblend",
    "#413B2D": "Армия",
    "#474747": "Асфальт",
    "#E6195C": "Берри",
    "#B2184C": "Берри Трибленд",
    "#FC7F5F": "Яндырылган апельсин",
    "#80011F": "Кардинал",
    "#382829": "Шоколад",
    "#F06336": "Корал",
    "#FAE7C9": "Каймак",
    "#6B2257": "Карагат",
    "#222127": "Кара соры",
    "#0D5A74": "Тирән чәй",
    "#00582F": "Мәңге яшел",
    "#214C30": "Урман",
    "#DC2867": "Фуксия",
    "#38561F" :"Келли",
    "#5C884D": "Яфрак",
    "#558450": "Lightиңел аквап",
    "#96B5C9": "Зәңгәрсу зәңгәр",
    "#DCAFCE": "Сирень",
    "#D3E1A4": "Лайм",
    "#9DE7C2": "Ясалма",
    "#F6EAD2": "Табигый",
    "#1A1F35": "Хәрби-диңгез флоты",
    "#404624": "Зәйтүнә",
    "#271020": "Караҗимеш",
    "#A8355C": "Кура җиләге",
    "#D6BEA6": "Йомшак каймак",
    "#BEA994": "Тан",
    "#0DB2AE": "Чәй",
    "#A86EA9": "Виолет",
    "#36454F": "Көмер",
    "#b3b0ab": "углерод соры",
    "#463e3d": "Көмер Хезер",
    "#282d3c": "Флот Блэйзер"
  },
  "address_info": {
    "name": "Исем",
    "tel": "Телефон",
    "email": "Электрон почта",
    "country": "Ил",
    "city": "Шәһәр",
    "state": "Дәүләт",
    "address": "адрес",
    "building_number": "Төзелеш номеры",
    "building_unit": "Берәмлек",
    "postcode": "Почта индексы",
    "note": "Тамга",
    "county": "Район"
  },
  "product_types": {
    "physical": "Физик",
    "physical_description": "Физик продуктлар: кесә телефоннары, китаплар, электрон компонентлар.",
    "virtual": "Виртуаль",
    "virtual_description": "Интернетка файдалы продуктлар: тулыландыру картасы, отельне броньлау, уенны тулыландыру.",
    "file": "Файл",
    "file_description": "Онлайн курс видео, йөкләнә торган документлар кебек барлык рөхсәт ителгән файллар.",
    "service": "Хезмәт",
    "service_description": "Хезмәтләр: ремонт, транспорт, укыту."
  },
  "license": {
    "free": "Түләүсез",
    "startup": "Башларга",
    "company": "Компания",
    "enterprise": "Предприятие"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "Томан",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW",
    "GHS": "GHS",
    "ZWD": "ZWD",
    "IQD": "IQD",
    "SYP": "SYP"
  },
  "variants": {
    "color": "Төс",
    "volume": "Размер",
    "count_in_pack": "Пакетта санагыз",
    "weight": "Авырлык",
    "type": "Материал",
    "style": "Стиль"
  },
  "delivery_state": {
    "check_queue": "Кабатлау",
    "order_confirm": "Заказны раслау",
    "preparing_order": "Әзерлек",
    "sent_order": "Тапшыруда",
    "to_customer": "Коткарылды"
  },
  "status": {
    "unpaid": "Түләнмәгән",
    "paid": "Түләүле",
    "canceled": "Беркетелде",
    "completed": "Урнаштырылган",
    "reserved": "Сакланган",
    "COD": "COD",
    "sold": "Сатылды",
    "open": "Ачык",
    "cancel": "Беркетелде",
    "active": "Актив",
    "inactive": "актив түгел",
    "debug": "Чишү",
    "live": "Тере",
    "test": "Тест",
    "connected": "Бәйләнгән",
    "disconnected": "Аерылган",
    "accept": "Кабул ит",
    "reject": "Баш тарту",
    "pending": "Көтелгән",
    "rejected": "Кире кагылды",
    "accepted": "Кабул ителде"
  },
  "dimensions": {
    "cm": "см",
    "km": "км",
    "kg": "кг"
  },
  "transportation_type": {
    "motorbike": "Мотоцикл",
    "motorbike_description": "Берничә километр эчендә уртача авырлык.",
    "cargo_small": "Кечкенә йөк",
    "cargo_small_description": "Күп километрлы җиңел йөк.",
    "cargo": "Йөк",
    "cargo_description": "Берничә километр эчендә уртача авырлык.",
    "truck": "Йөк машинасы",
    "truck_description": "Ил эчендә күпчелек яки авыр йөк.",
    "fast_post": "Тиз язма",
    "fast_post_description": "Почта бүлеге аша тиз урнаштыру.",
    "post": "Нормаль язма",
    "post_description": "Почта бүлеге аша регуляр почта.",
    "airplane": "Авиакомпания",
    "airplane_description": "Эчке һәм чит ил җиңел һәм урта йөк.",
    "bicycle": "Чиста җибәрү",
    "bicycle_description": "Автомобиль булмаган машиналарның берничә йөз яртысында җиңел йөк.",
    "global": "Глобаль транспорт",
    "global_description": "Чит илләргә һава, диңгез яки коры юл белән җибәрү.",
    "pickup": "Сайлап алу",
    "pickup_description": "Клиентлар әйберләрне сезнең физик кибетегездә яки складта алалар."
  },
  "article": {
    "login_to_see_error": "Мәкаләгә керү өчен керегез",
    "create_new_action": "Яңа эчтәлек булдыру",
    "menu_title": "Меню",
    "menu": {
      "edit": "Редакцияләү",
      "view_mode": "Тәртипне карау",
      "delete": "Мәкаләне бетерү"
    },
    "schedule_action": "Сез бастыруны расларга телисезме?",
    "schedule_title": "Авто-бастыру расписаниесе",
    "edit_mode": "Редакцияләү",
    "public_view_mode": "Иҗтимагый күренеш",
    "publish_at": "Басыгыз",
    "published": "Басылган",
    "draft": "Каралама",
    "saving": "Саклау",
    "save_and_publish_action": "Саклагыз һәм бастырыгыз",
    "save_draft_action": "Саклауны саклагыз",
    "private": "Шәхси",
    "public": "Халык",
    "category_input": "Төркем",
    "category_input_message": "Мәкалә категориясен сайлагыз",
    "parent_input": "Ата-аналар категориясе",
    "parent_input_message": "Ата эчтәлеген сайлагыз",
    "schedule_input": "Расписание",
    "schedule_input_placeholder": "Әгәр дә сез хикәянең билгеле бер вакытта бастырылуын телисез икән.",
    "schedule_view_action": "Расписание карау",
    "author_title": "Авторы",
    "read_time": "Уку вакыты",
    "read_time_unit": "Минутлар",
    "claps_action": "Алкышлар",
    "claps": "Алкышлар",
    "likes": "Кебек",
    "about_author": "Автор турында",
    "updated_at": "Яңартылды",
    "wrote_at": "Язылган",
    "now": "Хәзер",
    "follow_action": "Ияртегез",
    "followed": "Иярчен",
    "report_and_delete_action": "Бу мәкаләне хәбәр итегез һәм бетерегез",
    "report_action": "Хыянәт турында хәбәр итү",
    "you_reported_this_article": "Бу мәкаләдә хокук бозулар турында отчет бар.",
    "add_to_publication_action": "Басмага өстәргә",
    "author_socials": "Социаль медиада автор",
    "share": "Бүлешү",
    "report_dialog": {
      "report_and_delete_title": "Хокук бозулар турында хәбәр итегез һәм эчтәлекне бетерегез",
      "report_title": "Бу эчтәлекне мыскыллаучы дип хәбәр итегез",
      "message": "Бу эчтәлекне җибәрүнең сәбәбе нинди? Түбәндәге вариантларның берсен сайлагыз.",
      "accept_and_delete_action": "Эчтәлекне раслау һәм бетерү"
    },
    "schedule_dialog": {
      "title": "Эчтәлек чыгару графигы",
      "publish_at": "Басыгыз",
      "last_edit": "Соңгы редакция",
      "view_action": "Мәкаләне карау"
    },
    "notifications": {
      "update_success_title": "Мәгълүмат тапшыру",
      "update_success": "Мәкалә уңышлы яңартылды.",
      "update_error": "Керелгән мәгълүмат дөрес түгел.",
      "delete_error": "Сез бу мәкаләне бетерә алмыйсыз!",
      "report_and_delete_success_title": "Доклад һәм бетерү",
      "report_and_delete_success_message": "Мәкәлә уңышлы бетерелде.",
      "report_success_title": "Доклад мәкаләсе",
      "report_success_message": "Бу мәкалә турында сезнең доклад урнаштырылган."
    },
    "alert": {
      "delete_article": {
        "title": "Мәкаләне бетерү",
        "message": "Сез бу мәкаләне мәңгегә бетерергә телисезме?",
        "action": "Бетерү"
      }
    },
    "edit_window": {
      "title": "Рәсем текстын һәм кыскача мәгълүматны сайлагыз",
      "digest": "Аннотация"
    },
    "editor": {
      "title_placeholder": "Титул ..",
      "body_placeholder": "Зур эчтәлек языгыз ..",
      "accept_file_types_error": "Бу файл форматы кабул ителми:",
      "max_file_size_error": "Бу файл бик зур:",
      "notifications": {
        "image_uploaded_success": "Рәсем уңышлы сакланган",
        "image_uploaded_failed": "Рәсемне йөкләүдә хата."
      },
      "embed_placeholder": "Iframe кодын, Facebook, Youtube яки бүтән URL кертегез һәм Enter төймәсенә басыгыз.",
      "embed_caption_placeholder": "Титул кертегез (өстәмә)",
      "images_caption_placeholder": "Бу рәсем өчен исем кертегез .."
    }
  },
  "article_report": {
    "inappropriate": "Бу мәкаләнең эчтәлеге урынсыз.",
    "fake": "Бу ялган һәм алдаучы.",
    "spam": "Бу әйбер спам белән күчерелгән.",
    "scam": "Бу зарарлы программа, вирус яки система җимерелүенә китерергә мөмкин.",
    "hacked": "Бу сайт хакерланган кебек.",
    "offensive": "Телнең эчтәлеге һәм сүз байлыгы этика һәм хөрмәтсезлек.",
    "violent": "Бу эчтәлектә порнография бар һәм законнарны боза дип уйлыйм.",
    "harassment": "Бу расист дип уйлыйм.",
    "hate": "Минемчә, бу көч куллануны пропагандалау турында.",
    "infringe": "Бу минем хокукларымны боза."
  },
  "comments": {
    "new_action": "Аңлатма калдыру өчен басыгыз ..",
    "title": "Аңлатмалар",
    "body_placeholder": "Сезнең аңлатма яки хәбәр",
    "send_action": "Аңлатма җибәрегез",
    "body_is_empty_error": "Аңлатма буш!",
    "comments": "Аңлатмалар",
    "no_comments": "Беренче аңлатма языгыз ...",
    "load_more_action": "Күбрәк аңлатмалар алыгыз ..",
    "cant_send_comment": "Сез яңа язма өсти алмыйсыз.",
    "cant_remove_this_comment": "Сез бу аңлатманы бетерә алмыйсыз!",
    "product_buyer": "Сатып алучы",
    "delete_alert": {
      "title": "Аңлатманы бетерү",
      "message": "Бу аңлатманы бетерергә телисезме?",
      "action": "Бетерү"
    },
    "notifications": {
      "delete_success": "Сезнең комментарий уңышлы бетерелде."
    },
    "first_send": "Беренче язма",
    "comment_at": "Яна",
    "edit_comment": "Аңлатманы үзгәртү"
  },
  "customer_club": {
    "bronze": "Бронза",
    "silver": "Көмеш",
    "gold": "Алтын",
    "platinum": "Платина",
    "diamond": "Алмаз"
  },
  "application_categories": {
    "tracking": "Кулланучының тәртибен тикшерү",
    "payment": "Түләү",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "Транспорт",
    "automation": "Автоматизация",
    "inventory": "Склад",
    "accounting": "Бухгалтерлык",
    "marketing": "Маркетинг",
    "advertising": "Реклама",
    "staff": "Персонал",
    "incentive": "Стимуллар",
    "shop": "Кибет"
  },
  "social_network": {
    "instagram": "Инстаграм",
    "telegram": "Телеграмма",
    "googleplay": "GooglePlay",
    "appstore": "AppStore",
    "twitter": "Твиттер",
    "linkedin": "Линкиндин",
    "medium": "Урта",
    "selldone": "Селдон",
    "facebook": "Facebook",
    "pinterest": "Пинтерест",
    "whatsapp": "WhatsApp",
    "skype": "Скайп",
    "facebook_messenger": "Facebook Messenger"
  },
  "form_builder": {
    "add_item_action": "Яңа әйбер өстәгез",
    "title_input": "Титул",
    "name_input": "Nameзгәрешле исем",
    "value_input": "Кыйммәтләр",
    "value_input_message": "Кулланучының вариантлары исемлеге",
    "default": "Килешенгән кыйммәт",
    "types": {
      "simple": "Гади",
      "selective": "Сайланма",
      "switch": "Күчерү",
      "file": "Файл",
      "number": "Сан"
    },
    "placeholder_input": "Урын иясе",
    "file_type_input": "Кабул ителә торган файл төрләре",
    "file_type_message": "jpeg, png, zip, ..."
  },
  "virtual_order_info_summery": {
    "title": "Продукциянең исеме",
    "reserved_at": "Теркәлү вакыты",
    "total_price": "Тулы сумма",
    "discount": "Ташлама",
    "final_price": "Соңгы сумма",
    "payment_status": "Түләү статусы",
    "payment_status_waiting": "Түләү көтә",
    "payment_status_paid": "Түләүле",
    "buyer": "Сатып алучы"
  },
  "virtual_item_info": {
    "title": "Виртуаль пункт",
    "outputs": {
      "title": "Чыгыш турында мәгълүмат",
      "sub_title": "Бу пунктның яшерен мәгълүматы",
      "message": "Бу мәгълүмат продуктны сатып алганнан соң кулланучыга күрсәтеләчәк."
    },
    "inputs": {
      "title": "Мәгълүмат кирәк",
      "sub_title": "Сатып алучы турында мәгълүмат кирәк",
      "message": "Сатып алучы соралган мәгълүматны формада кертергә тиеш"
    },
    "notifications": {
      "inputs_set_success": "Мәгълүмат формасы уңышлы теркәлде.",
      "confirm_by_admin_success": "Заказ тәмамлануы расланды.",
      "confirm_by_buyer_success": "Заказ тәмамлануы расланды."
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "Бу заказны COD түләү белән кабул итеп булмый.",
    "payment_returned": "Клиент тарафыннан түләү кире кайтарыла.",
    "payment_fraud": "Түләү алдау дип билгеләнде.",
    "location_out_of_service": "Клиентларның урнашуы хезмәттән читтә.",
    "user_not_responding": "Клиент шалтыратуларга җавап бирмәде.",
    "shop_owner_fault": "Кибет хезмәткәрләре мәгълүмат тутыруда хата килеп чыктылар.",
    "lack_of_inventory": "Складта юк.",
    "legal_restriction": "Законлы чикләүләр аркасында заказ бирә алмый.",
    "pricing_fault": "Сатучы тарафыннан бәяләү хата.",
    "system_fault": "Система хата."
  },
  "basket_order_info_summery": {
    "receiver": "Алучы",
    "phone": "Тел",
    "reserved_date": "Сатып алу датасы",
    "total_price": "Тулы сумма",
    "discount": "Ташлама",
    "final_price": "Соңгы сумма",
    "address": "Китерү адресы",
    "payment_status": "Түләү статусы"
  },
  "basket_status": {
    "open": "Ачык",
    "reserved": "Сакланган",
    "paid": "Түләүле",
    "canceled": "Беркетелде",
    "cod": "Тапшыруда түләгез",
    "receipt_added": "Квитанция өстәлде",
    "payment_processing": "Түләү эшкәртү"
  },
  "basket_delivery_state": {
    "rejected": "Кире кагылды",
    "reject_reason_not_found": "Сәбәбе билгеле түгел.",
    "step_1": "Кабатлау",
    "step_2": "Ышандыру",
    "step_3": "Әзерлек",
    "step_4": "Тапшыруда",
    "step_5": "Коткарылды"
  },
  "basket_return_request_view": {
    "title": "Кайту соравы",
    "delivery_date": "Тапшыру вакыты",
    "return_date": "Сорау датасы",
    "items_count": "Кире әйберләр санала",
    "items_count_unit": "пункт (лар)",
    "reason": "Сәбәп",
    "description": "Тасвирлау",
    "status": "Статус",
    "download_image": "Рәсемне йөкләү",
    "download_film": "Видеоны йөкләү",
    "download_voice": "Тавышны йөкләү",
    "accept_by_admin_action": "Сорауны кабул итегез",
    "reject_by_admin_action": "Сораудан баш тарту",
    "message_for_admin": "Селдон кулланып сез кабул иткән килешү буенча, сез сатып алучыга мөрәҗәгать итәргә һәм аңа заказны кайтару процессы турында хәбәр итәргә тиеш. Әгәр дә сорау кабул ителсә яки кире кагылса һәм сатып алучының тулы ризалыгы алса, моны эшләргә кирәк.",
    "notifications": {
      "update_status_success": "Статус яңартылды."
    }
  },
  "basket_list": {
    "return_count": "Кайту: {count} саны",
    "table": {
      "row": "Рәт",
      "image": "Рәсем",
      "product_name": "Продукция",
      "variant": "Вариант",
      "warranty": "Гарантияләр",
      "count": "Сана",
      "price": "бәя"
    }
  },
  "return_request_list": {
    "count": "Белешмә номеры",
    "return_warranty": "Акчаны кире кайтару гарантиясе",
    "return_warranty_unit": "Көн (көн)",
    "table": {
      "code": "Заказ коды",
      "product": "Продукция",
      "delivery_at": "Алынган дата",
      "state": "Статус",
      "reason": "Сәбәп",
      "return_warranty_period": "Гарантия вакыты"
    }
  },
  "data_toolbar": {
    "search": "Эзләү",
    "sort_by": "Карата төрлә",
    "count_item": "{item} әйберләрне күрсәт"
  },
  "sort": {
    "created_at": "Дата яса",
    "updated_at": "Редакцияләү датасы",
    "title": "Титул",
    "description": "Тасвирлау",
    "like": "Популярлык",
    "power": "Алкышлар",
    "product_type": "Продукция төре",
    "discount": "Ташлама",
    "rate": "Рейтинг",
    "rate_count": "Рейтинглар саны",
    "category": "Төркем",
    "product": "Продукция",
    "body": "Эчтәлек",
    "card_type": "Карта төре",
    "card_number": "Карта саны",
    "balance": "Баланс",
    "paid": "Сарыф ителгән сумма",
    "currency": "Валюта",
    "expire_at": "Гамәлдән чыгу көне",
    "discount_code": "Ташлама коды",
    "discount_percent": "Ташлама",
    "discount_limit": "Ташлама чикләре",
    "max_count": "Максималь санау",
    "used_count": "Кулланыла",
    "start_date": "Башлангыч көне",
    "end_date": "Ахыр датасы",
    "total_discount_amount": "Гомуми ташламалар",
    "initial_charge": "Башлангыч заряд",
    "total_count": "Гомуми сан",
    "amount_paid": "Түләнгән сумма",
    "name": "Исем",
    "published": "Басылган",
    "visits": "Визит",
    "color": "Төс",
    "landing_page": "Десант бите",
    "enable": "Эшләтергә",
    "fix_commission": "Тикшерелгән комиссия",
    "percent_commission": "Процент комиссиясе",
    "payment_at": "Түләү вакыты",
    "issued_at": "Чыгарылыш датасы",
    "payment": "Түләү",
    "website": "Вебсайт",
    "email": "Электрон почта",
    "user": "кулланучы",
    "code": "Код",
    "schedule_at": "Расписание датасы",
    "sender": "Enderибәрүче",
    "in_que": "Чиратта",
    "sent": "Sentибәрелгән",
    "shop": "Кибет",
    "quantity": "Сан",
    "amount": "Күләм",
    "jobs": "Эш урыннары санала",
    "success": "Уңышны санау",
    "fail": "Уңайсызлык",
    "distance": "Аралык",
    "duration": "Озынлыгы",
    "reset_at": "Датаны яңарту",
    "delivery_person": "Шәхес",
    "delivery_service": "Хезмәт",
    "date": "Дата",
    "order": "Заказ",
    "order_id": "Заказ ID",
    "status": "Статус",
    "price": "бәя",
    "count": "Сана",
    "final_price": "Соңгы бәя",
    "charge": "Түләү",
    "mention": "Искә алыгыз",
    "officer": "Офицер",
    "registered": "Теркәлгән",
    "purchased": "Сатып алынган",
    "sex": "Гендер"
  },
  "search_box": {
    "result": "Эзләү нәтиҗәләре",
    "tips": "Продукцияне һәм категорияләрне эзләү",
    "label": "Эзләү ...",
    "category": "Төркем"
  },
  "lead_status": {
    "physical_fast_delivery": "Ашыгыч тапшыру",
    "physical_under_24h_delivery": "Киләсе {lead} сәгать эчендә китерегез",
    "physical_over_24h_delivery": "Киләсе {days} көннәреннән әзерләү һәм тапшыру",
    "virtual_fast_prepare": "Ашыгыч тапшыру",
    "virtual_under_24h": "Киләсе {әйдәп баручы сәгатьләр эчендә эшләнәчәк",
    "virtual_over_24h": "Киләсе {көннәрдән алып эшләнәчәк"
  },
  "return_request_state": {
    "pending": "Көтелгән",
    "accepted": "Ышандырылды",
    "rejected": "Кире кагылды"
  },
  "return_order_reason": {
    "physical": {
      "U1": "Продукциянең туры килмәве",
      "U2": "Тапшыру пакетында продукт юк",
      "U3": "Пакет яки продуктның өзелүе",
      "U4": "Пакет яки серия номерын бозу",
      "U5": "Посылкадан кайбер әйберләр юк",
      "U6": "Продукция оригиналь түгел",
      "U7": "Продукция спецификацияләрне канәгатьләндерми"
    }
  },
  "image_uploader": {
    "label": "<u>Файлны тарту һәм ташлау яки сайлау</u>",
    "max_size": "Рөхсәт ителгән максималь зурлык: {size}"
  },
  "timespan": {
    "Morning": "Иртәнге 8 - кичке 12",
    "Evening": "Көндезге 12дән кичке 6га кадәр",
    "Night": "Кичке 6дан 12гә кадәр",
    "Instant": "Тиз почта"
  },
  "week_day": {
    "Saturday": "Шимбә",
    "Sunday": "Якшәмбе",
    "Monday": "Дүшәмбе",
    "Tuesday": "Сишәмбе",
    "Wednesday": "Чәршәмбе",
    "Thursday": "Пәнҗешәмбе",
    "Friday": "Fridayомга"
  },
  "payment_form": {
    "title": "Түләү ысулын сайлагыз",
    "gift_cards_input": "Бүләк карточкалары",
    "gift_cards_input_empty": "Бүләк карточкалары табылмады ..",
    "more": "Бүтәннәр",
    "pay_amount_by_gift_cards": "Картаны түләү",
    "select_payment_method": "Түбәндәге вариантлардан түләү ысулын сайлагыз.",
    "payment_amount_remained": "Калган түләү күләме",
    "payment_amount": "Түләнгән сумма",
    "all_paid_by_gift_cards": "Котлыйбыз, сезгә бу заказ өчен түләргә кирәк түгел. Бүләк картасы белән түләү төймәсенә басыгыз.",
    "pay_by_gift_cards_action": "Заказны заряд картасы белән түләгез",
    "order_free_payment": "Котлыйбыз, заказ бушлай!",
    "order_free_payment_action": "Хәзер бушлай заказ бирегез",
    "qr": {
      "address": "Түләү адресы",
      "amount": "Күләм"
    }
  },
  "discount_input": {
    "limit": "{процент}% ташлама {лимитка кадәр {{валюта}",
    "action": "Ташлама коды өстәргә",
    "code_input": "Ташлама коды",
    "notifications": {
      "add_success": "Котлыйбыз, ташлама коды."
    }
  },
  "gift_card": {
    "inactive": "Карта сүндерелгән",
    "expire": "Срогы",
    "transfer": "Күчерү",
    "send_to_friend": "Дуска җибәр"
  },
  "count_down": {
    "days": "Көн",
    "hours": "Сәгать",
    "minutes": "Минутлар",
    "seconds": "Секундлар"
  },
  "gift_status": {
    "Unpaid": "Квитанцияне көтү",
    "Paid": "Түләүле",
    "Rejected": "Кире кагылды",
    "Canceled": "Беркетелде"
  },
  "gift_program_status": {
    "Airdrop": "Түләү системасы",
    "Advertising": "Реклама",
    "PersonalGift": "Шәхси бүләк",
    "ShopGift": "Бүләкләр кибете"
  },
  "currency_selector": {
    "label": "Валюта"
  },
  "need_login": {
    "title": "керергә",
    "login_sms": "SMS кертү",
    "login_google": "Google белән керегез",
    "login_facebook": "Facebook белән керегез",
    "login_account": "Селдон белән керегез",
    "register": "Яңа кулланучы? Хәзер теркәлегез.",
    "mobile_input": "Кәрәзле телефоныгызны кертегез",
    "verification_code": "Тикшерү коды",
    "msg_title": "Сәлам,",
    "msg_body": "Зинһар, керегез. Бу берничә секунд кына.",
    "login_apple": "Apple белән керегез"
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "5 еллык алтын кибет"
    },
    "GOLDEN_2YEAR": {
      "name": "4 еллык алтын кибет"
    },
    "GOLDEN_3YEAR": {
      "name": "3 еллык алтын кибет"
    },
    "GOLDEN_4YEAR": {
      "name": "2 еллык алтын кибет"
    },
    "GOLDEN_5YEAR": {
      "name": "1 еллык алтын кибет"
    },
    "TOKEN_OWNER_1M": {
      "name": "Алтын Инвестор"
    },
    "TOKEN_OWNER_10M": {
      "name": "Алмаз Инвестор"
    },
    "TOKEN_OWNER_100M": {
      "name": "Ruby Investor"
    },
    "COMMUNITY_LOYAL": {
      "name": "Элемтә челтәренең югары җәмгыяте әгъзасы"
    },
    "GOLD_SUPPLIER": {
      "name": "Алтын тәэмин итүче"
    },
    "GOLD_SELLER": {
      "name": "Алтын дилер"
    },
    "CONTENT_SUPERMAN": {
      "name": "Төп эчтәлек җитештерүче"
    },
    "NINJA": {
      "name": "Ниндзя"
    },
    "STAR": {
      "name": "Йолдыз"
    },
    "GUARDIAN": {
      "name": "Зур клиентларга хезмәт"
    },
    "KING": {
      "name": "Базар патшасы"
    }
  },
  "cookie": {
    "title": "Бу сайт cookie'ларны куллана",
    "message": "Бу вебсайт кулланучылар тәҗрибәсен яхшырту өчен cookie'ларны куллана. Вебсайтыбызны кулланып, сез безнең Cookie политикасы нигезендә барлык cookie'ларга ризасыз.",
    "preferences_action": "Сайлаулар белән идарә итү",
    "agree_action": "Мин риза"
  },
  "basket_item_message": {
    "title": "Бу пункт өчен кирәкле мәгълүмат",
    "save_actions": "Хәбәрне сакла",
    "notifications": {
      "success": "Сезнең кертү мәгълүматлары сакланган."
    }
  },
  "faq": {
    "faq": "Еш бирелә торган сораулар",
    "title": "Сораулар һәм җаваплар",
    "sub_title": "Сез бездән нәрсә сорадыгыз.",
    "message": "Түбәндәге җаваплар арасында сезнең сорауга җавап эзләгез. Сораулар җавапсыз калса, бездән сора.",
    "add_question_action": "Яңа сорау бирегез",
    "read_more": "Күбрәк укы ..",
    "load_more": "Күбрәк сораулар ..",
    "main_page": "Сораулар Төп бит",
    "add_new": "Яңа сорау җибәрегез",
    "login_alert": "Сорау бирү өчен керегез.",
    "question_input": "Сорау",
    "question_input_placeholder": "Соравыгызны бирегез.",
    "notifications": {
      "success_add": "Сезнең сорау уңышлы тапшырылды."
    }
  },
  "rating_labels": [
    "Бик начар",
    "Начар",
    "Нормаль",
    "Яхшы",
    "Яхшы"
  ],
  "map_view": {
    "address_detail": "Адрес детальләре",
    "change": "Changeзгәреш",
    "select": "Сайлагыз",
    "not_found_address": "Кыйммәт табылмады",
    "enter_address_hint": "Максат адресын кертегез",
    "enter_your_address": "Адресыгызны кертегез.",
    "postal_code": "Почта индексы",
    "phone_input": "Телефон {type}",
    "building_number": "Төзелеш номеры",
    "building_unit": "Берәмлек",
    "full_name_input": "Тулы исем {type}",
    "save_detail_action": "Детальләрне саклагыз",
    "more_detail_input": "Күбрәк тасвирлау",
    "add_address_to_list": "Исемлеккә исем өстәгез",
    "address_title_input": "Адрес ярлыгы (Таләп)",
    "notifications": {
      "save_in_list": "Бу адрес бөтен детальләре белән сезнең исемлектә сакланган.",
      "edit_success": "{Титулда сакланган яңа адрес кыйммәтләре."
    },
    "delete_address_dialog": {
      "title": "Адресны бетерү",
      "message": "Сез бу адресны бетерергә телисезме?",
      "action": "Адресны бетерегез"
    }
  },
  "comment_manager": {
    "can_not_edit": "Бу аңлатманы үзгәртә алмыйм!",
    "comment_input_empty": "Хәбәр тексты буш!",
    "article_not_saved": "Мәкаләне саклагыз!"
  },
  "wheel_fortune": {
    "title": "Уйнагыз һәм җиңегез",
    "message": "Gameәр уенның бәясе 10 чип. Сездә хәзерге вакытта {chips} чип бар. Кибеттән сатып алып, күбрәк чип алыгыз.",
    "win_message": "Котлыйбыз, сез җиңәсез!",
    "lost_message": "Гафу итегез, сез уенны югалттыгыз.",
    "try_again": "Сез кабатлап карый аласыз"
  },
  "json": {
    "add": "Структура мәгълүматларын өстәгез",
    "add_message": "Яңа структура мәгълүматлары булдыру",
    "structures": "Структуралар",
    "book": {
      "title": "Китап",
      "desc": "Кулланучыларга эзләү нәтиҗәләреннән турыдан-туры тапкан китапны сатып алырга мөмкинлек бирүче китаплар."
    },
    "occupation": {
      "title": "Фаразланган хезмәт хакы",
      "desc": "Хезмәт хакын бәяләү турында мәгълүмат, мәсәлән, хезмәт хакы диапазоны һәм эш төрләре буенча региональ хезмәт хакы уртача, Google'да эш эзләү тәҗрибәсендә күрсәтелә."
    },
    "course": {
      "title": "Курс",
      "desc": "Провайдерның махсус исемлегендә барлыкка килгән укыту курслары. Курсларда курсның исеме, провайдеры һәм кыскача тасвирламасы булырга мөмкин."
    },
    "howto": {
      "title": "Ничек",
      "desc": "Видео, рәсемнәр һәм текстны күрсәтеп, биремне уңышлы тәмамлау өчен, кулланучылар адымнары җыелмасы аша ничек йөрергә."
    },
    "recipe": {
      "title": "Рецепт",
      "desc": "Индивидуаль бай нәтиҗә яки хуҗа карусель өлеше итеп күрсәтүче рецептлар."
    }
  },
  "support": {
    "Financial": "Финанс",
    "Technical": "Техник",
    "Advisor": "Киңәшче"
  },
  "condition": {
    "new": "Яңа",
    "refurbished": "Яңартылды",
    "used": "Кулланыла",
    "used_fair": "Ярминкә",
    "used_good": "Яхшы кулланылган",
    "used_like_new": "Яңа кебек кулланыла"
  },
  "variant_filter": {
    "title": "Продукциянең вариант фильтры",
    "only_available": "Барлыкта"
  },
  "service": {
    "task": {
      "title": "Биремнәр",
      "message": "Бу хезмәттә башкарылган биремнәр исемлеге."
    },
    "appointment": {
      "title": "Билгеләнү",
      "message": "Сезгә туры килгән көнгә һәм сәгатькә нигезләнеп, атна вакытын түбәндәге вакытлардан сайлагыз."
    },
    "booking": {
      "title": "Броньлау",
      "message": "Түбәндәге календарьда бронь ясарга теләгән көннәрнең вакытын күрсәтегез."
    },
    "subscription": {
      "title": "Подписка"
    },
    "charge": {
      "title": "Түләү"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "Тикшерелгән бәяләр",
      "message": "Бу төр бәяләүдә продуктның бәясе - билгеле сумма, һәм сатып алучының бәяне исәпләвен таләп итүе юк."
    },
    "ESTIMATION": {
      "title": "Смета бәяләү",
      "message": "Продукциянең һәм хезмәтнең бәясе сатучы заказ биргәндә күпмедер дәрәҗәдә исәпләнәчәк, хезмәт вакытында түләү счет-фактуралары үзгәртелә яки өстәлергә мөмкин."
    },
    "AGREEMENT": {
      "title": "Килешү бәяләре",
      "message": "Продукциянең яки хезмәтнең соңгы бәясе заказ бирелгәннән соң сатучы тарафыннан үзгәртелмәячәк."
    },
    "BID": {
      "title": "Тендер / аукцион",
      "message": "Продукция потенциаль сатып алучылар тарафыннан иң югары бәядә сатылачак."
    }
  },
  "map": {
    "title": "Продукцияне кабул итү",
    "confirm": "Урын куегыз",
    "address": "Максат",
    "receptor": "Алучы"
  },
  "ShopBots": {
    "telegram": "Телеграмма"
  },
  "article_tags": {
    "title": "Эчтәлек",
    "tags_input": "Теги",
    "tags_input_message": "Теги Бу мәкалә исемлеге",
    "notification": {
      "add_success": "Тэглар өстәлде"
    }
  },
  "difficulties": {
    "very_complicated": "Бик катлаулы",
    "hard": "Каты",
    "intermediate": "Арадаш",
    "easy": "Easyиңел"
  }
};