export default {
  "currency_default": "USD",
  "language_default": "en",
  "selldone": "Продано",
  "store": "магазин",
  "not_exist": "Не існує",
  "error": "Помилка",
  "active": "Активний",
  "inactive": "неактивний",
  "required_value": "Обов’язкові значення",
  "original_warranty": "Гарантія на оригінальний продукт",
  "return_warranty_days": "{days} днів гарантії повернення",
  "no_return_warranty": "Повернення немає",
  "reed_agree_terms": "Я прочитав умови використання та політику конфіденційності та погоджуюся з ними.",
  "commons": {
    "Currency": "Валюта",
    "COD": "COD",
    "State": "держава",
    "Price": "ціна",
    "order_price": "Сума замовлення",
    "VAT": "VAT",
    "Discount": "Знижка",
    "In_Stock": "В наявності",
    "Variants": "Варіанти",
    "No_variants": "Без варіанта",
    "all": "ВСІ",
    "today": "Сьогодні",
    "yesterday": "Вчора",
    "license": "Ліцензія",
    "home": "Додому",
    "support": "Підтримка",
    "messages": "Повідомлення",
    "no_message": "Немає повідомлення",
    "empty": "Порожній",
    "phone": "Телефон",
    "address": "адреса",
    "name": "Ім'я",
    "password": "Пароль",
    "email": "Електронна пошта",
    "mobile": "Мобільний",
    "login": "увійти",
    "register": "Реєстрація",
    "select_account": "Виберіть обліковий запис",
    "online": "Онлайн",
    "offline": "Офлайн",
    "finish": "Закінчити",
    "finished": "Готово",
    "preview": "Попередній перегляд",
    "free": "Безкоштовно",
    "free_completely": "Повністю безкоштовна підписка",
    "fee": "Плата",
    "month": "Місяць",
    "months": "Місяці",
    "faq": "Часті запитання",
    "question": "Питання",
    "answer": "Відповідь",
    "create_date": "Створити дату",
    "update_date": "Дата оновлення",
    "start_date": "Дата початку",
    "end_date": "Дата закінчення",
    "social": "Соціальний",
    "total": "Всього",
    "orders": "Замовлення",
    "sessions": "Сесії",
    "product_views": "Перегляди продукту",
    "add_to_carts": "Додати в кошики",
    "checkouts": "Перевіряти",
    "payments": "оплата",
    "organic_search": "Органічний пошук",
    "other": "Інший",
    "landing_page": "Цільова сторінка",
    "discount_code": "Код на знижку",
    "total_sell": "Загальний обсяг продажів",
    "details": "Деталі",
    "currency": "Валюта",
    "amount": "Сума",
    "published": "Опубліковано",
    "draft": "Чернетка",
    "save_changes": "Зберегти зміни",
    "source": "Джерело",
    "medium": "Середній",
    "url": "URL-адреса",
    "revenue": "Дохід",
    "performance": "Продуктивність",
    "term": "Термін",
    "content": "Зміст",
    "session": "Сесія",
    "product": "Продукт",
    "add": "Додати",
    "checkout": "Перевіряти",
    "payment": "оплата",
    "more_options": "Більше варіантів",
    "full_name": "Повне ім'я",
    "tel": "тел",
    "about_me": "Про мене",
    "request_checking": "Запит на перевірку",
    "passport": "паспорт",
    "birthday": "День народження",
    "country": "Країна",
    "city": "Місто",
    "gender": "Стать",
    "offer": "Пропозиція",
    "website": "веб-сайт",
    "apply_for_all_products": "∞ Подайте заявку на всі продукти",
    "fix_commission": "Фіксована комісія",
    "percent_commission": "Відсоток комісії",
    "fixed_discount": "Фіксована знижка",
    "discount_percentage": "Відсоткова знижка",
    "discount_limit": "Ліміт знижки",
    "no_code": "Без коду",
    "max_count": "Максимальна кількість",
    "count_unit": "Предмети",
    "used": "Використовується",
    "daily": "Щодня",
    "monthly": "Щомісячно",
    "yearly": "Щорічно",
    "state": "Статус",
    "disable": "Вимкнути",
    "enable": "Увімкнути",
    "activation_code": "Код активації",
    "quantity": "Кількість",
    "no_club": "Немає клубу",
    "per_order": "За замовлення",
    "count": "Рахувати",
    "seconds": "Секунди",
    "auto": "Авто",
    "title": "Назва",
    "message": "повідомлення",
    "width": "Ширина",
    "length": "Довжина",
    "height": "Висота",
    "label": "Етикетка",
    "click": "Натисніть",
    "bank": "банк",
    "default": "За замовчуванням",
    "role": "Роль",
    "user": "Користувач",
    "users": "Користувачі",
    "code": "код",
    "total_payment": "Повна оплата",
    "balance": "Баланс",
    "chance": "Шанс",
    "free_for_new_users": "Безкоштовно для нових користувачів",
    "prize_amount": "Сума премії",
    "win": "Виграти",
    "gift_card": "Подарункова картка",
    "discount": "Знижка",
    "config": "конфіг",
    "prize": "премія",
    "Prizes": "Призи",
    "result": "Результат",
    "price": "ціна",
    "lottery": "Лотерея",
    "coupon": "Купон",
    "customer_club": "Клуб клієнтів",
    "shipping": "Доставка",
    "sum": "Сума",
    "not_paid": "Не оплачено",
    "category": "Категорія",
    "done": "Готово",
    "email_from": "Від",
    "subject": "Тема",
    "schedule": "Розклад",
    "files_list": "Список файлів",
    "file_max_size": "Максимальний розмір файлу",
    "value": "Значення",
    "help": "Допоможіть",
    "shipping_tax": "Податок на доставку",
    "net_price": "Ціна нетто",
    "tax": "податок",
    "tax_included": "Входить у вартість",
    "limit": "Ліміт",
    "min_purchase": "Мінімальна закупівля",
    "eligible_for": "Придатний для",
    "only_for_first_buy": "Тільки для першої покупки",
    "one_time_use": "Можна використовувати одноразово",
    "period_of_qualify": "Обмеження періоду використання",
    "no_constraint": "Немає межі",
    "timespan": "Період часу",
    "days": "день(и)",
    "weight": "Вага",
    "distance": "Відстань",
    "last_status": "Останній статус",
    "issued_at": "Виданий в",
    "order": "Замовити",
    "order_detail": "Деталі замовлення",
    "percent": "Відсоток",
    "applied_count": "Застосований кол",
    "campaign": "Кампанія",
    "os": "Операційна система",
    "browser": "браузер",
    "device": "Пристрій",
    "device_ip": "IP-адреса пристрою",
    "location": "Розташування",
    "user_agent": "Агент користувача",
    "affiliate": "Партнер",
    "timeline": "Хронологія",
    "add_note": "Додати коментар",
    "record": "Запис",
    "unlimited": "Необмежений",
    "show_coupons": "Показати купони",
    "hide_coupons": "Приховати купони",
    "service_area": "Зона обслуговування",
    "apps": "Програми",
    "plugins": "плагіни",
    "bots": "Боти",
    "categories": "Категорії",
    "products": "Продукти",
    "business": "Бізнес",
    "personal": "Особистий",
    "size": "Розмір",
    "holiday": "Свято",
    "sod": "Оплата при доставці",
    "cod": "Наложеним платежем",
    "free_shipping": "Безкоштовна доставка",
    "hours": "годин",
    "send_date": "Дата відправлення",
    "deliver_date": "Дата доставки",
    "return_date": "Дата повернення",
    "pending": "Очікується",
    "delivered": "Доставлено",
    "returned": "Повернувся",
    "canceled": "Скасовано",
    "shipping_cost": "Вартість доставки",
    "action": "Дія",
    "cancel_date": "Дата скасування",
    "deliver_in_process": "Замовлення відправлено..",
    "kind": "Тип",
    "detail": "Деталі",
    "map": "карта",
    "actions": "Дії",
    "navigation": "Навігація",
    "navigation_app": "Застосування",
    "payment_date": "Дата оплати",
    "duration": "Тривалість",
    "bill": "Білл",
    "delivery_persons": "Кур'єри",
    "delivery_services": "Послуги доставки",
    "live_view": "Живий перегляд",
    "cart": "Кошик",
    "priority": "Пріоритет",
    "sufficient_credit": "Достатній кредит",
    "max_package_size": "Максимальний розмір упаковки",
    "delay": "Затримка",
    "credit": "Кредит",
    "livemode": "жити",
    "paused": "Призупинено",
    "debug": "Налагоджувати",
    "token": "Токен",
    "status": "Статус",
    "courier": "Кур'єр",
    "track": "Трек",
    "track_order": "Відстеження замовлення",
    "cost": "Вартість",
    "receipt": "Квитанція",
    "origin": "Походження",
    "destination": "Пункт призначення",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "Недостатньо запасів!",
    "sub_total": "Проміжний підсумок",
    "customer": "Замовник",
    "delivery": "Доставка",
    "online_orders": "Онлайн замовлення",
    "pos_orders": "POS замовлення",
    "chips": "Чіпси",
    "subscribed": "Підписано",
    "unsubscribed": "Скасовано підписку",
    "last_login": "Останній вхід",
    "join_at": "Дата приєднання",
    "club": "клуб",
    "buyer": "Покупець",
    "seller": "Продавець",
    "or": "Або",
    "type": "Тип",
    "condition": "Хвороба",
    "brand": "Бренд",
    "attempt": "Спроба",
    "error": "Помилка",
    "success": "Успіх",
    "fail": "Не вдалося",
    "inventory": "Інвентаризація",
    "link": "Посилання",
    "visits": "Відвідування",
    "transactions": "Транзакції",
    "vat": "VAT",
    "pos_vat": "POS ПДВ",
    "sort_by": "Сортувати за..",
    "from": "Від",
    "from_lead_time": "Протягом наступних {hours} год",
    "no_credit_card_info": "Немає інформації про картку!",
    "active": "Активний",
    "not_active": "Не активовано!",
    "referrals": "Реферали",
    "dashboard": "Панель приладів",
    "more": "Більше",
    "inactive": "неактивний",
    "developer": "Розробник",
    "setting": "Налаштування",
    "membership_conditions": "Умови членства",
    "customers": "Клієнти",
    "created_at": "Дата створення",
    "updated_at": "Останнє оновлення",
    "register_at": "Дата реєстрації",
    "old": "Старий",
    "new": "Новий",
    "start": "Почніть",
    "end": "Кінець",
    "pos": "POS",
    "out_of_stock": "Немає в наявності",
    "fake": "Підробка",
    "low_inventory_warning": "Увага, невеликий запас!",
    "webhook": "Webhook",
    "notification": "Повідомлення",
    "sms": "SMS",
    "online_payment_link": "Посилання на оплату онлайн",
    "waiting_load_data": "Очікування завантаження даних..",
    "views": "Перегляди",
    "sales": "Продажі",
    "total_views": "Всього переглядів",
    "total_sales": "Загальний обсяг продажів",
    "from_previous_n_days": "За останні {days} днів",
    "drop_shipping": "Дропшипінг",
    "commission": "комісія",
    "shipping_area": "Зона доставки",
    "main_seller": "Основний продавець",
    "domain": "Домен",
    "contact": "Контактна інформація",
    "wallet": "гаманець",
    "reseller": "Торговий посередник",
    "tracking_code": "Код відстеження",
    "tracking_url": "URL-адреса для відстеження",
    "fulfillments": "Виконання",
    "reject": "Відхилити",
    "reserved": "Зарезервований",
    "score": "Оцінка",
    "customer_price": "Ціна клієнта",
    "options": "Параметри",
    "show_details": "Показати деталі",
    "no_data": "Немає даних..",
    "waiting": "Очікування...",
    "waiting_connecting_payment": "Чекаємо на платіжний сервіс...",
    "creating_secure_payment": "Створення безпечного платежу.",
    "officer": "Офіцер",
    "ticket": "Квиток",
    "ticket_url": "URL-адреса квитка",
    "closed_at": "Зачинено о",
    "close_ticket": "Закрити квиток",
    "reopen_ticket": "Повторне відкриття квитка",
    "require": "Вимагати*",
    "search": "Шукати...",
    "language": "Мова",
    "tasks": "Завдання",
    "permissions": "Дозволи",
    "finish_date": "Дата закінчення",
    "complete_date": "Дата Виконання",
    "settle_date": "Дата розрахунку",
    "cost_span": "Діапазон цін",
    "industry": "промисловість",
    "rating": "Рейтинги",
    "rates": "Рейтинг",
    "seen_at": "Побачено на",
    "completed": "Завершено",
    "you": "ви",
    "shop": "Магазин",
    "store": "магазин",
    "granted": "Допущено",
    "deny": "Заперечити",
    "request": "Запит",
    "expert": "Експерт",
    "response": "Відповідь",
    "requests": "Запити",
    "experts": "Експерти",
    "responses": "Відповіді",
    "negotiations": "Переговори",
    "all_chats": "Усі чати",
    "chats": "чати",
    "tags": "Мітки",
    "description": "Опис",
    "rates_count": "Кількість оцінок",
    "rate": "Рейтинг",
    "comment": "Коментар",
    "chat": "Чат",
    "install": "Встановити",
    "edited": "Відредаговано",
    "undo": "Скасувати",
    "redo": "Повторити",
    "male": "Чоловічий",
    "female": "Жіночий",
    "calculator": "Калькулятор",
    "catalog": "Каталог",
    "max_height": "Максимальна висота",
    "images_compare": "Порівняння зображень",
    "canvas": "Полотно",
    "table_of_contents": "Зміст",
    "comments": "Коментарі",
    "badge_codes": "Код значків",
    "need_more": "Потрібно більше?",
    "invite_glow_caption": "Отримайте 14,9$ за кожного друга!",
    "register_free": "100% безкоштовна реєстрація",
    "gift": "Подарунок",
    "google": "Google",
    "facebook": "Facebook",
    "instagram": "Instagram",
    "instashop": "Instashop",
    "show": "Показати",
    "hide": "Сховати",
    "waiting_review": "Очікування огляду",
    "not_selected": "Не вибрано",
    "time": "Час",
    "final_price": "Остаточна ціна",
    "starting_price": "Початкова ціна",
    "day": "День",
    "paid": "Оплачено",
    "service_bill": "Оплата рахунку",
    "avocado": "авокадо",
    "delivery_price": "Вартість доставки",
    "select_address": "Виберіть адресу",
    "image": "Зображення",
    "view": "Переглянути",
    "sell": "Продаж",
    "hyper": "Гіпер",
    "cart_list": "Кошик",
    "barcode_scanner": "Сканер штрих-коду",
    "scan_qr_code": "Скануйте QR-код",
    "new_carts": "Нові візки",
    "pays": "Виплати",
    "annually": "Щорічно",
    "sells": "Продажі",
    "articles": "статті",
    "jobs": "Робота",
    "job": "Робота",
    "blog": "Блог",
    "deleted_at": "Видалено о",
    "capacity": "Ємність",
    "download_at": "Дата останнього завантаження",
    "downloads": "Завантаження",
    "usage": "Використання",
    "select_upload_file": "Виберіть або скиньте файл",
    "download_link": "Посилання для скачування",
    "uploading": "Завантаження..",
    "files": "Файли",
    "star": "Зірка",
    "speed": "Швидкість",
    "feedback": "Зворотній зв'язок",
    "new_messages": "Нові повідомлення",
    "file": "Файл",
    "attachment": "Вкладення",
    "gallery": "Галерея",
    "sync": "Синхронізувати",
    "diff_time": "Різниця у часі",
    "network": "мережа",
    "account": "Рахунок",
    "configuration": "Конфігурація",
    "blockchain": "Блокчейн",
    "blog_link": "Посилання на блог",
    "community": "Спільнота",
    "critical_zone": "Критична зона",
    "statistics": "Статистика",
    "access": "Доступ",
    "seo": "SEO",
    "followers": "Послідовники",
    "followings": "Підписки",
    "private": "Попередній перегляд",
    "soon": "Незабаром",
    "features": "Особливості",
    "bot": "бот",
    "sample": "Зразок",
    "how_it_work": "Як це працює?",
    "page": "Сторінка",
    "congratulations": "Вітаю",
    "recommend": "Рекомендувати",
    "recommended": "Рекомендовано",
    "recoms": "Рекомендації",
    "likes": "Подобається",
    "clicks": "Кліки",
    "platform": "Платформа",
    "cms": "CMS",
    "cash": "готівкою",
    "dir_payment": "банківський переказ",
    "auto_complete": "Автозавершення",
    "compare": "Порівняйте",
    "infinite": "Нескінченний",
    "tips": "Поради",
    "technical": "Технічний",
    "finance": "фінанси",
    "your_phone_input": "Введіть номер телефону",
    "income": "Дохід",
    "change": "Змінити",
    "new_users": "Нові користувачі",
    "success_orders": "Вдалих замовлень",
    "direct": "Прямий",
    "last_activity": "Остання діяльність",
    "landing": "Посадка",
    "now": "Тепер",
    "accept_agreement": "Я прочитав і прийняв умови.",
    "report": "Звіт",
    "tablet": "планшет",
    "pc": "PC",
    "acquisition_channel": "Канал залучення",
    "to": "До",
    "info": "Інформація",
    "general": "Генеральний",
    "upload": "Завантажити",
    "general_config": "Загальна конфігурація",
    "limits_config": "Обмеження",
    "design_config": "Дизайн і стиль",
    "duration_config": "Обмеження тривалості",
    "constraints_config": "Межі прийнятності",
    "clubs_config": "Доступно в клубах",
    "additional_config": "Додаткові конфігурації",
    "import": "Імпорт",
    "ribbon": "Стрічка",
    "countries": "країни",
    "edit": "Редагувати",
    "delete": "Видалити",
    "analytics": "Аналітика",
    "rules": "правила",
    "unset": "Не встановлено",
    "carts": "Візки",
    "optional": "За бажанням",
    "design": "Дизайн",
    "filter": "Фільтр",
    "send": "Надіслати",
    "approved": "Затверджено",
    "unit": "одиниця",
    "profile": "профіль",
    "shipping_rates": "Тарифи доставки",
    "package": "Пакет",
    "overview": "Огляд",
    "live": "жити",
    "never": "Ніколи",
    "always": "Завжди",
    "mandatory": "Обов’язковий",
    "expire_at": "Термін придатності",
    "position": "Позиція",
    "channel": "канал",
    "age": "Вік",
    "charge": "Зарядити",
    "giftcard": "Подарункова картка",
    "acquisition": "Придбання",
    "conversion": "Перетворення",
    "total_payments": "Загальна сума платежів",
    "community_ask": "Запитайте у спільноті",
    "children": "Діти",
    "export": "Експорт",
    "list": "Список",
    "hierarchy": "Ієрархія",
    "images": "Зображення",
    "demo": "Демо",
    "author": "Автор",
    "designer": "Дизайнер",
    "max": "Максимум",
    "accepted": "Прийнято",
    "reply": "Відповісти",
    "reviewed": "Переглянуто",
    "restored": "Відновлено",
    "merchant": "купець",
    "per_product": "За продукт",
    "journey": "Подорож",
    "after": "Після",
    "waiting_for_payment": "Будь ласка, завершіть оплату...",
    "hour": "годину",
    "minute": "хвилина",
    "premium": "Преміум",
    "light": "Світло",
    "dark": "Темний",
    "guest": "Гість",
    "shops": "Магазини",
    "vendor": "Продавець",
    "vendors": "Продавці",
    "marketplace": "Ринок",
    "verify_date": "Перевірити дату",
    "note": "Примітка",
    "panel": "Панель",
    "removed": "Видалено",
    "segments": "Сегменти",
    "personal_info": "Особиста інформація",
    "preferences": "вподобання",
    "spec": "Специфікація",
    "reviews": "Відгуки",
    "constraints": "обмеження",
    "flexible": "гнучкий",
    "usage_limit": "Ліміт використання",
    "temporary": "Тимчасовий",
    "original": "Оригінал",
    "saved": "Збережено!",
    "sort": "Сортувати",
    "documents": "Документи",
    "document": "документ",
    "please_wait": "Будь ласка, зачекайте...",
    "pickup": "Самовивіз",
    "customize": "налаштувати",
    "difficulty": "Складність",
    "banned": "Заборонений",
    "company": "Компанія",
    "tax_shipping": "Податок на доставку",
    "warranty": "Гарантія",
    "return_policy": "Політика повернення",
    "guide": "Гід",
    "translate": "Перекласти",
    "public": "Громадський",
    "deleted": "Видалено",
    "variant": "Варіант",
    "secure": "Безпечний",
    "admin": "адмін",
    "tax_included_abstract": "в т.ч.",
    "payment_not_settled": "Оплата не проведена!",
    "orders_list": "Список замовлень",
    "subscription_plan": "План підписки",
    "contents": "Зміст",
    "pricings": "Ціноутворення",
    "static_page": "Статична сторінка",
    "shop_button": "кнопка магазину",
    "embed": "Вставити",
    "over": "закінчено",
    "tax_vary_by_location": "змінюватися. Місцезнаходження",
    "product_type": "Тип продукту",
    "tax_id": "ІПН",
    "business_name": "Назва фірми",
    "invoice": "Рахунок-фактура",
    "included_in_the_product": "Входить до складу продукту",
    "included_in_the_product_description": "До складу продукту входять наступні компоненти",
    "cross_sell": "Перехресний продаж",
    "discount_off": "OFF",
    "extra_discount": "Додаткова знижка",
    "template": "Шаблон",
    "in_cart": "У кошику",
    "pros_and_cons": "Плюси і мінуси",
    "related_products": "Супутні товари",
    "related_categories": "Пов'язані категорії",
    "badges": "Значки",
    "explore": "Досліджуйте",
    "updated": "Оновлено",
    "bank_name": "Назва банку",
    "bank_account_number": "Номер рахунку в банку",
    "bank_routing_number": "Банківський маршрутний номер",
    "bank_branch_address": "Адреса відділення банку",
    "bank_account_name": "Повне ім'я власника облікового запису",
    "valuation": "Оцінка",
    "cluster": "Кластер",
    "clusters": "Кластери",
    "subscriptions": "Підписки",
    "spam": "Спам",
    "video": "Відео"
  },
  "dialogs": {
    "delete": {
      "title": "Видалити",
      "message": "Ви впевнені, що видалили цей елемент?",
      "action": "Так, видалити зараз"
    }
  },
  "actions": {
    "add_to_cart": "Додати в кошик",
    "cancel": "Скасувати",
    "update": "Оновлення",
    "add": "Додати",
    "delete": "Видалити",
    "new": "Новий",
    "save_continue": "Зберегти та продовжити",
    "save": "Зберегти",
    "save_changes": "Зберегти зміни",
    "change": "Змінити",
    "continue": "Продовжуйте",
    "close": "Закрити",
    "finish": "Закінчити",
    "poll": "Опитування",
    "view": "Переглянути",
    "edit": "Редагувати",
    "next": "Далі",
    "previous": "Попередній",
    "create": "Створюйте",
    "set": "набір",
    "find": "Знайти",
    "accept": "Прийняти",
    "reject": "Відхилити",
    "back": "Назад",
    "pay": "Платити",
    "pay_now": "Платити зараз",
    "print": "Друк",
    "return": "Повернення",
    "publish": "Опублікувати",
    "confirm": "Підтвердьте",
    "copy": "Копія",
    "submit": "Подати",
    "send": "Надіслати",
    "yes": "Так",
    "no": "ні",
    "meh": "Хм",
    "clear": "Ясно",
    "dismiss": "Звільнити",
    "search": "Пошук",
    "deselect_all": "Скасуйте вибір усіх",
    "select_all": "Вибрати все",
    "refresh": "Оновити",
    "verify": "Перевірити",
    "play": "Грати",
    "open": "ВІДЧИНЕНО",
    "calculate": "Розрахувати",
    "quick_buy": "Швидка покупка",
    "click_here": "Натисніть тут",
    "schedule": "Розклад",
    "send_now": "Відправити зараз",
    "download": "Завантажити",
    "reset_default": "Скинути налаштування за замовчуванням",
    "reset": "Скинути",
    "check": "Перевірте",
    "cod_payment": "Наложеним платежем",
    "dir_payment": "Грошовий переказ",
    "online_payment": "Онлайн оплата",
    "checkout": "Перевіряти",
    "show_all": "Показати все",
    "login": "увійти",
    "logout": "Вийти",
    "more": "Більше..",
    "collapse": "Згорнути",
    "apply_change": "Застосувати зміни",
    "apply": "Застосувати",
    "add_giftcard": "Додати подарункову картку",
    "charge": "Зарядити",
    "send_invites": "Надішліть запрошення",
    "past": "Минуле",
    "restore": "Відновлення",
    "cut": "Вирізати",
    "get_sms_code": "Отримати код аутентифікації",
    "register_no_mail": "Продовжуйте без електронної пошти",
    "no_mail_register_message": "Не маєте електронної адреси або забули пароль?",
    "reset_by_mail": "Відновлення пароля електронною поштою",
    "reset_by_sms": "Відновлення пароля за допомогою смс",
    "cash_payment": "Оплата готівкою",
    "show_chart": "Показати діаграму",
    "open_app": "Відкрийте додаток",
    "login_now": "Увійдіть зараз",
    "watch_video": "Переглянути відео",
    "check_now": "Перевірь зараз",
    "remove_image": "Видалити зображення",
    "view_website": "Відкрити посилання",
    "explore": "Досліджуйте {name}",
    "go": "Іди",
    "read_more": "Детальніше",
    "start_now": "Почніть зараз — це безкоштовно",
    "view_live": "Дивіться наживо",
    "resend_code": "Надіслати код повторно",
    "invite": "Запросити",
    "add_more": "Додати більше",
    "install_now": "Встановити зараз",
    "uninstall": "Видалити",
    "show_preview": "Показати попередній перегляд",
    "hide_preview": "Приховати попередній перегляд",
    "download_now": "Скачати зараз",
    "auto_fill": "Автозаповнення",
    "track": "Трек",
    "change_state": "Змінити статус",
    "done": "Готово",
    "reply": "Відповісти",
    "watch_now": "Дивитися зараз",
    "unlock": "Розблокувати",
    "lock": "Замок",
    "create_clone": "Створити клон",
    "regenerate": "Регенерувати",
    "add_message": "Додати повідомлення",
    "continue_chat": "Продовжити чат",
    "add_new_message": "Додати нове повідомлення",
    "change_setting": "Змінити налаштування",
    "delete_all": "Видалити все",
    "transfer_fund": "Трансфертний фонд",
    "reverse_fund": "Зворотний фонд",
    "settlement": "Поселення",
    "refund": "Повернення коштів",
    "partial_refund": "Часткове повернення коштів",
    "change_payment_method": "Змінити спосіб оплати",
    "buy": "Купуйте",
    "view_all": "Подивитись все",
    "view_now": "Переглянути зараз",
    "paste": "Вставити"
  },
  "instance_message_title": "Відправити миттєве повідомлення",
  "instance_message": "Привіт, {name}! Мене звати {author} з {company}.",
  "errors": {
    "419": "Ви були неактивні протягом тривалого часу, будь ласка, <b>⟳ ОНОВІТЬ СТОРІНКУ</b> з міркувань безпеки.",
    "gateway_blockchain_sync_error": "Система не синхронізується з блокчейном. Створити нову транзакцію буде неможливо, доки не буде завершена синхронізація наших серверів. Ми вирішуємо проблему.",
    "gateway_network_error": "Служба платіжного шлюзу зіткнулася з проблемою зв’язку."
  },
  "receiver_info": {
    "map": {
      "title": "Адреса доставки",
      "confirm": "Встановити місце розташування",
      "address_type": "Пункт призначення",
      "receptor_type": "Приймач"
    },
    "receiver_address": "Виберіть адресу доставки",
    "address": "адреса",
    "postcode": "Поштовий індекс",
    "enter_value": "Заповніть тут",
    "address_note": "Примітка",
    "tel": "Контактний номер",
    "service_address": "Виберіть свою адресу"
  },
  "weight": {
    "g": "g",
    "oz": "унцій",
    "lb": "фунт",
    "kg": "кг"
  },
  "mass_unit_name": {
    "g": "грам",
    "oz": "унція",
    "lb": "фунт",
    "kg": "кілограм"
  },
  "length": {
    "cm": "см",
    "in": "в",
    "ft": "футів",
    "mm": "мм",
    "m": "м",
    "yd": "ярд"
  },
  "size_unit_name": {
    "cm": "Сантиметр",
    "in": "дюйм",
    "ft": "Нога",
    "mm": "міліметр",
    "m": "метр",
    "yd": "Двір"
  },
  "distance": {
    "m": "метр",
    "km": "км"
  },
  "time": {
    "days": "днів",
    "hours": "годин",
    "minutes": "Хвилини",
    "seconds": "Секунди"
  },
  "units": [
    "одиниця",
    "пункт",
    "кожен",
    "набір",
    "шматок",
    "кілограм",
    "грам",
    "міліграм",
    "метр",
    "міліметр",
    "квадратний метр",
    "квадратних футів",
    "кубічний метр",
    "л",
    "мілілітр",
    "ноги",
    "галонів",
    "дюймів",
    "унцій",
    "фунтів",
    "кварти",
    "дворів",
    "кімната",
    "секунд",
    "хвилин",
    "години",
    "днів",
    "тижнів",
    "місяців",
    "років"
  ],
  "region_types": {
    "State": "держава",
    "Territory": "Територія",
    "Province": "провінція"
  },
  "transaction_status": {
    "RequireAction": "Потрібна дія",
    "Processing": "Обробка",
    "Canceled": "Скасовано",
    "Succeeded": "Вдалось"
  },
  "placeholders": {
    "name": "Джон Кокс",
    "email": "your-mail@mail.com",
    "phone": "+1 000 0000",
    "language": "Оберіть мову..",
    "friend_email": "Електронна пошта вашого друга...",
    "friend_name": "Opt. Ім'я вашого друга",
    "select_date": "Виберіть дату..."
  },
  "notification": {
    "confirm": "Підтвердьте",
    "confirm_message": "Зміни успішно збережено.",
    "error": "Помилка",
    "message": "повідомлення",
    "caution": "Обережно",
    "warning": "УВАГА",
    "award": "Вітаю",
    "error_message": "На жаль, сталася помилка.",
    "congratulation": "Вітаю",
    "coming_soon": "Незабаром",
    "on_fetching_data": "Прийом інформації..",
    "new_pwa_version": "Нова версія доступна зараз. Бажаєте оновити програму?",
    "over_license_limit": "Понад ліміт ліцензії",
    "update_license": "Оновіть ліцензію",
    "required": "вимагається",
    "invalid_email": "Недійсна електронна адреса",
    "invalid_domain": "Недійсний домен",
    "invalid_min_length": "Мінімальна довжина має бути {length}",
    "invalid_min_array_length": "Виберіть принаймні {length} елементів",
    "invalid_max_chars": "Максимальна кількість символів: {maxCount}",
    "invalid_url": "Недійсна URL-адреса",
    "country_invalid": "Виберіть країну призначення!",
    "postal_code_invalid": "Встановіть дійсний поштовий індекс!"
  },
  "colors": {
    "#D32F2F": "червоний",
    "#C2185B": "рожевий",
    "#7B1FA2": "фіолетовий",
    "#512DA8": "Темно-фіолетовий",
    "#303F9F": "Синій індиго",
    "#1976D2": "Синій",
    "#0288D1": "Блакитний",
    "#0097A7": "Бірюзовий синій",
    "#00796B": "Гусака зелена",
    "#388E3C": "Зелений",
    "#689F38": "Світло-зелений",
    "#AFB42B": "Лімузин",
    "#FBC02D": "Жовтий",
    "#FFA000": "Янтарний",
    "#F57C00": "Помаранчевий",
    "#E64A19": "Блискучий апельсин",
    "#5D4037": "Коричневий",
    "#616161": "Сірий",
    "#455A64": "Сірий синій",
    "#FFD700": "Золотий",
    "#C0C0C0": "Срібло",
    "#b76e79": "Золота троянда",
    "#383838": "Матовий чорний",
    "#FFFFFF": "Білий",
    "#FFF": "Білий",
    "#000000": "Чорний",
    "#000": "Чорний",
    "#7d263a": "Бордовий",
    "#FD9F17": "золото",
    "#229DBF": "Аква",
    "#6DC9E2": "Аква Трибленд",
    "#413B2D": "Армія",
    "#474747": "Асфальт",
    "#E6195C": "ягода",
    "#B2184C": "Ягідна трибленда",
    "#FC7F5F": "Спалений апельсин",
    "#80011F": "Кардинал",
    "#382829": "Шоколад",
    "#F06336": "Кораловий",
    "#FAE7C9": "вершки",
    "#6B2257": "смородина",
    "#222127": "Темно-сірий",
    "#0D5A74": "Deep Teal",
    "#00582F": "Вічнозелений",
    "#214C30": "Ліс",
    "#DC2867": "Фуксія",
    "#38561F": "Келлі",
    "#5C884D": "листок",
    "#558450": "Світла Аква",
    "#96B5C9": "Блакитний",
    "#DCAFCE": "Бузок",
    "#D3E1A4": "Вапно",
    "#9DE7C2": "Монетний двір",
    "#F6EAD2": "Природні",
    "#1A1F35": "флот",
    "#404624": "Оливкова",
    "#271020": "Слива",
    "#A8355C": "Малина",
    "#D6BEA6": "М'який крем",
    "#BEA994": "Тан",
    "#0DB2AE": "Чирок",
    "#A86EA9": "Фіалка",
    "#36454F": "Деревне вугілля",
    "#b3b0ab": "вуглецевий сірий",
    "#463e3d": "Вугільний верес",
    "#282d3c": "Темно-синій піджак"
  },
  "address_info": {
    "name": "Ім'я",
    "tel": "Телефон",
    "email": "Електронна пошта",
    "country": "Країна",
    "city": "Місто",
    "state": "держава",
    "address": "адреса",
    "building_number": "Номер будівлі",
    "building_unit": "одиниця",
    "postcode": "Поштовий індекс",
    "note": "Примітка",
    "county": "графство"
  },
  "product_types": {
    "physical": "Фізичний",
    "physical_description": "Фізичні продукти, такі як: мобільні телефони, книги, електронні компоненти.",
    "virtual": "Віртуальний",
    "virtual_description": "Продукти, зручні для Інтернету, такі як: карта поповнення, бронювання готелю, поповнення рахунку в іграх.",
    "file": "Файл",
    "file_description": "Усі дозволені файли, як-от відео онлайн-курсу, документи для завантаження.",
    "service": "Обслуговування",
    "service_description": "Послуги: ремонт, транспорт, навчання.",
    "subscription": "Підписка",
    "subscription_description": "Підписки та виставлення рахунків за продукти, послуги чи вміст."
  },
  "license": {
    "free": "Безкоштовно",
    "startup": "Стартап",
    "company": "Компанія",
    "enterprise": "Підприємство"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "Томан",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW",
    "GHS": "GHS",
    "ZWD": "ZWD",
    "IQD": "IQD",
    "SYP": "SYP"
  },
  "variants": {
    "color": "Колір",
    "volume": "Розмір",
    "count_in_pack": "Порахуйте в пачці",
    "weight": "Вага",
    "type": "Матеріал",
    "style": "Стиль"
  },
  "delivery_state": {
    "check_queue": "Очікування огляду",
    "order_confirm": "Підтвердження замовлення",
    "preparing_order": "Підготовка",
    "sent_order": "При доставці",
    "to_customer": "Доставлено"
  },
  "status": {
    "unpaid": "Неоплачений",
    "paid": "Оплачено",
    "canceled": "Скасовано",
    "completed": "Влаштувалися",
    "reserved": "Зарезервований",
    "COD": "COD",
    "sold": "Продано",
    "open": "ВІДЧИНЕНО",
    "cancel": "Скасовано",
    "active": "Активний",
    "inactive": "неактивний",
    "debug": "Налагоджувати",
    "live": "жити",
    "test": "Тест",
    "connected": "Підключено",
    "disconnected": "Відключено",
    "accept": "Прийняти",
    "reject": "Відхилити",
    "pending": "Очікується",
    "rejected": "Відхилено",
    "accepted": "Прийнято"
  },
  "dimensions": {
    "cm": "см",
    "km": "км",
    "kg": "кг"
  },
  "transportation_type": {
    "motorbike": "мотоцикл",
    "motorbike_description": "Середня вага в межах кількох кілометрів.",
    "cargo_small": "Невеликий вантаж",
    "cargo_small_description": "Багатокілометровий легкий вантаж.",
    "cargo": "Вантаж",
    "cargo_description": "Середня вага в межах кількох кілометрів.",
    "truck": "Вантажівка",
    "truck_description": "Насипні або важкі вантажі всередині країни.",
    "fast_post": "Швидкий пост",
    "fast_post_description": "Швидка відправка через поштове відділення.",
    "post": "Звичайний пост",
    "post_description": "Звичайна пошта через пошту.",
    "airplane": "Авіапошта",
    "airplane_description": "Вітчизняні та іноземні легкі та середні вантажі.",
    "bicycle": "Чисте відправлення",
    "bicycle_description": "Легкий вантаж, в межах кількох сотень ярдів від немоторних транспортних засобів.",
    "global": "Глобальні перевезення",
    "global_description": "Доставка за кордон повітряним, морським або наземним транспортом.",
    "pickup": "Самовивіз",
    "pickup_description": "Клієнти забирають товари у вашому фізичному магазині або на складі."
  },
  "article": {
    "login_to_see_error": "Увійдіть, щоб отримати доступ до статті",
    "create_new_action": "Створити новий вміст",
    "menu_title": "Меню",
    "menu": {
      "edit": "Режим редагування",
      "view_mode": "Режим перегляду",
      "delete": "Видалити статтю"
    },
    "schedule_action": "Бажаєте запланувати публікацію?",
    "schedule_title": "Заплануйте автоматичну публікацію",
    "edit_mode": "Редагувати",
    "public_view_mode": "Суспільний погляд",
    "publish_at": "Опублікувати за адресою",
    "published": "Опубліковано",
    "draft": "Чернетка",
    "saving": "Збереження",
    "save_and_publish_action": "Зберегти та опублікувати",
    "save_draft_action": "Зберегти чернетку",
    "private": "Приватний",
    "public": "Громадський",
    "category_input": "Категорія",
    "category_input_message": "Виберіть категорію статті",
    "parent_input": "Батьківська категорія",
    "parent_input_message": "Виберіть вміст батька",
    "schedule_input": "Розклад",
    "schedule_input_placeholder": "Якщо ви хочете, щоб історія була опублікована в певний час.",
    "schedule_view_action": "Переглянути розклад публікації",
    "author_title": "Написано",
    "read_time": "Час навчання",
    "read_time_unit": "Хвилини",
    "claps_action": "Плески в долоні",
    "claps": "Плески в долоні",
    "likes": "Подібно до",
    "about_author": "Про автора",
    "updated_at": "Оновлено",
    "wrote_at": "Написано на",
    "now": "Тепер",
    "follow_action": "Слідкуйте",
    "followed": "Слідкує",
    "report_and_delete_action": "Повідомте та видаліть цю статтю",
    "report_action": "Повідомити про зловживання",
    "you_reported_this_article": "У цій статті вже є повідомлення про порушення.",
    "add_to_publication_action": "Додати до публікації",
    "author_socials": "Автор у соцмережах",
    "share": "Поділіться",
    "report_dialog": {
      "report_and_delete_title": "Повідомте про порушення та видаліть вміст",
      "report_title": "Повідомити про цей вміст як образливий",
      "message": "Яка причина подання цього вмісту? Виберіть один із наступних варіантів.",
      "accept_and_delete_action": "Підтвердьте та видаліть вміст"
    },
    "schedule_dialog": {
      "title": "Розклад випуску контенту",
      "publish_at": "Опублікувати за адресою",
      "last_edit": "Останнє редагування",
      "view_action": "Переглянути статтю"
    },
    "notifications": {
      "update_success_title": "Подати інформацію",
      "update_success": "Стаття успішно оновлена.",
      "update_error": "Введена інформація недійсна.",
      "delete_error": "Ви не можете видалити цю статтю!",
      "report_and_delete_success_title": "Повідомити та видалити",
      "report_and_delete_success_message": "Статтю успішно видалено.",
      "report_success_title": "Звітна стаття",
      "report_success_message": "Ваш звіт про цю статтю опубліковано."
    },
    "alert": {
      "delete_article": {
        "title": "Видалити статтю",
        "message": "Ви впевнені, що хочете назавжди видалити цю статтю?",
        "action": "Видалити"
      }
    },
    "edit_window": {
      "title": "Виберіть Текст зображення та підсумок",
      "digest": "Резюме"
    },
    "editor": {
      "title_placeholder": "Назва..",
      "body_placeholder": "Пишіть чудовий контент..",
      "accept_file_types_error": "Цей формат файлу неприйнятний:",
      "max_file_size_error": "Цей файл завеликий:",
      "notifications": {
        "image_uploaded_success": "Зображення успішно збережено",
        "image_uploaded_failed": "Помилка завантаження зображення."
      },
      "embed_placeholder": "Введіть код iframe, Facebook, Youtube або будь-яку іншу URL-адресу та натисніть Enter.",
      "embed_caption_placeholder": "Введіть назву (необов'язково)",
      "images_caption_placeholder": "Введіть назву для цього зображення .."
    }
  },
  "article_report": {
    "inappropriate": "Зміст цієї статті є невідповідним.",
    "fake": "Це фальшиво і оманливо.",
    "spam": "Цей елемент надіслано в спам і скопійовано.",
    "scam": "Очікується, що це спричинить зловмисне програмне забезпечення, віруси або збій системи.",
    "hacked": "Схоже, цей сайт зламали.",
    "offensive": "Зміст і лексика мови є неетичними та неповажними.",
    "violent": "Я вважаю, що цей вміст містить порнографію та порушує закони.",
    "harassment": "Я думаю, що це расизм.",
    "hate": "Я думаю, що мова йде про пропаганду насильства.",
    "infringe": "Це порушує мої права."
  },
  "comments": {
    "new_action": "Натисніть, щоб залишити коментар..",
    "title": "Коментарі",
    "body_placeholder": "Ваш коментар або повідомлення",
    "send_action": "Надіслати коментар",
    "body_is_empty_error": "Коментар пустий!",
    "comments": "Коментарі",
    "no_comments": "Напишіть перший коментар...",
    "load_more_action": "Отримайте більше коментарів..",
    "cant_send_comment": "Ви не можете додати новий пост.",
    "cant_remove_this_comment": "Ви не можете видалити цей коментар!",
    "product_buyer": "Покупець",
    "delete_alert": {
      "title": "Видалити коментар",
      "message": "Видалити цей коментар?",
      "action": "Видалити"
    },
    "notifications": {
      "delete_success": "Ваш коментар успішно видалено."
    },
    "first_send": "Перший пост",
    "comment_at": "Увімкнено",
    "edit_comment": "Редагувати коментар",
    "my_comments": "Мої коментарі"
  },
  "customer_club": {
    "bronze": "Бронза",
    "silver": "Срібло",
    "gold": "Золотий",
    "platinum": "платина",
    "diamond": "діамант"
  },
  "application_categories": {
    "tracking": "Перевірка поведінки користувача",
    "payment": "оплата",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "Перевезення",
    "automation": "Автоматизація",
    "inventory": "Складське господарство",
    "accounting": "Бухгалтерський облік",
    "marketing": "Маркетинг",
    "advertising": "Реклама",
    "staff": "Персонал",
    "incentive": "Заохочення",
    "shop": "Магазин"
  },
  "social_network": {
    "instagram": "Instagram",
    "telegram": "Telegram",
    "googleplay": "Google Play",
    "appstore": "App Store",
    "twitter": "Twitter",
    "linkedin": "Linkedin",
    "medium": "Середній",
    "selldone": "Продано",
    "facebook": "Facebook",
    "pinterest": "Pinterest",
    "whatsapp": "WhatsApp",
    "skype": "Skype",
    "facebook_messenger": "Facebook Messenger"
  },
  "form_builder": {
    "add_item_action": "Додати новий елемент",
    "title_input": "Назва",
    "name_input": "Ім'я змінної",
    "value_input": "Цінності",
    "value_input_message": "Список параметрів користувача",
    "default": "Значення за замовчуванням",
    "types": {
      "simple": "Просто",
      "selective": "Вибірковий",
      "switch": "Перемикач",
      "file": "Файл",
      "number": "Номер"
    },
    "placeholder_input": "Заповнювач",
    "file_type_input": "Прийнятні типи файлів",
    "file_type_message": "jpeg, png, zip, ..."
  },
  "virtual_order_info_summery": {
    "title": "Назва продукту",
    "reserved_at": "Дата Реєстрації",
    "total_price": "Загальна кількість",
    "discount": "Знижка",
    "final_price": "Остаточна сума",
    "payment_status": "Стан платежу",
    "payment_status_waiting": "Очікування оплати",
    "payment_status_paid": "Оплачено",
    "buyer": "Покупець"
  },
  "virtual_item_info": {
    "title": "Віртуальний предмет",
    "outputs": {
      "title": "Вихідна інформація",
      "sub_title": "Конфіденційна інформація цього пункту",
      "message": "Ця інформація буде показана користувачеві після покупки товару."
    },
    "inputs": {
      "title": "Потрібна інформація",
      "sub_title": "Потрібна інформація про покупця",
      "message": "Покупець повинен ввести запитувану інформацію у форму"
    },
    "notifications": {
      "inputs_set_success": "Інформаційна форма успішно зареєстрована.",
      "confirm_by_admin_success": "Завершення замовлення підтверджено.",
      "confirm_by_buyer_success": "Завершення замовлення підтверджено."
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "Це замовлення не може бути прийнято платіжною накладною на накладну плату.",
    "payment_returned": "Оплата замовником повертається.",
    "payment_fraud": "Платіж було визнано шахрайством.",
    "location_out_of_service": "Місцезнаходження клієнта не обслуговується.",
    "user_not_responding": "Клієнт не відповідав на дзвінки.",
    "shop_owner_fault": "Під час заповнення інформації працівниками магазину сталася помилка.",
    "lack_of_inventory": "Немає в наявності.",
    "legal_restriction": "Неможливо зробити замовлення через юридичні обмеження.",
    "pricing_fault": "Помилка в ціні продавця.",
    "system_fault": "Системна помилка."
  },
  "basket_order_info_summery": {
    "receiver": "Приймач",
    "phone": "тел",
    "reserved_date": "Дата покупки",
    "total_price": "Загальна кількість",
    "discount": "Знижка",
    "final_price": "Остаточна сума",
    "address": "Адреса доставки",
    "payment_status": "Стан платежу"
  },
  "basket_status": {
    "open": "ВІДЧИНЕНО",
    "reserved": "Зарезервований",
    "paid": "Оплачено",
    "canceled": "Скасовано",
    "cod": "Оплата при доставці",
    "receipt_added": "Квитанцію додано",
    "payment_processing": "Обробка платежів"
  },
  "basket_delivery_state": {
    "rejected": "Відхилено",
    "reject_reason_not_found": "Причина невідома.",
    "step_1": "Огляд",
    "step_2": "Підтвердження",
    "step_3": "Підготовка",
    "step_4": "При доставці",
    "step_5": "Доставлено"
  },
  "basket_return_request_view": {
    "title": "Запит на повернення",
    "delivery_date": "Дата доставки",
    "return_date": "Дата запиту",
    "items_count": "Кількість повернутих речей",
    "items_count_unit": "предмет(и)",
    "reason": "Причина",
    "description": "Опис",
    "status": "Статус",
    "download_image": "Завантажити зображення",
    "download_film": "Завантажити відео",
    "download_voice": "Завантажити голос",
    "accept_by_admin_action": "Прийняти запит",
    "reject_by_admin_action": "Відхилити запит",
    "message_for_admin": "Відповідно до угоди, яку ви прийняли, використовуючи Selldone, ви повинні зв’язатися з покупцем і інформувати його/її про процес повернення його/її замовлення. Це необхідно зробити, якщо запит прийнято або відхилено та отримана повна згода покупця.",
    "notifications": {
      "update_status_success": "Статус запиту оновлено."
    }
  },
  "basket_list": {
    "return_count": "Повернення: {count} номер",
    "table": {
      "row": "рядок",
      "image": "Зображення",
      "product_name": "Продукт",
      "variant": "Варіант",
      "warranty": "Гарантії",
      "count": "Рахувати",
      "price": "ціна"
    }
  },
  "return_request_list": {
    "count": "Номер для посилань",
    "return_warranty": "Гарантія повернення грошей",
    "return_warranty_unit": "день(и)",
    "table": {
      "code": "Код замовлення",
      "product": "Продукт",
      "delivery_at": "Дата отримання",
      "state": "Статус",
      "reason": "Причина",
      "return_warranty_period": "Гарантійний термін"
    }
  },
  "data_toolbar": {
    "search": "Пошук",
    "sort_by": "Сортувати за",
    "count_item": "Показати {item} елементів"
  },
  "sort": {
    "created_at": "Створити дату",
    "updated_at": "Редагувати дату",
    "title": "Назва",
    "description": "Опис",
    "like": "Популярність",
    "power": "Плески в долоні",
    "product_type": "Тип продукту",
    "discount": "Знижка",
    "rate": "Рейтинг",
    "rate_count": "Кількість оцінок",
    "category": "Категорія",
    "product": "Продукт",
    "body": "Зміст",
    "card_type": "Тип карти",
    "card_number": "Номер картки",
    "balance": "Баланс",
    "paid": "Витрачена сума",
    "currency": "Валюта",
    "expire_at": "Термін придатності",
    "discount_code": "Код на знижку",
    "discount_percent": "Знижка",
    "discount_limit": "Ліміт знижки",
    "max_count": "Максимальна кількість",
    "used_count": "Використовується",
    "start_date": "Дата початку",
    "end_date": "Дата закінчення",
    "total_discount_amount": "Загальні знижки",
    "initial_charge": "Початковий заряд",
    "total_count": "Загальна кількість",
    "amount_paid": "Виплачувана сума",
    "name": "Ім'я",
    "published": "Опубліковано",
    "visits": "Відвідування",
    "color": "Колір",
    "landing_page": "Цільова сторінка",
    "enable": "Увімкнути",
    "fix_commission": "Фіксована комісія",
    "percent_commission": "Відсоток комісії",
    "payment_at": "Дата оплати",
    "issued_at": "Дата випуску",
    "payment": "оплата",
    "website": "веб-сайт",
    "email": "Електронна пошта",
    "user": "Користувач",
    "code": "код",
    "schedule_at": "Дата розкладу",
    "sender": "Відправник",
    "in_que": "В черзі",
    "sent": "Надісланий",
    "shop": "Магазин",
    "quantity": "Кількість",
    "amount": "Сума",
    "jobs": "Вакансія враховується",
    "success": "Підрахунок успіху",
    "fail": "Підрахунок невдач",
    "distance": "Відстань",
    "duration": "Тривалість",
    "reset_at": "Скинути дату",
    "delivery_person": "Особа",
    "delivery_service": "Обслуговування",
    "date": "Дата",
    "order": "Замовити",
    "order_id": "Ідентифікатор замовлення",
    "status": "Статус",
    "price": "ціна",
    "count": "Рахувати",
    "final_price": "Остаточна ціна",
    "charge": "Зарядити",
    "mention": "Згадайте",
    "officer": "Офіцер",
    "registered": "Зареєстровано",
    "purchased": "Придбано",
    "sex": "Стать"
  },
  "search_box": {
    "result": "Результати пошуку",
    "tips": "Пошук продуктів і категорій",
    "label": "Шукати...",
    "category": "Категорія"
  },
  "lead_status": {
    "physical_fast_delivery": "Миттєва доставка",
    "physical_under_24h_delivery": "Доставте протягом наступних {lead} годин",
    "physical_over_24h_delivery": "Підготовка та подача з наступних {days} днів",
    "virtual_fast_prepare": "Миттєва доставка",
    "virtual_under_24h": "Буде виконано протягом наступних {lead} год",
    "virtual_over_24h": "Буде виконано з наступних {days} днів"
  },
  "return_request_state": {
    "pending": "Очікується",
    "accepted": "Підтверджено",
    "rejected": "Відхилено"
  },
  "return_order_reason": {
    "physical": {
      "U1": "Невідповідність товару",
      "U2": "Немає товару в транспортній упаковці",
      "U3": "Поломка упаковки або продукту",
      "U4": "Підробка пакету або серійного номера",
      "U5": "Деякі предмети з посилки відсутні",
      "U6": "Товар не оригінальний",
      "U7": "Товар не відповідає специфікаціям"
    }
  },
  "image_uploader": {
    "label": "Перетягніть або <u>виберіть файл</u>",
    "max_size": "Максимально дозволений розмір: {size}"
  },
  "timespan": {
    "Morning": "8 ранку - 12 вечора",
    "Evening": "з 12:00 до 18:00",
    "Night": "18:00-12:00",
    "Instant": "Миттєва публікація"
  },
  "week_day": {
    "Saturday": "субота",
    "Sunday": "неділя",
    "Monday": "понеділок",
    "Tuesday": "вівторок",
    "Wednesday": "середа",
    "Thursday": "четвер",
    "Friday": "п'ятниця"
  },
  "payment_form": {
    "title": "Виберіть Спосіб оплати",
    "gift_cards_input": "Подарункові карти",
    "gift_cards_input_empty": "Подарункових карток не знайдено..",
    "more": "Інший",
    "pay_amount_by_gift_cards": "Оплата платіжною карткою",
    "select_payment_method": "Виберіть спосіб оплати з наведених нижче варіантів.",
    "payment_amount_remained": "Сума платежу, що залишилася",
    "payment_amount": "Виплачувана сума",
    "all_paid_by_gift_cards": "Вітаємо, вам не потрібно платити за це замовлення. Натисніть клавішу Оплатити подарунковою карткою.",
    "pay_by_gift_cards_action": "Оплатіть замовлення платіжною карткою",
    "order_free_payment": "Вітаємо, Ваше замовлення безкоштовне!",
    "order_free_payment_action": "Замовляйте безкоштовно зараз",
    "qr": {
      "address": "Платіжна адреса",
      "amount": "Сума"
    }
  },
  "discount_input": {
    "limit": "{percent}% знижки до {limit} {currency}",
    "action": "Додайте код знижки",
    "code_input": "Код на знижку",
    "notifications": {
      "add_success": "Вітаємо, дійсний код знижки."
    }
  },
  "gift_card": {
    "inactive": "Картка вимкнена",
    "expire": "Термін дії",
    "transfer": "Передача",
    "send_to_friend": "Надіслати другу"
  },
  "count_down": {
    "days": "День",
    "hours": "годину",
    "minutes": "Хвилини",
    "seconds": "Секунди"
  },
  "gift_status": {
    "Unpaid": "очікуючи квитанцію",
    "Paid": "Оплачено",
    "Rejected": "Відхилено",
    "Canceled": "Скасовано"
  },
  "gift_program_status": {
    "Airdrop": "Платіжна система",
    "Advertising": "Реклама",
    "PersonalGift": "Особистий подарунок",
    "ShopGift": "Сувенірна лавка"
  },
  "currency_selector": {
    "label": "Валюта"
  },
  "need_login": {
    "title": "увійти",
    "login_sms": "Вхід по SMS",
    "login_google": "Увійдіть за допомогою Google",
    "login_facebook": "Увійти через Facebook",
    "login_account": "Вхід через Selldone",
    "register": "Новий користувач? Зареєструйтеся зараз.",
    "mobile_input": "Введіть свій мобільний",
    "verification_code": "Код підтвердження",
    "msg_title": "Привіт,",
    "msg_body": "Будь ласка, увійдіть. Це займає всього кілька секунд.",
    "login_apple": "Увійдіть через Apple",
    "login_email": "Вхід по електронній пошті",
    "email_login_step_1": "Будь ласка, вкажіть дійсну електронну адресу, і ми надішлемо на неї код входу. Реєстрація не потрібна.",
    "email_login_step_2": "Ви впевнені, що правильно ввели адресу електронної пошти? Ми надішлемо код входу на вказану електронну адресу, тому переконайтеся, що він точний.",
    "email_login_step_3": "Ми надіслали код на вашу електронну пошту. Зверніть увагу, що термін дії коду закінчується через 10 хвилин."
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "Магазин золота 5 років"
    },
    "GOLDEN_2YEAR": {
      "name": "Магазин золота 4 роки"
    },
    "GOLDEN_3YEAR": {
      "name": "Магазин золота 3 роки"
    },
    "GOLDEN_4YEAR": {
      "name": "Магазин золота 2 роки"
    },
    "GOLDEN_5YEAR": {
      "name": "Золотий магазин на 1 рік"
    },
    "TOKEN_OWNER_1M": {
      "name": "Золотий інвестор"
    },
    "TOKEN_OWNER_10M": {
      "name": "Діамантовий інвестор"
    },
    "TOKEN_OWNER_100M": {
      "name": "Рубіновий інвестор"
    },
    "COMMUNITY_LOYAL": {
      "name": "Член вищої спільноти комунікаційних мереж"
    },
    "GOLD_SUPPLIER": {
      "name": "Постачальник золота"
    },
    "GOLD_SELLER": {
      "name": "Торговець золотом"
    },
    "CONTENT_SUPERMAN": {
      "name": "Найкращий виробник контенту"
    },
    "NINJA": {
      "name": "ніндзя"
    },
    "STAR": {
      "name": "Зірка"
    },
    "GUARDIAN": {
      "name": "Чудове обслуговування клієнтів"
    },
    "KING": {
      "name": "Король ринку"
    }
  },
  "cookie": {
    "title": "Цей веб-сайт використовує файли cookie",
    "message": "Цей веб-сайт використовує файли cookie для покращення роботи користувача. Використовуючи наш веб-сайт, ви погоджуєтесь на всі файли cookie відповідно до нашої Політики щодо файлів cookie.",
    "preferences_action": "Керувати налаштуваннями",
    "agree_action": "Я згоден"
  },
  "basket_item_message": {
    "title": "Необхідна інформація для цього елемента",
    "save_actions": "Зберегти повідомлення",
    "notifications": {
      "success": "Ваші вхідні дані збережено."
    },
    "product_inputs_preview_message": "Ці параметри налаштування доступні для замовленого продукту. Щойно товар буде додано до кошика, ви зможете внести зміни тут."
  },
  "faq": {
    "faq": "Часті запитання",
    "title": "Питання та відповіді",
    "sub_title": "Те, що ви просили нас зробити.",
    "message": "Шукайте відповідь на своє запитання серед відповідей нижче. Запитайте нас, якщо питання залишилися без відповіді.",
    "add_question_action": "Задайте нове запитання",
    "read_more": "Детальніше ..",
    "load_more": "Більше питань..",
    "main_page": "Головна сторінка FAQ",
    "add_new": "Надіслати нове запитання",
    "login_alert": "Увійдіть, щоб поставити запитання.",
    "question_input": "Питання",
    "question_input_placeholder": "Задайте своє запитання.",
    "notifications": {
      "success_add": "Ваше запитання успішно надіслано."
    }
  },
  "rating_labels": [
    "Дуже погано",
    "Погано",
    "Нормальний",
    "добре",
    "Відмінно"
  ],
  "map_view": {
    "address_detail": "Деталі адреси",
    "change": "Змінити",
    "select": "Виберіть",
    "not_found_address": "Значення не знайдено",
    "enter_address_hint": "Введіть адресу призначення",
    "enter_your_address": "Введіть свою адресу.",
    "postal_code": "Поштовий індекс",
    "phone_input": "Телефон {type}",
    "building_number": "Номер будівлі",
    "building_unit": "одиниця",
    "full_name_input": "Повне ім'я {type}",
    "save_detail_action": "Збережіть деталі",
    "more_detail_input": "Більше опису",
    "add_address_to_list": "Додати адресу до списку",
    "address_title_input": "Мітка адреси (обов'язково)",
    "notifications": {
      "save_in_list": "Цю адресу збережено у вашому списку з усіма деталями.",
      "edit_success": "Нові значення адреси збережено в {title}."
    },
    "delete_address_dialog": {
      "title": "Видалити адресу",
      "message": "Ви впевнені, що хочете видалити цю адресу?",
      "action": "Видалити адресу"
    }
  },
  "comment_manager": {
    "can_not_edit": "Неможливо редагувати цей коментар!",
    "comment_input_empty": "Текст повідомлення порожній!",
    "article_not_saved": "Збережіть статтю!"
  },
  "wheel_fortune": {
    "title": "Грай і виграй",
    "message": "Вартість кожної гри становить 10 фішок. Зараз у вас є фішка {chips}. Отримайте більше фішок, купивши в магазині.",
    "win_message": "Вітаємо, ти переміг!",
    "lost_message": "Вибачте, ви програли гру.",
    "try_again": "Ви можете спробувати ще раз"
  },
  "json": {
    "add": "Додайте структурні дані",
    "add_message": "Створіть нові структурні дані",
    "structures": "Конструкції",
    "book": {
      "title": "Книга",
      "desc": "Дії з книгою, які дозволяють користувачам купувати книгу, яку вони знаходять безпосередньо з результатів пошуку."
    },
    "occupation": {
      "title": "Орієнтовна заробітна плата",
      "desc": "Інформація про розрахунок заробітної плати, як-от діапазони заробітної плати та середня заробітна плата на основі регіону для типів вакансій, відображається в пошуку роботи в Google."
    },
    "course": {
      "title": "курс",
      "desc": "Освітні курси, які відображаються в списку постачальника послуг. Курси можуть містити назву курсу, постачальника та короткий опис."
    },
    "howto": {
      "title": "Як",
      "desc": "Інструкція містить набір кроків для успішного виконання завдання, показуючи відео, зображення та текст."
    },
    "recipe": {
      "title": "Рецепт",
      "desc": "Рецепти, які відображаються як індивідуальний багатий результат або частина каруселі хоста."
    }
  },
  "support": {
    "Financial": "фінансовий",
    "Technical": "Технічний",
    "Advisor": "радник"
  },
  "condition": {
    "new": "Новий",
    "refurbished": "Відремонтований",
    "used": "Використовується",
    "used_fair": "Використовується справедливо",
    "used_good": "Вживаний добре",
    "used_like_new": "Використовувався як новий"
  },
  "variant_filter": {
    "title": "Фільтр варіантів продукту",
    "only_available": "В наявності"
  },
  "service": {
    "task": {
      "title": "Завдання",
      "message": "Список завдань, що виконуються в цій службі."
    },
    "appointment": {
      "title": "Призначення",
      "message": "Виберіть час тижня з наступних, виходячи з дня та години, які вам підходять."
    },
    "booking": {
      "title": "Бронювання",
      "message": "У календарі нижче вкажіть період часу, коли ви хочете зробити бронювання."
    },
    "subscription": {
      "title": "Підписка"
    },
    "charge": {
      "title": "Зарядити"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "Фіксована ціна",
      "message": "У цьому типі ціноутворення ціна товару є фіксованою сумою, і покупець не має потреби вимагати розрахунок ціни."
    },
    "ESTIMATION": {
      "title": "Оцінка ціни",
      "message": "Ціна на товари та послуги буде певною мірою розрахована продавцем при оформленні замовлення, рахунки на оплату можуть бути змінені або додані під час обслуговування."
    },
    "AGREEMENT": {
      "title": "Ціноутворення за договором",
      "message": "Кінцева ціна товарів або послуг не буде змінена продавцем після розміщення замовлення."
    },
    "BID": {
      "title": "Ставка / Аукціон",
      "message": "Товар буде проданий потенційними покупцями за найвищою ціною."
    }
  },
  "map": {
    "title": "Пункт призначення для отримання продукції",
    "confirm": "Встановити місце розташування",
    "address": "Пункт призначення",
    "receptor": "Приймач"
  },
  "ShopBots": {
    "telegram": "Telegram"
  },
  "article_tags": {
    "title": "Теги вмісту",
    "tags_input": "Мітки",
    "tags_input_message": "Теги Список цієї статті",
    "notification": {
      "add_success": "Додано теги"
    }
  },
  "difficulties": {
    "very_complicated": "Дуже складно",
    "hard": "важко",
    "intermediate": "Середній",
    "easy": "легко"
  },
  "billing_period": {
    "Daily": "Щодня",
    "Weekly": "Щотижня",
    "Monthly": "Щомісячно",
    "Every3Months": "Кожні 3 місяці",
    "Every6Months": "Кожні 6 місяців",
    "Yearly": "Щорічно"
  },
  "buyer_rating_statement": {
    "between1_2": "Ох не добре!",
    "between2_3": "Все добре!",
    "between3_4": "Людям подобається!",
    "between4_5": "Люди люблять це!"
  },
  "seasons": {
    "spring": "Весна",
    "summer": "Літо",
    "autumn": "осінь",
    "winter": "Зима"
  }
};