export default {
  "currency_default": "USD",
  "language_default": "en",
  "selldone": "Selldone",
  "store": "ivenkile",
  "not_exist": "Ayikho",
  "error": "Impazamo",
  "active": "Iyasebenza",
  "inactive": "Ayisebenzi",
  "required_value": "Amaxabiso afunekayo",
  "original_warranty": "Isiqinisekiso soMveliso sokuqala",
  "return_warranty_days": "{days} isiqinisekiso sokubuya kweentsuku",
  "no_return_warranty": "Akukho kubuya",
  "reed_agree_terms": "Ndiyifundile imigaqo yokusetyenziswa kunye nomgaqo-nkqubo wabucala kwaye ndiyavumelana nawo.",
  "commons": {
    "Currency": "Imali",
    "COD": "COD",
    "State": "Umbuso",
    "Price": "ixabiso",
    "order_price": "Imali yeodolo",
    "VAT": "VAT",
    "Discount": "Isaphulelo",
    "In_Stock": "Ikhona evenkileni",
    "Variants": "Ukwahluka",
    "No_variants": "Akukho mahluko",
    "all": "ZONKE",
    "today": "Namhlanje",
    "yesterday": "Izolo",
    "license": "Ilayisensi",
    "home": "Ekhaya",
    "support": "Inkxaso",
    "messages": "Imiyalezo",
    "no_message": "Akukho myalezo",
    "empty": "Akunanto",
    "phone": "Ifowuni",
    "address": "idilesi",
    "name": "Igama",
    "password": "Inombolo yokuvula",
    "email": "I-imeyile",
    "mobile": "Iselula",
    "login": "Ngema",
    "register": "Bhalisa",
    "select_account": "Khetha iakhawunti",
    "online": "Kwi-intanethi",
    "offline": "Ngaphandle kweintanethi",
    "finish": "Gqiba",
    "finished": "Igqitywe tu",
    "preview": "Jonga kwangaphambili",
    "free": "Mahala",
    "free_completely": "Ubhaliso lwasimahla ngokupheleleyo",
    "fee": "Umrhumo",
    "month": "Inyanga",
    "months": "Iinyanga",
    "faq": "Imibuzo ebuzwa qho",
    "question": "Umbuzo",
    "answer": "Phendula",
    "create_date": "Yenza umhla",
    "update_date": "Umhla wohlaziyo",
    "start_date": "Umhla wokuqala",
    "end_date": "Umhla wokuphela",
    "social": "Ezentlalontle",
    "total": "Iyonke",
    "orders": "Iiodolo",
    "sessions": "Iiseshoni",
    "product_views": "Iimbono zemveliso",
    "add_to_carts": "Yongeza kwiinqwelo",
    "checkouts": "Phuma",
    "payments": "Intlawulo",
    "organic_search": "Uphendlo lwendalo",
    "other": "Okunye",
    "landing_page": "Iphepha lokufika",
    "discount_code": "Ikhowudi yesaphulelo",
    "total_sell": "Iintengiso zizonke",
    "details": "Iinkcukacha",
    "currency": "Imali",
    "amount": "Isixa",
    "published": "Ipapashiwe",
    "draft": "Uyilo",
    "save_changes": "Gcina Utshintsho",
    "source": "Umthombo",
    "medium": "Phakathi",
    "url": "Url",
    "revenue": "Ingeniso",
    "performance": "Ukusebenza",
    "term": "Ixesha",
    "content": "Umxholo",
    "session": "Iseshoni",
    "product": "Imveliso",
    "add": "Yongeza",
    "checkout": "Phuma",
    "payment": "Intlawulo",
    "more_options": "Olunye ukhetho",
    "full_name": "Igama eliphelele",
    "tel": "Umnxeba",
    "about_me": "Ngam",
    "request_checking": "Cela ukujonga",
    "passport": "Ipasi",
    "birthday": "Usuku lokuzalwa",
    "country": "Ilizwe",
    "city": "Isixeko",
    "gender": "Isini",
    "offer": "Unikezelo",
    "website": "Iwebhusayithi",
    "apply_for_all_products": "∞ Faka isicelo kuzo zonke iimveliso",
    "fix_commission": "Ikhomishini emiselweyo",
    "percent_commission": "Ipesenti ikhomishini",
    "fixed_discount": "Isaphulelo esisisigxina",
    "discount_percentage": "Ipesenti yesaphulelo",
    "discount_limit": "Umda wesaphulelo",
    "no_code": "Akukho khowudi",
    "max_count": "Ubuninzi babalo",
    "count_unit": "Izinto",
    "used": "Isetyenzisiwe",
    "daily": "Yonke imihla",
    "monthly": "Ngenyanga",
    "yearly": "Ngonyaka",
    "state": "Ubume",
    "disable": "Khubaza",
    "enable": "Vulela",
    "activation_code": "Ikhowudi yokuvuselela",
    "quantity": "Ubungakanani",
    "no_club": "Akukho klabhu",
    "per_order": "Ngokomyalelo",
    "count": "Bala",
    "seconds": "Imizuzwana",
    "auto": "Ngokuzenzekelayo",
    "title": "Isihloko",
    "message": "Umyalezo",
    "width": "Ububanzi",
    "length": "Ubude",
    "height": "Ubude",
    "label": "Ileyibhile",
    "click": "Cofa",
    "bank": "Ibhanki",
    "default": "Ukuhlala kukho",
    "role": "Indima",
    "user": "umsebenzisi",
    "users": "Abasebenzisi",
    "code": "Ikhowudi",
    "total_payment": "Iyonke intlawulo",
    "balance": "Ibhalansi",
    "chance": "Ithuba",
    "free_for_new_users": "Isimahla kubasebenzisi abatsha",
    "prize_amount": "Isixa sebhaso",
    "win": "Phumelela",
    "gift_card": "Ikhadi lesipho",
    "discount": "Isaphulelo",
    "config": "Qwalasela",
    "prize": "Ibhaso",
    "Prizes": "Amabhaso",
    "result": "Isiphumo",
    "price": "ixabiso",
    "lottery": "Ilothari",
    "coupon": "Ikhuphoni",
    "customer_club": "Iklabhu yabaThengi",
    "shipping": "Ukuhambisa ngenqanawe",
    "sum": "Isishwankathelo",
    "not_paid": "Ayihlawulwa",
    "category": "Udidi",
    "done": "Ugqibile",
    "email_from": "Ukusuka",
    "subject": "Umxholo",
    "schedule": "Ishedyuli",
    "files_list": "Uluhlu lweefayile",
    "file_max_size": "Ubungakanani befayile enkulu",
    "value": "Ixabiso",
    "help": "Nceda",
    "shipping_tax": "Irhafu yokuthumela ngenqanawa",
    "net_price": "ixabiso Net",
    "tax": "Irhafu",
    "tax_included": "Ibandakanyiwe kwixabiso",
    "limit": "Umda",
    "min_purchase": "Ubuncinci bokuthenga",
    "eligible_for": "Ifanelekile",
    "only_for_first_buy": "Kuphela ukuthenga kuqala",
    "one_time_use": "Inokusetyenziswa ngexesha elinye",
    "period_of_qualify": "Umlinganiselo wokusetyenziswa kwexesha",
    "no_constraint": "Akukho mda",
    "timespan": "Ixesha lelixa",
    "days": "Iintsuku",
    "weight": "Ubunzima",
    "distance": "Umgama",
    "last_status": "Ubume bokugqibela",
    "issued_at": "Ikhutshwe ngo",
    "order": "Umyalelo",
    "order_detail": "Iinkcukacha zomyalelo",
    "percent": "ipesenti",
    "applied_count": "Ubalo olusetyenzisiweyo",
    "campaign": "Iphulo",
    "os": "Inkqubo yokwenza",
    "browser": "Isikhangeli",
    "device": "Isixhobo",
    "device_ip": "Idilesi ye-IP yesixhobo",
    "location": "Indawo",
    "user_agent": "Umenzeli womsebenzisi",
    "affiliate": "Affiliate",
    "timeline": "Umgca wexesha",
    "add_note": "Yongeza inqaku",
    "record": "Rekhoda",
    "unlimited": "Unlimited",
    "show_coupons": "Bonisa amakhuphoni",
    "hide_coupons": "Fihla amakhuphoni",
    "service_area": "Indawo yenkonzo",
    "apps": "Usetyenziso",
    "plugins": "Iiplagi",
    "bots": "Iibhotshi",
    "categories": "Iindidi",
    "products": "Iimveliso",
    "business": "Ishishini",
    "personal": "Okomntu",
    "size": "Ubungakanani",
    "holiday": "Iholide",
    "sod": "Hlawula Ekuhanjisweni",
    "cod": "Imali xa kuziswa",
    "free_shipping": "Ukuhanjiselwa ngenqanawe mahala",
    "hours": "Iiyure",
    "send_date": "Umhla wokuthumela ngenqanawe",
    "deliver_date": "Umhla wokuzisa",
    "return_date": "Umhla wokubuya",
    "pending": "Ilindile",
    "delivered": "Inikezelwe",
    "returned": "Ijikisiwe",
    "canceled": "Irhoxisiwe",
    "shipping_cost": "Imali yohambisa ngenqanawe",
    "action": "Isenzo",
    "cancel_date": "Umhla wokurhoxisa",
    "deliver_in_process": "Iodolo ithunyelwe ngenqanawa..",
    "kind": "Uhlobo",
    "detail": "Iinkcukacha",
    "map": "Imephu",
    "actions": "Izenzo",
    "navigation": "Ukukhangela",
    "navigation_app": "Isicelo",
    "payment_date": "Umhla wentlawulo",
    "duration": "Ubude bexesha",
    "bill": "Ibhili",
    "delivery_persons": "Iikhuriya",
    "delivery_services": "Iinkonzo zonikezelo",
    "live_view": "Imbono ephilayo",
    "cart": "Inqwelo",
    "priority": "Okubalulekileyo",
    "sufficient_credit": "Ityala elaneleyo",
    "max_package_size": "Ubukhulu bobungakanani bepakethe",
    "delay": "Ukulibazisa",
    "credit": "Ityala",
    "livemode": "Phila",
    "paused": "Inqunyanyisiwe",
    "debug": "Debug",
    "token": "Umqondiso",
    "status": "Ubume",
    "courier": "I-Courier",
    "track": "Umkhondo",
    "track_order": "Ukulandelela iodolo",
    "cost": "Iindleko",
    "receipt": "Irisithi",
    "origin": "Imvelaphi",
    "destination": "Indawo ekuyiwa kuyo",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "Akwanelanga isitokhwe!",
    "sub_total": "Iyonke",
    "customer": "Umthengi",
    "delivery": "Ukuhanjiswa",
    "online_orders": "Iiodolo ezikwi-Intanethi",
    "pos_orders": "Iiodolo zePOS",
    "chips": "Iitshiphusi",
    "subscribed": "Ubhalisile",
    "unsubscribed": "Ukhutshiwe kubhaliso",
    "last_login": "Okokugqibela ukungena",
    "join_at": "Umhla wokujoyina",
    "club": "Iklabhu",
    "buyer": "Umthengi",
    "seller": "Umthengisi",
    "or": "Okanye",
    "type": "Uhlobo",
    "condition": "Imeko",
    "brand": "Uphawu",
    "attempt": "Umzamo",
    "error": "Impazamo",
    "success": "Impumelelo",
    "fail": "Ukusilela",
    "inventory": "Uluhlu lwempahla",
    "link": "Ikhonkco",
    "visits": "Utyelelo",
    "transactions": "Iintengiselwano",
    "vat": "VAT",
    "pos_vat": "I-VAT ye-POS",
    "sort_by": "Misa nge..",
    "from": "Ukusuka",
    "from_lead_time": "Kwiiyure ezilandelayo {hours}",
    "no_credit_card_info": "Akukho lwazi lweKhadi!",
    "active": "Iyasebenza",
    "not_active": "Ayisebenzanga!",
    "referrals": "Ugqithiselo",
    "dashboard": "Dashboard",
    "more": "Kaninzi",
    "inactive": "Ayisebenzi",
    "developer": "Umphuhlisi",
    "setting": "Ukumisela",
    "membership_conditions": "Imiqathango yobulungu",
    "customers": "Abathengi",
    "created_at": "Umhla owenziweyo",
    "updated_at": "Uhlaziyo lokugqibela",
    "register_at": "Umhla wokubhalisa",
    "old": "Ndala",
    "new": "Entsha",
    "start": "Qala",
    "end": "Isiphelo",
    "pos": "POS",
    "out_of_stock": "Iphelile kwisitokhwe",
    "fake": "Umgunyathi",
    "low_inventory_warning": "Ingqalelo, uluhlu oluphantsi!",
    "webhook": "Webhook",
    "notification": "Isaziso",
    "sms": "SMS",
    "online_payment_link": "Ikhonkco lokuhlawula kwi-Intanethi",
    "waiting_load_data": "Ilinde ukulayisha idatha..",
    "views": "Iimbono",
    "sales": "Iintengiso",
    "total_views": "Iimbono zizonke",
    "total_sales": "Iintengiso zizonke",
    "from_previous_n_days": "Ukususela {days} zokugqibela",
    "drop_shipping": "Ukulahla",
    "commission": "IKhomishini",
    "shipping_area": "Indawo yokuthumela ngenqanawa",
    "main_seller": "Umthengisi ophambili",
    "domain": "Domain",
    "contact": "Iinkcukacha zoqhagamshelwano",
    "wallet": "Isipaji",
    "reseller": "Umthengisi",
    "tracking_code": "Ikhowudi yokulandelela",
    "tracking_url": "I-URL yokulandela umkhondo",
    "fulfillments": "Ukuzaliseka",
    "reject": "Yala",
    "reserved": "Igciniwe",
    "score": "Inqaku",
    "customer_price": "Ixabiso loMthengi",
    "options": "Iinketho",
    "show_details": "Bonisa iinkcukacha",
    "no_data": "Akukho data..",
    "waiting": "Ilindile...",
    "waiting_connecting_payment": "Ilinde inkonzo yentlawulo...",
    "creating_secure_payment": "Ukudala intlawulo ekhuselekileyo.",
    "officer": "Igosa",
    "ticket": "Itikiti",
    "ticket_url": "I-url yetikiti",
    "closed_at": "Ivaliwe ngo",
    "close_ticket": "Vala itikiti",
    "reopen_ticket": "Phinda uvule itikiti",
    "require": "Funa*",
    "search": "Phendla...",
    "language": "Ulwimi",
    "tasks": "Imisebenzi",
    "permissions": "Iimvume",
    "finish_date": "Umhla wokuphela",
    "complete_date": "Umhla wokugqiba",
    "settle_date": "Umhla wokugqiba",
    "cost_span": "Uluhlu lwexabiso",
    "industry": "Ishishini",
    "rating": "Amanqaku",
    "rates": "Ukukala",
    "seen_at": "Kubonwa e",
    "completed": "Igqityiwe",
    "you": "Wena",
    "shop": "Thenga",
    "store": "ivenkile",
    "granted": "Kuyavunywa",
    "deny": "Nqaba",
    "request": "Isicelo",
    "expert": "Ingcaphephe",
    "response": "Impendulo",
    "requests": "Izicelo",
    "experts": "Iingcali",
    "responses": "Iimpendulo",
    "negotiations": "Uthethathethwano",
    "all_chats": "Zonke iincoko",
    "chats": "Iincoko",
    "tags": "Iithegi",
    "description": "Inkcazo",
    "rates_count": "Inani lereyithingi",
    "rate": "Ukukala",
    "comment": "Comment",
    "chat": "Ncokola",
    "install": "Faka",
    "edited": "Ihlelwe",
    "undo": "qhaqha",
    "redo": "Phinda wenze",
    "male": "Indoda",
    "female": "Ibhinqa",
    "calculator": "Isibali-manani",
    "catalog": "Ikhathalogu",
    "max_height": "Ubude obuninzi",
    "images_compare": "Ukuthelekisa imifanekiso",
    "canvas": "Iseyile",
    "table_of_contents": "Isiqulatho",
    "comments": "Amagqabantshintshi",
    "badge_codes": "Ikhowudi yeebheji",
    "need_more": "Ngaba ufuna ngakumbi?",
    "invite_glow_caption": "Fumana i-14.9 $ ngomhlobo ngamnye!",
    "register_free": "100% Irejista yasimahla",
    "gift": "Isipho",
    "google": "Uphando",
    "facebook": "Facebook",
    "instagram": "Instagram",
    "instashop": "Instashop",
    "show": "Bonisa",
    "hide": "Fihla",
    "waiting_review": "Ilindele ukuphononongwa",
    "not_selected": "Ayikhethwanga",
    "time": "Ixesha",
    "final_price": "Ixabiso lokugqibela",
    "starting_price": "Ixabiso lokuqala",
    "day": "Usuku",
    "paid": "Ihlawulwe",
    "service_bill": "Intlawulo ye-invoyisi",
    "avocado": "Iponyoponyo",
    "delivery_price": "Imali yohambisa ngenqanawe",
    "select_address": "Khetha idilesi",
    "image": "Umfanekiso",
    "view": "Jonga",
    "sell": "Intengiso",
    "hyper": "Hyper",
    "cart_list": "Inqwelo",
    "barcode_scanner": "Iskena sebhakhowudi",
    "scan_qr_code": "Skena ikhowudi yeQR",
    "new_carts": "Iinqwelo ezintsha",
    "pays": "Iintlawulo",
    "annually": "Qho ngonyaka",
    "sells": "Iintengiso",
    "articles": "Amanqaku",
    "jobs": "Imisebenzi",
    "job": "Umsebenzi",
    "blog": "Ibhlog",
    "deleted_at": "Icinywe ngo",
    "capacity": "Umthamo",
    "download_at": "Umhla wokugqibela wokukhuphela",
    "downloads": "Khuphela",
    "usage": "Ukusetyenziswa",
    "select_upload_file": "Khetha okanye ulahle ifayile",
    "download_link": "Khuphela ikhonkco",
    "uploading": "Iyalayisha..",
    "files": "Iifayile",
    "star": "inkwenkwezi",
    "speed": "Isantya",
    "feedback": "Ingxelo",
    "new_messages": "Imiyalezo emitsha",
    "file": "Ifayile",
    "attachment": "Isiqhoboshelo",
    "gallery": "Igalari",
    "sync": "Ngqamanisa",
    "diff_time": "Umahluko wexesha",
    "network": "Uthungelwano",
    "account": "Iakhawunti",
    "configuration": "Uqwalaselo",
    "blockchain": "I-Blockchain",
    "blog_link": "Ikhonkco lebhlog",
    "community": "Uluntu",
    "critical_zone": "Indawo ebalulekileyo",
    "statistics": "Amanani",
    "access": "Ukufikelela",
    "seo": "SEO",
    "followers": "Abalandeli",
    "followings": "Okulandelayo",
    "private": "Jonga kwangaphambili",
    "soon": "Kungekudala",
    "features": "Iimbonakalo",
    "bot": "Bot",
    "sample": "Isampulu",
    "how_it_work": "Ingaba isebenza kanjani?",
    "page": "Iphepha",
    "congratulations": "Sivuyisana nawe",
    "recommend": "Ncoma",
    "recommended": "Kucetyiswa",
    "recoms": "Iingcebiso",
    "likes": "Ukuthandwa",
    "clicks": "Ukucofa",
    "platform": "Iqonga",
    "cms": "CMS",
    "cash": "Imali",
    "dir_payment": "Udluliselo lwebhanki",
    "auto_complete": "Zigqibezele ngokuzenzekela",
    "compare": "Thelekisa",
    "infinite": "Ayinasiphelo",
    "tips": "Iingcebiso",
    "technical": "Ezobugcisa",
    "finance": "Ezemali",
    "your_phone_input": "Faka inombolo yefowuni",
    "income": "Umvuzo",
    "change": "Guqula",
    "new_users": "Abasebenzisi abatsha",
    "success_orders": "Iiodolo eziyimpumelelo",
    "direct": "Ngqo",
    "last_activity": "Umsebenzi wokugqibela",
    "landing": "Ukufika",
    "now": "Ngoku",
    "accept_agreement": "Ndiyifundile kwaye ndayamkela imiqathango.",
    "report": "Ingxelo",
    "tablet": "Icwecwe",
    "pc": "PC",
    "acquisition_channel": "Umjelo wokufumana",
    "to": "Ukuya",
    "info": "Ulwazi",
    "general": "Ngokubanzi",
    "upload": "Layisha",
    "general_config": "Uqwalaselo jikelele",
    "limits_config": "Ukulinganiselwa",
    "design_config": "Uyilo kunye nesimbo",
    "duration_config": "Ubude bexesha",
    "constraints_config": "Imida yokufaneleka",
    "clubs_config": "Ifumaneka kwiiKlabhu",
    "additional_config": "Ulungelelwaniso olongezelelweyo",
    "import": "Ngenisa ngaphandle",
    "ribbon": "Iribhoni",
    "countries": "Amazwe",
    "edit": "Hlela",
    "delete": "Cima",
    "analytics": "Uhlalutyo",
    "rules": "Imigaqo",
    "unset": "Akumiselwanga",
    "carts": "Iinqwelo",
    "optional": "Ukhetho",
    "design": "Yila",
    "filter": "Hluza",
    "send": "Thumela",
    "approved": "Ivunyiwe",
    "unit": "Iyunithi",
    "profile": "iprofayile",
    "shipping_rates": "Amaxabiso okuthumela ngenqanawa",
    "package": "Iphakheji",
    "overview": "Isishwankathelo",
    "live": "Phila",
    "never": "Ungaze",
    "always": "Ngalo lonke ixesha",
    "mandatory": "Isinyanzelo",
    "expire_at": "Umhla wokuphelelwa",
    "position": "Isikhundla",
    "channel": "Umjelo",
    "age": "Ubudala",
    "charge": "Ukuhlawulisa",
    "giftcard": "Ikhadi lesipho",
    "acquisition": "Ukufumana",
    "conversion": "Uguqulo",
    "total_payments": "Iintlawulo zizonke",
    "community_ask": "Buza ekuhlaleni",
    "children": "Abantwana",
    "export": "Thumela ngaphandle",
    "list": "Uluhlu",
    "hierarchy": "Uluhlu lwemigangatho",
    "images": "Imifanekiso",
    "demo": "Idemo",
    "author": "Umbhali",
    "designer": "Umyili",
    "max": "Ubuninzi",
    "accepted": "Yamkelwe",
    "reply": "Phendula",
    "reviewed": "Ijongiwe",
    "restored": "Ibuyiselwe",
    "merchant": "Umrhwebi",
    "per_product": "Ngemveliso nganye",
    "journey": "Uhambo",
    "after": "Emva koko",
    "waiting_for_payment": "Nceda ugcwalise intlawulo...",
    "hour": "Yure",
    "minute": "Mzuzu",
    "premium": "Intlawulo yanyanga le",
    "light": "Ukukhanya",
    "dark": "Mnyama",
    "guest": "Undwendwe",
    "shops": "Iivenkile",
    "vendor": "Umthengisi",
    "vendors": "Abathengisi",
    "marketplace": "Indawo yentengiso",
    "verify_date": "Qinisekisa umhla",
    "note": "Phawula",
    "panel": "Iphaneli",
    "removed": "Isusiwe",
    "segments": "Amacandelo",
    "personal_info": "Ulwazi lomntu",
    "preferences": "Ezikhethwayo",
    "spec": "Spec",
    "reviews": "Uphononongo",
    "constraints": "Izithintelo",
    "flexible": "Ubhetyebhetye",
    "usage_limit": "Umda wosetyenziso",
    "temporary": "Okwexeshana",
    "original": "Eyoqobo",
    "saved": "Igciniwe!",
    "sort": "Hlela",
    "documents": "Amaxwebhu",
    "document": "Uxwebhu",
    "please_wait": "Nceda linda...",
    "pickup": "Phakamisa",
    "customize": "yenza ngokwezifiso",
    "difficulty": "Ubunzima",
    "banned": "Ivaliwe",
    "company": "Inkampani",
    "tax_shipping": "iRhafu yokuThutha",
    "warranty": "Iwaranti",
    "return_policy": "Umthetho WOKUBUYISA",
    "guide": "Isikhokelo",
    "translate": "Guqulela",
    "public": "Uluntu",
    "deleted": "Icinyiwe",
    "variant": "Ukwahluka",
    "secure": "Khusela",
    "admin": "Admin"
  },
  "dialogs": {
    "delete": {
      "title": "Cima",
      "message": "Uqinisekile ukuba uyayicima le nto?",
      "action": "Ewe, cima ngoku"
    }
  },
  "actions": {
    "add_to_cart": "ngeza kwitshathi",
    "cancel": "Rhoxisa",
    "update": "Hlaziya",
    "add": "Yongeza",
    "delete": "Cima",
    "new": "Entsha",
    "save_continue": "Gcina & Qhubeka",
    "save": "Gcina",
    "save_changes": "Gcina Utshintsho",
    "change": "Guqula",
    "continue": "Qhubeka",
    "close": "Vala",
    "finish": "Gqiba",
    "poll": "Uvoto",
    "view": "Jonga",
    "edit": "Hlela",
    "next": "Okulandelayo",
    "previous": "Ngaphambili",
    "create": "Yenza",
    "set": "iseti",
    "find": "Fumana",
    "accept": "Yamkela",
    "reject": "Yala",
    "back": "Emva",
    "pay": "Hlawula",
    "pay_now": "Bhatala ngoku",
    "print": "Shicilela",
    "return": "Buyela",
    "publish": "Papasha",
    "confirm": "Qinisekisa",
    "copy": "Khuphela",
    "submit": "Ngenisa",
    "send": "Thumela",
    "yes": "Ewe",
    "no": "hayi",
    "meh": "Hmm",
    "clear": "Cacileyo",
    "dismiss": "Gxotha",
    "search": "Khangela",
    "deselect_all": "Sukukhetha zonke",
    "select_all": "Khetha Zonke",
    "refresh": "Hlaziya",
    "verify": "Qinisekisa",
    "play": "Dlala",
    "open": "Vula",
    "calculate": "Bala",
    "quick_buy": "Thenga ngokukhawuleza",
    "click_here": "Cofa apha",
    "schedule": "Ishedyuli",
    "send_now": "Thumela ngoku",
    "download": "Khuphela",
    "reset_default": "Phinda umisele ummiselo",
    "reset": "Lungisa kwakhona",
    "check": "Khangela",
    "cod_payment": "Imali xa kuziswa",
    "dir_payment": "Ukudluliselwa kwemali",
    "online_payment": "Intlawulo ye-Intanethi",
    "checkout": "Phuma",
    "show_all": "Bonisa zonke",
    "login": "Ngema",
    "logout": "Phuma",
    "more": "Kaninzi..",
    "collapse": "Ukuwa",
    "apply_change": "Faka utshintsho",
    "apply": "Faka isicelo",
    "add_giftcard": "Yongeza ikhadi lesipho",
    "charge": "Ukuhlawulisa",
    "send_invites": "Thumela izimemo",
    "past": "Ixesha elidlulileyo",
    "restore": "Buyisela",
    "cut": "Sika",
    "get_sms_code": "Fumana ikhowudi yokuqinisekisa",
    "register_no_mail": "Qhubeka ngaphandle kwe-imeyile",
    "no_mail_register_message": "Awunayo idilesi ye-imeyile okanye ulibele igama eliyimfihlo?",
    "reset_by_mail": "Ukubuyisela igama lokugqitha nge-imeyile",
    "reset_by_sms": "Ukubuyisela igama lokugqitha ngeSMS",
    "cash_payment": "Intlawulo yemali",
    "show_chart": "Bonisa itshathi",
    "open_app": "Vula usetyenziso",
    "login_now": "Ngena ngoku",
    "watch_video": "Bukela ividiyo",
    "check_now": "Jonga ngoku",
    "remove_image": "Susa umfanekiso",
    "view_website": "Vula ikhonkco",
    "explore": "Phonononga {name}",
    "go": "Hamba",
    "read_more": "Funda ngokugqithisileyo",
    "start_now": "Qala ngoku — Isimahla",
    "view_live": "Jonga ngqo",
    "resend_code": "Phinda uthumele ikhowudi",
    "invite": "Mema",
    "add_more": "Yongeza ngakumbi",
    "install_now": "Faka ngoku",
    "uninstall": "Khipha",
    "show_preview": "Bonisa imboniso",
    "hide_preview": "Fihla imboniso",
    "download_now": "Khuphella ngoku",
    "auto_fill": "Zalisa ngokuzenzekela",
    "track": "Umkhondo",
    "change_state": "Guqula ubume",
    "done": "Ugqibile",
    "reply": "Phendula",
    "watch_now": "Jonga Ngoku",
    "unlock": "Vula",
    "lock": "Tshixa",
    "create_clone": "Yenza i-clone",
    "regenerate": "Hlaziya",
    "add_message": "Yongeza umyalezo",
    "continue_chat": "Qhubeka nencoko",
    "add_new_message": "Yongeza umyalezo omtsha"
  },
  "instance_message_title": "Thumela umyalezo ngoko nangoko",
  "instance_message": "Molo {name}, Igama lam ndingu{author} osuka {company}.",
  "errors": {
    "419": "Ubungasebenzi ixesha elide, nceda <b>⟳ HLAZIYA IPHEPHA</b> ngenxa yezizathu zokhuseleko.",
    "gateway_blockchain_sync_error": "Inkqubo ayihambelani ne-blockchain. Akunakwenzeka ukwenza intengiselwano entsha de ungqamaniso lweeseva zethu lugqitywe. Sisombulula ingxaki.",
    "gateway_network_error": "Inkonzo yesango lentlawulo idibene nengxaki yonxibelelwano."
  },
  "receiver_info": {
    "map": {
      "title": "Idilesi yokuyithumela ngenqanawe",
      "confirm": "Seta indawo",
      "address_type": "Indawo ekuyiwa kuyo",
      "receptor_type": "Umamkeli"
    },
    "receiver_address": "Khetha idilesi yokuthumela ngenqanawa",
    "address": "idilesi",
    "postcode": "Ikhowudi yeposi",
    "enter_value": "Gcwalisa apha",
    "address_note": "Phawula",
    "tel": "Inombolo YOQHAGAMSHELWANO",
    "service_address": "Khetha idilesi yakho"
  },
  "weight": {
    "g": "g",
    "oz": "oz",
    "lb": "i-Ib",
    "kg": "ikg"
  },
  "mass_unit_name": {
    "g": "igram",
    "oz": "I-Once",
    "lb": "Iponti",
    "kg": "ikhilogram"
  },
  "length": {
    "cm": "i-cm",
    "in": "kwi",
    "ft": "ft",
    "mm": "mm",
    "m": "m",
    "yd": "yd"
  },
  "size_unit_name": {
    "cm": "Isentimitha",
    "in": "Intshi",
    "ft": "Unyawo",
    "mm": "imilimitha",
    "m": "imitha",
    "yd": "Iyadi"
  },
  "distance": {
    "m": "imitha",
    "km": "km"
  },
  "time": {
    "days": "Iintsuku",
    "hours": "Iiyure",
    "minutes": "Imizuzu",
    "seconds": "Imizuzwana"
  },
  "units": [
    "Iyunithi",
    "into",
    "nganye",
    "iseti",
    "iqhekeza",
    "ikhilogram",
    "igram",
    "imiligram",
    "imitha",
    "imilimitha",
    "imitha yesikwere",
    "unywo olumbhoxo",
    "cubic meter",
    "ilitha",
    "imililitha",
    "iinyawo",
    "iigaloni",
    "intshi",
    "iiounces",
    "iiponti",
    "iilitha",
    "iiyadi",
    "igumbi",
    "imizuzwana",
    "imizuzu",
    "iiyure",
    "iintsuku",
    "iiveki",
    "iinyanga",
    "iminyaka"
  ],
  "region_types": {
    "State": "Umbuso",
    "Territory": "Ummandla",
    "Province": "iPhondo"
  },
  "transaction_status": {
    "RequireAction": "Kufuneka Inyathelo",
    "Processing": "Iyaqhuba",
    "Canceled": "Irhoxisiwe",
    "Succeeded": "Iphumelele"
  },
  "placeholders": {
    "name": "UJone Cox",
    "email": "your-mail@mail.com",
    "phone": "+1 000 0000",
    "language": "Khetha ulwimi..",
    "friend_email": "I-imeyile yomhlobo wakho...",
    "friend_name": "Khetha. Igama lomhlobo wakho",
    "select_date": "Khetha umhla..."
  },
  "notification": {
    "confirm": "Qinisekisa",
    "confirm_message": "Utshintsho lugcinwe ngempumelelo.",
    "error": "Impazamo",
    "message": "Umyalezo",
    "caution": "Isilumkiso",
    "warning": "Isilumkiso",
    "award": "Siyavuyisana nawe",
    "error_message": "Ngelishwa, kwenzeke impazamo.",
    "congratulation": "Siyavuyisana nawe",
    "coming_soon": "Kungekudala",
    "on_fetching_data": "Ukufumana ulwazi..",
    "new_pwa_version": "Inguqulelo entsha ekhoyo ngoku. Ngaba uyafuna ukuhlaziya usetyenziso?",
    "over_license_limit": "Ngaphezulu koMda weLayisensi",
    "update_license": "Hlaziya ilayisenisi yakho",
    "required": "Kufuneka",
    "invalid_email": "I-imeyile engekhoyo",
    "invalid_domain": "Indawo engasebenziyo",
    "invalid_min_length": "Ubuncinci ubude kufuneka bube {length}",
    "invalid_min_array_length": "Noko khetha {length} izinto",
    "invalid_max_chars": "Ubuninzi beempawu {maxCount}",
    "invalid_url": "I-URL engasebenziyo",
    "country_invalid": "Khetha ilizwe ekuyiwa kulo!",
    "postal_code_invalid": "Misela ikhowudi yeposi esebenzayo!"
  },
  "colors": {
    "#D32F2F": "Bomvu",
    "#C2185B": "Pinki",
    "#7B1FA2": "Mfusa",
    "#512DA8": "Umfusa omnyama",
    "#303F9F": "I-Indigo Blue",
    "#1976D2": "Luhlaza",
    "#0288D1": "Isibane esiluhlaza",
    "#0097A7": "I-Turquoise Blue",
    "#00796B": "IGoose Green",
    "#388E3C": "Luhlaza",
    "#689F38": "Ilitha elululhlaza",
    "#AFB42B": "Limo",
    "#FBC02D": "Lubhelu",
    "#FFA000": "I-Amber",
    "#F57C00": "orenji",
    "#E64A19": "I-Orenji ekhazimlayo",
    "#5D4037": "Ntsundu",
    "#616161": "Ngwevu",
    "#455A64": "Grey Blue",
    "#FFD700": "Golden",
    "#C0C0C0": "Isilivere",
    "#b76e79": "IRose yegolide",
    "#383838": "Umnyama omnyama",
    "#FFFFFF": "Mhlophe",
    "#FFF": "Mhlophe",
    "#000000": "Mnyama",
    "#000": "Mnyama",
    "#7d263a": "Maroon",
    "#FD9F17": "Igolide",
    "#229DBF": "Aqua",
    "#6DC9E2": "Aqua Triblend",
    "#413B2D": "Umkhosi",
    "#474747": "I-asphalt",
    "#E6195C": "Berry",
    "#B2184C": "UBerry Triblend",
    "#FC7F5F": "I-Orenji etshisiweyo",
    "#80011F": "UKhadinali",
    "#382829": "Itshokholethi",
    "#F06336": "Ikorale",
    "#FAE7C9": "Ikhrimu",
    "#6B2257": "Currant",
    "#222127": "Grey emnyama",
    "#0D5A74": "Ubunzulu beTeal",
    "#00582F": "Evergreen",
    "#214C30": "Ihlathi",
    "#DC2867": "Fuchsia",
    "#38561F" :"Kelly",
    "#5C884D": "Igqabi",
    "#558450": "Ukukhanya kwe-Aqua",
    "#96B5C9": "Isibane esiluhlaza",
    "#DCAFCE": "Lilac",
    "#D3E1A4": "Lamoni",
    "#9DE7C2": "Minti",
    "#F6EAD2": "Ngokwendalo",
    "#1A1F35": "Umkhosi wamanzi",
    "#404624": "Umnquma",
    "#271020": "iplamu",
    "#A8355C": "Irasbheri",
    "#D6BEA6": "I-Soft Cream",
    "#BEA994": "Tan",
    "#0DB2AE": "Teal",
    "#A86EA9": "Violet",
    "#36454F": "Amalahle",
    "#b3b0ab": "carbon Grey",
    "#463e3d": "UHeather wamalahle",
    "#282d3c": "UNavy Blazer"
  },
  "address_info": {
    "name": "Igama",
    "tel": "Ifowuni",
    "email": "I-imeyile",
    "country": "Ilizwe",
    "city": "Isixeko",
    "state": "Umbuso",
    "address": "idilesi",
    "building_number": "Inombolo yesakhiwo",
    "building_unit": "Iyunithi",
    "postcode": "Ikhowudi yeposi",
    "note": "Phawula",
    "county": "County"
  },
  "product_types": {
    "physical": "Enyameni",
    "physical_description": "Iimveliso zenyama ezinje: iiselfowuni, iincwadi, izinto zombane.",
    "virtual": "Inyani",
    "virtual_description": "Iimveliso ezisebenzisekayo kwi-Intanethi ezinje: ikhadi lokutshaja, ugcino lwasehotele, ukutshaja kwakhona komdlalo.",
    "file": "Ifayile",
    "file_description": "Zonke iifayile ezivumelekileyo njengevidiyo yekhosi ye-intanethi, amaxwebhu anokukhutshelwa.",
    "service": "Inkonzo",
    "service_description": "Iinkonzo ezifana: ukulungisa, ukuthutha, ukufundisa."
  },
  "license": {
    "free": "Mahala",
    "startup": "Ukuqala eqala",
    "company": "Inkampani",
    "enterprise": "Ishishini"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "UToman",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW",
    "GHS": "GHS",
    "ZWD": "ZWD",
    "IQD": "IQD",
    "SYP": "SYP"
  },
  "variants": {
    "color": "Umbala",
    "volume": "Ubungakanani",
    "count_in_pack": "Bala ngokwepakethe",
    "weight": "Ubunzima",
    "type": "Izinto eziphathekayo",
    "style": "Isimbo"
  },
  "delivery_state": {
    "check_queue": "Ilindele ukuphononongwa",
    "order_confirm": "Odola isingqino",
    "preparing_order": "Ukulungiselela",
    "sent_order": "Ekuhanjisweni",
    "to_customer": "Inikezelwe"
  },
  "status": {
    "unpaid": "Engahlawulwanga",
    "paid": "Ihlawulwe",
    "canceled": "Irhoxisiwe",
    "completed": "Ndizinzile",
    "reserved": "Igciniwe",
    "COD": "COD",
    "sold": "Iyathengiswa",
    "open": "Vula",
    "cancel": "Irhoxisiwe",
    "active": "Iyasebenza",
    "inactive": "Ayisebenzi",
    "debug": "Debug",
    "live": "Phila",
    "test": "Uvavanyo",
    "connected": "Iqhagamshelwe",
    "disconnected": "Iqhawulwe",
    "accept": "Yamkela",
    "reject": "Yala",
    "pending": "Ilindile",
    "rejected": "Yaliwe",
    "accepted": "Yamkelwe"
  },
  "dimensions": {
    "cm": "i-cm",
    "km": "km",
    "kg": "ikg"
  },
  "transportation_type": {
    "motorbike": "Isithuthuthu",
    "motorbike_description": "Ubunzima obuphakathi kwiikhilomitha ezimbalwa.",
    "cargo_small": "Umthwalo omncinci",
    "cargo_small_description": "Multi-kilometer ukukhanya umthwalo.",
    "cargo": "Impahla",
    "cargo_description": "Ubunzima obuphakathi kwiikhilomitha ezimbalwa.",
    "truck": "Ilori",
    "truck_description": "Umthwalo omninzi okanye onzima elizweni.",
    "fast_post": "Thumela ngokukhawuleza",
    "fast_post_description": "Ukuthunyelwa ngokukhawuleza ngeposi.",
    "post": "Isithuba esiqhelekileyo",
    "post_description": "Iposi rhoqo ngeposi.",
    "airplane": "Imeyile yomoya",
    "airplane_description": "Ukukhanya kwangaphakathi nangaphandle kunye nomthwalo ophakathi.",
    "bicycle": "Coca Thumela",
    "bicycle_description": "Umthwalo olula, phakathi kwamakhulu ambalwa eeyadi zezithuthi ezingezizo iimoto.",
    "global": "Uthutho lwehlabathi",
    "global_description": "Ukuthumela phesheya kolwandle ngomoya, elwandle okanye emhlabeni.",
    "pickup": "Phakamisa",
    "pickup_description": "Abathengi bathatha izinto kwivenkile yakho ebonakalayo okanye kwindawo yokugcina."
  },
  "article": {
    "login_to_see_error": "Ngena ukufikelela kwinqaku",
    "create_new_action": "Yenza umxholo omtsha",
    "menu_title": "Imenyu",
    "menu": {
      "edit": "Imo yokuhlela",
      "view_mode": "Imowudi yokujonga",
      "delete": "Cima Inqaku"
    },
    "schedule_action": "Ngaba uyafuna ukucwangcisa upapasho?",
    "schedule_title": "Cwangcisa ukupapasha ngokuzenzekelayo",
    "edit_mode": "Hlela",
    "public_view_mode": "Umbono woluntu",
    "publish_at": "Papasha apha",
    "published": "Ipapashiwe",
    "draft": "Uyilo",
    "saving": "Iyagcina",
    "save_and_publish_action": "Gcina kwaye Upapashe",
    "save_draft_action": "Gcina uyilo",
    "private": "Yabucala",
    "public": "Uluntu",
    "category_input": "Udidi",
    "category_input_message": "Khetha udidi lwenqaku",
    "parent_input": "Udidi lwabazali",
    "parent_input_message": "Khetha umxholo ubawo",
    "schedule_input": "Ishedyuli",
    "schedule_input_placeholder": "Ukuba ufuna ukuba ibali lipapashwe ngexesha elithile.",
    "schedule_view_action": "Jonga iShedyuli yokuPapasha",
    "author_title": "Ibhalwe ngu",
    "read_time": "Ixesha lokufunda",
    "read_time_unit": "Imizuzu",
    "claps_action": "Uqhwaba izandla",
    "claps": "Uqhwaba izandla",
    "likes": "Njengo",
    "about_author": "Malunga nombhali",
    "updated_at": "Ihlaziyiwe",
    "wrote_at": "Ibhalwe ku",
    "now": "Ngoku",
    "follow_action": "Landela",
    "followed": "Iyalandelwa",
    "report_and_delete_action": "Xela kwaye ucime eli nqaku",
    "report_action": "Xela ukuhlukunyezwa",
    "you_reported_this_article": "Eli nqaku sele linengxelo yokuxhatshazwa.",
    "add_to_publication_action": "Yongeza kuPapasho",
    "author_socials": "Umbhali kwimidiya yoluntu",
    "share": "Yabelana",
    "report_dialog": {
      "report_and_delete_title": "Xela uxhatshazo kwaye ususe umxholo",
      "report_title": "Xela lo mxholo njengokuhlukumezayo",
      "message": "Sithini isizathu sokungeniswa kwalo mxholo? Khetha enye yezi ndlela zilandelayo.",
      "accept_and_delete_action": "Qinisekisa kwaye Cima Umxholo"
    },
    "schedule_dialog": {
      "title": "IShedyuli yokukhutshwa komxholo",
      "publish_at": "Papasha apha",
      "last_edit": "Ukuhlelwa kokugqibela",
      "view_action": "Jonga inqaku"
    },
    "notifications": {
      "update_success_title": "Ngenisa Ulwazi",
      "update_success": "Inqaku lihlaziywe ngempumelelo.",
      "update_error": "Ulwazi olufakiweyo alusebenzi.",
      "delete_error": "Awukwazi ukucima eli nqaku!",
      "report_and_delete_success_title": "Ingxelo kwaye Cima",
      "report_and_delete_success_message": "Inqaku licinywe ngempumelelo.",
      "report_success_title": "Inqaku lengxelo",
      "report_success_message": "Ingxelo yakho kweli nqaku ithunyelwe."
    },
    "alert": {
      "delete_article": {
        "title": "Cima Inqaku",
        "message": "Uqinisekile ukuba ufuna ukucima ngokusisigxina eli nqaku?",
        "action": "Cima"
      }
    },
    "edit_window": {
      "title": "Khetha Isiqendu somfanekiso kunye nesiShwankathelo",
      "digest": "Isishwankathelo"
    },
    "editor": {
      "title_placeholder": "Isihloko..",
      "body_placeholder": "Bhala umxholo omnandi..",
      "accept_file_types_error": "Le fomati yefayile ayamkelekanga:",
      "max_file_size_error": "Le fayile inkulu kakhulu:",
      "notifications": {
        "image_uploaded_success": "Umfanekiso ugcinwe ngempumelelo",
        "image_uploaded_failed": "Impazamo yokulayisha umfanekiso."
      },
      "embed_placeholder": "Faka ikhowudi ye-iframe, i-Facebook, i-Youtube okanye nayiphi na enye i-URL kwaye ucinezele ukungena.",
      "embed_caption_placeholder": "Ngenisa isihloko (ukhetho)",
      "images_caption_placeholder": "Ngenisa isihloko salo mfanekiso .."
    }
  },
  "article_report": {
    "inappropriate": "Umxholo weli nqaku awufanelekanga.",
    "fake": "Oku kububuxoki kwaye kuyakhohlisa.",
    "spam": "Lo mba uthunyelwe ngogaxekile kwaye ukhutshelwe.",
    "scam": "Oku kunokulindeleka ukuba kubangele i-malware, iintsholongwane okanye ukuphazamiseka kwenkqubo.",
    "hacked": "Kubonakala ngathi le sayithi igqekeziwe.",
    "offensive": "Umxholo kunye nesigama solwimi alunambeko kwaye aluhloniphi.",
    "violent": "Ndicinga ukuba lo mxholo unephonografi kwaye wophula imithetho.",
    "harassment": "Ndicinga ukuba olu lucalucalulo.",
    "hate": "Ndicinga ukuba oku kukukhuthaza ubundlobongela.",
    "infringe": "Oku kunyhasha amalungelo am."
  },
  "comments": {
    "new_action": "Cofa ukushiya uluvo ..",
    "title": "Amagqabantshintshi",
    "body_placeholder": "Izimvo zakho okanye umyalezo",
    "send_action": "Thumela izimvo",
    "body_is_empty_error": "Uluvo alunanto!",
    "comments": "Amagqabantshintshi",
    "no_comments": "Bhala uluvo lokuqala...",
    "load_more_action": "Fumana ezinye izimvo..",
    "cant_send_comment": "Awukwazi ukongeza iposti entsha.",
    "cant_remove_this_comment": "Awukwazi ukucima le ngxelo!",
    "product_buyer": "Umthengi",
    "delete_alert": {
      "title": "Cima Izimvo",
      "message": "Ngaba uyafuna ukucima le nkcazo?",
      "action": "Cima"
    },
    "notifications": {
      "delete_success": "Izimvo zakho zicinywe ngempumelelo."
    },
    "first_send": "Isithuba sokuqala",
    "comment_at": "Vula",
    "edit_comment": "Hlela amagqabantshintshi"
  },
  "customer_club": {
    "bronze": "Ubhedu",
    "silver": "Isilivere",
    "gold": "Golden",
    "platinum": "iPlatinam",
    "diamond": "Idayimani"
  },
  "application_categories": {
    "tracking": "Ukujonga iNdlela yokuziPhatha yoMsebenzisi",
    "payment": "Intlawulo",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "Ezothutho",
    "automation": "Ukuzenzekela",
    "inventory": "Ugcino",
    "accounting": "Accounting",
    "marketing": "Intengiso",
    "advertising": "Intengiso",
    "staff": "Abasebenzi",
    "incentive": "Inkuthazo",
    "shop": "Thenga"
  },
  "social_network": {
    "instagram": "Instagram",
    "telegram": "ITelegram",
    "googleplay": "UDlalo lukaGoogle",
    "appstore": "Ivenkile yosetyenziso",
    "twitter": "Twitter",
    "linkedin": "Linkedin",
    "medium": "Phakathi",
    "selldone": "Selldone",
    "facebook": "Facebook",
    "pinterest": "Pinterest",
    "whatsapp": "WhatsApp",
    "skype": "I-Skype",
    "facebook_messenger": "Facebook Messenger"
  },
  "form_builder": {
    "add_item_action": "Yongeza into entsha",
    "title_input": "Isihloko",
    "name_input": "Igama eliguquguqukayo",
    "value_input": "Imilinganiselo",
    "value_input_message": "Uluhlu lweeKhetho zabasebenzisi",
    "default": "Ixabiso elimiselweyo",
    "types": {
      "simple": "Elula",
      "selective": "Khetha",
      "switch": "Tshintsha",
      "file": "Ifayile",
      "number": "Inani"
    },
    "placeholder_input": "Isibambi-ndawo",
    "file_type_input": "Iintlobo zeefayile ezamkelekileyo",
    "file_type_message": "jpeg , png , zip , ..."
  },
  "virtual_order_info_summery": {
    "title": "Igama lemveliso",
    "reserved_at": "Umhla woBhaliso",
    "total_price": "Imali iyonke",
    "discount": "Isaphulelo",
    "final_price": "Imali yokugqibela",
    "payment_status": "Ubume bentlawulo",
    "payment_status_waiting": "Ilinde intlawulo",
    "payment_status_paid": "Ihlawulwe",
    "buyer": "Umthengi"
  },
  "virtual_item_info": {
    "title": "Into ebonakalayo",
    "outputs": {
      "title": "Ulwazi Lweziphumo",
      "sub_title": "Ulwazi oluyiMfihlo lwale Nto",
      "message": "Olu lwazi luya kuboniswa kumsebenzisi emva kokuthenga imveliso."
    },
    "inputs": {
      "title": "Ulwazi olufunekayo",
      "sub_title": "Ulwazi lomthengi olufunekayo",
      "message": "Umthengi kufuneka afake ulwazi oluceliweyo kwifom"
    },
    "notifications": {
      "inputs_set_success": "Ifomu yolwazi ibhaliswe ngempumelelo.",
      "confirm_by_admin_success": "Ukugqitywa komyalelo kuqinisekisiwe.",
      "confirm_by_buyer_success": "Ukugqitywa komyalelo kuqinisekisiwe."
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "Lo myalelo awunakwamkelwa yintlawulo yeCOD.",
    "payment_returned": "Intlawulo yomthengi ibuyiswa.",
    "payment_fraud": "Intlawulo ichongwe njengobuqhophololo.",
    "location_out_of_service": "Indawo yomthengi ayisebenzi.",
    "user_not_responding": "Umthengi akazange aphendule iifowuni.",
    "shop_owner_fault": "Kwenzeke impazamo ngabasebenzi bevenkile ekugcwaliseni ulwazi.",
    "lack_of_inventory": "Iphelile kwisitokhwe.",
    "legal_restriction": "Ayikwazanga ukwenza umyalelo ngenxa yezithintelo ezisemthethweni.",
    "pricing_fault": "Impazamo yamaxabiso ngumthengisi.",
    "system_fault": "Inkqubo bug."
  },
  "basket_order_info_summery": {
    "receiver": "Umamkeli",
    "phone": "Umnxeba",
    "reserved_date": "Umhla wokuthenga",
    "total_price": "Imali iyonke",
    "discount": "Isaphulelo",
    "final_price": "Imali yokugqibela",
    "address": "Idilesi yokuhambisa",
    "payment_status": "Ubume bentlawulo"
  },
  "basket_status": {
    "open": "Vula",
    "reserved": "Igciniwe",
    "paid": "Ihlawulwe",
    "canceled": "Irhoxisiwe",
    "cod": "Hlawula Ekuhanjisweni",
    "receipt_added": "Irisithi yongeziwe",
    "payment_processing": "Ukwenziwa kwentlawulo"
  },
  "basket_delivery_state": {
    "rejected": "Yaliwe",
    "reject_reason_not_found": "Isizathu asaziwa.",
    "step_1": "Uphononongo",
    "step_2": "Isiqinisekiso",
    "step_3": "Ukulungiselela",
    "step_4": "Ekuhanjisweni",
    "step_5": "Inikezelwe"
  },
  "basket_return_request_view": {
    "title": "Buyisela isicelo",
    "delivery_date": "Umhla wokuzisa",
    "return_date": "Umhla wesicelo",
    "items_count": "Ubalo lwezinto ezibuyisiweyo",
    "items_count_unit": "izinto",
    "reason": "Isizathu",
    "description": "Inkcazo",
    "status": "Ubume",
    "download_image": "Khuphela umfanekiso",
    "download_film": "Khuphela ividiyo",
    "download_voice": "Khuphela ilizwi",
    "accept_by_admin_action": "Yamkela isicelo",
    "reject_by_admin_action": "Sale isicelo",
    "message_for_admin": "Ngokwesivumelwano owamkeleyo ngokusebenzisa i-Selldone, kufuneka uqhagamshelane nomthengi kwaye umgcine esazi ngenkqubo yokubuyisela iodolo yakhe. Oku kufuneka kwenziwe ukuba isicelo samkelwe okanye saliwe kwaye imvume epheleleyo yomthengi ifunyenwe.",
    "notifications": {
      "update_status_success": "Isimo sesicelo sihlaziyiwe."
    }
  },
  "basket_list": {
    "return_count": "Buyela: {count} inombolo",
    "table": {
      "row": "Umqolo",
      "image": "Umfanekiso",
      "product_name": "Imveliso",
      "variant": "Ukwahluka",
      "warranty": "Iziqinisekiso",
      "count": "Bala",
      "price": "ixabiso"
    }
  },
  "return_request_list": {
    "count": "Inombolo yerefurensi",
    "return_warranty": "Isiqinisekiso sokuBuyisa imali",
    "return_warranty_unit": "Iintsuku",
    "table": {
      "code": "Ikhowudi yeodolo",
      "product": "Imveliso",
      "delivery_at": "Umhla wokufunyanwa",
      "state": "Ubume",
      "reason": "Isizathu",
      "return_warranty_period": "Ixesha lewaranti"
    }
  },
  "data_toolbar": {
    "search": "Khangela",
    "sort_by": "Misa nge",
    "count_item": "Bonisa {item} izinto"
  },
  "sort": {
    "created_at": "Yenza umhla",
    "updated_at": "Hlela umhla",
    "title": "Isihloko",
    "description": "Inkcazo",
    "like": "Ukuduma",
    "power": "Uqhwaba izandla",
    "product_type": "Uhlobo lwemveliso",
    "discount": "Isaphulelo",
    "rate": "Ukukala",
    "rate_count": "Inani lereyithingi",
    "category": "Udidi",
    "product": "Imveliso",
    "body": "Umxholo",
    "card_type": "Uhlobo lwekhadi",
    "card_number": "Inombolo yekhadi",
    "balance": "Ibhalansi",
    "paid": "Imali echithiweyo",
    "currency": "Imali",
    "expire_at": "Umhla wokuphelelwa",
    "discount_code": "Ikhowudi yesaphulelo",
    "discount_percent": "Isaphulelo",
    "discount_limit": "Umda wesaphulelo",
    "max_count": "Ubuninzi babalo",
    "used_count": "Isetyenzisiwe",
    "start_date": "Umhla wokuqala",
    "end_date": "Umhla wokuphela",
    "total_discount_amount": "Izaphulelo zizonke",
    "initial_charge": "Intlawulo yokuqala",
    "total_count": "Ubalo lulonke",
    "amount_paid": "Imali ehlawulweyo",
    "name": "Igama",
    "published": "Ipapashiwe",
    "visits": "Utyelelo",
    "color": "Umbala",
    "landing_page": "Iphepha lokufika",
    "enable": "Vulela",
    "fix_commission": "Ikhomishini emiselweyo",
    "percent_commission": "Ipesenti ikhomishini",
    "payment_at": "Umhla wentlawulo",
    "issued_at": "Usuku lophuma",
    "payment": "Intlawulo",
    "website": "Iwebhusayithi",
    "email": "I-imeyile",
    "user": "umsebenzisi",
    "code": "Ikhowudi",
    "schedule_at": "Umhla weshedyuli",
    "sender": "Umthumeli",
    "in_que": "Emgceni",
    "sent": "Ithunyelwe",
    "shop": "Thenga",
    "quantity": "Ubungakanani",
    "amount": "Isixa",
    "jobs": "Ubalo lwemisebenzi",
    "success": "Ubalo lwempumelelo",
    "fail": "Ubalo olungaphumeleliyo",
    "distance": "Umgama",
    "duration": "Ubude bexesha",
    "reset_at": "Lungisa umhla",
    "delivery_person": "Umntu",
    "delivery_service": "Inkonzo",
    "date": "Umhla",
    "order": "Umyalelo",
    "order_id": "I-ID yeodolo",
    "status": "Ubume",
    "price": "ixabiso",
    "count": "Bala",
    "final_price": "Ixabiso lokugqibela",
    "charge": "Ukuhlawulisa",
    "mention": "Khankanya",
    "officer": "Igosa",
    "registered": "Ibhalisiwe",
    "purchased": "Ithengiwe",
    "sex": "Isini"
  },
  "search_box": {
    "result": "Iziphumo zokukhangela",
    "tips": "Khangela iMveliso kunye neeCategories",
    "label": "Phendla...",
    "category": "Udidi"
  },
  "lead_status": {
    "physical_fast_delivery": "Ukuhanjiswa kwangoko",
    "physical_under_24h_delivery": "Zisa kwiiyure ezilandelayo ezi- {lead}",
    "physical_over_24h_delivery": "Ukulungiselela nokungeniswa ukusuka kwimihla {days} elandelayo",
    "virtual_fast_prepare": "Ukuhanjiswa kwangoko",
    "virtual_under_24h": "Iza kwenziwa kwiiyure ezilandelayo ezi- {lead}",
    "virtual_over_24h": "Izakwenziwa ukusuka kwi{days} ezilandelayo"
  },
  "return_request_state": {
    "pending": "Ilindile",
    "accepted": "Iqinisekisiwe",
    "rejected": "Yaliwe"
  },
  "return_order_reason": {
    "physical": {
      "U1": "Ukungafani kwemveliso",
      "U2": "Akukho mveliso kwiphakheji yokuthumela",
      "U3": "Iphakheji okanye ukuphulwa kwemveliso",
      "U4": "Ipakethe okanye uthotho lwenombolo yesiriyali",
      "U5": "Ezinye izinto ezikwipasile azikho",
      "U6": "Imveliso ayiyoqobo",
      "U7": "Imveliso ayiyonelisi ingcaciso"
    }
  },
  "image_uploader": {
    "label": "Tsala & Lahla okanye <u>Khetha ifayile</u>",
    "max_size": "Obona bungakanani buvumelekileyo: {size}"
  },
  "timespan": {
    "Morning": "8am - 12pm",
    "Evening": "12 emini ukuya 6pm",
    "Night": "6pm-12pm",
    "Instant": "Thumela ngoko nangoko"
  },
  "week_day": {
    "Saturday": "uMgqibelo",
    "Sunday": "iCawe",
    "Monday": "uMvulo",
    "Tuesday": "uLwesibini",
    "Wednesday": "uLwesithathu",
    "Thursday": "uLwesine",
    "Friday": "uLwesihlanu"
  },
  "payment_form": {
    "title": "Khetha iNdlela yokuHlawula",
    "gift_cards_input": "Amakhadi esipho",
    "gift_cards_input_empty": "Akukho makhadi esipho afunyenweyo..",
    "more": "Okunye",
    "pay_amount_by_gift_cards": "Intlawulo yekhadi lentlawulo",
    "select_payment_method": "Khetha indlela yakho yokuhlawula kolu khetho lulandelayo.",
    "payment_amount_remained": "Imali eseleyo yentlawulo",
    "payment_amount": "Imali ehlawulweyo",
    "all_paid_by_gift_cards": "Sivuyisana nawe, awudingi kuhlawula le odolo. Cofa iqhosha elithi Hlawula Ngekhadi Lesipho.",
    "pay_by_gift_cards_action": "Hlawula iodolo ngekhadi lentlawulo",
    "order_free_payment": "Sivuyisana nawe, iodolo yakho isimahla!",
    "order_free_payment_action": "Oda Mahala Ngoku",
    "qr": {
      "address": "Idilesi yentlawulo",
      "amount": "Isixa"
    }
  },
  "discount_input": {
    "limit": "{percent}% isaphulelo ukuya kuthi ga kwi {limit} {currency}",
    "action": "Yongeza iKhowudi yesaphulelo",
    "code_input": "Ikhowudi yesaphulelo",
    "notifications": {
      "add_success": "Sivuyisana nawe, ikhowudi yesaphulelo esebenzayo."
    }
  },
  "gift_card": {
    "inactive": "Ikhadi livaliwe",
    "expire": "Ukuphelelwa lixesha",
    "transfer": "Udluliselo",
    "send_to_friend": "Thumela kumhlobo"
  },
  "count_down": {
    "days": "Usuku",
    "hours": "Yure",
    "minutes": "Imizuzu",
    "seconds": "Imizuzwana"
  },
  "gift_status": {
    "Unpaid": "linde isiliphu",
    "Paid": "Ihlawulwe",
    "Rejected": "Yaliwe",
    "Canceled": "Irhoxisiwe"
  },
  "gift_program_status": {
    "Airdrop": "Inkqubo yentlawulo",
    "Advertising": "Intengiso",
    "PersonalGift": "Isipho Sakho",
    "ShopGift": "Ivenkile yezipho"
  },
  "currency_selector": {
    "label": "Imali"
  },
  "need_login": {
    "title": "Ngema",
    "login_sms": "Ngena ngeSMS",
    "login_google": "Ngena ngoGoogle",
    "login_facebook": "Ngena kuFacebook",
    "login_account": "Ngena nguSelldone",
    "register": "Umsebenzisi omtsha? Bhalisa ngoku.",
    "mobile_input": "Faka ifowuni yakho",
    "verification_code": "Gqina ikhowudi",
    "msg_title": "Mholo,",
    "msg_body": "Nceda ungene. Kuthatha nje imizuzwana embalwa.",
    "login_apple": "Ngena ngeApple"
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "5 Year Gold Store"
    },
    "GOLDEN_2YEAR": {
      "name": "4 Year Gold Store"
    },
    "GOLDEN_3YEAR": {
      "name": "3 Year Gold Store"
    },
    "GOLDEN_4YEAR": {
      "name": "2 Year Gold Store"
    },
    "GOLDEN_5YEAR": {
      "name": "1 Year Gold Store"
    },
    "TOKEN_OWNER_1M": {
      "name": "Umtyali-mali wegolide"
    },
    "TOKEN_OWNER_10M": {
      "name": "UMtyali-mali weDayimani"
    },
    "TOKEN_OWNER_100M": {
      "name": "Umtyali mali weRuby"
    },
    "COMMUNITY_LOYAL": {
      "name": "Ilungu loNxibelelwano oluPhezulu loLuntu loThungelwano"
    },
    "GOLD_SUPPLIER": {
      "name": "Umthengisi weGolide"
    },
    "GOLD_SELLER": {
      "name": "Umthengisi wegolide"
    },
    "CONTENT_SUPERMAN": {
      "name": "Umvelisi woMxholo oPhezulu"
    },
    "NINJA": {
      "name": "Ninja"
    },
    "STAR": {
      "name": "inkwenkwezi"
    },
    "GUARDIAN": {
      "name": "Inkonzo enkulu yabaThengi"
    },
    "KING": {
      "name": "Kumkani weMarike"
    }
  },
  "cookie": {
    "title": "Le webhusayithi isebenzisa iikuki",
    "message": "Le webhusayithi isebenzisa iikuki ukuphucula amava omsebenzisi. Ngokusebenzisa iwebhusayithi yethu uvumela zonke iikuki ngokuhambelana nePolisi yethu yeCookie.",
    "preferences_action": "Lawula Okukhethwayo",
    "agree_action": "Ndiyavuma"
  },
  "basket_item_message": {
    "title": "Ulwazi olufunekayo lwale nto",
    "save_actions": "Gcina umyalezo",
    "notifications": {
      "success": "Igalelo lakho ledatha ligciniwe."
    }
  },
  "faq": {
    "faq": "Imibuzo ebuzwa qho",
    "title": "Imibuzo neempendulo",
    "sub_title": "Into osicelileyo ukuba siyenze.",
    "message": "Khangela impendulo yombuzo wakho phakathi kwezi mpendulo zingezantsi. Sibuze ukuba imibuzo ihlala ingaphendulwanga.",
    "add_question_action": "Buza Umbuzo Omtsha",
    "read_more": "Funda ngokugqithisileyo ..",
    "load_more": "Eminye imibuzo..",
    "main_page": "FAQ Iphepha Eliphambili",
    "add_new": "Ngenisa umbuzo omtsha",
    "login_alert": "Ngena ukuze ubuze umbuzo.",
    "question_input": "Umbuzo",
    "question_input_placeholder": "Buza umbuzo wakho.",
    "notifications": {
      "success_add": "Umbuzo wakho ungeniswe ngempumelelo."
    }
  },
  "rating_labels": [
    "Imbi kakhulu",
    "Imbi",
    "Okuqhelekileyo",
    "Kulungile",
    "Egqwesileyo"
  ],
  "map_view": {
    "address_detail": "Iinkcukacha zedilesi",
    "change": "Guqula",
    "select": "Khetha",
    "not_found_address": "Akukho xabiso lifunyenweyo",
    "enter_address_hint": "Ngenisa idilesi yendawo",
    "enter_your_address": "Faka idilesi yakho.",
    "postal_code": "Ikhowudi yeposi",
    "phone_input": "Ifowuni {type}",
    "building_number": "Inombolo yesakhiwo",
    "building_unit": "Iyunithi",
    "full_name_input": "Igama elipheleleyo {type}",
    "save_detail_action": "Gcina iinkcukacha",
    "more_detail_input": "Inkcazo engakumbi",
    "add_address_to_list": "Yongeza idilesi kuluhlu",
    "address_title_input": "Ileyibhile yedilesi (Funa)",
    "notifications": {
      "save_in_list": "Le dilesi igcinwe kuluhlu lwakho nazo zonke iinkcukacha zayo.",
      "edit_success": "Amaxabiso edilesi amatsha agcinwe kwi- {title}."
    },
    "delete_address_dialog": {
      "title": "Cima idilesi",
      "message": "Uqinisekile ufuna ukucima le dilesi?",
      "action": "Susa idilesi"
    }
  },
  "comment_manager": {
    "can_not_edit": "Ayikwazi ukuhlela le nkcazo!",
    "comment_input_empty": "Umyalezo obhaliweyo awunanto!",
    "article_not_saved": "Gcina inqaku!"
  },
  "wheel_fortune": {
    "title": "Dlala & Phumelela",
    "message": "Iindleko zomdlalo ngamnye ziitshiphusi ezili-10. Ngoku une {chips} chip. Fumana itshiphu eninzi ngokuyithenga evenkileni.",
    "win_message": "Sivuyisana nawe, Uphumelele!",
    "lost_message": "Uxolo, uphulukene nomdlalo.",
    "try_again": "Ungazama kwakhona"
  },
  "json": {
    "add": "Yongeza idatha yesakhiwo",
    "add_message": "Yenza idatha yesakhiwo esitsha",
    "structures": "Ulwakhiwo",
    "book": {
      "title": "Incwadi",
      "desc": "Iintshukumo zencwadi ezenza abasebenzisi bathenge incwadi abayifumene ngokuthe ngqo kwiziphumo zoPhendlo."
    },
    "occupation": {
      "title": "Umvuzo oqikelelweyo",
      "desc": "Ulwazi malunga noqikelelo lwemivuzo, olufana noluhlu lwemivuzo kunye ne-avareji yomvuzo esekwe kwingingqi kwiintlobo zemisebenzi, eboniswe kumava okukhangela umsebenzi kuGoogle."
    },
    "course": {
      "title": "Ikhosi",
      "desc": "Iikhosi zemfundo ezivela kuluhlu oluthile lwababoneleli. Izifundo zinokubandakanya isihloko sekhosi, umboneleli, kunye nenkcazo emfutshane."
    },
    "howto": {
      "title": "Kwenziwa kanjani",
      "desc": "Ubahamba njani abasebenzisi ngokweseti yamanyathelo ukugqiba ngempumelelo umsebenzi, onevidiyo, imifanekiso, kunye nombhalo."
    },
    "recipe": {
      "title": "Indlela yokupheka",
      "desc": "Iiresiphi ezibonisa njengesiphumo esityebileyo somntu okanye inxalenye yecarousel yomkhosi."
    }
  },
  "support": {
    "Financial": "Ezemali",
    "Technical": "Ezobugcisa",
    "Advisor": "Umcebisi"
  },
  "condition": {
    "new": "Entsha",
    "refurbished": "Ihlaziyiwe",
    "used": "Isetyenzisiwe",
    "used_fair": "Isetyenziswe ngokufanelekileyo",
    "used_good": "Isetyenziswe kakuhle",
    "used_like_new": "Isetyenziswa njengentsha"
  },
  "variant_filter": {
    "title": "Isihluzi esahlukileyo seMveliso",
    "only_available": "Ikhona evenkileni"
  },
  "service": {
    "task": {
      "title": "Imisebenzi",
      "message": "Uluhlu lwemisebenzi eyenziwa kule nkonzo."
    },
    "appointment": {
      "title": "Ukuqeshwa",
      "message": "Khetha amaxesha eveki kula maxesha alandelayo ngokusekwe kumhla kunye neyure ekulungeleyo."
    },
    "booking": {
      "title": "Ukubhukisha",
      "message": "Chaza ixesha leentsuku ofuna ukubhukisha ngazo kwikhalenda engezantsi."
    },
    "subscription": {
      "title": "Umrhumo"
    },
    "charge": {
      "title": "Ukuhlawulisa"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "Amaxabiso azinzileyo",
      "message": "Kulo hlobo lwamaxabiso, ixabiso lemveliso liyimali emiselweyo kwaye akukho mfuneko yokuba umthengi acele ukubalwa kwexabiso."
    },
    "ESTIMATION": {
      "title": "Amaxabiso oqikelelo",
      "message": "Ixabiso leemveliso kunye neenkonzo ziya kubalwa kwinqanaba elithile ngumthengisi xa ebeka umyalelo, ii-invoyisi zokuhlawula zingatshintshwa okanye zongezwe ngexesha lenkonzo."
    },
    "AGREEMENT": {
      "title": "Amaxabiso esivumelwano",
      "message": "Ixabiso lokugqibela leemveliso okanye iinkonzo aziyi kutshintshwa ngumthengisi emva kokuba umyalelo ubekwe."
    },
    "BID": {
      "title": "Ibhidi / ifandesi",
      "message": "Imveliso iya kuthengiswa ngexabiso eliphezulu lebhidi ngabo banokuba ngabathengi."
    }
  },
  "map": {
    "title": "Indawo yokufumana iimveliso",
    "confirm": "Seta indawo",
    "address": "Indawo ekuyiwa kuyo",
    "receptor": "Umamkeli"
  },
  "ShopBots": {
    "telegram": "ITelegram"
  },
  "article_tags": {
    "title": "Iithegi zomxholo",
    "tags_input": "Iithegi",
    "tags_input_message": "Iithegi Uluhlu lweli nqaku",
    "notification": {
      "add_success": "Iithegi zongeziwe"
    }
  },
  "difficulties": {
    "very_complicated": "Inzima kakhulu",
    "hard": "Kunzima",
    "intermediate": "Phakathi",
    "easy": "Kulula"
  }
};