export default {
  "currency_default": "USD",
  "language_default": "yi",
  "selldone": "סעלדאָנע",
  "store": "קראָם",
  "not_exist": "נישט עקסיסטירט",
  "error": "טעות",
  "active": "אַקטיוו",
  "inactive": "ינאַקטיוו",
  "required_value": "פארלאנגט וואַלועס",
  "original_warranty": "אָריגינעל פּראָדוקט גאַראַנטירן",
  "return_warranty_days": "{days} צוריקקומען גאַראַנטירן טאָג (s)",
  "no_return_warranty": "קיין צוריקקער",
  "reed_agree_terms": "איך האָבן לייענען די טערמינען פון נוצן און פּריוואַטקייט פּאָליטיק און שטימען מיט זיי.",
  "commons": {
    "Currency": "קראַנטקייַט",
    "COD": "COD",
    "State": "שטאַט",
    "Price": "פּרייַז",
    "order_price": "סדר סומע",
    "VAT": "VAT",
    "Discount": "אַראָפּרעכענען",
    "In_Stock": "אין סטאק",
    "Variants": "וועריאַנץ",
    "No_variants": "קיין וואַריאַנט",
    "all": "אַלע",
    "today": "היינט",
    "yesterday": "נעכטן",
    "license": "ליסענסע",
    "home": "היים",
    "support": "שטיצן",
    "messages": "אַרטיקלען",
    "no_message": "קיין אָנזאָג",
    "empty": "ליידיק",
    "phone": "טעלעפאָן",
    "address": "אַדרעס",
    "name": "נאָמען",
    "password": "שפּריכוואָרט",
    "email": "בליצפּאָסט",
    "mobile": "מאָביל",
    "login": "צייכן אריין",
    "register": "רעגיסטרירן",
    "select_account": "אויסקלייַבן חשבון",
    "online": "אָנליין",
    "offline": "אָפפלינע",
    "finish": "ענדיקן",
    "finished": "געענדיקט",
    "preview": "פאָרויסיקע ווייַזונג",
    "free": "פרייַ",
    "free_completely": "גאָר פריי אַבאָנעמענט",
    "fee": "אָפּצאָל",
    "month": "חודש",
    "months": "חדשים",
    "faq": "אָפט געשטעלטע פֿראגן",
    "question": "פראגע",
    "answer": "ענטפער",
    "create_date": "שאַפֿן דאַטע",
    "update_date": "דערהייַנטיקן דאַטע",
    "start_date": "אנהייב דאטום",
    "end_date": "סוף טאָג",
    "social": "סאציאל",
    "total": "גאַנץ",
    "orders": "אָרדערס",
    "sessions": "סעשאַנז",
    "product_views": "פּראָדוקט קוקן",
    "add_to_carts": "לייג צו קאַרץ",
    "checkouts": "קוק עס אויף",
    "payments": "צאָלונג",
    "organic_search": "אָרגאַניק זוכן",
    "other": "אנדערע",
    "landing_page": "לאַנדינג בלאַט",
    "discount_code": "אַראָפּרעכענען קאָד",
    "total_sell": "גאַנץ פארקויפונג",
    "details": "דעטאַילס",
    "currency": "קראַנטקייַט",
    "amount": "סומע",
    "published": "פֿאַרעפֿנטלעכט",
    "draft": "פּלאַן",
    "save_changes": "האלט די טוישונגען",
    "source": "מקור",
    "medium": "מיטל",
    "url": "URL",
    "revenue": "רעוועך",
    "performance": "פאָרשטעלונג",
    "term": "טערמין",
    "content": "אינהאַלט",
    "session": "סעסיע",
    "product": "פּראָדוקט",
    "add": "לייג צו",
    "checkout": "קוק עס אויף",
    "payment": "צאָלונג",
    "more_options": "מער אָפּציעס",
    "full_name": "גאנצע נאמען",
    "tel": "טעל",
    "about_me": "וועגן מיר",
    "request_checking": "בעטן קאָנטראָלירונג",
    "passport": "פאספארט",
    "birthday": "דיין געבורסטאָג",
    "country": "לאַנד",
    "city": "שטאָט",
    "gender": "דזשענדער",
    "offer": "פאָרשלאָג",
    "website": "וועבזייַטל",
    "apply_for_all_products": "∞ צולייגן פֿאַר אַלע פּראָדוקטן",
    "fix_commission": "פאַרפעסטיקט קאָמיסיע",
    "percent_commission": "פּראָצענט קאָמיסיע",
    "fixed_discount": "פאַרפעסטיקט אַראָפּרעכענען",
    "discount_percentage": "פּראָצענט אַראָפּרעכענען",
    "discount_limit": "אַראָפּרעכענען שיעור",
    "no_code": "קיין קאָד",
    "max_count": "מאַקסימום ציילן",
    "count_unit": "זאכן",
    "used": "געניצט",
    "daily": "טעגלעך",
    "monthly": "כוידעשלעך",
    "yearly": "יאָריק",
    "state": "סטאַטוס",
    "disable": "דיסייבאַל",
    "enable": "געבן",
    "activation_code": "אקטיוויזאציע קאוד",
    "quantity": "קוואַנטיטי",
    "no_club": "קיין קלוב",
    "per_order": "פּער סדר",
    "count": "ציילן",
    "seconds": "סעקונדעס",
    "auto": "אַוטאָ",
    "title": "טיטל",
    "message": "אָנזאָג",
    "width": "ברייט",
    "length": "לענג",
    "height": "הייך",
    "label": "לאַבעל",
    "click": "דריקט",
    "bank": "באַנק",
    "default": "פעליקייַט",
    "role": "ראָלע",
    "user": "באַניצער",
    "users": "יוזערז",
    "code": "קאָד",
    "total_payment": "גאַנץ צאָלונג",
    "balance": "וואָג",
    "chance": "געלעגנהייַט",
    "free_for_new_users": "פריי פֿאַר נייַע ניצערס",
    "prize_amount": "פרייז סומע",
    "win": "געווינען",
    "gift_card": "מתנה קארטל",
    "discount": "אַראָפּרעכענען",
    "config": "קאָנפיג",
    "prize": "פרייז",
    "Prizes": "פּרייזאַז",
    "result": "רעזולטאַט",
    "price": "פּרייַז",
    "lottery": "לאָטעריע",
    "coupon": "קופּאָן",
    "customer_club": "קונה קלוב",
    "shipping": "שיפּינג",
    "sum": "סאַכאַקל",
    "not_paid": "ניט באַצאָלט",
    "category": "קאַטעגאָריע",
    "done": "געטאן",
    "email_from": "פון",
    "subject": "ענין",
    "schedule": "פּלאַן",
    "files_list": "פילעס רשימה",
    "file_max_size": "מאַקסימום טעקע גרייס",
    "value": "ווערט",
    "help": "הילף",
    "shipping_tax": "שיפּינג שטייַער",
    "net_price": "נעץ פּרייַז",
    "tax": "שטייַער",
    "tax_included": "אַרייַנגערעכנט אין פּרייַז",
    "limit": "באַגרענעצן",
    "min_purchase": "מינימום קויפן",
    "eligible_for": "פּאַסיק פֿאַר",
    "only_for_first_buy": "בלויז פֿאַר ערשטער קויפן",
    "one_time_use": "קענען נוצן איין מאָל",
    "period_of_qualify": "פּעריאָד באַניץ שיעור",
    "no_constraint": "קיין שיעור",
    "timespan": "צייט צייַט",
    "days": "טאָג(ן)",
    "weight": "וואָג",
    "distance": "דיסטאַנסע",
    "last_status": "לעצטע סטאַטוס",
    "issued_at": "ארויס אין",
    "order": "סדר",
    "order_detail": "סדר פרטים",
    "percent": "פּראָצענט",
    "applied_count": "געווענדט ציילן",
    "campaign": "קאַמפּיין",
    "os": "אַפּערייטינג סיסטעם",
    "browser": "בלעטערער",
    "device": "מיטל",
    "device_ip": "מיטל IP אַדרעס",
    "location": "אָרט",
    "user_agent": "באַניצער אַגענט",
    "affiliate": "צוגעבן",
    "timeline": "טיימליין",
    "add_note": "לייג טאָן",
    "record": "רעקאָרד",
    "unlimited": "ונלימיטעד",
    "show_coupons": "ווייַזן קופּאָנז",
    "hide_coupons": "באַהאַלטן קופּאָנז",
    "service_area": "סערוויס געגנט",
    "apps": "אַפּפּס",
    "plugins": "פּלוגינס",
    "bots": "באָץ",
    "categories": "קאַטעגאָריעס",
    "products": "פּראָדוקטן",
    "business": "געשעפט",
    "personal": "פערזענליכע",
    "size": "גרייס",
    "holiday": "יום טוּב",
    "sod": "באַצאָלן אויף עקספּרעס",
    "cod": "געלט אויף עקספּרעס",
    "free_shipping": "שיקן אומזיסט",
    "hours": "שעהן",
    "send_date": "שיפּינג דאַטע",
    "deliver_date": "דעליווערי דאטע",
    "return_date": "צוריקקומען טאָג",
    "pending": "פּענדינג",
    "delivered": "איבערגעגעבן",
    "returned": "אומגעקערט",
    "canceled": "קאַנסאַלד",
    "shipping_cost": "שיפּינג פּרייַז",
    "action": "קאַמף",
    "cancel_date": "באָטל מאַכן דאַטע",
    "deliver_in_process": "די סדר איז געשיקט ..",
    "kind": "טיפּ",
    "detail": "דעטאַילס",
    "map": "מאַפּע",
    "actions": "אַקשאַנז",
    "navigation": "נאַוויגאַציע",
    "navigation_app": "אַפּפּליקאַטיאָן",
    "payment_date": "צאָלונג דאַטע",
    "duration": "געדויער",
    "bill": "ביל",
    "delivery_persons": "קעריערז",
    "delivery_services": "עקספּרעס באַדינונגס",
    "live_view": "לעבן מיינונג",
    "cart": "קאַרט",
    "priority": "בילכערקייַט",
    "sufficient_credit": "גענוג קרעדיט",
    "max_package_size": "מאַקסימום פּעקל גרייס",
    "delay": "פאַרהאַלטן",
    "credit": "קרעדיט",
    "livemode": "לעבן",
    "paused": "פּאַוזד",
    "debug": "דיבוג",
    "token": "סימען",
    "status": "סטאַטוס",
    "courier": "קעריער",
    "track": "שפּור",
    "track_order": "סדר טראַקינג",
    "cost": "פּרייַז",
    "receipt": "קאַבאָלע",
    "origin": "אָריגין",
    "destination": "דעסטיניישאַן",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "ניט גענוג לאַגער!",
    "sub_total": "סובטאָטאַל",
    "customer": "קונה",
    "delivery": "עקספּרעס",
    "online_orders": "אָנליין אָרדערס",
    "pos_orders": "POS אָרדערס",
    "chips": "טשיפּס",
    "subscribed": "אַבאָנירן",
    "unsubscribed": "אַנסאַבסקרייבד",
    "last_login": "לעצטע לאָגין",
    "join_at": "פאַרבינדן דאַטע",
    "club": "קלוב",
    "buyer": "קוינע",
    "seller": "טרעגער",
    "or": "אָדער",
    "type": "טיפּ",
    "condition": "צושטאַנד",
    "brand": "סאָרט",
    "attempt": "פּרווון",
    "error": "טעות",
    "success": "הצלחה",
    "fail": "דורכפאַלן",
    "inventory": "ינוואַנטאָרי",
    "link": "לינק",
    "visits": "וויזיץ",
    "transactions": "טראַנזאַקשאַנז",
    "vat": "VAT",
    "pos_vat": "POS VAT",
    "sort_by": "סאָרט דורך ..",
    "from": "פון",
    "from_lead_time": "אין די ווייַטער {hours} שעה",
    "no_credit_card_info": "קיין קאָרט אינפֿאָרמאַציע!",
    "active": "אַקטיוו",
    "not_active": "ניט אַקטיווייטיד!",
    "referrals": "רעפערראַלס",
    "dashboard": "דאַשבאָרד",
    "more": "מער",
    "inactive": "ינאַקטיוו",
    "developer": "דעוועלאָפּער",
    "setting": "באַשטעטיקן",
    "membership_conditions": "מיטגלידערשאַפֿט באדינגונגען",
    "customers": "קאַסטאַמערז",
    "created_at": "באשאפן דאַטע",
    "updated_at": "לעצטע דערהייַנטיקן",
    "register_at": "רעגיסטרירן דאַטע",
    "old": "אַלט",
    "new": "נייַ",
    "start": "אָנהייב",
    "end": "סוף",
    "pos": "POS",
    "out_of_stock": "אויס פון לאַגער",
    "fake": "שווינדל",
    "low_inventory_warning": "ופמערקזאַמקייַט, נידעריק ינוואַנטאָרי!",
    "webhook": "וועבהאָאָק",
    "notification": "אָנזאָג",
    "sms": "SMS",
    "online_payment_link": "אָנליין צאָלונג לינק",
    "waiting_load_data": "ווארטן צו לאָדן דאַטן ..",
    "views": "קוקן",
    "sales": "סאַלעס",
    "total_views": "גאַנץ קוקן",
    "total_sales": "גאַנץ פארקויפונג",
    "from_previous_n_days": "פון לעצטע {days} טעג",
    "drop_shipping": "דראָפּשיפּפּינג",
    "commission": "קאָמיסיע",
    "shipping_area": "שיפּינג געגנט",
    "main_seller": "הויפּט טרעגער",
    "domain": "פעלד",
    "contact": "קאָנטאַקט אינפֿאָרמאַציע",
    "wallet": "בייַטל",
    "reseller": "ריסעלער",
    "tracking_code": "טראַקינג קאָד",
    "tracking_url": "טראַקינג URL",
    "fulfillments": "מקיים",
    "reject": "אָפּוואַרפן",
    "reserved": "רעזערווירט",
    "score": "כעזשבן",
    "customer_price": "קונה פּרייַז",
    "options": "אָפּציעס",
    "show_details": "ווייז דעטאלן",
    "no_data": "קיין דאַטן..",
    "waiting": "ווארטן...",
    "waiting_connecting_payment": "ווארטן פֿאַר די צאָלונג דינסט ...",
    "creating_secure_payment": "שאפן זיכער צאָלונג.",
    "officer": "אָפיציר",
    "ticket": "בילעט",
    "ticket_url": "בילעט URL",
    "closed_at": "פארמאכט אין",
    "close_ticket": "נאָענט בילעט",
    "reopen_ticket": "ווידער עפענען בילעט",
    "require": "דאַרפן*",
    "search": "זוך...",
    "language": "שפּראַך",
    "tasks": "טאַסקס",
    "permissions": "פּערמישאַנז",
    "finish_date": "סוף טאָג",
    "complete_date": "קאַמפּלישאַן טאָג",
    "settle_date": "סעטאַלמאַנט טאָג",
    "cost_span": "פּרייַז קייט",
    "industry": "אינדוסטריע",
    "rating": "רייטינגז",
    "rates": "שאַץ",
    "seen_at": "געזען ביי",
    "completed": "געענדיקט",
    "you": "איר",
    "shop": "קראָם",
    "store": "קראָם",
    "granted": "געגעבן",
    "deny": "לייקענען",
    "request": "בעטן",
    "expert": "מומחה",
    "response": "ענטפער",
    "requests": "ריקוועס",
    "experts": "עקספּערץ",
    "responses": "ענטפער",
    "negotiations": "נאַגאָושייישאַנז",
    "all_chats": "אַלע שמועסן",
    "chats": "טשאַץ",
    "tags": "טאַגס",
    "description": "באַשרייַבונג",
    "rates_count": "נומער פון רייטינגז",
    "rate": "שאַץ",
    "comment": "באַמערקונג",
    "chat": "שמועסן",
    "install": "ינסטאַלירן",
    "edited": "עדיטיד",
    "undo": "ופמאַכן",
    "redo": "רעדאָ",
    "male": "זכר",
    "female": "ווייַבלעך",
    "calculator": "קאַלקולאַטאָר",
    "catalog": "קאַטאַלאָג",
    "max_height": "מאַקסימום הייך",
    "images_compare": "בילדער פאַרגלייַך",
    "canvas": "לייַוונט",
    "table_of_contents": "אינהאַלט פון אינהאַלט",
    "comments": "באַמערקונגען",
    "badge_codes": "באַדזשיז קאָד",
    "need_more": "דאַרפֿן מער?",
    "invite_glow_caption": "באַקומען 14.9 $ פֿאַר יעדער פרייַנד!",
    "register_free": "100% פריי רעגיסטרירן",
    "gift": "טאַלאַנט",
    "google": "גוגל",
    "facebook": "Facebook",
    "instagram": "ינסטאַגראַם",
    "instashop": "ינסטאַסטשאָפּ",
    "show": "ווייַזן",
    "hide": "באַהאַלטן",
    "waiting_review": "ווארטן רעצענזיע",
    "not_selected": "ניט אויסגעקליבן",
    "time": "צייַט",
    "final_price": "לעצט פּרייַז",
    "starting_price": "סטאַרטינג פּרייַז",
    "day": "טאָג",
    "paid": "באַצאָלט",
    "service_bill": "ינווויס צאָלונג",
    "avocado": "אַוואָקאַדאָ",
    "delivery_price": "שיפּינג פּרייַז",
    "select_address": "אויסקלייַבן אַדרעס",
    "image": "בילד",
    "view": "View",
    "sell": "פאַרקויף",
    "hyper": "היפּער",
    "cart_list": "קאַרט",
    "barcode_scanner": "באַרקאָדע סקאַננער",
    "scan_qr_code": "יבערקוקן QR קאָד",
    "new_carts": "נייַ קאַרץ",
    "pays": "פּיימאַנץ",
    "annually": "יערלעך",
    "sells": "סאַלעס",
    "articles": "ארטיקלען",
    "jobs": "דזשאָבס",
    "job": "אַרבעט",
    "blog": "בלאָג",
    "deleted_at": "אויסגעמעקט ביי",
    "capacity": "קאַפּאַציטעט",
    "download_at": "לעצטע אראפקאפיע טאָג",
    "downloads": "דאַונלאָודז",
    "usage": "באַניץ",
    "select_upload_file": "אויסקלייַבן אָדער פאַלן טעקע",
    "download_link": "אראפקאפיע לינק",
    "uploading": "ופּלאָאַדינג..",
    "files": "טעקעס",
    "star": "שטערן",
    "speed": "ספּיד",
    "feedback": "באַמערקונגען",
    "new_messages": "ניו אַרטיקלען",
    "file": "טעקע",
    "attachment": "אַטאַטשמאַנט",
    "gallery": "גאַלערי",
    "sync": "סינק",
    "diff_time": "צייט חילוק",
    "network": "נעץ",
    "account": "חשבון",
    "configuration": "קאָנפיגוראַטיאָן",
    "blockchain": "בלאָקטשיין",
    "blog_link": "בלאָג לינק",
    "community": "קהילה",
    "critical_zone": "קריטיש זאָנע",
    "statistics": "סטאַטיסטיק",
    "access": "אַקסעס",
    "seo": "SEO",
    "followers": "אנהענגערס",
    "followings": "פאָלגענדע",
    "private": "פאָרויסיקע ווייַזונג",
    "soon": "באלד",
    "features": "איינריכטונגען",
    "bot": "Bot",
    "sample": "מוסטער",
    "how_it_work": "וויאזוי ארבייט עס?",
    "page": "זייַט",
    "congratulations": "מאַזל - טאָוו",
    "recommend": "רעקאָמענדירן",
    "recommended": "רעקאַמענדיד",
    "recoms": "רעקאַמאַנדיישאַנז",
    "likes": "לייקס",
    "clicks": "קליקס",
    "platform": "פּלאַטפאָרמע",
    "cms": "CMS",
    "cash": "געלט",
    "dir_payment": "באַנק אַריבערפירן",
    "auto_complete": "אַוטאָ גאַנץ",
    "compare": "פאַרגלייַכן",
    "infinite": "Infinite",
    "tips": "עצות",
    "technical": "טעכניש",
    "finance": "פינאַנצן",
    "your_phone_input": "אַרייַן אַ טעלעפאָן נומער",
    "income": "האַכנאָסע",
    "change": "טוישן",
    "new_users": "ניו ניצערס",
    "success_orders": "געראָטן אָרדערס",
    "direct": "דירעקט",
    "last_activity": "לעצטע טעטיקייט",
    "landing": "לאַנדינג",
    "now": "איצט",
    "accept_agreement": "איך האב געליינט און אנגענומען די תנאים.",
    "report": "באַריכט",
    "tablet": "טאַבלעט",
    "pc": "PC",
    "acquisition_channel": "אַקוואַזישאַן קאַנאַל",
    "to": "צו",
    "info": "אינפֿאָרמאַציע",
    "general": "אַלגעמיינע",
    "upload": "צופֿעליקער",
    "general_config": "אַלגעמיינע קאָנפיגוראַטיאָן",
    "limits_config": "לימיטיישאַנז",
    "design_config": "פּלאַן & סטייל",
    "duration_config": "געדויער שיעור",
    "constraints_config": "בארעכטיגונג לימאַץ",
    "clubs_config": "בנימצא אין קלאַבז",
    "additional_config": "נאָך קאַנפיגיעריישאַנז",
    "import": "אַרייַנפיר",
    "ribbon": "בענד",
    "countries": "לענדער",
    "edit": "רעדאַגירן",
    "delete": "ויסמעקן",
    "analytics": "אַנאַליטיקס",
    "rules": "כּללים",
    "unset": "ניט באַשטימט",
    "carts": "קאַרץ",
    "optional": "אָפּטיאָנאַל",
    "design": "פּלאַן",
    "filter": "פילטער",
    "send": "שיקן",
    "approved": "באוויליקט",
    "unit": "אַפּאַראַט",
    "profile": "פּראָפיל",
    "shipping_rates": "שיפּינג רייץ",
    "package": "פּעקל",
    "overview": "איבערבליק",
    "live": "לעבן",
    "never": "קיינמאָל",
    "always": "אַלע מאָל",
    "mandatory": "מאַנדאַטאָרי",
    "expire_at": "עקספּיירי טאָג",
    "position": "שטעלע",
    "channel": "קאַנאַל",
    "age": "עלטער",
    "charge": "אָפּצאָל",
    "giftcard": "מתנה קארטל",
    "acquisition": "אַקוואַזישאַן",
    "conversion": "קאַנווערזשאַן",
    "total_payments": "גאַנץ פּיימאַנץ",
    "community_ask": "פרעגן אין קהל",
    "children": "קינדער",
    "export": "עקספּאָרט",
    "list": "רשימה",
    "hierarchy": "כייעראַרקי",
    "images": "בילדער",
    "demo": "דעמאָ",
    "author": "מחבר",
    "designer": "דיזיינער",
    "max": "מאַקסימום",
    "accepted": "אנגענומען",
    "reply": "ענטפער",
    "reviewed": "ריוויוד",
    "restored": "געזונט",
    "merchant": "סוחר",
    "per_product": "פּער פּראָדוקט",
    "journey": "נסיעה",
    "after": "נאָך",
    "waiting_for_payment": "ביטע פאַרענדיקן צאָלונג ...",
    "hour": "שעה",
    "minute": "מינוט",
    "premium": "פּרעמיום",
    "light": "ליכט",
    "dark": "טונקל",
    "guest": "גאַסט",
    "shops": "קלייטן",
    "vendor": "פאַרקויפער",
    "vendors": "ווענדאָרס",
    "marketplace": "מאַרקעטפּלאַסע",
    "verify_date": "באַשטעטיקן דאַטע",
    "note": "נאטיץ",
    "panel": "טאַפליע",
    "removed": "אַוועקגענומען",
    "segments": "סעגמאַנץ",
    "personal_info": "פערזענלעכע אינפֿאָרמאַציע",
    "preferences": "פּרעפֿערענצן",
    "spec": "ספּעק",
    "reviews": "באריכטן",
    "constraints": "קאַנסטריינץ",
    "flexible": "פלעקסאַבאַל",
    "usage_limit": "באַניץ שיעור",
    "temporary": "צייטווייליגע",
    "original": "אָריגינעל",
    "saved": "געראטעוועט!",
    "sort": "סאָרט",
    "documents": "דאָקומענטן",
    "document": "דאָקומענט",
    "please_wait": "ביטע ווארט...",
    "pickup": "הייב אויף",
    "customize": "קאַסטאַמייז",
    "difficulty": "שוועריקייט",
    "banned": "באַנד",
    "company": "פירמע",
    "tax_shipping": "שיפּינג טאַקס",
    "warranty": "וואָראַנטי",
    "return_policy": "צוריקקומען פּאָליטיק",
    "guide": "גייד",
    "translate": "איבערזעצן",
    "public": "עפנטלעך",
    "deleted": "אויסגעמעקט",
    "variant": "וואַריאַנט",
    "secure": "זיכער",
    "admin": "אַדמין",
    "tax_included_abstract": "ינקל.",
    "payment_not_settled": "צאָלונג נישט געזעצט!",
    "orders_list": "אָרדערס רשימה",
    "subscription_plan": "אַבאָנעמענט פּלאַן",
    "contents": "אינהאַלט",
    "pricings": "פּרייסינג",
    "static_page": "סטאַטיק בלאַט",
    "shop_button": "קראָם קנעפּל",
    "embed": "עמבעד",
    "over": "אַריבער",
    "tax_vary_by_location": "בייַטן. אָרט",
    "product_type": "פּראָדוקט טיפּ",
    "tax_id": "שטייער שייַן",
    "business_name": "געשעפט נאָמען",
    "invoice": "ינווויס",
    "included_in_the_product": "אַרייַנגערעכנט אין די פּראָדוקט",
    "included_in_the_product_description": "דער פּראָדוקט כולל די פאלגענדע קאַמפּאָונאַנץ",
    "cross_sell": "קרייַז פאַרקויפן",
    "discount_off": "OFF",
    "extra_discount": "עקסטרע אַראָפּרעכענען",
    "template": "מוסטער",
    "in_cart": "אין קאַרט",
    "pros_and_cons": "מעלות און חסרונות",
    "related_products": "פֿאַרבונדענע פּראָדוקטן",
    "related_categories": "שייַכות קאַטעגאָריעס",
    "badges": "באַדזשיז",
    "explore": "ויספאָרשן"
  },
  "dialogs": {
    "delete": {
      "title": "ויסמעקן",
      "message": "זענט איר זיכער צו ויסמעקן דעם נומער?",
      "action": "יא, דיליט איצט"
    }
  },
  "actions": {
    "add_to_cart": "לייג צו צום קארטע",
    "cancel": "באָטל מאַכן",
    "update": "דערהייַנטיקן",
    "add": "לייג צו",
    "delete": "ויסמעקן",
    "new": "נייַ",
    "save_continue": "היט & פאָרזעצן",
    "save": "היט",
    "save_changes": "האלט די טוישונגען",
    "change": "טוישן",
    "continue": "פאָרזעצן",
    "close": "נאָענט",
    "finish": "ענדיקן",
    "poll": "אַנקעטע",
    "view": "View",
    "edit": "רעדאַגירן",
    "next": "ווייַטער",
    "previous": "פֿריִערדיקע",
    "create": "שאַפֿן",
    "set": "שטעלן",
    "find": "געפֿינען",
    "accept": "אָננעמען",
    "reject": "אָפּוואַרפן",
    "back": "צוריק",
    "pay": "באַצאָלן",
    "pay_now": "באצאל יעצט",
    "print": "דרוקן",
    "return": "צוריקקומען",
    "publish": "אַרויסגעבן",
    "confirm": "באַשטעטיקן",
    "copy": "קאָפּי",
    "submit": "פאָרלייגן",
    "send": "שיקן",
    "yes": "יא",
    "no": "ניין",
    "meh": "הממ",
    "clear": "קלאָר",
    "dismiss": "אָפּזאָגן",
    "search": "זוכן",
    "deselect_all": "ויסמעקן אַלע",
    "select_all": "וועל אויס אלע",
    "refresh": "דערפרישן",
    "verify": "באַשטעטיקן",
    "play": "שפּיל",
    "open": "עפענען",
    "calculate": "רעכענען",
    "quick_buy": "שנעל קויפן",
    "click_here": "קליק דא",
    "schedule": "פּלאַן",
    "send_now": "שיקן איצט",
    "download": "אראפקאפיע",
    "reset_default": "באַשטעטיק צו פעליקייַט",
    "reset": "באַשטעטיק",
    "check": "טשעק",
    "cod_payment": "געלט אויף עקספּרעס",
    "dir_payment": "געלט אַריבערפירן",
    "online_payment": "אָנליין צאָלונג",
    "checkout": "קוק עס אויף",
    "show_all": "ווייז אלע",
    "login": "צייכן אריין",
    "logout": "Logout",
    "more": "מער..",
    "collapse": "ייַנבראָך",
    "apply_change": "צולייגן ענדערונגען",
    "apply": "צולייגן",
    "add_giftcard": "לייג טאַלאַנט קאָרט",
    "charge": "אָפּצאָל",
    "send_invites": "שיקן ינוויטיישאַנז",
    "past": "פאַרגאַנגענהייט",
    "restore": "ריסטאָר",
    "cut": "שנייַדן",
    "get_sms_code": "באַקומען אָטענטאַקיישאַן קאָד",
    "register_no_mail": "פאָרזעצן אָן בליצפּאָסט",
    "no_mail_register_message": "צי ניט האָבן אַן E- בריוו אַדרעס אָדער פֿאַרגעסן דיין פּאַראָל?",
    "reset_by_mail": "שפּריכוואָרט אָפּזוך דורך בליצפּאָסט",
    "reset_by_sms": "שפּריכוואָרט אָפּזוך דורך SMS",
    "cash_payment": "געלט צאָלונג",
    "show_chart": "ווייַזן טשאַרט",
    "open_app": "עפענען אַפּ",
    "login_now": "לאָגין איצט",
    "watch_video": "וואַך ווידעא",
    "check_now": "קוק איצט",
    "remove_image": "אַראָפּנעמען בילד",
    "view_website": "עפענען לינק",
    "explore": "ויספאָרשן {name}",
    "go": "גיי",
    "read_more": "לייענען מער",
    "start_now": "אָנהייב איצט - עס איז פריי",
    "view_live": "זען לעבן",
    "resend_code": "ווידער שיקן קאָד",
    "invite": "לאַדן",
    "add_more": "לייג מער",
    "install_now": "ינסטאַלירן איצט",
    "uninstall": "נעם אַוועק",
    "show_preview": "ווייַזן פאָרויסיקע ווייַזונג",
    "hide_preview": "באַהאַלטן פאָרויסיקע ווייַזונג",
    "download_now": "דאוונלאוד יעצט",
    "auto_fill": "אַוטאָפילל",
    "track": "שפּור",
    "change_state": "טוישן סטאַטוס",
    "done": "געטאן",
    "reply": "ענטפער",
    "watch_now": "קוק יעצט",
    "unlock": "ופשליסן",
    "lock": "שלאָס",
    "create_clone": "שאַפֿן קלאָון",
    "regenerate": "רידזשענערייט",
    "add_message": "לייג אָנזאָג",
    "continue_chat": "פאָרזעצן שמועסן",
    "add_new_message": "לייג אַ נייַע אָנזאָג",
    "change_setting": "טוישן באַשטעטיקן",
    "delete_all": "ויסמעקן אַלע",
    "transfer_fund": "אַריבערפירן פאָנד",
    "reverse_fund": "פאַרקערט פאָנד",
    "settlement": "ייִשובֿ",
    "refund": "צוריקצאָל",
    "partial_refund": "טייל צוריקצאָל",
    "change_payment_method": "טוישן צאָלונג אופֿן",
    "buy": "קויפן",
    "view_all": "זעה אלעס",
    "view_now": "View איצט"
  },
  "instance_message_title": "שיקן רעגע אָנזאָג",
  "instance_message": "הי {name}, מיין נאָמען איז {author} פֿון {company}.",
  "errors": {
    "419": "איר האָט שוין ינאַקטיוו פֿאַר אַ לאַנג צייַט, ביטע <b>⟳ דערפרישן די בלאַט</b> פֿאַר זיכערהייט סיבות.",
    "gateway_blockchain_sync_error": "די סיסטעם טוט נישט סינגקראַנייז מיט די בלאָקטשיין. עס וועט ניט זיין מעגלעך צו שאַפֿן אַ נייַע טראַנסאַקטיאָן ביז די סינגקראַנאַזיישאַנז פון אונדזער סערווערס זענען געענדיקט. מיר זענען סאַלווינג די פּראָבלעם.",
    "gateway_network_error": "צאָלונג גייטוויי דינסט האט געפּלאָנטערט אַ קאָמוניקאַציע פּראָבלעם."
  },
  "receiver_info": {
    "map": {
      "title": "אדרעס צו שיקן",
      "confirm": "שטעלן אָרט",
      "address_type": "דעסטיניישאַן",
      "receptor_type": "באקומער"
    },
    "receiver_address": "אויסקלייַבן שיפּינג אַדרעס",
    "address": "אַדרעס",
    "postcode": "פּאָסטקאָדע",
    "enter_value": "פּלאָמבירן דאָ",
    "address_note": "נאטיץ",
    "tel": "קאָנטאַקט נומער",
    "service_address": "אויסקלייַבן דיין אַדרעס"
  },
  "weight": {
    "g": "ג",
    "oz": "אַז",
    "lb": "לב",
    "kg": "קג"
  },
  "mass_unit_name": {
    "g": "גראַם",
    "oz": "אונס",
    "lb": "פונט",
    "kg": "קילאָ"
  },
  "length": {
    "cm": "סענטימעטער",
    "in": "אין",
    "ft": "ft",
    "mm": "מם",
    "m": "עם",
    "yd": "yd"
  },
  "size_unit_name": {
    "cm": "סענטימעטער",
    "in": "אינטש",
    "ft": "פֿיס",
    "mm": "מילאַמיטער",
    "m": "מעטער",
    "yd": "הויף"
  },
  "distance": {
    "m": "מעטער",
    "km": "קילאמעטער"
  },
  "time": {
    "days": "טעג",
    "hours": "שעהן",
    "minutes": "מינוטן",
    "seconds": "סעקונדעס"
  },
  "units": [
    "אַפּאַראַט",
    "נומער",
    "יעדער",
    "שטעלן",
    "שטיק",
    "קילאָ",
    "גראַם",
    "מילאַגראַם",
    "מעטער",
    "מילאַמיטער",
    "קוואַדראַט מעטער",
    "קוואַדראַט פֿיס",
    "קוביק מעטער",
    "ליטער",
    "מילליליטער",
    "פֿיס",
    "גאלאנען",
    "אינטשעס",
    "אונס",
    "פונט",
    "קוואַרץ",
    "יאַרדס",
    "צימער",
    "סעקונדעס",
    "מינוט",
    "שעה",
    "טעג",
    "וואָכן",
    "חדשים",
    "יאָרן"
  ],
  "region_types": {
    "State": "שטאַט",
    "Territory": "טעריטאָריע",
    "Province": "פּראָווינץ"
  },
  "transaction_status": {
    "RequireAction": "קאַמף פארלאנגט",
    "Processing": "פּראַסעסינג",
    "Canceled": "קאַנסאַלד",
    "Succeeded": "מצליח געווען"
  },
  "placeholders": {
    "name": "דזשאָן קאָקס",
    "email": "your-mail@mail.com",
    "phone": "+1 000 0000",
    "language": "אויסקלייַבן שפּראַך..",
    "friend_email": "דיין פרייַנד 'ס בליצפּאָסט ...",
    "friend_name": "אָפּט. דיין פרייַנד 'ס נאָמען",
    "select_date": "אויסקלייַבן אַ דאַטע ..."
  },
  "notification": {
    "confirm": "באַשטעטיקן",
    "confirm_message": "ענדערונגען געראטעוועט הצלחה.",
    "error": "טעות",
    "message": "אָנזאָג",
    "caution": "וואָרענען",
    "warning": "ווארענונג",
    "award": "מאַזל - טאָוו",
    "error_message": "צום באַדויערן, אַ טעות איז פארגעקומען.",
    "congratulation": "מאַזל - טאָוו",
    "coming_soon": "באלד",
    "on_fetching_data": "באַקומען אינפֿאָרמאַציע ..",
    "new_pwa_version": "ניו ווערסיע בנימצא איצט. צי איר ווילן צו דערהייַנטיקן די אַפּלאַקיישאַן?",
    "over_license_limit": "איבער ליסענסע לימיט",
    "update_license": "דערהייַנטיקן דיין דערלויבעניש",
    "required": "פארלאנגט",
    "invalid_email": "אומגילטיק בליצפּאָסט",
    "invalid_domain": "אומגילטיק פעלד",
    "invalid_min_length": "מינימום לענג מוזן זיין {length}",
    "invalid_min_array_length": "אין מינדסטער אויסקלייַבן {length} זאכן",
    "invalid_max_chars": "מאַקסימום {maxCount} אותיות",
    "invalid_url": "אומגילטיק URL",
    "country_invalid": "אויסקלייַבן דעסטיניישאַן לאַנד!",
    "postal_code_invalid": "שטעלן גילטיק פּאָסטקאָד!"
  },
  "colors": {
    "#D32F2F": "רויט",
    "#C2185B": "ראָזעווע",
    "#7B1FA2": "לילאַ",
    "#512DA8": "טונקל לילאַ",
    "#303F9F": "ינדיגאָ בלוי",
    "#1976D2": "בלוי",
    "#0288D1": "ליכטיג בלוי",
    "#0097A7": "טערקווויז בלוי",
    "#00796B": "גאַנדז גרין",
    "#388E3C": "גרין",
    "#689F38": "ליכט גרין",
    "#AFB42B": "לימאָ",
    "#FBC02D": "געל",
    "#FFA000": "בורשטין",
    "#F57C00": "מאַראַנץ",
    "#E64A19": "בלאַנק אָראַנדזש",
    "#5D4037": "ברוין",
    "#616161": "גרוי",
    "#455A64": "גרוי בלוי",
    "#FFD700": "גאָלדען",
    "#C0C0C0": "זילבער",
    "#b76e79": "גאָלדען רויז",
    "#383838": "מאַט שוואַרץ",
    "#FFFFFF": "ווייַס",
    "#FFF": "ווייַס",
    "#000000": "שוואַרץ",
    "#000": "שוואַרץ",
    "#7d263a": "מערון",
    "#FD9F17": "גאָלד",
    "#229DBF": "אַקוואַ",
    "#6DC9E2": "אַקוואַ טריבלענד",
    "#413B2D": "אַרמיי",
    "#474747": "אַספאָלט",
    "#E6195C": "יאַגדע",
    "#B2184C": "בערי טריבלענד",
    "#FC7F5F": "בערנט אָראַנדזש",
    "#80011F": "קאַרדינאַל",
    "#382829": "שאָקאָלאַד",
    "#F06336": "קאָראַל",
    "#FAE7C9": "קרעם",
    "#6B2257": "קורראַנט",
    "#222127": "טונקל גרוי",
    "#0D5A74": "טיף טיל",
    "#00582F": "עווערגרין",
    "#214C30": "וואַלד",
    "#DC2867": "פוטשסיאַ",
    "#38561F": "קעלי",
    "#5C884D": "בלאַט",
    "#558450": "ליכט אַקוואַ",
    "#96B5C9": "ליכטיג בלוי",
    "#DCAFCE": "לילאַק",
    "#D3E1A4": "לייַם",
    "#9DE7C2": "מינץ",
    "#F6EAD2": "נאַטירלעך",
    "#1A1F35": "נאַווי",
    "#404624": "מאַסלינע",
    "#271020": "פלוים",
    "#A8355C": "Raspberry",
    "#D6BEA6": "ווייך קרעם",
    "#BEA994": "טאַן",
    "#0DB2AE": "טיל",
    "#A86EA9": "פיאַלקע",
    "#36454F": "האָלצקוילן",
    "#b3b0ab": "טשאַד גריי",
    "#463e3d": "האָלצקוילן כעדער",
    "#282d3c": "נאַווי בלאַזער"
  },
  "address_info": {
    "name": "נאָמען",
    "tel": "טעלעפאָן",
    "email": "בליצפּאָסט",
    "country": "לאַנד",
    "city": "שטאָט",
    "state": "שטאַט",
    "address": "אַדרעס",
    "building_number": "בנין נומער",
    "building_unit": "אַפּאַראַט",
    "postcode": "פּאָסטקאָדע",
    "note": "נאטיץ",
    "county": "קאָונטי"
  },
  "product_types": {
    "physical": "פיזיש",
    "physical_description": "פיזיש פּראָדוקטן אַזאַ ווי: רירעוודיק פאָנעס, ביכער, עלעקטראָניש קאַמפּאָונאַנץ.",
    "virtual": "ווירטואַל",
    "virtual_description": "אינטערנעט-פרייַנדלעך פּראָדוקטן אַזאַ ווי: ריטשאַרדזש קאָרט, האָטעל רעזערוואַציע, שפּיל ריטשאַרדזש.",
    "file": "טעקע",
    "file_description": "כל דערלויבט טעקעס ווי אָנליין לויף ווידעא, דאָוונלאָאַדאַבלע דאָקומענטן.",
    "service": "סערוויס",
    "service_description": "סערוויסעס ווי: פאַרריכטן, טראַנספּערטיישאַן, לערנען.",
    "subscription": "אַבאָנעמענט",
    "subscription_description": "אַבאָנעמענט און ינווויסינג פֿאַר פּראָדוקטן, באַדינונגס אָדער אינהאַלט."
  },
  "license": {
    "free": "פרייַ",
    "startup": "הייב אן",
    "company": "פירמע",
    "enterprise": "פאַרנעמונג"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "טאָמאַן",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW",
    "GHS": "GHS",
    "ZWD": "ZWD",
    "IQD": "IQD",
    "SYP": "SYP"
  },
  "variants": {
    "color": "פאַרב",
    "volume": "גרייס",
    "count_in_pack": "ציילן אין פּאַק",
    "weight": "וואָג",
    "type": "מאַטעריאַל",
    "style": "סטייל"
  },
  "delivery_state": {
    "check_queue": "ווארטן רעצענזיע",
    "order_confirm": "באשטעלונג באשטעטיגונג",
    "preparing_order": "צוגרייטן",
    "sent_order": "אויף עקספּרעס",
    "to_customer": "איבערגעגעבן"
  },
  "status": {
    "unpaid": "ניט באַצאָלט",
    "paid": "באַצאָלט",
    "canceled": "קאַנסאַלד",
    "completed": "געזעצט",
    "reserved": "רעזערווירט",
    "COD": "COD",
    "sold": "סאָלד",
    "open": "עפענען",
    "cancel": "קאַנסאַלד",
    "active": "אַקטיוו",
    "inactive": "ינאַקטיוו",
    "debug": "דיבוג",
    "live": "לעבן",
    "test": "טעסט",
    "connected": "קאָננעקטעד",
    "disconnected": "דיסקאַנעקטיד",
    "accept": "אָננעמען",
    "reject": "אָפּוואַרפן",
    "pending": "פּענדינג",
    "rejected": "אפגעווארפן",
    "accepted": "אנגענומען"
  },
  "dimensions": {
    "cm": "סענטימעטער",
    "km": "קילאמעטער",
    "kg": "קג"
  },
  "transportation_type": {
    "motorbike": "מאָטאָרביקע",
    "motorbike_description": "מיטל וואָג אין אַ ביסל קילאָמעטערס.",
    "cargo_small": "קליין לאַסט",
    "cargo_small_description": "מאַלטי-קילאָמעטער ליכט לאַסט.",
    "cargo": "לאַסט",
    "cargo_description": "מיטל וואָג אין אַ ביסל קילאָמעטערס.",
    "truck": "טראָק",
    "truck_description": "פאַרנעם אָדער שווער לאַסט אין די מדינה.",
    "fast_post": "שנעל פּאָסטן",
    "fast_post_description": "שנעל פּאָסטינג דורך פּאָסט אָפיס.",
    "post": "נאָרמאַל פּאָסטן",
    "post_description": "רעגולער פּאָסטן דורך די פּאָסט אָפיס.",
    "airplane": "לופטפּאָסט",
    "airplane_description": "דינער און פרעמד ליכט און מיטל לאַסט.",
    "bicycle": "ריין שיקן",
    "bicycle_description": "ליכט לאַסט, ין אַ ביסל הונדערט יאַרדס פון ניט-מאָטאָר וועהיקלעס.",
    "global": "גלאבאלע טראַנספּערטיישאַן",
    "global_description": "שיפּינג מעייווער - לייאַם דורך לופט, ים אָדער לאַנד.",
    "pickup": "הייב אויף",
    "pickup_description": "קאַסטאַמערז קלייַבן די זאכן אין דיין גשמיות קראָם אָדער ווערכאַוס."
  },
  "article": {
    "login_to_see_error": "לאָגין צו אַקסעס דעם אַרטיקל",
    "create_new_action": "שאַפֿן נייַ אינהאַלט",
    "menu_title": "מעניו",
    "menu": {
      "edit": "רעדאַגירן מאָדע",
      "view_mode": "View מאָדע",
      "delete": "ויסמעקן אַרטיקל"
    },
    "schedule_action": "צי איר ווילן צו פּלאַן ארויסגעבן?",
    "schedule_title": "פּלאַן אַוטאָ-ארויסגעבן",
    "edit_mode": "רעדאַגירן",
    "public_view_mode": "ציבור מיינונג",
    "publish_at": "אַרויסגעבן בייַ",
    "published": "פֿאַרעפֿנטלעכט",
    "draft": "פּלאַן",
    "saving": "שפּאָרן",
    "save_and_publish_action": "היט און אַרויסגעבן",
    "save_draft_action": "היט פּלאַן",
    "private": "פּריוואַט",
    "public": "עפנטלעך",
    "category_input": "קאַטעגאָריע",
    "category_input_message": "אויסקלייַבן אַרטיקל קאַטעגאָריע",
    "parent_input": "פאָטער קאַטעגאָריע",
    "parent_input_message": "אויסקלייַבן פאטער צופרידן",
    "schedule_input": "פּלאַן",
    "schedule_input_placeholder": "אויב איר ווילן די געשיכטע צו זיין ארויס אין אַ ספּעציפיש צייט.",
    "schedule_view_action": "View אַרויסגעבן פּלאַן",
    "author_title": "געשריבען דורך",
    "read_time": "לערנען צייט",
    "read_time_unit": "מינוטן",
    "claps_action": "קלאַפּט",
    "claps": "קלאַפּט",
    "likes": "ווי",
    "about_author": "וועגן דעם מחבר",
    "updated_at": "דערהייַנטיקט",
    "wrote_at": "געשריבן אין",
    "now": "איצט",
    "follow_action": "גיי",
    "followed": "נאכגעפאלגט",
    "report_and_delete_action": "באריכט און ויסמעקן דעם אַרטיקל",
    "report_action": "באריכט זידלען",
    "you_reported_this_article": "דער אַרטיקל האט שוין אַ זידלען באַריכט.",
    "add_to_publication_action": "לייג צו אויסגאבע",
    "author_socials": "מחבר אויף געזעלשאַפטלעך מידיאַ",
    "share": "ייַנטיילן",
    "report_dialog": {
      "report_and_delete_title": "באריכט זידלען און אַראָפּנעמען אינהאַלט",
      "report_title": "באריכט דעם אינהאַלט ווי זידלען",
      "message": "וואָס איז די סיבה פֿאַר פאָרלייגן דעם אינהאַלט? קלייַבן איינער פון די פאלגענדע אָפּציעס.",
      "accept_and_delete_action": "באַשטעטיקן און ויסמעקן אינהאַלט"
    },
    "schedule_dialog": {
      "title": "אינהאַלט מעלדונג פּלאַן",
      "publish_at": "אַרויסגעבן בייַ",
      "last_edit": "לעצטע רעדאַגירן",
      "view_action": "זען אַרטיקל"
    },
    "notifications": {
      "update_success_title": "פאָרלייגן אינפֿאָרמאַציע",
      "update_success": "אַרטיקל דערהייַנטיקט הצלחה.",
      "update_error": "די אינפֿאָרמאַציע אריין איז נישט גילטיק.",
      "delete_error": "איר קענט נישט אויסמעקן דעם אַרטיקל!",
      "report_and_delete_success_title": "באריכט און ויסמעקן",
      "report_and_delete_success_message": "אַרטיקל איז אויסגעמעקט געווארן הצלחה.",
      "report_success_title": "באריכט אַרטיקל",
      "report_success_message": "דיין באַריכט אויף דעם אַרטיקל איז פּאָסטעד."
    },
    "alert": {
      "delete_article": {
        "title": "ויסמעקן אַרטיקל",
        "message": "זענט איר זיכער אַז איר ווילט פּערמאַנאַנטלי ויסמעקן דעם אַרטיקל?",
        "action": "ויסמעקן"
      }
    },
    "edit_window": {
      "title": "אויסקלייַבן בילד טעקסט און קיצער",
      "digest": "קיצער"
    },
    "editor": {
      "title_placeholder": "טיטל..",
      "body_placeholder": "שרייב גרויס אינהאַלט ..",
      "accept_file_types_error": "דער טעקע פֿאָרמאַט איז אַנאַקסעפּטאַבאַל:",
      "max_file_size_error": "די טעקע איז צו גרויס:",
      "notifications": {
        "image_uploaded_success": "בילד געראטעוועט הצלחה",
        "image_uploaded_failed": "טעות לאָודינג בילד."
      },
      "embed_placeholder": "אַרייַן די iframe קאָד, פאַסעבאָאָק, יאָוטובע אָדער קיין אנדערע URL און דריקן אַרייַן.",
      "embed_caption_placeholder": "אַרייַן אַ טיטל (אַפּשאַנאַל)",
      "images_caption_placeholder": "אַרייַן אַ טיטל פֿאַר דעם בילד .."
    }
  },
  "article_report": {
    "inappropriate": "דער אינהאַלט פון דעם אַרטיקל איז ינאַפּראָופּרייט.",
    "fake": "דאָס איז פאַלש און פאַרפירעריש.",
    "spam": "דעם נומער איז ספּאַם און קאַפּיד.",
    "scam": "דאָס קען זיין דערוואַרט צו פאַרשאַפן מאַלוואַרע, ווירוסעס אָדער סיסטעם קראַך.",
    "hacked": "דער פּלאַץ סימז צו זיין כאַקט.",
    "offensive": "די שפּראַך אינהאַלט און וואָקאַבולאַרי איז אַנעטיקאַל און דיסריספּעקטפאַל.",
    "violent": "איך טראַכטן דעם אינהאַלט כּולל פּאָרנאָגראַפי און איז אין הילעל פון די געזעצן.",
    "harassment": "איך מיין אז דאס איז ראסיסט.",
    "hate": "איך טראַכטן דאָס איז וועגן פּראַמאָוטינג גוואַלד.",
    "infringe": "דאס פארלעצט מיינע רעכטן."
  },
  "comments": {
    "new_action": "דריקט צו לאָזן אַ באַמערקונג ..",
    "title": "באַמערקונגען",
    "body_placeholder": "דיין באַמערקונג אָדער אָנזאָג",
    "send_action": "שיקן באַמערקונג",
    "body_is_empty_error": "באַמערקונג איז ליידיק!",
    "comments": "באַמערקונגען",
    "no_comments": "שרייב ערשטע תגובה...",
    "load_more_action": "באַקומען מער באַמערקונגען ..",
    "cant_send_comment": "איר קענען נישט לייגן נייַע פּאָסטן.",
    "cant_remove_this_comment": "איר קענען נישט ויסמעקן דעם באַמערקונג!",
    "product_buyer": "קוינע",
    "delete_alert": {
      "title": "ויסמעקן באַמערקונג",
      "message": "צי איר ווילן צו ויסמעקן דעם באַמערקונג?",
      "action": "ויסמעקן"
    },
    "notifications": {
      "delete_success": "דיין באַמערקונג אויסגעמעקט הצלחה."
    },
    "first_send": "ערשטער פּאָסטן",
    "comment_at": "אויף",
    "edit_comment": "רעדאַגירן באַמערקונג",
    "my_comments": "מייַן באַמערקונגען"
  },
  "customer_club": {
    "bronze": "בראָנדז",
    "silver": "זילבער",
    "gold": "גאָלדען",
    "platinum": "פּלאַטינום",
    "diamond": "דימענט"
  },
  "application_categories": {
    "tracking": "קאָנטראָלירונג באַניצער נאַטור",
    "payment": "צאָלונג",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "טראַנספּאָרטאַטיאָן",
    "automation": "אָטאַמיישאַן",
    "inventory": "וואַרעהאָוסינג",
    "accounting": "אַקאַונטינג",
    "marketing": "מאַרקעטינג",
    "advertising": "גאַנצע",
    "staff": "שטעקן",
    "incentive": "ינסענטיווז",
    "shop": "קראָם"
  },
  "social_network": {
    "instagram": "ינסטאַגראַם",
    "telegram": "טעלעגראַם",
    "googleplay": "GooglePlay",
    "appstore": "אַפּפּסטאָרע",
    "twitter": "טוויטער",
    "linkedin": "לינקעדין",
    "medium": "מיטל",
    "selldone": "סעלדאָנע",
    "facebook": "Facebook",
    "pinterest": "פּינטערעסט",
    "whatsapp": "ווהאַצאַפּפּ",
    "skype": "סקיפּע",
    "facebook_messenger": "Facebook מעסינדזשער"
  },
  "form_builder": {
    "add_item_action": "לייג נייַ נומער",
    "title_input": "טיטל",
    "name_input": "וואַריאַבלע נאָמען",
    "value_input": "וואַלועס",
    "value_input_message": "באַניצער אָפּציעס רשימה",
    "default": "פעליקייַט ווערט",
    "types": {
      "simple": "פּשוט",
      "selective": "סעלעקטיוו",
      "switch": "באַשטימען",
      "file": "טעקע",
      "number": "נומער"
    },
    "placeholder_input": "אָרטהאָלדער",
    "file_type_input": "פּאַסיק טעקע טייפּס",
    "file_type_message": "jpeg, png, zip, ..."
  },
  "virtual_order_info_summery": {
    "title": "פּראָדוקט נאָמען",
    "reserved_at": "פאַרשרייבונג טאָג",
    "total_price": "גאנצע סומע",
    "discount": "אַראָפּרעכענען",
    "final_price": "לעצט סומע",
    "payment_status": "צאָלונג סטאַטוס",
    "payment_status_waiting": "ווארטן פֿאַר צאָלונג",
    "payment_status_paid": "באַצאָלט",
    "buyer": "קוינע"
  },
  "virtual_item_info": {
    "title": "ווירטואַל יטעם",
    "outputs": {
      "title": "רעזולטאַט אינפֿאָרמאַציע",
      "sub_title": "קאַנפאַדענטשאַל אינפֿאָרמאַציע פון דעם נומער",
      "message": "די אינפֿאָרמאַציע וועט זיין געוויזן צו דער באַניצער נאָך פּערטשאַסינג דעם פּראָדוקט."
    },
    "inputs": {
      "title": "אינפֿאָרמאַציע פארלאנגט",
      "sub_title": "קוינע אינפֿאָרמאַציע פארלאנגט",
      "message": "דער קוינע מוזן אַרייַן די געבעטן אינפֿאָרמאַציע אין די פאָרעם"
    },
    "notifications": {
      "inputs_set_success": "אינפֿאָרמאַציע פאָרעם רעגיסטרירט הצלחה.",
      "confirm_by_admin_success": "סדר קאַמפּלישאַן באשטעטיקט.",
      "confirm_by_buyer_success": "סדר קאַמפּלישאַן באשטעטיקט."
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "דער סדר קענען ניט זיין אנגענומען דורך די COD צאָלונג.",
    "payment_returned": "די צאָלונג דורך דער קונה איז אומגעקערט.",
    "payment_fraud": "צאָלונג איז יידענאַפייד ווי שווינדל.",
    "location_out_of_service": "קונה אָרט איז אויס פון דינסט.",
    "user_not_responding": "קונה האט נישט ענטפֿערן קאַללס.",
    "shop_owner_fault": "א טעות פארגעקומען דורך קראָם שטעקן אין פילונג אינפֿאָרמאַציע.",
    "lack_of_inventory": "אויס פון לאַגער.",
    "legal_restriction": "ניט געקענט צו שטעלן אַ סדר רעכט צו לעגאַל ריסטריקשאַנז.",
    "pricing_fault": "פּרייסינג טעות דורך טרעגער.",
    "system_fault": "סיסטעם זשוק."
  },
  "basket_order_info_summery": {
    "receiver": "באקומער",
    "phone": "טעל",
    "reserved_date": "קויפן דאַטע",
    "total_price": "גאנצע סומע",
    "discount": "אַראָפּרעכענען",
    "final_price": "לעצט סומע",
    "address": "דעליווערי אדרעס",
    "payment_status": "צאָלונג סטאַטוס"
  },
  "basket_status": {
    "open": "עפענען",
    "reserved": "רעזערווירט",
    "paid": "באַצאָלט",
    "canceled": "קאַנסאַלד",
    "cod": "באַצאָלן אויף עקספּרעס",
    "receipt_added": "קאַבאָלע צוגעגעבן",
    "payment_processing": "צאָלונג פּראַסעסינג"
  },
  "basket_delivery_state": {
    "rejected": "אפגעווארפן",
    "reject_reason_not_found": "די סיבה איז אומבאַקאַנט.",
    "step_1": "איבערבליק",
    "step_2": "באַשטעטיקונג",
    "step_3": "צוגרייטונג",
    "step_4": "אויף עקספּרעס",
    "step_5": "איבערגעגעבן"
  },
  "basket_return_request_view": {
    "title": "צוריקקומען בעטן",
    "delivery_date": "דעליווערי דאטע",
    "return_date": "בעטן דאַטע",
    "items_count": "אומגעקערט זאכן ציילן",
    "items_count_unit": "נומער(ס)",
    "reason": "סיבה",
    "description": "באַשרייַבונג",
    "status": "סטאַטוס",
    "download_image": "אראפקאפיע בילד",
    "download_film": "אָפּלאָדירן ווידעא",
    "download_voice": "אָפּלאָדירן קול",
    "accept_by_admin_action": "אָננעמען בעטן",
    "reject_by_admin_action": "אָפּוואַרפן בעטן",
    "message_for_admin": "לויט די העסקעם וואָס איר האָט אנגענומען דורך ניצן די סעללדאָנע, איר מוזן קאָנטאַקט די קוינע און האַלטן אים ינפאָרמד וועגן דעם פּראָצעס פון צוריקקומען זיין סדר. דעם מוזן זיין געטאן אויב די בקשה איז אנגענומען אָדער פארווארפן און די קוינע ס פול צושטימען איז באקומען.",
    "notifications": {
      "update_status_success": "בעטן סטאַטוס דערהייַנטיקט."
    }
  },
  "basket_list": {
    "return_count": "צוריקקומען: {count} נומער",
    "table": {
      "row": "רודערן",
      "image": "בילד",
      "product_name": "פּראָדוקט",
      "variant": "וואַריאַנט",
      "warranty": "וואָראַנטיז",
      "count": "ציילן",
      "price": "פּרייַז"
    }
  },
  "return_request_list": {
    "count": "רעפערענץ נומער",
    "return_warranty": "געלט צוריק גאַראַנטירן",
    "return_warranty_unit": "טאָג(ן)",
    "table": {
      "code": "סדר קאָד",
      "product": "פּראָדוקט",
      "delivery_at": "באקומען טאָג",
      "state": "סטאַטוס",
      "reason": "סיבה",
      "return_warranty_period": "וואָראַנטי צייַט"
    }
  },
  "data_toolbar": {
    "search": "זוכן",
    "sort_by": "סאָרט דורך",
    "count_item": "ווייַזן {item} זאכן"
  },
  "sort": {
    "created_at": "שאַפֿן דאַטע",
    "updated_at": "רעדאַגירן דאַטע",
    "title": "טיטל",
    "description": "באַשרייַבונג",
    "like": "פּאָפּולאַריטעט",
    "power": "קלאַפּט",
    "product_type": "פּראָדוקט טיפּ",
    "discount": "אַראָפּרעכענען",
    "rate": "שאַץ",
    "rate_count": "נומער פון רייטינגז",
    "category": "קאַטעגאָריע",
    "product": "פּראָדוקט",
    "body": "אינהאַלט",
    "card_type": "קאָרט טיפּ",
    "card_number": "קארד נומער",
    "balance": "וואָג",
    "paid": "סכום אויסגעגעבן",
    "currency": "קראַנטקייַט",
    "expire_at": "עקספּיירי טאָג",
    "discount_code": "אַראָפּרעכענען קאָד",
    "discount_percent": "אַראָפּרעכענען",
    "discount_limit": "אַראָפּרעכענען שיעור",
    "max_count": "מאַקסימום ציילן",
    "used_count": "געניצט",
    "start_date": "אנהייב דאטום",
    "end_date": "סוף טאָג",
    "total_discount_amount": "גאַנץ דיסקאַונץ",
    "initial_charge": "ערשט אָפּצאָל",
    "total_count": "גאַנץ ציילן",
    "amount_paid": "סכום באַצאָלט",
    "name": "נאָמען",
    "published": "פֿאַרעפֿנטלעכט",
    "visits": "וויזיץ",
    "color": "פאַרב",
    "landing_page": "לאַנדינג בלאַט",
    "enable": "געבן",
    "fix_commission": "פאַרפעסטיקט קאָמיסיע",
    "percent_commission": "פּראָצענט קאָמיסיע",
    "payment_at": "צאָלונג דאַטע",
    "issued_at": "אויסגאבע דאטום",
    "payment": "צאָלונג",
    "website": "וועבזייַטל",
    "email": "בליצפּאָסט",
    "user": "באַניצער",
    "code": "קאָד",
    "schedule_at": "פּלאַן דאַטע",
    "sender": "סענדער",
    "in_que": "אין ריי",
    "sent": "געשיקט",
    "shop": "קראָם",
    "quantity": "קוואַנטיטי",
    "amount": "סומע",
    "jobs": "דזשאָבס ציילן",
    "success": "הצלחה ציילן",
    "fail": "דורכפאַל ציילן",
    "distance": "דיסטאַנסע",
    "duration": "געדויער",
    "reset_at": "באַשטעטיק דאַטע",
    "delivery_person": "מענטש",
    "delivery_service": "סערוויס",
    "date": "טאָג",
    "order": "סדר",
    "order_id": "סדר שייַן",
    "status": "סטאַטוס",
    "price": "פּרייַז",
    "count": "ציילן",
    "final_price": "לעצט פּרייַז",
    "charge": "אָפּצאָל",
    "mention": "דערמאָנען",
    "officer": "אָפיציר",
    "registered": "רעגיסטרירט",
    "purchased": "געקויפט",
    "sex": "דזשענדער"
  },
  "search_box": {
    "result": "זוכן רעזולטאַטן",
    "tips": "זוכן פּראָדוקטן און קאַטעגאָריעס",
    "label": "זוך ...",
    "category": "קאַטעגאָריע"
  },
  "lead_status": {
    "physical_fast_delivery": "רעגע עקספּרעס",
    "physical_under_24h_delivery": "דעליווער אין די ווייַטער {lead} שעה",
    "physical_over_24h_delivery": "צוגרייטן און פאָרלייגן פון ווייַטער {days} טעג",
    "virtual_fast_prepare": "רעגע עקספּרעס",
    "virtual_under_24h": "וועט זיין דורכגעקאָכט אין די ווייַטער {lead} שעה",
    "virtual_over_24h": "וועט זיין געטאן פון די ווייַטער {days} טעג"
  },
  "return_request_state": {
    "pending": "פּענדינג",
    "accepted": "באשטעטיקט",
    "rejected": "אפגעווארפן"
  },
  "return_order_reason": {
    "physical": {
      "U1": "פּראָדוקט ניט פּאַסיק",
      "U2": "קיין פּראָדוקט אין שיפּינג פּעקל",
      "U3": "פּעקל אָדער פּראָדוקט ברייקידזש",
      "U4": "טאַמפּערינג פון פּעקל אָדער סיריאַל נומער",
      "U5": "עטלעכע זאכן פון די פּעקל זענען פעלנדיק",
      "U6": "פּראָדוקט איז נישט אָריגינעל",
      "U7": "פּראָדוקט טוט נישט באַפרידיקן די ספּעסאַפאַקיישאַנז"
    }
  },
  "image_uploader": {
    "label": "שלעפּן & דראָפּ אָדער <u>אויסקלייַבן טעקע</u>",
    "max_size": "מאַקסימום ערלויבט גרייס: {size}"
  },
  "timespan": {
    "Morning": "8:00 - 12:00",
    "Evening": "12 מיטאָגצייַט צו 6 PM",
    "Night": "6 PM-12 PM",
    "Instant": "רעגע פּאָסטן"
  },
  "week_day": {
    "Saturday": "שבת",
    "Sunday": "זונטיק",
    "Monday": "מאנטאג",
    "Tuesday": "דינסטיק",
    "Wednesday": "מיטוואך",
    "Thursday": "דאנערשטאג",
    "Friday": "פרייטאג"
  },
  "payment_form": {
    "title": "אויסקלייַבן צאָלונג מעטאָד",
    "gift_cards_input": "גיפט קאַרדס",
    "gift_cards_input_empty": "קיין טאַלאַנט קאַרדס געפונען..",
    "more": "אנדערע",
    "pay_amount_by_gift_cards": "אָפּצאָל קאַרד צאָלונג",
    "select_payment_method": "קלייַבן דיין צאָלונג אופֿן פון די פאלגענדע אָפּציעס.",
    "payment_amount_remained": "רוען צאָלונג סומע",
    "payment_amount": "סכום באַצאָלט",
    "all_paid_by_gift_cards": "מאַזל - טאָוו, איר טאָן ניט דאַרפֿן צו באַצאָלן פֿאַר דעם סדר. דריקן די פּייַ מיט גיפט קאַרד שליסל.",
    "pay_by_gift_cards_action": "באַצאָלן די סדר מיט אַ אָפּצאָל קאָרט",
    "order_free_payment": "מאַזל - טאָוו, דיין סדר איז פריי!",
    "order_free_payment_action": "סדר פריי איצט",
    "qr": {
      "address": "צאָלונג אַדרעס",
      "amount": "סומע"
    }
  },
  "discount_input": {
    "limit": "{percent}% אַראָפּרעכענען אַרויף צו {limit} {currency}",
    "action": "לייג אַראָפּרעכענען קאָד",
    "code_input": "אַראָפּרעכענען קאָד",
    "notifications": {
      "add_success": "מאַזל - טאָוו, גילטיק אַראָפּרעכענען קאָד."
    }
  },
  "gift_card": {
    "inactive": "קאָרט איז פאַרקריפּלט",
    "expire": "עקספּיירי",
    "transfer": "אַריבערפירן",
    "send_to_friend": "שיקן צו אַ פרייַנד"
  },
  "count_down": {
    "days": "טאָג",
    "hours": "שעה",
    "minutes": "מינוטן",
    "seconds": "סעקונדעס"
  },
  "gift_status": {
    "Unpaid": "ווארט צו באקומען",
    "Paid": "באַצאָלט",
    "Rejected": "אפגעווארפן",
    "Canceled": "קאַנסאַלד"
  },
  "gift_program_status": {
    "Airdrop": "צאָלונג סיסטעם",
    "Advertising": "גאַנצע",
    "PersonalGift": "פערזענלעכע טאַלאַנט",
    "ShopGift": "טאַלאַנט שאָפּ"
  },
  "currency_selector": {
    "label": "קראַנטקייַט"
  },
  "need_login": {
    "title": "צייכן אריין",
    "login_sms": "SMS לאָגין",
    "login_google": "קלאָץ אין מיט Google",
    "login_facebook": "לאָגין מיט פאַסעבאָאָק",
    "login_account": "לאָגין דורך סעללדאָנע",
    "register": "נייַ באַניצער? רעגיסטרירן איצט.",
    "mobile_input": "אַרייַן דיין רירעוודיק",
    "verification_code": "וועראַפאַקיישאַן קאָד",
    "msg_title": "העלא,",
    "msg_body": "ביטע קלאָץ אין. עס נעמט נאָר אַ ביסל סעקונדעס.",
    "login_apple": "לאָגין מיט עפּל",
    "login_email": "לאָגין דורך בליצפּאָסט",
    "email_login_step_1": "ביטע צושטעלן אַ גילטיק בליצפּאָסט אַדרעס, און מיר וועלן שיקן די לאָגין קאָד צו עס. קיין רעגיסטראַציע איז נייטיק.",
    "email_login_step_2": "זענט איר זיכער אַז איר האָט אריין דיין בליצפּאָסט אַדרעס ריכטיק? מיר וועלן שיקן די לאָגין קאָד צו די צוגעשטעלט E- בריוו, אַזוי ביטע ענשור די אַקיעראַסי.",
    "email_login_step_3": "מיר האָבן געשיקט אַ קאָד צו דיין בליצפּאָסט. ביטע טאָן אַז די קאָד וועט ויסגיין אין 10 מינוט."
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "5 יאָר גאָלד קראָם"
    },
    "GOLDEN_2YEAR": {
      "name": "4 יאָר גאָלד קראָם"
    },
    "GOLDEN_3YEAR": {
      "name": "3 יאָר גאָלד קראָם"
    },
    "GOLDEN_4YEAR": {
      "name": "2 יאָר גאָלד קראָם"
    },
    "GOLDEN_5YEAR": {
      "name": "1 יאָר גאָלד קראָם"
    },
    "TOKEN_OWNER_1M": {
      "name": "גאָלדען ינוועסטער"
    },
    "TOKEN_OWNER_10M": {
      "name": "דימענט ינוועסטער"
    },
    "TOKEN_OWNER_100M": {
      "name": "רובין ינוועסטער"
    },
    "COMMUNITY_LOYAL": {
      "name": "מיטגליד פון דער העכער קאַמיוניטי פון קאָמוניקאַציע נעטוואָרקס"
    },
    "GOLD_SUPPLIER": {
      "name": "גאָלד סאַפּלייער"
    },
    "GOLD_SELLER": {
      "name": "גאָלד הענדלער"
    },
    "CONTENT_SUPERMAN": {
      "name": "Top אינהאַלט פּראָדוצירער"
    },
    "NINJA": {
      "name": "נינדזשאַ"
    },
    "STAR": {
      "name": "שטערן"
    },
    "GUARDIAN": {
      "name": "גרויס קונה סערוויס"
    },
    "KING": {
      "name": "מלך פון די מאַרק"
    }
  },
  "cookie": {
    "title": "דער וועבזייטל ניצט קיכלעך",
    "message": "דער וועבזייטל ניצט קיכלעך צו פֿאַרבעסערן באַניצער דערפאַרונג. דורך ניצן אונדזער וועבזייטל איר צושטימען צו אַלע קיכלעך אין לויט מיט אונדזער קיכל פּאָליטיק.",
    "preferences_action": "פירן פּרעפֿערענצן",
    "agree_action": "איך בין מסכים"
  },
  "basket_item_message": {
    "title": "פארלאנגט אינפֿאָרמאַציע פֿאַר דעם נומער",
    "save_actions": "היט אָנזאָג",
    "notifications": {
      "success": "דיין אַרייַנשרייַב דאַטן איז געראטעוועט."
    },
    "product_inputs_preview_message": "די קוסטאָמיזאַטיאָן אָפּציעס זענען בארעכטיגט פֿאַר דיין אָרדערד פּראָדוקט. אַמאָל די נומער איז מוסיף צו דיין וואָגן, איר קענען מאַכן אַדזשאַסטמאַנץ דאָ."
  },
  "faq": {
    "faq": "אָפט געשטעלטע פֿראגן",
    "title": "פֿראגן און ענטפֿערס",
    "sub_title": "וואָס איר האָט אונדז געבעטן צו טאָן.",
    "message": "קוק פֿאַר די ענטפער צו דיין קשיא צווישן די ענטפֿערס אונטן. פרעגן אונדז אויב פֿראגן בלייבן אַנאַנסערד.",
    "add_question_action": "פרעגן אַ נייַע קשיא",
    "read_more": "לייענען מער ..",
    "load_more": "מער שאלות..",
    "main_page": "FAQ הויפּט בלאַט",
    "add_new": "פאָרלייגן נייַע קשיא",
    "login_alert": "קלאָץ אין צו פרעגן אַ קשיא.",
    "question_input": "פראגע",
    "question_input_placeholder": "פרעגן דיין קשיא.",
    "notifications": {
      "success_add": "דיין קשיא איז דערלאנגט מיט הצלחה."
    }
  },
  "rating_labels": [
    "זייער שלעכט",
    "שלעכט",
    "נאָרמאַל",
    "גוט",
    "ויסגעצייכנט"
  ],
  "map_view": {
    "address_detail": "אַדרעס פּרטים",
    "change": "טוישן",
    "select": "אויסקלייַבן",
    "not_found_address": "קיין ווערט געפונען",
    "enter_address_hint": "אַרייַן דעסטיניישאַן אַדרעס",
    "enter_your_address": "אַרייַן דיין אַדרעס.",
    "postal_code": "פּאָסטקאָדע",
    "phone_input": "טעלעפאָן {type}",
    "building_number": "בנין נומער",
    "building_unit": "אַפּאַראַט",
    "full_name_input": "גאַנץ נאָמען {type}",
    "save_detail_action": "היט פרטים",
    "more_detail_input": "מער באַשרייַבונג",
    "add_address_to_list": "לייג אַדרעס צו רשימה",
    "address_title_input": "אַדרעס פירמע (פאָדערן)",
    "notifications": {
      "save_in_list": "די אַדרעס איז געראטעוועט צו דיין רשימה מיט אַלע זייַן דעטאַילס.",
      "edit_success": "נייַ אַדרעס וואַלועס געראטעוועט אין {title}."
    },
    "delete_address_dialog": {
      "title": "ויסמעקן אַדרעס",
      "message": "זענט איר זיכער אַז איר ווילט אויסמעקן דעם אַדרעס?",
      "action": "אַראָפּנעמען אַדרעס"
    }
  },
  "comment_manager": {
    "can_not_edit": "קענען נישט רעדאַגירן דעם באַמערקונג!",
    "comment_input_empty": "אָנזאָג טעקסט איז ליידיק!",
    "article_not_saved": "היט דעם אַרטיקל!"
  },
  "wheel_fortune": {
    "title": "שפּיל & געווינען",
    "message": "דער פּרייַז פון יעדער שפּיל איז 10 טשיפּס. איר איצט האָבן {chips} שפּאָן. באַקומען מער שפּאָן דורך קויפן פון די קראָם.",
    "win_message": "מאַזל - טאָוו, איר געווינען!",
    "lost_message": "אנטשולדיגט, איר פאַרפאַלן די שפּיל.",
    "try_again": "איר קענען פּרובירן ווידער"
  },
  "json": {
    "add": "לייג סטרוקטור דאַטן",
    "add_message": "שאַפֿן נייַ סטרוקטור דאַטן",
    "structures": "סטראַקטשערז",
    "book": {
      "title": "ספר",
      "desc": "ספר אַקשאַנז וואָס געבן ניצערס צו קויפן דעם בוך וואָס זיי געפֿינען גלייַך פֿון זוכן רעזולטאַטן."
    },
    "occupation": {
      "title": "עסטימאַטעד געצאָלט",
      "desc": "אינפֿאָרמאַציע וועגן געצאָלט אָפּשאַצונג, אַזאַ ווי געצאָלט ריינדזשאַז און געגנט-באזירט געצאָלט אַוורידזשיז פֿאַר אַרבעט טייפּס, געוויזן אין די אַרבעט זוכן דערפאַרונג אויף Google."
    },
    "course": {
      "title": "קורס",
      "desc": "בילדונגקרייז קאָרסאַז וואָס דערשייַנען אין אַ שפּייַזער-ספּעציפיש רשימה. קאָרסאַז קענען אַרייַננעמען דעם קורס טיטל, שפּייַזער און אַ קורץ באַשרייַבונג."
    },
    "howto": {
      "title": "ווי אזוי צו",
      "desc": "א ווי-צו גייט יוזערז דורך אַ גאַנג פון סטעפּס צו הצלחה פאַרענדיקן אַ אַרבעט, מיט ווידעא, בילדער און טעקסט."
    },
    "recipe": {
      "title": "רעצעפּט",
      "desc": "רעסיפּעס וואָס ווייַזן ווי אַ יחיד רייַך רעזולטאַט אָדער טייל פון אַ באַלעבאָס קעראַסעל."
    }
  },
  "support": {
    "Financial": "פינאַנציעל",
    "Technical": "טעכניש",
    "Advisor": "אַדווייזער"
  },
  "condition": {
    "new": "נייַ",
    "refurbished": "ריפערבישט",
    "used": "געניצט",
    "used_fair": "געוויינט שיין",
    "used_good": "געוויינט גוט",
    "used_like_new": "געוויינט ווי נייַ"
  },
  "variant_filter": {
    "title": "פּראָדוקט וואַריאַנט פילטער",
    "only_available": "אין סטאק"
  },
  "service": {
    "task": {
      "title": "טאַסקס",
      "message": "רשימה פון טאַסקס געטאן אין דעם דינסט."
    },
    "appointment": {
      "title": "אַפּוינטמאַנט",
      "message": "קלייַבן די צייט פון די וואָך פון די פאלגענדע צייט באזירט אויף די טאָג און שעה וואָס איז רעכט פֿאַר איר."
    },
    "booking": {
      "title": "בוקינג",
      "message": "ספּעציפיצירן די צייט פון די טעג איר ווילן צו מאַכן אַ רעזערוואַציע אין די קאַלענדאַר אונטן."
    },
    "subscription": {
      "title": "אַבאָנעמענט"
    },
    "charge": {
      "title": "אָפּצאָל"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "פאַרפעסטיקט פּרייסינג",
      "message": "אין דעם טיפּ פון פּרייסינג, די פּרייַז פון די פּראָדוקט איז אַ פאַרפעסטיקט סומע און עס איז ניט דאַרפֿן פֿאַר די קוינע צו בעטן אַ פּרייַז כעזשבן."
    },
    "ESTIMATION": {
      "title": "אָפּשאַצונג פּרייסינג",
      "message": "די פּרייַז פון פּראָדוקטן און באַדינונגס וועט זיין קאַלקיאַלייטיד צו עטלעכע מאָס דורך די טרעגער ווען פּלייסינג אַ סדר, צאָלונג ינווויסיז קענען זיין טשיינדזשד אָדער צוגעגעבן בעשאַס די דינסט."
    },
    "AGREEMENT": {
      "title": "העסקעם פּרייסינג",
      "message": "די לעצט פּרייַז פון די פּראָדוקטן אָדער באַדינונגס וועט נישט זיין פארענדערט דורך די טרעגער נאָך די סדר איז געשטעלט."
    },
    "BID": {
      "title": "באַפעלן / ליציטאַציע",
      "message": "דער פּראָדוקט וועט זיין סאָלד צו די העכסטן באַפעלן פּרייַז דורך פּאָטענציעל בויערס."
    }
  },
  "map": {
    "title": "דעסטיניישאַן צו באַקומען פּראָדוקטן",
    "confirm": "שטעלן אָרט",
    "address": "דעסטיניישאַן",
    "receptor": "באקומער"
  },
  "ShopBots": {
    "telegram": "טעלעגראַם"
  },
  "article_tags": {
    "title": "אינהאַלט טאַגס",
    "tags_input": "טאַגס",
    "tags_input_message": "טאַגס רשימה פון דעם אַרטיקל",
    "notification": {
      "add_success": "טאַגס צוגעגעבן"
    }
  },
  "difficulties": {
    "very_complicated": "זייער קאָמפּליצירט",
    "hard": "שווער",
    "intermediate": "ינטערמידייט",
    "easy": "לייַכט"
  },
  "billing_period": {
    "Daily": "טעגלעך",
    "Weekly": "וואכנשריפט",
    "Monthly": "כוידעשלעך",
    "Every3Months": "יעדער 3 חדשים",
    "Every6Months": "יעדער 6 חדשים",
    "Yearly": "יאָריק"
  },
  "buyer_rating_statement": {
    "between1_2": "אוי נישט גוט!",
    "between2_3": "ס 'איז גוט!",
    "between3_4": "מענטשן ווי עס!",
    "between4_5": "מענטשן ליבע עס!"
  }
};