export default {
  "currency_default": "USD",
  "language_default": "en",
  "selldone": "Ti pari",
  "store": "itaja",
  "not_exist": "Ko si",
  "error": "Asise",
  "active": "Ti nṣiṣe lọwọ",
  "inactive": "Aiṣiṣẹ",
  "required_value": "Awọn iye ti a beere",
  "original_warranty": "Atilẹba ọja Ẹri",
  "return_warranty_days": "Awọn ọjọ ẹri ipadabọ {days}",
  "no_return_warranty": "Ko si ipadabọ",
  "reed_agree_terms": "Mo ti ka awọn ofin lilo ati eto imulo ipamọ ati gba pẹlu wọn.",
  "commons": {
    "Currency": "Owo owo",
    "COD": "COD",
    "State": "Ìpínlẹ̀",
    "Price": "owo",
    "order_price": "Iye ibere",
    "VAT": "VAT",
    "Discount": "Eni owo",
    "In_Stock": "O wa",
    "Variants": "Awọn iyatọ",
    "No_variants": "Ko si iyatọ",
    "all": "GBOGBO",
    "today": "Loni",
    "yesterday": "Lana",
    "license": "Iwe-aṣẹ",
    "home": "Ile",
    "support": "Atilẹyin",
    "messages": "Awọn ifiranṣẹ",
    "no_message": "Ko si ifiranṣẹ",
    "empty": "Sofo",
    "phone": "Foonu",
    "address": "adirẹsi",
    "name": "Oruko",
    "password": "Ọrọigbaniwọle",
    "email": "Imeeli",
    "mobile": "Alagbeka",
    "login": "wo ile",
    "register": "Forukọsilẹ",
    "select_account": "Yan iroyin",
    "online": "Online",
    "offline": "Aisinipo",
    "finish": "Pari",
    "finished": "Ti pari",
    "preview": "Awotẹlẹ",
    "free": "Ọfẹ",
    "free_completely": "Ṣiṣe alabapin ọfẹ patapata",
    "fee": "Ọya",
    "month": "Osu",
    "months": "Awọn oṣu",
    "faq": "Awon ibeere ti awon eniyan saaba ma n beere",
    "question": "Ibeere",
    "answer": "Idahun",
    "create_date": "Ṣẹda ọjọ",
    "update_date": "Ọjọ imudojuiwọn",
    "start_date": "Ọjọ ibẹrẹ",
    "end_date": "Ọjọ ipari",
    "social": "Awujo",
    "total": "Lapapọ",
    "orders": "Awọn ibere",
    "sessions": "Awọn akoko",
    "product_views": "Ọja wiwo",
    "add_to_carts": "Fi si awọn kẹkẹ",
    "checkouts": "Ṣayẹwo",
    "payments": "Isanwo",
    "organic_search": "Organic search",
    "other": "Omiiran",
    "landing_page": "Oju-iwe ibalẹ",
    "discount_code": "Eni koodu",
    "total_sell": "Lapapọ tita",
    "details": "Awọn alaye",
    "currency": "Owo owo",
    "amount": "Iye",
    "published": "Atejade",
    "draft": "Akọpamọ",
    "save_changes": "Fi awọn ayipada pamọ",
    "source": "Orisun",
    "medium": "Alabọde",
    "url": "Url",
    "revenue": "Wiwọle",
    "performance": "Iṣẹ ṣiṣe",
    "term": "Igba",
    "content": "Akoonu",
    "session": "Igba",
    "product": "Ọja",
    "add": "Fi kun",
    "checkout": "Ṣayẹwo",
    "payment": "Isanwo",
    "more_options": "Awọn aṣayan diẹ sii",
    "full_name": "Akokun Oruko",
    "tel": "Tẹli",
    "about_me": "Nipa mi",
    "request_checking": "Beere yiyewo",
    "passport": "Iwe irinna",
    "birthday": "Ojo ibi",
    "country": "Orilẹ-ede",
    "city": "Ilu",
    "gender": "abo",
    "offer": "Ìfilọ",
    "website": "Aaye ayelujara",
    "apply_for_all_products": "∞ Waye fun gbogbo awọn ọja",
    "fix_commission": "Igbimọ ti o wa titi",
    "percent_commission": "Igbimo ogorun",
    "fixed_discount": "Eni ti o wa titi",
    "discount_percentage": "ẹdinwo ogorun",
    "discount_limit": "Eni aropin",
    "no_code": "Ko si koodu",
    "max_count": "Iwọn to pọju",
    "count_unit": "Awọn nkan",
    "used": "Lo",
    "daily": "Ojoojumọ",
    "monthly": "Oṣooṣu",
    "yearly": "Odoodun",
    "state": "Ipo",
    "disable": "Pa a",
    "enable": "Mu ṣiṣẹ",
    "activation_code": "koodu ibere ise",
    "quantity": "Opoiye",
    "no_club": "Ko si Ologba",
    "per_order": "Fun ibere",
    "count": "Ka",
    "seconds": "Aaya",
    "auto": "Aifọwọyi",
    "title": "Akọle",
    "message": "Ifiranṣẹ",
    "width": "Ìbú",
    "length": "Gigun",
    "height": "Giga",
    "label": "Aami",
    "click": "Tẹ",
    "bank": "Banki",
    "default": "Aiyipada",
    "role": "Ipa",
    "user": "olumulo",
    "users": "Awọn olumulo",
    "code": "koodu",
    "total_payment": "Lapapọ owo sisan",
    "balance": "Iwontunwonsi",
    "chance": "Anfani",
    "free_for_new_users": "Ọfẹ fun awọn olumulo titun",
    "prize_amount": "Iye owo",
    "win": "Ṣẹgun",
    "gift_card": "Kaadi ebun",
    "discount": "Eni owo",
    "config": "Iṣeto",
    "prize": "Ẹbun",
    "Prizes": "Awọn ẹbun",
    "result": "Abajade",
    "price": "owo",
    "lottery": "Lotiri",
    "coupon": "Kupọọnu",
    "customer_club": "Onibara Club",
    "shipping": "Gbigbe",
    "sum": "Apapọ",
    "not_paid": "Ko sanwo",
    "category": "Ẹka",
    "done": "Ti ṣe",
    "email_from": "Lati",
    "subject": "Koko-ọrọ",
    "schedule": "Iṣeto",
    "files_list": "Akojọ awọn faili",
    "file_max_size": "Iwọn faili ti o pọju",
    "value": "Iye",
    "help": "Egba Mi O",
    "shipping_tax": "Owo-ori gbigbe",
    "net_price": "Nẹtiwọki owo",
    "tax": "Owo-ori",
    "tax_included": "To wa ninu owo",
    "limit": "Idiwọn",
    "min_purchase": "O kere rira",
    "eligible_for": "Yẹ fun",
    "only_for_first_buy": "Nikan fun rira akọkọ",
    "one_time_use": "Le lo akoko kan",
    "period_of_qualify": "Iwọn lilo akoko",
    "no_constraint": "Ko si opin",
    "timespan": "Akoko akoko",
    "days": "Ọjọ (awọn ọjọ)",
    "weight": "Iwọn",
    "distance": "Ijinna",
    "last_status": "Ipo ikẹhin",
    "issued_at": "Ti jade ni",
    "order": "Bere fun",
    "order_detail": "Awọn alaye ibere",
    "percent": "ogorun",
    "applied_count": "Nọmba ti a lo",
    "campaign": "Ipolongo",
    "os": "Eto isesise",
    "browser": "Aṣàwákiri",
    "device": "Ẹrọ",
    "device_ip": "Adirẹsi IP ẹrọ",
    "location": "Ipo",
    "user_agent": "Aṣoju olumulo",
    "affiliate": "Alafaramo",
    "timeline": "Ago",
    "add_note": "Fi akọsilẹ kun",
    "record": "Gba silẹ",
    "unlimited": "Kolopin",
    "show_coupons": "Show kuponu",
    "hide_coupons": "Tọju awọn kuponu",
    "service_area": "Agbegbe iṣẹ",
    "apps": "Awọn ohun elo",
    "plugins": "Awọn afikun",
    "bots": "Boti",
    "categories": "Awọn ẹka",
    "products": "Awọn ọja",
    "business": "Iṣowo",
    "personal": "Ti ara ẹni",
    "size": "Iwọn",
    "holiday": "Isinmi",
    "sod": "Sanwo Lori Ifijiṣẹ",
    "cod": "Owo lori ifijiṣẹ",
    "free_shipping": "Gbe lo dele",
    "hours": "Awọn wakati",
    "send_date": "Ọjọ gbigbe",
    "deliver_date": "Deeti ifijiṣẹ",
    "return_date": "Ọjọ ipadabọ",
    "pending": "Ni isunmọtosi",
    "delivered": "Ti fi jiṣẹ",
    "returned": "Pada",
    "canceled": "fagilee",
    "shipping_cost": "Iye owo gbigbe",
    "action": "Iṣe",
    "cancel_date": "Fagilee ọjọ",
    "deliver_in_process": "Ti firanṣẹ aṣẹ naa..",
    "kind": "Iru",
    "detail": "Awọn alaye",
    "map": "Maapu",
    "actions": "Awọn iṣe",
    "navigation": "Lilọ kiri",
    "navigation_app": "Ohun elo",
    "payment_date": "Ọjọ sisan",
    "duration": "Iye akoko",
    "bill": "Bill",
    "delivery_persons": "Awọn onṣẹ",
    "delivery_services": "Awọn iṣẹ ifijiṣẹ",
    "live_view": "Wiwo ifiwe",
    "cart": "Kẹkẹ",
    "priority": "Ni ayo",
    "sufficient_credit": "Kirẹditi ti o to",
    "max_package_size": "Iwọn package ti o pọju",
    "delay": "Idaduro",
    "credit": "Kirẹditi",
    "livemode": "Gbe",
    "paused": "Daduro",
    "debug": "Ṣatunkọ",
    "token": "Àmi",
    "status": "Ipo",
    "courier": "Oluranse",
    "track": "Orin",
    "track_order": "Bere fun Àtòjọ",
    "cost": "Iye owo",
    "receipt": "gbigba",
    "origin": "Orisun",
    "destination": "Ibi-afẹde",
    "sku": "SKU",
    "mpn": "MPN",
    "not_in_stock": "Ko to iṣura!",
    "sub_total": "Lapapọ",
    "customer": "Onibara",
    "delivery": "Ifijiṣẹ",
    "online_orders": "Online Bibere",
    "pos_orders": "Awọn aṣẹ POS",
    "chips": "Awọn eerun igi",
    "subscribed": "Alabapin",
    "unsubscribed": "Ko ṣe alabapin",
    "last_login": "kẹhin wiwọle",
    "join_at": "Ọjọ ti o darapọ mọ",
    "club": "Ologba",
    "buyer": "Olura",
    "seller": "Olutaja",
    "or": "Tabi",
    "type": "Iru",
    "condition": "Ipo",
    "brand": "Brand",
    "attempt": "Igbiyanju",
    "error": "Asise",
    "success": "Aseyori",
    "fail": "Ikuna",
    "inventory": "Oja",
    "link": "Ọna asopọ",
    "visits": "Awọn abẹwo",
    "transactions": "Awọn iṣowo",
    "vat": "VAT",
    "pos_vat": "POS VAT",
    "sort_by": "Sa pelu..",
    "from": "Lati",
    "from_lead_time": "Laarin awọn wakati {hours} to nbọ",
    "no_credit_card_info": "Ko si Alaye Kaadi!",
    "active": "Ti nṣiṣe lọwọ",
    "not_active": "Ko mu ṣiṣẹ!",
    "referrals": "Awọn itọkasi",
    "dashboard": "Dasibodu",
    "more": "Die e sii",
    "inactive": "Aiṣiṣẹ",
    "developer": "Olùgbéejáde",
    "setting": "Eto",
    "membership_conditions": "Awọn ipo ẹgbẹ",
    "customers": "Awon onibara",
    "created_at": "Ọjọ ti a ṣẹda",
    "updated_at": "Imudojuiwọn to kẹhin",
    "register_at": "Ọjọ iforukọsilẹ",
    "old": "Atijo",
    "new": "Tuntun",
    "start": "Bẹrẹ",
    "end": "Ipari",
    "pos": "POS",
    "out_of_stock": "Ko si ọja",
    "fake": "Iro",
    "low_inventory_warning": "Ifarabalẹ, Ọja kekere!",
    "webhook": "Webhook",
    "notification": "Iwifunni",
    "sms": "SMS",
    "online_payment_link": "Online owo ọna asopọ",
    "waiting_load_data": "Nduro lati kojọpọ data..",
    "views": "Awọn iwo",
    "sales": "Tita",
    "total_views": "Lapapọ awọn iwo",
    "total_sales": "Lapapọ tita",
    "from_previous_n_days": "Lati kẹhin {days} ọjọ",
    "drop_shipping": "Gbigbe silẹ",
    "commission": "Igbimọ",
    "shipping_area": "Agbegbe gbigbe",
    "main_seller": "Olutaja akọkọ",
    "domain": "Ibugbe",
    "contact": "Alaye olubasọrọ",
    "wallet": "Apamọwọ",
    "reseller": "Alatunta",
    "tracking_code": "Koodu ipasẹ",
    "tracking_url": "URL titele",
    "fulfillments": "Awọn imuse",
    "reject": "Kọ",
    "reserved": "Ni ipamọ",
    "score": "O wole",
    "customer_price": "Iye owo onibara",
    "options": "Awọn aṣayan",
    "show_details": "Ṣe afihan awọn alaye",
    "no_data": "Ko si data..",
    "waiting": "Nduro...",
    "waiting_connecting_payment": "Nduro fun iṣẹ isanwo naa...",
    "creating_secure_payment": "Ṣiṣẹda ni aabo owo sisan.",
    "officer": "Oṣiṣẹ",
    "ticket": "Tiketi",
    "ticket_url": "url tiketi",
    "closed_at": "Ni pipade ni",
    "close_ticket": "Tiketi sunmọ",
    "reopen_ticket": "Tiketi tun ṣii",
    "require": "beere*",
    "search": "Wa...",
    "language": "Ede",
    "tasks": "Awọn iṣẹ-ṣiṣe",
    "permissions": "Awọn igbanilaaye",
    "finish_date": "Ọjọ ipari",
    "complete_date": "Ọjọ ipari",
    "settle_date": "Ọjọ iṣeto",
    "cost_span": "Iwọn idiyele",
    "industry": "Ile-iṣẹ",
    "rating": "Awọn iwontun-wonsi",
    "rates": "Idiwon",
    "seen_at": "Ti ri ni",
    "completed": "Ti pari",
    "you": "Iwọ",
    "shop": "Itaja",
    "store": "itaja",
    "granted": "Ti gba",
    "deny": "sẹ",
    "request": "Ibere",
    "expert": "Amoye",
    "response": "Idahun",
    "requests": "Awọn ibeere",
    "experts": "Awọn amoye",
    "responses": "Awọn idahun",
    "negotiations": "Idunadura",
    "all_chats": "Gbogbo chats",
    "chats": "Awọn ibaraẹnisọrọ",
    "tags": "Awọn afi",
    "description": "Apejuwe",
    "rates_count": "Nọmba ti-wonsi",
    "rate": "Idiwon",
    "comment": "Ọrọìwòye",
    "chat": "Wiregbe",
    "install": "Fi sori ẹrọ",
    "edited": "Ṣatunkọ",
    "undo": "Yipada",
    "redo": "Tunṣe",
    "male": "Okunrin",
    "female": "Obinrin",
    "calculator": "Ẹrọ iṣiro",
    "catalog": "Katalogi",
    "max_height": "Iwọn giga ti o pọju",
    "images_compare": "Images lafiwe",
    "canvas": "Kanfasi",
    "table_of_contents": "Atọka akoonu",
    "comments": "Comments",
    "badge_codes": "Awọn koodu Baajii",
    "need_more": "Nilo diẹ sii?",
    "invite_glow_caption": "Gba 14.9 $ fun ọrẹ kọọkan!",
    "register_free": "100% free Forukọsilẹ",
    "gift": "Ẹbun",
    "google": "Google",
    "facebook": "Facebook",
    "instagram": "Instagram",
    "instashop": "Instashop",
    "show": "Ṣe afihan",
    "hide": "Tọju",
    "waiting_review": "Nduro awotẹlẹ",
    "not_selected": "Ko yan",
    "time": "Aago",
    "final_price": "Ipari owo",
    "starting_price": "Iye owo ibẹrẹ",
    "day": "Ojo",
    "paid": "Sanwo",
    "service_bill": "isanwo risiti",
    "avocado": "Piha oyinbo",
    "delivery_price": "Iye owo gbigbe",
    "select_address": "Yan adirẹsi",
    "image": "Aworan",
    "view": "Wo",
    "sell": "Tita",
    "hyper": "Hyper",
    "cart_list": "Kẹkẹ",
    "barcode_scanner": "Barcode scanner",
    "scan_qr_code": "Ṣayẹwo koodu QR",
    "new_carts": "Awọn kẹkẹ tuntun",
    "pays": "Awọn sisanwo",
    "annually": "Ododun",
    "sells": "Tita",
    "articles": "Ìwé",
    "jobs": "Awọn iṣẹ",
    "job": "Job",
    "blog": "Bulọọgi",
    "deleted_at": "Parẹ ni",
    "capacity": "Agbara",
    "download_at": "Ọjọ igbasilẹ kẹhin",
    "downloads": "Awọn igbasilẹ",
    "usage": "Lilo",
    "select_upload_file": "Yan tabi ju faili silẹ",
    "download_link": "Download ọna asopọ",
    "uploading": "Ìrùsókè.",
    "files": "Awọn faili",
    "star": "Irawọ",
    "speed": "Iyara",
    "feedback": "Esi",
    "new_messages": "Awọn ifiranṣẹ titun",
    "file": "Faili",
    "attachment": "Asomọ",
    "gallery": "Ile aworan",
    "sync": "Amuṣiṣẹpọ",
    "diff_time": "Iyatọ akoko",
    "network": "Nẹtiwọọki",
    "account": "Iroyin",
    "configuration": "Iṣeto ni",
    "blockchain": "Blockchain",
    "blog_link": "Blog ọna asopọ",
    "community": "Agbegbe",
    "critical_zone": "Agbegbe pataki",
    "statistics": "Awọn iṣiro",
    "access": "Wiwọle",
    "seo": "SEO",
    "followers": "Awọn ọmọlẹhin",
    "followings": "Awọn atẹle",
    "private": "Awotẹlẹ",
    "soon": "Laipe",
    "features": "Awọn ẹya ara ẹrọ",
    "bot": "Bot",
    "sample": "Apeere",
    "how_it_work": "Báwo ló ṣe ń ṣiṣẹ́?",
    "page": "Oju-iwe",
    "congratulations": "Oriire",
    "recommend": "ṣeduro",
    "recommended": "Ti ṣe iṣeduro",
    "recoms": "Awọn iṣeduro",
    "likes": "Fẹran",
    "clicks": "Awọn titẹ",
    "platform": "Platform",
    "cms": "CMS",
    "cash": "Owo owo",
    "dir_payment": "afiranse ile ifowopamo",
    "auto_complete": "Laifọwọyi pari",
    "compare": "Fiwera",
    "infinite": "Ailopin",
    "tips": "Italolobo",
    "technical": "Imọ-ẹrọ",
    "finance": "Isuna",
    "your_phone_input": "Tẹ nọmba foonu kan sii",
    "income": "Owo ti n wọle",
    "change": "Yipada",
    "new_users": "Awọn olumulo titun",
    "success_orders": "Awọn ibere aṣeyọri",
    "direct": "Taara",
    "last_activity": "kẹhin aṣayan iṣẹ-ṣiṣe",
    "landing": "Ibalẹ",
    "now": "Bayi",
    "accept_agreement": "Mo ti ka ati ki o gba awọn ipo.",
    "report": "Iroyin",
    "tablet": "Tabulẹti",
    "pc": "PC",
    "acquisition_channel": "Akomora ikanni",
    "to": "Si",
    "info": "Alaye",
    "general": "Gbogboogbo",
    "upload": "Gbee si",
    "general_config": "Gbogbogbo atunto",
    "limits_config": "Awọn idiwọn",
    "design_config": "Apẹrẹ & Ara",
    "duration_config": "Iye akoko",
    "constraints_config": "Ifilelẹ yiyẹ ni",
    "clubs_config": "Wa ni Clubs",
    "additional_config": "Awọn atunto afikun",
    "import": "gbe wọle",
    "ribbon": "Ribbon",
    "countries": "Awọn orilẹ-ede",
    "edit": "Ṣatunkọ",
    "delete": "Paarẹ",
    "analytics": "Atupale",
    "rules": "Awọn ofin",
    "unset": "Ko ṣeto",
    "carts": "Awọn kẹkẹ",
    "optional": "iyan",
    "design": "Apẹrẹ",
    "filter": "Àlẹmọ",
    "send": "Firanṣẹ",
    "approved": "Ti fọwọsi",
    "unit": "Ẹyọ",
    "profile": "profaili",
    "shipping_rates": "Awọn oṣuwọn gbigbe",
    "package": "Package",
    "overview": "Akopọ",
    "live": "Gbe",
    "never": "Kò",
    "always": "Nigbagbogbo",
    "mandatory": "Dandan",
    "expire_at": "Ọjọ Ipari",
    "position": "Ipo",
    "channel": "ikanni",
    "age": "Ọjọ ori",
    "charge": "Gba agbara",
    "giftcard": "Kaadi ebun",
    "acquisition": "Gbigba",
    "conversion": "Iyipada",
    "total_payments": "Lapapọ owo sisan",
    "community_ask": "Beere ni agbegbe",
    "children": "Awọn ọmọde",
    "export": "okeere",
    "list": "Akojọ",
    "hierarchy": "Logalomomoise",
    "images": "Awọn aworan",
    "demo": "Ririnkiri",
    "author": "Onkọwe",
    "designer": "Onise",
    "max": "O pọju",
    "accepted": "Ti gba",
    "reply": "Fesi",
    "reviewed": "Atunwo",
    "restored": "pada sipo",
    "merchant": "Oniṣòwo",
    "per_product": "Fun ọja",
    "journey": "Irin ajo",
    "after": "Lẹhin",
    "waiting_for_payment": "Jọwọ pari owo sisan...",
    "hour": "Wakati",
    "minute": "Iṣẹju",
    "premium": "Ere",
    "light": "Imọlẹ",
    "dark": "Dudu",
    "guest": "Alejo",
    "shops": "Awọn ile itaja",
    "vendor": "Olutaja",
    "vendors": "Awọn olutaja",
    "marketplace": "Ibi ọja",
    "verify_date": "Daju ọjọ",
    "note": "Akiyesi",
    "panel": "Igbimọ",
    "removed": "Yiyọ kuro",
    "segments": "Awọn apakan",
    "personal_info": "Alaye ti ara ẹni",
    "preferences": "Awọn ayanfẹ",
    "spec": "Spec",
    "reviews": "agbeyewo",
    "constraints": "Awọn ihamọ",
    "flexible": "Rọ",
    "usage_limit": "Iwọn lilo",
    "temporary": "Igba die",
    "original": "Atilẹba",
    "saved": "Ti fipamọ!",
    "sort": "Too",
    "documents": "Awọn iwe aṣẹ",
    "document": "Iwe aṣẹ",
    "please_wait": "Jọwọ duro...",
    "pickup": "Gbigbe",
    "customize": "ṣe akanṣe",
    "difficulty": "Iṣoro",
    "banned": "Ti gbesele",
    "company": "Ile-iṣẹ",
    "tax_shipping": "Owo-ori gbigbe",
    "warranty": "Atilẹyin ọja",
    "return_policy": "Pada Afihan",
    "guide": "Itọsọna",
    "translate": "Tumọ",
    "public": "Gbangba",
    "deleted": "Parẹ",
    "variant": "Iyatọ",
    "secure": "Ni aabo",
    "admin": "Abojuto",
    "tax_included_abstract": "pẹlu.",
    "payment_not_settled": "Owo sisan ko yanju!",
    "orders_list": "Akojọ awọn ibere",
    "subscription_plan": "Eto ṣiṣe alabapin",
    "contents": "Awọn akoonu",
    "pricings": "Awọn idiyele",
    "static_page": "Oju-iwe aimi",
    "shop_button": "Bọtini itaja",
    "embed": "Fi sii",
    "over": "Pari",
    "tax_vary_by_location": "yatọ. ipo",
    "product_type": "Iru ọja",
    "tax_id": "ID owo-ori",
    "business_name": "Orukọ iṣowo",
    "invoice": "risiti",
    "included_in_the_product": "Ti o wa ninu ọja naa",
    "included_in_the_product_description": "Ọja naa pẹlu awọn paati wọnyi",
    "cross_sell": "Agbelebu Ta",
    "discount_off": "OFF",
    "extra_discount": "Eni afikun",
    "template": "Àdàkọ",
    "in_cart": "Ninu rira",
    "pros_and_cons": "Aleebu ati awọn konsi",
    "related_products": "Jẹmọ Products",
    "related_categories": "Awọn ẹka ibatan",
    "badges": "Baajii",
    "explore": "Ye",
    "updated": "imudojuiwọn",
    "bank_name": "Orukọ Bank",
    "bank_account_number": "Bank Account Number",
    "bank_routing_number": "Bank afisona Number",
    "bank_branch_address": "Bank Branch adirẹsi",
    "bank_account_name": "Ni kikun Name ti Account eni",
    "valuation": "Idiyele",
    "cluster": "Àkójọpọ̀",
    "clusters": "Awọn iṣupọ",
    "subscriptions": "Awọn iforukọsilẹ",
    "spam": "Àwúrúju",
    "video": "Fidio"
  },
  "dialogs": {
    "delete": {
      "title": "Paarẹ",
      "message": "Ṣe o da ọ loju pe o pa nkan yii rẹ bi?",
      "action": "Bẹẹni, Parẹ ni bayi"
    }
  },
  "actions": {
    "add_to_cart": "fi kun Awon nkan ti o nra",
    "cancel": "Fagilee",
    "update": "Imudojuiwọn",
    "add": "Fi kun",
    "delete": "Paarẹ",
    "new": "Tuntun",
    "save_continue": "Fipamọ & Tẹsiwaju",
    "save": "Fipamọ",
    "save_changes": "Fi awọn ayipada pamọ",
    "change": "Yipada",
    "continue": "Tesiwaju",
    "close": "Sunmọ",
    "finish": "Pari",
    "poll": "Idibo",
    "view": "Wo",
    "edit": "Ṣatunkọ",
    "next": "Itele",
    "previous": "Ti tẹlẹ",
    "create": "Ṣẹda",
    "set": "ṣeto",
    "find": "Wa",
    "accept": "Gba",
    "reject": "Kọ",
    "back": "Pada",
    "pay": "Sanwo",
    "pay_now": "Sanwo ni bayi",
    "print": "Titẹ sita",
    "return": "Pada",
    "publish": "Ṣe atẹjade",
    "confirm": "Jẹrisi",
    "copy": "Daakọ",
    "submit": "Fi silẹ",
    "send": "Firanṣẹ",
    "yes": "Bẹẹni",
    "no": "rara",
    "meh": "Unh",
    "clear": "Ko o",
    "dismiss": "Dasile",
    "search": "Wa",
    "deselect_all": "Yan gbogbo rẹ",
    "select_all": "Sa gbogbo re",
    "refresh": "Tuntun",
    "verify": "Jẹrisi",
    "play": "Ṣiṣẹ",
    "open": "Ṣii",
    "calculate": "Ṣe iṣiro",
    "quick_buy": "Awọn ọna Ra",
    "click_here": "kiliki ibi",
    "schedule": "Iṣeto",
    "send_now": "Firanṣẹ ni bayi",
    "download": "Gba lati ayelujara",
    "reset_default": "Tunto si aiyipada",
    "reset": "Tunto",
    "check": "Ṣayẹwo",
    "cod_payment": "Owo lori ifijiṣẹ",
    "dir_payment": "Owo gbigbe",
    "online_payment": "Isanwo Ayelujara",
    "checkout": "Ṣayẹwo",
    "show_all": "Ṣe afihan gbogbo rẹ",
    "login": "wo ile",
    "logout": "Jade jade",
    "more": "Die e sii..",
    "collapse": "Subu",
    "apply_change": "Waye awọn ayipada",
    "apply": "Waye",
    "add_giftcard": "Fi ebun kaadi",
    "charge": "Gba agbara",
    "send_invites": "Fi awọn ifiwepe",
    "past": "Ti o ti kọja",
    "restore": "Mu pada",
    "cut": "Ge",
    "get_sms_code": "Gba koodu ìfàṣẹsí",
    "register_no_mail": "Tẹsiwaju laisi imeeli",
    "no_mail_register_message": "Ṣe o ko ni adirẹsi imeeli tabi gbagbe ọrọ igbaniwọle rẹ?",
    "reset_by_mail": "Igbapada ọrọ igbaniwọle nipasẹ imeeli",
    "reset_by_sms": "Igbapada ọrọ igbaniwọle nipasẹ SMS",
    "cash_payment": "owo sisan",
    "show_chart": "Ṣe afihan aworan apẹrẹ",
    "open_app": "Ṣii app",
    "login_now": "Buwolu wọle ni bayi",
    "watch_video": "Wo fidio",
    "check_now": "Ṣayẹwo bayi",
    "remove_image": "Yọ aworan kuro",
    "view_website": "Ṣii ọna asopọ",
    "explore": "Ye {name}",
    "go": "Lọ",
    "read_more": "Ka siwaju",
    "start_now": "Bẹrẹ ni bayi - O jẹ ọfẹ",
    "view_live": "Wo ifiwe",
    "resend_code": "Tun koodu ranṣẹ",
    "invite": "Pe",
    "add_more": "Fi diẹ sii",
    "install_now": "Fi sori ẹrọ ni bayi",
    "uninstall": "Yọ kuro",
    "show_preview": "Ṣe afihan awotẹlẹ",
    "hide_preview": "Tọju awotẹlẹ",
    "download_now": "Ṣe Agbesọ nisinyii",
    "auto_fill": "Fi laifọwọyi kun",
    "track": "Orin",
    "change_state": "Yi Ipo",
    "done": "Ti ṣe",
    "reply": "Fesi",
    "watch_now": "Wo Bayi",
    "unlock": "Ṣii silẹ",
    "lock": "Titiipa",
    "create_clone": "Ṣẹda oniye",
    "regenerate": "Tuntun-pada",
    "add_message": "Fi ifiranṣẹ kun",
    "continue_chat": "Tesiwaju iwiregbe",
    "add_new_message": "Fi ifiranṣẹ titun kun",
    "change_setting": "Yi eto pada",
    "delete_all": "Pa Gbogbo Rẹ",
    "transfer_fund": "Owo gbigbe",
    "reverse_fund": "Iyipada owo",
    "settlement": "Ibugbe",
    "refund": "agbapada",
    "partial_refund": "Agbapada Apa kan",
    "change_payment_method": "Yi owo sisan ọna",
    "buy": "Ra",
    "view_all": "Wo Gbogbo",
    "view_now": "Wo Bayi",
    "paste": "Lẹẹmọ"
  },
  "instance_message_title": "Firanṣẹ lẹsẹkẹsẹ ifiranṣẹ",
  "instance_message": "Hi {name}, Oruko mi ni {author} lati {company}.",
  "errors": {
    "419": "O ti wa aláìṣiṣẹ́mọ́ fún ìgbà pípẹ́, jọ̀wọ́ <b>⟳ TÚN ÌWÉ ONÍWỌ́ JỌ̀YỌ̀ SỌ́</b> fún àwọn ìdí ààbò.",
    "gateway_blockchain_sync_error": "Eto naa ko muuṣiṣẹpọ pẹlu blockchain. Kii yoo ṣee ṣe lati ṣẹda idunadura tuntun titi awọn amuṣiṣẹpọ awọn olupin wa yoo pari. A n yanju iṣoro naa.",
    "gateway_network_error": "Iṣẹ ẹnu-ọna isanwo ti koju iṣoro ibaraẹnisọrọ kan."
  },
  "receiver_info": {
    "map": {
      "title": "Adiresi wo ni a ma gbe wa",
      "confirm": "Ṣeto ipo",
      "address_type": "Ibi-afẹde",
      "receptor_type": "Olugba"
    },
    "receiver_address": "Yan adirẹsi sowo",
    "address": "adirẹsi",
    "postcode": "koodu ifiweranṣẹ",
    "enter_value": "Fọwọsi nibi",
    "address_note": "Akiyesi",
    "tel": "Nọmba olubasọrọ",
    "service_address": "Yan adirẹsi rẹ"
  },
  "weight": {
    "g": "g",
    "oz": "iwon",
    "lb": "lb",
    "kg": "kg"
  },
  "mass_unit_name": {
    "g": "giramu",
    "oz": "Ounce",
    "lb": "Iwon",
    "kg": "kilo"
  },
  "length": {
    "cm": "cm",
    "in": "ninu",
    "ft": "ft",
    "mm": "mm",
    "m": "m",
    "yd": "yd"
  },
  "size_unit_name": {
    "cm": "Centimeter",
    "in": "Inṣi",
    "ft": "Ẹsẹ",
    "mm": "millimeter",
    "m": "mita",
    "yd": "Àgbàlá"
  },
  "distance": {
    "m": "mita",
    "km": "km"
  },
  "time": {
    "days": "Awọn ọjọ",
    "hours": "Awọn wakati",
    "minutes": "Iṣẹju",
    "seconds": "Aaya"
  },
  "units": [
    "Ẹyọ",
    "ohun kan",
    "kọọkan",
    "ṣeto",
    "nkan",
    "kilo",
    "giramu",
    "miligiramu",
    "mita",
    "millimeter",
    "square mita",
    "square ẹsẹ",
    "mita onigun",
    "lita",
    "milimita",
    "ẹsẹ",
    "galonu",
    "inches",
    "iwon",
    "poun",
    "idamẹrin",
    "àgbàlá",
    "yara",
    "iṣẹju-aaya",
    "iseju",
    "wakati",
    "awọn ọjọ",
    "ọsẹ",
    "osu",
    "ọdun"
  ],
  "region_types": {
    "State": "Ìpínlẹ̀",
    "Territory": "Agbègbè",
    "Province": "Agbegbe"
  },
  "transaction_status": {
    "RequireAction": "Igbese ti beere",
    "Processing": "Ṣiṣẹda",
    "Canceled": "fagilee",
    "Succeeded": "Aṣeyọri"
  },
  "placeholders": {
    "name": "Jone Cox",
    "email": "rẹ-mail{'@'}mail.com",
    "phone": "+1 000 0000",
    "language": "Yan ede..",
    "friend_email": "Imeeli ore re...",
    "friend_name": "Jáde. Oruko ore re",
    "select_date": "Yan ọjọ kan..."
  },
  "notification": {
    "confirm": "Jẹrisi",
    "confirm_message": "Awọn iyipada ti o fipamọ ni aṣeyọri.",
    "error": "Asise",
    "message": "Ifiranṣẹ",
    "caution": "Išọra",
    "warning": "Ikilo",
    "award": "Oriire",
    "error_message": "Laanu, aṣiṣe kan ti ṣẹlẹ.",
    "congratulation": "Oriire",
    "coming_soon": "Laipe",
    "on_fetching_data": "Ngba alaye..",
    "new_pwa_version": "Titun ti ikede wa bayi. Ṣe o fẹ lati ṣe imudojuiwọn ohun elo naa?",
    "over_license_limit": "Ju Ipari Iwe-aṣẹ",
    "update_license": "Ṣe imudojuiwọn iwe-aṣẹ rẹ",
    "required": "Ti beere fun",
    "invalid_email": "Imeeli ti ko tọ",
    "invalid_domain": "Ibugbe ti ko tọ",
    "invalid_min_length": "Ipari to kere julọ gbọdọ jẹ {length}",
    "invalid_min_array_length": "O kere ju yan awọn nkan {length}",
    "invalid_max_chars": "Awọn lẹta {maxCount} ti o pọju",
    "invalid_url": "URL ti ko tọ",
    "country_invalid": "Yan orilẹ-ede ti nlo!",
    "postal_code_invalid": "Ṣeto koodu ifiweranse to wulo!"
  },
  "colors": {
    "#D32F2F": "Pupa",
    "#C2185B": "Pink",
    "#7B1FA2": "eleyi ti",
    "#512DA8": "Dudu eleyi ti",
    "#303F9F": "Indigo Blue",
    "#1976D2": "Buluu",
    "#0288D1": "Buluu Imọlẹ",
    "#0097A7": "Turquoise Blue",
    "#00796B": "Gussi Green",
    "#388E3C": "Alawọ ewe",
    "#689F38": "Imọlẹ alawọ ewe",
    "#AFB42B": "Limo",
    "#FBC02D": "Yellow",
    "#FFA000": "awọ yẹlo to ṣokunkun",
    "#F57C00": "ọsan",
    "#E64A19": "Osan didan",
    "#5D4037": "Brown",
    "#616161": "Grẹy",
    "#455A64": "Buluu Grẹy",
    "#FFD700": "Wura",
    "#C0C0C0": "Fadaka",
    "#b76e79": "Golden Rose",
    "#383838": "Matte dudu",
    "#FFFFFF": "funfun",
    "#FFF": "funfun",
    "#000000": "Dudu",
    "#000": "Dudu",
    "#7d263a": "Maroon",
    "#FD9F17": "Wura",
    "#229DBF": "Aqua",
    "#6DC9E2": "Aqua Triblend",
    "#413B2D": "Ologun",
    "#474747": "Idapọmọra",
    "#E6195C": "Berry",
    "#B2184C": "Berry Triblend",
    "#FC7F5F": "sisun Orange",
    "#80011F": "Cardinal",
    "#382829": "Chocolate",
    "#F06336": "Coral",
    "#FAE7C9": "Ipara",
    "#6B2257": "Currant",
    "#222127": "Grẹy Dudu",
    "#0D5A74": "Tii Jin",
    "#00582F": "Evergreen",
    "#214C30": "Igbo",
    "#DC2867": "Fuchsia",
    "#38561F": "Kelly",
    "#5C884D": "Ewe",
    "#558450": "Imọlẹ Aqua",
    "#96B5C9": "Buluu Imọlẹ",
    "#DCAFCE": "Lilac",
    "#D3E1A4": "Orombo wewe",
    "#9DE7C2": "Mint",
    "#F6EAD2": "Adayeba",
    "#1A1F35": "Ọgagun",
    "#404624": "Olifi",
    "#271020": "Pupa buulu toṣokunkun",
    "#A8355C": "Rasipibẹri",
    "#D6BEA6": "Ipara Asọ",
    "#BEA994": "Tan",
    "#0DB2AE": "Tii",
    "#A86EA9": "Awọ aro",
    "#36454F": "Eedu",
    "#b3b0ab": "erogba Grey",
    "#463e3d": "Eedu Heather",
    "#282d3c": "Ọgagun Blazer"
  },
  "address_info": {
    "name": "Oruko",
    "tel": "Foonu",
    "email": "Imeeli",
    "country": "Orilẹ-ede",
    "city": "Ilu",
    "state": "Ìpínlẹ̀",
    "address": "adirẹsi",
    "building_number": "Nọmba ile",
    "building_unit": "Ẹyọ",
    "postcode": "koodu ifiweranṣẹ",
    "note": "Akiyesi",
    "county": "Agbegbe"
  },
  "product_types": {
    "physical": "Ti ara",
    "physical_description": "Awọn ọja ti ara gẹgẹbi: awọn foonu alagbeka, awọn iwe ohun, awọn eroja itanna.",
    "virtual": "Foju",
    "virtual_description": "Awọn ọja ore Intanẹẹti gẹgẹbi: kaadi gbigba agbara, ifiṣura hotẹẹli, gbigba agbara ere.",
    "file": "Faili",
    "file_description": "Gbogbo awọn faili ti a gba laaye gẹgẹbi fidio dajudaju ori ayelujara, awọn iwe aṣẹ ti o ṣe igbasilẹ.",
    "service": "Iṣẹ",
    "service_description": "Awọn iṣẹ bii: atunṣe, gbigbe, ẹkọ.",
    "subscription": "Ṣiṣe alabapin",
    "subscription_description": "Ṣiṣe alabapin ati risiti fun awọn ọja, awọn iṣẹ, tabi akoonu."
  },
  "license": {
    "free": "Ọfẹ",
    "startup": "Ibẹrẹ",
    "company": "Ile-iṣẹ",
    "enterprise": "Idawọlẹ"
  },
  "currency": {
    "IRR": "IRR",
    "IRR_alt": "Toman",
    "USD": "USD",
    "BTC": "BTC",
    "ETH": "ETH",
    "NIOC": "NIOC",
    "SEL": "SEL",
    "EUR": "EUR",
    "ADA": "ADA",
    "GBP": "GBP",
    "AED": "AED",
    "AFN": "AFN",
    "CAD": "CAD",
    "TRY": "TRY",
    "CNY": "CNY",
    "RUB": "RUB",
    "SAR": "SAR",
    "LBP": "LBP",
    "QAR": "QAR",
    "EGP": "EGP",
    "INR": "INR",
    "DKK": "DKK",
    "PKR": "PKR",
    "ALL": "ALL",
    "AMD": "AMD",
    "ANG": "ANG",
    "AOA": "AOA",
    "ARS": "ARS",
    "AUD": "AUD",
    "AWG": "AWG",
    "AZN": "AZN",
    "BAM": "BAM",
    "BBD": "BBD",
    "BDT": "BDT",
    "BGN": "BGN",
    "BIF": "BIF",
    "BMD": "BMD",
    "BND": "BND",
    "BOB": "BOB",
    "BRL": "BRL",
    "BSD": "BSD",
    "BWP": "BWP",
    "BYN": "BYN",
    "BZD": "BZD",
    "CDF": "CDF",
    "CHF": "CHF",
    "CLP": "CLP",
    "COP": "COP",
    "CRC": "CRC",
    "CVE": "CVE",
    "CZK": "CZK",
    "DJF": "DJF",
    "DOP": "DOP",
    "DZD": "DZD",
    "ETB": "ETB",
    "FJD": "FJD",
    "FKP": "FKP",
    "GEL": "GEL",
    "GIP": "GIP",
    "GMD": "GMD",
    "GNF": "GNF",
    "GTQ": "GTQ",
    "GYD": "GYD",
    "HKD": "HKD",
    "HNL": "HNL",
    "HRK": "HRK",
    "HTG": "HTG",
    "HUF": "HUF",
    "IDR": "IDR",
    "ILS": "ILS",
    "ISK": "ISK",
    "JMD": "JMD",
    "JPY": "JPY",
    "KES": "KES",
    "KGS": "KGS",
    "KHR": "KHR",
    "KMF": "KMF",
    "KRW": "KRW",
    "KYD": "KYD",
    "KZT": "KZT",
    "LAK": "LAK",
    "LKR": "LKR",
    "LRD": "LRD",
    "LSL": "LSL",
    "MAD": "MAD",
    "MDL": "MDL",
    "MGA": "MGA",
    "MKD": "MKD",
    "MMK": "MMK",
    "MNT": "MNT",
    "MOP": "MOP",
    "MRO": "MRO",
    "MUR": "MUR",
    "MVR": "MVR",
    "MWK": "MWK",
    "MXN": "MXN",
    "MYR": "MYR",
    "MZN": "MZN",
    "NAD": "NAD",
    "NGN": "NGN",
    "NIO": "NIO",
    "NOK": "NOK",
    "NPR": "NPR",
    "NZD": "NZD",
    "PAB": "PAB",
    "PEN": "PEN",
    "PGK": "PGK",
    "PHP": "PHP",
    "PLN": "PLN",
    "PYG": "PYG",
    "RON": "RON",
    "RSD": "RSD",
    "RWF": "RWF",
    "SBD": "SBD",
    "SCR": "SCR",
    "SGD": "SGD",
    "SEK": "SEK",
    "SHP": "SHP",
    "SLL": "SLL",
    "SOS": "SOS",
    "SRD": "SRD",
    "STD": "STD",
    "SZL": "SZL",
    "THB": "THB",
    "TJS": "TJS",
    "TOP": "TOP",
    "TTD": "TTD",
    "TWD": "TWD",
    "TZS": "TZS",
    "UAH": "UAH",
    "UGX": "UGX",
    "UYU": "UYU",
    "UZS": "UZS",
    "VND": "VND",
    "VUV": "VUV",
    "WST": "WST",
    "XAF": "XAF",
    "XCD": "XCD",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YER",
    "ZAR": "ZAR",
    "ZMW": "ZMW",
    "GHS": "GHS",
    "ZWD": "ZWD",
    "IQD": "IQD",
    "SYP": "SYP"
  },
  "variants": {
    "color": "Àwọ̀",
    "volume": "Iwọn",
    "count_in_pack": "Ka ni idii",
    "weight": "Iwọn",
    "type": "Ohun elo",
    "style": "Ara"
  },
  "delivery_state": {
    "check_queue": "Nduro awotẹlẹ",
    "order_confirm": "Bere fun ìmúdájú",
    "preparing_order": "Ngbaradi",
    "sent_order": "Lori ifijiṣẹ",
    "to_customer": "Ti fi jiṣẹ"
  },
  "status": {
    "unpaid": "Ti ko sanwo",
    "paid": "Sanwo",
    "canceled": "fagilee",
    "completed": "Ti yanju",
    "reserved": "Ni ipamọ",
    "COD": "COD",
    "sold": "Ti ta",
    "open": "Ṣii",
    "cancel": "fagilee",
    "active": "Ti nṣiṣe lọwọ",
    "inactive": "Aiṣiṣẹ",
    "debug": "Ṣatunkọ",
    "live": "Gbe",
    "test": "Idanwo",
    "connected": "Ti sopọ",
    "disconnected": "Ge asopọ",
    "accept": "Gba",
    "reject": "Kọ",
    "pending": "Ni isunmọtosi",
    "rejected": "Kọ silẹ",
    "accepted": "Ti gba"
  },
  "dimensions": {
    "cm": "cm",
    "km": "km",
    "kg": "kg"
  },
  "transportation_type": {
    "motorbike": "Alupupu",
    "motorbike_description": "Iwọn alabọde laarin awọn ibuso diẹ.",
    "cargo_small": "Ẹru kekere",
    "cargo_small_description": "Olona-kilometer eru ina.",
    "cargo": "Eru",
    "cargo_description": "Iwọn alabọde laarin awọn ibuso diẹ.",
    "truck": "Ọkọ ayọkẹlẹ",
    "truck_description": "Olopobobo tabi eru eru laarin orilẹ-ede naa.",
    "fast_post": "Yara Ifiweranṣẹ",
    "fast_post_description": "Yara ipolowo nipasẹ ifiweranṣẹ.",
    "post": "Ifiweranṣẹ deede",
    "post_description": "Ifiweranṣẹ deede nipasẹ ọfiisi ifiweranṣẹ.",
    "airplane": "Ifiweranṣẹ",
    "airplane_description": "Abele ati ajeji ina ati alabọde eru.",
    "bicycle": "Firanṣẹ mimọ",
    "bicycle_description": "Ẹru ina, laarin awọn ọgọọgọrun awọn bata meta ti awọn ọkọ ayọkẹlẹ ti kii ṣe mọto.",
    "global": "Gbigbe agbaye",
    "global_description": "Sowo si oke okun nipasẹ afẹfẹ, okun tabi ilẹ.",
    "pickup": "Gbigbe",
    "pickup_description": "Awọn alabara gbe awọn nkan naa ni ile itaja tabi ile-itaja ti ara rẹ."
  },
  "article": {
    "login_to_see_error": "Buwolu wọle lati wọle si nkan naa",
    "create_new_action": "Ṣẹda New akoonu",
    "menu_title": "Akojọ aṣyn",
    "menu": {
      "edit": "Ipo Ṣatunkọ",
      "view_mode": "Ipo wiwo",
      "delete": "Pa Abala"
    },
    "schedule_action": "Ṣe o fẹ lati seto titẹjade?",
    "schedule_title": "Iṣeto atẹjade aifọwọyi",
    "edit_mode": "Ṣatunkọ",
    "public_view_mode": "Wiwo gbogbo eniyan",
    "publish_at": "Ṣe atẹjade ni",
    "published": "Atejade",
    "draft": "Akọpamọ",
    "saving": "Nfipamọ",
    "save_and_publish_action": "Fipamọ ati Ṣe atẹjade",
    "save_draft_action": "Fipamọ osere",
    "private": "Ikọkọ",
    "public": "Gbangba",
    "category_input": "Ẹka",
    "category_input_message": "Yan ẹka nkan",
    "parent_input": "Ẹka obi",
    "parent_input_message": "Yan akoonu baba",
    "schedule_input": "Iṣeto",
    "schedule_input_placeholder": "Ti o ba fẹ ki itan naa gbejade ni akoko kan pato.",
    "schedule_view_action": "Wo Eto Atẹjade",
    "author_title": "Ti a kọ nipasẹ",
    "read_time": "Akoko ikẹkọ",
    "read_time_unit": "Iṣẹju",
    "claps_action": "Claps",
    "claps": "Claps",
    "likes": "Bi",
    "about_author": "Nipa onkowe",
    "updated_at": "imudojuiwọn",
    "wrote_at": "Ti a kọ si",
    "now": "Bayi",
    "follow_action": "Tẹle",
    "followed": "Tẹle",
    "report_and_delete_action": "Jabo ki o si pa nkan yii rẹ",
    "report_action": "Iroyin Abuse",
    "you_reported_this_article": "Nkan yii ti ni ijabọ ilokulo tẹlẹ.",
    "add_to_publication_action": "Fi si Atejade",
    "author_socials": "Onkọwe lori media media",
    "share": "Pin",
    "report_dialog": {
      "report_and_delete_title": "Jabọ ilokulo ati yọ akoonu kuro",
      "report_title": "Jabo akoonu yii bi irira",
      "message": "Kini idi fun fifisilẹ akoonu yii? Yan ọkan ninu awọn aṣayan wọnyi.",
      "accept_and_delete_action": "Jẹrisi ati Pa akoonu rẹ"
    },
    "schedule_dialog": {
      "title": "Eto Itusilẹ akoonu",
      "publish_at": "Ṣe atẹjade ni",
      "last_edit": "kẹhin àtúnṣe",
      "view_action": "Wo Abala"
    },
    "notifications": {
      "update_success_title": "Fi Alaye silẹ",
      "update_success": "A ṣe imudojuiwọn nkan ni aṣeyọri.",
      "update_error": "Alaye ti a tẹ ko wulo.",
      "delete_error": "O ko le pa nkan yii rẹ!",
      "report_and_delete_success_title": "Jabo ati Parẹ",
      "report_and_delete_success_message": "Abala ti paarẹ ni aṣeyọri.",
      "report_success_title": "Iroyin Iroyin",
      "report_success_message": "Ijabọ rẹ lori nkan yii ti gbejade."
    },
    "alert": {
      "delete_article": {
        "title": "Pa Abala",
        "message": "Ṣe o da ọ loju pe o fẹ paarẹ nkan yii patapata bi?",
        "action": "Paarẹ"
      }
    },
    "edit_window": {
      "title": "Yan Ọrọ Aworan ati Lakotan",
      "digest": "Lakotan"
    },
    "editor": {
      "title_placeholder": "Akole..",
      "body_placeholder": "Kọ akoonu nla ..",
      "accept_file_types_error": "Ọna kika faili yii ko ṣe itẹwọgba:",
      "max_file_size_error": "Faili yii ti tobi ju:",
      "notifications": {
        "image_uploaded_success": "Aworan ti o fipamọ ni aṣeyọri",
        "image_uploaded_failed": "Aṣiṣe gbigba aworan."
      },
      "embed_placeholder": "Tẹ koodu iframe sii, Facebook, Youtube tabi URL eyikeyi miiran ki o tẹ sii.",
      "embed_caption_placeholder": "Tẹ akọle sii (aṣayan)",
      "images_caption_placeholder": "Tẹ akọle sii fun aworan yii.."
    }
  },
  "article_report": {
    "inappropriate": "Awọn akoonu ti yi article ni sedede.",
    "fake": "Eyi jẹ iro ati ẹtan.",
    "spam": "Nkan yii ti jẹ spammed ati daakọ.",
    "scam": "Eyi le nireti lati fa malware, awọn ọlọjẹ tabi jamba eto.",
    "hacked": "Yi ojula han lati ti a ti gepa.",
    "offensive": "Akoonu ede ati awọn fokabulari jẹ aibikita ati aibọwọ.",
    "violent": "Mo ro pe akoonu yii ni awọn aworan iwokuwo ati pe o ṣẹ si awọn ofin.",
    "harassment": "Mo ro pe eyi jẹ ẹlẹyamẹya.",
    "hate": "Mo ro pe eyi jẹ nipa igbega iwa-ipa.",
    "infringe": "Eyi tako awọn ẹtọ mi."
  },
  "comments": {
    "new_action": "Tẹ lati fi asọye kan silẹ..",
    "title": "Comments",
    "body_placeholder": "Ọrọìwòye rẹ tabi ifiranṣẹ",
    "send_action": "Firanṣẹ asọye",
    "body_is_empty_error": "Ọrọìwòye ti ṣofo!",
    "comments": "Comments",
    "no_comments": "Kọ asọye akọkọ...",
    "load_more_action": "Gba awọn asọye diẹ sii ..",
    "cant_send_comment": "O ko le fi titun ifiweranṣẹ.",
    "cant_remove_this_comment": "O ko le pa yi ọrọìwòye!",
    "product_buyer": "Olura",
    "delete_alert": {
      "title": "Pa Ọrọìwòye rẹ",
      "message": "Ṣe o fẹ lati pa asọye yii rẹ bi?",
      "action": "Paarẹ"
    },
    "notifications": {
      "delete_success": "Ọrọìwòye rẹ paarẹ ni aṣeyọri."
    },
    "first_send": "Ifiweranṣẹ akọkọ",
    "comment_at": "Tan-an",
    "edit_comment": "Ṣatunkọ Ọrọìwòye",
    "my_comments": "Mi Comments"
  },
  "customer_club": {
    "bronze": "Idẹ",
    "silver": "Fadaka",
    "gold": "Wura",
    "platinum": "Platinum",
    "diamond": "Diamond"
  },
  "application_categories": {
    "tracking": "Ṣiṣayẹwo ihuwasi olumulo",
    "payment": "Isanwo",
    "seo": "SEO",
    "crm": "CRM",
    "transportation": "Gbigbe",
    "automation": "Adaṣiṣẹ",
    "inventory": "Ibi ipamọ",
    "accounting": "Iṣiro",
    "marketing": "Titaja",
    "advertising": "Ipolowo",
    "staff": "Oṣiṣẹ",
    "incentive": "Awọn iwuri",
    "shop": "Itaja"
  },
  "social_network": {
    "instagram": "Instagram",
    "telegram": "Telegram",
    "googleplay": "GooglePlay",
    "appstore": "AppStore",
    "twitter": "Twitter",
    "linkedin": "Linkedin",
    "medium": "Alabọde",
    "selldone": "Ti pari",
    "facebook": "Facebook",
    "pinterest": "Pinterest",
    "whatsapp": "WhatsApp",
    "skype": "Skype",
    "facebook_messenger": "Facebook ojiṣẹ"
  },
  "form_builder": {
    "add_item_action": "Fi nkan titun kun",
    "title_input": "Akọle",
    "name_input": "Orukọ oniyipada",
    "value_input": "Awọn iye",
    "value_input_message": "User Aw Akojọ",
    "default": "Iwọn aiyipada",
    "types": {
      "simple": "Rọrun",
      "selective": "Yiyan",
      "switch": "Yipada",
      "file": "Faili",
      "number": "Nọmba"
    },
    "placeholder_input": "Ibi ipamọ",
    "file_type_input": "Awọn iru faili ti o ṣe itẹwọgba",
    "file_type_message": "jpeg, png, zip,..."
  },
  "virtual_order_info_summery": {
    "title": "Orukọ ọja",
    "reserved_at": "Iforukọ Ọjọ",
    "total_price": "Oye gbo e",
    "discount": "Eni owo",
    "final_price": "Ipari iye",
    "payment_status": "Ipo sisan",
    "payment_status_waiting": "Nduro fun sisanwo",
    "payment_status_paid": "Sanwo",
    "buyer": "Olura"
  },
  "virtual_item_info": {
    "title": "Nkan Foju",
    "outputs": {
      "title": "O wu Alaye",
      "sub_title": "Alaye Asiri ti Nkan yii",
      "message": "Alaye yii yoo han si olumulo lẹhin rira ọja naa."
    },
    "inputs": {
      "title": "Alaye ti a beere",
      "sub_title": "Eniti o beere alaye",
      "message": "Olura gbọdọ tẹ alaye ti o beere sii ni fọọmu naa"
    },
    "notifications": {
      "inputs_set_success": "Fọọmu alaye forukọsilẹ ni aṣeyọri.",
      "confirm_by_admin_success": "Ipari ibere timo.",
      "confirm_by_buyer_success": "Ipari ibere timo."
    }
  },
  "order_reject_reasons": {
    "cant_accept_cod": "Aṣẹ yii ko le gba nipasẹ sisanwo COD.",
    "payment_returned": "Owo sisan nipasẹ alabara ti pada.",
    "payment_fraud": "Owo sisan ti jẹ idanimọ bi ẹtan.",
    "location_out_of_service": "Ipo onibara ko si ni iṣẹ.",
    "user_not_responding": "Onibara ko dahun awọn ipe.",
    "shop_owner_fault": "Aṣiṣe waye nipasẹ awọn oṣiṣẹ ile itaja ni kikun alaye.",
    "lack_of_inventory": "Ko si ọja.",
    "legal_restriction": "Ko le gbe aṣẹ kan nitori awọn ihamọ ofin.",
    "pricing_fault": "Asise ifowoleri nipasẹ eniti o.",
    "system_fault": "Kokoro eto."
  },
  "basket_order_info_summery": {
    "receiver": "Olugba",
    "phone": "Tẹli",
    "reserved_date": "Ọjọ rira",
    "total_price": "Oye gbo e",
    "discount": "Eni owo",
    "final_price": "Ipari iye",
    "address": "Ifijiṣẹ adirẹsi",
    "payment_status": "Ipo sisan"
  },
  "basket_status": {
    "open": "Ṣii",
    "reserved": "Ni ipamọ",
    "paid": "Sanwo",
    "canceled": "fagilee",
    "cod": "Sanwo Lori Ifijiṣẹ",
    "receipt_added": "Iwe-ẹri ti a ṣafikun",
    "payment_processing": "Sise owo sisan"
  },
  "basket_delivery_state": {
    "rejected": "Kọ silẹ",
    "reject_reason_not_found": "Idi ko mọ.",
    "step_1": "Atunwo",
    "step_2": "Ìmúdájú",
    "step_3": "Igbaradi",
    "step_4": "Lori ifijiṣẹ",
    "step_5": "Ti fi jiṣẹ"
  },
  "basket_return_request_view": {
    "title": "Ibere pada",
    "delivery_date": "Deeti ifijiṣẹ",
    "return_date": "Ọjọ ìbéèrè",
    "items_count": "Awọn nkan ti o pada jẹ iṣiro",
    "items_count_unit": "nkan(s)",
    "reason": "Idi",
    "description": "Apejuwe",
    "status": "Ipo",
    "download_image": "Ṣe igbasilẹ aworan",
    "download_film": "Ṣe igbasilẹ fidio",
    "download_voice": "Ṣe igbasilẹ ohun",
    "accept_by_admin_action": "Gba ìbéèrè",
    "reject_by_admin_action": "Kọ ìbéèrè",
    "message_for_admin": "Gẹgẹbi adehun ti o ti gba nipasẹ lilo Selldone, o gbọdọ kan si ẹniti o ra ọja naa ki o jẹ ki o sọ fun ilana ti mimu aṣẹ / aṣẹ rẹ pada. Eyi gbọdọ ṣee ṣe ti o ba gba ibeere tabi kọ ati gba aṣẹ ni kikun ti olura.",
    "notifications": {
      "update_status_success": "Ipo ibeere imudojuiwọn."
    }
  },
  "basket_list": {
    "return_count": "Pada: {count} nọmba",
    "table": {
      "row": "kana",
      "image": "Aworan",
      "product_name": "Ọja",
      "variant": "Iyatọ",
      "warranty": "Awọn iṣeduro",
      "count": "Ka",
      "price": "owo"
    }
  },
  "return_request_list": {
    "count": "Nọmba itọkasi",
    "return_warranty": "Owo Back Garanti",
    "return_warranty_unit": "Ọjọ (awọn ọjọ)",
    "table": {
      "code": "koodu ibere",
      "product": "Ọja",
      "delivery_at": "Ọjọ ti a gba wọle",
      "state": "Ipo",
      "reason": "Idi",
      "return_warranty_period": "Akoko atilẹyin ọja"
    }
  },
  "data_toolbar": {
    "search": "Wa",
    "sort_by": "Sa pelu",
    "count_item": "Ṣafihan awọn nkan {item}"
  },
  "sort": {
    "created_at": "Ṣẹda ọjọ",
    "updated_at": "Ọjọ Ṣatunkọ",
    "title": "Akọle",
    "description": "Apejuwe",
    "like": "Gbajumo",
    "power": "Claps",
    "product_type": "Iru ọja",
    "discount": "Eni owo",
    "rate": "Idiwon",
    "rate_count": "Nọmba ti-wonsi",
    "category": "Ẹka",
    "product": "Ọja",
    "body": "Akoonu",
    "card_type": "Iru kaadi",
    "card_number": "Nomba kaadi",
    "balance": "Iwontunwonsi",
    "paid": "Iye ti o lo",
    "currency": "Owo owo",
    "expire_at": "Ọjọ Ipari",
    "discount_code": "Eni koodu",
    "discount_percent": "Eni owo",
    "discount_limit": "Eni aropin",
    "max_count": "Iwọn to pọju",
    "used_count": "Lo",
    "start_date": "Ọjọ ibẹrẹ",
    "end_date": "Ọjọ ipari",
    "total_discount_amount": "Lapapọ eni",
    "initial_charge": "idiyele ibẹrẹ",
    "total_count": "Lapapọ kika",
    "amount_paid": "Iye owo ti a san",
    "name": "Oruko",
    "published": "Atejade",
    "visits": "Awọn abẹwo",
    "color": "Àwọ̀",
    "landing_page": "Oju-iwe ibalẹ",
    "enable": "Mu ṣiṣẹ",
    "fix_commission": "Igbimọ ti o wa titi",
    "percent_commission": "Igbimo ogorun",
    "payment_at": "Ọjọ sisan",
    "issued_at": "Ọjọ itẹjade",
    "payment": "Isanwo",
    "website": "Aaye ayelujara",
    "email": "Imeeli",
    "user": "olumulo",
    "code": "koodu",
    "schedule_at": "Ọjọ iṣeto",
    "sender": "Olufiranṣẹ",
    "in_que": "Ninu isinyi",
    "sent": "Ti firanṣẹ",
    "shop": "Itaja",
    "quantity": "Opoiye",
    "amount": "Iye",
    "jobs": "Iwọn iṣẹ",
    "success": "Iwọn aṣeyọri",
    "fail": "Iṣiro ikuna",
    "distance": "Ijinna",
    "duration": "Iye akoko",
    "reset_at": "Ojo atunto",
    "delivery_person": "Ènìyàn",
    "delivery_service": "Iṣẹ",
    "date": "Ọjọ",
    "order": "Bere fun",
    "order_id": "Paṣẹ ID",
    "status": "Ipo",
    "price": "owo",
    "count": "Ka",
    "final_price": "Ipari owo",
    "charge": "Gba agbara",
    "mention": "Darukọ",
    "officer": "Oṣiṣẹ",
    "registered": "Iforukọsilẹ",
    "purchased": "Ti ra",
    "sex": "abo"
  },
  "search_box": {
    "result": "Awọn abajade wiwa",
    "tips": "Wa Awọn ọja ati Awọn ẹka",
    "label": "Wa...",
    "category": "Ẹka"
  },
  "lead_status": {
    "physical_fast_delivery": "Ifijiṣẹ lẹsẹkẹsẹ",
    "physical_under_24h_delivery": "Pese laarin awọn wakati {lead} atẹle",
    "physical_over_24h_delivery": "Ngbaradi ati ifisilẹ lati awọn ọjọ {days} ti nbọ",
    "virtual_fast_prepare": "Ifijiṣẹ lẹsẹkẹsẹ",
    "virtual_under_24h": "Yoo ṣee ṣe laarin awọn wakati {lead} atẹle",
    "virtual_over_24h": "Yoo ṣee ṣe lati awọn ọjọ {days} to nbọ"
  },
  "return_request_state": {
    "pending": "Ni isunmọtosi",
    "accepted": "Timo",
    "rejected": "Kọ silẹ"
  },
  "return_order_reason": {
    "physical": {
      "U1": "Aiṣedeede ọja",
      "U2": "Ko si ọja ni package gbigbe",
      "U3": "Package tabi fifọ ọja",
      "U4": "Package tabi nọmba ni tẹlentẹle fifọwọkan",
      "U5": "Diẹ ninu awọn ohun kan lati inu apo ti nsọnu",
      "U6": "Ọja kii ṣe atilẹba",
      "U7": "Ọja ko ni itẹlọrun awọn pato"
    }
  },
  "image_uploader": {
    "label": "Fa & Ju silẹ tabi <u>Yan faili</u>",
    "max_size": "Iwọn idasilẹ ti o pọju: {size}"
  },
  "timespan": {
    "Morning": "8 owurọ - 12pm",
    "Evening": "12 kẹfa to 6 pm",
    "Night": "6 pm-12pm",
    "Instant": "Ifiweranṣẹ lẹsẹkẹsẹ"
  },
  "week_day": {
    "Saturday": "Satidee",
    "Sunday": "Sunday",
    "Monday": "Monday",
    "Tuesday": "Ọjọbọ",
    "Wednesday": "Wednesday",
    "Thursday": "Ojobo",
    "Friday": "Friday"
  },
  "payment_form": {
    "title": "Yan Ọna Isanwo",
    "gift_cards_input": "Awọn kaadi ẹbun",
    "gift_cards_input_empty": "Ko si awọn kaadi ẹbun ti a rii..",
    "more": "Omiiran",
    "pay_amount_by_gift_cards": "Owo sisan Kaadi",
    "select_payment_method": "Yan ọna isanwo rẹ lati awọn aṣayan atẹle.",
    "payment_amount_remained": "Ti o ku iye owo sisan",
    "payment_amount": "Iye owo ti a san",
    "all_paid_by_gift_cards": "Oriire, o ko nilo lati sanwo fun aṣẹ yii. Tẹ bọtini Pay Pẹlu Kaadi Ẹbun.",
    "pay_by_gift_cards_action": "San ibere pẹlu kaadi idiyele",
    "order_free_payment": "Oriire, aṣẹ rẹ jẹ ọfẹ!",
    "order_free_payment_action": "Bere fun Ọfẹ Bayi",
    "qr": {
      "address": "Adirẹsi owo sisan",
      "amount": "Iye"
    }
  },
  "discount_input": {
    "limit": "ẹdinwo {percent}% titi di {limit} {currency}",
    "action": "Fi eni koodu",
    "code_input": "Eni koodu",
    "notifications": {
      "add_success": "Oriire, wulo koodu eni."
    }
  },
  "gift_card": {
    "inactive": "Kaadi ti wa ni alaabo",
    "expire": "Ipari",
    "transfer": "Gbigbe",
    "send_to_friend": "Firanṣẹ si ọrẹ"
  },
  "count_down": {
    "days": "Ojo",
    "hours": "Wakati",
    "minutes": "Iṣẹju",
    "seconds": "Aaya"
  },
  "gift_status": {
    "Unpaid": "Nduro gbigba",
    "Paid": "Sanwo",
    "Rejected": "Kọ silẹ",
    "Canceled": "fagilee"
  },
  "gift_program_status": {
    "Airdrop": "sisan System",
    "Advertising": "Ipolowo",
    "PersonalGift": "Ẹbun Ti ara ẹni",
    "ShopGift": "Ile itaja ebun"
  },
  "currency_selector": {
    "label": "Owo owo"
  },
  "need_login": {
    "title": "wo ile",
    "login_sms": "SMS Wọle",
    "login_google": "Buwolu wọle pẹlu Google",
    "login_facebook": "Buwolu wọle pẹlu Facebook",
    "login_account": "Buwolu wọle nipasẹ Selldone",
    "register": "Olumulo titun? Forukọsilẹ bayi.",
    "mobile_input": "Tẹ alagbeka rẹ sii",
    "verification_code": "Kodu afimo",
    "msg_title": "Hi,",
    "msg_body": "Jọwọ buwolu wọle. Yoo gba to iṣẹju-aaya diẹ.",
    "login_apple": "Buwolu wọle pẹlu Apple",
    "login_email": "Buwolu wọle nipasẹ Imeeli",
    "email_login_step_1": "Jọwọ pese adirẹsi imeeli ti o wulo, ati pe a yoo fi koodu iwọle ranṣẹ si. Ko si ìforúkọsílẹ jẹ pataki.",
    "email_login_step_2": "Ṣe o da ọ loju pe o ti tẹ adirẹsi imeeli rẹ sii bi o ti tọ bi? A yoo firanṣẹ koodu iwọle si imeeli ti a pese, nitorinaa jọwọ rii daju pe deede.",
    "email_login_step_3": "A ti fi koodu ranṣẹ si imeeli rẹ. Jọwọ ṣe akiyesi pe koodu naa yoo pari ni iṣẹju 10."
  },
  "shop_badges": {
    "GOLDEN_1YEAR": {
      "name": "5 Odun Gold itaja"
    },
    "GOLDEN_2YEAR": {
      "name": "4 Odun Gold itaja"
    },
    "GOLDEN_3YEAR": {
      "name": "3 Odun Gold itaja"
    },
    "GOLDEN_4YEAR": {
      "name": "2 Odun Gold itaja"
    },
    "GOLDEN_5YEAR": {
      "name": "1 Odun Gold itaja"
    },
    "TOKEN_OWNER_1M": {
      "name": "Golden oludokoowo"
    },
    "TOKEN_OWNER_10M": {
      "name": "Diamond oludokoowo"
    },
    "TOKEN_OWNER_100M": {
      "name": "Ruby oludokoowo"
    },
    "COMMUNITY_LOYAL": {
      "name": "Ọmọ ẹgbẹ ti Superior Community ti Awọn nẹtiwọki Ibaraẹnisọrọ"
    },
    "GOLD_SUPPLIER": {
      "name": "Olupese goolu"
    },
    "GOLD_SELLER": {
      "name": "Gold Dealer"
    },
    "CONTENT_SUPERMAN": {
      "name": "Top Akoonu o nse"
    },
    "NINJA": {
      "name": "Ninja"
    },
    "STAR": {
      "name": "Irawọ"
    },
    "GUARDIAN": {
      "name": "Nla Onibara Service"
    },
    "KING": {
      "name": "Oba Oja"
    }
  },
  "cookie": {
    "title": "Oju opo wẹẹbu yii nlo awọn kuki",
    "message": "Oju opo wẹẹbu yii nlo awọn kuki lati mu iriri olumulo dara si. Nipa lilo oju opo wẹẹbu wa o gba gbogbo awọn kuki ni ibamu pẹlu Ilana Kuki wa.",
    "preferences_action": "Ṣakoso Awọn ayanfẹ",
    "agree_action": "Mo gba"
  },
  "basket_item_message": {
    "title": "Alaye ti a beere fun nkan yii",
    "save_actions": "Fi ifiranṣẹ pamọ",
    "notifications": {
      "success": "Ti fipamọ data titẹ sii rẹ."
    },
    "product_inputs_preview_message": "Awọn aṣayan isọdi wọnyi wa fun ọja ti o paṣẹ. Ni kete ti nkan naa ba ti ṣafikun si rira rẹ, iwọ yoo ni anfani lati ṣe awọn atunṣe nibi."
  },
  "faq": {
    "faq": "Awon ibeere ti awon eniyan saaba ma n beere",
    "title": "Awọn ibeere ati Idahun",
    "sub_title": "Ohun ti o ni ki a ṣe.",
    "message": "Wa idahun si ibeere rẹ laarin awọn idahun ni isalẹ. Beere lọwọ wa ti awọn ibeere ko ba dahun.",
    "add_question_action": "Beere Ibeere Tuntun",
    "read_more": "Ka siwaju ..",
    "load_more": "Awọn ibeere diẹ sii ..",
    "main_page": "FAQ akọkọ Page",
    "add_new": "Fi ibeere tuntun silẹ",
    "login_alert": "Wọle lati beere ibeere kan.",
    "question_input": "Ibeere",
    "question_input_placeholder": "Beere ibeere rẹ.",
    "notifications": {
      "success_add": "Ibeere rẹ silẹ ni aṣeyọri."
    }
  },
  "rating_labels": [
    "Kodara rara",
    "Buburu",
    "Deede",
    "O dara",
    "O tayọ"
  ],
  "map_view": {
    "address_detail": "Awọn alaye adirẹsi",
    "change": "Yipada",
    "select": "Yan",
    "not_found_address": "Ko si iye ti o rii",
    "enter_address_hint": "Tẹ adirẹsi ibi sii",
    "enter_your_address": "Tẹ adirẹsi rẹ sii.",
    "postal_code": "koodu ifiweranṣẹ",
    "phone_input": "Foonu {type}",
    "building_number": "Nọmba ile",
    "building_unit": "Ẹyọ",
    "full_name_input": "Orukọ kikun {type}",
    "save_detail_action": "Fi awọn alaye pamọ",
    "more_detail_input": "Apejuwe diẹ sii",
    "add_address_to_list": "Fi adirẹsi si akojọ",
    "address_title_input": "Aami adirẹsi (Beere)",
    "notifications": {
      "save_in_list": "Adirẹsi yii ti wa ni ipamọ si atokọ rẹ pẹlu gbogbo awọn alaye rẹ.",
      "edit_success": "Awọn iye adirẹsi titun ti a fipamọ sinu {title}."
    },
    "delete_address_dialog": {
      "title": "Pa Adirẹsi rẹ",
      "message": "Ṣe o da ọ loju pe o fẹ pa adirẹsi yii rẹ bi?",
      "action": "Yọ adirẹsi kuro"
    }
  },
  "comment_manager": {
    "can_not_edit": "Ko le ṣatunkọ asọye yii!",
    "comment_input_empty": "Ọrọ ifiranṣẹ ti ṣofo!",
    "article_not_saved": "Fi nkan pamọ!"
  },
  "wheel_fortune": {
    "title": "Play & Gba",
    "message": "Awọn iye owo ti kọọkan ere jẹ 10 eerun. Lọwọlọwọ o ni chips {chips}. Gba ërún diẹ sii nipa rira lati ile itaja.",
    "win_message": "Oriire, O ṣẹgun!",
    "lost_message": "Ma binu, O padanu ere naa.",
    "try_again": "O le gbiyanju lẹẹkansi"
  },
  "json": {
    "add": "Ṣafikun data igbekalẹ",
    "add_message": "Ṣẹda titun be data",
    "structures": "Awọn ẹya ara ẹrọ",
    "book": {
      "title": "Iwe",
      "desc": "Awọn iṣe iwe ti o fun awọn olumulo laaye lati ra iwe ti wọn rii taara lati awọn abajade wiwa."
    },
    "occupation": {
      "title": "Ifoju ekunwo",
      "desc": "Alaye nipa idiyele owo osu, gẹgẹbi awọn sakani owo-oya ati awọn aropin owo-oya orisun agbegbe fun awọn iru iṣẹ, ti o han ni iriri wiwa iṣẹ lori Google."
    },
    "course": {
      "title": "Dajudaju",
      "desc": "Awọn iṣẹ ikẹkọ ti o han ninu atokọ olupese kan pato. Awọn iṣẹ ikẹkọ le pẹlu akọle ikẹkọ, olupese, ati apejuwe kukuru kan."
    },
    "howto": {
      "title": "Bi o si",
      "desc": "Bi o ṣe le rin awọn olumulo nipasẹ ṣeto awọn igbesẹ kan lati ṣaṣeyọri iṣẹ-ṣiṣe kan, ti n ṣafihan fidio, awọn aworan, ati ọrọ."
    },
    "recipe": {
      "title": "Ohunelo",
      "desc": "Awọn ilana ti o ṣafihan bi abajade ọlọrọ kọọkan tabi apakan ti carousel agbalejo."
    }
  },
  "support": {
    "Financial": "Olowo",
    "Technical": "Imọ-ẹrọ",
    "Advisor": "Oludamoran"
  },
  "condition": {
    "new": "Tuntun",
    "refurbished": "Ti tunṣe",
    "used": "Lo",
    "used_fair": "Lo itẹ",
    "used_good": "Lo dara",
    "used_like_new": "Ti a lo bi tuntun"
  },
  "variant_filter": {
    "title": "Ajọ Iyatọ Ọja",
    "only_available": "O wa"
  },
  "service": {
    "task": {
      "title": "Awọn iṣẹ-ṣiṣe",
      "message": "Akojọ awọn iṣẹ ṣiṣe ti a ṣe ni iṣẹ yii."
    },
    "appointment": {
      "title": "Ipinnu",
      "message": "Yan awọn akoko ti ọsẹ lati awọn akoko atẹle ti o da lori ọjọ ati wakati ti o tọ fun ọ."
    },
    "booking": {
      "title": "Fowo si",
      "message": "Pato akoko akoko ti awọn ọjọ ti o fẹ ṣe ifiṣura ninu kalẹnda ni isalẹ."
    },
    "subscription": {
      "title": "Ṣiṣe alabapin"
    },
    "charge": {
      "title": "Gba agbara"
    }
  },
  "PricingTypes": {
    "FIX": {
      "title": "Idiyele ti o wa titi",
      "message": "Ni iru idiyele yii, idiyele ọja jẹ iye ti o wa titi ati pe ko si iwulo fun olura lati beere iṣiro idiyele kan."
    },
    "ESTIMATION": {
      "title": "Ifoju Ifilelẹ",
      "message": "Iye owo ti awọn ọja ati iṣẹ yoo ṣe iṣiro si iye diẹ nipasẹ ẹniti o ta ọja nigbati o ba paṣẹ, awọn risiti isanwo le yipada tabi ṣafikun lakoko iṣẹ naa."
    },
    "AGREEMENT": {
      "title": "Ifowoleri Adehun",
      "message": "Owo ikẹhin ti awọn ọja tabi awọn iṣẹ kii yoo yipada nipasẹ ẹniti o ta ọja lẹhin ti o ti gbe aṣẹ naa."
    },
    "BID": {
      "title": "Bid / Auction",
      "message": "Ọja naa yoo ta ni idiyele idu ti o ga julọ nipasẹ awọn olura ti o ni agbara."
    }
  },
  "map": {
    "title": "Nlo lati gba awọn ọja",
    "confirm": "Ṣeto ipo",
    "address": "Ibi-afẹde",
    "receptor": "Olugba"
  },
  "ShopBots": {
    "telegram": "Telegram"
  },
  "article_tags": {
    "title": "Akoonu Tags",
    "tags_input": "Awọn afi",
    "tags_input_message": "Tags Akojọ ti yi article",
    "notification": {
      "add_success": "Awọn afi kun"
    }
  },
  "difficulties": {
    "very_complicated": "Idiju pupọ",
    "hard": "Lile",
    "intermediate": "Agbedemeji",
    "easy": "Rọrun"
  },
  "billing_period": {
    "Daily": "Ojoojumọ",
    "Weekly": "Osẹ-ọsẹ",
    "Monthly": "Oṣooṣu",
    "Every3Months": "Ni gbogbo oṣu mẹta",
    "Every6Months": "Ni gbogbo oṣu 6",
    "Yearly": "Odoodun"
  },
  "buyer_rating_statement": {
    "between1_2": "Oh ko dara!",
    "between2_3": "O dara!",
    "between3_4": "Eniyan fẹran rẹ!",
    "between4_5": "Awọn eniyan nifẹ rẹ!"
  },
  "seasons": {
    "spring": "Orisun omi",
    "summer": "Ooru",
    "autumn": "Igba Irẹdanu Ewe",
    "winter": "Igba otutu"
  }
};