<?php 

 return [
     "accepted" => "Awọn abuda : gbọdọ jẹ gbigba.",
     "accepted_if" => "Aaye abuda gbọdọ jẹ gbigba nigbati :miran jẹ: iye.",
     "active_url" => "Ẹya-ara naa kii ṣe URL ti o wulo.",
     "after" => "Ẹya-ara naa gbọdọ jẹ ọjọ kan lẹhin: ọjọ.",
     "after_or_equal" => "Ẹya-ara naa gbọdọ jẹ ọjọ lẹhin tabi dọgba si ọjọ.",
     "alpha" => "Awọn abuda : le ni awọn lẹta nikan ninu.",
     "alpha_dash" => "Ẹya: Awọn lẹta le nikan ni awọn lẹta, awọn nọmba, ati dashes ninu.",
     "alpha_num" => "Ẹya: Awọn lẹta le nikan ni awọn lẹta ati awọn nọmba ninu.",
     "array" => "Ẹya-ara naa gbọdọ jẹ apẹrẹ.",
     "ascii" => "Aaye ẹya-ara gbọdọ ni awọn ami alphanumeric-baiti kan ṣoṣo ati awọn aami ninu.",
     "before" => "Ẹya-ara naa gbọdọ jẹ ọjọ kan ṣaaju: ọjọ.",
     "before_or_equal" => "Ẹya-ara naa gbọdọ jẹ ọjọ ṣaaju tabi dọgba si ọjọ.",
     "between" => [
     "array" => "Ẹya-ara gbọdọ ni laarin :min ati :awọn ohun ti o pọju.",
     "file" => "Ẹya-ara gbọdọ wa laarin: min ati : max kilobytes.",
     "numeric" => "Ẹya-ara gbọdọ wa laarin :min ati :max.",
     "string" => "Ẹya-ara gbọdọ wa laarin :min ati :max.",
],
     "boolean" => "Aaye abuda gbọdọ jẹ otitọ tabi eke.",
     "can" => "Aaye abuda ni iye laigba aṣẹ ninu.",
     "confirmed" => "Awọn: ìmúdájú ànímọ ko baramu.",
     "contains" => "Aaye abuda: nsọnu iye ti a beere.",
     "current_password" => "Ọrọigbaniwọle ko tọ.",
     "date" => "Awọn abuda : kii ṣe ọjọ to wulo.",
     "date_equals" => "Aaye abuda gbọdọ jẹ ọjọ ti o dọgba si ọjọ.",
     "date_format" => "Awọn abuda : ko baramu ọna kika: ọna kika.",
     "decimal" => "Aaye abuda : gbọdọ ni: awọn aaye eleemewa eleemewa.",
     "declined" => "Aaye abuda gbọdọ jẹ kọ.",
     "declined_if" => "Aaye abuda gbọdọ kọ silẹ nigbati: omiran jẹ: iye.",
     "different" => "Ẹya-ara ati : miiran gbọdọ yatọ.",
     "digits" => "Awọn abuda : gbọdọ jẹ awọn nọmba oni-nọmba.",
     "digits_between" => "Ẹya-ara gbọdọ wa laarin: min ati : awọn nọmba ti o pọju.",
     "dimensions" => "Ẹya-ara naa ni awọn iwọn aworan ti ko tọ.",
     "distinct" => "Aaye abuda: ni iye ẹda-ẹda kan.",
     "doesnt_end_with" => "Aaye abuda ko gbọdọ pari pẹlu ọkan ninu awọn atẹle: awọn iye.",
     "doesnt_start_with" => "Aaye abuda ko gbọdọ bẹrẹ pẹlu ọkan ninu awọn atẹle: awọn iye.",
     "email" => "Ẹya naa gbọdọ jẹ adirẹsi imeeli to wulo.",
     "ends_with" => "Aaye abuda gbọdọ pari pẹlu ọkan ninu awọn atẹle: awọn iye.",
     "enum" => "Iwa ti a yan ko wulo.",
     "exists" => "Iwa ti a yan ko wulo.",
     "extensions" => "Aaye abuda gbọdọ ni ọkan ninu awọn amugbooro wọnyi: awọn iye.",
     "file" => "Ẹya : gbọdọ jẹ faili kan.",
     "filled" => "Aaye abuda gbọdọ ni iye kan.",
     "gt" => [
     "array" => "Ẹya-ara gbọdọ ni diẹ ẹ sii ju: awọn ohun iye.",
     "file" => "Ẹya-ara gbọdọ jẹ tobi ju: iye kilobytes.",
     "numeric" => "Ẹya-ara gbọdọ jẹ tobi ju: iye.",
     "string" => "Ẹya-ara gbọdọ jẹ ti o tobi ju: awọn ohun kikọ iye.",
],
     "gte" => [
     "array" => "Ẹya-ara gbọdọ ni: awọn ohun iye tabi diẹ ẹ sii.",
     "file" => "Ẹya-ara gbọdọ tobi ju tabi dọgba: iye kilobytes.",
     "numeric" => "Ẹya-ara gbọdọ tobi ju tabi dọgba: iye.",
     "string" => "Ẹya-ara gbọdọ tobi ju tabi dọgba: awọn ohun kikọ iye.",
],
     "hex_color" => "Aaye abuda gbọdọ jẹ awọ hexadecimal to wulo.",
     "image" => "Awọn abuda: ẹya gbọdọ jẹ aworan kan.",
     "in" => "Iwa ti a yan ko wulo.",
     "in_array" => "Aaye abuda ko si ni:miiran.",
     "integer" => "Ẹya-ara gbọdọ jẹ odidi kan.",
     "ip" => "Awọn abuda : gbọdọ jẹ adiresi IP to wulo.",
     "ipv4" => "Ẹya-ara naa gbọdọ jẹ adiresi IPv4 to wulo.",
     "ipv6" => "Ẹya-ara naa gbọdọ jẹ adiresi IPv6 to wulo.",
     "json" => "Ẹya-ara naa gbọdọ jẹ okun JSON to wulo.",
     "list" => "Aaye abuda gbọdọ jẹ atokọ kan.",
     "lowercase" => "Aaye abuda gbọdọ jẹ kekere.",
     "lt" => [
     "array" => "Ẹya-ara gbọdọ ni kere ju: awọn ohun iye.",
     "file" => "Ẹya-ara gbọdọ jẹ kere ju: iye kilobytes.",
     "numeric" => "Ẹya-ara gbọdọ jẹ kere ju: iye.",
     "string" => "Ẹya-ara gbọdọ jẹ kere ju: awọn ohun kikọ iye.",
],
     "lte" => [
     "array" => "Ẹya-ara naa ko gbọdọ ni diẹ ẹ sii ju: awọn ohun iye.",
     "file" => "Ẹya-ara gbọdọ jẹ kere ju tabi dọgba: iye kilobytes.",
     "numeric" => "Ẹya-ara gbọdọ jẹ kere ju tabi dọgba: iye.",
     "string" => "Ẹya-ara gbọdọ jẹ kere ju tabi dọgba: awọn ohun kikọ iye.",
],
     "mac_address" => "Aaye abuda gbọdọ jẹ adiresi MAC ti o wulo.",
     "max" => [
     "array" => "Ẹya-ara naa le ma ni diẹ ẹ sii ju: awọn ohun ti o pọju lọ.",
     "file" => "Ẹya-ara le ma tobi ju: max kilobytes.",
     "numeric" => "Ẹya : le ma tobi ju: max.",
     "string" => "Awọn abuda : le ma tobi ju: max awọn lẹta.",
],
     "max_digits" => "Aaye abuda ko gbọdọ ni ju: awọn nọmba ti o pọju lọ.",
     "mimes" => "Ẹya-ara naa gbọdọ jẹ faili iru: : awọn iye.",
     "mimetypes" => "Ẹya-ara naa gbọdọ jẹ faili iru: : awọn iye.",
     "min" => [
     "array" => "Ẹya-ara gbọdọ ni o kere ju awọn nkan iṣẹju.",
     "file" => "Ẹya-ara gbọdọ jẹ o kere ju: min kilobytes.",
     "numeric" => "Ẹya-ara gbọdọ jẹ o kere ju: min.",
     "string" => "Ẹya-ara gbọdọ jẹ o kere ju awọn ami kikọ :min.",
],
     "min_digits" => "Aaye abuda gbọdọ ni o kere ju awọn nọmba :min.",
     "missing" => "Aaye abuda gbọdọ wa ni sonu.",
     "missing_if" => "Aaye abuda gbọdọ sonu nigbati :miran jẹ: iye.",
     "missing_unless" => "Aaye abuda gbọdọ sonu ayafi ti :omiran jẹ: iye.",
     "missing_with" => "Aaye abuda gbọdọ sonu nigbati: awọn iye wa.",
     "missing_with_all" => "Aaye abuda gbọdọ sonu nigbati: awọn iye wa.",
     "multiple_of" => "Aaye abuda gbọdọ jẹ ọpọ ti: iye.",
     "not_in" => "Iwa ti a yan ko wulo.",
     "not_regex" => "Ọna abuda : ko wulo.",
     "numeric" => "Ẹya-ara naa gbọdọ jẹ nọmba kan.",
     "password" => [
     "letters" => "Aaye abuda gbọdọ ni o kere ju lẹta kan ninu.",
     "mixed" => "Aaye abuda gbọdọ ni o kere ju lẹta nla kan ati lẹta kekere kan ninu.",
     "numbers" => "Aaye abuda gbọdọ ni o kere ju nọmba kan ninu.",
     "symbols" => "Aaye abuda gbọdọ ni o kere ju aami kan ninu.",
     "uncompromised" => "Iwa ti a fun ni ti han ninu jijo data kan. Jọwọ yan o yatọ: abuda.",
],
     "present" => "Aaye abuda gbọdọ wa.",
     "present_if" => "Aaye abuda gbọdọ wa nigbati :miran jẹ: iye.",
     "present_unless" => "Aaye abuda gbọdọ wa ayafi ti: omiran jẹ: iye.",
     "present_with" => "Aaye abuda gbọdọ wa nigbati: awọn iye ba wa.",
     "present_with_all" => "Aaye abuda gbọdọ wa nigba ti: awọn iye wa.",
     "prohibited" => "Aaye abuda ti ni eewọ.",
     "prohibited_if" => "Aaye abuda jẹ eewọ nigbati :miran jẹ: iye.",
     "prohibited_unless" => "Aaye abuda ti ni idinamọ ayafi ti :miran wa ninu: awọn iye.",
     "prohibits" => "Aaye abuda ti ni idinamọ: miiran lati wa.",
     "regex" => "Ọna abuda : ko wulo.",
     "required" => "Aaye abuda ni a nilo.",
     "required_array_keys" => "Aaye abuda gbọdọ ni awọn titẹ sii fun: awọn iye.",
     "required_if" => "Aaye abuda ni a nilo nigbati :miran jẹ: iye.",
     "required_if_accepted" => "Aaye abuda ni a nilo nigbati :miran ba gba.",
     "required_if_declined" => "Aaye abuda ni a nilo nigbati :miran ti kọ.",
     "required_unless" => "Aaye abuda ni a beere ayafi ti :miran wa ninu: iye.",
     "required_with" => "Aaye abuda ni a nilo nigbati: awọn iye wa.",
     "required_with_all" => "Aaye abuda ni a nilo nigbati: awọn iye wa.",
     "required_without" => "Aaye abuda ni a nilo nigbati: awọn iye ko si.",
     "required_without_all" => "Aaye abuda ni a nilo nigbati ko si ninu: awọn iye to wa.",
     "same" => "Awọn: abuda ati : miiran gbọdọ baramu.",
     "size" => [
     "array" => "Ẹya-ara gbọdọ ni: awọn ohun iwọn.",
     "file" => "Ẹya-ara gbọdọ jẹ: iwọn kilobytes.",
     "numeric" => "Ẹya naa gbọdọ jẹ: iwọn.",
     "string" => "Ẹya-ara gbọdọ jẹ: awọn ohun kikọ iwọn.",
],
     "starts_with" => "Aaye abuda gbọdọ bẹrẹ pẹlu ọkan ninu awọn atẹle: awọn iye.",
     "string" => "Awọn abuda : gbọdọ jẹ okun.",
     "timezone" => "Awọn abuda: ẹya gbọdọ jẹ agbegbe to wulo.",
     "unique" => "Awọn abuda: a ti mu tẹlẹ.",
     "uploaded" => "Awọn abuda : kuna lati gbejade.",
     "uppercase" => "Aaye abuda gbọdọ jẹ oke.",
     "url" => "Ọna abuda : ko wulo.",
     "ulid" => "Aaye abuda gbọdọ jẹ ULID to wulo.",
     "uuid" => "Aaye abuda gbọdọ jẹ UUID to wulo.",
     "custom" => [
     "attribute-name" => [
     "rule-name" => "aṣa-ifiranṣẹ",
],
     "g-recaptcha-response" => [
     "required" => "Jọwọ rii daju pe o kii ṣe roboti.",
     "captcha" => "Aṣiṣe Captcha! gbiyanju lẹẹkansi nigbamii tabi kan si alabojuto ojula.",
],
],
     "attributes" => [
        
     ],
];