<?php 

 return [
     "accepted" => "The :makhalidwe ayenera kulandiridwa.",
     "accepted_if" => "The :attribute field iyenera kulandiridwa pamene :other ndi :value.",
     "active_url" => ":attribute si ulalo wolondola.",
     "after" => ":mawonekedwe akuyenera kukhala tsiku pambuyo pa :date.",
     "after_or_equal" => ":mawonekedwe akuyenera kukhala tsiku lotsatira kapena lofanana ndi :deti.",
     "alpha" => ":attribute ikhoza kukhala ndi zilembo zokha.",
     "alpha_dash" => "The :attribute atha kukhala ndi zilembo, manambala, ndi mizere.",
     "alpha_num" => "The :attribute atha kukhala ndi zilembo ndi manambala okha.",
     "array" => ":mawonekedwe ayenera kukhala ophatikizika.",
     "ascii" => "Gawo la :attribute liyenera kukhala ndi zilembo za alphanumeric ndi zizindikiro zokha.",
     "before" => ":mawonekedwe akuyenera kukhala tsiku lisanafike :date.",
     "before_or_equal" => ":mawonekedwe akuyenera kukhala tsiku lisanafike kapena lofanana ndi :deti.",
     "between" => [
     "array" => ":mawonekedwe akuyenera kukhala pakati pa :min ndi :max zinthu.",
     "file" => ":mawonekedwe akuyenera kukhala pakati pa :min ndi :max kilobytes.",
     "numeric" => ":mawonekedwe akuyenera kukhala pakati pa :min ndi :max.",
     "string" => "The :attribute iyenera kukhala pakati pa :min ndi :max zilembo.",
],
     "boolean" => "The :attribute field iyenera kukhala yowona kapena zabodza.",
     "can" => "The :attribute field ili ndi mtengo wosaloleka.",
     "confirmed" => "The :attribute chitsimikizo sichikufanana.",
     "contains" => "Gawo la :attribute likusowa mtengo wofunikira.",
     "current_password" => "Mawu achinsinsi ndi olakwika.",
     "date" => "The :attribute si tsiku lovomerezeka.",
     "date_equals" => "The :attribute field iyenera kukhala deti lofanana ndi :deti.",
     "date_format" => "The :attribute sagwirizana ndi mtundu :format.",
     "decimal" => "The :attribute field should have :decimal decimal places.",
     "declined" => "The :mawonekedwe akuyenera kukanidwa.",
     "declined_if" => "The :attribute field iyenera kukanidwa pamene :other ndi :value.",
     "different" => ":mawonekedwe ndi :zina ziyenera kukhala zosiyana.",
     "digits" => ":mawonekedwe akuyenera kukhala : manambala a manambala.",
     "digits_between" => ":mawonekedwe akuyenera kukhala pakati pa :min ndi :max manambala.",
     "dimensions" => "The :attribute ali ndi miyeso yolakwika yazithunzi.",
     "distinct" => "The :attribute field ili ndi mtengo wobwereza.",
     "doesnt_end_with" => "The :attribute field sayenera kutha ndi chimodzi mwa izi: :values.",
     "doesnt_start_with" => "The :attribute field sayenera kuyamba ndi chimodzi mwa izi: :values.",
     "email" => "The :attribute iyenera kukhala imelo yovomerezeka.",
     "ends_with" => "The :attribute field iyenera kutha ndi chimodzi mwa izi: :values.",
     "enum" => "Chosankhidwa :mawonekedwe ndi olakwika.",
     "exists" => "Chosankhidwa :mawonekedwe ndi olakwika.",
     "extensions" => "The :attribute field iyenera kukhala ndi chimodzi mwazowonjezera izi: :values.",
     "file" => "The :attribute iyenera kukhala fayilo.",
     "filled" => "The :attribute field iyenera kukhala ndi mtengo.",
     "gt" => [
     "array" => "The :attribute ayenera kukhala ndi zambiri kuposa :value zinthu.",
     "file" => ":mawonekedwe akuyenera kukhala akulu kuposa :value kilobytes.",
     "numeric" => ":khalidwe liyenera kukhala lalikulu kuposa :value.",
     "string" => "The :attribute iyenera kukhala yayikulu kuposa :value zilembo.",
],
     "gte" => [
     "array" => "The :makhalidwe ayenera kukhala ndi :zinthu zamtengo wapatali kapena zambiri.",
     "file" => ":mawonekedwe akuyenera kukhala akulu kuposa kapena ofanana :value kilobytes.",
     "numeric" => ":khalidwe liyenera kukhala lalikulu kuposa kapena lofanana ndi :value.",
     "string" => ":mawonekedwe akuyenera kukhala akulu kuposa kapena ofanana ndi :value zilembo.",
],
     "hex_color" => "The :attribute field iyenera kukhala mtundu wovomerezeka wa hexadecimal.",
     "image" => ":mawonekedwe akuyenera kukhala chithunzi.",
     "in" => "Chosankhidwa :mawonekedwe ndi olakwika.",
     "in_array" => "The :attribute field palibe mu :zina.",
     "integer" => ":mawonekedwe akuyenera kukhala owerengeka.",
     "ip" => "The :attribute ayenera kukhala adilesi ya IP yovomerezeka.",
     "ipv4" => "The :attribute iyenera kukhala adilesi yovomerezeka ya IPv4.",
     "ipv6" => "The :attribute iyenera kukhala adilesi yovomerezeka ya IPv6.",
     "json" => "The :attribute iyenera kukhala chingwe chovomerezeka cha JSON.",
     "list" => "The :attribute field iyenera kukhala mndandanda.",
     "lowercase" => "The :attribute field iyenera kukhala yaing'ono.",
     "lt" => [
     "array" => "The :attribute iyenera kukhala ndi zochepa kuposa :value zinthu.",
     "file" => ":mawonekedwe akuyenera kukhala ochepera :value kilobytes.",
     "numeric" => ":mawonekedwe akuyenera kukhala ochepa kuposa :value.",
     "string" => "The :attribute should be less than :value characters.",
],
     "lte" => [
     "array" => "The :attribute sayenera kukhala ndi zinthu zambiri kuposa :value.",
     "file" => ":mawonekedwe akuyenera kukhala ochepera kapena ofanana :value kilobytes.",
     "numeric" => ":khalidwe liyenera kukhala lochepera kapena lofanana ndi :value.",
     "string" => ":mawonekedwe akuyenera kukhala ochepera kapena ofanana ndi :value zilembo.",
],
     "mac_address" => "The :attribute field iyenera kukhala adilesi yovomerezeka ya MAC.",
     "max" => [
     "array" => "The :attribute mwina asakhale ndi zinthu zopitilira :max.",
     "file" => "The :attribute mwina si wamkulu kuposa :max kilobytes.",
     "numeric" => ":makhalidwe sangakhale aakulu kuposa :max.",
     "string" => "The :attribute mwina sangakhale wamkulu kuposa :max zilembo.",
],
     "max_digits" => "Gawo la :attribute sikuyenera kukhala ndi manambala opitilira :max.",
     "mimes" => "The :attribute iyenera kukhala fayilo yamtundu: :values.",
     "mimetypes" => "The :attribute iyenera kukhala fayilo yamtundu: :values.",
     "min" => [
     "array" => ":mawonekedwe akuyenera kukhala ndi zinthu zosachepera :min.",
     "file" => ":mawonekedwe akuyenera kukhala osachepera :min kilobytes.",
     "numeric" => ":mawonekedwe akuyenera kukhala osachepera :min.",
     "string" => "The :attribute ayenera kukhala osachepera :min zilembo.",
],
     "min_digits" => "Gawo la :attribute liyenera kukhala ndi manambala osachepera :min.",
     "missing" => "The :attribute gawo liyenera kusowa.",
     "missing_if" => "The :attribute field iyenera kusowa pamene :other ndi :value.",
     "missing_unless" => "Gawo la :attribute liyenera kusowa pokhapokha :other ndi :value.",
     "missing_with" => "The :attribute field iyenera kusowa pamene :values ilipo.",
     "missing_with_all" => "The :attribute field iyenera kusowa pamene :values alipo.",
     "multiple_of" => "The :attribute field iyenera kukhala yochuluka ya :value.",
     "not_in" => "Chosankhidwa :mawonekedwe ndi olakwika.",
     "not_regex" => "Mtundu wa :attribute ndi wolakwika.",
     "numeric" => ":mawonekedwe akuyenera kukhala nambala.",
     "password" => [
     "letters" => "The :attribute field iyenera kukhala ndi chilembo chimodzi.",
     "mixed" => "The :attribute field iyenera kukhala ndi zilembo zazikulu imodzi ndi zing'onozing'ono.",
     "numbers" => "The :attribute field iyenera kukhala ndi nambala imodzi.",
     "symbols" => "The :attribute field iyenera kukhala ndi chizindikiro chimodzi.",
     "uncompromised" => "Zomwe zapatsidwa :attribute zawonekera pakutayikira kwa data. Chonde sankhani china :makhalidwe.",
],
     "present" => "The :attribute field iyenera kukhalapo.",
     "present_if" => "The :attribute field iyenera kukhalapo pamene :other ndi :value.",
     "present_unless" => "The :attribute field iyenera kukhalapo pokhapokha :other ndi :value.",
     "present_with" => "The :attribute field iyenera kukhalapo pamene :values ilipo.",
     "present_with_all" => "The :attribute field iyenera kukhalapo pamene :values alipo.",
     "prohibited" => "The :attribute field ndiyoletsedwa.",
     "prohibited_if" => "The :attribute field ndi yoletsedwa pamene :other ndi :value.",
     "prohibited_unless" => "The :attribute field ndiyoletsedwa pokhapokha :other ili mu :values.",
     "prohibits" => "The :attribute field imaletsa :zina kukhalapo.",
     "regex" => "Mtundu wa :attribute ndi wolakwika.",
     "required" => "The :attribute field ndiyofunika.",
     "required_array_keys" => "The :attribute field iyenera kukhala ndi zolembera za: :values.",
     "required_if" => "The :attribute field ndiyofunika pamene :other ndi :value.",
     "required_if_accepted" => "The :attribute field ikufunika pamene :zina zavomerezedwa.",
     "required_if_declined" => "The :attribute field ndiyofunika pamene :zina zikana.",
     "required_unless" => "The :attribute field ikufunika pokhapokha :other ili mu :values.",
     "required_with" => "The :attribute field ndiyofunika pamene :values ilipo.",
     "required_with_all" => "The :attribute field ndiyofunika pamene :values ilipo.",
     "required_without" => "The :attribute field ndiyofunika pamene :values palibe.",
     "required_without_all" => "The :attribute field ndiyofunika ngati palibe :values ilipo.",
     "same" => ":mawonekedwe ndi :zina ziyenera kufanana.",
     "size" => [
     "array" => ":mawonekedwe akuyenera kukhala ndi :kukula zinthu.",
     "file" => ":mawonekedwe akuyenera kukhala :size kilobytes.",
     "numeric" => ":mawonekedwe akuyenera kukhala :size.",
     "string" => "The :attribute should be :size characters.",
],
     "starts_with" => "The :attribute field iyenera kuyamba ndi chimodzi mwa izi: :values.",
     "string" => ":mawonekedwe ayenera kukhala chingwe.",
     "timezone" => ":mawonekedwe akuyenera kukhala malo oyenera.",
     "unique" => "The :attribute yatengedwa kale.",
     "uploaded" => ":attribute yalephera kukwezedwa.",
     "uppercase" => "The :attribute field iyenera kukhala yayikulu.",
     "url" => "Mtundu wa :attribute ndi wolakwika.",
     "ulid" => "The :attribute field iyenera kukhala ULID yovomerezeka.",
     "uuid" => "The :attribute field iyenera kukhala UUID yovomerezeka.",
     "custom" => [
     "attribute-name" => [
     "rule-name" => "mwambo-uthenga",
],
     "g-recaptcha-response" => [
     "required" => "Chonde tsimikizirani kuti sindinu loboti.",
     "captcha" => "Cholakwika cha Captcha! yesaninso nthawi ina kapena funsani woyang'anira webusayiti.",
],
],
     "attributes" => [
        
     ],
];