<?php 

 return [
     "invoice" => "Račun",
     "serial" => "serijski br.",
     "date" => "Datum računa",
     "seller" => "Prodavac",
     "buyer" => "Kupac",
     "address" => "adresa",
     "code" => "Kod",
     "vat" => "PDV kod",
     "phone" => "Telefon",
     "description" => "Opis",
     "units" => "Jedinice",
     "quantity" => "Kol",
     "price" => "Cijena",
     "discount" => "Popust",
     "tax" => "Porez",
     "sub_total" => "Sub Total",
     "total_discount" => "Totalni popust",
     "taxable_amount" => "Oporezivi iznos",
     "total_taxes" => "Ukupni porezi",
     "tax_rate" => "Stopa poreza",
     "total_amount" => "Ukupan iznos",
     "pay_until" => "Molimo platite do",
     "amount_in_words" => "Iznos riječima",
     "amount_in_words_format" => "%s %s i %s %s",
     "notes" => "Bilješke",
     "shipping" => "Dostava",
     "paid" => "Plaćeno",
     "due" => "Due",
];