<?php 

 return [
     "accepted" => ":atribut mora biti prihvaćen.",
     "active_url" => ":attribute nije važeći URL.",
     "after" => ":attribute mora biti datum nakon :date.",
     "after_or_equal" => ":attribute mora biti datum nakon ili jednak :date.",
     "alpha" => ":attribut može sadržavati samo slova.",
     "alpha_dash" => ":attribut može sadržavati samo slova, brojeve i crtice.",
     "alpha_num" => ":attribut može sadržavati samo slova i brojeve.",
     "array" => ":attribute mora biti niz.",
     "before" => ":attribute mora biti datum prije :date.",
     "before_or_equal" => ":attribute mora biti datum prije ili jednak :date.",
     "between" => [
     "numeric" => ":atribut mora biti između :min i :max.",
     "file" => ":attribut mora biti između :min i :max kilobajta.",
     "string" => ":attribut mora biti između :min i :max znakova.",
     "array" => ":attribut mora imati između :min i :max stavki.",
],
     "boolean" => "Polje :attribute mora biti istinito ili netočno.",
     "confirmed" => "Potvrda :attribute se ne podudara.",
     "date" => ":attribute nije važeći datum.",
     "date_format" => ":attribute ne odgovara formatu :format.",
     "different" => ":attribute i :other moraju biti različiti.",
     "digits" => ":atribut mora biti :cifre cifre.",
     "digits_between" => ":atribut mora biti između :min i :max cifara.",
     "dimensions" => ":attribute ima nevažeće dimenzije slike.",
     "distinct" => "Polje :attribute ima dupliranu vrijednost.",
     "email" => ":attribut mora biti važeća adresa e-pošte.",
     "exists" => "Odabrani :attribut je nevažeći.",
     "file" => ":attribute mora biti datoteka.",
     "filled" => "Polje :attribute mora imati vrijednost.",
     "gt" => [
     "numeric" => ":attribute mora biti veći od :value.",
     "file" => ":attribute mora biti veći od :value kilobajta.",
     "string" => ":attribute mora biti veći od :value znakova.",
     "array" => ":attribute mora imati više od :value stavki.",
],
     "gte" => [
     "numeric" => ":attribute mora biti veći ili jednak :value.",
     "file" => ":attribute mora biti veći ili jednak :value kilobajta.",
     "string" => ":attribute mora biti veći ili jednak :value znakova.",
     "array" => ":attribute mora imati :value stavke ili više.",
],
     "image" => ":attribut mora biti slika.",
     "in" => "Odabrani :attribut je nevažeći.",
     "in_array" => "Polje :attribute ne postoji u :other.",
     "integer" => ":attribut mora biti cijeli broj.",
     "ip" => ":attribute mora biti važeća IP adresa.",
     "ipv4" => ":attribute mora biti važeća IPv4 adresa.",
     "ipv6" => ":attribute mora biti važeća IPv6 adresa.",
     "json" => ":attribute mora biti važeći JSON niz.",
     "lt" => [
     "numeric" => ":attribute mora biti manji od :value.",
     "file" => ":attribute mora biti manji od :value kilobajta.",
     "string" => ":attribute mora biti manji od :value znakova.",
     "array" => ":attribute mora imati manje od :value stavki.",
],
     "lte" => [
     "numeric" => ":attribute mora biti manji ili jednak :value.",
     "file" => ":attribute mora biti manji ili jednak :value kilobajta.",
     "string" => ":attribute mora biti manji od ili jednak :value znakova.",
     "array" => ":attribute ne smije imati više od :value stavki.",
],
     "max" => [
     "numeric" => ":atribut ne smije biti veći od :max.",
     "file" => ":attribute ne smije biti veći od :max kilobajta.",
     "string" => ":attribute ne smije biti veći od :max znakova.",
     "array" => ":attribute ne smije imati više od :max stavki.",
],
     "mimes" => ":attribute mora biti datoteka tipa: :values.",
     "mimetypes" => ":attribute mora biti datoteka tipa: :values.",
     "min" => [
     "numeric" => ":atribut mora biti najmanje :min.",
     "file" => ":attribut mora biti najmanje :min kilobajta.",
     "string" => ":attribut mora imati najmanje :min znakova.",
     "array" => ":attribut mora imati najmanje :min stavke.",
],
     "not_in" => "Odabrani :attribut je nevažeći.",
     "not_regex" => "Format :attribute je nevažeći.",
     "numeric" => ":attribut mora biti broj.",
     "present" => "Polje :attribute mora biti prisutno.",
     "regex" => "Format :attribute je nevažeći.",
     "required" => "Polje :attribute je obavezno.",
     "required_if" => "Polje :attribute je obavezno kada je :other :value.",
     "required_unless" => "Polje :attribute je obavezno osim ako :other nije u :values.",
     "required_with" => "Polje :attribute je obavezno kada je :values prisutno.",
     "required_with_all" => "Polje :attribute je obavezno kada je :values prisutno.",
     "required_without" => "Polje :attribute je obavezno kada :values nije prisutno.",
     "required_without_all" => "Polje :attribute je obavezno kada nije prisutna nijedna od :vrijednosti.",
     "same" => ":attribute i :other moraju odgovarati.",
     "size" => [
     "numeric" => ":attribut mora biti :size.",
     "file" => ":attribut mora biti :size kilobajta.",
     "string" => ":attribute mora biti :size znakova.",
     "array" => ":attribute mora sadržavati :size stavke.",
],
     "string" => ":attribute mora biti string.",
     "timezone" => ":attribute mora biti važeća zona.",
     "unique" => "Atribut : je već zauzet.",
     "uploaded" => "Otpremanje :attributa nije uspjelo.",
     "url" => "Format :attribute je nevažeći.",
     "custom" => [
     "attribute-name" => [
     "rule-name" => "prilagođena poruka",
],
     "g-recaptcha-response" => [
     "required" => "Molimo potvrdite da niste robot.",
     "captcha" => "Captcha greška! pokušajte ponovo kasnije ili kontaktirajte administratora stranice.",
],
],
     "attributes" => [
        
     ],
];