<?php 

 return [
     "accepted" => "Divê taybetmendî were pejirandin.",
     "accepted_if" => "Dema ku :ya din :nirx be divê qada :taybet were qebûlkirin.",
     "active_url" => "Taybetmendî: URLek ne derbasdar e.",
     "after" => "Divê :taybet dîrokek piştî :date be.",
     "after_or_equal" => "Divê :taybet dîrokek li dû an jî wekî :date be.",
     "alpha" => "Dibe ku taybetmendî tenê tîpan hebe.",
     "alpha_dash" => "Taybetmendî: dibe ku tenê tîp, jimar û daçek hebin.",
     "alpha_num" => "Di taybetmendiyê de tenê tîp û jimar hene.",
     "array" => "Divê taybetmendî rêzek be.",
     "ascii" => "Di qada :taybetê de divê tenê tîp û sembolên alfan-hejmarî yên yek-byte hebin.",
     "before" => "Divê :taybet dîrokek berî :date be.",
     "before_or_equal" => "Divê :taybet dîrokek berî an jî wek :date be.",
     "between" => [
     "array" => "Divê taybetmendî di navbera :min û :max hêmanan de hebe.",
     "file" => "Divê taybetmendî di navbera :min û :max kilobytes de be.",
     "numeric" => "Divê taybetmendî di navbera :min û :max de be.",
     "string" => "Divê taybetmendî di navbera :min û :max tîpan de be.",
],
     "boolean" => "Divê qada :taybet rast an nerast be.",
     "can" => "Qada : taybetmendiyê nirxek nedestûrkirî dihewîne.",
     "confirmed" => "Pejirandina : taybetmendiyê li hev nayê.",
     "contains" => "Qada :taybetmendiyê nirxek pêwîst winda ye.",
     "current_password" => "Şîfre çewt e.",
     "date" => "Taybetmendî ne dîrokek derbasdar e.",
     "date_equals" => "Qada :taybet divê dîrokek bi :date be.",
     "date_format" => "Taybetmendî bi format :format re li hev nayê.",
     "decimal" => "Di qada :taybetmendiyê de divê :cihên dehiyên dehiyan hebe.",
     "declined" => "Divê qada :taybet bê redkirin.",
     "declined_if" => "Dema ku :ya din :nirx be divê qada :taybet were red kirin.",
     "different" => "Divê :taybet û :yên din cuda bin.",
     "digits" => "Divê taybetmendî :hejmar be.",
     "digits_between" => "Divê taybetmendî di navbera :min û :max reqeman de be.",
     "dimensions" => "Di : taybetmendiyê de pîvanên wêneyê nederbasdar hene.",
     "distinct" => "Qada : taybetmendiyê nirxek dubare ye.",
     "doesnt_end_with" => "Divê qada :taybetî bi yek ji van jêrîn bi dawî nebe: :nirx.",
     "doesnt_start_with" => "Divê qada :taybetî bi yek ji van jêrîn dest pê neke: :nirx.",
     "email" => "Divê taybetmendî navnîşek e-nameyek derbasdar be.",
     "ends_with" => "Qada :taybetî divê bi yek ji van jêrîn biqede: :nirx.",
     "enum" => "Taybetmendiya hilbijartî nederbasdar e.",
     "exists" => "Taybetmendiya hilbijartî nederbasdar e.",
     "extensions" => "Qada :taybetî divê yek ji van pêvekên jêrîn hebe: :nirx.",
     "file" => "Divê :taybet pelek be.",
     "filled" => "Qada :taybet divê xwedî nirxek be.",
     "gt" => [
     "array" => "Divê taybetmendî ji :nirxê zêdetir be.",
     "file" => "Divê taybetmendî ji :value kilobytes mezintir be.",
     "numeric" => "Divê taybetmendî ji :nirxê mezintir be.",
     "string" => "Divê taybetmendî ji tîpên :value mezintir be.",
],
     "gte" => [
     "array" => "Divê taybetmendî :tiştên nirx an jî zêdetir hebin.",
     "file" => "Divê taybetmendî ji :value kilobytes mezintir an wekhev be.",
     "numeric" => "Divê taybetmendî ji :nirxê mezintir an wekhev be.",
     "string" => "Divê taybetmendî ji tîpên :nirx mezintir an wekhev be.",
],
     "hex_color" => "Qada :taybetî divê rengek hexadecimal derbasdar be.",
     "image" => "Divê taybetmendî wêneyek be.",
     "in" => "Taybetmendiya hilbijartî nederbasdar e.",
     "in_array" => "Qada :taybetî di :dinê de tune.",
     "integer" => "Pêdivî ye ku :taybet jimareyek yekjimar be.",
     "ip" => "Divê taybetmendî navnîşek IP-ya derbasdar be.",
     "ipv4" => "Divê taybetmendî navnîşek IPv4 derbasdar be.",
     "ipv6" => "Divê taybetmendî navnîşek IPv6 derbasdar be.",
     "json" => "Divê : taybetmendî rêzek JSON derbasdar be.",
     "list" => "Qada :taybet divê lîsteyek be.",
     "lowercase" => "Qada :taybet divê bi tîpên piçûk be.",
     "lt" => [
     "array" => "Divê taybetmendî ji :nirxê kêmtir be.",
     "file" => "Divê taybetmendî ji :value kilobytes kêmtir be.",
     "numeric" => "Divê taybetmendî ji :nirxê kêmtir be.",
     "string" => "Divê taybetmendî ji tîpên :value kêmtir be.",
],
     "lte" => [
     "array" => "Divê taybetmendî ji :nirxê zêdetir nebe.",
     "file" => "Divê taybetmendî ji :value kilobytes kêmtir an wekhev be.",
     "numeric" => "Divê taybetmendî ji :nirxê kêmtir an wekhev be.",
     "string" => "Divê taybetmendî ji tîpên :value kêmtir an wekhev bin.",
],
     "mac_address" => "Qada : taybetmendiyê divê navnîşek MAC-a derbasdar be.",
     "max" => [
     "array" => "Dibe ku taybetmendî ji : max hêmanan zêdetir nebe.",
     "file" => "Dibe ku taybetmendî ji : max kilobytes mezintir nebe.",
     "numeric" => "Dibe ku taybetmendî ji : max mezintir nebe.",
     "string" => "Dibe ku taybetmendî ji :max tîpan mezintir nebe.",
],
     "max_digits" => "Di qada :taybetê de divê ji :max reqeman zêdetir nebe.",
     "mimes" => "Divê :taybetî pelek bi cure be: :nirx.",
     "mimetypes" => "Divê :taybetî pelek bi cure be: :nirx.",
     "min" => [
     "array" => "Divê di :taybetê de herî kêm :min hêman hebin.",
     "file" => "Divê taybetmendî herî kêm : min kilobyte be.",
     "numeric" => "Divê taybetmendî herî kêm :min be.",
     "string" => "Divê taybetmendî herî kêm : min tîpan bin.",
],
     "min_digits" => "Di qada :taybetê de divê herî kêm jimareyên :min hebin.",
     "missing" => "Divê qada :taybetî tune be.",
     "missing_if" => "Dema ku :nother :nirx be divê qada :taybetî tune be.",
     "missing_unless" => "Divê qada :taybetmendiyê winda nebe heya ku :nother ne :nirx be.",
     "missing_with" => "Dema ku :nirx hebin divê qada :taybetî tune be.",
     "missing_with_all" => "Dema ku :nirx hebin divê qada :taybetî tune be.",
     "multiple_of" => "Qada :taybet divê pirjimara :nirxê be.",
     "not_in" => "Taybetmendiya hilbijartî nederbasdar e.",
     "not_regex" => "Forma :taybet nederbasdar e.",
     "numeric" => "Divê :taybet jimareyek be.",
     "password" => [
     "letters" => "Di qada :taybetê de divê herî kêm yek herfek hebe.",
     "mixed" => "Qada :taybet divê herî kêm yek tîpek mezin û yek tîpek piçûk hebe.",
     "numbers" => "Di qada : taybetmendiyê de divê herî kêm yek hejmar hebe.",
     "symbols" => "Qada :taybet divê herî kêm sembolek hebe.",
     "uncompromised" => "Taybetmendiya diyarkirî: di lewazek daneyê de xuya bû. Ji kerema xwe celebek cûda hilbijêrin: taybetmendiyek.",
],
     "present" => "Divê qada :taybet hebe.",
     "present_if" => "Dema ku :nother :nirx be divê qada :taybet hebe.",
     "present_unless" => "Divê qada :taybetî hebe heya ku :nother :value be.",
     "present_with" => "Dema ku :nirx hebin divê qada :taybetî hebe.",
     "present_with_all" => "Dema ku :nirx hebin divê qada :taybet hebe.",
     "prohibited" => "Qada : taybetmendiyê qedexe ye.",
     "prohibited_if" => "Qada :taybetî qedexe ye dema :ya din :nirx be.",
     "prohibited_unless" => "Qada :taybet qedexe ye heya ku :yên din di :nirxan de nebe.",
     "prohibits" => "Qada :taybet hebûna :yên din qedexe dike.",
     "regex" => "Forma :taybet nederbasdar e.",
     "required" => "Qada : taybetmendiyê pêwîst e.",
     "required_array_keys" => "Di qada : taybetmendiyê de divê navnîşên ji bo: :nirxan hebe.",
     "required_if" => "Zeviya :taybetmendiyê pêwîst e dema ku :yên din :nirx be.",
     "required_if_accepted" => "Dema ku :yên din were pejirandin qada :taybetî pêwîst e.",
     "required_if_declined" => "Dema ku :yên din bê redkirin qada :taybetî pêwîst e.",
     "required_unless" => "Zeviya :taybetî hewce ye heya ku :yên din di :nirxan de nebe.",
     "required_with" => "Dema ku :nirx hebin qada :taybetî pêwîst e.",
     "required_with_all" => "Dema ku :nirx hebin qada :taybetî pêwîst e.",
     "required_without" => "Dema ku :nirx tune be qada :taybetî pêwîst e.",
     "required_without_all" => "Dema ku yek ji :nirxan tune be qada :taybetî hewce ye.",
     "same" => "Divê :taybet û :yên din li hev bikin.",
     "size" => [
     "array" => "Divê di :taybetê de hêmanên :size hebin.",
     "file" => "Divê taybetmendî :size kilobytes be.",
     "numeric" => "Divê taybetmendî :size be.",
     "string" => "Divê taybetmendî bi tîpên :size bin.",
],
     "starts_with" => "Qada :taybetî divê bi yek ji van jêrîn dest pê bike: :nirx.",
     "string" => "Divê taybetmendî rêzek be.",
     "timezone" => "Divê taybetmendî herêmek derbasdar be.",
     "unique" => "Jixwe :taybet hatiye girtin.",
     "uploaded" => "Barkirin :taybet bi ser neket.",
     "uppercase" => "Divê qada :taybetî bi tîpên mezin be.",
     "url" => "Forma :taybet nederbasdar e.",
     "ulid" => "Qada :taybet divê ULIDek derbasdar be.",
     "uuid" => "Divê qada :taybetî UUID-ya derbasdar be.",
     "custom" => [
     "attribute-name" => [
     "rule-name" => "custom-peyam",
],
     "g-recaptcha-response" => [
     "required" => "Ji kerema xwe verast bikin ku hûn ne robot in.",
     "captcha" => "Çewtiya Captcha! paşê dîsa biceribînin an bi rêvebirê malperê re têkilî daynin.",
],
],
     "attributes" => [
        
     ],
];