<?php 

 return [
     "profile" => "Bala lintlha tsa profaele ho kenyelletsa lebitso, aterese ea lengolo-tsoibila, setšoantšo le boemo ba netefatso.",
     "phone" => "Fumana nomoro ea mohala",
     "address" => "Bala 'me u fetole aterese ho tsoa bukeng ea liaterese e bolokiloeng",
     "buy" => "Odara & odara mabenkeleng.",
     "order-history" => "Bala nalane ea odara.",
     "my-gift-cards" => "Access to my cards.",
     "articles" => "Fetola Lingoloa.",
     "notifications" => "Romela le ho amohela ditsebiso.",
     "read-shops" => "Bala List Store.",
     "shop-edit" => "Boloka mokhoa oa ho fetola.",
     "shop-contacts" => "Fumana le ho lokisa liforomo tsa mabitso.",
     "shop-gift-cards" => "Ho theha, ho hlophisa, le ho laola likarete.",
     "shop-faqs" => "Etsa, fetola, le ho laola lipotso tse botsoang khafetsa.",
     "shop-categories" => "Ho theha, ho hlophisa le ho laola lihlopha.",
     "shop-products" => "Ho theha, ho hlophisa le ho laola lihlahisoa.",
     "shop-read-reports" => "Bala lintlha le litlaleho.",
     "shop-socials" => "Fetola marang-rang a lebenkeleng.",
     "shop-accounts" => "Fetola le ho hlakola liakhaonto tsa lichelete tse amanang le lebenkele.",
     "shop-menus" => "Fetola menyetla ea mabenkele.",
     "shop-pages" => "Fetola maqephe a lebenkele.",
     "shop-warehouse" => "Fetola Warehouse ea Lebenkele",
     "shop-permissions" => "Sheba le ho lokisa mokhoa oa ho kena lebenkeleng.",
     "shop-process-center" => "Laola litaelo tse amohetsoeng.",
     "shop-profile" => "Laola boemo ba lebenkele.",
     "shop-discount-code" => "Laola dikhoutu tsa theolelo.",
     "shop-coupon" => "Laola li-coupons.",
     "shop-offer" => "Laola litlhahiso.",
     "shop-lottery" => "Laola lilotho.",
     "shop-community" => "Laola sechaba.",
];