<?php 

 return [
     "invoice" => "Számla",
     "serial" => "Sorszám.",
     "date" => "Számla kiállítási dátuma",
     "seller" => "Eladó",
     "buyer" => "Vevő",
     "address" => "cím",
     "code" => "Kód",
     "vat" => "ÁFA kód",
     "phone" => "Telefon",
     "description" => "Leírás",
     "units" => "Egységek",
     "quantity" => "Menny",
     "price" => "ár",
     "discount" => "Kedvezmény",
     "tax" => "Adó",
     "sub_total" => "Részösszeg",
     "total_discount" => "Teljes kedvezmény",
     "taxable_amount" => "Adóköteles összeg",
     "total_taxes" => "Összes adó",
     "tax_rate" => "Adókulcs",
     "total_amount" => "Teljes összeg",
     "pay_until" => "Kérjük, fizessen ig",
     "amount_in_words" => "Mennyiség szavakban",
     "amount_in_words_format" => "%s %s és %s %s",
     "notes" => "Megjegyzések",
     "shipping" => "Szállítás",
     "paid" => "Fizetett",
     "due" => "Esedékes",
];