<?php 

 return [
     "home" => "selldone",
     "blogs" => "Blog",
     "helps" => "Help",
     "current_location" => "Kupinda uku",
     "dashboard" => "dashboard",
     "my_shops" => "Zvitoro Zvangu",
     "wallet" => "wallet",
     "about" => "Nezve Selldone",
     "contact" => "contact us",
     "comments" => "comments",
     "likes" => "Likes",
     "power" => "cheer",
     "build_free_shop" => "Vaka chitoro chako mahara",
     "shop_name" => "shop name",
     "categories" => "categories",
     "sub_articles" => "More",
     "terms" => "Terms",
     "colour" => "color",
     "style" => "style",
     "volume" => "volume",
     "weight" => "weight",
     "pack" => "Pack",
     "type" => "type",
     "add_to_card" => "Wedzera kuCart",
     "overview" => "Overview",
     "reviews" => "Ongororo",
     "spec" => "Full spec",
     "you_may_also_like" => "Unogonawo kuda",
     "about_us" => "Nezvedu",
     "contact_us" => "contact us",
     "cookie_privacy" => "Cookie &amp; privacy policy",
     "follow_us" => "titeverei",
     "category" => "Category",
     "author" => "Written by ",
     "published_at" => "Rakadhindwa pa",
     "modified_at" => "Modified at",
     "price" => "mutengo",
     "discount" => "Discount",
     "price_after_discount" => "Mutengo mushure mekuderedzwa",
     "available" => "Inowanikwa",
     "sold_out" => "Zvapera",
     "buy" => "Tenga izvozvi",
     "login_shop" => "Login Shop",
     "posted_on" => "Yakatumirwa pa:date",
];