<?php 

 return [
     "email-types-description" => [
     "shop-customer-join" => "Fáiltíonn an teachtaireacht seo roimh cheannaitheoir nua chuig an siopa.",
     "order-checkout" => "Seoltar an fógra seo nuair a dheimhníonn ceannaitheoir ordú.",
     "order-payment" => "Deimhníonn an fógra seo an íocaíocht rathúil a rinne custaiméir.",
     "order-payment-admin" => "Seoltar an teachtaireacht seo chuig díoltóir chun ordú deimhnithe a chur in iúl dó.",
     "pos-checkout" => "Seoltar an fógra seo chun ordú díolphointe a dheimhniú do cheannaitheoir.",
     "pos-payment" => "Deimhníonn an fógra seo íocaíocht pointe díola a rinne ceannaitheoir.",
     "pos-payment-admin" => "Cuireann an teachtaireacht seo an díoltóir ar an eolas faoi cheannachán a rinneadh ag an díolphointe.",
     "shop-contact" => "Seoltar an fógra seo nuair a chuirtear foirm teagmhála isteach.",
     "shop-giftcard" => "Cuireann an fógra seo in iúl d'úsáideoir go bhfuil cárta bronntanais faighte aige.",
     "shop-vendor-join" => "Fáiltíonn an teachtaireacht seo roimh dhíoltóir nua chuig an siopa.",
     "shop-vendor-invite" => "Seoltar an teachtaireacht seo chun cuireadh a thabhairt do dhíoltóir dul isteach i do mhargadh.",
     "shop-vendor-order" => "Seoltar an teachtaireacht seo chuig an díoltóir nuair a fhaightear ordú i stádas Íoctha nó Airgead Tirim ar Sheachadadh (COD).",
     "shop-vendor-products" => "Seolta go laethúil chun díoltóirí a nuashonrú ar stádas a gcuid táirgí.",
     "shop-login" => "Fógra a thabhairt don úsáideoir le sonraí logáil isteach, lena n-áirítear seoladh IP, dáta, agus gléas, chun críocha slándála.",
     "login-code" => "Seol cód pasfhocal aonuaire le go bhféadfaidh úsáideoirí logáil isteach sa siopa.",
     "shop-email-verify-link" => "Seol nasc chun seoladh ríomhphoist an úsáideora a fhíorú. Seoltar an ríomhphost seo nuair a chláraíonn úsáideoir trí SMS agus nuair a chuireann siad a ríomhphost isteach agus ní sheoltar é nuair a chláraíonn úsáideoir trí ríomhphost nó trí ríomhphost go díreach.",
],
     "global" => [
     "greetings" => "Hi : ainm",
     "end-statement" => "Foireann tacaíochta",
     "receiver_name" => "Hi :user_name",
     "footer-help" => "Teastaionn Cabhair? Fiafraigh ag [support@selldone.com](mailto:support@selldone.com) nó tabhair cuairt ar ár [ionad cabhrach]( https://selldone.com/help)",
     "footer-shop" => "Má tá cabhair uait le rud ar bith ná bíodh drogall ort ríomhphost a chur chugainn: :shop_mail",
     "accept" => "Glac",
     "reject" => "Diúltaigh",
     "verify" => "fhíorú",
     "title" => "Teideal",
     "value" => "Luach",
     "description" => "Cur síos",
     "Shop" => "Siopa",
     "user" => "úsáideoir",
     "license" => "Ceadúnas",
     "status" => "Stádas",
     "start" => "Tosaigh",
     "end" => "Deireadh",
     "renewal" => "Athnuachan",
     "view" => "Amharc",
     "balance" => "Iarmhéid",
     "card_number" => "Uimhir chárta",
     "cvv" => "cvv",
     "expire_date" => "Dáta éaga",
     "dashboard" => "deais",
     "order" => "ordú",
     "view_order" => "Féach ar ordú",
     "pay_now" => "Pay now",
     "official_selldone" => "DÍOLTA OIFIGIÚIL",
     "account-number" => "Account number",
     "account-name" => "Account name",
     "currency" => "Airgeadra",
     "free-balance" => "Iarmhéid saor in aisce,",
     "locked-balance" => "Iarmhéid faoi ghlas",
     "bot" => "Bot",
     "requests" => "Iarratais",
     "baskets" => "cairteacha",
     "physical" => "Fisiciúil",
     "virtual" => "Fíorúil",
     "file" => "Comhad",
     "service" => "Seirbhís",
     "fulfillment" => "Comhlíonadh",
     "open" => "Oscail",
     "reserved" => "Curtha in áirithe",
     "canceled" => "Ar ceal",
     "payed" => "Íoctha",
     "cod" => "COD",
     "orders-count" => "Orduithe",
     "payments-count" => "Íocaíochtaí",
     "confirms-count" => "Deimhníonn",
     "sends-count" => "Seolann",
     "delivers-count" => "Seachadann",
     "count" => "Áireamh",
     "transactions-count" => "Idirbhearta chomhaireamh",
     "success-transactions" => "Idirbhearta ratha",
     "total-amount" => "Iomlán",
     "amount" => "Méid",
     "wage" => "Pá",
     "debug" => "Dífhabhtaithe",
     "pos" => "POS",
     "live" => "Beo",
     "CheckQueue" => "Seiceáil scuaine",
     "OrderConfirm" => "Ordú a dheimhniú",
     "PreparingOrder" => "Ordú a ullmhú",
     "SentOrder" => "Ordú seolta",
     "ToCustomer" => "Seachadadh chuig an gcustaiméir",
     "Pending" => "Ar feitheamh",
     "Accepted" => "Glactar leis",
     "Rejected" => "Diúltaithe",
     "pc" => "PC",
     "tablet" => "Táibléad",
     "phone" => "Fón",
     "total" => "Iomlán",
     "view-detail" => "Féach ar Sonraigh",
     "empty" => "Folamh",
     "dropshipping" => "Dropshipping",
     "reply" => "Freagra",
     "reactions" => "Imoibrithe",
     "comments" => "tuairimí",
     "last-comment" => "Trácht deiridh",
     "response-to" => "Freagra ar",
     "posts" => "Poist",
     "post" => "Post",
     "name" => "Ainm",
     "email" => "Ríomhphost",
     "type" => "cineál",
     "device" => "Gléas",
     "platform" => "Ardán",
     "browser" => "Brabhsálaí",
     "time" => "Am",
     "wallet" => "sparán",
     "date" => "Dáta",
     "account" => "Cuntas",
     "transaction" => "Idirbheart",
     "fee" => "Táille",
     "location" => "Location",
     "ip" => "IP",
     "bill" => "Bille",
     "category" => "Catagóir",
     "password" => "Pasfhocal",
     "shop" => "Siopa",
     "verify-login" => "Fíoraigh & Logáil Isteach",
     "url" => "URL",
     "avocado" => "Avocado",
     "hyper" => "Hyper",
     "buy-now" => "Ceannaigh Anois",
     "add-domain" => "Add Domain",
     "views" => "Radhairc",
     "country" => "Tír",
     "address" => "seoladh",
     "postal" => "Cód Poist",
     "building_no" => "Foirgneamh #",
     "building_unit" => "Aonad #",
     "message" => "Teachtaireacht",
     "customer" => "Custaiméir",
     "cart-items" => "Míreanna cart",
     "payment" => "Íocaíocht",
     "receiver" => "Glacadóir",
     "virtual-items" => "Míreanna fíorúil",
     "no-payment" => "Gan íocaíocht!",
     "enable" => "Cumasaigh",
     "access" => "Rochtain",
     "bank" => "Eolas bainc",
     "vendor" => "Díoltóir",
     "view_content" => "Féach ar an ábhar iomlán",
     "files" => "Comhaid",
     "download" => "Íosluchtaigh",
     "file_name" => "Ainm an Chomhaid",
     "file_size" => "Méid",
     "subscription" => "Sintiús",
     "products" => "Táirgí",
     "vendor_products" => "Táirgí Díoltóra",
],
     "selldone-business-os" => "OS Gnó Soldone",
     "senders" => [
     "WeeklyReport" => [
     "id" => "performance",
     "name" => "Tuarascáil Feidhmíochta, Díolta",
],
     "SeasonalReport" => [
     "id" => "seasonal",
     "name" => "Tuairisc Séasúrach, Díolta",
],
     "Onboarding" => [
     "id" => "Haigh",
     "name" => "Ceadaigh, Selldone",
],
     "Support" => [
     "id" => "support",
     "name" => "Tacaíocht: ainm",
],
     "EmailVerify" => [
     "id" => "verify",
     "name" => "Fíoraigh, Díolta",
],
     "Welcome" => [
     "id" => "Haigh",
     "name" => "Pobal, Selldone",
],
     "NewShop" => [
     "id" => "ceannaithe",
     "name" => "Ceadaigh, Selldone",
],
     "Approve" => [
     "id" => "cheadú",
     "name" => "Ceadaigh, Selldone",
],
     "SellerReceiveOrder" => [
     "id" => "order",
     "name" => "Bainistíocht Orduithe : ainm",
],
     "Recovery" => [
     "id" => "téarnamh",
     "name" => "Foireann Aisghabhála Selldone",
],
],
     "bill-status" => [
     "PENDING" => "Ar feitheamh ⌛",
     "PAYED" => "Íoctha ✅",
     "CANCELED" => "Ar ceal ❌",
],
     "shop-invite" => [
     "LEVEL-NAME" => [
     "ADMIN" => "Riarthóir",
     "OFFICER" => "Oifigeach agus Maoirseoir",
     "AUDITING" => "Bainisteoir iniúchta",
     "EMPLOYEE" => "Fostaí",
     "PRODUCT" => "Bainisteoir táirgí",
     "CONTENT" => "Bainisteoir ábhar",
     "MARKETING" => "Bainisteoir Margaíochta",
     "VIEWER" => "Amharcóir",
],
     "subject" => ":inviter Tabhair cuireadh duit mar :level | :siopa",
     "category" => "Cuireadh foirne",
     "title" => "Tugadh cuireadh duit chuig <b>: shop_name</b> mar <b>:level</b> .",
     "message" => "Tá cuireadh seolta chugat. Is féidir leat é a dhearbhú nó a dhiúltú. Má cheadaíonn tú an cuireadh seo, ní mór duit dul isteach sa tseirbhís Sellone chun é a dhearbhú. Tríd an gcuireadh seo a dheimhniú, beidh rochtain agat ar an rannán bainistíochta stórais.",
],
     "welcome-email" => [
     "subject" => "👋 Fáilte :name, Roinnt rudaí suimiúla duitse.",
     "category" => "CONGRATULATION",
     "title" => "FÁILTE CHUIG DÍOLTA",
     "message" => "Go raibh maith agat as Selldone a roghnú, Tá tú anois mar chuid de phobal Soldone a nascann díoltóirí domhanda le custaiméirí, Gnó áitiúil le fiontar, Duine aonair don chorparáid! Tá gach uirlis máistir agus pro curtha ar fáil **saor in aisce** agus **gan teorainn** duit. Déanann tú iarracht, osclaíonn muid na doirse, Just Déan é!",
     "seller" => [
     "title" => "An díoltóir tú?",
     "message" => "Chun tosú ag díol, cuir isteach do dheais i Soldone tríd an nasc thíos agus cruthaigh do chéad siopa go hiomlán saor in aisce. Tógfaidh sé seo cúpla nóiméad agus beidh do stór féin agus do shuíomh ar líne agat. Déanfaimid tú a threorú ansin chuig na chéad chéimeanna eile agus gheobhaidh tú an geata íocaíochta.",
     "action" => "Logáil isteach ar mo dheais",
],
     "buyer" => [
     "title" => "Is ceannaitheoir mé",
     "message" => "Comhghairdeachas. Nuair a bheidh tú i do bhall de Soldone, gheobhaidh tú réidh leis na hassles ballraíochta agus fíordheimhnithe i siopaí ar líne. Chun leas a bhaint as aon siopa agus láithreán a úsáideann an t-ardán Selldone, is féidir leat logáil isteach le cliceáil amháin agus do cheannach a dhéanamh simplí, tapa agus sábháilte.",
],
],
     "charge-account" => [
     "category" => "Sparán > Cuntas > Muirear",
     "title" => "Muirear Ratha",
     "message" => "D'éirigh le do chuntas <b>:count_number</b> <b>:méid</b> a gearradh.",
     "account" => "Cuntas",
     "charge" => "Muirear",
     "balance" => "Iarmhéid",
     "footer" => "Déan gnó éasca, indéanta, agus inrochtana do dhuine ar bith ar fud an domhain.",
],
     "verify-email" => [
     "subject" => "🙌 Críochnaigh do chlárú le Selldone! Fíoraigh nasc.",
     "category" => "TÁ TÚ CÉIM AMHÁIN ACH",
     "title" => "Fíoraigh do sheoladh ríomhphoist",
     "message" => "Hi : ainm,<br> Go raibh maith agat as Selldone a roghnú.<br> Deimhnigh le do thoil gurb é **:ríomhphost** do sheoladh ríomhphoist trí chliceáil ar an gcnaipe nó úsáid an nasc thíos laistigh de 48 uair an chloig.",
     "footer" => "Má tá deacracht agat an cnaipe Fíoraigh a chliceáil, cóipeáil agus greamaigh an URL thíos isteach i do bhrabhsálaí gréasáin: __:activation_url__",
],
     "verify-email-code" => [
     "subject" => "Cód fíoraithe le haghaidh :name",
     "category" => "SECURITY",
     "title" => "Cód fíoraithe ríomhphoist",
     "message" => "Hi : ainm,<br><br> Deimhnigh le do thoil gurb é **:ríomhphost** do sheoladh r-phoist leis an gcód seo laistigh de 10 nóiméad.",
],
     "onboarding-verify-email" => [
     "subject" => "🎉 Tá do Shiopa Réidh | :ainm",
     "category" => "TÁ TÚ CÉIM AMHÁIN ACH",
     "title" => "Socrú críochnaithe",
     "account_title" => "Do chuntas",
     "account_msg" => "Fíoraigh agus logáil isteach ar do chuntas leis an bhfaisnéis seo.",
     "shop_msg" => "Faisnéis chuntais ar chóras oibriúcháin gnó Sellone.",
],
     "reset2fa" => [
     "category" => "TEACHTAIREACHT OIFIGIÚIL SLÁNDÁLA",
     "title" => "Iarratas a dhíchumasú logáil isteach 2-chéim",
     "message" => "Tá an ríomhphost seo á fháil agat toisc go bhfuaireamar iarratas athshocraithe fíordheimhnithe 2 fhachtóir do do chuntas.<br><br> Ríomhphost úsáideora: <b>: email</b><br> ainm: <b>:name</b>",
     "footer" => "Murar iarr tú athshocrú pasfhocail, níl aon ghníomh eile ag teastáil.",
     "action" => "Díchumasaigh logáil isteach dhá chéim",
],
     "build-new-shop" => [
     "subject" => "🎊 Tá do shiopa réidh anois!",
     "category" => "SIOPA AR LÍNE NUA RINNEADH SA DOMHAN",
     "title" => "Ag ceiliúradh",
     "message" => "<b>Comhghairdeachas :name, tá gnó nua ar líne cruthaithe agat;</b> Guímid gach rath ort i do ghnó. Fáilte go pobal Selldoners.<br> Déanann tú iarracht, osclaíonn muid na doirse, agus rinne Tú é.",
     "pdf-book" => "Ná caill an lámhleabhar ceangailte: Déan Do Ghnó Mar Chluiche",
     "account" => [
     "title" => "Céim 1: Cruthaigh cuntas sa sparán Selldone",
     "message" => "Mura bhfuil cuntas agat i do sparán, cruthaigh ceann. Asbhaineann Selldone an táille as an gcuntas seo. Is féidir leat breisiú a dhéanamh ar an gcuntas seo, agus gearrfaidh Selldone méid creidmheasa ort freisin ionas má tá an cuntas seo diúltach, leanfaidh do shuíomh agus Store ag feidhmiú.",
     "action" => "Logáil isteach sa sparán",
],
     "shop-account" => [
     "title" => "Céim 2: ceangal an cuntas chuig an siopa",
     "message" => "Cuir do chuntas sparán le do stór. Chun é seo a dhéanamh, cuir isteach Store > Cuntasaíocht > Sonrasc agus ceangail an cuntas leis an siopa. Tabhair faoi deara go ndéantar íocaíochtaí do chustaiméirí go léir a thaisceadh go díreach isteach i do chuntas bainc agus nach n-aistarraingítear nó nach n-asbhaineann Selldone aon mhéid, mar sin ní mór duit an cuntas seo de Selldone a nascadh leis an siopa.",
     "action" => "Painéal Sonrasc Store",
],
     "gateway" => [
     "title" => "Céim 3: Ceangail Geata Íocaíochta Ar Líne",
     "message" => "Téigh go dtí Store> Cuntasaíocht> Port agus brúigh <b>Cuir Port Nua</b> leis. Tar éis duit an t-airgeadra a roghnú, taispeánfar duit liosta de na calafoirt iniompartha. Tá sé an-simplí agus tapa an calafort a nascadh i Soldone, ach má tá Niza agat le haghaidh treorach, déan tagairt don alt treorach Selldone nó cuir ceist orainn.",
     "action" => "Cuir tairseach leis an siopa",
],
     "domain" => [
     "title" => "An chéim dheireanach: fearann tiomnaithe a nascadh",
     "message" => "Beidh tú in ann do stór a bheith agat ar an oiread fearainn agus is mian leat. Chun fearann tiomnaithe a nascadh le siopa, ní mór ceadúnas tosaithe ar a laghad a bheith agat. Trí gach cara a thabhairt isteach chuig Soldone, gheobhaidh tú cárta bronntanais ceadúnais tosaithe aon mhí amháin. Cuirfear céatadán d’íocaíochtaí do chairde chun sochair do chuntais do chustaiméirí freisin.",
     "action" => "Cártaí bronntanais gan teorainn a thabhairt isteach agus a fháil",
],
],
     "basket-list" => [
     "item" => "mír",
     "count" => "Áireamh",
     "price" => "praghas",
     "discount-code" => "Cód Lascaine",
     "customer-club" => "Club Custaiméirí",
     "shipping" => "Á sheoladh",
     "total" => "Iomlán",
     "offer" => "Tairiscint",
     "coupon" => "Cúpón",
     "lottery" => "Gradam",
     "tax" => "Cáin",
     "tax_included" => "San áireamh sa phraghas",
     "tax_shipping" => "Shipping Tax",
],
     "buyable-payments" => [
     "method" => "Modh",
     "amount" => "Méid",
     "giftcard" => "Gift card",
     "payment" => "Íocaíocht",
],
     "shop-subscription-email" => [
     "category" => "Nuashonrú síntiús",
     "title" => "Ceadúnas Stórais: : shop_title",
     "title-reserved" => "Ceadúnas áirithinte: : shop_title",
     "title-active" => "Ceadúnas gníomhach: : shop_title",
     "title-finished" => "Ceadúnas críochnaithe: : shop_title",
     "title-cancel" => "Cealaigh ceadúnas: : shop_title",
     "message" => "Nuashonraíodh do phlean ceadúnais siopa,",
     "RESERVED" => "⚡ Tá do phlean síntiús ** curtha in áirithe**.",
     "ACTIVE" => "🟢 Tá do phlean síntiús curtha i ngníomh ****.",
     "FINISHED" => "🚧 Tá do phlean síntiús **críochnaithe**.",
     "CANCEL" => "⛔ Tá do phlean síntiús ** ar ceal**.",
],
     "support" => [
     "subject" => "Ionad tacaíochta | :ainm fhreagair",
     "category" => "Ionad tacaíochta",
     "title" => "Fuair tú freagra",
     "action" => "Oscail riarachán siopa",
],
     "shop-customer-join" => [
     "subject" => "Glac páirt : shop_title",
     "category" => "Ceiliúradh custaiméara nua",
     "title" => "Tá áthas orainn as do bhallraíocht",
     "action" => "Tabhair cuairt anois",
],
     "shop-vendor-join" => [
     "subject" => "Bordáil Díoltóra | : siopa_teideal",
     "category" => "Ceiliúradh díoltóir nua",
     "title" => "Tá áthas orainn as do bhallraíocht",
     "action" => "Vendor Panel",
],
     "shop-giftcard" => [
     "subject" => "Cárta bronntanais : shop_title",
     "category" => "Cuir cárta nua leis",
     "title" => "Comhghairdeas, tá cárta bronntanais faighte agat",
     "action" => "Siopa anois",
     "message" => "Tá cárta bronntanais faighte agat sa mhéid :iarmhéid :airgeadra. Beidh tú in ann ceannach ónár siopa leis an gcárta bronntanais seo.",
],
     "contact" => [
     "subject" => "Ionad tacaíochta | :siopa",
     "category" => "tacaíocht",
     "title" => "Fuair tú freagra",
],
     "order-checkout" => [
     "subject" => "🛍 Seiceáil Amach a Ordú | : ordú_id",
     "title" => "ordú",
     "message" => "Deimhnigh d'ordú,<br> Tá d'ordú faighte againn. Seolfaimid ríomhphost eile chugat nuair a sheolfar d'ordú.",
     "payments" => "Íocaíochtaí",
],
     "order-payment" => [
     "subject" => "🛍 Deimhniú Íocaíochta | : ordú_id",
     "title" => "Ordú íocaíochta",
     "message" => "D'íocaíocht críochnaithe,<br> Tá d'ordú faighte againn. Seolfaimid ríomhphost eile chugat nuair a sheolfar d'ordú.",
     "payments" => "Íocaíochtaí",
],
     "get-voucher" => [
     "subject" => "Comhghairdeachas :name | Dearbhán nua: :title",
     "category" => "COMHGHAIRDEAS, Dearbhán NUA",
     "message" => "Faigheann tú dearbhán nua, Seo bronntanas uainn duit. Is féidir leat níos mó a fháil ó na dearbháin seo trí Selldone a chur in aithne do chairde agus do gach duine a bhfuil aithne agat air. Is fiú **:praghas :airgeadra** an dearbhán seo.<br> Déanann tú iarracht, osclaíonn tú na doirse, Comhghairdeachas, Díghlasáil gnéithe le do dhearbhán!",
     "action" => "Mo phainéal",
],
     "received-gift" => [
     "subject" => "Comhghairdeachas leat, a chara :name | Tá bronntanas faighte agat",
     "category" => "Fógra go bhfuarthas bronntanas",
     "title" => "Bronntanais ar do shon",
     "message" => "Tá bronntanas nua faighte agat. Seo bronntanas ó Selldone. Is féidir leat níos mó de na bronntanais seo a fháil trí bheith níos gníomhaí i Selldone agus do stór a fhorbairt agus do leibhéal speisialtóireachta a ardú. Is é luach an Bhronntanais seo ná **:praghas :airgeadra** ar féidir leat a thaisceadh go díreach isteach i do sparán agus tú ag díol airgid.<br><br> Bain úsáid as an bronntanas seo chun do cheadúnas siopa a uasghrádú agus úsáid níos mó uirlisí i do ghnó ar líne.",
     "action" => "Bronntanais",
],
     "order-payment-admin" => [
     "subject" => "🛍 Ordú Nua Faighte | : ordú_id",
     "title" => "New Order",
     "message" => "Tá ordú nua faighte agat. Téigh go dtí an leathanach próiseála orduithe i do stór.",
],
     "virtual-item" => [
     "input-form-title" => "Do Fhaisnéis Líonta",
     "output-form-title" => "Ceannaíodh faisnéis faoi mhíreanna",
],
     "selldone-weekly-report" => [
     "subject" => "📬 : siopa_teideal | Tuairisc na Seachtaine :time",
     "title" => "Tuarascáil sheachtainiúil ar fheidhmíocht an tsiopa",
     "message" => "Seo é tuairisc sheachtainiúil do shiopa ó :tús go :deireadh. Áirítear sa tuarascáil seo leideanna chun do ghnó a fheabhsú, is féidir leat stádas do shiopa ar líne agus orduithe le déanaí a sheiceáil freisin. Tá súil agam go mbeidh lá agus seachtain mhaith agaibh amach romhainn.",
],
     "shop-seasonal-report" => [
     "subject" => "☘ Do :thuarascáil choigiltis le trí mhí anuas | : siopa_teideal",
     "title" => "Tuairisc shéasúrach faoi do ghníomhaíocht gnó, luaíochtaí agus coigilteas airgeadais",
     "message" => "Seo í do thuairisc shéasúrach :shop_title ó :tús go :deireadh.",
],
     "EC-ShopAccounts" => [
     "title" => "Cuntais nasctha",
     "sub-title" => "Cad é an stádas is déanaí de na cuntais sparán a bhaineann le mo stór?",
     "view-wallet" => "Féach ar an sparán",
     "tip-title" => "Leideanna tábhachtacha",
     "tip" => "Sa chéad chéim eile, cruthaigh cuntas saor in aisce i do sparán Selldone agus ceangail leis an siopa seo é. Fiú má tá iarmhéid do chuntais Soldone diúltach, is féidir le do chustaiméirí ceannacháin agus íocaíochtaí a dhéanamh ar do stór gan aon fhadhbanna. Ní chuirfear isteach ar do shonraí agus seirbhís ná ní chuirfear srian orthu ar feadh 1 mhí ar a laghad.",
     "view-my-wallet" => "My wallet",
     "connect-account" => "Ceangail leis an gcuntas",
],
     "EC-ShopApps" => [
     "title" => "Apps suiteáilte",
     "sub-title" => "Liosta de na haipeanna atá suiteáilte agat i do shiopa an tseachtain seo.",
     "tip" => "Ar mhaith leat níos mó aipeanna a aimsiú do do shiopa?",
     "view-app-store" => "Tabhair cuairt ar an App Store Soldone..",
],
     "EC-ShopBots" => [
     "title" => "Do Store Róbónna",
     "sub-title" => "Róbónna díolacháin gníomhacha i mo stór.",
     "tip-title" => "Díolachán Bot",
     "tip" => "Chuir Soldone róbónna díolacháin uathoibríocha ar fáil duit. Níl le déanamh agat ach dul chuig an bpainéal Breiseáin> Róbónna agus do stór-róbónna a ghníomhachtú. Tabhair faoi deara go gcaithfidh an tseirbhís ábhartha a bheith ar fáil i do thír féin.",
     "view-bots" => "Bainistigh róbónna",
],
     "EC-ShopContacts" => [
     "title" => "Cumarsáid le Custaiméirí",
     "sub-title" => "Cé mhéad teagmháil a bhí agam le mo chliaint an tseachtain seo?",
     "faqs" => "Ceisteanna Coitianta",
     "tickets" => "Ticéid do Chustaiméirí",
],
     "EC-ShopData" => [
     "title" => "Stádas Úsáideora",
     "sub-title" => "Ón dáta: tús go : deireadh",
     "users" => [
     "title" => "Custaiméirí",
     "subtitle" => "Úsáideoirí Cláraigh",
],
     "views" => [
     "title" => "Cuairteanna",
     "subtitle" => "Cé mhéad uair a thug tú cuairt ar an siopa",
],
     "new_visitors" => "New Users",
     "returning_visitors" => "Úsáideoirí Ar Ais",
     "shop_views" => "Radhairc Siopa",
     "baskets" => [
     "title" => "Cairteacha Siopadóireachta",
     "subtitle" => "Tuairiscigh líon na gcairteanna siopadóireachta nua",
],
     "products" => [
     "title" => "Forbhreathnú ar Tháirgí",
     "subtitle" => "Stádas na dtáirgí sa siopa de réir cineáil",
     "value_name" => "Táirgí",
],
     "products_count" => "Cineálacha táirgí",
     "views_count" => "Féach ar chomhaireamh",
     "sell_count" => "Comhaireamh a dhíol",
     "send_count" => "Comhaireamh loingseoireachta",
],
     "EC-ShopDropShipping" => [
     "title" => "Buail Loingseoireacht",
     "sub-title" => "Painéal do mhórdhíoltóirí Drop Shipping Selldone.",
     "total_fulfillments" => "Iomlán na nOrduithe a Fuarthas",
     "ds_count" => "Orduithe Faighte",
     "statistics_title" => "Fuair an tuarascáil orduithe",
     "ds_cancels" => "Cealaigh ag díoltóir comhéadan",
     "ds_rejects" => "Cealaigh Tú",
     "tip" => "An díoltóir mór earraí tú? An bhfuil stóras, monarcha nó dáileoir táirgí agat? Is féidir leat do tháirgí a thairiscint do dhíoltóirí eile i seirbhís Soldone Drop Shipping chun do tháirge a dhíol ar scála mór. Seol ríomhphost chugainn ag support@selldone.com chun tú a threorú.",
     "view-drop-shipping-panel" => "Logáil isteach ar an bpainéal mórdhíola",
],
     "EC-ShopExchangeRates" => [
     "title" => "Rátaí malairte",
     "sub-title" => "Liosta de na rátaí comhshó airgeadra is déanaí i do stór.",
     "from" => "Airgeadra Foinse",
     "to" => "Airgeadra ceann scríbe",
     "rate" => "Ráta comhshó",
     "vew-exchange-panel" => "painéal bainistíochta ráta malairte",
],
     "EC-ShopExperts" => [
     "title" => "Conarthaí saineolaithe",
     "sub-title" => "Cad iad na gairmithe a oibríonn ar mo stór?",
     "cost" => "Méid an chonartha",
     "duration" => "Fad",
     "start_at" => "Start Date",
     "complete_at" => "Completion Date",
     "cancel_at" => "Dáta Cealaigh",
     "end_at" => "Dáta Seachadta",
     "tip" => "Is féidir leat na speisialtóirí is fearr a fhostú i Selldone chun do ghnó a fhorbairt.",
     "view-experts" => "Cliceáil chun tús a chur leis.",
],
     "EC-ShopGateways" => [
     "title" => "Payment gateways",
     "sub-title" => "Tuairiscigh geataí íocaíochta gníomhacha ar an siopa :siopa.",
     "tip-title" => "Leideanna tábhachtacha",
     "tip" => "Téigh go dtí an leathanach bainistíochta tairseach i do stór agus cuir calafort amháin ar a laghad i gceann cúpla nóiméad. Is maith le do chustaiméirí íoc go tapa agus go slán trí thairseacha ar líne.",
     "view-shop-gateways" => "Logáil isteach i mo stór bainistíochta tairseach.",
     "view-gateways" => "Féach ar níos mó geataí",
],
     "EC-ShopOrders" => [
     "title" => "Orduithe",
     "sub-title" => "Liosta na n-orduithe a fuair mé an tseachtain seo.",
     "total_baskets" => "Orduithe Iomlána",
     "total_posBaskets" => "Orduithe Airgid Iomlána",
     "pos-title" => "Bosca Stórais POS",
     "chart-label" => "Orduithe críochnaithe (ní gá go n-íoctar na horduithe seo!)",
     "tip-title" => "Ba chóir duit iarracht a dhéanamh níos deacra ...",
     "tip" => "Gan rath simplí.",
],
     "EC-ShopProcessCenter" => [
     "title" => "Ionad próiseála",
     "sub-title" => "Cé mhéad ordú a phróiseáil muid sa siopa an tseachtain seo?",
     "tip-title" => "Ní raibh díol agat!",
     "tip" => "Ar an drochuair ní raibh aon díolachán agat an tseachtain seo. Ní mór duit níos mó a fháil chuig do stór. Is féidir leat níos mó táirgí a chur leis, íomhánna níos fearr a roghnú nó tuairiscí níos fearr a scríobh ar do tháirgí. Smaoinigh ar phost lánaimseartha do do ghnó. Má dhéanann tú é i gceart agus mura bhfaigheann tú frustrachas, éireoidh leat.",
     "view-process-center" => "Féach ar lárionad próisis",
     "return" => [
     "title" => "Ordú ar Ais",
     "subtitle" => "Tuairiscigh orduithe ar ais.",
     "tip-title" => "An raibh a fhios agat go bhfuil ...",
     "tip" => "Is féidir leat an oiread scipéid airgid stórais agus is mian leat a chruthú trí Soldone POS! Déanta na fírinne, is féidir leat do táibléad, fón póca nó ríomhaire glúine a chur isteach i do bhosca isteach. Más rud é go spreagfaidh tú, Selldone POS Tá sé rud éigin ba chóir duit tosú a úsáid anois. Ní thógann sé ach cliceáil simplí le seoladh, tá gach rud ullmhaithe againn do do fhreastalaí roimh ré.",
     "view-pos" => "Logáil isteach ar Mo Airgeadóir Store Ar Líne",
],
],
     "EC-ShopSessions" => [
     "title" => "Seisiúin",
     "sub-title" => "Cé mhéad uair a thug mé cuairt ar mo stór?",
     "countries-title" => "Cad iad na tíortha is mó ar tugadh cuairt orthu?",
],
     "EC-PublicMessage" => [
     "title" => "Ar mhaith leat airgead a dhéanamh gan buicéad amháin a chaitheamh?",
     "message" => "A chara: ainm, is féidir leat dul go Painéal > Demonetization agus nasc atreoraithe a chruthú. Seol an nasc chuig do chairde, Faigheann tú cártaí bronntanais Sellone agus céatadán d'íocaíochtaí do chara. Tabhair faoi deara go seolfar an cárta bronntanais chugat féin agus chuig do chara.",
     "action" => "Féach ar mo nasc réamhrá",
     "mail-clip" => "<b style='color: #C2185B'>Tábhachtach:</b> Má úsáideann tú seirbhísí ríomhphoist ar nós Gmail a chuireann teorainn le fad an ríomhphoist, faigh an rogha seo a leanas ag deireadh an ríomhphoist chun an tuairisc iomlán a thaispeáint agus cliceáil air:",
     "no-coin-reward" => "<b style='color: #C2185B'>Ár leithscéal:</b> Níor chomhlíon do ghníomhaíocht an riachtanas chun luach saothair Boinn SEL saor in aisce a fháil. Déan iarracht níos deacra agus díol níos mó ar do shiopa don séasúr seo chugainn.",
     "yes-coin-reward" => "<b style='color: #4CAF50'>Luaíocht:</b> Comhghairdeas, mar gheall ar do fheidhmíocht iontach, thugamar luach saothair saor ó SEL Bonn duit: méid.",
     "need-buy-license" => "<b>Leibhéal suas do ghnó:</b> Níl aon phlean síntiús cláraithe agat do shuíomh Gréasáin do ghnó! Mar sin tá sé in am síntiús amháin ar a laghad a cheannach. Ní chosnaíonn sé ach: méid míosúil le ceannach bliantúil.",
     "not-afford-message" => "Mura bhfuil tú in acmhainn nó má tá deacracht ar bith agat le híocaíocht, ná bíodh drogall ort é sin a chur in iúl dúinn trí support@selldone.com.",
     "add-domain" => "<b>Cén fáth nach mbeadh fearann saincheaptha agat do do ghnó?</b><br> Cuir fearann le do shuíomh Gréasáin anois; tá sé saor!",
],
     "Widget-Socials" => [
     "title" => "Tá Selldone a<del> táirge</del> <span style = 'color: forestgreen'>pobail</span> .<br> Bí i do Dhíoltóir gairmiúil!",
     "message" => "Lean leathanaigh oifigiúla an Soldone ar Twitter, LinkedIn agus líonraí sóisialta. Seol aon tuairimí, iarratais nó cáineadh chugainn nó glac páirt i bplé faoin Selldone. Táimid mar chuid de phobal Selldone a <b>dhéanann</b> Túsa freisin.",
],
     "avocado-seller-daily-report" => [
     "subject" => "Orduithe nua Avocado faighte | : siopa_teideal : am",
     "title" => "Tuairisc feidhmíochta le 24 uair an chloig anuas",
     "message" => "Tá do chustaiméirí ag fanacht go ndéanfar athbhreithniú agus praghas ar d'orduithe. Freagair iarratais do chustaiméirí a luaithe is féidir chun níos mó díolacháin a fháil.",
     "card_title" => "Orduithe sa scuaine",
     "card_subtitle" => "Ó: dáta",
     "card_payed" => "Orduithe íoctha",
],
     "community-comments" => [
     "subject" => "Freagair do phostáil i :community_title",
     "title" => ":name, agus :count daoine eile a rinne trácht ar do phostálacha.",
     "title-simple" => ":ainm trácht ar do phostálacha.",
],
     "community-topic" => [
     "subject" => "🔔 Freagair do thopaic :topic_title",
     "title" => ":ainm, agus :count daoine eile a d'fhreagair ar d'ábhar.",
     "title-simple" => ":d'fhreagair ainm ar d'ábhar.",
],
     "user-login" => [
     "subject" => "🔔 Logáil Isteach Nua :ainm",
     "category" => "Fógraí slándála",
     "title" => "Logáil isteach sa Chuntas",
     "message" => "A chara :name, tá tú logáilte isteach i do chuntas Selldone.",
     "message-shop" => "A chara :ainm, tá tú logáilte isteach i : shop_title .",
     "footer" => "Mura bhfuil tú logáilte isteach, athraigh do phasfhocal.",
],
     "account-transaction" => [
     "withdraw" => "A tharraingt siar",
     "deposit" => "Taisce",
     "withdraw_subject" => "tarraingt siar as an gcuntas : account",
     "deposit_subject" => "Taisce sa chuntas: account",
     "message" => "Tá an t-aistriú airgid déanta leis na sonraíochtaí seo a leanas.",
     "type" => "Cineál idirbhirt",
     "from" => "Cuntas foinse",
     "to" => "Destination account",
     "desc" => "Cur síos ar an idirbhirt",
     "action" => "Féach ar idirbheart",
],
     "penalty" => [
     "subject" => "⛔ Tábhachtach! Sárú rialacha | :siopa",
     "category" => "Eolas criticiúil",
     "title" => "Gearradh pionós ar do shiopa",
     "action" => "Oscail painéal siopa",
],
     "invite" => [
     "subject" => ":cuireadh cuireadh duit chuig Selldone",
     "title" => ":an t-ainm seolta chugat : méid chun cabhrú leat do shuíomh Gréasáin nua ar líne a sheoladh agus airgead a dhéanamh air!",
     "message" => "Ar Soldone, is féidir leat do láithreán gréasáin ríomhthráchtála, blagála, agus pobal ar líne a chruthú agus fiú POS ar líne a fháil agus díolacháin phearsanta a bhunú i nóiméid. Is córas oibriúcháin gnó ar líne é chun do ghnó a dhéanamh ar líne, níos fearr agus níos tapúla. Níl le déanamh ach clárú roimh <b>:dáta</b> chun dearbhán :méid a fháil.",
     "accept" => "Glac le cuireadh",
     "owner" => "Úinéir na",
     "join-date" => "Ar Selldone ó shin",
],
     "shop-recovery" => [
     "subject" => "Nasc athshlánaithe | :siopa",
     "category" => "Slándáil siopa",
     "title" => "Nasc athshlánaithe an stórais de <b>: shop_name</b> .",
     "message" => "Seoladh an ríomhphost seo chugat toisc gur iarr tú do stór a chur ar ais. Má chliceálann tú ar an nasc thíos gheobhaidh tú do shiopa agus na sonraí go léir a bhaineann leis.",
     "action" => "Deimhnigh Aisghabháil Siopa",
],
     "SR-SeasonalSaving" => [
     "title" => "Cé mhéad airgid a shábháil Selldon do do ghnó?",
     "sub-title" => "Ón dáta: tús go : deireadh",
     "infrastructure" => [
     "title" => "Bonneagar",
     "subtitle" => "Freastalaithe, CDN, Stóráil, agus seirbhísí scamall eile",
],
     "experts" => [
     "title" => "Saineolaithe & Foireann",
     "subtitle" => "Forbróirí, cothabháil, agus tacaíocht",
],
     "total_save" => "Iomlán airgead a shábháil",
],
     "SR-SeasonalPerformance" => [
     "title" => "Do fheidhmíocht",
     "sub-title" => "Forbhreathnú gnó ó :tús go :deireadh",
     "new_visitors" => "New Users",
     "returning_visitors" => "Úsáideoirí Ar Ais",
     "shop_views" => "Radhairc Siopa",
     "baskets" => [
     "title" => "Cairteacha Siopadóireachta",
     "subtitle" => "Tuairiscigh líon na gcairteanna siopadóireachta nua",
],
     "products" => [
     "title" => "Forbhreathnú ar Tháirgí",
     "subtitle" => "Stádas na dtáirgí sa siopa de réir cineáil",
     "value_name" => "Táirgí",
],
     "views" => [
     "title" => "Page Views",
     "subtitle" => "Radhairc iomlán leathanaigh an tsuímh Ghréasáin",
],
],
     "vendor-order" => [
     "title" => "New Order",
     "message" => "Tá ordú nua faighte agat. Téigh go dtí an leathanach próiseála orduithe i do phainéal díoltóirí.",
     "subject" => "🛍 Ordú Nua Faighte | : ordú_id",
     "your_revenue" => "Do na Coimisinéirí Ioncaim",
],
     "vendor-invite" => [
     "title" => "Cuireadh Díoltóra",
     "message" => "Tá cuireadh faighte agat a bheith mar dhíoltóir :shop_name. Is féidir leat glacadh leis nó diúltú dó trí chliceáil ar na cnaipí seo a leanas.",
     "subject" => ":siopa_ainm | Fuair tú cuireadh a bheith inár ndíoltóir",
     "accept" => "Glac & Bí i do Dhíoltóir",
     "reject" => "Diúltaigh",
],
     "shop-email-login" => [
     "subject" => "Do Chód Logála Isteach le haghaidh :siopa",
     "header-message" => "Táimid ag seoladh an ríomhphost seo chugat toisc gur iarr tú cód logáil isteach don siopa. Faigh do Phasfhocal Aonuaire (OTP) thíos:",
     "footer-message" => "Beidh an cód seo bailí ar feadh 10 nóiméad. Murar iarr tú an cód logála isteach seo, déan neamhaird den ríomhphost seo le do thoil.",
],
     "shop-email-verify-link" => [
     "subject" => "Fíoraigh do ríomhphost | :siopa",
     "title" => "Fíorú Ríomhphoist",
     "header-message" => "Hi : ainm,<br> Deimhnigh le do thoil gurb é **:ríomhphost** do sheoladh ríomhphoist trí chliceáil ar an gcnaipe nó úsáid an nasc thíos laistigh de 48 uair an chloig.",
     "footer-message" => "",
],
     "vendor-products" => [
     "subject" => "Nuashonrú Táirgí: siopa",
     "title" => "Nuashonrú ar Stádas Táirge - 24 uair an chloig is déanaí",
     "message" => "Tá súil agam go bhfaighidh an teachtaireacht seo go maith thú. Is nuashonrú gairid é seo chun tú a chur ar an eolas faoi stádas do tháirgí ar ár n-ardán le 24 uair an chloig anuas. Le linn na tréimhse seo, tá athruithe tagtha ar stádas roinnt táirgí. D'fhéadfadh na hathruithe seo a bheith mar gheall ar cheannacháin, nuashonruithe stoic nó imeachtaí gaolmhara eile. Chun faisnéis níos mionsonraithe a fháil faoi gach táirge, logáil isteach i do chuntas agus seiceáil an rannán 'Stádas Táirge'.",
     "action" => "Oscail Painéal Díoltóra",
],
];