<?php 

 return [
     "invoice" => "Sonrasc",
     "serial" => "Sraithuimhir Uimh.",
     "date" => "Dáta an tsonraisc",
     "seller" => "Díoltóir",
     "buyer" => "Ceannaí",
     "address" => "seoladh",
     "code" => "Cód",
     "vat" => "Cód CBL",
     "phone" => "Fón",
     "description" => "Cur síos",
     "units" => "Aonaid",
     "quantity" => "Ceathair",
     "price" => "praghas",
     "discount" => "Lascaine",
     "tax" => "Cáin",
     "sub_total" => "Fo-iomlán",
     "total_discount" => "Lascaine iomlán",
     "taxable_amount" => "Méid inchánach",
     "total_taxes" => "Cánacha iomlána",
     "tax_rate" => "Ráta cánach",
     "total_amount" => "Iomlán",
     "pay_until" => "Le do thoil íoc go dtí",
     "amount_in_words" => "Méid i bhfocail",
     "amount_in_words_format" => "%s %s agus %s %s",
     "notes" => "Nótaí",
     "shipping" => "Á sheoladh",
     "paid" => "Íoctha",
     "due" => "Dlite",
];