<?php 

 return [
     "home" => "hoko atu",
     "blogs" => "Blog",
     "helps" => "Awhina",
     "current_location" => "Tenei urunga",
     "dashboard" => "dashboard",
     "my_shops" => "Aku Toa",
     "wallet" => "wallet",
     "about" => "Mo Seldone",
     "contact" => "contact us",
     "comments" => "comments",
     "likes" => "Ka pai",
     "power" => "harikoa",
     "build_free_shop" => "Hanga to toa mo te kore utu",
     "shop_name" => "shop name",
     "categories" => "categories",
     "sub_articles" => "More",
     "terms" => "Nga tikanga",
     "colour" => "tae",
     "style" => "style",
     "volume" => "volume",
     "weight" => "weight",
     "pack" => "Puke",
     "type" => "type",
     "add_to_card" => "Tāpiri ki te Kete",
     "overview" => "Overview",
     "reviews" => "Nga arotake",
     "spec" => "Spec katoa",
     "you_may_also_like" => "Ka pai pea koe",
     "about_us" => "Mo Tatou",
     "contact_us" => "contact us",
     "cookie_privacy" => "Cookie &amp; privacy policy",
     "follow_us" => "whai ia matou",
     "category" => "Kāwai",
     "author" => "Written by ",
     "published_at" => "I whakaputaina i",
     "modified_at" => "Whakarerekētia i",
     "price" => "utu",
     "discount" => "Te utu",
     "price_after_discount" => "Utu i muri i te hekenga",
     "available" => "Kei te waatea",
     "sold_out" => "Kua hokona atu",
     "buy" => "Hokona inaianei",
     "login_shop" => "Takiuru Toa",
     "posted_on" => "I whakairihia i te:ra",
];