<?php 

 return [
     "home" => "ရောင်းပြီးပြီ။",
     "blogs" => "ဘလော့",
     "helps" => "ကူညီပါ",
     "current_location" => "ဒီဝင်ခွင့်",
     "dashboard" => "dashboard",
     "my_shops" => "ကျွန်ုပ်၏ အရောင်းဆိုင်များ",
     "wallet" => "wallet",
     "about" => "Selldone အကြောင်း",
     "contact" => "contact us",
     "comments" => "comments",
     "likes" => "အကြိုက်များ",
     "power" => "ပျော်ရွှင်ပါစေ။",
     "build_free_shop" => "သင့်စတိုးကို အခမဲ့တည်ဆောက်ပါ။",
     "shop_name" => "shop name",
     "categories" => "categories",
     "sub_articles" => "More",
     "terms" => "စည်းမျဥ်း",
     "colour" => "အရောင်",
     "style" => "style",
     "volume" => "volume",
     "weight" => "weight",
     "pack" => "အထုပ်",
     "type" => "type",
     "add_to_card" => "စျေးဝယ်ခြင်းထဲသို့ထည့်သည်",
     "overview" => "Overview",
     "reviews" => "သုံးသပ်ချက်များ",
     "spec" => "Spec အပြည့်အစုံ",
     "you_may_also_like" => "ကြိုက်လည်းကြိုက်နိုင်တယ်။",
     "about_us" => "ကြှနျုပျတို့အကွောငျး",
     "contact_us" => "contact us",
     "cookie_privacy" => "Cookie &amp; privacy policy",
     "follow_us" => "ကြှနျုပျတို့နောကျလိုကျပါ",
     "category" => "အမျိုးအစား",
     "author" => "Written by ",
     "published_at" => "တွင်ထုတ်ဝေသည်။",
     "modified_at" => "ပြုပြင်မွမ်းမံထားသည်။",
     "price" => "စျေးနှုန်း",
     "discount" => "လျှော့စျေး",
     "price_after_discount" => "စျေးလျှော့ပြီးနောက်",
     "available" => "ရရှိနိုင်ပါသည်။",
     "sold_out" => "ရောင်းကုန်ပြီ",
     "buy" => "အခုဝယ်ပါ",
     "login_shop" => "ဆိုင်ထဲဝင်ပါ။",
     "posted_on" => ": date တွင်တင်ထားသည်။",
];