export default {
  "commons": {
    "approved": "Schválený",
    "trend": "Trend",
    "like": "Jako",
    "share": "Podíl",
    "comment": "Komentář",
    "view_insight": "Zobrazit statistiky",
    "trial_mode": "Zkušební mód",
    "no_trial_mode": "Žádné volné období",
    "nofollow": "Nofollow",
    "cross": "Přejít",
    "pin": "Připnout nahoru",
    "private": "Soukromá místnost",
    "text": "Text",
    "voice": "Hlas",
    "video": "Video",
    "link": "Odkaz",
    "image": "obraz",
    "product": "Produkt",
    "seo": "SEO",
    "configuration": "Konfigurace",
    "monetize": "zpeněžit",
    "subscription_fee": "Poplatek za předplatné",
    "login_msg": "Začněte svou komunitní cestu",
    "topic": "Téma",
    "topic_title": "Název tématu",
    "categories": "Kategorie",
    "author": "Autor",
    "reply": "Odpověď",
    "reports": "zpráva(y)",
    "show_more": "Zobrazit více..",
    "disagree": "Nesouhlasit",
    "agree": "Souhlasit",
    "suggestion_list": "Návrh pro vás",
    "following_action": "Následující",
    "follow_action": "Následovat",
    "rules_violation": "Vaše komunita čelí okolnostem porušení pravidel!",
    "cross_community": "Křížová komunita",
    "crossable": "Kříž schopný",
    "crossable_msg": "Jiné komunity mohou vytvářet různá témata podle komunity turné",
    "nofollow_msg": "Přidejte značku nofollow pro všechny odkazy",
    "topics": "Témata",
    "posts": "Příspěvky",
    "comments": "Komentáře",
    "total": "Celkový",
    "user_reactions": "Reakce uživatelů",
    "impressions": "dojmy",
    "reactions": "Reakce",
    "saves": "Uloží",
    "embeds": "Vloží",
    "shares": "akcie",
    "you_are_admin": "Jste admin",
    "you_are_moderator": "Jste moderátor",
    "invite_friend": "Pozvěte mého přítele",
    "nominate_friend": "Nominujte mého přítele",
    "request_nominate": "Požádejte někoho, aby vás nominoval!",
    "show_deleted_posts": "Zobrazit smazané příspěvky",
    "moderators": "Moderátoři",
    "analytics": "Analytics",
    "edit": "Upravit",
    "notify": "Oznámit",
    "rules": "Pravidla",
    "explore": "Prozkoumat",
    "my_feed": "Mě",
    "blocked_message": "Jste zablokováni do",
    "reported": "Nahlášeno",
    "report": "Zpráva",
    "post": "Pošta",
    "attach_file": "Přiložit soubor"
  },
  "invite_message": "{user} vás pozval do fóra {community}. Kliknutím na odkaz níže si můžete přečíst postřehy svých přátel a podělit se s nimi o svůj názor. Čekám na tebe.",
  "subscription_type": {
    "MONTHLY": "Měsíční",
    "SEASONAL": "Sezónní",
    "YEARLY": "Roční",
    "LIFETIME": "Život"
  },
  "trial_type": {
    "TRIO": "3 dny zdarma",
    "WEEK": "Jeden týden zdarma",
    "MONTH": "Jeden měsíc zdarma"
  },
  "post_reaction": {
    "LIKE": "Milovat",
    "SMILE": "Šťastný",
    "CLAP": "tleská",
    "IDEA": "Nápad",
    "DISAGREE": "Nesouhlasit"
  },
  "post_action": {
    "comments": "Komentáře",
    "impressions": "dojmy",
    "saves": "Uloží",
    "shares": "akcie",
    "embeds": "Vloží",
    "reports": "Zprávy"
  },
  "nominate": {
    "note": "Můžete nominovat někoho, koho znáte. Pokud tato osoba již nebyla schválena jinou osobou, budete registrováni jako její ověřovatel. Váš přítel musí být členem Selldone, než ho budete moci nominovat.",
    "no_credit_message": "Bohužel nemáte dostatek kreditu na schválení někoho jiného, ale brzy tento kredit obdržíte. Zkontrolujte prosím v následujících dnech.",
    "title": "Nominujte svého přítele",
    "remains_credit": "Vaše zásluha na nominaci ostatních",
    "user_nominate": "Vyberte svého přítele",
    "action": "Nominovat"
  },
  "stage_level": {
    "PUBLIC": "Všichni uživatelé",
    "PRIVATE": "Pouze moderátoři",
    "VERIFIED": "Všichni ověření uživatelé"
  },
  "widget": {
    "offensive_message": "Tento komentář je urážlivý!",
    "topic": "Téma"
  },
  "editor": {
    "topic_title": "Název tématu",
    "topic_desc": "Popis tématu",
    "send_post": "Odeslat příspěvek",
    "no_link": "Žádný odkaz",
    "add_link": "Přidat odkaz",
    "add_video": "Přidat video",
    "add_image": "Přidat obrázek",
    "no_subscription": "Žádný plán zpeněžení",
    "nofollow_msg": "Přidejte nofollow ke všem odkazům",
    "cross_msg": "Může z tohoto tématu vytvořit více témat",
    "pin_msg": "Připnout toto téma na začátek témat v kategorii",
    "private_on_msg": "Toto téma mohou vidět pouze administrátoři a moderátoři",
    "private_off_msg": "Toto téma může vidět kdokoli",
    "topic_placeholder": "Zajímavý název tématu zde...",
    "desc_placeholder": "Krátký popis k tématu...",
    "title_placeholder": "Jaká je vaše otázka, téma nebo...?",
    "body_placeholder": "Napsat nový příspěvek...",
    "remove_poll": "Odebrat anketu",
    "take_screenshot": "Vezměte jako kryt",
    "take_link_msg": "Minulý odkaz zde a vstupte",
    "eligible_title": "Kroky k tomu, abyste byli způsobilí k publikování",
    "public": "Veřejnost"
  },
  "tips": {
    "verify_email": "Zadejte a ověřte svůj e-mail.",
    "verify_phone": "Ověřte svůj telefon.",
    "need_nominate": "Nominujte jedním nebo požádejte o ověření."
  },
  "regime": {
    "Aristocracy": "Aristokracie",
    "Timocracy": "Timokracie",
    "Oligarchy": "Oligarchie",
    "Democracy": "Demokracie",
    "Tyranny": "Tyranie"
  },
  "comment": {
    "comment_plc": "Přidat komentář...",
    "comment_response_plc": "Odpověď uživateli {name}...",
    "first_comment": "Umístěte první komentář..."
  },
  "filter": {
    "created_at": "Nejnovější",
    "created_at_asc": "Pionýři",
    "positive_reactions": "Nejoblíbenější",
    "engaged": "Nejvíce angažovaná",
    "all_posts": "Všechny příspěvky",
    "media_only": "Pouze média"
  },
  "topic": {
    "add_topic": "Přidat nové téma",
    "add_topic_desc": "Nejprve vyhledejte své téma! Vůbec nevytvářejte duplicitní témata, protože budou odstraněna moderátory.",
    "can_create": "Lze vytvořit podle",
    "add_cross": "Přidat více témat",
    "add_cross_desc": "Můžete vytvářet společná vlákna s jinými komunitami. Chcete-li to provést, musíte zkopírovat kód napříč komunitami.",
    "admins_moderators": "Správci a moderátoři",
    "remove_msg": "Pokud toto téma odstraníte, jedná se o nevratnou akci!",
    "remove": "Odebrat téma",
    "main_post_removed_msg": "Hlavní příspěvek byl odstraněn autorem nebo administrátorem!",
    "delete_dialog": {
      "title": "Odebrat téma",
      "message": "Opravdu smazat toto téma?",
      "actions": "Ano, smazat nyní"
    },
    "statistics": "Statistika kategorií"
  },
  "community": {
    "disabled": "Vaše komunita je deaktivována!",
    "community_url": "Otevřít stránku komunity",
    "edit": "Upravit komunitu",
    "install": "Nainstalovat nyní",
    "start_community_message": "Začněte svou úžasnou komunitu.",
    "shop_community_setting": "Konfigurace komunity",
    "regime": "komunitární režim",
    "need_verify_to_create_message": "Chcete-li vytvořit svou skvělou komunitu zcela zdarma, proveďte tyto kroky",
    "name": "název",
    "name_plc": "moje jméno-komunity...",
    "name_msg": "Nastavte jedinečné uživatelské jméno pro vaši komunitu",
    "title": "Titul",
    "title_plc": "Nějaký úžasný komunitní titul...",
    "title_msg": "Nastavte konkrétní a komplexní název pro komunitu",
    "desc": "Popis",
    "desc_plc": "O této komunitě...",
    "desc_msg": "Krátký popis této komunity",
    "enable_msg": "Svou komunitu můžete povolit nebo zakázat",
    "hide_rule": "Skrýt pravidlo",
    "edit_rule": "Upravit pravidlo",
    "rule_plc": "Napište pravidla své komunity...",
    "statistics": "Komunitní statistiky"
  },
  "access": {
    "admins": "Správci",
    "moderators": "Moderátoři",
    "manage_admins": "Spravovat administrátory",
    "manage_moderators": "Spravovat moderátory",
    "add_moderator": "Přidat moderátora"
  },
  "category": {
    "add_new": "Přidat novou kategorii",
    "add_new_msg": "Můžete vytvořit celkem 20 kategorií. Je to víc než dost, aby přístup ke komunitě byl pohodlný a dosažitelný.",
    "title": "Titul",
    "title_plc": "Nějaká úžasná kategorie...",
    "title_msg": "Nastavte konkrétní a komplexní název pro kategorii",
    "desc": "Popis",
    "desc_plc": "O této kategorii...",
    "desc_msg": "Krátký popis této kategorie",
    "restrict": "Omezit režim",
    "restrict_msg": "Téma mohou vytvářet pouze moderátoři?",
    "statistics": "Statistika kategorií",
    "remove_msg": "Pokud tuto kategorii odstraníte, jedná se o nevratnou akci!",
    "delete_dialog": {
      "title": "Odebrat kategorii",
      "message": "Opravdu tuto kategorii smazat?",
      "actions": "Ano, smazat nyní"
    }
  },
  "invite": {
    "not_have_profile_error": "Tento uživatel nedokončil svůj profil!",
    "nominated_before_error": "Tento uživatel byl nominován dříve!",
    "verified_before_error": "Tento profil již dříve ověřen globální komunitou Soldone!",
    "send_invite_msg": "Pošlete tuto zprávu svým přátelům"
  },
  "post_actions": {
    "save": "Uložit",
    "save_msg": "Šetřit na později",
    "copy_code": "Kopírovat kód",
    "copy_link": "Kopírovat odkaz",
    "copy_link_msg": "Přímý odkaz na příspěvek",
    "embed": "Vložte tento příspěvek",
    "embed_msg": "Zkopírujte a vložte html kód pro vložení",
    "edit": "Upravit příspěvek",
    "edit_msg": "Změňte obsah příspěvku",
    "report_msg": "Je tento příspěvek nevhodný?",
    "delete": "Smazat příspěvek",
    "delete_msg": "Odebrat tento příspěvek",
    "approved": "Schválený příspěvek",
    "approve_action": "Označit jako přijaté",
    "approved_msg": "Nastavit tento příspěvek jako schválenou odpověď",
    "delete_dialog": {
      "title": "Smazat příspěvek",
      "message": "Opravdu smazat tento příspěvek?",
      "action": "Ano, smazat nyní"
    }
  },
  "comment_actions": {
    "edit": "Upravit komentář",
    "link": "Odkaz na komentář",
    "link_msg": "Zkopírujte odkaz pro sdílení komentáře",
    "edit_msg": "Změňte obsah komentáře",
    "delete": "Vymazat",
    "delete_msg": "Smazat tento komentář",
    "delete_dialog": {
      "title": "Smazat komentář",
      "message": "Opravdu smazat tento komentář?",
      "action": "Ano, smazat nyní"
    }
  },
  "embed": {
    "copy_code_msg": "Zkopírujte za kód",
    "copy_code": "Kopírovat kód"
  }
};