export default {
  "commons": {
    "approved": "Goedkard",
    "trend": "Trend",
    "like": "Lykas",
    "share": "Diele",
    "comment": "Kommentaar",
    "view_insight": "Besjoch ynsjoch",
    "trial_mode": "Trial modus",
    "no_trial_mode": "Gjin frije perioade",
    "nofollow": "Nofollow",
    "cross": "Krús",
    "pin": "Pin nei boppe",
    "private": "Eigen keamer",
    "text": "Tekst",
    "voice": "Lûd",
    "video": "Video",
    "link": "Link",
    "image": "Byld",
    "product": "Produkt",
    "seo": "SEO",
    "configuration": "Konfiguraasje",
    "monetize": "Monetize",
    "subscription_fee": "Abonnemintskosten",
    "login_msg": "Begjin jo mienskipsreis",
    "topic": "Ûnderwerp",
    "topic_title": "Underwerp titel",
    "categories": "Kategoryen",
    "author": "Skriuwer",
    "reply": "Antwurdzje",
    "reports": "rapport(en)",
    "show_more": "Lit mear sjen..",
    "disagree": "Net iens",
    "agree": "Oerienkomme",
    "suggestion_list": "Suggestje foar jo",
    "following_action": "Folgjend",
    "follow_action": "Folgje",
    "rules_violation": "Jo mienskip wurdt konfrontearre mei regels oertrêding omstannichheid!",
    "cross_community": "Cross mienskip",
    "crossable": "Krús yn steat",
    "crossable_msg": "Oare mienskippen kinne cross-ûnderwerpen meitsje troch toermienskip",
    "nofollow_msg": "Foegje nofollow-tag ta foar alle keppelings",
    "topics": "Underwerpen",
    "posts": "Posts",
    "comments": "Comments",
    "total": "Totaal",
    "user_reactions": "Reaksjes fan brûkers",
    "impressions": "Impressions",
    "reactions": "Reaksjes",
    "saves": "Besparret",
    "embeds": "Ynbêde",
    "shares": "Oandielen",
    "you_are_admin": "Do bist in admin",
    "you_are_moderator": "Do bist in moderator",
    "invite_friend": "Noegje myn freon út",
    "nominate_friend": "Nominearje myn freon",
    "request_nominate": "Freegje immen om jo te nominearjen!",
    "show_deleted_posts": "Lit wiske berjochten sjen",
    "moderators": "Moderators",
    "analytics": "Analytics",
    "edit": "Bewurkje",
    "notify": "Notify",
    "rules": "Regels",
    "explore": "Ferkenne",
    "my_feed": "My",
    "blocked_message": "Jo binne blokkearre oant",
    "reported": "Rapportearre",
    "report": "Melde"
  },
  "invite_message": "{user} hat jo útnoege foar it foarum {community}. Klikje op de link hjirûnder om de observaasjes fan jo freonen te lêzen en jo miening mei har te dielen. Ik wachtsje op dy.",
  "subscription_type": {
    "MONTHLY": "Moanne",
    "SEASONAL": "Seasonal",
    "YEARLY": "Jierliks",
    "LIFETIME": "Lifetime"
  },
  "trial_type": {
    "TRIO": "3 dagen fergees",
    "WEEK": "Ien wike frij",
    "MONTH": "Ien moanne fergees"
  },
  "post_reaction": {
    "LIKE": "Leafde",
    "SMILE": "Lokkich",
    "CLAP": "Klappe",
    "IDEA": "Idee",
    "DISAGREE": "Net iens"
  },
  "post_action": {
    "comments": "Comments",
    "impressions": "Impressions",
    "saves": "Besparret",
    "shares": "Oandielen",
    "embeds": "Ynbêde",
    "reports": "Ferslaggen"
  },
  "nominate": {
    "note": "Jo kinne immen nominearje dy't jo kenne. As dizze persoan net al goedkard is troch in oare persoan, wurde jo registrearre as har ferifiearder. Jo freon moat lid wêze fan Selldone foardat jo se kinne nominearje.",
    "no_credit_message": "Spitigernôch, do hast net genôch kredyt te goedkarre immen oars, mar jo krije dit kredyt gau. Kontrolearje asjebleaft yn 'e kommende dagen.",
    "title": "Nominearje jo freon",
    "remains_credit": "Jo kredyt om oaren te nominearjen",
    "user_nominate": "Selektearje jo freon",
    "action": "Nominearje"
  },
  "stage_level": {
    "PUBLIC": "Alle brûkers",
    "PRIVATE": "Allinnich moderators",
    "VERIFIED": "Alle ferifiearre brûkers"
  },
  "widget": {
    "offensive_message": "Dizze opmerking is beledigend!",
    "topic": "Ûnderwerp"
  },
  "editor": {
    "topic_title": "Underwerp titel",
    "topic_desc": "Underwerp beskriuwing",
    "send_post": "Stjoer post",
    "no_link": "Gjin keppeling",
    "add_link": "Add keppeling",
    "add_video": "Foegje fideo ta",
    "add_image": "Ofbylding tafoegje",
    "no_subscription": "Gjin plan foar monetarisaasje",
    "nofollow_msg": "Foegje nofollow ta oan alle keppelings",
    "cross_msg": "Kin krúsûnderwerp meitsje fan dit ûnderwerp",
    "pin_msg": "Pin dit ûnderwerp oan de top fan ûnderwerpen yn kategory",
    "private_on_msg": "Allinnich admin & moderators kinne dit ûnderwerp sjen",
    "private_off_msg": "Elkenien kin dit ûnderwerp sjen",
    "topic_placeholder": "Geweldige ûnderwerptitel hjir ...",
    "desc_placeholder": "Koarte beskriuwing oer it ûnderwerp ...",
    "title_placeholder": "Wat is dyn fraach, ûnderwerp of ...?",
    "body_placeholder": "Skriuw in nij berjocht...",
    "remove_poll": "Fuortsmite poll",
    "take_screenshot": "Nim as dekking",
    "take_link_msg": "Ferline keppeling hjir en enter",
    "eligible_title": "Stappen om yn oanmerking te kommen om te pleatsen"
  },
  "tips": {
    "verify_email": "Fier en ferifiearje jo e-mail.",
    "verify_phone": "Ferifiearje jo telefoan.",
    "need_nominate": "Nominearje troch ien of fersyk om te ferifiearjen."
  },
  "regime": {
    "Aristocracy": "Aristokrasy",
    "Timocracy": "Timokrasy",
    "Oligarchy": "Oligarchy",
    "Democracy": "Demokrasy",
    "Tyranny": "Tyranny"
  },
  "comment": {
    "comment_plc": "Foegje in reaksje ta...",
    "comment_response_plc": "Antwurd op {name}...",
    "first_comment": "Meitsje earste reaksje ..."
  },
  "filter": {
    "created_at": "Meast resint",
    "created_at_asc": "Pioniers",
    "positive_reactions": "Meast leuk",
    "engaged": "Meast ferloofd",
    "all_posts": "Alle berjochten",
    "media_only": "Allinnich media"
  },
  "topic": {
    "add_topic": "Foegje nij ûnderwerp ta",
    "add_topic_desc": "Earst sykje oer jo ûnderwerp! Meitsje hielendal gjin dûbele ûnderwerpen, om't se troch de moderators fuortsmiten wurde.",
    "can_create": "Kin meitsje troch",
    "add_cross": "Foegje krús ûnderwerp ta",
    "add_cross_desc": "Jo kinne mienskiplike diskusjes meitsje mei oare mienskippen. Om dit te dwaan, moatte jo de cross-community-koade kopiearje.",
    "admins_moderators": "Behearders & Moderators",
    "remove_msg": "As jo dit ûnderwerp fuortsmite, is it in ûnomkearbere aksje!",
    "remove": "Underwerp fuortsmite",
    "main_post_removed_msg": "Haadberjocht is fuortsmiten troch skriuwer of admin!",
    "delete_dialog": {
      "title": "Underwerp fuortsmite",
      "message": "Binne jo wis dat jo dit ûnderwerp wiskje?",
      "actions": "Ja, no wiskje"
    },
    "statistics": "Kategory statistyk"
  },
  "community": {
    "disabled": "Jo mienskip útskeakele!",
    "community_url": "Iepenje mienskip side",
    "edit": "Mienskip bewurkje",
    "install": "Ynstallearje no",
    "start_community_message": "Begjin jo geweldige mienskip.",
    "shop_community_setting": "Mienskip konfiguraasjes",
    "regime": "Mienskip regime",
    "need_verify_to_create_message": "Om jo geweldige mienskip folslein fergees te meitsjen, pass dizze stappen troch",
    "name": "Namme",
    "name_plc": "myn-mienskip-namme ...",
    "name_msg": "Stel in unike brûkersnamme yn foar jo mienskip",
    "title": "Titel",
    "title_plc": "Guon geweldige mienskipstitel ...",
    "title_msg": "Stel in spesifike en wiidweidige titel foar mienskip yn",
    "desc": "Beskriuwing",
    "desc_plc": "Oer dizze mienskip ...",
    "desc_msg": "In koarte beskriuwing oer dizze mienskip",
    "enable_msg": "Jo kinne jo mienskip yn- of útskeakelje",
    "hide_rule": "Regel ferbergje",
    "edit_rule": "Regel bewurkje",
    "rule_plc": "Skriuw jo mienskipsregels ...",
    "statistics": "Community Statistics"
  },
  "access": {
    "admins": "Admins",
    "moderators": "Moderators",
    "manage_admins": "Beheare admins",
    "manage_moderators": "Beheare moderators",
    "add_moderator": "Foegje moderator ta"
  },
  "category": {
    "add_new": "Add nije kategory",
    "add_new_msg": "Jo kinne yn totaal 20 kategoryen oanmeitsje. It is mear dan genôch om jo mienskip tagong handich en mear berikber te hâlden.",
    "title": "Titel",
    "title_plc": "Guon geweldige kategory ...",
    "title_msg": "Stel in spesifike en wiidweidige titel foar kategory yn",
    "desc": "Beskriuwing",
    "desc_plc": "Oer dizze kategory...",
    "desc_msg": "In koarte beskriuwing oer dizze kategory",
    "restrict": "Beheine modus",
    "restrict_msg": "Allinnich moderators kinne ûnderwerp oanmeitsje?",
    "statistics": "Kategory statistyk",
    "remove_msg": "As jo dizze kategory fuortsmite, is it in ûnomkearbere aksje!",
    "delete_dialog": {
      "title": "Kategory fuortsmite",
      "message": "Binne jo wis dizze kategory wiskje?",
      "actions": "Ja, no wiskje"
    }
  },
  "invite": {
    "not_have_profile_error": "Dizze brûker foltôgje syn/har profyl net!",
    "nominated_before_error": "Dizze brûker nominearre earder!",
    "verified_before_error": "Dit profyl ferifiearre troch Selldone wrâldwide mienskip earder!",
    "send_invite_msg": "Stjoer dit berjocht nei jo freonen"
  },
  "post_actions": {
    "save": "Rêde",
    "save_msg": "Bewarje foar letter",
    "copy_code": "Kopiearje koade",
    "copy_link": "Kopiearje keppeling",
    "copy_link_msg": "Direkte keppeling nei de post",
    "embed": "Embed dizze post",
    "embed_msg": "Kopiearje & ferline ynbêde html",
    "edit": "Post bewurkje",
    "edit_msg": "Feroarje de ynhâld fan 'e post",
    "report_msg": "Is dizze post net geskikt?",
    "delete": "Post wiskje",
    "delete_msg": "Fuortsmite dizze post",
    "approved": "Goedkard post",
    "approve_action": "Markearje as akseptearre",
    "approved_msg": "Stel dizze post as goedkard antwurd",
    "delete_dialog": {
      "title": "Post wiskje",
      "message": "Binne jo wis dizze post wiskje?",
      "action": "Ja, no wiskje"
    }
  },
  "comment_actions": {
    "edit": "Kommentaar bewurkje",
    "link": "Link nei reaksje",
    "link_msg": "Kopiearje keppeling om de opmerking te dielen",
    "edit_msg": "Feroarje jo kommentaar ynhâld",
    "delete": "Wiskje",
    "delete_msg": "Wiskje dizze opmerking",
    "delete_dialog": {
      "title": "Wiskje opmerking",
      "message": "Binne jo wis dizze opmerking wiskje?",
      "action": "Ja, no wiskje"
    }
  },
  "embed": {
    "copy_code_msg": "Kopiearje foarby de koade",
    "copy_code": "Kopiearje koade"
  }
};