export default {
  "commons": {
    "approved": "승인됨",
    "trend": "경향",
    "like": "처럼",
    "share": "공유하다",
    "comment": "논평",
    "view_insight": "인사이트 보기",
    "trial_mode": "평가판 모드",
    "no_trial_mode": "무료 기간 없음",
    "nofollow": "노팔로우",
    "cross": "가로 질러 가다",
    "pin": "상단에 고정",
    "private": "사적인 방",
    "text": "텍스트",
    "voice": "목소리",
    "video": "동영상",
    "link": "링크",
    "image": "영상",
    "product": "제품",
    "seo": "SEO",
    "configuration": "구성",
    "monetize": "수익 창출",
    "subscription_fee": "구독료",
    "login_msg": "커뮤니티 여정을 시작하세요",
    "topic": "주제",
    "topic_title": "주제 제목",
    "categories": "카테고리",
    "author": "작가",
    "reply": "회신하다",
    "reports": "보고서",
    "show_more": "자세히보기..",
    "disagree": "동의하지 않는다",
    "agree": "동의하다",
    "suggestion_list": "당신을 위한 제안",
    "following_action": "수행원",
    "follow_action": "따르다",
    "rules_violation": "커뮤니티는 규칙 위반 상황에 직면해 있습니다!",
    "cross_community": "크로스 커뮤니티",
    "crossable": "크로스 가능",
    "crossable_msg": "다른 커뮤니티는 투어 커뮤니티별로 교차 주제를 만들 수 있습니다.",
    "nofollow_msg": "모든 링크에 nofollow 태그 추가",
    "topics": "주제",
    "posts": "게시물",
    "comments": "코멘트",
    "total": "총",
    "user_reactions": "사용자 반응",
    "impressions": "노출수",
    "reactions": "반응",
    "saves": "저장",
    "embeds": "임베드",
    "shares": "주식",
    "you_are_admin": "당신은 관리자입니다",
    "you_are_moderator": "당신은 중재자입니다",
    "invite_friend": "내 친구 초대",
    "nominate_friend": "내 친구 추천",
    "request_nominate": "누군가에게 당신을 추천해달라고 요청하세요!",
    "show_deleted_posts": "삭제된 게시물 표시",
    "moderators": "중재자",
    "analytics": "해석학",
    "edit": "편집하다",
    "notify": "알림",
    "rules": "규칙",
    "explore": "탐구하다",
    "my_feed": "나",
    "blocked_message": "당신은 까지 차단됩니다",
    "reported": "보고됨",
    "report": "보고서",
    "post": "게시하다",
    "attach_file": "파일을 첨부"
  },
  "invite_message": "{user}님이 {community} 포럼에 귀하를 초대했습니다. 아래 링크를 클릭하여 친구의 관찰 내용을 읽고 의견을 공유하세요. 당신을 기다리고 있어요.",
  "subscription_type": {
    "MONTHLY": "월간 간행물",
    "SEASONAL": "계절",
    "YEARLY": "매년",
    "LIFETIME": "일생"
  },
  "trial_type": {
    "TRIO": "3일 무료",
    "WEEK": "일주일 무료",
    "MONTH": "1개월 무료"
  },
  "post_reaction": {
    "LIKE": "사랑",
    "SMILE": "행복하다",
    "CLAP": "박수",
    "IDEA": "아이디어",
    "DISAGREE": "동의하지 않는다"
  },
  "post_action": {
    "comments": "코멘트",
    "impressions": "노출수",
    "saves": "저장",
    "shares": "주식",
    "embeds": "임베드",
    "reports": "보고서"
  },
  "nominate": {
    "note": "아는 사람을 지명할 수 있습니다. 이 사람이 다른 사람에 의해 아직 승인되지 않은 경우 귀하는 검증자로 등록됩니다. 친구를 지명하려면 먼저 Selldone의 회원이어야 합니다.",
    "no_credit_message": "유감스럽게도 다른 사람을 승인할 만큼 충분한 크레딧이 없지만 곧 이 크레딧을 받게 됩니다. 며칠 후에 확인해 주세요.",
    "title": "친구 추천",
    "remains_credit": "다른 사람을 추천할 수 있는 크레딧",
    "user_nominate": "친구를 선택하세요",
    "action": "지명하다"
  },
  "stage_level": {
    "PUBLIC": "모든 사용자들",
    "PRIVATE": "중재자만",
    "VERIFIED": "인증된 모든 사용자"
  },
  "widget": {
    "offensive_message": "이 댓글은 공격적입니다!",
    "topic": "주제"
  },
  "editor": {
    "topic_title": "주제 제목",
    "topic_desc": "주제 설명",
    "send_post": "게시물 보내기",
    "no_link": "링크 없음",
    "add_link": "링크 추가",
    "add_video": "비디오 추가",
    "add_image": "이미지 추가",
    "no_subscription": "수익 창출 계획 없음",
    "nofollow_msg": "모든 링크에 nofollow 추가",
    "cross_msg": "이 주제에서 교차 주제를 만들 수 있습니다.",
    "pin_msg": "이 주제를 카테고리의 주제 상단에 고정",
    "private_on_msg": "관리자 및 중재자만 이 주제를 볼 수 있습니다.",
    "private_off_msg": "누구나 이 주제를 볼 수 있습니다.",
    "topic_placeholder": "놀라운 주제 제목이 여기에...",
    "desc_placeholder": "주제에 대한 간략한 설명...",
    "title_placeholder": "질문, 주제 또는 ...?",
    "body_placeholder": "새 글을 쓰다...",
    "remove_poll": "설문조사 삭제",
    "take_screenshot": "표지로 삼다",
    "take_link_msg": "여기에서 과거 링크를 입력하고",
    "eligible_title": "게시 자격이 되는 단계",
    "public": "공공의"
  },
  "tips": {
    "verify_email": "이메일을 입력하고 확인합니다.",
    "verify_phone": "전화를 확인합니다.",
    "need_nominate": "1인을 추천하거나 확인을 요청합니다."
  },
  "regime": {
    "Aristocracy": "귀족",
    "Timocracy": "티모크라시",
    "Oligarchy": "과두 정치",
    "Democracy": "민주주의",
    "Tyranny": "포학"
  },
  "comment": {
    "comment_plc": "의견을 추가하다...",
    "comment_response_plc": "{name}님에 대한 응답...",
    "first_comment": "첫 댓글 달기..."
  },
  "filter": {
    "created_at": "가장 최근",
    "created_at_asc": "개척자",
    "positive_reactions": "가장 좋아하는",
    "engaged": "가장 많이 참여",
    "all_posts": "모든 게시물",
    "media_only": "미디어 전용"
  },
  "topic": {
    "add_topic": "새 주제 추가",
    "add_topic_desc": "주제에 대한 첫 번째 검색! 중재자에 의해 제거될 것이므로 중복 주제를 전혀 만들지 마십시오.",
    "can_create": "에 의해 생성 가능",
    "add_cross": "교차 주제 추가",
    "add_cross_desc": "다른 커뮤니티와 공통 스레드를 만들 수 있습니다. 이렇게 하려면 커뮤니티 간 코드를 복사해야 합니다.",
    "admins_moderators": "관리자 및 중재자",
    "remove_msg": "이 주제를 삭제하면 되돌릴 수 없는 조치입니다!",
    "remove": "주제 제거",
    "main_post_removed_msg": "작성자 또는 관리자가 메인 게시물을 삭제했습니다!",
    "delete_dialog": {
      "title": "주제 제거",
      "message": "이 주제를 삭제하시겠습니까?",
      "actions": "예, 지금 삭제"
    },
    "statistics": "카테고리 통계"
  },
  "community": {
    "disabled": "커뮤니티가 비활성화되었습니다!",
    "community_url": "커뮤니티 페이지 열기",
    "edit": "커뮤니티 수정",
    "install": "지금 설치",
    "start_community_message": "놀라운 커뮤니티를 시작하세요.",
    "shop_community_setting": "커뮤니티 구성",
    "regime": "커뮤니티 체제",
    "need_verify_to_create_message": "훌륭한 커뮤니티를 완전히 무료로 만들려면 다음 단계를 통과하세요.",
    "name": "이름",
    "name_plc": "내 커뮤니티 이름...",
    "name_msg": "커뮤니티의 고유한 사용자 이름 설정",
    "title": "제목",
    "title_plc": "놀라운 커뮤니티 제목...",
    "title_msg": "커뮤니티에 대한 구체적이고 포괄적인 제목 설정",
    "desc": "설명",
    "desc_plc": "이 커뮤니티에 대해...",
    "desc_msg": "이 커뮤니티에 대한 간단한 설명",
    "enable_msg": "커뮤니티를 활성화하거나 비활성화할 수 있습니다.",
    "hide_rule": "규칙 숨기기",
    "edit_rule": "규칙 수정",
    "rule_plc": "커뮤니티 규칙 작성...",
    "statistics": "커뮤니티 통계"
  },
  "access": {
    "admins": "관리자",
    "moderators": "중재자",
    "manage_admins": "관리자 관리",
    "manage_moderators": "중재자 관리",
    "add_moderator": "중재자 추가"
  },
  "category": {
    "add_new": "새 카테고리 추가",
    "add_new_msg": "총 20개의 카테고리를 만들 수 있습니다. 커뮤니티 액세스를 편리하고 쉽게 접근할 수 있도록 하는 것으로 충분합니다.",
    "title": "제목",
    "title_plc": "놀라운 카테고리...",
    "title_msg": "카테고리에 대한 구체적이고 포괄적인 제목 설정",
    "desc": "설명",
    "desc_plc": "이 카테고리에 대해...",
    "desc_msg": "이 카테고리에 대한 간단한 설명",
    "restrict": "제한 모드",
    "restrict_msg": "중재자만 주제를 만들 수 있습니까?",
    "statistics": "카테고리 통계",
    "remove_msg": "이 카테고리를 제거하면 되돌릴 수 없는 조치입니다!",
    "delete_dialog": {
      "title": "카테고리 제거",
      "message": "이 카테고리를 삭제하시겠습니까?",
      "actions": "예, 지금 삭제"
    }
  },
  "invite": {
    "not_have_profile_error": "이 사용자는 프로필을 작성하지 않았습니다!",
    "nominated_before_error": "이 사용자는 이전에 지명되었습니다!",
    "verified_before_error": "이 프로필은 이전에 Selldone 글로벌 커뮤니티에서 확인되었습니다!",
    "send_invite_msg": "친구에게 이 메시지 보내기"
  },
  "post_actions": {
    "save": "구하다",
    "save_msg": "나중에 저장",
    "copy_code": "코드 복사",
    "copy_link": "링크 복사",
    "copy_link_msg": "포스팅 바로가기",
    "embed": "이 게시물 삽입",
    "embed_msg": "Embed html 복사 및 붙여넣기",
    "edit": "게시물 수정",
    "edit_msg": "게시물 내용 변경",
    "report_msg": "이 게시물이 부적절합니까?",
    "delete": "게시물 삭제",
    "delete_msg": "이 게시물 삭제",
    "approved": "승인된 게시물",
    "approve_action": "수락된 것으로 표시",
    "approved_msg": "이 게시물을 승인된 답변으로 설정",
    "delete_dialog": {
      "title": "게시물 삭제",
      "message": "이 게시물을 삭제하시겠습니까?",
      "action": "예, 지금 삭제"
    }
  },
  "comment_actions": {
    "edit": "댓글 수정",
    "link": "댓글 링크",
    "link_msg": "댓글을 공유하려면 링크 복사",
    "edit_msg": "댓글 내용 변경",
    "delete": "삭제",
    "delete_msg": "이 댓글 삭제",
    "delete_dialog": {
      "title": "댓글 삭제",
      "message": "이 댓글을 삭제하시겠습니까?",
      "action": "예, 지금 삭제"
    }
  },
  "embed": {
    "copy_code_msg": "코드를 지나 복사",
    "copy_code": "코드 복사"
  }
};