export default {
  "commons": {
    "approved": "Genehmegt",
    "trend": "Trend",
    "like": "Wéi",
    "share": "Deelen",
    "comment": "Kommentéieren",
    "view_insight": "View Abléck",
    "trial_mode": "Prouf Modus",
    "no_trial_mode": "Keng fräi Period",
    "nofollow": "Nofollow",
    "cross": "Kräiz",
    "pin": "Pin op erop",
    "private": "Privat Sall",
    "text": "Text",
    "voice": "Stëmm",
    "video": "Video",
    "link": "Link",
    "image": "Bild",
    "product": "Produit",
    "seo": "SEO",
    "configuration": "Configuratioun",
    "monetize": "Monetiséieren",
    "subscription_fee": "Abonnementskäschte",
    "login_msg": "Start Är Gemeinschaftsrees",
    "topic": "Thema",
    "topic_title": "Thema Titel",
    "categories": "Kategorien",
    "author": "Auteur",
    "reply": "Äntwert",
    "reports": "Rapport(en)",
    "show_more": "Méi weisen..",
    "disagree": "Desaccord",
    "agree": "Averstanen",
    "suggestion_list": "Virschlag fir Iech",
    "following_action": "Follegt",
    "follow_action": "Follegt",
    "rules_violation": "Är Gemeinschaft Gesiicht mat Regele Verletzung Ëmstänn!",
    "cross_community": "Kräiz Communautéit",
    "crossable": "Kräiz kënnen",
    "crossable_msg": "Aner Communautéiten kënnen Kräiz Themen vun Tour Communautéit schafen",
    "nofollow_msg": "Füügt nofollow Tag fir all Linken",
    "topics": "Themen",
    "posts": "Posts",
    "comments": "Kommentaren",
    "total": "Ganzen",
    "user_reactions": "Benotzer Reaktioune",
    "impressions": "Impressiounen",
    "reactions": "Reaktiounen",
    "saves": "Spuert",
    "embeds": "Embeds",
    "shares": "Aktien",
    "you_are_admin": "Dir sidd en Admin",
    "you_are_moderator": "Dir sidd e Moderator",
    "invite_friend": "Invitéiert mäi Frënd",
    "nominate_friend": "Nominéiert mäi Frënd",
    "request_nominate": "Frot een deen Iech nominéiert!",
    "show_deleted_posts": "Show geläscht posts",
    "moderators": "Moderatoren",
    "analytics": "Analytics",
    "edit": "Edit",
    "notify": "Notifikatioun",
    "rules": "Regelen",
    "explore": "Entdeckt",
    "my_feed": "Ech",
    "blocked_message": "Dir sidd blockéiert bis",
    "reported": "Rapportéiert",
    "report": "Rapport"
  },
  "invite_message": "{user} huet Iech op de Forum {community} invitéiert. Klickt op de Link hei ënnen fir d'Beobachtungen vun Äre Frënn ze liesen an Är Meenung mat hinnen ze deelen. Ech waarden op dech.",
  "subscription_type": {
    "MONTHLY": "Mount",
    "SEASONAL": "saisonal",
    "YEARLY": "Jährlech",
    "LIFETIME": "Liewenszäit"
  },
  "trial_type": {
    "TRIO": "3 Deeg fräi",
    "WEEK": "Eng Woch fräi",
    "MONTH": "Ee Mount gratis"
  },
  "post_reaction": {
    "LIKE": "Léift",
    "SMILE": "Glécklech",
    "CLAP": "Klappt",
    "IDEA": "Iddi",
    "DISAGREE": "Desaccord"
  },
  "post_action": {
    "comments": "Kommentaren",
    "impressions": "Impressiounen",
    "saves": "Spuert",
    "shares": "Aktien",
    "embeds": "Embeds",
    "reports": "Berichter"
  },
  "nominate": {
    "note": "Dir kënnt een nominéieren deen Dir kennt. Wann dës Persoun net scho vun enger anerer Persoun guttgeheescht gouf, gitt Dir als Verifizéierer ugemellt. Äre Frënd muss Member vu Selldone sinn ier Dir se nominéiere kënnt.",
    "no_credit_message": "Leider hutt Dir net genuch Kreditt fir een aneren ze stëmmen, awer Dir kritt dëse Kreditt geschwënn. Kuckt w.e.g. an den nächsten Deeg.",
    "title": "Nominéiert Äre Frënd",
    "remains_credit": "Äre Kreditt fir anerer ze nominéieren",
    "user_nominate": "Wielt Äre Frënd",
    "action": "Nominéieren"
  },
  "stage_level": {
    "PUBLIC": "All Benotzer",
    "PRIVATE": "Nëmme Moderatoren",
    "VERIFIED": "All verifizéiert Benotzer"
  },
  "widget": {
    "offensive_message": "Dëse Kommentar ass beleidegend!",
    "topic": "Thema"
  },
  "editor": {
    "topic_title": "Thema Titel",
    "topic_desc": "Thema Beschreiwung",
    "send_post": "Schécken Post",
    "no_link": "Kee Link",
    "add_link": "Add Link",
    "add_video": "Video addéieren",
    "add_image": "Foto derbäi",
    "no_subscription": "Kee Monetiséierungsplang",
    "nofollow_msg": "Füügt nofollow op all Linken",
    "cross_msg": "Kann Kräiz Thema aus dësem Thema schafen",
    "pin_msg": "Pin dëst Thema un Top vun Themen an der Kategorie",
    "private_on_msg": "Nëmmen Admin & Moderatore kënnen dëst Thema gesinn",
    "private_off_msg": "Jidderee kann dëst Thema gesinn",
    "topic_placeholder": "Erstaunlechen Thema Titel hei ...",
    "desc_placeholder": "Kuerz Beschreiwung zum Thema ...",
    "title_placeholder": "Wat ass Är Fro, Thema oder ...?",
    "body_placeholder": "Schreift en neie Post ...",
    "remove_poll": "Ewechzehuelen Ëmfro",
    "take_screenshot": "Huelt als Cover",
    "take_link_msg": "Vergaangenheet Link hei a gitt",
    "eligible_title": "Schrëtt fir Usproch ze posten"
  },
  "tips": {
    "verify_email": "Gitt an z'iwwerpréiwen Är E-Mail.",
    "verify_phone": "Verifizéiert Ären Telefon.",
    "need_nominate": "Nominéiert vun engem oder Ufro fir z'iwwerpréiwen."
  },
  "regime": {
    "Aristocracy": "Aristokratie",
    "Timocracy": "Timokratie",
    "Oligarchy": "Oligarchie",
    "Democracy": "Demokratie",
    "Tyranny": "Tyrannei"
  },
  "comment": {
    "comment_plc": "Füügt e Kommentar ...",
    "comment_response_plc": "Äntwert op {name}...",
    "first_comment": "Gitt éischt Kommentar ..."
  },
  "filter": {
    "created_at": "Déi lescht",
    "created_at_asc": "Pionéier",
    "positive_reactions": "Am meeschte gär",
    "engaged": "Am meeschten engagéiert",
    "all_posts": "All Posts",
    "media_only": "Nëmmen Medien"
  },
  "topic": {
    "add_topic": "Füügt neit Thema",
    "add_topic_desc": "Éischt Sich iwwer Äert Thema! Erstellt guer keng duplizéiert Themen, well se vun de Moderatore geläscht ginn.",
    "can_create": "Kann duerch schafen",
    "add_cross": "Füügt Kräiz Thema",
    "add_cross_desc": "Dir kënnt gemeinsame thread mat anere Gemeinschaften erstellen. Fir dëst ze maachen, musst Dir de Cross-Community Code kopéieren.",
    "admins_moderators": "Administrateuren & Moderatoren",
    "remove_msg": "Wann Dir dëst Thema läscht, ass et eng irreversibel Aktioun!",
    "remove": "Ewechzehuelen Thema",
    "main_post_removed_msg": "Main Post gouf vum Auteur oder Admin geläscht!",
    "delete_dialog": {
      "title": "Ewechzehuelen Thema",
      "message": "Sidd Dir sécher dëst Thema läschen?",
      "actions": "Jo, Elo läschen"
    },
    "statistics": "Kategorie Statistiken"
  },
  "community": {
    "disabled": "Är Gemeinschaft behënnert!",
    "community_url": "Open Communautéit Säit",
    "edit": "Gemeinschaft änneren",
    "install": "Installéiert elo",
    "start_community_message": "Start Är erstaunlech Gemeinschaft.",
    "shop_community_setting": "Gemeinschaftskonfiguratiounen",
    "regime": "Communautéit Regime",
    "need_verify_to_create_message": "Fir Är grouss Gemeinschaft komplett gratis ze kreéieren, passéiert dës Schrëtt",
    "name": "Numm",
    "name_plc": "meng Gemeinschaftsnumm ...",
    "name_msg": "Setzt en eenzegaartege Benotzernumm fir Är Gemeinschaft",
    "title": "Titel",
    "title_plc": "E puer erstaunlech Gemeinschaftstitel ...",
    "title_msg": "Setzt e spezifeschen an ëmfaassenden Titel fir Gemeinschaft",
    "desc": "Beschreiwung",
    "desc_plc": "Iwwer dës Gemeinschaft ...",
    "desc_msg": "Eng kuerz Beschreiwung iwwer dës Gemeinschaft",
    "enable_msg": "Dir kënnt Är Gemeinschaft aktivéieren oder deaktivéieren",
    "hide_rule": "Regel verstoppen",
    "edit_rule": "Regel änneren",
    "rule_plc": "Schreift Är Gemeinschaftsregelen ...",
    "statistics": "Communautéit Statistiken"
  },
  "access": {
    "admins": "Administrateuren",
    "moderators": "Moderatoren",
    "manage_admins": "Verwalte Administrateuren",
    "manage_moderators": "Verwalte Moderatoren",
    "add_moderator": "Moderator addéieren"
  },
  "category": {
    "add_new": "Füügt eng nei Kategorie",
    "add_new_msg": "Dir kënnt am Ganzen 20 Kategorien erstellen. Et ass méi wéi genuch fir Är Gemeinschaftszougang bequem a méi erreechbar ze halen.",
    "title": "Titel",
    "title_plc": "Eng erstaunlech Kategorie ...",
    "title_msg": "Setzt e spezifeschen an ëmfaassenden Titel fir Kategorie",
    "desc": "Beschreiwung",
    "desc_plc": "Iwwer dës Kategorie ...",
    "desc_msg": "Eng kuerz Beschreiwung iwwer dës Kategorie",
    "restrict": "Modus beschränken",
    "restrict_msg": "Nëmme Moderatore kënnen Thema erstellen?",
    "statistics": "Kategorie Statistiken",
    "remove_msg": "Wann Dir dës Kategorie läscht, ass et eng irreversibel Aktioun!",
    "delete_dialog": {
      "title": "Kategorie ewechhuelen",
      "message": "Sidd Dir sécher dës Kategorie läschen?",
      "actions": "Jo, Elo läschen"
    }
  },
  "invite": {
    "not_have_profile_error": "Dëse Benotzer fëllt säi Profil net aus!",
    "nominated_before_error": "Dëse Benotzer nominéiert virdrun!",
    "verified_before_error": "Dëse Profil iwwerpréift vun der Selldone globaler Gemeinschaft virdrun!",
    "send_invite_msg": "Schéckt dëse Message un Är Frënn"
  },
  "post_actions": {
    "save": "Spueren",
    "save_msg": "Späichert fir spéider",
    "copy_code": "Code kopéieren",
    "copy_link": "Link kopéieren",
    "copy_link_msg": "Direkte Link op de Post",
    "embed": "Embed dëse Post",
    "embed_msg": "Copy & past embed html",
    "edit": "Post änneren",
    "edit_msg": "Ännert de Postinhalt",
    "report_msg": "Ass dëse Post onpassend?",
    "delete": "Läschen Post",
    "delete_msg": "Ewechzehuelen dësem Post",
    "approved": "Genehmegt Post",
    "approve_action": "Mark als ugeholl",
    "approved_msg": "Setzt dëse Post als guttgeheescht Äntwert",
    "delete_dialog": {
      "title": "Läschen Post",
      "message": "Sidd Dir sécher dëse Post läschen?",
      "action": "Jo, Elo läschen"
    }
  },
  "comment_actions": {
    "edit": "Kommentar änneren",
    "link": "Link ze kommentéieren",
    "link_msg": "Kopie Link fir de Kommentar ze deelen",
    "edit_msg": "Änneren Äre Kommentar Inhalt",
    "delete": "Läschen",
    "delete_msg": "Dëse Kommentar läschen",
    "delete_dialog": {
      "title": "Läschen Kommentar",
      "message": "Sidd Dir sécher dëse Kommentar läschen?",
      "action": "Jo, Elo läschen"
    }
  },
  "embed": {
    "copy_code_msg": "Kopie laanscht de Code",
    "copy_code": "Code kopéieren"
  }
};