export default {
  "commons": {
    "approved": "Patvirtinta",
    "trend": "Tendencija",
    "like": "Kaip",
    "share": "Dalintis",
    "comment": "komentuoti",
    "view_insight": "Žiūrėti įžvalgas",
    "trial_mode": "Bandomasis režimas",
    "no_trial_mode": "Nėra laisvo laikotarpio",
    "nofollow": "Nofollow",
    "cross": "Kirsti",
    "pin": "Prisegti prie viršaus",
    "private": "Privatus kambarys",
    "text": "Tekstas",
    "voice": "Balsas",
    "video": "Vaizdo įrašas",
    "link": "Nuoroda",
    "image": "Vaizdas",
    "product": "Produktas",
    "seo": "SEO",
    "configuration": "Konfigūracija",
    "monetize": "Gaukite pajamų",
    "subscription_fee": "Prenumeratos mokestis",
    "login_msg": "Pradėkite savo bendruomenės kelionę",
    "topic": "Tema",
    "topic_title": "Temos pavadinimas",
    "categories": "Kategorijos",
    "author": "Autorius",
    "reply": "Atsakyti",
    "reports": "ataskaita (-os)",
    "show_more": "Rodyti daugiau..",
    "disagree": "Nesutikti",
    "agree": "Sutinku",
    "suggestion_list": "Pasiūlymas tau",
    "following_action": "Sekant",
    "follow_action": "Sekite",
    "rules_violation": "Jūsų bendruomenė susiduria su taisyklių pažeidimo aplinkybe!",
    "cross_community": "Kryžiaus bendruomenė",
    "crossable": "Kryžius gali",
    "crossable_msg": "Kitos bendruomenės gali kurti kelias temas pagal kelionių bendruomenę",
    "nofollow_msg": "Visoms nuorodoms pridėkite nofollow žymą",
    "topics": "Temos",
    "posts": "Įrašai",
    "comments": "komentarai",
    "total": "Iš viso",
    "user_reactions": "Vartotojų reakcijos",
    "impressions": "Įspūdžiai",
    "reactions": "Reakcijos",
    "saves": "Išsaugo",
    "embeds": "Įterpiama",
    "shares": "Akcijos",
    "you_are_admin": "Jūs esate administratorius",
    "you_are_moderator": "Jūs esate moderatorius",
    "invite_friend": "Pakviesk mano draugą",
    "nominate_friend": "Paskirkite mano draugą",
    "request_nominate": "Paprašykite, kad kas nors jus nominuotų!",
    "show_deleted_posts": "Rodyti ištrintus įrašus",
    "moderators": "Moderatoriai",
    "analytics": "Analizė",
    "edit": "Redaguoti",
    "notify": "Pranešti",
    "rules": "Taisyklės",
    "explore": "Naršyti",
    "my_feed": "Aš",
    "blocked_message": "Esate užblokuotas iki",
    "reported": "Pranešta",
    "report": "Pranešimas",
    "post": "Įrašas",
    "attach_file": "Pridėti failą"
  },
  "invite_message": "{user} pakvietė jus į forumą {community}. Spustelėkite toliau esančią nuorodą, kad perskaitytumėte savo draugų pastebėjimus ir pasidalykite savo nuomone su jais. Laukiu tavęs.",
  "subscription_type": {
    "MONTHLY": "Kas mėnesį",
    "SEASONAL": "Sezoninis",
    "YEARLY": "Kasmet",
    "LIFETIME": "Gyvenimas"
  },
  "trial_type": {
    "TRIO": "3 dienos nemokamai",
    "WEEK": "Viena savaitė nemokamai",
    "MONTH": "Vienas mėnuo nemokamai"
  },
  "post_reaction": {
    "LIKE": "Meilė",
    "SMILE": "laimingas",
    "CLAP": "Plojimai",
    "IDEA": "Idėja",
    "DISAGREE": "Nesutikti"
  },
  "post_action": {
    "comments": "komentarai",
    "impressions": "Įspūdžiai",
    "saves": "Išsaugo",
    "shares": "Akcijos",
    "embeds": "Įterpiama",
    "reports": "Ataskaitos"
  },
  "nominate": {
    "note": "Galite paskirti ką nors, ką pažįstate. Jei šio asmens dar nepatvirtino kitas asmuo, būsite užregistruotas kaip jo tikrintojas. Jūsų draugas turi būti Selldone narys, kad galėtumėte jį paskirti.",
    "no_credit_message": "Deja, neturite pakankamai kredito, kad patvirtintumėte ką nors kitą, bet netrukus gausite šį kreditą. Patikrinkite per kelias ateinančias dienas.",
    "title": "Paskirkite savo draugą",
    "remains_credit": "Jūsų nuopelnas skiriant kitus",
    "user_nominate": "Pasirinkite savo draugą",
    "action": "Nominuoti"
  },
  "stage_level": {
    "PUBLIC": "Visi vartotojai",
    "PRIVATE": "Tik moderatoriai",
    "VERIFIED": "Visi patvirtinti vartotojai"
  },
  "widget": {
    "offensive_message": "Šis komentaras yra įžeidžiantis!",
    "topic": "Tema"
  },
  "editor": {
    "topic_title": "Temos pavadinimas",
    "topic_desc": "Temos aprašymas",
    "send_post": "Siųsti postą",
    "no_link": "Nėra nuorodos",
    "add_link": "Pridėti nuorodą",
    "add_video": "Pridėti vaizdo įrašą",
    "add_image": "Pridėti vaizdą",
    "no_subscription": "Nėra pajamų gavimo plano",
    "nofollow_msg": "Pridėkite nofollow prie visų nuorodų",
    "cross_msg": "Gali sukurti kryžminę temą iš šios temos",
    "pin_msg": "Prisekite šią temą prie kategorijos temų viršaus",
    "private_on_msg": "Šią temą gali matyti tik administratoriai ir moderatoriai",
    "private_off_msg": "Šią temą gali peržiūrėti bet kas",
    "topic_placeholder": "Nuostabus temos pavadinimas čia...",
    "desc_placeholder": "Trumpas temos aprašymas...",
    "title_placeholder": "Koks tavo klausimas, tema ar...?",
    "body_placeholder": "Rašyti naują įrašą...",
    "remove_poll": "Pašalinti apklausą",
    "take_screenshot": "Imk kaip priedangą",
    "take_link_msg": "Pasukite nuorodą čia ir įveskite",
    "eligible_title": "Veiksmai, skirti norint paskelbti",
    "public": "Viešas"
  },
  "tips": {
    "verify_email": "Įveskite ir patvirtinkite savo el.",
    "verify_phone": "Patvirtinkite savo telefoną.",
    "need_nominate": "Paskirti vienas arba prašyti patvirtinti."
  },
  "regime": {
    "Aristocracy": "Aristokratija",
    "Timocracy": "Timokratija",
    "Oligarchy": "Oligarchija",
    "Democracy": "Demokratija",
    "Tyranny": "Tironija"
  },
  "comment": {
    "comment_plc": "Pridėti komentarą...",
    "comment_response_plc": "Atsakymas {name}...",
    "first_comment": "Rašyti pirmą komentarą..."
  },
  "filter": {
    "created_at": "Naujausias",
    "created_at_asc": "Pionieriai",
    "positive_reactions": "Labiausiai patiko",
    "engaged": "Labiausiai užsiėmę",
    "all_posts": "Visi įrašai",
    "media_only": "Tik žiniasklaida"
  },
  "topic": {
    "add_topic": "Pridėti naują temą",
    "add_topic_desc": "Pirmiausia ieškokite savo temos! Visiškai nekurkite pasikartojančių temų, nes jas pašalins moderatoriai.",
    "can_create": "Gali sukurti pagal",
    "add_cross": "Pridėti kryžminę temą",
    "add_cross_desc": "Galite sukurti bendrų gijų su kitomis bendruomenėmis. Norėdami tai padaryti, turite nukopijuoti kelių bendruomenių kodą.",
    "admins_moderators": "Administratoriai ir moderatoriai",
    "remove_msg": "Jei pašalinsite šią temą, tai bus negrįžtamas veiksmas!",
    "remove": "Pašalinti temą",
    "main_post_removed_msg": "Pagrindinį įrašą pašalino autorius arba administratorius!",
    "delete_dialog": {
      "title": "Pašalinti temą",
      "message": "Ar tikrai ištrinti šią temą?",
      "actions": "Taip, ištrinti dabar"
    },
    "statistics": "Kategorijų statistika"
  },
  "community": {
    "disabled": "Jūsų bendruomenė išjungta!",
    "community_url": "Atidarykite bendruomenės puslapį",
    "edit": "Redaguoti bendruomenę",
    "install": "Įdiegti dabar",
    "start_community_message": "Pradėkite savo nuostabią bendruomenę.",
    "shop_community_setting": "bendruomenės konfigūracijos",
    "regime": "Bendrijos režimas",
    "need_verify_to_create_message": "Norėdami sukurti savo puikią bendruomenę visiškai nemokamą, atlikite šiuos veiksmus",
    "name": "vardas",
    "name_plc": "mano bendruomenės vardas...",
    "name_msg": "Nustatykite unikalų savo bendruomenės vartotojo vardą",
    "title": "Pavadinimas",
    "title_plc": "Kažkoks nuostabus bendruomenės pavadinimas...",
    "title_msg": "Nustatykite konkretų ir išsamų bendruomenės pavadinimą",
    "desc": "apibūdinimas",
    "desc_plc": "Apie šią bendruomenę...",
    "desc_msg": "Trumpas šios bendruomenės aprašymas",
    "enable_msg": "Galite įjungti arba išjungti savo bendruomenę",
    "hide_rule": "Slėpti taisyklę",
    "edit_rule": "Redaguoti taisyklę",
    "rule_plc": "Parašykite savo bendruomenės taisykles...",
    "statistics": "Bendrijos statistika"
  },
  "access": {
    "admins": "Administratoriai",
    "moderators": "Moderatoriai",
    "manage_admins": "Tvarkyti administratorius",
    "manage_moderators": "Valdykite moderatorius",
    "add_moderator": "Pridėti moderatorių"
  },
  "category": {
    "add_new": "Pridėti naują kategoriją",
    "add_new_msg": "Iš viso galite sukurti 20 kategorijų. To daugiau nei pakankamai, kad jūsų bendruomenė būtų patogi ir lengviau pasiekiama.",
    "title": "Pavadinimas",
    "title_plc": "Kažkokia nuostabi kategorija...",
    "title_msg": "Nustatykite konkretų ir išsamų kategorijos pavadinimą",
    "desc": "apibūdinimas",
    "desc_plc": "Apie šią kategoriją...",
    "desc_msg": "Trumpas šios kategorijos aprašymas",
    "restrict": "Apriboti režimą",
    "restrict_msg": "Tik moderatoriai gali kurti temą?",
    "statistics": "Kategorijų statistika",
    "remove_msg": "Jei pašalinsite šią kategoriją, tai bus negrįžtamas veiksmas!",
    "delete_dialog": {
      "title": "Pašalinti kategoriją",
      "message": "Ar tikrai ištrinti šią kategoriją?",
      "actions": "Taip, ištrinti dabar"
    }
  },
  "invite": {
    "not_have_profile_error": "Šis vartotojas neužpildė savo profilio!",
    "nominated_before_error": "Šis vartotojas buvo nominuotas anksčiau!",
    "verified_before_error": "Šį profilį anksčiau patvirtino pasaulinė Selldone bendruomenė!",
    "send_invite_msg": "Išsiųskite šią žinutę savo draugams"
  },
  "post_actions": {
    "save": "Sutaupyti",
    "save_msg": "Išsaugoti ateičiai",
    "copy_code": "Nukopijuokite kodą",
    "copy_link": "Nukopijuoti nuorodą",
    "copy_link_msg": "Tiesioginė nuoroda į įrašą",
    "embed": "Įterpti šį įrašą",
    "embed_msg": "Nukopijuoti ir įterpti html",
    "edit": "Redaguoti įrašą",
    "edit_msg": "Pakeiskite įrašo turinį",
    "report_msg": "Ar šis įrašas netinkamas?",
    "delete": "Ištrinti įrašą",
    "delete_msg": "Pašalinti šį įrašą",
    "approved": "Patvirtintas įrašas",
    "approve_action": "Pažymėti kaip priimtą",
    "approved_msg": "Nustatyti šį įrašą kaip patvirtintą atsakymą",
    "delete_dialog": {
      "title": "Ištrinti įrašą",
      "message": "Ar tikrai ištrinate šį įrašą?",
      "action": "Taip, ištrinti dabar"
    }
  },
  "comment_actions": {
    "edit": "Redaguoti komentarą",
    "link": "Nuoroda į komentarą",
    "link_msg": "Jei norite bendrinti komentarą, nukopijuokite nuorodą",
    "edit_msg": "Pakeiskite komentaro turinį",
    "delete": "Ištrinti",
    "delete_msg": "Ištrinti šį komentarą",
    "delete_dialog": {
      "title": "Ištrinti komentarą",
      "message": "Ar tikrai ištrinate šį komentarą?",
      "action": "Taip, ištrinti dabar"
    }
  },
  "embed": {
    "copy_code_msg": "Nukopijuokite kodą",
    "copy_code": "Nukopijuokite kodą"
  }
};