export default {
  "commons": {
    "approved": "Diluluskan",
    "trend": "Trend",
    "like": "Suka",
    "share": "Kongsi",
    "comment": "Komen",
    "view_insight": "Lihat cerapan",
    "trial_mode": "Mod percubaan",
    "no_trial_mode": "Tiada tempoh percuma",
    "nofollow": "Tidak ikut",
    "cross": "Menyeberang",
    "pin": "Sematkan ke atas",
    "private": "Bilik peribadi",
    "text": "Teks",
    "voice": "Suara",
    "video": "Video",
    "link": "Pautan",
    "image": "Gambar",
    "product": "produk",
    "seo": "SEO",
    "configuration": "Konfigurasi",
    "monetize": "Mengewangkan",
    "subscription_fee": "Yuran langganan",
    "login_msg": "Mulakan perjalanan komuniti anda",
    "topic": "Topik",
    "topic_title": "Tajuk topik",
    "categories": "Kategori",
    "author": "Pengarang",
    "reply": "Balas",
    "reports": "laporan",
    "show_more": "Tunjukkan lagi..",
    "disagree": "Tidak bersetuju",
    "agree": "Setuju",
    "suggestion_list": "Cadangan untuk anda",
    "following_action": "Mengikuti",
    "follow_action": "ikut",
    "rules_violation": "Komuniti anda menghadapi keadaan pelanggaran peraturan!",
    "cross_community": "Komuniti silang",
    "crossable": "Lintas boleh",
    "crossable_msg": "Komuniti lain boleh mencipta topik silang mengikut komuniti pelancongan",
    "nofollow_msg": "Tambah tag nofollow untuk semua pautan",
    "topics": "Topik",
    "posts": "Catatan",
    "comments": "Komen",
    "total": "Jumlah",
    "user_reactions": "Reaksi pengguna",
    "impressions": "Kesan",
    "reactions": "Reaksi",
    "saves": "Menjimatkan",
    "embeds": "Benam",
    "shares": "Saham",
    "you_are_admin": "Anda seorang pentadbir",
    "you_are_moderator": "Anda seorang moderator",
    "invite_friend": "Jemput kawan saya",
    "nominate_friend": "Calonkan kawan saya",
    "request_nominate": "Minta seseorang untuk mencalonkan anda!",
    "show_deleted_posts": "Tunjukkan siaran yang dipadamkan",
    "moderators": "Moderator",
    "analytics": "Analitis",
    "edit": "Sunting",
    "notify": "Maklumkan",
    "rules": "Peraturan",
    "explore": "Meneroka",
    "my_feed": "saya",
    "blocked_message": "Anda disekat sehingga",
    "reported": "Dilaporkan",
    "report": "Laporan"
  },
  "invite_message": "{user} telah menjemput anda ke forum {community}. Klik pada pautan di bawah untuk membaca pemerhatian rakan anda dan berkongsi pendapat anda dengan mereka. saya tunggu awak.",
  "subscription_type": {
    "MONTHLY": "Bulanan",
    "SEASONAL": "bermusim",
    "YEARLY": "setiap tahun",
    "LIFETIME": "Seumur hidup"
  },
  "trial_type": {
    "TRIO": "3 hari percuma",
    "WEEK": "Seminggu percuma",
    "MONTH": "Percuma sebulan"
  },
  "post_reaction": {
    "LIKE": "cinta",
    "SMILE": "gembira",
    "CLAP": "Bertepuk tangan",
    "IDEA": "Idea",
    "DISAGREE": "Tidak bersetuju"
  },
  "post_action": {
    "comments": "Komen",
    "impressions": "Kesan",
    "saves": "Menjimatkan",
    "shares": "Saham",
    "embeds": "Benam",
    "reports": "Laporan"
  },
  "nominate": {
    "note": "Anda boleh mencalonkan seseorang yang anda kenali. Jika orang ini belum diluluskan oleh orang lain, anda akan didaftarkan sebagai pengesah mereka. Rakan anda mesti menjadi ahli Selldone sebelum anda boleh mencalonkan mereka.",
    "no_credit_message": "Malangnya, anda tidak mempunyai kredit yang mencukupi untuk meluluskan orang lain, tetapi anda akan menerima kredit ini tidak lama lagi. Sila semak dalam beberapa hari akan datang.",
    "title": "Calonkan rakan anda",
    "remains_credit": "Kredit anda untuk mencalonkan orang lain",
    "user_nominate": "Pilih rakan anda",
    "action": "mencalonkan"
  },
  "stage_level": {
    "PUBLIC": "Semua pengguna",
    "PRIVATE": "Hanya moderator",
    "VERIFIED": "Semua pengguna yang disahkan"
  },
  "widget": {
    "offensive_message": "Komen ini menyinggung perasaan!",
    "topic": "Topik"
  },
  "editor": {
    "topic_title": "Tajuk topik",
    "topic_desc": "Penerangan topik",
    "send_post": "Hantar pos",
    "no_link": "Tiada pautan",
    "add_link": "Tambah pautan",
    "add_video": "Tambah video",
    "add_image": "Tambah imej",
    "no_subscription": "Tiada pelan pengewangan",
    "nofollow_msg": "Tambahkan nofollow pada semua pautan",
    "cross_msg": "Boleh membuat topik silang daripada topik ini",
    "pin_msg": "Sematkan topik ini ke bahagian atas topik dalam kategori",
    "private_on_msg": "Hanya pentadbir & moderator boleh melihat topik ini",
    "private_off_msg": "Sesiapa sahaja boleh melihat topik ini",
    "topic_placeholder": "Tajuk topik yang menarik di sini...",
    "desc_placeholder": "Penerangan ringkas tentang topik...",
    "title_placeholder": "Apakah soalan anda, topik atau ...?",
    "body_placeholder": "Tulis catatan baharu...",
    "remove_poll": "Alih keluar tinjauan pendapat",
    "take_screenshot": "Ambil sebagai perlindungan",
    "take_link_msg": "Pautan lepas di sini dan masukkan",
    "eligible_title": "Langkah untuk layak menyiarkan"
  },
  "tips": {
    "verify_email": "Masukkan dan sahkan e-mel anda.",
    "verify_phone": "Sahkan telefon anda.",
    "need_nominate": "Calonkan oleh seorang atau minta untuk mengesahkan."
  },
  "regime": {
    "Aristocracy": "Aristokrasi",
    "Timocracy": "Timokrasi",
    "Oligarchy": "Oligarki",
    "Democracy": "Demokrasi",
    "Tyranny": "Kezaliman"
  },
  "comment": {
    "comment_plc": "Tambah komen...",
    "comment_response_plc": "Respons kepada {name}...",
    "first_comment": "Letakkan komen pertama..."
  },
  "filter": {
    "created_at": "Yang terbaru",
    "created_at_asc": "Perintis",
    "positive_reactions": "Paling suka",
    "engaged": "Paling bertunang",
    "all_posts": "Semua jawatan",
    "media_only": "Media sahaja"
  },
  "topic": {
    "add_topic": "Tambah topik baharu",
    "add_topic_desc": "Carian pertama tentang topik anda! Jangan buat topik pendua sama sekali, kerana ia akan dialih keluar oleh moderator.",
    "can_create": "Boleh buat oleh",
    "add_cross": "Tambah topik silang",
    "add_cross_desc": "Anda boleh membuat urutan biasa dengan komuniti lain. Untuk melakukan ini, anda perlu menyalin kod merentas komuniti.",
    "admins_moderators": "Pentadbir & Moderator",
    "remove_msg": "Jika anda mengalih keluar topik ini, ia adalah tindakan yang tidak boleh diubah!",
    "remove": "Alih keluar topik",
    "main_post_removed_msg": "Siaran utama telah dialih keluar oleh pengarang atau pentadbir!",
    "delete_dialog": {
      "title": "Alih keluar topik",
      "message": "Adakah anda pasti memadamkan topik ini?",
      "actions": "Ya, Padam Sekarang"
    },
    "statistics": "Statistik kategori"
  },
  "community": {
    "disabled": "Komuniti anda kurang upaya!",
    "community_url": "Buka halaman komuniti",
    "edit": "Edit komuniti",
    "install": "Install sekarang",
    "start_community_message": "Mulakan komuniti anda yang menakjubkan.",
    "shop_community_setting": "Konfigurasi komuniti",
    "regime": "Rejim masyarakat",
    "need_verify_to_create_message": "Untuk mencipta komuniti hebat anda secara percuma, lulus langkah ini",
    "name": "nama",
    "name_plc": "nama-komuniti saya...",
    "name_msg": "Tetapkan nama pengguna yang unik untuk komuniti anda",
    "title": "Tajuk",
    "title_plc": "Beberapa gelaran komuniti yang menakjubkan...",
    "title_msg": "Tetapkan tajuk khusus dan komprehensif untuk komuniti",
    "desc": "Penerangan",
    "desc_plc": "Mengenai komuniti ini...",
    "desc_msg": "Penerangan ringkas tentang komuniti ini",
    "enable_msg": "Anda boleh mendayakan atau melumpuhkan komuniti anda",
    "hide_rule": "Sembunyikan peraturan",
    "edit_rule": "Edit peraturan",
    "rule_plc": "Tulis peraturan komuniti anda...",
    "statistics": "Statistik Komuniti"
  },
  "access": {
    "admins": "Pentadbir",
    "moderators": "Moderator",
    "manage_admins": "Urus pentadbir",
    "manage_moderators": "Urus moderator",
    "add_moderator": "Tambah moderator"
  },
  "category": {
    "add_new": "Tambah kategori baharu",
    "add_new_msg": "Anda boleh membuat sejumlah 20 kategori. Ia lebih daripada mencukupi, untuk memastikan akses komuniti anda mudah dan lebih mudah dicapai.",
    "title": "Tajuk",
    "title_plc": "Beberapa kategori yang menakjubkan...",
    "title_msg": "Tetapkan tajuk khusus dan komprehensif untuk kategori",
    "desc": "Penerangan",
    "desc_plc": "Mengenai kategori ini...",
    "desc_msg": "Penerangan ringkas tentang kategori ini",
    "restrict": "Mod sekatan",
    "restrict_msg": "Hanya moderator boleh membuat topik?",
    "statistics": "Statistik kategori",
    "remove_msg": "Jika anda mengalih keluar kategori ini, ia adalah tindakan yang tidak boleh dipulihkan!",
    "delete_dialog": {
      "title": "Alih keluar kategori",
      "message": "Adakah anda pasti memadamkan kategori ini?",
      "actions": "Ya, Padam Sekarang"
    }
  },
  "invite": {
    "not_have_profile_error": "Pengguna ini tidak melengkapkan profilnya!",
    "nominated_before_error": "Pengguna ini dicalonkan sebelum ini!",
    "verified_before_error": "Profil ini disahkan oleh komuniti global Seldone sebelum ini!",
    "send_invite_msg": "Hantar mesej ini kepada rakan anda"
  },
  "post_actions": {
    "save": "Jimat",
    "save_msg": "Simpan untuk kemudian",
    "copy_code": "Salin kod",
    "copy_link": "Salin pautan",
    "copy_link_msg": "Pautan terus ke siaran",
    "embed": "Benamkan siaran ini",
    "embed_msg": "Salin & lepas html benam",
    "edit": "Edit siaran",
    "edit_msg": "Tukar kandungan siaran",
    "report_msg": "Adakah siaran ini tidak sesuai?",
    "delete": "Padamkan siaran",
    "delete_msg": "Alih keluar siaran ini",
    "approved": "Jawatan yang diluluskan",
    "approve_action": "Tandakan sebagai diterima",
    "approved_msg": "Tetapkan siaran ini sebagai jawapan yang diluluskan",
    "delete_dialog": {
      "title": "Padamkan siaran",
      "message": "Adakah anda pasti memadamkan siaran ini?",
      "action": "Ya, Padam Sekarang"
    }
  },
  "comment_actions": {
    "edit": "Edit ulasan",
    "link": "Pautan untuk mengulas",
    "link_msg": "Salin pautan untuk berkongsi ulasan",
    "edit_msg": "Tukar kandungan ulasan anda",
    "delete": "Padam",
    "delete_msg": "Padamkan ulasan ini",
    "delete_dialog": {
      "title": "Padamkan ulasan",
      "message": "Adakah anda pasti memadamkan ulasan ini?",
      "action": "Ya, Padam Sekarang"
    }
  },
  "embed": {
    "copy_code_msg": "Salin melepasi kod",
    "copy_code": "Salin kod"
  }
};