export default {
  "commons": {
    "approved": "Godkjent",
    "trend": "Trend",
    "like": "Som",
    "share": "Dele",
    "comment": "Kommentar",
    "view_insight": "Se innsikt",
    "trial_mode": "Prøvemodus",
    "no_trial_mode": "Ingen ledig periode",
    "nofollow": "Ingen følgere",
    "cross": "Kryss",
    "pin": "Fest til toppen",
    "private": "Privat rom",
    "text": "Tekst",
    "voice": "Stemme",
    "video": "Video",
    "link": "Link",
    "image": "Bilde",
    "product": "Produkt",
    "seo": "SEO",
    "configuration": "Konfigurasjon",
    "monetize": "Tjen penger",
    "subscription_fee": "Abonnementsavgift",
    "login_msg": "Start din samfunnsreise",
    "topic": "Emne",
    "topic_title": "Emne tittel",
    "categories": "Kategorier",
    "author": "Forfatter",
    "reply": "Svare",
    "reports": "rapport(er)",
    "show_more": "Vis mer..",
    "disagree": "Være uenig",
    "agree": "Bli enige",
    "suggestion_list": "Forslag til deg",
    "following_action": "Følgende",
    "follow_action": "Følg",
    "rules_violation": "Samfunnet ditt står overfor brudd på regler!",
    "cross_community": "På tvers av samfunn",
    "crossable": "Cross stand",
    "crossable_msg": "Andre fellesskap kan lage tverr-emner etter turfellesskap",
    "nofollow_msg": "Legg til nofollow-tag for alle lenker",
    "topics": "Emner",
    "posts": "Innlegg",
    "comments": "Kommentarer",
    "total": "Total",
    "user_reactions": "Brukernes reaksjoner",
    "impressions": "Inntrykk",
    "reactions": "Reaksjoner",
    "saves": "Lagrer",
    "embeds": "Bygger inn",
    "shares": "Aksjer",
    "you_are_admin": "Du er en admin",
    "you_are_moderator": "Du er moderator",
    "invite_friend": "Inviter vennen min",
    "nominate_friend": "Nominer vennen min",
    "request_nominate": "Be noen om å nominere deg!",
    "show_deleted_posts": "Vis slettede innlegg",
    "moderators": "Moderatorer",
    "analytics": "Analytics",
    "edit": "Redigere",
    "notify": "Gi beskjed",
    "rules": "Regler",
    "explore": "Utforske",
    "my_feed": "Meg",
    "blocked_message": "Du er blokkert til",
    "reported": "Rapportert",
    "report": "Rapportere",
    "post": "Post",
    "attach_file": "Legg ved fil"
  },
  "invite_message": "{user} har invitert deg til forumet {community}. Klikk på lenken nedenfor for å lese vennenes observasjoner og dele din mening med dem. Jeg venter på deg.",
  "subscription_type": {
    "MONTHLY": "Månedlig",
    "SEASONAL": "Sesongbestemt",
    "YEARLY": "Årlig",
    "LIFETIME": "Livstid"
  },
  "trial_type": {
    "TRIO": "3 dager gratis",
    "WEEK": "En uke ledig",
    "MONTH": "En måned gratis"
  },
  "post_reaction": {
    "LIKE": "Kjærlighet",
    "SMILE": "Lykkelig",
    "CLAP": "Klapper",
    "IDEA": "Idé",
    "DISAGREE": "Være uenig"
  },
  "post_action": {
    "comments": "Kommentarer",
    "impressions": "Inntrykk",
    "saves": "Lagrer",
    "shares": "Aksjer",
    "embeds": "Bygger inn",
    "reports": "Rapporter"
  },
  "nominate": {
    "note": "Du kan nominere noen du kjenner. Hvis denne personen ikke allerede er godkjent av en annen person, vil du bli registrert som verifikatoren. Vennen din må være medlem av Selldone før du kan nominere dem.",
    "no_credit_message": "Dessverre har du ikke nok kreditt til å godkjenne noen andre, men du vil snart motta denne kreditten. Vennligst sjekk i løpet av de neste dagene.",
    "title": "Nominer vennen din",
    "remains_credit": "Din kreditt for å nominere andre",
    "user_nominate": "Velg vennen din",
    "action": "Innstille"
  },
  "stage_level": {
    "PUBLIC": "Alle brukere",
    "PRIVATE": "Kun moderatorer",
    "VERIFIED": "Alle verifiserte brukere"
  },
  "widget": {
    "offensive_message": "Denne kommentaren er støtende!",
    "topic": "Emne"
  },
  "editor": {
    "topic_title": "Emne tittel",
    "topic_desc": "Emnebeskrivelse",
    "send_post": "Send innlegg",
    "no_link": "Ingen lenke",
    "add_link": "Legg til lenke",
    "add_video": "Legg til video",
    "add_image": "Legg til bilde",
    "no_subscription": "Ingen plan for inntektsgenerering",
    "nofollow_msg": "Legg til nofollow på alle lenker",
    "cross_msg": "Kan lage kryssemne fra dette emnet",
    "pin_msg": "Fest dette emnet til toppen av emner i kategorien",
    "private_on_msg": "Bare administratorer og moderatorer kan se dette emnet",
    "private_off_msg": "Alle kan se dette emnet",
    "topic_placeholder": "Fantastisk emnetittel her...",
    "desc_placeholder": "Kort beskrivelse av temaet...",
    "title_placeholder": "Hva er ditt spørsmål, emne eller ...?",
    "body_placeholder": "Skriv et nytt innlegg...",
    "remove_poll": "Fjern avstemningen",
    "take_screenshot": "Ta som dekke",
    "take_link_msg": "Tidligere lenke her og gå inn",
    "eligible_title": "Fremgangsmåte for å være kvalifisert til å legge ut",
    "public": "Offentlig"
  },
  "tips": {
    "verify_email": "Skriv inn og bekreft e-posten din.",
    "verify_phone": "Bekreft telefonen din.",
    "need_nominate": "Nominer av én eller be om å verifisere."
  },
  "regime": {
    "Aristocracy": "Aristokrati",
    "Timocracy": "Timokrati",
    "Oligarchy": "Oligarki",
    "Democracy": "Demokrati",
    "Tyranny": "Tyranni"
  },
  "comment": {
    "comment_plc": "Legg til en kommentar...",
    "comment_response_plc": "Svar til {name}...",
    "first_comment": "Legg inn første kommentar..."
  },
  "filter": {
    "created_at": "Senest",
    "created_at_asc": "Pionerer",
    "positive_reactions": "Mest likte",
    "engaged": "Mest engasjert",
    "all_posts": "Alle innlegg",
    "media_only": "Kun media"
  },
  "topic": {
    "add_topic": "Legg til nytt emne",
    "add_topic_desc": "Først søk om emnet ditt! Ikke lag dupliserte emner i det hele tatt, fordi de vil bli fjernet av moderatorene.",
    "can_create": "Kan lage av",
    "add_cross": "Legg til kryssemne",
    "add_cross_desc": "Du kan opprette felles tråder med andre fellesskap. For å gjøre dette må du kopiere koden på tvers av fellesskap.",
    "admins_moderators": "Administratorer og moderatorer",
    "remove_msg": "Hvis du fjerner dette emnet, er det en irreversibel handling!",
    "remove": "Fjern emnet",
    "main_post_removed_msg": "Hovedinnlegget er fjernet av forfatter eller admin!",
    "delete_dialog": {
      "title": "Fjern emnet",
      "message": "Er du sikker på at du sletter dette emnet?",
      "actions": "Ja, Slett nå"
    },
    "statistics": "Kategoristatistikk"
  },
  "community": {
    "disabled": "Samfunnet ditt er deaktivert!",
    "community_url": "Åpne fellesskapssiden",
    "edit": "Rediger fellesskap",
    "install": "Installere nå",
    "start_community_message": "Start ditt fantastiske fellesskap.",
    "shop_community_setting": "Fellesskapskonfigurasjoner",
    "regime": "Fellesskapsregime",
    "need_verify_to_create_message": "For å lage det flotte fellesskapet ditt helt gratis, bestå disse trinnene",
    "name": "Navn",
    "name_plc": "mitt-samfunnsnavn...",
    "name_msg": "Angi et unikt brukernavn for fellesskapet ditt",
    "title": "Tittel",
    "title_plc": "En fantastisk fellesskapstittel...",
    "title_msg": "Angi en spesifikk og omfattende tittel for fellesskapet",
    "desc": "Beskrivelse",
    "desc_plc": "Om dette fellesskapet...",
    "desc_msg": "En kort beskrivelse av dette fellesskapet",
    "enable_msg": "Du kan aktivere eller deaktivere fellesskapet ditt",
    "hide_rule": "Skjul regelen",
    "edit_rule": "Rediger regel",
    "rule_plc": "Skriv fellesskapets regler...",
    "statistics": "Samfunnsstatistikk"
  },
  "access": {
    "admins": "Administratorer",
    "moderators": "Moderatorer",
    "manage_admins": "Administrer administratorer",
    "manage_moderators": "Administrer moderatorer",
    "add_moderator": "Legg til moderator"
  },
  "category": {
    "add_new": "Legg til ny kategori",
    "add_new_msg": "Du kan opprette totalt 20 kategorier. Det er mer enn nok for å holde fellesskapets tilgang praktisk og mer tilgjengelig.",
    "title": "Tittel",
    "title_plc": "En fantastisk kategori...",
    "title_msg": "Angi en spesifikk og omfattende tittel for kategori",
    "desc": "Beskrivelse",
    "desc_plc": "Om denne kategorien...",
    "desc_msg": "En kort beskrivelse av denne kategorien",
    "restrict": "Begrensningsmodus",
    "restrict_msg": "Kun moderatorer kan lage emne?",
    "statistics": "Kategoristatistikk",
    "remove_msg": "Hvis du fjerner denne kategorien, er det en irreversibel handling!",
    "delete_dialog": {
      "title": "Fjern kategori",
      "message": "Er du sikker på at du sletter denne kategorien?",
      "actions": "Ja, Slett nå"
    }
  },
  "invite": {
    "not_have_profile_error": "Denne brukeren fullfører ikke profilen sin!",
    "nominated_before_error": "Denne brukeren nominert før!",
    "verified_before_error": "Denne profilen er verifisert av Selldones globale fellesskap før!",
    "send_invite_msg": "Send denne meldingen til vennene dine"
  },
  "post_actions": {
    "save": "Lagre",
    "save_msg": "Lagre til senere",
    "copy_code": "Kopier koden",
    "copy_link": "Kopier link",
    "copy_link_msg": "Direkte link til innlegget",
    "embed": "Bygg inn dette innlegget",
    "embed_msg": "Kopier og past inn embed html",
    "edit": "Rediger innlegg",
    "edit_msg": "Endre innleggets innhold",
    "report_msg": "Er dette innlegget upassende?",
    "delete": "Slett innlegget",
    "delete_msg": "Fjern dette innlegget",
    "approved": "Godkjent innlegg",
    "approve_action": "Merk som akseptert",
    "approved_msg": "Sett dette innlegget som godkjent svar",
    "delete_dialog": {
      "title": "Slett innlegget",
      "message": "Er du sikker på at du sletter dette innlegget?",
      "action": "Ja, Slett nå"
    }
  },
  "comment_actions": {
    "edit": "Rediger kommentar",
    "link": "Link til kommentar",
    "link_msg": "Kopier lenken for å dele kommentaren",
    "edit_msg": "Endre kommentarinnholdet ditt",
    "delete": "Slett",
    "delete_msg": "Slett denne kommentaren",
    "delete_dialog": {
      "title": "Slett kommentar",
      "message": "Er du sikker på at du sletter denne kommentaren?",
      "action": "Ja, Slett nå"
    }
  },
  "embed": {
    "copy_code_msg": "Kopier forbi koden",
    "copy_code": "Kopier koden"
  }
};