export default {
  "commons": {
    "approved": "Yakatenderwa",
    "trend": "Trend",
    "like": "Kuda",
    "share": "Share",
    "comment": "Comment",
    "view_insight": "Ona maonero",
    "trial_mode": "Muedzo mode",
    "no_trial_mode": "Hapana nguva yemahara",
    "nofollow": "Nofollow",
    "cross": "Muchinjikwa",
    "pin": "Pin kumusoro",
    "private": "Imba yega",
    "text": "Text",
    "voice": "Voice",
    "video": "Vhidhiyo",
    "link": "Link",
    "image": "Image",
    "product": "Product",
    "seo": "SEO",
    "configuration": "Configuration",
    "monetize": "Ita mari",
    "subscription_fee": "Muripo wekunyoresa",
    "login_msg": "Tanga rwendo rwako rwenharaunda",
    "topic": "Topic",
    "topic_title": "Musoro wenyaya",
    "categories": "Categories",
    "author": "Munyori",
    "reply": "Reply",
    "reports": "report(s)",
    "show_more": "Ratidza zvimwe..",
    "disagree": "Usabvumira",
    "agree": "Bvumiranai",
    "suggestion_list": "Mhinduro kwauri",
    "following_action": "Kutevera",
    "follow_action": "Tevera",
    "rules_violation": "Nharaunda yako yakatarisana nekutyorwa kwemitemo mamiriro!",
    "cross_community": "Cross community",
    "crossable": "Kuyambuka kugona",
    "crossable_msg": "Dzimwe nharaunda dzinogona kugadzira misoro mikuru nenharaunda yevashanyi",
    "nofollow_msg": "Wedzera nofollow tag kune ese ma link",
    "topics": "Topics",
    "posts": "Zvinyorwa",
    "comments": "Comments",
    "total": "Total",
    "user_reactions": "Maitiro evashandisi",
    "impressions": "Maonero",
    "reactions": "Reactions",
    "saves": "Saves",
    "embeds": "Embeds",
    "shares": "Shares",
    "you_are_admin": "Iwe uri admin",
    "you_are_moderator": "Uri mutungamiriri",
    "invite_friend": "Koka shamwari yangu",
    "nominate_friend": "Sarudza shamwari yangu",
    "request_nominate": "Kumbira mumwe munhu kuti akusarudzire!",
    "show_deleted_posts": "Ratidza zvakadzimwa",
    "moderators": "Vatungamiriri",
    "analytics": "Analytics",
    "edit": "Edit",
    "notify": "Zivisa",
    "rules": "Mitemo",
    "explore": "Explore",
    "my_feed": "Me",
    "blocked_message": "Wakavharwa kusvika",
    "reported": "Zvataurwa",
    "report": "Report",
    "post": "Post",
    "attach_file": "Batanidza faira"
  },
  "invite_message": "{user} akakukoka kuforamu {community}. Tinya pane iyi link iripazasi kuti uverenge zvakaonekwa neshamwari dzako uye ugovane maonero ako kwavari. Ndakakumirira.",
  "subscription_type": {
    "MONTHLY": "Monthly",
    "SEASONAL": "Mwaka",
    "YEARLY": "Gore negore",
    "LIFETIME": "Hupenyu hwose"
  },
  "trial_type": {
    "TRIO": "3 mazuva emahara",
    "WEEK": "Vhiki imwe yemahara",
    "MONTH": "Mwedzi mumwe mahara"
  },
  "post_reaction": {
    "LIKE": "Rudo",
    "SMILE": "Happy",
    "CLAP": "Kuombera maoko",
    "IDEA": "Idea",
    "DISAGREE": "Usabvumira"
  },
  "post_action": {
    "comments": "Comments",
    "impressions": "Maonero",
    "saves": "Saves",
    "shares": "Shares",
    "embeds": "Embeds",
    "reports": "Reports"
  },
  "nominate": {
    "note": "Unogona kudoma mumwe munhu waunoziva. Kana munhu uyu asati atopihwa mvumo nemumwe munhu, unonyoreswa semuongorori wavo. Shamwari yako inofanira kunge iri nhengo yeSelldone usati wavadoma.",
    "no_credit_message": "Nehurombo, iwe hauna chikwereti chakakwana chekubvumidza mumwe munhu, asi iwe uchagamuchira iyi kiredhiti nekukurumidza. Ndokumbira utarise mumazuva mashoma anotevera.",
    "title": "Sarudza shamwari yako",
    "remains_credit": "Chikwereti chako kudoma vamwe",
    "user_nominate": "Sarudza shamwari yako",
    "action": "Nominate"
  },
  "stage_level": {
    "PUBLIC": "Vese vashandisi",
    "PRIVATE": "Vatungamiriri chete",
    "VERIFIED": "Vese vashandisi vakasimbiswa"
  },
  "widget": {
    "offensive_message": "Mashoko aya anogumbura!",
    "topic": "Topic"
  },
  "editor": {
    "topic_title": "Musoro wenyaya",
    "topic_desc": "Tsanangudzo yemusoro",
    "send_post": "Send post",
    "no_link": "Hapana chinongedzo",
    "add_link": "Wedzera link",
    "add_video": "Wedzera vhidhiyo",
    "add_image": "Wedzera mufananidzo",
    "no_subscription": "Hapana chirongwa chekuita mari",
    "nofollow_msg": "Wedzera nofollow kune zvese zvinongedzo",
    "cross_msg": "Inogona kugadzira mhiri kwemusoro kubva pane ino musoro",
    "pin_msg": "Pina musoro uyu pamusoro pemisoro muchikamu",
    "private_on_msg": "Admin & moderator chete ndivo vanogona kuona nyaya iyi",
    "private_off_msg": "Chero ani zvake anogona kuona nyaya iyi",
    "topic_placeholder": "Inoshamisa musoro wenyaya pano...",
    "desc_placeholder": "Tsanangudzo pfupi nezvemusoro wenyaya...",
    "title_placeholder": "Ndeupi mubvunzo wako, musoro kana ...?",
    "body_placeholder": "Nyora chinyorwa chitsva...",
    "remove_poll": "Bvisa sarudzo",
    "take_screenshot": "Tora sebutiro",
    "take_link_msg": "Yapfuura link pano uye isa",
    "eligible_title": "Matanho ekukodzera kutumira",
    "public": "Veruzhinji"
  },
  "tips": {
    "verify_email": "Pinda uye simbisa email yako.",
    "verify_phone": "Simbisa foni yako.",
    "need_nominate": "Sarudza nemumwe kana kukumbira kuti uone."
  },
  "regime": {
    "Aristocracy": "Aristocracy",
    "Timocracy": "Timocracy",
    "Oligarchy": "Oligarchy",
    "Democracy": "Democracy",
    "Tyranny": "Udzvinyiriri"
  },
  "comment": {
    "comment_plc": "Wedzera mhinduro...",
    "comment_response_plc": "Mhinduro ku {name}...",
    "first_comment": "Isa mhinduro yekutanga..."
  },
  "filter": {
    "created_at": "Zvichangopfuura",
    "created_at_asc": "Mapiyona",
    "positive_reactions": "Vazhinji vaifarira",
    "engaged": "Vazhinji vakabatikana",
    "all_posts": "All posts",
    "media_only": "Media chete"
  },
  "topic": {
    "add_topic": "Wedzera musoro mutsva",
    "add_topic_desc": "Tanga watsvaga nezvenyaya yako! Usaite duplicate misoro zvachose, nekuti inobviswa nemamodhita.",
    "can_create": "Inogona kugadzira ne",
    "add_cross": "Add cross topic",
    "add_cross_desc": "Unogona kugadzira tambo dzakajairika nedzimwe nharaunda. Kuti uite izvi, unofanirwa kukopa iyo cross-community kodhi.",
    "admins_moderators": "Admins & Moderators",
    "remove_msg": "Kana ukabvisa musoro uyu, chiito chisingadzoreki!",
    "remove": "Bvisa musoro",
    "main_post_removed_msg": "Main post yabviswa nemunyori kana admin!",
    "delete_dialog": {
      "title": "Bvisa musoro",
      "message": "Une chokwadi chekudzima musoro uyu?",
      "actions": "Hongu, Delete Now"
    },
    "statistics": "Category statistics"
  },
  "community": {
    "disabled": "Nharaunda yako yakaremara!",
    "community_url": "Vhura peji renharaunda",
    "edit": "Rongedza nharaunda",
    "install": "Isa ikozvino",
    "start_community_message": "Tanga nharaunda yako inoshamisa.",
    "shop_community_setting": "Community configs",
    "regime": "Utongi hwenharaunda",
    "need_verify_to_create_message": "Kuti ugadzire nharaunda yako huru yemahara, pfuura matanho aya",
    "name": "Zita",
    "name_plc": "nharaunda-yangu-zita...",
    "name_msg": "Seta yakasarudzika zita remushandisi renharaunda yako",
    "title": "Title",
    "title_plc": "Imwe inoshamisa nharaunda zita ...",
    "title_msg": "Seta zita chairo uye rakazara renharaunda",
    "desc": "Tsanangudzo",
    "desc_plc": "Nezvenharaunda iyi...",
    "desc_msg": "Tsanangudzo pfupi pamusoro penharaunda iyi",
    "enable_msg": "Unogona kugonesa kana kudzima nharaunda yako",
    "hide_rule": "Viga mutemo",
    "edit_rule": "Edit mutemo",
    "rule_plc": "Nyora mitemo yenharaunda yako...",
    "statistics": "Community Statistics"
  },
  "access": {
    "admins": "Admins",
    "moderators": "Vatungamiriri",
    "manage_admins": "Manage admins",
    "manage_moderators": "Manage moderators",
    "add_moderator": "Wedzera mutungamiriri"
  },
  "category": {
    "add_new": "Wedzera chikamu chitsva",
    "add_new_msg": "Unogona kugadzira zvikamu makumi maviri. Zvinopfuura zvakakwana, kuchengetedza nharaunda yako kuwana zviri nyore uye zvakanyanya kusvikika.",
    "title": "Title",
    "title_plc": "Zvimwe zvinoshamisa chikamu...",
    "title_msg": "Seta chaiyo uye yakazara zita rechikamu",
    "desc": "Tsanangudzo",
    "desc_plc": "Nezve chikamu ichi...",
    "desc_msg": "Tsanangudzo pfupi nezvechikamu ichi",
    "restrict": "Restrict mode",
    "restrict_msg": "Vatungamiriri chete ndivo vanogona kugadzira musoro wenyaya?",
    "statistics": "Category statistics",
    "remove_msg": "Kana ukabvisa chikamu ichi, chiito chisingadzoreki!",
    "delete_dialog": {
      "title": "Bvisa chikamu",
      "message": "Une chokwadi chekudzima chikamu ichi?",
      "actions": "Hongu, Delete Now"
    }
  },
  "invite": {
    "not_have_profile_error": "Mushandisi uyu haana kupedzisa chimiro chake!",
    "nominated_before_error": "Mushandisi uyu akambodanwa!",
    "verified_before_error": "Iyi mbiri yakasimbiswa neSelldone yepasi rose nharaunda kare!",
    "send_invite_msg": "Tumira meseji iyi kushamwari dzako"
  },
  "post_actions": {
    "save": "Sevha",
    "save_msg": "Chengetedza gare gare",
    "copy_code": "Kopi kodhi",
    "copy_link": "Copy link",
    "copy_link_msg": "Yakananga link kune iyo post",
    "embed": "Embed this post",
    "embed_msg": "Kopa & yapfuura embed html",
    "edit": "Edit post",
    "edit_msg": "Shandura zvinyorwa zvepositi",
    "report_msg": "Iyi post haina kufanira here?",
    "delete": "Delete post",
    "delete_msg": "Bvisa chinyorwa ichi",
    "approved": "Chinyorwa chakabvumidzwa",
    "approve_action": "Maka sekugamuchirwa",
    "approved_msg": "Seta iyi positi semhinduro inotenderwa",
    "delete_dialog": {
      "title": "Delete post",
      "message": "Une chokwadi chekudzima chinyorwa ichi?",
      "action": "Hongu, Delete Now"
    }
  },
  "comment_actions": {
    "edit": "Rongedza mhinduro",
    "link": "Link kuti utaure",
    "link_msg": "Kopa link kuti ugovane mhinduro",
    "edit_msg": "Chinja zvauri kutaura",
    "delete": "Delete",
    "delete_msg": "Dzima mhinduro iyi",
    "delete_dialog": {
      "title": "Delete comment",
      "message": "Une chokwadi chekudzima chirevo ichi?",
      "action": "Hongu, Delete Now"
    }
  },
  "embed": {
    "copy_code_msg": "Kopa kupfuura kodhi",
    "copy_code": "Kopi kodhi"
  }
};