export default {
  "commons": {
    "approved": "Miratuar",
    "trend": "Trendi",
    "like": "si",
    "share": "Shpërndaje",
    "comment": "Komentoni",
    "view_insight": "Shiko njohuritë",
    "trial_mode": "Mënyra e provës",
    "no_trial_mode": "Nuk ka periudhë të lirë",
    "nofollow": "Nofollow",
    "cross": "kryq",
    "pin": "Gozhdoni në krye",
    "private": "Dhome private",
    "text": "Teksti",
    "voice": "Zëri",
    "video": "Video",
    "link": "Lidhje",
    "image": "Imazhi",
    "product": "Produkt",
    "seo": "SEO",
    "configuration": "Konfigurimi",
    "monetize": "Fito para",
    "subscription_fee": "Tarifë abonimi",
    "login_msg": "Filloni udhëtimin tuaj në komunitet",
    "topic": "Tema",
    "topic_title": "Titulli i temës",
    "categories": "Kategoritë",
    "author": "Autori",
    "reply": "Përgjigju",
    "reports": "raport(et)",
    "show_more": "Trego më shumë..",
    "disagree": "Nuk bie dakort",
    "agree": "Dakord",
    "suggestion_list": "Sugjerim për ju",
    "following_action": "duke ndjekur",
    "follow_action": "Ndiqni",
    "rules_violation": "Komuniteti juaj përballet me rrethana të shkeljes së rregullave!",
    "cross_community": "Kryq komuniteti",
    "crossable": "Kryq i aftë",
    "crossable_msg": "Komunitete të tjera mund të krijojnë tema të kryqëzuara sipas komunitetit të turneut",
    "nofollow_msg": "Shto etiketën nofollow për të gjitha lidhjet",
    "topics": "Temat",
    "posts": "Postimet",
    "comments": "Komentet",
    "total": "Total",
    "user_reactions": "Reagimet e përdoruesve",
    "impressions": "Përshtypjet",
    "reactions": "Reagimet",
    "saves": "kursen",
    "embeds": "Përfshin",
    "shares": "Aksionet",
    "you_are_admin": "Ju jeni një administrator",
    "you_are_moderator": "Jeni moderatore",
    "invite_friend": "Fto mikun tim",
    "nominate_friend": "Emëroni mikun tim",
    "request_nominate": "Kërkoni dikë që t'ju propozojë!",
    "show_deleted_posts": "Shfaq postimet e fshira",
    "moderators": "Moderatorët",
    "analytics": "Analiza",
    "edit": "Redakto",
    "notify": "Njoftoni",
    "rules": "Rregullat",
    "explore": "Eksploroni",
    "my_feed": "Unë",
    "blocked_message": "Jeni të bllokuar deri në",
    "reported": "Raportuar",
    "report": "Raportoni",
    "post": "Posto",
    "attach_file": "Bashkangjit skedarin"
  },
  "invite_message": "{user} ju ka ftuar në forumin {community}. Klikoni në linkun e mëposhtëm për të lexuar vëzhgimet e miqve tuaj dhe për të ndarë mendimin tuaj me ta. Unë jam duke pritur për ju.",
  "subscription_type": {
    "MONTHLY": "Mujore",
    "SEASONAL": "Sezonale",
    "YEARLY": "vjetore",
    "LIFETIME": "Jetëgjatësia"
  },
  "trial_type": {
    "TRIO": "3 dite falas",
    "WEEK": "Një javë falas",
    "MONTH": "Një muaj falas"
  },
  "post_reaction": {
    "LIKE": "Dashuria",
    "SMILE": "Gëzuar",
    "CLAP": "Duartrokitje",
    "IDEA": "Ideja",
    "DISAGREE": "Nuk bie dakort"
  },
  "post_action": {
    "comments": "Komentet",
    "impressions": "Përshtypjet",
    "saves": "kursen",
    "shares": "Aksionet",
    "embeds": "Përfshin",
    "reports": "Raportet"
  },
  "nominate": {
    "note": "Ju mund të emëroni dikë që njihni. Nëse ky person nuk është miratuar tashmë nga një person tjetër, ju do të regjistroheni si verifikues i tyre. Miku juaj duhet të jetë anëtar i Selldone përpara se të mund t'i emëroni ata.",
    "no_credit_message": "Fatkeqësisht, nuk keni kredi të mjaftueshme për të miratuar dikë tjetër, por së shpejti do ta merrni këtë kredit. Ju lutemi kontrolloni në ditët në vijim.",
    "title": "Emëroni mikun tuaj",
    "remains_credit": "Merita juaj për të emëruar të tjerët",
    "user_nominate": "Zgjidhni shokun tuaj",
    "action": "Emëroni"
  },
  "stage_level": {
    "PUBLIC": "Te gjithe perdoruesit",
    "PRIVATE": "Vetëm moderatorë",
    "VERIFIED": "Të gjithë përdoruesit e verifikuar"
  },
  "widget": {
    "offensive_message": "Ky koment është fyes!",
    "topic": "Tema"
  },
  "editor": {
    "topic_title": "Titulli i temës",
    "topic_desc": "Përshkrimi i temës",
    "send_post": "Dërgo postimin",
    "no_link": "Asnjë lidhje",
    "add_link": "Shto lidhje",
    "add_video": "Shto video",
    "add_image": "Shto imazh",
    "no_subscription": "Asnjë plan fitimi parash",
    "nofollow_msg": "Shto nofollow në të gjitha lidhjet",
    "cross_msg": "Mund të krijojë një temë të kryqëzuar nga kjo temë",
    "pin_msg": "Vendoseni këtë temë në krye të temave në kategori",
    "private_on_msg": "Vetëm administratorët dhe moderatorët mund ta shohin këtë temë",
    "private_off_msg": "Kushdo mund ta shohë këtë temë",
    "topic_placeholder": "Titulli i mrekullueshem i temes ketu...",
    "desc_placeholder": "Përshkrim i shkurtër rreth temës...",
    "title_placeholder": "Cila është pyetja juaj, tema apo ...?",
    "body_placeholder": "Shkruaj një postim të ri...",
    "remove_poll": "Hiq sondazhin",
    "take_screenshot": "Merrni si mbulesë",
    "take_link_msg": "Kaloni lidhjen këtu dhe futni",
    "eligible_title": "Hapat për t'u kualifikuar për të postuar",
    "public": "Publike"
  },
  "tips": {
    "verify_email": "Futni dhe verifikoni emailin tuaj.",
    "verify_phone": "Verifikoni telefonin tuaj.",
    "need_nominate": "Emëroni nga një ose kërkoni të verifikoni."
  },
  "regime": {
    "Aristocracy": "Aristokracia",
    "Timocracy": "Timokraci",
    "Oligarchy": "Oligarkia",
    "Democracy": "Demokraci",
    "Tyranny": "Tirania"
  },
  "comment": {
    "comment_plc": "Shto një koment...",
    "comment_response_plc": "Përgjigje për {name}...",
    "first_comment": "Vendos komentin e parë..."
  },
  "filter": {
    "created_at": "Me e fundit",
    "created_at_asc": "Pionierët",
    "positive_reactions": "Më të pëlqyerit",
    "engaged": "Më të angazhuarit",
    "all_posts": "Të gjitha postimet",
    "media_only": "Vetëm media"
  },
  "topic": {
    "add_topic": "Shto temë të re",
    "add_topic_desc": "Së pari kërkoni për temën tuaj! Mos krijoni fare tema dublikate, sepse ato do të hiqen nga moderatorët.",
    "can_create": "Mund të krijojë nga",
    "add_cross": "Shto temë të kryqëzuar",
    "add_cross_desc": "Ju mund të krijoni fije të përbashkëta me komunitetet e tjera. Për ta bërë këtë, ju duhet të kopjoni kodin ndër-komuniteti.",
    "admins_moderators": "Administratorët dhe Moderatorët",
    "remove_msg": "Nëse e hiqni këtë temë, është një veprim i pakthyeshëm!",
    "remove": "Hiq temën",
    "main_post_removed_msg": "Postimi kryesor është hequr nga autori ose administratori!",
    "delete_dialog": {
      "title": "Hiq temën",
      "message": "Jeni i sigurt që e fshini këtë temë?",
      "actions": "Po, Fshije Tani"
    },
    "statistics": "Statistikat e kategorive"
  },
  "community": {
    "disabled": "Komuniteti juaj është me aftësi të kufizuara!",
    "community_url": "Hapni faqen e komunitetit",
    "edit": "Redakto komunitetin",
    "install": "Instaloje tani",
    "start_community_message": "Filloni komunitetin tuaj të mrekullueshëm.",
    "shop_community_setting": "Konfigurimet e komunitetit",
    "regime": "Regjimi i komunitetit",
    "need_verify_to_create_message": "Për të krijuar komunitetin tuaj të madh plotësisht falas, kaloni këto hapa",
    "name": "Emri",
    "name_plc": "emri i komunitetit tim...",
    "name_msg": "Vendosni një emër përdoruesi unik për komunitetin tuaj",
    "title": "Titulli",
    "title_plc": "Një titull i mrekullueshëm i komunitetit...",
    "title_msg": "Vendosni një titull specifik dhe gjithëpërfshirës për komunitetin",
    "desc": "Përshkrim",
    "desc_plc": "Rreth këtij komuniteti...",
    "desc_msg": "Një përshkrim i shkurtër për këtë komunitet",
    "enable_msg": "Ju mund të aktivizoni ose çaktivizoni komunitetin tuaj",
    "hide_rule": "Rregulli i fshehjes",
    "edit_rule": "Redakto rregullin",
    "rule_plc": "Shkruani rregullat e komunitetit tuaj...",
    "statistics": "Statistikat e Komunitetit"
  },
  "access": {
    "admins": "Administratorët",
    "moderators": "Moderatorët",
    "manage_admins": "Menaxho administratorët",
    "manage_moderators": "Menaxho moderatorët",
    "add_moderator": "Shto moderator"
  },
  "category": {
    "add_new": "Shto kategori të re",
    "add_new_msg": "Mund të krijoni gjithsej 20 kategori. Është më se e mjaftueshme, për ta mbajtur aksesin në komunitet të përshtatshëm dhe më të arritshëm.",
    "title": "Titulli",
    "title_plc": "Një kategori e mahnitshme...",
    "title_msg": "Vendosni një titull specifik dhe gjithëpërfshirës për kategorinë",
    "desc": "Përshkrim",
    "desc_plc": "Rreth kësaj kategorie...",
    "desc_msg": "Një përshkrim i shkurtër për këtë kategori",
    "restrict": "Kufizo modalitetin",
    "restrict_msg": "Vetëm moderatorët mund të krijojnë temë?",
    "statistics": "Statistikat e kategorive",
    "remove_msg": "Nëse e hiqni këtë kategori, është një veprim i pakthyeshëm!",
    "delete_dialog": {
      "title": "Hiq kategorinë",
      "message": "Jeni të sigurt që e fshini këtë kategori?",
      "actions": "Po, Fshije Tani"
    }
  },
  "invite": {
    "not_have_profile_error": "Ky përdorues nuk e plotëson profilin e tij/saj!",
    "nominated_before_error": "Ky përdorues është nominuar më parë!",
    "verified_before_error": "Ky profil është verifikuar më parë nga komuniteti global i Selldone!",
    "send_invite_msg": "Dërgoni këtë mesazh miqve tuaj"
  },
  "post_actions": {
    "save": "Ruaj",
    "save_msg": "Ruani për më vonë",
    "copy_code": "Kopjo kodin",
    "copy_link": "Kopjo lidhjen",
    "copy_link_msg": "Lidhje direkte me postimin",
    "embed": "Vendos këtë postim",
    "embed_msg": "Kopjoni dhe kaloni embed html",
    "edit": "Redakto postimin",
    "edit_msg": "Ndryshoni përmbajtjen e postimit",
    "report_msg": "A është ky postim i papërshtatshëm?",
    "delete": "Fshi postimin",
    "delete_msg": "Hiqeni këtë postim",
    "approved": "Postimi i miratuar",
    "approve_action": "Shënoni si të pranuar",
    "approved_msg": "Vendoseni këtë postim si përgjigje të miratuar",
    "delete_dialog": {
      "title": "Fshi postimin",
      "message": "Jeni të sigurt që e fshini këtë postim?",
      "action": "Po, Fshije Tani"
    }
  },
  "comment_actions": {
    "edit": "Redakto komentin",
    "link": "Lidhja me komentin",
    "link_msg": "Kopjo lidhjen për të ndarë komentin",
    "edit_msg": "Ndryshoni përmbajtjen e komentit tuaj",
    "delete": "Fshije",
    "delete_msg": "Fshije këtë koment",
    "delete_dialog": {
      "title": "Fshi komentin",
      "message": "Jeni të sigurt që e fshini këtë koment?",
      "action": "Po, Fshije Tani"
    }
  },
  "embed": {
    "copy_code_msg": "Kopjojeni kodin",
    "copy_code": "Kopjo kodin"
  }
};