export default {
  "commons": {
    "approved": "Imeidhinishwa",
    "trend": "Mwenendo",
    "like": "Kama",
    "share": "Shiriki",
    "comment": "Maoni",
    "view_insight": "Tazama maarifa",
    "trial_mode": "Hali ya majaribio",
    "no_trial_mode": "Hakuna kipindi cha bure",
    "nofollow": "Hakuna kufuata",
    "cross": "Msalaba",
    "pin": "Bandika juu",
    "private": "Chumba cha kibinafsi",
    "text": "Maandishi",
    "voice": "Sauti",
    "video": "Video",
    "link": "Kiungo",
    "image": "Picha",
    "product": "Bidhaa",
    "seo": "SEO",
    "configuration": "Usanidi",
    "monetize": "Chuma mapato",
    "subscription_fee": "Ada ya usajili",
    "login_msg": "Anza safari yako ya jumuiya",
    "topic": "Mada",
    "topic_title": "Kichwa cha mada",
    "categories": "Kategoria",
    "author": "Mwandishi",
    "reply": "Jibu",
    "reports": "ripoti",
    "show_more": "Onyesha zaidi..",
    "disagree": "Usikubali",
    "agree": "Kubali",
    "suggestion_list": "Pendekezo kwako",
    "following_action": "Kufuatia",
    "follow_action": "Fuata",
    "rules_violation": "Jumuiya yako inakabiliwa na hali ya ukiukaji wa sheria!",
    "cross_community": "Jumuiya ya msalaba",
    "crossable": "Kuvuka uwezo",
    "crossable_msg": "Jumuiya zingine zinaweza kuunda mada tofauti kwa jumuiya ya watalii",
    "nofollow_msg": "Ongeza lebo ya nofollow kwa viungo vyote",
    "topics": "Mada",
    "posts": "Machapisho",
    "comments": "Maoni",
    "total": "Jumla",
    "user_reactions": "Maoni ya watumiaji",
    "impressions": "Maonyesho",
    "reactions": "Miitikio",
    "saves": "Huhifadhi",
    "embeds": "Kupachika",
    "shares": "Hisa",
    "you_are_admin": "Wewe ni msimamizi",
    "you_are_moderator": "Wewe ni msimamizi",
    "invite_friend": "Alika rafiki yangu",
    "nominate_friend": "Mteule rafiki yangu",
    "request_nominate": "Omba mtu akuteue!",
    "show_deleted_posts": "Onyesha machapisho yaliyofutwa",
    "moderators": "Wasimamizi",
    "analytics": "Uchanganuzi",
    "edit": "Hariri",
    "notify": "Arifu",
    "rules": "Kanuni",
    "explore": "Chunguza",
    "my_feed": "Mimi",
    "blocked_message": "Umezuiwa hadi",
    "reported": "Imeripotiwa",
    "report": "Ripoti"
  },
  "invite_message": "{user} amekualika kwenye mijadala ya {community}. Bofya kiungo kilicho hapa chini ili kusoma maoni ya marafiki zako na kushiriki maoni yako nao. nakungoja.",
  "subscription_type": {
    "MONTHLY": "Kila mwezi",
    "SEASONAL": "Msimu",
    "YEARLY": "Kila mwaka",
    "LIFETIME": "Maisha yote"
  },
  "trial_type": {
    "TRIO": "Siku 3 bila malipo",
    "WEEK": "Wiki moja bila malipo",
    "MONTH": "Mwezi mmoja bila malipo"
  },
  "post_reaction": {
    "LIKE": "Upendo",
    "SMILE": "Furaha",
    "CLAP": "Makofi",
    "IDEA": "Wazo",
    "DISAGREE": "Usikubali"
  },
  "post_action": {
    "comments": "Maoni",
    "impressions": "Maonyesho",
    "saves": "Huhifadhi",
    "shares": "Hisa",
    "embeds": "Kupachika",
    "reports": "Ripoti"
  },
  "nominate": {
    "note": "Unaweza kuteua mtu unayemfahamu. Ikiwa mtu huyu tayari hajaidhinishwa na mtu mwingine, utasajiliwa kama mthibitishaji wake. Rafiki yako lazima awe mwanachama wa Selldone kabla ya kuwateua.",
    "no_credit_message": "Kwa bahati mbaya, huna salio la kutosha kuidhinisha mtu mwingine, lakini utapokea salio hili hivi karibuni. Tafadhali angalia siku chache zijazo.",
    "title": "Teua rafiki yako",
    "remains_credit": "Mkopo wako wa kuteua wengine",
    "user_nominate": "Chagua rafiki yako",
    "action": "Teua"
  },
  "stage_level": {
    "PUBLIC": "Watumiaji wote",
    "PRIVATE": "Wasimamizi pekee",
    "VERIFIED": "Watumiaji wote waliothibitishwa"
  },
  "widget": {
    "offensive_message": "Maoni haya yanakera!",
    "topic": "Mada"
  },
  "editor": {
    "topic_title": "Kichwa cha mada",
    "topic_desc": "Maelezo ya mada",
    "send_post": "Tuma chapisho",
    "no_link": "Hakuna kiungo",
    "add_link": "Ongeza kiungo",
    "add_video": "Ongeza video",
    "add_image": "Ongeza picha",
    "no_subscription": "Hakuna mpango wa uchumaji wa mapato",
    "nofollow_msg": "Ongeza nofollow kwa viungo vyote",
    "cross_msg": "Inaweza kuunda mada tofauti kutoka kwa mada hii",
    "pin_msg": "Bandika mada hii juu ya mada katika kategoria",
    "private_on_msg": "Wasimamizi na wasimamizi pekee ndio wanaoweza kuona mada hii",
    "private_off_msg": "Mtu yeyote anaweza kuona mada hii",
    "topic_placeholder": "Mada ya mada ya kushangaza hapa...",
    "desc_placeholder": "Maelezo mafupi kuhusu mada...",
    "title_placeholder": "Swali lako ni nini, mada au ...?",
    "body_placeholder": "Andika chapisho jipya...",
    "remove_poll": "Ondoa kura",
    "take_screenshot": "Chukua kama kifuniko",
    "take_link_msg": "Kiungo kilichopita hapa na ingiza",
    "eligible_title": "Hatua za kustahiki kuchapisha"
  },
  "tips": {
    "verify_email": "Ingiza na uthibitishe barua pepe yako.",
    "verify_phone": "Thibitisha simu yako.",
    "need_nominate": "Teua na mmoja au ombi la kuthibitisha."
  },
  "regime": {
    "Aristocracy": "Aristocracy",
    "Timocracy": "Timokrasia",
    "Oligarchy": "Oligarchy",
    "Democracy": "Demokrasia",
    "Tyranny": "Udhalimu"
  },
  "comment": {
    "comment_plc": "Ongeza maoni...",
    "comment_response_plc": "Jibu kwa {name}...",
    "first_comment": "Weka maoni kwanza..."
  },
  "filter": {
    "created_at": "Hivi karibuni",
    "created_at_asc": "Waanzilishi",
    "positive_reactions": "Iliyopendwa zaidi",
    "engaged": "Wengi wanaohusika",
    "all_posts": "Machapisho yote",
    "media_only": "Vyombo vya habari pekee"
  },
  "topic": {
    "add_topic": "Ongeza mada mpya",
    "add_topic_desc": "Tafuta kwanza kuhusu mada yako! Usiunde nakala za mada hata kidogo, kwa sababu zitaondolewa na wasimamizi.",
    "can_create": "Inaweza kuunda na",
    "add_cross": "Ongeza mada tofauti",
    "add_cross_desc": "Unaweza kuunda mazungumzo ya kawaida na jumuiya zingine. Ili kufanya hivyo, unahitaji kunakili msimbo wa jumuiya ya msalaba.",
    "admins_moderators": "Wasimamizi na Wasimamizi",
    "remove_msg": "Ukiondoa mada hii, ni kitendo kisichoweza kutenduliwa!",
    "remove": "Ondoa mada",
    "main_post_removed_msg": "Chapisho kuu limeondolewa na mwandishi au msimamizi!",
    "delete_dialog": {
      "title": "Ondoa mada",
      "message": "Je, una uhakika kufuta mada hii?",
      "actions": "Ndiyo, Futa Sasa"
    },
    "statistics": "Takwimu za kitengo"
  },
  "community": {
    "disabled": "Jumuiya yako imezimwa!",
    "community_url": "Fungua ukurasa wa jumuiya",
    "edit": "Badilisha jumuiya",
    "install": "Sakinisha sasa",
    "start_community_message": "Anzisha jumuiya yako ya ajabu.",
    "shop_community_setting": "Mipangilio ya jumuiya",
    "regime": "Utawala wa jamii",
    "need_verify_to_create_message": "Ili kuunda jumuiya yako kuu bila malipo kabisa, pitia hatua hizi",
    "name": "Jina",
    "name_plc": "jina la jumuiya yangu...",
    "name_msg": "Weka jina la kipekee la mtumiaji kwa jumuiya yako",
    "title": "Kichwa",
    "title_plc": "Kichwa cha kushangaza cha jamii ...",
    "title_msg": "Weka jina mahususi na la kina kwa jumuiya",
    "desc": "Maelezo",
    "desc_plc": "Kuhusu jumuiya hii...",
    "desc_msg": "Maelezo mafupi kuhusu jumuiya hii",
    "enable_msg": "Unaweza kuwezesha au kuzima jumuiya yako",
    "hide_rule": "Ficha kanuni",
    "edit_rule": "Badilisha kanuni",
    "rule_plc": "Andika sheria za jumuiya yako...",
    "statistics": "Takwimu za Jumuiya"
  },
  "access": {
    "admins": "Wasimamizi",
    "moderators": "Wasimamizi",
    "manage_admins": "Dhibiti wasimamizi",
    "manage_moderators": "Dhibiti wasimamizi",
    "add_moderator": "Ongeza msimamizi"
  },
  "category": {
    "add_new": "Ongeza aina mpya",
    "add_new_msg": "Unaweza kuunda jumla ya kategoria 20. Inatosha, ili kuweka ufikiaji wa jumuiya yako kwa urahisi na kufikiwa zaidi.",
    "title": "Kichwa",
    "title_plc": "Kategoria fulani ya kushangaza...",
    "title_msg": "Weka mada mahususi na ya kina kwa kategoria",
    "desc": "Maelezo",
    "desc_plc": "Kuhusu kategoria hii...",
    "desc_msg": "Maelezo mafupi kuhusu kategoria hii",
    "restrict": "Hali ya kuzuia",
    "restrict_msg": "Wasimamizi pekee ndio wanaweza kuunda mada?",
    "statistics": "Takwimu za kitengo",
    "remove_msg": "Ukiondoa aina hii, ni kitendo kisichoweza kutenduliwa!",
    "delete_dialog": {
      "title": "Ondoa kategoria",
      "message": "Je, una uhakika kufuta kategoria hii?",
      "actions": "Ndiyo, Futa Sasa"
    }
  },
  "invite": {
    "not_have_profile_error": "Mtumiaji huyu hajakamilisha wasifu wake!",
    "nominated_before_error": "Mtumiaji huyu aliteuliwa hapo awali!",
    "verified_before_error": "Wasifu huu ulithibitishwa na jumuiya ya kimataifa ya Selldone hapo awali!",
    "send_invite_msg": "Tuma ujumbe huu kwa marafiki zako"
  },
  "post_actions": {
    "save": "Hifadhi",
    "save_msg": "Hifadhi kwa ajili ya baadaye",
    "copy_code": "Nakili msimbo",
    "copy_link": "Nakili kiungo",
    "copy_link_msg": "Kiungo cha moja kwa moja kwa chapisho",
    "embed": "Pachika chapisho hili",
    "embed_msg": "Nakili na html iliyopachikwa hapo awali",
    "edit": "Badilisha chapisho",
    "edit_msg": "Badilisha yaliyomo kwenye chapisho",
    "report_msg": "Je, chapisho hili halifai?",
    "delete": "Futa chapisho",
    "delete_msg": "Ondoa chapisho hili",
    "approved": "Chapisho lililoidhinishwa",
    "approve_action": "Weka alama kuwa imekubaliwa",
    "approved_msg": "Weka chapisho hili kama jibu lililoidhinishwa",
    "delete_dialog": {
      "title": "Futa chapisho",
      "message": "Je, una uhakika kufuta chapisho hili?",
      "action": "Ndiyo, Futa Sasa"
    }
  },
  "comment_actions": {
    "edit": "Hariri maoni",
    "link": "Kiungo cha kutoa maoni",
    "link_msg": "Nakili kiungo ili kushiriki maoni",
    "edit_msg": "Badilisha maudhui ya maoni yako",
    "delete": "Futa",
    "delete_msg": "Futa maoni haya",
    "delete_dialog": {
      "title": "Futa maoni",
      "message": "Je, una uhakika kufuta maoni haya?",
      "action": "Ndiyo, Futa Sasa"
    }
  },
  "embed": {
    "copy_code_msg": "Nakili nyuma ya msimbo",
    "copy_code": "Nakili msimbo"
  }
};