export default {
  "commons": {
    "approved": "Tasdiqlangan",
    "trend": "Trend",
    "like": "Kabi",
    "share": "Ulashish",
    "comment": "Izoh",
    "view_insight": "Aniqliklarni ko'rish",
    "trial_mode": "Sinov rejimi",
    "no_trial_mode": "Bo'sh muddat yo'q",
    "nofollow": "Nofollow",
    "cross": "Kesib o'tish",
    "pin": "Yuqoriga mahkamlang",
    "private": "Shaxsiy xona",
    "text": "Matn",
    "voice": "Ovoz",
    "video": "Video",
    "link": "Havola",
    "image": "Rasm",
    "product": "Mahsulot",
    "seo": "SEO",
    "configuration": "Konfiguratsiya",
    "monetize": "Monetizatsiya",
    "subscription_fee": "Abonent to‘lovi",
    "login_msg": "Jamiyat sayohatingizni boshlang",
    "topic": "Mavzu",
    "topic_title": "Mavzu sarlavhasi",
    "categories": "Kategoriyalar",
    "author": "Muallif",
    "reply": "Javob bering",
    "reports": "hisobotlar)",
    "show_more": "Ko'proq ko'rsatish..",
    "disagree": "rozi emasman",
    "agree": "Rozi",
    "suggestion_list": "Siz uchun taklif",
    "following_action": "Kuzatish",
    "follow_action": "Kuzatish",
    "rules_violation": "Sizning hamjamiyatingiz qoidalarni buzish holatlariga duch keladi!",
    "cross_community": "O'zaro hamjamiyat",
    "crossable": "O'tish mumkin",
    "crossable_msg": "Boshqa jamoalar sayohatlar hamjamiyati tomonidan o'zaro mavzularni yaratishi mumkin",
    "nofollow_msg": "Barcha havolalar uchun nofollow tegini qo'shing",
    "topics": "Mavzular",
    "posts": "Xabarlar",
    "comments": "Izohlar",
    "total": "Jami",
    "user_reactions": "Foydalanuvchilarning reaktsiyalari",
    "impressions": "Taassurotlar",
    "reactions": "Reaksiyalar",
    "saves": "Saqlaydi",
    "embeds": "Oʻrnatish",
    "shares": "Ulushlar",
    "you_are_admin": "Siz adminsiz",
    "you_are_moderator": "Siz moderatorsiz",
    "invite_friend": "Do'stimni taklif qiling",
    "nominate_friend": "Mening do'stimni taklif qiling",
    "request_nominate": "Kimdandir sizni nomzod qilib ko'rsatishini so'rang!",
    "show_deleted_posts": "O'chirilgan xabarlarni ko'rsatish",
    "moderators": "Moderatorlar",
    "analytics": "Analitika",
    "edit": "Tahrirlash",
    "notify": "Xabar berish",
    "rules": "Qoidalar",
    "explore": "Tadqiq qiling",
    "my_feed": "Men",
    "blocked_message": "Siz bloklangansiz",
    "reported": "Xabar qilingan",
    "report": "Hisobot",
    "post": "Post",
    "attach_file": "Fayl biriktirish"
  },
  "invite_message": "{user} sizni {community} forumiga taklif qildi. Do'stlaringizning kuzatishlarini o'qish va ular bilan o'z fikringizni bildirish uchun quyidagi havolani bosing. Men sizni kutyapman.",
  "subscription_type": {
    "MONTHLY": "Oylik",
    "SEASONAL": "Mavsumiy",
    "YEARLY": "Yillik",
    "LIFETIME": "Muddat"
  },
  "trial_type": {
    "TRIO": "3 kun bepul",
    "WEEK": "Bir hafta bepul",
    "MONTH": "Bir oy bepul"
  },
  "post_reaction": {
    "LIKE": "Sevgi",
    "SMILE": "Baxtli",
    "CLAP": "Qarsaklar",
    "IDEA": "Fikr",
    "DISAGREE": "rozi emasman"
  },
  "post_action": {
    "comments": "Izohlar",
    "impressions": "Taassurotlar",
    "saves": "Saqlaydi",
    "shares": "Ulushlar",
    "embeds": "Oʻrnatish",
    "reports": "Hisobotlar"
  },
  "nominate": {
    "note": "Siz o'zingiz bilgan odamni nomzod qilib ko'rsatishingiz mumkin. Agar bu shaxs boshqa shaxs tomonidan tasdiqlanmagan bo'lsa, siz uning tekshiruvchisi sifatida ro'yxatdan o'tasiz. Do'stingiz Selldone a'zosi bo'lishi kerak, siz ularni nomzod qilib ko'rsatishingizdan oldin.",
    "no_credit_message": "Afsuski, sizda boshqa birovni ma’qullash uchun yetarli kredit yo‘q, lekin tez orada bu kreditni olasiz. Iltimos, keyingi bir necha kun ichida tekshiring.",
    "title": "Do'stingizni belgilang",
    "remains_credit": "Boshqalarni nomzod qilib ko'rsatish uchun sizning kreditingiz",
    "user_nominate": "Do'stingizni tanlang",
    "action": "Nomzod qilish"
  },
  "stage_level": {
    "PUBLIC": "Barcha foydalanuvchilar",
    "PRIVATE": "Faqat moderatorlar",
    "VERIFIED": "Barcha tasdiqlangan foydalanuvchilar"
  },
  "widget": {
    "offensive_message": "Bu fikr haqoratli!",
    "topic": "Mavzu"
  },
  "editor": {
    "topic_title": "Mavzu sarlavhasi",
    "topic_desc": "Mavzu tavsifi",
    "send_post": "Xabar yuborish",
    "no_link": "Havola yo'q",
    "add_link": "Havola qo'shing",
    "add_video": "Video qo'shish",
    "add_image": "Rasm qo'shish",
    "no_subscription": "Monetizatsiya rejasi yo'q",
    "nofollow_msg": "Barcha havolalarga nofollow qo'shing",
    "cross_msg": "Ushbu mavzu bo‘yicha o‘zaro mavzu yaratishi mumkin",
    "pin_msg": "Ushbu mavzuni toifadagi mavzular tepasiga mahkamlang",
    "private_on_msg": "Bu mavzuni faqat admin va moderatorlar koʻra oladi",
    "private_off_msg": "Har kim bu mavzuni ko'rishi mumkin",
    "topic_placeholder": "Bu yerda ajoyib mavzu sarlavhasi...",
    "desc_placeholder": "Mavzu haqida qisqacha ma'lumot...",
    "title_placeholder": "Savolingiz, mavzuingiz yoki ...?",
    "body_placeholder": "Yangi post yozing...",
    "remove_poll": "So‘rovnomani olib tashlash",
    "take_screenshot": "Qopqoq sifatida oling",
    "take_link_msg": "O'tgan havola bu yerga va kiriting",
    "eligible_title": "E'lon qilish huquqiga ega bo'lish uchun qadamlar",
    "public": "Ommaviy"
  },
  "tips": {
    "verify_email": "Elektron pochtangizni kiriting va tasdiqlang.",
    "verify_phone": "Telefoningizni tasdiqlang.",
    "need_nominate": "Ulardan birini taklif qiling yoki tasdiqlashni so'rang."
  },
  "regime": {
    "Aristocracy": "Aristokratiya",
    "Timocracy": "Timokratiya",
    "Oligarchy": "Oligarxiya",
    "Democracy": "Demokratiya",
    "Tyranny": "Zulm"
  },
  "comment": {
    "comment_plc": "Fikr qo'shing...",
    "comment_response_plc": "{name} ga javob...",
    "first_comment": "Birinchi fikrni qo'ying..."
  },
  "filter": {
    "created_at": "Eng so'nggi",
    "created_at_asc": "Kashshoflar",
    "positive_reactions": "Eng yoqdi",
    "engaged": "Eng band",
    "all_posts": "Barcha postlar",
    "media_only": "Faqat ommaviy axborot vositalari"
  },
  "topic": {
    "add_topic": "Yangi mavzu qo'shish",
    "add_topic_desc": "Mavzu bo'yicha birinchi qidiruv! Ikki nusxadagi mavzularni umuman yaratmang, chunki ular moderatorlar tomonidan olib tashlanadi.",
    "can_create": "tomonidan yaratish mumkin",
    "add_cross": "O'zaro mavzu qo'shing",
    "add_cross_desc": "Boshqa jamoalar bilan umumiy mavzular yaratishingiz mumkin. Buni amalga oshirish uchun siz jamiyatlararo kodni nusxalashingiz kerak.",
    "admins_moderators": "Adminlar va Moderatorlar",
    "remove_msg": "Agar siz ushbu mavzuni olib tashlasangiz, bu qaytarib bo'lmaydigan harakatdir!",
    "remove": "Mavzuni olib tashlash",
    "main_post_removed_msg": "Asosiy post muallif yoki administrator tomonidan olib tashlangan!",
    "delete_dialog": {
      "title": "Mavzuni olib tashlash",
      "message": "Bu mavzuni oʻchirib tashlaysizmi?",
      "actions": "Ha, Hozir oʻchirish"
    },
    "statistics": "Kategoriyalar statistikasi"
  },
  "community": {
    "disabled": "Hamjamiyatingiz o'chirildi!",
    "community_url": "Hamjamiyat sahifasini oching",
    "edit": "Jamiyatni tahrirlash",
    "install": "Hozir oʻrnating",
    "start_community_message": "Ajoyib hamjamiyatingizni boshlang.",
    "shop_community_setting": "Hamjamiyat konfiguratsiyasi",
    "regime": "Jamoa rejimi",
    "need_verify_to_create_message": "Ajoyib hamjamiyatingizni mutlaqo bepul yaratish uchun ushbu bosqichlarni bajaring",
    "name": "Ism",
    "name_plc": "mening hamjamiyat nomim...",
    "name_msg": "Jamiyatingiz uchun noyob foydalanuvchi nomini o'rnating",
    "title": "Sarlavha",
    "title_plc": "Qandaydir ajoyib jamoa unvoni...",
    "title_msg": "Jamiyat uchun aniq va keng qamrovli sarlavha o'rnating",
    "desc": "Tavsif",
    "desc_plc": "Bu hamjamiyat haqida...",
    "desc_msg": "Ushbu jamoa haqida qisqacha ma'lumot",
    "enable_msg": "Siz hamjamiyatingizni yoqishingiz yoki o'chirib qo'yishingiz mumkin",
    "hide_rule": "Qoidani yashirish",
    "edit_rule": "Qoidani tahrirlash",
    "rule_plc": "Jamiyat qoidalarini yozing...",
    "statistics": "Jamiyat statistikasi"
  },
  "access": {
    "admins": "Adminlar",
    "moderators": "Moderatorlar",
    "manage_admins": "Administratorlarni boshqarish",
    "manage_moderators": "Moderatorlarni boshqaring",
    "add_moderator": "Moderator qo'shing"
  },
  "category": {
    "add_new": "Yangi turkum qo'shing",
    "add_new_msg": "Siz jami 20 ta toifani yaratishingiz mumkin. Bu hamjamiyatga kirishni qulay va qulayroq saqlash uchun yetarli.",
    "title": "Sarlavha",
    "title_plc": "Qandaydir ajoyib toifa...",
    "title_msg": "Kategoriya uchun aniq va keng qamrovli sarlavha o'rnating",
    "desc": "Tavsif",
    "desc_plc": "Ushbu turkum haqida...",
    "desc_msg": "Ushbu toifa haqida qisqacha tavsif",
    "restrict": "Cheklash rejimi",
    "restrict_msg": "Faqat moderatorlar mavzu yaratishi mumkinmi?",
    "statistics": "Kategoriyalar statistikasi",
    "remove_msg": "Agar siz ushbu toifani olib tashlasangiz, bu qaytarib bo'lmaydigan harakatdir!",
    "delete_dialog": {
      "title": "Kategoriyani olib tashlash",
      "message": "Bu turkumni oʻchirib tashlaysizmi?",
      "actions": "Ha, Hozir oʻchirish"
    }
  },
  "invite": {
    "not_have_profile_error": "Bu foydalanuvchi oʻz profilini toʻldirgani yoʻq!",
    "nominated_before_error": "Bu foydalanuvchi ilgari nomzod bo'lgan!",
    "verified_before_error": "Bu profil Selldone global hamjamiyati tomonidan tasdiqlangan!",
    "send_invite_msg": "Ushbu xabarni do'stlaringizga yuboring"
  },
  "post_actions": {
    "save": "Saqlash",
    "save_msg": "Keyinroq uchun saqlang",
    "copy_code": "Kodni nusxalash",
    "copy_link": "Havolani nusxalash",
    "copy_link_msg": "Xabarga to'g'ridan-to'g'ri havola",
    "embed": "Ushbu postni joylashtiring",
    "embed_msg": "Htmlni nusxalash va joylashtirish",
    "edit": "Xabarni tahrirlash",
    "edit_msg": "Xabar mazmunini o'zgartiring",
    "report_msg": "Bu post nomaqbulmi?",
    "delete": "Postni oʻchirish",
    "delete_msg": "Ushbu postni olib tashlang",
    "approved": "Tasdiqlangan post",
    "approve_action": "Qabul qilingan deb belgilang",
    "approved_msg": "Ushbu postni tasdiqlangan javob sifatida belgilang",
    "delete_dialog": {
      "title": "Postni oʻchirish",
      "message": "Bu postni oʻchirib tashlaysizmi?",
      "action": "Ha, Hozir oʻchirish"
    }
  },
  "comment_actions": {
    "edit": "Fikrni tahrirlash",
    "link": "Fikr bildirish uchun havola",
    "link_msg": "Fikrni baham ko'rish uchun havoladan nusxa oling",
    "edit_msg": "Fikringiz mazmunini o'zgartiring",
    "delete": "Oʻchirish",
    "delete_msg": "Bu fikrni oʻchirib tashlang",
    "delete_dialog": {
      "title": "Fikrni o'chirish",
      "message": "Bu fikrni oʻchirib tashlaysizmi?",
      "action": "Ha, Hozir oʻchirish"
    }
  },
  "embed": {
    "copy_code_msg": "Kodni o'tgandan nusxa ko'chiring",
    "copy_code": "Kodni nusxalash"
  }
};