<?php 

 return [
     "home" => "વેચાઈ ગયું",
     "blogs" => "બ્લોગ",
     "helps" => "મદદ",
     "current_location" => "આ પ્રવેશ",
     "dashboard" => "dashboard",
     "my_shops" => "મારા સ્ટોર્સ",
     "wallet" => "wallet",
     "about" => "Selldone વિશે",
     "contact" => "contact us",
     "comments" => "comments",
     "likes" => "પસંદ",
     "power" => "ઉત્સાહ",
     "build_free_shop" => "તમારો સ્ટોર મફતમાં બનાવો",
     "shop_name" => "shop name",
     "categories" => "categories",
     "sub_articles" => "More",
     "terms" => "શરતો",
     "colour" => "રંગ",
     "style" => "style",
     "volume" => "volume",
     "weight" => "weight",
     "pack" => "પૅક",
     "type" => "type",
     "add_to_card" => "સૂચી માં સામેલ કરો",
     "overview" => "Overview",
     "reviews" => "સમીક્ષાઓ",
     "spec" => "સંપૂર્ણ સ્પેક",
     "you_may_also_like" => "તમને પણ ગમશે",
     "about_us" => "અમારા વિશે",
     "contact_us" => "contact us",
     "cookie_privacy" => "Cookie &amp; privacy policy",
     "follow_us" => "અમને અનુસરો",
     "category" => "શ્રેણી",
     "author" => "Written by ",
     "published_at" => "પર પ્રકાશિત",
     "modified_at" => "ખાતે સંશોધિત",
     "price" => "કિંમત",
     "discount" => "ડિસ્કાઉન્ટ",
     "price_after_discount" => "ડિસ્કાઉન્ટ પછી કિંમત",
     "available" => "ઉપલબ્ધ છે",
     "sold_out" => "વેચાઈ ગયું",
     "buy" => "હમણાં જ ખરીદો",
     "login_shop" => "લૉગિન દુકાન",
     "posted_on" => "તારીખ: તારીખે પોસ્ટ કર્યું",
];