<?php 

 return [
     "accepted" => "આ :attribute સ્વીકારવી આવશ્યક છે.",
     "active_url" => "આ :attribute માન્ય URL નથી.",
     "after" => ":attribute :date પછીની તારીખ હોવી જોઈએ.",
     "after_or_equal" => ":attribute :date પછીની અથવા તેની બરાબરની તારીખ હોવી જોઈએ.",
     "alpha" => ":attribute માં માત્ર અક્ષરો હોઈ શકે છે.",
     "alpha_dash" => ": લક્ષણમાં માત્ર અક્ષરો, સંખ્યાઓ અને ડેશ હોઈ શકે છે.",
     "alpha_num" => ": લક્ષણમાં માત્ર અક્ષરો અને સંખ્યાઓ હોઈ શકે છે.",
     "array" => "આ :attribute એરે હોવી જોઈએ.",
     "before" => ":attribute :date પહેલાની તારીખ હોવી જોઈએ.",
     "before_or_equal" => ":attribute :date પહેલાંની અથવા તેની બરાબરની તારીખ હોવી જોઈએ.",
     "between" => [
     "numeric" => "આ :attribute :min અને :max ની વચ્ચે હોવી જોઈએ.",
     "file" => ":attribute :min અને :max kilobytes ની વચ્ચે હોવી જોઈએ.",
     "string" => ":attribute :min અને :max અક્ષરોની વચ્ચે હોવી જોઈએ.",
     "array" => ":attributeમાં :min અને :max આઇટમ્સ વચ્ચે હોવી આવશ્યક છે.",
],
     "boolean" => ":attribute ફીલ્ડ સાચું કે ખોટું હોવું જોઈએ.",
     "confirmed" => "આ :attribute પુષ્ટિ મેળ ખાતી નથી.",
     "date" => "આ :attribute માન્ય તારીખ નથી.",
     "date_format" => "આ :attribute format :format સાથે મેળ ખાતું નથી.",
     "different" => "આ :attribute અને :other અલગ હોવા જોઈએ.",
     "digits" => ":attribute :digits અંકો હોવા જોઈએ.",
     "digits_between" => "આ :attribute :min અને :max અંકોની વચ્ચે હોવી જોઈએ.",
     "dimensions" => "આ :attribute માં અમાન્ય ઇમેજ પરિમાણો છે.",
     "distinct" => ":attribute ફીલ્ડમાં ડુપ્લિકેટ મૂલ્ય છે.",
     "email" => "આ :attribute માન્ય ઇમેઇલ સરનામું હોવું આવશ્યક છે.",
     "exists" => "પસંદ કરેલ : વિશેષતા અમાન્ય છે.",
     "file" => "આ :attribute ફાઇલ હોવી આવશ્યક છે.",
     "filled" => ":attribute ફીલ્ડમાં મૂલ્ય હોવું આવશ્યક છે.",
     "gt" => [
     "numeric" => ":attribute :value કરતાં મોટી હોવી જોઈએ.",
     "file" => "આ :attribute :value kilobytes કરતાં મોટી હોવી જોઈએ.",
     "string" => "આ :attribute :value અક્ષરો કરતાં મોટી હોવી જોઈએ.",
     "array" => ":attributeમાં :value કરતાં વધુ વસ્તુઓ હોવી આવશ્યક છે.",
],
     "gte" => [
     "numeric" => ":attribute :value કરતાં મોટી અથવા સમાન હોવી જોઈએ.",
     "file" => "આ :attribute :value kilobytes કરતાં વધારે અથવા બરાબર હોવું જોઈએ.",
     "string" => ":attribute :value અક્ષરો કરતાં વધારે અથવા સમાન હોવું જોઈએ.",
     "array" => ":વિશેષમાં :મૂલ્ય વસ્તુઓ અથવા વધુ હોવી આવશ્યક છે.",
],
     "image" => "આ :attribute એક છબી હોવી આવશ્યક છે.",
     "in" => "પસંદ કરેલ : વિશેષતા અમાન્ય છે.",
     "in_array" => "આ :attribute ફીલ્ડ :other માં અસ્તિત્વમાં નથી.",
     "integer" => "આ :attribute પૂર્ણાંક હોવો જોઈએ.",
     "ip" => "આ :attribute માન્ય IP સરનામું હોવું આવશ્યક છે.",
     "ipv4" => "આ :attribute માન્ય IPv4 સરનામું હોવું આવશ્યક છે.",
     "ipv6" => "આ :attribute માન્ય IPv6 સરનામું હોવું આવશ્યક છે.",
     "json" => "આ :attribute માન્ય JSON સ્ટ્રિંગ હોવી આવશ્યક છે.",
     "lt" => [
     "numeric" => ":attribute :value કરતાં ઓછી હોવી જોઈએ.",
     "file" => ":attribute :value kilobytes કરતાં ઓછી હોવી જોઈએ.",
     "string" => "આ :attribute :value અક્ષરો કરતાં ઓછી હોવી જોઈએ.",
     "array" => ": વિશેષતામાં : મૂલ્ય આઇટમ કરતાં ઓછી હોવી આવશ્યક છે.",
],
     "lte" => [
     "numeric" => ":attribute :value કરતાં ઓછું અથવા બરાબર હોવું જોઈએ.",
     "file" => "આ :attribute :value kilobytes કરતાં ઓછી અથવા બરાબર હોવી જોઈએ.",
     "string" => "આ :attribute :value અક્ષરો કરતાં ઓછી અથવા સમાન હોવી જોઈએ.",
     "array" => ": વિશેષતામાં : મૂલ્ય આઇટમ કરતાં વધુ ન હોવી જોઈએ.",
],
     "max" => [
     "numeric" => "આ :attribute :max કરતાં વધુ ન હોઈ શકે.",
     "file" => "આ :attribute :max kilobytes કરતાં વધુ ન હોઈ શકે.",
     "string" => "આ :attribute :max અક્ષરો કરતા વધારે ન હોઈ શકે.",
     "array" => ":attributeમાં :max કરતાં વધુ વસ્તુઓ ન હોઈ શકે.",
],
     "mimes" => ":attribute પ્રકાર: :values ની ફાઇલ હોવી આવશ્યક છે.",
     "mimetypes" => ":attribute પ્રકાર: :values ની ફાઇલ હોવી આવશ્યક છે.",
     "min" => [
     "numeric" => "આ :attribute ઓછામાં ઓછું હોવું જોઈએ :min.",
     "file" => "આ :attribute ઓછામાં ઓછું :min kilobytes હોવી જોઈએ.",
     "string" => ":attribute ઓછામાં ઓછા :min અક્ષરોની હોવી જોઈએ.",
     "array" => ":attributeમાં ઓછામાં ઓછી :min આઇટમ હોવી આવશ્યક છે.",
],
     "not_in" => "પસંદ કરેલ : વિશેષતા અમાન્ય છે.",
     "not_regex" => "આ :attribute ફોર્મેટ અમાન્ય છે.",
     "numeric" => "આ :attribute સંખ્યા હોવી જોઈએ.",
     "present" => ":attribute ફીલ્ડ હાજર હોવું આવશ્યક છે.",
     "regex" => "આ :attribute ફોર્મેટ અમાન્ય છે.",
     "required" => "આ :attribute ફીલ્ડ જરૂરી છે.",
     "required_if" => "જ્યારે :અન્ય :વેલ્યુ હોય ત્યારે :attribute ફીલ્ડ જરૂરી છે.",
     "required_unless" => "આ :attribute ફીલ્ડ જરૂરી છે સિવાય કે :other :values માં હોય.",
     "required_with" => "જ્યારે :values હાજર હોય ત્યારે :attribute ફીલ્ડ જરૂરી છે.",
     "required_with_all" => "જ્યારે :values હાજર હોય ત્યારે :attribute ફીલ્ડ જરૂરી છે.",
     "required_without" => "જ્યારે :values હાજર ન હોય ત્યારે :attribute ફીલ્ડ જરૂરી છે.",
     "required_without_all" => "જ્યારે :મૂલ્યોમાંથી કોઈ હાજર ન હોય ત્યારે :attribute ફીલ્ડ જરૂરી છે.",
     "same" => "આ :attribute અને :other મેચ થવો જોઈએ.",
     "size" => [
     "numeric" => "આ :attribute :size હોવી જોઈએ.",
     "file" => "આ :attribute :size kilobytes હોવી જોઈએ.",
     "string" => ": લક્ષણ : કદના અક્ષરો હોવા જોઈએ.",
     "array" => "એટ્રીબ્યુટમાં :સાઇઝની વસ્તુઓ હોવી આવશ્યક છે.",
],
     "string" => "આ :attribute એક શબ્દમાળા હોવી જોઈએ.",
     "timezone" => "આ :attribute માન્ય ઝોન હોવું આવશ્યક છે.",
     "unique" => "આ :attribute પહેલેથી લેવામાં આવી છે.",
     "uploaded" => "આ :attribute અપલોડ કરવામાં નિષ્ફળ.",
     "url" => "આ :attribute ફોર્મેટ અમાન્ય છે.",
     "custom" => [
     "attribute-name" => [
     "rule-name" => "કસ્ટમ-સંદેશ",
],
     "g-recaptcha-response" => [
     "required" => "કૃપા કરીને ચકાસો કે તમે રોબોટ નથી.",
     "captcha" => "કેપ્ચા ભૂલ! પછીથી ફરી પ્રયાસ કરો અથવા સાઇટ એડમિનનો સંપર્ક કરો.",
],
],
     "attributes" => [
        
     ],
];