<?php 

 return [
     "email-types" => [
        [
     "title" => "Pedido confirmado por el comprador",
],
        [
     "title" => "Confirmación de pago del cliente",
],
        [
     "title" => "Aviso de confirmación de pedido al vendedor",
],
        [
     "title" => "Confirmar pedido de caja de tienda para el comprador",
],
        [
     "title" => "Confirmar el pago de la caja registradora para el comprador",
],
        [
     "title" => "Aviso de compra en la caja del vendedor",
],
        [
     "title" => "Informar formulario de contacto",
],
        [
     "title" => "Felicidades por unirte a la tienda.",
],
        [
     "title" => "Anuncio de recepción de una tarjeta regalo al usuario",
]
     ],
     "global" => [
     "greetings" => "Nombre Hola",
     "end-statement" => "Equipo de apoyo",
     "receiver_name" => "Hola: nombre_de_usuario",
     "footer-help" => "¿Necesitas ayuda? Pregunte en [support@selldone.com](mailto:support@selldone.com) o visite nuestro [centro de ayuda](https://selldone.com/help)",
     "footer-shop" => "Si necesita ayuda con algo, no dude en enviarnos un correo electrónico: :shop_mail",
     "accept" => "Aceptar",
     "reject" => "Rechazar",
     "verify" => "verificar",
     "title" => "Título",
     "value" => "Valor",
     "description" => "Descripción",
     "Shop" => "Tienda",
     "user" => "Usuario",
     "license" => "Licencia",
     "status" => "Estado",
     "start" => "Comienzo",
     "end" => "Fin",
     "renewal" => "Renovación",
     "view" => "Vista",
     "balance" => "Equilibrio",
     "card_number" => "Número de tarjeta",
     "cvv" => "cvv",
     "expire_date" => "Fecha de caducidad",
     "dashboard" => "tablero",
     "order" => "ordenar",
     "view_order" => "Ver pedido",
     "pay_now" => "Pay now",
     "official_selldone" => "VENTA OFICIAL HECHA",
     "account-number" => "Account number",
     "account-name" => "Account name",
     "currency" => "Divisa",
     "free-balance" => "Saldo libre",
     "locked-balance" => "Saldo bloqueado",
     "bot" => "Bot",
     "requests" => "Peticiones",
     "baskets" => "carros",
     "physical" => "Físico",
     "virtual" => "Virtual",
     "file" => "Archivo",
     "service" => "Servicio",
     "fulfillment" => "Cumplimiento",
     "open" => "Abierto",
     "reserved" => "Reservado",
     "canceled" => "Cancelado",
     "payed" => "Pagado",
     "cod" => "COD",
     "orders-count" => "Pedidos",
     "payments-count" => "Pagos",
     "confirms-count" => "Confirma",
     "sends-count" => "envía",
     "delivers-count" => "entrega",
     "count" => "Contar",
     "transactions-count" => "Cuenta de transacciones",
     "success-transactions" => "Transacciones exitosas",
     "total-amount" => "Cantidad total",
     "amount" => "Monto",
     "wage" => "Salario",
     "debug" => "Depurar",
     "pos" => "POS",
     "live" => "Vivir",
     "CheckQueue" => "comprobar la cola",
     "OrderConfirm" => "Confirmación de pedido",
     "PreparingOrder" => "Preparando pedido",
     "SentOrder" => "pedido enviado",
     "ToCustomer" => "Entregado al cliente",
     "Pending" => "Pendiente",
     "Accepted" => "Aceptado",
     "Rejected" => "Rechazado",
     "pc" => "PC",
     "tablet" => "Tableta",
     "phone" => "Teléfono",
     "total" => "Total",
     "view-detail" => "Ver Detalle",
     "empty" => "Vacío",
     "dropshipping" => "Envío directo",
     "reply" => "Respuesta",
     "reactions" => "reacciones",
     "comments" => "comentarios",
     "last-comment" => "Último comentario",
     "response-to" => "Respuesta a",
     "posts" => "Publicaciones",
     "post" => "Correo",
     "name" => "Nombre",
     "email" => "Correo electrónico",
     "type" => "escribe",
     "device" => "Dispositivo",
     "platform" => "Plataforma",
     "browser" => "Navegador",
     "time" => "Tiempo",
     "wallet" => "cartera",
     "date" => "Fecha",
     "account" => "Cuenta",
     "transaction" => "Transacción",
     "fee" => "Tarifa",
     "location" => "Location",
     "ip" => "Ip",
     "bill" => "Factura",
     "category" => "Categoría",
     "password" => "Clave",
     "shop" => "Tienda",
     "verify-login" => "Verificar e iniciar sesión",
     "url" => "URL",
     "avocado" => "Palta",
     "hyper" => "Hiper",
     "buy-now" => "Compra ahora",
     "add-domain" => "Add Domain",
     "views" => "Puntos de vista",
     "country" => "País",
     "address" => "dirección",
     "postal" => "Código postal",
     "building_no" => "Edificio #",
     "building_unit" => "Unidad #",
     "message" => "Mensaje",
     "customer" => "Cliente",
     "cart-items" => "Artículos del carrito",
     "payment" => "Pago",
     "receiver" => "Receptor",
     "virtual-items" => "Artículos virtuales",
     "no-payment" => "¡Sin pago!",
],
     "selldone-business-os" => "Sistema operativo comercial Selldone",
     "senders" => [
     "WeeklyReport" => [
     "id" => "performance",
     "name" => "Informe de rendimiento, Selldone",
],
     "SeasonalReport" => [
     "id" => "seasonal",
     "name" => "Informe de temporada, Selldone",
],
     "Onboarding" => [
     "id" => "hola",
     "name" => "Equipo Selldone",
],
     "Support" => [
     "id" => "support",
     "name" => "Soporte :nombre",
],
     "EmailVerify" => [
     "id" => "verify",
     "name" => "Verificar, vender hecho",
],
     "Welcome" => [
     "id" => "hola",
     "name" => "Comunidad, Selldone",
],
     "NewShop" => [
     "id" => "comerciantes",
     "name" => "Comerciantes, Selldone",
],
     "Approve" => [
     "id" => "aprobar",
     "name" => "Aprobar, vender hecho",
],
     "SellerReceiveOrder" => [
     "id" => "order",
     "name" => "Gestión de pedidos :nombre",
],
     "Recovery" => [
     "id" => "recuperación",
     "name" => "Equipo de recuperación de Selldone",
],
],
     "bill-status" => [
     "PENDING" => "Pendiente ⌛",
     "PAYED" => "Pagado ✅",
     "CANCELED" => "Cancelado ❌",
],
     "shop-invite" => [
     "LEVEL-NAME" => [
     "ADMIN" => "Administrador",
     "OFFICER" => "oficial y supervisor",
     "AUDITING" => "gerente de auditoria",
     "EMPLOYEE" => "Empleado",
     "PRODUCT" => "gerente de productos",
     "CONTENT" => "Gestor de contenidos",
     "MARKETING" => "gerente de mercadotecnia",
     "VIEWER" => "Espectador",
],
     "subject" => ":inviter Invitarte como :level | :tienda",
     "category" => "invitación del personal",
     "title" => "Ha sido invitado a <b>:shop_name</b> como <b>:level</b> .",
     "message" => "Se le ha enviado una invitación. Puede confirmarlo o rechazarlo. Si esta invitación es aprobada por usted, debe ingresar al servicio de Selldone para confirmarla. Al confirmar esta invitación, tendrá acceso a la sección de gestión de la tienda.",
],
     "welcome-email" => [
     "subject" => "👋 Bienvenido :name, Algunas cosas interesantes solo para ti.",
     "category" => "CONGRATULATION",
     "title" => "BIENVENIDO A SELLDONE",
     "message" => "Gracias por elegir Selldone. Ahora es parte de la comunidad de Selldone que conecta a vendedores globales con clientes, negocios locales con empresas, individuos con corporaciones. Todas las herramientas maestras y profesionales se han proporcionado **gratis** e **ilimitadas** para usted. ¡Tú lo intentas, nosotros te abrimos las puertas, Just Do It!",
     "seller" => [
     "title" => "¿Eres un vendedor?",
     "message" => "Para comenzar a vender, ingrese a su tablero en Selldone a través del enlace a continuación y cree su primera tienda completamente gratis. Esto le llevará unos minutos y tendrá su propia tienda y sitio en línea. Luego lo guiaremos a los siguientes pasos y obtendremos la pasarela de pago.",
     "action" => "Iniciar sesión en mi tablero",
],
     "buyer" => [
     "title" => "soy un comprador",
     "message" => "Felicidades. Una vez que sea miembro de Selldone, se librará de todas las molestias de la membresía y la autenticación en las tiendas en línea. Para beneficiarse de cualquier tienda y sitio que utilice la plataforma Selldone, puede iniciar sesión con un clic y hacer su compra simple, rápida y segura.",
],
],
     "charge-account" => [
     "category" => "Monedero > Cuenta > Cargo",
     "title" => "Cargo de éxito",
     "message" => "Su cuenta <b>:número_de_cuenta</b> ha sido cargada correctamente <b>:cantidad</b> .",
     "account" => "Cuenta",
     "charge" => "Cargo",
     "balance" => "Equilibrio",
     "footer" => "Haga que los negocios sean fáciles, alcanzables y accesibles para cualquier persona en todo el mundo.",
],
     "verify-email" => [
     "subject" => "🙌 ¡Completa tu registro en Selldone! Verificar enlace.",
     "category" => "ESTÁS A UN PASO DE DISTANCIA",
     "title" => "Verifique su dirección de correo electrónico",
     "message" => "Nombre Hola,<br> Gracias por elegir Selldone.<br> Confirme que **:email** es su dirección de correo electrónico haciendo clic en el botón o utilice el enlace a continuación dentro de las 48 horas.",
     "footer" => "Si tiene problemas para hacer clic en el botón Verificar, copie y pegue la siguiente URL en su navegador web: __:activation_url__",
],
     "verify-email-code" => [
     "subject" => "Código de verificación para :nombre",
     "category" => "SECURITY",
     "title" => "Código de verificación de correo electrónico",
     "message" => "Nombre Hola,<br><br> Confirme que **:email** es su dirección de correo electrónico con este código en 10 minutos.",
],
     "onboarding-verify-email" => [
     "subject" => "🎉 Tu Tienda Está Lista | :nombre",
     "category" => "ESTÁS A UN PASO DE DISTANCIA",
     "title" => "Configuración completada",
     "account_title" => "Su cuenta",
     "account_msg" => "Verifique e inicie sesión en su cuenta con esta información.",
     "shop_msg" => "Información de la cuenta en el sistema operativo comercial de Selldone.",
],
     "reset2fa" => [
     "category" => "MENSAJE OFICIAL DE SEGURIDAD",
     "title" => "Solicitar deshabilitar inicio de sesión en 2 pasos",
     "message" => "Está recibiendo este correo electrónico porque recibimos una solicitud de restablecimiento de autenticación de 2 factores para su cuenta.<br><br> Correo electrónico del usuario: <b>:correo electrónico</b><br> Nombre: <b>:nombre</b>",
     "footer" => "Si no solicitó un restablecimiento de contraseña, no se requiere ninguna otra acción.",
     "action" => "Deshabilitar el inicio de sesión en dos pasos",
],
     "build-new-shop" => [
     "subject" => "🎊 ¡Tu tienda ya está lista!",
     "category" => "NACE NUEVA TIENDA ONLINE EN EL MUNDO",
     "title" => "Celebrando",
     "message" => "<b>Felicitaciones :name, ha creado un nuevo negocio en línea;</b> Le deseamos éxito en su negocio. Bienvenido a la comunidad Selldoners.<br> Lo intentas, abrimos las puertas, y lo hiciste.",
     "pdf-book" => "No se pierda el manual adjunto: Haga sus negocios como un juego",
     "account" => [
     "title" => "Paso 1: Crea una cuenta en la billetera Selldone",
     "message" => "Si no tiene una cuenta en su billetera, cree una. Selldone deduce la tarifa de esta cuenta. Puede recargar esta cuenta y Selldone también le cobrará una cantidad de crédito para que, si esta cuenta es negativa, su sitio y la Tienda continúen funcionando.",
     "action" => "Iniciar sesión en la billetera",
],
     "shop-account" => [
     "title" => "Paso 2: conecta la cuenta a la tienda",
     "message" => "Agregue su cuenta de billetera a su tienda. Para hacer esto, ingrese a Tienda > Contabilidad > Factura y conecte la cuenta a la tienda. Tenga en cuenta que todos los pagos de sus clientes se depositan directamente en su cuenta bancaria y Selldone no retira ni deduce ningún monto, por lo que debe conectar esta cuenta de Selldone a la tienda.",
     "action" => "Panel Factura de tienda",
],
     "gateway" => [
     "title" => "Paso 3: Conecte la pasarela de pago en línea",
     "message" => "Vaya a Tienda> Contabilidad> Puerto y presione <b>Agregar nuevo puerto</b> . Después de seleccionar la moneda, se le mostrará una lista de puertos portátiles. Conectar el puerto en Selldone es muy sencillo y rápido, pero si tienes Niza para orientarte, consulta la sección de guías de Selldone o consúltanos.",
     "action" => "Agregar un portal a la tienda",
],
     "domain" => [
     "title" => "Último paso: conectar un dominio dedicado",
     "message" => "Podrás tener tu tienda en tantos dominios como quieras. Para conectar un dominio dedicado a una tienda, debe tener al menos una licencia de inicio. Al presentar Selldone a cada amigo, recibirá una tarjeta de regalo de licencia de inicio de un mes. Un porcentaje de los pagos de sus amigos también se acreditará en las cuentas de sus clientes.",
     "action" => "Presentar y recibir tarjetas de regalo ilimitadas",
],
],
     "basket-list" => [
     "item" => "ít",
     "count" => "Contar",
     "price" => "precio",
     "discount-code" => "Código de descuento",
     "customer-club" => "club de clientes",
     "shipping" => "Envío",
     "total" => "Total",
     "offer" => "Oferta",
     "coupon" => "Cupón",
     "lottery" => "Otorgar",
     "tax" => "Impuesto",
     "tax_included" => "Incluido en el precio",
     "tax_shipping" => "Shipping Tax",
],
     "buyable-payments" => [
     "method" => "Método",
     "amount" => "Monto",
     "giftcard" => "Gift card",
     "payment" => "Pago",
],
     "shop-subscription-email" => [
     "category" => "actualización de suscripción",
     "title" => "Licencia de tienda: :shop_title",
     "title-reserved" => "Reservar licencia: :shop_title",
     "title-active" => "Licencia activa: :shop_title",
     "title-finished" => "Licencia terminada: :shop_title",
     "title-cancel" => "Cancelar licencia: :shop_title",
     "message" => "Su plan de licencia de tienda actualizado,",
     "RESERVED" => "⚡ Su plan de suscripción ha sido **reservado**.",
     "ACTIVE" => "🟢 Su plan de suscripción ha sido **activado**.",
     "FINISHED" => "🚧 Su plan de suscripción ha sido **terminado**.",
     "CANCEL" => "⛔ Tu plan de suscripción ha sido **cancelado**.",
],
     "support" => [
     "subject" => "Centro de soporte | :nombre respondió",
     "category" => "Centro de Apoyo",
     "title" => "Recibiste una respuesta",
     "action" => "Abrir administrador de tienda",
],
     "shop-customer-join" => [
     "subject" => "Únete a :shop_title",
     "category" => "Celebración de nuevos clientes",
     "title" => "Estamos felices por su membresía",
     "action" => "Visitar ahora",
],
     "shop-giftcard" => [
     "subject" => "Tarjeta de regalo :shop_title",
     "category" => "Agregar nueva tarjeta",
     "title" => "Enhorabuena, has recibido una tarjeta regalo",
     "action" => "Compra ahora",
     "message" => "Ha recibido una tarjeta de regalo por el importe de :saldo :moneda. Podrás comprar en nuestra tienda con esta tarjeta regalo.",
],
     "contact" => [
     "subject" => "Centro de soporte | :tienda",
     "category" => "apoyo",
     "title" => "Recibiste una respuesta",
],
     "order-checkout" => [
     "subject" => "🛍 Pago de pedidos | :Solicitar ID",
     "title" => "ordenar",
     "message" => "Tu pedido confirma,<br> Tenemos tu pedido. Le enviaremos otro correo electrónico cuando se envíe su pedido.",
     "payments" => "Pagos",
],
     "order-payment" => [
     "subject" => "🛍 Confirmación de pago | :Solicitar ID",
     "title" => "Orden de pago",
     "message" => "Su pago completado,<br> Tenemos tu pedido. Le enviaremos otro correo electrónico cuando se envíe su pedido.",
     "payments" => "Pagos",
],
     "get-voucher" => [
     "subject" => "Felicidades :nombre | Nuevo vale: :título",
     "category" => "ENHORABUENA, NUEVO VALE",
     "message" => "Obtiene un nuevo cupón, este es un regalo de nosotros para usted. Puede obtener más de estos cupones presentando Selldone a sus amigos y a todos sus conocidos. Este vale vale **:precio:moneda**.<br> Prueba, te abrimos las puertas, Enhorabuena, ¡Desbloquea funciones con tu cupón!",
     "action" => "Mi tablero",
],
     "received-gift" => [
     "subject" => "Felicitaciones, querido :nombre | Has recibido un regalo",
     "category" => "Anuncio de recibir un regalo",
     "title" => "regalos para ti",
     "message" => "Has recibido un nuevo regalo. Este es un regalo de Selldone. Puede recibir más de estos obsequios siendo más activo en Selldone y desarrollando su tienda y elevando su nivel de especialización. El valor de este regalo es **: precio: moneda ** que puede depositar directamente en su billetera en selldone.<br><br> Use este regalo para actualizar la licencia de su tienda y usar más herramientas en su negocio en línea.",
     "action" => "Regalos",
],
     "order-payment-admin" => [
     "subject" => "🛍 Nuevo Pedido Recibido | :Solicitar ID",
     "title" => "New Order",
     "message" => "Has recibido un nuevo pedido. Vaya a la página de procesamiento de pedidos en su tienda.",
],
     "virtual-item" => [
     "input-form-title" => "Su información completa",
     "output-form-title" => "Información del artículo comprado",
],
     "selldone-weekly-report" => [
     "subject" => "📬 :shop_title | Informe semanal: tiempo",
     "title" => "Informe semanal de rendimiento de la tienda",
     "message" => "Este es el informe semanal de su tienda de :comienzo a :fin. Este informe incluye consejos para mejorar tu negocio, también puedes consultar el estado de tu tienda online y los últimos pedidos. Espero que tengas un buen día y semana por delante.",
],
     "shop-seasonal-report" => [
     "subject" => "☘ Su informe de ahorro de :cantidad en los últimos tres meses | :shop_title",
     "title" => "Informe estacional sobre la actividad de su negocio, recompensas y ahorros financieros",
     "message" => "Este es su informe de temporada de :shop_title de :comienzo a :fin.",
],
     "EC-ShopAccounts" => [
     "title" => "Cuentas conectadas",
     "sub-title" => "¿Cuál es el estado más reciente de las cuentas de billetera conectadas a mi tienda?",
     "view-wallet" => "Ver billetera",
     "tip-title" => "Consejos importantes",
     "tip" => "En el siguiente paso, cree una cuenta gratuita en su billetera Selldone y conéctela a esta tienda. Incluso si el saldo de su cuenta Selldone es negativo, sus clientes aún pueden realizar compras y pagos para su tienda sin ningún problema. Sus datos y servicios no se interrumpirán ni restringirán durante al menos 1 mes.",
     "view-my-wallet" => "My wallet",
     "connect-account" => "Conectar a la cuenta",
],
     "EC-ShopApps" => [
     "title" => "Aplicaciones instaladas",
     "sub-title" => "Lista de aplicaciones que has instalado en tu tienda esta semana.",
     "tip" => "¿Quieres encontrar más aplicaciones para tu tienda?",
     "view-app-store" => "Visite la tienda de aplicaciones de Selldone..",
],
     "EC-ShopBots" => [
     "title" => "Los robots de tu tienda",
     "sub-title" => "Bots de ventas activos en mi tienda.",
     "tip-title" => "Venta de bots",
     "tip" => "Selldone le ha proporcionado bots de ventas automáticos. Todo lo que tienes que hacer es ir al panel Complementos > Bots y activar los bots de tu tienda. Tenga en cuenta que el servicio correspondiente debe estar disponible en su país.",
     "view-bots" => "Administrar bots",
],
     "EC-ShopContacts" => [
     "title" => "Comunicación con los Clientes",
     "sub-title" => "¿Cuántos contactos he tenido con mis clientes esta semana?",
     "faqs" => "Preguntas frecuentes",
     "tickets" => "Boletos de clientes",
],
     "EC-ShopData" => [
     "title" => "Estado de los usuarios",
     "sub-title" => "Desde la fecha :inicio hasta :fin",
     "users" => [
     "title" => "Clientes",
     "subtitle" => "Registrar Usuarios",
],
     "views" => [
     "title" => "Visitas",
     "subtitle" => "¿Cuántas veces has visitado la tienda?",
],
     "new_visitors" => "New Users",
     "returning_visitors" => "Usuarios devueltos",
     "shop_views" => "Vistas de la tienda",
     "baskets" => [
     "title" => "Carritos de compra",
     "subtitle" => "Informar el número de carritos de compra nuevos",
],
     "products" => [
     "title" => "Resumen de productos",
     "subtitle" => "Estado de los productos en la tienda por tipo",
     "value_name" => "productos",
],
     "products_count" => "Tipos de productos",
     "views_count" => "Conteo de visitas",
     "sell_count" => "Vender cuenta",
     "send_count" => "Recuento de envíos",
],
     "EC-ShopDropShipping" => [
     "title" => "Envío de la gota",
     "sub-title" => "Panel para los principales vendedores de Drop Shipping Selldone.",
     "total_fulfillments" => "Total de pedidos recibidos",
     "ds_count" => "Pedidos recibidos",
     "statistics_title" => "Reportar pedidos recibidos",
     "ds_cancels" => "Cancelar por vendedor de interfaz",
     "ds_rejects" => "Cancelar por usted",
     "tip" => "¿Es usted un importante vendedor de mercancías? ¿Es dueño de un almacén, fábrica o distribuidor de productos? Puede ofrecer sus productos a otros vendedores en el servicio Drop Shipping de Selldone para vender su producto a gran escala. Envíenos un correo electrónico a support@selldone.com para guiarlo.",
     "view-drop-shipping-panel" => "Inicie sesión en el panel de venta al por mayor",
],
     "EC-ShopExchangeRates" => [
     "title" => "Los tipos de cambio",
     "sub-title" => "Lista de las últimas tasas de conversión de moneda en su tienda.",
     "from" => "Moneda de origen",
     "to" => "Moneda de destino",
     "rate" => "Tasa de conversión",
     "vew-exchange-panel" => "panel de gestión de tipo de cambio",
],
     "EC-ShopExperts" => [
     "title" => "Contratos de expertos",
     "sub-title" => "¿Qué profesionales trabajan en mi tienda?",
     "cost" => "Monto del contrato",
     "duration" => "Duración",
     "start_at" => "Start Date",
     "complete_at" => "Completion Date",
     "cancel_at" => "Fecha Cancelar",
     "end_at" => "Fecha de entrega",
     "tip" => "Puede contratar a los mejores especialistas en Selldone para desarrollar su negocio.",
     "view-experts" => "Haga clic para comenzar.",
],
     "EC-ShopGateways" => [
     "title" => "Payment gateways",
     "sub-title" => "Reportar pasarelas de pago activas en la tienda :shop.",
     "tip-title" => "Consejos importantes",
     "tip" => "Vaya a la página de administración del portal en su tienda y agregue al menos un puerto en unos minutos. A tus clientes les gusta pagar de forma rápida y segura a través de portales online.",
     "view-shop-gateways" => "Inicie sesión en la gestión del portal de mi tienda.",
     "view-gateways" => "Vea más puertas de enlace",
],
     "EC-ShopOrders" => [
     "title" => "Pedidos",
     "sub-title" => "Lista de pedidos que he recibido esta semana.",
     "total_baskets" => "Pedidos totales",
     "total_posBaskets" => "Total de pedidos en efectivo",
     "pos-title" => "Caja de tienda POS",
     "chart-label" => "Pedidos completados (¡estos pedidos no están necesariamente pagados!)",
     "tip-title" => "Deberías esforzarte más...",
     "tip" => "Ningún éxito sencillo.",
],
     "EC-ShopProcessCenter" => [
     "title" => "Centro de procesamiento",
     "sub-title" => "¿Cuánto pedido procesamos en la tienda esta semana?",
     "tip-title" => "¡No tuviste una venta!",
     "tip" => "Desafortunadamente no tuviste ninguna venta esta semana. Necesitas llegar más a tu tienda. Puede agregar más productos, elegir mejores imágenes o escribir mejores descripciones para sus productos. Considere un trabajo de tiempo completo para su negocio. Si lo haces bien y no te frustras, tendrás éxito.",
     "view-process-center" => "Ver centro de procesos",
     "return" => [
     "title" => "Pedido devuelto",
     "subtitle" => "Informe de pedidos devueltos.",
     "tip-title" => "Sabía usted que ...",
     "tip" => "¡Puede crear tantas cajas registradoras de tiendas como desee a través de Selldone POS! De hecho, puede convertir su tableta, teléfono móvil o computadora portátil en su bandeja de entrada. Si eso te emociona, Selldone POS es algo que deberías comenzar a usar ahora. Solo se necesita un simple clic para iniciar, tenemos todo preparado para su servidor de antemano.",
     "view-pos" => "Iniciar sesión en el cajero de mi tienda en línea",
],
],
     "EC-ShopSessions" => [
     "title" => "Sesiones",
     "sub-title" => "¿Cuántas veces visité mi tienda?",
     "countries-title" => "¿Qué países han sido los más visitados?",
],
     "EC-PublicMessage" => [
     "title" => "¿Quieres ganar dinero sin gastar un dólar?",
     "message" => "Estimado: nombre, puede ir a Panel de control> Desmonetización y crear un enlace de referencia. Envía el enlace a tus amigos, recibes tarjetas de regalo de Selldone y un porcentaje de los pagos de tus amigos. Tenga en cuenta que la tarjeta de regalo se le enviará tanto a usted como a su amigo.",
     "action" => "Ver mi enlace de introducción",
     "mail-clip" => "<b style='color: #C2185B'>Importante:</b> si utiliza servicios de correo electrónico como Gmail que limitan la longitud del correo electrónico, busque la siguiente opción al final del correo electrónico para mostrar el informe completo y haga clic en él:",
     "no-coin-reward" => "<b style='color: #C2185B'>Lo sentimos:</b> su actividad no cumplió con los requisitos para obtener la recompensa de SEL Coins gratis. Esfuérzate más y vende más en tu tienda para la próxima temporada.",
     "yes-coin-reward" => "<b style='color: #4CAF50'>Recompensa:</b> Felicitaciones, debido a su fantástico desempeño, le otorgamos una recompensa gratuita de :amount SEL Coin.",
     "need-buy-license" => "<b>Sube de nivel tu negocio:</b> ¡No has registrado ningún plan de suscripción para el sitio web de tu negocio! Así que es el momento de comprar al menos una suscripción. Solo cuesta: monto mensual para la compra anual.",
     "not-afford-message" => "Si no puede pagar o tiene algún problema con el pago, no dude en comunicárnoslo a través de support@selldone.com.",
     "add-domain" => "<b>¿Por qué no tener un dominio personalizado para su negocio?</b><br> Agregue un dominio a su sitio web ahora; ¡es gratis!",
],
     "Widget-Socials" => [
     "title" => "Selldone es un<del> producto</del> <span style = 'color: forestgreen'>comunidad</span><br> ¡Sé un Selldoner profesional!",
     "message" => "Siga las páginas oficiales de Selldone en Twitter, LinkedIn y redes sociales. Envíenos cualquier comentario, solicitud o crítica o participe en debates sobre Selldone. También somos parte de la comunidad de Selldone que <b>Tú haces</b> .",
],
     "avocado-seller-daily-report" => [
     "subject" => "Recibió nuevos pedidos de aguacate | :shop_title :tiempo",
     "title" => "Informe de rendimiento de las últimas 24 horas",
     "message" => "Sus clientes están esperando que sus pedidos sean revisados y cotizados. Responda a las solicitudes de sus clientes lo antes posible para obtener más ventas.",
     "card_title" => "Pedidos en la cola",
     "card_subtitle" => "Partir de la fecha",
     "card_payed" => "pedidos pagados",
],
     "community-comments" => [
     "subject" => "Responde a tu publicación en :community_title",
     "title" => ":name, y :count otros comentaron en tus publicaciones.",
     "title-simple" => ":name comentó en tus publicaciones.",
],
     "community-topic" => [
     "subject" => "🔔 Responde a tu tema :topic_title",
     "title" => ":name, y :count otros respondieron sobre tu tema.",
     "title-simple" => ":name respondió sobre tu tema.",
],
     "user-login" => [
     "subject" => "🔔 Nuevo inicio de sesión: nombre",
     "category" => "Notificaciones de seguridad",
     "title" => "Iniciar sesión en la cuenta",
     "message" => "Estimado: nombre, ha iniciado sesión en su cuenta de Selldone.",
     "footer" => "Si no ha iniciado sesión, cambie su contraseña.",
],
     "account-transaction" => [
     "withdraw" => "Retiro",
     "deposit" => "Depósito",
     "withdraw_subject" => "retirar de la cuenta: cuenta",
     "deposit_subject" => "Depósito a cuenta :cuenta",
     "message" => "La transferencia de dinero se ha realizado con las siguientes especificaciones.",
     "type" => "Tipo de transacción",
     "from" => "Cuenta de origen",
     "to" => "Destination account",
     "desc" => "Descripción de la transacción",
     "action" => "Ver transacción",
],
     "penalty" => [
     "subject" => "⛔ ¡Importante! Violación de reglas | :tienda",
     "category" => "Informe crítico",
     "title" => "Tu tienda ha sido penalizada",
     "action" => "Abrir panel de control de la tienda",
],
     "invite" => [
     "subject" => ":inviter te invitó a Selldone",
     "title" => ":name le envió :amount para ayudarlo a lanzar su nuevo sitio web en línea y monetizarlo.",
     "message" => "En Selldone, puede crear su comercio electrónico, sitio web de blogs y comunidad en línea e incluso obtener un POS en línea y configurar ventas en persona en minutos. Es un sistema operativo de negocios en línea para hacer su negocio en línea, mejor y más rápido. Simplemente regístrese antes de <b>:fecha</b> para obtener un cupón de :cantidad.",
     "accept" => "Aceptar la invitacion",
     "owner" => "Propietario de",
     "join-date" => "En Selldone desde",
],
     "shop-recovery" => [
     "subject" => "Enlace de recuperación | :tienda",
     "category" => "Tienda de seguridad",
     "title" => "Almacene el enlace de recuperación de <b>:shop_name</b> .",
     "message" => "Te enviamos este correo electrónico porque solicitaste restaurar tu tienda. Al hacer clic en el enlace a continuación, recuperará su tienda y todos los datos que le pertenecen.",
     "action" => "Confirmar la recuperación de la tienda",
],
     "SR-SeasonalSaving" => [
     "title" => "¿Cuánto dinero ahorró Selldone para su negocio?",
     "sub-title" => "Desde la fecha :inicio hasta :fin",
     "infrastructure" => [
     "title" => "Infraestructura",
     "subtitle" => "Servidores, CDN, almacenamiento y otros servicios en la nube",
],
     "experts" => [
     "title" => "Expertos y personal",
     "subtitle" => "Desarrolladores, mantenimiento y soporte",
],
     "total_save" => "Dinero total ahorrado",
],
     "SR-SeasonalPerformance" => [
     "title" => "Tu actuación",
     "sub-title" => "Descripción general del negocio de: inicio a: final",
     "new_visitors" => "New Users",
     "returning_visitors" => "Usuarios devueltos",
     "shop_views" => "Vistas de la tienda",
     "baskets" => [
     "title" => "Carritos de compra",
     "subtitle" => "Informar el número de carritos de compra nuevos",
],
     "products" => [
     "title" => "Resumen de productos",
     "subtitle" => "Estado de los productos en la tienda por tipo",
     "value_name" => "productos",
],
     "views" => [
     "title" => "Page Views",
     "subtitle" => "Vistas totales de la página del sitio web",
],
],
];