export default {
  "title": "Cuminciate Gratuitu, Cresce Rapidu!",
  "sub_title": "Accessu illimitatu à tutte e funzioni senza costu! Solu <b>u 2% di a vendita</b> , ghjustu dopu a compra successu. Avete assai vendite è vulete riduce i tariffi?",
  "show_detail_list": "Mostra a lista di dettagli",
  "plan_free_detail": "<b class='text-capitalize'>Un sistema upirativu per l'imprese in rapida crescita</b> | Cumincià a vostra attività cù u nostru pianu gratuitu. Tuttu ciò chì avete bisognu per inizià è lancià u vostru situ web di eCommerce hè prontu quì. Selldone furnisce tuttu u software, l'arnesi è a suluzione di hosting cloud per un pianu di abbonamentu gratuitu. Selldone si occupa in più di tutte l'aghjurnamenti di u software è di e considerazioni di sicurezza. Cusì pudete concentrà tutti i vostri sforzi nantu à a vendita è ùn preoccupate micca di prublemi tecnichi è costi.",
  "pay_monthly": "Paga mensili",
  "pay_yearly": "Paga annu",
  "pay_yearly_off": "30% off",
  "transparency_title": "Trasparenza in i servizii",
  "monthly_cost": "Prezzu mensili",
  "suggested_plan": "Pianu suggeritu",
  "monthly_sell": "Vendite mensili",
  "saving_amount": "Salvà mensili",
  "saving_tips": "Cumprendu u pianu suggeritu, salverà sta quantità mensili.",
  "have_all_features": "Averete tutte e funziunalità.",
  "currency": "USD",
  "want_free": "Vulete liberu?",
  "stack_price": "Stack {amount} million tokens a second",
  "gift": "Rigali speciale",
  "gift_info": "Ottene stu rigalu cumprà stu pianu.",
  "toke_gift_ratio": "Equivalente à a quantità pagata",
  "unlimited": "Illimitatu",
  "items_unit": "x",
  "delivery_person_unit": "Corrieri",
  "soon": "Prestu",
  "domains": "Duminii persunalizati",
  "staff": "Amministratori",
  "community_builder": "Custruttore di a cumunità",
  "active_discount_codes": "Codici sconti attivi",
  "active_coupons": "Coupons avanzati attivi",
  "active_offers": "Offerte avanzate attive",
  "active_gift_card_types": "Programmi Giftcard",
  "active_campaigns": "Campagne di marketing attivu",
  "active_affiliates": "Affiliati attivi",
  "active_emails": "Campagne di email marketing attive",
  "active_transportation_persons": "Corrieri privati",
  "active_importing_que": "Max importazione simultanea di prudutti",
  "active_reselling": "Rivendita; Vendi articuli grossisti",
  "max_file_size": "Dimensione massima di u schedariu per vende; Sicondu a vostra regione Euro/US/...",
  "active_capacity": "Spaziu di discu liberu",
  "active_drop_shipping": "Dropshipping à l'ingrossu (Verificazione necessaria)",
  "common_features": "Inclusu in tutti i piani di {license}",
  "unlimited_storage": "Storage illimitatu",
  "priority_support": "Supportu di priorità",
  "support_247": "Supportu 24/7",
  "read_more": "Leghjite più nantu à e caratteristiche ...",
  "partners_upgrade_suggestion_message": "Ùn avete micca u megliu affare pussibule nantu à {name}! Ricumandemu assai di aghjurnà à u più altu livellu se ùn ti piace micca i limiti.",
  "partners_upgrade_suggestion_action": "Aghjurnate u vostru pianu nantu à {name} avà",
  "free": {
    "title": "Personale",
    "info": "Per e persone appena principianti",
    "cost": "Gratuitu",
    "fee_percent": 2,
    "items": [
      "Prudutti illimitati",
      "1 GB di almacenamiento",
      "Larghezza di banda illimitata",
      "Tutte e funziunalità prufessiunali è arnesi inclusi",
      "Drag & Drop Landing Page Builder",
      "Funzionalità cumpleta CMS è blog",
      "3 Codici sconti attivi",
      "3 Coupons avanzati attivi",
      "3 Offerte avanzate attive",
      "1 Programmi Giftcard",
      "2 Campagni di marketing attivu",
      "2 Programmi di affiliazione attivi",
      "2 Campagne attive di marketing email",
      "2 corrieri privati",
      "Tutti i servizii di spedizione",
      "1 Admin",
      "Custruttore di a cumunità (Basic)"
    ]
  },
  "startup": {
    "title": "Abbrivu",
    "info": "Per i picculi imprese chì principianu",
    "fee_percent": 1.5,
    "items": [
      "Tutte e funzioni gratuiti incluse",
      "10 GB di almacenamiento",
      "Clienti SMS login",
      "Integrazione 3D / AR",
      "10 Codici di sconto attivi",
      "10 cuponi avanzati attivi",
      "10 offerte avanzate attive",
      "10 prugrammi Giftcard",
      "10 Campagne di marketing attive",
      "10 Programmi di affiliazione attivi",
      "10 Campagne di email marketing attive",
      "10 corrieri privati",
      "Supportu nurmale",
      "1 Dominiu",
      "5 amministratori",
      "Custruttore di a cumunità (Basic)"
    ]
  },
  "company": {
    "title": "Cumpagnia",
    "info": "Piccole è Medie Imprese Locali",
    "fee_percent": 1,
    "items": [
      "Tutte e funzioni di startup incluse",
      "Storage illimitatu",
      "50 codici sconti attivi",
      "50 cuponi avanzati attivi",
      "50 offerte avanzate attive",
      "50 prugrammi Giftcard",
      "50 Campagne di marketing attive",
      "100 prugrammi di affiliazione attivi",
      "100 campagne di marketing per email attive",
      "50 corrieri privati",
      "Supportu di priorità",
      "5 Duminii",
      "20 amministratori",
      "Custruttore di a cumunità (Normale)"
    ]
  },
  "enterprise": {
    "title": "Impresa",
    "info": "Imprese à grande scala",
    "fee_percent": 0.5,
    "items": [
      "Tutte e caratteristiche di a cumpagnia incluse",
      "1K codici di sconto attivi",
      "1K cuponi avanzati attivi",
      "1K offerte avanzate attive",
      "1K prugrammi Giftcard",
      "1K Campagne di marketing attive",
      "1K Programmi di affiliazione attivi",
      "1K Campagne di email marketing attive",
      "200 corrieri privati",
      "Supportu 24/7",
      "∞ Duminii",
      "∞ Amministratori",
      "Custruttore di a cumunità (Avanzatu)",
      "Fornitore di Dropshipping",
      "Custruttore di u mercatu"
    ]
  },
  "features": {
    "title": "Features",
    "products": "I prudutti",
    "usage": "Traffico mensuale",
    "custom_domain": "Aghjunghjite un duminiu persunalizatu",
    "invite_to_get_free": "Invita un amicu è uttene gratis",
    "ssl": "Cunferma SSL",
    "support": "Supportu 24/7",
    "staff": "Numero di amministratori",
    "staff_info": "Dà accessu à i membri di a vostra squadra.",
    "person": "persona(e)",
    "shop_name_length": "Lunghezza minima di u nome di u magazinu",
    "chars": "Carattere",
    "page_builder": "Crea a vostra propria pagina",
    "page_builder_info": "Drag & Drop Landing Page Builder",
    "pages": "Pagine",
    "cms": "CMS & Blog",
    "cms_info": "Sistema di Gestione di Cuntinutu Prufessiunale è Editore per Articuli è Prodotti di Blog.",
    "tax": "U calculu di l'impositu",
    "tax_info": "U calculu di l'impositu automaticu basatu annantu à u locu di u cliente, a vendita B2B / B2C, è annullà a capacità di e regule fiscali per i paesi è stati.",
    "tax_profiles": "Profili fiscali - Prufessiunali",
    "tax_profiles_info": "Pudete stabilisce e regule fiscali di vendita dedicate per i prudutti creendu profili fiscali.",
    "extra_tax_profiles": "Extra {count} profili.",
    "tax_profile_fee": "Tariffa 0.0% (serviziu totalmente gratuitu)",
    "tax_pro": "Pro."
  },
  "gateways": {
    "title": "Portal di pagamentu",
    "sub_title": "I porti novi seranu aghjuntu prestu.",
    "gateways": "Gateways",
    "currencies": "Currencies",
    "currencies_info": "Nove valute seranu aghjuntu prestu.",
    "currencies_encrypted": "Codice di valuta",
    "currencies_encrypted_info": "Valute nantu à a piattaforma blockchain",
    "online_pay_wage": "Tariffa portu in linea",
    "online_pay_wage_info": "Stu ammontu serà dedutu da u vostru contu di ricarica in Selldone.",
    "cod_wage": "Tariffe di Pagamentu COD",
    "cod_wage_info": "Stu ammontu serà dedutu da u vostru contu di carica",
    "file_wage": "Tassa di vendita di schedari",
    "file_wage_info": "Cummissione di vendita di schedari chì hè accreditata à u vostru contu dopu una vendita riescita (Ospitatu nantu à l'almacenamiento in nuvola SSD d'alta velocità selldone)."
  },
  "apps": {
    "title": "App Store / Site",
    "pwa": "App Web Avanzata",
    "android": "Android",
    "android_info": "App Android Phone è Tablet",
    "ios": "iOS (à prestu)",
    "ios_info": "App Apple Phone & Tablet"
  },
  "custom_domain": {
    "title": "Dominiu persunalizatu",
    "sub_title": "Avè a vostra tenda nantu à u vostru propiu duminiu.",
    "domains_count": "U numeru di domini di magazzini",
    "dns": "Cloud DNS",
    "cdn": "Cloud CDN",
    "cdn_info": "Cloud Content Spiegazione Network"
  },
  "host": {
    "title": "Cloud Host / Server gratuitu",
    "ssl": "Certificazione SSL",
    "storage": "Storage",
    "usage": "Traffico mensuale",
    "setup": "Setup gratuitu",
    "technical_support": "sustegnu tecnicu",
    "file_sell": "Archivi di vendita di schedari",
    "file_sell_info": "Discu di almacenamentu in nuvola gratuitu per a vendita di fugliali (Super fast)",
    "file_size": "Dimensione massima di ogni schedariu",
    "file_size_info": "Dimensione massima di ogni fugliale per a vendita (pudete caricate più di un schedariu per ogni pruduttu)"
  },
  "products": {
    "title": "I prudutti"
  },
  "seo": {
    "title": "SEO",
    "meta": "Meta tags",
    "meta_info": "Crea automaticamente meta tags cumplettamente avanzati",
    "jsonld": "JSON-LD",
    "jsonld_info": "Dati strutturati",
    "amp": "AMP",
    "amp_info": "Pagine mobile accelerate",
    "compress": "Cumpressione di l'Image",
    "compress_info": "jpg, png, svg, wpng, ...",
    "boost": "Acceleratore di velocità",
    "boost_info": "Schedulatore di carica di pagina per i mutori di ricerca",
    "sitemap": "Sitemap",
    "sitemap_info": "Search Engine Sitemap"
  },
  "other": {
    "title": "Altre caratteristiche",
    "plugins": "Add-ons & Applicazioni",
    "plugins_info": "Accessu à i Add-ons Selldone Store",
    "customer_service": "Serviziu à i clienti",
    "customer_service_info": "Domande Frequenti, Forma di Relazione Clienti, Gestione di Ritorni ...",
    "export": "Esporta prudutti",
    "export_info": "Riceve i schedarii di output di tutti i prudutti cù tutte l'infurmazioni è u cuntenutu. Cù sta funzione, averete una basa di dati standard di i vostri prudutti offline.",
    "import": "Prudutti impurtati in massa",
    "import_info": "U serviziu avanzatu è automaticu di Selldone vi aiuta à carricà i vostri prudutti cù l'imaghjini 100% automaticamente senza avè da pagà alcun costu da qualsiasi altru serviziu di custruttore di magazzini o a vostra basa di dati offline.",
    "Simultaneous": "Simultaneu"
  },
  "logistic": {
    "title": "Logistica",
    "logistic": "Logistica è Trasportu",
    "logistic_desc": "Gestione di l'inventariu è i metudi di spedizione",
    "private_transportation": "Sistema di spedizione privatu",
    "private_transportation_desc": "Crea è gestisce un serviziu di spedizione privatu.",
    "transportation": "Gestisce i metudi di spedizione avanzati",
    "transportation_desc": "Servizi di spedizione lucali è internaziunali",
    "process_center": "Centru di Trattamentu Avanzatu",
    "process_center_desc": "Pannellu di gestione di ordini facili da aduprà",
    "return_requests": "A gestione di ritornu",
    "return_requests_desc": "Gestione di ritornu di l'ordine."
  },
  "marketing": {
    "title": "Marketing & Vendite",
    "campaign": "Crea è gestisce una campagna",
    "affiliate_marketing": "Marketing di affiliazione",
    "affiliate_marketing_desc": "Crea è gestisce piani di impegni di vendita",
    "email_marketing": "Panel di marketing per e-mail",
    "email_marketing_desc": "Cuncepimentu è invià e-mail destinati à u publicu cù filtri è feedback",
    "funnel": "Filtru Advanced User",
    "funnel_desc": "Filtrà l'utilizatori per sessu, storia di compra, ultimu login, etc.",
    "ab_test": "Test A/B",
    "user_reaction": "Analisi di a pagina di destinazione",
    "user_reaction_desc": "Vede e sezioni sbarcate è clicate di e pagine di destinazione cum'è una mappa termale è diagramma"
  },
  "customers": {
    "title": "Clienti è Incentivi",
    "club": "Client Club",
    "discount_code": "Codice di sconto",
    "discount_code_info": "Crea codici di sconto illimitati.",
    "coupon": "Coupon / Voucher",
    "coupon_info": "Offre à i vostri clienti un valore fissu, percentuale, o scontu di spedizione.",
    "gift_card": "Carta rigalu",
    "gift_card_info": "Fate una carta di carica illimitata.",
    "offer": "Offerta",
    "offer_desc": "Cumprate stu pruduttu, uttene quellu liberu (o cù scontu)",
    "game": "Gamificazione",
    "game_desc": "Cuncepisce un ghjocu cù premii"
  },
  "bots": {
    "title": "Bots, Rete Suciali è Canali di Vendita",
    "telegram": "Robot di vendita di Telegram",
    "telegram_info": "Custruite a vostra propria tenda Telegram gratuitamente",
    "instagram": "Instagram",
    "instagram_info": "Cunnette a vostra tenda à Instagram.",
    "facebook": "Facebook",
    "facebook_info": "Generazione automatica è sincronizzazione di una lista di prudutti cumpleti.",
    "avocado": "Serviziu di Vendita di Avocado Social Media",
    "avocado_info": "Cù stu serviziu, puderà riceve ordini da i clienti senza aghjunghje un pruduttu è attraversu una forma nantu à e rete soziale.",
    "hyper": "Ordine Hyper Rapidu",
    "hyper_info": "Per vende centinaie di prudutti per minutu in fiere, festivals, stalle è induve vulete vende parechji prudutti à un gran numaru di clienti."
  },
  "assistance": {
    "title": "Notificazioni",
    "notifications": "Canali di notificazione",
    "email": "E-mail",
    "email_info": "Mandate e-mail à i clienti è u staffu di a tenda.",
    "sms": "SMS",
    "sms_info": "Mandate SMS à i clienti è u staffu di a tenda.",
    "report": "Rapportu intelligente",
    "report_info": "Inviate rapporti periodici settimanali è annuali di i punti debbuli di u magazinu, l'utilizatori è e vendite, cù cunsiglii per migliurà u vostru rendimentu è aumentà e vendite."
  },
  "automation": {
    "title": "L'automatizazione",
    "niomatic": "Niomatic",
    "niomatic_info": "L'automatizazione avanzata di u prucessu basatu nantu à e preferenze di blocchi grafichi",
    "autopilot": "Autopilota",
    "autopilot_info": "Pianificate l'avvenimenti, sconti, pubblicà blog posts, prudutti è altre cose.",
    "webhook": "Webhook",
    "webhook_info": "Una API ligera chì permette a spartera di dati unidirezionale attivata da l'avvenimenti."
  },
  "pos": {
    "title": "Selldone POS",
    "pos": "Cassiera di a tenda",
    "pos_info": "U sistema POS cunnessu à a vostra tenda in linea vi furnisce tutti i prucessi di magazzinu, vendita è supportu cù una interfaccia d'utilizatore unica.",
    "online_payment": "Pagamentu in linea",
    "online_payment_info": "Possibilità di pagamentu in linea per i vostri clienti in a vostra tenda fisica.",
    "hardware": "Hardwares",
    "hardware_info": "Capacità di cunnette cù scanners di codici à barre, display di u cliente, stampanti di etichette è altre hardware per simplificà u prucessu di vendita."
  },
  "dropshipping": {
    "title": "Hub di Dropshipping",
    "reseller": "Rivendita",
    "reseller_info": "Pudete aghjunghje i prudutti di grossista à a vostra tenda cun un clic, tutti i passi di cumplimentu è spedizione seranu fatti automaticamente.",
    "wholesaler": "Grossista",
    "wholesaler_info": "I vostri prudutti seranu cummercializati è venduti da rivenditori chì appruvati da voi."
  },
  "community": {
    "title": "Piattaforma di Custruttore di a cumunità",
    "available": "Cumunità persunalizata gratuita",
    "available_info": "Capacità di creà una cumunità persunalizata",
    "nomination": "Per nomina",
    "domain": "Dominiu persunalizatu",
    "domain_info": "Averete u foru nantu à u vostru propiu duminiu.",
    "onboarding": "Onboarding",
    "onboarding_info": "Capacità di aghjunghje un amministratore è un moderatore per u foru.",
    "seo": "SEO",
    "seo_info": "Ùn avete bisognu di cumprà pacchetti supplementari o plugins per i servizii di SEO prufessiunale.",
    "analytic": "Analytics",
    "analytic_info": "L'infurmazioni sò facilmente visibili in e pagine di a cumunità.",
    "post": "Post",
    "post_info": "Limitu di post mensili.",
    "comment": "Cumentu",
    "comment_info": "Capacità di mandà è gestisce i cumenti.",
    "voice": "Voce",
    "voice_info": "Capacità di arregistrà è mandà audio direttu.",
    "video": "Video",
    "video_info": "Capacità di mandà video (finu à 8 MB)",
    "product": "Pruduttu",
    "product_info": "Capacità di mandà u pruduttu direttamente per mail.",
    "poll": "Sondaggio",
    "poll_info": "Capacità di aghjunghje sondaggi à un tema.",
    "report": "Segnala l'abusu",
    "report_info": "Capacità di signalà abusu da l'utilizatori.",
    "profile": "prufilu",
    "profile_info": "Profil d'utilizatore persunalizatu.",
    "sso": "Single sign-on (SSO)",
    "sso_info": "Possibilità di login veloce attraversu u serviziu SSO di Selldone.",
    "embed": "Incrustà",
    "embed_info": "Capacità di incrustà è sparte i posti.",
    "reaction": "Reazione",
    "reaction_info": "L'utilizatori puderanu registrà cumu si sentenu annantu à una storia.",
    "moderation": "Moderation",
    "moderation_info": "Aghjunghjite è gestisce l'accessu à u foru."
  },
  "mission": {
    "title": "Semu nantu à a missione",
    "message": "Fate l'affari faciuli, rializabili è accessibili per tutti in u mondu"
  },
  "marketplace": "Custruttore di u mercatu",
  "connect_os": {
    "subtitle": "Cunnettete cù i fornitori di dropshipping cun un clic. Pudete cunnette à POD cum'è Prinful o Import Woocomerce store gratuitamente."
  }
};