export default {
  "title": "Starten Sie kostenlos, wachsen Sie schnell!",
  "sub_title": "Unbegrenzter Zugriff auf alle Funktionen ohne Kosten! Nur <b>2 % Gebühr</b> direkt nach erfolgreichen Verkäufen. Sie haben viel Umsatz und möchten die Gebühren senken?",
  "show_detail_list": "Detaillierte Liste anzeigen",
  "plan_free_detail": "<b class='text-capitalize'>Ein Betriebssystem für schnell wachsende Unternehmen</b> ╏ Starten Sie Ihr Geschäft mit unserem kostenlosen Plan. Hier finden Sie alles, was Sie zum Start und Betrieb Ihrer E-Commerce-Website benötigen. Selldone bietet alle Software-, Tool- und Cloud-Hosting-Lösungen im Rahmen eines kostenlosen Abonnements an. Selldone kümmert sich zusätzlich um alle Software-Updates und Sicherheitsaspekte. So können Sie sich voll und ganz auf den Verkauf konzentrieren und müssen sich nicht um technische Fragen und Kosten kümmern.",
  "pay_monthly": "Monatlich zahlen",
  "pay_yearly": "Jährlich zahlen",
  "pay_yearly_off": "30 % reduziert",
  "transparency_title": "Transparenz bei Dienstleistungen",
  "monthly_cost": "Monatlicher Preis",
  "suggested_plan": "Vorgeschlagener Plan",
  "monthly_sell": "Monatsumsatz",
  "saving_amount": "Monatliche Ersparnis",
  "saving_tips": "Durch den Kauf des vorgeschlagenen Plans sparen Sie diesen Betrag monatlich.",
  "have_all_features": "Sie erhalten alle Funktionen.",
  "currency": "USD",
  "want_free": "Möchten Sie kostenlos starten?",
  "stack_price": "Stapeln Sie {amount} Millionen Token pro Sekunde",
  "gift": "Spezielles Geschenk",
  "gift_info": "Erhalten Sie dieses Geschenk, wenn Sie diesen Plan kaufen.",
  "toke_gift_ratio": "Entspricht dem gezahlten Betrag",
  "unlimited": "Unbegrenzt",
  "items_unit": "x",
  "delivery_person_unit": "Kuriere",
  "soon": "Kommt bald",
  "domains": "Benutzerdefinierte Domains",
  "staff": "Admins",
  "community_builder": "Community-Builder",
  "active_discount_codes": "Aktive Rabattcodes",
  "active_coupons": "Aktive erweiterte Gutscheine",
  "active_offers": "Aktive erweiterte Angebote",
  "active_gift_card_types": "Geschenkkartenprogramme",
  "active_campaigns": "Aktive Marketingkampagnen",
  "active_affiliates": "Aktive Partner",
  "active_emails": "Aktive E-Mail-Marketingkampagnen",
  "active_transportation_persons": "Private Kuriere",
  "active_importing_que": "Max. gleichzeitige Produktimporte",
  "active_reselling": "Weiterverkauf; Großhandelsartikel verkaufen",
  "max_file_size": "Maximale Dateigröße für den Verkauf; abhängig von Ihrer Region Europa/USA/...",
  "active_capacity": "Freier Speicherplatz",
  "active_drop_shipping": "Großhandels-Dropshipping (Überprüfung erforderlich)",
  "common_features": "In allen {license}-Plänen enthalten",
  "unlimited_storage": "Unbegrenzter Speicherplatz",
  "priority_support": "Vorrangiger Support",
  "support_247": "24/7-Support",
  "read_more": "Mehr über Funktionen lesen...",
  "partners_upgrade_suggestion_message": "Sie haben nicht das bestmögliche Angebot für {name}! Wir empfehlen dringend, auf die höchste Stufe zu aktualisieren, wenn Ihnen die Limits nicht gefallen.",
  "partners_upgrade_suggestion_action": "Aktualisieren Sie jetzt Ihren Plan auf {name}",
  "free": {
    "title": "Persönlich",
    "info": "Für Menschen, die gerade erst anfangen",
    "cost": "Kostenlos",
    "fee_percent": 2,
    "items": [
      "Unbegrenzte Produkte",
      "1 GB Speicher",
      "Unbegrenzte Bandbreite",
      "Alle professionellen Funktionen und Tools inklusive",
      "Landingpage-Builder per Drag-and-drop",
      "CMS & Blogs mit vollem Funktionsumfang",
      "3 aktive Rabattcodes",
      "3 aktive erweiterte Gutscheine",
      "3 aktive erweiterte Angebote",
      "1 Geschenkkartenprogramm",
      "2 aktive Marketingkampagnen",
      "2 aktive Partnerprogramme",
      "2 aktive E-Mail-Marketingkampagnen",
      "2 private Kuriere",
      "Alle Versanddienste",
      "1 Administrator",
      "Community-Builder (Basis)"
    ]
  },
  "startup": {
    "title": "Startup",
    "info": "Für kleine Unternehmen, die gerade erst anfangen",
    "fee_percent": 1.5,
    "items": [
      "Alle kostenlosen Funktionen inklusive",
      "10 GB Speicher",
      "Kunden-SMS-Login",
      "3D-/AR-Integration",
      "10 aktive Rabattcodes",
      "10 aktive erweiterte Gutscheine",
      "10 aktive erweiterte Angebote",
      "10 Geschenkkartenprogramme",
      "10 aktive Marketingkampagnen",
      "10 aktive Affiliate-Programme",
      "10 aktive E-Mail-Marketingkampagnen",
      "10 private Kuriere",
      "Normaler Support",
      "1 Domain",
      "5 Administratoren",
      "Community-Builder (Basis)"
    ]
  },
  "company": {
    "title": "Unternehmen",
    "info": "Kleine und mittlere lokale Unternehmen",
    "fee_percent": 1,
    "items": [
      "Alle Startup-Funktionen enthalten",
      "Unbegrenzter Speicherplatz",
      "50 aktive Rabattcodes",
      "50 aktive erweiterte Gutscheine",
      "50 aktive erweiterte Angebote",
      "50 Geschenkkartenprogramme",
      "50 aktive Marketingkampagnen",
      "100 aktive Partnerprogramme",
      "100 aktive E-Mail-Marketingkampagnen",
      "50 private Kuriere",
      "Vorrangiger Support",
      "5 Domains",
      "20 Administratoren",
      "Community-Builder (Normal)"
    ]
  },
  "enterprise": {
    "title": "Enterprise",
    "info": "Großunternehmen",
    "fee_percent": 0.5,
    "items": [
      "Alle Unternehmensfunktionen enthalten",
      "1K aktive Rabattcodes",
      "1K aktive erweiterte Gutscheine",
      "1K aktive erweiterte Angebote",
      "1K Geschenkkartenprogramme",
      "1K aktive Marketingkampagnen",
      "1K aktive Partnerprogramme",
      "1K aktive E-Mail-Marketingkampagnen",
      "200 private Kuriere",
      "24/7-Support",
      "∞ Domains",
      "∞ Administratoren",
      "Community-Builder (Fortgeschritten)",
      "Dropshipping-Anbieter",
      "Marktplatz-Builder"
    ]
  },
  "features": {
    "title": "Funktionen",
    "products": "Produkte",
    "usage": "Monatlicher Traffic",
    "custom_domain": "Benutzerdefinierte Domain hinzufügen",
    "invite_to_get_free": "Laden Sie einen Freund ein und erhalten Sie es kostenlos",
    "ssl": "SSL-Zertifikat",
    "support": "24/7-Support",
    "staff": "Anzahl der Administratoren",
    "staff_info": "Geben Sie Ihren Teammitgliedern Zugriff.",
    "person": "Person(en)",
    "shop_name_length": "Mindestlänge des Shop-Namens",
    "chars": "Zeichen",
    "page_builder": "Erstellen Sie Ihre eigene Seite",
    "page_builder_info": "Landingpage-Builder per Drag-and-drop",
    "pages": "Seiten",
    "cms": "CMS & Blog",
    "cms_info": "Professionelles Content-Management- und Editor-System für Blogbeiträge und Produkte.",
    "tax": "Steuerberechnung",
    "tax_info": "Automatische Steuerberechnung basierend auf dem Standort des Kunden, B2B/B2C-Verkäufen und der Möglichkeit, Steuerregeln für Länder und Bundesstaaten zu überschreiben.",
    "tax_profiles": "Steuerprofile – Professionell",
    "tax_profiles_info": "Sie können spezielle Umsatzsteuerregeln für Produkte festlegen, indem Sie Steuerprofile erstellen.",
    "extra_tax_profiles": "Zusätzliche {count} Profile.",
    "tax_profile_fee": "0,0 % Gebühr (völlig kostenloser Service)",
    "tax_pro": "Profi."
  },
  "gateways": {
    "title": "Zahlungsgateway",
    "sub_title": "Neue Gateways werden in Kürze hinzugefügt.",
    "gateways": "Gateways",
    "currencies": "Währungen",
    "currencies_info": "Neue Währungen werden in Kürze hinzugefügt.",
    "currencies_encrypted": "Währungscode",
    "currencies_encrypted_info": "Währungen auf Blockchain-Plattform",
    "online_pay_wage": "Online-Zahlungsgebühr",
    "online_pay_wage_info": "Dieser Betrag wird von Ihrem Guthabenkonto in Selldone abgebucht.",
    "cod_wage": "Nachnahmegebühren",
    "cod_wage_info": "Dieser Betrag wird von Ihrem Gebührenkonto abgebucht.",
    "file_wage": "Dateiverkaufsgebühr",
    "file_wage_info": "Dateiverkaufsprovision, die Ihrem Konto nach erfolgreichem Verkauf gutgeschrieben wird (gehostet auf Selldones schnellem SSD-Cloud-Speicher)."
  },
  "apps": {
    "title": "Shop-/Website-App",
    "pwa": "Progressive Web-App",
    "android": "Android",
    "android_info": "Android-Smartphone- und Tablet-App",
    "ios": "iOS (bald verfügbar)",
    "ios_info": "Apple-Smartphone- und Tablet-App"
  },
  "custom_domain": {
    "title": "Benutzerdefinierte Domain",
    "sub_title": "Betreiben Sie Ihren Shop auf Ihrer eigenen Domain.",
    "domains_count": "Anzahl der Shop-Domains",
    "dns": "Cloud-DNS",
    "cdn": "Cloud-CDN",
    "cdn_info": "Cloud Content Delivery Network"
  },
  "host": {
    "title": "Kostenloser Cloud-Host / Server",
    "ssl": "SSL-Zertifikat",
    "storage": "Speicher",
    "usage": "Monatlicher Traffic",
    "setup": "Kostenlose Einrichtung",
    "technical_support": "Technischer Support",
    "file_sell": "Speicher zum Verkauf von Dateien",
    "file_sell_info": "Kostenloser Cloud-Speicher zum Verkaufen von Dateien (superschnell)",
    "file_size": "Maximale Größe jeder Datei",
    "file_size_info": "Maximale Größe jeder Datei für den Verkauf (Sie können mehr als eine Datei für jedes Produkt hochladen)"
  },
  "products": {
    "title": "Produkte"
  },
  "seo": {
    "title": "SEO",
    "meta": "Meta-Tags",
    "meta_info": "Automatisch vollständig erweiterte Meta-Tags erstellen",
    "jsonld": "JSON-LD",
    "jsonld_info": "Strukturierte Daten",
    "amp": "AMP",
    "amp_info": "Beschleunigte mobile Seiten",
    "compress": "Bildkomprimierung",
    "compress_info": "jpg, png, svg, wpng, ...",
    "boost": "Geschwindigkeitsbeschleuniger",
    "boost_info": "Seitenlade-Optimierung für Suchmaschinen",
    "sitemap": "Sitemap",
    "sitemap_info": "Suchmaschinen-Sitemap"
  },
  "other": {
    "title": "Weitere Funktionen",
    "plugins": "Add-ons und Anwendungen",
    "plugins_info": "Zugriff auf Selldone-Shop-Add-ons",
    "customer_service": "Kundendienst",
    "customer_service_info": "Häufig gestellte Fragen, Kundenkontaktformular, Retourenmanagement ...",
    "export": "Produkte exportieren",
    "export_info": "Erhalten Sie Ausgabedateien aller Produkte mit allen Informationen und Inhalten. Mit dieser Funktion haben Sie offline eine Standarddatenbank Ihrer Produkte.",
    "import": "Produkte in großen Mengen importieren",
    "import_info": "Der erweiterte und automatische Selldone-Service hilft Ihnen, Ihre Produkte mit Bildern zu 100 % automatisch hochzuladen, ohne dass Sie dafür Kosten an einen anderen Shop-Builder-Service oder Ihre Offline-Datenbank zahlen müssen.",
    "Simultaneous": "Gleichzeitig"
  },
  "Logistics": {
    "title": "Logistik",
    "Logistics": "Logistik & Transport",
    "Logistics_desc": "Verwaltung von Lagerbeständen und Versandmethoden",
    "private_transportation": "Privates Versandsystem",
    "private_transportation_desc": "Erstellen und verwalten Sie einen privaten Versanddienst.",
    "transportation": "Erweiterte Versandmethoden verwalten",
    "transportation_desc": "Lokale und internationale Versanddienste",
    "process_center": "Erweitertes Bearbeitungszentrum",
    "process_center_desc": "Benutzerfreundliches Bestellverwaltungspanel",
    "return_requests": "Retourenmanagement",
    "return_requests_desc": "Management von Bestellretouren."
  },
  "marketing": {
    "title": "Marketing & Vertrieb",
    "campaign": "Kampagne erstellen und verwalten",
    "affiliate_marketing": "Affiliate-Marketing",
    "affiliate_marketing_desc": "Erstellen und verwalten Sie Verkaufsbeteiligungspläne",
    "email_marketing": "E-Mail-Marketing-Panel",
    "email_marketing_desc": "Gezielte E-Mails an Zielgruppen mit Filtern und Feedback entwerfen und versenden",
    "funnel": "Erweiterter Benutzerfilter",
    "funnel_desc": "Filtern Sie Benutzer nach Geschlecht, Kaufhistorie, letztem Login usw.",
    "ab_test": "A/B-Test",
    "user_reaction": "Landingpage-Analyse",
    "user_reaction_desc": "Zeigen Sie besuchte und angeklickte Abschnitte der Landingpages als Heatmap und Diagramm an"
  },
  "customers": {
    "title": "Kunden & Anreize",
    "club": "Kundenclub",
    "discount_code": "Rabattcode",
    "discount_code_info": "Erstellen Sie unbegrenzte Rabattcodes.",
    "coupon": "Gutschein",
    "coupon_info": "Bieten Sie Ihren Kunden einen festen Betrag, einen prozentualen Rabatt oder einen Versandrabatt an.",
    "gift_card": "Geschenkkarte",
    "gift_card_info": "Erstellen Sie unbegrenzt Guthabenkarten.",
    "offer": "Angebot",
    "offer_desc": "Kaufen Sie dieses Produkt und erhalten Sie es kostenlos (oder mit Rabatt).",
    "game": "Gamification",
    "game_desc": "Entwerfen Sie ein Spiel mit Preisen."
  },
  "bots": {
    "title": "Bots, soziale Netzwerke und Vertriebskanäle",
    "telegram": "Telegram-Verkaufsbot",
    "telegram_info": "Erstellen Sie kostenlos Ihren eigenen Telegram-Shop",
    "instagram": "Instagram",
    "instagram_info": "Verbinden Sie Ihren Shop mit Instagram.",
    "facebook": "Facebook",
    "facebook_info": "Automatische Generierung und Synchronisierung der Produktliste mit allen Funktionen.",
    "avocado": "Avocado-Social-Media-Verkaufsservice",
    "avocado_info": "Mit diesem Service können Sie Bestellungen von Kunden erhalten, ohne ein Produkt hinzuzufügen, und über ein Formular in sozialen Netzwerken verkaufen.",
    "hyper": "Hyperschnelle Bestellung",
    "hyper_info": "Hunderte von Produkten pro Minute auf Messen, Festivals, Ständen und überall dort verkaufen, wo Sie einige Produkte an eine große Anzahl von Kunden verkaufen möchten."
  },
  "assistance": {
    "title": "Benachrichtigungen",
    "notifications": "Benachrichtigungskanäle",
    "email": "E-Mail",
    "email_info": "Senden Sie E-Mails an Kunden und Shop-Mitarbeiter.",
    "sms": "SMS",
    "sms_info": "Senden Sie SMS an Kunden und Shop-Mitarbeiter.",
    "report": "Intelligenter Bericht",
    "report_info": "Erstellen Sie wöchentliche und jährliche Berichte über Schwächen des Shops, Benutzer und Verkäufe – zusammen mit Tipps zur Verbesserung Ihrer Leistung und zur Umsatzsteigerung."
  },
  "automation": {
    "title": "Automatisierung",
    "niomatic": "Niomatic",
    "niomatic_info": "Erweiterte Prozessautomatisierung basierend auf grafischen Blockeinstellungen",
    "autopilot": "Autopilot",
    "autopilot_info": "Planen Sie Veranstaltungen, Rabatte, Blogbeiträge, Produkte und andere Dinge.",
    "webhook": "Webhook",
    "webhook_info": "Eine schlanke API, die einen unidirektionalen, durch Ereignisse ausgelösten Datenaustausch ermöglicht."
  },
  "pos": {
    "title": "Selldone-POS",
    "pos": "Kasse",
    "pos_info": "Das mit Ihrem Onlineshop verbundene Kassensystem bietet Ihnen alle Lager-, Verkaufs- und Supportprozesse mit einer einzigartigen Benutzeroberfläche.",
    "online_payment": "Online-Zahlung",
    "online_payment_info": "Möglichkeit der Online-Zahlung für Ihre Kunden in Ihrem Ladengeschäft.",
    "hardware": "Hardware",
    "hardware_info": "Möglichkeit zur Verbindung mit Barcode-Scannern, Kundendisplays, Etikettendruckern und anderer Hardware, um den Verkaufsprozess zu vereinfachen."
  },
  "dropshipping": {
    "title": "Dropshipping-Hub",
    "reseller": "Wiederverkauf",
    "reseller_info": "Sie können die Produkte des Großhändlers mit einem Klick zu Ihrem Shop hinzufügen; alle Fulfillment- und Versandschritte werden automatisch durchgeführt.",
    "wholesaler": "Großhändler",
    "wholesaler_info": "Ihre Produkte werden von den von Ihnen zugelassenen Wiederverkäufern vermarktet und verkauft."
  },
  "community": {
    "title": "Community-Builder-Plattform",
    "available": "Kostenlose benutzerdefinierte Community",
    "available_info": "Möglichkeit, eine benutzerdefinierte Community zu erstellen",
    "nomination": "Durch Nominierung",
    "domain": "Benutzerdefinierte Domain",
    "domain_info": "Sie betreiben das Forum auf Ihrer eigenen Domain.",
    "onboarding": "Onboarding",
    "onboarding_info": "Möglichkeit, einen Administrator und Moderator für das Forum hinzuzufügen.",
    "seo": "SEO",
    "seo_info": "Sie müssen keine zusätzlichen Pakete oder Plugins für professionelle SEO-Dienste kaufen.",
    "analytic": "Analysen",
    "analytic_info": "Informationen sind auf Community-Seiten leicht sichtbar.",
    "post": "Beitrag",
    "post_info": "Monatliches Beitragslimit.",
    "comment": "Kommentar",
    "comment_info": "Möglichkeit zum Senden und Verwalten von Kommentaren.",
    "voice": "Sprachnachricht",
    "voice_info": "Möglichkeit, Audio direkt aufzunehmen und zu senden.",
    "video": "Video",
    "video_info": "Möglichkeit zum Senden von Videos (bis zu 8 MB)",
    "product": "Produkt",
    "product_info": "Möglichkeit, das Produkt direkt per Beitrag zu versenden.",
    "poll": "Umfrage",
    "poll_info": "Möglichkeit, Umfragen zu einem Thema hinzuzufügen.",
    "report": "Missbrauch melden",
    "report_info": "Möglichkeit, Missbrauch durch Benutzer zu melden.",
    "profile": "Profil",
    "profile_info": "Personalisiertes Benutzerprofil.",
    "sso": "Single Sign-On (SSO)",
    "sso_info": "Möglichkeit der schnellen Anmeldung über den SSO-Service von Selldone.",
    "embed": "Einbetten",
    "embed_info": "Möglichkeit zum Einbetten und Teilen von Beiträgen.",
    "reaction": "Reaktion",
    "reaction_info": "Benutzer können festhalten, wie sie zu einer Geschichte stehen.",
    "moderation": "Moderation",
    "moderation_info": "Forenzugriff hinzufügen und verwalten."
  },
  "mission": {
    "title": "Wir haben die Mission",
    "message": "Geschäfte für jeden Menschen auf der ganzen Welt einfach, erreichbar und zugänglich zu machen"
  },
  "logistic": {
    "title": "Logistik",
    "logistic": "Logistik & Transport",
    "logistic_desc": "Verwaltung von Lagerbeständen und Versandmethoden",
    "private_transportation": "Privates Versandsystem",
    "private_transportation_desc": "Erstellen und verwalten Sie einen privaten Versanddienst.",
    "transportation": "Erweiterte Versandmethoden verwalten",
    "transportation_desc": "Lokale und internationale Versanddienste",
    "process_center": "Erweitertes Bearbeitungszentrum",
    "process_center_desc": "Benutzerfreundliches Bestellverwaltungspanel",
    "return_requests": "Retourenmanagement",
    "return_requests_desc": "Management von Bestellretouren."
  },
  "marketplace": "Marktplatz-Builder",
  "connect_os": {
    "subtitle": "Stellen Sie mit einem Klick eine Verbindung zu Dropshipping-Anbietern her. Sie können sich kostenlos mit POD-Anbietern wie Printful verbinden oder einen WooCommerce-Shop importieren."
  },
  "ai": {
    "title": "KI",
    "sub_title": "Copilot- und KI-Assistentfunktionen.",
    "bg_remove": "KI-Hintergrundentfernung",
    "bg_remove_info": "Hintergrund automatisch aus Bildern entfernen.",
    "content_creation": "KI-Inhaltserstellung",
    "content_creation_info": "Automatisch Inhalte für Produkte erstellen.",
    "add_product": "KI-Produktunterstützung",
    "add_product_info": "Produkte automatisch per Bild und Sprache hinzufügen.",
    "magic_ai_buttons": "Magische KI-Schaltflächen",
    "magic_ai_buttons_info": "Automatisches Entfernen des Hintergrunds, Massenübersetzung, Generieren von Inhalten und mehr mit einem Klick.",
    "translate": "KI-Übersetzung",
    "translate_info": "Übersetzen Sie Inhalte in jede beliebige Sprache."
  }
};
