export default {
  "title": "Malite n'efu, too ngwa ngwa!",
  "sub_title": "Nweta njirimara niile na-akparaghị ókè n'efu! Naanị <b>2% nke ire ere</b> , obere oge ịzụrụ ihe ịga nke ọma. Ị nwere ọtụtụ ahịa ma chọọ ibelata ụgwọ?",
  "show_detail_list": "Gosi ndepụta nkọwa",
  "plan_free_detail": "<b class='text-capitalize'>Sistemụ arụmọrụ maka azụmaahịa na-eto ngwa ngwa</b> | Malite azụmahịa gị site na atụmatụ efu anyị. Ihe niile ịchọrọ ịmalite wee malite webụsaịtị eCommerce gị adịla njikere ebe a. Selldone na-enye sọftụwia niile, ngwa ọrụ, yana ngwọta nnabata igwe ojii site na atụmatụ ndenye aha efu. Selldone na-elekọtakwa mmelite ngwanrọ niile yana nlebanya nchekwa. Ya mere, ị nwere ike ilekwasị anya mgbalị gị niile na ire ere ma ghara ichegbu onwe gị banyere okwu teknụzụ na ụgwọ.",
  "pay_monthly": "Na-akwụ ụgwọ kwa ọnwa",
  "pay_yearly": "Na-akwụ ụgwọ kwa afọ",
  "pay_yearly_off": "30% kwụsịrị",
  "transparency_title": "nghọta na ọrụ",
  "monthly_cost": "Ọnụ ego kwa ọnwa",
  "suggested_plan": "Atụmatụ atụnyere",
  "monthly_sell": "Ịre ahịa kwa ọnwa",
  "saving_amount": "Na-echekwa kwa ọnwa",
  "saving_tips": "Site na ịzụrụ atụmatụ atụpụtara, ị ga-echekwa ego a kwa ọnwa.",
  "have_all_features": "Ị ga-enwe atụmatụ niile.",
  "currency": "USD",
  "want_free": "Achọrọ Free?",
  "stack_price": "Kpakọba {amount} nde token otu nkeji",
  "gift": "Onyinye pụrụ iche",
  "gift_info": "Nweta onyinye a site na ịzụrụ atụmatụ a.",
  "toke_gift_ratio": "Dakọtara na ego a kwụrụ",
  "unlimited": "Enweghị oke",
  "items_unit": "x",
  "delivery_person_unit": "Ndị ozi",
  "soon": "Na-abịa oge adịghị anya",
  "domains": "Ngalaba omenala",
  "staff": "Ndị nlekọta",
  "community_builder": "Onye nrụpụta obodo",
  "active_discount_codes": "Koodu mbelata ego na-arụ ọrụ",
  "active_coupons": "Kupọns dị elu na-arụ ọrụ",
  "active_offers": "Onyinye dị elu na-arụ ọrụ",
  "active_gift_card_types": "Mmemme kaadị onyinye",
  "active_campaigns": "Mgbasa mgbasa ozi na-arụsi ọrụ ike",
  "active_affiliates": "Ndị mmekọ nọ n'ọrụ",
  "active_emails": "Mgbasa ozi email na-arụ ọrụ",
  "active_transportation_persons": "Ndị ozi nkeonwe",
  "active_importing_que": "Mbubata ngwaahịa n'otu oge kacha",
  "active_reselling": "Ire ere; Ree ihe ndị na-ere ahịa",
  "max_file_size": "Oke faịlụ kacha ere; Dabere na mpaghara gị Euro/US/...",
  "active_capacity": "Oghere diski efu",
  "active_drop_shipping": "Mbupu n'ahịa (Nnwale achọrọ)",
  "common_features": "Agụnyere na atụmatụ {license} niile",
  "unlimited_storage": "Nchekwa na-akparaghị ókè",
  "priority_support": "Nkwado ụzọ",
  "support_247": "24/7 nkwado",
  "read_more": "Gụkwuo maka atụmatụ...",
  "partners_upgrade_suggestion_message": "Ị nweghị nkwekọrịta kacha mma na {name}! Anyị na-akwado nke ukwuu ịkwalite ya ka ọ bụrụ ọkwa kachasị elu ma ọ bụrụ na oke na-amasịghị gị.",
  "partners_upgrade_suggestion_action": "Kwalite atụmatụ gị na {name} ugbu a",
  "free": {
    "title": "Nkeonwe",
    "info": "Maka ndị mmadụ na-amalite",
    "cost": "N'efu",
    "fee_percent": 2,
    "items": [
      "Ngwaahịa na-akparaghị ókè",
      "1GB nchekwa",
      "bandwit na-akparaghị ókè",
      "Niile ọkachamara atụmatụ na ngwaọrụ gụnyere",
      "Dọrọ & Wetuo Ihe Nrụpụta Ibe",
      "CMS zuru oke & blọọgụ",
      "3 Koodu mbelata ego na-arụ ọrụ",
      "3 Kupọns dị elu na-arụ ọrụ",
      "3 Onyinye dị elu na-arụ ọrụ",
      "1 Mmemme kaadị onyinye",
      "2 Mgbasa ozi ahịa na-arụsi ọrụ ike",
      "2 Mmemme mmekọ na-arụ ọrụ",
      "2 Mgbasa ozi ahịa email na-arụ ọrụ",
      "2 ndị ozi nzuzo",
      "Ọrụ mbupu niile",
      "1 Admin"
    ]
  },
  "startup": {
    "title": "Malite",
    "info": "Maka obere azụmaahịa na-amalite",
    "fee_percent": 1.5,
    "items": [
      "agụnyere atụmatụ niile efu",
      "10GB nchekwa",
      "Nbanye SMS ndị ahịa",
      "Njikọ 3D / AR",
      "Koodu mbelata 10 na-arụ ọrụ",
      "10 Kupọns dị elu na-arụ ọrụ",
      "10 Onyinye dị elu na-arụ ọrụ",
      "Mmemme kaadị onyinye 10",
      "10 Mgbasa ozi ahịa na-arụsi ọrụ ike",
      "10 Mmemme mmekọ na-arụ ọrụ",
      "10 Mgbasa ozi ahịa email na-arụ ọrụ",
      "10 ndị ozi nzuzo",
      "Nkwado nkịtị",
      "1 ngalaba",
      "5 Ndị isi"
    ]
  },
  "company": {
    "title": "Ụlọ ọrụ",
    "info": "Azụmahịa Obere na Ọkara",
    "fee_percent": 1,
    "items": [
      "Atụmatụ mmalite niile gụnyere",
      "Nchekwa na-akparaghị ókè",
      "Koodu mbelata 50 na-arụ ọrụ",
      "50 Kupọns dị elu na-arụ ọrụ",
      "Onyinye dị elu 50 na-arụ ọrụ",
      "Mmemme kaadị onyinye 50",
      "50 Mgbasa ozi ahịa na-arụsi ọrụ ike",
      "Mmemme mmekọ 100 na-arụ ọrụ",
      "100 mgbasa ozi email na-arụ ọrụ",
      "Ndị njem 50 nkeonwe",
      "Nkwado ụzọ",
      "5 ngalaba",
      "20 Admin"
    ]
  },
  "enterprise": {
    "title": "Ụlọ ọrụ",
    "info": "Nnukwu Azụmahịa",
    "fee_percent": 0.5,
    "items": [
      "Atụmatụ ụlọ ọrụ niile gụnyere",
      "Koodu mbelata 1K na-arụ ọrụ",
      "1K Kupọns dị elu na-arụ ọrụ",
      "Onyinye dị elu 1K nọ n'ọrụ",
      "Mmemme kaadị onyinye 1K",
      "Mgbasa ozi ahịa 1K nọ n'ọrụ",
      "Mmemme mmekọ na-arụ ọrụ 1K",
      "Mgbasa ozi email 1K na-arụ ọrụ",
      "Ndị ozi nzuzo 200",
      "24/7 nkwado",
      "∞ ngalaba",
      "∞ Admins"
    ]
  },
  "features": {
    "title": "Atụmatụ",
    "products": "Ngwaahịa",
    "usage": "Okporo ụzọ kwa ọnwa",
    "custom_domain": "Tinye ngalaba ahaziri iche",
    "invite_to_get_free": "Kpọọ enyi wee nweta ya n'efu",
    "ssl": "Nkwenye SSL",
    "support": "24/7 nkwado",
    "staff": "Ọnụọgụ admins",
    "staff_info": "Nye ndị otu gị ohere ohere.",
    "person": "onye (s)",
    "shop_name_length": "Ogologo aha ụlọ ahịa kacha nta",
    "chars": "agwa",
    "page_builder": "Mepụta ibe nke gị",
    "page_builder_info": "Dọrọ & Wetuo Ihe Nrụpụta Ibe",
    "pages": "Ibe",
    "cms": "CMS & blọọgụ",
    "cms_info": "Ọkachamara njikwa ọdịnaya yana Sistemụ ndezi maka blọọgụ na ngwaahịa."
  },
  "gateways": {
    "title": "Ọnụ ụzọ ịkwụ ụgwọ",
    "sub_title": "A ga-agbakwunye ọdụ ụgbọ mmiri ọhụrụ n'oge adịghị anya.",
    "gateways": "Ọnụ ụzọ ámá",
    "currencies": "Ego",
    "currencies_info": "A ga-agbakwunye ego ọhụrụ n'oge adịghị anya.",
    "currencies_encrypted": "Koodu ego",
    "currencies_encrypted_info": "Ego n'elu ikpo okwu blockchain",
    "online_pay_wage": "Ego ọdụ ụgbọ mmiri dị n'ịntanetị",
    "online_pay_wage_info": "A ga-ewepụ ego a n'akaụntụ nkwụghachi gị na Selldone.",
    "cod_wage": "Ụgwọ ịkwụ ụgwọ COD",
    "cod_wage_info": "A ga-ewepụ ego a n'akaụntụ ụgwọ gị",
    "file_wage": "Ego ire faịlụ",
    "file_wage_info": "Kọmịshọna ire ere faịlụ nke enwetara na akaụntụ gị ka ire ere na-aga nke ọma ( A na-akwado ya na nchekwa igwe ojii SSD nke erere dị elu)."
  },
  "apps": {
    "title": "Ngwa ụlọ ahịa / saịtị",
    "pwa": "Ngwa Weebụ dị elu",
    "android": "Android",
    "android_info": "Ngwa ekwentị gam akporo na mbadamba",
    "ios": "iOS (na-abịa ngwa ngwa)",
    "ios_info": "Ekwentị Apple & Mbadamba ụrọ"
  },
  "custom_domain": {
    "title": "ngalaba omenala",
    "sub_title": "Nweta ụlọ ahịa gị na ngalaba nke gị.",
    "domains_count": "Ọnụọgụ ngalaba ụlọ ahịa",
    "dns": "Cloud DNS",
    "cdn": "CDN igwe ojii",
    "cdn_info": "Netwọk nkọwa ọdịnaya igwe ojii"
  },
  "host": {
    "title": "Onye nnabata igwe ojii / nkesa efu",
    "ssl": "Asambodo SSL",
    "storage": "Nchekwa",
    "usage": "Okporo ụzọ kwa ọnwa",
    "setup": "Ntọlite n'efu",
    "technical_support": "nkwado ndị teknuzu",
    "file_sell": "Nchekwa ire faịlụ",
    "file_sell_info": "Diski nchekwa igwe ojii efu maka ire faịlụ (Super fast)",
    "file_size": "Oke kachasị nke faịlụ ọ bụla",
    "file_size_info": "Oke kachasị nke faịlụ ọ bụla maka ire ere (ị nwere ike bulite ihe karịrị otu faịlụ maka ngwaahịa ọ bụla)"
  },
  "products": {
    "title": "Ngwaahịa"
  },
  "seo": {
    "title": "SEO",
    "meta": "Meta mkpado",
    "meta_info": "Mepụta mkpado meta dị elu na-akpaghị aka",
    "jsonld": "JSON-LD",
    "jsonld_info": "Data Haziri",
    "amp": "AMP",
    "amp_info": "Ibe mkpanaaka emelitere",
    "compress": "Mkpakọ onyonyo",
    "compress_info": "jpg, png, svg, wpng,...",
    "boost": "Ọsọ osooso",
    "boost_info": "Onye na-eme ihe nhazi ihu ihu maka igwe ọchụchọ",
    "sitemap": "map saịtị",
    "sitemap_info": "Map saịtị nchọta"
  },
  "other": {
    "title": "Atụmatụ ndị ọzọ",
    "plugins": "Tinye-ons & Ngwa",
    "plugins_info": "Ịnweta mgbakwunye ụlọ ahịa ere ere",
    "customer_service": "Ndị ọrụ nlekọta ndị ahịa",
    "customer_service_info": "Ajụjụ ndị a na-ajụkarị, fọm mmekọrịta ndị ahịa, njikwa nlọghachi...",
    "export": "Mbupụ ngwaahịa",
    "export_info": "Nweta faịlụ mmepụta nke ngwaahịa niile nwere ozi na ọdịnaya niile. Site na njirimara a, ị ga-enwe nchekwa data ọkọlọtọ nke ngwaahịa gị na-anọghị n'ịntanetị.",
    "import": "Bubata ngwaahịa na nnukwu",
    "import_info": "Selldone dị elu yana ọrụ akpaaka na-enyere gị aka iji foto 100% bulite ngwaahịa gị na-akpaghị aka na-akwụghị ụgwọ ọ bụla site na ọrụ nrụpụta ụlọ ahịa ọ bụla ma ọ bụ nchekwa data na-anọghị n'ịntanetị.",
    "Simultaneous": "N'otu oge"
  },
  "logistic": {
    "title": "Logistics",
    "logistic": "Logistics & Ụgbọ njem",
    "logistic_desc": "Njikwa nke ngwa ahịa na ụzọ mbupu",
    "private_transportation": "Usoro mbupu nkeonwe",
    "private_transportation_desc": "Mepụta ma jikwaa ọrụ mbupu nkeonwe.",
    "transportation": "Jikwaa ụzọ mbupu dị elu",
    "transportation_desc": "Ọrụ mbupu mpaghara na nke mba ụwa",
    "process_center": "Ebe nhazi ọkwa dị elu",
    "process_center_desc": "Ogwe njikwa iwu dị mfe iji",
    "return_requests": "Njikwa nlọghachi",
    "return_requests_desc": "Nye njikwa nlọghachi."
  },
  "marketing": {
    "title": "Ahịa & Ahịa",
    "campaign": "Mepụta ma jikwaa mkpọsa",
    "affiliate_marketing": "Mgbakwunye ahịa",
    "affiliate_marketing_desc": "Mepụta ma jikwaa atụmatụ ntinye aka ahịa",
    "email_marketing": "Ogwe ahịa ahịa email",
    "email_marketing_desc": "Ịmepụta na izipu ozi-e ezubere iche nye ndị na-ege ntị nwere nzacha na nzaghachi",
    "funnel": "Ihe nzacha onye ọrụ dị elu",
    "funnel_desc": "Wepụta ndị ọrụ site na okike, akụkọ ịzụ ahịa, nbanye ikpeazụ, wdg.",
    "ab_test": "A/B ule",
    "user_reaction": "Nyocha ibe ọdịda",
    "user_reaction_desc": "Lelee akụkụ ala na pịa nke ibe ọdịda dị ka maapụ okpomọkụ na eserese"
  },
  "customers": {
    "title": "Ndị ahịa & ihe mkpali",
    "club": "Klọb ndị ahịa",
    "discount_code": "Koodu nkwụnye ego",
    "discount_code_info": "Mepụta koodu mbelata ego na-akparaghị ókè.",
    "coupon": "Ụgwọ akwụkwọ / akwụkwọ ego",
    "coupon_info": "Nye ndị ahịa gị uru a kapịrị ọnụ, pasentị ma ọ bụ mbelata mbupu.",
    "gift_card": "Kaadị onyinye",
    "gift_card_info": "Mee kaadị chajị na-akparaghị ókè.",
    "offer": "Nye",
    "offer_desc": "Zụrụ ngwaahịa a, nweta nke ahụ n'efu (ma ọ bụ site na mbelata)",
    "game": "Ịgba egwu",
    "game_desc": "Chepụta egwuregwu nwere ihe nrite"
  },
  "bots": {
    "title": "Bots, netwọkụ mmekọrịta, na ọwa ire ere",
    "telegram": "Robot ire ere Telegram",
    "telegram_info": "Wulite ụlọ ahịa Telegram nke gị n'efu",
    "instagram": "Instagram",
    "instagram_info": "Jikọọ ụlọ ahịa gị na Instagram.",
    "facebook": "Facebook",
    "facebook_info": "Na-emepụta na ịmekọrịta ndepụta ngwaahịa njirimara zuru oke.",
    "avocado": "Avocado Social Media Sales Service",
    "avocado_info": "Site na ọrụ a, ị ga-enwe ike ịnata iwu n'aka ndị ahịa na-agbakwunyeghị ngwaahịa na site na ụdị na netwọk mmekọrịta.",
    "hyper": "Usoro ngwa ngwa Hyper",
    "hyper_info": "Ịre ọtụtụ narị ngwaahịa kwa nkeji na ngosi, ememme, ụlọ ahịa na ebe ọ bụla ịchọrọ ire ngwaahịa ụfọdụ nye ọnụ ọgụgụ buru ibu nke ndị ahịa."
  },
  "assistance": {
    "title": "Amamọkwa",
    "notifications": "Ọwa ọkwa",
    "email": "Email",
    "email_info": "Ziga ndị ahịa na ndị ọrụ ụlọ ahịa ozi-e.",
    "sms": "SMS",
    "sms_info": "Ziga SMS na ndị ahịa yana ndị ọrụ ụlọ ahịa.",
    "report": "Akụkọ Smart",
    "report_info": "Nyefee akụkọ kwa izu na kwa afọ maka adịghị ike ụlọ ahịa, ndị ọrụ na ịre ahịa, yana ndụmọdụ iji melite arụmọrụ gị yana ịbawanye ahịa."
  },
  "automation": {
    "title": "Akpaaka",
    "niomatic": "Niomatic",
    "niomatic_info": "Akpaaka usoro dị elu dabere na mmasị ngọngọ eserese",
    "autopilot": "Onye na-anya ụgbọ elu",
    "autopilot_info": "Hazie mmemme, mbelata ego, bipụta blọgụ, ngwaahịa na ihe ndị ọzọ."
  },
  "pos": {
    "title": "E rere POS",
    "pos": "Ụlọ ahịa ego",
    "pos_info": "Sistemu POS ejikọrọ na ụlọ ahịa dị n'ịntanetị na-enye gị ụlọ nkwakọba ihe, ịre ahịa, na usoro nkwado yana ngwa ọrụ pụrụ iche.",
    "online_payment": "Ịkwụ ụgwọ n'ịntanetị",
    "online_payment_info": "Enwere ike ịkwụ ụgwọ ịntanetị maka ndị ahịa gị n'ụlọ ahịa anụ ahụ gị.",
    "hardware": "Akụrụngwa",
    "hardware_info": "Ikike iji jikọọ na nyocha koodu koodu, ihe ngosi ndị ahịa na-eche ihu, ndị na-ebi akwụkwọ akara na ngwaike ndị ọzọ iji mee ka usoro ahịa dị mfe."
  },
  "dropshipping": {
    "title": "Ebe mbupu",
    "reseller": "Na-ere ere",
    "reseller_info": "Ị nwere ike tinye ngwaahịa nke wholesaler na ụlọ ahịa gị na otu click, niile mmezu na mbupu nzọụkwụ ga-eme na-akpaghị aka.",
    "wholesaler": "Onye na-ere ahịa",
    "wholesaler_info": "Ndị na-ere ere ga-ere ahịa ma ree ngwaahịa gị nke gị kwadoro."
  },
  "community": {
    "title": "Ogbe Nwube Platform",
    "available": "Ogbe omenala efu",
    "available_info": "Ikike ịmepụta obodo omenala",
    "nomination": "Site na nhọpụta",
    "domain": "ngalaba omenala",
    "domain_info": "Ị ga-enwe forum na ngalaba nke gị.",
    "onboarding": "Ịbanye",
    "onboarding_info": "Ikike ịgbakwunye onye nchịkwa na onye nhazi maka nnọkọ ahụ.",
    "seo": "SEO",
    "seo_info": "Ịkwesighi ịzụta ngwugwu ma ọ bụ plugins maka ọrụ SEO ọkachamara.",
    "analytic": "Nchịkọta",
    "analytic_info": "Ozi dị mfe ịhụ na ibe obodo.",
    "post": "Biputere",
    "post_info": "Oke mgbasa ozi kwa ọnwa.",
    "comment": "Ikwu",
    "comment_info": "Ikike izipu na jikwaa nkọwa.",
    "voice": "Olu",
    "voice_info": "Ikike ịdekọ na izipu ọdịyo ozugbo.",
    "video": "Vidiyo",
    "video_info": "Ikike izipu vidiyo (ruo 8 MB)",
    "product": "Ngwaahịa",
    "product_info": "Ikike izipu ngwaahịa ozugbo site na mail.",
    "poll": "Ntụli aka",
    "poll_info": "Ikike itinye ntuli aka na isiokwu.",
    "report": "Kpesa mmegbu",
    "report_info": "Ikike ịkọ mkpesa site n'aka ndị ọrụ.",
    "profile": "profaịlụ",
    "profile_info": "Profaịlụ onye ọrụ ahaziri onwe ya.",
    "sso": "Otu nbanye (SSO)",
    "sso_info": "Enwere ike ịbanye ngwa ngwa site na ọrụ Selldone SSO.",
    "embed": "Tinye",
    "embed_info": "Ikike itinye na ịkekọrịta posts.",
    "reaction": "Mmeghachi omume",
    "reaction_info": "Ndị ọrụ ga-enwe ike ịdekọ mmetụta ha nwere maka akụkọ.",
    "moderation": "Imeru ihe n'ókè",
    "moderation_info": "Tinye ma jikwaa ohere ọgbakọ."
  },
  "mission": {
    "title": "Anyị na-eje ozi ka",
    "message": "Mee ka azụmahịa dị mfe, nweta ya, yana nweta onye ọ bụla gburugburu ụwa"
  }
};