export default {
  "title": "Byrjaðu ókeypis, vaxa hratt!",
  "sub_title": "Ótakmarkaður aðgangur að öllum eiginleikum án kostnaðar! Aðeins <b>2% af sölu</b> , rétt eftir vel heppnuð kaup. Ertu með mikla sölu og vilt lækka gjöldin?",
  "show_detail_list": "Sýna upplýsingar lista",
  "plan_free_detail": "<b class='text-capitalize'>Stýrikerfi fyrir ört vaxandi fyrirtæki</b> | Byrjaðu fyrirtæki þitt með ókeypis áætlun okkar. Allt sem þú þarft til að hefja og opna netverslunarvefsíðuna þína er tilbúið hér. Selldone býður upp á allan hugbúnað, verkfæri og skýhýsingarlausn með ókeypis áskriftaráætlun. Selldone sér að auki um allar hugbúnaðaruppfærslur og öryggissjónarmið. Þannig að þú getur einbeitt þér að því að selja og ekki hafa áhyggjur af tæknilegum vandamálum og kostnaði.",
  "pay_monthly": "Borga mánaðarlega",
  "pay_yearly": "Borga árlega",
  "pay_yearly_off": "30% afsláttur",
  "transparency_title": "Gagnsæi í þjónustu",
  "monthly_cost": "Mánaðarverð",
  "suggested_plan": "Tillaga að áætlun",
  "monthly_sell": "Mánaðarleg sala",
  "saving_amount": "Sparnaður mánaðarlega",
  "saving_tips": "Með því að kaupa fyrirhugaða áætlun spararðu þessa upphæð mánaðarlega.",
  "have_all_features": "Þú munt hafa alla eiginleika.",
  "currency": "USD",
  "want_free": "Viltu ókeypis?",
  "stack_price": "Settu {amount} milljón tákn á sekúndu",
  "gift": "Sérstök gjöf",
  "gift_info": "Fáðu þessa gjöf með því að kaupa þessa áætlun.",
  "toke_gift_ratio": "Jafngildir þeirri upphæð sem greidd er",
  "unlimited": "Ótakmarkað",
  "items_unit": "x",
  "delivery_person_unit": "Sendiboðar",
  "soon": "Kemur bráðum",
  "domains": "Sérsniðin lén",
  "staff": "Stjórnendur",
  "community_builder": "Samfélagsbyggjandi",
  "active_discount_codes": "Virkir afsláttarkóðar",
  "active_coupons": "Virkir háþróaðir afsláttarmiðar",
  "active_offers": "Virk háþróuð tilboð",
  "active_gift_card_types": "Gjafakortaforrit",
  "active_campaigns": "Virkar markaðsherferðir",
  "active_affiliates": "Virkir samstarfsaðilar",
  "active_emails": "Virkar markaðsherferðir í tölvupósti",
  "active_transportation_persons": "Einka sendiboðar",
  "active_importing_que": "Hámarks samtímis innflutningur á vörum",
  "active_reselling": "Endursala; Selja heildsala hluti",
  "max_file_size": "Hámarks skráarstærð til að selja; Það fer eftir þínu svæði Euro/US/...",
  "active_capacity": "Laust diskpláss",
  "active_drop_shipping": "Heildsölu dropshipping (staðfesting þarf)",
  "common_features": "Innifalið í öllum {license} áætlunum",
  "unlimited_storage": "Ótakmarkað geymsla",
  "priority_support": "Forgangsstuðningur",
  "support_247": "24/7 stuðningur",
  "read_more": "Lestu meira um eiginleika...",
  "partners_upgrade_suggestion_message": "Þú ert ekki með besta mögulega samninginn á {name}! Við mælum eindregið með því að uppfæra það á hæsta stig ef þér líkar ekki við takmörkin.",
  "partners_upgrade_suggestion_action": "Uppfærðu áskriftina þína á {name} núna",
  "free": {
    "title": "Persónulegt",
    "info": "Fyrir fólk sem er að byrja",
    "cost": "Ókeypis",
    "fee_percent": 2,
    "items": [
      "Ótakmarkaðar vörur",
      "1GB geymsla",
      "Ótakmörkuð bandbreidd",
      "Allir faglegir eiginleikar og verkfæri fylgja með",
      "Drag & slepptu áfangasíðugerð",
      "Full lögun CMS og blogg",
      "3 Virkir afsláttarkóðar",
      "3 Virkir háþróaðir afsláttarmiðar",
      "3 Virk háþróuð tilboð",
      "1 Gjafakortaforrit",
      "2 Virkar markaðsherferðir",
      "2 Virk tengd forrit",
      "2 Virkar markaðsherferðir í tölvupósti",
      "2 einkapóstsendingar",
      "Öll sendingarþjónusta",
      "1 Stjórnandi"
    ]
  },
  "startup": {
    "title": "Gangsetning",
    "info": "Fyrir lítil fyrirtæki rétt að byrja",
    "fee_percent": 1.5,
    "items": [
      "Allir ókeypis eiginleikar fylgja með",
      "10GB geymsla",
      "SMS innskráning viðskiptavina",
      "3D / AR samþætting",
      "10 Virkir afsláttarkóðar",
      "10 Virkir háþróaðir afsláttarmiðar",
      "10 Virk háþróuð tilboð",
      "10 gjafakortaforrit",
      "10 Virkar markaðsherferðir",
      "10 Virk tengd forrit",
      "10 Virkar markaðsherferðir í tölvupósti",
      "10 einkapóstsendingar",
      "Venjulegur stuðningur",
      "1 Lén",
      "5 stjórnendur"
    ]
  },
  "company": {
    "title": "Fyrirtæki",
    "info": "Lítil og meðalstór staðbundin fyrirtæki",
    "fee_percent": 1,
    "items": [
      "Allir ræsiaðgerðir fylgja með",
      "Ótakmarkað geymsla",
      "50 Virkir afsláttarkóðar",
      "50 Virkir háþróaðir afsláttarmiðar",
      "50 Virk háþróuð tilboð",
      "50 gjafakortaforrit",
      "50 Virkar markaðsherferðir",
      "100 virk tengd forrit",
      "100 virkar markaðsherferðir í tölvupósti",
      "50 einkapóstsendingar",
      "Forgangsstuðningur",
      "5 lén",
      "20 Stjórnendur"
    ]
  },
  "enterprise": {
    "title": "Fyrirtæki",
    "info": "Stórfyrirtæki",
    "fee_percent": 0.5,
    "items": [
      "Allir eiginleikar fyrirtækisins fylgja með",
      "1K Virkir afsláttarkóðar",
      "1K Virkir háþróaðir afsláttarmiðar",
      "1K Active háþróuð tilboð",
      "1K gjafakortaforrit",
      "1K Virkar markaðsherferðir",
      "1K virk tengd forrit",
      "1K Virkar markaðsherferðir í tölvupósti",
      "200 einkapóstsendingar",
      "24/7 stuðningur",
      "∞ Lén",
      "∞ Stjórnendur"
    ]
  },
  "features": {
    "title": "Eiginleikar",
    "products": "Vörur",
    "usage": "Mánaðarleg umferð",
    "custom_domain": "Bættu við sérsniðnu léni",
    "invite_to_get_free": "Bjóddu vini og fáðu það ókeypis",
    "ssl": "SSL staðfesting",
    "support": "24/7 stuðningur",
    "staff": "Fjöldi stjórnenda",
    "staff_info": "Gefðu liðsmönnum þínum aðgang.",
    "person": "manneskja(r)",
    "shop_name_length": "Lágmarkslengd verslunarheita",
    "chars": "Karakter",
    "page_builder": "Búðu til þína eigin síðu",
    "page_builder_info": "Drag & slepptu áfangasíðugerð",
    "pages": "Síður",
    "cms": "CMS og blogg",
    "cms_info": "Faglegt efnisstjórnunar- og ritstjórakerfi fyrir bloggfærslur og vörur."
  },
  "gateways": {
    "title": "Greiðslugátt",
    "sub_title": "Nýjum höfnum verður bætt við fljótlega.",
    "gateways": "Gáttir",
    "currencies": "Gjaldmiðlar",
    "currencies_info": "Nýjum gjaldmiðlum verður bætt við fljótlega.",
    "currencies_encrypted": "Gjaldmiðilskóði",
    "currencies_encrypted_info": "Gjaldmiðlar á blockchain vettvang",
    "online_pay_wage": "Hafnargjald á netinu",
    "online_pay_wage_info": "Þessi upphæð verður dregin af endurhleðslureikningnum þínum í Selldone.",
    "cod_wage": "COD greiðslugjöld",
    "cod_wage_info": "Þessi upphæð verður dregin af gjaldreikningnum þínum",
    "file_wage": "Skráasölugjald",
    "file_wage_info": "Skráasöluþóknun sem er lögð inn á reikninginn þinn eftir vel heppnaða sölu (Hýst á seldri háhraða SSD skýgeymslu)."
  },
  "apps": {
    "title": "Store / Site App",
    "pwa": "Ítarlegt vefforrit",
    "android": "Android",
    "android_info": "Android síma- og spjaldtölvuforrit",
    "ios": "iOS (kemur bráðum)",
    "ios_info": "Apple síma- og spjaldtölvuforrit"
  },
  "custom_domain": {
    "title": "Sérsniðið lén",
    "sub_title": "Hafðu verslunina þína á þínu eigin léni.",
    "domains_count": "Fjöldi verslunarléna",
    "dns": "Cloud DNS",
    "cdn": "Cloud CDN",
    "cdn_info": "Cloud Content Explanation Network"
  },
  "host": {
    "title": "Ókeypis Cloud Host / Server",
    "ssl": "SSL vottun",
    "storage": "Geymsla",
    "usage": "Mánaðarleg umferð",
    "setup": "Ókeypis uppsetning",
    "technical_support": "tækniaðstoð",
    "file_sell": "Skráasölugeymsla",
    "file_sell_info": "Ókeypis skýjageymsludiskur til að selja skrár (ofur hratt)",
    "file_size": "Hámarksstærð hverrar skráar",
    "file_size_info": "Hámarksstærð hverrar skráar til sölu (þú getur hlaðið upp fleiri en einni skrá fyrir hverja vöru)"
  },
  "products": {
    "title": "Vörur"
  },
  "seo": {
    "title": "SEO",
    "meta": "Metamerki",
    "meta_info": "Búðu til fullkomlega háþróuð meta tags sjálfkrafa",
    "jsonld": "JSON-LD",
    "jsonld_info": "Skipulögð gögn",
    "amp": "AMP",
    "amp_info": "Hraðvirkar farsímasíður",
    "compress": "Myndþjöppun",
    "compress_info": "jpg, png, svg, wpng, ...",
    "boost": "Hraða hröðun",
    "boost_info": "Síðuhleðsluáætlun fyrir leitarvélar",
    "sitemap": "Veftré",
    "sitemap_info": "Leitarvél Veftré"
  },
  "other": {
    "title": "Aðrir eiginleikar",
    "plugins": "Viðbætur og forrit",
    "plugins_info": "Aðgangur að Selldone Store viðbótum",
    "customer_service": "Þjónustuver",
    "customer_service_info": "Algengar spurningar, eyðublað fyrir viðskiptatengsl, skilastjórnun ...",
    "export": "Flytja út vörur",
    "export_info": "Fáðu úttaksskrár af öllum vörum með öllum upplýsingum og innihaldi. Með þessum eiginleika muntu hafa staðlaðan gagnagrunn yfir vörur þínar án nettengingar.",
    "import": "Flytja inn vörur í lausu",
    "import_info": "Sellone háþróuð og sjálfvirk þjónusta hjálpar þér að hlaða upp vörum þínum með myndum 100% sjálfkrafa án þess að þurfa að borga neinn kostnað af annarri þjónustu sem byggir verslun eða offline gagnagrunninum þínum.",
    "Simultaneous": "Samtímis"
  },
  "logistic": {
    "title": "Logistics",
    "logistic": "Vöruflutningar og flutningar",
    "logistic_desc": "Umsjón með birgðum og sendingaraðferðum",
    "private_transportation": "Einkaskipakerfi",
    "private_transportation_desc": "Búðu til og stjórnaðu einkaflutningaþjónustu.",
    "transportation": "Stjórna háþróuðum sendingaraðferðum",
    "transportation_desc": "Staðbundin og alþjóðleg sendingarþjónusta",
    "process_center": "Háþróuð vinnslustöð",
    "process_center_desc": "Auðvelt í notkun pantanastjórnunarborð",
    "return_requests": "Skilastjórnun",
    "return_requests_desc": "Skilastjórnun pantana."
  },
  "marketing": {
    "title": "Markaðssetning og sala",
    "campaign": "Búðu til og stjórnaðu herferð",
    "affiliate_marketing": "Tengja markaðssetning",
    "affiliate_marketing_desc": "Búðu til og stjórnaðu söluáætlanir",
    "email_marketing": "Markaðssetning tölvupósts",
    "email_marketing_desc": "Hanna og senda markvissa tölvupósta til áhorfenda með síum og endurgjöf",
    "funnel": "Ítarleg notendasía",
    "funnel_desc": "Sía notendur eftir kyni, innkaupasögu, síðustu innskráningu osfrv.",
    "ab_test": "A/B próf",
    "user_reaction": "Áfangasíðugreining",
    "user_reaction_desc": "Skoðaðu lönduðu og smelltu hluta áfangasíðunnar sem hitakort og skýringarmynd"
  },
  "customers": {
    "title": "Viðskiptavinir og hvatningar",
    "club": "Viðskiptavinaklúbbur",
    "discount_code": "Afsláttarkóði",
    "discount_code_info": "Búðu til ótakmarkaða afsláttarkóða.",
    "coupon": "Afsláttarmiði / skírteini",
    "coupon_info": "Bjóddu viðskiptavinum þínum fast verðmæti, prósentu eða sendingarafslátt.",
    "gift_card": "Gjafakort",
    "gift_card_info": "Búðu til ótakmarkað gjaldkort.",
    "offer": "Tilboð",
    "offer_desc": "Kauptu þessa vöru, fáðu hana ókeypis (eða með afslætti)",
    "game": "Gamification",
    "game_desc": "Hannaðu leik með verðlaunum"
  },
  "bots": {
    "title": "Bots, samfélagsnet og sölurásir",
    "telegram": "Telegram söluvélmenni",
    "telegram_info": "Byggðu þína eigin Telegram búð ókeypis",
    "instagram": "Instagram",
    "instagram_info": "Tengdu verslunina þína við Instagram.",
    "facebook": "Facebook",
    "facebook_info": "Sjálfvirk framleiðslu og samstilling vörulista með fullum eiginleikum.",
    "avocado": "Avókadó söluþjónusta á samfélagsmiðlum",
    "avocado_info": "Með þessari þjónustu muntu geta tekið á móti pöntunum frá viðskiptavinum án þess að bæta við vöru og í gegnum eyðublað á samfélagsnetum.",
    "hyper": "Hyper Quick Order",
    "hyper_info": "Að selja hundruð vara á mínútu á sýningum, hátíðum, sölubásum og hvar sem þú vilt selja nokkrar vörur til fjölda viðskiptavina."
  },
  "assistance": {
    "title": "Tilkynningar",
    "notifications": "Tilkynningarrásir",
    "email": "Tölvupóstur",
    "email_info": "Sendu tölvupóst til viðskiptavina og starfsfólks verslana.",
    "sms": "SMS",
    "sms_info": "Sendu SMS til viðskiptavina og starfsfólks verslana.",
    "report": "Snjöll skýrsla",
    "report_info": "Sendu vikulegar og árlegar reglubundnar skýrslur um veikleika verslana, notendur og sölu, ásamt ráðum til að bæta árangur þinn og auka sölu."
  },
  "automation": {
    "title": "Sjálfvirkni",
    "niomatic": "Niomatic",
    "niomatic_info": "Háþróuð ferli sjálfvirkni byggt á myndrænum blokkastillingum",
    "autopilot": "Sjálfstýring",
    "autopilot_info": "Skipuleggðu viðburði, afslætti, birtu bloggfærslur, vörur og annað."
  },
  "pos": {
    "title": "Seldóna POS",
    "pos": "Gjaldkeri verslunar",
    "pos_info": "Póstkerfið sem er tengt við netverslunina þína veitir þér öll geymslu-, sölu- og stuðningsferli með einstöku notendaviðmóti.",
    "online_payment": "Greiðsla á netinu",
    "online_payment_info": "Möguleiki á greiðslu á netinu fyrir viðskiptavini þína í líkamlegu versluninni þinni.",
    "hardware": "Vélbúnaður",
    "hardware_info": "Geta til að tengjast strikamerkjaskanna, skjáum sem snúa að viðskiptavinum, merkimiðaprentara og annan vélbúnað til að einfalda söluferlið."
  },
  "dropshipping": {
    "title": "Dropshipping miðstöð",
    "reseller": "Endurselja",
    "reseller_info": "Þú getur bætt vörum heildsala við verslunina þína með einum smelli, öll uppfyllingar- og sendingarskref verða gerð sjálfkrafa.",
    "wholesaler": "Heildsali",
    "wholesaler_info": "Vörur þínar verða markaðssettar og seldar af söluaðilum sem þú hefur samþykkt."
  },
  "community": {
    "title": "Samfélagsbyggingarvettvangur",
    "available": "Ókeypis sérsniðið samfélag",
    "available_info": "Geta til að búa til sérsniðið samfélag",
    "nomination": "Með tilnefningu",
    "domain": "Sérsniðið lén",
    "domain_info": "Þú munt hafa spjallborðið á þínu eigin léni.",
    "onboarding": "Um borð",
    "onboarding_info": "Geta til að bæta við stjórnanda og stjórnanda fyrir spjallborðið.",
    "seo": "SEO",
    "seo_info": "Þú þarft ekki að kaupa viðbótarpakka eða viðbætur fyrir faglega SEO þjónustu.",
    "analytic": "Greining",
    "analytic_info": "Upplýsingar eru auðveldlega sýnilegar á samfélagssíðum.",
    "post": "Post",
    "post_info": "Mánaðarlegt pósttakmark.",
    "comment": "Athugasemd",
    "comment_info": "Geta til að senda og stjórna athugasemdum.",
    "voice": "Rödd",
    "voice_info": "Geta til að taka upp og senda beint hljóð.",
    "video": "Myndband",
    "video_info": "Geta til að senda myndskeið (allt að 8 MB)",
    "product": "Vara",
    "product_info": "Möguleiki á að senda vöruna beint í pósti.",
    "poll": "Könnun",
    "poll_info": "Möguleiki á að bæta skoðanakönnunum við efni.",
    "report": "Tilkynna misnotkun",
    "report_info": "Geta til að tilkynna misnotkun notenda.",
    "profile": "prófíl",
    "profile_info": "Sérsniðið notendasnið.",
    "sso": "Einskráning (SSO)",
    "sso_info": "Möguleiki á skjótri innskráningu í gegnum Selldone SSO þjónustu.",
    "embed": "Fella inn",
    "embed_info": "Geta til að fella inn og deila færslum.",
    "reaction": "Viðbrögð",
    "reaction_info": "Notendur munu geta skráð hvernig þeim finnst um sögu.",
    "moderation": "Hófsemi",
    "moderation_info": "Bættu við og stjórnaðu aðgangi að spjallborði."
  },
  "mission": {
    "title": "Við erum í því verkefni að",
    "message": "Gerðu viðskipti auðveld, framkvæmanleg og aðgengileg fyrir alla um allan heim"
  }
};