export default {
  "title": "無料で始めて、速く成長しましょう！",
  "sub_title": "すべての機能に無料で無制限にアクセスできます！購入が成功した直後<b>の売上のわずか2％</b> 。あなたはたくさんの売り上げがあり、料金を下げたいですか？",
  "show_detail_list": "詳細リストを表示",
  "plan_free_detail": "<b class='text-capitalize'>急成長しているビジネスのためのオペレーティングシステム</b>|私たちの無料プランであなたのビジネスを始めましょう。 eコマースウェブサイトを開始して立ち上げるために必要なものはすべてここに用意されています。 Selldoneは、すべてのソフトウェア、ツール、およびクラウドホスティングソリューションを無料のサブスクリプションプランで提供します。 Selldoneはさらに、すべてのソフトウェアアップデートとセキュリティの考慮事項を処理します。そのため、技術的な問題やコストを気にせずに、販売に全力を注ぐことができます。",
  "pay_monthly": "月払い",
  "pay_yearly": "年払い",
  "pay_yearly_off": "30％オフ",
  "transparency_title": "サービスの透明性",
  "monthly_cost": "月額料金",
  "suggested_plan": "提案された計画",
  "monthly_sell": "月間売上高",
  "saving_amount": "毎月の節約",
  "saving_tips": "提案されたプランを購入することにより、この金額を毎月節約できます。",
  "have_all_features": "すべての機能があります。",
  "currency": "USD",
  "want_free": "無料にしたいですか？",
  "stack_price": "1秒間に{amount}百万トークンをスタックする",
  "gift": "特別なプレゼント",
  "gift_info": "このプランを購入してこのギフトを手に入れましょう。",
  "toke_gift_ratio": "支払った金額に相当",
  "unlimited": "無制限",
  "items_unit": "バツ",
  "delivery_person_unit": "宅配便",
  "soon": "近日公開",
  "domains": "カスタムドメイン",
  "staff": "管理者",
  "community_builder": "コミュニティビルダー",
  "active_discount_codes": "アクティブな割引コード",
  "active_coupons": "アクティブなアドバンスクーポン",
  "active_offers": "アクティブな高度なオファー",
  "active_gift_card_types": "ギフトカードプログラム",
  "active_campaigns": "アクティブなマーケティングキャンペーン",
  "active_affiliates": "アクティブなアフィリエイト",
  "active_emails": "アクティブなEメールマーケティングキャンペーン",
  "active_transportation_persons": "プライベート宅配便",
  "active_importing_que": "最大同時製品輸入",
  "active_reselling": "再販;卸売業者の商品を売る",
  "max_file_size": "販売する最大ファイルサイズ。お住まいの地域に応じてユーロ/米国/...",
  "active_capacity": "ディスクの空き容量",
  "active_drop_shipping": "卸売ドロップシッピング（確認が必要）",
  "common_features": "すべての{license}プランに含まれています",
  "unlimited_storage": "無制限のストレージ",
  "priority_support": "優先サポート",
  "support_247": "24時間年中無休のサポート",
  "read_more": "機能についてもっと読む...",
  "partners_upgrade_suggestion_message": "あなたは{name}で可能な限り最良の取引をしていません！制限が気に入らない場合は、最高レベルにアップグレードすることを強くお勧めします。",
  "partners_upgrade_suggestion_action": "今すぐ{name}でプランをアップグレードしてください",
  "free": {
    "title": "個人的",
    "info": "始めたばかりの人のために",
    "cost": "無料",
    "fee_percent": 2,
    "items": [
      "無制限の製品",
      "1GBのストレージ",
      "無制限の帯域幅",
      "含まれているすべての専門的な機能とツール",
      "ランディングページビルダーのドラッグアンドドロップ",
      "フル機能のCMSとブログ",
      "3アクティブな割引コード",
      "3アクティブアドバンスクーポン",
      "3アクティブな高度なオファー",
      "1ギフトカードプログラム",
      "2アクティブなマーケティングキャンペーン",
      "2アクティブなアフィリエイトプログラム",
      "2アクティブなEメールマーケティングキャンペーン",
      "2つのプライベート宅配便",
      "すべての配送サービス",
      "1管理者",
      "コミュニティビルダー（ベーシック）"
    ]
  },
  "startup": {
    "title": "起動",
    "info": "始めたばかりの中小企業向け",
    "fee_percent": 1.5,
    "items": [
      "すべての無料機能が含まれています",
      "10GBのストレージ",
      "顧客のSMSログイン",
      "3D/AR統合",
      "10アクティブな割引コード",
      "10アクティブアドバンスクーポン",
      "10アクティブな高度なオファー",
      "10ギフトカードプログラム",
      "10のアクティブなマーケティングキャンペーン",
      "10アクティブなアフィリエイトプログラム",
      "10のアクティブなEメールマーケティングキャンペーン",
      "10のプライベート宅配便",
      "通常のサポート",
      "1ドメイン",
      "5人の管理者",
      "コミュニティビルダー（ベーシック）"
    ]
  },
  "company": {
    "title": "会社",
    "info": "中小の地元企業",
    "fee_percent": 1,
    "items": [
      "含まれているすべてのスタートアップ機能",
      "無制限のストレージ",
      "50のアクティブな割引コード",
      "50アクティブアドバンスクーポン",
      "50のアクティブな高度なオファー",
      "50ギフトカードプログラム",
      "50のアクティブなマーケティングキャンペーン",
      "100のアクティブなアフィリエイトプログラム",
      "100のアクティブなEメールマーケティングキャンペーン",
      "50のプライベート宅配便",
      "優先サポート",
      "5つのドメイン",
      "20人の管理者",
      "コミュニティビルダー（ノーマル）"
    ]
  },
  "enterprise": {
    "title": "企業",
    "info": "大規模企業",
    "fee_percent": 0.5,
    "items": [
      "すべての会社の機能が含まれています",
      "1Kアクティブ割引コード",
      "1Kアクティブアドバンストクーポン",
      "1Kアクティブアドバンスドオファー",
      "1Kギフトカードプログラム",
      "1Kアクティブマーケティングキャンペーン",
      "1Kアクティブアフィリエイトプログラム",
      "1KアクティブなEメールマーケティングキャンペーン",
      "200のプライベート宅配便",
      "24時間年中無休のサポート",
      "∞ドメイン",
      "∞管理者",
      "コミュニティビルダー（上級）",
      "ドロップシッピングサプライヤー",
      "マーケットプレイスビルダー"
    ]
  },
  "features": {
    "title": "特徴",
    "products": "製品",
    "usage": "月間トラフィック",
    "custom_domain": "カスタムドメインを追加する",
    "invite_to_get_free": "友達を招待して無料でゲット",
    "ssl": "SSL確認",
    "support": "24時間年中無休のサポート",
    "staff": "管理者の数",
    "staff_info": "チームメンバーにアクセスを許可します。",
    "person": "人）",
    "shop_name_length": "店舗名の最小の長さ",
    "chars": "キャラクター",
    "page_builder": "独自のページを作成する",
    "page_builder_info": "ランディングページビルダーのドラッグアンドドロップ",
    "pages": "ページ",
    "cms": "CMSとブログ",
    "cms_info": "ブログ投稿および製品用のプロフェッショナルコンテンツ管理およびエディターシステム。",
    "tax": "税金の計算",
    "tax_info": "顧客の所在地、B2B/B2C 売上に基づいて自動税を計算し、国や州の税金ルールを上書きする機能。",
    "tax_profiles": "税務プロファイル - プロフェッショナル",
    "tax_profiles_info": "税金プロファイルを作成することで、商品に専用の売上税ルールを設定できます。",
    "extra_tax_profiles": "追加の {count} 個のプロファイル。",
    "tax_profile_fee": "手数料0.0％（完全無料サービス）",
    "tax_pro": "プロ。"
  },
  "gateways": {
    "title": "支払いポータル",
    "sub_title": "新しいポートはまもなく追加されます。",
    "gateways": "ゲートウェイ",
    "currencies": "通貨",
    "currencies_info": "新しい通貨はまもなく追加されます。",
    "currencies_encrypted": "通貨コード",
    "currencies_encrypted_info": "ブロックチェーンプラットフォームの通貨",
    "online_pay_wage": "オンラインポート料金",
    "online_pay_wage_info": "この金額は、Selldoneのリチャージアカウントから差し引かれます。",
    "cod_wage": "代金引換手数料",
    "cod_wage_info": "この金額は、請求先アカウントから差し引かれます",
    "file_wage": "ファイル販売手数料",
    "file_wage_info": "販売が成功した後にアカウントに入金されるファイル販売手数料（selldone高速SSDクラウドストレージでホストされます）。"
  },
  "apps": {
    "title": "ストア/サイトアプリ",
    "pwa": "高度なWebアプリ",
    "android": "アンドロイド",
    "android_info": "Android携帯およびタブレットアプリ",
    "ios": "iOS（近日公開）",
    "ios_info": "Apple Phone＆Tabletアプリ"
  },
  "custom_domain": {
    "title": "カスタムドメイン",
    "sub_title": "あなた自身のドメインにあなたの店を持ってください。",
    "domains_count": "ストアドメインの数",
    "dns": "クラウドDNS",
    "cdn": "クラウドCDN",
    "cdn_info": "クラウドコンテンツ説明ネットワーク"
  },
  "host": {
    "title": "無料のクラウドホスト/サーバー",
    "ssl": "SSL認証",
    "storage": "ストレージ",
    "usage": "月間トラフィック",
    "setup": "無料セットアップ",
    "technical_support": "技術サポート",
    "file_sell": "ファイル販売ストレージ",
    "file_sell_info": "ファイルを販売するための無料のクラウドストレージディスク（超高速）",
    "file_size": "各ファイルの最大サイズ",
    "file_size_info": "販売する各ファイルの最大サイズ（製品ごとに複数のファイルをアップロードできます）"
  },
  "products": {
    "title": "製品"
  },
  "seo": {
    "title": "SEO",
    "meta": "メタタグ",
    "meta_info": "完全に高度なメタタグを自動的に作成する",
    "jsonld": "JSON-LD",
    "jsonld_info": "構造化データ",
    "amp": "AMP",
    "amp_info": "Accelerated Mobile Pages",
    "compress": "画像圧縮",
    "compress_info": "jpg、png、svg、wpng、..。",
    "boost": "スピードアクセラレータ",
    "boost_info": "検索エンジン用のページ読み込みスケジューラ",
    "sitemap": "サイトマップ",
    "sitemap_info": "検索エンジンのサイトマップ"
  },
  "other": {
    "title": "その他の機能",
    "plugins": "アドオンとアプリケーション",
    "plugins_info": "Selldoneストアアドオンへのアクセス",
    "customer_service": "顧客サービス",
    "customer_service_info": "よくある質問、顧客関係フォーム、返品管理..。",
    "export": "製品の輸出",
    "export_info": "すべての情報とコンテンツを含むすべての製品の出力ファイルを受信します。この機能を使用すると、製品の標準データベースをオフラインにすることができます。",
    "import": "製品をまとめてインポートする",
    "import_info": "Selldoneの高度な自動サービスを使用すると、他のストアビルダーサービスやオフラインデータベースから費用を支払うことなく、画像付きの商品を100％自動的にアップロードできます。",
    "Simultaneous": "同時に"
  },
  "Logistics": {
    "title": "ロジスティクス",
    "Logistics": "ロジスティクスと輸送",
    "Logistics_desc": "在庫管理と配送方法",
    "private_transportation": "専用配送システム",
    "private_transportation_desc": "プライベート配送サービスを作成および管理します。",
    "transportation": "高度な配送方法を管理する",
    "transportation_desc": "国内および国際配送サービス",
    "process_center": "高度な処理センター",
    "process_center_desc": "使いやすい注文管理パネル",
    "return_requests": "返品管理",
    "return_requests_desc": "注文返品管理。"
  },
  "marketing": {
    "title": "マーケティング販売",
    "campaign": "キャンペーンの作成と管理",
    "affiliate_marketing": "アフィリエイトマーケティング",
    "affiliate_marketing_desc": "セールスエンゲージメントプランを作成および管理する",
    "email_marketing": "メールマーケティングパネル",
    "email_marketing_desc": "フィルタとフィードバックを使用して、対象を絞った電子メールを設計してオーディエンスに送信する",
    "funnel": "高度なユーザーフィルター",
    "funnel_desc": "性別、購入履歴、最終ログインなどでユーザーをフィルタリングします。",
    "ab_test": "A/Bテスト",
    "user_reaction": "ランディングページ分析",
    "user_reaction_desc": "ランディングページのランディングセクションとクリックセクションをサーマルマップと図として表示します"
  },
  "customers": {
    "title": "顧客とインセンティブ",
    "club": "クライアントクラブ",
    "discount_code": "ディスカウントコード",
    "discount_code_info": "無制限の割引コードを作成します。",
    "coupon": "クーポン/バウチャー",
    "coupon_info": "顧客に固定値、パーセンテージ、または送料割引を提供します。",
    "gift_card": "ギフトカード",
    "gift_card_info": "無制限のチャージカードを作成します。",
    "offer": "オファー",
    "offer_desc": "この製品を購入して、無料で（または割引で）入手してください",
    "game": "ゲーミフィケーション",
    "game_desc": "賞品を使ってゲームをデザインする"
  },
  "bots": {
    "title": "ボット、ソーシャルネットワーク、および販売チャネル",
    "telegram": "電報販売ロボット",
    "telegram_info": "無料で独自の電報ショップを構築する",
    "instagram": "インスタグラム",
    "instagram_info": "ストアをInstagramに接続します。",
    "facebook": "フェイスブック",
    "facebook_info": "全機能製品リストの自動生成と同期。",
    "avocado": "アボカドソーシャルメディアセールスサービス",
    "avocado_info": "このサービスを利用すると、商品を追加することなく、ソーシャルネットワーク上のフォームを介して顧客から注文を受け取ることができます。",
    "hyper": "ハイパークイックオーダー",
    "hyper_info": "見本市、お祭り、屋台など、多数の顧客に製品を販売したい場所で、毎分数百の製品を販売すること。"
  },
  "assistance": {
    "title": "通知",
    "notifications": "通知チャネル",
    "email": "Eメール",
    "email_info": "顧客や店舗スタッフにメールを送信します。",
    "sms": "SMS",
    "sms_info": "顧客と店舗スタッフにSMSを送信します。",
    "report": "スマートレポート",
    "report_info": "店舗の弱点、ユーザー、売上に関する週次および年次の定期レポートを、パフォーマンスを向上させて売上を増やすためのヒントとともに送信します。"
  },
  "automation": {
    "title": "オートメーション",
    "niomatic": "ニオマティック",
    "niomatic_info": "グラフィカルなブロック設定に基づく高度なプロセス自動化",
    "autopilot": "オートパイロット",
    "autopilot_info": "イベントのスケジュール、割引、ブログ投稿、製品などの公開。",
    "webhook": "Webhook",
    "webhook_info": "イベントによってトリガーされる一方向のデータ共有を強化する軽量 API。"
  },
  "pos": {
    "title": "Selldone POS",
    "pos": "キャッシャーを保管する",
    "pos_info": "オンラインストアに接続されたPOSシステムは、独自のユーザーインターフェイスを備えたすべての倉庫保管、販売、およびサポートプロセスを提供します。",
    "online_payment": "オンライン支払い",
    "online_payment_info": "実店舗での顧客のオンライン支払いの可能性。",
    "hardware": "ハードウェア",
    "hardware_info": "バーコードスキャナー、顧客向けディスプレイ、ラベルプリンター、その他のハードウェアに接続して、販売プロセスを簡素化する機能。"
  },
  "dropshipping": {
    "title": "ドロップシッピングハブ",
    "reseller": "再販",
    "reseller_info": "あなたはワンクリックであなたの店に卸売業者の製品を加えることができます、すべての履行と輸送ステップは自動的に行われます。",
    "wholesaler": "卸売業者",
    "wholesaler_info": "あなたの製品は、あなたが承認した再販業者によって販売および販売されます。"
  },
  "community": {
    "title": "コミュニティビルダープラットフォーム",
    "available": "無料のカスタムコミュニティ",
    "available_info": "カスタムコミュニティを作成する機能",
    "nomination": "指名による",
    "domain": "カスタムドメイン",
    "domain_info": "自分のドメインにフォーラムがあります。",
    "onboarding": "オンボーディング",
    "onboarding_info": "フォーラムの管理者とモデレーターを追加する機能。",
    "seo": "SEO",
    "seo_info": "プロのSEOサービスのために追加のパッケージやプラグインを購入する必要はありません。",
    "analytic": "分析",
    "analytic_info": "情報はコミュニティページに簡単に表示されます。",
    "post": "役職",
    "post_info": "毎月の投稿制限。",
    "comment": "コメント",
    "comment_info": "コメントを送信および管理する機能。",
    "voice": "声",
    "voice_info": "直接音声を録音して送信する機能。",
    "video": "ビデオ",
    "video_info": "ビデオを送信する機能（最大8 MB）",
    "product": "製品",
    "product_info": "製品を直接郵送する機能。",
    "poll": "投票",
    "poll_info": "トピックに投票を追加する機能。",
    "report": "不正使用を報告する",
    "report_info": "ユーザーによる不正使用を報告する機能。",
    "profile": "プロフィール",
    "profile_info": "パーソナライズされたユーザープロファイル。",
    "sso": "シングルサインオン（SSO）",
    "sso_info": "SelldoneSSOサービスを介した高速ログインの可能性。",
    "embed": "埋め込む",
    "embed_info": "投稿を埋め込んで共有する機能。",
    "reaction": "反応",
    "reaction_info": "ユーザーは、ストーリーについてどのように感じているかを記録できます。",
    "moderation": "節度",
    "moderation_info": "フォーラムへのアクセスを追加および管理します。"
  },
  "mission": {
    "title": "私たちは使命を帯びています",
    "message": "ビジネスを簡単に、達成可能に、そして世界中の誰もがアクセスできるようにする"
  },
  "logistic": {
    "title": "ロジスティクス",
    "logistic": "ロジスティクスと輸送",
    "logistic_desc": "在庫管理と配送方法",
    "private_transportation": "専用配送システム",
    "private_transportation_desc": "プライベート配送サービスを作成および管理します。",
    "transportation": "高度な配送方法を管理する",
    "transportation_desc": "国内および国際配送サービス",
    "process_center": "高度な処理センター",
    "process_center_desc": "使いやすい注文管理パネル",
    "return_requests": "返品管理",
    "return_requests_desc": "注文返品管理。"
  },
  "marketplace": "マーケットプレイスビルダー",
  "connect_os": {
    "subtitle": "ワンクリックでドロップシッピングのサプライヤーに接続できます。 Prinful や Import Woocomerce ストアなどの POD に無料で接続できます。"
  }
};