export default {
  "title": "Belaş dest pê bikin, bi lez mezin bibin!",
  "sub_title": "Gihîştina bêsînor ji hemî taybetmendiyan re bêyî lêçûn! Tenê <b>2% ji firotanê</b> , tenê piştî kirîna serketî. Gelek firotana we heye û hûn dixwazin xercê kêm bikin?",
  "show_detail_list": "Lîsteya hûrguliyan nîşan bide",
  "plan_free_detail": "<b class='text-capitalize'>Pergalek xebitandinê ji bo karsaziyên ku zû mezin dibin</b> | Karsaziya xwe bi plansaziya meya belaş dest pê bikin. Her tiştê ku hûn hewce ne ku hûn malpera xweya e-commerce dest pê bikin û bidin destpêkirin li vir amade ye. Selldone hemî nermalava, amûr û çareseriya mêvandariya cloudê bi plansaziya abonetiya belaş peyda dike. Selldone di heman demê de hemî nûvekirinên nermalavê û ramanên ewlehiyê digire. Ji ber vê yekê hûn dikarin hemî hewildanên xwe li ser firotanê bikin û ji pirsgirêk û lêçûnên teknîkî netirsin.",
  "pay_monthly": "Bi mehane bidin",
  "pay_yearly": "Salê bidin",
  "pay_yearly_off": "30% off",
  "transparency_title": "Zelalbûna di xizmetan de",
  "monthly_cost": "Bihayê mehane",
  "suggested_plan": "Plana pêşniyar kirin",
  "monthly_sell": "firotana mehane",
  "saving_amount": "Saving mehane",
  "saving_tips": "Bi kirîna plansaziya pêşniyarkirî hûn ê vê mîqdarê mehane hilînin.",
  "have_all_features": "Hûn ê hemî taybetmendiyan hebin.",
  "currency": "USD",
  "want_free": "Belaş dixwazin?",
  "stack_price": "Di saniyeyekê de {amount} mîlyon nîşanekan li hev bixin",
  "gift": "Diyariya taybetî",
  "gift_info": "Vê diyariyê bi kirîna vê planê bistînin.",
  "toke_gift_ratio": "Wekheviya mûçeya dayîn",
  "unlimited": "Bêsînor",
  "items_unit": "x",
  "delivery_person_unit": "Couriers",
  "soon": "Hema têm",
  "domains": "Domên Custom",
  "staff": "Admins",
  "community_builder": "avakerê civakê",
  "active_discount_codes": "Kodên discount Active",
  "active_coupons": "Coupons pêşketî Active",
  "active_offers": "Pêşniyarên pêşkeftî yên çalak",
  "active_gift_card_types": "bernameyên Giftcard",
  "active_campaigns": "Kampanyayên kirrûbirra çalak",
  "active_affiliates": "Parmendên çalak",
  "active_emails": "Kampanyayên kirrûbirra e-nameyê çalak",
  "active_transportation_persons": "Kuryeyên taybet",
  "active_importing_que": "Hilberîna hilberên hevdemî herî zêde",
  "active_reselling": "Reselling; Sell tiştên wholesale",
  "max_file_size": "Mezinahiya pelê ya herî zêde ya firotanê; Li gorî herêma we Euro / DY / ...",
  "active_capacity": "Cihê dîskê belaş",
  "active_drop_shipping": "Firotina firotanê ya firotanê (Pêdivî ye verastkirin)",
  "common_features": "Di hemî plansaziyên {lîsansê de cih digire",
  "unlimited_storage": "hilanînê bêsînor",
  "priority_support": "Piştgiriya pêşîn",
  "support_247": "24/7 piştgirî",
  "read_more": "Di derbarê taybetmendiyan de bêtir bixwînin ...",
  "partners_upgrade_suggestion_message": "Li ser {name} peymana we ya herî baş tune! Heke hûn ji sînoran hez nakin, em bi tundî pêşniyar dikin ku hûn wê di asta herî bilind de nûve bikin.",
  "partners_upgrade_suggestion_action": "Plana xwe li ser {name} niha nûve bikin",
  "free": {
    "title": "Şexsî",
    "info": "Ji bo kesên ku nû dest pê dikin",
    "cost": "Belaş",
    "fee_percent": 2,
    "items": [
      "berhemên bêsînor",
      "1 GB hilanînê",
      "Bandfirehiya bêsînor",
      "Hemî taybetmendî û amûrên profesyonel tê de hene",
      "Afirînerê Rûpelê Zevî bikişîne & Davêje",
      "Taybetmendiya tevahî CMS & blog",
      "3 Kodên dakêşanê yên çalak",
      "3 kuponên pêşkeftî yên çalak",
      "3 Pêşniyarên pêşkeftî yên çalak",
      "1 bernameyên Giftcard",
      "2 Kampanyayên kirrûbirra çalak",
      "2 Bernameyên hevkariyê yên çalak",
      "2 Kampanyayên kirrûbirra e-nameyê çalak",
      "2 derhênerên taybet",
      "Hemû xizmetên barkirinê",
      "1 Admin",
      "Avakerê civatê (Bingehîn)"
    ]
  },
  "startup": {
    "title": "Damezirandin",
    "info": "Ji bo Karsaziyên Piçûk Tenê Dest pê dikin",
    "fee_percent": 1.5,
    "items": [
      "Hemî taybetmendiyên belaş tê de hene",
      "10 GB hilanînê",
      "Mişterî têketina SMS",
      "Yekbûna 3D / AR",
      "10 Kodên dakêşanê yên çalak",
      "10 kuponên pêşkeftî yên çalak",
      "10 Pêşniyarên pêşkeftî yên çalak",
      "10 bernameyên Giftcard",
      "10 Kampanyayên kirrûbirra çalak",
      "10 Bernameyên hevkariyê yên çalak",
      "10 Kampanyayên kirrûbirra e-nameyê çalak",
      "10 derhênerên taybet",
      "Piştgiriya normal",
      "1 Domain",
      "5 Admins",
      "Avakerê civatê (Bingehîn)"
    ]
  },
  "company": {
    "title": "Şîrket",
    "info": "Karsaziyên Herêmî yên Piçûk û Navîn",
    "fee_percent": 1,
    "items": [
      "Hemî taybetmendiyên destpêkê tê de hene",
      "hilanînê bêsînor",
      "50 Kodên discount Active",
      "50 kuponên pêşkeftî yên çalak",
      "50 Pêşniyarên pêşkeftî yên Active",
      "50 bernameyên Giftcard",
      "50 kampanyayên kirrûbirra çalak",
      "100 bernameyên hevkariyê yên çalak",
      "100 kampanyayên kirrûbirra e-nameyê çalak",
      "50 derhênerên taybet",
      "Piştgiriya pêşîn",
      "5 Domên",
      "20 Admins",
      "Avakerê civakê (Normal)"
    ]
  },
  "enterprise": {
    "title": "Enterprise",
    "info": "Karsaziyên Pîvana Mezin",
    "fee_percent": 0.5,
    "items": [
      "Hemî taybetmendiyên pargîdaniyê tê de hene",
      "1K Kodên dakêşanê yên çalak",
      "Kuponên pêşkeftî yên 1K Active",
      "Pêşniyarên pêşkeftî yên 1K Active",
      "1K bernameyên Giftcard",
      "1K kampanyayên kirrûbirra çalak",
      "Bernameyên pêwendiya 1K Active",
      "1K Kampanyayên kirrûbirra e-nameyê çalak",
      "200 derhênerên taybet",
      "24/7 piştgirî",
      "∞ Domên",
      "∞ Admins",
      "Avakerê civakê (Pêşketî)",
      "Dropshipping Supplier",
      "Avakerê bazarê"
    ]
  },
  "features": {
    "title": "Features",
    "products": "Products",
    "usage": "Trafîka mehane",
    "custom_domain": "domaina xwerû lê zêde bikin",
    "invite_to_get_free": "Hevalek vexwendin û belaş bistînin",
    "ssl": "Pejirandina SSL",
    "support": "24/7 piştgirî",
    "staff": "Hejmara rêveberan",
    "staff_info": "Gihîştina endamên tîmê xwe bidin.",
    "person": "kes (kes)",
    "shop_name_length": "Dirêjahiya navê dikana hindiktirîn",
    "chars": "Şexsîyet",
    "page_builder": "Rûpelê xwe biafirînin",
    "page_builder_info": "Afirînerê Rûpelê Zevî bikişîne & Davêje",
    "pages": "Pages",
    "cms": "CMS & Blog",
    "cms_info": "Pergala Rêvebiriya Naveroka Pîşeyî û Edîtor ji bo Post û Berhemên Blogê.",
    "tax": "Hesabkirina bacê",
    "tax_info": "Hesabkirina baca otomatîkî ya li ser bingeha cîhê xerîdar, firotana B2B / B2C, û qabiliyeta qaîdeyên bacê ji bo welat û dewletan vedihewîne.",
    "tax_profiles": "Profîlên bacê - Profesyonel",
    "tax_profiles_info": "Hûn dikarin bi afirandina profîlên bacê rêzikên baca firotanê yên taybetî ji bo hilberan saz bikin.",
    "extra_tax_profiles": "Extra {count} profîl.",
    "tax_profile_fee": "0.0% heqê (karûbarê bi tevahî belaş)",
    "tax_pro": "Pro."
  },
  "gateways": {
    "title": "Portal Payment",
    "sub_title": "Portên nû dê di demek nêzîk de werin zêdekirin.",
    "gateways": "Gateways",
    "currencies": "Currencies",
    "currencies_info": "Dê di demek nêzîk de pereyên nû werin zêdekirin.",
    "currencies_encrypted": "Koda diravê",
    "currencies_encrypted_info": "Pereyên li ser platforma blokê",
    "online_pay_wage": "Xerca portê ya serhêl",
    "online_pay_wage_info": "Ev mîqdar dê ji hesabê weya barkirinê ya li Selldone were derxistin.",
    "cod_wage": "Xercên Tezmînata COD",
    "cod_wage_info": "Ev mîqdar dê ji hesabê heqê we were derxistin",
    "file_wage": "Heqê firotina pelê",
    "file_wage_info": "Komîsyona firotana pelê ya ku piştî firotek serketî li hesabê we tê veqetandin (Li ser hilanîna cloudê ya SSD-ê ya bi lez û bez tê firoştin)."
  },
  "apps": {
    "title": "App Store / Malperê",
    "pwa": "Pêşveçûn App Web",
    "android": "Android",
    "android_info": "App Phone and Tablet Android",
    "ios": "iOS (di nêzîk de)",
    "ios_info": "App Apple Phone & Tablet"
  },
  "custom_domain": {
    "title": "domain Custom",
    "sub_title": "Dikana xwe li ser domaina xwe hebe.",
    "domains_count": "Hejmara domên dikanê",
    "dns": "Cloud DNS",
    "cdn": "Cloud CDN",
    "cdn_info": "Tora Ravekirina Naveroka Cloud"
  },
  "host": {
    "title": "Mêvandar / Pêşkêşkara Cloud Belaş",
    "ssl": "Sertîfîkaya SSL",
    "storage": "Embarkirinî",
    "usage": "Trafîka mehane",
    "setup": "Sazkirina belaş",
    "technical_support": "piştgiriya teknîkî",
    "file_sell": "Pargîdaniya firotanê ya pelê",
    "file_sell_info": "Dîska hilanîna ewr a belaş ji bo firotina pelan (Super bilez)",
    "file_size": "Mezinahiya herî zêde ya her pelê",
    "file_size_info": "Mezinahiya herî zêde ya her pelê ji bo firotanê (hûn dikarin ji bo her hilberek bêtir ji yek pelê bar bikin)"
  },
  "products": {
    "title": "Products"
  },
  "seo": {
    "title": "SEO",
    "meta": "Meta tags",
    "meta_info": "Meta tagên bi tevahî pêşkeftî bixweber biafirînin",
    "jsonld": "JSON-LD",
    "jsonld_info": "Daneyên Structured",
    "amp": "AMP",
    "amp_info": "Rûpelên mobîl ên bilezkirî",
    "compress": "Compression Wêne",
    "compress_info": "jpg, png, svg, wpng, ...",
    "boost": "Speed Accelerator",
    "boost_info": "Ji bo motorên lêgerînê nexşerê barkirina rûpelê",
    "sitemap": "Sitemap",
    "sitemap_info": "Nexşeya Malperê ya Motora Lêgerînê"
  },
  "other": {
    "title": "Taybetmendiyên din",
    "plugins": "Pêvek & Serlêdan",
    "plugins_info": "Gihîştina Pêvekên Firotgeha Selldone",
    "customer_service": "Balkeş bûn",
    "customer_service_info": "Pirsên Pir Pir Dipirsin, Forma Têkiliya Xerîdar, Rêvebiriya Vegerê ...",
    "export": "berhemên Export",
    "export_info": "Pelên derketinê yên hemî hilberan bi hemî agahdarî û naverokê bistînin. Bi vê taybetmendiyê, hûn ê databasek standard a hilberên xwe yên negirêdayî bin.",
    "import": "Hilberên Hilber Bi Kirin",
    "import_info": "Karûbarê pêşkeftî û otomatîkî Selldone ji we re dibe alîkar ku hûn hilberên xwe bi wêneyan 100% bixweber bar bikin bêyî ku hûn lêçûnek ji karûbarek din a dikan-çêker an databasa xweya negirêdayî bidin.",
    "Simultaneous": "Yekwext"
  },
  "logistic": {
    "title": "Lojîstîk",
    "logistic": "Lojîstîk & Veguhastin",
    "logistic_desc": "Rêvebiriya envanter û rêbazên barkirinê",
    "private_transportation": "Pergala barkirina taybet",
    "private_transportation_desc": "Karûbarek barkirina taybet biafirînin û rêvebirin.",
    "transportation": "Rêbazên sewqiyata pêşkeftî birêve bibin",
    "transportation_desc": "Karûbarên barkirina herêmî û navneteweyî",
    "process_center": "Navenda Pêvajoya Pêşkeftî",
    "process_center_desc": "Panela rêveberiya fermanan-karanîna hêsan",
    "return_requests": "Rêveberiya Vegerê",
    "return_requests_desc": "Order management vegere."
  },
  "marketing": {
    "title": "Bazirganî & Firotin",
    "campaign": "Kampanyayek çêbikin û rêvebirin",
    "affiliate_marketing": "marketing Affiliate",
    "affiliate_marketing_desc": "Planên tevlêbûna firotanê biafirînin û rêvebirin",
    "email_marketing": "Panela Kirrûbirra E-nameyê",
    "email_marketing_desc": "Sêwirandin û şandina e-nameyên armanckirî ji temaşevanan re bi fîlter û bertek",
    "funnel": "Parzûna Bikarhêner Pêşketî",
    "funnel_desc": "Bikarhênerên li gorî zayend, dîroka kirînê, têketina paşîn, hwd.",
    "ab_test": "testa A/B",
    "user_reaction": "Analîza Rûpelê Zevî",
    "user_reaction_desc": "Beşên dakêşandî û klîkkirî yên rûpelên dakêşanê wekî nexşeyek germî û diagram bibînin"
  },
  "customers": {
    "title": "Mişterî & Teşwîq",
    "club": "Client Club",
    "discount_code": "Code Discount",
    "discount_code_info": "Kodên dakêşanê yên bêsînor biafirînin.",
    "coupon": "Coupon / Voucher",
    "coupon_info": "Ji xerîdarên xwe nirxek sabît, ji sedî, an dakêşana barkirinê pêşkêşî bikin.",
    "gift_card": "Karta diyariyê",
    "gift_card_info": "Karta heqê bêsînor çêbikin.",
    "offer": "Pêşnîyar",
    "offer_desc": "Vê hilberê bikirin, wê belaş bistînin (an jî bi dakêşanê)",
    "game": "Gamification",
    "game_desc": "Lîstikek bi xelatan dîzayn bikin"
  },
  "bots": {
    "title": "Bot, Torên Civakî, û Kanalên Firotanê",
    "telegram": "Robotê firotanê Telegram",
    "telegram_info": "Dikana xweya Telegramê belaş ava bikin",
    "instagram": "Instagram",
    "instagram_info": "Dikana xwe bi Instagram ve girêdin.",
    "facebook": "Facebook",
    "facebook_info": "Navnîşa hilberên taybetmendiyên tevahî hilberîn û hevdengkirina otomatîkî.",
    "avocado": "Karûbarê Firotanê ya Medya Civakî ya Avocado",
    "avocado_info": "Bi vê karûbarê hûn ê bikaribin bêyî ku hilberek zêde bikin û bi formek li ser torên civakî fermanan ji xerîdaran bistînin.",
    "hyper": "Order Hyper Quick",
    "hyper_info": "Di fûar, mîhrîcan, esnafan de û li her dera ku hûn dixwazin hin hilberan bifiroşin hejmareke mezin ji xerîdar."
  },
  "assistance": {
    "title": "Notifications",
    "notifications": "Kanalên ragihandinê",
    "email": "Email",
    "email_info": "Ji xerîdar û karmendên firotgehê re e-nameyê bişînin.",
    "sms": "SMS",
    "sms_info": "Ji xerîdar û karmendên dikanê re SMS bişînin.",
    "report": "Rapora Smart",
    "report_info": "Raporên heftane û salane yên periyodîk ên qelsiyên firotgehê, bikarhêner û firotanê, digel serişteyên ji bo baştirkirina performansa xwe û zêdekirina firotanê bişînin."
  },
  "automation": {
    "title": "Otomatîkî",
    "niomatic": "Niomatic",
    "niomatic_info": "Xweseriya pêvajoyê ya pêşkeftî li ser bingeha tercîhên blokên grafîkî",
    "autopilot": "Autopilot",
    "autopilot_info": "Bûyeran, dakêşan plansaz bikin, postên blogê, hilber û tiştên din biweşînin.",
    "webhook": "Webhook",
    "webhook_info": "API-ya sivik a ku parvekirina daneya yekalî ya ku ji hêla bûyeran ve hatî destpêkirin hêz dike."
  },
  "pos": {
    "title": "Soldone POS",
    "pos": "Store Cashier",
    "pos_info": "Pergala POS-a ku bi dikana weya serhêl ve girêdayî ye hemî pêvajoyên hilanîn, firotanê û piştgirîyê bi navgînek bikarhênerek bêhempa peyda dike.",
    "online_payment": "Tezmînata serhêl",
    "online_payment_info": "Di firotgeha weya laşî de ji bo xerîdarên we îmkana dravê serhêl.",
    "hardware": "Hardwares",
    "hardware_info": "Qabiliyeta girêdana bi skanerên barkodê, dîmenên rû-rû bi xerîdar, çapkerên etîketan û amûrên din re ji bo hêsankirina pêvajoya firotanê."
  },
  "dropshipping": {
    "title": "Dropshipping Hub",
    "reseller": "Refirotin",
    "reseller_info": "Hûn dikarin bi yek klîk hilberên firotanê li firotgeha xwe zêde bikin, hemî gavên bicîhkirin û barkirinê dê bixweber bêne kirin.",
    "wholesaler": "Wholesaler",
    "wholesaler_info": "Berhemên we dê ji hêla firoşkarên ku ji hêla we ve hatine pejirandin ve werin firotin û firotin."
  },
  "community": {
    "title": "Platforma Avaker a Civakê",
    "available": "Civaka Xweseriya Belaş",
    "available_info": "Kapasîteya afirandina civakek xwerû",
    "nomination": "Bi namzetiyê",
    "domain": "domain Custom",
    "domain_info": "Hûn ê forûmê li ser domaina xwe hebin.",
    "onboarding": "Onboarding",
    "onboarding_info": "Kapasîteya lê zêdekirina rêveber û moderatorek ji bo forumê.",
    "seo": "SEO",
    "seo_info": "Hûn ne hewce ne ku ji bo karûbarên SEO yên profesyonel pakêt an pêvekên zêde bikirin.",
    "analytic": "Analytics",
    "analytic_info": "Agahdarî li ser rûpelên civakê bi hêsanî têne xuyang kirin.",
    "post": "Koz",
    "post_info": "Sînorê posta mehane.",
    "comment": "Agahkişî",
    "comment_info": "Kapasîteya şandin û birêvebirina şîroveyan.",
    "voice": "Deng",
    "voice_info": "Kapasîteya tomarkirin û şandina dengê rasterast.",
    "video": "Video",
    "video_info": "Hêza şandina vîdyoyê (heta 8 MB)",
    "product": "Mal",
    "product_info": "Kapasîteya şandina hilberê rasterast bi nameyê.",
    "poll": "Gelpisî",
    "poll_info": "Qabiliyeta zêdekirina anketan li mijarekê.",
    "report": "Report abuse",
    "report_info": "Kapasîteya raporkirina binpêkirinê ji hêla bikarhêneran ve.",
    "profile": "tengal",
    "profile_info": "Profîla bikarhênerê ya kesane.",
    "sso": "Îmzekirina yekane (SSO)",
    "sso_info": "Di nav karûbarê Selldone SSO de îmkana têketina bilez.",
    "embed": "Embed",
    "embed_info": "Qabiliyeta binavkirin û parvekirina postan.",
    "reaction": "Bersivî",
    "reaction_info": "Bikarhêner dê karibin tomar bikin ka ew li ser çîrokek çawa hîs dikin.",
    "moderation": "Moderation",
    "moderation_info": "Gihîştina forumê zêde bikin û rêvebirin."
  },
  "mission": {
    "title": "Em di peywirê de ne",
    "message": "Karsaziyê ji her kesê li çaraliyê cîhanê re hêsan, gihîştî û gihîştî bikin"
  },
  "marketplace": "Avakerê bazarê",
  "connect_os": {
    "subtitle": "Bi yek klîk bi dabînkerên dropshipping ve girêdin. Hûn dikarin belaş bi POD-ê mîna firotgeha Prinful an Import Woocomerce ve girêbidin."
  }
};