export default {
  "title": "Sāciet bez maksas, strauji augiet!",
  "sub_title": "Neierobežota piekļuve visām funkcijām bez maksas! Tikai <b>2% no pārdošanas</b> , tikko pēc veiksmīgiem pirkumiem. Vai jums ir daudz pārdošanas un vēlaties samazināt maksas?",
  "show_detail_list": "Rādīt detalizētu sarakstu",
  "plan_free_detail": "<b class='text-capitalize'>Operētājsistēma strauji augošiem uzņēmumiem</b> | Sāciet savu biznesu, izmantojot mūsu bezmaksas plānu. Šeit ir gatavs viss, kas nepieciešams, lai sāktu un palaistu savu e-komercijas vietni. Selldone nodrošina visu programmatūru, rīkus un mākoņa mitināšanas risinājumu, izmantojot bezmaksas abonēšanas plānu. Selldone papildus rūpējas par visiem programmatūras atjauninājumiem un drošības apsvērumiem. Tātad jūs varat koncentrēt visus savus spēkus uz pārdošanu un neuztraukties par tehniskām problēmām un izmaksām.",
  "pay_monthly": "Maksājiet katru mēnesi",
  "pay_yearly": "Maksājiet katru gadu",
  "pay_yearly_off": "30% atlaide",
  "transparency_title": "Pārredzamība pakalpojumos",
  "monthly_cost": "Mēneša cena",
  "suggested_plan": "Ieteiktais plāns",
  "monthly_sell": "Ikmēneša izpārdošana",
  "saving_amount": "Ikmēneša ietaupījumi",
  "saving_tips": "Iegādājoties piedāvāto plānu, jūs ietaupīsiet šo summu katru mēnesi.",
  "have_all_features": "Jums būs visas funkcijas.",
  "currency": "USD",
  "want_free": "Vēlaties Bezmaksas?",
  "stack_price": "Saglabājiet {amount} miljonus marķieru sekundē",
  "gift": "Īpaša dāvana",
  "gift_info": "Iegūstiet šo dāvanu, iegādājoties šo plānu.",
  "toke_gift_ratio": "Līdzvērtīga samaksātajai summai",
  "unlimited": "Neierobežots",
  "items_unit": "x",
  "delivery_person_unit": "Kurjeri",
  "soon": "Drīzumā",
  "domains": "Pielāgoti domēni",
  "staff": "Admini",
  "community_builder": "Kopienas veidotājs",
  "active_discount_codes": "Aktīvie atlaižu kodi",
  "active_coupons": "Aktīvi uzlaboti kuponi",
  "active_offers": "Aktīvi uzlaboti piedāvājumi",
  "active_gift_card_types": "Dāvanu karšu programmas",
  "active_campaigns": "Aktīvās mārketinga kampaņas",
  "active_affiliates": "Aktīvās filiāles",
  "active_emails": "Aktīvās e-pasta mārketinga kampaņas",
  "active_transportation_persons": "Privātie kurjeri",
  "active_importing_que": "Maksimālais vienlaicīga produktu imports",
  "active_reselling": "Tālākpārdošana; Pārdod vairumtirgotāja preces",
  "max_file_size": "Maksimālais pārdodamā faila lielums; Atkarībā no jūsu reģiona eiro/ASV/...",
  "active_capacity": "Brīva vieta diskā",
  "active_drop_shipping": "Vairumtirdzniecības piegāde (nepieciešama pārbaude)",
  "common_features": "Iekļauts visos {license} plānos",
  "unlimited_storage": "Neierobežota krātuve",
  "priority_support": "Prioritārais atbalsts",
  "support_247": "24/7 atbalsts",
  "read_more": "Lasiet vairāk par funkcijām...",
  "partners_upgrade_suggestion_message": "Jums nav labākā iespējamā piedāvājuma vietnē {name}! Mēs ļoti iesakām to jaunināt uz augstāko līmeni, ja jums nepatīk ierobežojumi.",
  "partners_upgrade_suggestion_action": "Jauniniet savu plānu vietnē {name} tūlīt",
  "free": {
    "title": "Personīga",
    "info": "Cilvēkiem, kas tikko sākuši darbu",
    "cost": "Bezmaksas",
    "fee_percent": 2,
    "items": [
      "Neierobežots produktu daudzums",
      "1 GB krātuve",
      "Neierobežots joslas platums",
      "Iekļautas visas profesionālās funkcijas un rīki",
      "Vilkšanas un nomešanas galvenās lapas veidotājs",
      "Pilnas funkcijas CMS un emuāri",
      "3 Aktīvie atlaižu kodi",
      "3 aktīvi papildu kuponi",
      "3 aktīvi papildu piedāvājumi",
      "1 Dāvanu karšu programmas",
      "2 Aktīvās mārketinga kampaņas",
      "2 aktīvas saistītās programmas",
      "2 Aktīvās e-pasta mārketinga kampaņas",
      "2 privātie kurjeri",
      "Visi nosūtīšanas pakalpojumi",
      "1 Administrators",
      "Kopienas veidotājs (pamata)"
    ]
  },
  "startup": {
    "title": "Uzsākt",
    "info": "Mazajiem uzņēmumiem, kas tikko sāk darboties",
    "fee_percent": 1.5,
    "items": [
      "Iekļautas visas bezmaksas funkcijas",
      "10 GB krātuve",
      "Klientu SMS pieteikšanās",
      "3D / AR integrācija",
      "10 aktīvi atlaižu kodi",
      "10 aktīvi papildu kuponi",
      "10 aktīvi uzlaboti piedāvājumi",
      "10 dāvanu karšu programmas",
      "10 aktīvās mārketinga kampaņas",
      "10 aktīvās saistītās programmas",
      "10 aktīvas e-pasta mārketinga kampaņas",
      "10 privātie kurjeri",
      "Normāls atbalsts",
      "1 domēns",
      "5 administratori",
      "Kopienas veidotājs (pamata)"
    ]
  },
  "company": {
    "title": "Uzņēmums",
    "info": "Mazie un vidējie vietējie uzņēmumi",
    "fee_percent": 1,
    "items": [
      "Iekļautas visas startēšanas funkcijas",
      "Neierobežota krātuve",
      "50 aktīvie atlaižu kodi",
      "50 aktīvi papildu kuponi",
      "50 aktīvi uzlaboti piedāvājumi",
      "50 dāvanu karšu programmas",
      "50 aktīvās mārketinga kampaņas",
      "100 aktīvas saistītās programmas",
      "100 aktīvas e-pasta mārketinga kampaņas",
      "50 privātie kurjeri",
      "Prioritārais atbalsts",
      "5 domēni",
      "20 administratori",
      "Kopienas veidotājs (parasts)"
    ]
  },
  "enterprise": {
    "title": "Uzņēmums",
    "info": "Liela mēroga uzņēmumi",
    "fee_percent": 0.5,
    "items": [
      "Iekļautas visas uzņēmuma funkcijas",
      "1K aktīvi atlaižu kodi",
      "1 000 aktīvo papildu kuponu",
      "1K aktīvi uzlabotie piedāvājumi",
      "1K dāvanu karšu programmas",
      "1K aktīvās mārketinga kampaņas",
      "1K aktīvās saistītās programmas",
      "1K aktīvas e-pasta mārketinga kampaņas",
      "200 privātie kurjeri",
      "24/7 atbalsts",
      "∞ Domēni",
      "∞ Administratori",
      "Kopienas veidotājs (uzlabots)",
      "Dropshipping piegādātājs",
      "Tirgus laukuma veidotājs"
    ]
  },
  "features": {
    "title": "Iespējas",
    "products": "Produkti",
    "usage": "Ikmēneša satiksme",
    "custom_domain": "Pievienojiet pielāgotu domēnu",
    "invite_to_get_free": "Uzaiciniet draugu un saņemiet to bez maksas",
    "ssl": "SSL apstiprinājums",
    "support": "24/7 atbalsts",
    "staff": "Adminu skaits",
    "staff_info": "Piešķiriet piekļuvi saviem komandas locekļiem.",
    "person": "persona(s)",
    "shop_name_length": "Minimālais veikala nosaukuma garums",
    "chars": "Raksturs",
    "page_builder": "Izveidojiet savu lapu",
    "page_builder_info": "Vilkšanas un nomešanas galvenās lapas veidotājs",
    "pages": "Lapas",
    "cms": "CMS un emuārs",
    "cms_info": "Profesionāla satura pārvaldības un redaktora sistēma emuāru ziņām un produktiem.",
    "tax": "Nodokļa aprēķins",
    "tax_info": "Automātisks nodokļu aprēķins, pamatojoties uz klienta atrašanās vietu, B2B/B2C pārdošanu un ignorēt nodokļu noteikumu iespējas valstīm un štatiem.",
    "tax_profiles": "Nodokļu profili - profesionāli",
    "tax_profiles_info": "Varat iestatīt īpašus tirdzniecības nodokļa noteikumus produktiem, izveidojot nodokļu profilus.",
    "extra_tax_profiles": "Papildu {count} profili.",
    "tax_profile_fee": "0,0% maksa (pilnīgi bezmaksas pakalpojums)",
    "tax_pro": "Pro."
  },
  "gateways": {
    "title": "Maksājumu portāls",
    "sub_title": "Drīzumā tiks pievienoti jauni porti.",
    "gateways": "Vārti",
    "currencies": "Valūtas",
    "currencies_info": "Drīzumā tiks pievienotas jaunas valūtas.",
    "currencies_encrypted": "Valūtas kods",
    "currencies_encrypted_info": "Valūtas blokķēdes platformā",
    "online_pay_wage": "Tiešsaistes ostas maksa",
    "online_pay_wage_info": "Šī summa tiks atskaitīta no jūsu papildināšanas konta Selldone.",
    "cod_wage": "COD maksājumu maksas",
    "cod_wage_info": "Šī summa tiks atskaitīta no jūsu maksas konta",
    "file_wage": "Failu pārdošanas maksa",
    "file_wage_info": "Failu pārdošanas komisija, kas tiek ieskaitīta jūsu kontā pēc veiksmīgas pārdošanas (hosted onseldone ātrgaitas SSD mākoņkrātuvē)."
  },
  "apps": {
    "title": "Veikala/vietnes lietotne",
    "pwa": "Uzlabotā tīmekļa lietotne",
    "android": "Android",
    "android_info": "Android tālruņu un planšetdatoru lietotne",
    "ios": "iOS (drīzumā)",
    "ios_info": "Apple tālruņu un planšetdatoru lietotne"
  },
  "custom_domain": {
    "title": "Pielāgots domēns",
    "sub_title": "Izveidojiet savu veikalu savā domēnā.",
    "domains_count": "Veikalu domēnu skaits",
    "dns": "Mākoņa DNS",
    "cdn": "Mākoņu CDN",
    "cdn_info": "Mākoņa satura skaidrošanas tīkls"
  },
  "host": {
    "title": "Bezmaksas mākoņa resursdators/serveris",
    "ssl": "SSL sertifikācija",
    "storage": "Uzglabāšana",
    "usage": "Ikmēneša satiksme",
    "setup": "Bezmaksas iestatīšana",
    "technical_support": "tehniskā palīdzība",
    "file_sell": "Failu pārdošanas krātuve",
    "file_sell_info": "Bezmaksas mākoņa krātuves disks failu pārdošanai (īpaši ātrs)",
    "file_size": "Katra faila maksimālais lielums",
    "file_size_info": "Katra pārdošanai paredzētā faila maksimālais lielums (katram produktam varat augšupielādēt vairāk nekā vienu failu)"
  },
  "products": {
    "title": "Produkti"
  },
  "seo": {
    "title": "SEO",
    "meta": "Meta tagi",
    "meta_info": "Automātiski izveidojiet pilnībā uzlabotus metatagus",
    "jsonld": "JSON-LD",
    "jsonld_info": "Strukturētie dati",
    "amp": "AMP",
    "amp_info": "Paātrinātās mobilās lapas",
    "compress": "Attēlu saspiešana",
    "compress_info": "jpg, png, svg, wpng, ...",
    "boost": "Ātruma paātrinātājs",
    "boost_info": "Lapu ielādes plānotājs meklētājprogrammām",
    "sitemap": "Vietnes karte",
    "sitemap_info": "Meklētājprogrammas vietnes karte"
  },
  "other": {
    "title": "Citas funkcijas",
    "plugins": "Papildinājumi un lietojumprogrammas",
    "plugins_info": "Piekļuve Selldone veikala papildinājumiem",
    "customer_service": "Klientu apkalpošana",
    "customer_service_info": "Bieži uzdotie jautājumi, klientu attiecību veidlapa, atgriešanas pārvaldība...",
    "export": "Eksportēt produktus",
    "export_info": "Saņemiet visu produktu izvadfailus ar visu informāciju un saturu. Izmantojot šo funkciju, bezsaistē būs pieejama standarta datu bāze ar saviem produktiem.",
    "import": "Importēt produktus vairumā",
    "import_info": "Selldone uzlabotais un automātiskais pakalpojums palīdz 100% automātiski augšupielādēt savus produktus ar attēliem, nemaksājot nekādas izmaksas no jebkura cita veikala veidotāja pakalpojuma vai jūsu bezsaistes datu bāzes.",
    "Simultaneous": "Vienlaicīgi"
  },
  "logistic": {
    "title": "Loģistika",
    "logistic": "Loģistika un transports",
    "logistic_desc": "Inventāra un nosūtīšanas metožu vadība",
    "private_transportation": "Privātā piegādes sistēma",
    "private_transportation_desc": "Izveidojiet un pārvaldiet privātu piegādes pakalpojumu.",
    "transportation": "Pārvaldiet uzlabotās piegādes metodes",
    "transportation_desc": "Vietējie un starptautiskie kuģniecības pakalpojumi",
    "process_center": "Papildu apstrādes centrs",
    "process_center_desc": "Viegli lietojams pasūtījumu pārvaldības panelis",
    "return_requests": "Atgriešanas vadība",
    "return_requests_desc": "Pasūtījumu atgriešanas vadība."
  },
  "marketing": {
    "title": "Mārketings un pārdošana",
    "campaign": "Izveidojiet un pārvaldiet kampaņu",
    "affiliate_marketing": "Filiāles mārketings",
    "affiliate_marketing_desc": "Izveidojiet un pārvaldiet pārdošanas iesaistes plānus",
    "email_marketing": "E-pasta mārketinga panelis",
    "email_marketing_desc": "Mērķtiecīgu e-pasta ziņojumu izstrāde un nosūtīšana auditorijām, izmantojot filtrus un atsauksmes",
    "funnel": "Uzlabots lietotāja filtrs",
    "funnel_desc": "Filtrējiet lietotājus pēc dzimuma, pirkumu vēstures, pēdējās pieteikšanās utt.",
    "ab_test": "A/B tests",
    "user_reaction": "Galvenās lapas analīze",
    "user_reaction_desc": "Skatiet galvenās lapas sadaļas, uz kurām ir noklikšķināts un uz kurām tika noklikšķināts, kā termisko karti un diagrammu"
  },
  "customers": {
    "title": "Klienti un stimuli",
    "club": "Klientu klubs",
    "discount_code": "Atlaides kods",
    "discount_code_info": "Izveidojiet neierobežotu atlaižu kodus.",
    "coupon": "Kupons / Kupons",
    "coupon_info": "Piedāvājiet saviem klientiem fiksētu vērtību, procentuālo daļu vai piegādes atlaidi.",
    "gift_card": "Dāvanu karte",
    "gift_card_info": "Izveidojiet neierobežotu maksājumu karti.",
    "offer": "Piedāvājums",
    "offer_desc": "Pērciet šo produktu, saņemiet to bez maksas (vai ar atlaidi)",
    "game": "Gamifikācija",
    "game_desc": "Izveidojiet spēli ar balvām"
  },
  "bots": {
    "title": "Boti, sociālie tīkli un pārdošanas kanāli",
    "telegram": "Telegram pārdošanas robots",
    "telegram_info": "Izveidojiet savu Telegram veikalu bez maksas",
    "instagram": "Instagram",
    "instagram_info": "Savienojiet savu veikalu ar Instagram.",
    "facebook": "Facebook",
    "facebook_info": "Automātiski ģenerē un sinhronizē visu funkciju produktu sarakstu.",
    "avocado": "Avokado sociālo mediju pārdošanas pakalpojums",
    "avocado_info": "Izmantojot šo pakalpojumu, jūs varēsiet saņemt pasūtījumus no klientiem, nepievienojot preci un izmantojot veidlapu sociālajos tīklos.",
    "hyper": "Hiperātrs pasūtījums",
    "hyper_info": "Pārdot simtiem produktu minūtē gadatirgos, festivālos, stendos un visur, kur vēlaties pārdot kādu produktu lielam skaitam klientu."
  },
  "assistance": {
    "title": "Paziņojumi",
    "notifications": "Paziņojumu kanāli",
    "email": "E-pasts",
    "email_info": "Sūtiet e-pastus klientiem un veikala darbiniekiem.",
    "sms": "SMS",
    "sms_info": "Sūtiet SMS klientiem un veikala darbiniekiem.",
    "report": "Gudrais ziņojums",
    "report_info": "Iesniedziet iknedēļas un gada periodiskus ziņojumus par veikalu trūkumiem, lietotājiem un pārdošanu, kā arī padomus, kā uzlabot veiktspēju un palielināt pārdošanas apjomu."
  },
  "automation": {
    "title": "Automatizācija",
    "niomatic": "Niomatic",
    "niomatic_info": "Uzlabota procesu automatizācija, kuras pamatā ir grafisko bloku preferences",
    "autopilot": "Autopilots",
    "autopilot_info": "Plānojiet pasākumus, atlaides, publicējiet emuāra ierakstus, produktus un citas lietas.",
    "webhook": "Web aizķere",
    "webhook_info": "Viegla API, kas nodrošina vienvirziena datu koplietošanu, ko aktivizē notikumi."
  },
  "pos": {
    "title": "Pārdots POS",
    "pos": "Veikala kasiere",
    "pos_info": "POS sistēma, kas savienota ar jūsu tiešsaistes veikalu, nodrošina visus noliktavas, pārdošanas un atbalsta procesus ar unikālu lietotāja interfeisu.",
    "online_payment": "Tiešsaistes maksājums",
    "online_payment_info": "Iespēja norēķināties tiešsaistē jūsu klientiem jūsu fiziskajā veikalā.",
    "hardware": "Aparatūra",
    "hardware_info": "Iespēja savienot ar svītrkoda skeneriem, uz klientu vērstiem displejiem, uzlīmju printeriem un citu aparatūru, lai vienkāršotu pārdošanas procesu."
  },
  "dropshipping": {
    "title": "Dropshipping centrs",
    "reseller": "Tālākpārdošana",
    "reseller_info": "Vairumtirgotāja produktus savam veikalam varat pievienot ar vienu klikšķi, visas izpildes un piegādes darbības tiks veiktas automātiski.",
    "wholesaler": "Vairumtirgotājs",
    "wholesaler_info": "Jūsu produktus tirgos un pārdos jūsu apstiprinātie tālākpārdevēji."
  },
  "community": {
    "title": "Kopienas veidotāju platforma",
    "available": "Bezmaksas pielāgota kopiena",
    "available_info": "Iespēja izveidot pielāgotu kopienu",
    "nomination": "Pēc nominācijas",
    "domain": "Pielāgots domēns",
    "domain_info": "Forums būs jūsu domēnā.",
    "onboarding": "Uzņemšana",
    "onboarding_info": "Iespēja forumam pievienot administratoru un moderatoru.",
    "seo": "SEO",
    "seo_info": "Jums nav jāiegādājas papildu pakotnes vai spraudņi profesionāliem SEO pakalpojumiem.",
    "analytic": "Analytics",
    "analytic_info": "Informācija ir viegli redzama kopienas lapās.",
    "post": "Post",
    "post_info": "Ikmēneša ziņu limits.",
    "comment": "komentēt",
    "comment_info": "Iespēja nosūtīt un pārvaldīt komentārus.",
    "voice": "Balss",
    "voice_info": "Iespēja ierakstīt un nosūtīt tiešo audio.",
    "video": "Video",
    "video_info": "Iespēja nosūtīt video (līdz 8 MB)",
    "product": "Produkts",
    "product_info": "Iespēja nosūtīt preci tieši pa pastu.",
    "poll": "Aptauja",
    "poll_info": "Iespēja pievienot aptaujas tēmai.",
    "report": "Ziņot par pārkāpumu",
    "report_info": "Iespēja ziņot par lietotāju ļaunprātīgu izmantošanu.",
    "profile": "profils",
    "profile_info": "Personalizēts lietotāja profils.",
    "sso": "Vienotā pierakstīšanās (SSO)",
    "sso_info": "Ātras pieteikšanās iespēja, izmantojot Selldone SSO pakalpojumu.",
    "embed": "Iegult",
    "embed_info": "Iespēja iegult un kopīgot ziņas.",
    "reaction": "Reakcija",
    "reaction_info": "Lietotāji varēs ierakstīt, kā viņi jūtas par stāstu.",
    "moderation": "Mērenība",
    "moderation_info": "Pievienojiet un pārvaldiet piekļuvi forumam."
  },
  "mission": {
    "title": "Mēs esam misijā, lai",
    "message": "Padariet uzņēmējdarbību vienkāršu, sasniedzamu un pieejamu ikvienam visā pasaulē"
  },
  "marketplace": "Tirgus laukuma veidotājs",
  "connect_os": {
    "subtitle": "Sazinieties ar dropshipping piegādātājiem ar vienu klikšķi. Varat bez maksas izveidot savienojumu ar POD, piemēram, Prinful vai Import Woocomerce veikalu."
  }
};