export default {
  "title": "Anza Bure, Ukue Haraka!",
  "sub_title": "Ufikiaji usio na kikomo wa huduma zote bila gharama! <b>2% tu ya mauzo</b> , baada ya ununuzi uliofanikiwa. Je! una mauzo mengi na unataka kupunguza ada?",
  "show_detail_list": "Onyesha orodha ya maelezo",
  "plan_free_detail": "<b class='text-capitalize'>Mfumo wa uendeshaji kwa biashara zinazokua kwa kasi</b> ╏ Anzisha biashara yako kwa mpango wetu wa bure. Kila kitu unachohitaji ili kuanza na kuzindua tovuti yako ya eCommerce iko tayari hapa. Selldone hutoa programu zote, zana, na suluhisho la mwenyeji wa wingu kwa mpango wa usajili bila malipo. Selldone pia hutunza masasisho yote ya programu na masuala ya usalama. Kwa hivyo unaweza kuzingatia juhudi zako zote kwenye uuzaji na usiwe na wasiwasi juu ya maswala ya kiufundi na gharama.",
  "pay_monthly": "Lipa kila mwezi",
  "pay_yearly": "Lipa kila mwaka",
  "pay_yearly_off": "Punguzo la 30%.",
  "transparency_title": "Uwazi katika huduma",
  "monthly_cost": "Bei ya kila mwezi",
  "suggested_plan": "Mpango uliopendekezwa",
  "monthly_sell": "Uuzaji wa kila mwezi",
  "saving_amount": "Kuokoa kila mwezi",
  "saving_tips": "Kwa kununua mpango uliopendekezwa utahifadhi kiasi hiki kila mwezi.",
  "have_all_features": "Utakuwa na sifa zote.",
  "currency": "USD",
  "want_free": "Unataka Bure?",
  "stack_price": "Randa tokeni milioni {amount} kwa sekunde",
  "gift": "Zawadi maalum",
  "gift_info": "Pata zawadi hii kwa kununua mpango huu.",
  "toke_gift_ratio": "Sawa na kiasi kilicholipwa",
  "unlimited": "Bila kikomo",
  "items_unit": "x",
  "delivery_person_unit": "Wasafirishaji",
  "soon": "Inakuja hivi karibuni",
  "domains": "Vikoa maalum",
  "staff": "Wasimamizi",
  "community_builder": "Mjenzi wa jumuiya",
  "active_discount_codes": "Nambari za punguzo zinazotumika",
  "active_coupons": "Kuponi za hali ya juu zinazotumika",
  "active_offers": "Ofa za hali ya juu zinazotumika",
  "active_gift_card_types": "Programu za kadi za zawadi",
  "active_campaigns": "Kampeni zinazotumika za uuzaji",
  "active_affiliates": "Washirika wanaofanya kazi",
  "active_emails": "Kampeni zinazotumika za uuzaji wa barua pepe",
  "active_transportation_persons": "Wajumbe wa kibinafsi",
  "active_importing_que": "Kiwango cha juu cha kuagiza bidhaa kwa wakati mmoja",
  "active_reselling": "Kuuza tena; Uza vitu vya jumla",
  "max_file_size": "Ukubwa wa juu wa faili wa kuuza; Kulingana na eneo lako Euro/US/...",
  "active_capacity": "Nafasi ya bure ya diski",
  "active_drop_shipping": "Usafirishaji wa jumla (Uthibitishaji Unahitajika)",
  "common_features": "Imejumuishwa katika mipango yote ya {license}",
  "unlimited_storage": "Hifadhi isiyo na kikomo",
  "priority_support": "Msaada wa kipaumbele",
  "support_247": "24/7 msaada",
  "read_more": "Soma zaidi kuhusu vipengele...",
  "partners_upgrade_suggestion_message": "Huna ofa bora zaidi kwenye {name}! Tunapendekeza sana kuisasisha hadi kiwango cha juu zaidi ikiwa hupendi vikomo.",
  "partners_upgrade_suggestion_action": "Boresha mpango wako kwenye {name} sasa",
  "free": {
    "title": "Binafsi",
    "info": "Kwa watu wanaoanza tu",
    "cost": "Bure",
    "fee_percent": 2,
    "items": [
      "Bidhaa zisizo na kikomo",
      "1GB ya hifadhi",
      "Bandwidth isiyo na kikomo",
      "Vipengele vyote vya kitaaluma na zana pamoja",
      "Buruta & Achia Kiunda Ukurasa wa Kutua",
      "Kipengele kamili cha CMS & blogu",
      "3 Nambari za punguzo zinazotumika",
      "3 Kuponi za hali ya juu zinazoendelea",
      "3 Ofa za hali ya juu zinazoendelea",
      "Programu 1 za kadi ya zawadi",
      "2 Kampeni hai za uuzaji",
      "2 Programu za washirika zinazotumika",
      "2 Kampeni zinazotumika za uuzaji wa barua pepe",
      "Wajumbe 2 wa kibinafsi",
      "Huduma zote za usafirishaji",
      "1 Msimamizi",
      "Mjenzi wa jumuiya (Msingi)"
    ]
  },
  "startup": {
    "title": "Anzisha",
    "info": "Kwa Biashara Ndogo Ndogo Zinazoanza",
    "fee_percent": 1.5,
    "items": [
      "Vipengele vyote vya bure vimejumuishwa",
      "10GB ya hifadhi",
      "Kuingia kwa SMS kwa wateja",
      "Muunganisho wa 3D / AR",
      "Nambari 10 za punguzo zinazotumika",
      "10 Kuponi za hali ya juu zinazotumika",
      "Ofa 10 za hali ya juu zinazoendelea",
      "Programu 10 za kadi ya zawadi",
      "Kampeni 10 za uuzaji zinazofanya kazi",
      "Programu 10 za washirika zinazotumika",
      "Kampeni 10 za uuzaji za barua pepe zinazotumika",
      "Wajumbe 10 wa kibinafsi",
      "Msaada wa kawaida",
      "1 Kikoa",
      "5 Admins",
      "Mjenzi wa jumuiya (Msingi)"
    ]
  },
  "company": {
    "title": "Kampuni",
    "info": "Biashara Ndogo na za Kati za Mitaa",
    "fee_percent": 1,
    "items": [
      "Vipengele vyote vya kuanza vimejumuishwa",
      "Hifadhi isiyo na kikomo",
      "Nambari 50 za punguzo zinazotumika",
      "50 Kuponi za hali ya juu zinazotumika",
      "Ofa 50 za hali ya juu zinazoendelea",
      "Programu 50 za Kadi za Kipawa",
      "Kampeni 50 za uuzaji zinazofanya kazi",
      "Programu 100 za washirika zinazotumika",
      "Kampeni 100 za uuzaji za barua pepe zinazotumika",
      "Wajumbe 50 wa kibinafsi",
      "Msaada wa kipaumbele",
      "5 Vikoa",
      "20 Admins",
      "Mjenzi wa Jumuiya (Kawaida)"
    ]
  },
  "enterprise": {
    "title": "Biashara",
    "info": "Biashara Kubwa",
    "fee_percent": 0.5,
    "items": [
      "Vipengele vyote vya kampuni vimejumuishwa",
      "Misimbo ya punguzo 1K inayotumika",
      "1K Kuponi za hali ya juu zinazotumika",
      "Ofa za hali ya juu za 1K",
      "Programu za 1K Giftcard",
      "1K Kampeni za uuzaji zinazotumika",
      "1K Programu za washirika zinazotumika",
      "1K Kampeni zinazotumika za uuzaji wa barua pepe",
      "Wajumbe 200 wa kibinafsi",
      "24/7 msaada",
      "∞ Vikoa",
      "∞ Wasimamizi",
      "Mjenzi wa Jumuiya (Advanced)",
      "Dropshipping Supplier",
      "Mjenzi wa soko"
    ]
  },
  "features": {
    "title": "Vipengele",
    "products": "Bidhaa",
    "usage": "Trafiki ya kila mwezi",
    "custom_domain": "Ongeza kikoa maalum",
    "invite_to_get_free": "Alika rafiki na uipate bila malipo",
    "ssl": "Uthibitishaji wa SSL",
    "support": "24/7 msaada",
    "staff": "Idadi ya wasimamizi",
    "staff_info": "Wape washiriki wa timu yako idhini ya kufikia.",
    "person": "mtu(watu)",
    "shop_name_length": "Urefu wa chini wa jina la duka",
    "chars": "Tabia",
    "page_builder": "Unda ukurasa wako mwenyewe",
    "page_builder_info": "Buruta & Achia Kiunda Ukurasa wa Kutua",
    "pages": "Kurasa",
    "cms": "CMS & Blogu",
    "cms_info": "Usimamizi wa Maudhui ya Kitaalamu na Mfumo wa Kuhariri kwa Machapisho na Bidhaa za Blogu.",
    "tax": "Hesabu ya ushuru",
    "tax_info": "Hesabu ya kodi ya kiotomatiki kulingana na eneo la mteja, mauzo ya B2B/B2C na kubatilisha uwezo wa sheria za kodi kwa nchi na majimbo.",
    "tax_profiles": "Wasifu wa ushuru - Mtaalamu",
    "tax_profiles_info": "Unaweza kuweka sheria maalum za ushuru wa mauzo kwa bidhaa kwa kuunda wasifu wa ushuru.",
    "extra_tax_profiles": "Wasifu wa ziada wa {count}.",
    "tax_profile_fee": "Ada ya 0.0% (huduma ya bure kabisa)",
    "tax_pro": "Pro."
  },
  "gateways": {
    "title": "Malipo Portal",
    "sub_title": "Bandari mpya zitaongezwa hivi karibuni.",
    "gateways": "Milango",
    "currencies": "Sarafu",
    "currencies_info": "Sarafu mpya zitaongezwa hivi karibuni.",
    "currencies_encrypted": "Msimbo wa Sarafu",
    "currencies_encrypted_info": "Sarafu kwenye jukwaa la blockchain",
    "online_pay_wage": "Ada ya bandari mtandaoni",
    "online_pay_wage_info": "Kiasi hiki kitakatwa kutoka kwa akaunti yako ya kuchaji tena katika Selldone.",
    "cod_wage": "Ada ya Malipo ya COD",
    "cod_wage_info": "Kiasi hiki kitakatwa kutoka kwa akaunti yako ya malipo",
    "file_wage": "Ada ya kuuza faili",
    "file_wage_info": "Tume ya uuzaji wa faili ambayo imewekwa kwenye akaunti yako baada ya mauzo kufanikiwa (Inapangishwa kwa hifadhi ya wingu ya SSD ya kasi ya juu)."
  },
  "apps": {
    "title": "Hifadhi / Programu ya Tovuti",
    "pwa": "Programu ya Juu ya Wavuti",
    "android": "Android",
    "android_info": "Programu ya Simu ya Android na Kompyuta Kibao",
    "ios": "iOS (inakuja hivi karibuni)",
    "ios_info": "Programu ya Simu ya Apple na Kompyuta Kibao"
  },
  "custom_domain": {
    "title": "Kikoa maalum",
    "sub_title": "Kuwa na duka lako kwenye kikoa chako.",
    "domains_count": "Idadi ya vikoa vya duka",
    "dns": "Cloud DNS",
    "cdn": "Cloud CDN",
    "cdn_info": "Mtandao wa Maelezo ya Maudhui ya Wingu"
  },
  "host": {
    "title": "Mpangishi wa Wingu / Seva ya Bure",
    "ssl": "Udhibitisho wa SSL",
    "storage": "Hifadhi",
    "usage": "Trafiki ya kila mwezi",
    "setup": "Mpangilio wa bure",
    "technical_support": "msaada wa kiufundi",
    "file_sell": "Hifadhi ya kuuza faili",
    "file_sell_info": "Diski ya bure ya kuhifadhi wingu ya kuuza faili (Haraka sana)",
    "file_size": "Upeo wa ukubwa wa kila faili",
    "file_size_info": "Upeo wa ukubwa wa kila faili kwa ajili ya kuuza (unaweza kupakia zaidi ya faili moja kwa kila bidhaa)"
  },
  "products": {
    "title": "Bidhaa"
  },
  "seo": {
    "title": "SEO",
    "meta": "Meta tagi",
    "meta_info": "Unda meta tagi za hali ya juu kiotomatiki",
    "jsonld": "JSON-LD",
    "jsonld_info": "Data Iliyoundwa",
    "amp": "AMP",
    "amp_info": "Kurasa za rununu zilizoharakishwa",
    "compress": "Mfinyazo wa Picha",
    "compress_info": "jpg, png, svg, wpng, ...",
    "boost": "Kiongeza kasi",
    "boost_info": "Kipanga upakiaji wa ukurasa kwa injini za utafutaji",
    "sitemap": "Ramani ya tovuti",
    "sitemap_info": "Tafuta ramani ya tovuti"
  },
  "other": {
    "title": "Sifa Nyingine",
    "plugins": "Viongezi & Maombi",
    "plugins_info": "Inafikia Viongezi vya Duka la Selldone",
    "customer_service": "Huduma kwa wateja",
    "customer_service_info": "Maswali Yanayoulizwa Mara Kwa Mara, Fomu ya Mahusiano ya Wateja, Usimamizi wa Urejeshaji ...",
    "export": "Hamisha bidhaa",
    "export_info": "Pokea faili za pato za bidhaa zote zilizo na habari na yaliyomo. Ukiwa na kipengele hiki, utakuwa na hifadhidata ya kawaida ya bidhaa zako nje ya mtandao.",
    "import": "Ingiza Bidhaa Kwa Wingi",
    "import_info": "Huduma ya kina na ya kiotomatiki ya Selldone hukusaidia kupakia bidhaa zako na picha 100% kiotomatiki bila kulazimika kulipa gharama yoyote kutoka kwa huduma nyingine yoyote ya wajenzi wa duka au hifadhidata yako ya nje ya mtandao.",
    "Simultaneous": "Sambamba"
  },
  "logistic": {
    "title": "Vifaa",
    "logistic": "Usafirishaji na Usafirishaji",
    "logistic_desc": "Usimamizi wa hesabu na njia za usafirishaji",
    "private_transportation": "Mfumo wa usafirishaji wa kibinafsi",
    "private_transportation_desc": "Unda na udhibiti huduma ya kibinafsi ya usafirishaji.",
    "transportation": "Dhibiti njia za juu za usafirishaji",
    "transportation_desc": "Huduma za meli za ndani na kimataifa",
    "process_center": "Kituo cha Uchakataji wa hali ya juu",
    "process_center_desc": "Jopo la usimamizi wa maagizo rahisi kutumia",
    "return_requests": "Usimamizi wa kurudi",
    "return_requests_desc": "Udhibiti wa kurejesha agizo."
  },
  "marketing": {
    "title": "Uuzaji na Uuzaji",
    "campaign": "Unda na udhibiti kampeni",
    "affiliate_marketing": "Affiliate masoko",
    "affiliate_marketing_desc": "Unda na udhibiti mipango ya ushirikiano wa mauzo",
    "email_marketing": "Jopo la Uuzaji wa Barua pepe",
    "email_marketing_desc": "Kubuni na kutuma barua pepe zinazolengwa kwa hadhira kwa kutumia vichungi na maoni",
    "funnel": "Kichujio cha Juu cha Mtumiaji",
    "funnel_desc": "Chuja watumiaji kulingana na jinsia, historia ya ununuzi, kuingia mara ya mwisho, n.k.",
    "ab_test": "Mtihani wa A / B",
    "user_reaction": "Uchambuzi wa Ukurasa wa Kutua",
    "user_reaction_desc": "Tazama sehemu zilizotua na kubofya za kurasa za kutua kama ramani ya joto na mchoro"
  },
  "customers": {
    "title": "Wateja & Motisha",
    "club": "Klabu ya Wateja",
    "discount_code": "Msimbo wa Punguzo",
    "discount_code_info": "Unda misimbo ya punguzo isiyo na kikomo.",
    "coupon": "Kuponi / Vocha",
    "coupon_info": "Wape wateja wako bei isiyobadilika, asilimia au punguzo la usafirishaji.",
    "gift_card": "Kadi ya Zawadi",
    "gift_card_info": "Tengeneza kadi ya malipo isiyo na kikomo.",
    "offer": "Toa",
    "offer_desc": "Nunua bidhaa hii, Pata hiyo bila malipo (au kwa punguzo)",
    "game": "Uboreshaji",
    "game_desc": "Tengeneza mchezo na zawadi"
  },
  "bots": {
    "title": "Boti, Mitandao ya Kijamii, na Njia za Uuzaji",
    "telegram": "Roboti ya mauzo ya telegraph",
    "telegram_info": "Jenga duka lako la Telegraph bila malipo",
    "instagram": "Instagram",
    "instagram_info": "Unganisha duka lako kwenye Instagram.",
    "facebook": "Facebook",
    "facebook_info": "Kuzalisha na kusawazisha kiotomatiki orodha ya bidhaa za vipengele kamili.",
    "avocado": "Huduma ya Uuzaji wa Mitandao ya Kijamii ya Parachichi",
    "avocado_info": "Kwa huduma hii, utaweza kupokea maagizo kutoka kwa wateja bila kuongeza bidhaa na kupitia fomu kwenye mitandao ya kijamii.",
    "hyper": "Agizo la haraka la Hyper",
    "hyper_info": "Kuuza mamia ya bidhaa kwa dakika katika maonyesho, sherehe, maduka na popote unapotaka kuuza baadhi ya bidhaa kwa idadi kubwa ya wateja."
  },
  "assistance": {
    "title": "Arifa",
    "notifications": "Vituo vya arifa",
    "email": "Barua pepe",
    "email_info": "Tuma barua pepe kwa wateja na wafanyikazi wa duka.",
    "sms": "SMS",
    "sms_info": "Tuma SMS kwa wateja na wafanyikazi wa duka.",
    "report": "Ripoti ya Smart",
    "report_info": "Wasilisha ripoti za mara kwa mara za kila wiki na kila mwaka za udhaifu wa duka, watumiaji na mauzo, pamoja na vidokezo vya kuboresha utendaji wako na kuongeza mauzo."
  },
  "automation": {
    "title": "Automation",
    "niomatic": "Niomatic",
    "niomatic_info": "Mchakato wa hali ya juu otomatiki kulingana na mapendeleo ya kizuizi cha picha",
    "autopilot": "Otomatiki",
    "autopilot_info": "Panga matukio, punguzo, chapisha machapisho ya blogu, bidhaa na mambo mengine.",
    "webhook": "Mtandao",
    "webhook_info": "API nyepesi inayowezesha ushiriki wa data wa njia moja unaosababishwa na matukio."
  },
  "pos": {
    "title": "Selldone POS",
    "pos": "Keshia ya Hifadhi",
    "pos_info": "Mfumo wa POS uliounganishwa kwenye duka lako la mtandaoni hukupa taratibu zote za kuhifadhi, mauzo na usaidizi na kiolesura cha kipekee cha mtumiaji.",
    "online_payment": "Malipo ya mtandaoni",
    "online_payment_info": "Uwezekano wa malipo ya mtandaoni kwa wateja wako katika duka lako halisi.",
    "hardware": "Vifaa",
    "hardware_info": "Uwezo wa kuunganisha kwenye vichanganuzi vya msimbo pau, skrini zinazowakabili wateja, vichapishaji lebo na maunzi mengine ili kurahisisha mchakato wa mauzo."
  },
  "dropshipping": {
    "title": "Kitovu cha Kudondosha",
    "reseller": "Kuuza tena",
    "reseller_info": "Unaweza kuongeza bidhaa za muuzaji wa jumla kwenye duka lako kwa mbofyo mmoja, utimilifu wote na hatua za usafirishaji zitafanywa kiotomatiki.",
    "wholesaler": "Mfanyabiashara wa jumla",
    "wholesaler_info": "Bidhaa zako zitauzwa na kuuzwa na wauzaji ambao umeidhinisha nawe."
  },
  "community": {
    "title": "Jukwaa la Wajenzi wa Jamii",
    "available": "Jumuiya Maalum ya Bure",
    "available_info": "Uwezo wa kuunda jumuiya maalum",
    "nomination": "Kwa kuteuliwa",
    "domain": "Kikoa maalum",
    "domain_info": "Utakuwa na jukwaa kwenye kikoa chako mwenyewe.",
    "onboarding": "Kupanda",
    "onboarding_info": "Uwezo wa kuongeza msimamizi na msimamizi kwa ajili ya jukwaa.",
    "seo": "SEO",
    "seo_info": "Huna haja ya kununua vifurushi vya ziada au programu-jalizi kwa huduma za kitaalamu za SEO.",
    "analytic": "Uchanganuzi",
    "analytic_info": "Habari inaonekana kwa urahisi kwenye kurasa za jumuiya.",
    "post": "Chapisha",
    "post_info": "Kikomo cha chapisho cha kila mwezi.",
    "comment": "Maoni",
    "comment_info": "Uwezo wa kutuma na kusimamia maoni.",
    "voice": "Sauti",
    "voice_info": "Uwezo wa kurekodi na kutuma sauti moja kwa moja.",
    "video": "Video",
    "video_info": "Uwezo wa kutuma video (hadi 8 MB)",
    "product": "Bidhaa",
    "product_info": "Uwezo wa kutuma bidhaa moja kwa moja kwa barua.",
    "poll": "Kura ya maoni",
    "poll_info": "Uwezo wa kuongeza kura kwenye mada.",
    "report": "Ripoti matumizi mabaya",
    "report_info": "Uwezo wa kuripoti matumizi mabaya ya watumiaji.",
    "profile": "wasifu",
    "profile_info": "Wasifu wa mtumiaji uliobinafsishwa.",
    "sso": "Kuingia kwa mtu mmoja (SSO)",
    "sso_info": "Uwezekano wa kuingia haraka kupitia huduma ya Selldone SSO.",
    "embed": "Pachika",
    "embed_info": "Uwezo wa kupachika na kushiriki machapisho.",
    "reaction": "Mwitikio",
    "reaction_info": "Watumiaji wataweza kurekodi jinsi wanavyohisi kuhusu hadithi.",
    "moderation": "Kiasi",
    "moderation_info": "Ongeza na udhibiti ufikiaji wa mijadala."
  },
  "mission": {
    "title": "Tuko kwenye dhamira ya",
    "message": "Fanya biashara iwe rahisi, iweze kufikiwa na kufikiwa na mtu yeyote duniani kote"
  },
  "marketplace": "Mjenzi wa soko",
  "connect_os": {
    "subtitle": "Unganisha kwa wauzaji wa kushuka kwa mbofyo mmoja. Unaweza kuunganisha kwenye POD kama vile Prinful au Import Woocomerce store bila malipo."
  }
};