export default {
  "title": "Bắt đầu miễn phí, phát triển nhanh chóng!",
  "sub_title": "Quyền truy cập không giới hạn vào tất cả các tính năng miễn phí! Chỉ <b>2%</b> khi mua hàng thành công. Bạn có nhiều doanh số và muốn giảm phí?",
  "show_detail_list": "Hiển thị danh sách chi tiết",
  "plan_free_detail": "<b class='text-capitalize'>Hệ điều hành dành cho các doanh nghiệp phát triển nhanh</b> ╏ Bắt đầu kinh doanh của bạn bằng gói miễn phí của chúng tôi. Mọi thứ bạn cần để bắt đầu và khởi chạy trang web Thương mại điện tử của mình đã sẵn sàng ở đây. Selldone cung cấp tất cả phần mềm, công cụ và giải pháp lưu trữ đám mây theo gói đăng ký miễn phí. Selldone cũng quan tâm đến tất cả các bản cập nhật phần mềm và các cân nhắc về bảo mật. Vì vậy, bạn có thể tập trung mọi nỗ lực của mình vào việc bán hàng và không phải lo lắng về các vấn đề kỹ thuật và chi phí.",
  "pay_monthly": "Trả hàng tháng",
  "pay_yearly": "Thanh toán hàng năm",
  "pay_yearly_off": "giảm giá 30",
  "transparency_title": "Tính minh bạch trong các dịch vụ",
  "monthly_cost": "Giá hàng tháng",
  "suggested_plan": "Kế hoạch đề xuất",
  "monthly_sell": "Tháng giảm giá",
  "saving_amount": "Tiết kiệm hàng tháng",
  "saving_tips": "Bằng cách mua gói được đề xuất, bạn sẽ tiết kiệm được số tiền này hàng tháng.",
  "have_all_features": "Bạn sẽ có tất cả các tính năng.",
  "currency": "USD",
  "want_free": "Muốn miễn phí?",
  "stack_price": "Xếp chồng {amount} triệu mã thông báo mỗi giây",
  "gift": "Món quà đặc biệt",
  "gift_info": "Nhận món quà này bằng cách mua gói này.",
  "toke_gift_ratio": "Tương đương với số tiền đã trả",
  "unlimited": "Vô hạn",
  "items_unit": "x",
  "delivery_person_unit": "Giao thông viên",
  "soon": "Sắp có",
  "domains": "Miền tùy chỉnh",
  "staff": "Quản trị viên",
  "community_builder": "Người xây dựng cộng đồng",
  "active_discount_codes": "Mã giảm giá đang hoạt động",
  "active_coupons": "Phiếu thưởng nâng cao đang hoạt động",
  "active_offers": "Ưu đãi nâng cao đang hoạt động",
  "active_gift_card_types": "Các chương trình thẻ quà tặng",
  "active_campaigns": "Các chiến dịch tiếp thị đang hoạt động",
  "active_affiliates": "Các chi nhánh đang hoạt động",
  "active_emails": "Các chiến dịch tiếp thị qua email đang hoạt động",
  "active_transportation_persons": "Giao thông viên tư nhân",
  "active_importing_que": "Nhập sản phẩm đồng thời tối đa",
  "active_reselling": "Bán lại; Bán các mặt hàng của người bán buôn",
  "max_file_size": "Kích thước tệp tối đa để bán; Tùy thuộc vào khu vực của bạn Euro / US / ...",
  "active_capacity": "Không gian trống của đĩa",
  "active_drop_shipping": "Bán buôn dropshipping (Cần xác minh)",
  "common_features": "Có trong tất cả các gói {license}",
  "unlimited_storage": "Bộ nhớ không giới hạn",
  "priority_support": "Hỗ trợ ưu tiên",
  "support_247": "Hỗ trợ 24/7",
  "read_more": "Đọc thêm về các tính năng ...",
  "partners_upgrade_suggestion_message": "Bạn không có thỏa thuận tốt nhất có thể về {name}! Chúng tôi thực sự khuyên bạn nên nâng cấp nó lên mức cao nhất nếu bạn không thích các giới hạn.",
  "partners_upgrade_suggestion_action": "Nâng cấp gói của bạn trên {name} ngay bây giờ",
  "free": {
    "title": "Riêng tư",
    "info": "Đối với những người mới bắt đầu",
    "cost": "Miễn phí",
    "fee_percent": 2,
    "items": [
      "Sản phẩm không giới hạn",
      "1GB bộ nhớ",
      "Băng thông không giới hạn",
      "Tất cả các tính năng chuyên nghiệp và công cụ bao gồm",
      "Kéo & Thả Trình tạo Trang Đích",
      "CMS và blog đầy đủ tính năng",
      "3 mã giảm giá đang hoạt động",
      "3 phiếu thưởng nâng cao đang hoạt động",
      "3 ưu đãi nâng cao đang hoạt động",
      "1 chương trình Giftcard",
      "2 Chiến dịch tiếp thị đang hoạt động",
      "2 chương trình liên kết đang hoạt động",
      "2 Chiến dịch tiếp thị qua email đang hoạt động",
      "2 giao thông viên tư nhân",
      "Tất cả các dịch vụ vận chuyển",
      "1 quản trị viên",
      "Người xây dựng cộng đồng (Cơ bản)"
    ]
  },
  "startup": {
    "title": "Khởi động",
    "info": "Dành cho các doanh nghiệp nhỏ mới bắt đầu",
    "fee_percent": 1.5,
    "items": [
      "Tất cả các tính năng miễn phí bao gồm",
      "Bộ nhớ 10GB",
      "Đăng nhập SMS của khách hàng",
      "Tích hợp 3D / AR",
      "10 mã giảm giá đang hoạt động",
      "10 phiếu thưởng nâng cao đang hoạt động",
      "10 ưu đãi nâng cao đang hoạt động",
      "10 chương trình Giftcard",
      "10 chiến dịch tiếp thị tích cực",
      "10 chương trình liên kết đang hoạt động",
      "10 chiến dịch tiếp thị qua email đang hoạt động",
      "10 giao thông viên tư nhân",
      "Hỗ trợ bình thường",
      "1 miền",
      "5 quản trị viên",
      "Người xây dựng cộng đồng (Cơ bản)"
    ]
  },
  "company": {
    "title": "Công ty",
    "info": "Doanh nghiệp địa phương quy mô vừa và nhỏ",
    "fee_percent": 1,
    "items": [
      "Tất cả các tính năng khởi động bao gồm",
      "Bộ nhớ không giới hạn",
      "50 mã giảm giá đang hoạt động",
      "50 phiếu thưởng nâng cao đang hoạt động",
      "50 ưu đãi nâng cao đang hoạt động",
      "50 chương trình Giftcard",
      "50 chiến dịch tiếp thị đang hoạt động",
      "100 chương trình liên kết đang hoạt động",
      "100 chiến dịch tiếp thị qua email đang hoạt động",
      "50 giao thông viên tư nhân",
      "Hỗ trợ ưu tiên",
      "5 miền",
      "20 quản trị viên",
      "Người xây dựng cộng đồng (Bình thường)"
    ]
  },
  "enterprise": {
    "title": "Doanh nghiệp",
    "info": "Doanh nghiệp quy mô lớn",
    "fee_percent": 0.5,
    "items": [
      "Tất cả các tính năng của công ty bao gồm",
      "1K mã giảm giá đang hoạt động",
      "1K phiếu thưởng nâng cao đang hoạt động",
      "Ưu đãi nâng cao 1K Active",
      "Chương trình 1K Giftcard",
      "1K chiến dịch tiếp thị đang hoạt động",
      "1K chương trình liên kết đang hoạt động",
      "1K chiến dịch tiếp thị qua email đang hoạt động",
      "200 giao thông viên tư nhân",
      "Hỗ trợ 24/7",
      "∞ Miền",
      "∞ Quản trị viên",
      "Xây dựng cộng đồng (Nâng cao)",
      "Nhà cung cấp Dropshipping",
      "Người xây dựng thị trường"
    ]
  },
  "features": {
    "title": "Đặc trưng",
    "products": "Các sản phẩm",
    "usage": "Lưu lượng truy cập hàng tháng",
    "custom_domain": "Thêm miền tùy chỉnh",
    "invite_to_get_free": "Mời bạn bè và nhận miễn phí",
    "ssl": "Xác nhận SSL",
    "support": "Hỗ trợ 24/7",
    "staff": "Số lượng quản trị viên",
    "staff_info": "Cấp quyền truy cập cho các thành viên trong nhóm của bạn.",
    "person": "người",
    "shop_name_length": "Độ dài tên cửa hàng tối thiểu",
    "chars": "Tính cách",
    "page_builder": "Tạo trang của riêng bạn",
    "page_builder_info": "Kéo & Thả Trình tạo Trang Đích",
    "pages": "Các trang",
    "cms": "CMS & Blog",
    "cms_info": "Hệ thống quản lý và biên tập nội dung chuyên nghiệp cho các bài đăng trên blog và sản phẩm.",
    "tax": "Tính thuế",
    "tax_info": "Tự động tính thuế dựa trên vị trí của khách hàng, doanh số B2B/B2C và khả năng ghi đè quy tắc thuế cho các quốc gia và tiểu bang.",
    "tax_profiles": "Hồ sơ thuế - Chuyên nghiệp",
    "tax_profiles_info": "Bạn có thể đặt quy tắc thuế bán hàng riêng cho sản phẩm bằng cách tạo hồ sơ thuế.",
    "extra_tax_profiles": "Hồ sơ {count} bổ sung.",
    "tax_profile_fee": "Phí 0,0% (dịch vụ hoàn toàn miễn phí)",
    "tax_pro": "Chuyên nghiệp."
  },
  "gateways": {
    "title": "Cổng thanh toán",
    "sub_title": "Các cổng mới sẽ sớm được thêm vào.",
    "gateways": "Cổng vào",
    "currencies": "Tiền tệ",
    "currencies_info": "Các loại tiền mới sẽ sớm được thêm vào.",
    "currencies_encrypted": "Mã tiền tệ",
    "currencies_encrypted_info": "Tiền tệ trên nền tảng blockchain",
    "online_pay_wage": "Phí cổng trực tuyến",
    "online_pay_wage_info": "Số tiền này sẽ được trừ vào tài khoản nạp tiền của bạn tại Selldone.",
    "cod_wage": "Phí thanh toán COD",
    "cod_wage_info": "Số tiền này sẽ được trừ vào tài khoản phí của bạn",
    "file_wage": "Phí bán hồ sơ",
    "file_wage_info": "Hoa hồng bán tệp được ghi có vào tài khoản của bạn sau khi bán thành công (Được lưu trữ trên bộ nhớ đám mây SSD tốc độ cao của selldone)."
  },
  "apps": {
    "title": "Ứng dụng Cửa hàng / Trang web",
    "pwa": "Ứng dụng web nâng cao",
    "android": "Android",
    "android_info": "Ứng dụng điện thoại và máy tính bảng Android",
    "ios": "iOS (sắp ra mắt)",
    "ios_info": "Ứng dụng điện thoại & máy tính bảng Apple"
  },
  "custom_domain": {
    "title": "Tên miền tùy chọn",
    "sub_title": "Có cửa hàng của bạn trên miền của riêng bạn.",
    "domains_count": "Số lượng miền cửa hàng",
    "dns": "DNS đám mây",
    "cdn": "Cloud CDN",
    "cdn_info": "Mạng giải thích nội dung đám mây"
  },
  "host": {
    "title": "Máy chủ / Máy chủ đám mây miễn phí",
    "ssl": "Chứng nhận SSL",
    "storage": "Kho",
    "usage": "Lưu lượng truy cập hàng tháng",
    "setup": "Thiết lập miễn phí",
    "technical_support": "hỗ trợ kỹ thuật",
    "file_sell": "Tệp bán bộ nhớ",
    "file_sell_info": "Đĩa lưu trữ đám mây miễn phí để bán tệp (Siêu nhanh)",
    "file_size": "Kích thước tối đa của mỗi tệp",
    "file_size_info": "Kích thước tối đa của mỗi tệp để bán (bạn có thể tải lên nhiều tệp cho mỗi sản phẩm)"
  },
  "products": {
    "title": "Các sản phẩm"
  },
  "seo": {
    "title": "SEO",
    "meta": "Thẻ meta",
    "meta_info": "Tự động tạo các thẻ meta nâng cao hoàn toàn",
    "jsonld": "JSON-LD",
    "jsonld_info": "Dữ liệu có cấu trúc",
    "amp": "AMP",
    "amp_info": "Trang di động được tăng tốc",
    "compress": "Nén hình ảnh",
    "compress_info": "jpg, png, svg, wpng, ...",
    "boost": "Bộ tăng tốc tốc độ",
    "boost_info": "Bộ lập lịch tải trang cho các công cụ tìm kiếm",
    "sitemap": "Sơ đồ trang web",
    "sitemap_info": "Sơ đồ trang web của Công cụ Tìm kiếm"
  },
  "other": {
    "title": "Các tính năng khác",
    "plugins": "Tiện ích bổ sung & Ứng dụng",
    "plugins_info": "Truy cập Tiện ích bổ sung của Selldone Store",
    "customer_service": "Dịch vụ khách hàng",
    "customer_service_info": "Câu hỏi thường gặp, Biểu mẫu quan hệ khách hàng, Quản lý trả hàng ...",
    "export": "Sản phẩm xuất khẩu",
    "export_info": "Nhận các tập tin đầu ra của tất cả các sản phẩm với tất cả các thông tin và nội dung. Với tính năng này, bạn sẽ có một cơ sở dữ liệu chuẩn về sản phẩm của mình ngoại tuyến.",
    "import": "Nhập sản phẩm với số lượng lớn",
    "import_info": "Dịch vụ nâng cao và tự động của Selldone giúp bạn tải lên các sản phẩm có hình ảnh một cách tự động 100% mà không phải trả bất kỳ chi phí nào từ bất kỳ dịch vụ xây dựng cửa hàng nào khác hoặc cơ sở dữ liệu ngoại tuyến của bạn.",
    "Simultaneous": "Đồng thời"
  },
  "logistic": {
    "title": "Logistics",
    "logistic": "Logistics & Vận tải",
    "logistic_desc": "Quản lý hàng tồn kho và phương thức vận chuyển",
    "private_transportation": "Hệ thống vận chuyển tư nhân",
    "private_transportation_desc": "Tạo và quản lý một dịch vụ vận chuyển tư nhân.",
    "transportation": "Quản lý các phương thức vận chuyển nâng cao",
    "transportation_desc": "Dịch vụ vận chuyển trong nước và quốc tế",
    "process_center": "Trung tâm xử lý nâng cao",
    "process_center_desc": "Bảng quản lý đơn đặt hàng dễ sử dụng",
    "return_requests": "Quản lý trở lại",
    "return_requests_desc": "Quản lý đơn hàng trả lại."
  },
  "marketing": {
    "title": "Tiếp thị & Bán hàng",
    "campaign": "Tạo và quản lý một chiến dịch",
    "affiliate_marketing": "Tiếp thị liên kết",
    "affiliate_marketing_desc": "Tạo và quản lý các kế hoạch tham gia bán hàng",
    "email_marketing": "Bảng điều khiển tiếp thị qua email",
    "email_marketing_desc": "Thiết kế và gửi email được nhắm mục tiêu đến khán giả bằng bộ lọc và phản hồi",
    "funnel": "Bộ lọc người dùng nâng cao",
    "funnel_desc": "Lọc người dùng theo giới tính, lịch sử mua hàng, lần đăng nhập gần đây nhất, v.v.",
    "ab_test": "Thử nghiệm A / B",
    "user_reaction": "Phân tích trang đích",
    "user_reaction_desc": "Xem các phần đã hạ cánh và được nhấp của trang đích dưới dạng bản đồ nhiệt và sơ đồ"
  },
  "customers": {
    "title": "Khách hàng & Khuyến khích",
    "club": "Câu lạc bộ khách hàng",
    "discount_code": "Mã giảm giá",
    "discount_code_info": "Tạo mã giảm giá không giới hạn.",
    "coupon": "Phiếu giảm giá / Phiếu mua hàng",
    "coupon_info": "Cung cấp cho khách hàng của bạn một giá trị cố định, tỷ lệ phần trăm hoặc chiết khấu giao hàng.",
    "gift_card": "Thẻ quà tặng",
    "gift_card_info": "Làm thẻ nạp không giới hạn.",
    "offer": "Phục vụ",
    "offer_desc": "Mua sản phẩm này, nhận miễn phí (hoặc giảm giá)",
    "game": "Gamification",
    "game_desc": "Thiết kế một trò chơi có giải thưởng"
  },
  "bots": {
    "title": "Bots, Mạng xã hội và Kênh bán hàng",
    "telegram": "Robot bán hàng Telegram",
    "telegram_info": "Xây dựng cửa hàng Telegram của riêng bạn miễn phí",
    "instagram": "Instagram",
    "instagram_info": "Kết nối cửa hàng của bạn với Instagram.",
    "facebook": "Facebook",
    "facebook_info": "Tự động tạo và đồng bộ hóa danh sách sản phẩm đầy đủ tính năng.",
    "avocado": "Dịch vụ bán hàng truyền thông xã hội của Avocado",
    "avocado_info": "Với dịch vụ này, bạn sẽ có thể nhận đơn đặt hàng từ khách hàng mà không cần thêm sản phẩm và thông qua biểu mẫu trên mạng xã hội.",
    "hyper": "Đặt hàng siêu nhanh",
    "hyper_info": "Để bán hàng trăm sản phẩm mỗi phút trong các hội chợ, lễ hội, gian hàng và bất cứ nơi nào bạn muốn bán một số sản phẩm cho một số lượng lớn khách hàng."
  },
  "assistance": {
    "title": "Thông báo",
    "notifications": "Các kênh thông báo",
    "email": "E-mail",
    "email_info": "Gửi email cho khách hàng và nhân viên cửa hàng.",
    "sms": "SMS",
    "sms_info": "Gửi SMS cho khách hàng và nhân viên cửa hàng.",
    "report": "Báo cáo thông minh",
    "report_info": "Gửi báo cáo định kỳ hàng tuần và hàng năm về điểm yếu của cửa hàng, người dùng và doanh số bán hàng, cùng với các mẹo để cải thiện hiệu suất và tăng doanh số bán hàng của bạn."
  },
  "automation": {
    "title": "Tự động hóa",
    "niomatic": "Niomatic",
    "niomatic_info": "Tự động hóa quy trình nâng cao dựa trên tùy chọn khối đồ họa",
    "autopilot": "Lái tự động",
    "autopilot_info": "Lên lịch sự kiện, giảm giá, xuất bản bài đăng trên blog, sản phẩm và những thứ khác.",
    "webhook": "Webhook",
    "webhook_info": "API nhẹ hỗ trợ chia sẻ dữ liệu một chiều được kích hoạt bởi các sự kiện."
  },
  "pos": {
    "title": "Selldone POS",
    "pos": "Thu ngân cửa hàng",
    "pos_info": "Hệ thống POS được kết nối với cửa hàng trực tuyến của bạn cung cấp cho bạn tất cả các quy trình lưu kho, bán hàng và hỗ trợ với giao diện người dùng độc đáo.",
    "online_payment": "Thanh toán trực tuyến",
    "online_payment_info": "Khả năng thanh toán trực tuyến cho khách hàng của bạn tại cửa hàng thực của bạn.",
    "hardware": "Phần cứng",
    "hardware_info": "Khả năng kết nối với máy quét mã vạch, màn hình hiển thị trực tiếp với khách hàng, máy in nhãn và phần cứng khác để đơn giản hóa quy trình bán hàng."
  },
  "dropshipping": {
    "title": "Trung tâm Dropshipping",
    "reseller": "Bán lại",
    "reseller_info": "Bạn có thể thêm các sản phẩm của nhà bán buôn vào cửa hàng của mình bằng một cú nhấp chuột, tất cả các bước thực hiện và vận chuyển sẽ được thực hiện tự động.",
    "wholesaler": "Người bán buôn",
    "wholesaler_info": "Sản phẩm của bạn sẽ được tiếp thị và bán bởi những người bán lại được bạn chấp thuận."
  },
  "community": {
    "title": "Nền tảng xây dựng cộng đồng",
    "available": "Cộng đồng tùy chỉnh miễn phí",
    "available_info": "Khả năng tạo một cộng đồng tùy chỉnh",
    "nomination": "Bằng cách đề cử",
    "domain": "Tên miền tùy chọn",
    "domain_info": "Bạn sẽ có diễn đàn trên miền của riêng bạn.",
    "onboarding": "Nhập môn",
    "onboarding_info": "Khả năng thêm quản trị viên và người kiểm duyệt cho diễn đàn.",
    "seo": "SEO",
    "seo_info": "Bạn không cần phải mua thêm các gói hoặc plugin cho các dịch vụ SEO chuyên nghiệp.",
    "analytic": "phân tích",
    "analytic_info": "Thông tin dễ dàng nhìn thấy trên các trang cộng đồng.",
    "post": "Đăng tải",
    "post_info": "Giới hạn bài đăng hàng tháng.",
    "comment": "Nhận xét",
    "comment_info": "Khả năng gửi và quản lý bình luận.",
    "voice": "Tiếng nói",
    "voice_info": "Khả năng ghi và gửi âm thanh trực tiếp.",
    "video": "Video",
    "video_info": "Khả năng gửi video (lên đến 8 MB)",
    "product": "Sản phẩm",
    "product_info": "Khả năng gửi sản phẩm trực tiếp qua đường bưu điện.",
    "poll": "Thăm dò ý kiến",
    "poll_info": "Khả năng thêm các cuộc thăm dò vào một chủ đề.",
    "report": "Báo cáo lạm dụng",
    "report_info": "Khả năng báo cáo lạm dụng của người dùng.",
    "profile": "Hồ sơ",
    "profile_info": "Hồ sơ người dùng được cá nhân hóa.",
    "sso": "Đăng nhập một lần (SSO)",
    "sso_info": "Khả năng đăng nhập nhanh thông qua dịch vụ Selldone SSO.",
    "embed": "Nhúng",
    "embed_info": "Khả năng nhúng và chia sẻ bài viết.",
    "reaction": "Sự phản ứng lại",
    "reaction_info": "Người dùng sẽ có thể ghi lại cảm nhận của họ về một câu chuyện.",
    "moderation": "Điều độ",
    "moderation_info": "Thêm và quản lý quyền truy cập diễn đàn."
  },
  "mission": {
    "title": "Chúng tôi đang thực hiện sứ mệnh",
    "message": "Giúp cho việc kinh doanh trở nên dễ dàng, có thể đạt được và có thể truy cập được cho bất kỳ ai trên khắp thế giới"
  },
  "marketplace": "Người xây dựng thị trường",
  "connect_os": {
    "subtitle": "Kết nối với các nhà cung cấp dropshipping chỉ bằng một cú nhấp chuột. Bạn có thể kết nối miễn phí với POD như cửa hàng Prinful hoặc Import Woocomerce."
  }
};