export default {
  "title": "Qala Mahhala, Khula Ngokushesha!",
  "sub_title": "Ukufinyelela okungenamkhawulo kuzo zonke izici ngaphandle kwenkokhiso! U <b>-2% kuphela wendali</b> , ngemva nje kokuthenga okuyimpumelelo. Ingabe unokuningi okuthengiswayo futhi ufuna ukunciphisa izinkokhelo?",
  "show_detail_list": "Bonisa uhlu lwemininingwane",
  "plan_free_detail": "<b class='text-capitalize'>Uhlelo lokusebenza lwamabhizinisi akhula ngokushesha</b> | Qala ibhizinisi lakho ngohlelo lwethu lwamahhala. Konke okudingayo ukuze uqale futhi wethule iwebhusayithi yakho ye-eCommerce isilungile lapha. I-Selldone inikeza yonke isofthiwe, amathuluzi, nesisombululo sokusingatha ifu ngohlelo lokubhalisa lwamahhala. I-Selldone ngaphezu kwalokho inakekela zonke izibuyekezo zesofthiwe nokucatshangelwa kokuphepha. Ngakho-ke ungakwazi ukugxila yonke imizamo yakho ekuthengiseni futhi ungakhathazeki ngezinkinga zobuchwepheshe nezindleko.",
  "pay_monthly": "Khokha nyanga zonke",
  "pay_yearly": "Khokha minyaka yonke",
  "pay_yearly_off": "30% isephulelo",
  "transparency_title": "Ukungafihli kumasevisi",
  "monthly_cost": "Intengo yanyanga zonke",
  "suggested_plan": "Uhlelo oluphakanyisiwe",
  "monthly_sell": "Ukuthengisa kwanyanga zonke",
  "saving_amount": "Ilondoloza nyanga zonke",
  "saving_tips": "Ngokuthenga uhlelo oluphakanyisiwe uzolondoloza le mali nyanga zonke.",
  "have_all_features": "Uzoba nazo zonke izici.",
  "currency": "USD",
  "want_free": "Ufuna Mahhala?",
  "stack_price": "Isitaki samathokheni ayizigidi ezingu-{amount} ngesekhondi",
  "gift": "Isipho esikhethekile",
  "gift_info": "Thola lesi sipho ngokuthenga lolu hlelo.",
  "toke_gift_ratio": "Ilingana nenani elikhokhiwe",
  "unlimited": "Okungenamkhawulo",
  "items_unit": "x",
  "delivery_person_unit": "Izithunywa",
  "soon": "Kuyeza maduze",
  "domains": "Izizinda ngokwezifiso",
  "staff": "Abaphathi",
  "community_builder": "Umakhi womphakathi",
  "active_discount_codes": "Amakhodi esaphulelo asebenzayo",
  "active_coupons": "Amakhuphoni athuthukile asebenzayo",
  "active_offers": "Imititilizo ethuthukisiwe esebenzayo",
  "active_gift_card_types": "Izinhlelo zekhadi lesipho",
  "active_campaigns": "Imikhankaso yokuthengisa esebenzayo",
  "active_affiliates": "Amanxusa asebenzayo",
  "active_emails": "Imikhankaso yokuthengisa ye-imeyili esebenzayo",
  "active_transportation_persons": "Izithunywa ezizimele",
  "active_importing_que": "Ubuningi bemikhiqizo engenisiwe ngesikhathi esisodwa",
  "active_reselling": "Ukuthengisa kabusha; Thengisa izinto zezitolo",
  "max_file_size": "Usayizi wefayela omkhulu ongathengiswa; Kuya ngesifunda sakho i-Euro/US/...",
  "active_capacity": "Isikhala sediski samahhala",
  "active_drop_shipping": "I-Wholesale dropshipping (Kudingeka Ukuqinisekisa)",
  "common_features": "Kufakwe kuzo zonke izinhlelo ze-{license}",
  "unlimited_storage": "Isitoreji esingenamkhawulo",
  "priority_support": "Usekelo olubalulekile",
  "support_247": "24/7 ukwesekwa",
  "read_more": "Funda kabanzi mayelana nezici...",
  "partners_upgrade_suggestion_message": "Awunakho ukuthenga okungcono kakhulu kokuthi {name}! Sincoma kakhulu ukuthi uyithuthukisele ezingeni eliphezulu kakhulu uma ungathandi imikhawulo.",
  "partners_upgrade_suggestion_action": "Thuthukisa uhlelo lwakho kokuthi {name} manje",
  "free": {
    "title": "Okomuntu siqu",
    "info": "Kubantu abasanda kuqala",
    "cost": "Mahhala",
    "fee_percent": 2,
    "items": [
      "Imikhiqizo engenamkhawulo",
      "1GB isitoreji",
      "Umkhawulokudonsa ongenamkhawulo",
      "Zonke izici zochwepheshe namathuluzi afakiwe",
      "Hudula Udedele Umakhi Wekhasi Lokuhlala",
      "Isici esigcwele se-CMS namabhulogi",
      "3 Amakhodi esaphulelo asebenzayo",
      "3 Amakhuphoni athuthukile",
      "3 Izipesheli ezithuthukile ezisebenzayo",
      "1 Izinhlelo zekhadi lesipho",
      "2 Imikhankaso yokuthengisa esebenzayo",
      "2 Izinhlelo ezisebenzisana nazo ezisebenzayo",
      "2 Imikhankaso yokuthengisa nge-imeyili esebenzayo",
      "2 izithunywa ezizimele",
      "Zonke izinsiza zokuthumela",
      "1 Admin"
    ]
  },
  "startup": {
    "title": "Qalisa",
    "info": "Okwamabhizinisi Amancane Asanda Kuqala",
    "fee_percent": 1.5,
    "items": [
      "Zonke izici zamahhala zifakiwe",
      "10GB isitoreji",
      "Ukungena ngemvume kwe-SMS yamakhasimende",
      "Ukuhlanganiswa kwe-3D / AR",
      "10 Amakhodi esaphulelo asebenzayo",
      "10 Amakhuphoni asethuthukile asebenzayo",
      "10 Izipesheli ezithuthukile ezisebenzayo",
      "Izinhlelo eziyi-10 zekhadi lesipho",
      "Imikhankaso eyi-10 yokuthengisa esebenzayo",
      "10 Izinhlelo ezisebenzisanayo ezisebenzayo",
      "Imikhankaso eyi-10 esebenzayo yokuthengisa nge-imeyili",
      "Izithunywa ezizimele eziyi-10",
      "Ukwesekwa okuvamile",
      "1 Isizinda",
      "5 Abaphathi"
    ]
  },
  "company": {
    "title": "Inkampani",
    "info": "Amabhizinisi Asendaweni Amancane Namaphakathi",
    "fee_percent": 1,
    "items": [
      "Zonke izici zokuqalisa zifakiwe",
      "Isitoreji esingenamkhawulo",
      "50 Amakhodi esaphulelo asebenzayo",
      "50 Amakhuphoni athuthukile asebenzayo",
      "50 Izipesheli ezithuthukile ezisebenzayo",
      "Izinhlelo ze-Giftcard ezingama-50",
      "Imikhankaso engama-50 yokuthengisa esebenzayo",
      "Izinhlelo ezisebenzisana nazo eziyi-100 ezisebenzayo",
      "Imikhankaso eyi-100 esebenzayo yokuthengisa nge-imeyili",
      "Izithunywa ezizimele ezingama-50",
      "Usekelo olubalulekile",
      "5 Izizinda",
      "20 Abaphathi"
    ]
  },
  "enterprise": {
    "title": "Ibhizinisi",
    "info": "Amabhizinisi Amakhulu",
    "fee_percent": 0.5,
    "items": [
      "Zonke izici zenkampani zifakiwe",
      "1K Amakhodi esaphulelo asebenzayo",
      "1K Amakhuphoni athuthukile asebenzayo",
      "1K Izipesheli ezithuthukisiwe ezisebenzayo",
      "1K Izinhlelo zekhadi lesipho",
      "1K Imikhankaso yokuthengisa esebenzayo",
      "1K Izinhlelo ezisebenzisana nazo ezisebenzayo",
      "1K Imikhankaso yokuthengisa ye-imeyili esebenzayo",
      "Izithunywa ezizimele ezingama-200",
      "24/7 ukwesekwa",
      "∞ Izizinda",
      "∞ Abaphathi"
    ]
  },
  "features": {
    "title": "Izici",
    "products": "Imikhiqizo",
    "usage": "Ithrafikhi yanyanga zonke",
    "custom_domain": "Engeza isizinda ngokwezifiso",
    "invite_to_get_free": "Mema umngane ukuthole mahhala",
    "ssl": "Ukuqinisekiswa kwe-SSL",
    "support": "24/7 ukwesekwa",
    "staff": "Inombolo yabalawuli",
    "staff_info": "Nikeza ukufinyelela kumalungu eqembu lakho.",
    "person": "umuntu(abantu)",
    "shop_name_length": "Ubude obuncane begama lesitolo",
    "chars": "Umlingiswa",
    "page_builder": "Dala elakho ikhasi",
    "page_builder_info": "Hudula Udedele Umakhi Wekhasi Lokuhlala",
    "pages": "Amakhasi",
    "cms": "I-CMS & Blog",
    "cms_info": "Ukuphathwa Kokuqukethwe Okuchwepheshile Nohlelo Lokuhlela Lokuthunyelwe Kwebhulogi Nemikhiqizo."
  },
  "gateways": {
    "title": "Iphothali Yokukhokha",
    "sub_title": "Izimbobo ezintsha zizongezwa maduze.",
    "gateways": "Amasango",
    "currencies": "Izimali",
    "currencies_info": "Izinhlobo zemali ezintsha zizongezwa maduze.",
    "currencies_encrypted": "Ikhodi yemali",
    "currencies_encrypted_info": "Imali yesikhulumi se-blockchain",
    "online_pay_wage": "Imali yembobo eku-inthanethi",
    "online_pay_wage_info": "Le mali izodonswa ku-akhawunti yakho yokushajwa kabusha e-Selldone.",
    "cod_wage": "Izimali Zokukhokha ze-COD",
    "cod_wage_info": "Le mali izodonswa ku-akhawunti yakho yezindleko",
    "file_wage": "Imali yokuthengisa ifayela",
    "file_wage_info": "Ikhomishana yokuthengisa ifayela efakwe ku-akhawunti yakho ngemuva kokuthengisa okuyimpumelelo (Isingathwe kusitoreji samafu se-SSD esinesivinini esikhulu)."
  },
  "apps": {
    "title": "Isitolo / Uhlelo Lokusebenza Lwesayithi",
    "pwa": "Uhlelo Lokusebenza Lwewebhu Oluthuthukisiwe",
    "android": "Android",
    "android_info": "Ifoni ye-Android ne-Tablet App",
    "ios": "I-iOS (iyeza maduze)",
    "ios_info": "I-Apple Ucingo & Uhlelo Lokusebenza Lwethebulethi"
  },
  "custom_domain": {
    "title": "Isizinda ngokwezifiso",
    "sub_title": "Yiba nesitolo sakho esizindeni sakho.",
    "domains_count": "Inombolo yezizinda zesitolo",
    "dns": "Cloud DNS",
    "cdn": "Cloud CDN",
    "cdn_info": "Inethiwekhi Yencazelo Yokuqukethwe Kwefu"
  },
  "host": {
    "title": "I-Cloud Host / Server yamahhala",
    "ssl": "Isitifiketi se-SSL",
    "storage": "Isitoreji",
    "usage": "Ithrafikhi yanyanga zonke",
    "setup": "Ukusetha kwamahhala",
    "technical_support": "ukusekela kwezobuchwepheshe",
    "file_sell": "Isitoreji sokuthengisa ifayela",
    "file_sell_info": "Idiski yokugcina amafu yamahhala yokuthengisa amafayela (Ngokushesha kakhulu)",
    "file_size": "Umkhawulo kasayizi wefayela ngalinye",
    "file_size_info": "Umkhawulo kasayizi wefayela ngalinye elithengiswayo (ungalayisha ifayela elingaphezu kwelilodwa lomkhiqizo ngamunye)"
  },
  "products": {
    "title": "Imikhiqizo"
  },
  "seo": {
    "title": "SEO",
    "meta": "Amathegi e-Meta",
    "meta_info": "Dala ama-meta tags athuthuke ngokugcwele ngokuzenzakalela",
    "jsonld": "JSON-LD",
    "jsonld_info": "Idatha Eyakhiwe",
    "amp": "AMP",
    "amp_info": "Amakhasi eselula asheshisiwe",
    "compress": "Ukucindezelwa Kwesithombe",
    "compress_info": "jpg, png, svg, wpng, ...",
    "boost": "I-Speed Accelerator",
    "boost_info": "Isihleli sokulayisha ikhasi lezinjini zokusesha",
    "sitemap": "Imephu yesayithi",
    "sitemap_info": "Imephu Yesayithi Yenjini Yokusesha"
  },
  "other": {
    "title": "Ezinye Izici",
    "plugins": "Izengezo Nezinhlelo zokusebenza",
    "plugins_info": "Ukufinyelela Izengezo Zesitolo Se-Selldone",
    "customer_service": "Insizakalo yekhasimende",
    "customer_service_info": "Imibuzo Evame Ukubuzwa, Ifomu Lobudlelwane Bekhasimende, Ukuphathwa Kwembuyiselo ...",
    "export": "Thumela imikhiqizo",
    "export_info": "Thola amafayela okukhiphayo ayo yonke imikhiqizo analo lonke ulwazi nokuqukethwe. Ngalesi sici, uzoba nesizindalwazi esijwayelekile semikhiqizo yakho ungaxhunyiwe ku-inthanethi.",
    "import": "Ngenisa Imikhiqizo Ngobuningi",
    "import_info": "Isevisi ethuthukisiwe ye-Selldone ikusiza ukuthi ulayishe imikhiqizo yakho ngezithombe 100% ngokuzenzakalelayo ngaphandle kokukhokha noma yiziphi izindleko kunoma iyiphi enye isevisi yomakhi wesitolo noma isizindalwazi sakho esingaxhunyiwe ku-inthanethi.",
    "Simultaneous": "Kanyekanye"
  },
  "logistic": {
    "title": "Logistics",
    "logistic": "Logistics & Ezokuthutha",
    "logistic_desc": "Ukuphathwa kwempahla nezindlela zokuthumela",
    "private_transportation": "Isistimu yokuthumela yangasese",
    "private_transportation_desc": "Dala futhi uphathe isevisi yokuthumela eyimfihlo.",
    "transportation": "Phatha izindlela zokuthumela ezithuthukile",
    "transportation_desc": "Izinkonzo zemikhumbi zasekhaya nezamazwe ngamazwe",
    "process_center": "Isikhungo Sokucubungula Esithuthukile",
    "process_center_desc": "Iphaneli yokuphatha ama-oda okulula ukuyisebenzisa",
    "return_requests": "Abaphathi bokubuyisela",
    "return_requests_desc": "Ukuphathwa kokubuyisela i-oda."
  },
  "marketing": {
    "title": "Ukuthengisa Nokuthengisa",
    "campaign": "Dala futhi uphathe umkhankaso",
    "affiliate_marketing": "Ukuthengisa okuhambisanayo",
    "affiliate_marketing_desc": "Dala futhi uphathe izinhlelo zokuthengisa",
    "email_marketing": "Iphaneli yokumaketha nge-imeyili",
    "email_marketing_desc": "Ukudizayina nokuthumela ama-imeyili ahlosiwe ezithamelini ngezihlungi nempendulo",
    "funnel": "Isihlungi somsebenzisi Esithuthukisiwe",
    "funnel_desc": "Hlunga abasebenzisi ngobulili, umlando wokuthenga, ukungena ngemvume kokugcina, njll.",
    "ab_test": "Ukuhlolwa kwe-A / B",
    "user_reaction": "Ukuhlaziywa Kwekhasi Lokuhlala",
    "user_reaction_desc": "Buka izingxenye ezibekiwe nezichofoziwe zamakhasi okufika njengemephu eshisayo kanye nomdwebo"
  },
  "customers": {
    "title": "Amakhasimende & Incentives",
    "club": "I-Client Club",
    "discount_code": "Ikhodi yesaphulelo",
    "discount_code_info": "Dala amakhodi esaphulelo angenamkhawulo.",
    "coupon": "Ikhuphoni / Ivawusha",
    "coupon_info": "Nikeza amakhasimende akho inani elingashintshi, iphesenti, noma isaphulelo sokuhambisa.",
    "gift_card": "Ikhadi lesipho",
    "gift_card_info": "Yenza ikhadi lokushaja elingenamkhawulo.",
    "offer": "Nikeza",
    "offer_desc": "Thenga lo mkhiqizo, Thola lowo mahhala (noma ngesaphulelo)",
    "game": "I-Gamification",
    "game_desc": "Dizayina umdlalo onemiklomelo"
  },
  "bots": {
    "title": "Amabhothi, Amanethiwekhi Omphakathi, Neziteshi Zokuthengisa",
    "telegram": "Irobhothi yokuthengisa yocingo",
    "telegram_info": "Yakha isitolo sakho seTelegramu mahhala",
    "instagram": "I-Instagram",
    "instagram_info": "Xhuma isitolo sakho ku-Instagram.",
    "facebook": "Facebook",
    "facebook_info": "Ukukhiqiza ngokuzenzakalela nokuvumelanisa uhlu lwemikhiqizo egcwele.",
    "avocado": "Ukwatapheya Social Media Sales Service",
    "avocado_info": "Ngale sevisi, uzokwazi ukuthola ama-oda avela kumakhasimende ngaphandle kokwengeza umkhiqizo nangefomu ezinkundleni zokuxhumana.",
    "hyper": "I-Hyper Quick Order",
    "hyper_info": "Ukuthengisa amakhulukhulu emikhiqizo ngomzuzu emibukisweni, emikhosini, ezitebeleni nanoma yikuphi lapho ufuna ukudayisa imikhiqizo kunombolo enkulu yamakhasimende."
  },
  "assistance": {
    "title": "Izaziso",
    "notifications": "Iziteshi zezaziso",
    "email": "I-imeyili",
    "email_info": "Thumela ama-imeyili kumakhasimende nabasebenzi basesitolo.",
    "sms": "SMS",
    "sms_info": "Thumela i-SMS kumakhasimende nabasebenzi basesitolo.",
    "report": "Umbiko Ohlakaniphile",
    "report_info": "Thumela imibiko yezikhathi yangeviki neyonyaka yobuthakathaka besitolo, abasebenzisi nokuthengisa, kanye namathiphu okuthuthukisa ukusebenza kwakho nokwandisa ukuthengisa."
  },
  "automation": {
    "title": "Okuzenzakalelayo",
    "niomatic": "I-Niomatic",
    "niomatic_info": "Inqubo ethuthukisiwe yokuzenzakalela ngokusekelwe kokuthandwayo kwebhulokhi eyisithombe",
    "autopilot": "I-Autopilot",
    "autopilot_info": "Hlela imicimbi, izaphulelo, shicilela okuthunyelwe kwebhulogi, imikhiqizo nezinye izinto."
  },
  "pos": {
    "title": "Selldone POS",
    "pos": "Store Cashier",
    "pos_info": "Uhlelo lwe-POS oluxhunywe esitolo sakho esiku-inthanethi luhlinzeka ngakho konke ukugcina, ukuthengisa, nezinqubo zokusekela ezinomsebenzi obonakalayo oyingqayizivele.",
    "online_payment": "Inkokhelo ye-inthanethi",
    "online_payment_info": "Amathuba okukhokha ku-inthanethi kumakhasimende akho esitolo sakho sangempela.",
    "hardware": "Izingxenyekazi zekhompuyutha",
    "hardware_info": "Ikhono lokuxhuma kuzikena zebhakhodi, izibonisi ezibhekene nekhasimende, amaphrinta ngelebula nezinye izingxenyekazi zekhompuyutha ukwenza lula inqubo yokuthengisa."
  },
  "dropshipping": {
    "title": "Ihabhu ye-Dropshipping",
    "reseller": "Ukudayisa kabusha",
    "reseller_info": "Ungangeza imikhiqizo yomthengisi esitolo sakho ngokuchofoza okukodwa, konke ukugcwaliseka nezinyathelo zokuthumela kuzokwenziwa ngokuzenzakalelayo.",
    "wholesaler": "Umthengisi",
    "wholesaler_info": "Imikhiqizo yakho izomakethwa futhi ithengiswe abadayisi abagunyazwe nguwe."
  },
  "community": {
    "title": "I-Community Builder Platform",
    "available": "Umphakathi Wamahhala Wangokwezifiso",
    "available_info": "Ikhono lokudala umphakathi wangokwezifiso",
    "nomination": "Ngokuqokwa",
    "domain": "Isizinda ngokwezifiso",
    "domain_info": "Uzoba nenkundla esizindeni sakho.",
    "onboarding": "Ukugibela",
    "onboarding_info": "Ikhono lokwengeza umlawuli kanye nomengameli wenkundla.",
    "seo": "SEO",
    "seo_info": "Awudingi ukuthenga amaphakheji engeziwe noma ama-plugin wezinsizakalo ze-SEO ezichwepheshile.",
    "analytic": "Izibalo",
    "analytic_info": "Ulwazi lubonakala kalula emakhasini omphakathi.",
    "post": "Thumela",
    "post_info": "Umkhawulo wokuthunyelwe wanyanga zonke.",
    "comment": "Phawula",
    "comment_info": "Ikhono lokuthumela nokuphatha imibono.",
    "voice": "Izwi",
    "voice_info": "Ikhono lokurekhoda nokuthumela umsindo oqondile.",
    "video": "Ividiyo",
    "video_info": "Ikhono lokuthumela ividiyo (kufika ku-8 MB)",
    "product": "Umkhiqizo",
    "product_info": "Ikhono lokuthumela umkhiqizo ngokuqondile ngeposi.",
    "poll": "Ipholi",
    "poll_info": "Ikhono lokwengeza ama-poll esihlokweni.",
    "report": "Bika ngokuhlukunyezwa",
    "report_info": "Ikhono lokubika ukuhlukunyezwa ngabasebenzisi.",
    "profile": "iphrofayili",
    "profile_info": "Iphrofayili yomsebenzisi eyenziwe yaba ngeyakho.",
    "sso": "Ukungena ngemvume okukodwa (SSO)",
    "sso_info": "Amathuba okungena ngokushesha ngesevisi ye-Selldone SSO.",
    "embed": "Shumeka",
    "embed_info": "Ikhono lokushumeka futhi wabelane ngokuthunyelwe.",
    "reaction": "Ukusabela",
    "reaction_info": "Abasebenzisi bazokwazi ukurekhoda ukuthi bazizwa kanjani ngendaba.",
    "moderation": "Ukulinganisela",
    "moderation_info": "Engeza futhi uphathe ukufinyelela kwenkundla."
  },
  "mission": {
    "title": "Siku mission to",
    "message": "Yenza ibhizinisi libe lula, lifinyeleleke, futhi lifinyeleleke kunoma ubani emhlabeni jikelele"
  }
};