<?php 

 return [
     "email-types" => [
        [
     "title" => "Zamówienie potwierdzone przez kupującego",
],
        [
     "title" => "Potwierdzenie płatności klienta",
],
        [
     "title" => "Powiadomienie o potwierdzeniu zamówienia do sprzedawcy",
],
        [
     "title" => "Potwierdź zamówienie w sklepie dla kupującego",
],
        [
     "title" => "Potwierdź płatność kasy dla kupującego",
],
        [
     "title" => "Zawiadomienie o zakupie w pudełku sprzedawcy",
],
        [
     "title" => "Poinformuj formularz kontaktowy",
],
        [
     "title" => "Gratulujemy dołączenia do sklepu",
],
        [
     "title" => "Ogłoszenie o otrzymaniu karty podarunkowej dla użytkownika",
]
     ],
     "global" => [
     "greetings" => "Cześć :imię",
     "end-statement" => "Grupa wsparcia",
     "receiver_name" => "Cześć :nazwa_użytkownika",
     "footer-help" => "Potrzebuję pomocy? Zapytaj na [support@selldone.com](mailto:support@selldone.com) lub odwiedź nasze [centrum pomocy](https://selldone.com/help)",
     "footer-shop" => "Jeśli potrzebujesz pomocy, napisz do nas e-mail: :shop_mail",
     "accept" => "Zaakceptować",
     "reject" => "Odrzucić",
     "verify" => "zweryfikować",
     "title" => "Tytuł",
     "value" => "Wartość",
     "description" => "Opis",
     "Shop" => "Sklep",
     "user" => "użytkownik",
     "license" => "Licencja",
     "status" => "Status",
     "start" => "Początek",
     "end" => "Koniec",
     "renewal" => "Odnowienie",
     "view" => "Pogląd",
     "balance" => "Saldo",
     "card_number" => "Numer karty",
     "cvv" => "Cvv",
     "expire_date" => "Data ważności",
     "dashboard" => "panel",
     "order" => "zamówienie",
     "view_order" => "Zobacz zamówienie",
     "pay_now" => "Pay now",
     "official_selldone" => "OFICJALNA SPRZEDAŻ",
     "account-number" => "Account number",
     "account-name" => "Account name",
     "currency" => "Waluta",
     "free-balance" => "Darmowe saldo",
     "locked-balance" => "Zablokowane saldo",
     "bot" => "Nerw",
     "requests" => "Upraszanie",
     "baskets" => "Wózki",
     "physical" => "Fizyczny",
     "virtual" => "Wirtualny",
     "file" => "Plik",
     "service" => "Usługa",
     "fulfillment" => "Spełnienie",
     "open" => "otwarty",
     "reserved" => "Skryty",
     "canceled" => "Odwołany",
     "payed" => "Płatny",
     "cod" => "COD",
     "orders-count" => "Zamówienia",
     "payments-count" => "Płatności",
     "confirms-count" => "Potwierdza",
     "sends-count" => "Wysyła",
     "delivers-count" => "Dostarcza",
     "count" => "Liczyć",
     "transactions-count" => "Liczba transakcji",
     "success-transactions" => "Transakcje sukcesu",
     "total-amount" => "Całkowita kwota",
     "amount" => "Ilość",
     "wage" => "Płaca",
     "debug" => "Odpluskwić",
     "pos" => "POS",
     "live" => "Na żywo",
     "CheckQueue" => "Sprawdź kolejkę",
     "OrderConfirm" => "Zamówienie potwierdzone",
     "PreparingOrder" => "Przygotowanie zamówienia",
     "SentOrder" => "Wysłano zamówienie",
     "ToCustomer" => "Dostarczone do klienta",
     "Pending" => "Aż do",
     "Accepted" => "Przyjęty",
     "Rejected" => "Odrzucony",
     "pc" => "PC",
     "tablet" => "Tablet",
     "phone" => "Telefon",
     "total" => "Całkowity",
     "view-detail" => "Pokaż szczegóły",
     "empty" => "Pusty",
     "dropshipping" => "Dropshipping",
     "reply" => "Odpowiedź",
     "reactions" => "Reakcje",
     "comments" => "uwagi",
     "last-comment" => "Ostatni komentarz",
     "response-to" => "Odpowiedź na",
     "posts" => "Posty",
     "post" => "Poczta",
     "name" => "Nazwać",
     "email" => "E-mail",
     "type" => "rodzaj",
     "device" => "Urządzenie",
     "platform" => "Platforma",
     "browser" => "Przeglądarka",
     "time" => "Czas",
     "wallet" => "portfel",
     "date" => "Data",
     "account" => "Rachunek",
     "transaction" => "Transakcja",
     "fee" => "Opłata",
     "location" => "Location",
     "ip" => "Ip",
     "bill" => "Rachunek",
     "category" => "Kategoria",
     "password" => "Hasło",
     "shop" => "Sklep",
     "verify-login" => "Zweryfikuj i zaloguj się",
     "url" => "URL",
     "avocado" => "Awokado",
     "hyper" => "Hiper",
     "buy-now" => "Kup Teraz",
     "add-domain" => "Add Domain",
     "views" => "Wyświetlenia",
     "country" => "Kraj",
     "address" => "adres",
     "postal" => "kod pocztowy",
     "building_no" => "Budynek #",
     "building_unit" => "Jednostka #",
     "message" => "Wiadomość",
     "customer" => "Klient",
     "cart-items" => "Elementy koszyka",
     "payment" => "Zapłata",
     "receiver" => "Odbiorca",
     "virtual-items" => "Przedmioty wirtualne",
     "no-payment" => "Brak płatności!",
],
     "selldone-business-os" => "Sprzedany biznesowy system operacyjny",
     "senders" => [
     "WeeklyReport" => [
     "id" => "performance",
     "name" => "Raport skuteczności, sprzedany",
],
     "SeasonalReport" => [
     "id" => "seasonal",
     "name" => "Raport sezonowy, sprzedany",
],
     "Onboarding" => [
     "id" => "cześć",
     "name" => "Sprzedany zespół",
],
     "Support" => [
     "id" => "support",
     "name" => "Wsparcie: nazwa",
],
     "EmailVerify" => [
     "id" => "verify",
     "name" => "Zweryfikuj, sprzedane",
],
     "Welcome" => [
     "id" => "cześć",
     "name" => "Społeczność, Sprzedane",
],
     "NewShop" => [
     "id" => "kupcy",
     "name" => "Kupcy, Sprzedane",
],
     "Approve" => [
     "id" => "zatwierdzić",
     "name" => "Zatwierdź, sprzedane",
],
     "SellerReceiveOrder" => [
     "id" => "order",
     "name" => "Zarządzanie zamówieniami: nazwa",
],
     "Recovery" => [
     "id" => "powrót do zdrowia",
     "name" => "Sprzedany zespół odzyskiwania",
],
],
     "bill-status" => [
     "PENDING" => "Oczekujące ⌛",
     "PAYED" => "Płatne ✅",
     "CANCELED" => "Anulowano",
],
     "shop-invite" => [
     "LEVEL-NAME" => [
     "ADMIN" => "Administrator",
     "OFFICER" => "Oficer i Inspektor",
     "AUDITING" => "Kierownik audytu",
     "EMPLOYEE" => "Pracownik",
     "PRODUCT" => "Menedżer produktów",
     "CONTENT" => "Menedżer treści",
     "MARKETING" => "Menadżer marketingu",
     "VIEWER" => "Widz",
],
     "subject" => ":inviter Zapraszam jako :level | :sklep",
     "category" => "Zaproszenie personelu",
     "title" => "Zostałeś zaproszony do <b>:shop_name</b> jako <b>:level</b> .",
     "message" => "Zaproszenie zostało wysłane do Ciebie. Możesz to potwierdzić lub odrzucić. Jeśli to zaproszenie zostanie przez Ciebie zaakceptowane, musisz wejść do usługi Selldone, aby je potwierdzić. Potwierdzając to zaproszenie, uzyskasz dostęp do sekcji zarządzania sklepem.",
],
     "welcome-email" => [
     "subject" => "👋 Witaj :imię, kilka ciekawych rzeczy właśnie dla Ciebie.",
     "category" => "CONGRATULATION",
     "title" => "ZAPRASZAMY DO SPRZEDAŻY",
     "message" => "Dziękujemy za wybranie Selldone. Jesteś teraz częścią społeczności Selldone, która łączy globalnych sprzedawców z klientami, lokalną firmę z przedsiębiorstwem, osobę prywatną z korporacją! Wszystkie narzędzia master i pro zostały dostarczone **bezpłatnie** i **nieograniczone** dla Ciebie. Próbujesz, otwieramy drzwi, po prostu zrób to!",
     "seller" => [
     "title" => "Czy jesteś sprzedawcą?",
     "message" => "Aby rozpocząć sprzedaż, wejdź do swojego pulpitu nawigacyjnego w Selldone za pomocą poniższego linku i utwórz swój pierwszy sklep całkowicie za darmo. Zajmie to kilka minut i będziesz mieć własny sklep i stronę internetową. Następnie poprowadzimy Cię do kolejnych kroków i uzyskamy bramkę płatności.",
     "action" => "Zaloguj się do mojego pulpitu nawigacyjnego",
],
     "buyer" => [
     "title" => "jestem kupującym",
     "message" => "Gratulacje. Gdy zostaniesz członkiem Selldone, pozbędziesz się wszystkich problemów związanych z członkostwem i uwierzytelnianiem w sklepach internetowych. Aby skorzystać z dowolnego sklepu i witryny korzystającej z platformy Selldone, możesz zalogować się jednym kliknięciem i dokonać prostego, szybkiego i bezpiecznego zakupu.",
],
],
     "charge-account" => [
     "category" => "Portfel > Konto > Obciążenie",
     "title" => "Opłata za sukces",
     "message" => "Twoje konto <b>:account_number</b> zostało pomyślnie <b>:amount</b> obciążone.",
     "account" => "Rachunek",
     "charge" => "Opłata",
     "balance" => "Saldo",
     "footer" => "Spraw, by biznes był łatwy, osiągalny i dostępny dla każdego na całym świecie.",
],
     "verify-email" => [
     "subject" => "🙌 Dokończ rejestrację w Selldone! Zweryfikuj link.",
     "category" => "JESTEŚ O KROK DANYCH",
     "title" => "Zweryfikuj swój adres email",
     "message" => "Cześć :imię,<br> Dziękujemy za wybranie Selldone.<br> Potwierdź, że **:email** to Twój adres e-mail, klikając przycisk lub użyj poniższego linku w ciągu 48 godzin.",
     "footer" => "Jeśli masz problem z kliknięciem przycisku Zweryfikuj, skopiuj poniższy adres URL i wklej go w przeglądarce internetowej: __:activation_url__",
],
     "verify-email-code" => [
     "subject" => "Kod weryfikacyjny dla :nazwa",
     "category" => "SECURITY",
     "title" => "Kod weryfikacyjny e-mail",
     "message" => "Cześć :imię,<br><br> Potwierdź, że **:e-mail** to Twój adres e-mail za pomocą tego kodu w ciągu 10 minut.",
],
     "onboarding-verify-email" => [
     "subject" => "🎉 Twój sklep jest gotowy | :Nazwa",
     "category" => "JESTEŚ O KROK DANYCH",
     "title" => "Konfiguracja zakończona",
     "account_title" => "Twoje konto",
     "account_msg" => "Zweryfikuj i zaloguj się na swoje konto za pomocą tych informacji.",
     "shop_msg" => "Informacje o koncie w firmowym systemie operacyjnym Selldone.",
],
     "reset2fa" => [
     "category" => "OFICJALNA WIADOMOŚĆ BEZPIECZEŃSTWA",
     "title" => "Poproś o wyłączenie logowania dwuetapowego",
     "message" => "Otrzymujesz tę wiadomość e-mail, ponieważ otrzymaliśmy prośbę o zresetowanie uwierzytelniania dwuskładnikowego dla Twojego konta.<br><br> E-mail użytkownika: <b>:e-mail</b><br> Imię: <b>:nazwa</b>",
     "footer" => "Jeśli nie zażądałeś zresetowania hasła, nie są wymagane żadne dalsze działania.",
     "action" => "Wyłącz logowanie dwuetapowe",
],
     "build-new-shop" => [
     "subject" => "🎊 Twój sklep jest już gotowy!",
     "category" => "NARODZONY NOWY SKLEP INTERNETOWY NA ŚWIECIE",
     "title" => "Świętujemy",
     "message" => "<b>Gratulacje :nazwa, stworzyłeś nowy biznes online;</b> Życzymy powodzenia w Twoim biznesie. Witamy w społeczności Selldoners.<br> Ty próbujesz, my otwieramy drzwi i Ty to zrobiłeś.",
     "pdf-book" => "Nie przegap dołączonego podręcznika: Do Your Business Like A Game",
     "account" => [
     "title" => "Krok 1: Utwórz konto w portfelu Selldone",
     "message" => "Jeśli nie masz konta w swoim portfelu, utwórz je. Selldone potrąca opłatę z tego konta. Możesz doładować to konto, a Selldone obciąży Cię również kwotą kredytu, dzięki czemu jeśli to konto będzie ujemne, Twoja witryna i Sklep będą nadal działać.",
     "action" => "Zaloguj się do portfela",
],
     "shop-account" => [
     "title" => "Krok 2: połącz konto ze sklepem",
     "message" => "Dodaj konto portfela do swojego sklepu. W tym celu wejdź w Sklep > Księgowość > Faktura i połącz konto ze sklepem. Pamiętaj, że wszystkie płatności Twoich klientów są deponowane bezpośrednio na Twoim koncie bankowym i żadna kwota nie jest wypłacana ani odliczana przez Selldone, więc musisz połączyć to konto Selldone ze sklepem.",
     "action" => "Sklepowy panel faktur",
],
     "gateway" => [
     "title" => "Krok 3: Podłącz bramkę płatności online",
     "message" => "Przejdź do Sklep> Księgowość> Port i naciśnij <b>Dodaj nowy port</b> . Po wybraniu waluty zostanie wyświetlona lista portów przenośnych. Podłączenie portu w Selldone jest bardzo proste i szybkie, ale jeśli masz Nizę po wskazówki, zapoznaj się z sekcją przewodnika Selldone lub zapytaj nas.",
     "action" => "Dodaj portal do sklepu",
],
     "domain" => [
     "title" => "Ostatni krok: podłączenie dedykowanej domeny",
     "message" => "Będziesz mógł mieć swój sklep na tylu domenach, ile chcesz. Aby podłączyć dedykowaną domenę do sklepu, musisz mieć przynajmniej licencję startową. Przedstawiając każdemu znajomemu Selldone, otrzymasz miesięczną kartę podarunkową z licencją startową. Procent płatności Twoich znajomych zostanie również zaksięgowany na kontach Twoich klientów.",
     "action" => "Wprowadzanie i otrzymywanie nielimitowanych kart podarunkowych",
],
],
     "basket-list" => [
     "item" => "przedmiot",
     "count" => "Liczyć",
     "price" => "Cena",
     "discount-code" => "Kod rabatowy",
     "customer-club" => "Klub Klienta",
     "shipping" => "Wysyłka",
     "total" => "Całkowity",
     "offer" => "Oferta",
     "coupon" => "Kupon",
     "lottery" => "Nagroda",
     "tax" => "Podatek",
     "tax_included" => "Wliczony w cenę",
     "tax_shipping" => "Shipping Tax",
],
     "buyable-payments" => [
     "method" => "metoda",
     "amount" => "Ilość",
     "giftcard" => "Gift card",
     "payment" => "Zapłata",
],
     "shop-subscription-email" => [
     "category" => "Aktualizacja subskrypcji",
     "title" => "Licencja na sklep: :shop_title",
     "title-reserved" => "Zarezerwuj licencję: :shop_title",
     "title-active" => "Aktywna licencja: :shop_title",
     "title-finished" => "Gotowa licencja: :shop_title",
     "title-cancel" => "Anuluj licencję: :shop_title",
     "message" => "Zaktualizowany plan licencyjny Twojego sklepu,",
     "RESERVED" => "⚡ Twój plan subskrypcji został **zarezerwowany**.",
     "ACTIVE" => "🟢 Twój plan subskrypcji został **aktywowany**.",
     "FINISHED" => "🚧 Twój plan subskrypcji został **ukończony**.",
     "CANCEL" => "⛔ Twój plan subskrypcji został **anulowany**.",
],
     "support" => [
     "subject" => "Centrum wsparcia | :nazwa odpowiedziała",
     "category" => "Centrum Wsparcia",
     "title" => "Otrzymałeś odpowiedź",
     "action" => "Otwórz sklep administratora",
],
     "shop-customer-join" => [
     "subject" => "Dołącz do: tytuł_sklepu",
     "category" => "Święto nowego klienta",
     "title" => "Cieszymy się z Twojego członkostwa",
     "action" => "Odwiedź teraz",
],
     "shop-giftcard" => [
     "subject" => "Karta podarunkowa :shop_title",
     "category" => "Dodaj nową kartę",
     "title" => "Gratulacje, otrzymałeś kartę podarunkową",
     "action" => "Kupuj teraz",
     "message" => "Otrzymałeś kartę podarunkową na kwotę :balance :currency. Za pomocą tej karty podarunkowej będziesz mógł kupować w naszym sklepie.",
],
     "contact" => [
     "subject" => "Centrum wsparcia | :sklep",
     "category" => "Pomoc",
     "title" => "Otrzymałeś odpowiedź",
],
     "order-checkout" => [
     "subject" => "🛍 Zamów kasę | :id_zamówienia",
     "title" => "zamówienie",
     "message" => "Twoje zamówienie potwierdza,<br> Mamy twoje zamówienie. Wyślemy Ci kolejną wiadomość e-mail, gdy Twoje zamówienie zostanie wysłane.",
     "payments" => "Płatności",
],
     "order-payment" => [
     "subject" => "🛍 Potwierdzenie płatności | :id_zamówienia",
     "title" => "Polecenie zapłaty",
     "message" => "Twoja płatność zakończona,<br> Mamy twoje zamówienie. Wyślemy Ci kolejną wiadomość e-mail, gdy Twoje zamówienie zostanie wysłane.",
     "payments" => "Płatności",
],
     "get-voucher" => [
     "subject" => "Gratulacje :nazwa | Nowy kupon: :tytuł",
     "category" => "GRATULACJE, NOWY VOUCHER",
     "message" => "Otrzymujesz nowy voucher, To prezent od nas dla Ciebie. Możesz uzyskać więcej z tych kuponów, przedstawiając Selldone znajomym i wszystkim, których znasz. Ten voucher jest wart **:cena :waluta**.<br> Próbujesz, otwieramy drzwi, Gratulacje, Odblokuj funkcje za pomocą kuponu!",
     "action" => "Moja tablica",
],
     "received-gift" => [
     "subject" => "Gratulacje, Kochanie :imię | Otrzymałeś prezent",
     "category" => "Ogłoszenie otrzymania prezentu",
     "title" => "Prezenty dla Ciebie",
     "message" => "Otrzymałeś nowy prezent. To prezent od Selldone. Możesz otrzymać więcej takich prezentów, będąc bardziej aktywnym w Selldone, rozwijając swój sklep i podnosząc poziom specjalizacji. Wartość prezentu to **:cena :waluta**, którą możesz wpłacić bezpośrednio do swojego portfela w sprzedaży.<br><br> Użyj tego prezentu, aby uaktualnić licencję na sklep i korzystać z większej liczby narzędzi w swoim biznesie online.",
     "action" => "Prezenty",
],
     "order-payment-admin" => [
     "subject" => "🛍 Otrzymano nowe zamówienie | :id_zamówienia",
     "title" => "New Order",
     "message" => "Otrzymałeś nowe zamówienie. Przejdź do strony przetwarzania zamówienia w swoim sklepie.",
],
     "virtual-item" => [
     "input-form-title" => "Twoje wypełnione informacje",
     "output-form-title" => "Informacje o zakupionym przedmiocie",
],
     "selldone-weekly-report" => [
     "subject" => "📬: tytuł_sklepu | Raport tygodniowy: czas",
     "title" => "Tygodniowy raport wydajności sklepu",
     "message" => "To jest tygodniowy raport Twojego sklepu od :początek do :koniec. Ten raport zawiera wskazówki, jak usprawnić swój biznes, możesz także sprawdzić stan swojego sklepu internetowego i ostatnie zamówienia. Mam nadzieję, że masz przed sobą dobry dzień i tydzień.",
],
     "shop-seasonal-report" => [
     "subject" => "☘ Twój raport oszczędności :amount w ciągu ostatnich trzech miesięcy | :tytuł_sklepu",
     "title" => "Raport sezonowy o Twojej działalności, nagrodach i oszczędnościach finansowych",
     "message" => "To jest Twój raport sezonowy :shop_title od :początek do :koniec.",
],
     "EC-ShopAccounts" => [
     "title" => "Połączone konta",
     "sub-title" => "Jaki jest najnowszy stan kont portfela połączonych z moim sklepem?",
     "view-wallet" => "Zobacz portfel",
     "tip-title" => "Ważne wskazówki",
     "tip" => "W kolejnym kroku utwórz darmowe konto w swoim portfelu Selldone i połącz je z tym sklepem. Nawet jeśli saldo Twojego konta Selldone jest ujemne, Twoi klienci mogą nadal bez problemu dokonywać zakupów i płatności w Twoim sklepie. Twoje dane i usługa nie zostaną przerwane ani ograniczone przez co najmniej 1 miesiąc.",
     "view-my-wallet" => "My wallet",
     "connect-account" => "Połącz z kontem",
],
     "EC-ShopApps" => [
     "title" => "Zainstalowane aplikacje",
     "sub-title" => "Lista aplikacji, które zainstalowałeś w swoim sklepie w tym tygodniu.",
     "tip" => "Chcesz znaleźć więcej aplikacji do swojego sklepu?",
     "view-app-store" => "Odwiedź Selldone App Store..",
],
     "EC-ShopBots" => [
     "title" => "Twoje boty w sklepie",
     "sub-title" => "Aktywne boty sprzedażowe w moim sklepie.",
     "tip-title" => "Wyprzedaż botów",
     "tip" => "Selldone udostępnił Ci automatyczne boty sprzedażowe. Wszystko, co musisz zrobić, to przejść do panelu Dodatki> Boty i aktywować boty sklepu. Pamiętaj, że odpowiednia usługa musi być dostępna w Twoim kraju.",
     "view-bots" => "Zarządzaj botami",
],
     "EC-ShopContacts" => [
     "title" => "Komunikacja z Klientami",
     "sub-title" => "Ile kontaktów miałem w tym tygodniu z moimi klientami?",
     "faqs" => "Często Zadawane Pytania",
     "tickets" => "Bilety klienta",
],
     "EC-ShopData" => [
     "title" => "Status użytkowników",
     "sub-title" => "Od daty :początek do :koniec",
     "users" => [
     "title" => "Klienci",
     "subtitle" => "Rejestracja użytkowników",
],
     "views" => [
     "title" => "Odwiedziny",
     "subtitle" => "Ile razy odwiedziłeś sklep",
],
     "new_visitors" => "New Users",
     "returning_visitors" => "Zwróceni użytkownicy",
     "shop_views" => "Widoki sklepu",
     "baskets" => [
     "title" => "Wózki na zakupy",
     "subtitle" => "Zgłoś liczbę nowych koszyków",
],
     "products" => [
     "title" => "Przegląd produktów",
     "subtitle" => "Status produktów w sklepie według typu",
     "value_name" => "Produkty",
],
     "products_count" => "Rodzaje produktów",
     "views_count" => "Licznik wyświetleń",
     "sell_count" => "Sprzedaj licznik",
     "send_count" => "Liczba przesyłek",
],
     "EC-ShopDropShipping" => [
     "title" => "Drop Shipping",
     "sub-title" => "Panel dla głównych sprzedawców Drop Shipping Selldone.",
     "total_fulfillments" => "Łączna liczba otrzymanych zamówień",
     "ds_count" => "Otrzymane zamówienia",
     "statistics_title" => "Zgłoś otrzymane zamówienia",
     "ds_cancels" => "Anuluj przez sprzedawcę interfejsu",
     "ds_rejects" => "Anuluj przez Ciebie",
     "tip" => "Czy jesteś głównym sprzedawcą towarów? Posiadasz magazyn, fabrykę lub dystrybutora produktów? Możesz oferować swoje produkty innym sprzedawcom w usłudze Selldone Drop Shipping, aby sprzedawać swój produkt na dużą skalę. Napisz do nas na support@selldone.com, aby Cię poprowadzić.",
     "view-drop-shipping-panel" => "Zaloguj się do panelu hurtowego",
],
     "EC-ShopExchangeRates" => [
     "title" => "Kurs wymiany",
     "sub-title" => "Lista najnowszych kursów wymiany walut w Twoim sklepie.",
     "from" => "Waluta źródłowa",
     "to" => "Waluta docelowa",
     "rate" => "Współczynnik konwersji",
     "vew-exchange-panel" => "panel zarządzania kursami walut",
],
     "EC-ShopExperts" => [
     "title" => "Kontrakty eksperckie",
     "sub-title" => "Jacy profesjonaliści pracują w moim sklepie?",
     "cost" => "Kwota kontraktu",
     "duration" => "Czas trwania",
     "start_at" => "Start Date",
     "complete_at" => "Completion Date",
     "cancel_at" => "Data Anuluj",
     "end_at" => "Data dostarczenia",
     "tip" => "Możesz zatrudnić najlepszych specjalistów w Selldone, aby rozwijać swój biznes.",
     "view-experts" => "Kliknij, aby rozpocząć.",
],
     "EC-ShopGateways" => [
     "title" => "Payment gateways",
     "sub-title" => "Zgłoś aktywne bramki płatności w sklepie :shop.",
     "tip-title" => "Ważne wskazówki",
     "tip" => "Przejdź do strony zarządzania portalem w swoim sklepie i dodaj co najmniej jeden port w ciągu kilku minut. Twoi klienci lubią płacić szybko i bezpiecznie za pośrednictwem portali internetowych.",
     "view-shop-gateways" => "Zaloguj się do zarządzania portalem mojego sklepu.",
     "view-gateways" => "Zobacz więcej bram",
],
     "EC-ShopOrders" => [
     "title" => "Zamówienia",
     "sub-title" => "Lista zamówień, które otrzymałem w tym tygodniu.",
     "total_baskets" => "Razem zamówienia",
     "total_posBaskets" => "Łączne zamówienia gotówkowe",
     "pos-title" => "Pudełko sklepu POS",
     "chart-label" => "Zamówienia zrealizowane (te zamówienia niekoniecznie są płatne!)",
     "tip-title" => "Powinieneś spróbować mocniej ...",
     "tip" => "Nie ma prostego sukcesu.",
],
     "EC-ShopProcessCenter" => [
     "title" => "Centrum przetwarzania",
     "sub-title" => "Ile zamówień przetworzyliśmy w sklepie w tym tygodniu?",
     "tip-title" => "Nie miałeś wyprzedaży!",
     "tip" => "Niestety w tym tygodniu nie miałeś żadnych wyprzedaży. Potrzebujesz więcej do swojego sklepu. Możesz dodać więcej produktów, wybrać lepsze zdjęcia lub napisać lepsze opisy swoich produktów. Zastanów się nad pracą na pełen etat dla swojej firmy. Jeśli zrobisz to dobrze i nie będziesz sfrustrowany, odniesiesz sukces.",
     "view-process-center" => "Zobacz centrum przetwarzania",
     "return" => [
     "title" => "Zwrócone zamówienie",
     "subtitle" => "Zgłoś zwrócone zamówienia.",
     "tip-title" => "Czy wiedziałeś o tym ...",
     "tip" => "Możesz utworzyć dowolną liczbę kas sklepowych za pośrednictwem Selldone POS! W rzeczywistości możesz zmienić swój tablet, telefon komórkowy lub laptop w skrzynkę odbiorczą. Jeśli to Cię ekscytuje, Selldone POS To coś, czego powinieneś zacząć używać już teraz. Wystarczy jedno kliknięcie, aby uruchomić, z wyprzedzeniem mamy wszystko przygotowane dla Twojego serwera.",
     "view-pos" => "Zaloguj się do Kasjera mojego sklepu internetowego",
],
],
     "EC-ShopSessions" => [
     "title" => "Sesje",
     "sub-title" => "Ile razy odwiedziłem mój sklep?",
     "countries-title" => "Które kraje były najczęściej odwiedzane?",
],
     "EC-PublicMessage" => [
     "title" => "Chcesz zarabiać nie wydając ani złotówki?",
     "message" => "Drogi :name, możesz przejść do Dashboard > Demonetization i utworzyć link polecający. Wyślij link do znajomych, Otrzymasz karty podarunkowe Selldone i procent od wpłat znajomego. Pamiętaj, że karta podarunkowa zostanie wysłana zarówno do Ciebie, jak i do Twojego znajomego.",
     "action" => "Wyświetl mój link wprowadzający",
     "mail-clip" => "<b style='color: #C2185B'>Ważne:</b> jeśli korzystasz z usług poczty e-mail, takich jak Gmail, które ograniczają długość wiadomości e-mail, znajdź następującą opcję na końcu wiadomości e-mail, aby wyświetlić pełny raport, i kliknij ją:",
     "no-coin-reward" => "<b style='color: #C2185B'>Przepraszamy:</b> Twoja aktywność nie spełniała wymagań, aby otrzymać darmową nagrodę w postaci monet SEL. Staraj się i sprzedawaj więcej w swoim sklepie na następny sezon.",
     "yes-coin-reward" => "<b style='color: #4CAF50'>Nagroda:</b> Gratulacje, z powodu twojego fantastycznego występu, daliśmy ci darmową nagrodę :amount SEL Coin.",
     "need-buy-license" => "<b>Zwiększ poziom swojej firmy:</b> Nie zarejestrowałeś żadnego abonamentu dla swojej witryny biznesowej! Czas więc kupić przynajmniej jedną subskrypcję. To tylko kosztuje :kwota miesięcznie za roczny zakup.",
     "not-afford-message" => "Jeśli nie możesz sobie pozwolić lub masz problem z płatnością, skontaktuj się z nami poprzez support@selldone.com.",
     "add-domain" => "<b>Dlaczego nie mieć niestandardowej domeny dla swojej firmy?</b><br> Dodaj domenę do swojej witryny teraz; jest wolne!",
],
     "Widget-Socials" => [
     "title" => "Sprzedane jest<del> produkt</del> <span style = 'color: forestgreen'>społeczność</span> .<br> Bądź profesjonalnym sprzedawcą!",
     "message" => "Śledź oficjalne strony Selldone na Twitterze, LinkedIn i portalach społecznościowych. Przesyłaj nam wszelkie uwagi, prośby lub krytykę lub uczestnicz w dyskusjach na temat Sprzedanego. Jesteśmy również częścią społeczności Selldone, którą <b>tworzysz</b> .",
],
     "avocado-seller-daily-report" => [
     "subject" => "Otrzymano nowe zamówienia na awokado | :tytuł_sklepu :czas",
     "title" => "Raport skuteczności z ostatnich 24 godzin",
     "message" => "Twoi klienci czekają na sprawdzenie i wycenę Twoich zamówień. Odpowiadaj na prośby swoich klientów tak szybko, jak to możliwe, aby zwiększyć sprzedaż.",
     "card_title" => "Zamówienia w kolejce",
     "card_subtitle" => "Od daty",
     "card_payed" => "Opłacone zamówienia",
],
     "community-comments" => [
     "subject" => "Odpowiedz na swój post w :community_title",
     "title" => ":name i :count inni skomentowali Twoje posty.",
     "title-simple" => ":nazwa skomentował Twoje posty.",
],
     "community-topic" => [
     "subject" => "🔔 Odpowiedz na swój temat :topic_title",
     "title" => ":name i :count inni odpowiedzieli na Twój temat.",
     "title-simple" => ":nazwa odpowiedziała na twój temat.",
],
     "user-login" => [
     "subject" => "🔔Nowy login: nazwa",
     "category" => "Powiadomienia dotyczące bezpieczeństwa",
     "title" => "Zaloguj się do konta",
     "message" => "Drogi :name, byłeś zalogowany do swojego konta Selldone.",
     "footer" => "Jeśli nie jesteś zalogowany, zmień hasło.",
],
     "account-transaction" => [
     "withdraw" => "Wycofanie",
     "deposit" => "Depozyt",
     "withdraw_subject" => "wypłata z konta :konto",
     "deposit_subject" => "Wpłata na konto: konto",
     "message" => "Przelew został wykonany z następującymi specyfikacjami.",
     "type" => "Typ transakcji",
     "from" => "Konto źródłowe",
     "to" => "Destination account",
     "desc" => "Opis transakcji",
     "action" => "Zobacz transakcję",
],
     "penalty" => [
     "subject" => "⛔ Ważne! Naruszenie zasad | :sklep",
     "category" => "Informacje krytyczne",
     "title" => "Twój sklep został ukarany",
     "action" => "Otwórz pulpit nawigacyjny sklepu",
],
     "invite" => [
     "subject" => ":zapraszający zaprosił Cię do Selldone",
     "title" => ":nazwa wysłała Ci :kwotę, aby pomóc Ci uruchomić nową stronę internetową i zarabiać na niej!",
     "message" => "W Selldone możesz stworzyć swój sklep internetowy, bloga i społeczność online, a nawet uzyskać online POS i skonfigurować sprzedaż osobistą w ciągu kilku minut. Jest to system operacyjny dla biznesu online, który sprawi, że Twoja firma będzie online, lepsza i szybsza. Wystarczy zarejestrować się do <b>:date</b> , aby otrzymać kupon :amount.",
     "accept" => "Przyjąć zaproszenie",
     "owner" => "Właściciel",
     "join-date" => "Sprzedane od",
],
     "shop-recovery" => [
     "subject" => "Link do odzyskiwania | :sklep",
     "category" => "Bezpieczeństwo sklepu",
     "title" => "Link do odzyskiwania sklepu <b>: nazwa_sklepu</b> .",
     "message" => "Ta wiadomość e-mail została do Ciebie wysłana, ponieważ poprosiłeś o przywrócenie sklepu. Kliknięcie w poniższy link spowoduje odzyskanie Twojego sklepu i wszystkich należących do niego danych.",
     "action" => "Potwierdź odzyskanie sklepu",
],
     "SR-SeasonalSaving" => [
     "title" => "Ile pieniędzy Selldone zaoszczędziło dla Twojej firmy?",
     "sub-title" => "Od daty :początek do :koniec",
     "infrastructure" => [
     "title" => "Infrastruktura",
     "subtitle" => "Serwery, CDN, pamięć masowa i inne usługi w chmurze",
],
     "experts" => [
     "title" => "Eksperci i personel",
     "subtitle" => "Deweloperzy, utrzymanie i wsparcie",
],
     "total_save" => "Razem zaoszczędzone pieniądze",
],
     "SR-SeasonalPerformance" => [
     "title" => "Twój występ",
     "sub-title" => "Przegląd biznesowy od :początku do :koniec",
     "new_visitors" => "New Users",
     "returning_visitors" => "Zwróceni użytkownicy",
     "shop_views" => "Widoki sklepu",
     "baskets" => [
     "title" => "Wózki na zakupy",
     "subtitle" => "Zgłoś liczbę nowych koszyków",
],
     "products" => [
     "title" => "Przegląd produktów",
     "subtitle" => "Status produktów w sklepie według typu",
     "value_name" => "Produkty",
],
     "views" => [
     "title" => "Page Views",
     "subtitle" => "Całkowita liczba wyświetleń strony internetowej",
],
],
];