<?php 

 return [
     "invoice" => "Faktura",
     "serial" => "Numer seryjny.",
     "date" => "Data wystawienia faktury",
     "seller" => "Sprzedawca",
     "buyer" => "Kupujący",
     "address" => "adres",
     "code" => "Kod",
     "vat" => "Kod VAT",
     "phone" => "Telefon",
     "description" => "Opis",
     "units" => "Jednostki",
     "quantity" => "Ilość",
     "price" => "Cena",
     "discount" => "Zniżka",
     "tax" => "Podatek",
     "sub_total" => "Suma częściowa",
     "total_discount" => "Całkowity rabat",
     "taxable_amount" => "Kwota podlegająca opodatkowaniu",
     "total_taxes" => "Całkowite podatki",
     "tax_rate" => "Wysokość podatku",
     "total_amount" => "Całkowita kwota",
     "pay_until" => "Proszę zapłacić do",
     "amount_in_words" => "Kwota słownie",
     "amount_in_words_format" => "%s %s i %s %s",
     "notes" => "Uwagi",
     "shipping" => "Wysyłka",
     "paid" => "Płatny",
     "due" => "Należny",
];