<?php 

 return [
     "invoice" => "Faktura",
     "serial" => "Serie zk.",
     "date" => "Fakturaren data",
     "seller" => "Saltzailea",
     "buyer" => "Eroslea",
     "address" => "helbidea",
     "code" => "Kodea",
     "vat" => "BEZ kodea",
     "phone" => "Mugikorra",
     "description" => "Deskribapena",
     "units" => "Unitateak",
     "quantity" => "Kot",
     "price" => "prezioa",
     "discount" => "Deskontua",
     "tax" => "Zerga",
     "sub_total" => "Azpi totala",
     "total_discount" => "Deskontua osoa",
     "taxable_amount" => "Zerga-kopurua",
     "total_taxes" => "Zergak guztira",
     "tax_rate" => "Zerga-tasa",
     "total_amount" => "Kopuru osoa",
     "pay_until" => "Mesedez, ordaindu arte",
     "amount_in_words" => "Zenbatekoa hitzetan",
     "amount_in_words_format" => "%s %s eta %s %s",
     "notes" => "Oharrak",
     "shipping" => "Bidalketa",
     "paid" => "Ordaindua",
     "due" => "Ondorioz",
];