<?php 

 return [
     "invoice" => "Arve",
     "serial" => "Seerianumber.",
     "date" => "Arve kuupäev",
     "seller" => "Müüja",
     "buyer" => "Ostja",
     "address" => "aadress",
     "code" => "Kood",
     "vat" => "KMKR kood",
     "phone" => "Telefon",
     "description" => "Kirjeldus",
     "units" => "Ühikud",
     "quantity" => "Kogus",
     "price" => "hind",
     "discount" => "Allahindlus",
     "tax" => "Maksud",
     "sub_total" => "Vahesumma",
     "total_discount" => "Kogu allahindlus",
     "taxable_amount" => "Maksustatav summa",
     "total_taxes" => "Maksud kokku",
     "tax_rate" => "Maksumäär",
     "total_amount" => "Kogu summa",
     "pay_until" => "Palun tasuda kuni",
     "amount_in_words" => "Summa sõnades",
     "amount_in_words_format" => "%s %s ja %s %s",
     "notes" => "Märkmed",
     "shipping" => "Saatmine",
     "paid" => "Tasuline",
     "due" => "Tähtaeg",
];