<?php 

 return [
     "profile" => "Lugege profiiliteavet, sealhulgas nime, e-posti aadressi, pilti ja autentimise olekut.",
     "phone" => "Juurdepääs kontaktinumbrile",
     "address" => "Lugege ja muutke aadressi salvestatud aadressiraamatust",
     "buy" => "Tellimine ja tellimus poodi.",
     "order-history" => "Lugege tellimuste ajalugu.",
     "my-gift-cards" => "Access to my cards.",
     "articles" => "Redigeeri artikleid.",
     "notifications" => "Saatke ja võtke vastu teateid.",
     "read-shops" => "Lugege poe loendit.",
     "shop-edit" => "Poe muutmise juurdepääs.",
     "shop-contacts" => "Võtke vastu ja muutke kontaktivorme.",
     "shop-gift-cards" => "Kaartide loomine, redigeerimine ja haldamine.",
     "shop-faqs" => "Korduma kippuvate küsimuste loomine, muutmine ja haldamine.",
     "shop-categories" => "Kategooriate loomine, redigeerimine ja haldamine.",
     "shop-products" => "Toodete loomine, redigeerimine ja haldamine.",
     "shop-read-reports" => "Lugege teavet ja aruandeid.",
     "shop-socials" => "Muutke poe sotsiaalvõrgustikke.",
     "shop-accounts" => "Muutke ja kustutage kauplusega seotud finantskontosid.",
     "shop-menus" => "Muutke poe menüüsid.",
     "shop-pages" => "Muutke poe lehti.",
     "shop-warehouse" => "Redigeeri poe ladu",
     "shop-permissions" => "Poe juurdepääsu vaatamine ja muutmine.",
     "shop-process-center" => "Hallake saadud tellimusi.",
     "shop-profile" => "Kaupluste profiilide haldamine.",
     "shop-discount-code" => "Halda sooduskoode.",
     "shop-coupon" => "Kupongide haldamine.",
     "shop-offer" => "Pakkumiste haldamine.",
     "shop-lottery" => "Halda loteriisid.",
     "shop-community" => "Halda kogukonda.",
];