<?php 

 return [
     "home" => "solgt færdig",
     "blogs" => "Blog",
     "helps" => "Hjælp",
     "current_location" => "Denne post",
     "dashboard" => "dashboard",
     "my_shops" => "Mine butikker",
     "wallet" => "wallet",
     "about" => "Om Selldone",
     "contact" => "contact us",
     "comments" => "comments",
     "likes" => "Kan lide",
     "power" => "opmuntre",
     "build_free_shop" => "Byg din butik gratis",
     "shop_name" => "shop name",
     "categories" => "categories",
     "sub_articles" => "More",
     "terms" => "Vilkår",
     "colour" => "farve",
     "style" => "style",
     "volume" => "volume",
     "weight" => "weight",
     "pack" => "Pakke",
     "type" => "type",
     "add_to_card" => "Tilføj til kurv",
     "overview" => "Overview",
     "reviews" => "Anmeldelser",
     "spec" => "Fuld spec",
     "you_may_also_like" => "Du vil måske også syntes om",
     "about_us" => "Om os",
     "contact_us" => "contact us",
     "cookie_privacy" => "Cookie &amp; privacy policy",
     "follow_us" => "Følg os",
     "category" => "Kategori",
     "author" => "Written by ",
     "published_at" => "Udgivet kl",
     "modified_at" => "Ændret kl",
     "price" => "pris",
     "discount" => "Rabat",
     "price_after_discount" => "Pris efter rabat",
     "available" => "Ledig",
     "sold_out" => "Udsolgt",
     "buy" => "Køb nu",
     "login_shop" => "Log ind Shop",
     "posted_on" => "Udgivet den :date",
];