<?php 

 return [
     "profile" => "Læs profiloplysninger, herunder navn, e-mailadresse, billede og godkendelsesstatus.",
     "phone" => "Adgang til kontaktnummer",
     "address" => "Læs og rediger adresse fra gemt adressebog",
     "buy" => "Ordre & Shop Ordre.",
     "order-history" => "Læs ordrehistorik.",
     "my-gift-cards" => "Access to my cards.",
     "articles" => "Rediger artikler.",
     "notifications" => "Send og modtag notifikationer.",
     "read-shops" => "Læs butiksliste.",
     "shop-edit" => "Redigeringsadgang til butik.",
     "shop-contacts" => "Modtag og rediger kontaktformularer.",
     "shop-gift-cards" => "Oprettelse, redigering og administration af kort.",
     "shop-faqs" => "Opret, rediger og administrer ofte stillede spørgsmål.",
     "shop-categories" => "Oprettelse, redigering og administration af kategorier.",
     "shop-products" => "Oprettelse, redigering og administration af produkter.",
     "shop-read-reports" => "Læs information og rapporter.",
     "shop-socials" => "Rediger butiks sociale netværk.",
     "shop-accounts" => "Rediger og slet butikslinkede finansielle konti.",
     "shop-menus" => "Rediger butiksmenuer.",
     "shop-pages" => "Rediger butikssider.",
     "shop-warehouse" => "Rediger butikslager",
     "shop-permissions" => "Se og rediger butiksadgang.",
     "shop-process-center" => "Administrer modtagne ordrer.",
     "shop-profile" => "Administrer butiksprofiler.",
     "shop-discount-code" => "Administrer rabatkoder.",
     "shop-coupon" => "Administrer kuponer.",
     "shop-offer" => "Administrer tilbud.",
     "shop-lottery" => "Håndtere lotterier.",
     "shop-community" => "Administrer fællesskabet.",
];