<?php 

 return [
     "accepted" => "L'attribut : doit être accepté.",
     "accepted_if" => "Le champ :attribute doit être accepté lorsque :other est :value.",
     "active_url" => "L'attribut : n'est pas une URL valide.",
     "after" => "Le :attribut doit être une date après :date.",
     "after_or_equal" => "Le :attribut doit être une date postérieure ou égale à :date.",
     "alpha" => "L'attribut :ne peut contenir que des lettres.",
     "alpha_dash" => "L'attribut :ne peut contenir que des lettres, des chiffres et des tirets.",
     "alpha_num" => "L'attribut :ne peut contenir que des lettres et des chiffres.",
     "array" => "Le :attribut doit être un tableau.",
     "ascii" => "Le champ :attribute ne doit contenir que des caractères alphanumériques et des symboles sur un octet.",
     "before" => "Le :attribut doit être une date avant :date.",
     "before_or_equal" => "Le :attribut doit être une date antérieure ou égale à :date.",
     "between" => [
     "array" => "L'attribut : doit avoir entre : min et : max éléments.",
     "file" => "Le :attribut doit être compris entre :min et :max kilo-octets.",
     "numeric" => "Le :attribut doit être compris entre :min et :max.",
     "string" => "Le :attribut doit être compris entre :min et :max caractères.",
],
     "boolean" => "Le champ :attribute doit être vrai ou faux.",
     "can" => "Le champ :attribute contient une valeur non autorisée.",
     "confirmed" => "La confirmation :attribute ne correspond pas.",
     "contains" => "Le champ :attribute manque d'une valeur obligatoire.",
     "current_password" => "Le mot de passe est incorrect.",
     "date" => "L'attribut :n'est pas une date valide.",
     "date_equals" => "Le champ :attribute doit être une date égale à :date.",
     "date_format" => "Le :attribut ne correspond pas au format :format.",
     "decimal" => "Le champ :attribute doit avoir :decimal décimales.",
     "declined" => "Le champ :attribute doit être refusé.",
     "declined_if" => "Le champ :attribute doit être refusé lorsque :other est :value.",
     "different" => "Le :attribut et :autre doivent être différents.",
     "digits" => "Le :attribut doit être :chiffres chiffres.",
     "digits_between" => "Le :attribut doit être compris entre :min et :max chiffres.",
     "dimensions" => "L'attribut : a des dimensions d'image non valides.",
     "distinct" => "Le champ :attribute a une valeur en double.",
     "doesnt_end_with" => "Le champ :attribute ne doit pas se terminer par l’un des éléments suivants : :values.",
     "doesnt_start_with" => "Le champ :attribute ne doit pas commencer par l’un des éléments suivants : :values.",
     "email" => "L'attribut : doit être une adresse e-mail valide.",
     "ends_with" => "Le champ :attribute doit se terminer par l’un des éléments suivants : :values.",
     "enum" => "L'attribut : sélectionné n'est pas valide.",
     "exists" => "L'attribut : sélectionné n'est pas valide.",
     "extensions" => "Le champ :attribute doit avoir l'une des extensions suivantes : :values.",
     "file" => "Le :attribut doit être un fichier.",
     "filled" => "Le champ :attribute doit avoir une valeur.",
     "gt" => [
     "array" => "Le :attribute doit avoir plus de :éléments de valeur.",
     "file" => "Le :attribut doit être supérieur à :value kilo-octets.",
     "numeric" => "Le :attribut doit être supérieur à :valeur.",
     "string" => "Le :attribut doit être supérieur à :valeur caractères.",
],
     "gte" => [
     "array" => "Le :attribut doit avoir des éléments :value ou plus.",
     "file" => "Le :attribut doit être supérieur ou égal à :value kilo-octets.",
     "numeric" => "Le :attribut doit être supérieur ou égal à :valeur.",
     "string" => "Le :attribut doit être supérieur ou égal à :valeur caractères.",
],
     "hex_color" => "Le champ :attribute doit être une couleur hexadécimale valide.",
     "image" => "L'attribut : doit être une image.",
     "in" => "L'attribut : sélectionné n'est pas valide.",
     "in_array" => "Le champ :attribute n'existe pas dans :other.",
     "integer" => "L'attribut : doit être un entier.",
     "ip" => "L'attribut : doit être une adresse IP valide.",
     "ipv4" => "L'attribut : doit être une adresse IPv4 valide.",
     "ipv6" => "L'attribut : doit être une adresse IPv6 valide.",
     "json" => "L'attribut : doit être une chaîne JSON valide.",
     "list" => "Le champ :attribute doit être une liste.",
     "lowercase" => "Le champ :attribute doit être en minuscules.",
     "lt" => [
     "array" => "Le :attribut doit avoir moins de :value éléments.",
     "file" => "Le :attribut doit être inférieur à :value kilo-octets.",
     "numeric" => "Le :attribut doit être inférieur à :valeur.",
     "string" => "Le :attribut doit être inférieur à :valeur caractères.",
],
     "lte" => [
     "array" => "Le :attribute ne doit pas avoir plus de :éléments de valeur.",
     "file" => "Le :attribut doit être inférieur ou égal à :value kilo-octets.",
     "numeric" => "Le :attribut doit être inférieur ou égal à :valeur.",
     "string" => "Le :attribut doit être inférieur ou égal à :valeur caractères.",
],
     "mac_address" => "Le champ :attribute doit être une adresse MAC valide.",
     "max" => [
     "array" => "Le :attribut ne peut pas avoir plus de :max éléments.",
     "file" => "Le :attribut ne peut pas être supérieur à :max kilo-octets.",
     "numeric" => "Le :attribut ne peut pas être supérieur à :max.",
     "string" => "Le :attribut ne peut pas être supérieur à :max caractères.",
],
     "max_digits" => "Le champ :attribute ne doit pas contenir plus de :max chiffres.",
     "mimes" => "Le :attribute doit être un fichier de type : :values.",
     "mimetypes" => "Le :attribute doit être un fichier de type : :values.",
     "min" => [
     "array" => "Le :attribut doit avoir au moins :min éléments.",
     "file" => "L' :attribut doit être d'au moins :min kilo-octets.",
     "numeric" => "Le :attribut doit être au moins :min.",
     "string" => "Le :attribut doit contenir au moins :min caractères.",
],
     "min_digits" => "Le champ :attribute doit avoir au moins :min chiffres.",
     "missing" => "Le champ :attribute doit être manquant.",
     "missing_if" => "Le champ :attribute doit être manquant lorsque :other est :value.",
     "missing_unless" => "Le champ :attribute doit être manquant sauf si :other est :value.",
     "missing_with" => "Le champ :attribute doit être manquant lorsque :values est présent.",
     "missing_with_all" => "Le champ :attribute doit être manquant lorsque :values est présent.",
     "multiple_of" => "Le champ :attribute doit être un multiple de :value.",
     "not_in" => "L'attribut : sélectionné n'est pas valide.",
     "not_regex" => "Le format :attribut n'est pas valide.",
     "numeric" => "Le :attribut doit être un nombre.",
     "password" => [
     "letters" => "Le champ :attribute doit contenir au moins une lettre.",
     "mixed" => "Le champ :attribute doit contenir au moins une lettre majuscule et une lettre minuscule.",
     "numbers" => "Le champ :attribute doit contenir au moins un nombre.",
     "symbols" => "Le champ :attribute doit contenir au moins un symbole.",
     "uncompromised" => "L'attribut :attribute donné est apparu dans une fuite de données. Veuillez choisir un autre :attribute.",
],
     "present" => "Le champ :attribut doit être présent.",
     "present_if" => "Le champ :attribute doit être présent lorsque :other est :value.",
     "present_unless" => "Le champ :attribute doit être présent sauf si :other est :value.",
     "present_with" => "Le champ :attribute doit être présent lorsque :values est présent.",
     "present_with_all" => "Le champ :attribute doit être présent lorsque :values est présent.",
     "prohibited" => "Le champ :attribute est interdit.",
     "prohibited_if" => "Le champ :attribute est interdit lorsque :other est :value.",
     "prohibited_unless" => "Le champ :attribute est interdit sauf si :other est dans :values.",
     "prohibits" => "Le champ :attribute interdit à :other d'être présent.",
     "regex" => "Le format :attribut n'est pas valide.",
     "required" => "Le champ :attribut est obligatoire.",
     "required_array_keys" => "Le champ :attribute doit contenir des entrées pour : :values.",
     "required_if" => "Le champ :attribute est obligatoire lorsque :other vaut :value.",
     "required_if_accepted" => "Le champ :attribute est obligatoire lorsque :other est accepté.",
     "required_if_declined" => "Le champ :attribute est obligatoire lorsque :other est refusé.",
     "required_unless" => "Le champ :attribute est obligatoire sauf si :other est dans :values.",
     "required_with" => "Le champ :attribute est obligatoire lorsque :values est présent.",
     "required_with_all" => "Le champ :attribute est obligatoire lorsque :values est présent.",
     "required_without" => "Le champ :attribute est obligatoire lorsque :values n'est pas présent.",
     "required_without_all" => "Le champ :attribute est obligatoire lorsqu'aucune des :valeurs n'est présente.",
     "same" => "Le :attribut et :autre doivent correspondre.",
     "size" => [
     "array" => "L'attribut : doit contenir des éléments :size.",
     "file" => "Le :attribut doit être :size kilo-octets.",
     "numeric" => "Le :attribut doit être :size.",
     "string" => "L'attribut : doit contenir des caractères :size.",
],
     "starts_with" => "Le champ :attribute doit commencer par l’un des éléments suivants : :values.",
     "string" => "Le :attribut doit être une chaîne.",
     "timezone" => "L'attribut : doit être une zone valide.",
     "unique" => "L'attribut :a déjà été pris.",
     "uploaded" => "L':attribut n'a pas pu être téléchargé.",
     "uppercase" => "Le champ :attribute doit être en majuscules.",
     "url" => "Le format :attribut n'est pas valide.",
     "ulid" => "Le champ :attribute doit être un ULID valide.",
     "uuid" => "Le champ :attribute doit être un UUID valide.",
     "custom" => [
     "attribute-name" => [
     "rule-name" => "message personnalisé",
],
     "g-recaptcha-response" => [
     "required" => "Veuillez vérifier que vous n'êtes pas un robot.",
     "captcha" => "Erreur CAPTCHA! réessayez plus tard ou contactez l'administrateur du site.",
],
],
     "attributes" => [
        
     ],
];