<?php 

 return [
     "email-types" => [
        [
     "title" => "Oda ya tabbatar da mai siye",
],
        [
     "title" => "Tabbatar da biyan kuɗi na abokin ciniki",
],
        [
     "title" => "Oda sanarwar tabbatarwa ga mai siyarwa",
],
        [
     "title" => "Tabbatar da odar akwatin ajiya don mai siye",
],
        [
     "title" => "Tabbatar da biyan kuɗin rajistar kuɗi don mai siye",
],
        [
     "title" => "Sanarwa na siyan a cikin akwatin mai siyarwa",
],
        [
     "title" => "Sanar da hanyar tuntuɓar",
],
        [
     "title" => "Barka da shiga kantin",
],
        [
     "title" => "Sanarwa na karɓar katin kyauta ga mai amfani",
]
     ],
     "global" => [
     "greetings" => "Hi: suna",
     "end-statement" => "Taimako tawagar",
     "receiver_name" => "Barka dai :user_name",
     "footer-help" => "Kuna buƙatar taimako? Tambayi a [support@sellone.com](mailto:support@sellone.com) ko ziyarci [cibiyar taimako](https://seldone.com/help)",
     "footer-shop" => "Idan kuna buƙatar taimako da wani abu don Allah kar a yi shakka a aiko mana da imel:shop_mail",
     "accept" => "Karba",
     "reject" => "Ƙi",
     "verify" => "tabbatar",
     "title" => "Take",
     "value" => "Daraja",
     "description" => "Bayani",
     "Shop" => "Shago",
     "user" => "mai amfani",
     "license" => "Lasisi",
     "status" => "Matsayi",
     "start" => "Fara",
     "end" => "Ƙarshe",
     "renewal" => "Sabuntawa",
     "view" => "Duba",
     "balance" => "Ma'auni",
     "card_number" => "Lambar kati",
     "cvv" => "CV",
     "expire_date" => "Ranar ƙarewa",
     "dashboard" => "dashboard",
     "order" => "oda",
     "view_order" => "Duba oda",
     "pay_now" => "Pay now",
     "official_selldone" => "SIYAR DA HUKUNCI",
     "account-number" => "Account number",
     "account-name" => "Account name",
     "currency" => "Kuɗi",
     "free-balance" => "Ma'auni kyauta",
     "locked-balance" => "Ma'auni mai kulle",
     "bot" => "Bot",
     "requests" => "Bukatu",
     "baskets" => "Katuna",
     "physical" => "Na zahiri",
     "virtual" => "Na gani",
     "file" => "Fayil",
     "service" => "Sabis",
     "fulfillment" => "Cika",
     "open" => "Bude",
     "reserved" => "Ajiye",
     "canceled" => "An soke",
     "payed" => "An biya",
     "cod" => "COD",
     "orders-count" => "Umarni",
     "payments-count" => "Biyan kuɗi",
     "confirms-count" => "Ya tabbatar",
     "sends-count" => "Aika",
     "delivers-count" => "Bayarwa",
     "count" => "Ƙidaya",
     "transactions-count" => "Ma'amaloli suna ƙidaya",
     "success-transactions" => "Cin nasara ma'amaloli",
     "total-amount" => "Jimla",
     "amount" => "Adadin",
     "wage" => "Albashi",
     "debug" => "Gyara kuskure",
     "pos" => "POS",
     "live" => "Rayuwa",
     "CheckQueue" => "Duba jerin gwano",
     "OrderConfirm" => "Tabbatar da oda",
     "PreparingOrder" => "Ana shirya oda",
     "SentOrder" => "An aika oda",
     "ToCustomer" => "Bayar da abokin ciniki",
     "Pending" => "Ana jiran",
     "Accepted" => "Karba",
     "Rejected" => "An ƙi",
     "pc" => "PC",
     "tablet" => "Tablet",
     "phone" => "Waya",
     "total" => "Jimlar",
     "view-detail" => "Duba cikakken bayani",
     "empty" => "Babu komai",
     "dropshipping" => "Dropshipping",
     "reply" => "Amsa",
     "reactions" => "Martani",
     "comments" => "sharhi",
     "last-comment" => "Sharhi na ƙarshe",
     "response-to" => "Martani ga",
     "posts" => "Posts",
     "post" => "Buga",
     "name" => "Suna",
     "email" => "Imel",
     "type" => "nau'in",
     "device" => "Na'ura",
     "platform" => "Dandalin",
     "browser" => "Browser",
     "time" => "Lokaci",
     "wallet" => "walat",
     "date" => "Kwanan wata",
     "account" => "Asusu",
     "transaction" => "Ma'amala",
     "fee" => "Kudin",
     "location" => "Location",
     "ip" => "Ip",
     "bill" => "Bill",
     "category" => "Rukuni",
     "password" => "Kalmar wucewa",
     "shop" => "Shago",
     "verify-login" => "Tabbatar & Shiga",
     "url" => "URL",
     "avocado" => "Avocado",
     "hyper" => "Hyper",
     "buy-now" => "Saya yanzu",
     "add-domain" => "Add Domain",
     "views" => "Ra'ayi",
     "country" => "Ƙasa",
     "address" => "adireshin",
     "postal" => "Lambar gidan waya",
     "building_no" => "Gina #",
     "building_unit" => "Naúrar #",
     "message" => "Sako",
     "customer" => "Abokin ciniki",
     "cart-items" => "Kayan kwalliya",
     "payment" => "Biya",
     "receiver" => "Mai karɓa",
     "virtual-items" => "Abubuwa na zahiri",
     "no-payment" => "Babu biya!",
],
     "selldone-business-os" => "Siyar da Kasuwancin OS",
     "senders" => [
     "WeeklyReport" => [
     "id" => "performance",
     "name" => "Rahoton Ayyuka, Selldone",
],
     "SeasonalReport" => [
     "id" => "seasonal",
     "name" => "Rahoton Yanayi, Selldone",
],
     "Onboarding" => [
     "id" => "sannu",
     "name" => "Ƙungiyar Selldone",
],
     "Support" => [
     "id" => "support",
     "name" => "Support :name",
],
     "EmailVerify" => [
     "id" => "verify",
     "name" => "Tabbatar, Selldone",
],
     "Welcome" => [
     "id" => "sannu",
     "name" => "Al'umma, Selldone",
],
     "NewShop" => [
     "id" => "yan kasuwa",
     "name" => "Yan kasuwa, Selldone",
],
     "Approve" => [
     "id" => "yarda",
     "name" => "Amincewa, Selldone",
],
     "SellerReceiveOrder" => [
     "id" => "order",
     "name" => "Gudanar da umarni: suna",
],
     "Recovery" => [
     "id" => "farfadowa",
     "name" => "Tawagar farfadowa da Selldone",
],
],
     "bill-status" => [
     "PENDING" => "Mai jiran gado",
     "PAYED" => "An biya ✅",
     "CANCELED" => "An soke ❌",
],
     "shop-invite" => [
     "LEVEL-NAME" => [
     "ADMIN" => "Mai gudanarwa",
     "OFFICER" => "Jami'i kuma mai kulawa",
     "AUDITING" => "Manajan binciken",
     "EMPLOYEE" => "Ma'aikaci",
     "PRODUCT" => "Mai sarrafa kayayyaki",
     "CONTENT" => "Manajan abun ciki",
     "MARKETING" => "Manajan tallace-tallace",
     "VIEWER" => "Mai kallo",
],
     "subject" => ":mai gayyatar Gayyatar ku a matsayin :level | : kantin",
     "category" => "Gayyatar ma'aikata",
     "title" => "An gayyace ku zuwa <b>:shop_name</b> as <b>:level</b> .",
     "message" => "An aika maka gayyata. Kuna iya tabbatarwa ko ƙin yarda da shi. Idan wannan gayyatar ta sami amincewa da ku, dole ne ku shigar da sabis ɗin Selldone don tabbatar da ita. Ta hanyar tabbatar da wannan gayyata, zaku sami damar zuwa sashin sarrafa kantin.",
],
     "welcome-email" => [
     "subject" => "👋 Barka da zuwa :name, Wasu abubuwa masu ban sha'awa a gare ku kawai.",
     "category" => "CONGRATULATION",
     "title" => "BARKANMU DA SALLAH",
     "message" => "Na gode don zaɓar Selldone, Yanzu kun kasance wani ɓangare na al'ummar Selldone wanda ke haɗa masu siyar da kayayyaki na duniya zuwa abokan ciniki, Kasuwancin gida zuwa kasuwanci, Mutum ga kamfani! An ba da duk kayan aikin master da pro ** kyauta *** da ** marasa iyaka ** a gare ku. Kuna gwada, muna buɗe kofofin, Kawai Yi!",
     "seller" => [
     "title" => "Kai mai sayarwa ne?",
     "message" => "Don fara siyarwa, shigar da dashboard ɗinku a cikin Selldone ta hanyar mahaɗin da ke ƙasa kuma ƙirƙirar kantin sayar da ku na farko gabaɗaya kyauta. Wannan zai ɗauki 'yan mintoci kaɗan kuma za ku sami kantin sayar da ku da gidan yanar gizon ku. Sannan za mu jagorance ku zuwa matakai na gaba kuma mu sami ƙofar biyan kuɗi.",
     "action" => "Shiga dashboard dina",
],
     "buyer" => [
     "title" => "Ni mai saye ne",
     "message" => "Ina taya ku murna. Da zarar kun kasance memba na Selldone, za ku kawar da duk wahalhalun kasancewa memba da tabbatarwa a cikin shagunan kan layi. Don amfana daga kowane shago da rukunin yanar gizon da ke amfani da dandalin Selldone, zaku iya shiga tare da dannawa ɗaya kuma ku sanya siyan ku mai sauƙi, sauri da aminci.",
],
],
     "charge-account" => [
     "category" => "Wallet > Account > Caji",
     "title" => "Cajin Nasara",
     "message" => "An yi nasarar caje asusun ku <b>:account_number</b> <b>: adadin</b> da aka caje.",
     "account" => "Asusu",
     "charge" => "Caji",
     "balance" => "Ma'auni",
     "footer" => "Sanya kasuwanci cikin sauƙi, mai yiwuwa, kuma mai isa ga kowa a duniya.",
],
     "verify-email" => [
     "subject" => "🙌 Cika rajistar ku zuwa Selldone! Tabbatar da hanyar haɗin gwiwa.",
     "category" => "KAINE MATAKI DAYA",
     "title" => "Tabbatar da adireshin imel ɗin ku",
     "message" => "Hi :name,<br> Na gode don zaɓar Selldone.<br> Da fatan za a tabbatar da cewa **:email** shine adireshin imel ɗin ku ta danna maballin ko amfani da hanyar haɗin da ke ƙasa cikin awanni 48.",
     "footer" => "Idan kuna fuskantar matsala ta danna maɓallin Tabbatarwa, kwafi kuma liƙa URL ɗin da ke ƙasa cikin mazuruftan gidan yanar gizon ku: __:activation_url__",
],
     "verify-email-code" => [
     "subject" => "Lambar tabbatarwa don :name",
     "category" => "SECURITY",
     "title" => "Lambar tabbatarwa ta imel",
     "message" => "Hi :name,<br><br> Da fatan za a tabbatar da cewa **:email** shine adireshin imel ɗin ku ta wannan lambar a cikin mintuna 10.",
],
     "onboarding-verify-email" => [
     "subject" => "🎉 Shagon Ku Ya Shirya | : suna",
     "category" => "KAINE MATAKI DAYA",
     "title" => "An gama saitin",
     "account_title" => "Asusun ku",
     "account_msg" => "Tabbatar da shiga cikin asusunku tare da wannan bayanin.",
     "shop_msg" => "Bayanin asusu akan tsarin kasuwancin Selldone.",
],
     "reset2fa" => [
     "category" => "SAKON TSARO",
     "title" => "Neman musaki shiga matakai biyu",
     "message" => "Kuna karɓar wannan imel ɗin saboda mun sami buƙatun sake saitin tantance abubuwa biyu don asusunku.<br><br> Imel mai amfani: <b>:email</b><br> Name: <b>:suna</b>",
     "footer" => "Idan baku nemi sake saitin kalmar sirri ba, ba a buƙatar ƙarin wani mataki.",
     "action" => "Kashe shiga ta mataki biyu",
],
     "build-new-shop" => [
     "subject" => "🎊 Shagon ku yana shirye yanzu!",
     "category" => "HAIHUWA NEW ONLINE Store A DUNIYA",
     "title" => "Biki",
     "message" => "<b>Taya murna :name, kun ƙirƙiri sabon kasuwancin kan layi;</b> Muna yi muku fatan nasara a kasuwancin ku. Barka da zuwa jama'ar Selldoners.<br> Kuna gwada, mun buɗe kofofin, kuma kun yi.",
     "pdf-book" => "Kar a rasa littafin hannu da aka makala: Yi Kasuwancin ku Kamar Wasan",
     "account" => [
     "title" => "Mataki 1: Ƙirƙiri asusu a cikin walat ɗin Selldone",
     "message" => "Idan ba ku da asusu a cikin walat ɗin ku, ƙirƙira ɗaya. Selldone yana cire kuɗin daga wannan asusun. Kuna iya cika wannan asusun, kuma Selldone kuma zai caje ku adadin kuɗi ta yadda idan wannan asusun ba shi da kyau, rukunin yanar gizonku da Store ɗinku za su ci gaba da aiki.",
     "action" => "Shiga cikin walat",
],
     "shop-account" => [
     "title" => "Mataki 2: haɗa asusun zuwa kantin sayar da",
     "message" => "Ƙara asusun ajiyar ku zuwa kantin sayar da ku. Don yin wannan, shigar da Store> Accounting> Invoice kuma haɗa asusun zuwa shagon. Lura cewa duk biyan kuɗin abokan cinikin ku ana saka su kai tsaye cikin asusun banki kuma babu wani adadin da Selldone ya cire ko cirewa, don haka kuna buƙatar haɗa wannan asusun na Selldone zuwa kantin sayar da.",
     "action" => "Ajiye daftari Panel",
],
     "gateway" => [
     "title" => "Mataki 3: Haɗa Ƙofar Biyan Kan layi",
     "message" => "Je zuwa Store> Accounting> Port kuma latsa <b>Add New Port</b> . Bayan zabar kudin, za a nuna maka jerin tashoshin jiragen ruwa masu ɗaukar nauyi. Haɗa tashar jiragen ruwa a cikin Selldone abu ne mai sauƙi kuma mai sauri, amma idan kuna da Niza don jagora, koma zuwa sashin jagorar Selldone ko tambaye mu.",
     "action" => "Ƙara portal zuwa shagon",
],
     "domain" => [
     "title" => "Mataki na ƙarshe: haɗa yanki mai kwazo",
     "message" => "Za ku iya samun kantin sayar da ku akan yawancin yankuna kamar yadda kuke so. Don haɗa yanki da aka keɓe zuwa shago, kuna buƙatar samun aƙalla lasisin farawa. Ta hanyar gabatar da kowane aboki zuwa Selldone, zaku karɓi katin kyautar lasisin farawa na wata ɗaya. Hakanan za a ƙididdige kaso na kuɗin abokan ku zuwa asusun abokan cinikin ku.",
     "action" => "Gabatarwa da karɓar katunan kyauta marasa iyaka",
],
],
     "basket-list" => [
     "item" => "abu",
     "count" => "Ƙidaya",
     "price" => "farashin",
     "discount-code" => "Lambar rangwame",
     "customer-club" => "Ƙungiyar Abokin Ciniki",
     "shipping" => "Jirgin ruwa",
     "total" => "Jimlar",
     "offer" => "Bayar",
     "coupon" => "Copon",
     "lottery" => "Kyauta",
     "tax" => "Haraji",
     "tax_included" => "Kunshe cikin farashi",
     "tax_shipping" => "Shipping Tax",
],
     "buyable-payments" => [
     "method" => "Hanya",
     "amount" => "Adadin",
     "giftcard" => "Gift card",
     "payment" => "Biya",
],
     "shop-subscription-email" => [
     "category" => "Sabunta biyan kuɗi",
     "title" => "Lasisin shago: :shop_title",
     "title-reserved" => "Lasin ajiyar kuɗi: :shop_title",
     "title-active" => "Lasisi mai aiki: :shop_title",
     "title-finished" => "Ƙarshen lasisi: :shop_title",
     "title-cancel" => "Soke lasisi: :shop_title",
     "message" => "An sabunta tsarin lasisin kantin ku,",
     "RESERVED" => "⚡ An ajiye tsarin biyan kuɗin ku **.",
     "ACTIVE" => "🟢 An kunna tsarin biyan kuɗin ku ** kunna**.",
     "FINISHED" => "🚧 An gama shirin biyan kuɗin ku **.",
     "CANCEL" => "⛔ An soke tsarin biyan kuɗin ku **.",
],
     "support" => [
     "subject" => "Cibiyar Tallafawa | :suna amsa",
     "category" => "Cibiyar tallafi",
     "title" => "Kun sami amsa",
     "action" => "Bude admin kantin",
],
     "shop-customer-join" => [
     "subject" => "Shiga :shop_title",
     "category" => "Sabuwar bikin abokin ciniki",
     "title" => "Muna farin ciki da kasancewar ku",
     "action" => "Ziyarci yanzu",
],
     "shop-giftcard" => [
     "subject" => "Katin kyauta: shop_title",
     "category" => "Ƙara sabon kati",
     "title" => "Taya murna, kun karɓi katin kyauta",
     "action" => "Siyayya yanzu",
     "message" => "Kun karɓi katin kyauta a cikin adadin :balance :currency. Zaku iya siya daga shagonmu da wannan katin kyauta.",
],
     "contact" => [
     "subject" => "Cibiyar Tallafawa | : kantin",
     "category" => "goyon baya",
     "title" => "Kun sami amsa",
],
     "order-checkout" => [
     "subject" => "🛍 oda Checkout | : order_id",
     "title" => "oda",
     "message" => "Odar ku ta tabbatar,<br> Mun sami odar ku. Za mu sake jefar da ku wani imel lokacin da odar ku ta tashi.",
     "payments" => "Biyan kuɗi",
],
     "order-payment" => [
     "subject" => "🛍 Tabbatar da Biyan Kuɗi | : order_id",
     "title" => "Odar biyan kuɗi",
     "message" => "An kammala biyan ku,<br> Mun sami odar ku. Za mu sake jefar da ku wani imel lokacin da odar ku ta tashi.",
     "payments" => "Biyan kuɗi",
],
     "get-voucher" => [
     "subject" => "Taya murna :name | Sabuwar baucan: :title",
     "category" => "TAYA TAYA, SABON BAUCHI",
     "message" => "Kuna samun sabon baucan, Wannan kyauta ce daga gare mu a gare ku. Kuna iya samun ƙarin daga waɗannan takaddun ta hanyar gabatar da Selldone ga abokai da duk wanda kuka sani. Wannan baucan yana da daraja **:farashin: kuɗaɗe**.<br> Kuna gwada, muna buɗe kofofin, Taya murna, Buɗe fasali ta baucan ku!",
     "action" => "Dashboard na",
],
     "received-gift" => [
     "subject" => "Taya murna, Dear :name | Kun karɓi kyauta",
     "category" => "Sanarwa na samun kyauta",
     "title" => "Gifts gare ku",
     "message" => "Kun karɓi sabuwar kyauta. Wannan kyauta ce daga Selldone. Kuna iya karɓar ƙarin waɗannan kyaututtukan ta hanyar yin aiki sosai a cikin Selldone da haɓaka kantin sayar da ku da haɓaka matakin ƙwarewar ku. Wannan darajar Kyauta ita ce **: farashin: kuɗaɗe ** wanda zaku iya saka kai tsaye a cikin walat ɗin ku a cikin siyarwa.<br><br> Yi amfani da wannan kyauta don haɓaka lasisin kantin sayar da ku da kuma amfani da ƙarin kayan aiki a cikin kasuwancin ku na kan layi.",
     "action" => "Kyauta",
],
     "order-payment-admin" => [
     "subject" => "🛍 An Karɓi Sabon Umarni | : order_id",
     "title" => "New Order",
     "message" => "Kun karɓi sabon oda. Da fatan za a je shafin sarrafa oda a cikin shagon ku.",
],
     "virtual-item" => [
     "input-form-title" => "Cikakkun Bayananku",
     "output-form-title" => "Bayanan abu da aka saya",
],
     "selldone-weekly-report" => [
     "subject" => "📬 : shop_title | Rahoton mako: lokaci",
     "title" => "Rahoton aikin kantin mako-mako",
     "message" => "Wannan shine rahoton kantin ku na mako-mako daga :fara zuwa :karshe. Wannan rahoton ya ƙunshi shawarwari don inganta kasuwancin ku, kuna iya bincika matsayin kantin sayar da kan layi da umarni na baya-bayan nan. Ina fatan kuna da rana mai kyau da mako mai zuwa.",
],
     "shop-seasonal-report" => [
     "subject" => "☘ Rahoton ajiyar ku na adadin a cikin watanni uku da suka gabata | : shop_title",
     "title" => "Rahoton lokaci game da ayyukan kasuwancin ku, lada da ajiyar kuɗi",
     "message" => "Wannan shine rahoton ku na yanayi na :shop_title daga :fara zuwa :karshe.",
],
     "EC-ShopAccounts" => [
     "title" => "Asusun da aka haɗa",
     "sub-title" => "Menene sabon matsayi na asusun walat ɗin da aka haɗa da kantina?",
     "view-wallet" => "Duba walat",
     "tip-title" => "Muhimman shawarwari",
     "tip" => "A mataki na gaba, ƙirƙirar asusun kyauta a cikin walat ɗin Selldone ɗin ku kuma haɗa shi zuwa wannan kantin. Ko da ma'aunin asusun Selldone ɗinku mara kyau ne, abokan cinikin ku har yanzu suna iya yin sayayya da biya don kantin sayar da ku ba tare da wata matsala ba. Ba za a katse bayananku da sabis ɗinku ko ƙuntatawa na akalla wata 1 ba.",
     "view-my-wallet" => "My wallet",
     "connect-account" => "Haɗa zuwa lissafi",
],
     "EC-ShopApps" => [
     "title" => "An shigar da apps",
     "sub-title" => "Jerin aikace-aikacen da kuka shigar a cikin kantin sayar da ku a wannan makon.",
     "tip" => "Kuna son nemo ƙarin ƙa'idodi don kantin sayar da ku?",
     "view-app-store" => "Ziyarci Shagon Selldone App Store..",
],
     "EC-ShopBots" => [
     "title" => "Bots Store ɗinku",
     "sub-title" => "Bots tallace-tallace masu aiki a cikin shagona.",
     "tip-title" => "Bot Sale",
     "tip" => "Selldone ya samar muku da bots tallace-tallace ta atomatik. Abin da kawai za ku yi shi ne je zuwa Add-ons> Bots panel kuma kunna bots ɗin kantin ku. Lura cewa sabis ɗin da ya dace dole ne ya kasance a cikin ƙasar ku.",
     "view-bots" => "Sarrafa bots",
],
     "EC-ShopContacts" => [
     "title" => "Sadarwa tare da Abokan ciniki",
     "sub-title" => "Abokan hulɗa nawa na yi da abokan cinikina a wannan makon?",
     "faqs" => "Tambayoyin da ake yawan yi",
     "tickets" => "Tikitin abokin ciniki",
],
     "EC-ShopData" => [
     "title" => "Matsayin masu amfani",
     "sub-title" => "Daga kwanan wata :fara zuwa :ƙarshe",
     "users" => [
     "title" => "Abokan ciniki",
     "subtitle" => "Masu Amfani",
],
     "views" => [
     "title" => "Ziyara",
     "subtitle" => "Sau nawa ka ziyarci kantin",
],
     "new_visitors" => "New Users",
     "returning_visitors" => "Masu amfani da aka dawo",
     "shop_views" => "Kayayyakin Kayayyakin kallo",
     "baskets" => [
     "title" => "Kasuwancin Siyayya",
     "subtitle" => "Bayar da rahoton adadin sabbin motocin sayayya",
],
     "products" => [
     "title" => "Bayanin Samfura",
     "subtitle" => "Matsayin samfurori a cikin shagon ta nau'in",
     "value_name" => "Kayayyaki",
],
     "products_count" => "Nau'in samfur",
     "views_count" => "Duba ƙidaya",
     "sell_count" => "Ƙididdiga na siyarwa",
     "send_count" => "Ƙididdigar jigilar kaya",
],
     "EC-ShopDropShipping" => [
     "title" => "Ajiye jigilar kaya",
     "sub-title" => "Panel don manyan masu siyar da Drop Shipping Selldone.",
     "total_fulfillments" => "Jimillar oda da aka karɓa",
     "ds_count" => "An Karɓi Umarni",
     "statistics_title" => "Rahoton da aka samu oda",
     "ds_cancels" => "Soke ta mai siyar da kayan masarufi",
     "ds_rejects" => "Soke ta Kai",
     "tip" => "Shin kai babban mai siyar da kaya ne? Kuna mallaki wurin ajiya, masana'anta ko mai rarraba kayayyaki? Kuna iya ba da samfuran ku ga sauran masu siyarwa a cikin sabis ɗin jigilar kaya na Selldone don siyar da samfuran ku akan babban sikeli. Yi mana imel a support@sellone.com don jagorance ku.",
     "view-drop-shipping-panel" => "Shiga zuwa babban kwamiti na wholesale",
],
     "EC-ShopExchangeRates" => [
     "title" => "Darajar musayar kudi",
     "sub-title" => "Jerin sabbin farashin canjin kuɗi a cikin shagon ku.",
     "from" => "Tushen Currency",
     "to" => "Kuɗin makoma",
     "rate" => "Yawan tuba",
     "vew-exchange-panel" => "canjin kudi management panel",
],
     "EC-ShopExperts" => [
     "title" => "Kwangilolin masana",
     "sub-title" => "Wadanne kwararru ne ke aiki a kantina?",
     "cost" => "Adadin kwangila",
     "duration" => "Tsawon lokaci",
     "start_at" => "Start Date",
     "complete_at" => "Completion Date",
     "cancel_at" => "Kwanan wata Soke",
     "end_at" => "Ranar bayarwa",
     "tip" => "Kuna iya hayar ƙwararrun ƙwararru a cikin Selldone don haɓaka kasuwancin ku.",
     "view-experts" => "Danna don farawa.",
],
     "EC-ShopGateways" => [
     "title" => "Payment gateways",
     "sub-title" => "Bayar da ƙofofin biyan kuɗi masu aiki akan shago: shago.",
     "tip-title" => "Muhimman shawarwari",
     "tip" => "Jeka shafin sarrafa tashar yanar gizo a cikin kantin sayar da ku kuma ƙara aƙalla tashar jiragen ruwa guda ɗaya a cikin 'yan mintuna kaɗan. Abokan cinikin ku suna son biyan kuɗi cikin sauri da aminci ta hanyoyin yanar gizo.",
     "view-shop-gateways" => "Shiga cikin sarrafa tashar tashar kantina.",
     "view-gateways" => "Duba ƙarin ƙofofin",
],
     "EC-ShopOrders" => [
     "title" => "Umarni",
     "sub-title" => "Jerin umarni da na samu a wannan makon.",
     "total_baskets" => "Jimlar oda",
     "total_posBaskets" => "Jimlar odar Kuɗi",
     "pos-title" => "Akwatin Shagon POS",
     "chart-label" => "An kammala oda (waɗannan umarni ba lallai ba ne a biya su!)",
     "tip-title" => "Yakamata ka kara kokari...",
     "tip" => "Babu nasara mai sauƙi.",
],
     "EC-ShopProcessCenter" => [
     "title" => "Cibiyar sarrafawa",
     "sub-title" => "Nawa muka aiwatar a cikin kantin wannan makon?",
     "tip-title" => "Ba ku da siyarwa!",
     "tip" => "Abin takaici ba ku da wani tallace-tallace a wannan makon. Kuna buƙatar samun ƙarin zuwa kantin sayar da ku. Kuna iya ƙara ƙarin samfura, zaɓi mafi kyawun hotuna ko rubuta mafi kyawun kwatance don samfuran ku. Yi la'akari da aikin cikakken lokaci don kasuwancin ku. Idan kun yi daidai kuma ba ku yi takaici ba, za ku yi nasara.",
     "view-process-center" => "Duba cibiyar aiwatarwa",
     "return" => [
     "title" => "Oda da aka dawo",
     "subtitle" => "Rahoton da aka dawo da oda.",
     "tip-title" => "Ko kun san cewa...",
     "tip" => "Kuna iya ƙirƙirar rajistar tsabar kuɗi da yawa kamar yadda kuke so ta hanyar Selldone POS! A zahiri, zaku iya juya kwamfutar hannu, wayar hannu ko kwamfutar tafi-da-gidanka zuwa akwatin saƙon saƙo na ku. Idan hakan ya burge ku, Selldone POS abu ne da yakamata ku fara amfani dashi yanzu. Yana ɗaukar sauƙi mai sauƙi don ƙaddamarwa, muna da duk abin da aka shirya don sabar ku a gaba.",
     "view-pos" => "Shiga cikin Kasuwar Kan layi Na",
],
],
     "EC-ShopSessions" => [
     "title" => "Zama",
     "sub-title" => "Sau nawa na ziyarci kantina?",
     "countries-title" => "Wadanne kasashe ne aka fi ziyarta?",
],
     "EC-PublicMessage" => [
     "title" => "Kuna so ku sami kuɗi ba tare da kashe kuɗi ɗaya ba?",
     "message" => "Dear :name, za ku iya zuwa Dashboard> Demonetization kuma ƙirƙirar hanyar haɗi. Aika hanyar haɗi zuwa abokanka, Kuna karɓar katunan kyauta na Selldone da kashi ɗaya na biyan kuɗin abokin ku. Lura cewa za a aika da katin kyauta ga ku da abokin ku.",
     "action" => "Duba mahaɗin gabatarwa na",
     "mail-clip" => "<b style='color: #C2185B'>Muhimmi:</b> Idan kuna amfani da sabis na imel kamar Gmail waɗanda ke iyakance tsawon imel ɗin, nemo zaɓi mai zuwa a ƙarshen imel ɗin don nuna cikakken rahoton kuma danna shi:",
     "no-coin-reward" => "<b style='color: #C2185B'>Yi haƙuri:</b> Ayyukanku bai cika buƙatun don samun ladan SEL Coins kyauta ba. Yi ƙoƙari sosai kuma ku sayar da ƙarin akan shagon ku don kakar wasa ta gaba.",
     "yes-coin-reward" => "<b style='color: #4CAF50'>Kyauta:</b> Taya murna, saboda kyakkyawan aikin da kuka yi, mun ba ku kyauta : adadin SEL Coin kyauta.",
     "need-buy-license" => "<b>Haɓaka kasuwancin ku:</b> Ba ku yi rajistar kowane tsarin biyan kuɗi don gidan yanar gizon kasuwancin ku ba! Don haka lokaci ya yi da za a saya aƙalla biyan kuɗi ɗaya. Kudinsa kawai: adadin kowane wata don siyan shekara.",
     "not-afford-message" => "Idan ba za ku iya samun kuɗi ko samun matsala tare da biyan kuɗi ba, jin daɗin faɗa mana ta support@sellone.com.",
     "add-domain" => "<b>Me yasa ba ku da yankin al'ada don kasuwancin ku?</b><br> Ƙara yanki zuwa gidan yanar gizon ku yanzu; kyauta ne!",
],
     "Widget-Socials" => [
     "title" => "Selldone shine a<del> samfur</del> <span style = 'color: forestgreen'>al'umma</span> .<br> Kasance ƙwararren Mai siyarwa!",
     "message" => "Bi shafukan hukuma na Selldone akan Twitter, LinkedIn da hanyoyin sadarwar zamantakewa. Aiko mana da duk wani sharhi, buƙatu ko zargi ko shiga cikin tattaunawa game da Selldone. Mu kuma wani bangare ne na al'ummar Selldone da <b>kuke yi</b> .",
],
     "avocado-seller-daily-report" => [
     "subject" => "An karɓi sabbin odar Avocado | : shop_title :lokaci",
     "title" => "Rahoton aiki na awa 24 da suka gabata",
     "message" => "Abokan cinikin ku suna jiran a sake duba odar ku da farashi. Amsa ga buƙatun abokan cinikin ku da wuri-wuri don samun ƙarin tallace-tallace.",
     "card_title" => "Oda a cikin jerin gwano",
     "card_subtitle" => "Daga: kwanan wata",
     "card_payed" => "oda da aka biya",
],
     "community-comments" => [
     "subject" => "Amsa sakonku a cikin :community_title",
     "title" => ":name, da :count wasu sun yi sharhi akan posts ɗinku.",
     "title-simple" => ": sunan yayi sharhi akan posts ɗinku.",
],
     "community-topic" => [
     "subject" => "🔔 Amsa kan batun ku: topic_title",
     "title" => ":name, and :count wasu amsa akan batun ku.",
     "title-simple" => ":suna amsa akan batun ku.",
],
     "user-login" => [
     "subject" => "🔔 Sabon Login :name",
     "category" => "Sanarwa na tsaro",
     "title" => "Shiga Account",
     "message" => "Dear :name, an shiga cikin asusunka na Selldone.",
     "footer" => "Idan ba a shiga ba, da fatan za a canza kalmar sirrinku.",
],
     "account-transaction" => [
     "withdraw" => "Janyewa",
     "deposit" => "Deposit",
     "withdraw_subject" => "janye daga account: account",
     "deposit_subject" => "Deposit to account :account",
     "message" => "An yi musayar kuɗin tare da cikakkun bayanai masu zuwa.",
     "type" => "Nau'in ciniki",
     "from" => "Asusun tushen",
     "to" => "Destination account",
     "desc" => "Bayanin ciniki",
     "action" => "Duba ciniki",
],
     "penalty" => [
     "subject" => "⛔ Muhimmanci! Cin zarafin dokoki | : kantin",
     "category" => "Mahimman bayanai",
     "title" => "An hukunta shagon ku",
     "action" => "Buɗe dashboard ɗin kanti",
],
     "invite" => [
     "subject" => ":mai gayyace ku zuwa Selldone",
     "title" => ":name ya aiko muku: adadin da zai taimaka muku ƙaddamar da sabon gidan yanar gizon ku na kan layi da samun monetize shi!",
     "message" => "A kan Selldone, zaku iya ƙirƙirar kasuwancin ku na e-commerce, gidan yanar gizon rubutun ra'ayin kanka a yanar gizo, da al'ummar kan layi har ma da samun POS akan layi da saita tallace-tallace na mutum cikin mintuna. Tsarin kasuwanci ne na kan layi don sanya kasuwancin ku akan layi, mafi kyau da sauri. Kawai yi rajista ta <b>: kwanan wata</b> don samun baucan : adadin.",
     "accept" => "Karɓi gayyata",
     "owner" => "Mai shi",
     "join-date" => "A kan Selldone tun",
],
     "shop-recovery" => [
     "subject" => "Hanyar farfadowa | : kantin",
     "category" => "Tsaro kantin",
     "title" => "Adana hanyar dawo da <b>:shop_name</b> .",
     "message" => "An aiko muku da wannan imel ɗin saboda kuna buƙatar dawo da kantin sayar da ku. Danna mahaɗin da ke ƙasa zai dawo da shagon ku da duk bayanan da ke cikinsa.",
     "action" => "Tabbatar da Maido da Shagon",
],
     "SR-SeasonalSaving" => [
     "title" => "Nawa ne Selldone ya ajiye don kasuwancin ku?",
     "sub-title" => "Daga kwanan wata :fara zuwa :ƙarshe",
     "infrastructure" => [
     "title" => "Kayan aiki",
     "subtitle" => "Sabar, CDN, Adanawa, da sauran sabis na girgije",
],
     "experts" => [
     "title" => "Masana & Ma'aikata",
     "subtitle" => "Masu haɓakawa, kulawa, da tallafi",
],
     "total_save" => "Jimlar kuɗin da aka ajiye",
],
     "SR-SeasonalPerformance" => [
     "title" => "Ayyukanku",
     "sub-title" => "Bayanin kasuwanci daga :fara zuwa :karshe",
     "new_visitors" => "New Users",
     "returning_visitors" => "Masu amfani da aka dawo",
     "shop_views" => "Kayayyakin Kayayyakin kallo",
     "baskets" => [
     "title" => "Kasuwancin Siyayya",
     "subtitle" => "Bayar da rahoton adadin sabbin motocin sayayya",
],
     "products" => [
     "title" => "Bayanin Samfura",
     "subtitle" => "Matsayin samfurori a cikin shagon ta nau'in",
     "value_name" => "Kayayyaki",
],
     "views" => [
     "title" => "Page Views",
     "subtitle" => "Jimlar ra'ayoyin shafin yanar gizon",
],
],
];