<?php 

 return [
     "home" => "seldone",
     "blogs" => "Blog",
     "helps" => "Vonjeo",
     "current_location" => "Ity fidirana ity",
     "dashboard" => "dashboard",
     "my_shops" => "My Stores",
     "wallet" => "wallet",
     "about" => "Momba an'i Seldone",
     "contact" => "contact us",
     "comments" => "comments",
     "likes" => "tiany",
     "power" => "fifaliana",
     "build_free_shop" => "Amboary maimaim-poana ny fivarotanao",
     "shop_name" => "shop name",
     "categories" => "categories",
     "sub_articles" => "More",
     "terms" => "Anarana iombonana",
     "colour" => "COLOR",
     "style" => "style",
     "volume" => "volume",
     "weight" => "weight",
     "pack" => "entana",
     "type" => "type",
     "add_to_card" => "atao anaty harona",
     "overview" => "Overview",
     "reviews" => "Hevitra",
     "spec" => "Spec feno",
     "you_may_also_like" => "Mety tianao koa",
     "about_us" => "Momba anay",
     "contact_us" => "contact us",
     "cookie_privacy" => "Cookie &amp; privacy policy",
     "follow_us" => "Araho izahay",
     "category" => "Sokajy",
     "author" => "Written by ",
     "published_at" => "Navoaka tamin'ny",
     "modified_at" => "Ovaina amin'ny",
     "price" => "vidiny",
     "discount" => "Discount",
     "price_after_discount" => "Vidiny aorian'ny fihenam-bidy",
     "available" => "Available",
     "sold_out" => "Lafo daholo",
     "buy" => "Hividy izao",
     "login_shop" => "Login Shop",
     "posted_on" => "Navoaka tamin'ny : date",
];