<?php 

 return [
     "invoice" => "faktiora",
     "serial" => "Série No.",
     "date" => "Daty faktiora",
     "seller" => "Mpivarotra",
     "buyer" => "mpividy",
     "address" => "adiresy",
     "code" => "fehezan-dalàna",
     "vat" => "VAT code",
     "phone" => "Phone",
     "description" => "Description",
     "units" => "vondrona",
     "quantity" => "Qty",
     "price" => "vidiny",
     "discount" => "Discount",
     "tax" => "HETRA",
     "sub_total" => "Sub Total",
     "total_discount" => "fihenam-bidy tanteraka",
     "taxable_amount" => "Vola azo hetra",
     "total_taxes" => "Total hetra",
     "tax_rate" => "Hetra",
     "total_amount" => "Fitambarany",
     "pay_until" => "Mba andoavam-bola hatramin'ny",
     "amount_in_words" => "Vola amin'ny teny",
     "amount_in_words_format" => "%s %s sy %s %s",
     "notes" => "-tsoratra",
     "shipping" => "Fandefasana",
     "paid" => "karama",
     "due" => "noho",
];