<?php 

 return [
     "invoice" => "Fatura",
     "serial" => "Número de série.",
     "date" => "Data da fatura",
     "seller" => "Vendedor",
     "buyer" => "Comprador",
     "address" => "Morada",
     "code" => "Código",
     "vat" => "Código do IVA",
     "phone" => "Telefone",
     "description" => "Descrição",
     "units" => "Unidades",
     "quantity" => "Quantidade",
     "price" => "preço",
     "discount" => "Desconto",
     "tax" => "Imposto",
     "sub_total" => "Subtotal",
     "total_discount" => "Desconto total",
     "taxable_amount" => "Valor taxado",
     "total_taxes" => "Total de impostos",
     "tax_rate" => "Taxa de imposto",
     "total_amount" => "Montante total",
     "pay_until" => "Por favor, pague até",
     "amount_in_words" => "Quantidade em palavras",
     "amount_in_words_format" => "%s %s e %s %s",
     "notes" => "Notas",
     "shipping" => "Envio",
     "paid" => "Pago",
     "due" => "Vencimento",
];