<?php 

 return [
     "invoice" => "Faktura",
     "serial" => "Seriya nömrəsi",
     "date" => "Faktura tarixi",
     "seller" => "Satıcı",
     "buyer" => "Alıcı",
     "address" => "ünvanı",
     "code" => "Kod",
     "vat" => "ƏDV kodu",
     "phone" => "Telefon",
     "description" => "Təsvir",
     "units" => "Vahidlər",
     "quantity" => "Miqdar",
     "price" => "qiymət",
     "discount" => "Güzəşt",
     "tax" => "vergi",
     "sub_total" => "Alt cəmi",
     "total_discount" => "Ümumi endirim",
     "taxable_amount" => "Vergi tutulan məbləğ",
     "total_taxes" => "Ümumi vergilər",
     "tax_rate" => "Vergi dərəcəsi",
     "total_amount" => "Ümumi miqdar",
     "pay_until" => "Zəhmət olmasa ödəyin",
     "amount_in_words" => "Məbləğ sözlə",
     "amount_in_words_format" => "%s %s və %s %s",
     "notes" => "Qeydlər",
     "shipping" => "Göndərmə",
     "paid" => "Ödənişli",
     "due" => "Vaxtı var",
];