<?php 

 return [
     "accepted" => ":atributu qəbul edilməlidir.",
     "active_url" => ":atributu etibarlı URL deyil.",
     "after" => ":atributu :date-dən sonrakı tarix olmalıdır.",
     "after_or_equal" => ":atributu :date-dən sonrakı və ya ona bərabər olan tarix olmalıdır.",
     "alpha" => ":atributunda yalnız hərflər ola bilər.",
     "alpha_dash" => ":atributunda yalnız hərf, rəqəm və tire ola bilər.",
     "alpha_num" => ":atributunda yalnız hərflər və rəqəmlər ola bilər.",
     "array" => ":atributu massiv olmalıdır.",
     "before" => ":atributu :date-dən əvvəlki tarix olmalıdır.",
     "before_or_equal" => ":atributu :date-dən əvvəl və ya ona bərabər bir tarix olmalıdır.",
     "between" => [
     "numeric" => ":atributu :min və :max arasında olmalıdır.",
     "file" => ":atributu :min və :max kilobayt arasında olmalıdır.",
     "string" => ":atributu :min və :max simvolları arasında olmalıdır.",
     "array" => ":atributunda :min və :max elementləri olmalıdır.",
],
     "boolean" => ":atribut sahəsi doğru və ya yalan olmalıdır.",
     "confirmed" => ":atribut təsdiqi uyğun gəlmir.",
     "date" => ":atributu etibarlı tarix deyil.",
     "date_format" => ":atributu :format formatına uyğun gəlmir.",
     "different" => ":atribut və :digər fərqli olmalıdır.",
     "digits" => ":atributu :digits rəqəmləri olmalıdır.",
     "digits_between" => ":atributu :min və :max rəqəmləri arasında olmalıdır.",
     "dimensions" => ":atributunda yanlış şəkil ölçüləri var.",
     "distinct" => ":atribut sahəsinin dublikat dəyəri var.",
     "email" => ":atributu etibarlı e-poçt ünvanı olmalıdır.",
     "exists" => "Seçilmiş :atribut etibarsızdır.",
     "file" => ":atributu fayl olmalıdır.",
     "filled" => ":atribut sahəsinin dəyəri olmalıdır.",
     "gt" => [
     "numeric" => ":atributu :value-dən böyük olmalıdır.",
     "file" => ":atributu :value kilobaytdan böyük olmalıdır.",
     "string" => ":atributu :value simvollarından böyük olmalıdır.",
     "array" => ":atributunda :value elementindən çox olmalıdır.",
],
     "gte" => [
     "numeric" => ":atributu :value-dən böyük və ya bərabər olmalıdır.",
     "file" => ":atributu :value kilobaytdan böyük və ya bərabər olmalıdır.",
     "string" => ":atributu :value simvollarından böyük və ya bərabər olmalıdır.",
     "array" => ":atributunda :value elementləri və ya daha çox olmalıdır.",
],
     "image" => ":atributu şəkil olmalıdır.",
     "in" => "Seçilmiş :atribut etibarsızdır.",
     "in_array" => ":atribut sahəsi :digərdə mövcud deyil.",
     "integer" => ":atributu tam ədəd olmalıdır.",
     "ip" => ":atributu etibarlı IP ünvanı olmalıdır.",
     "ipv4" => ":atributu etibarlı IPv4 ünvanı olmalıdır.",
     "ipv6" => ":atributu etibarlı IPv6 ünvanı olmalıdır.",
     "json" => ":atributu etibarlı JSON sətri olmalıdır.",
     "lt" => [
     "numeric" => ":atributu :value-dən kiçik olmalıdır.",
     "file" => ":atributu :value kilobaytdan kiçik olmalıdır.",
     "string" => ":atributu :value simvollarından kiçik olmalıdır.",
     "array" => ":atributunda :value elementlərindən az olmalıdır.",
],
     "lte" => [
     "numeric" => ":atributu :value-dan kiçik və ya bərabər olmalıdır.",
     "file" => ":atributu :value kilobaytdan kiçik və ya bərabər olmalıdır.",
     "string" => ":atributu :value simvollarından kiçik və ya bərabər olmalıdır.",
     "array" => ":atributunda :value elementindən çox olmamalıdır.",
],
     "max" => [
     "numeric" => ":atributu :max-dan böyük ola bilməz.",
     "file" => ":atributu :max kilobaytdan çox ola bilməz.",
     "string" => ":atributu :max simvolundan çox ola bilməz.",
     "array" => ":atributunda :max-dan çox element ola bilməz.",
],
     "mimes" => ":atributu :value tipli fayl olmalıdır.",
     "mimetypes" => ":atributu :value tipli fayl olmalıdır.",
     "min" => [
     "numeric" => ":atributu ən azı :min olmalıdır.",
     "file" => ":atributu ən azı :min kilobayt olmalıdır.",
     "string" => ":atributu ən azı :min simvoldan ibarət olmalıdır.",
     "array" => ":atributunda ən azı :min elementləri olmalıdır.",
],
     "not_in" => "Seçilmiş :atribut etibarsızdır.",
     "not_regex" => ":atribut formatı yanlışdır.",
     "numeric" => ":atributu rəqəm olmalıdır.",
     "present" => ":atribut sahəsi mövcud olmalıdır.",
     "regex" => ":atribut formatı yanlışdır.",
     "required" => ":atribut sahəsi tələb olunur.",
     "required_if" => ":atribut sahəsi :digər :dəyər olduqda tələb olunur.",
     "required_unless" => ":digər :dəyərlərdə olmadığı halda :atribut sahəsi tələb olunur.",
     "required_with" => ":atribut sahəsi :dəyərlər mövcud olduqda tələb olunur.",
     "required_with_all" => ":atribut sahəsi :dəyərlər mövcud olduqda tələb olunur.",
     "required_without" => ":atribut sahəsi :dəyərlər olmadıqda tələb olunur.",
     "required_without_all" => ":atribut sahəsi :dəyərlərdən heç biri mövcud olmadıqda tələb olunur.",
     "same" => ":atribut və :digər uyğun olmalıdır.",
     "size" => [
     "numeric" => ":atributu :size olmalıdır.",
     "file" => ":atributu :size kilobayt olmalıdır.",
     "string" => ":atributu :size simvolları olmalıdır.",
     "array" => ":atributunda :size elementləri olmalıdır.",
],
     "string" => ":atributu sətir olmalıdır.",
     "timezone" => ":atributu etibarlı zona olmalıdır.",
     "unique" => ":atributu artıq götürülüb.",
     "uploaded" => ":atributunu yükləmək alınmadı.",
     "url" => ":atribut formatı yanlışdır.",
     "custom" => [
     "attribute-name" => [
     "rule-name" => "xüsusi mesaj",
],
     "g-recaptcha-response" => [
     "required" => "Robot olmadığınızı təsdiqləyin.",
     "captcha" => "Captcha xətası! sonra yenidən cəhd edin və ya sayt admini ilə əlaqə saxlayın.",
],
],
     "attributes" => [
        
     ],
];