<?php 

 return [
     "home" => "賣完了",
     "blogs" => "博客",
     "helps" => "幫助",
     "current_location" => "此條目",
     "dashboard" => "dashboard",
     "my_shops" => "我的商店",
     "wallet" => "wallet",
     "about" => "關於 Selldone",
     "contact" => "contact us",
     "comments" => "comments",
     "likes" => "喜歡",
     "power" => "歡呼",
     "build_free_shop" => "免費建立您的商店",
     "shop_name" => "shop name",
     "categories" => "categories",
     "sub_articles" => "More",
     "terms" => "條款",
     "colour" => "顏色",
     "style" => "style",
     "volume" => "volume",
     "weight" => "weight",
     "pack" => "盒",
     "type" => "type",
     "add_to_card" => "添加到購物車",
     "overview" => "Overview",
     "reviews" => "評論",
     "spec" => "完整規格",
     "you_may_also_like" => "你也許也喜歡",
     "about_us" => "關於我們",
     "contact_us" => "contact us",
     "cookie_privacy" => "Cookie &amp; privacy policy",
     "follow_us" => "跟著我們",
     "category" => "類別",
     "author" => "Written by ",
     "published_at" => "發表於",
     "modified_at" => "修改於",
     "price" => "價格",
     "discount" => "折扣",
     "price_after_discount" => "折扣後的價格",
     "available" => "可用的",
     "sold_out" => "售罄",
     "buy" => "立即購買",
     "login_shop" => "登錄商店",
     "posted_on" => "發表於：日期",
];