<?php 

 return [
     "email-types-description" => [
     "shop-customer-join" => "此消息歡迎新買家來到商店。",
     "order-checkout" => "當買家確認訂單時發送此通知。",
     "order-payment" => "此通知確認客戶已成功付款。",
     "order-payment-admin" => "此訊息發送給賣家，通知他們訂單已確認。",
     "pos-checkout" => "發送此通知是為了確認買家的銷售點訂單。",
     "pos-payment" => "此通知確認買家進行的銷售點付款。",
     "pos-payment-admin" => "此訊息通知賣家在其銷售點進行的購買。",
     "shop-contact" => "提交聯絡表單後會發送此通知。",
     "shop-giftcard" => "此通知通知用戶他們已收到禮品卡。",
     "shop-vendor-join" => "此消息歡迎新供應商來到商店。",
     "shop-vendor-invite" => "發送此訊息是為了邀請供應商加入您的市場。",
     "shop-vendor-order" => "當收到處於「已付款」或「貨到付款」(COD) 狀態的訂單時，將向供應商發送此訊息。",
     "shop-vendor-products" => "每天發送，向供應商更新其產品狀態。",
     "shop-login" => "出於安全目的，通知用戶登入詳細信息，包括 IP 位址、日期和設備。",
     "login-code" => "發送一次性密碼，供用戶登入商店。",
     "shop-email-verify-link" => "發送連結以驗證使用者的電子郵件地址。當用戶透過簡訊註冊並輸入電子郵件時會發送此郵件，而當用戶直接透過社交或電子郵件註冊時不會發送此郵件。",
],
     "global" => [
     "greetings" => "嗨：名字",
     "end-statement" => "支持團隊",
     "receiver_name" => "嗨：用戶名",
     "footer-help" => "需要幫忙？在 [support@selldone.com](mailto:support@selldone.com) 詢問或訪問我們的 [幫助中心](https://selldone.com/help)",
     "footer-shop" => "如果您需要任何幫助，請隨時給我們發送電子郵件：：shop_mail",
     "accept" => "接受",
     "reject" => "拒絕",
     "verify" => "核實",
     "title" => "標題",
     "value" => "價值",
     "description" => "描述",
     "Shop" => "店鋪",
     "user" => "用戶",
     "license" => "執照",
     "status" => "地位",
     "start" => "開始",
     "end" => "結尾",
     "renewal" => "續訂",
     "view" => "看法",
     "balance" => "平衡",
     "card_number" => "卡號",
     "cvv" => "簡歷",
     "expire_date" => "到期日期",
     "dashboard" => "儀表板",
     "order" => "命令",
     "view_order" => "查看訂單",
     "pay_now" => "Pay now",
     "official_selldone" => "官方銷售",
     "account-number" => "Account number",
     "account-name" => "Account name",
     "currency" => "貨幣",
     "free-balance" => "免費餘額",
     "locked-balance" => "鎖定餘額",
     "bot" => "機器人",
     "requests" => "要求",
     "baskets" => "推車",
     "physical" => "身體的",
     "virtual" => "虛擬的",
     "file" => "文件",
     "service" => "服務",
     "fulfillment" => "履行",
     "open" => "打開",
     "reserved" => "預訂的",
     "canceled" => "取消",
     "payed" => "有薪酬的",
     "cod" => "COD",
     "orders-count" => "訂單",
     "payments-count" => "付款",
     "confirms-count" => "確認",
     "sends-count" => "發送",
     "delivers-count" => "提供",
     "count" => "數數",
     "transactions-count" => "交易計數",
     "success-transactions" => "成功交易",
     "total-amount" => "總金額",
     "amount" => "數量",
     "wage" => "工資",
     "debug" => "調試",
     "pos" => "POS",
     "live" => "居住",
     "CheckQueue" => "檢查隊列",
     "OrderConfirm" => "訂單確認",
     "PreparingOrder" => "準備訂單",
     "SentOrder" => "已發送訂單",
     "ToCustomer" => "交付給客戶",
     "Pending" => "待辦的",
     "Accepted" => "公認",
     "Rejected" => "被拒絕",
     "pc" => "PC",
     "tablet" => "藥片",
     "phone" => "電話",
     "total" => "全部的",
     "view-detail" => "查看詳細",
     "empty" => "空的",
     "dropshipping" => "代發貨",
     "reply" => "回复",
     "reactions" => "反應",
     "comments" => "註釋",
     "last-comment" => "最後評論",
     "response-to" => "響應",
     "posts" => "帖子",
     "post" => "郵政",
     "name" => "姓名",
     "email" => "電子郵件",
     "type" => "類型",
     "device" => "設備",
     "platform" => "平台",
     "browser" => "瀏覽器",
     "time" => "時間",
     "wallet" => "錢包",
     "date" => "日期",
     "account" => "帳戶",
     "transaction" => "交易",
     "fee" => "費用",
     "location" => "Location",
     "ip" => "IP",
     "bill" => "賬單",
     "category" => "類別",
     "password" => "密碼",
     "shop" => "店鋪",
     "verify-login" => "驗證並登錄",
     "url" => "URL",
     "avocado" => "牛油果",
     "hyper" => "超",
     "buy-now" => "立即購買",
     "add-domain" => "Add Domain",
     "views" => "意見",
     "country" => "國家",
     "address" => "地址",
     "postal" => "郵政編碼",
     "building_no" => "建造 ＃",
     "building_unit" => "單元 ＃",
     "message" => "信息",
     "customer" => "顧客",
     "cart-items" => "購物車物品",
     "payment" => "支付",
     "receiver" => "接收者",
     "virtual-items" => "虛擬物品",
     "no-payment" => "沒有付款！",
     "enable" => "使能夠",
     "access" => "使用權",
     "bank" => "銀行信息",
     "vendor" => "小販",
     "view_content" => "看完整內容",
     "files" => "文件",
     "download" => "下載",
     "file_name" => "檔案名稱",
     "file_size" => "尺寸",
     "subscription" => "訂閱",
     "products" => "產品",
     "vendor_products" => "供應商產品",
],
     "selldone-business-os" => "Selldone 商業操作系統",
     "senders" => [
     "WeeklyReport" => [
     "id" => "performance",
     "name" => "業績報告，Selldone",
],
     "SeasonalReport" => [
     "id" => "seasonal",
     "name" => "季節性報告，Selldone",
],
     "Onboarding" => [
     "id" => "你好",
     "name" => "批准，出售",
],
     "Support" => [
     "id" => "support",
     "name" => "支持：名稱",
],
     "EmailVerify" => [
     "id" => "verify",
     "name" => "驗證，出售",
],
     "Welcome" => [
     "id" => "你好",
     "name" => "社區，Selldone",
],
     "NewShop" => [
     "id" => "商人",
     "name" => "批准，出售",
],
     "Approve" => [
     "id" => "批准",
     "name" => "批准，出售",
],
     "SellerReceiveOrder" => [
     "id" => "order",
     "name" => "訂單管理：名稱",
],
     "Recovery" => [
     "id" => "恢復",
     "name" => "Selldone 恢復團隊",
],
],
     "bill-status" => [
     "PENDING" => "待定⌛",
     "PAYED" => "付費✅",
     "CANCELED" => "取消❌",
],
     "shop-invite" => [
     "LEVEL-NAME" => [
     "ADMIN" => "行政人員",
     "OFFICER" => "官員和主管",
     "AUDITING" => "審計經理",
     "EMPLOYEE" => "員工",
     "PRODUCT" => "產品經理",
     "CONTENT" => "內容管理者",
     "MARKETING" => "市場經理",
     "VIEWER" => "查看器",
],
     "subject" => ":inviter 邀請你為 :level | ：店鋪",
     "category" => "員工邀請",
     "title" => "您已被邀請到<b>:shop_name</b>作為<b>:level</b> 。",
     "message" => "已向您發送邀請。您可以確認或拒絕它。如果此邀請得到您的批准，您必須進入 Selldone 服務進行確認。通過確認此邀請，您將可以訪問商店管理部分。",
],
     "welcome-email" => [
     "subject" => "👋 歡迎 :name，一些有趣的事情只為你。",
     "category" => "CONGRATULATION",
     "title" => "歡迎光臨",
     "message" => "感謝您選擇 Selldone，您現在是 Selldone 社區的一員，該社區將全球賣家與客戶、本地企業與企業、個人與公司聯繫起來！為您提供**免費**和**無限**的所有大師和專業工具。你試一試，我們開門，Just Do It！",
     "seller" => [
     "title" => "你是賣家嗎？",
     "message" => "要開始銷售，請通過以下鏈接在 Selldone 中輸入您的儀表板，並完全免費創建您的第一家商店。這將需要幾分鐘，您將擁有自己的商店和在線網站。然後，我們將引導您進行下一步並獲取支付網關。",
     "action" => "登錄我的儀表板",
],
     "buyer" => [
     "title" => "我是買家",
     "message" => "恭喜。一旦您成為 Selldone 的會員，您將擺脫在線商店的會員資格和身份驗證的所有麻煩。要從使用 Selldone 平台的任何商店和網站中受益，您可以一鍵登錄，讓您的購買變得簡單、快速和安全。",
],
],
     "charge-account" => [
     "category" => "錢包 > 賬戶 > 收費",
     "title" => "成功衝鋒",
     "message" => "您的帳戶<b>：account_number</b>已成功<b>：收取金額</b>。",
     "account" => "帳戶",
     "charge" => "收費",
     "balance" => "平衡",
     "footer" => "讓世界各地的任何人都可以輕鬆、可實現和訪問業務。",
],
     "verify-email" => [
     "subject" => "🙌 完成您對 Selldone 的註冊！驗證鏈接。",
     "category" => "一步之遙",
     "title" => "確認你的郵件地址",
     "message" => "嗨：名字，<br>感謝您選擇 Selldone。<br>請在 48 小時內單擊按鈕或使用以下鏈接確認 **:email** 是您的電子郵件地址。",
     "footer" => "如果您在單擊“驗證”按鈕時遇到問題，請將以下 URL 複製並粘貼到您的網絡瀏覽器中：__:activation_url__",
],
     "verify-email-code" => [
     "subject" => ":name 的驗證碼",
     "category" => "SECURITY",
     "title" => "郵箱驗證碼",
     "message" => "嗨：名字，<br><br>請在 10 分鐘內通過此代碼確認 **:email** 是您的電子郵件地址。",
],
     "onboarding-verify-email" => [
     "subject" => "🎉 您的店鋪已準備就緒 | ：姓名",
     "category" => "一步之遙",
     "title" => "設置完成",
     "account_title" => "您的帳戶",
     "account_msg" => "使用此信息驗證並登錄您的帳戶。",
     "shop_msg" => "Selldone 業務操作系統上的帳戶信息。",
],
     "reset2fa" => [
     "category" => "安全官方消息",
     "title" => "請求禁用兩步登錄",
     "message" => "您收到這封電子郵件是因為我們收到了您帳戶的 2 因素身份驗證重置請求。<br><br>用戶郵箱: <b>:email</b><br>名稱<b>：：名稱</b>",
     "footer" => "如果您未請求重置密碼，則無需進一步操作。",
     "action" => "禁用兩步登錄",
],
     "build-new-shop" => [
     "subject" => "🎊 您的店鋪現已準備就緒！",
     "category" => "在世界上誕生新的在線商店",
     "title" => "慶祝",
     "message" => "<b>恭喜：name，您創建了一個新的在線業務；</b>我們祝您事業成功。歡迎來到賣家社區。<br>你試試，我們打開門，你做到了。",
     "pdf-book" => "不要錯過隨附的手冊：像遊戲一樣開展業務",
     "account" => [
     "title" => "第 1 步：在 Selldone 錢包中創建一個賬戶",
     "message" => "如果您的錢包中沒有帳戶，請創建一個。 Selldone 會從該賬戶中扣除費用。您可以充值此帳戶，Selldone 還會向您收取一定金額的信用額度，這樣如果此帳戶為負數，您的網站和商店將繼續運營。",
     "action" => "登錄錢包",
],
     "shop-account" => [
     "title" => "第 2 步：將帳戶連接到商店",
     "message" => "將您的錢包帳戶添加到您的商店。為此，請輸入商店 > 會計 > 發票並將帳戶連接到商店。請注意，您所有客戶的付款都直接存入您的銀行帳戶，Selldone 不會提取或扣除任何金額，因此您需要將 Selldone 的此帳戶連接到商店。",
     "action" => "商店發票面板",
],
     "gateway" => [
     "title" => "第三步：連接在線支付網關",
     "message" => "轉到 Store> Accounting> Port 並按<b>Add New Port</b> 。選擇貨幣後，您將看到一個便攜式端口列表。在 Selldone 中連接端口非常簡單快捷，但如果您有 Niza 尋求指導，請參閱 Selldone 指南部分或詢問我們。",
     "action" => "將門戶添加到商店",
],
     "domain" => [
     "title" => "最後一步：連接專用域",
     "message" => "您將能夠在任意數量的域上擁有您的商店。要將專用域連接到商店，您至少需要擁有啟動許可證。通過將每位朋友介紹給 Selldone，您將收到一張為期一個月的創業許可證禮品卡。您朋友的一部分付款也將記入您客戶的帳戶。",
     "action" => "介紹和接收無限的禮品卡",
],
],
     "basket-list" => [
     "item" => "物品",
     "count" => "數數",
     "price" => "價格",
     "discount-code" => "優惠碼",
     "customer-club" => "客戶俱樂部",
     "shipping" => "船運",
     "total" => "全部的",
     "offer" => "提供",
     "coupon" => "優惠券",
     "lottery" => "獎",
     "tax" => "稅",
     "tax_included" => "包含在價格中",
     "tax_shipping" => "Shipping Tax",
],
     "buyable-payments" => [
     "method" => "方法",
     "amount" => "數量",
     "giftcard" => "Gift card",
     "payment" => "支付",
],
     "shop-subscription-email" => [
     "category" => "訂閱更新",
     "title" => "店鋪執照: :shop_title",
     "title-reserved" => "預留許可證：:shop_title",
     "title-active" => "有效許可證：：shop_title",
     "title-finished" => "完成的許可證：：shop_title",
     "title-cancel" => "取消許可證：:shop_title",
     "message" => "您的商店許可證計劃已更新，",
     "RESERVED" => "⚡ 您的訂閱計劃已被**保留**。",
     "ACTIVE" => "🟢 您的訂閱計劃已**激活**。",
     "FINISHED" => "🚧 您的訂閱計劃已**完成**。",
     "CANCEL" => "⛔ 您的訂閱計劃已**取消**。",
],
     "support" => [
     "subject" => "支持中心 | :name 回复",
     "category" => "支持中心",
     "title" => "您收到了回复",
     "action" => "開店管理員",
],
     "shop-customer-join" => [
     "subject" => "加入：shop_title",
     "category" => "新客戶慶典",
     "title" => "我們很高興成為您的會員",
     "action" => "立即訪問",
],
     "shop-vendor-join" => [
     "subject" => "供應商入職| :商店名稱",
     "category" => "新供應商慶祝活動",
     "title" => "我們很高興成為您的會員",
     "action" => "Vendor Panel",
],
     "shop-giftcard" => [
     "subject" => "禮品卡：shop_title",
     "category" => "添加新卡",
     "title" => "恭喜，您已收到禮品卡",
     "action" => "現在去購物",
     "message" => "您收到了一張金額為 :balance :currency 的禮品卡。您可以使用此禮品卡從我們的商店購買。",
],
     "contact" => [
     "subject" => "支持中心 | ：店鋪",
     "category" => "支援",
     "title" => "您收到了回复",
],
     "order-checkout" => [
     "subject" => "🛍 訂單結帳 | :order_id",
     "title" => "命令",
     "message" => "您的訂單確認，<br>我們收到了您的訂單。當您的訂單發貨時，我們會再給您發送一封電子郵件。",
     "payments" => "付款",
],
     "order-payment" => [
     "subject" => "🛍 付款確認 | :order_id",
     "title" => "付款單",
     "message" => "您的付款已完成，<br>我們收到了您的訂單。當您的訂單發貨時，我們會再給您發送一封電子郵件。",
     "payments" => "付款",
],
     "get-voucher" => [
     "subject" => "恭喜：姓名 |新優惠券: :title",
     "category" => "恭喜，新優惠券",
     "message" => "您將獲得新的優惠券，這是我們送給您的禮物。通過將 Selldone 介紹給朋友和您認識的每個人，您可以從這些代金券中獲得更多收益。此優惠券價值**：價格：貨幣**。<br>你試試看，我們開門，恭喜你，用你的代金券解鎖功能！",
     "action" => "我的儀表板",
],
     "received-gift" => [
     "subject" => "恭喜，親愛的:name |你收到了一份禮物",
     "category" => "收到禮物的通知",
     "title" => "給你的禮物",
     "message" => "你收到了一份新禮物。這是 Selldone 的禮物。您可以通過在 Selldone 中更加活躍並發展您的商店並提高您的專業化水平來獲得更多這些禮物。此禮品價值為**:price :currency**，您可以直接存入您的錢包中。<br><br>使用此禮物升級您的商店許可證並在您的在線業務中使用更多工具。",
     "action" => "禮物",
],
     "order-payment-admin" => [
     "subject" => "🛍 收到新訂單 | :order_id",
     "title" => "New Order",
     "message" => "您收到了一份新訂單。請轉到您商店的訂單處理頁面。",
],
     "virtual-item" => [
     "input-form-title" => "您填寫的信息",
     "output-form-title" => "購買商品信息",
],
     "selldone-weekly-report" => [
     "subject" => "📬 :shop_title |週報：時間",
     "title" => "每週商店業績報告",
     "message" => "這是您商店從 :start 到 :end 的每週報告。此報告包括改善業務的提示，您還可以查看在線商店的狀態和最近的訂單。我希望你有一個美好的一天和一周。",
],
     "shop-seasonal-report" => [
     "subject" => "☘ 您最近三個月的儲蓄金額報告 | :shop_title",
     "title" => "關於您的業務活動、獎勵和財務節省的季節性報告",
     "message" => "這是您從 :start 到 :end 的 :shop_title 季節性報告。",
],
     "EC-ShopAccounts" => [
     "title" => "關聯賬戶",
     "sub-title" => "連接到我的商店的錢包帳戶的最新狀態是什麼？",
     "view-wallet" => "查看錢包",
     "tip-title" => "重要提示",
     "tip" => "在下一步中，在您的 Selldone 錢包中創建一個免費帳戶並將其連接到該商店。即使您的 Selldone 帳戶餘額為負數，您的客戶仍然可以毫無問題地為您的商店進行購買和付款。您的數據和服務至少在 1 個月內不會中斷或受到限制。",
     "view-my-wallet" => "My wallet",
     "connect-account" => "連接到帳戶",
],
     "EC-ShopApps" => [
     "title" => "已安裝的應用程序",
     "sub-title" => "本週您在商店中安裝的應用程序列表。",
     "tip" => "您想為您的商店找到更多應用嗎？",
     "view-app-store" => "訪問 Selldone 應用商店。",
],
     "EC-ShopBots" => [
     "title" => "您的商店機器人",
     "sub-title" => "我商店中的活躍銷售機器人。",
     "tip-title" => "機器人銷售",
     "tip" => "Selldone 為您提供了自動銷售機器人。您所要做的就是轉到附加組件> 機器人面板並激活您的商店機器人。請注意，您所在的國家/地區必須提供相關服務。",
     "view-bots" => "管理機器人",
],
     "EC-ShopContacts" => [
     "title" => "與客戶溝通",
     "sub-title" => "本週我與客戶有多少聯繫？",
     "faqs" => "經常問的問題",
     "tickets" => "客戶票",
],
     "EC-ShopData" => [
     "title" => "用戶狀態",
     "sub-title" => "從日期：開始到：結束",
     "users" => [
     "title" => "顧客",
     "subtitle" => "註冊用戶",
],
     "views" => [
     "title" => "訪問",
     "subtitle" => "你去過這家店多少次",
],
     "new_visitors" => "New Users",
     "returning_visitors" => "返回用戶",
     "shop_views" => "店鋪景觀",
     "baskets" => [
     "title" => "購物車",
     "subtitle" => "報告新購物車的數量",
],
     "products" => [
     "title" => "產品概述",
     "subtitle" => "商店中產品的狀態（按類型）",
     "value_name" => "產品",
],
     "products_count" => "產品類型",
     "views_count" => "查看次數",
     "sell_count" => "銷售數量",
     "send_count" => "運輸計數",
],
     "EC-ShopDropShipping" => [
     "title" => "代發貨",
     "sub-title" => "Drop Shipping Selldone 主要賣家的面板。",
     "total_fulfillments" => "收到的訂單總數",
     "ds_count" => "收到的訂單",
     "statistics_title" => "報告收到的訂單",
     "ds_cancels" => "接口賣家取消",
     "ds_rejects" => "由您取消",
     "tip" => "您是商品的主要賣家嗎？您是否擁有倉庫、工廠或產品經銷商？您可以在 Selldone Drop Shipping 服務中將您的產品提供給其他賣家，以大規模銷售您的產品。發送電子郵件至 support@selldone.com 為您提供指導。",
     "view-drop-shipping-panel" => "登錄批發麵板",
],
     "EC-ShopExchangeRates" => [
     "title" => "匯率",
     "sub-title" => "您商店中最新的貨幣兌換率列表。",
     "from" => "來源貨幣",
     "to" => "目的地貨幣",
     "rate" => "轉化率",
     "vew-exchange-panel" => "匯率管理小組",
],
     "EC-ShopExperts" => [
     "title" => "專家合同",
     "sub-title" => "哪些專業人員在我的商店工作？",
     "cost" => "合約金額",
     "duration" => "期間",
     "start_at" => "Start Date",
     "complete_at" => "Completion Date",
     "cancel_at" => "日期取消",
     "end_at" => "交貨日期",
     "tip" => "您可以聘請 Selldone 最好的專家來發展您的業務。",
     "view-experts" => "點擊開始。",
],
     "EC-ShopGateways" => [
     "title" => "Payment gateways",
     "sub-title" => "報告商店：shop 上的活動支付網關。",
     "tip-title" => "重要提示",
     "tip" => "轉到您商店的門戶管理頁面，並在幾分鐘內添加至少一個端口。您的客戶喜歡通過在線門戶快速安全地付款。",
     "view-shop-gateways" => "登錄我的商店門戶管理。",
     "view-gateways" => "查看更多網關",
],
     "EC-ShopOrders" => [
     "title" => "訂單",
     "sub-title" => "我本週收到的訂單清單。",
     "total_baskets" => "總訂單",
     "total_posBaskets" => "總現金訂單",
     "pos-title" => "POS 存儲箱",
     "chart-label" => "訂單已完成（這些訂單不一定要付款！）",
     "tip-title" => "你應該更加努力...",
     "tip" => "沒有簡單的成功。",
],
     "EC-ShopProcessCenter" => [
     "title" => "加工中心",
     "sub-title" => "本週我們在商店處理了多少訂單？",
     "tip-title" => "你沒有銷售！",
     "tip" => "不幸的是，你這週沒有任何銷售。你需要更多的東西到你的商店。您可以添加更多產品、選擇更好的圖像或為您的產品編寫更好的描述。考慮為您的企業找一份全職工作。如果你做對了並且不沮喪，你就會成功。",
     "view-process-center" => "查看流程中心",
     "return" => [
     "title" => "退貨訂單",
     "subtitle" => "報告退貨訂單。",
     "tip-title" => "你知道嗎 ...",
     "tip" => "您可以通過 Selldone POS 創建任意數量的商店收銀機！事實上，您可以將平板電腦、手機或筆記本電腦變成收件箱。如果這讓您興奮，Selldone POS 您現在應該開始使用它。只需單擊一下即可啟動，我們已為您的服務器提前準備好一切。",
     "view-pos" => "登錄我的在線商店收銀員",
],
],
     "EC-ShopSessions" => [
     "title" => "會話",
     "sub-title" => "我光顧了我的商店多少次？",
     "countries-title" => "訪問量最大的國家是哪些？",
],
     "EC-PublicMessage" => [
     "title" => "你想不花一分錢就賺錢嗎？",
     "message" => "親愛的 :name，您可以轉到儀表板 > 取消貨幣化並創建推薦鏈接。將鏈接發送給您的朋友，您會收到一張 Selldone 禮品卡和您朋友付款的百分比。請注意，禮品卡將同時發送給您和您的朋友。",
     "action" => "查看我的介紹鏈接",
     "mail-clip" => "<b style='color: #C2185B'>重要提示：</b>如果您使用限制電子郵件長度的電子郵件服務（例如 Gmail），請在電子郵件末尾找到以下選項以顯示完整報告並單擊它：",
     "no-coin-reward" => "<b style='color: #C2185B'>抱歉：</b>您的活動不符合獲得免費 SEL Coins 獎勵的要求。更加努力地為下一季在您的商店銷售更多產品。",
     "yes-coin-reward" => "<b style='color: #4CAF50'>獎勵：</b>恭喜，因為你的出色表現，我們給了你一個:amount SEL Coin的免費獎勵。",
     "need-buy-license" => "<b>升級您的業務：</b>您尚未為您的企業網站註冊任何訂閱計劃！因此，現在是購買至少一份訂閱的時候了。它只需花費：每年購買的每月金額。",
     "not-afford-message" => "如果您負擔不起或付款有任何問題，請隨時通過 support@selldone.com 告訴我們。",
     "add-domain" => "<b>為什麼不為您的企業創建一個自定義域？</b><br>立即向您的網站添加域；免費！",
],
     "Widget-Socials" => [
     "title" => "Selldone 是一個<del>產品</del><span style = 'color: forestgreen'>社區</span>。<br>做一個專業的賣家！",
     "message" => "在 Twitter、LinkedIn 和社交網絡上關注 Selldone 的官方頁面。向我們發送任何評論、請求或批評，或參與有關 Selldone 的討論。我們也是<b>您創建</b>的 Selldone 社區的一部分。",
],
     "avocado-seller-daily-report" => [
     "subject" => "收到新的鱷梨訂單 | :shop_title :時間",
     "title" => "過去 24 小時的績效報告",
     "message" => "您的客戶正在等待對您的訂單進行審核和定價。盡快響應客戶的要求以獲得更多銷售。",
     "card_title" => "隊列中的訂單",
     "card_subtitle" => "從日期",
     "card_payed" => "已付款訂單",
],
     "community-comments" => [
     "subject" => "在 :community_title 中回复您的帖子",
     "title" => ":name 和 :count 其他人對您的帖子發表了評論。",
     "title-simple" => ":name 對您的帖子發表了評論。",
],
     "community-topic" => [
     "subject" => "🔔 回复你的話題：topic_title",
     "title" => ":name 和 :count 其他人回復了您的主題。",
     "title-simple" => ":name 回復了您的主題。",
],
     "user-login" => [
     "subject" => "🔔 新登錄名：姓名",
     "category" => "安全通知",
     "title" => "登錄帳戶",
     "message" => "親愛的 :name，您已登錄您的 Selldone 帳戶。",
     "message-shop" => "親愛的 :name，您已登入 :shop_title 。",
     "footer" => "如果您沒有登錄，請更改您的密碼。",
],
     "account-transaction" => [
     "withdraw" => "退出",
     "deposit" => "訂金",
     "withdraw_subject" => "從帳戶中提取：帳戶",
     "deposit_subject" => "存款到賬戶：account",
     "message" => "匯款已按照以下規格進行。",
     "type" => "交易類型",
     "from" => "來源賬戶",
     "to" => "Destination account",
     "desc" => "交易說明",
     "action" => "查看交易",
],
     "penalty" => [
     "subject" => "⛔ 重要！違反規則 | ：店鋪",
     "category" => "關鍵信息",
     "title" => "您的店鋪已被處罰",
     "action" => "打開商店儀表板",
],
     "invite" => [
     "subject" => ":inviter 邀請你到 Selldone",
     "title" => ":name 向您發送 :amount 以幫助您啟動新的在線網站並從中獲利！",
     "message" => "在 Selldone，您可以創建您的電子商務、博客網站和在線社區，甚至可以在幾分鐘內獲得在線 POS 並設置面對面銷售。它是一個在線業務操作系統，可讓您的業務在線，更好，更快。只需在<b>:date 之前</b>註冊即可獲得 :amount 代金券。",
     "accept" => "接受邀請",
     "owner" => "的主人",
     "join-date" => "自 Selldone 以來",
],
     "shop-recovery" => [
     "subject" => "恢復鏈接 | ：店鋪",
     "category" => "店鋪保安",
     "title" => "存儲<b>:shop_name</b>的恢復鏈接。",
     "message" => "之所以向您發送這封電子郵件，是因為您請求恢復您的商店。單擊下面的鏈接將恢復您的商店和屬於它的所有數據。",
     "action" => "確認商店恢復",
],
     "SR-SeasonalSaving" => [
     "title" => "Selldone 為您的企業節省了多少錢？",
     "sub-title" => "從日期：開始到：結束",
     "infrastructure" => [
     "title" => "基礎設施",
     "subtitle" => "服務器、CDN、存儲和其他雲服務",
],
     "experts" => [
     "title" => "專家和員工",
     "subtitle" => "開發人員、維護和支持",
],
     "total_save" => "總節省的錢",
],
     "SR-SeasonalPerformance" => [
     "title" => "你的表現",
     "sub-title" => "從 :start 到 :end 的業務概覽",
     "new_visitors" => "New Users",
     "returning_visitors" => "返回用戶",
     "shop_views" => "店鋪景觀",
     "baskets" => [
     "title" => "購物車",
     "subtitle" => "報告新購物車的數量",
],
     "products" => [
     "title" => "產品概述",
     "subtitle" => "商店中產品的狀態（按類型）",
     "value_name" => "產品",
],
     "views" => [
     "title" => "Page Views",
     "subtitle" => "網站總瀏覽量",
],
],
     "vendor-order" => [
     "title" => "New Order",
     "message" => "您收到了一份新訂單。請前往供應商面板中的訂單處理頁面。",
     "subject" => "🛍 收到新訂單 | :order_id",
     "your_revenue" => "您的收入",
],
     "vendor-invite" => [
     "title" => "供應商邀請",
     "message" => "您已收到成為 :shop_name 供應商的邀請。您可以透過點擊以下按鈕來接受或拒絕它。",
     "subject" => ":店鋪名稱 |您收到成為我們供應商的邀請",
     "accept" => "接受並成為供應商",
     "reject" => "拒絕",
],
     "shop-email-login" => [
     "subject" => "您的 :shop 登入代碼",
     "header-message" => "我們向您發送這封電子郵件是因為您要求了商店的登入代碼。請在下面找到您的一次性密碼 (OTP)：",
     "footer-message" => "該代碼的有效期為 10 分鐘。如果您沒有請求此登入代碼，請忽略此電子郵件。",
],
     "shop-email-verify-link" => [
     "subject" => "驗證您的電子郵件 | ：店鋪",
     "title" => "電子郵件驗證",
     "header-message" => "嗨：名字，<br>請在 48 小時內點擊按鈕或使用以下連結確認 **:email** 是您的電子郵件地址。",
     "footer-message" => "",
],
     "vendor-products" => [
     "subject" => "產品更新：商店",
     "title" => "產品狀態更新 - 過去 24 小時",
     "message" => "我希望這封郵件對您有好處。這是一個簡短的更新，旨在告知您過去 24 小時內您的產品在我們平台上的狀態。在此期間，部分產品的狀態發生了變化。這些變化可能是由於購買、庫存更新或其他相關事件造成的。有關每個產品的更多詳細信息，請登入您的帳戶並查看“產品狀態”部分。",
     "action" => "打開供應商面板",
],
];