<?php 

 return [
     "accepted" => "The :attribute ຕ້ອງໄດ້ຮັບການຍອມຮັບ.",
     "active_url" => ":attribute ບໍ່ແມ່ນ URL ທີ່ຖືກຕ້ອງ.",
     "after" => ":attribute ຈະຕ້ອງເປັນວັນທີຫຼັງຈາກ :date.",
     "after_or_equal" => "The :attribute ຈະຕ້ອງເປັນວັນທີຫຼັງຈາກ ຫຼືເທົ່າກັບ :date.",
     "alpha" => "The :attribute ອາດມີຕົວອັກສອນເທົ່ານັ້ນ.",
     "alpha_dash" => "ຄຸນສົມບັດ :attribute ອາດມີພຽງຕົວອັກສອນ, ຕົວເລກ, ແລະເຄື່ອງໝາຍຂີດ.",
     "alpha_num" => "The :attribute ອາດມີພຽງຕົວອັກສອນ ແລະຕົວເລກເທົ່ານັ້ນ.",
     "array" => "The :attribute ຈະຕ້ອງເປັນ array.",
     "before" => "The :attribute ຈະຕ້ອງເປັນວັນທີກ່ອນ :date.",
     "before_or_equal" => "The :attribute ຈະຕ້ອງເປັນວັນທີກ່ອນ ຫຼືເທົ່າກັບ :date.",
     "between" => [
     "numeric" => ":attribute ຈະຕ້ອງຢູ່ລະຫວ່າງ :min ແລະ :max.",
     "file" => ":attribute ຈະຕ້ອງຢູ່ລະຫວ່າງ :min ແລະ :max kilobytes.",
     "string" => ":attribute ຈະຕ້ອງຢູ່ລະຫວ່າງ :min ແລະ :max ຕົວອັກສອນ.",
     "array" => ":attribute ຕ້ອງມີລະຫວ່າງ :min ແລະ :max items.",
],
     "boolean" => "ຊ່ອງຂໍ້ມູນ :attribute ຈະຕ້ອງເປັນ true ຫຼື false.",
     "confirmed" => "ການຢືນຢັນ :attribute ບໍ່ກົງກັນ.",
     "date" => ":attribute ບໍ່ແມ່ນວັນທີທີ່ຖືກຕ້ອງ.",
     "date_format" => ":attribute ບໍ່ກົງກັບຮູບແບບ :format.",
     "different" => "The :attribute ແລະ :other ຈະຕ້ອງແຕກຕ່າງກັນ.",
     "digits" => ":attribute ຈະຕ້ອງເປັນ :digits digits.",
     "digits_between" => ":attribute ຈະຕ້ອງຢູ່ລະຫວ່າງ :min ແລະ :max digits.",
     "dimensions" => "The :attribute ມີຂະໜາດຮູບທີ່ບໍ່ຖືກຕ້ອງ.",
     "distinct" => "ຊ່ອງຂໍ້ມູນ :attribute ມີມູນຄ່າຊໍ້າກັນ.",
     "email" => "The :attribute ຈະຕ້ອງເປັນທີ່ຢູ່ອີເມວທີ່ຖືກຕ້ອງ.",
     "exists" => "ທີ່ເລືອກ :attribute ບໍ່ຖືກຕ້ອງ.",
     "file" => ":attribute ຈະຕ້ອງເປັນໄຟລ໌.",
     "filled" => "ຊ່ອງຂໍ້ມູນ :attribute ຕ້ອງມີຄ່າ.",
     "gt" => [
     "numeric" => ":attribute ຈະຕ້ອງໃຫຍ່ກວ່າ :value.",
     "file" => ":attribute ຈະຕ້ອງໃຫຍ່ກວ່າ :value kilobytes.",
     "string" => ":attribute ຈະຕ້ອງໃຫຍ່ກວ່າ :value ຕົວອັກສອນ.",
     "array" => ":attribute ຕ້ອງມີຫຼາຍກວ່າ :value items.",
],
     "gte" => [
     "numeric" => ":attribute ຈະຕ້ອງໃຫຍ່ກວ່າ ຫຼືເທົ່າກັບ :value.",
     "file" => ":attribute ຈະຕ້ອງໃຫຍ່ກວ່າ ຫຼືເທົ່າກັບ :value kilobytes.",
     "string" => ":attribute ຈະຕ້ອງໃຫຍ່ກວ່າ ຫຼືເທົ່າກັບ :value ຕົວອັກສອນ.",
     "array" => ":attribute ຕ້ອງມີ :value items ຫຼືຫຼາຍກວ່ານັ້ນ.",
],
     "image" => "The :attribute ຈະຕ້ອງເປັນຮູບພາບ.",
     "in" => "ທີ່ເລືອກ :attribute ບໍ່ຖືກຕ້ອງ.",
     "in_array" => "ຊ່ອງຂໍ້ມູນ :attribute ບໍ່ມີຢູ່ໃນ :other.",
     "integer" => "The :attribute ຈະຕ້ອງເປັນຈຳນວນເຕັມ.",
     "ip" => ":attribute ຈະຕ້ອງເປັນທີ່ຢູ່ IP ທີ່ຖືກຕ້ອງ.",
     "ipv4" => ":attribute ຈະຕ້ອງເປັນທີ່ຢູ່ IPv4 ທີ່ຖືກຕ້ອງ.",
     "ipv6" => ":attribute ຈະຕ້ອງເປັນທີ່ຢູ່ IPv6 ທີ່ຖືກຕ້ອງ.",
     "json" => ":attribute ຈະຕ້ອງເປັນສະຕຣິງ JSON ທີ່ຖືກຕ້ອງ.",
     "lt" => [
     "numeric" => ":attribute ຈະຕ້ອງໜ້ອຍກວ່າ :value.",
     "file" => ":attribute ຈະຕ້ອງໜ້ອຍກວ່າ :value kilobytes.",
     "string" => ":attribute ຈະຕ້ອງໜ້ອຍກວ່າ :value ຕົວອັກສອນ.",
     "array" => ":attribute ຕ້ອງມີໜ້ອຍກວ່າ :value items.",
],
     "lte" => [
     "numeric" => ":attribute ຈະຕ້ອງໜ້ອຍກວ່າ ຫຼືເທົ່າກັບ :value.",
     "file" => ":attribute ຈະຕ້ອງໜ້ອຍກວ່າ ຫຼືເທົ່າກັບ :value kilobytes.",
     "string" => ":attribute ຈະຕ້ອງໜ້ອຍກວ່າ ຫຼືເທົ່າກັບ :value ຕົວອັກສອນ.",
     "array" => "The :attribute ຈະຕ້ອງບໍ່ມີຫຼາຍກ່ວາ :value items.",
],
     "max" => [
     "numeric" => ":attribute ອາດຈະບໍ່ໃຫຍ່ກວ່າ :max.",
     "file" => ":attribute ອາດຈະບໍ່ໃຫຍ່ກວ່າ :max kilobytes.",
     "string" => ":attribute ອາດຈະບໍ່ໃຫຍ່ກວ່າ :max ຕົວອັກສອນ.",
     "array" => ":attribute ອາດຈະບໍ່ມີຫຼາຍກວ່າ :max items.",
],
     "mimes" => ":attribute ຕ້ອງເປັນໄຟລ໌ປະເພດ: :values.",
     "mimetypes" => ":attribute ຕ້ອງເປັນໄຟລ໌ປະເພດ: :values.",
     "min" => [
     "numeric" => ":attribute ຕ້ອງມີຢ່າງໜ້ອຍ :min.",
     "file" => ":attribute ຕ້ອງມີຢ່າງໜ້ອຍ :min kilobytes.",
     "string" => ":attribute ຕ້ອງມີຢ່າງໜ້ອຍ :min ຕົວອັກສອນ.",
     "array" => ":attribute ຕ້ອງມີຢ່າງໜ້ອຍ :min items.",
],
     "not_in" => "ທີ່ເລືອກ :attribute ບໍ່ຖືກຕ້ອງ.",
     "not_regex" => "ຮູບແບບ :attribute ບໍ່ຖືກຕ້ອງ.",
     "numeric" => "The :attribute ຈະຕ້ອງເປັນຕົວເລກ.",
     "present" => "ຊ່ອງຂໍ້ມູນ :attribute ຕ້ອງມີຢູ່.",
     "regex" => "ຮູບແບບ :attribute ບໍ່ຖືກຕ້ອງ.",
     "required" => "ຕ້ອງລະບຸຊ່ອງຂໍ້ມູນ :attribute.",
     "required_if" => "ຊ່ອງຂໍ້ມູນ :attribute ແມ່ນຕ້ອງການເມື່ອ :other ແມ່ນ :value.",
     "required_unless" => "ຊ່ອງຂໍ້ມູນ :attribute ແມ່ນຕ້ອງການເວັ້ນເສຍແຕ່ວ່າ :other ຢູ່ໃນ :values.",
     "required_with" => "ຊ່ອງຂໍ້ມູນ :attribute ແມ່ນຕ້ອງການເມື່ອ :values ມີຢູ່.",
     "required_with_all" => "ຊ່ອງຂໍ້ມູນ :attribute ແມ່ນຕ້ອງການເມື່ອ :values ມີຢູ່.",
     "required_without" => "ຊ່ອງຂໍ້ມູນ :attribute ແມ່ນຕ້ອງການເມື່ອ :values ບໍ່ມີຢູ່.",
     "required_without_all" => "ຊ່ອງຂໍ້ມູນ :attribute ແມ່ນຕ້ອງການເມື່ອບໍ່ມີ :values ຢູ່.",
     "same" => ":attribute ແລະ :other ຈະຕ້ອງກົງກັນ.",
     "size" => [
     "numeric" => "The :attribute ຈະຕ້ອງເປັນ :size.",
     "file" => ":attribute ຈະຕ້ອງເປັນ :size kilobytes.",
     "string" => ":attribute ຈະຕ້ອງເປັນຕົວອັກສອນ :size.",
     "array" => ":attribute ຕ້ອງມີລາຍການ :size.",
],
     "string" => "The :attribute ຈະຕ້ອງເປັນສະຕຣິງ.",
     "timezone" => "The :attribute ຈະຕ້ອງເປັນເຂດທີ່ຖືກຕ້ອງ.",
     "unique" => ":attribute ໄດ້ຖືກປະຕິບັດແລ້ວ.",
     "uploaded" => ":attribute ລົ້ມເຫລວໃນການອັບໂຫລດ.",
     "url" => "ຮູບແບບ :attribute ບໍ່ຖືກຕ້ອງ.",
     "custom" => [
     "attribute-name" => [
     "rule-name" => "ຂໍ້ຄວາມແບບກຳນົດເອງ",
],
     "g-recaptcha-response" => [
     "required" => "ກະລຸນາກວດສອບວ່າທ່ານບໍ່ແມ່ນຫຸ່ນຍົນ.",
     "captcha" => "Captcha ຜິດພາດ! ກະລຸນາລອງໃໝ່ໃນພາຍຫຼັງ ຫຼືຕິດຕໍ່ຜູ້ເບິ່ງແຍງເວັບໄຊທ໌.",
],
],
     "attributes" => [
        
     ],
];