<?php 

 return [
     "accepted" => "The : atribut kudu ditarima.",
     "accepted_if" => "Widang :atribut kedah ditampi nalika:lain nyaéta:nilai.",
     "active_url" => "The : atribut sanes URL valid.",
     "after" => "The : atribut kudu tanggal sanggeus : date.",
     "after_or_equal" => "Atribut : kudu tanggal sanggeus atawa sarua jeung : tanggal.",
     "alpha" => "Atribut : ngan ukur tiasa ngandung hurup.",
     "alpha_dash" => "Atribut : ngan ukur tiasa ngandung hurup, angka, sareng tanda hubung.",
     "alpha_num" => "Atribut : ngan ukur tiasa ngandung hurup sareng angka.",
     "array" => "Atribut: kedah janten array.",
     "ascii" => "Widang : atribut ngan ukur kedah ngandung karakter sareng simbol alfanumerik bait tunggal.",
     "before" => "Atribut: kedah janten tanggal sateuacan: tanggal.",
     "before_or_equal" => "Atribut: kedah janten tanggal sateuacan atanapi sami sareng: tanggal.",
     "between" => [
     "array" => "The : atribut kudu antara : mnt jeung : max item.",
     "file" => "The : atribut kudu antara : mnt jeung : max kilobytes.",
     "numeric" => "The : atribut kudu antara : mnt jeung : max.",
     "string" => "The : atribut kudu antara : mnt jeung : karakter max.",
],
     "boolean" => "Widang : atribut kedah leres atanapi salah.",
     "can" => "Widang :atribut ngandung nilai anu teu sah.",
     "confirmed" => "Konfirmasi: atribut teu cocog.",
     "contains" => "Widang : atribut leungit nilai anu diperyogikeun.",
     "current_password" => "Sandi lepat.",
     "date" => "The : atribut sanes tanggal valid.",
     "date_equals" => "Widang :atribut kedah janten tanggal anu sami sareng:tanggal.",
     "date_format" => "Atribut: henteu cocog sareng format: format.",
     "decimal" => "Widang : atribut kedah gaduh : tempat desimal desimal.",
     "declined" => "Widang : atribut kedah ditolak.",
     "declined_if" => "Widang :atribut kedah ditolak nalika:lain nyaéta:nilai.",
     "different" => "The : atribut jeung : other kudu béda.",
     "digits" => "The : atribut kudu : digit digit.",
     "digits_between" => "The : atribut kudu antara : mnt jeung : max digit.",
     "dimensions" => "Atribut: gaduh ukuran gambar anu teu valid.",
     "distinct" => "Widang : atribut ngagaduhan nilai duplikat.",
     "doesnt_end_with" => "Widang : atribut teu kudu ditungtungan ku salah sahiji di handap ieu: : nilai.",
     "doesnt_start_with" => "Widang : atribut teu kudu dimimitian ku salah sahiji di handap ieu: : nilai.",
     "email" => "The : atribut kedah alamat surélék nu valid.",
     "ends_with" => "Widang : atribut kudu ditungtungan ku salah sahiji di handap ieu: : nilai.",
     "enum" => "Atribut anu dipilih henteu sah.",
     "exists" => "Atribut anu dipilih henteu sah.",
     "extensions" => "Widang : atribut kedah gaduh salah sahiji ekstensi ieu: : nilai.",
     "file" => "The : atribut kedah file.",
     "filled" => "Widang : atribut kedah gaduh nilai.",
     "gt" => [
     "array" => "Atribut : kudu boga leuwih ti : item nilai.",
     "file" => "Atribut : kudu leuwih gede ti : nilai kilobyte.",
     "numeric" => "The : atribut kudu leuwih gede ti: nilai.",
     "string" => "Atribut : kudu leuwih gede ti : karakter nilai.",
],
     "gte" => [
     "array" => "The : atribut kudu boga : item nilai atawa leuwih.",
     "file" => "Atribut : kudu leuwih gede atawa sarua : nilai kilobyte.",
     "numeric" => "Atribut : kudu leuwih gede atawa sarua : nilai.",
     "string" => "Atribut : kudu leuwih gede atawa sarua : karakter nilai.",
],
     "hex_color" => "Widang : atribut kedah warna héksadesimal anu valid.",
     "image" => "The : atribut kudu gambar.",
     "in" => "Atribut anu dipilih henteu sah.",
     "in_array" => "Widang :atribut teu aya di :lain.",
     "integer" => "Atribut : kudu integer.",
     "ip" => "Atribut : kedah janten alamat IP anu sah.",
     "ipv4" => "Atribut: kedah janten alamat IPv4 anu valid.",
     "ipv6" => "Atribut: kudu alamat IPv6 valid.",
     "json" => "The : atribut kedah janten string JSON valid.",
     "list" => "Widang : atribut kedah janten daptar.",
     "lowercase" => "Widang : atribut kedah hurup leutik.",
     "lt" => [
     "array" => "The : atribut kudu boga kirang ti: item nilai.",
     "file" => "The : atribut kedah kirang ti : nilai kilobytes.",
     "numeric" => "The : atribut kedah kirang ti: nilai.",
     "string" => "The : atribut kedah kirang ti: nilai karakter.",
],
     "lte" => [
     "array" => "The : atribut teu kudu boga leuwih ti: item nilai.",
     "file" => "Atribut :atribut kudu kurang atawa sarua jeung :nilai kilobyte.",
     "numeric" => "Atribut : kudu kurang atawa sarua : nilai.",
     "string" => "Atribut : kudu kurang atawa sarua : karakter nilai.",
],
     "mac_address" => "Widang : atribut kedah alamat MAC anu valid.",
     "max" => [
     "array" => "Atribut: teu tiasa gaduh langkung ti: item maksimal.",
     "file" => "Atribut : bisa jadi teu leuwih gede ti : max kilobytes.",
     "numeric" => "The : atribut teu bisa leuwih gede ti: max.",
     "string" => "The : atribut teu bisa leuwih gede ti: max karakter.",
],
     "max_digits" => "Widang : atribut teu kedah gaduh langkung ti : max digit.",
     "mimes" => "Atribut: kedah janten file tina tipe:: nilai.",
     "mimetypes" => "Atribut: kedah janten file tina tipe:: nilai.",
     "min" => [
     "array" => "The : atribut kudu boga sahanteuna: item mnt.",
     "file" => "The : atribut kedah sahenteuna: mnt kilobytes.",
     "numeric" => "The : atribut kedah sahenteuna: mnt.",
     "string" => "The : atribut kedah sahenteuna : karakter mnt.",
],
     "min_digits" => "Widang : atribut kedah gaduh sahenteuna : min digit.",
     "missing" => "Widang : atribut kedah leungit.",
     "missing_if" => "Widang :atribut kedah leungit nalika:lain nyaéta:nilai.",
     "missing_unless" => "Widang :atribut kedah leungit kecuali:lain nyaéta:nilai.",
     "missing_with" => "Widang : atribut kedah leungit nalika: nilai aya.",
     "missing_with_all" => "Widang : atribut kedah leungit nalika: nilai aya.",
     "multiple_of" => "Widang : atribut kudu mangrupa kelipatan tina : nilai.",
     "not_in" => "Atribut anu dipilih henteu sah.",
     "not_regex" => "Format: atribut teu valid.",
     "numeric" => "Atribut : kudu mangrupa angka.",
     "password" => [
     "letters" => "Widang :atribut kedah ngandung sahenteuna hiji hurup.",
     "mixed" => "Widang :atribut kedah ngandung sahenteuna hiji hurup ageung sareng hiji hurup leutik.",
     "numbers" => "Widang : atribut kudu ngandung sahanteuna hiji angka.",
     "symbols" => "Widang : atribut kudu ngandung sahanteuna hiji simbol.",
     "uncompromised" => "Atribut anu dipasihkeun parantos muncul dina bocor data. Mangga pilih anu béda: atribut.",
],
     "present" => "Widang : atribut kedah aya.",
     "present_if" => "Widang :atribut kedah aya nalika:lain nyaéta:nilai.",
     "present_unless" => "Widang :atribut kedah aya iwal :lain nyaeta :nilai.",
     "present_with" => "Widang : atribut kedah aya nalika : nilai aya.",
     "present_with_all" => "Widang :atribut kedah aya nalika:nilai aya.",
     "prohibited" => "Widang : atribut dilarang.",
     "prohibited_if" => "Widang :atribut dilarang nalika:lain nyaéta:nilai.",
     "prohibited_unless" => "Widang :atribut dilarang iwal:lain aya dina:nilai.",
     "prohibits" => "Widang :atribut ngalarang :lain hadir.",
     "regex" => "Format: atribut teu valid.",
     "required" => "Widang : atribut diperlukeun.",
     "required_array_keys" => "Widang : atribut kedah ngandung éntri pikeun: : nilai.",
     "required_if" => "Widang: atribut diperlukeun nalika: séjén nyaéta: nilai.",
     "required_if_accepted" => "Widang :atribut diperyogikeun nalika:lainna ditarima.",
     "required_if_declined" => "Widang :atribut diperyogikeun nalika:lain ditolak.",
     "required_unless" => "Widang : atribut diperlukeun iwal : lianna aya dina : nilai.",
     "required_with" => "Widang :atribut diperyogikeun nalika:nilai aya.",
     "required_with_all" => "Widang :atribut diperyogikeun nalika:nilai aya.",
     "required_without" => "Widang : atribut diperlukeun nalika : nilai teu aya.",
     "required_without_all" => "Widang :atribut diperyogikeun nalika teu aya: nilai anu aya.",
     "same" => "The : atribut jeung : séjén kudu cocog.",
     "size" => [
     "array" => "The : atribut kedah ngandung: item ukuran.",
     "file" => "The : atribut kudu : ukuran kilobytes.",
     "numeric" => "The : atribut kudu: ukuran.",
     "string" => "The : atribut kudu: karakter ukuran.",
],
     "starts_with" => "Widang : atribut kudu dimimitian ku salah sahiji di handap ieu: : nilai.",
     "string" => "The : atribut kudu string a.",
     "timezone" => "Atribut : kedah janten zona valid.",
     "unique" => "The : atribut geus dicokot.",
     "uploaded" => "Atribut : gagal diunggah.",
     "uppercase" => "Widang : atribut kedah hurup ageung.",
     "url" => "Format: atribut teu valid.",
     "ulid" => "Widang :atribut kedah janten ULID anu valid.",
     "uuid" => "Widang : atribut kedah janten UUID anu valid.",
     "custom" => [
     "attribute-name" => [
     "rule-name" => "custom-pesen",
],
     "g-recaptcha-response" => [
     "required" => "Punten parios yén anjeun sanés robot.",
     "captcha" => "Kasalahan Captcha! cobian deui engké atanapi hubungi admin situs.",
],
],
     "attributes" => [
        
     ],
];