export default {
  "AD": "Andorre",
  "AE": "Émirats arabes unis",
  "AF": "Afghanistan",
  "AG": "Antigua-et-Barbuda",
  "AI": "Anguilla",
  "AL": "Albanie",
  "AM": "Arménie",
  "AO": "Angola",
  "AQ": "Antarctique",
  "AR": "Argentine",
  "AS": "Samoa américaines",
  "AT": "Autriche",
  "AU": "Australie",
  "AW": "Aruba",
  "AX": "Îles Åland",
  "AZ": "Azerbaïdjan",
  "BA": "Bosnie-Herzégovine",
  "BB": "Barbade",
  "BD": "Bangladesh",
  "BE": "Belgique",
  "BF": "Burkina Faso",
  "BG": "Bulgarie",
  "BH": "Bahreïn",
  "BI": "Burundi",
  "BJ": "Bénin",
  "BL": "Saint-Barthélemy",
  "BM": "Bermudes",
  "BN": "Brunéi Darussalam",
  "BO": "Bolivie, État plurinational de",
  "BQ": "Bonaire, Saint-Eustache et Saba",
  "BR": "Brésil",
  "BS": "Bahamas",
  "BT": "Bhoutan",
  "BV": "Ile Bouvet",
  "BW": "Botswana",
  "BY": "Biélorussie",
  "BZ": "Bélize",
  "CA": "Canada",
  "CC": "Îles Cocos (Keeling)",
  "CD": "Congo, République démocratique du",
  "CF": "République centrafricaine",
  "CG": "Congo",
  "CH": "Suisse",
  "CI": "Côte d'Ivoire",
  "CK": "Îles Cook",
  "CL": "Chili",
  "CM": "Cameroun",
  "CN": "Chine",
  "CO": "Colombie",
  "CR": "Costa Rica",
  "CU": "Cuba",
  "CV": "Cap-Vert",
  "CW": "Curaçao",
  "CX": "L'île Christmas",
  "CY": "Chypre",
  "CZ": "Tchéquie",
  "DE": "Allemagne",
  "DJ": "Djibouti",
  "DK": "Danemark",
  "DM": "Dominique",
  "DO": "République dominicaine",
  "DZ": "Algérie",
  "EC": "Équateur",
  "EE": "Estonie",
  "EG": "Egypte",
  "EH": "Sahara occidental",
  "ER": "Érythrée",
  "ES": "Espagne",
  "ET": "Ethiopie",
  "FI": "Finlande",
  "FJ": "Fidji",
  "FK": "Îles Falkland (Malvinas)",
  "FM": "Micronésie, États fédérés de",
  "FO": "Îles Féroé",
  "FR": "France",
  "GA": "Gabon",
  "GB": "Royaume-Uni",
  "GD": "Grenade",
  "GE": "Géorgie",
  "GF": "Guyane française",
  "GG": "Guernesey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Groenland",
  "GM": "Gambie",
  "GN": "Guinée",
  "GP": "Guadeloupe",
  "GQ": "Guinée équatoriale",
  "GR": "Grèce",
  "GS": "Géorgie du Sud et les îles Sandwich du Sud",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinée-Bissau",
  "GY": "Guyane",
  "HK": "Hong Kong",
  "HM": "Îles Heard et McDonald",
  "HN": "Honduras",
  "HR": "Croatie",
  "HT": "Haïti",
  "HU": "Hongrie",
  "ID": "Indonésie",
  "IE": "Irlande",
  "IL": "Israël",
  "IM": "Île de Man",
  "IN": "Inde",
  "IO": "Territoire britannique de l'océan Indien",
  "IQ": "Irak",
  "IR": "L'Iran",
  "IS": "Islande",
  "IT": "Italie",
  "JE": "Jersey",
  "JM": "Jamaïque",
  "JO": "Jordanie",
  "JP": "Japon",
  "KE": "Kenya",
  "KG": "Kirghizistan",
  "KH": "Cambodge",
  "KI": "Kiribati",
  "KM": "Comores",
  "KN": "Saint-Kitts-et-Nevis",
  "KP": "Corée, République populaire démocratique de",
  "KR": "Corée, République de",
  "KW": "Koweit",
  "KY": "Îles Caïmans",
  "KZ": "Kazakhstan",
  "LA": "République démocratique populaire lao",
  "LB": "Liban",
  "LC": "Sainte-Lucie",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Libéria",
  "LS": "Lesotho",
  "LT": "Lituanie",
  "LU": "Luxembourg",
  "LV": "Lettonie",
  "LY": "Libye",
  "MA": "Maroc",
  "MC": "Monaco",
  "MD": "Moldavie, République de",
  "ME": "Monténégro",
  "MF": "Saint Martin, (partie française)",
  "MG": "Madagascar",
  "MH": "Îles Marshall",
  "MK": "Macédoine du Nord",
  "ML": "Mali",
  "MM": "Birmanie",
  "MN": "Mongolie",
  "MO": "Macao",
  "MP": "Îles Mariannes du Nord",
  "MQ": "Martinique",
  "MR": "Mauritanie",
  "MS": "Montserrat",
  "MT": "Malte",
  "MU": "Ile Maurice",
  "MV": "Maldives",
  "MW": "Malawi",
  "MX": "Mexique",
  "MY": "Malaisie",
  "MZ": "Mozambique",
  "NA": "Namibie",
  "NC": "Nouvelle-Calédonie",
  "NE": "Niger",
  "NF": "Île Norfolk",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Pays-Bas",
  "NO": "Norvège",
  "NP": "Népal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Nouvelle-Zélande",
  "OM": "Oman",
  "PA": "Panama",
  "PE": "Pérou",
  "PF": "Polynésie française",
  "PG": "Papouasie-Nouvelle-Guinée",
  "PH": "Philippines",
  "PK": "Pakistan",
  "PL": "Pologne",
  "PM": "Saint-Pierre-et-Miquelon",
  "PN": "Pitcairn",
  "PR": "Porto Rico",
  "PS": "Palestine, État de",
  "PT": "Portugal",
  "PW": "Palaos",
  "PY": "Paraguay",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Roumanie",
  "RS": "Serbie",
  "RU": "Fédération de Russie",
  "RW": "Rwanda",
  "SA": "Arabie Saoudite",
  "SB": "Îles Salomon",
  "SC": "Seychelles",
  "SD": "Soudan",
  "SE": "Suède",
  "SG": "Singapour",
  "SH": "Sainte-Hélène, Ascension et Tristan da Cunha",
  "SI": "Slovénie",
  "SJ": "Svalbard et Jan Mayen",
  "SK": "Slovaquie",
  "SL": "Sierra Leone",
  "SM": "Saint Marin",
  "SN": "Sénégal",
  "SO": "Somalie",
  "SR": "Suriname",
  "SS": "Soudan du Sud",
  "ST": "Sao Tomé-et-Principe",
  "SV": "Le Salvador",
  "SX": "Sint Maarten, (partie néerlandaise)",
  "SY": "République arabe syrienne",
  "SZ": "Eswatini",
  "TC": "Îles Turques-et-Caïques",
  "TD": "Tchad",
  "TF": "Terres Australes Françaises",
  "TG": "Aller",
  "TH": "Thaïlande",
  "TJ": "Tadjikistan",
  "TK": "Tokélaou",
  "TL": "Timor-Leste",
  "TM": "Turkménistan",
  "TN": "Tunisie",
  "TO": "Tonga",
  "TR": "Turquie",
  "TT": "Trinité-et-Tobago",
  "TV": "Tuvalu",
  "TW": "Taïwan, province de Chine",
  "TZ": "Tanzanie, République-Unie de",
  "UA": "Ukraine",
  "UG": "Ouganda",
  "UM": "Îles mineures éloignées des États-Unis",
  "US": "les états-unis d'Amérique",
  "UY": "Uruguay",
  "UZ": "Ouzbékistan",
  "VA": "Saint-Siège",
  "VC": "Saint-Vincent-et-les Grenadines",
  "VE": "Venezuela, République bolivarienne du",
  "VG": "Îles Vierges britanniques",
  "VI": "Îles Vierges, États-Unis",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "WF": "Wallis et Futuna",
  "WS": "Samoa",
  "YE": "Yémen",
  "YT": "Mayotte",
  "ZA": "Afrique du Sud",
  "ZM": "Zambie",
  "ZW": "Zimbabwe"
};