export default {
  "AD": "Andorra",
  "AE": "Uni Emirat Arab",
  "AF": "Afganistan",
  "AG": "Antigua dan Barbuda",
  "AI": "Anguila",
  "AL": "Albania",
  "AM": "Bahasa Indonesia: Armenia",
  "AO": "Indonesia",
  "AQ": "Antartika",
  "AR": "Argentina",
  "AS": "Samoa Amerika",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Bahasa Indonesia: Aruba",
  "AX": "Kepulauan Aland",
  "AZ": "Azerbaijan",
  "BA": "Bosnia dan Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgia",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Bahasa Indonesia: Benin",
  "BL": "Saint Barthelemy",
  "BM": "Bermuda",
  "BN": "Brunei Darussalam",
  "BO": "Bolivia, Negara Plurinasional",
  "BQ": "Bonaire, Sint Eustatius dan Saba",
  "BR": "Brazil",
  "BS": "Bahama",
  "BT": "Bahasa Indonesia: Bhutan",
  "BV": "Pulau Bouvet",
  "BW": "Republik Demokratik Rakyat Botswana",
  "BY": "Belarusia",
  "BZ": "Belize",
  "CA": "Kanada",
  "CC": "Kepulauan Cocos (Keeling)",
  "CD": "Kongo, Republik Demokratik",
  "CF": "Republik Afrika Tengah",
  "CG": "Kongo",
  "CH": "Swiss",
  "CI": "Pantai Gading",
  "CK": "Kepulauan Cook",
  "CL": "Chili",
  "CM": "Kamerun",
  "CN": "Cina",
  "CO": "Kolumbia",
  "CR": "Kosta Rika",
  "CU": "Kuba",
  "CV": "Tanjung Verde",
  "CW": "Curacao, Amerika Serikat",
  "CX": "Pulau Natal",
  "CY": "Siprus",
  "CZ": "Republik Ceko",
  "DE": "Jerman",
  "DJ": "Jibuti",
  "DK": "Denmark",
  "DM": "Dominika",
  "DO": "Republik Dominika",
  "DZ": "Aljazair",
  "EC": "Ekuador",
  "EE": "Estonia",
  "EG": "Mesir",
  "EH": "Sahara Barat",
  "ER": "Eritrea",
  "ES": "Spanyol",
  "ET": "Etiopia",
  "FI": "Finlandia",
  "FJ": "Indonesia",
  "FK": "Kepulauan Falkland (Malvinas)",
  "FM": "Mikronesia, Negara Federasi",
  "FO": "Kepulauan Faroe",
  "FR": "Perancis",
  "GA": "Bahasa Indonesia: Gabon",
  "GB": "Inggris Raya",
  "GD": "Grenada",
  "GE": "Bahasa Indonesia: Georgia",
  "GF": "Guyana Prancis",
  "GG": "Bahasa Indonesia: Guernsey",
  "GH": "Indonesia",
  "GI": "Bahasa Indonesia: Gibraltar",
  "GL": "Tanah penggembalaan",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Guinea Khatulistiwa",
  "GR": "Yunani",
  "GS": "Georgia Selatan dan Kepulauan Sandwich Selatan",
  "GT": "Guatemala",
  "GU": "Bahasa Indonesia: Guam",
  "GW": "Guinea Bissau",
  "GY": "Guyana",
  "HK": "Hongkong",
  "HM": "Pulau Heard dan Kepulauan McDonald",
  "HN": "Honduras",
  "HR": "Kroasia",
  "HT": "Haiti",
  "HU": "Hongaria",
  "ID": "Indonesia",
  "IE": "Irlandia",
  "IL": "Israel",
  "IM": "Pulau Man",
  "IN": "India",
  "IO": "Wilayah Samudra Hindia Britania",
  "IQ": "Irak",
  "IR": "Bahasa Indonesia:Iran",
  "IS": "Islandia",
  "IT": "Italia",
  "JE": "Baju jersey",
  "JM": "Jamaika",
  "JO": "Yordania",
  "JP": "Jepang",
  "KE": "Bahasa Indonesia: Kenya",
  "KG": "Kirgistan",
  "KH": "Kamboja",
  "KI": "Bahasa Indonesia: Kiribati",
  "KM": "Komoro",
  "KN": "Saint Kitts dan Nevis",
  "KP": "Korea, Republik Rakyat Demokratik",
  "KR": "Korea, Republik",
  "KW": "Bahasa Indonesia: Kuwait",
  "KY": "Kepulauan Cayman",
  "KZ": "Kazakstan",
  "LA": "Republik Demokratik Rakyat Laos",
  "LB": "Libanon",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Srilanka",
  "LR": "Liberia",
  "LS": "Indonesia",
  "LT": "Lithuania",
  "LU": "Luksemburg",
  "LV": "Latvia",
  "LY": "Libya",
  "MA": "Maroko",
  "MC": "Monako",
  "MD": "Republik Moldova",
  "ME": "Montenegro",
  "MF": "Saint Martin, (bagian Prancis)",
  "MG": "Madagaskar",
  "MH": "Kepulauan Marshall",
  "MK": "Makedonia Utara",
  "ML": "Bahasa Mali",
  "MM": "Myanmar",
  "MN": "Mongolia",
  "MO": "Makau",
  "MP": "Kepulauan Mariana Utara",
  "MQ": "Martinik",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maladewa",
  "MW": "Malawi",
  "MX": "Meksiko",
  "MY": "Malaysia",
  "MZ": "Mozambik",
  "NA": "Namibia",
  "NC": "Kaledonia Baru",
  "NE": "Bahasa Indonesia: Nigeria",
  "NF": "Pulau Norfolk",
  "NG": "Nigeria",
  "NI": "Nikaragua",
  "NL": "Belanda",
  "NO": "Norway",
  "NP": "Nepal",
  "NR": "Bahasa Indonesia: Nauru",
  "NU": "Bahasa Niue",
  "NZ": "Selandia Baru",
  "OM": "Bahasa Indonesia:",
  "PA": "Panama",
  "PE": "Bahasa Indonesia: Peru",
  "PF": "Polinesia Prancis",
  "PG": "Papua Nugini",
  "PH": "Filipina",
  "PK": "Pakistan",
  "PL": "Polandia",
  "PM": "Saint Pierre dan Miquelon",
  "PN": "Pulau Pitcairn",
  "PR": "Puerto Riko",
  "PS": "Palestina, Negara",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Bahasa Indonesia: Paraguay",
  "QA": "Bahasa Indonesia: Qatar",
  "RE": "Reuni",
  "RO": "Rumania",
  "RS": "Serbia",
  "RU": "Federasi Rusia",
  "RW": "Rwanda",
  "SA": "Arab Saudi",
  "SB": "Kepulauan Solomon",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Swedia",
  "SG": "Singapura",
  "SH": "Saint Helena, Ascension dan Tristan da Cunha",
  "SI": "Slovenia",
  "SJ": "Svalbard dan Jan Mayen",
  "SK": "Slowakia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Indonesia",
  "SR": "Suriname",
  "SS": "Sudan Selatan",
  "ST": "Sao Tome dan Principe",
  "SV": "El Salvador",
  "SX": "Sint Maarten, (bagian Belanda)",
  "SY": "Republik Arab Suriah",
  "SZ": "Bahasa Eswatini",
  "TC": "Kepulauan Turks dan Caicos",
  "TD": "Bahasa Indonesia: Chad",
  "TF": "Wilayah Selatan Prancis",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tajikistan",
  "TK": "Tokelau",
  "TL": "Timor Leste",
  "TM": "Turkmenistan",
  "TN": "Turki",
  "TO": "Bahasa Tonga",
  "TR": "Turki",
  "TT": "Trinidad dan Tobago",
  "TV": "Bahasa Indonesia: Tuvalu",
  "TW": "Taiwan, Provinsi Tiongkok",
  "TZ": "Tanzania, Republik Bersatu",
  "UA": "Ukraina",
  "UG": "Indonesia",
  "UM": "Kepulauan Kecil Terluar Amerika Serikat",
  "US": "Amerika Serikat",
  "UY": "Bahasa Indonesia:",
  "UZ": "Bahasa Indonesia: Uzbek",
  "VA": "Takhta Suci",
  "VC": "Saint Vincent dan Grenadines",
  "VE": "Venezuela, Republik Bolivarian",
  "VG": "Kepulauan Virgin, Inggris",
  "VI": "Kepulauan Virgin, AS",
  "VN": "Vietnam",
  "VU": "Indonesia",
  "WF": "Wallis dan Futuna",
  "WS": "Bahasa Indonesia: Samoa",
  "YE": "Yaman",
  "YT": "Kota Mayotte",
  "ZA": "Afrika Selatan",
  "ZM": "Zambia",
  "ZW": "zimbabwe"
};