<?php 

 return [
     "home" => "vendido",
     "blogs" => "Blog",
     "helps" => "Axuda",
     "current_location" => "Esta entrada",
     "dashboard" => "dashboard",
     "my_shops" => "As miñas tendas",
     "wallet" => "wallet",
     "about" => "Sobre Selldone",
     "contact" => "contact us",
     "comments" => "comments",
     "likes" => "Gústame",
     "power" => "ánimo",
     "build_free_shop" => "Crea a túa tenda de balde",
     "shop_name" => "shop name",
     "categories" => "categories",
     "sub_articles" => "More",
     "terms" => "Termos",
     "colour" => "cor",
     "style" => "style",
     "volume" => "volume",
     "weight" => "weight",
     "pack" => "Pack",
     "type" => "type",
     "add_to_card" => "Engadir á cesta",
     "overview" => "Overview",
     "reviews" => "Recensións",
     "spec" => "Especificación completa",
     "you_may_also_like" => "Tamén che pode gustar",
     "about_us" => "Sobre nós",
     "contact_us" => "contact us",
     "cookie_privacy" => "Cookie &amp; privacy policy",
     "follow_us" => "Síguenos",
     "category" => "Categoría",
     "author" => "Written by ",
     "published_at" => "Publicado en",
     "modified_at" => "Modificado en",
     "price" => "prezo",
     "discount" => "Desconto",
     "price_after_discount" => "Prezo despois do desconto",
     "available" => "Dispoñible",
     "sold_out" => "Vendido",
     "buy" => "Compre agora",
     "login_shop" => "Iniciar sesión na tenda",
     "posted_on" => "Publicado en :date",
];