<?php 

 return [
     "profile" => "Le a información do perfil, incluíndo nome, enderezo de correo electrónico, imaxe e estado de autenticación.",
     "phone" => "Acceso ao número de contacto",
     "address" => "Le e edita o enderezo da axenda de enderezos gardada",
     "buy" => "Orde e pedido da tenda.",
     "order-history" => "Ler o historial de pedidos.",
     "my-gift-cards" => "Access to my cards.",
     "articles" => "Editar artigos.",
     "notifications" => "Enviar e recibir notificacións.",
     "read-shops" => "Ler a lista de tendas.",
     "shop-edit" => "Acceso á edición da tenda.",
     "shop-contacts" => "Recibir e editar formularios de contacto.",
     "shop-gift-cards" => "Creación, edición e xestión de tarxetas.",
     "shop-faqs" => "Crea, edita e xestiona as preguntas máis frecuentes.",
     "shop-categories" => "Creación, edición e xestión de categorías.",
     "shop-products" => "Creación, edición e xestión de produtos.",
     "shop-read-reports" => "Ler información e informes.",
     "shop-socials" => "Editar as redes sociais da tenda.",
     "shop-accounts" => "Edita e elimina contas financeiras vinculadas a tendas.",
     "shop-menus" => "Editar menús da tenda.",
     "shop-pages" => "Editar páxinas da tenda.",
     "shop-warehouse" => "Editar almacén almacén",
     "shop-permissions" => "Consulta e edita o acceso á tenda.",
     "shop-process-center" => "Xestionar pedidos recibidos.",
     "shop-profile" => "Xestionar perfís de tenda.",
     "shop-discount-code" => "Xestionar códigos de desconto.",
     "shop-coupon" => "Xestionar cupóns.",
     "shop-offer" => "Xestionar ofertas.",
     "shop-lottery" => "Xestionar loterías.",
     "shop-community" => "Xestionar comunidade.",
];