<?php 

 return [
     "accepted" => "Debe aceptarse o atributo :.",
     "active_url" => "O :attribute non é un URL válido.",
     "after" => "O atributo : debe ser unha data posterior a :date.",
     "after_or_equal" => "O atributo : debe ser unha data posterior ou igual a :date.",
     "alpha" => "O atributo : só pode conter letras.",
     "alpha_dash" => "O atributo : só pode conter letras, números e guións.",
     "alpha_num" => "O atributo : só pode conter letras e números.",
     "array" => "O atributo : debe ser unha matriz.",
     "before" => "O atributo : debe ser unha data anterior a :date.",
     "before_or_equal" => "O atributo : debe ser unha data anterior ou igual a :date.",
     "between" => [
     "numeric" => "O atributo : debe estar entre :min e :max.",
     "file" => "O atributo : debe estar entre :min e :max kilobytes.",
     "string" => "O atributo : debe estar entre os caracteres :min e :max.",
     "array" => "O atributo : debe ter entre elementos :min e :max.",
],
     "boolean" => "O campo :attribute debe ser verdadeiro ou falso.",
     "confirmed" => "A confirmación :attribute non coincide.",
     "date" => "O atributo : non é unha data válida.",
     "date_format" => "O atributo : non coincide co formato :format.",
     "different" => "O :attribute e :other deben ser diferentes.",
     "digits" => "O atributo : debe ser díxitos :digits.",
     "digits_between" => "O atributo : debe estar entre os díxitos :min e :max.",
     "dimensions" => "O atributo : ten dimensións de imaxe non válidas.",
     "distinct" => "O campo :attribute ten un valor duplicado.",
     "email" => "O atributo : debe ser un enderezo de correo electrónico válido.",
     "exists" => "O atributo : seleccionado non é válido.",
     "file" => "O atributo : debe ser un ficheiro.",
     "filled" => "O campo :attribute debe ter un valor.",
     "gt" => [
     "numeric" => "O atributo : debe ser maior que :value.",
     "file" => "O :attribute debe ser maior que :value kilobytes.",
     "string" => "O atributo : debe ser maior que os caracteres :value.",
     "array" => "O atributo : debe ter máis de elementos : valor.",
],
     "gte" => [
     "numeric" => "O atributo : debe ser maior ou igual que :value.",
     "file" => "O atributo : debe ser maior ou igual que :value kilobytes.",
     "string" => "O atributo : debe ser maior ou igual que os caracteres :value.",
     "array" => "O atributo : debe ter elementos :value ou máis.",
],
     "image" => "O atributo : debe ser unha imaxe.",
     "in" => "O atributo : seleccionado non é válido.",
     "in_array" => "O campo :attribute non existe en :other.",
     "integer" => "O atributo : debe ser un número enteiro.",
     "ip" => "O atributo : debe ser un enderezo IP válido.",
     "ipv4" => "O atributo : debe ser un enderezo IPv4 válido.",
     "ipv6" => "O atributo : debe ser un enderezo IPv6 válido.",
     "json" => "O atributo : debe ser unha cadea JSON válida.",
     "lt" => [
     "numeric" => "O atributo : debe ser menor que :value.",
     "file" => "O atributo : debe ser inferior a :value kilobytes.",
     "string" => "O atributo : debe ter menos de caracteres :value.",
     "array" => "O atributo : debe ter menos de elementos :value.",
],
     "lte" => [
     "numeric" => "O atributo : debe ser menor ou igual que :value.",
     "file" => "O atributo : debe ser menor ou igual que :value kilobytes.",
     "string" => "O atributo : debe ser inferior ou igual aos caracteres :value.",
     "array" => "O atributo :non debe ter máis de elementos :value.",
],
     "max" => [
     "numeric" => "O atributo :non pode ser maior que :max.",
     "file" => "O atributo :non pode ser maior que :max kilobytes.",
     "string" => "O atributo :non pode ser maior que os caracteres :max.",
     "array" => "O atributo :non pode ter máis de elementos :max.",
],
     "mimes" => "O atributo : debe ser un ficheiro de tipo: :values.",
     "mimetypes" => "O atributo : debe ser un ficheiro de tipo: :values.",
     "min" => [
     "numeric" => "O atributo : debe ser polo menos :min.",
     "file" => "O atributo : debe ser polo menos : min kilobytes.",
     "string" => "O atributo : debe ter polo menos caracteres :min.",
     "array" => "O atributo : debe ter polo menos elementos :min.",
],
     "not_in" => "O atributo : seleccionado non é válido.",
     "not_regex" => "O formato :attribute non é válido.",
     "numeric" => "O atributo : debe ser un número.",
     "present" => "O campo :attribute debe estar presente.",
     "regex" => "O formato :attribute non é válido.",
     "required" => "O campo :attribute é obrigatorio.",
     "required_if" => "O campo :attribute é obrigatorio cando :other é :value.",
     "required_unless" => "O campo :attribute é obrigatorio a menos que :other estea en :values.",
     "required_with" => "O campo :attribute é obrigatorio cando :values está presente.",
     "required_with_all" => "O campo :attribute é obrigatorio cando :values está presente.",
     "required_without" => "O campo :attribute é obrigatorio cando :values non está presente.",
     "required_without_all" => "O campo :attribute é obrigatorio cando ningún dos :values está presente.",
     "same" => "O :attribute e :other deben coincidir.",
     "size" => [
     "numeric" => "O atributo : debe ser :size.",
     "file" => "O atributo : debe ser :size kilobytes.",
     "string" => "O atributo : debe ser caracteres :size.",
     "array" => "O atributo : debe conter elementos :size.",
],
     "string" => "O atributo : debe ser unha cadea.",
     "timezone" => "O atributo : debe ser unha zona válida.",
     "unique" => "Xa se tomou o atributo :.",
     "uploaded" => "Non se puido cargar o atributo :.",
     "url" => "O formato :attribute non é válido.",
     "custom" => [
     "attribute-name" => [
     "rule-name" => "mensaxe personalizada",
],
     "g-recaptcha-response" => [
     "required" => "Verifique que non es un robot.",
     "captcha" => "Erro de captcha! téntao de novo máis tarde ou ponte en contacto co administrador do sitio.",
],
],
     "attributes" => [
        
     ],
];