<?php 

 return [
     "email-types-description" => [
     "shop-customer-join" => "Ujumbe huu unakaribisha mnunuzi mpya kwenye duka.",
     "order-checkout" => "Arifa hii inatumwa wakati mnunuzi anathibitisha agizo.",
     "order-payment" => "Arifa hii inathibitisha malipo yaliyofaulu yaliyofanywa na mteja.",
     "order-payment-admin" => "Ujumbe huu unatumwa kwa muuzaji ili kuwaarifu kuhusu agizo lililothibitishwa.",
     "pos-checkout" => "Arifa hii inatumwa ili kuthibitisha eneo la mauzo kwa mnunuzi.",
     "pos-payment" => "Arifa hii inathibitisha malipo ya mauzo yaliyofanywa na mnunuzi.",
     "pos-payment-admin" => "Ujumbe huu unamjulisha muuzaji kuhusu ununuzi uliofanywa katika eneo lao la mauzo.",
     "shop-contact" => "Arifa hii inatumwa wakati fomu ya mawasiliano imewasilishwa.",
     "shop-giftcard" => "Arifa hii hufahamisha mtumiaji kuwa amepokea kadi ya zawadi.",
     "shop-vendor-join" => "Ujumbe huu unakaribisha mchuuzi mpya kwenye duka.",
     "shop-vendor-invite" => "Ujumbe huu unatumwa ili kumwalika mchuuzi ajiunge na soko lako.",
     "shop-vendor-order" => "Ujumbe huu hutumwa kwa muuzaji agizo linapopokelewa katika hali ya Kulipiwa au Pesa kwenye Utumaji (COD).",
     "shop-vendor-products" => "Hutumwa kila siku ili kusasisha wachuuzi kuhusu hali ya bidhaa zao.",
     "shop-login" => "Mjulishe mtumiaji kwa maelezo ya kuingia, ikiwa ni pamoja na anwani ya IP, tarehe na kifaa, kwa madhumuni ya usalama.",
     "login-code" => "Tuma msimbo wa nenosiri wa mara moja ili watumiaji waingie kwenye duka.",
     "shop-email-verify-link" => "Tuma kiungo ili kuthibitisha anwani ya barua pepe ya mtumiaji. Barua hii hutumwa mtumiaji anapojiandikisha kwa SMS na kuingiza barua pepe zake na haitumiwi mtumiaji anapojiandikisha kwa njia ya kijamii au barua pepe moja kwa moja.",
],
     "global" => [
     "greetings" => "Hi: jina",
     "end-statement" => "Timu ya usaidizi",
     "receiver_name" => "Habari :jina_la_mtumiaji",
     "footer-help" => "Je, unahitaji usaidizi? Uliza kwa [support@selldone.com](mailto:support@selldone.com) au tembelea [kituo chetu cha usaidizi](https://selldone.com/help)",
     "footer-shop" => "Ikiwa unahitaji usaidizi wa jambo lolote tafadhali usisite kututumia barua pepe: :shop_mail",
     "accept" => "Kubali",
     "reject" => "Kataa",
     "verify" => "thibitisha",
     "title" => "Kichwa",
     "value" => "Thamani",
     "description" => "Maelezo",
     "Shop" => "Duka",
     "user" => "Mtumiaji",
     "license" => "Leseni",
     "status" => "Hali",
     "start" => "Anza",
     "end" => "Mwisho",
     "renewal" => "Upya",
     "view" => "Tazama",
     "balance" => "Mizani",
     "card_number" => "Namba ya kadi",
     "cvv" => "Cvv",
     "expire_date" => "Tarehe ya mwisho wa matumizi",
     "dashboard" => "dashibodi",
     "order" => "agizo",
     "view_order" => "Tazama agizo",
     "pay_now" => "Pay now",
     "official_selldone" => "IMEUZWA RASMI",
     "account-number" => "Account number",
     "account-name" => "Account name",
     "currency" => "Sarafu",
     "free-balance" => "Mizani ya bure",
     "locked-balance" => "Salio lililofungwa",
     "bot" => "Bot",
     "requests" => "Maombi",
     "baskets" => "Mikokoteni",
     "physical" => "Kimwili",
     "virtual" => "Mtandaoni",
     "file" => "Faili",
     "service" => "Huduma",
     "fulfillment" => "Utimilifu",
     "open" => "Fungua",
     "reserved" => "Imehifadhiwa",
     "canceled" => "Imeghairiwa",
     "payed" => "Imelipwa",
     "cod" => "COD",
     "orders-count" => "Maagizo",
     "payments-count" => "Malipo",
     "confirms-count" => "Inathibitisha",
     "sends-count" => "Inatuma",
     "delivers-count" => "Inatoa",
     "count" => "Hesabu",
     "transactions-count" => "Idadi ya miamala",
     "success-transactions" => "Shughuli za mafanikio",
     "total-amount" => "Jumla",
     "amount" => "Kiasi",
     "wage" => "Mshahara",
     "debug" => "Tatua",
     "pos" => "POS",
     "live" => "Ishi",
     "CheckQueue" => "Angalia foleni",
     "OrderConfirm" => "Agizo thibitisha",
     "PreparingOrder" => "Kuandaa utaratibu",
     "SentOrder" => "Agizo lililotumwa",
     "ToCustomer" => "Imewasilishwa kwa mteja",
     "Pending" => "Inasubiri",
     "Accepted" => "Imekubaliwa",
     "Rejected" => "Imekataliwa",
     "pc" => "PC",
     "tablet" => "Kompyuta kibao",
     "phone" => "Simu",
     "total" => "Jumla",
     "view-detail" => "Tazama maelezo",
     "empty" => "Tupu",
     "dropshipping" => "Dropshipping",
     "reply" => "Jibu",
     "reactions" => "Miitikio",
     "comments" => "maoni",
     "last-comment" => "Maoni ya mwisho",
     "response-to" => "Jibu kwa",
     "posts" => "Machapisho",
     "post" => "Chapisha",
     "name" => "Jina",
     "email" => "Barua pepe",
     "type" => "aina",
     "device" => "Kifaa",
     "platform" => "Jukwaa",
     "browser" => "Kivinjari",
     "time" => "Wakati",
     "wallet" => "pochi",
     "date" => "Tarehe",
     "account" => "Akaunti",
     "transaction" => "Shughuli",
     "fee" => "Ada",
     "location" => "Location",
     "ip" => "IP",
     "bill" => "Bill",
     "category" => "Kategoria",
     "password" => "Nenosiri",
     "shop" => "Duka",
     "verify-login" => "Thibitisha na Uingie",
     "url" => "URL",
     "avocado" => "Parachichi",
     "hyper" => "Hyper",
     "buy-now" => "Nunua Sasa",
     "add-domain" => "Add Domain",
     "views" => "Maoni",
     "country" => "Nchi",
     "address" => "anwani",
     "postal" => "Msimbo wa Posta",
     "building_no" => "Jengo #",
     "building_unit" => "Kitengo #",
     "message" => "Ujumbe",
     "customer" => "Mteja",
     "cart-items" => "Vitu vya gari",
     "payment" => "Malipo",
     "receiver" => "Mpokeaji",
     "virtual-items" => "Vipengee pepe",
     "no-payment" => "Hakuna malipo!",
     "enable" => "Washa",
     "access" => "Ufikiaji",
     "bank" => "Taarifa za benki",
     "vendor" => "Mchuuzi",
     "view_content" => "Tazama maudhui kamili",
     "files" => "Mafaili",
     "download" => "Pakua",
     "file_name" => "Jina la Faili",
     "file_size" => "Ukubwa",
     "subscription" => "Usajili",
     "products" => "Bidhaa",
     "vendor_products" => "Bidhaa za Wauzaji",
],
     "selldone-business-os" => "Selldone Business OS",
     "senders" => [
     "WeeklyReport" => [
     "id" => "performance",
     "name" => "Ripoti ya Utendaji, Selldone",
],
     "SeasonalReport" => [
     "id" => "seasonal",
     "name" => "Ripoti ya Msimu, Selldone",
],
     "Onboarding" => [
     "id" => "habari",
     "name" => "Idhinisha, Selldone",
],
     "Support" => [
     "id" => "support",
     "name" => "Msaada: jina",
],
     "EmailVerify" => [
     "id" => "verify",
     "name" => "Thibitisha, Selldone",
],
     "Welcome" => [
     "id" => "habari",
     "name" => "Jumuiya, Selldone",
],
     "NewShop" => [
     "id" => "wafanyabiashara",
     "name" => "Idhinisha, Selldone",
],
     "Approve" => [
     "id" => "kuidhinisha",
     "name" => "Idhinisha, Selldone",
],
     "SellerReceiveOrder" => [
     "id" => "order",
     "name" => "Usimamizi wa maagizo: jina",
],
     "Recovery" => [
     "id" => "kupona",
     "name" => "Timu ya Urejeshaji ya Selldone",
],
],
     "bill-status" => [
     "PENDING" => "Inasubiri ⌛",
     "PAYED" => "Imelipwa ✅",
     "CANCELED" => "Imeghairiwa ❌",
],
     "shop-invite" => [
     "LEVEL-NAME" => [
     "ADMIN" => "Msimamizi",
     "OFFICER" => "Afisa na Msimamizi",
     "AUDITING" => "Meneja wa ukaguzi",
     "EMPLOYEE" => "Mfanyakazi",
     "PRODUCT" => "Meneja wa bidhaa",
     "CONTENT" => "Kidhibiti maudhui",
     "MARKETING" => "Meneja masoko",
     "VIEWER" => "Mtazamaji",
],
     "subject" => ":mwalikaji Anakualika kama :level | :Duka",
     "category" => "Mwaliko wa wafanyakazi",
     "title" => "Umealikwa <b>:shop_name</b> kama <b>:level</b> .",
     "message" => "Mwaliko umetumwa kwako. Unaweza kuithibitisha au kuikataa. Ikiwa mwaliko huu umeidhinishwa na wewe, lazima uweke huduma ya Selldone ili kuithibitisha. Kwa kuthibitisha mwaliko huu, utakuwa na idhini ya kufikia sehemu ya usimamizi wa duka.",
],
     "welcome-email" => [
     "subject" => "👋 Karibu :jina, Baadhi ya mambo ya kuvutia kwa ajili yako tu.",
     "category" => "CONGRATULATION",
     "title" => "KARIBU UUZWE",
     "message" => "Asante kwa kuchagua Selldone, Sasa wewe ni sehemu ya jumuiya ya Selldone inayounganisha wauzaji wa kimataifa na wateja, Biashara ya ndani kwa biashara, Mtu binafsi kwa shirika! Zana zote kuu na za kitaalamu zimetolewa **bila malipo** na **bila kikomo** kwa ajili yako. Unajaribu, tunafungua milango, Fanya tu!",
     "seller" => [
     "title" => "Je, wewe ni muuzaji?",
     "message" => "Ili kuanza kuuza, weka dashibodi yako katika Selldone kupitia kiungo kilicho hapa chini na uunde duka lako la kwanza bila malipo kabisa. Hii itachukua dakika chache na utakuwa na duka lako mwenyewe na tovuti ya mtandaoni. Kisha tutakuongoza kwa hatua zinazofuata na kupata lango la malipo.",
     "action" => "Ingia kwenye dashibodi yangu",
],
     "buyer" => [
     "title" => "Mimi ni mnunuzi",
     "message" => "Hongera sana. Ukishakuwa mwanachama wa Selldone, utaondoa kero zote za uanachama na uthibitishaji katika maduka ya mtandaoni. Ili kufaidika na duka na tovuti yoyote inayotumia jukwaa la Selldone, unaweza kuingia kwa mbofyo mmoja na kufanya ununuzi wako kuwa rahisi, haraka na salama.",
],
],
     "charge-account" => [
     "category" => "Wallet > Akaunti > Chaji",
     "title" => "Malipo ya Mafanikio",
     "message" => "Akaunti yako <b>:account_number</b> imefanikiwa <b>:kiasi kilichotozwa</b> .",
     "account" => "Akaunti",
     "charge" => "Malipo",
     "balance" => "Mizani",
     "footer" => "Fanya biashara iwe rahisi, iweze kufikiwa na kufikiwa na mtu yeyote duniani kote.",
],
     "verify-email" => [
     "subject" => "🙌 Kamilisha kujisajili kwa Selldone! Thibitisha kiungo.",
     "category" => "UKO HATUA MOJA",
     "title" => "Thibitisha anwani yako ya barua pepe",
     "message" => "Hi: jina,<br> Asante kwa kuchagua Selldone.<br> Tafadhali thibitisha kwamba **:barua pepe** ni anwani yako ya barua pepe kwa kubofya kitufe au tumia kiungo kilicho hapa chini ndani ya saa 48.",
     "footer" => "Ikiwa unatatizika kubofya kitufe cha Thibitisha, nakili na ubandike URL hapa chini kwenye kivinjari chako cha wavuti: __:activation_url__",
],
     "verify-email-code" => [
     "subject" => "Nambari ya uthibitishaji ya :name",
     "category" => "SECURITY",
     "title" => "Nambari ya uthibitishaji ya barua pepe",
     "message" => "Hi: jina,<br><br> Tafadhali thibitisha kwamba **:barua pepe** ni anwani yako ya barua pepe kwa msimbo huu ndani ya dakika 10.",
],
     "onboarding-verify-email" => [
     "subject" => "🎉 Duka Lako Liko Tayari | :jina",
     "category" => "UKO HATUA MOJA",
     "title" => "Usanidi umekamilika",
     "account_title" => "Akaunti yako",
     "account_msg" => "Thibitisha na uingie kwenye akaunti yako kwa maelezo haya.",
     "shop_msg" => "Maelezo ya akaunti kwenye mfumo wa uendeshaji wa biashara wa Selldone.",
],
     "reset2fa" => [
     "category" => "UJUMBE RASMI WA USALAMA",
     "title" => "Omba lemaza kuingia kwa hatua 2",
     "message" => "Unapokea barua pepe hii kwa sababu tulipokea ombi la kuweka upya uthibitishaji wa sababu 2 kwa akaunti yako.<br><br> Barua pepe ya mtumiaji: <b>:email</b><br> Jina <b>:: jina</b>",
     "footer" => "Ikiwa hukuomba kuweka upya nenosiri, hakuna hatua zaidi inayohitajika.",
     "action" => "Zima kuingia kwa hatua mbili",
],
     "build-new-shop" => [
     "subject" => "🎊 Duka lako liko tayari sasa!",
     "category" => "KUZALIWA DUKA MPYA MTANDAONI DUNIANI",
     "title" => "Kusherehekea",
     "message" => "<b>Hongera :jina, umeunda biashara mpya mtandaoni;</b> Tunakutakia mafanikio katika biashara yako. Karibu kwa Jumuiya ya Wauzaji.<br> Unajaribu, tunafungua milango, na Ulifanya hivyo.",
     "pdf-book" => "Usikose kitabu kilichoambatishwa cha mkono: Fanya Biashara Yako Kama Mchezo",
     "account" => [
     "title" => "Hatua ya 1: Fungua akaunti katika pochi ya Selldone",
     "message" => "Ikiwa huna akaunti kwenye mkoba wako, fungua moja. Selldone inakata ada kutoka kwa akaunti hii. Unaweza kujaza akaunti hii, na Selldone pia itakutoza kiasi cha mkopo ili ikiwa akaunti hii ni hasi, tovuti na Duka lako litaendelea kufanya kazi.",
     "action" => "Ingia kwenye mkoba",
],
     "shop-account" => [
     "title" => "Hatua ya 2: unganisha akaunti kwenye duka",
     "message" => "Ongeza akaunti yako ya pochi kwenye duka lako. Ili kufanya hivyo, ingiza Hifadhi > Uhasibu > Ankara na uunganishe akaunti kwenye duka. Kumbuka kuwa malipo yote ya wateja wako yanawekwa moja kwa moja kwenye akaunti yako ya benki na hakuna kiasi kinachotolewa au kukatwa na Selldone, kwa hivyo unahitaji kuunganisha akaunti hii ya Selldone kwenye duka.",
     "action" => "Hifadhi Paneli ya ankara",
],
     "gateway" => [
     "title" => "Hatua ya 3: Unganisha Lango la Kulipa Mtandaoni",
     "message" => "Nenda kwa Store> Accounting> Port na ubonyeze <b>Ongeza New Port</b> . Baada ya kuchagua sarafu, utaonyeshwa orodha ya bandari zinazobebeka. Kuunganisha bandari katika Selldone ni rahisi sana na haraka, lakini ikiwa una Niza kwa mwongozo, rejelea sehemu ya mwongozo ya Selldone au utuulize.",
     "action" => "Ongeza lango kwenye duka",
],
     "domain" => [
     "title" => "Hatua ya mwisho: kuunganisha kikoa maalum",
     "message" => "Utaweza kuwa na duka lako kwenye vikoa vingi unavyotaka. Ili kuunganisha kikoa maalum kwenye duka, unahitaji kuwa na angalau leseni ya kuanzisha. Kwa kumtambulisha kila rafiki kwa Selldone, utapokea kadi ya zawadi ya leseni ya kuanzia ya mwezi mmoja. Asilimia ya malipo ya marafiki zako pia itawekwa kwenye akaunti za wateja wako.",
     "action" => "Kuanzisha na kupokea kadi za zawadi bila kikomo",
],
],
     "basket-list" => [
     "item" => "kipengee",
     "count" => "Hesabu",
     "price" => "bei",
     "discount-code" => "Msimbo wa Punguzo",
     "customer-club" => "Klabu ya Wateja",
     "shipping" => "Usafirishaji",
     "total" => "Jumla",
     "offer" => "Toa",
     "coupon" => "Kuponi",
     "lottery" => "Tuzo",
     "tax" => "Kodi",
     "tax_included" => "Imejumuishwa katika bei",
     "tax_shipping" => "Shipping Tax",
],
     "buyable-payments" => [
     "method" => "Njia",
     "amount" => "Kiasi",
     "giftcard" => "Gift card",
     "payment" => "Malipo",
],
     "shop-subscription-email" => [
     "category" => "Sasisho la usajili",
     "title" => "Leseni ya Hifadhi: :shop_title",
     "title-reserved" => "Leseni ya hifadhi: :shop_title",
     "title-active" => "Leseni inayotumika: :shop_title",
     "title-finished" => "Leseni iliyokamilika: :shop_title",
     "title-cancel" => "Ghairi leseni: :shop_title",
     "message" => "Mpango wako wa leseni ya duka umesasishwa,",
     "RESERVED" => "⚡ Mpango wako wa usajili **umehifadhiwa**.",
     "ACTIVE" => "🟢 Mpango wako wa usajili **umewezeshwa**.",
     "FINISHED" => "🚧 Mpango wako wa usajili **umekamilika**.",
     "CANCEL" => "⛔ Mpango wako wa usajili **umeghairiwa**.",
],
     "support" => [
     "subject" => "Kituo cha usaidizi | :jina lilijibu",
     "category" => "Kituo cha usaidizi",
     "title" => "Umepokea jibu",
     "action" => "Fungua msimamizi wa duka",
],
     "shop-customer-join" => [
     "subject" => "Jiunge na :shop_title",
     "category" => "Sherehe ya mteja mpya",
     "title" => "Tuna furaha kwa uanachama wako",
     "action" => "Tembelea sasa",
],
     "shop-vendor-join" => [
     "subject" => "Kupanda kwa Wachuuzi | :kichwa_cha_duka",
     "category" => "Sherehe ya muuzaji mpya",
     "title" => "Tuna furaha kwa uanachama wako",
     "action" => "Vendor Panel",
],
     "shop-giftcard" => [
     "subject" => "Kadi ya zawadi :shop_title",
     "category" => "Ongeza kadi mpya",
     "title" => "Hongera, umepokea kadi ya zawadi",
     "action" => "Nunua sasa",
     "message" => "Umepokea kadi ya zawadi ya kiasi cha :salio :fedha. Utaweza kununua kutoka kwa duka letu na kadi hii ya zawadi.",
],
     "contact" => [
     "subject" => "Kituo cha usaidizi | :Duka",
     "category" => "msaada",
     "title" => "Umepokea jibu",
],
     "order-checkout" => [
     "subject" => "🛍 Malipo ya Agizo | :kitambulisho_cha_agizo",
     "title" => "agizo",
     "message" => "Agizo lako thibitisha,<br> Tumepokea agizo lako. Tutakutumia barua pepe nyingine agizo lako litakaposafirishwa.",
     "payments" => "Malipo",
],
     "order-payment" => [
     "subject" => "🛍 Uthibitishaji wa Malipo | :kitambulisho_cha_agizo",
     "title" => "Agizo la malipo",
     "message" => "Malipo yako yamekamilika,<br> Tumepokea agizo lako. Tutakutumia barua pepe nyingine agizo lako litakaposafirishwa.",
     "payments" => "Malipo",
],
     "get-voucher" => [
     "subject" => "Hongera :jina | Vocha mpya: :title",
     "category" => "HONGERA, VOCHA MPYA",
     "message" => "Unapata vocha mpya, Hii ni zawadi kutoka kwetu kwa ajili yako. Unaweza kupata zaidi kutoka kwa vocha hizi kwa kutambulisha Selldone kwa marafiki na kila mtu unayemjua. Vocha hii ina thamani ya **:bei :fedha**.<br> Unajaribu, tunafungua milango, Hongera, Fungua vipengele kwa vocha yako!",
     "action" => "Dashibodi yangu",
],
     "received-gift" => [
     "subject" => "Hongera, Mpendwa :jina | Umepokea zawadi",
     "category" => "Tangazo la kupokea zawadi",
     "title" => "Zawadi kwa ajili yako",
     "message" => "Umepokea zawadi mpya. Hii ni zawadi kutoka kwa Selldone. Unaweza kupokea zaidi ya zawadi hizi kwa kuwa hai zaidi katika Selldone na kukuza duka lako na kuinua kiwango chako cha utaalam. Thamani hii ya Zawadi ni **:bei :fedha** ambayo unaweza kuweka moja kwa moja kwenye mkoba wako ikiwa imekamilika.<br><br> Tumia zawadi hii kuboresha leseni yako ya duka na kutumia zana zaidi katika biashara yako ya mtandaoni.",
     "action" => "Zawadi",
],
     "order-payment-admin" => [
     "subject" => "🛍 Agizo Jipya Limepokelewa | :kitambulisho_cha_agizo",
     "title" => "New Order",
     "message" => "Umepokea agizo jipya. Tafadhali nenda kwenye ukurasa wa kuchakata agizo kwenye duka lako.",
],
     "virtual-item" => [
     "input-form-title" => "Taarifa Yako Iliyojazwa",
     "output-form-title" => "Taarifa ya bidhaa iliyonunuliwa",
],
     "selldone-weekly-report" => [
     "subject" => "📬 :kichwa_cha_duka | Ripoti ya kila wiki: wakati",
     "title" => "Ripoti ya utendaji wa duka ya kila wiki",
     "message" => "Hii ni ripoti ya kila wiki ya duka lako kutoka :start hadi :end. Ripoti hii inajumuisha vidokezo vya kuboresha biashara yako, unaweza pia kuangalia hali ya duka lako la mtandaoni na maagizo ya hivi majuzi. Natumai una siku na wiki njema mbeleni.",
],
     "shop-seasonal-report" => [
     "subject" => "☘ Ripoti yako :ya kuokoa kiasi katika miezi mitatu iliyopita | :kichwa_cha_duka",
     "title" => "Ripoti ya msimu kuhusu shughuli zako za biashara, zawadi na akiba ya kifedha",
     "message" => "Hii ni :shop_title ripoti yako ya msimu kutoka :start hadi :end.",
],
     "EC-ShopAccounts" => [
     "title" => "Akaunti zilizounganishwa",
     "sub-title" => "Je, hali ya hivi punde ya akaunti za pochi iliyounganishwa kwenye duka langu ni ipi?",
     "view-wallet" => "Tazama mkoba",
     "tip-title" => "Vidokezo muhimu",
     "tip" => "Katika hatua inayofuata, fungua akaunti isiyolipishwa kwenye pochi yako ya Selldone na uiunganishe na duka hili. Hata kama salio la akaunti yako ya Selldone ni hasi, wateja wako bado wanaweza kufanya ununuzi na malipo ya duka lako bila matatizo yoyote. Data na huduma yako hazitakatizwa au kuzuiwa kwa angalau mwezi 1.",
     "view-my-wallet" => "My wallet",
     "connect-account" => "Unganisha kwenye akaunti",
],
     "EC-ShopApps" => [
     "title" => "Programu zilizosakinishwa",
     "sub-title" => "Orodha ya programu ambazo umesakinisha kwenye duka lako wiki hii.",
     "tip" => "Je, ungependa kupata programu zaidi za duka lako?",
     "view-app-store" => "Tembelea Selldone App Store..",
],
     "EC-ShopBots" => [
     "title" => "Vijibu vyako vya Hifadhi",
     "sub-title" => "Boti za mauzo zinazotumika kwenye duka langu.",
     "tip-title" => "Uuzaji wa Bot",
     "tip" => "Selldone imekupa roboti za mauzo otomatiki. Unachohitajika kufanya ni kwenda kwenye kidirisha cha Viongezi> Boti na uamilishe roboti zako za duka. Kumbuka kwamba huduma husika lazima ipatikane katika nchi yako.",
     "view-bots" => "Dhibiti roboti",
],
     "EC-ShopContacts" => [
     "title" => "Mawasiliano na Wateja",
     "sub-title" => "Je, ni watu wangapi ambao nimekuwa nao na wateja wangu wiki hii?",
     "faqs" => "maswali yanayoulizwa mara kwa mara",
     "tickets" => "Tiketi za Wateja",
],
     "EC-ShopData" => [
     "title" => "Hali ya Watumiaji",
     "sub-title" => "Kuanzia tarehe :anza hadi :mwisho",
     "users" => [
     "title" => "Wateja",
     "subtitle" => "Watumiaji wa Kujiandikisha",
],
     "views" => [
     "title" => "Ziara",
     "subtitle" => "Umetembelea duka mara ngapi",
],
     "new_visitors" => "New Users",
     "returning_visitors" => "Watumiaji Waliorudishwa",
     "shop_views" => "Maoni ya Duka",
     "baskets" => [
     "title" => "Mikokoteni ya Ununuzi",
     "subtitle" => "Ripoti idadi ya mikokoteni mpya ya ununuzi",
],
     "products" => [
     "title" => "Muhtasari wa Bidhaa",
     "subtitle" => "Hali ya bidhaa katika duka kwa aina",
     "value_name" => "Bidhaa",
],
     "products_count" => "Aina za bidhaa",
     "views_count" => "Idadi ya maoni",
     "sell_count" => "Idadi ya mauzo",
     "send_count" => "Idadi ya usafirishaji",
],
     "EC-ShopDropShipping" => [
     "title" => "Usafirishaji wa Kuacha",
     "sub-title" => "Jopo kwa wauzaji wakuu wa Drop Shipping Selldone.",
     "total_fulfillments" => "Jumla ya Maagizo Yaliyopokelewa",
     "ds_count" => "Maagizo Yaliyopokelewa",
     "statistics_title" => "Ripoti kupokea maagizo",
     "ds_cancels" => "Ghairi kwa muuzaji wa kiolesura",
     "ds_rejects" => "Ghairi na Wewe",
     "tip" => "Je, wewe ni muuzaji mkuu wa bidhaa? Je, unamiliki ghala, kiwanda au msambazaji wa bidhaa? Unaweza kutoa bidhaa zako kwa wauzaji wengine katika huduma ya Selldone Drop Shipping ili kuuza bidhaa yako kwa kiwango kikubwa. Tutumie barua pepe kwa support@selldone.com ili kukuongoza.",
     "view-drop-shipping-panel" => "Ingia kwenye paneli ya jumla",
],
     "EC-ShopExchangeRates" => [
     "title" => "Viwango vya ubadilishaji",
     "sub-title" => "Orodha ya viwango vya hivi punde vya ubadilishaji wa sarafu katika duka lako.",
     "from" => "Sarafu Chanzo",
     "to" => "Sarafu ya lengwa",
     "rate" => "Kiwango cha ubadilishaji",
     "vew-exchange-panel" => "jopo la usimamizi wa viwango vya ubadilishaji",
],
     "EC-ShopExperts" => [
     "title" => "Mikataba ya wataalam",
     "sub-title" => "Ni wataalamu gani hufanya kazi kwenye duka langu?",
     "cost" => "Kiasi cha mkataba",
     "duration" => "Muda",
     "start_at" => "Start Date",
     "complete_at" => "Completion Date",
     "cancel_at" => "Tarehe ya Kughairi",
     "end_at" => "Tarehe ya utoaji",
     "tip" => "Unaweza kuajiri wataalamu bora katika Selldone ili kukuza biashara yako.",
     "view-experts" => "Bofya ili kuanza.",
],
     "EC-ShopGateways" => [
     "title" => "Payment gateways",
     "sub-title" => "Ripoti njia za malipo zinazotumika kwenye duka :duka.",
     "tip-title" => "Vidokezo muhimu",
     "tip" => "Nenda kwenye ukurasa wa usimamizi wa tovuti katika duka lako na uongeze angalau mlango mmoja baada ya dakika chache. Wateja wako wanapenda kulipa haraka na kwa usalama kupitia lango za mtandaoni.",
     "view-shop-gateways" => "Ingia kwenye usimamizi wa tovuti ya duka langu.",
     "view-gateways" => "Tazama malango zaidi",
],
     "EC-ShopOrders" => [
     "title" => "Maagizo",
     "sub-title" => "Orodha ya maagizo niliyopokea wiki hii.",
     "total_baskets" => "Jumla ya Maagizo",
     "total_posBaskets" => "Jumla ya Maagizo ya Fedha",
     "pos-title" => "Sanduku la Duka la POS",
     "chart-label" => "Maagizo yamekamilika (maagizo haya si lazima yalipwe!)",
     "tip-title" => "Unapaswa kujaribu zaidi ...",
     "tip" => "Hakuna mafanikio rahisi.",
],
     "EC-ShopProcessCenter" => [
     "title" => "Kituo cha usindikaji",
     "sub-title" => "Je, ni kiasi gani cha agizo tulilochakata dukani wiki hii?",
     "tip-title" => "Hukuwa na mauzo!",
     "tip" => "Kwa bahati mbaya hukuwa na mauzo yoyote wiki hii. Unahitaji kupata zaidi kwenye duka lako. Unaweza kuongeza bidhaa zaidi, kuchagua picha bora au kuandika maelezo bora ya bidhaa zako. Fikiria kazi ya wakati wote kwa biashara yako. Ukifanya vizuri na usikatishwe tamaa, utafanikiwa.",
     "view-process-center" => "Angalia kituo cha mchakato",
     "return" => [
     "title" => "Agizo Limerejeshwa",
     "subtitle" => "Ripoti zilizorudishwa amri.",
     "tip-title" => "Je, wajua kuwa...",
     "tip" => "Unaweza kuunda rejista nyingi za pesa za duka unavyotaka kupitia Selldone POS! Kwa kweli, unaweza kugeuza kompyuta yako kibao, simu ya mkononi au kompyuta ya mkononi kuwa kikasha chako. Ikiwa hiyo inakusisimua, Selldone POS Ni kitu unapaswa kuanza kutumia sasa. Inachukua tu kubofya rahisi ili kuzindua, tuna kila kitu tayari kwa ajili ya seva yako mapema.",
     "view-pos" => "Ingia kwa Keshia Yangu ya Duka la Mtandaoni",
],
],
     "EC-ShopSessions" => [
     "title" => "Vikao",
     "sub-title" => "Je, nilitembelea duka langu mara ngapi?",
     "countries-title" => "Ni nchi gani zimetembelewa zaidi?",
],
     "EC-PublicMessage" => [
     "title" => "Je! Unataka kupata pesa bila kutumia pesa moja?",
     "message" => "Mpendwa :name, unaweza kwenda kwenye Dashibodi > Uchumaji wa mapato na uunde kiungo cha rufaa. Tuma kiungo kwa marafiki zako, Unapokea kadi za zawadi za Selldone na asilimia ya malipo ya rafiki yako. Kumbuka kwamba kadi ya zawadi itatumwa kwa wewe na rafiki yako.",
     "action" => "Tazama kiunga changu cha utangulizi",
     "mail-clip" => "<b style='color: #C2185B'>Muhimu:</b> Ikiwa unatumia huduma za barua pepe kama vile Gmail zinazoweka kikomo cha urefu wa barua pepe, tafuta chaguo lifuatalo mwishoni mwa barua pepe ili kuonyesha ripoti kamili na ubofye juu yake:",
     "no-coin-reward" => "<b style='color: #C2185B'>Samahani:</b> Shughuli yako haikukidhi mahitaji ya kupata zawadi ya Sarafu za SEL bila malipo. Jaribu zaidi na uuze zaidi kwenye duka lako kwa msimu ujao.",
     "yes-coin-reward" => "<b style='color: #4CAF50'>Zawadi:</b> Hongera, kwa sababu ya utendakazi wako mzuri, tumekupa zawadi ya :kiasi cha SEL Coin bila malipo.",
     "need-buy-license" => "Ongeza <b>biashara yako:</b> Hujasajili mpango wowote wa usajili wa tovuti yako ya biashara! Kwa hivyo ni wakati wa kununua angalau usajili mmoja. Inagharimu tu:kiasi kila mwezi kwa ununuzi wa kila mwaka.",
     "not-afford-message" => "Ikiwa huwezi kumudu au una shida yoyote na malipo, jisikie huru kutuambia kupitia support@selldone.com.",
     "add-domain" => "<b>Kwa nini usiwe na kikoa maalum cha biashara yako?</b><br> Ongeza kikoa kwenye tovuti yako sasa; ni bure!",
],
     "Widget-Socials" => [
     "title" => "Selldone ni<del> bidhaa</del> <span style = 'color: forestgreen'>jamii</span> .<br> Kuwa Selldoner kitaaluma!",
     "message" => "Fuata kurasa rasmi za Selldone kwenye Twitter, LinkedIn na mitandao ya kijamii. Tutumie maoni, maombi au ukosoaji wowote au ushiriki katika majadiliano kuhusu Selldone. Sisi pia ni sehemu ya jumuiya ya Selldone ambayo <b>Wewe hufanya</b> .",
],
     "avocado-seller-daily-report" => [
     "subject" => "Umepokea maagizo mapya ya Parachichi | :kichwa_cha_duka :wakati",
     "title" => "Ripoti ya utendaji kwa saa 24 zilizopita",
     "message" => "Wateja wako wanasubiri maagizo yako yakaguliwe na kuwekewa bei. Jibu maombi ya wateja wako haraka iwezekanavyo ili kupata mauzo zaidi.",
     "card_title" => "Maagizo kwenye foleni",
     "card_subtitle" => "Kuanzia :tarehe",
     "card_payed" => "Amri zilizolipwa",
],
     "community-comments" => [
     "subject" => "Jibu chapisho lako katika :community_title",
     "title" => ":name, na :count wengine walitoa maoni kwenye machapisho yako.",
     "title-simple" => ":name alitoa maoni kwenye machapisho yako.",
],
     "community-topic" => [
     "subject" => "🔔 Jibu mada yako :topic_title",
     "title" => ":jina, na :hesabu wengine walijibu juu ya mada yako.",
     "title-simple" => ":jina lilijibu kwenye mada yako.",
],
     "user-login" => [
     "subject" => "🔔 Ingia Mpya :jina",
     "category" => "Arifa za usalama",
     "title" => "Ingia kwa Akaunti",
     "message" => "Mpendwa :jina, umekuwa ukiingia kwenye akaunti yako ya Selldone.",
     "message-shop" => "Mpendwa :name, umeingia kwenye :shop_title .",
     "footer" => "Ikiwa hujaingia, tafadhali badilisha nenosiri lako.",
],
     "account-transaction" => [
     "withdraw" => "Uondoaji",
     "deposit" => "Amana",
     "withdraw_subject" => "ondoa kutoka kwa akaunti: akaunti",
     "deposit_subject" => "Amana kwa akaunti :account",
     "message" => "Uhamisho wa pesa umefanywa kwa vigezo vifuatavyo.",
     "type" => "Aina ya muamala",
     "from" => "Akaunti ya chanzo",
     "to" => "Destination account",
     "desc" => "Maelezo ya muamala",
     "action" => "Tazama muamala",
],
     "penalty" => [
     "subject" => "⛔ Muhimu! Ukiukaji wa sheria | :Duka",
     "category" => "Taarifa muhimu",
     "title" => "Duka lako limeadhibiwa",
     "action" => "Fungua dashibodi ya duka",
],
     "invite" => [
     "subject" => ":mwalikaji amekualika kwa Selldone",
     "title" => ":jina limekutumia :kiasi kukusaidia kuzindua tovuti yako mpya ya mtandaoni na kuchuma mapato yake!",
     "message" => "Kwenye Selldone, unaweza kuunda biashara yako ya mtandaoni, tovuti ya blogu, na jumuiya ya mtandaoni na hata kupata POS mtandaoni na kuanzisha mauzo ya ana kwa ana kwa dakika. Ni mfumo wa uendeshaji wa biashara mtandaoni ili kufanya biashara yako mtandaoni, bora na haraka. Jisajili tu kufikia <b>:date</b> ili kupata :kiasi vocha.",
     "accept" => "Kubali mwaliko",
     "owner" => "Mmiliki wa",
     "join-date" => "Kwenye Selldone tangu",
],
     "shop-recovery" => [
     "subject" => "Kiungo cha urejeshaji | :Duka",
     "category" => "Usalama wa duka",
     "title" => "Kiungo cha uokoaji cha <b>:shop_name</b> .",
     "message" => "Barua pepe hii ilitumwa kwako kwa sababu uliomba kurejesha duka lako. Kubofya kiungo kilicho hapa chini kutaokoa duka lako na data yote inayomilikiwa nayo.",
     "action" => "Thibitisha Urejeshaji wa Duka",
],
     "SR-SeasonalSaving" => [
     "title" => "Je, Selldone alihifadhi pesa ngapi kwa biashara yako?",
     "sub-title" => "Kuanzia tarehe :anza hadi :mwisho",
     "infrastructure" => [
     "title" => "Miundombinu",
     "subtitle" => "Seva, CDN, Hifadhi, na huduma zingine za wingu",
],
     "experts" => [
     "title" => "Wataalam na Wafanyakazi",
     "subtitle" => "Watengenezaji, matengenezo na usaidizi",
],
     "total_save" => "Jumla ya pesa zilizohifadhiwa",
],
     "SR-SeasonalPerformance" => [
     "title" => "Utendaji wako",
     "sub-title" => "Muhtasari wa biashara kutoka :start hadi :mwisho",
     "new_visitors" => "New Users",
     "returning_visitors" => "Watumiaji Waliorudishwa",
     "shop_views" => "Maoni ya Duka",
     "baskets" => [
     "title" => "Mikokoteni ya Ununuzi",
     "subtitle" => "Ripoti idadi ya mikokoteni mpya ya ununuzi",
],
     "products" => [
     "title" => "Muhtasari wa Bidhaa",
     "subtitle" => "Hali ya bidhaa katika duka kwa aina",
     "value_name" => "Bidhaa",
],
     "views" => [
     "title" => "Page Views",
     "subtitle" => "Jumla ya mionekano ya ukurasa wa tovuti",
],
],
     "vendor-order" => [
     "title" => "New Order",
     "message" => "Umepokea agizo jipya. Tafadhali nenda kwenye ukurasa wa kuchakata agizo katika paneli yako ya muuzaji.",
     "subject" => "🛍 Agizo Jipya Limepokelewa | :kitambulisho_cha_agizo",
     "your_revenue" => "Mapato Yako",
],
     "vendor-invite" => [
     "title" => "Mwaliko wa Muuzaji",
     "message" => "Umepokea mwaliko wa kuwa mchuuzi wa :shop_name. Unaweza kuikubali au kuikataa kwa kubofya vitufe vifuatavyo.",
     "subject" => ":jina_la_duka | Umepokea mwaliko wa kuwa mchuuzi wetu",
     "accept" => "Kubali na Uwe Muuzaji",
     "reject" => "Kataa",
],
     "shop-email-login" => [
     "subject" => "Nambari yako ya Kuingia ya :shop",
     "header-message" => "Tunakutumia barua pepe hii kwa sababu uliomba msimbo wa kuingia katika duka. Tafadhali tafuta Nenosiri lako la Wakati Mmoja (OTP) hapa chini:",
     "footer-message" => "Nambari hii itatumika kwa dakika 10. Ikiwa hukuomba msimbo huu wa kuingia, tafadhali puuza barua pepe hii.",
],
     "shop-email-verify-link" => [
     "subject" => "Thibitisha barua pepe yako | : duka",
     "title" => "Uthibitishaji wa Barua Pepe",
     "header-message" => "Hi: jina,<br> Tafadhali thibitisha kwamba **:barua pepe** ni anwani yako ya barua pepe kwa kubofya kitufe au tumia kiungo kilicho hapa chini ndani ya saa 48.",
     "footer-message" => "",
],
     "vendor-products" => [
     "subject" => "Bidhaa Update :duka",
     "title" => "Sasisha kuhusu Hali ya Bidhaa - Saa 24 Zilizopita",
     "message" => "Natumai ujumbe huu utakupata vyema. Hili ni sasisho fupi la kukuarifu kuhusu hali ya bidhaa zako kwenye jukwaa letu katika muda wa saa 24 zilizopita. Katika kipindi hiki, kumekuwa na mabadiliko katika hali ya baadhi ya bidhaa. Mabadiliko haya yanaweza kutokana na ununuzi, masasisho ya hisa au matukio mengine yanayohusiana. Kwa maelezo zaidi kuhusu kila bidhaa, tafadhali ingia katika akaunti yako na uangalie sehemu ya 'Hali ya Bidhaa'.",
     "action" => "Fungua Paneli ya Wauzaji",
],
];