<?php 

 return [
     "accepted" => ":attribute는 허용되어야 합니다.",
     "accepted_if" => ":other가 :value인 경우 :attribute 필드는 허용되어야 합니다.",
     "active_url" => ":attribute는 유효한 URL이 아닙니다.",
     "after" => ":attribute는 :date 이후의 날짜여야 합니다.",
     "after_or_equal" => ":attribute는 :date 이후의 날짜이거나 같아야 합니다.",
     "alpha" => ":attribute에는 문자만 포함될 수 있습니다.",
     "alpha_dash" => ":attribute에는 문자, 숫자 및 대시만 포함될 수 있습니다.",
     "alpha_num" => ":attribute에는 문자와 숫자만 포함될 수 있습니다.",
     "array" => ":attribute는 배열이어야 합니다.",
     "ascii" => ":attribute 필드에는 단일 바이트 영숫자 문자와 기호만 포함되어야 합니다.",
     "before" => ":attribute는 :date 이전의 날짜여야 합니다.",
     "before_or_equal" => ":attribute는 :date 이전의 날짜이거나 같아야 합니다.",
     "between" => [
     "array" => ":attribute에는 :min과 :max 항목이 있어야 합니다.",
     "file" => ":attribute는 :min과 :max 킬로바이트 사이여야 합니다.",
     "numeric" => ":attribute는 :min과 :max 사이에 있어야 합니다.",
     "string" => ":attribute는 :min과 :max 사이에 있어야 합니다.",
],
     "boolean" => ":attribute 필드는 true 또는 false여야 합니다.",
     "can" => ":attribute 필드에 승인되지 않은 값이 포함되어 있습니다.",
     "confirmed" => ":attribute 확인이 일치하지 않습니다.",
     "contains" => ":attribute 필드에 필수 값이 없습니다.",
     "current_password" => "비밀번호가 틀렸습니다.",
     "date" => ":attribute는 유효한 날짜가 아닙니다.",
     "date_equals" => ":attribute 필드는 :date와 같은 날짜여야 합니다.",
     "date_format" => ":attribute가 형식 :format과 일치하지 않습니다.",
     "decimal" => ":attribute 필드에는 :decimal 소수 자릿수가 있어야 합니다.",
     "declined" => ":attribute 필드는 거부되어야 합니다.",
     "declined_if" => ":other가 :value인 경우 :attribute 필드는 거부되어야 합니다.",
     "different" => ":attribute 및 :other는 달라야 합니다.",
     "digits" => ":attribute는 :digits 숫자여야 합니다.",
     "digits_between" => ":attribute는 :min과 :max 사이에 있어야 합니다.",
     "dimensions" => ":attribute의 이미지 크기가 잘못되었습니다.",
     "distinct" => ":attribute 필드에 중복 값이 있습니다.",
     "doesnt_end_with" => ":attribute 필드는 다음 중 하나로 끝날 수 없습니다: :values.",
     "doesnt_start_with" => ":attribute 필드는 다음 중 하나로 시작할 수 없습니다: :values.",
     "email" => ":attribute는 유효한 이메일 주소여야 합니다.",
     "ends_with" => ":attribute 필드는 다음 중 하나로 끝나야 합니다: :values.",
     "enum" => "선택한 :속성이 잘못되었습니다.",
     "exists" => "선택한 :속성이 잘못되었습니다.",
     "extensions" => ":attribute 필드에는 다음 확장자 중 하나가 있어야 합니다: :values.",
     "file" => ":attribute는 파일이어야 합니다.",
     "filled" => ":attribute 필드에는 값이 있어야 합니다.",
     "gt" => [
     "array" => ":attribute에는 :value 이상의 항목이 있어야 합니다.",
     "file" => ":attribute는 :value 킬로바이트보다 커야 합니다.",
     "numeric" => ":attribute는 :value보다 커야 합니다.",
     "string" => ":attribute는 :value 문자보다 커야 합니다.",
],
     "gte" => [
     "array" => ":attribute에는 :value 항목 이상이 있어야 합니다.",
     "file" => ":attribute는 :value 킬로바이트보다 크거나 같아야 합니다.",
     "numeric" => ":attribute는 :value보다 크거나 같아야 합니다.",
     "string" => ":attribute는 :value 문자보다 크거나 같아야 합니다.",
],
     "hex_color" => ":attribute 필드는 유효한 16진수 색상이어야 합니다.",
     "image" => ":attribute는 이미지여야 합니다.",
     "in" => "선택한 :속성이 잘못되었습니다.",
     "in_array" => ":attribute 필드는 :other에 존재하지 않습니다.",
     "integer" => ":attribute는 정수여야 합니다.",
     "ip" => ":attribute는 유효한 IP 주소여야 합니다.",
     "ipv4" => ":attribute는 유효한 IPv4 주소여야 합니다.",
     "ipv6" => ":attribute는 유효한 IPv6 주소여야 합니다.",
     "json" => ":attribute는 유효한 JSON 문자열이어야 합니다.",
     "list" => ":attribute 필드는 목록이어야 합니다.",
     "lowercase" => ":attribute 필드는 소문자여야 합니다.",
     "lt" => [
     "array" => ":attribute에는 :value보다 작은 항목이 있어야 합니다.",
     "file" => ":attribute는 :value 킬로바이트보다 작아야 합니다.",
     "numeric" => ":attribute는 :value보다 작아야 합니다.",
     "string" => ":attribute는 :value 문자보다 작아야 합니다.",
],
     "lte" => [
     "array" => ":attribute에는 :value 항목보다 많은 항목이 없어야 합니다.",
     "file" => ":attribute는 :value 킬로바이트보다 작거나 같아야 합니다.",
     "numeric" => ":attribute는 :value보다 작거나 같아야 합니다.",
     "string" => ":attribute는 :value 문자보다 작거나 같아야 합니다.",
],
     "mac_address" => ":attribute 필드는 유효한 MAC 주소여야 합니다.",
     "max" => [
     "array" => ":attribute에는 최대 :max 항목이 있을 수 없습니다.",
     "file" => ":attribute는 :max 킬로바이트보다 클 수 없습니다.",
     "numeric" => ":attribute는 :max보다 클 수 없습니다.",
     "string" => ":attribute는 :max 문자보다 클 수 없습니다.",
],
     "max_digits" => ":attribute 필드에는 :max개 이상의 숫자가 있을 수 없습니다.",
     "mimes" => ":attribute는 유형: :values의 파일이어야 합니다.",
     "mimetypes" => ":attribute는 유형: :values의 파일이어야 합니다.",
     "min" => [
     "array" => ":attribute에는 최소한 :min 항목이 있어야 합니다.",
     "file" => ":attribute는 최소 :min 킬로바이트 이상이어야 합니다.",
     "numeric" => ":attribute는 최소한 :min이어야 합니다.",
     "string" => ":attribute는 최소한 :min 문자여야 합니다.",
],
     "min_digits" => ":attribute 필드에는 최소한 :min자리 숫자가 있어야 합니다.",
     "missing" => ":attribute 필드가 없어야 합니다.",
     "missing_if" => ":other가 :value인 경우 :attribute 필드가 누락되어야 합니다.",
     "missing_unless" => ":other가 :value가 아닌 한 :attribute 필드는 누락되어야 합니다.",
     "missing_with" => ":values가 있는 경우 :attribute 필드는 없어야 합니다.",
     "missing_with_all" => ":values가 존재하는 경우 :attribute 필드는 누락되어야 합니다.",
     "multiple_of" => ":attribute 필드는 :value의 배수여야 합니다.",
     "not_in" => "선택한 :속성이 잘못되었습니다.",
     "not_regex" => ":attribute 형식이 잘못되었습니다.",
     "numeric" => ":attribute는 숫자여야 합니다.",
     "password" => [
     "letters" => ":attribute 필드에는 최소한 한 글자가 포함되어야 합니다.",
     "mixed" => ":attribute 필드에는 대문자와 소문자가 각각 최소한 하나씩 포함되어야 합니다.",
     "numbers" => ":attribute 필드에는 최소한 하나의 숫자가 포함되어야 합니다.",
     "symbols" => ":attribute 필드에는 최소한 하나의 기호가 포함되어야 합니다.",
     "uncompromised" => "주어진 :attribute가 데이터 누출에 나타났습니다. 다른 :attribute를 선택하세요.",
],
     "present" => ":attribute 필드가 있어야 합니다.",
     "present_if" => ":other가 :value인 경우 :attribute 필드가 있어야 합니다.",
     "present_unless" => ":other가 :value가 아닌 한 :attribute 필드는 반드시 존재해야 합니다.",
     "present_with" => ":values가 있는 경우 :attribute 필드가 있어야 합니다.",
     "present_with_all" => ":values가 있는 경우 :attribute 필드가 있어야 합니다.",
     "prohibited" => ":attribute 필드는 금지되어 있습니다.",
     "prohibited_if" => ":other가 :value인 경우 :attribute 필드는 금지됩니다.",
     "prohibited_unless" => ":attribute 필드는 :other가 :values에 없는 한 금지됩니다.",
     "prohibits" => ":attribute 필드는 :other가 존재하는 것을 금지합니다.",
     "regex" => ":attribute 형식이 잘못되었습니다.",
     "required" => ":attribute 필드는 필수입니다.",
     "required_array_keys" => ":attribute 필드에는 :values에 대한 항목이 포함되어야 합니다.",
     "required_if" => ":attribute 필드는 :other가 :value일 때 필요합니다.",
     "required_if_accepted" => ":other가 승인되는 경우 :attribute 필드가 필요합니다.",
     "required_if_declined" => ":other가 거부되는 경우 :attribute 필드가 필요합니다.",
     "required_unless" => ":attribute 필드는 :other가 :values에 있지 않는 한 필수입니다.",
     "required_with" => ":values가 있는 경우 :attribute 필드가 필요합니다.",
     "required_with_all" => ":values가 있는 경우 :attribute 필드가 필요합니다.",
     "required_without" => ":values가 없으면 :attribute 필드가 필요합니다.",
     "required_without_all" => ":value가 없는 경우 :attribute 필드가 필요합니다.",
     "same" => ":attribute 및 :other는 일치해야 합니다.",
     "size" => [
     "array" => ":attribute에는 :size 항목이 포함되어야 합니다.",
     "file" => ":attribute는 :size 킬로바이트여야 합니다.",
     "numeric" => ":attribute는 :size여야 합니다.",
     "string" => ":attribute는 :size 문자여야 합니다.",
],
     "starts_with" => ":attribute 필드는 다음 중 하나로 시작해야 합니다: :values.",
     "string" => ":attribute는 문자열이어야 합니다.",
     "timezone" => ":attribute는 유효한 영역이어야 합니다.",
     "unique" => ":attribute는 이미 사용 중입니다.",
     "uploaded" => ":attribute 업로드에 실패했습니다.",
     "uppercase" => ":attribute 필드는 대문자여야 합니다.",
     "url" => ":attribute 형식이 잘못되었습니다.",
     "ulid" => ":attribute 필드는 유효한 ULID여야 합니다.",
     "uuid" => ":attribute 필드는 유효한 UUID여야 합니다.",
     "custom" => [
     "attribute-name" => [
     "rule-name" => "맞춤 메시지",
],
     "g-recaptcha-response" => [
     "required" => "로봇이 아닌지 확인하십시오.",
     "captcha" => "보안문자 오류! 나중에 다시 시도하거나 사이트 관리자에게 문의하세요.",
],
],
     "attributes" => [
        
     ],
];