<?php 

 return [
     "invoice" => "Счет",
     "serial" => "Серийный номер.",
     "date" => "Дата счета",
     "seller" => "Продавец",
     "buyer" => "Покупатель",
     "address" => "адрес",
     "code" => "Код",
     "vat" => "Код НДС",
     "phone" => "Телефон",
     "description" => "Описание",
     "units" => "Единицы",
     "quantity" => "Кол-во",
     "price" => "цена",
     "discount" => "Скидка",
     "tax" => "налог",
     "sub_total" => "Промежуточный итог",
     "total_discount" => "Общая скидка",
     "taxable_amount" => "Налогооблагаемая сумма",
     "total_taxes" => "Итого налоги",
     "tax_rate" => "Ставка налога",
     "total_amount" => "Общая сумма",
     "pay_until" => "Пожалуйста, платите до",
     "amount_in_words" => "Сумма прописью",
     "amount_in_words_format" => "%s %s и %s %s",
     "notes" => "Заметки",
     "shipping" => "Перевозки",
     "paid" => "Оплаченный",
     "due" => "В связи",
];