<?php 

 return [
     "accepted" => "Атрибут : должен быть принят.",
     "active_url" => ":attribute не является допустимым URL.",
     "after" => ":attribute должен быть датой после :date.",
     "after_or_equal" => ":attribute должен быть датой после :date или равным ей.",
     "alpha" => ":attribute может содержать только буквы.",
     "alpha_dash" => ":attribute может содержать только буквы, цифры и тире.",
     "alpha_num" => ":attribute может содержать только буквы и цифры.",
     "array" => ":attribute должен быть массивом.",
     "before" => ":attribute должен быть датой до :date.",
     "before_or_equal" => ":attribute должен быть датой, предшествующей :date или равной ей.",
     "between" => [
     "numeric" => ":attribute должен быть между :min и :max.",
     "file" => ":attribute должен быть между :min и :max килобайтами.",
     "string" => ":attribute должен находиться между символами :min и :max.",
     "array" => ":attribute должен иметь элементы от :min до :max.",
],
     "boolean" => "Поле :attribute должно быть истинным или ложным.",
     "confirmed" => "Подтверждение :attribute не совпадает.",
     "date" => ":attribute не является действительной датой.",
     "date_format" => ":attribute не соответствует формату :format.",
     "different" => ":attribute и :other должны быть разными.",
     "digits" => ":attribute должен быть :digits цифры.",
     "digits_between" => ":attribute должен быть между цифрами :min и :max.",
     "dimensions" => ":attribute имеет недопустимые размеры изображения.",
     "distinct" => "Поле :attribute имеет повторяющееся значение.",
     "email" => ":attribute должен быть действительным адресом электронной почты.",
     "exists" => "Выбранный :attribute недействителен.",
     "file" => ":attribute должен быть файлом.",
     "filled" => "Поле :attribute должно иметь значение.",
     "gt" => [
     "numeric" => ":attribute должен быть больше :value.",
     "file" => ":attribute должен быть больше :value килобайт.",
     "string" => ":attribute должен быть больше символов :value.",
     "array" => ":attribute должен иметь более :value элементов.",
],
     "gte" => [
     "numeric" => ":attribute должен быть больше или равен :value.",
     "file" => ":attribute должен быть больше или равен :value килобайт.",
     "string" => ":attribute должен быть больше или равен :value символов.",
     "array" => ":attribute должен иметь элементы :value или более.",
],
     "image" => ":attribute должен быть изображением.",
     "in" => "Выбранный :attribute недействителен.",
     "in_array" => "Поле :attribute не существует в :other.",
     "integer" => ":attribute должен быть целым числом.",
     "ip" => ":attribute должен быть действительным IP-адресом.",
     "ipv4" => ":attribute должен быть действительным адресом IPv4.",
     "ipv6" => ":attribute должен быть действительным адресом IPv6.",
     "json" => ":attribute должен быть допустимой строкой JSON.",
     "lt" => [
     "numeric" => ":attribute должен быть меньше :value.",
     "file" => "Размер :attribute должен быть меньше :value килобайт.",
     "string" => ":attribute должен быть меньше символов :value.",
     "array" => "Элемент :attribute должен содержать меньше элементов :value.",
],
     "lte" => [
     "numeric" => ":attribute должен быть меньше или равен :value.",
     "file" => ":attribute должен быть меньше или равен :value килобайтам.",
     "string" => ":attribute должен быть меньше или равен :value символов.",
     "array" => ":attribute не должен содержать более :value элементов.",
],
     "max" => [
     "numeric" => ":attribute не может быть больше :max.",
     "file" => "Размер :attribute не может превышать :max килобайт.",
     "string" => ":attribute не может быть больше, чем :max символов.",
     "array" => ":attribute может иметь не более :max элементов.",
],
     "mimes" => ":attribute должен быть файлом типа: :values.",
     "mimetypes" => ":attribute должен быть файлом типа: :values.",
     "min" => [
     "numeric" => ":attribute должен быть как минимум :min.",
     "file" => "Размер :attribute должен быть не менее :min килобайт.",
     "string" => ":attribute должен содержать не менее :min символов.",
     "array" => ":attribute должен иметь как минимум :min элементов.",
],
     "not_in" => "Выбранный :attribute недействителен.",
     "not_regex" => "Недопустимый формат :attribute.",
     "numeric" => ":attribute должен быть числом.",
     "present" => "Поле :attribute должно присутствовать.",
     "regex" => "Недопустимый формат :attribute.",
     "required" => "Поле :attribute является обязательным.",
     "required_if" => "Поле :attribute является обязательным, если :other равно :value.",
     "required_unless" => "Поле :attribute является обязательным, если только :other не находится в :values.",
     "required_with" => "Поле :attribute обязательно, когда присутствует :values.",
     "required_with_all" => "Поле :attribute обязательно, когда присутствует :values.",
     "required_without" => "Поле :attribute является обязательным, если :values отсутствует.",
     "required_without_all" => "Поле :attribute является обязательным, если ни одно из значений :value не присутствует.",
     "same" => ":attribute и :other должны совпадать.",
     "size" => [
     "numeric" => "Атрибут : должен быть :size.",
     "file" => ":attribute должен быть :size килобайт.",
     "string" => ":attribute должен состоять из символов :size.",
     "array" => ":attribute должен содержать элементы :size.",
],
     "string" => ":attribute должен быть строкой.",
     "timezone" => ":attribute должен быть допустимой зоной.",
     "unique" => "Атрибут : уже занят.",
     "uploaded" => "Не удалось загрузить :attribute.",
     "url" => "Недопустимый формат :attribute.",
     "custom" => [
     "attribute-name" => [
     "rule-name" => "пользовательское сообщение",
],
     "g-recaptcha-response" => [
     "required" => "Пожалуйста, подтвердите, что вы не робот.",
     "captcha" => "Ошибка капчи! повторите попытку позже или обратитесь к администратору сайта.",
],
],
     "attributes" => [
        
     ],
];