<?php 

 return [
     "email-types" => [
        [
     "title" => "Đơn đặt hàng được xác nhận bởi người mua",
],
        [
     "title" => "Xác nhận thanh toán của khách hàng",
],
        [
     "title" => "Thông báo xác nhận đơn hàng cho người bán",
],
        [
     "title" => "Xác nhận đơn đặt hàng hộp cửa hàng cho người mua",
],
        [
     "title" => "Xác nhận thanh toán máy tính tiền cho người mua",
],
        [
     "title" => "Thông báo mua hàng trong hộp của người bán",
],
        [
     "title" => "Thông báo biểu mẫu liên hệ",
],
        [
     "title" => "Chúc mừng bạn đã tham gia cửa hàng",
],
        [
     "title" => "Thông báo nhận thẻ quà tặng cho người dùng",
]
     ],
     "global" => [
     "greetings" => "Xin chào tên",
     "end-statement" => "Nhóm hỗ trợ",
     "receiver_name" => "Xin chào: user_name",
     "footer-help" => "Cần giúp đỡ? Hỏi tại [support@selldone.com] (mailto: support@selldone.com) hoặc truy cập [trung tâm trợ giúp] của chúng tôi (https://selldone.com/help)",
     "footer-shop" => "Nếu bạn cần trợ giúp về bất cứ điều gì, vui lòng gửi email cho chúng tôi:: shop_mail",
     "accept" => "Chấp nhận",
     "reject" => "Từ chối",
     "verify" => "kiểm chứng",
     "title" => "Tiêu đề",
     "value" => "Giá trị",
     "description" => "Sự miêu tả",
     "Shop" => "Cửa hàng",
     "user" => "Người dùng",
     "license" => "Giấy phép",
     "status" => "Tình trạng",
     "start" => "Khởi đầu",
     "end" => "Chấm dứt",
     "renewal" => "Sự đổi mới",
     "view" => "Lượt xem",
     "balance" => "Sự cân bằng",
     "card_number" => "Số thẻ",
     "cvv" => "Cvv",
     "expire_date" => "Hạn sử dụng",
     "dashboard" => "bảng điều khiển",
     "order" => "gọi món",
     "view_order" => "Xem đơn đặt hàng",
     "pay_now" => "Pay now",
     "official_selldone" => "NGƯỜI BÁN CHÍNH THỨC",
     "account-number" => "Account number",
     "account-name" => "Account name",
     "currency" => "Tiền tệ",
     "free-balance" => "Số dư miễn phí",
     "locked-balance" => "Số dư bị khóa",
     "bot" => "Người máy",
     "requests" => "Yêu cầu",
     "baskets" => "Xe đẩy",
     "physical" => "Vật lý",
     "virtual" => "Ảo",
     "file" => "Tập tin",
     "service" => "Dịch vụ",
     "fulfillment" => "Sự hoàn thành",
     "open" => "Mở",
     "reserved" => "Để dành",
     "canceled" => "Đã hủy",
     "payed" => "Trả",
     "cod" => "COD",
     "orders-count" => "Đơn hàng",
     "payments-count" => "Thanh toán",
     "confirms-count" => "Xác nhận",
     "sends-count" => "Gửi",
     "delivers-count" => "Giao hàng",
     "count" => "Đếm",
     "transactions-count" => "Số lượng giao dịch",
     "success-transactions" => "Giao dịch thành công",
     "total-amount" => "Tổng cộng",
     "amount" => "Số lượng",
     "wage" => "Tiền công",
     "debug" => "Gỡ lỗi",
     "pos" => "POS",
     "live" => "Sống",
     "CheckQueue" => "Kiểm tra hàng đợi",
     "OrderConfirm" => "Xác nhận đơn hàng",
     "PreparingOrder" => "Chuẩn bị đơn đặt hàng",
     "SentOrder" => "Đã gửi đơn đặt hàng",
     "ToCustomer" => "Đã giao cho khách hàng",
     "Pending" => "Chưa giải quyết",
     "Accepted" => "Đã được chấp nhận",
     "Rejected" => "Từ chối",
     "pc" => "PC",
     "tablet" => "Máy tính bảng",
     "phone" => "Điện thoại",
     "total" => "Toàn bộ",
     "view-detail" => "Xem chi tiết",
     "empty" => "Làm rỗng cái gì",
     "dropshipping" => "Vận chuyển thả",
     "reply" => "Đáp lại",
     "reactions" => "Phản ứng",
     "comments" => "bình luận",
     "last-comment" => "Bình luận cuối cùng",
     "response-to" => "Phản hồi với",
     "posts" => "Bài viết",
     "post" => "Đăng tải",
     "name" => "Tên",
     "email" => "E-mail",
     "type" => "loại hình",
     "device" => "Thiết bị",
     "platform" => "Nền tảng",
     "browser" => "Trình duyệt",
     "time" => "Thời gian",
     "wallet" => "cái ví",
     "date" => "Ngày tháng",
     "account" => "Tài khoản",
     "transaction" => "Giao dịch",
     "fee" => "Học phí",
     "location" => "Location",
     "ip" => "Ip",
     "bill" => "Hóa đơn thanh toán",
     "category" => "Danh mục",
     "password" => "Mật khẩu",
     "shop" => "Cửa hàng",
     "verify-login" => "Xác minh & Đăng nhập",
     "url" => "URL",
     "avocado" => "Trái bơ",
     "hyper" => "Hyper",
     "buy-now" => "Mua ngay",
     "add-domain" => "Add Domain",
     "views" => "Lượt xem",
     "country" => "Quốc gia",
     "address" => "Địa chỉ",
     "postal" => "Mã bưu điện",
     "building_no" => "Tòa nhà #",
     "building_unit" => "Đơn vị #",
     "message" => "Tin nhắn",
     "customer" => "Khách hàng",
     "cart-items" => "Các mặt hàng trong giỏ hàng",
     "payment" => "Sự chi trả",
     "receiver" => "Người nhận",
     "virtual-items" => "Vật phẩm ảo",
     "no-payment" => "Không thanh toán!",
],
     "selldone-business-os" => "Hệ điều hành doanh nghiệp Selldone",
     "senders" => [
     "WeeklyReport" => [
     "id" => "performance",
     "name" => "Báo cáo hiệu suất, Selldone",
],
     "SeasonalReport" => [
     "id" => "seasonal",
     "name" => "Báo cáo theo mùa, Selldone",
],
     "Onboarding" => [
     "id" => "Chào",
     "name" => "Đội Selldone",
],
     "Support" => [
     "id" => "support",
     "name" => "Hỗ trợ: tên",
],
     "EmailVerify" => [
     "id" => "verify",
     "name" => "Xác minh, Selldone",
],
     "Welcome" => [
     "id" => "Chào",
     "name" => "Cộng đồng, Selldone",
],
     "NewShop" => [
     "id" => "thương gia",
     "name" => "Thương gia, Selldone",
],
     "Approve" => [
     "id" => "chấp thuận",
     "name" => "Chấp thuận, Selldone",
],
     "SellerReceiveOrder" => [
     "id" => "order",
     "name" => "Quản lý đơn hàng: tên",
],
     "Recovery" => [
     "id" => "sự hồi phục",
     "name" => "Nhóm phục hồi Selldone",
],
],
     "bill-status" => [
     "PENDING" => "Đang chờ xử lý ⌛",
     "PAYED" => "Trả phí ✅",
     "CANCELED" => "Đã hủy ❌",
],
     "shop-invite" => [
     "LEVEL-NAME" => [
     "ADMIN" => "Người quản lý",
     "OFFICER" => "Cán bộ và Giám sát",
     "AUDITING" => "Giám đốc kiểm toán",
     "EMPLOYEE" => "Nhân viên",
     "PRODUCT" => "Quản lý sản phẩm",
     "CONTENT" => "Nội dung quản lí",
     "MARKETING" => "Giám đốc tiếp thị",
     "VIEWER" => "Người xem",
],
     "subject" => ": inviter Mời bạn với tư cách: cấp độ | :cửa tiệm",
     "category" => "Lời mời nhân viên",
     "title" => "Bạn đã được mời vào <b>: shop_name</b> với tư cách là <b>: level</b> .",
     "message" => "Một lời mời đã được gửi đến bạn. Bạn có thể xác nhận hoặc từ chối nó. Nếu lời mời này được bạn chấp thuận, bạn phải vào dịch vụ Selldone để xác nhận. Bằng cách xác nhận lời mời này, bạn sẽ có quyền truy cập vào phần quản lý cửa hàng.",
],
     "welcome-email" => [
     "subject" => "👋 Chào mừng: tên, Một số điều thú vị chỉ dành cho bạn.",
     "category" => "CONGRATULATION",
     "title" => "CHÀO MỪNG BẠN ĐẾN VỚI SELLDONE",
     "message" => "Cảm ơn bạn đã chọn Selldone, Bạn hiện là thành viên của cộng đồng Selldone kết nối người bán toàn cầu với khách hàng, Doanh nghiệp địa phương với doanh nghiệp, Cá nhân với tập đoàn! Tất cả các công cụ chính và chuyên nghiệp đã được cung cấp ** miễn phí ** và ** không giới hạn ** cho bạn. Bạn cố gắng, chúng tôi mở cửa, Just Do It!",
     "seller" => [
     "title" => "Bạn là người bán?",
     "message" => "Để bắt đầu bán hàng, hãy nhập trang tổng quan của bạn trong Selldone qua liên kết bên dưới và tạo cửa hàng đầu tiên của bạn hoàn toàn miễn phí. Quá trình này sẽ mất vài phút và bạn sẽ có cửa hàng và trang web trực tuyến của riêng mình. Sau đó chúng tôi sẽ hướng dẫn bạn các bước tiếp theo và lấy cổng thanh toán.",
     "action" => "Đăng nhập vào trang tổng quan của tôi",
],
     "buyer" => [
     "title" => "Tôi là người mua",
     "message" => "Xin chúc mừng. Một khi bạn là thành viên của Selldone, bạn sẽ thoát khỏi tất cả những phức tạp của tư cách thành viên và xác thực trong các cửa hàng trực tuyến. Để hưởng lợi từ bất kỳ cửa hàng và trang web nào sử dụng nền tảng Selldone, bạn có thể đăng nhập bằng một cú nhấp chuột và thực hiện mua hàng đơn giản, nhanh chóng và an toàn.",
],
],
     "charge-account" => [
     "category" => "Wallet> Tài khoản> Phí",
     "title" => "Phí thành công",
     "message" => "Tài khoản của bạn <b>: account_number</b> đã được thành công <b>: số tiền</b> được tính.",
     "account" => "Tài khoản",
     "charge" => "Thù lao",
     "balance" => "Sự cân bằng",
     "footer" => "Giúp cho việc kinh doanh trở nên dễ dàng, có thể đạt được và mọi người trên thế giới đều có thể tiếp cận được.",
],
     "verify-email" => [
     "subject" => "🙌 Hoàn tất đăng ký Selldone của bạn! Xác minh liên kết.",
     "category" => "BẠN CHỈ CÓ MỘT BƯỚC ĐI",
     "title" => "Xác minh địa chỉ email của bạn",
     "message" => "Xin chào tên,<br> Cảm ơn bạn đã chọn Selldone.<br> Vui lòng xác nhận rằng **: email ** là địa chỉ e-mail của bạn bằng cách nhấp vào nút hoặc sử dụng liên kết dưới đây trong vòng 48 giờ.",
     "footer" => "Nếu bạn gặp sự cố khi nhấp vào nút Xác minh, hãy sao chép và dán URL bên dưới vào trình duyệt web của bạn: __: activation_url__",
],
     "verify-email-code" => [
     "subject" => "Mã xác minh cho: tên",
     "category" => "SECURITY",
     "title" => "Mã xác minh email",
     "message" => "Xin chào tên,<br><br> Vui lòng xác nhận rằng **: email ** là địa chỉ e-mail của bạn bằng mã này trong vòng 10 phút.",
],
     "onboarding-verify-email" => [
     "subject" => "🎉 Cửa hàng của bạn đã sẵn sàng | :Tên",
     "category" => "BẠN CHỈ CÓ MỘT BƯỚC ĐI",
     "title" => "Thiết lập hoàn tất",
     "account_title" => "Tài khoản của bạn",
     "account_msg" => "Xác minh và đăng nhập vào tài khoản của bạn bằng thông tin này.",
     "shop_msg" => "Thông tin tài khoản trên hệ điều hành kinh doanh Selldone.",
],
     "reset2fa" => [
     "category" => "THÔNG ĐIỆP CHÍNH THỨC CỦA BẢO MẬT",
     "title" => "Yêu cầu tắt đăng nhập 2 bước",
     "message" => "Bạn nhận được email này vì chúng tôi đã nhận được yêu cầu đặt lại xác thực 2 yếu tố cho tài khoản của bạn.<br><br> Email người dùng <b>:: email</b><br> Tên <b>:: tên</b>",
     "footer" => "Nếu bạn không yêu cầu đặt lại mật khẩu, bạn không cần thực hiện thêm hành động nào.",
     "action" => "Tắt đăng nhập hai bước",
],
     "build-new-shop" => [
     "subject" => "🎊 Cửa hàng của bạn đã sẵn sàng ngay bây giờ!",
     "category" => "SINH RA CỬA HÀNG TRỰC TUYẾN MỚI TRÊN THẾ GIỚI",
     "title" => "Kỷ niệm",
     "message" => "<b>Chúc mừng: tên, bạn đã tạo một doanh nghiệp trực tuyến mới;</b> Chúng tôi chúc bạn thành công trong công việc kinh doanh của mình. Chào mừng đến với cộng đồng Selldoners.<br> Bạn cố gắng, chúng tôi mở cửa, và Bạn đã làm được.",
     "pdf-book" => "Đừng bỏ lỡ cuốn sách tay đính kèm: Do Your Business Like A Game",
     "account" => [
     "title" => "Bước 1: Tạo tài khoản trong ví Selldone",
     "message" => "Nếu bạn chưa có tài khoản trong ví của mình, hãy tạo một tài khoản. Selldone khấu trừ phí từ tài khoản này. Bạn có thể nạp tiền vào tài khoản này và Selldone cũng sẽ tính phí bạn một khoản tín dụng để nếu tài khoản này bị âm, trang web và Cửa hàng của bạn sẽ tiếp tục hoạt động.",
     "action" => "Đăng nhập vào ví",
],
     "shop-account" => [
     "title" => "Bước 2: Kết nối tài khoản với cửa hàng",
     "message" => "Thêm tài khoản ví của bạn vào cửa hàng của bạn. Để thực hiện việc này, hãy nhập Cửa hàng> Kế toán> Hóa đơn và kết nối tài khoản với cửa hàng. Lưu ý rằng tất cả các khoản thanh toán của khách hàng đều được gửi trực tiếp vào tài khoản ngân hàng của bạn và Selldone không có số tiền nào được rút hoặc khấu trừ, vì vậy bạn cần kết nối tài khoản Selldone này với cửa hàng.",
     "action" => "Bảng điều khiển hóa đơn lưu trữ",
],
     "gateway" => [
     "title" => "Bước 3: Kết nối Cổng thanh toán trực tuyến",
     "message" => "Đi tới Cửa hàng> Kế toán> Cổng và nhấn <b>Thêm cổng mới</b> . Sau khi chọn đơn vị tiền tệ, bạn sẽ được hiển thị danh sách các cổng di động. Kết nối cổng trong Selldone rất đơn giản và nhanh chóng, nhưng nếu bạn có Niza để được hướng dẫn, hãy tham khảo phần hướng dẫn Selldone hoặc hỏi chúng tôi.",
     "action" => "Thêm một cổng vào cửa hàng",
],
     "domain" => [
     "title" => "Bước cuối cùng: kết nối một miền chuyên dụng",
     "message" => "Bạn sẽ có thể có cửa hàng của mình trên bao nhiêu miền tùy thích. Để kết nối miền chuyên dụng với cửa hàng, bạn cần có ít nhất giấy phép khởi động. Bằng cách giới thiệu từng người bạn với Selldone, bạn sẽ nhận được thẻ quà tặng giấy phép khởi nghiệp một tháng. Một phần trăm thanh toán của bạn bè cũng sẽ được ghi có vào tài khoản của khách hàng của bạn.",
     "action" => "Giới thiệu và nhận thẻ quà tặng không giới hạn",
],
],
     "basket-list" => [
     "item" => "mục",
     "count" => "Đếm",
     "price" => "giá",
     "discount-code" => "Mã giảm giá",
     "customer-club" => "Câu lạc bộ khách hàng",
     "shipping" => "Đang chuyển hàng",
     "total" => "Toàn bộ",
     "offer" => "Phục vụ",
     "coupon" => "Phiếu mua hàng",
     "lottery" => "Phần thưởng",
     "tax" => "Thuế",
     "tax_included" => "Đã bao gồm trong giá",
     "tax_shipping" => "Shipping Tax",
],
     "buyable-payments" => [
     "method" => "Phương pháp",
     "amount" => "Số lượng",
     "giftcard" => "Gift card",
     "payment" => "Sự chi trả",
],
     "shop-subscription-email" => [
     "category" => "Cập nhật đăng ký",
     "title" => "Giấy phép Cửa hàng:: shop_title",
     "title-reserved" => "Giấy phép dự trữ:: shop_title",
     "title-active" => "Giấy phép đang hoạt động:: shop_title",
     "title-finished" => "Giấy phép đã hoàn thành:: shop_title",
     "title-cancel" => "Huỷ giấy phép:: shop_title",
     "message" => "Gói giấy phép cửa hàng của bạn đã được cập nhật,",
     "RESERVED" => "⚡ Gói đăng ký của bạn đã được ** đặt trước **.",
     "ACTIVE" => "🟢 Gói đăng ký của bạn đã được ** kích hoạt **.",
     "FINISHED" => "🚧 Gói đăng ký của bạn đã ** hoàn tất **.",
     "CANCEL" => "⛔ Gói đăng ký của bạn đã bị ** hủy bỏ **.",
],
     "support" => [
     "subject" => "Trung tâm hỗ trợ | : tên đã trả lời",
     "category" => "Trung tâm hỗ trợ",
     "title" => "Bạn đã nhận được phản hồi",
     "action" => "Quản trị viên mở cửa hàng",
],
     "shop-customer-join" => [
     "subject" => "Tham gia: shop_title",
     "category" => "Lễ kỷ niệm khách hàng mới",
     "title" => "Chúng tôi rất vui vì thành viên của bạn",
     "action" => "Đến thăm bây giờ",
],
     "shop-giftcard" => [
     "subject" => "Thẻ quà tặng: shop_title",
     "category" => "Thêm thẻ mới",
     "title" => "Xin chúc mừng, bạn đã nhận được một thẻ quà tặng",
     "action" => "Mua sắm ngay bây giờ",
     "message" => "Bạn đã nhận được một thẻ quà tặng với số tiền là: số dư: tiền tệ. Bạn sẽ có thể mua từ cửa hàng của chúng tôi với thẻ quà tặng này.",
],
     "contact" => [
     "subject" => "Trung tâm hỗ trợ | :cửa tiệm",
     "category" => "ủng hộ",
     "title" => "Bạn đã nhận được phản hồi",
],
     "order-checkout" => [
     "subject" => "🛍 Đặt hàng Thanh toán | : order_id",
     "title" => "gọi món",
     "message" => "Đơn đặt hàng của bạn xác nhận,<br> Chúng tôi đã nhận được đơn đặt hàng của bạn. Chúng tôi sẽ gửi cho bạn một email khác khi đơn đặt hàng của bạn được giao.",
     "payments" => "Thanh toán",
],
     "order-payment" => [
     "subject" => "🛍 Xác nhận Thanh toán | : order_id",
     "title" => "Đề nghị thanh toán",
     "message" => "Thanh toán của bạn đã hoàn tất,<br> Chúng tôi đã nhận được đơn đặt hàng của bạn. Chúng tôi sẽ gửi cho bạn một email khác khi đơn đặt hàng của bạn được giao.",
     "payments" => "Thanh toán",
],
     "get-voucher" => [
     "subject" => "Chúc mừng: tên | Phiếu mua hàng mới:: title",
     "category" => "XIN CHÚC MỪNG, VOUCHER MỚI",
     "message" => "Bạn nhận được phiếu mua hàng mới, Đây là một món quà từ chúng tôi dành cho bạn. Bạn có thể nhận được nhiều hơn từ những phiếu thưởng này bằng cách giới thiệu Selldone với bạn bè và những người bạn biết. Phiếu mua hàng này có giá trị **: price: currency **.<br> Bạn thử xem, chúng tôi mở các tính năng Chúc mừng, Mở khóa bằng voucher của bạn!",
     "action" => "Bảng điều khiển của tôi",
],
     "received-gift" => [
     "subject" => "Xin chúc mừng, Kính gửi: name | Bạn đã nhận được một món quà",
     "category" => "Thông báo nhận quà",
     "title" => "Quà tặng cho bạn",
     "message" => "Bạn đã nhận được một món quà mới. Đây là một món quà từ Selldone. Bạn có thể nhận được nhiều quà tặng hơn bằng cách tích cực hơn trong Selldone và phát triển cửa hàng cũng như nâng cao mức độ chuyên môn hóa của mình. Giá trị Quà tặng này là **: price: currency ** mà bạn có thể nạp trực tiếp vào ví của mình trong selldone.<br><br> Sử dụng quà tặng này để nâng cấp giấy phép cửa hàng của bạn và sử dụng nhiều công cụ hơn trong kinh doanh trực tuyến của bạn.",
     "action" => "Những món quà",
],
     "order-payment-admin" => [
     "subject" => "🛍 Đơn hàng mới đã nhận | : order_id",
     "title" => "New Order",
     "message" => "Bạn đã nhận được một đơn đặt hàng mới. Vui lòng truy cập trang xử lý đơn đặt hàng trong cửa hàng của bạn.",
],
     "virtual-item" => [
     "input-form-title" => "Thông tin đã điền của bạn",
     "output-form-title" => "Thông tin mặt hàng đã mua",
],
     "selldone-weekly-report" => [
     "subject" => "📬: shop_title | Báo cáo hàng tuần: thời gian",
     "title" => "Báo cáo hiệu suất hàng tuần của cửa hàng",
     "message" => "Đây là báo cáo hàng tuần của cửa hàng bạn từ: bắt đầu đến: kết thúc. Báo cáo này bao gồm các mẹo để cải thiện hoạt động kinh doanh của bạn, bạn cũng có thể kiểm tra trạng thái của cửa hàng trực tuyến và các đơn đặt hàng gần đây. Tôi hy vọng bạn có một ngày và tuần mới tốt lành.",
],
     "shop-seasonal-report" => [
     "subject" => "☘ Của bạn: Báo cáo tiết kiệm số tiền trong ba tháng qua | : shop_title",
     "title" => "Báo cáo theo mùa về hoạt động kinh doanh, phần thưởng và khoản tiết kiệm tài chính của bạn",
     "message" => "Đây là: shop_title báo cáo theo mùa của bạn từ: bắt đầu đến: kết thúc.",
],
     "EC-ShopAccounts" => [
     "title" => "Các tài khoản được kết nối",
     "sub-title" => "Trạng thái mới nhất của tài khoản ví được kết nối với cửa hàng của tôi là gì?",
     "view-wallet" => "Xem ví",
     "tip-title" => "Những lời khuyên quan trọng",
     "tip" => "Trong bước tiếp theo, hãy tạo một tài khoản miễn phí trong ví Selldone của bạn và kết nối nó với cửa hàng này. Ngay cả khi số dư tài khoản Selldone của bạn bị âm, khách hàng vẫn có thể mua hàng và thanh toán cho cửa hàng của bạn mà không gặp bất kỳ sự cố nào. Dữ liệu và dịch vụ của bạn sẽ không bị gián đoạn hoặc hạn chế trong ít nhất 1 tháng.",
     "view-my-wallet" => "My wallet",
     "connect-account" => "Kết nối với tài khoản",
],
     "EC-ShopApps" => [
     "title" => "Ứng dụng đã cài đặt",
     "sub-title" => "Danh sách các ứng dụng bạn đã cài đặt trong cửa hàng của mình trong tuần này.",
     "tip" => "Bạn có muốn tìm thêm ứng dụng cho cửa hàng của mình không?",
     "view-app-store" => "Truy cập Cửa hàng ứng dụng Selldone ..",
],
     "EC-ShopBots" => [
     "title" => "Bots trong cửa hàng của bạn",
     "sub-title" => "Các bot bán hàng đang hoạt động trong cửa hàng của tôi.",
     "tip-title" => "Giảm giá Bot",
     "tip" => "Selldone đã cung cấp cho bạn các bot bán hàng tự động. Tất cả những gì bạn phải làm là chuyển đến bảng Tiện ích> Bots và kích hoạt các bot cửa hàng của bạn. Lưu ý rằng dịch vụ liên quan phải có sẵn ở quốc gia của bạn.",
     "view-bots" => "Quản lý bot",
],
     "EC-ShopContacts" => [
     "title" => "Giao tiếp với khách hàng",
     "sub-title" => "Tôi đã có bao nhiêu liên hệ với khách hàng của mình trong tuần này?",
     "faqs" => "Các câu hỏi thường gặp",
     "tickets" => "Vé khách hàng",
],
     "EC-ShopData" => [
     "title" => "Trạng thái người dùng",
     "sub-title" => "Từ ngày: bắt đầu đến: kết thúc",
     "users" => [
     "title" => "Khách hàng",
     "subtitle" => "Người dùng đăng ký",
],
     "views" => [
     "title" => "Lượt truy cập",
     "subtitle" => "Bạn đã ghé thăm cửa hàng bao nhiêu lần rồi",
],
     "new_visitors" => "New Users",
     "returning_visitors" => "Người dùng đã trả lại",
     "shop_views" => "Lượt xem cửa hàng",
     "baskets" => [
     "title" => "Xe đẩy hàng",
     "subtitle" => "Báo cáo số lượng giỏ hàng mới",
],
     "products" => [
     "title" => "Tổng quan về sản phẩm",
     "subtitle" => "Tình trạng sản phẩm trong cửa hàng theo loại",
     "value_name" => "Các sản phẩm",
],
     "products_count" => "Các loại sản phẩm",
     "views_count" => "Lượng xem",
     "sell_count" => "Số lượng bán",
     "send_count" => "Số lượng vận chuyển",
],
     "EC-ShopDropShipping" => [
     "title" => "Vận chuyển thả",
     "sub-title" => "Bảng điều khiển dành cho những người bán lớn của Drop Shipping Selldone.",
     "total_fulfillments" => "Tổng số đơn đặt hàng đã nhận",
     "ds_count" => "Đơn hàng đã nhận",
     "statistics_title" => "Báo cáo đơn đặt hàng đã nhận",
     "ds_cancels" => "Hủy bởi người bán giao diện",
     "ds_rejects" => "Hủy bỏ bởi bạn",
     "tip" => "Bạn có phải là người bán hàng lớn không? Bạn có sở hữu một nhà kho, nhà máy hoặc nhà phân phối sản phẩm? Bạn có thể cung cấp sản phẩm của mình cho những người bán khác trong dịch vụ Selldone Drop Shipping để bán sản phẩm của bạn trên quy mô lớn. Gửi email cho chúng tôi theo địa chỉ support@selldone.com để hướng dẫn bạn.",
     "view-drop-shipping-panel" => "Đăng nhập vào bảng điều khiển bán buôn",
],
     "EC-ShopExchangeRates" => [
     "title" => "Tỷ giá hối đoái",
     "sub-title" => "Danh sách tỷ giá quy đổi tiền tệ mới nhất trong cửa hàng của bạn.",
     "from" => "Tiền tệ nguồn",
     "to" => "Đơn vị tiền tệ đích",
     "rate" => "Tỷ lệ chuyển đổi",
     "vew-exchange-panel" => "bảng quản lý tỷ giá hối đoái",
],
     "EC-ShopExperts" => [
     "title" => "Hợp đồng chuyên gia",
     "sub-title" => "Chuyên gia nào làm việc trên cửa hàng của tôi?",
     "cost" => "Giá trị hợp đồng",
     "duration" => "Khoảng thời gian",
     "start_at" => "Start Date",
     "complete_at" => "Completion Date",
     "cancel_at" => "Ngày hủy bỏ",
     "end_at" => "Ngày giao hàng",
     "tip" => "Bạn có thể thuê các chuyên gia giỏi nhất ở Selldone để phát triển doanh nghiệp của mình.",
     "view-experts" => "Bấm để bắt đầu.",
],
     "EC-ShopGateways" => [
     "title" => "Payment gateways",
     "sub-title" => "Báo cáo các cổng thanh toán đang hoạt động trên shop: shop.",
     "tip-title" => "Những lời khuyên quan trọng",
     "tip" => "Truy cập trang quản lý cổng trong cửa hàng của bạn và thêm ít nhất một cổng sau vài phút. Khách hàng của bạn thích thanh toán nhanh chóng và an toàn thông qua các cổng trực tuyến.",
     "view-shop-gateways" => "Đăng nhập vào quản lý cổng thông tin cửa hàng của tôi.",
     "view-gateways" => "Xem thêm các cổng khác",
],
     "EC-ShopOrders" => [
     "title" => "Đơn hàng",
     "sub-title" => "Danh sách các đơn đặt hàng tôi nhận được trong tuần này.",
     "total_baskets" => "Tổng số đơn hàng",
     "total_posBaskets" => "Tổng số đơn đặt hàng bằng tiền mặt",
     "pos-title" => "Hộp cửa hàng POS",
     "chart-label" => "Các đơn đặt hàng đã hoàn thành (những đơn đặt hàng này không nhất thiết phải được thanh toán!)",
     "tip-title" => "Bạn nên cố gắng hơn nữa ...",
     "tip" => "Không có thành công đơn giản.",
],
     "EC-ShopProcessCenter" => [
     "title" => "Trung tâm xử lý",
     "sub-title" => "Chúng tôi đã xử lý bao nhiêu đơn hàng trong cửa hàng trong tuần này?",
     "tip-title" => "Bạn đã không có một cuộc mua bán!",
     "tip" => "Thật không may, bạn không có bất kỳ doanh số bán hàng nào trong tuần này. Bạn cần đến cửa hàng của mình nhiều hơn. Bạn có thể thêm nhiều sản phẩm hơn, chọn hình ảnh đẹp hơn hoặc viết mô tả tốt hơn cho sản phẩm của mình. Cân nhắc một công việc toàn thời gian cho doanh nghiệp của bạn. Nếu bạn làm đúng và không nản lòng, bạn sẽ thành công.",
     "view-process-center" => "Xem trung tâm quy trình",
     "return" => [
     "title" => "Đơn hàng đã trả lại",
     "subtitle" => "Báo cáo các đơn hàng bị trả lại.",
     "tip-title" => "Bạn có biết rằng ...",
     "tip" => "Bạn có thể tạo bao nhiêu máy tính tiền tại cửa hàng tùy thích thông qua Selldone POS! Trên thực tế, bạn có thể biến máy tính bảng, điện thoại di động hoặc máy tính xách tay thành hộp thư đến của mình. Nếu điều đó kích thích bạn, Selldone POS Đó là thứ bạn nên bắt đầu sử dụng ngay bây giờ. Chỉ cần một cú nhấp chuột đơn giản để khởi chạy, chúng tôi đã chuẩn bị trước mọi thứ cho máy chủ của bạn.",
     "view-pos" => "Đăng nhập vào Thu ngân cửa hàng trực tuyến của tôi",
],
],
     "EC-ShopSessions" => [
     "title" => "Phiên",
     "sub-title" => "Tôi đã ghé thăm cửa hàng của mình bao nhiêu lần?",
     "countries-title" => "Những quốc gia nào đã được ghé thăm nhiều nhất?",
],
     "EC-PublicMessage" => [
     "title" => "Bạn có muốn kiếm tiền mà không tốn một đồng nào không?",
     "message" => "Kính gửi: name, bạn có thể vào Dashboard> Demonetization và tạo liên kết giới thiệu. Gửi liên kết cho bạn bè của bạn, Bạn sẽ nhận được thẻ quà tặng Selldone và phần trăm thanh toán của bạn bè. Lưu ý rằng thẻ quà tặng sẽ được gửi cho cả bạn và bạn bè của bạn.",
     "action" => "Xem liên kết giới thiệu của tôi",
     "mail-clip" => "<b style='color: #C2185B'>Quan trọng:</b> Nếu bạn sử dụng các dịch vụ email như Gmail giới hạn độ dài của email, hãy tìm tùy chọn sau ở cuối email để hiển thị báo cáo đầy đủ và nhấp vào nó:",
     "no-coin-reward" => "<b style='color: #C2185B'>Rất tiếc:</b> Hoạt động của bạn không đáp ứng yêu cầu để nhận phần thưởng SEL Xu miễn phí. Cố gắng hơn nữa và bán được nhiều hơn trên cửa hàng của bạn cho mùa giải tới.",
     "yes-coin-reward" => "<b style='color: #4CAF50'>Phần thưởng:</b> Xin chúc mừng, vì thành tích tuyệt vời của bạn, chúng tôi đã tặng bạn phần thưởng miễn phí: SEL Coin.",
     "need-buy-license" => "<b>Nâng cấp doanh nghiệp của bạn:</b> Bạn chưa đăng ký bất kỳ gói đăng ký nào cho trang web doanh nghiệp của mình! Vì vậy, đã đến lúc mua ít nhất một gói đăng ký. Nó chỉ tốn: số tiền hàng tháng để mua hàng năm.",
     "not-afford-message" => "Nếu bạn không đủ khả năng hoặc gặp bất kỳ khó khăn nào với việc thanh toán, vui lòng cho chúng tôi biết qua support@selldone.com.",
     "add-domain" => "<b>Tại sao không có miền tùy chỉnh cho doanh nghiệp của bạn?</b><br> Thêm miền vào trang web của bạn ngay bây giờ; nó miễn phí!",
],
     "Widget-Socials" => [
     "title" => "Selldone là một<del> sản phẩm</del> <span style = 'color: forestgreen'>cộng đồng</span> .<br> Hãy là một Selldoner chuyên nghiệp!",
     "message" => "Theo dõi các trang chính thức của Selldone trên Twitter, LinkedIn và các mạng xã hội. Gửi cho chúng tôi bất kỳ nhận xét, yêu cầu hoặc phê bình nào hoặc tham gia vào các cuộc thảo luận về Selldone. Chúng tôi cũng là một phần của cộng đồng Selldone mà <b>Bạn tạo ra</b> .",
],
     "avocado-seller-daily-report" => [
     "subject" => "Đã nhận được đơn đặt hàng Bơ mới | : shop_title: time",
     "title" => "Báo cáo hiệu suất trong 24 giờ qua",
     "message" => "Khách hàng của bạn đang đợi đơn đặt hàng của bạn được xem xét và định giá. Đáp ứng yêu cầu của khách hàng càng sớm càng tốt để có được nhiều doanh thu hơn.",
     "card_title" => "Đơn hàng trong hàng đợi",
     "card_subtitle" => "Từ ngày",
     "card_payed" => "Đơn đặt hàng đã trả tiền",
],
     "community-comments" => [
     "subject" => "Trả lời bài đăng của bạn trong: community_title",
     "title" => ": name, và: đếm những người khác đã nhận xét về bài đăng của bạn.",
     "title-simple" => ": tên đã nhận xét về bài viết của bạn.",
],
     "community-topic" => [
     "subject" => "🔔 Trả lời chủ đề của bạn: topic_title",
     "title" => ": tên, và: đếm những người khác đã trả lời về chủ đề của bạn.",
     "title-simple" => ": tên đã trả lời về chủ đề của bạn.",
],
     "user-login" => [
     "subject" => "🔔 Đăng nhập mới: tên",
     "category" => "Thông báo bảo mật",
     "title" => "Đăng nhập vào tài khoản",
     "message" => "Kính gửi: tên, bạn đã đăng nhập vào tài khoản Selldone của mình.",
     "footer" => "Nếu bạn chưa đăng nhập, vui lòng thay đổi mật khẩu của bạn.",
],
     "account-transaction" => [
     "withdraw" => "Rút tiền",
     "deposit" => "Gửi tiền",
     "withdraw_subject" => "rút từ tài khoản: tài khoản",
     "deposit_subject" => "Nộp tiền vào tài khoản: tài khoản",
     "message" => "Việc chuyển tiền đã được thực hiện với các thông số kỹ thuật sau.",
     "type" => "Loại giao dịch",
     "from" => "Nguồn tài khoản",
     "to" => "Destination account",
     "desc" => "Mô tả giao dịch",
     "action" => "Xem giao dịch",
],
     "penalty" => [
     "subject" => "⛔ Quan trọng! Vi phạm nội quy | :cửa tiệm",
     "category" => "Thông tin quan trọng",
     "title" => "Cửa hàng của bạn đã bị phạt",
     "action" => "Mở trang tổng quan cửa hàng",
],
     "invite" => [
     "subject" => ": người mời đã mời bạn đến Selldone",
     "title" => ": tên đã gửi cho bạn: số tiền để giúp bạn khởi chạy trang web trực tuyến mới của mình và kiếm tiền từ nó!",
     "message" => "Trên Selldone, bạn có thể tạo thương mại điện tử, trang web viết blog và cộng đồng trực tuyến của mình và thậm chí có được một máy bán hàng trực tuyến và thiết lập bán hàng trực tiếp trong vài phút. Đó là một hệ điều hành kinh doanh trực tuyến để làm cho doanh nghiệp của bạn trực tuyến, tốt hơn và nhanh hơn. Chỉ cần đăng ký trước <b>: ngày</b> để nhận: phiếu giảm giá.",
     "accept" => "Chấp nhận lời mời",
     "owner" => "Chủ sở hữu của",
     "join-date" => "Trên Selldone kể từ",
],
     "shop-recovery" => [
     "subject" => "Liên kết khôi phục | :cửa tiệm",
     "category" => "Bảo mật cửa hàng",
     "title" => "Liên kết khôi phục cửa hàng của <b>: shop_name</b> .",
     "message" => "Email này được gửi cho bạn vì bạn đã yêu cầu khôi phục cửa hàng của mình. Nhấp vào liên kết dưới đây sẽ khôi phục cửa hàng của bạn và tất cả dữ liệu thuộc về nó.",
     "action" => "Xác nhận khôi phục cửa hàng",
],
     "SR-SeasonalSaving" => [
     "title" => "Selldone đã tiết kiệm được bao nhiêu tiền cho công việc kinh doanh của bạn?",
     "sub-title" => "Từ ngày: bắt đầu đến: kết thúc",
     "infrastructure" => [
     "title" => "Cơ sở hạ tầng",
     "subtitle" => "Máy chủ, CDN, Bộ nhớ và các dịch vụ đám mây khác",
],
     "experts" => [
     "title" => "Chuyên gia & Nhân viên",
     "subtitle" => "Nhà phát triển, bảo trì và hỗ trợ",
],
     "total_save" => "Tổng số tiền tiết kiệm được",
],
     "SR-SeasonalPerformance" => [
     "title" => "Hiệu suất của bạn",
     "sub-title" => "Tổng quan kinh doanh từ: bắt đầu đến: kết thúc",
     "new_visitors" => "New Users",
     "returning_visitors" => "Người dùng đã trả lại",
     "shop_views" => "Lượt xem cửa hàng",
     "baskets" => [
     "title" => "Xe đẩy hàng",
     "subtitle" => "Báo cáo số lượng giỏ hàng mới",
],
     "products" => [
     "title" => "Tổng quan về sản phẩm",
     "subtitle" => "Tình trạng sản phẩm trong cửa hàng theo loại",
     "value_name" => "Các sản phẩm",
],
     "views" => [
     "title" => "Page Views",
     "subtitle" => "Tổng số lượt xem trang của trang web",
],
],
];