<?php 

 return [
     "home" => "selldone",
     "blogs" => "Blog",
     "helps" => "Għajnuna",
     "current_location" => "Din id-dħul",
     "dashboard" => "dashboard",
     "my_shops" => "L-Imħażen Tiegħi",
     "wallet" => "wallet",
     "about" => "Dwar Selldone",
     "contact" => "contact us",
     "comments" => "comments",
     "likes" => "Jħobb",
     "power" => "ferħ",
     "build_free_shop" => "Ibni l-maħżen tiegħek b'xejn",
     "shop_name" => "shop name",
     "categories" => "categories",
     "sub_articles" => "More",
     "terms" => "Termini",
     "colour" => "kulur",
     "style" => "style",
     "volume" => "volume",
     "weight" => "weight",
     "pack" => "Pakkett",
     "type" => "type",
     "add_to_card" => "Żid mal-CART",
     "overview" => "Overview",
     "reviews" => "Reviżjonijiet",
     "spec" => "Speċifikazzjoni sħiħa",
     "you_may_also_like" => "Inti tista 'wkoll tixtieq",
     "about_us" => "Fuqna",
     "contact_us" => "contact us",
     "cookie_privacy" => "Cookie &amp; privacy policy",
     "follow_us" => "Segwina",
     "category" => "Kategorija",
     "author" => "Written by ",
     "published_at" => "Ippubblikat fi",
     "modified_at" => "Modifikat fi",
     "price" => "prezz",
     "discount" => "Roħs",
     "price_after_discount" => "Prezz wara skont",
     "available" => "Disponibbli",
     "sold_out" => "Mibjuħ",
     "buy" => "Ixtri issa",
     "login_shop" => "Idħol Ħanut",
     "posted_on" => "Posted on :data",
];