<?php 

 return [
     "home" => "გაყიდული",
     "blogs" => "ბლოგი",
     "helps" => "დახმარება",
     "current_location" => "ეს ჩანაწერი",
     "dashboard" => "dashboard",
     "my_shops" => "ჩემი მაღაზიები",
     "wallet" => "wallet",
     "about" => "სელდონის შესახებ",
     "contact" => "contact us",
     "comments" => "comments",
     "likes" => "მოსწონს",
     "power" => "გაიხარე",
     "build_free_shop" => "შექმენით თქვენი მაღაზია უფასოდ",
     "shop_name" => "shop name",
     "categories" => "categories",
     "sub_articles" => "More",
     "terms" => "Ვადები",
     "colour" => "ფერი",
     "style" => "style",
     "volume" => "volume",
     "weight" => "weight",
     "pack" => "შეფუთვა",
     "type" => "type",
     "add_to_card" => "Კალათაში დამატება",
     "overview" => "Overview",
     "reviews" => "მიმოხილვები",
     "spec" => "სრული სპეც",
     "you_may_also_like" => "შეიძლება თქვენც მოგეწონოთ",
     "about_us" => "Ჩვენს შესახებ",
     "contact_us" => "contact us",
     "cookie_privacy" => "Cookie &amp; privacy policy",
     "follow_us" => "მოგვყევი",
     "category" => "კატეგორია",
     "author" => "Written by ",
     "published_at" => "გამოქვეყნებულია",
     "modified_at" => "შეცვლილია ზე",
     "price" => "ფასი",
     "discount" => "ფასდაკლება",
     "price_after_discount" => "ფასი ფასდაკლების შემდეგ",
     "available" => "ხელმისაწვდომია",
     "sold_out" => "Გაყიდულია",
     "buy" => "Იყიდე ეხლა",
     "login_shop" => "შესვლა მაღაზია",
     "posted_on" => "გამოქვეყნებულია :date",
];