<?php 

 return [
     "invoice" => "Faktur",
     "serial" => "Nomor Seri",
     "date" => "Tanggal faktur",
     "seller" => "Penjual",
     "buyer" => "Pembeli",
     "address" => "alamat",
     "code" => "Kode",
     "vat" => "kode PPN",
     "phone" => "Telepon",
     "description" => "Keterangan",
     "units" => "Satuan",
     "quantity" => "jumlah",
     "price" => "harga",
     "discount" => "Diskon",
     "tax" => "Pajak",
     "sub_total" => "SubTotal",
     "total_discount" => "Total diskon",
     "taxable_amount" => "Jumlah kena pajak",
     "total_taxes" => "Total pajak",
     "tax_rate" => "Persentase pajak",
     "total_amount" => "Jumlah total",
     "pay_until" => "Silahkan bayar sampai",
     "amount_in_words" => "Jumlah dalam kata-kata",
     "amount_in_words_format" => "%s %s dan %s %s",
     "notes" => "Catatan",
     "shipping" => "Pengiriman",
     "paid" => "Dibayar",
     "due" => "Jatuh tempo",
];