<?php 

 return [
     "profile" => "Darllen gwybodaeth proffil gan gynnwys enw, cyfeiriad e-bost, delwedd a statws dilysu.",
     "phone" => "Mynediad rhif cyswllt",
     "address" => "Darllen a golygu cyfeiriad o'r llyfr cyfeiriadau sydd wedi'i gadw",
     "buy" => "Archeb a Siop Archeb.",
     "order-history" => "Darllenwch hanes archeb.",
     "my-gift-cards" => "Access to my cards.",
     "articles" => "Golygu Erthyglau.",
     "notifications" => "Anfon a derbyn hysbysiadau.",
     "read-shops" => "Darllen Rhestr Siop.",
     "shop-edit" => "Mynediad golygu storfa.",
     "shop-contacts" => "Derbyn a golygu ffurflenni cyswllt.",
     "shop-gift-cards" => "Creu, Golygu, a Rheoli Cardiau.",
     "shop-faqs" => "Creu, golygu a rheoli cwestiynau cyffredin.",
     "shop-categories" => "Creu, Golygu, a Rheoli Categorïau.",
     "shop-products" => "Creu, Golygu a Rheoli Cynhyrchion.",
     "shop-read-reports" => "Darllen gwybodaeth ac adroddiadau.",
     "shop-socials" => "Golygu rhwydweithiau cymdeithasol storfa.",
     "shop-accounts" => "Golygu a dileu cyfrifon ariannol sy'n gysylltiedig â siop.",
     "shop-menus" => "Golygu dewislenni siop.",
     "shop-pages" => "Golygu tudalennau siop.",
     "shop-warehouse" => "Golygu Warws Store",
     "shop-permissions" => "Gweld a golygu mynediad siop.",
     "shop-process-center" => "Rheoli archebion a dderbyniwyd.",
     "shop-profile" => "Rheoli proffiliau siopau.",
     "shop-discount-code" => "Rheoli codau disgownt.",
     "shop-coupon" => "Rheoli cwponau.",
     "shop-offer" => "Rheoli cynigion.",
     "shop-lottery" => "Rheoli loterïau.",
     "shop-community" => "Rheoli cymuned.",
];