<?php 

 return [
     "home" => "ਵੇਚਿਆ",
     "blogs" => "ਬਲੌਗ",
     "helps" => "ਮਦਦ ਕਰੋ",
     "current_location" => "ਇਹ ਇੰਦਰਾਜ਼",
     "dashboard" => "dashboard",
     "my_shops" => "ਮੇਰੇ ਸਟੋਰ",
     "wallet" => "wallet",
     "about" => "Selldone ਬਾਰੇ",
     "contact" => "contact us",
     "comments" => "comments",
     "likes" => "ਪਸੰਦ ਹੈ",
     "power" => "ਖੁਸ਼ੀ",
     "build_free_shop" => "ਮੁਫ਼ਤ ਵਿੱਚ ਆਪਣਾ ਸਟੋਰ ਬਣਾਓ",
     "shop_name" => "shop name",
     "categories" => "categories",
     "sub_articles" => "More",
     "terms" => "ਸ਼ਰਤਾਂ",
     "colour" => "ਰੰਗ",
     "style" => "style",
     "volume" => "volume",
     "weight" => "weight",
     "pack" => "ਪੈਕ",
     "type" => "type",
     "add_to_card" => "ਠੇਲ੍ਹੇ ਵਿੱਚ ਪਾਓ",
     "overview" => "Overview",
     "reviews" => "ਸਮੀਖਿਆਵਾਂ",
     "spec" => "ਪੂਰੀ ਸਪੈਸ",
     "you_may_also_like" => "ਤੁਸੀਂ ਵੀ ਪਸੰਦ ਕਰ ਸਕਦੇ ਹੋ",
     "about_us" => "ਸਾਡੇ ਬਾਰੇ",
     "contact_us" => "contact us",
     "cookie_privacy" => "Cookie &amp; privacy policy",
     "follow_us" => "ਸਾਡੇ ਪਿਛੇ ਆਓ",
     "category" => "ਸ਼੍ਰੇਣੀ",
     "author" => "Written by ",
     "published_at" => "'ਤੇ ਪ੍ਰਕਾਸ਼ਿਤ",
     "modified_at" => "'ਤੇ ਸੋਧਿਆ ਗਿਆ",
     "price" => "ਕੀਮਤ",
     "discount" => "ਛੂਟ",
     "price_after_discount" => "ਛੋਟ ਤੋਂ ਬਾਅਦ ਕੀਮਤ",
     "available" => "ਉਪਲੱਬਧ",
     "sold_out" => "ਸਭ ਵਿੱਕ ਗਇਆ",
     "buy" => "ਹੁਣੇ ਖਰੀਦੋ",
     "login_shop" => "ਲੌਗਇਨ ਦੁਕਾਨ",
     "posted_on" => "ਮਿਤੀ: ਮਿਤੀ ਨੂੰ ਪੋਸਟ ਕੀਤਾ ਗਿਆ",
];