<?php 

 return [
     "invoice" => "Рахунок-фактура",
     "serial" => "Серійний номер.",
     "date" => "Дата рахунку-фактури",
     "seller" => "Продавець",
     "buyer" => "Покупець",
     "address" => "адреса",
     "code" => "код",
     "vat" => "код ПДВ",
     "phone" => "Телефон",
     "description" => "Опис",
     "units" => "одиниці",
     "quantity" => "кількість",
     "price" => "ціна",
     "discount" => "Знижка",
     "tax" => "податок",
     "sub_total" => "Підсумок",
     "total_discount" => "Загальна знижка",
     "taxable_amount" => "Оподатковувана сума",
     "total_taxes" => "Загальні податки",
     "tax_rate" => "Ставка податку",
     "total_amount" => "Загальна кількість",
     "pay_until" => "Будь ласка, сплатіть до",
     "amount_in_words" => "Сума прописом",
     "amount_in_words_format" => "%s %s і %s %s",
     "notes" => "Примітки",
     "shipping" => "Доставка",
     "paid" => "Оплачено",
     "due" => "належний",
];