<?php 

 return [
     "accepted" => "Необхідно прийняти атрибут :attribute.",
     "accepted_if" => "Поле :attribute має бути прийнятним, якщо :other є :value.",
     "active_url" => ":attribute не є дійсною URL-адресою.",
     "after" => ":attribute має бути датою після :date.",
     "after_or_equal" => ":attribute має бути датою після або дорівнювати :date.",
     "alpha" => "Атрибут :може містити лише літери.",
     "alpha_dash" => "Атрибут :може містити лише літери, цифри та тире.",
     "alpha_num" => ":attribute може містити лише літери та цифри.",
     "array" => ":attribute має бути масивом.",
     "ascii" => "Поле :attribute має містити лише однобайтові буквено-цифрові символи та символи.",
     "before" => ":attribute має бути датою перед :date.",
     "before_or_equal" => ":attribute має бути датою, що передує або дорівнює :date.",
     "between" => [
     "array" => ":attribute має містити між елементами :min і :max.",
     "file" => ":attribute має бути між :min і :max кілобайтами.",
     "numeric" => ":attribute має бути між :min та :max.",
     "string" => ":attribute має бути між символами :min і :max.",
],
     "boolean" => "Поле :attribute має мати значення true або false.",
     "can" => "Поле :attribute містить недозволене значення.",
     "confirmed" => "Підтвердження :attribute не збігається.",
     "contains" => "У полі :attribute відсутнє обов’язкове значення.",
     "current_password" => "Пароль неправильний.",
     "date" => ":attribute не є дійсною датою.",
     "date_equals" => "Поле :attribute має бути датою, що дорівнює :date.",
     "date_format" => ":attribute не відповідає формату :format.",
     "decimal" => "Поле :attribute має містити :decimal знаків після коми.",
     "declined" => "Поле :attribute має бути відхилено.",
     "declined_if" => "Поле :attribute має бути відхилено, якщо :other дорівнює :value.",
     "different" => ":attribute та :other мають бути різними.",
     "digits" => ":attribute має бути :digits цифрами.",
     "digits_between" => ":attribute має бути між :min та :max цифрами.",
     "dimensions" => ":attribute має недійсні розміри зображення.",
     "distinct" => "Поле :attribute має повторюване значення.",
     "doesnt_end_with" => "Поле :attribute не має закінчуватися одним із таких: :values.",
     "doesnt_start_with" => "Поле :attribute не має починатися з одного з наступного: :values.",
     "email" => ":attribute має бути дійсною електронною адресою.",
     "ends_with" => "Поле :attribute має закінчуватися одним із таких: :values.",
     "enum" => "Вибраний :attribute недійсний.",
     "exists" => "Вибраний :attribute недійсний.",
     "extensions" => "Поле :attribute повинно мати одне з таких розширень: :values.",
     "file" => ":attribute має бути файлом.",
     "filled" => "Поле :attribute має містити значення.",
     "gt" => [
     "array" => ":attribute має містити більше ніж :value елементів.",
     "file" => ":attribute має бути більшим за :value кілобайт.",
     "numeric" => ":attribute має бути більшим за :value.",
     "string" => ":attribute має бути більшим за :value.",
],
     "gte" => [
     "array" => ":attribute повинен містити елементи :value або більше.",
     "file" => ":attribute має бути більшим або дорівнювати :value кілобайтам.",
     "numeric" => ":attribute має бути більшим або дорівнювати :value.",
     "string" => ":attribute має бути більше або дорівнювати символам :value.",
],
     "hex_color" => "Поле :attribute має мати дійсний шістнадцятковий колір.",
     "image" => ":attribute має бути зображенням.",
     "in" => "Вибраний :attribute недійсний.",
     "in_array" => "Поле :attribute не існує в :other.",
     "integer" => ":attribute має бути цілим числом.",
     "ip" => ":attribute має бути дійсною IP-адресою.",
     "ipv4" => ":attribute має бути дійсною адресою IPv4.",
     "ipv6" => ":attribute має бути дійсною адресою IPv6.",
     "json" => ":attribute має бути дійсним рядком JSON.",
     "list" => "Поле :attribute має бути списком.",
     "lowercase" => "Поле :attribute має бути малим регістром.",
     "lt" => [
     "array" => ":attribute має містити менше ніж :value елементів.",
     "file" => ":attribute має бути меншим за :value кілобайт.",
     "numeric" => ":attribute має бути меншим за :value.",
     "string" => ":attribute має містити менше ніж :value символів.",
],
     "lte" => [
     "array" => ":attribute не може містити більше ніж :value елементів.",
     "file" => ":attribute має бути меншим або дорівнювати :value кілобайтам.",
     "numeric" => ":attribute має бути меншим або дорівнювати :value.",
     "string" => ":attribute має містити менше або дорівнювати символам :value.",
],
     "mac_address" => "Поле :attribute має бути дійсною MAC-адресою.",
     "max" => [
     "array" => ":attribute не може містити більше ніж :max елементів.",
     "file" => ":attribute не може бути більшим за :max кілобайт.",
     "numeric" => ":attribute не може перевищувати :max.",
     "string" => ":attribute не може містити більше :max символів.",
],
     "max_digits" => "Поле :attribute не повинно містити більше ніж :max цифр.",
     "mimes" => ":attribute має бути файлом типу: :values.",
     "mimetypes" => ":attribute має бути файлом типу: :values.",
     "min" => [
     "array" => ":attribute має містити принаймні :min елементів.",
     "file" => ":attribute має бути не менше :min кілобайт.",
     "numeric" => ":attribute має бути принаймні :min.",
     "string" => ":attribute має містити принаймні :min символів.",
],
     "min_digits" => "Поле :attribute має містити принаймні :min цифр.",
     "missing" => "Поле :attribute має бути відсутнім.",
     "missing_if" => "Поле :attribute має бути відсутнім, якщо :other є :value.",
     "missing_unless" => "Поле :attribute має бути відсутнім, якщо :other не є :value.",
     "missing_with" => "Поле :attribute має бути відсутнім, якщо присутній :values.",
     "missing_with_all" => "Поле :attribute має бути відсутнім, якщо присутні :values.",
     "multiple_of" => "Поле :attribute має бути кратним :value.",
     "not_in" => "Вибраний :attribute недійсний.",
     "not_regex" => "Формат :attribute недійсний.",
     "numeric" => ":attribute має бути числом.",
     "password" => [
     "letters" => "Поле :attribute має містити принаймні одну літеру.",
     "mixed" => "Поле :attribute має містити принаймні одну велику та одну малу літери.",
     "numbers" => "Поле :attribute має містити принаймні одне число.",
     "symbols" => "Поле :attribute має містити принаймні один символ.",
     "uncompromised" => "Даний :attribute з’явився під час витоку даних. Виберіть інший :attribute.",
],
     "present" => "Поле :attribute має бути присутнім.",
     "present_if" => "Поле :attribute має бути присутнім, коли :other є :value.",
     "present_unless" => "Поле :attribute має бути присутнім, якщо :other не є :value.",
     "present_with" => "Поле :attribute має бути присутнім, якщо присутній :values.",
     "present_with_all" => "Поле :attribute має бути присутнім, якщо присутні :values.",
     "prohibited" => "Поле :attribute заборонено.",
     "prohibited_if" => "Поле :attribute заборонено, якщо :other дорівнює :value.",
     "prohibited_unless" => "Поле :attribute заборонено, якщо :other не міститься в :values.",
     "prohibits" => "Поле :attribute забороняє присутність :other.",
     "regex" => "Формат :attribute недійсний.",
     "required" => "Поле :attribute є обов’язковим.",
     "required_array_keys" => "Поле :attribute має містити записи для: :values.",
     "required_if" => "Поле :attribute є обов’язковим, якщо :other дорівнює :value.",
     "required_if_accepted" => "Поле :attribute є обов’язковим, якщо прийнято :other.",
     "required_if_declined" => "Поле :attribute є обов’язковим, якщо відхилено :other.",
     "required_unless" => "Поле :attribute є обов’язковим, якщо :other не міститься в :values.",
     "required_with" => "Поле :attribute є обов’язковим, якщо присутній :values.",
     "required_with_all" => "Поле :attribute є обов’язковим, якщо присутній :values.",
     "required_without" => "Поле :attribute є обов’язковим, якщо немає :values.",
     "required_without_all" => "Поле :attribute є обов’язковим, якщо немає жодного з :values.",
     "same" => ":attribute та :other мають збігатися.",
     "size" => [
     "array" => ":attribute повинен містити елементи :size.",
     "file" => ":attribute має бути :size кілобайт.",
     "numeric" => ":attribute має бути :size.",
     "string" => ":attribute має бути символами :size.",
],
     "starts_with" => "Поле :attribute має починатися з одного з наступного: :values.",
     "string" => ":attribute має бути рядком.",
     "timezone" => ":attribute має бути дійсною зоною.",
     "unique" => "Атрибут : уже використано.",
     "uploaded" => "Не вдалося завантажити :attribute.",
     "uppercase" => "Поле :attribute має бути великим.",
     "url" => "Формат :attribute недійсний.",
     "ulid" => "Поле :attribute має бути дійсним ULID.",
     "uuid" => "Поле :attribute має бути дійсним UUID.",
     "custom" => [
     "attribute-name" => [
     "rule-name" => "custom-message",
],
     "g-recaptcha-response" => [
     "required" => "Підтвердьте, що ви не робот.",
     "captcha" => "Помилка Captcha! спробуйте пізніше або зверніться до адміністратора сайту.",
],
],
     "attributes" => [
        
     ],
];