<?php 

 return [
     "profile" => "Profil ma'lumotlarini o'qing, jumladan ism, elektron pochta manzili, rasm va autentifikatsiya holati.",
     "phone" => "Aloqa raqamiga kirish",
     "address" => "Saqlangan manzillar kitobidan manzilni o'qing va tahrirlang",
     "buy" => "Buyurtma va xarid qilish.",
     "order-history" => "Buyurtma tarixini o'qing.",
     "my-gift-cards" => "Access to my cards.",
     "articles" => "Maqolalarni tahrirlash.",
     "notifications" => "Bildirishnomalarni yuborish va qabul qilish.",
     "read-shops" => "Do'konlar ro'yxatini o'qing.",
     "shop-edit" => "Tahrirlash ruxsatini saqlash.",
     "shop-contacts" => "Aloqa shakllarini qabul qilish va tahrirlash.",
     "shop-gift-cards" => "Kartochkalarni yaratish, tahrirlash va boshqarish.",
     "shop-faqs" => "Tez-tez beriladigan savollarni yarating, tahrirlang va boshqaring.",
     "shop-categories" => "Kategoriyalarni yaratish, tahrirlash va boshqarish.",
     "shop-products" => "Mahsulotlarni yaratish, tahrirlash va boshqarish.",
     "shop-read-reports" => "Ma'lumot va hisobotlarni o'qing.",
     "shop-socials" => "Do'konning ijtimoiy tarmoqlarini tahrirlash.",
     "shop-accounts" => "Do'konga bog'langan moliyaviy hisoblarni tahrirlash va o'chirish.",
     "shop-menus" => "Do'kon menyularini tahrirlash.",
     "shop-pages" => "Do'kon sahifalarini tahrirlash.",
     "shop-warehouse" => "Do'kon omborini tahrirlash",
     "shop-permissions" => "Doʻkonga kirishni koʻrish va tahrirlash.",
     "shop-process-center" => "Qabul qilingan buyurtmalarni boshqarish.",
     "shop-profile" => "Do'kon profillarini boshqaring.",
     "shop-discount-code" => "Chegirma kodlarini boshqaring.",
     "shop-coupon" => "Kuponlarni boshqarish.",
     "shop-offer" => "Takliflarni boshqarish.",
     "shop-lottery" => "Lotereyalarni boshqaring.",
     "shop-community" => "Jamiyatni boshqaring.",
];