<?php 

 return [
     "home" => "Selldone",
     "blogs" => "博客",
     "helps" => "帮助",
     "current_location" => "当前位置",
     "dashboard" => "仪表盘",
     "my_shops" => "我的店铺",
     "wallet" => "钱包",
     "about" => "关于 Selldone",
     "contact" => "联系我们",
     "comments" => "评论",
     "likes" => "喜欢",
     "power" => "加油",
     "build_free_shop" => "免费建立您的商店",
     "shop_name" => "店铺名称",
     "categories" => "分类",
     "sub_articles" => "更多",
     "terms" => "条款",
     "colour" => "颜色",
     "style" => "风格",
     "volume" => "体积",
     "weight" => "重量",
     "pack" => "包装",
     "type" => "类型",
     "add_to_card" => "添加到购物车",
     "overview" => "概览",
     "reviews" => "评论",
     "spec" => "完整规格",
     "you_may_also_like" => "你可能也喜欢",
     "about_us" => "关于我们",
     "contact_us" => "联系我们",
     "cookie_privacy" => "Cookie & 隐私政策",
     "follow_us" => "关注我们",
     "category" => "分类",
     "author" => "作者 ",
     "published_at" => "发布于",
     "modified_at" => "修改于",
     "price" => "价格",
     "discount" => "折扣",
     "price_after_discount" => "折扣后的价格",
     "available" => "可用",
     "sold_out" => "售罄",
     "buy" => "立即购买",
     "login_shop" => "登录商店",
     "posted_on" => "发表于：日期",
];
