<?php 

 return [
     "email-types-description" => [
     "shop-customer-join" => "Stu messagiu accoglie un novu cumpratore in a buttrega.",
     "order-checkout" => "Questa notificazione hè mandata quandu un cumpratore cunfirma un ordine.",
     "order-payment" => "Questa notificazione cunfirma u pagamentu successu fattu da un cliente.",
     "order-payment-admin" => "Stu messagiu hè mandatu à un venditore per avvisà li di un ordine cunfirmatu.",
     "pos-checkout" => "Questa notificazione hè mandata per cunfirmà un ordine di puntu di vendita per un cumpratore.",
     "pos-payment" => "Questa notificazione cunfirma un pagamentu puntu di vendita fattu da un cumpratore.",
     "pos-payment-admin" => "Stu missaghju informa u vinditore di una compra fatta in u so puntu di vendita.",
     "shop-contact" => "Questa notificazione hè mandata quandu un furmulariu di cuntattu hè statu sottumessu.",
     "shop-giftcard" => "Questa notificazione informa un utilizatore chì hà ricevutu una carta rigalu.",
     "shop-vendor-join" => "Stu messagiu accoglie un novu venditore in a buttrega.",
     "shop-vendor-invite" => "Stu messagiu hè speditu per invità un venditore à unisce à u vostru mercatu.",
     "shop-vendor-order" => "Stu missaghju hè mandatu à u vinditore quandu un ordine hè ricevutu in u statu Paid o Cash on Delivery (COD).",
     "shop-vendor-products" => "Speditu ogni ghjornu per aghjurnà i venditori nantu à u statutu di i so prudutti.",
     "shop-login" => "Notificà l'utilizatore cù i dati di login, cumpresu l'indirizzu IP, a data è u dispositivu, per scopi di sicurità.",
     "login-code" => "Mandate un codice di password una volta per l'utilizatori per accede à a tenda.",
     "shop-email-verify-link" => "Mandate un ligame per verificà l'indirizzu email di l'utilizatore. Stu mail hè mandatu quandu un utilizatore si registra per SMS è entre in u so email è ùn hè micca mandatu quandu l'utilizatore si registra per e-mail o suciali direttamente.",
],
     "global" => [
     "greetings" => "Salute : nome",
     "end-statement" => "Squadra di sustegnu",
     "receiver_name" => "Salute : user_name",
     "footer-help" => "Avete bisognu di aiutu? Fate à [support@selldone.com](mailto:support@selldone.com) o visitate u nostru [help center](https://selldone.com/help)",
     "footer-shop" => "Sè avete bisognu di aiutu cù qualcosa per piacè ùn esitate à abbandunà un email: :shop_mail",
     "accept" => "Accetta",
     "reject" => "Rifiuta",
     "verify" => "verificate",
     "title" => "Titulu",
     "value" => "Valore",
     "description" => "Descrizzione",
     "Shop" => "Shop",
     "user" => "User",
     "license" => "Licenza",
     "status" => "Status",
     "start" => "Principià",
     "end" => "fine",
     "renewal" => "Rinuvamentu",
     "view" => "Vede",
     "balance" => "Balance",
     "card_number" => "Numero di carta",
     "cvv" => "Cvv",
     "expire_date" => "Data di scadenza",
     "dashboard" => "dashboard",
     "order" => "ordine",
     "view_order" => "Vede l'ordine",
     "pay_now" => "Pay now",
     "official_selldone" => "VENDUTA UFFICIALE",
     "account-number" => "Account number",
     "account-name" => "Account name",
     "currency" => "valuta",
     "free-balance" => "Bilanciu liberu",
     "locked-balance" => "Equilibre chjusu",
     "bot" => "Bot",
     "requests" => "E dumande",
     "baskets" => "carretti",
     "physical" => "Fisica",
     "virtual" => "Virtuale",
     "file" => "File",
     "service" => "serviziu",
     "fulfillment" => "Cumplimentu",
     "open" => "Apertu",
     "reserved" => "Riservatu",
     "canceled" => "Annulatu",
     "payed" => "Pagatu",
     "cod" => "COD",
     "orders-count" => "Ordini",
     "payments-count" => "Pagamenti",
     "confirms-count" => "Cunfirma",
     "sends-count" => "Mandate",
     "delivers-count" => "Consegna",
     "count" => "Conti",
     "transactions-count" => "E transacciones contanu",
     "success-transactions" => "Transazzione di successu",
     "total-amount" => "A quantità tutale",
     "amount" => "A quantità",
     "wage" => "Salariu",
     "debug" => "Debug",
     "pos" => "POS",
     "live" => "Live",
     "CheckQueue" => "Verificate a fila",
     "OrderConfirm" => "Ordine cunfirmatu",
     "PreparingOrder" => "Preparazione di l'ordine",
     "SentOrder" => "Mandatu ordine",
     "ToCustomer" => "Cunsegna à u cliente",
     "Pending" => "In attesa",
     "Accepted" => "Acceptatu",
     "Rejected" => "Rifiutata",
     "pc" => "PC",
     "tablet" => "Tablet",
     "phone" => "telefonu",
     "total" => "Totale",
     "view-detail" => "Vede i dettagli",
     "empty" => "Viotu",
     "dropshipping" => "Dropshipping",
     "reply" => "Rispondimi",
     "reactions" => "Reazzione",
     "comments" => "cumenti",
     "last-comment" => "Ultimu cumentu",
     "response-to" => "Risposta à",
     "posts" => "Posti",
     "post" => "Post",
     "name" => "Nome",
     "email" => "E-mail",
     "type" => "tipu",
     "device" => "Dispositivu",
     "platform" => "Piattaforma",
     "browser" => "Browser",
     "time" => "U tempu",
     "wallet" => "portafoglio",
     "date" => "Data",
     "account" => "contu",
     "transaction" => "Transazzione",
     "fee" => "Tariffa",
     "location" => "Location",
     "ip" => "IP",
     "bill" => "Bill",
     "category" => "categuria",
     "password" => "Codice",
     "shop" => "Shop",
     "verify-login" => "Verificate è accede",
     "url" => "URL",
     "avocado" => "Avocado",
     "hyper" => "Hyper",
     "buy-now" => "Cumprà avà",
     "add-domain" => "Add Domain",
     "views" => "Viste",
     "country" => "Paese",
     "address" => "indirizzu",
     "postal" => "Codice pustale",
     "building_no" => "Edificiu #",
     "building_unit" => "Unità #",
     "message" => "Missaghju",
     "customer" => "Cliente",
     "cart-items" => "Articuli di u carrettu",
     "payment" => "Pagamentu",
     "receiver" => "Ricevitore",
     "virtual-items" => "Articuli virtuali",
     "no-payment" => "Nisun pagamentu !",
     "enable" => "Attivà",
     "access" => "Accessu",
     "bank" => "infurmazione bancaria",
     "vendor" => "Venditore",
     "view_content" => "Vede u cuntenutu sanu",
     "files" => "I schedari",
     "download" => "Scaricate",
     "file_name" => "File Name",
     "file_size" => "Taglia",
     "subscription" => "Abbonamentu",
     "products" => "I prudutti",
     "vendor_products" => "I prudutti di u venditore",
],
     "selldone-business-os" => "Selldone Business OS",
     "senders" => [
     "WeeklyReport" => [
     "id" => "performance",
     "name" => "Rapportu di performance, Selldone",
],
     "SeasonalReport" => [
     "id" => "seasonal",
     "name" => "Rapportu di stagione, Selldone",
],
     "Onboarding" => [
     "id" => "salute",
     "name" => "Approva, Selldone",
],
     "Support" => [
     "id" => "support",
     "name" => "Supportu : nome",
],
     "EmailVerify" => [
     "id" => "verify",
     "name" => "Verificate, Selldone",
],
     "Welcome" => [
     "id" => "salute",
     "name" => "Cumunità, Selldone",
],
     "NewShop" => [
     "id" => "i cummercianti",
     "name" => "Approva, Selldone",
],
     "Approve" => [
     "id" => "appruvà",
     "name" => "Approva, Selldone",
],
     "SellerReceiveOrder" => [
     "id" => "order",
     "name" => "Gestione di ordini : nome",
],
     "Recovery" => [
     "id" => "ricuperazione",
     "name" => "Selldone Recovery Team",
],
],
     "bill-status" => [
     "PENDING" => "In attesa ⌛",
     "PAYED" => "Pagatu ✅",
     "CANCELED" => "Annulatu ❌",
],
     "shop-invite" => [
     "LEVEL-NAME" => [
     "ADMIN" => "Amministratore",
     "OFFICER" => "Ufficiale è Supervisore",
     "AUDITING" => "Responsabile di auditing",
     "EMPLOYEE" => "Impiegatu",
     "PRODUCT" => "Manager di i prudutti",
     "CONTENT" => "Manager di cuntenutu",
     "MARKETING" => "Manager di marketing",
     "VIEWER" => "Viewer",
],
     "subject" => ":inviter Invitati cum'è :level | : buttrega",
     "category" => "Invitu di u persunale",
     "title" => "Avete statu invitatu à <b>:shop_name</b> cum'è <b>:level</b> .",
     "message" => "Un invitu hè statu mandatu à voi. Pudete cunfirmà o ricusà. Se sta invitazione hè appruvata da voi, deve entre in u serviziu di Selldone per cunfirmà. Cunfirmendu stu invitu, avete accessu à a sezione di gestione di a tenda.",
],
     "welcome-email" => [
     "subject" => "👋 Benvenuti : nome, Alcune cose interessanti solu per voi.",
     "category" => "CONGRATULATION",
     "title" => "BENVENU À SELLDONE",
     "message" => "Grazie per avè sceltu Selldone, site avà parte di a cumunità di Selldone chì cunnetta i venditori glubale à i clienti, l'impresa locale à l'impresa, l'individuu à a corporazione! Tutti i strumenti maestri è pro sò stati furniti **gratis** è **illimitati** per voi. Pruvate, apremu e porte, basta à fà !",
     "seller" => [
     "title" => "Sò un venditore?",
     "message" => "Per inizià a vendita, entre in u vostru dashboard in Selldone via u ligame sottu è crea a vostra prima tenda completamente gratis. Questu hà da piglià uni pochi di minuti è avete a vostra propria tenda è u situ in linea. Allora vi guideremu à i prossimi passi è uttene u gateway di pagamentu.",
     "action" => "Accedi à u mo dashboard",
],
     "buyer" => [
     "title" => "Sò un cumpratore",
     "message" => "Felicitazioni. Una volta site un membru di Selldone, sbararete di tutti i fastidi di l'appartenenza è l'autentificazione in i buttreghi in linea. Per prufittà di qualsiasi tenda è situ chì usa a piattaforma Selldone, pudete login cun un clic è fà a vostra compra simplice, veloce è sicura.",
],
],
     "charge-account" => [
     "category" => "Wallet> Account> Charge",
     "title" => "Carica di successu",
     "message" => "U vostru contu <b>:account_number</b> hè statu cun successu <b>:quantità</b> caricata.",
     "account" => "contu",
     "charge" => "Carica",
     "balance" => "Balance",
     "footer" => "Fate l'affari faciuli, rializabili è accessibili à tutti in u mondu.",
],
     "verify-email" => [
     "subject" => "🙌 Completa a vostra iscrizzione à Selldone! Verificate u ligame.",
     "category" => "TU SIETE A UN PASSU",
     "title" => "Verificate u vostru indirizzu email",
     "message" => "Salute : nome,<br> Grazie per avè sceltu Selldone.<br> Per piacè cunfirmà chì **:email** hè u vostru indirizzu e-mail clicchendu nant'à u buttone o aduprate u ligame sottu in 48 ore.",
     "footer" => "Sè avete prublemi à cliccà u buttone Verificate, copia è incollà l'URL sottu in u vostru navigatore web: __:activation_url__",
],
     "verify-email-code" => [
     "subject" => "Codice di verificazione per :name",
     "category" => "SECURITY",
     "title" => "Codice di verificazione email",
     "message" => "Salute : nome,<br><br> Per piacè cunfirmà chì **:email** hè u vostru indirizzu email cù stu codice in 10 minuti.",
],
     "onboarding-verify-email" => [
     "subject" => "🎉 A vostra tenda hè pronta | : nome",
     "category" => "TU SIETE A UN PASSU",
     "title" => "L'installazione hè finita",
     "account_title" => "U vostru contu",
     "account_msg" => "Verificate è accede à u vostru contu cù questa infurmazione.",
     "shop_msg" => "Info di u contu nantu à u sistema operatore cummerciale Selldone.",
],
     "reset2fa" => [
     "category" => "MESSAGGIU UFFICIALE DI SECURITY",
     "title" => "Richiesta disattivà u login in 2 passi",
     "message" => "Ricevete stu email perchè avemu ricevutu una dumanda di reset di autentificazione à 2 fattori per u vostru contu.<br><br> E-mail d'utilizatore: <b>:email</b><br> Nome: <b>: nome</b>",
     "footer" => "Se ùn avete micca dumandatu un resettore di password, ùn hè micca necessariu più azione.",
     "action" => "Disattivà u login in dui passi",
],
     "build-new-shop" => [
     "subject" => "🎊 A vostra buttrega hè pronta avà!",
     "category" => "NATA NOVA STORE ONLINE IN U MONDU",
     "title" => "Celebrendu",
     "message" => "<b>Felicitazione : nome, avete creatu un novu affari in linea;</b> Vulemu successu in a vostra attività. Benvenuti à a cumunità di Selldoners.<br> Pruvate, apremu e porte, è avete fattu.",
     "pdf-book" => "Ùn mancate micca u libru di manu attaccatu: Fate a vostra attività cum'è un ghjocu",
     "account" => [
     "title" => "Passu 1: Crea un contu in a billetera Selldone",
     "message" => "Se ùn avete micca un contu in a vostra billetera, creane unu. Selldone deduce a tarifa da stu contu. Pudete ripiglià stu contu, è Selldone vi incaricà dinù una quantità di creditu cusì chì, se stu contu hè negativu, u vostru situ è Store vi cuntinuà à upirari.",
     "action" => "Accedi à u wallet",
],
     "shop-account" => [
     "title" => "Passu 2: cunnette u contu à a tenda",
     "message" => "Aghjunghjite u vostru contu wallet à a vostra tenda. Per fà questu, entre Store> Accounting> Invoice è cunnette u contu à a tenda. Nota chì tutti i pagamenti di i vostri clienti sò dipositati direttamente in u vostru contu bancariu è nisuna quantità hè ritirata o dedotta da Selldone, cusì avete bisognu di cunnette stu contu di Selldone à a tenda.",
     "action" => "Pannello di fattura di a tenda",
],
     "gateway" => [
     "title" => "Passu 3: Connect Gateway di Pagamentu Online",
     "message" => "Andà à Store> Accounting> Port è appughjà <b>Add New Port</b> . Dopu à sceglie a munita, vi sarà mustratu una lista di porti portable. Cunnessu u portu in Selldone hè assai sèmplice è viloci, ma s'è vo avete Niza di guida, riferite à a rùbbrica di guida Selldone o dumandà à noi.",
     "action" => "Aghjunghjite un portale à a tenda",
],
     "domain" => [
     "title" => "Ultimu passu: cunnette un duminiu dedicatu",
     "message" => "Puderete avè a vostra tenda nantu à quanti duminii chì vulete. Per cunnette un duminiu dedicatu à una tenda, avete bisognu di avè almenu una licenza di startup. Introducendu ogni amicu à Selldone, riceverete una carta rigalu di licenza di startup di un mese. Un percentinu di i pagamenti di i vostri amichi serà ancu creditu à i cunti di i vostri clienti.",
     "action" => "Introducendu è riceve carte rigalu illimitate",
],
],
     "basket-list" => [
     "item" => "articulu",
     "count" => "Conti",
     "price" => "prezzu",
     "discount-code" => "Codice di sconto",
     "customer-club" => "Club di i Clienti",
     "shipping" => "spedizione",
     "total" => "Totale",
     "offer" => "Offerta",
     "coupon" => "Coupon",
     "lottery" => "Premiu",
     "tax" => "Tassa",
     "tax_included" => "Inclusu in u prezzu",
     "tax_shipping" => "Shipping Tax",
],
     "buyable-payments" => [
     "method" => "Metudu",
     "amount" => "A quantità",
     "giftcard" => "Gift card",
     "payment" => "Pagamentu",
],
     "shop-subscription-email" => [
     "category" => "Actualizazione di l'abbonamentu",
     "title" => "Licenza di Store: :shop_title",
     "title-reserved" => "Riserva di licenza: :shop_title",
     "title-active" => "Licenza attiva: :shop_title",
     "title-finished" => "Licenza finita: :shop_title",
     "title-cancel" => "Annulà a licenza: :shop_title",
     "message" => "U vostru pianu di licenza di a tenda hè aghjurnatu,",
     "RESERVED" => "⚡ U vostru pianu di abbonamentu hè statu **riservatu**.",
     "ACTIVE" => "🟢 U vostru pianu di abbonamentu hè statu **attivatu**.",
     "FINISHED" => "🚧 U vostru pianu di abbonamentu hè statu **finitu**.",
     "CANCEL" => "⛔ U vostru pianu di abbonamentu hè statu **annullatu**.",
],
     "support" => [
     "subject" => "Centru di sustegnu | : nome rispose",
     "category" => "Centru di sustegnu",
     "title" => "Avete ricevutu una risposta",
     "action" => "Apertura amministratore di a tenda",
],
     "shop-customer-join" => [
     "subject" => "Unisci à :shop_title",
     "category" => "Festa di u novu cliente",
     "title" => "Semu felici per a vostra adesione",
     "action" => "Visita avà",
],
     "shop-vendor-join" => [
     "subject" => "Vendor Onboarding | : shop_title",
     "category" => "Festa di u novu venditore",
     "title" => "Semu felici per a vostra adesione",
     "action" => "Vendor Panel",
],
     "shop-giftcard" => [
     "subject" => "Giftcard :shop_title",
     "category" => "Aghjunghjite una nova carta",
     "title" => "Felicitazioni, avete ricevutu una carta rigalu",
     "action" => "Cumprate avà",
     "message" => "Avete ricevutu una carta rigalu in quantità di :balance :currency. Puderete cumprà da a nostra tenda cù questa carta rigalu.",
],
     "contact" => [
     "subject" => "Centru di sustegnu | : buttrega",
     "category" => "sustegnu",
     "title" => "Avete ricevutu una risposta",
],
     "order-checkout" => [
     "subject" => "🛍 Ordine Checkout | : id_ordine",
     "title" => "ordine",
     "message" => "U vostru ordine cunfirmà,<br> Avemu u vostru ordine. Vi lasceremu un altru email quandu u vostru ordine spedisce.",
     "payments" => "Pagamenti",
],
     "order-payment" => [
     "subject" => "🛍 Cunfirmazione di Pagamentu | : id_ordine",
     "title" => "Ordine di pagamentu",
     "message" => "U vostru pagamentu cumpletu,<br> Avemu u vostru ordine. Vi lasceremu un altru email quandu u vostru ordine spedisce.",
     "payments" => "Pagamenti",
],
     "get-voucher" => [
     "subject" => "Felicitazione : nome | Novu voucher: :title",
     "category" => "FELICITAZIONI, NEW VOUCHER",
     "message" => "Avete un novu voucher, questu hè un rigalu da noi per voi. Pudete ottene più da questi vouchers presentendu Selldone à l'amichi è à tutti quelli chì cunnosci. Stu voucher vale **:price:currency**.<br> Pruvate, apremu e porte, Felicitazione, Sbloccate e funzioni cù u vostru voucher!",
     "action" => "U mo dashboard",
],
     "received-gift" => [
     "subject" => "Felicitazioni, Caru :name | Avete ricevutu un rigalu",
     "category" => "L'annunziu di riceve un rigalu",
     "title" => "Rigali per voi",
     "message" => "Avete ricevutu un novu rigalu. Questu hè un rigalu da Selldone. Pudete riceve più di sti rigali essendu più attivu in Selldone è sviluppendu a vostra tenda è elevendu u vostru livellu di specializazione. Stu valore di Gift hè **:price:currency** chì pudete deposità direttamente in a vostra billetera in selldone.<br><br> Aduprate stu rigalu per aghjurnà a vostra licenza di a tenda è utilizate più strumenti in a vostra attività in linea.",
     "action" => "Rigali",
],
     "order-payment-admin" => [
     "subject" => "🛍 Novu Ordine Ricevutu | : id_ordine",
     "title" => "New Order",
     "message" => "Avete ricevutu un novu ordine. Per piacè andate à a pagina di trasfurmazioni di l'ordine in a vostra tenda.",
],
     "virtual-item" => [
     "input-form-title" => "A vostra infurmazione cumpleta",
     "output-form-title" => "L'infurmazione nantu à l'articulu acquistatu",
],
     "selldone-weekly-report" => [
     "subject" => "📬 :shop_title | Rapportu settimanale : tempu",
     "title" => "Rapportu settimanale di u rendiment di u magazinu",
     "message" => "Questu hè u rapportu settimanale di a vostra tenda da :start à :end. Stu rapportu include cunsiglii per migliurà a vostra attività, pudete ancu verificà u statutu di a vostra tenda in linea è ordini recenti. Spergu chì avete un bonu ghjornu è settimana avanti.",
],
     "shop-seasonal-report" => [
     "subject" => "☘ U vostru :rapportu di risparmiu di quantità in l'ultimi trè mesi | : shop_title",
     "title" => "Rapportu stagionale nantu à a vostra attività cummerciale, ricumpensa è risparmiu finanziariu",
     "message" => "Questu hè u vostru rapportu di stagione :shop_title da :start à :end.",
],
     "EC-ShopAccounts" => [
     "title" => "Conti cunnessi",
     "sub-title" => "Chì ghjè l'ultimu statutu di i cunti di portafogli cunnessi à a mo tenda?",
     "view-wallet" => "Vede u wallet",
     "tip-title" => "Cunsiglii impurtanti",
     "tip" => "In u prossimu passu, crea un contu gratuitu in a vostra billetera Selldone è cunnette à questa tenda. Ancu s'è u vostru saldu di u vostru contu Selldone hè negativu, i vostri clienti ponu sempre fà cumerci è pagamenti per a vostra tenda senza prublemi. I vostri dati è serviziu ùn saranu micca interrotti o limitati per almenu 1 mese.",
     "view-my-wallet" => "My wallet",
     "connect-account" => "Cunnette vi cuntu",
],
     "EC-ShopApps" => [
     "title" => "Apps stallati",
     "sub-title" => "Lista di l'applicazioni chì avete installatu in a vostra tenda sta settimana.",
     "tip" => "Vulete truvà più app per a vostra tenda?",
     "view-app-store" => "Visita l'App Store di Selldone..",
],
     "EC-ShopBots" => [
     "title" => "U vostru Store Bots",
     "sub-title" => "Bots di vendita attivi in a mo tenda.",
     "tip-title" => "Vendita di bot",
     "tip" => "Selldone vi hà furnitu bots di vendita automatica. Tuttu ciò chì duvete fà hè di andà in u pannellu Add-ons> Bots è attivà i vostri bots di a tenda. Nota chì u serviziu pertinente deve esse dispunibule in u vostru paese.",
     "view-bots" => "Gestisce i bots",
],
     "EC-ShopContacts" => [
     "title" => "Comunicazione cù i Clienti",
     "sub-title" => "Quanti cuntatti aghju avutu cù i mo clienti sta settimana?",
     "faqs" => "Domande Frequenti",
     "tickets" => "Biglietti di i Clienti",
],
     "EC-ShopData" => [
     "title" => "Status di l'utilizatori",
     "sub-title" => "Da a data : principiu à : fine",
     "users" => [
     "title" => "Clienti",
     "subtitle" => "Iscriviti Users",
],
     "views" => [
     "title" => "Visite",
     "subtitle" => "Quante volte avete visitatu a tenda",
],
     "new_visitors" => "New Users",
     "returning_visitors" => "Utenti tornati",
     "shop_views" => "Shop Views",
     "baskets" => [
     "title" => "Carrelli di shopping",
     "subtitle" => "Segnala u numeru di novi carri di shopping",
],
     "products" => [
     "title" => "Panoramica di i prudutti",
     "subtitle" => "Status di i prudutti in a tenda per tipu",
     "value_name" => "I prudutti",
],
     "products_count" => "Tipi di prudutti",
     "views_count" => "Vede u conte",
     "sell_count" => "Conte di vendita",
     "send_count" => "Conte di spedizione",
],
     "EC-ShopDropShipping" => [
     "title" => "Drop Shipping",
     "sub-title" => "Panel per i principali venditori di Drop Shipping Selldone.",
     "total_fulfillments" => "Total Ordini Ricevuti",
     "ds_count" => "Ordini ricevuti",
     "statistics_title" => "Segnala ordini ricevuti",
     "ds_cancels" => "Cancella da u venditore di l'interfaccia",
     "ds_rejects" => "Cancella da voi",
     "tip" => "Sò un venditore maiò di merchenzie? Avete un magazzinu, una fabbrica o un distributore di prudutti? Pudete offre i vostri prudutti à altri venditori in u serviziu di Selldone Drop Shipping per vende u vostru pruduttu à grande scala. Mandateci un email à support@selldone.com per guidà vi.",
     "view-drop-shipping-panel" => "Accedi à u pannellu grossista",
],
     "EC-ShopExchangeRates" => [
     "title" => "Tassi di scambiu",
     "sub-title" => "Lista di l'ultimi tassi di cunversione di valuta in a vostra tenda.",
     "from" => "Valuta fonte",
     "to" => "Valuta di destinazione",
     "rate" => "Rate di cunversione",
     "vew-exchange-panel" => "pannellu di gestione di u scambiu",
],
     "EC-ShopExperts" => [
     "title" => "Cuntratti esperti",
     "sub-title" => "Chì prufessiunali travaglianu nantu à a mo tenda?",
     "cost" => "A quantità di u cuntrattu",
     "duration" => "Durata",
     "start_at" => "Start Date",
     "complete_at" => "Completion Date",
     "cancel_at" => "Data di annullà",
     "end_at" => "Data di consegna",
     "tip" => "Pudete impiegà i migliori specialisti in Selldone per sviluppà a vostra attività.",
     "view-experts" => "Cliccate per cumincià.",
],
     "EC-ShopGateways" => [
     "title" => "Payment gateways",
     "sub-title" => "Segnala i gateway di pagamentu attivi nantu à a buttrega :shop.",
     "tip-title" => "Cunsiglii impurtanti",
     "tip" => "Andate à a pagina di gestione di u portale in a vostra tenda è aghjunghje almenu un portu in pochi minuti. I vostri clienti piace à pagà rapidamente è in modu sicuru attraversu portali in linea.",
     "view-shop-gateways" => "Accedi à a mo gestione di u portale di a tenda.",
     "view-gateways" => "Vede più gateway",
],
     "EC-ShopOrders" => [
     "title" => "Ordini",
     "sub-title" => "Lista di ordini chì aghju ricevutu sta settimana.",
     "total_baskets" => "Ordini totali",
     "total_posBaskets" => "Ordini totali di Cash",
     "pos-title" => "Box Store POS",
     "chart-label" => "Ordini cumpletati (questi ordini ùn sò micca necessariamente pagati!)",
     "tip-title" => "Duvete pruvà di più ...",
     "tip" => "Nisun successu simplice.",
],
     "EC-ShopProcessCenter" => [
     "title" => "Centru di trasfurmazioni",
     "sub-title" => "Quantu ordine avemu processatu in a tenda sta settimana?",
     "tip-title" => "Ùn avete micca una vendita!",
     "tip" => "Sfurtunatamente ùn avete micca vendita sta settimana. Avete bisognu di più à a vostra tenda. Pudete aghjunghje più prudutti, sceglie l'imaghjini megliu o scrivite descrizzioni megliu per i vostri prudutti. Cunsiderate un travagliu full-time per a vostra attività. Se fate bè è ùn avete micca frustratu, avete successu.",
     "view-process-center" => "Vede u centru di prucessu",
     "return" => [
     "title" => "Ordine restituitu",
     "subtitle" => "Segnala l'ordini tornati.",
     "tip-title" => "Sapete chì...",
     "tip" => "Pudete creà quanti registratori di cassa in magazzini vulete attraversu Selldone POS! In fatti, pudete turnà a vostra tableta, telefuninu o laptop in u vostru inbox. S'ellu vi eccita, Selldone POS Hè qualcosa chì duvete cumincià à aduprà avà. Ci hè solu un clic simplice per lancià, avemu tuttu preparatu per u vostru servitore in anticipu.",
     "view-pos" => "Accedi à My Online Store Cashier",
],
],
     "EC-ShopSessions" => [
     "title" => "Sessioni",
     "sub-title" => "Quante volte aghju visitatu a mo tenda?",
     "countries-title" => "Quali paesi sò stati i più visitati?",
],
     "EC-PublicMessage" => [
     "title" => "Vulete fà soldi senza spende un dolar?",
     "message" => "Caru : nome, pudete andà in Dashboard> Demonetization è creà un ligame di riferimentu. Mandate u ligame à i vostri amichi, Ricevete una carta di rigalu Selldone è un percentinu di i pagamenti di u vostru amicu. Nota chì a carta rigalu serà mandata à voi è à u vostru amicu.",
     "action" => "Vede u mo ligame di introduzione",
     "mail-clip" => "<b style='color: #C2185B'>Impurtante:</b> Se utilizate servizii di e-mail cum'è Gmail chì limitanu a durata di l'email, truvate l'opzione seguente à a fine di l'email per vede u rapportu cumpletu è cliccate nantu à questu:",
     "no-coin-reward" => "<b style='color: #C2185B'>Scusate:</b> A vostra attività ùn hà micca scuntratu u requisitu per uttene una ricumpensa SEL Coins gratuiti. Pruvate più è vende più nantu à a vostra buttrega per a prossima stagione.",
     "yes-coin-reward" => "<b style='color: #4CAF50'>Ricompensa:</b> Felicitazioni, per via di a vostra fantastica prestazione, vi avemu datu una ricumpensa senza : quantità SEL Coin.",
     "need-buy-license" => "<b>Aumenta a vostra attività:</b> Ùn avete micca registratu alcun pianu di abbonamentu per u vostru situ web di cummerciale! Allora hè u tempu di cumprà almenu un abbonamentu. Custa solu: quantità mensili per a compra annuale.",
     "not-afford-message" => "Se ùn pudete micca pagà o avete qualchì prublema cù u pagamentu, sentite liberu di diteci via support@selldone.com.",
     "add-domain" => "<b>Perchè ùn avete micca un duminiu persunalizatu per a vostra attività?</b><br> Aghjunghjite un duminiu à u vostru situ web avà; hè gratis !",
],
     "Widget-Socials" => [
     "title" => "Selldone hè un<del> pruduttu</del> <span style = 'color: forestgreen'>cumunità</span> .<br> Siate un Selldoner prufessiunale!",
     "message" => "Segui e pagine ufficiali di u Selldone in Twitter, LinkedIn è e rete suciale. Mandateci qualsiasi cumenti, richieste o critiche o participà à discussioni nantu à u Selldone. Facemu ancu parte di a cumunità di Selldone chì <b>fate</b> .",
],
     "avocado-seller-daily-report" => [
     "subject" => "Ricevutu novi ordini Avocado | :shop_title :tempu",
     "title" => "Rapportu di rendiment per l'ultime 24 ore",
     "message" => "I vostri clienti aspettanu chì i vostri ordini per esse rivisiuti è prezzu. Rispondi à e dumande di i vostri clienti u più prestu pussibule per ottene più vendite.",
     "card_title" => "Ordini in a fila",
     "card_subtitle" => "Da: data",
     "card_payed" => "Ordini pagati",
],
     "community-comments" => [
     "subject" => "Rispondi à u vostru postu in :community_title",
     "title" => ":name, è :count altri anu cummentatu nantu à i vostri posti.",
     "title-simple" => ":name hà cummentatu nantu à i vostri posti.",
],
     "community-topic" => [
     "subject" => "🔔 Rispondi à u vostru tema :topic_title",
     "title" => ":name, è :count altri risposti nantu à u vostru tema.",
     "title-simple" => ": nome hà rispostu nantu à u vostru tema.",
],
     "user-login" => [
     "subject" => "🔔 New Login : nome",
     "category" => "Notificazioni di sicurità",
     "title" => "Accedi à u contu",
     "message" => "Caru : nome, avete statu login à u vostru contu Selldone.",
     "message-shop" => "Caru :name, site cunnessu à :shop_title .",
     "footer" => "Se ùn site micca cunnessu, cambiate a vostra password.",
],
     "account-transaction" => [
     "withdraw" => "Ritirata",
     "deposit" => "Depositu",
     "withdraw_subject" => "retirer du compte : account",
     "deposit_subject" => "Depositu à u contu : account",
     "message" => "U trasferimentu di soldi hè statu fattu cù e seguenti specificazioni.",
     "type" => "Tipu di transazzione",
     "from" => "Contu fonte",
     "to" => "Destination account",
     "desc" => "Descrizzione di a transazzione",
     "action" => "Vede a transazzione",
],
     "penalty" => [
     "subject" => "⛔ Impurtante! Viulenza di regule | : buttrega",
     "category" => "Informazione critica",
     "title" => "A vostra buttrega hè stata penalizzata",
     "action" => "Apertura dashboard di a tenda",
],
     "invite" => [
     "subject" => ":inviter vi hà invitatu à Selldone",
     "title" => ":name t'hà mandatu :quantità per aiutà à lancià u vostru novu situ web in linea è monetizà!",
     "message" => "In Selldone, pudete creà u vostru e-commerce, u situ web di blogging, è a cumunità in linea è ancu uttene un POS in linea è stabilisce a vendita in persona in pochi minuti. Hè un sistema operatore di cummerciale in linea per fà a vostra attività in linea, megliu è più veloce. Basta à iscrivete da <b>:date</b> per uttene un voucher :amount.",
     "accept" => "Accetta l'invitu",
     "owner" => "Pruprietariu di",
     "join-date" => "Dapoi Selldone",
],
     "shop-recovery" => [
     "subject" => "Link di ricuperazione | : buttrega",
     "category" => "Sicurezza di a tenda",
     "title" => "Ligame di ricuperazione di u magazinu di <b>:shop_name</b> .",
     "message" => "Questu email hè statu mandatu à voi perchè avete dumandatu à restaurà a vostra tenda. Cliccà nant'à u ligame sottu vi ritruvà a vostra buttrega è tutti i dati chì appartene à ellu.",
     "action" => "Cunfirmà Shop Recovery",
],
     "SR-SeasonalSaving" => [
     "title" => "Quantu soldi hà risparmiatu Selldone per a vostra attività?",
     "sub-title" => "Da a data : principiu à : fine",
     "infrastructure" => [
     "title" => "Infrastruttura",
     "subtitle" => "Servitori, CDN, Storage, è altri servizii cloud",
],
     "experts" => [
     "title" => "Esperti è Staff",
     "subtitle" => "Sviluppatori, mantenimentu è supportu",
],
     "total_save" => "Soldi salvati totali",
],
     "SR-SeasonalPerformance" => [
     "title" => "A vostra prestazione",
     "sub-title" => "Panoramica di l'affari da :start to :end",
     "new_visitors" => "New Users",
     "returning_visitors" => "Utenti tornati",
     "shop_views" => "Shop Views",
     "baskets" => [
     "title" => "Carrelli di shopping",
     "subtitle" => "Segnala u numeru di novi carri di shopping",
],
     "products" => [
     "title" => "Panoramica di i prudutti",
     "subtitle" => "Status di i prudutti in a tenda per tipu",
     "value_name" => "I prudutti",
],
     "views" => [
     "title" => "Page Views",
     "subtitle" => "Totale viste di pagina di u situ web",
],
],
     "vendor-order" => [
     "title" => "New Order",
     "message" => "Avete ricevutu un novu ordine. Per piacè andate à a pagina di trattamentu di l'ordine in u vostru pannellu di venditore.",
     "subject" => "🛍 Novu Ordine Ricevutu | : id_ordine",
     "your_revenue" => "U vostru Revenue",
],
     "vendor-invite" => [
     "title" => "Invitu di u venditore",
     "message" => "Avete ricevutu un invitu à diventà venditore di :shop_name. Pudete accettà o ricusà clicchendu nantu à i seguenti buttoni.",
     "subject" => ":shop_name | Avete ricevutu un invitu à diventà u nostru venditore",
     "accept" => "Accetta è diventa un venditore",
     "reject" => "Rifiuta",
],
     "shop-email-login" => [
     "subject" => "U vostru codice di login per :shop",
     "header-message" => "Vi mandemu stu email perchè avete dumandatu un codice di login per a buttrega. Per piacè truvate a vostra Password One-Time (OTP) quì sottu:",
     "footer-message" => "Stu codice serà validu per 10 minuti. Se ùn avete micca dumandatu stu codice di login, ignurate stu email.",
],
     "shop-email-verify-link" => [
     "subject" => "Verificate u vostru email | : buttrega",
     "title" => "Verificazione di e-mail",
     "header-message" => "Salute : nome,<br> Per piacè cunfirmà chì **:email** hè u vostru indirizzu e-mail clicchendu nant'à u buttone o aduprate u ligame sottu in 48 ore.",
     "footer-message" => "",
],
     "vendor-products" => [
     "subject" => "Actualizazione di i prudutti: shop",
     "title" => "Actualizazione nantu à u Statu di u Produttu - Ultime 24 Ore",
     "message" => "Spergu chì stu missaghju vi trova bè. Questa hè una breve aghjurnazione per informàvi di u statutu di i vostri prudutti nantu à a nostra piattaforma in l'ultime 24 ore. Duranti stu periodu, ci sò stati cambiamenti in u statutu di certi prudutti. Questi cambiamenti pò esse dovutu à compra, aghjurnamenti di stock, o altri avvenimenti rilativi. Per infurmazione più dettagliata nantu à ogni pruduttu, accede à u vostru contu è verificate a sezione 'Status di u produttu'.",
     "action" => "Open Vendor Panel",
],
];