<?php 

 return [
     "profile" => "Leghjite l'infurmazioni di u prufilu cumprese u nome, l'indirizzu email, l'imaghjini è u statutu di autentificazione.",
     "phone" => "Accessu à u numeru di cuntattu",
     "address" => "Leghjite è edità l'indirizzu da u libru di indirizzu salvatu",
     "buy" => "Ordine & Shop Order.",
     "order-history" => "Leghjite a storia di l'ordine.",
     "my-gift-cards" => "Access to my cards.",
     "articles" => "Edita l'articuli.",
     "notifications" => "Mandate è riceve notificazioni.",
     "read-shops" => "Leghjite a lista di a tenda.",
     "shop-edit" => "Accessu di editazione di u magazinu.",
     "shop-contacts" => "Riceve è edità forme di cuntattu.",
     "shop-gift-cards" => "Creazione, editazione è gestione di carte.",
     "shop-faqs" => "Crea, edità è gestione e dumande frequenti.",
     "shop-categories" => "Crià, edità, è Gestisce Categorie.",
     "shop-products" => "Crià, edità è gestione di i prudutti.",
     "shop-read-reports" => "Leghjite l'infurmazioni è i rapporti.",
     "shop-socials" => "Edite e rete suciale di a tenda.",
     "shop-accounts" => "Edite è sguassate i cunti finanziari ligati à u magazinu.",
     "shop-menus" => "Edite i menu di u magazinu.",
     "shop-pages" => "Edite e pagine di u magazinu.",
     "shop-warehouse" => "Edita Store Warehouse",
     "shop-permissions" => "Vede è edità l'accessu à a tenda.",
     "shop-process-center" => "Gestisce ordini ricevuti.",
     "shop-profile" => "Gestisce i profili di a tenda.",
     "shop-discount-code" => "Gestisce i codici di sconto.",
     "shop-coupon" => "Gestisce i cuponi.",
     "shop-offer" => "Gestisce offerte.",
     "shop-lottery" => "Gestisce lotterie.",
     "shop-community" => "Gestisce a cumunità.",
];