<?php 

 return [
     "accepted" => ": Atribut kabul edilmeli.",
     "active_url" => ": Atribut dogry URL däl.",
     "after" => ": Atribut: seneden soň bir sene bolmaly.",
     "after_or_equal" => ": Atribut: seneden soň ýa-da deň bolan sene bolmaly.",
     "alpha" => ": Atributda diňe harplar bolup biler.",
     "alpha_dash" => ": Atributda diňe harplar, sanlar we çyzyklar bolup biler.",
     "alpha_num" => ": Atributda diňe harplar we sanlar bolup biler.",
     "array" => ": Atribut bir massiw bolmaly.",
     "before" => ": Atributdan öň bir sene bolmaly.",
     "before_or_equal" => ": Atribut seneden öň ýa-da oňa deň bolmaly.",
     "between" => [
     "numeric" => ": Atribut: min bilen: max arasynda bolmaly.",
     "file" => ": Atribut: min bilen: max kilobaýt arasynda bolmaly.",
     "string" => ": Atribut: min we: max nyşanlaryň arasynda bolmaly.",
     "array" => ": Atributyň arasynda: min we: max elementleriň arasynda bolmaly.",
],
     "boolean" => ": Atribut meýdany dogry ýa-da ýalan bolmaly.",
     "confirmed" => ": Atribut tassyklamasy gabat gelenok",
     "date" => ": Atribut dogry senä däl.",
     "date_format" => ": Atribut formata: formata gabat gelenok.",
     "different" => "The: atribut we: başga bolmaly.",
     "digits" => ": Atribut bolmaly: sanlar.",
     "digits_between" => ": Atribut: min bilen: iň köp san arasynda bolmaly.",
     "dimensions" => ": Atributyň şekil ölçegleri nädogry.",
     "distinct" => ": Atribut meýdanynyň iki gezek bahasy bar.",
     "email" => ": Atribut dogry e-poçta salgysy bolmaly.",
     "exists" => "Saýlanan: atribut nädogry.",
     "file" => ": Atribut faýl bolmaly.",
     "filled" => ": Atribut meýdanynyň bahasy bolmaly.",
     "gt" => [
     "numeric" => ": Atribut: bahadan uly bolmaly.",
     "file" => ": Atributdan uly bolmaly: kilobaýt bahasy.",
     "string" => ": Atribut: baha nyşanlaryndan uly bolmaly.",
     "array" => ": Atributda: baha elementlerinden köp bolmaly.",
],
     "gte" => [
     "numeric" => ": Atribut uly ýa-da deň bolmaly: baha.",
     "file" => ": Atribut uly ýa-da deň bolmaly: kilobaýt bahasy.",
     "string" => ": Atribut uly ýa-da deň bolmaly: baha nyşanlary.",
     "array" => ": Atributda: baha elementleri ýa-da has köp bolmaly.",
],
     "image" => ": Atribut şekil bolmaly.",
     "in" => "Saýlanan: atribut nädogry.",
     "in_array" => ": Atribut meýdançasy ýok: başga.",
     "integer" => ": Atribut bitewi san bolmaly.",
     "ip" => ": Atribut dogry IP adresi bolmaly.",
     "ipv4" => ": Atribut dogry IPv4 salgy bolmaly.",
     "ipv6" => ": Atribut dogry IPv6 salgy bolmaly.",
     "json" => ": Atribut dogry JSON setiri bolmaly.",
     "lt" => [
     "numeric" => ": Atribut: bahadan pes bolmaly.",
     "file" => ": Atributdan pes bolmaly: kilobaýt bahasy.",
     "string" => ": Atributdan pes bolmaly: baha nyşanlary.",
     "array" => ": Atributyň: baha elementlerinden az bolmalydyr.",
],
     "lte" => [
     "numeric" => ": Atribut az ýa-da deň bolmaly: baha.",
     "file" => ": Atribut az ýa-da deň bolmaly: kilobaýt bahasy.",
     "string" => ": Atribut az ýa-da deň bolmaly: baha nyşanlary.",
     "array" => ": Atributyň: baha elementlerinden köp bolmaly däldir.",
],
     "max" => [
     "numeric" => ": Atribut: max-dan uly bolup bilmez.",
     "file" => ": Sypaty: max kilobaýtdan uly bolup bilmez.",
     "string" => ": Atribut: uly nyşanlardan uly bolup bilmez.",
     "array" => ": Atributyň: iň köp elementden köp bolmagy mümkin.",
],
     "mimes" => ": Atribut görnüşi bir faýl bolmaly: bahalar.",
     "mimetypes" => ": Atribut görnüşi bir faýl bolmaly: bahalar.",
     "min" => [
     "numeric" => ": Atribut iň bolmanda bolmaly: min.",
     "file" => ": Atribut iň bolmanda bolmaly: min kilobaýt.",
     "string" => ": Atribut iň bolmanda: min nyşan bolmaly.",
     "array" => ": Atributyň iň bolmanda: min elementleri bolmaly.",
],
     "not_in" => "Saýlanan: atribut nädogry.",
     "not_regex" => ": Atribut formaty nädogry.",
     "numeric" => ": Atribut san bolmaly.",
     "present" => ": Atribut meýdany bolmaly.",
     "regex" => ": Atribut formaty nädogry.",
     "required" => ": Atribut meýdany talap edilýär.",
     "required_if" => ": Atribut meýdany talap edilýär: beýlekisi: baha.",
     "required_unless" => ": Atribut meýdany talap edilýär: beýlekisi: bahalar.",
     "required_with" => ": Atribut meýdany talap edilýär: bahalar bar bolsa.",
     "required_with_all" => ": Atribut meýdany talap edilýär: bahalar bar bolsa.",
     "required_without" => ": Atribut meýdany talap edilende talap edilýär: bahalar ýok.",
     "required_without_all" => "Hiç biri: bahalar ýok bolanda: atribut meýdany talap edilýär.",
     "same" => ": Atribut we: beýleki gabat gelmeli.",
     "size" => [
     "numeric" => ": Atribut: ululyk bolmaly.",
     "file" => ": Atribut: ölçeg kilobaýt bolmaly.",
     "string" => ": Atribut: ölçeg nyşanlary bolmaly.",
     "array" => ": Atributda: ululykdaky zatlar bolmaly.",
],
     "string" => ": Atribut setir bolmaly.",
     "timezone" => ": Atribut dogry zona bolmaly.",
     "unique" => ": Atribut eýýäm alyndy.",
     "uploaded" => ": Atribut ýükläp bilmedi.",
     "url" => ": Atribut formaty nädogry.",
     "custom" => [
     "attribute-name" => [
     "rule-name" => "adaty habar",
],
     "g-recaptcha-response" => [
     "required" => "Robot däldigiňizi barlaň.",
     "captcha" => "Captcha ýalňyşlygy! soň gaýtadan synanyşyň ýa-da sahypa administratoryna ýüz tutuň.",
],
],
     "attributes" => [
        
     ],
];