<?php 

 return [
     "home" => "продадено",
     "blogs" => "Блог",
     "helps" => "Помощ",
     "current_location" => "Този запис",
     "dashboard" => "Табло",
     "my_shops" => "Моите магазини",
     "wallet" => "Портфейл",
     "about" => "Относно Селдоун",
     "contact" => "Свържете се с нас",
     "comments" => "Отзиви",
     "likes" => "Харесвания",
     "power" => "Подкрепа",
     "build_free_shop" => "Изградете своя магазин безплатно",
     "shop_name" => "Име на магазина",
     "categories" => "Категории",
     "sub_articles" => "Още",
     "terms" => "Условия",
     "colour" => "цвят",
     "style" => "Стил",
     "volume" => "Обем",
     "weight" => "Тегло",
     "pack" => "пакет",
     "type" => "вид",
     "add_to_card" => "Добави в кошницата",
     "overview" => "Преглед",
     "reviews" => "Отзиви",
     "spec" => "Пълна спецификация",
     "you_may_also_like" => "Може да харесате още",
     "about_us" => "За нас",
     "contact_us" => "Свържете се с нас",
     "cookie_privacy" => "Политика на бисквитките",
     "follow_us" => "Последвай ни",
     "category" => "Категория",
     "author" => "Написано от ",
     "published_at" => "Публикувано в",
     "modified_at" => "Променен на",
     "price" => "цена",
     "discount" => "Отстъпка",
     "price_after_discount" => "Цена след отстъпка",
     "available" => "На разположение",
     "sold_out" => "Продадено",
     "buy" => "Купи сега",
     "login_shop" => "Магазин за вход",
     "posted_on" => "Публикувано на :date",
];