<?php 

 return [
     "email-types-description" => [
     "shop-customer-join" => "Acest mesaj salută un nou cumpărător în magazin.",
     "order-checkout" => "Această notificare este trimisă atunci când un cumpărător confirmă o comandă.",
     "order-payment" => "Această notificare confirmă plata cu succes efectuată de un client.",
     "order-payment-admin" => "Acest mesaj este trimis unui vânzător pentru a-l notifica despre o comandă confirmată.",
     "pos-checkout" => "Această notificare este trimisă pentru a confirma o comandă la punctul de vânzare pentru un cumpărător.",
     "pos-payment" => "Această notificare confirmă o plată la punctul de vânzare efectuată de un cumpărător.",
     "pos-payment-admin" => "Acest mesaj anunță vânzătorul cu privire la o achiziție efectuată la punctul său de vânzare.",
     "shop-contact" => "Această notificare este trimisă atunci când a fost trimis un formular de contact.",
     "shop-giftcard" => "Această notificare informează un utilizator că a primit un card cadou.",
     "shop-vendor-join" => "Acest mesaj salută un nou furnizor în magazin.",
     "shop-vendor-invite" => "Acest mesaj este trimis pentru a invita un furnizor să se alăture pieței dvs.",
     "shop-vendor-order" => "Acest mesaj este trimis vânzătorului atunci când o comandă este primită fie în stare plătită, fie în ramburs la livrare (COD).",
     "shop-vendor-products" => "Expediat zilnic pentru a actualiza furnizorii cu privire la starea produselor lor.",
     "shop-login" => "Notificați utilizatorul cu detaliile de conectare, inclusiv adresa IP, data și dispozitivul, din motive de securitate.",
     "login-code" => "Trimiteți un cod de parolă unic pentru ca utilizatorii să se conecteze la magazin.",
     "shop-email-verify-link" => "Trimiteți un link pentru a verifica adresa de e-mail a utilizatorului. Acest e-mail este trimis atunci când un utilizator se înregistrează prin SMS și îi introduce e-mailul și nu este trimis atunci când utilizatorul se înregistrează prin social sau prin e-mail direct.",
],
     "global" => [
     "greetings" => "Salut :nume",
     "end-statement" => "Echipa de suport",
     "receiver_name" => "Bună:nume_utilizator",
     "footer-help" => "Nevoie de ajutor? Întrebați la [support@selldone.com](mailto:support@selldone.com) sau vizitați [centrul de ajutor](https://selldone.com/help)",
     "footer-shop" => "Dacă aveți nevoie de ajutor cu ceva, vă rugăm să nu ezitați să ne trimiteți un e-mail: :shop_mail",
     "accept" => "Accept",
     "reject" => "Respinge",
     "verify" => "verifica",
     "title" => "Titlu",
     "value" => "Valoare",
     "description" => "Descriere",
     "Shop" => "Magazin",
     "user" => "utilizator",
     "license" => "Licență",
     "status" => "stare",
     "start" => "start",
     "end" => "Sfârşit",
     "renewal" => "Reînnoire",
     "view" => "Vedere",
     "balance" => "Echilibru",
     "card_number" => "Număr de card",
     "cvv" => "Cvv",
     "expire_date" => "Data de expirare",
     "dashboard" => "bord",
     "order" => "comanda",
     "view_order" => "Vezi comanda",
     "pay_now" => "Pay now",
     "official_selldone" => "VANZAT OFICIAL",
     "account-number" => "Account number",
     "account-name" => "Account name",
     "currency" => "Valută",
     "free-balance" => "Sold liber",
     "locked-balance" => "Echilibrul blocat",
     "bot" => "Bot",
     "requests" => "Cereri",
     "baskets" => "Cărucioare",
     "physical" => "Fizic",
     "virtual" => "Virtual",
     "file" => "Fişier",
     "service" => "Serviciu",
     "fulfillment" => "Împlinire",
     "open" => "Deschis",
     "reserved" => "Rezervat",
     "canceled" => "Anulat",
     "payed" => "Plătit",
     "cod" => "COD",
     "orders-count" => "Comenzi",
     "payments-count" => "Plăți",
     "confirms-count" => "Confirmă",
     "sends-count" => "Trimite",
     "delivers-count" => "Livrează",
     "count" => "Numara",
     "transactions-count" => "Tranzacțiile contează",
     "success-transactions" => "Tranzacții de succes",
     "total-amount" => "Valoare totală",
     "amount" => "Cantitate",
     "wage" => "Salariu",
     "debug" => "Depanați",
     "pos" => "POS",
     "live" => "Trăi",
     "CheckQueue" => "Verificați coada",
     "OrderConfirm" => "Confirmare comanda",
     "PreparingOrder" => "Pregatirea comenzii",
     "SentOrder" => "Comanda trimisă",
     "ToCustomer" => "Livrat clientului",
     "Pending" => "In asteptarea",
     "Accepted" => "Admis",
     "Rejected" => "Respins",
     "pc" => "PC",
     "tablet" => "Comprimat",
     "phone" => "Telefon",
     "total" => "Total",
     "view-detail" => "Vezi detalii",
     "empty" => "Gol",
     "dropshipping" => "Dropshipping",
     "reply" => "Răspuns",
     "reactions" => "Reacții",
     "comments" => "comentarii",
     "last-comment" => "Ultimul comentariu",
     "response-to" => "Raspuns catre",
     "posts" => "Postări",
     "post" => "Post",
     "name" => "Nume",
     "email" => "E-mail",
     "type" => "tip",
     "device" => "Dispozitiv",
     "platform" => "Platformă",
     "browser" => "Browser",
     "time" => "Timp",
     "wallet" => "portofel",
     "date" => "Data",
     "account" => "Cont",
     "transaction" => "Tranzacţie",
     "fee" => "Taxa",
     "location" => "Location",
     "ip" => "IP",
     "bill" => "Factură",
     "category" => "Categorie",
     "password" => "Parola",
     "shop" => "Magazin",
     "verify-login" => "Verificați și autentificați-vă",
     "url" => "URL",
     "avocado" => "Avocado",
     "hyper" => "Hiper",
     "buy-now" => "Cumpără acum",
     "add-domain" => "Add Domain",
     "views" => "Vizualizări",
     "country" => "Țară",
     "address" => "abordare",
     "postal" => "Cod poștal",
     "building_no" => "Clădirea #",
     "building_unit" => "Unitate #",
     "message" => "Mesaj",
     "customer" => "Client",
     "cart-items" => "Articole din coș",
     "payment" => "Plată",
     "receiver" => "Receptor",
     "virtual-items" => "Articole virtuale",
     "no-payment" => "Fara plata!",
     "enable" => "Permite",
     "access" => "Acces",
     "bank" => "Informații bancare",
     "vendor" => "Furnizor",
     "view_content" => "Vizualizați conținutul complet",
     "files" => "Fișiere",
     "download" => "Descarca",
     "file_name" => "Nume de fișier",
     "file_size" => "mărimea",
     "subscription" => "Abonament",
     "products" => "Produse",
     "vendor_products" => "Produse vânzători",
],
     "selldone-business-os" => "Selldone Business OS",
     "senders" => [
     "WeeklyReport" => [
     "id" => "performance",
     "name" => "Raport de performanță, Selldone",
],
     "SeasonalReport" => [
     "id" => "seasonal",
     "name" => "Raport sezonier, Selldone",
],
     "Onboarding" => [
     "id" => "Bună",
     "name" => "Aprobă, Selldone",
],
     "Support" => [
     "id" => "support",
     "name" => "Suport:nume",
],
     "EmailVerify" => [
     "id" => "verify",
     "name" => "Verificați, Selldone",
],
     "Welcome" => [
     "id" => "Bună",
     "name" => "Comunitate, Selldone",
],
     "NewShop" => [
     "id" => "negustori",
     "name" => "Aprobă, Selldone",
],
     "Approve" => [
     "id" => "aproba",
     "name" => "Aprobă, Selldone",
],
     "SellerReceiveOrder" => [
     "id" => "order",
     "name" => "Managementul comenzilor :nume",
],
     "Recovery" => [
     "id" => "recuperare",
     "name" => "Echipa de recuperare Selldone",
],
],
     "bill-status" => [
     "PENDING" => "În așteptare ⌛",
     "PAYED" => "Plătit ✅",
     "CANCELED" => "Anulat ❌",
],
     "shop-invite" => [
     "LEVEL-NAME" => [
     "ADMIN" => "Administrator",
     "OFFICER" => "Ofițer și supraveghetor",
     "AUDITING" => "Manager de audit",
     "EMPLOYEE" => "Angajat",
     "PRODUCT" => "Manager de produse",
     "CONTENT" => "Manager de continut",
     "MARKETING" => "manager de marketing",
     "VIEWER" => "Vizualizator",
],
     "subject" => ":inviter Te invită ca :level | :magazin",
     "category" => "Invitația personalului",
     "title" => "Ai fost invitat la <b>:shop_name</b> ca <b>:level</b> .",
     "message" => "V-a fost trimisă o invitație. Îl puteți confirma sau respinge. Dacă această invitație este aprobată de dvs., trebuie să intrați în serviciul Selldone pentru a o confirma. Confirmând această invitație, veți avea acces la secțiunea de gestionare a magazinului.",
],
     "welcome-email" => [
     "subject" => "👋 Bun venit :name, Câteva lucruri interesante doar pentru tine.",
     "category" => "CONGRATULATION",
     "title" => "Bine ați venit la SELLDONE",
     "message" => "Vă mulțumim pentru că ați ales Selldone. Acum faceți parte din comunitatea Selldone care conectează vânzătorii globali la clienți, Întreprindere locală la întreprindere, Individ cu corporație! Toate instrumentele master și pro au fost oferite **gratuit** și **nelimitat** pentru dvs. Încercați, deschidem ușile, Just Do It!",
     "seller" => [
     "title" => "Ești vânzător?",
     "message" => "Pentru a începe să vindeți, introduceți tabloul de bord în Selldone prin linkul de mai jos și creați primul magazin complet gratuit. Acest lucru va dura câteva minute și veți avea propriul magazin și site online. Vă vom ghida apoi către următorii pași și vom obține gateway-ul de plată.",
     "action" => "Conectați-vă la tabloul de bord",
],
     "buyer" => [
     "title" => "Sunt cumpărător",
     "message" => "Felicitări. Odată ce sunteți membru Selldone, veți scăpa de toate necazurile legate de calitatea de membru și de autentificare în magazinele online. Pentru a beneficia de orice magazin și site care utilizează platforma Selldone, vă puteți conecta cu un singur clic și vă puteți face achiziția simplă, rapidă și sigură.",
],
],
     "charge-account" => [
     "category" => "Portofel > Cont > Debitare",
     "title" => "Taxa de succes",
     "message" => "Contul dvs. <b>:account_number</b> a fost debitat cu succes <b>:amount</b> .",
     "account" => "Cont",
     "charge" => "Încărca",
     "balance" => "Echilibru",
     "footer" => "Faceți afacerile ușoare, realizabile și accesibile oricui din întreaga lume.",
],
     "verify-email" => [
     "subject" => "🙌 Completează-ți înscrierea la Selldone! Verificați linkul.",
     "category" => "ESTI LA UN PAS DEPARTE",
     "title" => "Verifică-ți adresa de email",
     "message" => "Salut :nume,<br> Vă mulțumim că ați ales Selldone.<br> Vă rugăm să confirmați că **:email** este adresa dvs. de e-mail făcând clic pe butonul sau folosiți linkul de mai jos în termen de 48 de ore.",
     "footer" => "Dacă întâmpinați probleme la a face clic pe butonul Verificați, copiați și inserați adresa URL de mai jos în browserul dvs. web: __:activation_url__",
],
     "verify-email-code" => [
     "subject" => "Cod de verificare pentru :nume",
     "category" => "SECURITY",
     "title" => "Codul de verificare a e-mailului",
     "message" => "Salut :nume,<br><br> Vă rugăm să confirmați că **:email** este adresa dvs. de e-mail prin acest cod în 10 minute.",
],
     "onboarding-verify-email" => [
     "subject" => "🎉 Magazinul tău este gata | :Nume",
     "category" => "ESTI LA UN PAS DEPARTE",
     "title" => "Configurare finalizată",
     "account_title" => "Contul tău",
     "account_msg" => "Verificați și conectați-vă la contul dvs. cu aceste informații.",
     "shop_msg" => "Informații despre cont pe sistemul de operare Selldone business.",
],
     "reset2fa" => [
     "category" => "MESAJ OFICIAL DE SECURITATE",
     "title" => "Solicitați dezactivarea autentificării în 2 pași",
     "message" => "Primiți acest e-mail deoarece am primit o solicitare de resetare a autentificării cu doi factori pentru contul dvs.<br><br> E-mail utilizator: <b>:email</b><br> Nume: <b>:nume</b>",
     "footer" => "Dacă nu ați solicitat resetarea parolei, nu este necesară nicio acțiune suplimentară.",
     "action" => "Dezactivați autentificarea în doi pași",
],
     "build-new-shop" => [
     "subject" => "🎊 Magazinul tău este gata acum!",
     "category" => "NĂScut NOU MAGAZIN ONLINE ÎN LUME",
     "title" => "Sărbătorind",
     "message" => "<b>Felicitări :name, ați creat o nouă afacere online;</b> Vă dorim succes în afacerea dvs. Bun venit în comunitatea Selldoners.<br> Încercați, deschidem ușile și ați reușit.",
     "pdf-book" => "Nu ratați manualul atașat: Faceți-vă afacerea ca un joc",
     "account" => [
     "title" => "Pasul 1: Creați un cont în portofelul Selldone",
     "message" => "Dacă nu aveți un cont în portofel, creați unul. Selldone deduce comisionul din acest cont. Puteți încărca acest cont, iar Selldone vă va percepe și o sumă de credit, astfel încât, dacă acest cont este negativ, site-ul și Magazinul dvs. vor continua să funcționeze.",
     "action" => "Conectați-vă la portofel",
],
     "shop-account" => [
     "title" => "Pasul 2: conectați contul la magazin",
     "message" => "Adăugați contul dvs. de portofel în magazinul dvs. Pentru a face acest lucru, intrați în Magazin > Contabilitate > Factură și conectați contul la magazin. Rețineți că toate plățile clienților dvs. sunt depuse direct în contul dvs. bancar și nicio sumă nu este retrasă sau dedusă de către Selldone, așa că trebuie să conectați acest cont al Selldone la magazin.",
     "action" => "Panoul de facturi din magazin",
],
     "gateway" => [
     "title" => "Pasul 3: Conectați Gateway-ul de plată online",
     "message" => "Accesați Magazin> Contabilitate> Port și apăsați <b>Adăugare port nou</b> . După selectarea monedei, vi se va afișa o listă de porturi portabile. Conectarea portului în Selldone este foarte simplă și rapidă, dar dacă aveți Niza pentru îndrumare, consultați secțiunea de ghid Selldone sau întrebați-ne.",
     "action" => "Adăugați un portal la magazin",
],
     "domain" => [
     "title" => "Ultimul pas: conectarea unui domeniu dedicat",
     "message" => "Veți putea avea magazinul dvs. pe câte domenii doriți. Pentru a conecta un domeniu dedicat la un magazin, trebuie să aveți cel puțin o licență de pornire. Prin prezentarea fiecărui prieten la Selldone, veți primi un card cadou de o lună de licență de pornire. Un procent din plățile prietenilor tăi vor fi, de asemenea, creditate în conturile clienților tăi.",
     "action" => "Introducerea și primirea de carduri cadou nelimitate",
],
],
     "basket-list" => [
     "item" => "articol",
     "count" => "Numara",
     "price" => "Preț",
     "discount-code" => "Cod de reducere",
     "customer-club" => "Clubul Clienților",
     "shipping" => "livrare",
     "total" => "Total",
     "offer" => "Oferi",
     "coupon" => "Cupon",
     "lottery" => "Adjudecare",
     "tax" => "Impozit",
     "tax_included" => "Inclus in pret",
     "tax_shipping" => "Shipping Tax",
],
     "buyable-payments" => [
     "method" => "Metodă",
     "amount" => "Cantitate",
     "giftcard" => "Gift card",
     "payment" => "Plată",
],
     "shop-subscription-email" => [
     "category" => "Actualizare abonament",
     "title" => "Licență de magazin: :shop_title",
     "title-reserved" => "Licență de rezervă: :shop_title",
     "title-active" => "Licență activă: :shop_title",
     "title-finished" => "Licență terminată: :shop_title",
     "title-cancel" => "Anulați licența: :shop_title",
     "message" => "Planul dvs. de licență pentru magazin a fost actualizat,",
     "RESERVED" => "⚡ Planul tău de abonament a fost **rezervat**.",
     "ACTIVE" => "🟢 Planul tău de abonament a fost **activat**.",
     "FINISHED" => "🚧 Planul tău de abonament a fost **terminat**.",
     "CANCEL" => "⛔ Planul tău de abonament a fost **anulat**.",
],
     "support" => [
     "subject" => "Centru de suport | :nume a raspuns",
     "category" => "Centru de asistență",
     "title" => "Ai primit un răspuns",
     "action" => "Deschideți administratorul magazinului",
],
     "shop-customer-join" => [
     "subject" => "Alăturați-vă :shop_title",
     "category" => "Sărbătoarea noilor clienți",
     "title" => "Ne bucurăm pentru calitatea ta de membru",
     "action" => "Vizitează acum",
],
     "shop-vendor-join" => [
     "subject" => "Incorporarea furnizorului | :shop_title",
     "category" => "Sărbătoarea noului furnizor",
     "title" => "Ne bucurăm pentru calitatea ta de membru",
     "action" => "Vendor Panel",
],
     "shop-giftcard" => [
     "subject" => "Card cadou :shop_title",
     "category" => "Adăugați un card nou",
     "title" => "Felicitări, ați primit un card cadou",
     "action" => "Cumpără acum",
     "message" => "Ați primit un card cadou în valoare de :balance :currency. Veți putea cumpăra din magazinul nostru cu acest card cadou.",
],
     "contact" => [
     "subject" => "Centru de suport | :magazin",
     "category" => "sprijin",
     "title" => "Ai primit un răspuns",
],
     "order-checkout" => [
     "subject" => "🛍 Comandă Checkout | :Comanda ID",
     "title" => "comanda",
     "message" => "Confirmați comanda dvs.,<br> Avem comanda ta. Vă vom trimite un alt e-mail când comanda dvs. este expediată.",
     "payments" => "Plăți",
],
     "order-payment" => [
     "subject" => "🛍 Confirmare plată | :Comanda ID",
     "title" => "Ordin de plata",
     "message" => "Plata dvs. a fost finalizată,<br> Avem comanda ta. Vă vom trimite un alt e-mail când comanda dvs. este expediată.",
     "payments" => "Plăți",
],
     "get-voucher" => [
     "subject" => "Felicitări :nume | Voucher nou: :title",
     "category" => "FELICITĂRI, VOUCHER NOU",
     "message" => "Primești un nou voucher, acesta este un cadou de la noi pentru tine. Puteți obține mai mult din aceste vouchere prezentând Selldone prietenilor și tuturor celor pe care îi cunoașteți. Acest voucher valorează **:preț :valută**.<br> Încercați, deschidem ușile, Felicitări, Deblocați funcții prin voucher!",
     "action" => "Panoul meu de control",
],
     "received-gift" => [
     "subject" => "Felicitări, dragă :name | Ai primit un cadou",
     "category" => "Anunțul de primire a unui cadou",
     "title" => "Cadouri pentru tine",
     "message" => "Ai primit un nou cadou. Acesta este un cadou de la Selldone. Puteți primi mai multe dintre aceste cadouri fiind mai activ în Selldone și dezvoltându-vă magazinul și ridicându-vă nivelul de specializare. Această valoare cadou este **:price :currency** pe care o puteți depune direct în portofel în selldone.<br><br> Folosiți acest cadou pentru a vă actualiza licența de magazin și pentru a folosi mai multe instrumente în afacerea dvs. online.",
     "action" => "Cadouri",
],
     "order-payment-admin" => [
     "subject" => "🛍 Comandă nouă primită | :Comanda ID",
     "title" => "New Order",
     "message" => "Ați primit o nouă comandă. Vă rugăm să accesați pagina de procesare a comenzii din magazinul dvs.",
],
     "virtual-item" => [
     "input-form-title" => "Informațiile dvs. completate",
     "output-form-title" => "Informații despre articolul achiziționat",
],
     "selldone-weekly-report" => [
     "subject" => "📬 :shop_title | Raport săptămânal: oră",
     "title" => "Raport săptămânal de performanță a magazinului",
     "message" => "Acesta este raportul săptămânal al magazinului dvs. de la :start la :end. Acest raport include sfaturi pentru îmbunătățirea afacerii dvs., puteți verifica, de asemenea, starea magazinului dvs. online și comenzile recente. Sper să aveți o zi și o săptămână bună înainte.",
],
     "shop-seasonal-report" => [
     "subject" => "☘ Raportul dvs. privind economisirea sumei în ultimele trei luni | :shop_title",
     "title" => "Raport sezonier despre activitatea dvs. de afaceri, recompense și economii financiare",
     "message" => "Acesta este raportul dvs. sezonier :shop_title de la :start la :end.",
],
     "EC-ShopAccounts" => [
     "title" => "Conturi conectate",
     "sub-title" => "Care este cea mai recentă stare a conturilor portofel conectate la magazinul meu?",
     "view-wallet" => "Vizualizați portofelul",
     "tip-title" => "Sfaturi importante",
     "tip" => "În pasul următor, creați un cont gratuit în portofelul dvs. Selldone și conectați-l la acest magazin. Chiar dacă soldul contului tău Selldone este negativ, clienții tăi pot face în continuare achiziții și plăți pentru magazinul tău fără probleme. Datele și serviciile dumneavoastră nu vor fi întrerupte sau restricționate timp de cel puțin 1 lună.",
     "view-my-wallet" => "My wallet",
     "connect-account" => "Conectați-vă la cont",
],
     "EC-ShopApps" => [
     "title" => "Aplicații instalate",
     "sub-title" => "Lista de aplicații pe care le-ați instalat în magazin săptămâna aceasta.",
     "tip" => "Doriți să găsiți mai multe aplicații pentru magazinul dvs.?",
     "view-app-store" => "Vizitați Magazinul de aplicații Selldone..",
],
     "EC-ShopBots" => [
     "title" => "Boții dvs. de magazin",
     "sub-title" => "Boți de vânzări activi în magazinul meu.",
     "tip-title" => "Vânzare de bot",
     "tip" => "Selldone v-a furnizat roboți de vânzări automate. Tot ce trebuie să faceți este să accesați panoul Add-ons> Bots și să vă activați roboții din magazin. Rețineți că serviciul relevant trebuie să fie disponibil în țara dvs.",
     "view-bots" => "Gestionați roboții",
],
     "EC-ShopContacts" => [
     "title" => "Comunicarea cu Clienții",
     "sub-title" => "Câte contacte am avut cu clienții mei în această săptămână?",
     "faqs" => "întrebări frecvente",
     "tickets" => "Bilete pentru clienți",
],
     "EC-ShopData" => [
     "title" => "Statutul utilizatorilor",
     "sub-title" => "De la data :start to :end",
     "users" => [
     "title" => "Clienți",
     "subtitle" => "Înscrieți-vă utilizatori",
],
     "views" => [
     "title" => "Vizite",
     "subtitle" => "De câte ori ai vizitat magazinul",
],
     "new_visitors" => "New Users",
     "returning_visitors" => "Utilizatori returnați",
     "shop_views" => "Vizualizări ale magazinului",
     "baskets" => [
     "title" => "Coșurile de cumpărături",
     "subtitle" => "Raportați numărul de coșuri de cumpărături noi",
],
     "products" => [
     "title" => "Prezentare generală a produselor",
     "subtitle" => "Starea produselor din magazin după tip",
     "value_name" => "Produse",
],
     "products_count" => "Tipuri de produse",
     "views_count" => "Număr de vizualizări",
     "sell_count" => "Număr de vânzări",
     "send_count" => "Număr de expedieri",
],
     "EC-ShopDropShipping" => [
     "title" => "Drop Shipping",
     "sub-title" => "Panou pentru principalii vânzători de Drop Shipping Selldone.",
     "total_fulfillments" => "Total comenzi primite",
     "ds_count" => "Comenzi primite",
     "statistics_title" => "Raportați comenzile primite",
     "ds_cancels" => "Anulați de către vânzătorul de interfață",
     "ds_rejects" => "Anulați de către dvs",
     "tip" => "Sunteți un vânzător important de mărfuri? Dețineți un depozit, fabrică sau distribuitor de produse? Puteți oferi produsele dumneavoastră altor vânzători în serviciul Selldone Drop Shipping pentru a vă vinde produsul pe scară largă. Trimiteți-ne un e-mail la support@selldone.com pentru a vă ghida.",
     "view-drop-shipping-panel" => "Conectați-vă la panoul cu ridicata",
],
     "EC-ShopExchangeRates" => [
     "title" => "Rate de schimb",
     "sub-title" => "Lista celor mai recente rate de conversie valutară din magazinul dvs.",
     "from" => "Moneda sursă",
     "to" => "Moneda de destinație",
     "rate" => "Rata de conversie",
     "vew-exchange-panel" => "panoul de gestionare a cursului de schimb",
],
     "EC-ShopExperts" => [
     "title" => "Contracte de expertiză",
     "sub-title" => "Ce profesioniști lucrează la magazinul meu?",
     "cost" => "Valoarea contractului",
     "duration" => "Durată",
     "start_at" => "Start Date",
     "complete_at" => "Completion Date",
     "cancel_at" => "Data Anulare",
     "end_at" => "Data de livrare",
     "tip" => "Puteți angaja cei mai buni specialiști din Selldone pentru a vă dezvolta afacerea.",
     "view-experts" => "Faceți clic pentru a începe.",
],
     "EC-ShopGateways" => [
     "title" => "Payment gateways",
     "sub-title" => "Raportați gateway-uri de plată active pe magazin :shop.",
     "tip-title" => "Sfaturi importante",
     "tip" => "Accesați pagina de gestionare a portalului din magazinul dvs. și adăugați cel puțin un port în câteva minute. Clienților tăi le place să plătească rapid și în siguranță prin portaluri online.",
     "view-shop-gateways" => "Conectați-vă la gestionarea portalului magazinului meu.",
     "view-gateways" => "Vedeți mai multe gateway-uri",
],
     "EC-ShopOrders" => [
     "title" => "Comenzi",
     "sub-title" => "Lista comenzilor primite saptamana aceasta.",
     "total_baskets" => "Total comenzi",
     "total_posBaskets" => "Total comenzi în numerar",
     "pos-title" => "Cutia de magazin POS",
     "chart-label" => "Comenzi finalizate (aceste comenzi nu sunt neapărat plătite!)",
     "tip-title" => "Ar trebui să încerci mai mult...",
     "tip" => "Nici un simplu succes.",
],
     "EC-ShopProcessCenter" => [
     "title" => "Centru de procesare",
     "sub-title" => "Câtă comandă am procesat în magazin săptămâna aceasta?",
     "tip-title" => "Nu ai avut vânzare!",
     "tip" => "Din păcate, nu ați avut vânzări în această săptămână. Trebuie să ajungeți mai mult la magazinul dvs. Puteți adăuga mai multe produse, puteți alege imagini mai bune sau puteți scrie descrieri mai bune pentru produsele dvs. Luați în considerare un loc de muncă cu normă întreagă pentru afacerea dvs. Dacă o faci corect și nu te simți frustrat, vei reuși.",
     "view-process-center" => "Vedeți centrul de proces",
     "return" => [
     "title" => "Comanda returnata",
     "subtitle" => "Raportați comenzile returnate.",
     "tip-title" => "Stiai asta ...",
     "tip" => "Puteți crea câte case de marcat de magazin doriți prin Selldone POS! De fapt, îți poți transforma tableta, telefonul mobil sau laptopul în căsuța de e-mail. Dacă asta te entuziasmează, Selldone POS este ceva pe care ar trebui să începi să-l folosești acum. Este nevoie doar de un simplu clic pentru a lansa, avem totul pregătit pentru serverul tău în avans.",
     "view-pos" => "Conectați-vă la Casiera magazinului meu online",
],
],
     "EC-ShopSessions" => [
     "title" => "Sesiuni",
     "sub-title" => "De câte ori mi-am vizitat magazinul?",
     "countries-title" => "Care țări au fost cele mai vizitate?",
],
     "EC-PublicMessage" => [
     "title" => "Vrei să faci bani fără a cheltui un dolar?",
     "message" => "Dragă :name, poți accesa Tabloul de bord > Demonetizare și poți crea un link de recomandare. Trimite link-ul prietenilor tăi, primești un card cadou Selldone și un procent din plățile prietenului tău. Rețineți că cardul cadou va fi trimis atât dvs., cât și prietenului dvs.",
     "action" => "Vezi linkul meu de prezentare",
     "mail-clip" => "<b style='color: #C2185B'>Important:</b> dacă utilizați servicii de e-mail, cum ar fi Gmail, care limitează lungimea e-mailului, găsiți următoarea opțiune la sfârșitul e-mailului pentru a afișa raportul complet și faceți clic pe el:",
     "no-coin-reward" => "<b style='color: #C2185B'>Ne pare rău:</b> Activitatea dvs. nu a îndeplinit cerințele pentru a obține recompensă SEL Coins gratuită. Încercați mai mult și vindeți mai mult în magazinul dvs. pentru sezonul următor.",
     "yes-coin-reward" => "<b style='color: #4CAF50'>Recompensă:</b> Felicitări, datorită performanței tale fantastice, ți-am oferit o recompensă gratuită de :amount SEL Coin.",
     "need-buy-license" => "<b>Creșteți-vă afacerea:</b> nu ați înregistrat niciun plan de abonament pentru site-ul web al companiei dvs.! Așa că este momentul să cumperi cel puțin un abonament. Doar costă: suma lunară pentru achiziția anuală.",
     "not-afford-message" => "Dacă nu vă permiteți sau aveți probleme cu plata, nu ezitați să ne spuneți prin support@selldone.com.",
     "add-domain" => "<b>De ce să nu ai un domeniu personalizat pentru afacerea ta?</b><br> Adăugați un domeniu pe site-ul dvs. acum; este gratis!",
],
     "Widget-Socials" => [
     "title" => "Selldone este un<del> produs</del> <span style = 'color: forestgreen'>comunitate</span> .<br> Fii un vânzător profesionist!",
     "message" => "Urmărește paginile oficiale ale Selldone pe Twitter, LinkedIn și rețelele sociale. Trimiteți-ne orice comentarii, solicitări sau critici sau participați la discuții despre Selldone. De asemenea, facem parte din comunitatea Selldone pe care <b>o creați</b> .",
],
     "avocado-seller-daily-report" => [
     "subject" => "Am primit comenzi noi de avocado | :shop_title :time",
     "title" => "Raport de performanță pentru ultimele 24 de ore",
     "message" => "Clienții dvs. așteaptă ca comenzile dvs. să fie revizuite și stabilite prețul. Răspundeți la solicitările clienților dvs. cât mai curând posibil pentru a obține mai multe vânzări.",
     "card_title" => "Comenzi în coadă",
     "card_subtitle" => "Din data",
     "card_payed" => "Comenzi plătite",
],
     "community-comments" => [
     "subject" => "Răspundeți la postarea dvs. din :community_title",
     "title" => ":name și :count alții au comentat postările tale.",
     "title-simple" => ":name a comentat postările tale.",
],
     "community-topic" => [
     "subject" => "🔔 Răspunde la subiectul tău :topic_title",
     "title" => ":name și :count alții au răspuns la subiectul tău.",
     "title-simple" => ":name a răspuns la subiectul tău.",
],
     "user-login" => [
     "subject" => "🔔 Autentificare nouă:nume",
     "category" => "Notificări de securitate",
     "title" => "Conectați-vă la Cont",
     "message" => "Dragă :name, v-ați conectat la contul dvs. Selldone.",
     "message-shop" => "Dragă :name, ați fost conectat la :shop_title .",
     "footer" => "Dacă nu sunteți autentificat, vă rugăm să vă schimbați parola.",
],
     "account-transaction" => [
     "withdraw" => "Retragere",
     "deposit" => "Depozit",
     "withdraw_subject" => "retrage din cont :account",
     "deposit_subject" => "Depunere în cont :cont",
     "message" => "Transferul de bani s-a făcut cu următoarele specificații.",
     "type" => "Tipul tranzacției",
     "from" => "Cont sursă",
     "to" => "Destination account",
     "desc" => "Descrierea tranzacției",
     "action" => "Vedeți tranzacția",
],
     "penalty" => [
     "subject" => "⛔ Important! Încălcarea regulilor | :magazin",
     "category" => "Informare critică",
     "title" => "Magazinul dvs. a fost penalizat",
     "action" => "Deschideți tabloul de bord al magazinului",
],
     "invite" => [
     "subject" => ":inviter v-a invitat la Selldone",
     "title" => ":name v-a trimis :sumă pentru a vă ajuta să vă lansați noul site web online și să-l monetizați!",
     "message" => "Pe Selldone, puteți să vă creați comerțul electronic, site-ul de blogging și comunitatea online și chiar să obțineți un POS online și să configurați vânzări personale în câteva minute. Este un sistem de operare pentru afaceri online pentru a vă face afacerea online, mai bună și mai rapidă. Înscrieți-vă până la <b>:date</b> pentru a obține un voucher de :amount.",
     "accept" => "Accepta invitatia",
     "owner" => "Proprietar al",
     "join-date" => "Pe Selldone de atunci",
],
     "shop-recovery" => [
     "subject" => "Link de recuperare | :magazin",
     "category" => "Securitatea magazinului",
     "title" => "Link de recuperare a stocării pentru <b>:shop_name</b> .",
     "message" => "Acest e-mail v-a fost trimis deoarece ați solicitat să vă restabiliți magazinul. Făcând clic pe linkul de mai jos, veți recupera magazinul dvs. și toate datele care îi aparțin.",
     "action" => "Confirmați recuperarea magazinului",
],
     "SR-SeasonalSaving" => [
     "title" => "Câți bani a economisit Selldone pentru afacerea ta?",
     "sub-title" => "De la data :start to :end",
     "infrastructure" => [
     "title" => "Infrastructură",
     "subtitle" => "Servere, CDN, stocare și alte servicii cloud",
],
     "experts" => [
     "title" => "Experți și personal",
     "subtitle" => "Dezvoltatori, întreținere și asistență",
],
     "total_save" => "Bani economisiți în total",
],
     "SR-SeasonalPerformance" => [
     "title" => "Performanța ta",
     "sub-title" => "Prezentare generală a afacerii de la :start to :end",
     "new_visitors" => "New Users",
     "returning_visitors" => "Utilizatori returnați",
     "shop_views" => "Vizualizări ale magazinului",
     "baskets" => [
     "title" => "Coșurile de cumpărături",
     "subtitle" => "Raportați numărul de coșuri de cumpărături noi",
],
     "products" => [
     "title" => "Prezentare generală a produselor",
     "subtitle" => "Starea produselor din magazin după tip",
     "value_name" => "Produse",
],
     "views" => [
     "title" => "Page Views",
     "subtitle" => "Numărul total de vizualizări ale paginilor site-ului web",
],
],
     "vendor-order" => [
     "title" => "New Order",
     "message" => "Ați primit o nouă comandă. Vă rugăm să accesați pagina de procesare a comenzii din panoul furnizorului dvs.",
     "subject" => "🛍 Comandă nouă primită | :Comanda ID",
     "your_revenue" => "Venitul dvs",
],
     "vendor-invite" => [
     "title" => "Invitația vânzătorului",
     "message" => "Ați primit o invitație pentru a deveni furnizor de :shop_name. O puteți accepta sau respinge făcând clic pe următoarele butoane.",
     "subject" => ":nume_magazin | Ați primit o invitație pentru a deveni furnizorul nostru",
     "accept" => "Acceptați și deveniți un furnizor",
     "reject" => "Respinge",
],
     "shop-email-login" => [
     "subject" => "Codul dvs. de conectare pentru :shop",
     "header-message" => "Vă trimitem acest e-mail deoarece ați solicitat un cod de conectare pentru magazin. Vă rugăm să găsiți mai jos parola dvs. unică (OTP):",
     "footer-message" => "Acest cod va fi valabil timp de 10 minute. Dacă nu ați solicitat acest cod de conectare, vă rugăm să ignorați acest e-mail.",
],
     "shop-email-verify-link" => [
     "subject" => "Verificați-vă adresa de e-mail | :magazin",
     "title" => "Verificare e-mail",
     "header-message" => "Salut :nume,<br> Vă rugăm să confirmați că **:email** este adresa dvs. de e-mail făcând clic pe butonul sau folosiți linkul de mai jos în termen de 48 de ore.",
     "footer-message" => "",
],
     "vendor-products" => [
     "subject" => "Actualizare produse: magazin",
     "title" => "Actualizare privind starea produsului - ultimele 24 de ore",
     "message" => "Sper că acest mesaj te va găsi bine. Aceasta este o scurtă actualizare pentru a vă informa despre starea produselor dvs. pe platforma noastră în ultimele 24 de ore. În această perioadă s-au produs schimbări în statutul unor produse. Aceste modificări se pot datora achizițiilor, actualizărilor de stoc sau altor evenimente conexe. Pentru informații mai detaliate despre fiecare produs, vă rugăm să vă conectați la contul dvs. și să verificați secțiunea „Starea produsului”.",
     "action" => "Deschideți Panoul furnizorului",
],
];