<?php 

 return [
     "profile" => "Citiți informațiile de profil, inclusiv numele, adresa de e-mail, imaginea și starea de autentificare.",
     "phone" => "Acces la numărul de contact",
     "address" => "Citiți și editați adresa din agenda salvată",
     "buy" => "Comandă și comandă la magazin.",
     "order-history" => "Citiți istoricul comenzilor.",
     "my-gift-cards" => "Access to my cards.",
     "articles" => "Editați articole.",
     "notifications" => "Trimiteți și primiți notificări.",
     "read-shops" => "Citiți Lista magazinului.",
     "shop-edit" => "Acces de editare în magazin.",
     "shop-contacts" => "Primiți și editați formulare de contact.",
     "shop-gift-cards" => "Crearea, editarea și gestionarea cardurilor.",
     "shop-faqs" => "Creați, editați și gestionați întrebările frecvente.",
     "shop-categories" => "Crearea, editarea și gestionarea categoriilor.",
     "shop-products" => "Crearea, editarea și gestionarea produselor.",
     "shop-read-reports" => "Citiți informații și rapoarte.",
     "shop-socials" => "Editați rețelele sociale ale magazinului.",
     "shop-accounts" => "Editați și ștergeți conturile financiare legate de magazine.",
     "shop-menus" => "Editați meniurile magazinului.",
     "shop-pages" => "Editați paginile magazinului.",
     "shop-warehouse" => "Editați depozitul magazinului",
     "shop-permissions" => "Vizualizați și editați accesul la magazin.",
     "shop-process-center" => "Gestionați comenzile primite.",
     "shop-profile" => "Gestionați profilurile magazinului.",
     "shop-discount-code" => "Gestionați codurile de reducere.",
     "shop-coupon" => "Gestionați cupoanele.",
     "shop-offer" => "Gestionați ofertele.",
     "shop-lottery" => "Gestionați loteriile.",
     "shop-community" => "Gestionează comunitatea.",
];