<?php 

 return [
     "profile" => "Lasiet profila informāciju, tostarp vārdu, e-pasta adresi, attēlu un autentifikācijas statusu.",
     "phone" => "Piekļuve kontaktpersonas numuram",
     "address" => "Lasīt un rediģēt adresi no saglabātās adrešu grāmatas",
     "buy" => "Pasūtījums un pasūtījums veikalā.",
     "order-history" => "Lasīt pasūtījumu vēsturi.",
     "my-gift-cards" => "Access to my cards.",
     "articles" => "Rediģēt rakstus.",
     "notifications" => "Sūtīt un saņemt paziņojumus.",
     "read-shops" => "Izlasiet veikalu sarakstu.",
     "shop-edit" => "Veikala rediģēšanas piekļuve.",
     "shop-contacts" => "Saņemt un rediģēt kontaktu veidlapas.",
     "shop-gift-cards" => "Karšu izveide, rediģēšana un pārvaldība.",
     "shop-faqs" => "Izveidojiet, rediģējiet un pārvaldiet bieži uzdotos jautājumus.",
     "shop-categories" => "Kategoriju izveide, rediģēšana un pārvaldība.",
     "shop-products" => "Produktu izveide, rediģēšana un pārvaldība.",
     "shop-read-reports" => "Lasīt informāciju un atskaites.",
     "shop-socials" => "Rediģēt veikala sociālos tīklus.",
     "shop-accounts" => "Rediģējiet un dzēsiet ar veikalu saistītos finanšu kontus.",
     "shop-menus" => "Rediģēt veikala izvēlnes.",
     "shop-pages" => "Rediģēt veikala lapas.",
     "shop-warehouse" => "Rediģēt veikala noliktavu",
     "shop-permissions" => "Skatiet un rediģējiet piekļuvi veikalam.",
     "shop-process-center" => "Pārvaldiet saņemtos pasūtījumus.",
     "shop-profile" => "Pārvaldīt veikalu profilus.",
     "shop-discount-code" => "Pārvaldiet atlaižu kodus.",
     "shop-coupon" => "Pārvaldīt kuponus.",
     "shop-offer" => "Pārvaldiet piedāvājumus.",
     "shop-lottery" => "Pārvaldīt loterijas.",
     "shop-community" => "Pārvaldīt kopienu.",
];