<?php 

 return [
     "accepted" => ":attribute ir jāpieņem.",
     "accepted_if" => "Lauks :attribute ir jāpieņem, ja :other ir :value.",
     "active_url" => ":attribute nav derīgs URL.",
     "after" => "Atribūtam :attribute ir jābūt datumam pēc :date.",
     "after_or_equal" => "Atribūtam :attribute ir jābūt datumam pēc :date vai vienādam ar to.",
     "alpha" => "Atribūtā :attribute var būt tikai burti.",
     "alpha_dash" => "Atribūts : var saturēt tikai burtus, ciparus un domuzīmes.",
     "alpha_num" => "Atribūts : var saturēt tikai burtus un ciparus.",
     "array" => "Atribūtam :attribute ir jābūt masīvam.",
     "ascii" => "Laukā :attribute drīkst būt tikai viena baita burtciparu rakstzīmes un simboli.",
     "before" => "Atribūtam :attribute ir jābūt datumam pirms :date.",
     "before_or_equal" => "Atribūtam :attribute ir jābūt datumam pirms :date vai vienādam ar to.",
     "between" => [
     "array" => "Atribūtam :attribute jābūt no :min līdz :max vienumiem.",
     "file" => ":attribute ir jābūt no :min un :max kilobaitiem.",
     "numeric" => "Atribūtam :attribute ir jābūt no :min līdz :max.",
     "string" => ":attribute ir jābūt starp :min un :max rakstzīmēm.",
],
     "boolean" => "Laukam :attribute ir jābūt patiesam vai nepatiesam.",
     "can" => "Laukā :attribute ir neatļauta vērtība.",
     "confirmed" => ":attribute apstiprinājums neatbilst.",
     "contains" => "Laukā :attribute trūkst obligātās vērtības.",
     "current_password" => "Parole ir nepareiza.",
     "date" => ":attribute nav derīgs datums.",
     "date_equals" => "Laukam :attribute ir jābūt datumam, kas vienāds ar :date.",
     "date_format" => "Atribūts :attribute neatbilst formātam :format.",
     "decimal" => "Laukā :attribute jābūt :decimal decimālzīmēm.",
     "declined" => "Lauks :attribute ir jānoraida.",
     "declined_if" => "Lauks :attribute ir jānoraida, ja :other ir :value.",
     "different" => ":attribute un :other ir jāatšķiras.",
     "digits" => "Atribūtam :attribute jābūt :digits cipariem.",
     "digits_between" => "Atribūtam :attribute ir jābūt no :min līdz :max cipariem.",
     "dimensions" => "Atribūtam :attribute ir nederīgi attēla izmēri.",
     "distinct" => "Laukam :attribute ir dublēta vērtība.",
     "doesnt_end_with" => "Lauks :attribute nedrīkst beigties ar vienu no šiem: :values.",
     "doesnt_start_with" => "Lauks :attribute nedrīkst sākties ar vienu no šiem: :values.",
     "email" => "Atribūtam :attribute ir jābūt derīgai e-pasta adresei.",
     "ends_with" => "Laukam :attribute jābeidzas ar vienu no šiem: :values.",
     "enum" => "Atlasītais :attribute nav derīgs.",
     "exists" => "Atlasītais :attribute nav derīgs.",
     "extensions" => "Laukam :attribute ir jābūt vienam no šiem paplašinājumiem: :values.",
     "file" => "Atribūtam :attribute ir jābūt failam.",
     "filled" => "Laukam :attribute ir jābūt vērtībai.",
     "gt" => [
     "array" => "Atribūtam :attribute ir jābūt vairāk nekā :value vienumiem.",
     "file" => ":attribute ir jābūt lielākam par :value kilobaitiem.",
     "numeric" => "Atribūtam :attribute ir jābūt lielākam par :value.",
     "string" => ":attribute ir jābūt lielākam par :value rakstzīmēm.",
],
     "gte" => [
     "array" => "Atribūtam :attribute ir jābūt :value vienumiem vai vairāk.",
     "file" => "Atribūtam :attribute ir jābūt lielākam vai vienādam ar :value kilobaiti.",
     "numeric" => "Atribūtam :attribute ir jābūt lielākam vai vienādam ar :value.",
     "string" => ":attribute ir jābūt lielākam vai vienādam ar :value rakstzīmēm.",
],
     "hex_color" => "Laukam :attribute ir jābūt derīgai heksadecimālajai krāsai.",
     "image" => "Atribūtam :attribute ir jābūt attēlam.",
     "in" => "Atlasītais :attribute nav derīgs.",
     "in_array" => "Lauks :attribute neeksistē :other.",
     "integer" => ":attribute ir jābūt veselam skaitlim.",
     "ip" => "Atribūtam :attribute ir jābūt derīgai IP adresei.",
     "ipv4" => "Atribūtam :attribute ir jābūt derīgai IPv4 adresei.",
     "ipv6" => "Atribūtam :attribute ir jābūt derīgai IPv6 adresei.",
     "json" => "Atribūtam :attribute ir jābūt derīgai JSON virknei.",
     "list" => "Laukam :attribute ir jābūt sarakstam.",
     "lowercase" => "Laukam :attribute jābūt ar mazajiem burtiem.",
     "lt" => [
     "array" => "Atribūtam :attribute jābūt mazākam par :value vienumiem.",
     "file" => ":attribute ir jābūt mazākam par :value kilobaitiem.",
     "numeric" => "Atribūtam :attribute ir jābūt mazākam par :value.",
     "string" => "Atribūtam :attribute ir jābūt mazākam par :value rakstzīmēm.",
],
     "lte" => [
     "array" => "Atribūtā :attribute nedrīkst būt vairāk par :value vienumiem.",
     "file" => "Atribūtam :attribute ir jābūt mazākam vai vienādam ar :value kilobaitiem.",
     "numeric" => "Atribūtam :attribute ir jābūt mazākam vai vienādam ar :value.",
     "string" => ":attribute ir jābūt mazākam vai vienādam ar :value rakstzīmēm.",
],
     "mac_address" => "Laukam :attribute ir jābūt derīgai MAC adresei.",
     "max" => [
     "array" => "Atribūtā :attribute nedrīkst būt vairāk par :max vienumiem.",
     "file" => ":attribute nedrīkst būt lielāks par :max kilobaiti.",
     "numeric" => "Atribūts :attribute nedrīkst būt lielāks par :max.",
     "string" => ":attribute nedrīkst būt lielāks par :max rakstzīmēm.",
],
     "max_digits" => "Laukā :attribute nedrīkst būt vairāk par :max cipariem.",
     "mimes" => "Atribūtam :attribute ir jābūt šāda veida failam: :values.",
     "mimetypes" => "Atribūtam :attribute ir jābūt šāda veida failam: :values.",
     "min" => [
     "array" => "Atribūtā :attribute ir jābūt vismaz :min vienumiem.",
     "file" => "Atribūtam :attribute ir jābūt vismaz :min kilobaitiem.",
     "numeric" => "Atribūtam :attribute ir jābūt vismaz :min.",
     "string" => "Atribūtam :attribute ir jābūt vismaz :min rakstzīmēm.",
],
     "min_digits" => "Laukā :attribute jābūt vismaz :min cipariem.",
     "missing" => "Jātrūkst laukam :attribute.",
     "missing_if" => "Laukam :attribute ir jābūt iztrūkstošam, ja :other ir :value.",
     "missing_unless" => "Laukam :attribute ir jātrūkst, ja vien :other nav :value.",
     "missing_with" => "Laukam :attribute ir jābūt iztrūkstošam, ja ir :values.",
     "missing_with_all" => "Ja ir :vērtības, laukam :attribute ir jābūt iztrūkstošam.",
     "multiple_of" => "Laukam :attribute ir jābūt :value daudzkārtnim.",
     "not_in" => "Atlasītais :attribute nav derīgs.",
     "not_regex" => ":attribute formāts nav derīgs.",
     "numeric" => "Atribūtam :attribute ir jābūt skaitlim.",
     "password" => [
     "letters" => "Laukā :attribute ir jāsatur vismaz viens burts.",
     "mixed" => "Laukā :attribute ir jābūt vismaz vienam lielajam un vienam mazajam burtam.",
     "numbers" => "Laukā :attribute ir jābūt vismaz vienam skaitlim.",
     "symbols" => "Laukā :attribute ir jābūt vismaz vienam simbolam.",
     "uncompromised" => "Dotais :attribute ir parādījies datu noplūdē. Lūdzu, izvēlieties citu :attribute.",
],
     "present" => "Jābūt laukam :attribute.",
     "present_if" => "Laukam :attribute ir jābūt, ja :other ir :value.",
     "present_unless" => "Laukam :attribute ir jābūt, ja vien :other nav :value.",
     "present_with" => "Laukam :attribute ir jābūt klāt, ja ir :values.",
     "present_with_all" => "Laukam :attribute ir jābūt klāt, ja ir :vērtības.",
     "prohibited" => "Lauks :attribute ir aizliegts.",
     "prohibited_if" => "Lauks :attribute ir aizliegts, ja :other ir :value.",
     "prohibited_unless" => "Lauks :attribute ir aizliegts, ja vien :other nav :values.",
     "prohibits" => "Lauks :attribute neļauj :other atrasties.",
     "regex" => ":attribute formāts nav derīgs.",
     "required" => "Lauks :attribute ir jāaizpilda obligāti.",
     "required_array_keys" => "Laukā :attribute ir jābūt ierakstiem: :values.",
     "required_if" => "Lauks :attribute ir nepieciešams, ja :other ir :value.",
     "required_if_accepted" => "Lauks :attribute ir obligāts, ja tiek pieņemts :other.",
     "required_if_declined" => "Lauks :attribute ir nepieciešams, ja :other ir noraidīts.",
     "required_unless" => "Lauks :attribute ir obligāts, ja vien :other nav :values.",
     "required_with" => "Lauks :attribute ir nepieciešams, ja ir :values.",
     "required_with_all" => "Lauks :attribute ir nepieciešams, ja ir :values.",
     "required_without" => "Lauks :attribute ir nepieciešams, ja :values nav.",
     "required_without_all" => "Lauks :attribute ir nepieciešams, ja nav neviena no :vērtībām.",
     "same" => ":attribute un :other ir jāsakrīt.",
     "size" => [
     "array" => "Atribūtā :attribute ir jāsatur :size vienumi.",
     "file" => ":attribute ir jābūt :size kilobaitiem.",
     "numeric" => ":attribute ir jābūt :size.",
     "string" => ":attribute ir jābūt :size rakstzīmēm.",
],
     "starts_with" => "Laukam :attribute jāsākas ar vienu no šiem: :values.",
     "string" => "Atribūtam :attribute ir jābūt virknei.",
     "timezone" => "Atribūtam :attribute ir jābūt derīgai zonai.",
     "unique" => ":attribute jau ir izmantots.",
     "uploaded" => "Atribūtu :attribute neizdevās augšupielādēt.",
     "uppercase" => "Laukam :attribute jābūt ar lielajiem burtiem.",
     "url" => ":attribute formāts nav derīgs.",
     "ulid" => "Laukam :attribute ir jābūt derīgam ULID.",
     "uuid" => "Laukam :attribute ir jābūt derīgam UUID.",
     "custom" => [
     "attribute-name" => [
     "rule-name" => "pielāgots ziņojums",
],
     "g-recaptcha-response" => [
     "required" => "Lūdzu, pārbaudiet, vai neesat robots.",
     "captcha" => "Captcha kļūda! vēlāk mēģiniet vēlreiz vai sazinieties ar vietnes administratoru.",
],
],
     "attributes" => [
        
     ],
];