<?php 

 return [
     "email-types" => [
        [
     "title" => "Naročilo potrjeno s strani kupca",
],
        [
     "title" => "Potrdilo o plačilu stranke",
],
        [
     "title" => "Obvestilo prodajalca o potrditvi naročila",
],
        [
     "title" => "Potrdite naročilo škatle za kupca",
],
        [
     "title" => "Potrdite plačilo blagajne za kupca",
],
        [
     "title" => "Obvestilo o nakupu v škatli prodajalca",
],
        [
     "title" => "Obvestite kontaktni obrazec",
],
        [
     "title" => "Čestitke za vstop v trgovino",
],
        [
     "title" => "Obvestilo o prejemu darilne kartice uporabniku",
]
     ],
     "global" => [
     "greetings" => "Živjo :ime",
     "end-statement" => "Podporna ekipa",
     "receiver_name" => "Pozdravljeni :user_name",
     "footer-help" => "Rabim pomoč? Vprašajte na [support@selldone.com](mailto:support@selldone.com) ali obiščite naš [center za pomoč](https://selldone.com/help)",
     "footer-shop" => "Če potrebujete pomoč pri čemer koli, nam ne oklevajte in nam pišite na e-pošto: :shop_mail",
     "accept" => "Sprejmi",
     "reject" => "Zavrni",
     "verify" => "preveriti",
     "title" => "Naslov",
     "value" => "vrednost",
     "description" => "Opis",
     "Shop" => "Nakupujte",
     "user" => "Uporabnik",
     "license" => "Licenca",
     "status" => "Stanje",
     "start" => "Začni",
     "end" => "Konec",
     "renewal" => "Obnova",
     "view" => "Ogled",
     "balance" => "Ravnovesje",
     "card_number" => "Številka kartice",
     "cvv" => "Cvv",
     "expire_date" => "Rok uporabnosti",
     "dashboard" => "armaturna plošča",
     "order" => "naročilo",
     "view_order" => "Oglejte si naročilo",
     "pay_now" => "Pay now",
     "official_selldone" => "URADNO PRODANO",
     "account-number" => "Account number",
     "account-name" => "Account name",
     "currency" => "valuta",
     "free-balance" => "Prosto stanje",
     "locked-balance" => "Zaklenjeno stanje",
     "bot" => "bot",
     "requests" => "Zahteve",
     "baskets" => "Vozički",
     "physical" => "fizično",
     "virtual" => "Virtualna",
     "file" => "mapa",
     "service" => "Storitev",
     "fulfillment" => "Izpolnitev",
     "open" => "Odprto",
     "reserved" => "Rezervirano",
     "canceled" => "Prekinjeno",
     "payed" => "Plačano",
     "cod" => "COD",
     "orders-count" => "Naročila",
     "payments-count" => "plačila",
     "confirms-count" => "Potrjuje",
     "sends-count" => "Pošlje",
     "delivers-count" => "Dostavlja",
     "count" => "štetje",
     "transactions-count" => "Štejejo se transakcije",
     "success-transactions" => "Uspešne transakcije",
     "total-amount" => "Skupni znesek",
     "amount" => "Znesek",
     "wage" => "Plača",
     "debug" => "Odpravljanje napak",
     "pos" => "POS",
     "live" => "V živo",
     "CheckQueue" => "Preverite čakalno vrsto",
     "OrderConfirm" => "Potrditev naročila",
     "PreparingOrder" => "Priprava naročila",
     "SentOrder" => "Poslano naročilo",
     "ToCustomer" => "Dostavljeno stranki",
     "Pending" => "V teku",
     "Accepted" => "Sprejeto",
     "Rejected" => "Zavrnjeno",
     "pc" => "PC",
     "tablet" => "tablica",
     "phone" => "Telefon",
     "total" => "Skupaj",
     "view-detail" => "Poglej Podrobnosti",
     "empty" => "Prazno",
     "dropshipping" => "Dropshipping",
     "reply" => "Odgovori",
     "reactions" => "Reakcije",
     "comments" => "komentarji",
     "last-comment" => "Zadnji komentar",
     "response-to" => "Odgovor na",
     "posts" => "Objave",
     "post" => "Objava",
     "name" => "ime",
     "email" => "E-naslov",
     "type" => "vrsta",
     "device" => "Naprava",
     "platform" => "Platforma",
     "browser" => "Brskalnik",
     "time" => "Čas",
     "wallet" => "denarnica",
     "date" => "Datum",
     "account" => "račun",
     "transaction" => "Transakcija",
     "fee" => "Pristojbina",
     "location" => "Location",
     "ip" => "Ip",
     "bill" => "Bill",
     "category" => "Kategorija",
     "password" => "Geslo",
     "shop" => "Nakupujte",
     "verify-login" => "Preveri in se prijavi",
     "url" => "URL",
     "avocado" => "Avokado",
     "hyper" => "Hiper",
     "buy-now" => "Kupi zdaj",
     "add-domain" => "Add Domain",
     "views" => "Pogledi",
     "country" => "Država",
     "address" => "naslov",
     "postal" => "Poštna številka",
     "building_no" => "Stavba št.",
     "building_unit" => "Enota št.",
     "message" => "Sporočilo",
     "customer" => "Stranka",
     "cart-items" => "Predmeti v košarici",
     "payment" => "Plačilo",
     "receiver" => "Sprejemnik",
     "virtual-items" => "Virtualni predmeti",
     "no-payment" => "Brez plačila!",
],
     "selldone-business-os" => "Selldone Business OS",
     "senders" => [
     "WeeklyReport" => [
     "id" => "performance",
     "name" => "Poročilo o uspešnosti, Selldone",
],
     "SeasonalReport" => [
     "id" => "seasonal",
     "name" => "Sezonsko poročilo, Selldone",
],
     "Onboarding" => [
     "id" => "živjo",
     "name" => "Ekipa Selldone",
],
     "Support" => [
     "id" => "support",
     "name" => "Podpora: ime",
],
     "EmailVerify" => [
     "id" => "verify",
     "name" => "Preveri, prodano",
],
     "Welcome" => [
     "id" => "živjo",
     "name" => "Skupnost, Selldone",
],
     "NewShop" => [
     "id" => "trgovci",
     "name" => "Trgovci, Selldone",
],
     "Approve" => [
     "id" => "odobriti",
     "name" => "Odobri, Selldone",
],
     "SellerReceiveOrder" => [
     "id" => "order",
     "name" => "Upravljanje naročil: ime",
],
     "Recovery" => [
     "id" => "okrevanje",
     "name" => "Ekipa za obnovitev Selldone",
],
],
     "bill-status" => [
     "PENDING" => "V teku ⌛",
     "PAYED" => "Plačano ✅",
     "CANCELED" => "Preklicano ❌",
],
     "shop-invite" => [
     "LEVEL-NAME" => [
     "ADMIN" => "Administrator",
     "OFFICER" => "Častnik in nadzornik",
     "AUDITING" => "Vodja revizije",
     "EMPLOYEE" => "Zaposleni",
     "PRODUCT" => "Vodja izdelkov",
     "CONTENT" => "Upravitelj vsebine",
     "MARKETING" => "Vodja marketinga",
     "VIEWER" => "Pregledovalec",
],
     "subject" => ":inviter Povabi vas kot :level | :trgovina",
     "category" => "Vabilo osebju",
     "title" => "Povabljeni ste bili v <b>:shop_name</b> kot <b>:level</b> .",
     "message" => "Poslano vam je bilo povabilo. Lahko ga potrdite ali zavrnete. Če ste to povabilo odobrili, morate vstopiti v storitev Selldone, da ga potrdite. S potrditvijo tega povabila boste imeli dostop do razdelka za upravljanje trgovine.",
],
     "welcome-email" => [
     "subject" => "👋 Dobrodošli :name, nekaj zanimivih stvari samo za vas.",
     "category" => "CONGRATULATION",
     "title" => "DOBRODOŠLI V SELLDONE",
     "message" => "Hvala, ker ste izbrali Selldone. Zdaj ste del skupnosti Selldone, ki povezuje globalne prodajalce s strankami, lokalno podjetje s podjetjem, posameznika s korporacijo! Vsa glavna in profesionalna orodja so vam na voljo **brezplačno** in **neomejeno**. Vi poskusite, mi odpremo vrata, Just Do It!",
     "seller" => [
     "title" => "Ali ste prodajalec?",
     "message" => "Če želite začeti prodajati, vnesite svojo nadzorno ploščo v Selldone prek spodnje povezave in ustvarite svojo prvo trgovino popolnoma brezplačno. To bo trajalo nekaj minut in imeli boste svojo trgovino in spletno stran. Nato vas bomo vodili do naslednjih korakov in pridobili plačilni prehod.",
     "action" => "Prijavite se na mojo nadzorno ploščo",
],
     "buyer" => [
     "title" => "Jaz sem kupec",
     "message" => "čestitke Ko postanete član Selldone, se boste znebili vseh težav s članstvom in preverjanjem pristnosti v spletnih trgovinah. Če želite izkoristiti vse trgovine in spletne strani, ki uporabljajo platformo Selldone, se lahko prijavite z enim klikom in naredite svoj nakup preprost, hiter in varen.",
],
],
     "charge-account" => [
     "category" => "Denarnica > Račun > Bremenitev",
     "title" => "Naboj za uspeh",
     "message" => "Vaš račun <b>:account_number</b> je bil uspešno <b>:</b> zaračunan.",
     "account" => "račun",
     "charge" => "Napolniti",
     "balance" => "Ravnovesje",
     "footer" => "Naredite poslovanje enostavno, dosegljivo in dostopno vsem po svetu.",
],
     "verify-email" => [
     "subject" => "🙌 Dokončajte svojo prijavo v Selldone! Preveri povezavo.",
     "category" => "SI EN KORAK DALJE",
     "title" => "Preverite svoj e-poštni naslov",
     "message" => "Živjo :name,<br> Hvala, ker ste izbrali Selldone.<br> Prosimo potrdite, da je **:email** vaš e-poštni naslov s klikom na gumb ali uporabite spodnjo povezavo v 48 urah.",
     "footer" => "Če imate težave s klikom na gumb Preveri, kopirajte in prilepite spodnji URL v spletni brskalnik: __:activation_url__",
],
     "verify-email-code" => [
     "subject" => "Koda za preverjanje za :name",
     "category" => "SECURITY",
     "title" => "E-poštna koda za preverjanje",
     "message" => "Živjo :name,<br><br> S to kodo v 10 minutah potrdite, da je **:email** vaš e-poštni naslov.",
],
     "onboarding-verify-email" => [
     "subject" => "🎉 Vaša trgovina je pripravljena | :ime",
     "category" => "SI EN KORAK DALJE",
     "title" => "Namestitev končana",
     "account_title" => "Vaš račun",
     "account_msg" => "Preverite in se prijavite v svoj račun s temi podatki.",
     "shop_msg" => "Podatki o računu v poslovnem operacijskem sistemu Selldone.",
],
     "reset2fa" => [
     "category" => "URADNO VARNOSTNO SPOROČILO",
     "title" => "Zahtevajte onemogočanje prijave v dveh korakih",
     "message" => "To e-poštno sporočilo ste prejeli, ker smo prejeli zahtevo za ponastavitev dvostopenjske avtentikacije za vaš račun.<br><br> E-pošta uporabnika: <b>:e-pošta</b><br> Ime: <b>:ime</b>",
     "footer" => "Če niste zahtevali ponastavitve gesla, ni potrebno nobeno nadaljnje dejanje.",
     "action" => "Onemogoči prijavo v dveh korakih",
],
     "build-new-shop" => [
     "subject" => "🎊 Vaša trgovina je zdaj pripravljena!",
     "category" => "RODJENA NOVA SPLETNA TRGOVINA NA SVETU",
     "title" => "praznuje",
     "message" => "<b>Čestitke :name, ustvarili ste novo spletno podjetje;</b> Želimo vam uspeh pri vašem poslu. Dobrodošli v skupnosti Selldoners.<br> Vi poskusite, mi odpremo vrata in uspelo vam je.",
     "pdf-book" => "Ne zamudite priložene priročnike: Poslujte kot igra",
     "account" => [
     "title" => "1. korak: ustvarite račun v denarnici Selldone",
     "message" => "Če v denarnici nimate računa, ga ustvarite. Selldone odšteje pristojbino s tega računa. Ta račun lahko dopolnite, Selldone pa vam bo zaračunal tudi znesek kredita, tako da bosta vaše spletno mesto in trgovina še naprej delovala, če je ta račun negativen.",
     "action" => "Prijava v denarnico",
],
     "shop-account" => [
     "title" => "2. korak: povežite račun s trgovino",
     "message" => "Dodajte svoj račun denarnice v svojo trgovino. To storite tako, da vnesete Trgovina > Računovodstvo > Račun in povežete račun s trgovino. Upoštevajte, da so vsa plačila vaših strank nakazana neposredno na vaš bančni račun in Selldone ne dvigne ali odšteje nobenega zneska, zato morate ta račun Selldone povezati s trgovino.",
     "action" => "Plošča za račune trgovine",
],
     "gateway" => [
     "title" => "3. korak: Povežite spletni plačilni prehod",
     "message" => "Pojdite na Trgovina> Računovodstvo> Vrata in pritisnite <b>Dodaj nova vrata</b> . Ko izberete valuto, se vam prikaže seznam prenosnih vrat. Povezovanje vrat v Selldone je zelo preprosto in hitro, vendar če imate Nizo za vodenje, si oglejte razdelek vodnika Selldone ali vprašajte nas.",
     "action" => "Dodajte portal v trgovino",
],
     "domain" => [
     "title" => "Zadnji korak: povezava namenske domene",
     "message" => "Svojo trgovino boste lahko imeli na poljubnem številu domen. Če želite namensko domeno povezati s trgovino, morate imeti vsaj zagonsko licenco. Če vsakemu prijatelju predstavite Selldone, boste prejeli enomesečno darilno kartico za zagonsko licenco. Odstotek plačil vaših prijateljev bo knjižen tudi na račune vaših strank.",
     "action" => "Predstavitev in prejemanje neomejenih darilnih kartic",
],
],
     "basket-list" => [
     "item" => "predmet",
     "count" => "štetje",
     "price" => "cena",
     "discount-code" => "Koda za popust",
     "customer-club" => "Klub strank",
     "shipping" => "Dostava",
     "total" => "Skupaj",
     "offer" => "Ponudba",
     "coupon" => "kupon",
     "lottery" => "Nagrada",
     "tax" => "davek",
     "tax_included" => "Vključeno v ceno",
     "tax_shipping" => "Shipping Tax",
],
     "buyable-payments" => [
     "method" => "Metoda",
     "amount" => "Znesek",
     "giftcard" => "Gift card",
     "payment" => "Plačilo",
],
     "shop-subscription-email" => [
     "category" => "Posodobitev naročnine",
     "title" => "Licenca trgovine: :shop_title",
     "title-reserved" => "Rezervna licenca: :shop_title",
     "title-active" => "Aktivna licenca: :shop_title",
     "title-finished" => "Dokončana licenca: :shop_title",
     "title-cancel" => "Prekliči licenco: :shop_title",
     "message" => "Vaš licenčni načrt trgovine posodobljen,",
     "RESERVED" => "⚡ Vaša naročnina je bila **rezervirana**.",
     "ACTIVE" => "🟢 Vaša naročnina je bila **aktivirana**.",
     "FINISHED" => "🚧 Vaš naročniški načrt je **dokončan**.",
     "CANCEL" => "⛔ Vaša naročnina je bila **preklicana**.",
],
     "support" => [
     "subject" => "Center za podporo | :name je odgovoril",
     "category" => "Center za podporo",
     "title" => "Prejeli ste odgovor",
     "action" => "Odpri skrbnika trgovine",
],
     "shop-customer-join" => [
     "subject" => "Pridružite se :shop_title",
     "category" => "Praznovanje nove stranke",
     "title" => "Veseli smo vašega članstva",
     "action" => "Obiščite zdaj",
],
     "shop-giftcard" => [
     "subject" => "Darilna kartica :shop_title",
     "category" => "Dodaj novo kartico",
     "title" => "Čestitamo, prejeli ste darilno kartico",
     "action" => "Nakupujte zdaj",
     "message" => "Prejeli ste darilno kartico v vrednosti :balance :currency. S to darilno kartico boste lahko kupovali v naši trgovini.",
],
     "contact" => [
     "subject" => "Center za podporo | :trgovina",
     "category" => "podporo",
     "title" => "Prejeli ste odgovor",
],
     "order-checkout" => [
     "subject" => "🛍 Naročilo Blagajna | :Številka naročila",
     "title" => "naročilo",
     "message" => "Potrditev vašega naročila,<br> Dobili smo vaše naročilo. Ko bo vaše naročilo poslano, vam bomo poslali še eno e-poštno sporočilo.",
     "payments" => "plačila",
],
     "order-payment" => [
     "subject" => "🛍 Potrditev plačila | :Številka naročila",
     "title" => "Plačilni nalog",
     "message" => "Vaše plačilo je zaključeno,<br> Dobili smo vaše naročilo. Ko bo vaše naročilo poslano, vam bomo poslali še eno e-poštno sporočilo.",
     "payments" => "plačila",
],
     "get-voucher" => [
     "subject" => "Čestitke :name | Nov kupon: :title",
     "category" => "ČESTITKE, NOV BON",
     "message" => "Prejmete nov bon, to je naše darilo za vas. S temi kuponi lahko dobite več, če predstavite Selldone prijateljem in vsem, ki jih poznate. Ta kupon je vreden **:cena :valuta**.<br> Vi poskusite, mi odpremo vrata, čestitamo, odklenete funkcije z vašim kuponom!",
     "action" => "Moja nadzorna plošča",
],
     "received-gift" => [
     "subject" => "Čestitke, draga :name | Prejeli ste darilo",
     "category" => "Obvestilo o prejemu darila",
     "title" => "Darila za vas",
     "message" => "Prejeli ste novo darilo. To je darilo podjetja Selldone. Več teh daril lahko prejmete, če ste bolj dejavni v Selldone in razvijate svojo trgovino ter dvignete raven specializacije. Vrednost tega darila je **:cena :valuta**, ki jo lahko položite neposredno v svojo denarnico v selldone.<br><br> Uporabite to darilo za nadgradnjo licence za trgovino in uporabo več orodij v vašem spletnem poslovanju.",
     "action" => "darila",
],
     "order-payment-admin" => [
     "subject" => "🛍 Prejeto novo naročilo | :Številka naročila",
     "title" => "New Order",
     "message" => "Prejeli ste novo naročilo. Pojdite na stran za obdelavo naročil v vaši trgovini.",
],
     "virtual-item" => [
     "input-form-title" => "Vaše izpolnjene informacije",
     "output-form-title" => "Informacije o kupljenem artiklu",
],
     "selldone-weekly-report" => [
     "subject" => "📬 :shop_title | Tedensko poročilo :čas",
     "title" => "Tedensko poročilo o uspešnosti trgovine",
     "message" => "To je tedensko poročilo vaše trgovine od :začetka do :konca. To poročilo vsebuje nasvete za izboljšanje vašega poslovanja, preverite lahko tudi stanje vaše spletne trgovine in zadnja naročila. Upam, da imate dober dan in teden.",
],
     "shop-seasonal-report" => [
     "subject" => "☘ Vaše poročilo o prihrankih v zadnjih treh mesecih | :naslov_trgovine",
     "title" => "Sezonsko poročilo o vaši poslovni dejavnosti, nagradah in finančnih prihrankih",
     "message" => "To je vaše :shop_title sezonsko poročilo od :start do :end.",
],
     "EC-ShopAccounts" => [
     "title" => "Povezani računi",
     "sub-title" => "Kakšno je zadnje stanje računov denarnice, povezanih z mojo trgovino?",
     "view-wallet" => "Ogled denarnice",
     "tip-title" => "Pomembni nasveti",
     "tip" => "V naslednjem koraku ustvarite brezplačen račun v denarnici Selldone in ga povežite s to trgovino. Tudi če je stanje na vašem računu Selldone negativno, lahko vaše stranke še vedno brez težav opravljajo nakupe in plačila za vašo trgovino. Vaši podatki in storitev ne bodo prekinjeni ali omejeni vsaj 1 mesec.",
     "view-my-wallet" => "My wallet",
     "connect-account" => "Povežite se z računom",
],
     "EC-ShopApps" => [
     "title" => "Nameščene aplikacije",
     "sub-title" => "Seznam aplikacij, ki ste jih ta teden namestili v svojo trgovino.",
     "tip" => "Ali želite najti več aplikacij za svojo trgovino?",
     "view-app-store" => "Obiščite trgovino z aplikacijami Selldone..",
],
     "EC-ShopBots" => [
     "title" => "Vaši Store Boti",
     "sub-title" => "Aktivni prodajni roboti v moji trgovini.",
     "tip-title" => "Razprodaja botov",
     "tip" => "Selldone vam je zagotovil samodejne prodajne robote. Vse, kar morate storiti, je, da odprete ploščo Dodatki> Boti in aktivirate bote svoje trgovine. Upoštevajte, da mora biti ustrezna storitev na voljo v vaši državi.",
     "view-bots" => "Upravljanje botov",
],
     "EC-ShopContacts" => [
     "title" => "Komunikacija s strankami",
     "sub-title" => "Koliko stikov sem imel s svojimi strankami ta teden?",
     "faqs" => "Pogosto zastavljena vprašanja",
     "tickets" => "Vstopnice za stranke",
],
     "EC-ShopData" => [
     "title" => "Stanje uporabnikov",
     "sub-title" => "Od datuma :začetek do :konec",
     "users" => [
     "title" => "Stranke",
     "subtitle" => "Prijava uporabnikov",
],
     "views" => [
     "title" => "Obiski",
     "subtitle" => "Kolikokrat ste že obiskali trgovino",
],
     "new_visitors" => "New Users",
     "returning_visitors" => "Vrnjeni uporabniki",
     "shop_views" => "Trgovina Pogledi",
     "baskets" => [
     "title" => "Nakupovalni vozički",
     "subtitle" => "Sporočite število novih nakupovalnih vozičkov",
],
     "products" => [
     "title" => "Pregled izdelkov",
     "subtitle" => "Status izdelkov v trgovini po vrstah",
     "value_name" => "Izdelki",
],
     "products_count" => "Vrste izdelkov",
     "views_count" => "Število ogledov",
     "sell_count" => "Število prodaj",
     "send_count" => "Število pošiljk",
],
     "EC-ShopDropShipping" => [
     "title" => "Pametna dostava",
     "sub-title" => "Panel za glavne prodajalce Drop Shipping Selldone.",
     "total_fulfillments" => "Skupno število prejetih naročil",
     "ds_count" => "Prejeta naročila",
     "statistics_title" => "Poročilo o prejetih naročilih",
     "ds_cancels" => "Prekliči prodajalec vmesnika",
     "ds_rejects" => "Preklic z vaše strani",
     "tip" => "Ste glavni prodajalec blaga? Ste lastnik skladišča, tovarne ali distributerja izdelkov? Svoje izdelke lahko ponudite drugim prodajalcem v storitvi Selldone Drop Shipping, da svoj izdelek prodate v velikem obsegu. Pišite nam na support@selldone.com, da vas vodimo.",
     "view-drop-shipping-panel" => "Prijavite se v veleprodajno ploščo",
],
     "EC-ShopExchangeRates" => [
     "title" => "Menjalni tečaji",
     "sub-title" => "Seznam najnovejših menjalnih tečajev valut v vaši trgovini.",
     "from" => "Izvorna valuta",
     "to" => "Ciljna valuta",
     "rate" => "Stopnja konverzije",
     "vew-exchange-panel" => "plošča za upravljanje menjalnih tečajev",
],
     "EC-ShopExperts" => [
     "title" => "Strokovne pogodbe",
     "sub-title" => "Kateri strokovnjaki delajo v moji trgovini?",
     "cost" => "Znesek pogodbe",
     "duration" => "Trajanje",
     "start_at" => "Start Date",
     "complete_at" => "Completion Date",
     "cancel_at" => "Datum Prekliči",
     "end_at" => "Datum dostave",
     "tip" => "Za razvoj vašega podjetja lahko najamete najboljše strokovnjake v Selldone.",
     "view-experts" => "Kliknite za začetek.",
],
     "EC-ShopGateways" => [
     "title" => "Payment gateways",
     "sub-title" => "Prijavite aktivne plačilne prehode v trgovini :shop.",
     "tip-title" => "Pomembni nasveti",
     "tip" => "Pojdite na stran za upravljanje portala v svoji trgovini in v nekaj minutah dodajte vsaj ena vrata. Vaše stranke rade plačujejo hitro in varno prek spletnih portalov.",
     "view-shop-gateways" => "Prijavite se v upravljanje portala moje trgovine.",
     "view-gateways" => "Oglejte si več prehodov",
],
     "EC-ShopOrders" => [
     "title" => "Naročila",
     "sub-title" => "Seznam naročil, ki sem jih prejel ta teden.",
     "total_baskets" => "Skupna naročila",
     "total_posBaskets" => "Skupni gotovinski nalogi",
     "pos-title" => "POS Store Box",
     "chart-label" => "Naročila zaključena (ta naročila niso nujno plačana!)",
     "tip-title" => "Moral bi se bolj potruditi ...",
     "tip" => "Ni preprostega uspeha.",
],
     "EC-ShopProcessCenter" => [
     "title" => "Obdelovalni center",
     "sub-title" => "Koliko naročil smo ta teden obdelali v trgovini?",
     "tip-title" => "Niste imeli razprodaje!",
     "tip" => "Na žalost ta teden niste imeli nobene prodaje. V svojo trgovino morate prinesti več. Dodate lahko več izdelkov, izberete boljše slike ali napišete boljše opise za svoje izdelke. Razmislite o zaposlitvi za polni delovni čas za svoje podjetje. Če boste to storili pravilno in ne boste razočarani, vam bo uspelo.",
     "view-process-center" => "Ogled procesnega centra",
     "return" => [
     "title" => "Vrnjeno naročilo",
     "subtitle" => "Prijavi vrnjena naročila.",
     "tip-title" => "Ali ste vedeli, da ...",
     "tip" => "Prek Selldone POS lahko ustvarite poljubno število trgovinskih blagajn! Pravzaprav lahko tablični računalnik, mobilni telefon ali prenosni računalnik spremenite v svoj nabiralnik. Če vas to navdušuje, Selldone POS To je nekaj, kar bi morali začeti uporabljati zdaj. Za zagon potrebujete le preprost klik, za vaš strežnik imamo vse pripravljeno vnaprej.",
     "view-pos" => "Prijavite se v Blagajno moje spletne trgovine",
],
],
     "EC-ShopSessions" => [
     "title" => "Seje",
     "sub-title" => "Kolikokrat sem obiskal svojo trgovino?",
     "countries-title" => "Katere države so bile najbolj obiskane?",
],
     "EC-PublicMessage" => [
     "title" => "Ali želite zaslužiti denar, ne da bi porabili en dolar?",
     "message" => "Spoštovani :name, lahko greš na nadzorno ploščo > Demonetizacija in ustvariš napotitveno povezavo. Pošljite povezavo svojim prijateljem, prejeli boste darilne kartice Selldone in odstotek plačil vašega prijatelja. Upoštevajte, da bo darilna kartica poslana vam in vašemu prijatelju.",
     "action" => "Oglejte si mojo uvodno povezavo",
     "mail-clip" => "<b style='color: #C2185B'>Pomembno:</b> če uporabljate e-poštne storitve, kot je Gmail, ki omejujejo dolžino e-pošte, poiščite naslednjo možnost na koncu e-pošte, da prikažete celotno poročilo, in jo kliknite:",
     "no-coin-reward" => "<b style='color: #C2185B'>Oprostite:</b> vaša dejavnost ni izpolnjevala pogojev za pridobitev brezplačne nagrade SEL Coins. Potrudite se bolj in prodajte več v svoji trgovini za naslednjo sezono.",
     "yes-coin-reward" => "<b style='color: #4CAF50'>Nagrada:</b> Čestitamo, zaradi vaše fantastične uspešnosti smo vam podelili nagrado :amount SEL Coin.",
     "need-buy-license" => "<b>Izboljšajte svoje podjetje:</b> za spletno mesto vašega podjetja niste registrirali nobenega naročniškega paketa! Zato je čas, da kupite vsaj eno naročnino. Stane samo : znesek na mesec za letni nakup.",
     "not-afford-message" => "Če si ne morete privoščiti ali imate težave s plačilom, nam to sporočite na support@selldone.com.",
     "add-domain" => "<b>Zakaj ne bi imeli domene po meri za svoje podjetje?</b><br> Dodajte domeno svojemu spletnemu mestu zdaj; brezplačno je!",
],
     "Widget-Socials" => [
     "title" => "Selldone je a<del> izdelek</del> <span style = 'color: forestgreen'>skupnost</span><br> Bodite profesionalni Selldoner!",
     "message" => "Sledite uradnim stranem Selldone na Twitterju, LinkedInu in družbenih omrežjih. Pošljite nam morebitne komentarje, zahteve ali kritike ali sodelujte v razpravah o Selldone. Smo tudi del skupnosti Selldone, ki <b>jo ustvarite vi</b> .",
],
     "avocado-seller-daily-report" => [
     "subject" => "Prejeto novo naročilo avokada | :shop_title :čas",
     "title" => "Poročilo o uspešnosti za zadnjih 24 ur",
     "message" => "Vaše stranke čakajo na pregled in ceno vaših naročil. Čim prej se odzovite na zahteve svojih strank, da zagotovite večjo prodajo.",
     "card_title" => "Naročila v čakalni vrsti",
     "card_subtitle" => "Od: datum",
     "card_payed" => "Plačana naročila",
],
     "community-comments" => [
     "subject" => "Odgovorite na svojo objavo v :community_title",
     "title" => ":name in :count drugi so komentirali vaše objave.",
     "title-simple" => ":name je komentiral vaše objave.",
],
     "community-topic" => [
     "subject" => "🔔 Odgovorite na svojo temo :topic_title",
     "title" => ":name in :count drugi so odgovorili na vašo temo.",
     "title-simple" => ":name je odgovoril na vašo temo.",
],
     "user-login" => [
     "subject" => "🔔 Nova prijava :name",
     "category" => "Varnostna obvestila",
     "title" => "Prijavite se v račun",
     "message" => "Dragi :name, prijavljeni ste v svoj račun Selldone.",
     "footer" => "Če niste prijavljeni, prosimo spremenite geslo.",
],
     "account-transaction" => [
     "withdraw" => "Umik",
     "deposit" => "Polog",
     "withdraw_subject" => "dvig z računa :račun",
     "deposit_subject" => "Polog na račun :račun",
     "message" => "Prenos denarja je bil opravljen z naslednjimi specifikacijami.",
     "type" => "Vrsta transakcije",
     "from" => "Izvorni račun",
     "to" => "Destination account",
     "desc" => "Opis transakcije",
     "action" => "Ogled transakcije",
],
     "penalty" => [
     "subject" => "⛔ Pomembno! Kršitev pravil | :trgovina",
     "category" => "Kritične informacije",
     "title" => "Vaša trgovina je bila kaznovana",
     "action" => "Odpri nadzorno ploščo trgovine",
],
     "invite" => [
     "subject" => ":inviter te je povabil v Selldone",
     "title" => ":name vam je poslal :amount, da vam pomaga zagnati novo spletno spletno stran in jo monetizirati!",
     "message" => "Na Selldone lahko ustvarite svoje spletno mesto za e-trgovino, bloganje in spletno skupnost ter celo dobite spletno POS in nastavite osebno prodajo v nekaj minutah. To je operacijski sistem za spletno poslovanje, s katerim bo vaše poslovanje na spletu boljše in hitrejše. Preprosto se prijavite do <b>:date</b> , da prejmete bon za :amount.",
     "accept" => "Sprejmi povabilo",
     "owner" => "Lastnik",
     "join-date" => "Na Selldone od",
],
     "shop-recovery" => [
     "subject" => "Povezava za obnovitev | :trgovina",
     "category" => "Varnost trgovine",
     "title" => "Povezava za obnovitev trgovine <b>:shop_name</b> .",
     "message" => "To e-poštno sporočilo ste prejeli, ker ste zahtevali obnovitev vaše trgovine. S klikom na spodnjo povezavo boste obnovili svojo trgovino in vse podatke, ki pripadajo njej.",
     "action" => "Potrdite obnovitev trgovine",
],
     "SR-SeasonalSaving" => [
     "title" => "Koliko denarja je Selldone prihranil vašemu podjetju?",
     "sub-title" => "Od datuma :začetek do :konec",
     "infrastructure" => [
     "title" => "Infrastruktura",
     "subtitle" => "Strežniki, CDN, Storage in druge storitve v oblaku",
],
     "experts" => [
     "title" => "Strokovnjaki in osebje",
     "subtitle" => "Razvijalci, vzdrževanje in podpora",
],
     "total_save" => "Skupaj prihranjen denar",
],
     "SR-SeasonalPerformance" => [
     "title" => "Vaš nastop",
     "sub-title" => "Pregled poslovanja od :začetka do :konca",
     "new_visitors" => "New Users",
     "returning_visitors" => "Vrnjeni uporabniki",
     "shop_views" => "Trgovina Pogledi",
     "baskets" => [
     "title" => "Nakupovalni vozički",
     "subtitle" => "Sporočite število novih nakupovalnih vozičkov",
],
     "products" => [
     "title" => "Pregled izdelkov",
     "subtitle" => "Status izdelkov v trgovini po vrstah",
     "value_name" => "Izdelki",
],
     "views" => [
     "title" => "Page Views",
     "subtitle" => "Skupno število ogledov strani spletnega mesta",
],
],
];