<?php 

 return [
     "home" => "sålt gjort",
     "blogs" => "Blogg",
     "helps" => "Hjälp",
     "current_location" => "Denna post",
     "dashboard" => "dashboard",
     "my_shops" => "Mina butiker",
     "wallet" => "wallet",
     "about" => "Om Selldone",
     "contact" => "contact us",
     "comments" => "comments",
     "likes" => "Gillar",
     "power" => "heja på",
     "build_free_shop" => "Bygg din butik gratis",
     "shop_name" => "shop name",
     "categories" => "categories",
     "sub_articles" => "More",
     "terms" => "Villkor",
     "colour" => "Färg",
     "style" => "style",
     "volume" => "volume",
     "weight" => "weight",
     "pack" => "Packa",
     "type" => "type",
     "add_to_card" => "Lägg till i kundvagn",
     "overview" => "Overview",
     "reviews" => "Recensioner",
     "spec" => "Full spec",
     "you_may_also_like" => "Du kanske också gillar",
     "about_us" => "Om oss",
     "contact_us" => "contact us",
     "cookie_privacy" => "Cookie &amp; privacy policy",
     "follow_us" => "Följ oss",
     "category" => "Kategori",
     "author" => "Written by ",
     "published_at" => "Publicerad på",
     "modified_at" => "Ändrad kl",
     "price" => "pris",
     "discount" => "Rabatt",
     "price_after_discount" => "Pris efter rabatt",
     "available" => "Tillgängliga",
     "sold_out" => "Utsåld",
     "buy" => "Köp nu",
     "login_shop" => "Logga in butik",
     "posted_on" => "Postat den :date",
];