<?php 

 return [
     "profile" => "Funda imininingwane yephrofayili efaka igama, ikheli le-imeyili, isithombe nesimo sokuqinisekisa.",
     "phone" => "Ukufinyelela inombolo yokuxhumana",
     "address" => "Funda futhi uhlele ikheli encwadini yamakheli elondoloziwe",
     "buy" => "Oda & Thenga Oda.",
     "order-history" => "Funda umlando we-oda.",
     "my-gift-cards" => "Access to my cards.",
     "articles" => "Hlela Izihloko.",
     "notifications" => "Thumela futhi wamukele izaziso.",
     "read-shops" => "Funda Uhlu Lwesitolo.",
     "shop-edit" => "Gcina ukufinyelela kokuhlela.",
     "shop-contacts" => "Thola futhi uhlele amafomu okuxhumana.",
     "shop-gift-cards" => "Ukudala, ukuhlela, nokuphatha amakhadi.",
     "shop-faqs" => "Dala, hlela, futhi uphathe imibuzo evame ukubuzwa.",
     "shop-categories" => "Ukudala, ukuhlela, nokuphatha izigaba.",
     "shop-products" => "Ukudala, Ukuhlela kanye Nokuphatha Imikhiqizo.",
     "shop-read-reports" => "Funda ulwazi nemibiko.",
     "shop-socials" => "Hlela amanethiwekhi omphakathi esitolo.",
     "shop-accounts" => "Hlela futhi ususe ama-akhawunti ezezimali axhunywe esitolo.",
     "shop-menus" => "Hlela amamenyu esitolo.",
     "shop-pages" => "Hlela amakhasi esitolo.",
     "shop-warehouse" => "Hlela Isitolo Sempahla",
     "shop-permissions" => "Buka futhi uhlele ukufinyelela esitolo.",
     "shop-process-center" => "Phatha ama-oda atholiwe.",
     "shop-profile" => "Phatha amaphrofayili esitolo.",
     "shop-discount-code" => "Phatha amakhodi esaphulelo.",
     "shop-coupon" => "Phatha amakhuphoni.",
     "shop-offer" => "Phatha okunikezwayo.",
     "shop-lottery" => "Phatha amalotho.",
     "shop-community" => "Phatha umphakathi.",
];