<?php 

 return [
     "accepted" => "គុណលក្ខណៈ : ត្រូវតែទទួលយក។",
     "active_url" => ":attribute មិនមែនជា URL ត្រឹមត្រូវទេ។",
     "after" => ":attribute ត្រូវតែជាកាលបរិច្ឆេទបន្ទាប់ពី :date ។",
     "after_or_equal" => ":attribute ត្រូវតែជាកាលបរិច្ឆេទបន្ទាប់ពី ឬស្មើនឹង :date។",
     "alpha" => ":attribute អាចមានត្រឹមតែអក្សរប៉ុណ្ណោះ។",
     "alpha_dash" => "គុណលក្ខណៈ :attribute អាចមានតែអក្សរ លេខ និងសញ្ញាដាច់ៗប៉ុណ្ណោះ។",
     "alpha_num" => ":attribute អាចមានត្រឹមតែអក្សរ និងលេខប៉ុណ្ណោះ។",
     "array" => "គុណលក្ខណៈ : ត្រូវតែជាអារេ។",
     "before" => ":attribute ត្រូវតែជាកាលបរិច្ឆេទមុន :date ។",
     "before_or_equal" => ":attribute ត្រូវតែជាកាលបរិច្ឆេទមុន ឬស្មើនឹង :date។",
     "between" => [
     "numeric" => ":attribute ត្រូវតែស្ថិតនៅចន្លោះ :min និង :max។",
     "file" => ":attribute ត្រូវតែស្ថិតនៅចន្លោះ :min និង :max kilobytes។",
     "string" => ":attribute ត្រូវតែស្ថិតនៅចន្លោះ :min និង :max តួអក្សរ។",
     "array" => ":attribute ត្រូវតែមានរវាង :min និង :max items។",
],
     "boolean" => "វាល :attribute ត្រូវតែពិត ឬមិនពិត។",
     "confirmed" => "ការបញ្ជាក់ :attribute មិនត្រូវគ្នាទេ។",
     "date" => ":attribute មិនមែនជាកាលបរិច្ឆេទត្រឹមត្រូវទេ។",
     "date_format" => ":attribute មិនត្រូវគ្នានឹង format :format។",
     "different" => ":attribute និង :other ត្រូវតែខុសគ្នា។",
     "digits" => ":attribute ត្រូវតែជា :digits digits។",
     "digits_between" => ":attribute ត្រូវតែស្ថិតនៅចន្លោះ :min និង :max digits។",
     "dimensions" => ":attribute មានវិមាត្ររូបភាពមិនត្រឹមត្រូវ។",
     "distinct" => "វាល :attribute មានតម្លៃស្ទួន។",
     "email" => ":attribute ត្រូវតែជាអាសយដ្ឋានអ៊ីមែលត្រឹមត្រូវ។",
     "exists" => "គុណលក្ខណៈដែលបានជ្រើសរើសគឺមិនត្រឹមត្រូវទេ។",
     "file" => ":attribute ត្រូវតែជាឯកសារ។",
     "filled" => "វាល :attribute ត្រូវតែមានតម្លៃ។",
     "gt" => [
     "numeric" => ":attribute ត្រូវតែធំជាង :value។",
     "file" => ":attribute ត្រូវតែធំជាង :value kilobytes។",
     "string" => ":attribute ត្រូវតែធំជាង :value តួអក្សរ។",
     "array" => ":attribute ត្រូវតែមានច្រើនជាង :value items។",
],
     "gte" => [
     "numeric" => "គុណលក្ខណៈ :attribute ត្រូវតែធំជាង ឬស្មើ :value។",
     "file" => ":attribute ត្រូវតែធំជាង ឬស្មើ :value kilobytes។",
     "string" => ":attribute ត្រូវតែធំជាង ឬស្មើ :value តួអក្សរ។",
     "array" => ":attribute ត្រូវតែមាន :value items ឬច្រើនជាងនេះ។",
],
     "image" => "គុណលក្ខណៈ : ត្រូវតែជារូបភាព។",
     "in" => "គុណលក្ខណៈដែលបានជ្រើសរើសគឺមិនត្រឹមត្រូវទេ។",
     "in_array" => "វាល :attribute មិនមាននៅក្នុង :other ទេ។",
     "integer" => "គុណលក្ខណៈ : ត្រូវតែជាចំនួនគត់។",
     "ip" => ":attribute ត្រូវតែជាអាសយដ្ឋាន IP ត្រឹមត្រូវ។",
     "ipv4" => ":attribute ត្រូវតែជាអាសយដ្ឋាន IPv4 ត្រឹមត្រូវ។",
     "ipv6" => ":attribute ត្រូវតែជាអាសយដ្ឋាន IPv6 ត្រឹមត្រូវ។",
     "json" => ":attribute ត្រូវតែជាខ្សែអក្សរ JSON ត្រឹមត្រូវ។",
     "lt" => [
     "numeric" => ":attribute ត្រូវតែតិចជាង :value។",
     "file" => ":attribute ត្រូវតែតិចជាង :value kilobytes។",
     "string" => ":attribute ត្រូវតែតិចជាង :value តួអក្សរ។",
     "array" => ":attribute ត្រូវតែមានធាតុតិចជាង :value ។",
],
     "lte" => [
     "numeric" => ":attribute ត្រូវតែតិចជាង ឬស្មើ :value។",
     "file" => ":attribute ត្រូវតែតិចជាង ឬស្មើ :value kilobytes។",
     "string" => ":attribute ត្រូវតែតិចជាង ឬស្មើ :value តួអក្សរ។",
     "array" => ":attribute មិនត្រូវមានច្រើនជាង :value items។",
],
     "max" => [
     "numeric" => ":attribute ប្រហែលជាមិនធំជាង :max.",
     "file" => ":attribute ប្រហែលជាមិនធំជាង :max kilobytes។",
     "string" => ":attribute ប្រហែលជាមិនធំជាង :max តួអក្សរទេ។",
     "array" => ":attribute ប្រហែលជាមិនមានច្រើនជាង :max items។",
],
     "mimes" => ":attribute ត្រូវតែជាឯកសារប្រភេទ: :values។",
     "mimetypes" => ":attribute ត្រូវតែជាឯកសារប្រភេទ: :values។",
     "min" => [
     "numeric" => "គុណលក្ខណៈ :attribute ត្រូវតែមានយ៉ាងហោចណាស់ :min ។",
     "file" => ":attribute ត្រូវតែមានយ៉ាងហោចណាស់ :min គីឡូបៃ។",
     "string" => ":attribute ត្រូវតែមានយ៉ាងហោចណាស់ :min តួអក្សរ។",
     "array" => ":attribute ត្រូវតែមានយ៉ាងហោចណាស់ :min items ។",
],
     "not_in" => "គុណលក្ខណៈដែលបានជ្រើសរើសគឺមិនត្រឹមត្រូវទេ។",
     "not_regex" => "ទម្រង់ :attribute មិន​ត្រឹមត្រូវ។",
     "numeric" => "គុណលក្ខណៈ : ត្រូវតែជាលេខ។",
     "present" => "វាល :attribute ត្រូវតែមានវត្តមាន។",
     "regex" => "ទម្រង់ :attribute មិន​ត្រឹមត្រូវ។",
     "required" => "វាល :attribute ត្រូវបានទាមទារ។",
     "required_if" => "វាល :attribute ត្រូវបានទាមទារនៅពេលដែល :other is :value។",
     "required_unless" => "វាល :attribute គឺត្រូវបានទាមទារ លុះត្រាតែ :other ស្ថិតនៅក្នុង :values។",
     "required_with" => "វាល :attribute ត្រូវបានទាមទារនៅពេលដែល :values មានវត្តមាន។",
     "required_with_all" => "វាល :attribute ត្រូវបានទាមទារនៅពេលដែល :values មានវត្តមាន។",
     "required_without" => "វាល :attribute ត្រូវបានទាមទារនៅពេលដែល :values មិនមានវត្តមាន។",
     "required_without_all" => "វាល :attribute គឺត្រូវបានទាមទារនៅពេលដែលគ្មាន :values មានវត្តមាន។",
     "same" => ":attribute និង :other ត្រូវតែផ្គូផ្គង។",
     "size" => [
     "numeric" => ":attribute ត្រូវតែជា :size ។",
     "file" => ":attribute ត្រូវតែជា :size kilobytes។",
     "string" => ":attribute ត្រូវតែជា :size តួអក្សរ។",
     "array" => ":attribute ត្រូវតែមានធាតុ :size ។",
],
     "string" => "គុណលក្ខណៈ : ត្រូវតែជាខ្សែអក្សរ។",
     "timezone" => ":attribute ត្រូវតែជាតំបន់ត្រឹមត្រូវ។",
     "unique" => ": attribute ត្រូវបានគេយករួចហើយ។",
     "uploaded" => ":attribute បរាជ័យក្នុងការបង្ហោះ។",
     "url" => "ទម្រង់ :attribute មិន​ត្រឹមត្រូវ។",
     "custom" => [
     "attribute-name" => [
     "rule-name" => "សារផ្ទាល់ខ្លួន",
],
     "g-recaptcha-response" => [
     "required" => "សូមផ្ទៀងផ្ទាត់ថាអ្នកមិនមែនជាមនុស្សយន្តទេ។",
     "captcha" => "កំហុស Captcha! ព្យាយាមម្តងទៀតនៅពេលក្រោយ ឬទាក់ទងអ្នកគ្រប់គ្រងគេហទំព័រ។",
],
],
     "attributes" => [
        
     ],
];