<?php 

 return [
     "email-types" => [
        [
     "title" => "Pesenan dikonfirmasi dening panuku",
],
        [
     "title" => "Konfirmasi pembayaran pelanggan",
],
        [
     "title" => "Kabar konfirmasi pesenan menyang penjual",
],
        [
     "title" => "Konfirmasi pesenan kothak toko kanggo panuku",
],
        [
     "title" => "Konfirmasi pembayaran kasir kanggo panuku",
],
        [
     "title" => "Kabar tuku ing kothak bakul",
],
        [
     "title" => "Informasi formulir kontak",
],
        [
     "title" => "Sugeng gabung ing toko",
],
        [
     "title" => "Pengumuman nampa kertu hadiah kanggo pangguna",
]
     ],
     "global" => [
     "greetings" => "Hi: jeneng",
     "end-statement" => "Tim dhukungan",
     "receiver_name" => "Halo :user_name",
     "footer-help" => "Perlu bantuan? Takon ing [support@selldone.com](mailto:support@selldone.com) utawa bukak [pusat bantuan](https://selldone.com/help)",
     "footer-shop" => "Yen sampeyan butuh bantuan babagan apa wae, aja ragu-ragu ngirim email:: shop_mail",
     "accept" => "Nampa",
     "reject" => "nolak",
     "verify" => "ngecek",
     "title" => "judhul",
     "value" => "Nilai",
     "description" => "Katrangan",
     "Shop" => "Toko",
     "user" => "panganggo",
     "license" => "Lisensi",
     "status" => "Status",
     "start" => "Miwiti",
     "end" => "Pungkasan",
     "renewal" => "nganyari maneh",
     "view" => "Ndeleng",
     "balance" => "imbangan",
     "card_number" => "Nomer Kartu",
     "cvv" => "Cvv",
     "expire_date" => "Tanggal kadaluwarsa",
     "dashboard" => "dashboard",
     "order" => "dhawuh",
     "view_order" => "Ndeleng pesenan",
     "pay_now" => "Pay now",
     "official_selldone" => "DIJUAL RESMI",
     "account-number" => "Account number",
     "account-name" => "Account name",
     "currency" => "mata uang",
     "free-balance" => "Saldo gratis",
     "locked-balance" => "imbangan dikunci",
     "bot" => "Bot",
     "requests" => "Njaluk",
     "baskets" => "Gerobak",
     "physical" => "fisik",
     "virtual" => "Virtual",
     "file" => "File",
     "service" => "Layanan",
     "fulfillment" => "Kasembadan",
     "open" => "Mbukak",
     "reserved" => "dilindhungi",
     "canceled" => "dibatalake",
     "payed" => "Dibayar",
     "cod" => "COD",
     "orders-count" => "Pesenan",
     "payments-count" => "Pembayaran",
     "confirms-count" => "Konfirmasi",
     "sends-count" => "Ngirim",
     "delivers-count" => "Ngirim",
     "count" => "Count",
     "transactions-count" => "Jumlah transaksi",
     "success-transactions" => "Transaksi sukses",
     "total-amount" => "Jumlah total",
     "amount" => "Jumlah",
     "wage" => "Wage",
     "debug" => "Debug",
     "pos" => "POS",
     "live" => "Urip",
     "CheckQueue" => "Priksa antrian",
     "OrderConfirm" => "Konfirmasi pesenan",
     "PreparingOrder" => "Nyiapake pesenan",
     "SentOrder" => "Dikirim pesenan",
     "ToCustomer" => "Dikirim menyang pelanggan",
     "Pending" => "Ditunggu",
     "Accepted" => "Ketompo",
     "Rejected" => "Ditolak",
     "pc" => "PC",
     "tablet" => "Tablet",
     "phone" => "Telpon",
     "total" => "Total",
     "view-detail" => "Deleng rincian",
     "empty" => "kosong",
     "dropshipping" => "Dropshipping",
     "reply" => "wangsulan",
     "reactions" => "Reaksi",
     "comments" => "komentar",
     "last-comment" => "Komentar pungkasan",
     "response-to" => "Respon kanggo",
     "posts" => "kiriman",
     "post" => "Posting",
     "name" => "jeneng",
     "email" => "Email",
     "type" => "jinis",
     "device" => "piranti",
     "platform" => "Platform",
     "browser" => "Browser",
     "time" => "Wektu",
     "wallet" => "dhompet",
     "date" => "Tanggal",
     "account" => "Akun",
     "transaction" => "Transaksi",
     "fee" => "ragad",
     "location" => "Location",
     "ip" => "Ip",
     "bill" => "Bill",
     "category" => "Babagan",
     "password" => "Sandi",
     "shop" => "Toko",
     "verify-login" => "Verifikasi & Login",
     "url" => "URL",
     "avocado" => "Avocado",
     "hyper" => "Hyper",
     "buy-now" => "Tuku saiki",
     "add-domain" => "Add Domain",
     "views" => "Ndeleng",
     "country" => "negara",
     "address" => "alamat",
     "postal" => "Kode Pos",
     "building_no" => "Gedung #",
     "building_unit" => "Unit #",
     "message" => "Pesen",
     "customer" => "Pelanggan",
     "cart-items" => "Barang kréta",
     "payment" => "pambayaran",
     "receiver" => "panrima",
     "virtual-items" => "Item virtual",
     "no-payment" => "Ora mbayar!",
],
     "selldone-business-os" => "Seldone Business OS",
     "senders" => [
     "WeeklyReport" => [
     "id" => "performance",
     "name" => "Laporan Kinerja, Selldone",
],
     "SeasonalReport" => [
     "id" => "seasonal",
     "name" => "Laporan Musiman, Selldone",
],
     "Onboarding" => [
     "id" => "hi",
     "name" => "Tim Seldone",
],
     "Support" => [
     "id" => "support",
     "name" => "Dhukungan: jeneng",
],
     "EmailVerify" => [
     "id" => "verify",
     "name" => "Verifikasi, Seldone",
],
     "Welcome" => [
     "id" => "hi",
     "name" => "Komunitas, Seldone",
],
     "NewShop" => [
     "id" => "sudagar",
     "name" => "Pedagang, Selldone",
],
     "Approve" => [
     "id" => "nyetujoni",
     "name" => "Setuju, Seldone",
],
     "SellerReceiveOrder" => [
     "id" => "order",
     "name" => "Manajemen Pesenan: jeneng",
],
     "Recovery" => [
     "id" => "mbalekake",
     "name" => "Tim Recovery Seldone",
],
],
     "bill-status" => [
     "PENDING" => "Menunggu ⌛",
     "PAYED" => "Bayar ✅",
     "CANCELED" => "Batal ❌",
],
     "shop-invite" => [
     "LEVEL-NAME" => [
     "ADMIN" => "Administrator",
     "OFFICER" => "Petugas lan Pengawas",
     "AUDITING" => "Manajer audit",
     "EMPLOYEE" => "pegawe",
     "PRODUCT" => "Manajer produk",
     "CONTENT" => "Manajer konten",
     "MARKETING" => "Pimpinan Pemasaran",
     "VIEWER" => "Panyawang",
],
     "subject" => ":pengundang Ngundang sampeyan minangka :level | : toko",
     "category" => "Undangan Staff",
     "title" => "Sampeyan wis diundang menyang <b>:shop_name</b> minangka <b>:level</b> .",
     "message" => "Undhangan wis dikirim menyang sampeyan. Sampeyan bisa konfirmasi utawa nolak. Yen undhangan iki disetujoni dening sampeyan, sampeyan kudu ngetik layanan Seldone kanggo konfirmasi. Kanthi konfirmasi undhangan iki, sampeyan bakal duwe akses menyang bagean manajemen toko.",
],
     "welcome-email" => [
     "subject" => "👋 Sugeng rawuh :name, Sawetara hal menarik mung kanggo sampeyan.",
     "category" => "CONGRATULATION",
     "title" => "WELCOME TO SELLDONE",
     "message" => "Matur nuwun kanggo milih Selldone, Sampeyan saiki dadi bagian saka komunitas Selldone sing nyambungake penjual global menyang pelanggan, Bisnis lokal menyang perusahaan, Individu menyang perusahaan! Kabeh alat master lan pro wis kasedhiya ** gratis ** lan ** tanpa watesan ** kanggo sampeyan. Sampeyan nyoba, kita mbukak lawang, Just Do It!",
     "seller" => [
     "title" => "Apa sampeyan bakul?",
     "message" => "Kanggo miwiti adol, ketik dashboard ing Selldone liwat link ing ngisor iki lan nggawe toko pisanan sampeyan kanthi gratis. Iki bakal njupuk sawetara menit lan sampeyan bakal duwe toko lan situs online dhewe. Banjur kita bakal nuntun sampeyan menyang langkah sabanjure lan entuk gateway pambayaran.",
     "action" => "Mlebet ing dashboard kula",
],
     "buyer" => [
     "title" => "Aku dadi panuku",
     "message" => "Sugeng. Sawise sampeyan dadi anggota Selldone, sampeyan bakal nyingkirake kabeh masalah keanggotaan lan otentikasi ing toko online. Kanggo entuk manfaat saka sembarang toko lan situs sing nggunakake platform Selldone, sampeyan bisa mlebu karo siji klik lan nggawe tuku prasaja, cepet lan aman.",
],
],
     "charge-account" => [
     "category" => "Dompet > Akun > Ngisi daya",
     "title" => "Biaya Sukses",
     "message" => "Akun <b>sampeyan:account_number</b> wis sukses <b>: jumlah</b> sing dikenani biaya.",
     "account" => "Akun",
     "charge" => "Ngisi daya",
     "balance" => "imbangan",
     "footer" => "Nggawe bisnis gampang, bisa digayuh, lan bisa diakses sapa wae ing saindenging jagad.",
],
     "verify-email" => [
     "subject" => "🙌 Rampungake pendaftaran menyang Seldone! Verifikasi link.",
     "category" => "KOWE SING LANGKAH",
     "title" => "Verifikasi alamat email sampeyan",
     "message" => "Halo: jeneng,<br> Matur nuwun kanggo milih Seldone.<br> Mangga konfirmasi yen **: email ** minangka alamat e-mail sampeyan kanthi ngeklik tombol kasebut utawa gunakake link ing ngisor iki sajrone 48 jam.",
     "footer" => "Yen sampeyan ngalami masalah ngeklik tombol Verifikasi, salin lan tempel URL ing ngisor iki menyang browser web sampeyan: __:activation_url__",
],
     "verify-email-code" => [
     "subject" => "Kode verifikasi kanggo: jeneng",
     "category" => "SECURITY",
     "title" => "Kode verifikasi email",
     "message" => "Halo: jeneng,<br><br> Mangga konfirmasi yen **: email ** minangka alamat e-mail sampeyan kanthi kode iki sajrone 10 menit.",
],
     "onboarding-verify-email" => [
     "subject" => "🎉 Toko Sampeyan Siap | : jeneng",
     "category" => "KOWE SING LANGKAH",
     "title" => "Persiyapan rampung",
     "account_title" => "Akun sampeyan",
     "account_msg" => "Verifikasi lan mlebu menyang akun kanthi informasi iki.",
     "shop_msg" => "Info akun babagan sistem operasi bisnis Selldone.",
],
     "reset2fa" => [
     "category" => "PESAN RESMI KEAMANAN",
     "title" => "Njaluk mateni login 2-langkah",
     "message" => "Sampeyan nampa email iki amarga kita nampa panjalukan reset otentikasi 2 faktor kanggo akun sampeyan.<br><br> Email pangguna <b>:: email</b><br> <b>jeneng:: jeneng</b>",
     "footer" => "Yen sampeyan ora njaluk reset sandhi, ora ana tumindak maneh sing dibutuhake.",
     "action" => "Pateni login rong langkah",
],
     "build-new-shop" => [
     "subject" => "🎊 Toko sampeyan wis siyap saiki!",
     "category" => "LAHIR NEW STORE ONLINE ING WORLD",
     "title" => "ngrayakake",
     "message" => "<b>Sugeng :jeneng, sampeyan wis nggawe bisnis online anyar;</b> Muga-muga sampeyan sukses ing bisnis sampeyan. Sugeng rawuh ing komunitas Selldoners.<br> Sampeyan nyoba, kita mbukak lawang, lan sampeyan nindakake.",
     "pdf-book" => "Aja kantun buku tangan sing dilampirake: Apa Bisnis Sampeyan Kaya Game",
     "account" => [
     "title" => "Langkah 1: Nggawe akun ing dompet Seldone",
     "message" => "Yen sampeyan ora duwe akun ing dompet, nggawe akun. Selldone nyuda ragad saka akun iki. Sampeyan bisa ngisi akun iki, lan Selldone uga bakal ngisi jumlah kredit supaya yen akun iki negatif, situs lan Toko bakal terus operate.",
     "action" => "Mlebet ing dompet",
],
     "shop-account" => [
     "title" => "Langkah 2: sambungake akun menyang toko",
     "message" => "Tambah akun dompet menyang toko. Kanggo nindakake iki, ketik Toko> Akuntansi> Invoice lan sambungake akun kasebut menyang toko. Elinga yen kabeh pembayaran pelanggan disimpen langsung menyang akun bank lan ora ana jumlah sing ditarik utawa dikurangi dening Selldone, dadi sampeyan kudu nyambungake akun Selldone iki menyang toko.",
     "action" => "Panel Invoice Toko",
],
     "gateway" => [
     "title" => "Langkah 3: Sambungake Gateway Pembayaran Online",
     "message" => "Pindhah menyang Toko> Akuntansi> Port banjur pencet <b>Tambah Port Anyar</b> . Sawise milih mata uang, sampeyan bakal ditampilake dhaptar port portabel. Nyambungake port ing Selldone banget prasaja lan cepet, nanging yen sampeyan duwe Niza kanggo panuntun dhumateng, deleng bagean Selldone guide utawa takon kita.",
     "action" => "Tambah portal menyang toko",
],
     "domain" => [
     "title" => "Langkah pungkasan: nyambungake domain khusus",
     "message" => "Sampeyan bakal bisa duwe toko ing akeh domain sing dikarepake. Kanggo nyambungake domain khusus menyang toko, sampeyan kudu duwe paling sethithik lisensi wiwitan. Kanthi ngenalake saben kanca menyang Selldone, sampeyan bakal nampa kertu hadiah lisensi wiwitan siji wulan. Persentase pembayaran kanca-kanca uga bakal dikreditake menyang akun pelanggan.",
     "action" => "Ngenalke lan nampa kertu hadiah tanpa wates",
],
],
     "basket-list" => [
     "item" => "item",
     "count" => "Count",
     "price" => "regane",
     "discount-code" => "Kode diskon",
     "customer-club" => "Klub pelanggan",
     "shipping" => "Pengiriman",
     "total" => "Total",
     "offer" => "nawarake",
     "coupon" => "kupon",
     "lottery" => "Penghargaan",
     "tax" => "Pajak",
     "tax_included" => "Klebu ing rega",
     "tax_shipping" => "Shipping Tax",
],
     "buyable-payments" => [
     "method" => "Metode",
     "amount" => "Jumlah",
     "giftcard" => "Gift card",
     "payment" => "pambayaran",
],
     "shop-subscription-email" => [
     "category" => "Nganyari langganan",
     "title" => "Lisensi Toko::shop_title",
     "title-reserved" => "Lisensi cadangan::shop_title",
     "title-active" => "Lisensi aktif::shop_title",
     "title-finished" => "Lisensi rampung::shop_title",
     "title-cancel" => "Batal lisensi::shop_title",
     "message" => "Rencana lisensi toko sampeyan dianyari,",
     "RESERVED" => "⚡ Rencana langganan sampeyan wis ** dilindhungi **.",
     "ACTIVE" => "🟢 Rencana langganan sampeyan wis **diaktifake**.",
     "FINISHED" => "🚧 Rencana langganan sampeyan wis **rampung**.",
     "CANCEL" => "⛔ Rencana langganan sampeyan wis **dibatalake**.",
],
     "support" => [
     "subject" => "Pusat Dhukungan | : jeneng wangsulane",
     "category" => "Pusat dhukungan",
     "title" => "Sampeyan nampa respon",
     "action" => "Bukak admin toko",
],
     "shop-customer-join" => [
     "subject" => "Gabung:shop_title",
     "category" => "perayaan pelanggan anyar",
     "title" => "Kita seneng kanggo anggota",
     "action" => "Dolan maring saiki",
],
     "shop-giftcard" => [
     "subject" => "Giftcard:shop_title",
     "category" => "Tambah kertu anyar",
     "title" => "Sugeng, sampeyan wis nampa kertu hadiah",
     "action" => "Tuku saiki",
     "message" => "Sampeyan wis nampa kertu hadiah ing jumlah: imbangan: itungan. Sampeyan bakal bisa tuku saka toko kita nganggo kertu hadiah iki.",
],
     "contact" => [
     "subject" => "Pusat Dhukungan | : toko",
     "category" => "nyokong",
     "title" => "Sampeyan nampa respon",
],
     "order-checkout" => [
     "subject" => "🛍 Order Checkout | : order_id",
     "title" => "dhawuh",
     "message" => "Konfirmasi pesenan sampeyan,<br> Kita wis entuk pesenan sampeyan. Kita bakal ngirim email liyane nalika pesenan dikirim.",
     "payments" => "Pembayaran",
],
     "order-payment" => [
     "subject" => "🛍 Konfirmasi Pembayaran | : order_id",
     "title" => "pesenan pembayaran",
     "message" => "Pembayaran sampeyan wis rampung,<br> Kita wis entuk pesenan sampeyan. Kita bakal ngirim email liyane nalika pesenan dikirim.",
     "payments" => "Pembayaran",
],
     "get-voucher" => [
     "subject" => "Sugeng : jeneng | voucher anyar:: judhul",
     "category" => "SELAMAT, VOUCHER ANYAR",
     "message" => "Sampeyan entuk voucer anyar, Iki minangka hadiah saka kita kanggo sampeyan. Sampeyan bisa entuk luwih akeh saka voucher kasebut kanthi ngenalake Selldone menyang kanca lan kabeh wong sing sampeyan kenal. Voucher iki regane **: rega: mata uang **.<br> Sampeyan nyoba, kita mbukak lawang, Sugeng, Mbukak kunci fitur dening voucer!",
     "action" => "dashboard kula",
],
     "received-gift" => [
     "subject" => "Sugeng, Dear :name | Sampeyan wis nampa hadiah",
     "category" => "Pengumuman nampa hadiah",
     "title" => "Hadiah kanggo sampeyan",
     "message" => "Sampeyan wis nampa hadiah anyar. Iki minangka hadiah saka Selldone. Sampeyan bisa nampa luwih akeh hadiah kasebut kanthi luwih aktif ing Selldone lan ngembangake toko sampeyan lan ngunggahake tingkat spesialisasi. Nilai Gift iki **: rega: itungan ** sing bisa sampeyan setor langsung menyang dompet ing seldone.<br><br> Gunakake hadiah iki kanggo nganyarke lisensi toko lan nggunakake alat liyane ing bisnis online.",
     "action" => "peparingé",
],
     "order-payment-admin" => [
     "subject" => "🛍 Pesenan Anyar Ditampa | : order_id",
     "title" => "New Order",
     "message" => "Sampeyan wis nampa pesenan anyar. Mangga menyang kaca pangolahan pesenan ing toko sampeyan.",
],
     "virtual-item" => [
     "input-form-title" => "Informasi Sampeyan Isi",
     "output-form-title" => "Informasi item sing dituku",
],
     "selldone-weekly-report" => [
     "subject" => "📬 :shop_title | Laporan Mingguan: wektu",
     "title" => "Laporan kinerja toko mingguan",
     "message" => "Iki laporan mingguan toko sampeyan saka: wiwitan nganti: pungkasan. Laporan iki kalebu tips kanggo nambah bisnis, sampeyan uga bisa mriksa status toko online lan pesenan anyar. Muga-muga sampeyan duwe dina lan minggu sing apik.",
],
     "shop-seasonal-report" => [
     "subject" => "☘ Laporan tabungan :jumlah sampeyan ing telung sasi pungkasan | :shop_title",
     "title" => "Laporan musiman babagan kegiatan bisnis, ganjaran lan tabungan finansial",
     "message" => "Iki minangka laporan musiman: shop_title saka: wiwitan nganti: pungkasan.",
],
     "EC-ShopAccounts" => [
     "title" => "Akun sing disambungake",
     "sub-title" => "Apa status paling anyar saka akun dompet sing disambungake menyang tokoku?",
     "view-wallet" => "Ndeleng dompet",
     "tip-title" => "Tips penting",
     "tip" => "Ing langkah sabanjure, nggawe akun gratis ing dompet Seldone lan sambungake menyang toko iki. Sanajan imbangan akun Selldone sampeyan negatif, pelanggan sampeyan isih bisa tuku lan mbayar kanggo toko sampeyan tanpa masalah. Data lan layanan sampeyan ora bakal diselani utawa diwatesi paling sethithik 1 sasi.",
     "view-my-wallet" => "My wallet",
     "connect-account" => "Nyambung menyang akun",
],
     "EC-ShopApps" => [
     "title" => "Aplikasi diinstal",
     "sub-title" => "Dhaptar aplikasi sing wis diinstal ing toko minggu iki.",
     "tip" => "Apa sampeyan pengin golek aplikasi liyane kanggo toko sampeyan?",
     "view-app-store" => "Dolan maring Selldone App Store..",
],
     "EC-ShopBots" => [
     "title" => "Bot Toko Panjenengan",
     "sub-title" => "Bot dodolan aktif ing tokoku.",
     "tip-title" => "Bot Sale",
     "tip" => "Selldone wis nyedhiyakake bot penjualan otomatis. Sampeyan mung kudu pindhah menyang panel Add-ons> Bots lan aktifake bot toko sampeyan. Elinga yen layanan sing cocog kudu kasedhiya ing negara sampeyan.",
     "view-bots" => "Ngatur bot",
],
     "EC-ShopContacts" => [
     "title" => "Komunikasi karo Pelanggan",
     "sub-title" => "Pira pirang-pirang kontak karo klienku minggu iki?",
     "faqs" => "Pitakonan Paling Sering",
     "tickets" => "Tiket Pelanggan",
],
     "EC-ShopData" => [
     "title" => "Status pangguna",
     "sub-title" => "Saka tanggal: wiwitan nganti: pungkasan",
     "users" => [
     "title" => "Pelanggan",
     "subtitle" => "Pangguna Ndhaptar",
],
     "views" => [
     "title" => "Kunjungan",
     "subtitle" => "Kaping pirang-pirang sampeyan ngunjungi toko",
],
     "new_visitors" => "New Users",
     "returning_visitors" => "Pangguna sing bali",
     "shop_views" => "Tampilan Toko",
     "baskets" => [
     "title" => "Kréta Blanja",
     "subtitle" => "Laporaké nomer kréta blanja anyar",
],
     "products" => [
     "title" => "Gambaran Umum Produk",
     "subtitle" => "Status produk ing toko miturut jinis",
     "value_name" => "Produk",
],
     "products_count" => "jinis produk",
     "views_count" => "Ndeleng count",
     "sell_count" => "Sell count",
     "send_count" => "Jumlah pengiriman",
],
     "EC-ShopDropShipping" => [
     "title" => "Drop Shipping",
     "sub-title" => "Panel kanggo bakul utama Drop Shipping Selldone.",
     "total_fulfillments" => "Total Pesenan Ditampa",
     "ds_count" => "Ditampa Pesenan",
     "statistics_title" => "Laporan nampa pesenan",
     "ds_cancels" => "Batal dening bakul antarmuka",
     "ds_rejects" => "Batal dening Sampeyan",
     "tip" => "Apa sampeyan bakul utama barang? Apa sampeyan duwe gudang, pabrik utawa distributor produk? Sampeyan bisa nawakake produk sampeyan menyang adol liyane ing layanan Selldone Drop Shipping kanggo adol produk sampeyan kanthi skala gedhe. Email kita ing support@seldone.com kanggo nuntun sampeyan.",
     "view-drop-shipping-panel" => "Mlebet menyang panel Grosir",
],
     "EC-ShopExchangeRates" => [
     "title" => "Exchange Rates",
     "sub-title" => "Dhaptar tarif konversi mata uang paling anyar ing toko sampeyan.",
     "from" => "Sumber Mata Uang",
     "to" => "Mata uang tujuan",
     "rate" => "Tingkat konversi",
     "vew-exchange-panel" => "panel manajemen nilai tukar",
],
     "EC-ShopExperts" => [
     "title" => "Kontrak pakar",
     "sub-title" => "Apa profesional sing kerja ing tokoku?",
     "cost" => "Jumlah kontrak",
     "duration" => "Duration",
     "start_at" => "Start Date",
     "complete_at" => "Completion Date",
     "cancel_at" => "Tanggal Batal",
     "end_at" => "Tanggal pangiriman",
     "tip" => "Sampeyan bisa nyewa spesialis paling apik ing Selldone kanggo ngembangake bisnis sampeyan.",
     "view-experts" => "Klik kanggo miwiti.",
],
     "EC-ShopGateways" => [
     "title" => "Payment gateways",
     "sub-title" => "Lapor gateway pembayaran aktif ing toko:shop.",
     "tip-title" => "Tips penting",
     "tip" => "Bukak kaca manajemen portal ing toko sampeyan lan tambahake paling ora siji port ing sawetara menit. Pelanggan sampeyan seneng mbayar kanthi cepet lan aman liwat portal online.",
     "view-shop-gateways" => "Mlebet menyang manajemen portal tokoku.",
     "view-gateways" => "Ndeleng gateway liyane",
],
     "EC-ShopOrders" => [
     "title" => "Pesenan",
     "sub-title" => "Dhaftar pesenan aku ditampa minggu iki.",
     "total_baskets" => "Total Pesenan",
     "total_posBaskets" => "Total Pesanan Kas",
     "pos-title" => "Kotak Toko POS",
     "chart-label" => "Pesenan rampung (pesenan iki ora kudu dibayar!)",
     "tip-title" => "Sampeyan kudu nyoba luwih ...",
     "tip" => "Ora ana sukses sing prasaja.",
],
     "EC-ShopProcessCenter" => [
     "title" => "Pusat pangolahan",
     "sub-title" => "Pira pesenan sing diproses ing toko minggu iki?",
     "tip-title" => "Sampeyan ora duwe dodolan!",
     "tip" => "Sayange sampeyan ora duwe dodolan minggu iki. Sampeyan kudu entuk luwih akeh menyang toko sampeyan. Sampeyan bisa nambah luwih akeh produk, milih gambar sing luwih apik utawa nulis deskripsi sing luwih apik kanggo produk sampeyan. Coba proyek full-time kanggo bisnis sampeyan. Yen sampeyan nindakake kanthi bener lan ora frustasi, sampeyan bakal sukses.",
     "view-process-center" => "Deleng pusat proses",
     "return" => [
     "title" => "Wangsul pesenan",
     "subtitle" => "Laporan pesenan bali.",
     "tip-title" => "Apa sampeyan ngerti yen ...",
     "tip" => "Sampeyan bisa nggawe akeh kasir toko sing dikarepake liwat Selldone POS! Nyatane, sampeyan bisa nguripake tablet, ponsel utawa laptop menyang kothak mlebu. Yen sing excites sampeyan, Selldone POS Iku soko sampeyan kudu miwiti nggunakake saiki. Iku mung njupuk prasaja klik kanggo miwiti, kita wis kabeh disiapake kanggo server ing advance.",
     "view-pos" => "Mlebu menyang Kasir Toko Onlineku",
],
],
     "EC-ShopSessions" => [
     "title" => "Sesi",
     "sub-title" => "Kaping pirang-pirang aku ngunjungi tokoku?",
     "countries-title" => "Negara endi sing paling kerep dibukak?",
],
     "EC-PublicMessage" => [
     "title" => "Apa sampeyan pengin entuk dhuwit tanpa mbuwang dhuwit?",
     "message" => "Dear :name, sampeyan bisa pindhah menyang Dashboard > Demonetization lan nggawe link referral. Kirimi link kanggo kanca-kanca, Sampeyan nampa kertu hadiah Selldone lan persentasi saka pembayaran kanca. Elinga yen kertu hadiah bakal dikirim menyang sampeyan lan kanca sampeyan.",
     "action" => "Deleng link introduksiku",
     "mail-clip" => "<b style='color: #C2185B'>Penting:</b> Yen sampeyan nggunakake layanan email kayata Gmail sing mbatesi dawa email, goleki pilihan ing mburi email kanggo nampilake laporan lengkap banjur klik:",
     "no-coin-reward" => "<b style='color: #C2185B'>Nuwun sewu:</b> Aktivitas sampeyan ora nyukupi syarat kanggo entuk hadiah SEL Coin gratis. Coba luwih lan adol luwih akeh ing toko kanggo musim ngarep.",
     "yes-coin-reward" => "<b style='color: #4CAF50'>Ganjaran:</b> Sugeng, amarga kinerja sing apik banget, kita menehi hadiah gratis SEL Coin.",
     "need-buy-license" => "<b>Tingkatake bisnis sampeyan:</b> Sampeyan durung ndhaptar rencana langganan kanggo situs web bisnis sampeyan! Dadi wektu kanggo tuku paling ora siji langganan. Iku mung biaya: jumlah saben wulan kanggo tuku taunan.",
     "not-afford-message" => "Yen sampeyan ora bisa mbayar utawa duwe masalah karo pembayaran, aja ragu marang kita liwat support@selldone.com.",
     "add-domain" => "<b>Napa ora duwe domain khusus kanggo bisnis sampeyan?</b><br> Tambah domain menyang situs web sampeyan saiki; iku gratis!",
],
     "Widget-Socials" => [
     "title" => "Seldone yaiku a<del> produk</del> <span style = 'color: forestgreen'>masyarakat</span> .<br> Dadi Seldoner profesional!",
     "message" => "Tindakake kaca resmi Selldone ing Twitter, LinkedIn lan jaringan sosial. Kirimi kita komentar, panjalukan utawa kritik utawa melu diskusi babagan Selldone. Kita uga bagean saka komunitas Selldone sing <b>Sampeyan nggawe</b> .",
],
     "avocado-seller-daily-report" => [
     "subject" => "Nampa pesenan Avocado anyar | :shop_title :wektu",
     "title" => "Laporan kinerja sajrone 24 jam pungkasan",
     "message" => "Pelanggan sampeyan nunggu pesenan sampeyan dideleng lan regane. Tanggapi panjaluk pelanggan kanthi cepet supaya bisa entuk dodolan luwih akeh.",
     "card_title" => "Pesenan ing antrian",
     "card_subtitle" => "Saka: tanggal",
     "card_payed" => "pesenan mbayar",
],
     "community-comments" => [
     "subject" => "Mbales kiriman sampeyan ing :community_title",
     "title" => ": jeneng, lan: count liyane komentar ing kiriman Panjenengan.",
     "title-simple" => ": jeneng menehi komentar ing kiriman sampeyan.",
],
     "community-topic" => [
     "subject" => "🔔 Mbales topik sampeyan :topic_title",
     "title" => ": jeneng, lan: count liyane mangsuli topik sampeyan.",
     "title-simple" => ": jeneng mangsuli ing topik sampeyan.",
],
     "user-login" => [
     "subject" => "🔔 Login anyar :name",
     "category" => "Kabar keamanan",
     "title" => "Mlebu menyang Akun",
     "message" => "Dear :name, sampeyan wis mlebu menyang akun Seldone sampeyan.",
     "footer" => "Yen sampeyan durung mlebu, ganti tembung sandhi.",
],
     "account-transaction" => [
     "withdraw" => "Penarikan",
     "deposit" => "Simpenan",
     "withdraw_subject" => "mundur saka akun: akun",
     "deposit_subject" => "Simpenan menyang akun: akun",
     "message" => "Transfer dhuwit wis rampung kanthi spesifikasi ing ngisor iki.",
     "type" => "Jinis transaksi",
     "from" => "Akun sumber",
     "to" => "Destination account",
     "desc" => "Katrangan transaksi",
     "action" => "Ndeleng transaksi",
],
     "penalty" => [
     "subject" => "⛔ Penting! nglanggar aturan | : toko",
     "category" => "Informasi kritis",
     "title" => "Toko sampeyan wis dihukum",
     "action" => "Bukak dashboard toko",
],
     "invite" => [
     "subject" => ": Pengundang ngajak sampeyan menyang Seldone",
     "title" => ":name ngirim sampeyan :jumlah kanggo mbantu mbukak situs web online anyar lan monetisasi!",
     "message" => "Ing Selldone, sampeyan bisa nggawe e-commerce, situs web blog, lan komunitas online lan malah entuk POS online lan nyiyapake dodolan pribadi ing sawetara menit. Iku sistem operasi bisnis online kanggo nggawe bisnis online, luwih apik lan luwih cepet. Cukup ndhaptar kanthi <b>: tanggal</b> kanggo entuk voucer: jumlah.",
     "accept" => "Nampa uleman",
     "owner" => "Pemilik saka",
     "join-date" => "On Seldone wiwit",
],
     "shop-recovery" => [
     "subject" => "Link Recovery | : toko",
     "category" => "Keamanan toko",
     "title" => "Link pemulihan toko saka <b>:shop_name</b> .",
     "message" => "Email iki dikirim menyang sampeyan amarga sampeyan njaluk mulihake toko sampeyan. Ngeklik link ing ngisor iki bakal mbalekake toko lan kabeh data sing ana.",
     "action" => "Konfirmasi Recovery Toko",
],
     "SR-SeasonalSaving" => [
     "title" => "Pira dhuwit sing disimpen Selldone kanggo bisnis sampeyan?",
     "sub-title" => "Saka tanggal: wiwitan nganti: pungkasan",
     "infrastructure" => [
     "title" => "Infrastruktur",
     "subtitle" => "Server, CDN, Panyimpenan, lan layanan awan liyane",
],
     "experts" => [
     "title" => "Pakar & Staff",
     "subtitle" => "Pangembang, pangopènan, lan dhukungan",
],
     "total_save" => "Total dhuwit disimpen",
],
     "SR-SeasonalPerformance" => [
     "title" => "Kinerja sampeyan",
     "sub-title" => "Ringkesan bisnis saka: wiwitan nganti: pungkasan",
     "new_visitors" => "New Users",
     "returning_visitors" => "Pangguna sing bali",
     "shop_views" => "Tampilan Toko",
     "baskets" => [
     "title" => "Kréta Blanja",
     "subtitle" => "Laporaké nomer kréta blanja anyar",
],
     "products" => [
     "title" => "Gambaran Umum Produk",
     "subtitle" => "Status produk ing toko miturut jinis",
     "value_name" => "Produk",
],
     "views" => [
     "title" => "Page Views",
     "subtitle" => "Total tampilan kaca situs web",
],
],
];